### ISSUE TITLE
Add support for CollectionDiscovererAttribute

### ISSUE THREAD

**Issue by DixonDs** [xunit/xunit#1004]
I would like to have a possibility to have a custom collection attribute with a custom discoverer. In my scenario I want to created by customer IntegrationTestAttribute which would put all marked tests into the same collection.

**Comment by dmccaffery** [comment]
I do something similar to this for my own purposes:

https://github.com/pulsebridge/condo/blob/b53fb7f518b7fa81f92758406631cf07e75691d5/src/PulseBridge.Condo.Testing/PurposeType.cs

https://github.com/pulsebridge/condo/blob/b53fb7f518b7fa81f92758406631cf07e75691d5/src/PulseBridge.Condo.Testing/PurposeAttribute.cs

https://github.com/pulsebridge/condo/blob/b53fb7f518b7fa81f92758406631cf07e75691d5/src/PulseBridge.Condo.Testing/PurposeDiscoverer.cs

You can then filter execution of the test by trait:

-notrait purpose not-integration

This would execute any test case [fact] that was marked with the following attribute:

[Purpose(PurposeType.Integration)]

While it doesn't technically put it in its own collection, which I do not believe is even possible, it does at least allow you to run tests in isolation no matter where they are. This in combination with the ability to disable parallel test execution gives you what I think you're looking for.

If there is a desire to have this, I can look at putting these extensions into their own library and nuget package for public consumption.

**Comment by bradwilson** [comment]
Closed for age.
