### ISSUE TITLE
dotnet-test-xunit NuGet package error

### ISSUE THREAD

**Issue by girishjjain** [xunit/xunit#1009]
Trying to add pre-release version of dotnet-test-xunit NuGet package fails with below error:

Failed to add reference. The package 'dotnet-test-xunit' tried to add a framework reference to 'System.Threading.Tasks' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

**Comment by bradwilson** [comment]
Please provide a repro project. Thanks!

**Comment by bradwilson** [comment]
Closed for age.
