### ISSUE TITLE
Enums are converted to strings oddly - please use the builtin `ToString()`!

### ISSUE THREAD

**Issue by ericwj** [xunit/xunit#1012]
I find that my enums used in theories are converted to different strings than the debugger displays in VS, or what I get by simply calling `ToString()`.

For one, it insists on including enum members of a `[Flags]` enum that are zero, if the value actually isn't.

Please use the default enum to string conversion!

**Comment by akazemis** [comment]
I had a look into the code and wrote some tests to reproduce your problem. Couldn't find any problem.
Not form Enums nor for flags enums. 
Here is some examples : 

`class ClassUnderTestForEnums
        {
            [Theory]
            [InlineData(TestEnum.Option2)]
            public void TestMethod(TestEnum value) { ... }
        }

        enum TestEnum
        {
            Option1,
            Option2,
            Option3
        }`

`class ClassUnderTestForFlagEnums
        {
            [Theory]
            [InlineData(TestFlagsEnum.Option1| TestFlagsEnum.Option3)]
            public void TestMethod(string value) { ... }
        }

        [Flags]
        enum TestFlagsEnum
        {
            None = 0,
            Option1 = 2,
            Option2 = 4,
            Option3 = 8
        }`

Could you copy paste your code to see if I'm on the right track?

**Comment by ericwj** [comment]
Investigating this further, I'm getting confused really. I am seeing the same output to the console as Visual Studio Test Explorer shows with the below code. The difference really is with the debugger so it seems.

I have seen differences between Xunit and ToString, but that could be due to ToString not being consistent from the one build to the other, perhaps depending on enumeration field declaration order?

One occassion I saw this happen is with an enum that is something like `enum E { A = 1, B = 2, Alpha = A, Bravo = B }` and `Xunit` would be showing `A` for the one occurrence of 1 but `Alpha` for another. Right now I am seeing one test refer to `A` and another to `Bravo` which is already odd.

```CSharp
namespace Xunit {
	public class EnumDemo
	{
		private readonly ITestOutputHelper output;
		public EnumDemo(ITestOutputHelper output) { this.output = output; }

		[Flags]
		public enum ModRegRMFlags : byte
		{
			MemoryAtDisposition16 = ModifierRMIsMemoryNoDisp | MemoryAtBP,

			ModifierRMIsMemoryNoDisp = 0,
			ModifierRMIsMemoryDisp8 = 0x40,
			ModifierRMIsMemoryDisp16 = 0x80,
			ModifierRMIsRegister = 0xC0,

			MemoryAtBXSI = 0,
			MemoryAtBXDI = 1,
			MemoryAtBPSI = 2,
			MemoryAtBPDI = 3,
			MemoryAtSI = 4,
			MemoryAtDI = 5,
			MemoryAtBP = 6,
			MemoryAtBX = 7,

			Reg0 = 0 << 3,
			Reg1 = 1 << 3,
			Reg2 = 2 << 3,
			Reg3 = 3 << 3,
			Reg4 = 4 << 3,
			Reg5 = 5 << 3,
			Reg6 = 6 << 3,
			Reg7 = 7 << 3,
		}
		[Theory]
		[InlineData(ModRegRMFlags.ModifierRMIsRegister)]
		[InlineData(ModRegRMFlags.MemoryAtDisposition16)]
		[InlineData(ModRegRMFlags.MemoryAtBP | ModRegRMFlags.ModifierRMIsMemoryDisp8)]
		[InlineData(ModRegRMFlags.MemoryAtBP | ModRegRMFlags.ModifierRMIsMemoryDisp16)]
		[InlineData(ModRegRMFlags.MemoryAtBPDI | ModRegRMFlags.ModifierRMIsMemoryNoDisp)]
		[InlineData(ModRegRMFlags.MemoryAtBPDI | ModRegRMFlags.ModifierRMIsMemoryDisp8)]
		[InlineData(ModRegRMFlags.MemoryAtBPDI | ModRegRMFlags.ModifierRMIsMemoryDisp16)]
		[InlineData(ModRegRMFlags.MemoryAtBPSI | ModRegRMFlags.ModifierRMIsMemoryNoDisp)]
		[InlineData(ModRegRMFlags.MemoryAtBPSI | ModRegRMFlags.ModifierRMIsMemoryDisp8)]
		[InlineData(ModRegRMFlags.MemoryAtBPSI | ModRegRMFlags.ModifierRMIsMemoryDisp16)]
		[InlineData(ModRegRMFlags.MemoryAtBX | ModRegRMFlags.ModifierRMIsMemoryNoDisp)]
		[InlineData(ModRegRMFlags.MemoryAtBX | ModRegRMFlags.ModifierRMIsMemoryDisp8)]
		[InlineData(ModRegRMFlags.MemoryAtBX | ModRegRMFlags.ModifierRMIsMemoryDisp16)]
		public void Noop(ModRegRMFlags flags) { Console.WriteLine(flags.ToString()); }
	}
}
```

Here's what Test Explorer shows:  
![Test Explorer Test Names](https://gpkq6w-sn3302.files.1drv.com/y3mYju3Eh0hig-okn2pzZddITIyvxHA7KDI1Fdet0-FlXLHh84KwoOv2nUv45lninlanZfy0FjY_G4Au9bhcrvzbgJdplsWEvT3ux4gAA0C0Z5q8xxlc-DFLvRGSK-1lUa7YZ05ghpz9LKtI368N1kZvBQvHSCL2zGZyflkLCvvCnc?width=1021&height=431&cropmode=none)

Here's what running `dotnet test -class Xunit.EnumDemo` writes to the console:
![dotnet test Output](https://uqcg0w-sn3302.files.1drv.com/y3mGPz_lObeUpgpAeg_tEsFpHwK_OxeA1SFG9yysc9LhVyx88Q64S-CQG-J4DlNRcNdinajMv1ehpriqWE4RuKOEL_Rrx_5xLUTWJ40KDqpHGs8YFsIutEVUqvxdw49gvBm7nu2vl6Zidfa9Z8iUzIo_vr-WaQAa_8yq6tyvoVmBCQ?width=1060&height=837&cropmode=none)

Here's what the Watches window shows:
![Watch Window Display](https://uij5ma-sn3302.files.1drv.com/y3mwfz5Fz9WXOxgkEQUjxmYt5Tjm7ri7ltg88I2Ha2N7LdxZTnAePoiiIiywzp8P3aKVEQUQLCrYHC55Byz-El_jlLmzwqtWOZBzZJIs5y7dTX-cARst4ru1auG4ELUKDYi_Q0gvoJEqm0Hmf0XqmcvL_tRXt33z5jW1uFz8fgLfCE?width=1339&height=436&cropmode=none)

**Comment by bradwilson** [comment]
The difference is that `Foo, Bar` is what `ToString()` returns. The value you want is actually the debugger display, which is separate from `ToString()`.

That said, this is easy to fix. :)

**Comment by ericwj** [comment]
Oh man you think I care about comma's or pipelines?

Look closer!

**Comment by bradwilson** [comment]
I can't do anything about duplicate values. We're not directly doing the translation, as you can; we just call `ToString()`. /shrug

**Comment by ericwj** [comment]
Well you tagged it as a bug and fixed it. I kind of assumed you did something useful.

Thinking about filing this as an issue with Enum.ToString() but I'm afraid that'd get stuck at it being conformant to a spec or another.

But fair enough if you argue my real issue isn't with Xunit.
