### ISSUE TITLE
Please use the implicit or explicit type conversion operators on theory arguments

### ISSUE THREAD

**Issue by ericwj** [xunit/xunit#1013]
I have types that have a `[DebuggerDisplay]` attribute so debugging is quite a lot easier. However, they cannot be arguments to a theory with `[InlineData]` because they cannot be provided as constants. Some of them convert nicely (and trivially) to a blittable type however, which I can use with `[InlineData]`.

However if I change the theories method signature, all tests fail with 
`Object of type 'A' cannot be converted to type 'B'.`
at
`RuntimeType.TryChangeType(object, Binder, CultureInfo, Boolean)`
(...)
`TestInvoker'1.CallTestMethod(object)`.

If I do this at runtime, there's no problem - first of all it obviously compiles without explicit type cast.

Truth be told, one reason why I would especially like this is to make the names of tests more relevant in Test Explorer in VS.

**Comment by bradwilson** [comment]
Resolved by #1020.
