### ISSUE TITLE
test runner does not finish and returns fail on linux

### ISSUE THREAD

**Issue by myaeger** [xunit/xunit#1014]
Running unit tests on our linux build machine always fails but works on dev machine (windows 7).

Here is example of sucessful run locally:

$ dotnet test test/ss-asset.Tests/
Project ss-asset (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Project ss-asset.Tests (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
xUnit.net .NET CLI test runner (64-bit .NET Core win7-x64)
  Discovering: ss-asset.Tests
  Discovered:  ss-asset.Tests
  Starting:    ss-asset.Tests
  Finished:    ss-asset.Tests
=== TEST EXECUTION SUMMARY ===
   ss-asset.Tests  Total: 154, Errors: 0, Failed: 0, Skipped: 0, Time: 1.943s
SUMMARY: Total: 1 targets, Passed: 1, Failed: 0.

Here is the same test run on build machine:

xUnit.net .NET CLI test runner (64-bit .NET Core ubuntu.14.04-x64)
  Discovering: ss-asset.Tests
  Discovered:  ss-asset.Tests
  Starting:    ss-asset.Tests
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.

I notice that there is no Finished log entry and it immediately reports failed.  I've tried newer versions of xunit dotnet-test-xunit, even the latest prerelease, but I get the same result.

Here is my project.json:

{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "copyToOutput": { "includeFiles": [ "ExampleFiles/BlueprintExample.zip" ] }
  },
  "dependencies": {
    "System.Runtime.Serialization.Primitives": "4.1.1",
    "xunit": "2.1.0",
    "dotnet-test-xunit": "1.0.0-rc2-build10025",
    "Moq": "4.6.36-alpha",
    "ss-asset": {
      "target": "project"
    },
    "Microsoft.NETCore.App": "1.0.0"
  },
  "testRunner": "xunit",
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        }
      },
      "imports": [
        "dotnet5.4",
        "portable-net451+win8"
      ]
    }
  }
}

**Comment by bradwilson** [comment]
You are using an out-of-date version of `dotnet-test-xunit`. Please following our [Getting Started with .NET Core](https://xunit.github.io/docs/getting-started-dotnet-core.html) directions.

**Comment by myaeger** [comment]
I updated to     "dotnet-test-xunit": "2.2.0-preview2-build1029",

and get the same resullt.

**Comment by bradwilson** [comment]
Please provide a full repro project. Thanks!

**Comment by bradwilson** [comment]
Closed for age.
