### ISSUE TITLE
Xunit not supported with .Net core unit test project

### ISSUE THREAD

**Issue by jainaashish** [xunit/xunit#1016]
Installing XUnit 2.1.0 on .Net core unit test project fails with below error:

> Package xunit.assert 2.1.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package xunit.assert 2.1.0 supports:
>   - dotnet (.NETPlatform,Version=v5.0)
>   - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
> One or more packages are incompatible with .NETCoreApp,Version=v1.0.

Please make sure Xunit and its dependencies are supported with .netcoreapp

**Comment by bradwilson** [comment]
Getting started instructions are here: https://xunit.github.io/docs/getting-started-dotnet-core.html

**Comment by bradwilson** [comment]
Closed for age.
