### ISSUE TITLE
Documentation on using a config file for .NET Core is incorrect

### ISSUE THREAD

**Issue by jhubsharp** [xunit/xunit#1022]
https://xunit.github.io/docs/getting-started-dotnet-core.html

Under "Adding a configuration file", the way to specify files to copy to the output directory doesn't work. I think this is something that likely changed since the Core config was in flux for a while. I was able to get this to work by changing

`{
    "buildOptions": {
        "copyToOutput": {
            "include": [ "xunit.runner.json" ]
        }
    }
}`

to

`{
    "buildOptions": {
        "copyToOutput": [ "xunit.runner.json" ]
    }
}`

I can submit a PR to update the docs.

**Comment by bradwilson** [comment]
Closed for age.
