### ISSUE TITLE
Remove Win 8.1 and WPA 8.1 support

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1027]
This is a discussion thread about removing support for deprecated technologies.

If we implemented this, then version 2.1 would be the last version to support Windows 8.1 and Windows Phone App 8.1 unit tests. This is similar to our move in 2.1 to remove Windows 8.0 unit test support.

**Clarification** This would remove the ability to write unit tests for Windows 8.1 STORE applications, not Windows 8.1 DESKTOP applications. Desktop will continue to be supported on any platform where .NET 4.5 is available.

**Comment by pebezo** [comment]
Are you saying that xunit wouldn't run on Win8.1 anymore? I don't care about WPA, but if I need to move to W10 then that would suck...

**Comment by onovotny** [comment]
To be clear, this is about removing the VS runner for xUnit. The xUnit for Devices runner stiQ

**Comment by onovotny** [comment]
hitting the wrong button failure

**Comment by onovotny** [comment]
@pebezo to be clear, Windows 10 is and will continue to be supported.

**Comment by pebezo** [comment]
@onovotny Did you mean Windows 8.1?

**Comment by bradwilson** [comment]
@pebezo I've clarified the language. This does NOT affect desktop unit tests, only unit tests for STORE applications.

**Comment by fearthecowboy** [comment]
This is why I love @bradwilson . He's the only guy I know that has the guts to drop support for old technologies that you know damn well that you shouldn't be writing new code for. 

(that's my way of saying 👍 )

**Comment by bradwilson** [comment]
Wave goodbye... :)
