### ISSUE TITLE
Assert.ThrowsAsync Generic does not run when using custom Exceptions

### ISSUE THREAD

**Issue by jroger2908** [xunit/xunit#1028]
It appears that using the ThrowsAsync_Generic method with custom exceptions does not run
```
[Fact]
public async Task WriteAsyncThrowsExceptionWhenNoDeviceFound()
{
       DateTimeOffset firstDate = DateTimeOffset.UtcNow.AddHours(-2);
       DateTimeOffset secondDate = DateTimeOffset.UtcNow.AddHours(-1);
       _fakeDispenserDbSet.RemoveAll();

       await Assert.ThrowsAsync<DispenserNotFoundException>(() => _target.WriteAsync(SetupMessageModel(firstDate, secondDate)));
}
```

When changed to the non generic version the test will run
`await Assert.ThrowsAsync(typeof(DispenserNotFoundException), () => _target.WriteAsync(SetupMessageModel(firstDate, secondDate)));`

When changed to just Exception, the test will run.
`await Assert.ThrowsAsync<Exception>(() => _target.WriteAsync(SetupMessageModel(firstDate, secondDate)));`

**Comment by bradwilson** [comment]
Closed for age.
