### ISSUE TITLE
STA Thread for WPF objects

### ISSUE THREAD

**Issue by cbuteau** [xunit/xunit#103]
Is there a RequireSTA type attribute for xUnit.Net like there is in NUnit.
I am building complex tests that involve WPF objects and running into ...
"The calling thread cannot access this object because a different thread owns it." exceptions.

**Comment by eggapauli** [comment]
Why is this just a sample and not part of the core project? Would be useful I guess. If I want to use this by now I have to rip off this code, right?

**Comment by ivanrusso** [comment]
@bradwilson  Any news to support STAFact and STATheory in xunit.core.
I'm working on a SpecFlow PR https://github.com/techtalk/SpecFlow/pull/429 to support xunit2.
But the WPF-Tests (ViewModels) will throw an Exeption "must run on STA".
If xunit will support to define a test to run in STA (similar to Nunit http://nunit.org/index.php?p=requiresSTA&r=2.6.3), so i can support it too on Specflow Scenarios.

**Comment by bradwilson** [comment]
We have no intention of supporting this in the core framework. We do have a backlog item to provide the sample in NuGet form, for WPF and WinForms tests (need two separate libraries).

**Comment by JohanLarsson** [comment]
Any reason this went into samples and not an xunit.wpf nuget?

**Comment by cbuteau** [comment]
I guessing less work.  I haven't worked on an OSS project but I imagine it is really hard prioritizing what should be a feature versus a workaround.  Because no pay is involved.

**Comment by bradwilson** [comment]
The WPF version was picked up and released by @AArnott: https://www.nuget.org/packages/Xunit.StaFact/0.1.29-alpha

**Comment by JohanLarsson** [comment]
ah, thank you sir!
