### ISSUE TITLE
xUnit runner for Vs installation error

### ISSUE THREAD

**Issue by tahaipek** [xunit/xunit#1030]
I can't install [this extension](https://visualstudiogallery.msdn.microsoft.com/463c5987-f82b-46c8-a97e-b1cde42b9099). What do I need to do in this situation?

> 15.11.2016 00:39:44 - Microsoft VSIX Installer
15.11.2016 00:39:44 - -------------------------------------------
15.11.2016 00:39:44 - Initializing Install...
15.11.2016 00:39:44 - Extension Details...
15.11.2016 00:39:44 - 	Identifier         : xunit.runner.visualstudio.Microsoft.623f78dd-6d4b-48f3-a2c7-4bbb381bb146
15.11.2016 00:39:44 - 	Name               : xUnit.net runner for Visual Studio
15.11.2016 00:39:44 - 	Author             : Outercurve Foundation
15.11.2016 00:39:44 - 	Version            : 0.99.9
15.11.2016 00:39:44 - 	Description        : NO LONGER NEEDED. Please un-install this extension. See http://xunit.github.io/docs/vsix-deprecated.html
15.11.2016 00:39:44 - 	Locale             : en-US
15.11.2016 00:39:44 - 	MoreInfoURL        : http://xunit.github.io/docs/vsix-deprecated.html
15.11.2016 00:39:44 - 	InstalledByMSI     : False
15.11.2016 00:39:44 - 	SupportedFrameworkVersionRange : [3.5,)
15.11.2016 00:39:44 - 
15.11.2016 00:39:44 - 	SignatureState     : Unsigned
15.11.2016 00:39:44 - 	Supported Products : 
15.11.2016 00:39:44 - 		Microsoft.VisualStudio.Ultimate
15.11.2016 00:39:44 - 			Version : [11.0]
15.11.2016 00:39:44 - 		Microsoft.VisualStudio.Ultimate
15.11.2016 00:39:44 - 			Version : [12.0]
15.11.2016 00:39:44 - 		Microsoft.VisualStudio.Ultimate
15.11.2016 00:39:44 - 			Version : [14.0]
15.11.2016 00:39:44 - 		Microsoft.VisualStudio.Premium
15.11.2016 00:39:44 - 			Version : [11.0]
15.11.2016 00:39:44 - 		Microsoft.VisualStudio.Premium
15.11.2016 00:39:44 - 			Version : [12.0]
15.11.2016 00:39:44 - 		Microsoft.VisualStudio.Premium
15.11.2016 00:39:44 - 			Version : [14.0]
15.11.2016 00:39:44 - 		Microsoft.VisualStudio.Pro
15.11.2016 00:39:44 - 			Version : [11.0]
15.11.2016 00:39:44 - 		Microsoft.VisualStudio.Pro
15.11.2016 00:39:44 - 			Version : [12.0]
15.11.2016 00:39:44 - 		Microsoft.VisualStudio.Pro
15.11.2016 00:39:44 - 			Version : [14.0]
15.11.2016 00:39:44 - 
15.11.2016 00:39:44 - 	References         : 
15.11.2016 00:39:44 - Signature Details...
15.11.2016 00:39:44 - 	Extension is not signed.
15.11.2016 00:39:44 - 
15.11.2016 00:39:44 - Searching for applicable products...
15.11.2016 00:39:45 - Found installed product - Microsoft Visual Studio Enterprise 2015
15.11.2016 00:39:46 - The extension with ID 'xunit.runner.visualstudio.Microsoft.623f78dd-6d4b-48f3-a2c7-4bbb381bb146' is not installed to Microsoft Visual Studio Enterprise 2015.
15.11.2016 00:39:46 - Found installed product - Microsoft Visual Studio Professional 2015
15.11.2016 00:39:46 - Found installed product - Microsoft Visual Studio Community 2015
15.11.2016 00:39:46 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
15.11.2016 00:39:46 - Found installed product - Global Location
15.11.2016 00:39:46 - Found installed product - ssms
15.11.2016 00:39:49 - The following target products have been selected...
15.11.2016 00:39:49 - 	Microsoft Visual Studio Enterprise 2015
15.11.2016 00:39:49 - 
15.11.2016 00:39:50 - Beginning to install extension to Microsoft Visual Studio Enterprise 2015...
15.11.2016 00:39:50 - **Install Error : System.NullReferenceException: Object reference not set to an instance of an object.**
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForValidDotNetFramework(IExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten, Boolean enforceCertificateCheckForUpgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp, Boolean enforceCertificateCheckForUpgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp, Boolean enforceCertificateCheckForUpgrade)

**Comment by bradwilson** [comment]
Allow me to quote your message:

> Description : NO LONGER NEEDED. Please un-install this extension.

The VSIX is no longer supported. Use the NuGet package `xunit.runner.visualstudio` instead.

**Comment by tahaipek** [comment]
Thanks for answer @bradwilson
