### ISSUE TITLE
Add formatted messages to Assertions

### ISSUE THREAD

**Issue by mwpowellhtx** [xunit/xunit#1035]
In general I like the "light weight" feel of the library, but finding there are cases where messaging is ***ESSENTIAL***.

Similar to NUnit parity (haven't dug into the message trail [here](http://github.com/xunit/xunit/issues/350)...), except to say, it's a must have, especially in cases where I have 2-3 levels of separation between the target under test and the actual granular assertion being enforced. Some context in the form of messaging would be welcome.

That or can you recommend an exception wrapper through which messaging could occur (i.e. assuming exceptions are the "communication" that occurs upon assertion). For instance, I could see something like this:

```C#
using (var ac = new AssertionContext("Contextual message {0}, {1}. {2}", a, i, x))
{
    ac.Enforce(() =>
    {
        Assert.Equals(...);
        Assert.True(...);
        Assert.This(...);
        Assert.That(...);
        Assert.Or.Other(...);
    });
}
```

In which, ``Enforce`` wraps the action in a ``try/catch`` statement, with appropriate writes to Trace, Console, etc, and which would necessarily re-throw. Or with options how strong an enforcement on whether to re-throw. but that's a distant side issue.

Something along those lines.

Thank you...

**Comment by bradwilson** [comment]
Closed for age.
