### ISSUE TITLE
Proposal: Assert.Equal/InRange for 3+ arguments

### ISSUE THREAD

**Issue by jamesqo** [xunit/xunit#1036]
## Background

Often I find that there are multiple methods I want to test that lead to the same result. For example, here's a snippet from my codebase that asserts multiple expressions are equal to `sum` /  `-sum`:

```cs
// (Note: These are not integers, but custom types with overloaded +/subtraction/negation operators)
Assert.Equal(sum, first + second);
Assert.Equal(sum, second + first);

Assert.Equal(sum, first - (-second));
Assert.Equal(sum, second - (-first));

Assert.Equal(-sum, -first - second);
Assert.Equal(-sum, -second - first);
```

I have to type out `Assert.Equal(sum,` each time I want to verify the same thing is equal to a new expression, which feels repetitive. I think it would be helpful if we could consolidate all equivalent expressions into a single assert.

## Proposal

- I propose adding an overload of `Equal` accepting `params T[]` to allow for any number of 'actual' arguments:

```cs
public class Assert
{
    public static void Equal<T>(T expected, params T[] actual);
}
```

With this API addition, the above code becomes:

```cs
Assert.Equal(sum, first + second, second + first, first - (-second), second - (-first));
Assert.Equal(-sum, -first - second, -second - first);
```

- Along a similar line, I also think it would be useful to add a version of `InRange` designed for 3+ arguments, e.g. `Assert.Ordered`. This would be very helpful for testing `IComparable` implementations, because instead of writing

```cs
Assert.InRange(least, MinValue, less); // MinValue <= least <= less
Assert.InRange(less, least, more); // least <= less <= more
Assert.InRange(more, less, most); // less <= more <= most
Assert.InRange(most, more, MaxValue); // more <= most <= MaxValue
```

(which can be dizzying because of the middle/low/high order), you could write

```cs
// MinValue <= least <= less <= more <= most <= MaxValue
Assert.Ordered(MinValue, least, less, more, most, MaxValue);
```

Here's the full API proposal for these methods:

```cs
public class Assert
{
    public static void Equal<T>(T expected, params T[] actual);
    public static void Ordered<T>(params T[] values); // An alternative name could be InOrder
}
```

## Possible caveats

- `params` allows you to specify as little as 0 arguments, so all of the following meaningless combinations would be possible with the above proposal:

```cs
Assert.Equal(foo);
Assert.Ordered();
Assert.Ordered(foo); // A single-item array is always ordered
```

To enforce that we receive at least 2 parameters in both cases, we can modify the signatures slightly.

```cs
public class Assert
{
    public static void Equal<T>(T expected, T actual0, params T[] rest);
    public static void Ordered<T>(T value0, T value1, params T[] rest);
}
```

One other thing this fixes is `Assert.Equal(foo, new[] { foo })` being reinterpreted to use the `params` overload.

- The user won't be able to specify the comparer as the last argument. Unfortunately, I see no way around this but to accept the comparer as the first argument, which is inconsistent with the other methods in this class.

```cs
// Final proposal:
public class Assert
{
    public static void Equal<T>(T expected, T actual0, params T[] rest);
    public static void Equal<T>(IEqualityComparer<T> comparer, T expected, T actual0, params T[] rest);
    public static void Ordered<T>(T value0, T value1, params T[] rest);
    public static void Ordered<T>(IComparer<T> comparer, T value0, T value1, params T[] rest);
}
```

Thoughts?

**Comment by bradwilson** [comment]
Closed for age.

**Comment by jamesqo** [comment]
@bradwilson That seems somewhat arbitrary... so does that mean you don't think this is a good idea?

**Comment by bradwilson** [comment]
https://twitter.com/bradwilson/status/929046059640225793

**Comment by jamesqo** [comment]
OK. Does that mean that I should just go ahead and submit a PR next time, instead of opening an issue?

**Comment by bradwilson** [comment]
In this case, I probably should've said that this was not an issue we're interested in.

**Comment by jamesqo** [comment]
Ok. Nice of you to clarify :smile:
