### ISSUE TITLE
Mixed mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 4.0 runtime without additional configuration information

### ISSUE THREAD

**Issue by patricknolan** [xunit/xunit#1037]
Hi,

I have a test which calls an assembly built against version 'v2.0.50727' of the .net framework. This results in the following error

> Mixed mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 4.0 runtime without additional configuration information

When calling the assembly from a console app adding the following to the app.config file resolves the issue. 
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <startup useLegacyV2RuntimeActivationPolicy="true">
    <supportedRuntime version="v4.0"/>
  </startup>
</configuration>
```

Adding the above configuration to a app.config file in the assembly containing the XUnit test does not help. Adding to the TE.ProcessHost.Managed.Clr20.exe config file doesn't seem to help either.

How would I get around this error with XUnit in Visual Studio 2015?

**Comment by patnolan** [comment]
I should also include that I'm using a .Net Core project.

**Comment by patnolan** [comment]
Just worked it out. The startup supportedRuntime configuration needs to be added to a config file named dotnet-test-xunit.exe.Config located in the project containing the XUnit tests.

**Comment by bradwilson** [comment]
Closed for age.
