### ISSUE TITLE
Log output from the SUT?

### ISSUE THREAD

**Issue by drauch** [xunit/xunit#1038]
Are there any plans to allow log output **from the SUT** (so no ITestOutputHelper) to the console?

Yes, I understand, that there are problems of associating the output with the corresponding test, but in some cases "printf-debugging" is a magnitude faster than to start a debugger.

(it would be a start to have output at least in scenarios where I execute only a single test is executed; that way the associating should be no problem)

All the best,
D.R.

**Comment by bradwilson** [comment]
Closed for age.

**Comment by drauch** [comment]
This is also a way to say "no" ...

**Comment by bradwilson** [comment]
https://twitter.com/bradwilson/status/929046059640225793

**Comment by drauch** [comment]
I don't see how closing issues is magically removing the technical debt. But you're not the only OSS project to do so ... unfortunately.

**Comment by bradwilson** [comment]
In this particular case, this is not something we're going to add. It should've been closed prior to today.
