### ISSUE TITLE
Unable to load Xunit tests in Test Explorer

### ISSUE THREAD

**Issue by vikasillumina** [xunit/xunit#1039]
Hi there,

I have one of my team member having issue with loading the xunit tests in the test explorer. He is getting below error:
vstest.discoveryengine.x86.exe' WCF communication channel unavailable. Active request will be aborted.

Please note we have already tried below solution:
o	Go to run type %TEMP%
o	Look for VisualStudioTestExplorerExtensions folder and delete it.
Referred from here: http://xunit.github.io/docs/running-tests-in-vs.html

This didn't help.
He has the exact same version of Visual Studio 2015 Enterprise and Xunit 2.1 that we all have. Within same solution we have non xunit tests and he is able to load those tests.  Except this team member all of us are able to load all the tests without any issue. He even tried reinstalling his visual studio and running it under administrator account as well but none of that helped so far. Please can you suggest what can we do?

Thanks for your help in advance.

**Comment by bradwilson** [comment]
Is the source on a network drive? If so, that causes permission issues when loading assemblies into .NET.

That's the only thing I can think of off the top of my head without more detail and/or a repro case.

**Comment by vikasillumina** [comment]
Thanks Brad for your quick response. I will double check where the source code is. But I am almost certain that its on local. But I have asked the team member to move the code to d drive instead of the system c drive.

**Comment by vikasillumina** [comment]
Hi Brad, 
Sorry the late response. My colleague later found out the issue to be that he had opened the project solution on his parallel vm running inside his mac while the source code was on mac instead of a local copy inside his vm. After he copied the code to his vm the problem went away.  
So not an issue but user issue. :) 

Thanks for your quick response earlier.
