### ISSUE TITLE
Visual Studio for Mac Preview Testrunner Support

### ISSUE THREAD

**Issue by jlebensold** [xunit/xunit#1041]
Hi there,

I'm trying to get Visual Studio for Mac to work with xUnit with the VS for Mac test runner. Is there a build / configuration where this is supported?

**Comment by mhutch** [comment]
cc @slluis @Therzok

**Comment by jlebensold** [comment]
Hey all, anyone get this working?

**Comment by slluis** [comment]
If the xUnit runner is compiled for VS for Mac, it should just work. The unit testing api has not changed.

**Comment by jlebensold** [comment]
@slluis I'm trying to start with the NUnit sample project (Target framework – Mono / .NET 4.5)

I tried removing the `nunit.framework` package and added `xunit.runner.visualstudio` and `xunit.core` with version 2.1.0.

The Unit Tests runner simply doesn't pick up any test cases. Please let me know what I'm missing.

**Comment by bradwilson** [comment]
Dup of #1043
