### ISSUE TITLE
Visual Studio test runner fails if test class has method overloads.

### ISSUE THREAD

**Issue by Ilchert** [xunit/xunit#1042]
Tests fail from visual studio runner if test class has method overloads.

There is a small demo:

![image](https://cloud.githubusercontent.com/assets/13449633/20835976/61fc6998-b8ae-11e6-9b3a-3030b5241f2f.png)

**Comment by bradwilson** [comment]
Unfortunately, this is not fixable. To work around it, rename one of the methods.

**Comment by Ilchert** [comment]
Thanks!

**Comment by codito** [comment]
@bradwilson @onovotny any idea of the root cause for this issue?
