### ISSUE TITLE
Test aren't being discovered [VS for Mac]

### ISSUE THREAD

**Issue by zorthgo** [xunit/xunit#1043]
Hi Guys, I am having an issue with xUnit and Visual Studio for Mac. None of my tests are being discovered. 

These are the steps that I went through to test this issue:

  1 - I created a test application on my Visual Studio on Windows.
  2 - Ran my unit tests (they work fine) 
  3 - Commit the solution to git. 
  4 - Pull the solution to my Visual Studio for Mac
  5 - Ran the tests (No go. They aren't being discovered).  

I've also created the tests directly on my VS for mac. And still no go!.. 

Any help would be appreciated. Thanks! ;0)

Regards, 
Jay

**Comment by bradwilson** [comment]
We do not support Visual Studio for Mac.

It's possible that the [third party Xamarin plugin](https://github.com/xunit/xamarinstudio.xunit) will eventually be adapted, but we have no plans for this on the core team.

**Comment by zorthgo** [comment]
Bummer!... :(

But hey, thanks for the quick reply. I'll try with the third party Xamarin plugin guys. ;0)

**Comment by Leonardo-Ferreira** [comment]
I just managed to kind of do it...
I added these:
<PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-beta3-build3705" />
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
<PackageReference Include="xunit" Version="2.3.0-beta2-build3683" />
<DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta2-build3683" />

the tests are discovered and everything... only problem is "Unsupported target framework '.NETStandard 1.6' (only .NETCoreApp 1.0+ and .NETFramework 4.5.2+ are supported)"

any ideas anyone?

**Comment by bradwilson** [comment]
Yes. Follow the directions and make your test project either `netcoreapp1.0` (or later) or `net452` (or later).

**Comment by Leonardo-Ferreira** [comment]
everything working fine now... discovering and running via test explorer and all

**Comment by bradwilson** [comment]
@karlingen `netstandard` test libraries are not supported. https://xunit.github.io/docs/why-no-netstandard

**Comment by ChristopherJdL** [comment]
I found it easier for VS for Mac to discover the tests when I created a "Xunit Test Project".
This way, VS for Mac discovers the test way more easily.

Furthermore, Make sure every project of the solution you're testing (including the test project) target the same .NET Runtime and SDK.

This should help VS for Mac to discover the tests.
