### ISSUE TITLE
[Feature Request] Add process-isolation to testrunners

### ISSUE THREAD

**Issue by 0x53A** [xunit/xunit#1044]
(So I thought this would be a popular request, but searching for ___xunit process isolation___ I could only find articles which talked about __the tdd _process___, and that __components in a test should be _isolated___. Apologies if this is a dupe.)

Currently you can use app-domains to isolate test code. This works reasonably well for managed code, but has a few issues:

* It only isolates managed code, if I load a native dll and set a static value, this will be visible in all appdomains.
* It doesn't protect against some kinds of crashes: Stackoverflows, exceptions from finalizers, Environment.Exit, and probably a few others.

In our latest CI build I got an exception in a finalizer, which caused the process to terminate without writing a result xml file, which caused the build to go green because there were no failed tests =) (ok, that is really an issue with our build script...).

I would like to be able to isolate tests in a separate process. Similar to App-Domains, I think it should be possible to 

* run all tests in the main process (default, like today).
* run all tests in one sub-process, if that process dies, the whole run is aborted and marked as failed. (this would enable at least a broad failure detection.)
* run each test in a single process (multiple processes in parallel, if enabled). If a process dies, only that test can be marked as failed, and the run can continue.

In addition to the increased fault tolerance, this would also enable to isolate native components from different tests. Currently we need to run a few tests serially, because they load mixed mode c++/cli modules which in turn heavily depend on native dlls and global state.

**Comment by bradwilson** [comment]
We considered process isolation long long ago, but rejected it because it has a dramatically negative effect on debugging. Unless you install a third party extension into Visual Studio, it would not be possible to directly debug your unit tests; you would be forced to attach the debugger to the spawned process by hand.

For that reason, we've already considered and rejected this idea.

**Comment by 0x53A** [comment]
Sure, debugging would be a little bit harder. Worst case, you could add a call to Debugger.Attach, which opens up a window where the user can then attach.

But if this was a runner-specific setting then the tests could continue to run in-proc in visual studio. (Similar to app-domains, with IfAvailable, Always, Denied)
I'm still convinced the pros outweigh the cons, at least for the console runner, for CI builds.

My main motivation is failure detection, so just running all tests in a single sub-process would be enough so that it doesn't silently crash.

Are you totally against this forever, or just low on the priority?

Anyway, thank you for taking the time to respond and for providing this project.

**Comment by yatli** [comment]
I'm also facing the same situation here. The tests involve P/Invoke and would possibly crash the runner process so no reports are collected. It's a little bit hard to automate failure detection from outside the test runner because we don't know what is inside a test assembly (how many tests are there, inline data etc.).

**Comment by bradwilson** [comment]
We have no intention of supporting this directly.

If your tests need process isolation, then only run them one assembly at a time to get this isolation.

**Comment by bradwilson** [comment]
Closed for age.
