### ISSUE TITLE
Custom ITraitAttribute are not compatible with the console runner and absent from xml report

### ISSUE THREAD

**Issue by xlegalles** [xunit/xunit#1045]
I have implemented some custom Trait attributes using ITraitAttribute/ITraitDiscover but there are not usable with the xUnit console runner (2.1) using the -trait command line parameter.
There are also missing from the XML report.

As soon as I use a standard TraitAttribute, everything works.

Do I miss something? I have even tried the last beta runner wo success.

**Comment by bradwilson** [comment]
Can you provide a repro project?

**Comment by xlegalles** [comment]
My fault, you can close it: the type name of the discoverer was wrong because in a sub-namespace.
Sorry about that.
