### ISSUE TITLE
Unable to get tests discovered Visual Studio 2013 Update 4

### ISSUE THREAD

**Issue by ricardomlourenco** [xunit/xunit#1047]
Hey guys,

I tried to created a basic test like the example and still not working on my machine. I used this reference:

1. http://xunit.github.io/docs/getting-started-desktop#run-tests-visualstudio.
I stopped on Running tests with Visual Studio

2. I deleted the folder %TEMP%\VisualStudioTestExplorerExtensions

3. I recompile the Project and the Tests aren't being discovered by Visual Studio whatsoever.
------ Discover test started ------
========== Discover test finished: 0 found (0:00:00.0510051) ==========

Notes:
- My class is public
- I'm using public class to create tests.
- I restarted VS several times.
- I restarted my machine as well
Can anyone help please?

Thank you,
Ricardo
![capture](https://cloud.githubusercontent.com/assets/5605533/20989633/6a8b1002-bca3-11e6-885b-8465d78a79be.JPG)

**Comment by bradwilson** [comment]
What version of the `xunit.runner.visualstudio` NuGet package are you using?

**Comment by ricardomlourenco** [comment]
Hi Brad, thanks for quickly reply.

I'm using xUnit 2.1 and xUnit runner 2.1.

I believe must be something on my machine in the Office. I'll try it on another machine later on. 

Do you know if there are some logs or anything that I can use to check if my xUnit version is having some problem of confit?

**Comment by bradwilson** [comment]
It depends on where the problem is, but the first thing I'd recommend is [enabling diagnostic messages](http://xunit.github.io/docs/configuring-with-xml.html), and seeing if anything shows up in the Tests tab of the Output window.

**Comment by ricardomlourenco** [comment]
Ok! I'm gonna do that tomorrow morning and I post here the results...

Thanks a lot!

**Comment by ricardomlourenco** [comment]
I added the App.config file as below and still nothing has changed.
Also I couldn't see the diagnostic on Test window. So I enabled the diagnostic for MsBuild (please see file attached)

It looks like the runner is not being triggered after the Build.

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <add key="xunit.diagnosticMessages" value="true" />    
  </appSettings>  
</configuration>

[xunit.project.buildLog.txt](https://github.com/xunit/xunit/files/639919/xunit.project.buildLog.txt)

**Comment by ricardomlourenco** [comment]
I tested at home in another Machine and it works just fine! There are some issue loading extensions on my Visual Studio 2012 and 2013 as well. I'm unable to load any extension such as Specflow and Telerik.
I'll try to find out why this is happening.

Thank you Brad for the support.

Best regards,
Ricardo
