### ISSUE TITLE
Request: support assertion counting

### ISSUE THREAD

**Issue by jovanpop-msft** [xunit/xunit#1048]
Ability to assert that test has executed exactly N assertions is very valuable especially in async commands or tests with if/else logic. If we have assert in if statement, test may pass because assertion didn't failed, or because this code was not executed at all. 
Currently I need to create some flags that are set after assertion check in code and check at the end of the test is this flag set. This feature already exists in csUnit: http://www.csunit.org/documentation/classdoc.2.0/csUnit.Assert.Count.html

**Comment by bradwilson** [comment]
Closed for age.
