### ISSUE TITLE
AssebmlyRunner.cs returning null for stacktrace

### ISSUE THREAD

**Issue by karthikasobhana** [xunit/xunit#1049]
We are using AssemblyRunner.cs for running xunit tests programmatically. 
Test methods are [Fact] attributed and couple of Assert() functions are there inside each one of them.
Also, some tests have following structure :
[Fact]
public void TestMethod_1(){
        Method_2();
       Assert.Equal(.....);   _//Outer_assert_1_
       Assert.Equal(.....);   _//Outer_assert_2_
}

public class Method_2{
     Method_2(){
        Assert. True(...);  _//Inner_assert_1_
    }
}

Here, whenever the Inner_assert_1 fails, control is passed to OnTestFailed() as expected, but **without any StackTrace or Exception details**.

But if we comment the inner_assert_1 and only the outer asserts are there, then Stacktrace is obtained inside the delegate.

Also when tests are run using xunit.console.exe we got stacktrace(in the output file).
Any possible solution for this?

**Comment by bradwilson** [comment]
Closed for age.
