### ISSUE TITLE
Running OWIN self hosted Web API unit tests fail

### ISSUE THREAD

**Issue by mwpowellhtx** [xunit/xunit#1053]
I have a couple of unit test fixtures, if you will. Fixture being the classes hosting the facts, theories, etc. They both derive from a self hosting test fixture that establishes the base address and port, localhost and a randomly chosen port number.

The test fixtures are each focused on a specific controller. It appears the VS runner is running the tests in parallel, which causes some problems. This exception occurs on the first invocation. Every invocation following that one succeeds. I can re-run the test and it runs successfully.

```
System.Net.HttpListenerException
Failed to listen on prefix 'http://localhost:9998/' because it conflicts with an existing registration on the machine.
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
```

Perhaps is a bug in the OWIN framework, I don't know.

**Comment by bradwilson** [comment]
Everything you ever wanted to know about parallelism in xUnit.net (I think): https://xunit.github.io/docs/running-tests-in-parallel.html

**Comment by mwpowellhtx** [comment]
@bradwilson Hey I appreciate it; I'm all for parallelism as much as possible. However, this is a corner case, that OWIN appears not to respond well to this, AT ALL.

So, I disabled it at the assembly level, and all seems to be well, now. Thanks again!

```C#
[assembly: CollectionBehavior(DisableTestParallelization = true)]
```

**Comment by bradwilson** [comment]
Closed for age.
