### ISSUE TITLE
Go to source in VS not working for xunit .net core tests

### ISSUE THREAD

**Issue by codito** [xunit/xunit#1054]
## Steps to reproduce
* Install VS 2017 RC with .net and docker preview workload
* Create a new xunit test project
* Build the project
* After tests are discovered in the Test Explorer, double click on a Test

## Expected
User should be able to navigate to source code

## Actual
Nothing happens since source code information is not available in Test Explorer.

**Comment by codito** [comment]
The fix is probably to include [DiaSession](https://github.com/xunit/xunit/blob/master/src/xunit.runner.utility/Utility/DiaSession.cs) for netcore builds.

**Comment by onovotny** [comment]
@codito please see my comment: https://github.com/xunit/xunit/pull/1055#issuecomment-268281826. Looks like there's a bug in the ObjectModel lib.
