### ISSUE TITLE
How to unit test for Asp.Net Mvc

### ISSUE THREAD

**Issue by mwpowellhtx** [xunit/xunit#1063]
Would like to discuss in appropriate forum, but will use this for now. See message offline for Slack request.

Okay, I would like to test an Asp.Net Mvc extension. I've done so for an OWIN-self-hosted Web API along these lines. But apparently, with Mvc 5 it isn't possible?

That, or potentially adopt vNext, provided it is mature enough; although what I gather is that the vNext core refactor is still in RC mode, has not been officially released through NuGet channels, for instance.

At present, it looks like I at least need to have a test Mvc site within my solution. Then the question becomes, how to activate that site when the unit tests run.

Thanks for any insights!

**Comment by bradwilson** [comment]
Closed for age.
