### ISSUE TITLE
Strange behavior when calling async method within tests

### ISSUE THREAD

**Issue by anass-b** [xunit/xunit#1066]
Hello,
I have some integration tests that connects to database and message brokers, and therefore they are async, but I every time use `MyMethodAsync().Wait()` or `MyMethodAsync().GetAwaiter().GetResult()` so I keep all my tests **non async** because I saw there are some bug reports concerning async tests with xUnit.
So here is the problem: while running my tests from time to time in Visual Studio 2015, or from `dotnet test` in the command line, all is good. Until I decided to do this in PowerShell:
```
while ($true) { Invoke-Expression "dotnet test" }
```
The reason behind it is that I needed to keep the tests running for some time in order to discover any race conditions within my microservices and look at the overall performance etc.
What happened is that my tests were passing only 98% of the time, it was really hard to reproduce that 2%. Sometimes it happens after 2 minutes, sometimes in 15 or 40 minutes. After spending 3 days looking for the issue in my code, I couldn't find anything. Then I had the idea of maybe trying to run my tests with NUnit, when I did that, my tests would run forever without failing, it was 100% all the time.
You can reproduce that with a code similar to this:
```
class MyTests
{
   [Fact]
   public void MyTest()
   {
      MyMethodAync().Wait();
      var result = MyOtherMethod().GetAwaiter().GetResult();
   }
}
```
and keep it running for some time with:
```
while ($true) { Invoke-Expression "dotnet test" }
```
The problem is that I'm not sure the issue can be reproduced with simple methods, but rather with some laborious database logic like database/networking so the person can start seeing strange behavior within the code.

**Comment by onovotny** [comment]
async tests work very well with xUnit. Calling `Wait()` or `GetResult()` will almost certainly lead to deadlocks.

What happens if you update your test to be either `async void` or `async Task` and use `await`?

**Comment by anass-b** [comment]
@onovotny I updated my tests to use `async Task` and `await`, I got the same issues.

**Comment by maxmantz** [comment]
Hi,

I got similar issues. I'm testing async service methods interacting with an EFCore-mapped database. My test  classes inherit from a base `ContextFixture` class which implements `IDisposable`. In the `Dispose()` method, I destroy the entire database and in the constructor I create it again (no in-memory DB possible I'm afraid...)

This leads to strange issues: when I run all tests, some tests fail with error messages relating to assertion failures, or the database not being present. However when I single out the test classes and run only the tests within them, they all pass.

I've tried async tests with `public async Task TestSomething()` or `public async void TestSomething()` as well as synchronous tests with calls to `GetAwaiter().GetResult()`. All approaches have the same issue.

**Comment by marcind** [comment]
@maxmantz try implementing [IAsyncLifetime](https://github.com/xunit/xunit/blob/master/src/xunit.core/IAsyncLifetime.cs) instead of constructor/Dispose. Also make sure your tests are not accessing a shared resource when being run in parallel. You can find more information here: http://xunit.github.io/docs/running-tests-in-parallel.html.

**Comment by maxmantz** [comment]
@marcind Thank you. Implementing `IAsyncLifetime` together with `[assembly: CollectionBehavior(DisableTestParallelization = true)]` fixed these issues for me.

**Comment by bradwilson** [comment]
Closed for age.
