### ISSUE TITLE
Test defined in base class fails to run when using IClassFixture

### ISSUE THREAD

**Issue by pmiddleton** [xunit/xunit#1068]
In a 3 tier hierarchy (child -> parent -> grandparent) if a test is defined on the grandparent and overridden in the child the test will not run.  The test needs to be also overridden in the parent.  

TestDriven.Net returns the error "The containing class must have a default constructor." and the XUnit console runner does not find the test.

The issue only presents itself when IClassFixture is being used.

I have tested this using XUnit 2.1 and the latest beta of 2.2

The following code repos the issue.  Uncomment the code in parent to get the test to run successfully.

```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xunit;

namespace ClassLibrary1
{
    public class Foo
    {
    }

    public class Child : Parent<Foo>
    {
        public Child(Foo fixture)
            : base(fixture)
        { }

        public override void Test()
        {
            base.Test();
        }
    }

    public abstract class Parent<TFixture> : GrandParent<TFixture>
        where TFixture : class
    {
        protected Parent(TFixture fixture) : base(fixture)
        { }

        /*public override void Test()
        {
            base.Test();
        }*/
    }

    public abstract class GrandParent<TFixture> : IClassFixture<TFixture>
        where TFixture : class
    {
        protected GrandParent(TFixture fixture)
        {
        }

        [Fact]
        public virtual void Test()
        {
            Assert.True(1 == 1);
        }
    }
}
```

**Comment by smitpatel** [comment]
I also encountered same issue today and it happens even in the absence of IClassFixture.
