### ISSUE TITLE
Deadlock When No Tests To Run

### ISSUE THREAD

**Issue by marko-vasic** [xunit/xunit#1071]
In cases when no tests are selected for execution
OnExecutionComplete handler is not called.

As a workaround I call Cancel method on a AssemblyRunner
which causes OnExecutionComplete handler to get triggered,
however another problem in that case is that Status is never set to Idle,
which causes exception when Disposing the runner.
I call Cancel inside of OnDiscoveryComplete handler in cases when there are no tests to run.

Comment:
I do not know how many tests will be left for run after filtering,
I just know a filtering algorithm which I apply inside of TestCaseFilter callback
this is in a case you wonder why I don't just skip calling Start method if there are no tests to run.

**Comment by bradwilson** [comment]
Closed for age.
