### ISSUE TITLE
IHostingEnvironment injection?

### ISSUE THREAD

**Issue by another-guy** [xunit/xunit#1072]
As per [SO answert](http://stackoverflow.com/a/38917833/482868) there's currently no way to get a reference to IHostingEnvironment in a test. I wonder if there is a plan to support injection of this object into the test environment.

**Comment by bradwilson** [comment]
There is no plan for this today in the core framework. This feature would belong in an extension.

**Comment by another-guy** [comment]
@bradwilson thanks for the update! When you say 'in an extension', are you referring to [xunit.extensions](https://www.nuget.org/packages/xunit.extensions/) ?

**Comment by bradwilson** [comment]
Closed for age.
