### ISSUE TITLE
Perf issue in visualstudio.xunit adapter during test discovery

### ISSUE THREAD

**Issue by Shyam-Gupta** [xunit/xunit#1074]
During test discovery, VisualStudio xunit adapter returns a test as soon as it gets discovered. This behavior increases the overall time taken for test discovery in comparison to caching the discovered tests first and sending them later.

Consider following code snippet taken from VsDiscoverySink.cs:

```
void HandleTestCaseDiscoveryMessage(MessageHandlerArgs<ITestCaseDiscoveryMessage> args)
{
    var testCase = args.Message.TestCase;            
    var testClass = $"{testCase.TestMethod.TestClass.Class.Name}.{testCase.TestMethod.Method.Name}";
    if (lastTestClass != testClass)
        SendExistingTestCases();

    lastTestClass = testClass;
    lastTestClassTestCases.Add(testCase);
    TotalTests++;

    HandleCancellation(args);
}
```

This function handles test discovery event. Although logic is present to cache all tests in a test class in lastTestClassTestCases list, it is not working due to bug in following statement:

`var testClass = $"{testCase.TestMethod.TestClass.Class.Name}.{testCase.TestMethod.Method.Name}";`

The variable testClass expects test class name. Instead test method name is getting assigned. Since test method names are distinct in a test class, SendExistingTestCases() gets called for each test case.
This increases the overall time taken for test discovery.

We observed significant performance gains after assigning test class name instead of test method name to testClass variable. Following are the numbers obtained on a VM having 8 cores 56 GB RAM, to discover 5000 tests present in 10 test classes with 500 tests each:

Time taken with current code: 83.5 sec
Time taken after fix: 48.2 sec
Time saving = 35 sec or 42% approx.

Another experiment with 5000 tests in a single test class gave numbers: 73.8 sec and 51.2 sec for before and after fix scenarios respectively. Saving = 22.6 sec or 30.6%

Hence requesting you to consider this bug fix.

**Comment by bradwilson** [comment]
Fixed by https://github.com/xunit/visualstudio.xunit/commit/a9fa27a564bd8f350e6e978ee1337f39ac647538
