### ISSUE TITLE
VS Adapter test discovery when running tests very slow

### ISSUE THREAD

**Issue by ErikEJ** [xunit/xunit#1075]
```
------ Run test started ------
[xUnit.net 00:00:00.8096647]   Discovering: EntityFramework.SqlServerCompact.FunctionalTests
[xUnit.net 00:14:47.0497186]   Discovered:  EntityFramework.SqlServerCompact.FunctionalTests
[xUnit.net 00:14:47.5409732]   Discovering: EntityFramework.SqlServerCompact.Tests
[xUnit.net 00:14:51.4586458]   Discovered:  EntityFramework.SqlServerCompact.Tests
[xUnit.net 00:14:51.9199657]   Discovering: EntityFramework.SqlServerCompact.Legacy.FunctionalTests
[xUnit.net 00:14:52.6598653]   Discovered:  EntityFramework.SqlServerCompact.Legacy.FunctionalTests
[xUnit.net 00:14:53.3792714]   Discovering: EntityFramework.SqlServerCompact40.Design.FunctionalTest
[xUnit.net 00:14:53.6836639]   Discovered:  EntityFramework.SqlServerCompact40.Design.FunctionalTest
[xUnit.net 00:14:56.5883914]   Starting:    EntityFramework.SqlServerCompact.FunctionalTests
```

On VS 2015 Update 3 (Intel Core i7, 16 GB RAM, SSD)

Yes, the EF Test classes are huge, but 15 minutes?

**Comment by bradwilson** [comment]
Is this new with beta 5? Are these the tests that are in the EF Github repository, and if so, what branch/commit hash?

**Comment by ErikEJ** [comment]
package id="xunit.runner.visualstudio" version="2.2.0-beta4-build1194" targetFramework="net46" developmentDependency="true" 

The tests are   package id="Microsoft.EntityFrameworkCore.Relational.Specification.Tests" version="1.2.0-preview1-22878" targetFramework="net46" (From dotnet.myge.org)

I could try beta5 perhaps?

**Comment by bradwilson** [comment]
You can try beta 5. I was just trying to see if this was something caused recently.

**Comment by bradwilson** [comment]
I grabbed your repo, and I'm not able to reproduce this.

```
[xUnit.net 00:00:01.0989258]   Discovering: EntityFramework.SqlServerCompact.FunctionalTests
[xUnit.net 00:00:25.3090753]   Discovered:  EntityFramework.SqlServerCompact.FunctionalTests
```

**Comment by ErikEJ** [comment]
Thanks, Brad, I will clear caches etc...

**Comment by bradwilson** [comment]
So you're saying discovery for discovery is fast, but discovery for execution is slow...?

**Comment by ErikEJ** [comment]
Indeed!

**Comment by ErikEJ** [comment]
Seems to be fixed with latest test DLLs from EF Core and beta5-build3474
