### ISSUE TITLE
xunit.runner.visualstudio should add nuget dependency on Microsoft.DotNet.InternalAbstractions

### ISSUE THREAD

**Issue by codito** [xunit/xunit#1080]
_From @ardalis on January 17, 2017 21:37_

I have a test project that utilizes ASP.NET Core 1.1 and it's getting this error when trying to discover tests in Visual Studio.

[xUnit.net 00:00:00.0439643] Exception discovering tests: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.InternalAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.DotNet.InternalAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.GetAvailableRunnerReporters(IEnumerable`1 sources)

   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.GetRunnerReporter(IEnumerable`1 assemblyFileNames)

   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.DiscoverTests[TVisitor](IRunSettings runSettings, IEnumerable`1 sources, LoggerHelper logger, Func`4 visitorFactory, Action`4 visitComplete)

I talked to @bradwilson and he let me know to add the missing package as a reference to the test project, and this worked as a workaround.

Also posted here: http://ardalis.com/xunit-test-discovery-error-with-aspnet-core-1-1

_Copied from original issue: dotnet/roslyn-project-system#1221_

**Comment by bradwilson** [comment]
I am 100% against the idea of adding a dependency on someone else's internal packages.

**Comment by codito** [comment]
The dependency on InternalAbstractions is possibly coming from `RuntimeEnvironment` usage: https://github.com/xunit/visualstudio.xunit/blob/1fef0e328a43a2309df285e52580f1f95e1a48fc/xunit.runner.visualstudio.desktop/VsTestRunner.cs#L543

**Comment by onovotny** [comment]
This isn't an xUnit issue, this was a breaking change in .NET Core 1.1 vs 1.0.

https://github.com/aspnet/EntityFramework/pull/6678#issuecomment-251477754

The `Microsoft.DotNet.InternalAbstractions` was replaced by `Microsoft.DotNet.PlatformAbstractions` but anyone building against 1.0 that uses those types will need it if you pull in the NET Core App 1.1 graph instead of the 1.0 graph.

**Comment by codito** [comment]
The `Microsoft.Extensions.DependencyModel` package uses `PlatformAbstractions` as a dependency starting `1.1.0`. Since it supports `netstandard1.3`, could xunit.runner.visualstudio.dotnetcore refer this version of DependencyModel?

The `1.0.0` version of DependencyModel pulls in `InternalAbstractions` package dependency.

**Comment by bradwilson** [comment]
A general note: The .NET Core team is going to have to figure out how to solve these kinds of issues in a non-breaking way if they want to have any kind of backward compatibility.

> The Microsoft.Extensions.DependencyModel package uses PlatformAbstractions as a dependency starting 1.1.0. Since it supports netstandard1.3, could xunit.runner.visualstudio.dotnetcore refer this version of DependencyModel?

If we refer to the 1.1.0 DependencyModel package, does that now preclude us from running on .NET Core 1.0? If the answer is "yes", then my answer is "no".

**Comment by onovotny** [comment]
@bradwilson looking at that package, as far as I can tell, it's "just" a netstandard1.3, 1.6 and net451 package. The 1.0 version was net451 and 1.6, so 1.1 added a 1.3 version. There's no specific netcoreapp runtime components to it, other than simply being included by Microsoft.NetCore.App by default.

I don't see any reason why the 1.1 package wouldn't work on both.
