### ISSUE TITLE
Add void Write(string) to ITestOutputHelper

### ISSUE THREAD

**Issue by siegfriedpammer** [xunit/xunit#1082]
Please add `void Write(string)` to`ITestOutputHelper` to make it more flexible.

**Comment by bradwilson** [comment]
The API for communication requires test output to be communicated in full lines. So this feature request would buffer output, waiting for `\r\n` pairs before sending the information.

Is this still what you want?

**Comment by siegfriedpammer** [comment]
I am only interested in full lines, so I would not mind. But I am already using StringBuilder as a workaround, so my use case does no longer exist. This was just a suggestion, because all the other Text-IO-APIs in .NET feature Write as well as WriteLine.

**Comment by bradwilson** [comment]
Closed for age.
