### ISSUE TITLE
Unable to discover test in Visual Studio with latest xunit.extensibility.execution package

### ISSUE THREAD

**Issue by genlu** [xunit/xunit#1083]
With `xunit.extensibility.execution, version="2.2.0-beta6-build3477`, run test in VS no longer works (I'm using VS 2017 RC). Here's the output from a desktop test project:

```
------ Discover test started ------
[xUnit.net 00:00:00.1168722] Skipping: ClassLibrary1 (Could not find any of the following assemblies: xunit.execution.desktop.dll)
========== Discover test finished: 0 found (0:00:01.024) ==========
```

**Comment by bradwilson** [comment]
Can you provide the repro project? There are many unaccounted for variables that would be easy to discover with a repro.

**Comment by genlu** [comment]
Sure, here you go:
https://1drv.ms/f/s!AkbPBE3d3Hv-hLoYgtYG-vuzlxJtNQ

It's just a desktop class template project with references to Xunit packages. And if you downgrade them from 2.2.0-beta6-build3477 to 2.2.0-beta5-build3474, everything will work again. 
As far as I can tell, `xunit.execution.desktop.dll` was recently removed from `xunit.extensibility.execution` package, which might be related.

**Comment by bradwilson** [comment]
I just upgraded to the latest build and things appear to be working again:

```xml
  <package id="xunit" version="2.2.0-beta6-build3501" targetFramework="net452" />
  <package id="xunit.abstractions" version="2.0.1" targetFramework="net452" />
  <package id="xunit.assert" version="2.2.0-beta6-build3501" targetFramework="net452" />
  <package id="xunit.core" version="2.2.0-beta6-build3501" targetFramework="net452" />
  <package id="xunit.extensibility.core" version="2.2.0-beta6-build3501" targetFramework="net452" />
  <package id="xunit.extensibility.execution" version="2.2.0-beta6-build3501" targetFramework="net452" />
  <package id="xunit.runner.visualstudio" version="2.2.0-beta6-build1243" targetFramework="net452" developmentDependency="true" />
```

**Comment by genlu** [comment]
Yes, I can confirm `xunit.execution.desktop.dll` is added back to the package, which fixed the issue. Thanks

**Comment by Joebeazelman** [comment]
I have the same issue using the UWP project template.  During the discover, it couldn't find xunit.execution.desktop.dll.  I cannot change the project to 4.5.2 and I have it installed on my system.
