### ISSUE TITLE
xunit.runner.visualstudio.testadapter is not strong-named assembly

### ISSUE THREAD

**Issue by smadala** [xunit/xunit#1086]
`Assembly.GetTypes()` failing for xunit.runner.visualstudio.testadapter with `System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.`

**Comment by bradwilson** [comment]
Fixed by https://github.com/xunit/visualstudio.xunit/commit/e35c4cd82b479f236903c5fec5033af8d410800e
