### ISSUE TITLE
Get a warning when build xunit project in VS2017RC: Found conflicts between different versions of the same dependent assembly that could not be resolved.

### ISSUE THREAD

**Issue by zwcloud** [xunit/xunit#1091]
I just create a new xunit text project by 

![devenv_2017-02-08_12-06-12](https://cloud.githubusercontent.com/assets/6965758/22723231/a2219d58-edf7-11e6-8173-5f6ee42ace73.png)

Then build it and get a warning:
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1912,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.

The relevant detailed log is

> 1>    Dependency "Microsoft.Extensions.DependencyModel, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60".
> 1>        Could not resolve this reference. Could not locate the assembly "Microsoft.Extensions.DependencyModel, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
> 1>            For SearchPath "C:\Users\cloud\.nuget\packages\microsoft.testplatform.testhost\15.0.0-preview-20170106-08\lib\netstandard1.5".
> 1>            Considered "C:\Users\cloud\.nuget\packages\microsoft.testplatform.testhost\15.0.0-preview-20170106-08\lib\netstandard1.5\Microsoft.Extensions.DependencyModel.winmd", but it didn't exist.
> 1>            Considered "C:\Users\cloud\.nuget\packages\microsoft.testplatform.testhost\15.0.0-preview-20170106-08\lib\netstandard1.5\Microsoft.Extensions.DependencyModel.dll", but it didn't exist.
> 1>            Considered "C:\Users\cloud\.nuget\packages\microsoft.testplatform.testhost\15.0.0-preview-20170106-08\lib\netstandard1.5\Microsoft.Extensions.DependencyModel.exe", but it didn't exist.
> 1>            For SearchPath "{CandidateAssemblyFiles}".
> 1>            Considered "C:\Users\cloud\.nuget\packages\xunit.runner.visualstudio\2.2.0-beta5-build1225\build\netcoreapp1.0\xunit.runner.visualstudio.dotnetcore.testadapter.dll",
> 1>    			but its name "xunit.runner.visualstudio.dotnetcore.testadapter"
> 1>    			didn't match the expected name "Microsoft.Extensions.DependencyModel, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60".
> 1>            Considered "C:\Users\cloud\.nuget\packages\xunit.runner.visualstudio\2.2.0-beta5-build1225\build\netcoreapp1.0\xunit.runner.utility.dotnet.dll",
> 1>    			but its name "xunit.runner.utility.dotnet"
> 1>    			didn't match the expected name "Microsoft.Extensions.DependencyModel, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60".
> 1>            Considered "C:\Users\cloud\.nuget\packages\xunit.runner.visualstudio\2.2.0-beta5-build1225\build\netcoreapp1.0\xunit.runner.reporters.dotnet.dll",
> 1>    			but its name "xunit.runner.reporters.dotnet"
> 1>    			didn't match the expected name "Microsoft.Extensions.DependencyModel, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60".
> 1>        Required by "C:\Users\cloud\.nuget\packages\microsoft.testplatform.testhost\15.0.0-preview-20170106-08\lib\netstandard1.5\testhost.dll".
> 1>        Required by "C:\Users\cloud\.nuget\packages\microsoft.testplatform.testhost\15.0.0-preview-20170106-08\lib\netstandard1.5\Microsoft.TestPlatform.CrossPlatEngine.dll".
> 1>    There was a conflict between "Microsoft.Extensions.DependencyModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" and "Microsoft.Extensions.DependencyModel, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60".
> 1>        "Microsoft.Extensions.DependencyModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" was chosen because it was primary and "Microsoft.Extensions.DependencyModel, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" was not.
> 1>        References which depend on "Microsoft.Extensions.DependencyModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" [C:\Users\cloud\.nuget\packages\microsoft.extensions.dependencymodel\1.0.0\lib\netstandard1.6\Microsoft.Extensions.DependencyModel.dll].
> 1>            C:\Users\cloud\.nuget\packages\microsoft.extensions.dependencymodel\1.0.0\lib\netstandard1.6\Microsoft.Extensions.DependencyModel.dll
> 1>              Project file item includes which caused reference "C:\Users\cloud\.nuget\packages\microsoft.extensions.dependencymodel\1.0.0\lib\netstandard1.6\Microsoft.Extensions.DependencyModel.dll".
> 1>                C:\Users\cloud\.nuget\packages\microsoft.extensions.dependencymodel\1.0.0\lib\netstandard1.6\Microsoft.Extensions.DependencyModel.dll
> 1>        References which depend on "Microsoft.Extensions.DependencyModel, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" [].
> 1>            C:\Users\cloud\.nuget\packages\microsoft.testplatform.testhost\15.0.0-preview-20170106-08\lib\netstandard1.5\Microsoft.TestPlatform.CrossPlatEngine.dll
> 1>              Project file item includes which caused reference "C:\Users\cloud\.nuget\packages\microsoft.testplatform.testhost\15.0.0-preview-20170106-08\lib\netstandard1.5\Microsoft.TestPlatform.CrossPlatEngine.dll".
> 1>                C:\Users\cloud\.nuget\packages\microsoft.testplatform.testhost\15.0.0-preview-20170106-08\lib\netstandard1.5\testhost.dll
> 1>                C:\Users\cloud\.nuget\packages\microsoft.testplatform.testhost\15.0.0-preview-20170106-08\lib\netstandard1.5\Microsoft.TestPlatform.CrossPlatEngine.dll
> 1>    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1912,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
> 1>  Done executing task "ResolveAssemblyReference".

Environment:

> Microsoft Visual Studio Community 2017 RC
> Version 15.0.26127.3 D15SVC
> Microsoft .NET Framework
> Version 4.6.01586

A project that can reproduce the issue on VS2017RC:
[XUnitTestProject1.zip](https://github.com/xunit/xunit/files/759704/XUnitTestProject1.zip)

**Comment by bradwilson** [comment]
Please try using a [CI build from MyGet](http://myget.org/gallery/xunit).

**Comment by bradwilson** [comment]
Fixed by https://github.com/xunit/visualstudio.xunit/commit/72295787b3e3a5f5658bd9ac634ba9152f022d43
