### ISSUE TITLE
Asp.net Core 1.1 integration Problem

### ISSUE THREAD

**Issue by aammfe** [xunit/xunit#1092]
> Severity	Code	Description	Project	File	Line	Suppression State
> Error		Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1) / win. Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)			0	
> 

i m having upper mentioned issue , trying to add reference of core1.1 app to xunit project , using VS 2017 RC .
> now "project.json" has converted in to csproj
 
how i can use it..?

**Comment by bradwilson** [comment]
Can you provide a repro project?

**Comment by aammfe** [comment]
using VS 2017Rc
1-New Project in .NetCore 1.1
2-Add XUnit Project
Reference 1frst Project to XUnit Project
and below error appears 
[Image](http://prntscr.com/e9d2cn)


[project](https://we.tl/SboTfYuZ4w)

**Comment by bradwilson** [comment]
I was able to make this work by doing the following:

1. Create new ASP.NET Core 1.1 Project
2. Create new Xunit Test .NET Core Project
    1. Convert test project to .NET Core 1.1 (it defaults to 1.0)
    2. Upgrade NuGet packages (as illustrated below)
3. Create reference in test project to ASP.NET Core Project

Everything compiles as expected, tests are discovered correctly.

![repro](https://cloud.githubusercontent.com/assets/16944/23019982/b4227b50-f3f9-11e6-9ddf-02064c514820.png)

**Comment by aammfe** [comment]
👍 thanx

**Comment by bdparrish** [comment]
I am having the same issue as @aammfe with the same 5 output lines when running a .NET Core Web Application in the new download of VS 2017 from yesterday.  Chrome starts up and says my application is starting, but then it terminates and the output on has the following.

> code:-32000
> message:No script for id: 31
> The program '[19664] dotnet.exe' has exited with code -2147450749 (0x80008083).
> The program '[13976] chrome.exe: WebKit' has exited with code -1 (0xffffffff).
> The program '[16048] iisexpress.exe' has exited with code 0 (0x0).

**Comment by aammfe** [comment]
In my case some how .netcore1.1 was missing ,after installing lastest version of .netcore , it solved

**Comment by fred2u** [comment]
Thanks, after installing both (x86) and (x64) version of .netcore, it works for me too (https://www.microsoft.com/net/download/core)

**Comment by MNF** [comment]
I fixed the error by adding to .csproj
` <PackageTargetFallback>$(PackageTargetFallback);dotnet5.6;portable-net45+win8</PackageTargetFallback> 
`
as suggested in http://stackoverflow.com/questions/40846326/the-dependency-microsoft-composition-1-0-27-does-not-support-framework-netcorea/42973648#42973648

**Comment by bradwilson** [comment]
Closed for age.
