### ISSUE TITLE
Unit tests are not observable in Test Explorer with custom BaseIntermediateOutputPath

### ISSUE THREAD

**Issue by alexanderkozlenko** [xunit/xunit#1101]
Unit tests are not observable in Test Explorer when a custom path is specified for the `BaseIntermediateOutputPath` property.

Steps to reproduce:

1. Create new "xUnit Test Project (.NET Core)".
2. Update Microsoft.NET.Test.Sdk and xUnit packages to the latest versions.
3. Build the project and observe one unit test in Test Explorer ("Test1").
4. Add the following code to the project file as a first child of `Project` element:

```
<PropertyGroup>
   <BaseIntermediateOutputPath>..\obj\</BaseIntermediateOutputPath>
</PropertyGroup>
```
5. Close Visual Studio and delete  `.vs`, `bin`, and `obj` directories.
6. Open Visual Studio, build the project, and observe zero tests in Test Explorer.

Microsoft Visual Studio 15.0.0-RC.4+26206.0
Microsoft.NET.Test.Sdk 15.0.0-preview-20170125-04
xunit 2.2.0-rc1-build3507
xunit.runner.visualstudio 2.2.0-rc1-build1247

[XUnitTestProject1.zip](https://github.com/xunit/xunit/files/769261/XUnitTestProject1.zip)

**Comment by bradwilson** [comment]
This should be reported here: https://github.com/Microsoft/vstest/issues/

Nothing that xUnit.net does has anything to do with the `obj` folder.

**Comment by bradwilson** [comment]
Closed for age.
