### ISSUE TITLE
xUnit 2.2.0-rc1-build3507 package not working in .NET 4.5.1 test runs

### ISSUE THREAD

**Issue by dougbu** [xunit/xunit#1102]
With move from xUnit 2.2.0-beta5-build3474 to 2.2.0-rc1-build3507, .NET 4.5.1 runs no longer discover or execute tests.

E.g.
1. create a new xUnit Test Project (.NET Core) in Visual Studio 2017
2. add the target framework `net451` to the project:
  ``` xml
  <TargetFrameworks>net451;netcoreapp1.0</TargetFrameworks>
  ```
3. restore, build and test on the command line
  a. `dotnet restore`
  b. `dotnet build`
  c. `dotnet test --no-build --framework net451`
  - everything works as expected
4. update xunit.runner.visualstudio to latest version (2.2.0-rc1-build1247)
5. restore, build and test on the command line
  - everything works as expected
6. update Microsoft.NET.Test.Sdk to latest version (15.0.0-preview-20170210-02)
7. restore, build and test on the command line
  - everything works as expected
8. update xUnit package to latest version (2.2.0-rc1-build3507)
9. restore, build and test on the command line
  - expected: everything works
  - actual:
  ```
  Starting test execution, please wait...
  Warning: No test is available in C:\...\XUnitTestProject3\bin\Debug\net451\XUnitTestProject3.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
  ```

Note: .NET 4.5.2 runs (e.g. `<TargetFramework>net452</TargetFramework>`) work correctly with the same packages.

**Comment by antrv** [comment]
I think the reason is that the last xUnit version 2.2.0-rc1-build3507 is not compatible with .net core 1.0.0 and 1.0.1.

**Comment by onovotny** [comment]
.NET 4.5.1 is obsolete and unsupported by Microsoft. .NET 4.5.2 is the minimum version with support. Your unit tests need to be for .NET 4.5.2 but they can still reference .NET 4.5 libraries (as per normal referencing rules).

**Comment by dougbu** [comment]
Well, we on the ASP.NET Core team were still testing against .NET 4.5.1. But, we'll stop now.

**Comment by zdravkov** [comment]
The error at our side was "Make sure that installed test discoverers & executors,
 platform & framework version settings are appropriate and try again." and updating from net451 to net452 solved the issue.
