### ISSUE TITLE
xunit.runner.visualstudio 2.2.0-rc1-build1247 causes dotnet.exe to crash with .net core 1.0.1

### ISSUE THREAD

**Issue by antrv** [xunit/xunit#1103]
The dotnet.exe (.net core 1.0.0 and .net core 1.0.1) crashes with the last xunit.runner.visualstudio version 2.2.0-rc1-build1247:

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.InternalAbstractions, Version=1.0.0.
0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
   at Xunit.Runner.DotNet.Program.GetAvailableRunnerReporters()
   at Xunit.Runner.DotNet.Program.Run(String[] args)
   at Xunit.Runner.DotNet.Program.Main(String[] args)
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.

Possibly the nuget package has no dependency to Microsoft.DotNet.InternalAbstractions.

**Comment by bradwilson** [comment]
If you upgraded the runner, you probably need to shutdown and restart Visual Studio in order for it to pick up the new runner (alternatively, use Task Manager to find the VSTest discoverer executable and terminate it).

**Comment by antrv** [comment]
Even restarting computer does not help.
'dotnet test' command running from command line also shows that exception.
If I put the older version of xunit.runner.visualstudio package in project.json, then no exception.
After upgrading to the latest version the exception appears again.
The same issue is repeated on several computers (win 10, win 2012 r2 server).

**Comment by bradwilson** [comment]
I've just pushed an RC2 build. Please retry with that build and see if the problem is resolved. We took an explicit dependency on PlatformAbstractions which I think should prevent this (IMO, broken) downgrade behavior from NuGet.

**Comment by antrv** [comment]
The same issue is repeated with RC2

**Comment by bradwilson** [comment]
Can you provide a repro project? I'm not able to repro locally.

**Comment by antrv** [comment]
https://github.com/antrv/XunitIssue1103

**Comment by antrv** [comment]
just do from cmdl:
cd XunitIssue1103/XunitIssue1103.Tests
dotnet test

**Comment by bradwilson** [comment]
Unfortunately, we are not planning on fixing any issues with `project.json`-based .NET Core projects, because they will never be officially supported.

**Comment by bradwilson** [comment]
Closed for age.
