### ISSUE TITLE
Allow for assembly setup and teardown

### ISSUE THREAD

**Issue by giggio** [xunit/xunit#111]
Similar to what is find in `AssemblyInitialize` for MsTest or `SetUpFixture` in NUnit, allow some code to run before any test in a specific assembly run, and after all of them have ran.

The main reason to ask for that is because of integration tests, where we usually need to do some preparation on the environment before any tests can run, like write some files, migrate a DB, bring up a web server, etc. And to clear it all up at the end.

Also, it is very hard to migrate from other framework that already support this.

I am aware that there are workarounds. I understand that it is possible to create some static class with a static constructor and call it somehow, or maybe have all test classes inherit from a base test class and do the setup there. But this means have to mix setup concerns with test concerns, which is not good design. Also, again, it is a lot of work when migrating from some other framework and you have hundreds of tests.

**Comment by ewilde** [comment]
@bradwilson I struggling to enable some scenarios without this kind of feature. Here is what i do with nunit during an integration test.

```
[SetUpFixture]
    public class RunOncePerNamespace
    {
        [SetUp]
        public void Setup()
        {
           // Setup databases and services
        }

        [TearDown]
        public void TearDown()
        {
            // Shutdown databases and services
        }
    }
```

What are the workarounds in `xunit` the enable this type of thing ? Care to share why you opted out of doing this?

**Comment by athinboy** [comment]
@ewilde @bradwilson 
I think ewilde is reasonable!  
Can you give us a why ?
