### ISSUE TITLE
The reason why the test run was aborted is not indicated.

### ISSUE THREAD

**Issue by zwcloud** [xunit/xunit#1111]
## Environment
VS2017RC

    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170210-02" />
    <PackageReference Include="xunit" Version="2.2.0-rc2-build3523" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0-rc2-build1249" />

## Repro

```CSharp
using Xunit;

namespace XUnitTestProject1
{
    public class UnitTest1
    {
        public class Class1
        {
            public static bool Fun()
            {
                Fun();
                return true;
            }
        }

        [Fact]
        public void Test1()
        {
            Assert.True(Class1.Fun());
        }
    }
}

```

The output just prints:

> ------ Discover test started ------
> [xUnit.net 00:00:01.1107388]   Discovering: XUnitTestProject1
> [xUnit.net 00:00:01.3233828]   Discovered:  XUnitTestProject1
> ========== Discover test finished: 1 found (0:00:02.253) ==========
> ------ Run test started ------
> [xUnit.net 00:00:00.9959544]   Starting:    XUnitTestProject1
> The active Test Run was aborted.
> ========== Run test finished: 0 run (0:00:04.260) ==========

It's better to let the user know why the test run was aborted. In my case, may be showing something like _Process is terminated due to StackOverflowException._ That's what dotnet core console app have done:
After `Class1.Fun()` was called in a console app, the console showed that message:
![devenv_2017-02-14_23-09-26](https://cloud.githubusercontent.com/assets/6965758/22934809/48c952aa-f30b-11e6-99df-16ddf851b80a.png)

**Comment by bradwilson** [comment]
That message is outside of our control. This bug belongs in the VSTest repository: https://github.com/Microsoft/vstest/issues/

**Comment by zwcloud** [comment]
@bradwilson Thanks for your reply! I have report this to vstest.

**Comment by bradwilson** [comment]
Closed for age.
