### ISSUE TITLE
"no source available" when targeting net462

### ISSUE THREAD

**Issue by attilah** [xunit/xunit#1112]
When I create a new xUnit test project in VS2017 RC4 (or newer), test Explorer cannot show the source code for any of the tests. When targeting netcoreapp1.1 (which is there by default in the template, it works as expected.

csproj file
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170125-04" />
    <PackageReference Include="xunit" Version="2.2.0-beta5-build3474" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0-beta5-build1225" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>

</Project>
```

UnitTest1.cs file:
```
using System;
using Xunit;

namespace XUnitTestProject1
{
    public class UnitTest1
    {
        [Fact]
        public void Test1()
        {
        }
    }
}
```

**Comment by bradwilson** [comment]
Please re-test with the RC2 builds for `xunit` and `xunit.runner.visualstudio`.

**Comment by attilah** [comment]
I've updated all the packages to latest prerelease versions:

```
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170210-02" />
    <PackageReference Include="xunit" Version="2.2.0-rc2-build3523" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0-rc2-build1249" />
```

The issue still presents itself.

**Comment by bradwilson** [comment]
I'm able to reproduce this, and it appears that you cannot use the new-style CSProj files with just a desktop framework, because it appears that it implies .NET Core. If you create an old-style CSProj `net462` class library and add `xunit` and `xunit.runner.visualstudio`, this does work.

This feels like a bug in VSTest, and should maybe be reported there: https://github.com/Microsoft/vstest/issues/

**Comment by onovotny** [comment]
I've filed an issue here https://github.com/Microsoft/vstest/issues/523

**Comment by attilah** [comment]
We still have this with VS 15.3 and xUnit latest beta :-(

**Comment by bradwilson** [comment]
Make sure you generating "full" debug symbols (and not "portable").

**Comment by attilah** [comment]
Thanks, I'm confirming it and getting back to you after, meanwhile I found in other places this tip. Everything is connected within VS...

**Comment by nebosite** [comment]
I set both my test project and my product builds to output "full" debug symbols and i am still having this problem with VS 15.3.5.  Any other Ideas?

**Comment by bradwilson** [comment]
xUnit.net will do this for you by default, assuming you're using 2.3 beta 3 or later:

https://github.com/xunit/xunit/blob/6b58a2a983de6c7d590d2533341afb25807a0323/src/xunit.core/build/xunit.core.props#L8-L23

**Comment by nebosite** [comment]
Ah.  I think I created this project a while back with an earlier version of xUnit.

**Comment by bradwilson** [comment]
Closed for age.
