### ISSUE TITLE
xunit.runner.msbuild for .NET Core

### ISSUE THREAD

**Issue by natemcmaster** [xunit/xunit#1114]
To distinguish, there are two runtimes to consider: MSBuild's runtime and the test app's runtime. 

1. MSBuild's runtime. dotnet-msbuild runs on .NET Core, MSBuild.exe runs on .NET framework.  Supporting for the MSBuild task assembly on .NET Core would make it possible to build projects using MSBuild 15 from either MSbuild.exe or dotnet.exe. This can be done by cross-compiling the task library for .NET Standard 1.3 and .NET Framework 4.6 (Here's [one example](https://github.com/aspnet/BuildTools/blob/63fe2164664d5ea514c4c7e46cfd1516dbcdc409/src/Internal.AspNetCore.BuildTools.Tasks/Internal.AspNetCore.BuildTools.Tasks.nuspec)).

2. Test app's runtime. Support for running .NET Core test assemblies. Would be awesome if the MSBuild runner could be used to launch a .NET Core test project.

**Comment by bradwilson** [comment]
You're just trying to keep me busy, aren't you. 😛

**Comment by borgdylan** [comment]
Ideally this should not depend on the .net core msbuild being present for mono/desktop .net support.

**Comment by bradwilson** [comment]
@borgdylan The existing desktop CLR MSBuild runner is what you'd use for Mono.

**Comment by borgdylan** [comment]
But is it tied to a specific MSBuild version earlier than 15.0? The new msbuild requires tasks to be compiled against its nuget packages and delivers no libraries into the GAC.

**Comment by bradwilson** [comment]
No, it's not tied to a specific version.
