### ISSUE TITLE
use [DebuggerStepThrough] Attribute and [DebuggerNonUserCode]

### ISSUE THREAD

**Issue by aclarke6** [xunit/xunit#1115]
use [DebuggerStepThrough] Attribute and [DebuggerNonUserCode]
on XUnit code so that it instructs the debugger to step through XUnit's code instead of stepping into it.

**Comment by bradwilson** [comment]
We ship symbols and source precisely so that developers can step into the code if they need to.

If you don't want to step in, don't step in. ;)

**Comment by aclarke6** [comment]
Unfortunately, if a developer has not gone to GitHug and downloaded the source and attached it to his Solution, VS repeatedly complains about missing source. If a developer has an unexpected exception thrown within his own code, he ends up stepping out, and into XUnit code without a choice.

I guess that option of having the source to step through is wonderful for few developers who are looking at XUnit code in the source, but those of us who just grab the NuGet packages to work on our own code, which may be buggy, often jump into XUnit code through an exception in our own code and do this unintentionally. We don't have the source code, so Visual Studio tries and fails to locate the source for XUnit and VS pops up a really annoying dialog asking for the developer to locate the XUnit code he doesn't have, and then it repeats this frequently.

It would be possible to surround the two attributes with a #IF DEBUG ... #ENDIF so that those wishing to develop XUnit can do so freely, and those just using XUnit modules from NuGet are not inconvenienced.

Personally, I'd regard that as the best of both worlds. If you wish to enter the XUNit code to see good code, you can. If you just wish to use a tool downloaded from NuGet, then you can.

**Comment by bradwilson** [comment]
Closed for age.

**Comment by jnm2** [comment]
@aclarke6 I'd recommend leaving Debug > Options > Enable Just My Code on for this reason. (https://docs.microsoft.com/en-us/visualstudio/debugger/just-my-code)

For when I do turn it off, I always have Debug > Options > Symbols > 'Load only specified modules.' You can add to the list right there, but I usually add to the list by right-clicking the call stack or Modules view when debugging and selecting 'Always load symbols automatically'.
