### ISSUE TITLE
Tests not automatically reported in TeamCity after update to RC4 tooling

### ISSUE THREAD

**Issue by martincostello** [xunit/xunit#1116]
Using .NET SDK ```1.0.0-rc4-004788``` with xunit ```2.2.0-rc3-build3528``` xunit tests are no longer reported automatically as part of a TeamCity build when run in a PowerShell script with ```dotnet test <project>```.

Does this need to be manually configured now with the move to MSBuild, or should this still "just work"?

**Comment by onovotny** [comment]
do you see a .reporters.* dll file in your output directory?

**Comment by martincostello** [comment]
I see these files for xunit in the build Artifacts:

![image](https://cloud.githubusercontent.com/assets/1439341/23037132/344255a2-f47d-11e6-9834-52b897eefd54.png)

**Comment by martincostello** [comment]
Test-related references are:

```xml
<PackageReference Include="Microsoft.AspNetCore.TestHost" Version="1.1.0" />
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170106-08" />
<PackageReference Include="xunit" Version="2.2.0-rc3-build3528" />
<PackageReference Include="xunit.runner.visualstudio" Version="2.2.0-rc3-build1252" />
```

**Comment by daviwil** [comment]
My tests also stopped reporting on AppVeyor after switching to RC4.  One thing I've noticed is that I got `xunit.runner.reporters.desktop.dll` in the test assembly's output folder when building with RC3 but after changing to RC4 I get `xunit.runner.reporters.net452.dll`.

**Comment by martincostello** [comment]
Actually, I'm also getting this with AppVeyor; I just hadn't noticed. Interestingly the _count_ is correct, but the xunit tests' names are not listed:.

  1. [Older build, 24 tests, all appear in list](https://ci.appveyor.com/project/martincostello/website/build/1.0.239/tests)
  1. [Latest build, 24 tests but xunit tests not listed](https://ci.appveyor.com/project/martincostello/website/build/tests)

**Comment by bradwilson** [comment]
We have a test project that includes desktop tests run via Console, run via MSBuild, and .NET Core tests run via `dotnet test`: https://github.com/xunit/appveyor-validation.xunit

And after a bug fix for .NET Core, I am seeing all results in AppVeyor: https://ci.appveyor.com/project/BradWilson/appveyor-validation-xunit/build/1.0.23/tests

**Comment by martincostello** [comment]
@bradwilson 👍 I'll try updating to the bits you've referenced above and see what I get. I think I've also nearly got a repro for #1117 ready too.

**Comment by bradwilson** [comment]
@martincostello Simulating TeamCity auto-detection behavior, I can see that the TeamCity output is present: https://gist.github.com/bradwilson/7e902619af8e4da060838ed34b11b9fa

**Comment by martincostello** [comment]
@bradwilson I'll update to the latest xunit bits on Monday for my work project that goes through TeamCity and check whether it's resolved. My AppVeyor build still isn't reporting the tests in the build log pane, but it [looks like there's an error occurring when it posts to AppVeyor](https://ci.appveyor.com/project/martincostello/website/build/1.0.274#L1303). Encoding issue maybe because I have paths/MIME types as inline data input to a ```[Theory]```?

```powershell
Warning: [xUnit.net 00:00:03.4739184] When sending 'POST http://localhost:1031/api/tests/batch', received status code 'BadRequest'; request body: [{"testName":"Can_Load_Resource(requestUri: \\"/home/about\\", contentType: \\"text/html\\")","testFramework":"xUnit","fileName":"Website.Tests.dll","outcome":"Running"}]
```

**Comment by martincostello** [comment]
Looks like the test name is being escaped incorrectly when it's converted to JSON.

| | Value |
|--|--|
| Name | ```Can_Load_Resource(requestUri: "/home/about", contentType: "text/html")``` |
| Expected | ```"Can_Load_Resource(requestUri: \"/home/about\", contentType: \"text/html\")"``` |
| Actual | ```"Can_Load_Resource(requestUri: \\"/home/about\\", contentType: \\"text/html\\")"``` |

**Comment by martincostello** [comment]
I've updated to xunit 2.2.0 in my Team City build and it's still not reporting the results through to Team City for the xunit tests, though it is for some PhantomJS tests in the build. It looks like the auto-detection is failing as I can't see the special output format in the logs.

**Comment by martincostello** [comment]
I think the Team City issue was actually an issue in the test SDK. After updating to ```15.0.0-preview-20170217-05``` the xunit results re-appeared.

**Comment by JamesFenton** [comment]
I'm having the same issue with Microsoft.NET.Test.Sdk v15.0.0 and XUnit v2.2.0, but only when targeting .Net Framework 4.6. 

When target .net core (after running `dotnet new xunit`), I get TeamCity test results:
```
PS C:\Temp> $env:TEAMCITY_PROJECT_NAME = "foo"
PS C:\Temp> dotnet test
Build started, please wait...
Build completed.

Test run for C:\Temp\bin\Debug\netcoreapp1.1\Temp.dll(.NETCoreApp,Version=v1.1)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.7228998] ##teamcity[testSuiteStarted name='Test collection f
or Temp.UnitTest1 (1)' flowId='ba43300101aa431480ba4dd45f401e26']
[xUnit.net 00:00:00.7696587] ##teamcity[testStarted name='Temp.UnitTest1.Test1'
flowId='ba43300101aa431480ba4dd45f401e26']
[xUnit.net 00:00:00.8003461] ##teamcity[testFinished name='Temp.UnitTest1.Test1'
 duration='5' flowId='ba43300101aa431480ba4dd45f401e26']
[xUnit.net 00:00:00.8142548] ##teamcity[testSuiteFinished name='Test collection
for Temp.UnitTest1 (1)' flowId='ba43300101aa431480ba4dd45f401e26']

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.8679 Seconds
```

But when I change the `TargetFramework` to `net46` I get the following:
```
PS C:\Temp> $env:TEAMCITY_PROJECT_NAME = "foo"
PS C:\Temp> dotnet test
Build started, please wait...
Build completed.

Test run for C:\Temp\bin\Debug\net46\Temp.dll(.NETFramework,Version=v4.6)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.3655305]   Discovering: Temp
[xUnit.net 00:00:00.5005984]   Discovered:  Temp
[xUnit.net 00:00:00.8716970]   Starting:    Temp
[xUnit.net 00:00:01.0364414]   Finished:    Temp

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.4920 Seconds
```

**Comment by macgyver76** [comment]
Same as @JamesFenton when targeting to `net461`.

**Comment by JamesFenton** [comment]
@macgyver76 I have found a workaround that I've explained on https://github.com/xunit/xunit/issues/1162
