### ISSUE TITLE
xunit tests reported as project "External" in Visual Studio 2017 RC

### ISSUE THREAD

**Issue by martincostello** [xunit/xunit#1117]
Using Visual Studio 2017 RC (```VisualStudio/15.0.0-RC.4+26206.0```) with xunit.runner.visualstudio ```2.2.0-rc3-build1252``` in a project with 3 test projects, either the tests from only one project are detected, and the project is reported as "External", or not tests are detected at all.

_Tests_ Output from Visual Studio:

```
------ Discover test started ------
[xUnit.net 00:00:01.3670755]   Discovering: MyProject.EndToEndTests
[xUnit.net 00:00:01.5238641]   Discovering: MyProject.UnitTests
[xUnit.net 00:00:01.4400179]   Discovering: MyProject.IntegrationTests
The active Test Discovery was aborted.
[xUnit.net 00:00:02.5821343]   Discovered:  MyProject.IntegrationTests
[xUnit.net 00:00:04.2581457]   Discovered:  MyProject.UnitTests
```

**Comment by onovotny** [comment]
Do you have any repro you can share? The integration project we have has tons of projects in it and we're not seeing that issue there. https://github.com/xunit/xunit.integration

**Comment by martincostello** [comment]
I'll try and hack down the private project to make a repo on Monday.

**Comment by seanterryoutlook** [comment]
I'm experiencing something similar, but I don't get the error message in test output that martincostello posted.
```
------ Discover test started ------
[xUnit.net 00:00:00.5400928]   Discovering: Echo.Core.Tests
[xUnit.net 00:00:00.5411517]   Discovering: Echo.Scheduler.Tests
[xUnit.net 00:00:00.6560845]   Discovered:  Echo.Scheduler.Tests
[xUnit.net 00:00:00.7298822]   Discovered:  Echo.Core.Tests
```
No tests are discovered when I have two xunit projects in my solution. If I remove either test project from the solution, everything works fine. I don't get the "External" reporting above.
I was using the same test runner, and have tried 2.2.0-rc4-build1270 as well.

**Comment by onovotny** [comment]
@seanterryoutlook is there a small repro you can share?

**Comment by martincostello** [comment]
@onovotny I thought I'd got a working repro for this with a project of my own, but since updating xunit to the version referenced in #1116 I can no longer reproduce it. I'll update my work project on Monday and see if that removes the issue too.

**Comment by bradwilson** [comment]
Closed for age.

**Comment by johndkane** [comment]
FWIW my *.sln Project Type GUIDs for new test projects started becoming different over time. Changing them to be the same Project Type GUID for all test projects in the solution fixed this issue for me.  Before the change, I was getting an "External" labeled node in Test Explorer for the latest added test project, whereas older test projects were rooted in Test Explorer on their respective namespaces instead as expected. 

What I found - While investigating the SLN file: all my older test projects had Project Type GUID  9A19103F-16F7-4668-BE54-9A1E7A4F7556 likely generated with the dotnet CLI tools of the time; whereas a new test project added using updated Visual Studio 2017 got a different Project Type GUID FAE04EC0-301F-11D3-BF4B-00C04F79EFBC.  The latest project is the one showing the "External" node. 

What I did - I made all Project Type GUIDs consistent (for all test projects) by changing the latest differing Project Type GUID to be the same as the other traditional ones.  After this change and reloading the solution in Visual Studio the "External" node in Test Explorer went away. 

When tracking down the issue I'd suggest reviewing Solution file Project Type GUIDs for the test projects. 

Before changing the solution file 
```
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "test-commonlib", "..\dotnet-commonlib\test-commonlib\test-commonlib.csproj", "{D5C80372-BBD3-4744-81A7-E1D579A6D42D}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "test-consoleapp", "test-consoleapp\test-consoleapp.csproj", "{13ECEF61-E591-4733-B4D4-C7E277ABCC3B}"
EndProject
```

After changing the solution file 
```
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "test-commonlib", "..\dotnet-commonlib\test-commonlib\test-commonlib.csproj", "{D5C80372-BBD3-4744-81A7-E1D579A6D42D}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "test-consoleapp", "test-consoleapp\test-consoleapp.csproj", "{13ECEF61-E591-4733-B4D4-C7E277ABCC3B}"
EndProject
```

**Comment by andylholloway** [comment]
@johndkane Thanks for the post. I had the exact same issue and changing the Project Type GUID fix it.
We have a solution that contains tests with the Project Type GUID:` 9A19103F-16F7-4668-BE54-9A1E7A4F7556`
I add an XUnitTest project using the Visual Studio project template which created a project with the Project Type GUID: `FAE04EC0-301F-11D3-BF4B-00C04F79EFBC`
By changing the new Project Type GUID to `9A19103F-16F7-4668-BE54-9A1E7A4F7556` the `External` node was removed. 

Should this issue be re-opened? 

Visual Studio 2017  v15.8.7
Test Project:
Microsoft.NET.Test.Sdk v15.9.0
xunit.runner.visualstudio v2.4.1
xunit v2.4.1
dotnet-xunit 2.3.1

**Comment by bradwilson** [comment]
This bug should be opened against Visual Studio. We have no control over that GUID.

**Comment by mad7art** [comment]
Adding following line to cproj and reloading solution in VS helped me to fix this issue:
<DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
