### ISSUE TITLE
Xunit extensibility points

### ISSUE THREAD

**Issue by SaltyDH** [xunit/xunit#1119]
In our migration from NUnit to Xunit I wanted to fill some of the missing functionality of our automated test strategy. I have forked and implemented some additional changes to the Xunit discovery and test case runner implementations that allow custom extension points in these parts of the platform.

I realise I've missed the boat for inclusion on the current Xunit release but I hope these can be considered for a future release. I don't believe I've implemented any breaking changes, mostly just exposing some members as protected visibility and extracting a couple of methods to provide easier class and method overriding opportunities.

Right, to the inclusions:

TestCaseRunners now expose:

+ [GenerateTestRunner](https://github.com/SaltyDH/xunit/commit/0418794bfff0914b9131bca7ff506524c4c659b8#diff-ef4168acf6803b51a4b784f14ce17301R136) protected method so that custom test runners can be specified.

+ [GenerateTest](https://github.com/SaltyDH/xunit/commit/0418794bfff0914b9131bca7ff506524c4c659b8#diff-ef4168acf6803b51a4b784f14ce17301R142) protected method so that custom test classes can be specified.

XunitTestFrameworkDiscoverer.cs:

+ [DiscovererTypeCache made protected](https://github.com/SaltyDH/xunit/commit/0418794bfff0914b9131bca7ff506524c4c659b8#diff-7fda4f9ad329b37fddbd205c55866508R24) This provides a way to override the standard TheoryAttribute and FactAttributes discovery process.

XunitTestCaseRunner.cs

+ [ProvideAdditionalTestInterceptions](
https://github.com/SaltyDH/xunit/commit/0418794bfff0914b9131bca7ff506524c4c659b8#diff-430f40b3ed6a13c66560687958d4e88fR137) provides a way for inheriting classes to register specific test interceptors.

Finally DiagnosticMessageSink readonly members are made protected so that inheriting classes don't have to store the same value in an additional field in the subclass.

An example of how these changes might be consumed into an Integration testing framework are available in my sample project here: https://github.com/SaltyDH/xunit/blob/example-autofac/samples/xunit.samples.autofac/UnitTest1.cs

Anyway, I hope that's enough to get the discussion going around these changes.

**Comment by SaltyDH** [comment]
The issue here: https://github.com/xunit/xunit/issues/1190 may be solved by the approach detailed in the original post above.

**Comment by SaltyDH** [comment]
A pull request for this: https://github.com/xunit/xunit/pull/1209

**Comment by bradwilson** [comment]
Closed for age.
