### ISSUE TITLE
Visual Studio Runner won't find tests if only xunit.core is used in a ASP.NET Core project in VS2017

### ISSUE THREAD

**Issue by DerAlbertCom** [xunit/xunit#1120]
In VS2017 RC.4  i created a new xUnit Test Project (file new project). Updated to the newest nugets of xunit (rc4).

The Sample Unit Tests is up an running.

Now i remove xunit, and added xunit.core, because i like FluentAssertions instead of xunit.assert.

The Visual Studio Test Runner won't find and run the sample unit test.

If i add xunit back again to the test project, then test is found and run by VS2017.

**Comment by bradwilson** [comment]
Fixed in https://github.com/xunit/visualstudio.xunit/commit/2e758f5eb879d71d435b7956f2397353b9915afc

Thanks!

**Comment by bradwilson** [comment]
You can validate using package version `2.2.0-rc5-build1271` from MyGet. Remember that when upgrading the Visual Studio runner package, you must shut down Visual Studio and restart it.
