### ISSUE TITLE
Running tests for Platform=x86 not working via "dotnet test"

### ISSUE THREAD

**Issue by nietras** [xunit/xunit#1123]
I'm trying to run xunit tests via `dotnet test` (and visual studio 2017 RC4) for different platforms e.g. x64 and x86. However, this fails with:
```
Test run for E:\oss\NativeInts\src\DotNetCross.NativeInts.Tests\bin\X86\Release\netcoreapp1.0\DotNetCross.NativeInts.Tests.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Warning: [xUnit.net 00:00:00.6399043] Skipping: DotNetCross.NativeInts.Tests (could not find dependent assembly 'DotNetCross.NativeInts.Tests, Version=0.0.0')

Warning: No test is available in E:\oss\NativeInts\src\DotNetCross.NativeInts.Tests\bin\X86\Release\netcoreapp1.0\DotNetCross.NativeInts.Tests.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
```
Using a command like:
```
dotnet test src/DotNetCross.NativeInts.Tests/DotNetCross.NativeInts.Tests.csproj -c Debug -v q /nologo /property:Platform=X86
```
Dotnet info:
```
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771
```
And packages are
```
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170210-02" />
    <PackageReference Include="xunit" Version="2.2.0-rc4-build3536" />
    <PackageReference Include="xunit.runner.console" Version="2.2.0-rc4-build3536" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0-rc4-build1270" />
  </ItemGroup>
```
I added `console` package to see if it helped, but it did not. I assume the `visualstudio` package is used when using `dotnet test`/`msbuild`.

This project is open source and can be found https://github.com/DotNetCross/NativeInts and is a work in progress (only supports windows build right now, try running `all.ps1`).

**Comment by ppekrol** [comment]
Hi,

today I've encountered a similar issue, but with 'old format' (VS2015 sln with xproj's).

I'm executing command as follows expecting it to run everything on win10-x86 runtime (I'm on Win10 x64)
```
dotnet test --framework netcoreapp1.1 --runtime win10-x86
```
but at the end it spawns x64 process
```
xUnit.net .NET CLI test runner (64-bit .NET Core win10-x64)
```

Am I doing something wrong or this is just not working?

**Comment by 6bee** [comment]
`dotnet test` seems to be able to discover the tests with `xUnit.net 2.2.0-beta5-build3474` but not with any later version (current is `xUnit.net 2.2.0`). And as I see the issue only exists for .NET Full while .NET Core ist just fine. 


Failing to discover tests with (net451 and 2.2.0-rc1-build3507 and later):
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>    
    <TargetFramework>net451</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170125-04" />
    <PackageReference Include="xunit" Version="2.2.0-rc1-build3507" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0-beta5-build1225" />
  </ItemGroup>

</Project>
```

Successfully discover tests with (net451 and 2.2.0-beta5-build3474):
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>    
    <TargetFramework>net451</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170125-04" />
    <PackageReference Include="xunit" Version="2.2.0-beta5-build3474" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0-beta5-build1225" />
  </ItemGroup>

</Project>
```

Successfully discover tests with (netcoreapp1.0 and 2.2.0-rc1-build3507 and later):
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>    
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170125-04" />
    <PackageReference Include="xunit" Version="2.2.0-rc1-build3507" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0-beta5-build1225" />
  </ItemGroup>

</Project>
```

Updating the other packages to their latest version has not impact.

**Comment by bradwilson** [comment]
If you want your tests to run in 32-bit, you must install and run the 32-bit dotnet.exe.

**Comment by nietras** [comment]
@bradwilson how do you then easily switch and test both of these e.g. both 32-bit and 64-bit both from Visual Studio and from command line?

**Comment by bradwilson** [comment]
You install both the 32- and 64-bit SDKs, then use a full path to dotnet.exe to pick which one to run (`Program Files` vs. `Program Files (x86)`).

**Comment by ceztko** [comment]
The bad news is that atm `& "C:\Program Files (x86)\dotnet\dotnet.exe" --list-sdks` shows no SDK even if x86 SDK is installed, and trying to run tests with the 32bit dotnet host results in error `The application 'test' does not exist`.

The good news is that the 64bit dotnet host is still able to recognize the architecture of the test assembly, and if it's marked to run on `x86`, as opposed to being `x64` or `Any CPU`, it will still support running 32 bit tests correctly.

**Comment by bradwilson** [comment]
@ceztko wrote:

> The bad news is that atm `& "C:\Program Files (x86)\dotnet\dotnet.exe" --list-sdks` shows no SDK even if x86 SDK is installed

That's not true for me. Perhaps your installation is broken and needs to be repaired (or removed & reinstalled).

![image](https://github.com/xunit/xunit/assets/16944/4c84fc92-646b-4347-8ded-8380d6df44ae)

**Comment by ceztko** [comment]
I see, in my case `dotnet --info` tells:

```
.NET SDKs installed:
  No SDKs were found.
```

Repairing the x86 SDK didn't work, and uninstalling and re-installing is problematic since the actual MSI package is refcounted by VisualStudio, so no true uninstalling happens. We'll, for now I'll keep this way: if I'll ever need x86 `dotnet` I will take some more strong measures. Anyway, commenting again on the original issue, since the 64 bit `dotnet` host is still able to spawn 32 bit test processes, maybe having a switch to enforce test executions in 32 bit, like it was possible with `VSTest.console.exe`, wouldn't be inappropriate.

**Comment by bradwilson** [comment]
As far as I know, Visual Studio (at least 2022) does not install an x86 SDK, and the x86 SDKs are separate from the x64 SDKs. I have three SDKs installed; two I installed by hand, and one is automatically installed (and moved forward over time) by Visual Studio. This is what I see in "Add or Remove Programs":

![image](https://github.com/xunit/xunit/assets/16944/d23e9208-521a-4a8a-9ba5-e2eb61158478)

**Comment by eXpl0it3r** [comment]
> If you want your tests to run in 32-bit, you must install and run the 32-bit dotnet.exe.

Maybe this was true in 2017, but since this lead me onto the wrong path, I wanted to add a response, so other travelers don't have to go down the same path.

You can use `--platform x86` to run with a different target platform, without having to install x86 of `dotnet` nor fight the `PATH` environment variable.

```
dotnet test MyTests.dll --platform x86
```

**Comment by bradwilson** [comment]
There is no `--platform` switch, perhaps you meant `--arch x86`?

**Comment by eXpl0it3r** [comment]
Maybe it's a vstest specific alias. Either way it works, so it's not like the switch doesn't exist at all, even if I can't find the necessary documention for it. 😄

I've found it mentioned here: https://github.com/microsoft/vstest/issues/2576

**Comment by bradwilson** [comment]
Ah, yeah, the command line switches for `dotnet test` and `dotnet vstest` are definitely quite different. :)
