### ISSUE TITLE
Unable to update or install XUnit 2.2.0 in a .net 4.6.2 project

### ISSUE THREAD

**Issue by SeanFarrow** [xunit/xunit#1127]
I am unable to install or update the main XUnit package in a .net 4.6.2 project. Iss this supported, or was this an oversight/should I be doing something I'm not? I'm running vs2013 for now, so it might be this that is causing the issue.
Cheers
Sean.

**Comment by onovotny** [comment]
.NET 4.6.2 is supported. What error are you getting?

**Comment by SeanFarrow** [comment]
Hi,

I’m getting the message that Xunit.core does not contain any assembly references or content files that are compatible with 4.6.2.
Cheers
Sean.

**Comment by onovotny** [comment]
What version of NuGet do you have installed?

**Comment by SeanFarrow** [comment]
The latest for vs2013, 2.12 I think.
This appears to be an issue around all the packages, core, assertions etc.
Wonder whether moving to vs2015 will help.
Cheers
Sean.

**Comment by onovotny** [comment]
Can you please verify the version in the Extensions and Updates window? I ask because 2.12 is supposed to have `netstandard` support and that's the underlying issue.

**Comment by SeanFarrow** [comment]
Hi,

Version installed 2.12.0.817.
VS2013 community.

**Comment by onovotny** [comment]
If you change your .net version to 4.5.2 or 4.6, does it work then? this seems like a NuGet bug

**Comment by SeanFarrow** [comment]
No, not at all, I can set allowedVersions for now, I just don’t want other upgrading things if it’s going to cause issues.
I’ll let you file a NuGet issue, just create a new class library and try installing XUnit, you will then run in to the problem.
This happens in vs2015 as well.

**Comment by onovotny** [comment]
I don't have VS 2013 installed and have no plans to, sorry. Just trying to identify where the issue is. Sorry to say that if it doesn't work, it's unlikely to get fixed. Microsoft is unlikely to release another NuGet for 2013.

I just tested in VS 2015 with a new .NET 4.6.2 class library. I then added xunit and it installed correctly:

```


Attempting to gather dependency information for package 'xunit.2.2.0' with respect to project 'ClassLibrary5', targeting '.NETFramework,Version=v4.6.2'
  GET https://api.nuget.org/v3/registration1-gz/xunit/index.json
  OK https://api.nuget.org/v3/registration1-gz/xunit/index.json 33ms
  GET https://api.nuget.org/v3/registration1-gz/xunit.assert/index.json
  GET https://api.nuget.org/v3/registration1-gz/xunit.core/index.json
  GET https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/FindPackagesById()?id='xunit.core'
  GET https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/FindPackagesById()?id='xunit.assert'
  OK https://api.nuget.org/v3/registration1-gz/xunit.assert/index.json 141ms
  OK https://api.nuget.org/v3/registration1-gz/xunit.core/index.json 155ms
  OK https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/FindPackagesById()?id='xunit.assert' 232ms
  GET https://api.nuget.org/v3/registration1-gz/xunit.extensibility.core/index.json
  GET https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/FindPackagesById()?id='xunit.extensibility.core'
  GET https://api.nuget.org/v3/registration1-gz/xunit.abstractions/index.json
  GET https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/FindPackagesById()?id='xunit.extensibility.execution'
  GET https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/FindPackagesById()?id='xunit.abstractions'
  GET https://api.nuget.org/v3/registration1-gz/xunit.extensibility.execution/index.json
  OK https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/FindPackagesById()?id='xunit.core' 262ms
  OK https://api.nuget.org/v3/registration1-gz/xunit.abstractions/index.json 117ms
  OK https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/FindPackagesById()?id='xunit.extensibility.core' 141ms
  OK https://api.nuget.org/v3/registration1-gz/xunit.extensibility.core/index.json 148ms
  OK https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/FindPackagesById()?id='xunit.abstractions' 148ms
  OK https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/FindPackagesById()?id='xunit.extensibility.execution' 235ms
  OK https://api.nuget.org/v3/registration1-gz/xunit.extensibility.execution/index.json 327ms
Total number of results gathered : 21
Gathering dependency information took 961.02 ms
Summary of time taken to gather dependencies per source :
C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\	-	24.38 ms
https://api.nuget.org/v3/index.json	-	1.31 sec
C:\dev\ClassLibrary5\packages	-	24.52 ms
https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/	-	1.11 sec
Attempting to resolve dependencies for package 'xunit.2.2.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'xunit.2.2.0'
Resolved actions to install package 'xunit.2.2.0'
Retrieving package 'xunit.abstractions 2.0.1' from 'nuget.org'.
Retrieving package 'xunit.assert 2.2.0' from 'nuget.org'.
Retrieving package 'xunit.extensibility.core 2.2.0' from 'nuget.org'.
Retrieving package 'xunit.extensibility.execution 2.2.0' from 'nuget.org'.
Retrieving package 'xunit.core 2.2.0' from 'nuget.org'.
Retrieving package 'xunit 2.2.0' from 'nuget.org'.
For adding package 'xunit.abstractions.2.0.1' to project 'ClassLibrary5' that targets 'net462'.
For adding package 'xunit.abstractions.2.0.1' to project 'ClassLibrary5' that targets 'net462'.
Adding package 'xunit.abstractions.2.0.1' to folder 'C:\dev\ClassLibrary5\packages'
Added package 'xunit.abstractions.2.0.1' to folder 'C:\dev\ClassLibrary5\packages'
Added reference 'xunit.abstractions' to project 'ClassLibrary5'.
Added package 'xunit.abstractions.2.0.1' to 'packages.config'
Added file 'packages.config' to project 'ClassLibrary5'.
Successfully installed 'xunit.abstractions 2.0.1' to ClassLibrary5
For adding package 'xunit.assert.2.2.0' to project 'ClassLibrary5' that targets 'net462'.
For adding package 'xunit.assert.2.2.0' to project 'ClassLibrary5' that targets 'net462'.
Adding package 'xunit.assert.2.2.0' to folder 'C:\dev\ClassLibrary5\packages'
Added package 'xunit.assert.2.2.0' to folder 'C:\dev\ClassLibrary5\packages'
Added reference 'xunit.assert' to project 'ClassLibrary5'.
Added package 'xunit.assert.2.2.0' to 'packages.config'
Successfully installed 'xunit.assert 2.2.0' to ClassLibrary5
For adding package 'xunit.extensibility.core.2.2.0' to project 'ClassLibrary5' that targets 'net462'.
For adding package 'xunit.extensibility.core.2.2.0' to project 'ClassLibrary5' that targets 'net462'.
Adding package 'xunit.extensibility.core.2.2.0' to folder 'C:\dev\ClassLibrary5\packages'
Added package 'xunit.extensibility.core.2.2.0' to folder 'C:\dev\ClassLibrary5\packages'
Added reference 'xunit.core' to project 'ClassLibrary5'.
Added package 'xunit.extensibility.core.2.2.0' to 'packages.config'
Successfully installed 'xunit.extensibility.core 2.2.0' to ClassLibrary5
For adding package 'xunit.extensibility.execution.2.2.0' to project 'ClassLibrary5' that targets 'net462'.
For adding package 'xunit.extensibility.execution.2.2.0' to project 'ClassLibrary5' that targets 'net462'.
Adding package 'xunit.extensibility.execution.2.2.0' to folder 'C:\dev\ClassLibrary5\packages'
Added package 'xunit.extensibility.execution.2.2.0' to folder 'C:\dev\ClassLibrary5\packages'
Added reference 'xunit.execution.desktop' to project 'ClassLibrary5'.
Added package 'xunit.extensibility.execution.2.2.0' to 'packages.config'
Successfully installed 'xunit.extensibility.execution 2.2.0' to ClassLibrary5
For adding package 'xunit.core.2.2.0' to project 'ClassLibrary5' that targets 'net462'.
For adding package 'xunit.core.2.2.0' to project 'ClassLibrary5' that targets 'net462'.
Adding package 'xunit.core.2.2.0' to folder 'C:\dev\ClassLibrary5\packages'
Added package 'xunit.core.2.2.0' to folder 'C:\dev\ClassLibrary5\packages'
Added package 'xunit.core.2.2.0' to 'packages.config'
Successfully installed 'xunit.core 2.2.0' to ClassLibrary5
Adding package 'xunit.2.2.0', which only has dependencies, to project 'ClassLibrary5'.
Adding package 'xunit.2.2.0' to folder 'C:\dev\ClassLibrary5\packages'
Added package 'xunit.2.2.0' to folder 'C:\dev\ClassLibrary5\packages'
Added package 'xunit.2.2.0' to 'packages.config'
Successfully installed 'xunit 2.2.0' to ClassLibrary5
Executing nuget actions took 1.35 sec
========== Finished ==========
Time Elapsed: 00:00:04.6404151
```

**Comment by onovotny** [comment]
Can you please share what's in your Package Manager output? There might be more details about the issue in there.

**Comment by SeanFarrow** [comment]
Hi,

Below is my entire package manager output, in vs2015. Is there any chance you could upload a sample?
Cheers
Sean.
---Begin output---
Attempting to gather dependencies information for package 'xunit.2.2.0' with respect to project 'XUnitTest', targeting '.NETFramework,Version=v4.6'
Attempting to resolve dependencies for package 'xunit.2.2.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'xunit.2.2.0'
Resolved actions to install package 'xunit.2.2.0'
Adding package 'xunit.abstractions.2.0.1' to folder 'C:\Work\XUnitTest\XUnitTest\packages'
Added package 'xunit.abstractions.2.0.1' to folder 'C:\Work\XUnitTest\XUnitTest\packages'
Added package 'xunit.abstractions.2.0.1' to 'packages.config'
Successfully installed 'xunit.abstractions 2.0.1' to XUnitTest
Adding package 'xunit.assert.2.2.0' to folder 'C:\Work\XUnitTest\XUnitTest\packages'
Added package 'xunit.assert.2.2.0' to folder 'C:\Work\XUnitTest\XUnitTest\packages'
Added package 'xunit.assert.2.2.0' to 'packages.config'
Successfully installed 'xunit.assert 2.2.0' to XUnitTest
Adding package 'xunit.extensibility.core.2.2.0' to folder 'C:\Work\XUnitTest\XUnitTest\packages'
Added package 'xunit.extensibility.core.2.2.0' to folder 'C:\Work\XUnitTest\XUnitTest\packages'
Added package 'xunit.extensibility.core.2.2.0' to 'packages.config'
Successfully installed 'xunit.extensibility.core 2.2.0' to XUnitTest
Adding package 'xunit.extensibility.execution.2.2.0' to folder 'C:\Work\XUnitTest\XUnitTest\packages'
Added package 'xunit.extensibility.execution.2.2.0' to folder 'C:\Work\XUnitTest\XUnitTest\packages'
Added package 'xunit.extensibility.execution.2.2.0' to 'packages.config'
Successfully installed 'xunit.extensibility.execution 2.2.0' to XUnitTest
Install failed. Rolling back...
Package 'xunit.core.2.2.0 : xunit.extensibility.core [2.2.0, 2.2.0], xunit.extensibility.execution [2.2.0, 2.2.0]' does not exist in project 'XUnitTest'
Removed package 'xunit.extensibility.execution.2.2.0 : xunit.extensibility.core [2.2.0, 2.2.0]' from 'packages.config'
Removed package 'xunit.extensibility.core.2.2.0 : xunit.abstractions [2.0.1, )' from 'packages.config'
Removed package 'xunit.assert.2.2.0 : ' from 'packages.config'
Removed package 'xunit.abstractions.2.0.1 : ' from 'packages.config'
Package 'xunit.core.2.2.0 : xunit.extensibility.core [2.2.0, 2.2.0], xunit.extensibility.execution [2.2.0, 2.2.0]' does not exist in folder 'C:\Work\XUnitTest\XUnitTest\packages'
Removing package 'xunit.extensibility.execution.2.2.0 : xunit.extensibility.core [2.2.0, 2.2.0]' from folder 'C:\Work\XUnitTest\XUnitTest\packages'
Removed package 'xunit.extensibility.execution.2.2.0 : xunit.extensibility.core [2.2.0, 2.2.0]' from folder 'C:\Work\XUnitTest\XUnitTest\packages'
Removing package 'xunit.extensibility.core.2.2.0 : xunit.abstractions [2.0.1, )' from folder 'C:\Work\XUnitTest\XUnitTest\packages'
Removed package 'xunit.extensibility.core.2.2.0 : xunit.abstractions [2.0.1, )' from folder 'C:\Work\XUnitTest\XUnitTest\packages'
Removing package 'xunit.assert.2.2.0 : ' from folder 'C:\Work\XUnitTest\XUnitTest\packages'
Removed package 'xunit.assert.2.2.0 : ' from folder 'C:\Work\XUnitTest\XUnitTest\packages'
Removing package 'xunit.abstractions.2.0.1 : ' from folder 'C:\Work\XUnitTest\XUnitTest\packages'
Removed package 'xunit.abstractions.2.0.1 : ' from folder 'C:\Work\XUnitTest\XUnitTest\packages'
Could not install package 'xunit.core 2.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
========== Finished ==========
---end output---

**Comment by codekoenig** [comment]
I have exactly the same issue with xUnit 2.2 in VS2013 Ultimate Update 5. NuGet is also 2.12 ... tried changing to different framework versions (4.5.2 and higher), tried on another machine, in a fresh project ... so far no luck.

**Comment by SeanFarrow** [comment]
Wonder whether this is because the XUnit.core package doesn't have any target frameworks?

**Comment by onovotny** [comment]
It doesn't need anything in the lib directory, it has targets in the \build\netstandard1.0 directory, which is supposed to work with NuGet 2.12+. 

Investigating.

**Comment by bradwilson** [comment]
An issue has been filed with NuGet: https://github.com/NuGet/Home/issues/4685

A work-around is available, depending on how you were referencing xUnit.net:

1. If you reference `xunit` today, please uninstall that, and instead add references to: `xunit.assert`, `xunit.extensibility.core`, and `xunit.extensibility.exection`.
2. If you reference `xunit.core` today, please uninstall that, and instead add references to: `xunit.extensibility.core` and `xunit.extensibility.exection`.

**Comment by AnnieOletubo** [comment]
Hi there,

I'm figuring issue while I want to install a NuGet that is referencing xUnit.
Even if I install the xunit.assert, xunit.extensibility.core, and xunit.extensibility.execution before installing the other NuGet, it keeps on trying to install xUnit.core and xUnit... so the installationfailed..

What can I do ?

**Comment by bradwilson** [comment]
To be clear: with VS2013 and xUnit.net 2.2, you will **never** be able to install the <code>xunit</code> package successfully. Please follow my instructions above exactly.

**Comment by ormedo** [comment]
That problems reproduce on VS 2017 for Mac. I have to install 2.1 and get no errors.

**Comment by bradwilson** [comment]
External issue.
