### ISSUE TITLE
When I run a working project, I get the following message: Could not load file or assembly 'System.Data.SQLite, Version=1.0.104.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139' or one of its dependencies. An attempt was made to load a program with an incorrect format.  Please keep in mind that this works with MSTest and all by itself.

### ISSUE THREAD

**Issue by pbainter** [xunit/xunit#1128]

**Comment by bradwilson** [comment]
It sounds like you're trying to load a 32-bit DLL into a 64-bit unit test, or vice versa.

**Comment by pbainter** [comment]
Just shut things down, but I will take a look, thanks

**Comment by pbainter** [comment]
I checked and there are 5 different projects in this solution, 1 of the 5 is the testing project.  Each project is set to "Any CPU" and .NET 4.6.1, so I don't think I see a problem with that unless I can't use "Any CPU" as a platform target.  The message above is the Inner message. The primary message states:

An exception of type 'System.BadImageFormatException' occurred in DapperBase.dll but was not handled in user code.

There is plenty of code in the DapperBase.dll that gets executed before the message is hit and I can't see anything in particular that.

**Comment by bradwilson** [comment]
Closed for age.
