### ISSUE TITLE
"No test is available in .." when targeting net451

### ISSUE THREAD

**Issue by smadala** [xunit/xunit#1130]
_From @adamsitnik on February 21, 2017 11:39_

When I create a new test project with `dotnet new xunit`, add `net451` target framework and update the packages to the latest versions I get "No test is available in" error:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp1.0;net451</TargetFrameworks>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170217-05" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  </ItemGroup>
</Project>
```

```
C:\tmp>dotnet restore
C:\tmp>dotnet test tmp.csproj -f net451 -c Release
Build started, please wait...
Build completed.

Test run for C:\tmp\bin\Release\net451\tmp.exe(.NETFramework,Version=v4.5.1)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Warning: No test is available in C:\tmp\bin\Release\net451\tmp.exe. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
```

When I downgrade the packages things work fine
```xml
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170123-02" />
<PackageReference Include="xunit" Version="2.2.0-beta5-build3474" />
<PackageReference Include="xunit.runner.visualstudio" Version="2.2.0-beta5-build1225" />
```

It seems to be similar to #523. the following workaround does not help:
```xml
<PropertyGroup>
    <DebugType Condition="'$(TargetFramework)' != '' AND !$(TargetFramework.StartsWith('netcoreapp'))">Full</DebugType>
</PropertyGroup>
```

_Copied from original issue: Microsoft/vstest#526_

**Comment by smadala** [comment]
Looks like there are packaging change in xunit.
xunit.runner.visualstudio > 2.2.0-beta5-build1225 moved from net45 to net452.

 `
 <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170217-05" />
 <PackageReference Include="xunit" Version="2.2.0" />
 <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />`

with above packages I am seeing following message, In which we can notice
 xunit.execution.desktop.dll skipping log.
 If you are not seeing skipping message, can please provide more info about your platform.
```
Starting test execution, please wait...
[xUnit.net 00:00:00.1805285] Skipping: net45 (Could not find any of the following assemblies: xunit.execution.desktop.dll)
No test is available in C:\Users\samadala\tmp\net45\bin\Debug\net451\net45.exe. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
```

FYI, `<OutputType>Exe</OutputType>    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>` properties not required with latest templates.

**Comment by bradwilson** [comment]
That is correct. .NET 4.5.2 is the minimum supported version for desktop CLR now. From the [release notes](https://xunit.github.io/release-notes/2017-02-19.html):

> The minimum version of .NET required for desktop CLR unit tests is now .NET 4.5.2. This change was made since both 4.5 and 4.5.1 are now out of official support. This change only affects your unit test projects; your production code is still free to target lower versions of .NET. (Note: Because we support netstandard1.1, you will still be able to link your desktop unit test projects that target 4.5 and 4.5.1, but they will not show up in the Visual Studio runner, and they will not get desktop features like AppDomain isolation. Make sure you upgrade the .NET version of your projects before installing the new NuGet packages.)

**Comment by adamsitnik** [comment]
@smadala @bradwilson thanks for help! Once I upgraded the test projects to net452 it works now.

**Comment by bradwilson** [comment]
Closed for age.
