### ISSUE TITLE
AssemblyTrait not shown on Visual Studio's Test Explorer

### ISSUE THREAD

**Issue by kazuk** [xunit/xunit#1131]
I plan to run test on .NET Core App 1.1 and .NET Framework 4.6.2

solution image is bellow
 
![image](https://cloud.githubusercontent.com/assets/192684/23199910/b360dd54-f914-11e6-8d7a-0bd0839533e9.png)

CoreAppAttr.cs contains only 1 line
```
[assembly: Xunit.AssemblyTrait("framework", ".NETCoreApp1.0")]
```

FullFrameworkAttr.cs contains only 1 line
```
[assembly: Xunit.AssemblyTrait("framework", ".NET Framework4.6.2")]
```

Visual Studio Test explorer show this.

![image](https://cloud.githubusercontent.com/assets/192684/23199995/26d98290-f915-11e6-9f53-963884ed2c98.png)

I expected

`framework [.NET Framework4.6.2]` is shown but `特徴無し` (meaning no traits) shown.

Environment

Visual Studio 2017 RC (with JA-JP localization)

**Comment by bradwilson** [comment]
Closed for age.
