### ISSUE TITLE
Error when running test in VS2017

### ISSUE THREAD

**Issue by FelschR** [xunit/xunit#1132]
I'm currently trying to setup xunit in a .NET Core project with the new csproj/MSBuild format.

I'm using the most recent versions of:
- Microsoft.NET.Test.Sdk (15.0.0-preview-20170217-05)
- xunit (2.2.0)
- xunit.runner.visualstudio (2.2.0)

It's already possible to run the tests via "dotnet build" in the console but when using VS2017 I get the following error for a lot of tests:
`Message: System.AggregateException : One or more errors occurred.
---- System.IO.FileLoadException : Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

It occurs in tests that invoke certain methods of the DocumentDB SDK which seems to try to get an older version of Newtonsoft.Json.
I have no clue what's causing this issue as I don't really know how running from VS differs to the console variant.

**Comment by onovotny** [comment]
is the project targeting `netcoreapp1.0`, `netcoreapp1.1` or `net46`? .NET Core isn't supposed to care about assembly versions and desktop .net should be getting a binding redirect.

**Comment by onovotny** [comment]
this seems like an issue for https://GitHub.com/Microsoft/vstest btw...

**Comment by FelschR** [comment]
My test project is targeting net452 & netcoreapp1.0.
The project that is being tested targets net451 & netstandard1.6.

**Comment by codito** [comment]
This looks similar to https://github.com/Microsoft/vstest/issues/391

**Comment by bradwilson** [comment]
Closed for age.
