### ISSUE TITLE
Two Theory with the same name but different args cause failures

### ISSUE THREAD

**Issue by krwq** [xunit/xunit#1133]
This is probably very rare scenario and not sure if worth fixing - I hit it today when accidentally forgot to rename the test when copy pasting it - at least some better error message would be helpful.

Repro:
- create two Theories with the same name but different args (in my case number of args was different)

observe failures when runner tries to run them.

**Comment by hughbe** [comment]
E.g. the following doesn't work?

```
[Theory]
public void Test(int x) {}

[Theory]
public void Test(int x, int y) {}

```

**Comment by bradwilson** [comment]
That is correct. This is an unsupported scenario.

**Comment by bradwilson** [comment]
#21 
#650

**Comment by hughbe** [comment]
Might be worth fixing if it's come up 3 times - I'll see if it is easy or requires a lot of changes

**Comment by krwq** [comment]
@bradwilson @hughbe I think the exception: "this is not supported" should be fine - it is not obvious by looking at the failure what is going on

**Comment by bradwilson** [comment]
Closed for age.
