### ISSUE TITLE
Error upgrading from 2.1 to 2.2 on .NET 4.5.2

### ISSUE THREAD

**Issue by TicoDePano** [xunit/xunit#1134]
Install failed. Rolling back...
Could not install package 'xunit.core 2.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by scpeterson** [comment]
I get this same error as well when upgrading via NuGet.  My projects are all at 4.5.2 so I'm not sure why the upgrade is failing.

**Comment by onovotny** [comment]
@scpeterson What version of VS do you have? What version of the NuGet extension do you have (from the Extensions and Updates dialog)? Do you happen to have the ASP.NET Core tooling installed (not suggesting to install it, trying to gather data as we can't repro).

**Comment by scpeterson** [comment]
@onovotny  I am using VS 2013 with the Nuget Package Manager for Visual Studio 2013 version 2.12.0.817.  The Core Tools do not appear to be installed.

**Comment by TicoDePano** [comment]
I am using VS 2013 in 2 different PCs, one with nuget 2.12.0.817.

**Comment by bradwilson** [comment]
An issue has been filed with NuGet: https://github.com/NuGet/Home/issues/4685

A work-around is available, depending on how you were referencing xUnit.net:

1. If you reference `xunit` today, please uninstall that, and instead add references to: `xunit.assert`, `xunit.extensibility.core`, and `xunit.extensibility.exection`.
2. If you reference `xunit.core` today, please uninstall that, and instead add references to: `xunit.extensibility.core` and `xunit.extensibility.exection`.

**Comment by vcsjones** [comment]
@bradwilson I think you mean `xunit.extensibility.execution`?

**Comment by perezLamed** [comment]
This error also occurs on VS 2013 on .NET 4.6.1. 
Your workaround does work for me:
1. If you reference xunit today, please uninstall that, and instead add references to: xunit.assert, xunit.extensibility.core, and xunit.extensibility.execution.
2. If you reference xunit.core today, please uninstall that, and instead add references to: xunit.extensibility.core and xunit.extensibility.execution.

**Comment by bradwilson** [comment]
It's unlikely that this issue will ever be fixed. ☹️

**Comment by bradwilson** [comment]
Our updated .props file has fixed this as of `2.3.0-beta2-build3665`.

**Comment by PureKrome** [comment]
@bradwilson Just to confirm:
- This is an issue with NuGet 2.x?
- If yes to above, then this is an issue with the older versions of VS only?

so .. if we're on the newer versions of VS we don't really have to worry about this?

**Comment by bradwilson** [comment]
@PureKrome Yes, the original problem is a bug in NuGet 2.x. But as it turns out, we ended up working around it (unintentionally, mostly :-p) with a change to the .props file that no longer triggers the NuGet bug. Also, yes, this only affects VS2013 (2015 and later do not suffer from the bug).
