### ISSUE TITLE
Code coverage running same tests more than once 

### ISSUE THREAD

**Issue by srini1978** [xunit/xunit#1137]
I have a Visual Studio Solution on .net core. I am using dotest-xunit-1.0.0 rc2 version for some projects and for some test projects , using 2.2.0  preview version.

Code coverage seems to run fine on Visual Studio but when I put it in build server as a build step, I get skewed results. For example , if there is a dll

ABC.dll with ABC.tests.dll

I can see that in code coverage, ABC.dll has been run twice with different timestamps . it should have run only once.

**Comment by bradwilson** [comment]
Closed for age.
