### ISSUE TITLE
No unit tests discovered

### ISSUE THREAD

**Issue by martinfletcher** [xunit/xunit#1138]
Hi,

I have a solution in which no unit tests are found. I have followed the docs about clearing out temp directories etc, but still have the same issue. I have even created a new solution with a single class library in, and still no luck.

I am getting the following error (xunit and xunit.runner.visualstudio nuget packages, both at 2.2.0):

(Could not find any of the following assemblies: xunit.execution.desktop.dll)

Thanks

Martin

**Comment by martinfletcher** [comment]
Seems like this may be  the cause https://www.bountysource.com/issues/41491870-unable-to-discover-test-in-visual-studio-with-latest-xunit-extensibility-execution-package?show_profile_modal=1

**Comment by martinfletcher** [comment]
Any update on this? Not been able to get xunit working for new projects for over a week now....

**Comment by mkchandler** [comment]
I'm running into this same issue, any updates?

**Comment by bradwilson** [comment]
Can you provide a repro project?

**Comment by martinfletcher** [comment]
https://www.dropbox.com/s/rjfkgrb6dnd03qk/XunitNoTestDiscovered.zip?dl=0

That is a project with the error.

**Comment by bradwilson** [comment]
@martinfletcher You're not seeing tests in Visual Studio because you don't meet the minimum requirements for 2.2 as documented in the [release notes](https://xunit.github.io/release-notes/2017-02-19.html):

> The minimum version of .NET required for desktop CLR unit tests is now .NET 4.5.2. This change was made since both 4.5 and 4.5.1 are now out of official support. This change only affects your unit test projects; your production code is still free to target lower versions of .NET. (Note: Because we support netstandard1.1, you will still be able to link your desktop unit test projects that target 4.5 and 4.5.1, but they will not show up in the Visual Studio runner, and they will not get desktop features like AppDomain isolation. Make sure you upgrade the .NET version of your projects before installing the new NuGet packages.)

**Comment by mkchandler** [comment]
@bradwilson Thanks. I missed that part of the release notes. Changing the test project to 4.5.2 fixed my issue.

**Comment by twsouthwick** [comment]
I hit this same issue. 

On the release notes, it says you dropped support since 4.5 and 4.5.1 are out of support. Unless there's a technical reason for requiring 4.5.2 (such as new surface area), you can still target 4.5 (even 4.0). The "out-of-support" messaging refers to the runtimes not being supported; it is still a supported scenario to have applications that target (and therefore don't opt into the latest changes) on a later version of the framework.

**Comment by martinfletcher** [comment]
Thanks for that, I also missed that in the tech notes.......

I am closing this issue now as its already been answered.
