### ISSUE TITLE
Long test data results in `Contents of string '{test name}' exceeds max of '449', string has been truncated.` messages

### ISSUE THREAD

**Issue by dougbu** [xunit/xunit#1139]
When using the xunit and xunit.runner.visualstudio v2.2.0 packages in a recent copy of Visual Studio 2017 RC, messages such as the above appear frequently in the Output window. Not sure whether such test name truncation is in itself a problem e.g. not executing or reporting on some tests. But, the extra output definitely makes it difficult to see messages about other problems.

The [aspnet/Mvc](https://github.com/aspnet/Mvc) repo hits this problem fairly frequently. (See the `dougbu/migration` branch until I get that switch to use MSBuild and the xunit.runner.visualstudio package in.) I haven't checked all tests that cause this output. But, test data tends to involve `Type`s with long names and POCO classes with many properties e.g. `DisplayFormatAttribute`.

See also a similar nUnit bug: nunit/nunit#59.

**Comment by cknaap** [comment]
And at the same time this happens, the Test Explorer does not finish it's progress bar. If I run just the one test with 16 cases that (all) cause this '449' message, the progress bar stops at 50%.

**Comment by bradwilson** [comment]
Closed for age.

**Comment by dougbu** [comment]
@bradwilson the problem may be longstanding but it hasn't gone away. Issue still exists in the latest xUnit packages. And, it seems like the xUnit team could make changes similar to whatever the nUnit team did to avoid the problem.

I don't have much time to work on this but could investigate further if a PR would be of interest. LMK&hellip;

**Comment by bradwilson** [comment]
Please provide a PR to fix the issue.
