### ISSUE TITLE
Visual Studio runner not showing test in CodeLens and only runs all

### ISSUE THREAD

**Issue by M4ttsson** [xunit/xunit#1140]
When upgrading xunit.runner.visualstudio to version 2.2 tests are not shown in CodeLens. And when using shortcut ctrl+r+t to run a specific test, all tests in the current class is run. Right clicking a test and selecting Run Tests option also runs all tests in the class.
I'm using VS 2015, Update 3.

If I downgrade the runner to version 2.1 everything works again. 

Reproducing steps:
1. Create a new class library in a new solution.
2. Get Xunit 2.2 and Visual Studio runner 2.2 from NuGet.
3. Restart Visual Studio just to make sure the correct runner is loaded.
4. Create two test methods in Class1.cs
5. Build Solution, this should trigger CodeLens to show the test button above the test (if CodeLens is available).
6. Right click a test in the source code and click Run Tests (or use shortcut), this will cause both tests to be run and not only the clicked one.

Selecting a single test and running in test explorer window still works.

**Comment by Shyam-Gupta** [comment]
Bug reproes for me as well.

**Comment by bradwilson** [comment]
Just to be clear, this is only a CodeLens issue? You can still run individual tests in the Test Explorer, right?

**Comment by M4ttsson** [comment]
It's not only CodeLens. Confirmed it on community edition this morning.
Yes, you can run individual tests in Test Explorer. But you can not run or debug the test your writing using the keyboard shortcut (ctrl+r+t) or right clicking. Only way to run an individual test in 2.2 is Test Explorer, the other ways to do it (CodeLens, shortcut, etc.) doesn't work anymore.

**Comment by navin22** [comment]
@bradwilson : In xunit2.2.0 the full qualified name of a test case is coming as <fullqualifiedName>+ " " +(<guid>).
And we are comparing this with the <fullqualifiedname> that we get from the document context. 
We are expecting these two to be equal then we will run that particular test. If not we run all the tests in the document as default action.
Hence it's running all the tests in the document.

**Comment by bradwilson** [comment]
@navin22 Given that explanation, I'm not clear why this is broken for desktop CLR projects, but not for .NET Core projects. Shouldn't the same logic be failing in both places?

**Comment by navin22** [comment]
@bradwilson : In .Net Core projects also it's broken. Only for the first time and only the default test that's already there will work as expected. If you close and open the solution, we can repro the above issue.

**Comment by bradwilson** [comment]
https://github.com/xunit/visualstudio.xunit/commit/0d9bbb48cf78a376ee354760a992081d85f6b5f8

<img src="https://cloud.githubusercontent.com/assets/16944/24335763/5edfd81a-1238-11e7-8165-15b187df6322.png" width="450" />

This is fixed for desktop projects, but .NET Core still appears to be broken. Since we use the same code for all, my suspicion is that the .NET Core issue is elsewhere (maybe in the VSTest code rather than our code).

**Comment by PureKrome** [comment]
Such a bummer this is only supported in CodeLens :( (yes, tis a rant. nothing to do with xUnit, etc :(  )

**Comment by treenew** [comment]
How fix this bug?If use [ctrl]+[r] [t] run all test. The tests are not shown in CodeLens.

**Comment by treenew** [comment]
Change xunit vession to "2.3.0-beta1-build3642" fix this bug.....

**Comment by wgross** [comment]
Upgrading to the beta version didn't work for me. I'm using 

xunit 2.3.0-beta1-build3643, 
xunit.runner.visualstudio v2.3.0-beta1-build1309
visual studio community edition version 15.1 (26403.3)

While command line is working (dotnet test) running tests from VS isn't possible any more:
All tests are shown as external and are executable from test explorer but ctrl+r+t isn't working any more (No tests found to run)

Target framework of all test projects is:   

<TargetFramework>netcoreapp1.1</TargetFramework>

target framework of the src projects differ

<TargetFrameworks>netstandard1.1;net461</TargetFrameworks>
<TargetFramework>netstandard1.4</TargetFramework>

If I change the target framework of the test projects to net461 test are discovered as projects again.
Is there anything else i can provide? logs? Experiments?

**Comment by bradwilson** [comment]
I feel you consult the compatibility table for the runners:

https://xunit.github.io/#runners

You will see that netstandard is *not* compatible with the Visual Studio runner.

**Comment by wgross** [comment]
@bradwilson thanks, that helps it! 
I wasn't aware of the compatibility restrictions of the runners.

**Comment by PureKrome** [comment]
>You will see that netstandard is not compatible with the Visual Studio runner.

@bradwilson - trying to understand that table.

-- RUNNRERS
- xunit.net : this is xunit.runners.<any/all of em>  ?
- visual studio: this is the built in test explorer that comes baked into VS?

and if yes to both .. does this mean we sorta need to wait for xunit runner 2.3 to rtm to get _real proper_ unit test support in VS or in console?

**Comment by bradwilson** [comment]
This was fixed in 2.3 beta 1. I forgot to tag it when it got released.

**Comment by poke** [comment]
@bradwilson
> You will see that netstandard is not compatible with the Visual Studio runner.

Does that refer to the new .csproj project format, or actually targetting netstandard?

I’m testing 2.3.0-beta1 with a new-style .csproj targetting .NET 4.6.1. I can run the tests just fine from the test explorer, but the tests are not recognized as tests in the source editor. I get no code lens information about the unit test, and executing the tests using the context menu (single or all in the file) runs no test.

Is this currently to be expected? Is there any bug tracking progress on the supporting the new .csproj?

**Comment by bradwilson** [comment]
> Does that refer to the new .csproj project format, or actually targetting netstandard?

It is not supported at all, regardless of project format.

> I’m testing 2.3.0-beta1 with a new-style .csproj targetting .NET 4.6.1. I can run the tests just fine from the test explorer, but the tests are not recognized as tests in the source editor. I get no code lens information about the unit test, and executing the tests using the context menu (single or all in the file) runs no test.

This should be fixed in 2.3 beta 1 **_of the Visual Studio runner_**, but as always, only for `[Fact]` tests. Pre-enumerated theories have never supported CodeLens.

**Comment by bradwilson** [comment]
You can always used our [Integration Test Project](https://github.com/xunit/xunit.integration) to help determine whether issues are related to your specific project or generally to your machine. As you can see here, CodeLens is functional for `[Fact]` tests but not `[Theory]` tests, as expected:

![image](https://cloud.githubusercontent.com/assets/16944/25440204/86ff6a9e-2a53-11e7-96c6-0ac7d2816f98.png)

**Comment by poke** [comment]
@bradwilson Thank you, the integration project helped me. I was missing the `Microsoft.NET.Test.Sdk` reference in my project. It is working now.

**Comment by EliiseS** [comment]
I updated to the latest beta version of Xunit, Xunit.Runner.VisualStudio and for good measure, Microsft.Net.Test.Sdk. The icons still aren't being shown on my tests.

**Comment by GeorgDangl** [comment]
I'm not getting the CodeLens to show up for nested classes:
![xunitcodelens](https://user-images.githubusercontent.com/10274404/27004079-7219a7a6-4e03-11e7-96df-95a39fb28154.PNG)

I'm running Visual Studio 2017 with the latest update (15.2.26430.13, not preview) and the following references:
```xml
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0-preview-20170601-03" />
<PackageReference Include="xunit" Version="2.3.0-beta4-build3707" />
<PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-beta4-build3707" />
<DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta2-build3683" />
```

It is also configured as test project via:
```xml
<ItemGroup>
  <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
</ItemGroup>
```

The target framework for the test project is `netcoreapp1.1`. I'm usually structuring my tests in a base class per class to test and parent classes for each method, e.g.:
```csharp
public class AccountCountrollerTests
{
  public class Login
  {
    [Fact]
    public void OkWithUsernameInsteadOfEmail()
    {
      // ...
    }
  }

  public class Logout
  {
    // ...
  }
}
```

The TestExplorer is fine and I'm able to run single tests in nested classes. It's just not showing up in CodeLens. I've tried to create nested classes in the xUnit Integration Test Project with the same result.

**Comment by philwindsor** [comment]
We've just tried the latest beta build of the visual studio runner and the cross/tick is still missing from code lens.

**Comment by axelheer** [comment]
@bradwilson I compared my projects with your Test Integration Project and noticed, that adding the following line to *v2x_netcoreapp1.1.csproj*

```xml
<DebugType>full</DebugType>
```

breaks CodeLens and [ctrl]+[r] [t] as already described within this thread.

Note: setting this to *full* is required in order to use OpenCover (see OpenCover/opencover#601).

**Comment by GeorgDangl** [comment]
You need to only set it on the project you're actually generating coverage for.

[Here's an example project](https://github.com/GeorgDangl/Dangl.Calculator/blob/master/src/Dangl.Calculator/Dangl.Calculator.csproj#L28-L31). Only the actual code library generates pdb files, the unit tests don't.

**Comment by axelheer** [comment]
Yeah, I'm not quite sure why we're creating coverage data for the test projects too (maybe to bump up the total coverage... ;)). Nevertheless, the debug type shouldn't be able to kill CodeLens, should it?

**Comment by bradwilson** [comment]
> the debug type shouldn't be able to kill CodeLens, should it?

Yes, it absolutely will kill CodeLens.

The component inside Visual Studio which maps methods to source lines does so by reading the debug symbols. You must have them, and they must be in the expected format, or else it won't work. AFAIK, .NET Core requires Portable PDBs, and desktop requires Full (classic) PDBs. The VSTest team will know better, as it's their component doing the mapping.

**Comment by axelheer** [comment]
> The component inside Visual Studio which maps methods to source lines does so by reading the debug symbols.

Makes sense, thank you!

**Comment by GeorgDangl** [comment]
I think this is broken again, with Visual Studio 2017 15.3.5 and the `xunit.runner.visualstudio` version `2.3.0-rc1-build3795` added to the [integration project/dotnet-xunit](https://github.com/xunit/xunit.integration/tree/master/dotnet-xunit). generating `full` or `portable` pdbs doesn't make a difference for me.

Any tips?

**Comment by xavero** [comment]
@GeorgDangl Same problem here. Upgrading `xunit.runner.visualstudio` to version `2.3.0-beta5-build3769` has resolved this issue for me.

**Comment by bradwilson** [comment]
@GeorgDangl Did you remember to also add `Microsoft.NET.Test.Sdk` version `15.3.0` as well? That's required for .NET Core tests in Visual Studio.

If you run `dotnet test` and forget this reference, it should give you a suitable error message:

```
Test run for C:\Dev\xunit\xunit.integration\dotnet-xunit\bin\Debug\netcoreapp1.0\v2x_MultiTarget_DotNetSdk.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
No test is available in C:\Dev\xunit\xunit.integration\dotnet-xunit\bin\Debug\netcoreapp1.0\v2x_MultiTarget_DotNetSdk.dll. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate and try again.
```

Once I added both packages, I can see tests in VS 2017 15.3.5:

![Visual Studio](https://user-images.githubusercontent.com/16944/30980520-37b19afe-a436-11e7-8a3f-666a192542ca.png)

**Comment by bradwilson** [comment]
Also bear in mind: with multi-targeting, inside Visual Studio you can only run the first target framework (in this case, net452). If you want to be able to run multiple target frameworks inside Visual Studio, you will need to use multiple projects.

I am hopeful that the VSTest team will address this shortcoming in a future build.

**Comment by GeorgDangl** [comment]
@bradwilson Yeah, I did add `Microsoft.NET.Tests.Sdk`, the latest prerelease version that was available on NuGet. Tests ran fine and navigation from the Test Explorer to the source code worked as expected.

I'm no longer at work now, but I just checked at home in a personal project, here the latest RC versions `2.3.0-rc1-build3797` work fine with `netcoreapp2.0`. I'll investigate what's different between the two projects and report back tomorrow.

But, generally, should there be any difference in the test project setup depending on if I'm testing against `net461` vs `netcoreapp`?

**Comment by bradwilson** [comment]
To run inside Visual Studio, desktop CLR projects don't require `Microsoft.NET.Test.Sdk`, because they use the older Test Platform v1 (aka, the code that has shipped since VS2012). .NET Core, on the other hand, runs with Test Platform v2 and requires that package reference.

You can even see this difference by failing to add `Microsoft.NET.Test.Sdk` in our `dotnet-xunit` integration project: when you run `dotnet test`, it happily runs the desktop CLR framework tests, and only fails the netcoreapp projects.

Otherwise, no... there are no differences between the two. There's no harm in adding `Microsoft.NET.Test.Sdk` to a desktop CLR project, even though it's not used.

**Comment by Thorocaine** [comment]
I seem to be having this problem.
If I run all from Test Explorer all tests are found (new ones as well) and run.

If I _Ctrl-R, T_ from my test class then `No tests found to run.`

I have _xunit_ and _xunit.runner.visualstudio_ v2.3.1

**Comment by navin22** [comment]
Adding more folks
+Manish, peter and Shyam

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Shyam-Gupta** [comment]
@Thorocaine 
With which VS version are you seeing this issue ?

**Comment by Thorocaine** [comment]
15.4.3 (2017 Enterprise)

**Comment by zhouguoqing** [comment]
How to fixed it？
