### ISSUE TITLE
.NET Core tests produce no output

### ISSUE THREAD

**Issue by borrrden** [xunit/xunit#1141]
When running on Windows or Ubuntu after upgrading to RC4, test methods no longer have any visible output from calls to `Console.WriteLine` (my OS X machine seems to have it, but none of our build machines including an OS X machine seem to have it, and my Windows machine does not have it).  I tried moving everything over to `ITestOutputHelper` but still no luck.  How can I get back this output?  Not sure if the issue is here or upstream with `dotnet` or possibly `vstest`.  The only output I see is a bunch of:

> Passed TestName
> Passed TestName
> Passed TestName
> Passed TestName

etc

Running in VS2017 properly captures the output once I switched over to using `ITestOutputHelper`

[Here](https://github.com/couchbase/couchbase-lite-core/blob/master/CSharp/test/LiteCore.Tests/LiteCore.Tests.csproj) is the csproj file I am using.  

`dotnet --info`

> .NET Command Line Tools (1.0.0-rc4-004771)
Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.0-rc4-004771

> .NET Command Line Tools (1.0.0-rc4-004771)
Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e
Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-rc4-004771

> .NET Command Line Tools (1.0.0-rc4-004771)
Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771

**Comment by borrrden** [comment]
Note: I did try upgrading Microsoft.Net.Test.Sdk to 15.0.0, and the xunit packages to 2.2.0 but the situation remained the same.

**Comment by bradwilson** [comment]
That is correct. There is no way to see that output with `dotnet test` because of limitations in the VSTest runner.

We will be fixing this (and many, many other issues) with `dotnet xunit`.

**Comment by borrrden** [comment]
In the meantime, should I use the xunit console runner to run the tests if I need to see the output?  I have a similar issue of the tests simply dying with the unhelpful message "Error: The active test run was aborted" that I am trying to get to the bottom of.  

Or is there a way to signal that `ITestOutputHelper` should write to a file (I suppose even if there were `dotnet test` would not be able to send the correct things to the runner?)

**Comment by bradwilson** [comment]
The console runner should be able to run desktop projects (i.e., `net4x` target frameworks) as-is.

For .NET Core (i.e., `netcoreapp1.x` target frameworks), the console runner _might_ be able to run them after you've run `dotnet publish` so that it collects all the necessary DLLs, but I've never verified this, and it's possible that it doesn't work at all, because it would be bootstrapping and running it using the desktop CLR, despite the system having targeted .NET Core.

**Comment by borrrden** [comment]
I see. In the new command dependent on dotnet changes as well or is there a
way I could try running one of the preview builds to enable this feature.
Or anything else you can think of that can be done now to get output?  I'm
not entirely sure the second issue I am facing would output anything more
even with console.writeline working but this would help determine one way
or the other.

**Comment by codito** [comment]
@bradwilson wrote:
> There is no way to see that output with dotnet test because of limitations in the VSTest runner.

Can you elaborate? The adapter could listen to stdout (and debug traces if needed) when test is running and sending it to runner? Similar to how it sends the `Passed`, `Failed` today.

**Comment by bradwilson** [comment]
We do not capture stdout (users are free to use that if they so choose). Our output capture system pushes that information into the test result rather than to stdout. The TRX report may or may not generate reports which include "output" results (I don't personally know, since I have no knowledge of this format), but today there's no simple way today to get this output from `dotnet test` directly on the console.

Visual Studio's UI, on the other hand, offers ready access to "output", which is where this information is captured.

**Comment by bradwilson** [comment]
No, that is incorrect.

Users will use `ITestOutputHelper` to write output. That's what ends up in `ITestResultMessage.Output`. We **_do not_** capture any device like console, debug, or tracing.

**Comment by borrrden** [comment]
Is there a build available with `dotnet xunit`  I just upgrade Visual Studio and now there is no output at all except for the stats at the end.

**Comment by borrrden** [comment]
What is the timetable for `dotnet xunit`?

**Comment by bradwilson** [comment]
It is available today in 2.3 beta 1.

https://xunit.github.io/docs/getting-started-dotnet-core.html

**Comment by zwcloud** [comment]
> There is no way to see that output with dotnet test because of limitations in the VSTest runner.
> We do not capture any device like console, debug, or tracing.

@bradwilson 
I'm really curious why there is no way and what the limitations VSTest runner are. I don't think it is completely impossible. Could you please provide more information about the limitations? Is there any related code?

**Comment by rogusdev** [comment]
I want to do debug logging from my actual code and not just inside my tests though, how do you suggest I do this?  I cannot inject ITestOutputHelper in my business logic.

**Comment by MohsenBzm** [comment]
I have the same problem, but I checked my project's path and also installed Rapid Environment Editor  and found no errors with file paths.

**Comment by sergeysolovev** [comment]
@bradwilson before you wrote

> For .NET Core (i.e., netcoreapp1.x target frameworks), the console runner might be able to run them 

JFYI, it does, example https://travis-ci.org/sergeysolovev/webpack-aspnetcore/builds/288072858#L1016

**Comment by wizofaus** [comment]
This is an essential feature - I'm having to switch all my unit tests over to use mstest/vstest now, as being able to grab console and/or trace output from the classes I'm trying to run my tests on is an essential debugging technique.  Surely there should be an option to turn off parallelisation so as to avoid any risk of simultaneously running tests garbling each other's output?  But even garbled output would be more useful than nothing. Further it should be possible to install a TraceListener that uses the current thread id to make a reasonable guess which test is output which message (obviously it won't work if the code under test spawns secondary threads that then write to the console).

**Comment by wizofaus** [comment]
Having written that, I realised I can quite easily do that myself from my tests:

			class TestTraceListener : TraceListener
			{
				ITestOutputHelper _output;
				public TestTraceListener(ITestOutputHelper output) { _output = output; }
				public override void Write(string message) { _output.WriteLine(message); }
				public override void WriteLine(string message) { _output.WriteLine(message); }
			}

in test constructor... 

                        System.Diagnostics.Trace.AddListener(new TestTraceListener(outputHelper));

Does the job well enough for now, despite the addition of newlines after Trace.Write( ... ). Haven't tried for System.Out yet but the same sort of idea could apply.  But I do think there's a good argument for xUnit providing this out of the box, even if it's only as an option.

**Comment by bradwilson** [comment]
The original request is no longer valid. Side comments should become new issues.

**Comment by mattfrear** [comment]
A google search of `xunit console output` in 2018 leads me here. 
`dotnet xunit` has been released, and is now discontinued so don't waste your time trying to use that as I did today. https://xunit.github.io/releases/2.4

**Comment by mattleibow** [comment]
A related issue is here: https://github.com/xunit/xunit/issues/1078

**Comment by trivigy** [comment]
Why is this issue closed? Is there a workaround to "`dotnet test` console output not showing" issue?

**Comment by trivigy** [comment]
After some exploration I figured out an easy solution:
`dotnet test --logger:"console;verbosity=detailed"`

**Comment by bradwilson** [comment]
It was closed because `dotnet test` is not under our control. Any questions/issues you have related to `dotnet test` itself (like, how to get verbose output) belong to the VSTest team.

**Comment by trivigy** [comment]
@bradwilson fair reason. Hopefully my posted solution will help people not search in circles.

**Comment by sa89p** [comment]
Using ITestOutputHelper in unit test classes will provide output only if the test fails. I got an output with `dotnet test` when using this helper interface

**Comment by pkehrer** [comment]
Just to make sure no one missed it, if your issue is "I want to see output which I provide in my tests via `ITestOutputHelper.WriteLine()` when I run `dotnet test`",  @trivigy 's answer of running `dotnet test --logger:"console;verbosity=detailed"` does exactly that.  It provides some extra messages about test discovery, etc. but I'm happy with it.

**Comment by ashishnegi** [comment]
> 
> 
> After some exploration I figured out an easy solution:
> `dotnet test --logger:"console;verbosity=detailed"`

Hey @trivigy What is the dotnet version ? Below dotnet version does not work for me on windows.
```
>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.103\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.1.500-preview-009297 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by ashishnegi** [comment]
This [solution](https://stackoverflow.com/a/47529356/728407) worked.
Set console out to xunit's ITestOutputHelper.

```cs
public MyTestClass(ITestOutputHelper output)
    {
        var converter = new Converter(output);
        Console.SetOut(converter);
    }

    private class Converter : TextWriter
    {
        ITestOutputHelper _output;
        public Converter(ITestOutputHelper output)
        {
            _output = output;
        }
        public override Encoding Encoding
        {
            get { return Encoding.Whatever; }
        }
        public override void WriteLine(string message)
        {
            _output.WriteLine(message);
        }
        public override void WriteLine(string format, params object[] args)
        {
            _output.WriteLine(format, args);
        }
    }
```

**Comment by SimonCropp** [comment]
this might help some of the people on this thread https://github.com/SimonCropp/XunitLogger

**Comment by nyarusinga** [comment]
> @bradwilson fair reason. Hopefully my posted solution will help people not search in circles.

It saved my debug session. Thank you!

**Comment by samuell** [comment]
@trivigy wrote:
> After some exploration I figured out an easy solution:
> `dotnet test --logger:"console;verbosity=detailed"`

This gives more detailed output for me (such as which tests are being run), but still not the WriteLine() statement from within my own library and testing code. Any more settings needed for that to happen?

**Comment by bradwilson** [comment]
We don't do anything with Console output. Your question should be asked of the VSTest team, as they own the machinery behind `dotnet test`.
