### ISSUE TITLE
If an IXunitTestCase does not inherit from LongLivedMarshalByRefObject, it is silently ignored

### ISSUE THREAD

**Issue by 0x53A** [xunit/xunit#1143]
I had created a custom IXunitTestCaseDiscoverer which returned a custom IXunitTestCase.

With printf statements, I could see that my tests were correctly discovered, but none of them were run.

After I inherited from LongLivedMarshalByRefObject, they were correctly executed.

If this is required, please add a runtime check and print an error/warning if an IXunitTestCase does not inherit from this type.

**Comment by bradwilson** [comment]
Covered by #1492
