### ISSUE TITLE
Project/Solution Build should invoke xUnit.net unit test cases as well

### ISSUE THREAD

**Issue by victory4vivek** [xunit/xunit#1144]
1. How could we **restrict developers from code check-ins** until unless all the xUnit.net unit test cases passes?
2. How could we **configure our solution/project to run related xUnit.net unit test cases**? I mean to say whenever a developer builds a particular project in solution or whenever a developer builds entire solutions all the related written unit test cases should be run as well.

**Comment by bradwilson** [comment]
You can do this today.

The console runner NuGet package injects properties to find the runner, so you can write your own target.

https://github.com/xunit/xunit/blob/6ee07f1d4126c7a156318007e1a3a68a09235601/src/xunit.console/build/xunit.runner.console.props#L3-L8

The MSbuild runner NuGet package injects tasks and a target for you:

https://github.com/xunit/xunit/blob/6ee07f1d4126c7a156318007e1a3a68a09235601/src/xunit.runner.msbuild/build/xunit.runner.msbuild.props#L2-L9

https://github.com/xunit/xunit/blob/6ee07f1d4126c7a156318007e1a3a68a09235601/src/xunit.runner.msbuild/build/xunit.runner.msbuild.targets#L2-L27
