### ISSUE TITLE
VS2015 Enterprise/VS2017 RC coverage showing coverage on tests, not testees, when testing .net core application

### ISSUE THREAD

**Issue by Mardoxx** [xunit/xunit#1146]
I have my tests working in VS2015 using xUnit and the visualstudio runner.

When I go to `Test -> Analyse Code Coverage -> All Tests` the tests run, and complete, but the coverage shows on my test classes, not on my actual test code!

Any ideas?

my project.json is as follows:

```
{
  "version": "1.0.0-*",

  "testRunner": "xunit",

  "dependencies": {
    "dotnet-test-xunit": "2.2.0-preview2-build1029",
    "FluentAssertions": "4.19.0",
    "MyLibraryToTest": "1.0.0-*",
    "Microsoft.DotNet.InternalAbstractions": "1.0.1-beta-003206",
    "Moq": "4.7.0",
    "Newtonsoft.Json": "9.0.1",
    "xunit": "2.2.0",
    "xunit.runner.visualstudio": "2.2.0"
  },

  "frameworks": {
    "net452": { }
  }
}
```

**Comment by Mardoxx** [comment]
Just set up a new project with VS2017 RC, as soon as you reference a .net core application that targets .net framework coverage stops working.

**Comment by bradwilson** [comment]
We have nothing to do with code coverage. Please open this issue with the Visual Studio team.

**Comment by Mardoxx** [comment]
I apologise, that was my naivety. Very new to testing in C#, as in, today 😋.

Turns out code coverage is not supported for .net core applications!
https://developercommunity.visualstudio.com/content/problem/5813/cannot-get-test-coverage-for-net-core-projects.html

**Comment by PoppyPham** [comment]
No i using Net framwork 4.7.1 and xunit and got the same issue.
