### ISSUE TITLE
Multiple traits in theory causes xunit.runner.visualstudio to abort in .NET core (VS2017 RC4)

### ISSUE THREAD

**Issue by MichaelStromberg** [xunit/xunit#1147]
The VS runner aborts when encountering a theory with multiple traits.

**Current environment:**

- VS2017 RC4
- xunit 2.2.0
- xunit.runner.visualstudio 2.2.0
- .NET core 1.1

The following nonsensical test class works:

```cs
using Xunit;

namespace XunitTraitBug
{
    public class MultipleTraitsBug
    {
        [Theory]
        [Trait("ID", "A")]
        //[Trait("ID", "B")]
        //[Trait("ID", "C")]
        //[Trait("ID", "D")]
        [InlineData("dummy1")]
        [InlineData("dummy2")]
        [InlineData("dummy3")]
        [InlineData("dummy4")]
        public void CheckNotNull(string s)
        {
            Assert.NotNull(s);
        }
    }
}
```

However, when all the traits above are uncommented, the following text is output to the Tests Output window and no unit tests are displayed in the Test Explorer window:

```
------ Discover test started ------
[xUnit.net 00:00:00.7149134]   Discovering: XunitTraitBug
[xUnit.net 00:00:00.8792495]   Discovered:  XunitTraitBug
The active Test Discovery was aborted.
========== Discover test finished: 0 found (0:00:01.4736754) ==========
```

**Comment by MichaelStromberg** [comment]
It should be noted that running dotnet test seems to work with the example above - with or without multiple traits.

**Comment by MichaelStromberg** [comment]
Targeting .NET core 1.0 or 1.1 makes no difference in this case. The VS runner has the same issue in .NET core 1.0.

**Comment by bradwilson** [comment]
Closed for age.
