### ISSUE TITLE
Updating to XUnit 2.2.0 on a 4.6.2 project results in a System.TypeLoadException

### ISSUE THREAD

**Issue by luisabreu** [xunit/xunit#1149]
After updating my nuget package to v 2.2.0, I've ended up with the following exception:

System.TypeLoadException
Could not load type 'Xunit.Sdk.LongLivedMarshalByRefObject' from assembly 'xunit.execution.desktop, Version=2.2.0.3545, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'.
   at Xbehave.Execution.ScenarioRunnerFactory.Create(Object[] scenarioMethodArguments)
   at Xbehave.Execution.ScenarioOutlineRunner.<AfterTestCaseStartingAsync>d__8.MoveNext() in C:\projects\xbehave-net\src\Xbehave.2.Execution.desktop\ScenarioOutlineRunner.cs:line 81

**Comment by ravicini** [comment]
@luisabreu I ran in the same issue today, may I get to know your solution?

**Comment by luisabreu** [comment]
In my case, I've noticed that the exception was thrown from the XBehave assemblies (which I was using at the time - in other words, the problem was not related with XUnit, but with a 3rd party lib which hasn't been updated yet).

**Comment by ravicini** [comment]
I'm using XBehave too, so this exception is raised even with the newest XBehave library (2.1.4).
I'll move to the preview build, maybe I can fix this.
Thanks.

**Comment by Toixinhell** [comment]
I am also experiencing this Error. Are there any known solutions?

**Comment by ravicini** [comment]
@Toixinhell updating to the newest xBehave preview build worked for me.

**Comment by Toixinhell** [comment]
Any idea on where I could find a xBehave preview build?

**Comment by ravicini** [comment]
You can find the newest packages on nuget.org.
This is the latest preview pacakge: https://www.nuget.org/packages/Xbehave/2.2.0-beta0003-build685

In VS you can enable the "use preview builds" in the nuget client.

**Comment by Toixinhell** [comment]
I am sorry if I am wasting your time. But after using the Console on my project: 
System.TypeLoadException: Der Typ "Xunit.LongLivedMarshalByRefObject" in der Assembly "xunit.execution.desktop, Version=2.1.0.3179,

But I have 2.2.0 xUnit installed.

**Comment by bradwilson** [comment]
@Toixinhell Sounds like NuGet failed to add assembly binding redirects when updating the packages. https://msdn.microsoft.com/en-us/library/eftw1fys

**Comment by Toixinhell** [comment]
I found out that the tests accually run fine on MS Testing. We are using Ncrunch and it seems only when running Ncruch the tests fail. Will look into the settings to see if I can change this behavior.
Thanks again for all your help.

**Comment by biohazard999** [comment]
Changing the Framework utilisation type for Xunit v2+ to UseStaticAnalysis did the trick with the Preview Build of XBehave. So now its working in VSTest, NCrunch and CodeRush for Roslyn.

![2017-05-02 08_03_42-](https://cloud.githubusercontent.com/assets/653905/25605858/321cde5c-2f0e-11e7-8762-ca3470e495b9.png)
