### ISSUE TITLE
Test Runner Crashes.  Getting System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

### ISSUE THREAD

**Issue by mskarthickGH** [xunit/xunit#1151]
Hello,
I am trying to configure xuint 2.2.0 with VSTFS 2015 as part of CI build (Windows 2012 build servers) that reports code coverage numbers after build.   (VS2015, .net4.6.1, ClassLibrary proj) 
The build is failing with test runner crashing with below error if code coverage is Enabled.

```
 Starting test execution, please wait...
41:37.5509803Z Information: [xUnit.net 00:00:01.7371872]   Discovering: XXXXX.UnitTests
41:39.1320874Z Information: [xUnit.net 00:00:04.5358418]   Discovered:  XXXXX.UnitTests
41:39.3130962Z Warning: System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain. This can happen if the test(s) started a thread but did not stop it. Make sure that all the threads started by the test(s) are stopped before completion.
41:40.2671641Z Information: [xUnit.net 00:00:05.6658536]   Starting:    XXXXXX.UnitTests
41:43.7184139Z Warning: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
41:43.7204107Z    at XXXXXX.UnitTests.XXXXX.XXXXX_Test()
41:43.7214138Z    --- End of inner exception stack trace ---
```

Basically I added a CommandLine task to Build Definition and uses VSTest.console.exe to execute xunit tests. The command works just fine on my dev machine executing the test and generates the coverage file, but fails in Build server. (Runing test with VSTest task also results in same error) 

 However the build is successful with tests passing if CodeCoverage options is unchecked in Build definition. Please help.
Below is the logs (Anonmysed) please see attached for full logs. Runsetting file is very generic(also attached) 

[codecoverage.txt](https://github.com/xunit/xunit/files/821695/codecoverage.txt)
[Logs.txt](https://github.com/xunit/xunit/files/821696/Logs.txt)

`39:37.6100480Z Executing the following command-line. (workingFolder = E:xxxxxxxxxxx)
39:37.6120041Z "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe " E:\xxxxxxxx.UnitTests.dll /TestAdapterPath:E:xxxx\packages\xunit.runner.visualstudio.2.2.0\build\_common /EnableCodeCoverage /Settings:E:xxxxx\CodeCoverage.Runsettings /InIsolation
39:37.6160016Z Error message highlight pattern: 
39:37.6170043Z Warning message highlight pattern: 
39:37.6180067Z C:\Windows\system32\cmd.exe /c ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe " E:XXXXXXX.UnitTests.dll /TestAdapterPath:E:XXXXXXXXX\packages\xunit.runner.visualstudio.2.2.0\build\_common /EnableCodeCoverage /Settings:E:XXXXXX\CodeCoverage.Runsettings /InIsolation"
39:51.2289526Z Microsoft (R) Test Execution Command Line Tool Version 14.0.25420.1
39:51.2299533Z Copyright (c) Microsoft Corporation.  All rights reserved.
40:11.4157403Z Starting test execution, please wait...
41:37.5509803Z Information: [xUnit.net 00:00:01.7371872]   Discovering: XXXXX.UnitTests
41:39.1320874Z Information: [xUnit.net 00:00:04.5358418]   Discovered:  XXXXX.UnitTests
41:39.3130962Z Warning: System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain. This can happen if the test(s) started a thread but did not stop it. Make sure that all the threads started by the test(s) are stopped before completion.
41:40.2671641Z Information: [xUnit.net 00:00:05.6658536]   Starting:    XXXXXX.UnitTests
41:43.7184139Z Warning: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
41:43.7204107Z    at XXXXXX.UnitTests.XXXXX.XXXXX_Test()
41:43.7214138Z    --- End of inner exception stack trace ---
41:43.7234090Z    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
41:43.7244141Z    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
41:43.7264069Z    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
41:43.7274234Z    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
41:43.7294088Z    at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance)
41:43.7304143Z    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext()
41:43.7324091Z    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)`

I also notice similar error reported in bug (https://github.com/xunit/xunit/issues/1051)  Is it fixed ?
Am I missing something?

**Comment by bradwilson** [comment]
We do not test with, nor officially support, TFS. We will accept patches that fix issues with TFS.

We also have no relationship at all to the code coverage features. If code coverage is causing the crash, then this issue should be raised with the Visual Studio team.

**Comment by bradwilson** [comment]
Closed for age.
