### ISSUE TITLE
MessageSinkMessageExtensions.Dispatch calls MRES.Wait and throws ObjectDisposedException

### ISSUE THREAD

**Issue by AArnott** [xunit/xunit#1152]
As can be [seen here](https://ci.appveyor.com/project/AArnott/pinvoke/build/0.5.45+g3ffdfa6208), the xunit.runner.console 2.2.0 test runner experiences an internal error several times:

```
    [FATAL ERROR] System.ObjectDisposedException
      System.ObjectDisposedException : Cannot access a disposed object.
      Object name: 'The event has been disposed.'.
      Stack Trace:
        
        Server stack trace: 
           at System.Threading.ManualResetEventSlim.ThrowIfDisposed()
           at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
           at MessageSinkMessageExtensions.Dispatch[TMessage](IMessageSinkMessage message, HashSet`1 messageTypes, MessageHandler`1 callback)
           at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
           at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
        
        Exception rethrown at [0]: 
           at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
           at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
```

**Comment by AArnott** [comment]
It didn't repro for me locally -- just in appveyor.

**Comment by AArnott** [comment]
In fact the build appears to have simply hung now after reporting this error several times. My guess is the test runner's mixing up of MRES objects has led to it deadlocking itself.

**Comment by bradwilson** [comment]
The only usage of `ManualResetEventSlim` is within the AppVeyor reporter, so it makes sense that if the bug is there, it would require AppVeyor to reproduce. /cc @onovotny

**Comment by onovotny** [comment]
ugh...

We call it in one place:
https://github.com/xunit/xunit/blob/master/src/xunit.runner.reporters/AppVeyorClient.cs#L40

That's called by the handler here on AssemblyFinished:
https://github.com/xunit/xunit/blob/master/src/xunit.runner.reporters/AppVeyorReporterMessageHandler.cs#L30

@bradwilson I thought it was supposed to be using a different reporter instance per test assembly. I think this is failing because it's using the same reporter instance for multiple assemblies.

**Comment by bradwilson** [comment]
After discussion, @onovotny and I agree that the bug is in our AppVeyor support layer.

@AArnott As a work-around, we think you should be able to turn off assembly parallelism until we can get a fixed version for you.

**Comment by onovotny** [comment]
@AArnott 2.3 beta 1 should be in MyGet very shortly once the CI build finishes. Would love to get your confirmation that it solves this for you.

**Comment by AArnott** [comment]
Thanks for the fast response, folks. I've queued builds both to validate the workaround and the fix. I'll report here shortly.

**Comment by AArnott** [comment]
The latest CI build doesn't work. The hang is gone, but now I get [lots a errors](https://ci.appveyor.com/project/AArnott/pinvoke/build/0.5.51+g7ff7131b96) of a new kind:

```
    [FATAL ERROR] System.Collections.Generic.KeyNotFoundException
      System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
      Stack Trace:
        
        Server stack trace: 
           at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
           at MessageSinkMessageExtensions.Dispatch[TMessage](IMessageSinkMessage message, HashSet`1 messageTypes, MessageHandler`1 callback)
           at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
           at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
        
        Exception rethrown at [0]: 
           at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
           at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
      System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
      Stack Trace:
        
        Server stack trace: 
           at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
           at MessageSinkMessageExtensions.Dispatch[TMessage](IMessageSinkMessage message, HashSet`1 messageTypes, MessageHandler`1 callback)
           at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
           at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
        
        Exception rethrown at [0]: 
           at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
           at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
      System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
      Stack Trace:
        
        Server stack trace: 
           at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
           at MessageSinkMessageExtensions.Dispatch[TMessage](IMessageSinkMessage message, HashSet`1 messageTypes, MessageHandler`1 callback)
           at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
           at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
        
        Exception rethrown at [0]: 
           at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
           at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
```

**Comment by onovotny** [comment]
Looks like `ITestAssembly` isn't reference equatable. Just changed that to something else. Can you please test `2.3.0-beta1-build3557` when it's done building?

**Comment by AArnott** [comment]
OK, so that build "works". But the [parallel execution](https://ci.appveyor.com/project/AArnott/pinvoke/build/0.5.52+gdda9b625e5) is *much* slower than the [non-parallel one](https://ci.appveyor.com/project/AArnott/pinvoke/build/0.5.50+g0702570df0).

| Type | Duration
| -- | --
Parallel:  | 33.723s (23.435s)
Non-parallel: | 4.265s (9.103s)

**Comment by bradwilson** [comment]
I'd guess that the locks in the code are probably working against performance here.

**Comment by onovotny** [comment]
Okay, it's a start that we can work from though.

**Comment by onovotny** [comment]
@AArnott can you please check one thing - disable appdomains in the config. `appDomain` : `denied`
http://xunit.github.io/docs/configuring-with-json.html

What are the timings with/without parallelization there? I have a theory and it's not the locks.

**Comment by AArnott** [comment]
@onovotny do you mind sending a PR with your proposed change to my [appveyorFixTest](https://github.com/aarnott/pinvoke/tree/appveyorFixTest) branch? That will get it to build and you can tinker with it all you want.

**Comment by onovotny** [comment]
will do in the am

**Comment by bradwilson** [comment]
Also, how many CPUs do AppVeyor VMs have? If it's a low number, you should probably also force a maxThreads that's much higher. This could be especially painful if you had parallelism turned on with a CPU count of 1.

**Comment by AArnott** [comment]
I do think appveyor VMs only offer 1 cpu core. At least, when I use "msbuild /m" I don't get any parallelism I think. 

So I tried running this version locally on an 8 core machine. This is what I got:

Type | Timing
-- | --
Parallel | 12.519s (5.380s)
Non-parallel | 5.170s (14.064s)

That seems odd. I'm not even sure what the two numbers mean, but why would they "switch places" like that?

**Comment by AArnott** [comment]
@onovotny I can specify `-noappdomain` as a switch, which was easy enough I just made a change and ran it locally. I've updated my table above with the timing.

**Comment by onovotny** [comment]
Thanks, will try out a few things in the morning. For CI builds, you don't need an appdomain anyway. That's there to prevent dll locking when using VS and/or other runners like R#, NCrunch, etc.

**Comment by AArnott** [comment]
Given I can see that 2.3.0-beta1-build3557 is no slower than 2.2.0 (on a multi-core machine) we may be ok. But I'll have to disable parallel test execution on appveyor regardless since it really slows things down (at least in 2.3.0) so I don't actually need the fix and can stick with 2.2.0 for now.

**Comment by bradwilson** [comment]
The time numbers shown reflect accumulated time and clock time (the latter being the number in parenthesis).

If two things ran 100% in parallel, each taking 2s, then the totals would show `4s (2s)`. If the parenthetical number is larger than the accumulated time, then parallelization is absolutely working against you in terms of performance.

It's possible that at least part of this is because you have a large number of very small, very fast assemblies. Parallelization isn't free, and you may be experiencing that your scenario has a very high parallelization overhead, whereas most people (a few assemblies which take many seconds, or even minutes) have a very low cost of parallelization overhead.

**Comment by bradwilson** [comment]
An indicator that you have high parallelization overhead is the fact that the accumulated time is dramatically higher when parallelization is turned on. Most projects aren't like that.

Here is xUnit.net with parallelization on:

```
  === TEST EXECUTION SUMMARY ===
     test.xunit.assert            Total:  380, Errors: 0, Failed: 0, Skipped: 0, Time:  1.226s
     test.xunit.console           Total:   82, Errors: 0, Failed: 0, Skipped: 0, Time:  1.621s
     test.xunit.execution         Total:  797, Errors: 0, Failed: 0, Skipped: 0, Time:  9.027s
     test.xunit.runner.msbuild    Total:   25, Errors: 0, Failed: 0, Skipped: 0, Time:  1.128s
     test.xunit.runner.reporters  Total:   28, Errors: 0, Failed: 0, Skipped: 0, Time:  1.683s
     test.xunit.runner.tdnet      Total:   28, Errors: 0, Failed: 0, Skipped: 0, Time:  1.614s
     test.xunit.runner.utility    Total:  209, Errors: 0, Failed: 0, Skipped: 3, Time:  2.812s
                                         ----          -          -           -        -------
                            GRAND TOTAL: 1549          0          0           3        19.110s (13.301s)
```

And here it is with parallelization off:

```
  === TEST EXECUTION SUMMARY ===
     test.xunit.assert            Total:  380, Errors: 0, Failed: 0, Skipped: 0, Time:  0.774s
     test.xunit.console           Total:   82, Errors: 0, Failed: 0, Skipped: 0, Time:  0.647s
     test.xunit.execution         Total:  797, Errors: 0, Failed: 0, Skipped: 0, Time: 26.712s
     test.xunit.runner.msbuild    Total:   25, Errors: 0, Failed: 0, Skipped: 0, Time:  0.410s
     test.xunit.runner.reporters  Total:   28, Errors: 0, Failed: 0, Skipped: 0, Time:  0.674s
     test.xunit.runner.tdnet      Total:   28, Errors: 0, Failed: 0, Skipped: 0, Time:  0.708s
     test.xunit.runner.utility    Total:  209, Errors: 0, Failed: 0, Skipped: 3, Time:  3.384s
                                         ----          -          -           -        -------
                            GRAND TOTAL: 1549          0          0           3        33.309s (37.605s)
```

**Comment by AArnott** [comment]
Thank you both very much for responding so quickly on this. I know @onovotny offered to look into this, and I suspect there is some inefficiencies that could be improved, as enabling parallelism seems like it shouldn't cost this much, but given I have a reasonable workaround (don't use parallelism for many assemblies that are all cheap) I think we can close the issue now that the original issue has been fixed.
