### ISSUE TITLE
xml parameter for xunit.runner.visualstudio

### ISSUE THREAD

**Issue by thoean** [xunit/xunit#1154]
After upgrading form .NET Core 1.1 to .NET Core 1.1.1, and project.json to csproj (`dotnet migrate`), I can't run `dotnet test -xml result.xml` anymore. This switch seems to be invalid, message `MSB1001: Unknown switch`. I was unable to find good documentation how parameters are passed from msbuild to the test runner to eventually xUnit. The one thing I additionally tried was specifying a `.runsettings` file (see below), but this seems to be ignored.

Example `.runsettings` file, and running the tests with `dotnet test -s .runsettings`.
```xml
<?xml version="1.0" encoding="utf-8"?>  
<RunSettings>  
  <RunConfiguration>  
    <ResultsDirectory>abcdef</ResultsDirectory>  
  </RunConfiguration>
</RunSettings>
```

csproj details:

```xml
 <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <!-- .... -->
  </ItemGroup>
```

Thanks for pointers on what options I have to retrieve the xUnit XML output from `dotnet test`.

**Comment by brianengel** [comment]
It looks like they added [support for .runsettings back in 2014](https://xunit.codeplex.com/workitem/9914), but only support a handful of options including:

* MaxParallelThreads - integer
* MessageDisplay - None, Minimal, Diagnostic
* NameDisplay - Short, Full
* ParallelizeAssemblies - True, False
* ParallelizeTestCollections - True, False
* ShutdownAfterRun - True, False

Still haven't found a way to pass parameters to xUnit beyond those run settings or using the `--` syntax seen [here](https://github.com/dotnet/cli/pull/5181).

You can generate the old .trx files if you use `dotnet test --logger:trx`. I have yet to been able to find a logger that outputs in the xUnit XML format.

**Comment by thoean** [comment]
Thanks for the hint with the logger. Having the xUnit format would ease our transition, so if anyone knows that, thanks for sharing!

I'm also referencing https://github.com/Microsoft/vsts-tasks/issues/2126 where a similar switch is being discussed.

**Comment by adini81** [comment]
I am ran into the exact same issue. Thanks for the detailed explanation @thoean. Could someone please provide us with a solution?

-logger:trx is neither a solution nor a workaround on my side.

Thanks in advance...

**Comment by gruntster** [comment]
These links may help.  They cover the dotnet and vstest.console commands.  Worked for me.

https://github.com/Faizan2304/LoggerExtensions
https://github.com/Microsoft/vstest-docs/blob/master/docs/report.md

**Comment by erikest** [comment]
@adini81  check out my [answer](http://stackoverflow.com/questions/43333240/how-to-run-and-publish-netcore-xunit-tests-on-vsts-vs2017/43482928#43482928) on stackoverflow, it applies to VSTS, but the steps are the same for running local.

**Comment by RehanSaeed** [comment]
Use `dotnet xunit` instead of `dotnet test`. See [Getting Started with .NET Core](https://xunit.github.io/docs/getting-started-dotnet-core).

**Comment by bradwilson** [comment]
Closed for age.

**Comment by ViktorHofer** [comment]
is there any way to enable a xml logger since `dotnet xunit` is now deprecated?

**Comment by bradwilson** [comment]
`dotnet test` is able to generate TRX reports, which are XML.

There is no way today to get any of xUnit.net custom outputs from `dotnet test`.

**Comment by Matt-J-Hosking** [comment]
Will https://github.com/spekt/xunit.testlogger still work?

**Comment by TylerAP** [comment]
@bradwilson is there a new issue for this?

**Comment by bradwilson** [comment]
There are no plans to support this in VSTest. There are plans for better .NET Core support in 3.0 which will include XML output.
