### ISSUE TITLE
Update Getting Started for .NET Core

### ISSUE THREAD

**Issue by portaljacker** [xunit/xunit#1156]
Currently the documentation located [here](http://xunit.github.io/docs/getting-started-dotnet-core) is still completely blank other than the notice about it being available again soon.

The `New content will be added here when the new .NET CLI SDK runner is available.` part is a bit vague as it's hard for me to know when or if the exact thing you're referencing is available yet.

I'm assuming that since the SDK is out of RC and live that it should be.

Basically I'm wondering when the guide will be available again, as I wanted to try unit testing for the first time with my .NET Core project, but I've never used xunit (or any testing in VS) so a guide like the one supposed to be there would be a great help. Even [this guide](https://blog.jetbrains.com/dotnet/2017/02/21/resharper-net-core-unit-testing/) from Jetbrains doesn't help much as it only applies to projects using the now defunct project.json format.

**Comment by bradwilson** [comment]
We are working on a port of xunit.console for the .NET CLI SDK (note: this is different than the xunit.runner.visualstudio package). When this is available, then this new page will be restored with contents equivalent to https://xunit.github.io/docs/getting-started-desktop.html

**Comment by Ketrex** [comment]
Not sure why the old page was taken down, a simple notice at the top of the page that "an updated version is coming soon" would have been sufficient. Most of the previous information is still relevant, and extremely helpful. Now there's just nothing, which is a much less pleasant experience.

**Comment by bradwilson** [comment]
The old page had outdated content related to project.json. Leaving the old content makes no sense.

**Comment by Ketrex** [comment]
@bradwilson and I'm saying a simple "this page is outdated" posted at the top would have been sufficient to alert users to that problem. But the getting started page had a lot of useful information on how to write first tests and whatnot that is still relevant. Now there is literally zero documentation, api or resources for beginner developers to even start using xunit on core.  

Sometimes the historical (or outdated) information is better than none.

**Comment by portaljacker** [comment]
Exactly, I'm not exactly a beginner programmer, but I basically am when it comes to testing, especially with xunit and VS.

**Comment by portaljacker** [comment]
Whoops, closed it by accident.

**Comment by ScottKissinger** [comment]
For those not able to migrate to VS2017 yet, can the older documentation be brought back up or made available?

**Comment by portaljacker** [comment]
Judging by the response [here](https://github.com/xunit/xunit/issues/888#issuecomment-283977942), it looks like they won't because they don't want to support project.json if it's never going to be officially supported by Microsoft.

**Comment by portaljacker** [comment]
Looks like Microsoft has a updated [their guide](https://docs.microsoft.com/en-us/dotnet/articles/core/testing/unit-testing-with-dotnet-test) to use the csproj format.

**Comment by portaljacker** [comment]
In addition Resharper 2017.1 supports xUnit with .NET core for project.json and .csproj formats now: https://blog.jetbrains.com/dotnet/2017/04/03/meet-resharper-ultimate-2017-1/#UnitTesting

**Comment by portaljacker** [comment]
Not sure why it's not closed yet, but excellent work @bradwilson on the [new article](http://xunit.github.io/docs/getting-started-dotnet-core)! It looks great. Can't wait until I actually have time free to add it to my personal project.
