### ISSUE TITLE
Is there any way i can pass playlist /test list to the 'dotnet test'

### ISSUE THREAD

**Issue by radhikagadde** [xunit/xunit#1158]
I want to run same testlist/playlist for regression testing,so i wanted to create a playlist  and pass as a parameter to dotnet test.I don't see any option for this purpose through help.
Any other way through which i can acheive this?

**Comment by radhikagadde** [comment]
Any comments?

**Comment by bradwilson** [comment]
Closed for age.

**Comment by Sergi0Martin** [comment]
This would be useful. It has been a long time since the issue was opened; does anything exist now?

**Comment by bradwilson** [comment]
@Sergi0Martin This would be an issue to be opened against VSTest, not us. We do not control the command line for `dotnet test`.
