### ISSUE TITLE
VSTS test task unable to locate Nuget restored test adapter 

### ISSUE THREAD

**Issue by robpex** [xunit/xunit#1161]
According to the first comment at the bottom of the documentation (https://xunit.github.io/docs/getting-test-results-in-vsts.html), we shouldn't need to specify the custom test adapter path.  However, I found the opposite to be true.  Once I specified the custom path, it started running my tests.

**Comment by bradwilson** [comment]
This bug should probably be opened against VSTS.

**Comment by robpex** [comment]
Completely agree, sorry about that.  FYI -  https://github.com/Microsoft/vsts-tasks/issues/3776
