### ISSUE TITLE
TeamCity results not present when targeting .Net Framework in VS2017

### ISSUE THREAD

**Issue by JamesFenton** [xunit/xunit#1162]
When running tests under the `Microsoft.NET.Test.Sdk` v15.0.0 in Visual Studio 2017 with the .Net Core tooling, TeamCity results are not present when targeting the .Net Framework (4.6) using xUnit 2.2

Steps to reproduce:
```
PS C:\Temp> $env:TEAMCITY_PROJECT_NAME = "foo"
PS C:\Temp> dotnet new xunit
PS C:\Temp> dotnet restore
PS C:\Temp> dotnet test
Build started, please wait...
Build completed.

Test run for C:\Temp\bin\Debug\netcoreapp1.1\Temp.dll(.NETCoreApp,Version=v1.1)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.7228998] ##teamcity[testSuiteStarted name='Test collection f
or Temp.UnitTest1 (1)' flowId='ba43300101aa431480ba4dd45f401e26']
[xUnit.net 00:00:00.7696587] ##teamcity[testStarted name='Temp.UnitTest1.Test1'
flowId='ba43300101aa431480ba4dd45f401e26']
[xUnit.net 00:00:00.8003461] ##teamcity[testFinished name='Temp.UnitTest1.Test1'
 duration='5' flowId='ba43300101aa431480ba4dd45f401e26']
[xUnit.net 00:00:00.8142548] ##teamcity[testSuiteFinished name='Test collection
for Temp.UnitTest1 (1)' flowId='ba43300101aa431480ba4dd45f401e26']

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.8679 Seconds
```

Correct output (TargetFramework is `netcoreapp1.1`). But when I change the csproj to `<TargetFramework>net46</TargetFramework>` I get the following (no TeamCity output is present):

```
PS C:\Temp> dotnet restore
PS C:\Temp> dotnet test
Build started, please wait...
Build completed.

Test run for C:\Temp\bin\Debug\net46\Temp.dll(.NETFramework,Version=v4.6)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.3655305]   Discovering: Temp
[xUnit.net 00:00:00.5005984]   Discovered:  Temp
[xUnit.net 00:00:00.8716970]   Starting:    Temp
[xUnit.net 00:00:01.0364414]   Finished:    Temp

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.4920 Seconds
```

**Comment by JamesFenton** [comment]
My workaround is:
- copy the files from tools folder in the `xunit.runner.console` nuget package to a folder on our build agent
- add that folder to PATH
- call `xunit.console.exe Path\To\Test\Assembly.dll` from our build script

**Comment by adriaanp** [comment]
Also having this issue at the moment.

@JamesFenton my workaround is to use the dotnet xunit tool, `dotnet xunit`, I think then you don't need to do that crazy other stuff

**Comment by johncrim** [comment]
This should be re-opened - I'm still having this issue using dotnet 1.0.4, xunit 2.2, and .NET framework 4.7.

`dotnet xunit` doesn't appear to be an option for .NET framework 4.7 (it depends on Microsoft.NETCore.App 1.x), so I'm going with the workaround of using `xunit.runner.console` for the time being.

**Comment by JamesFenton** [comment]
@adriaanp `dotnet xunit` (xUnit 2.3+) does solve the problem, so I'm happy to close this issue.

@johncrim `dotnet xunit` seems to work fine for me when my test project targets `net461`. The `dotnet-xunit` package does depend on `netcoreapp1.0`, but my guess is that since it is a `DotNetCliToolReference` and not a `PackageReference`, it is ok.

**Comment by HubertPietruczuk** [comment]
@adriaanp Thank you, your solution solved my problem. To install dotnet-xunit i needed insert  `<DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta2-build3683" />` to my .csproj.
