### ISSUE TITLE
System.IO.File InvalidOperationException

### ISSUE THREAD

**Issue by jefffhaynes** [xunit/xunit#1165]
Hi, I'm attempting to debug xunit tests that are running against a UWP app.  I feel like they were working at some point in time but now every time I run them I get "Could not load type: System.IO.File", which is clearly coming from:

https://github.com/xunit/xunit/blob/master/src/xunit.runner.utility/Configuration/ConfigReader_Json.cs

The test project is a modified UWP test project where I've removed the MSTest stuff and added in xunit and xunit.runner.visualstudio.  For the life of me I can't figure out why xunit is unable to load System.IO.File.  I've also tired adding System.IO.FileSystem to the project.json explicitly and clearing the nuget cache.  Nothing seems to work.

**Comment by bradwilson** [comment]
Closed for age.
