### ISSUE TITLE
differences between 2.1 and 2.2 now cause test failures

### ISSUE THREAD

**Issue by minoseah629** [xunit/xunit#1166]
I just recently updated my test projects to use xunit 2.2. 

Before updating xunit to 2.2, a few of my unit tests depended on the test project app.config.  In the app.config, there is a key for our encryption algorithm 

Attached to this issue is a zip file containing two html output logs of the test execution.  The log are labelled to their respective version.  

With this version update, I do not see why this would cause a failure. I did see several new dependencies when updating to 2.2, which did not exist in 2.1.

[xunit 2.2 output.zip](https://github.com/xunit/xunit/files/848577/xunit.2.2.output.zip)

**Comment by minoseah629** [comment]
To add onto this issue, I did some more investigation on my end. 

The System under Test uses this method. 

`(Hashtable)WebConfigurationManager.GetSection("Keys");`

This method is provides the data from the unit test project app config for this 

`<configuration>
  <configSections>
    <section name="Keys" type="System.Configuration.SingleTagSectionHandler" />
    <Keys KeyIv="fakeKey" Key128="fakedata" />
`

If I comment out this line from the app.config with xunit v2.1 , I get the same result as when it ran in xunit v 2.2
![image](https://cloud.githubusercontent.com/assets/1980068/24014422/43dd8a24-0a5b-11e7-8aad-617cc099becb.png)
Below is what should be after putting it back. 
![image](https://cloud.githubusercontent.com/assets/1980068/24014469/6fc94b64-0a5b-11e7-90e3-469640328ae6.png)

Could the issue be around handling app.config and xunit?

**Comment by bradwilson** [comment]
From [the release notes](https://xunit.github.io/release-notes/2017-02-19.html):

> The minimum version of .NET required for desktop CLR unit tests is now .NET 4.5.2. This change was made since both 4.5 and 4.5.1 are now out of official support. This change only affects your unit test projects; your production code is still free to target lower versions of .NET. (Note: Because we support netstandard1.1, you will still be able to link your desktop unit test projects that target 4.5 and 4.5.1, but they will not show up in the Visual Studio runner, and they will not get desktop features like AppDomain isolation. Make sure you upgrade the .NET version of your projects before installing the new NuGet packages.)

One of the "desktop" feature you'll get if you do this wrong is the lack of configuration file support (which requires App Domains).

Undo the NuGet package upgrade, upgrade your test project(s) to .NET 4.5.2 (or, better, something even newer), then re-update the NuGet packages.
