### ISSUE TITLE
Exception deserializing messages from vstest.console.exe 

### ISSUE THREAD

**Issue by borrrden** [xunit/xunit#1168]
Similar to https://github.com/xunit/xunit/issues/492 but for v2 tests and only for UWP (so far)

I have a test suite that I am attempting to run in a CI environment for UWP.  The tests pass fine in the test explorer in Visual Studio, but when I try to run from the command line it is a different story.  

I use the following command:
`vstest.console.exe /InIsolation /Platform:x64 /TestCaseFilter:"slow!=true" <package name>`

The test runner app launches, and I am treating to a series of messages like:

> Error occurred while RecordStart for test case xxxxx: System.ServiceModel.FaultException:  The formatter threw an exception while trying to deserialize to message:  There was an error while trying to deserialize parameter http://tempuri.org/:newTestResults.  The InnerException message was 'There was an error deserializing the object of type System.Collections.Generic.IEnumerable\`1[[Microsoft.VisualStudio.TestPlatform.ObjectModel.TestResult, Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].  StringConverter cannot convert from System.Guid'.  Please see InnerException for more details.
&nbsp;&nbsp;&nbsp;&nbsp;at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
&nbsp;&nbsp;&nbsp;&nbsp;at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyRuntimeOperation operation, Object[] ins, Object[] outs, TimeSpan timeout)
&nbsp;&nbsp;&nbsp;&nbsp;at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation0
&nbsp;&nbsp;&nbsp;&nbsp;at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
--- End of stack trace from previous location where exception was thrown ---
&nbsp;&nbsp;&nbsp;&nbsp;at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
&nbsp;&nbsp;&nbsp;&nbsp;at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
&nbsp;&nbsp;&nbsp;&nbsp;at Microsoft.VisualStudio.TestPlatform.TestExecutor.RocksteadyExecutor.SendTestRunStats Change(TestRunStats testRunStats, IEnumerable\`1 newTestResults, IEnumerable\`1 inProgressTestCases)
&nbsp;&nbsp;&nbsp;&nbsp;at Microsoft.VisualStudio.TestPlatform.Core.TestRunCache.SendResults()
&nbsp;&nbsp;&nbsp;&nbsp;at Microsoft.VisualStudio.TestPlatform.Core.TestRunCache.CheckForCacheHit()
&nbsp;&nbsp;&nbsp;&nbsp;at Microsoft.VisualStudio.TestPlatform.Core.TestRunCache.OnTestStarted(TestCase testCase)
&nbsp;&nbsp;&nbsp;&nbsp;at Microsoft.VisualStudio.TestPlatform.Core.TestExecutionManager.SendTestCaseStart (TestCase testCase)
&nbsp;&nbsp;&nbsp;&nbsp;at Xunit.Runer.VisualStudio.TestAdapter.VsExecutionSink.TryAndReport(String actionDescription, ITestCase testCase, Action action)

**Comment by borrrden** [comment]
P.S. This is an installation of Visual Studio Community 2017 (15.0.0+26228.9) with Visual Studio Tools for Universal Windows Apps (15.0.26228.00) and on [the project](https://github.com/couchbase/couchbase-lite-net/blob/c0ddefbf8c44c43c6bbf059c35e339369d272499/src/Couchbase.Lite.Tests.UWP/Couchbase.Lite.Tests.UWP.csproj) xunit 2.2 and xunit.runner.visualstudio 2.2 [are used](https://github.com/couchbase/couchbase-lite-net/blob/c0ddefbf8c44c43c6bbf059c35e339369d272499/src/Couchbase.Lite.Tests.UWP/project.json#L7-L8)

**Comment by bradwilson** [comment]
Please re-open with a repro project.
