### ISSUE TITLE
Disable parallel test runs in dotnet test

### ISSUE THREAD

**Issue by codito** [xunit/xunit#1169]
_From @lukasz-pyrzyk on March 17, 2017 14:39_

How to disable parallel run for xunit tests? 

I found similar issues (#1447, #401), but they look out of date. There is no `-diagnostics`` flag.

Should I use `-s` and create some configuration file?

## Steps to reproduce
`dotnet test Project.csproj -parallel None`
or
`dotnet test Project.csproj -parallel none`

## Expected  behavior
Disable parallel execution of the tests

## Actual behavior
```
MSBUILD : error MSB1001: Unknown switch.
Switch: -parallel
```

## Environment data
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

_Copied from original issue: dotnet/cli#6059_

**Comment by codito** [comment]
I think you can use `parallelizeAssembly` and `parallelizeTestCollections` options in xunit.runner.json (https://xunit.github.io/docs/configuring-with-json.html). A sample project with xunit.runner.json is available here: https://github.com/Reactive-Extensions/Rx.NET/blob/develop/Ix.NET/Source/Tests/Tests.csproj.

It is possible to pass arguments to adapters by using `dotnet test -- xunit.parallel=xyz` for example. Copied this issue here to discuss if this is an interesting feature for xunit adapter to support.

**Comment by bradwilson** [comment]
There is currently no supported way to pass flags to `dotnet test`. You must use [configuration files](https://xunit.github.io/docs/configuring-with-json.html), instead. Set `"parallelizeTestCollections": false`.

**Comment by cateyes99** [comment]
You can disable parallel test runs by passing `p:ParallelizeTestCollections` in this way `dotnet test test.csproj -p:ParallelizeTestCollections=false`

**Comment by bradwilson** [comment]
This feature is adequately supposed by configuration files and `dotnet xunit`.

**Comment by jzabroski** [comment]
@bradwilson https://xunit.net/docs/running-tests-in-parallel.html does not mention `dotnet xunit`.  I'm running into a bizarre issue with `xunit 2.4` where it looks like Theories are running in parallel.

**Comment by mattfrear** [comment]
@jzabroski I remember reading somewhere on github that `dotnet xunit` is no longer supported, and that we have to use `dotnet test`.

**Comment by jzabroski** [comment]
> @jzabroski I remember reading somewhere on github that `dotnet xunit` is no longer supported, and that we have to use `dotnet test`.

I think my particular confusion is when using the Resharper Test Runner for Visual Studio.  They appear to limit parallelism to the assembly level.  Just mentioning this in case anyone else gets tripped up.  In particular, when you have Theories, it doesnt seem to respect CollectionDefinition + Collection.

Only replying now because I hit the problem again today, and don't remember what I did to work around it last time.

**Comment by bradwilson** [comment]
The Resharper runner is custom code written by them without using our runner libraries, so as our feature sets evolve, they will continue to drift further and further out of date. I don't expect them to be able to run v3 projects at all once we ship.

**Comment by jzabroski** [comment]
I figured out the issue. I had a File.Create without disposal of the stream and that was not isolated per test.
