### ISSUE TITLE
xunit.runner.visualstudio adds content to nuget package produced by test project.

### ISSUE THREAD

**Issue by hubuk** [xunit/xunit#1170]
MSBuild prop files located in [visualstudio.xunit/build/](https://github.com/xunit/visualstudio.xunit/tree/e5e6a5eeda84887aefe6b6bfa753a811ddb79ef6/build) add xunit libraries as a content to the referencing project. This causes inclusion of the xunit libraries in the resulting test project nuget package when targeting classic .Net Framework.
In order to copy xunit libraries to output directory without including them in test project nuget packege \<Content> elements could be changed to \<None>.
The same way xunit.execution.desktop.dll is being copied in [xunit.core.props](https://github.com/xunit/xunit/blob/4089905f0e7ba13160f6048b32b3a3988eb203dc/src/xunit.core/build/xunit.core.props#L4-L8)

**Comment by hubuk** [comment]
PR available at [#107](https://github.com/xunit/visualstudio.xunit/pull/107).

**Comment by onovotny** [comment]
Curious as to why you're creating nuget packages of a test project to begin with?

**Comment by hubuk** [comment]
I am distributing my test packages next to my libraries. Test packages contain reusable behavior specification for all types in my libraries.

For example:
[DisposableBaseSpecification{TSut}](https://github.com/Leet/Corelib/blob/1f6ff3076e38664f98715b4181a6d9cb7fcc49d1/test/Leet.Tests.Corelib/Specifications/DisposableBaseSpecification%7BTSut%7D.cs) is a generic test class template that has some tests defined:
```C#
public abstract class DisposableBaseSpecification<TSut>
  : ObjectSpecification<TSut>
  where TSut : DisposableBase
```
When I create a type in other library that inherits from `DisposableBase`, let's say `ConcreteDisposable`, I can create a specification for it:
```C#
public abstract class ConcreteDisposableSpecification<TSut>
  : DisposableBaseSpecification<TSut>
  where TSut : ConcreteDisposable
```
This class inherits all tests from `DisposableBaseSpecification` and add some more specific for `ConcreteDisposable`.
All I have to do to make tests runnable is to create a non abstract class:
```C#
public class ConcreteDisposableTests
  : ConcreteDisposableSpecification<ConcreteDisposable> { }
```

Using this technique I am able to provide reusable test packages side-by-side with my libraries.
It also allows me to create basic specifications for standard types and then use them to check my implementation.
As a basic example see  [IEqualityComparerSpecification{TSut}](https://github.com/Leet/Corelib/blob/1f6ff3076e38664f98715b4181a6d9cb7fcc49d1/test/Leet.Tests.Corelib/Specifications/IEqualityComparerSpecification%7BTSut%2CT%7D.cs) as a simple set of behaviors for every IEqualityComparer{T} implementation.

**Comment by onovotny** [comment]
I would recommend using `PrivateAssets="all"` on your xUnit references then. You're likely going to hit other issues as there's complex dependencies in the targets. The test assembly/runner needs to bring its own versions.

So `<PackageReference Include="xunit" version="2.2.0" PrivateAssets="all" />`, etc, for each xUnit reference. Then xUnit, the runner and its content won't be part of your package...

**Comment by hubuk** [comment]
Already checked that. Setting `PrivateAssets="All"` does not work. Resulting package still contains xunit assemblies as a content. I think the reason is that [xunit.runner.visualstudio.desktop.props](https://github.com/xunit/visualstudio.xunit/blob/e5e6a5eeda84887aefe6b6bfa753a811ddb79ef6/build/xunit.runner.visualstudio.desktop.props) is still executed for my project. `PrivateAssets="All"` hides xunit assets from consumers of my package, not rom the package itself.

Obviously, `ExcludeAssets="Build"` works. As a result there are no xunit files inside my nuget package, because the entire `build` folder of `xunit.runner.visualstudio` nuget is being ignored. This of course causes absence of all the files listed in [xunit.runner.visualstudio.desktop.props](https://github.com/xunit/visualstudio.xunit/blob/e5e6a5eeda84887aefe6b6bfa753a811ddb79ef6/build/xunit.runner.visualstudio.desktop.props) missing from the output directory.

Anyway, is there any reason for keeping dll files as `<Content>`? Is there something more than copying them to output directory?

**Comment by hubuk** [comment]
Some additional info:
1. `<Content>` items trigger following warnings during the build with `<GeneratePackageOnBuild>True</GeneratePackageOnBuild>`:
```
warning : Issue: Assembly outside lib folder.
warning : Description: The assembly 'content\xunit.runner.visualstudio.testadapter.dll'
is not inside the 'lib' folder and hence it won't be added as reference when the package
is installed into a project.
warning : Solution: Move it into the 'lib' folder if it should be referenced.
```
and 7 similar warnings for other files.

2. Trick with `ExcludeAssets="Build"` does work in VS but does not work for `dotnet test`. Execution fails with the following message:
```
The path '(...)\bin\Debug\net452' specified in the 'TestAdapterPath' does not contain
any test adapters, provide a valid path and try again.
```

**Comment by bradwilson** [comment]
Agreed that `<Content>` was wrong and `<None>` is right. It's a subtle thing that doesn't bite you until it really bites you. :-p

**Comment by ewertonline** [comment]
Hi,

I just set <IsPackable>true</IsPackable> in .csproj and work´s

**Comment by trullock** [comment]
For future people who end up here because its the top result in google,

When you find your class library with a reference to xunit doesnt generate a nupkg on build when  `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>` is set, you need to add

`<IsPackable>true</IsPackable>`

to your project file

**Comment by bradwilson** [comment]
Test projects are never intended to be packable.

**Comment by trullock** [comment]
adding a reference to xunit != a project with tests in it

**Comment by bradwilson** [comment]
> adding a reference to xunit != a project with tests in it

It is, actually.

If you're writing extensibility points, there are different packages for you to reference. We definitely do things in `xunit.core` (which `xunit` references) which are based on the assumption that you are writing unit tests. The `xunit.extensibility.core` and `xunit.extensibility.execution` are designed for people extending xUnit.net, and `xunit.runner.utility` is for people writing runners.

**Comment by trullock** [comment]
OK so I need to reference `FactAttribute` and `Assert`, so I've changed to referencing `xunit.core` and `xunit.assert` which makes sense. You still get the same nuget behaviour though. Am I still not referencing the intended things?

I'm not arguing about the default behaviour, simply trying to be helpful in providing the info on what to do when you're in one of many possible scenarios where you want this nuget behaviour to happen.

**Comment by bradwilson** [comment]
If you're writing extensions, and not unit tests, then referencing `xunit.extensibility.core` instead of `xunit.core` is the correct behavior. You can continue to reference `xunit.assert` (it does not have any of the "unit testing" assumptions that come with referencing the `xunit.core` NuGet package).
