### ISSUE TITLE
Running test with multiple xunit projects in a solution

### ISSUE THREAD

**Issue by couven92** [xunit/xunit#1174]
In a solution with more than once XUnit test project, the Visual Studio test runner is only able to run the first xunit project in the solution. The xunit test runner then fails and prints the following to the test output:
> The active test run was aborted. Reason: Unable to communicate with test host process.

Installed XUnit packages (verfied as being the same version on both test projects):
```
Package: Microsoft.NET.Test.Sdk, Version: 15.0.0
Package: xunit, Version: 2.2.0
Package: xunit.runner.visualstudio, Version: 2.2.0
```

Visual Studio:
```
Microsoft Visual Studio Community 2017
VisualStudio/15.0.0-RTW+26228.4
```

.NET Core SDK: 
```
>dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

Installed .NET Core Runtime: `Version 1.1.1`

**Comment by couven92** [comment]
If it helps, here's the Visual Studio test runner output:
```
------ Run test started ------
[xUnit.net 00:00:00.4085073]   Discovering: Project1
[xUnit.net 00:00:00.4909859]   Discovered:  Project1
[xUnit.net 00:00:00.5303576]   Starting:    Project1
[xUnit.net 00:00:00.6400431]   Finished:    Project1
[xUnit.net 00:00:00.4103602]   Discovering: Project2
[xUnit.net 00:00:00.5088196]   Discovered:  Project2
[xUnit.net 00:00:00.5463868]   Starting:    Project2
The active test run was aborted. Reason: Unable to communicate with test host process.
========== Run test finished: 3 run (0:00:06,7388473) ==========
```

**Comment by bradwilson** [comment]
That error message is not from xUnit.net, it's from VSTest. The bug should be surfaced with them.

**Comment by couven92** [comment]
okay... which repository? I'll move it there

**Comment by couven92** [comment]
Nevermind... I think I found it... Closing this issue.
