### ISSUE TITLE
System.IO.FileLoadException: Could not load file or assembly Microsoft.Extensions.DependencyModel, Version=1.1.0.0 in VS2015

### ISSUE THREAD

**Issue by hardhub** [xunit/xunit#1175]
I got this error when run "dotnet test" in command line.

Adding "Microsoft.Extensions.DependencyModel": "1.1.0" to test project directly (project.json) gives different error:

dotnet-test-xunit.exe - System Error
Exception Processing Message 0xc0000005
Parameters 0x000007FEFCEB819C 0x000007FEFCEB819C 0x000007FEFCEB819C 0x000007FEFCEB819C

**Comment by bradwilson** [comment]
Please provide a repro project.

Also note that we don't support project.json projects, so please project an MSBuild-based repro.

Thanks!

**Comment by hardhub** [comment]
I think it can be a reason why it does not work.. because it is exactly project.json project... VS2017 is just released so we had to analyze how to better migrate to it first... 
If it can be repeated I will come back with this issue...

But it is still strange way... What is option for users using VS2015 and xunit? Previously xunit worked relatively good (before latest updates).

**Comment by hardhub** [comment]
I can confirm in VS2017 with csproj all works fine...
But as I said there are no options for developers using VS2015 .net core projects (based on project.json).
Strange decision.. very strange...

**Comment by bradwilson** [comment]
Please re-open with a repro project.
