### ISSUE TITLE
[Question] How to Determine and Report Skipped Tests

### ISSUE THREAD

**Issue by shaggygi** [xunit/xunit#1176]
Is there a mechanism to determine how many skipped tests are within a project/solution?  Meaning, is there something available to report back in Test Explorer or elsewhere to inform the number of skipped tests?

In addition, is there a widget to report the number of skipped tests in a CI platform like VSTS?

Thanks in advance for any help.

**Comment by bradwilson** [comment]
If you're asking about getting a count after a run is complete, then the report formats include that information. Here is an example from the XML report from xUnit.net itself:

```xml
<assembly
    name="C:\Dev\xunit\xunit\test\test.xunit.assert\bin\Release\net452\test.xunit.assert.DLL"
    environment="64-bit .NET 4.0.30319.42000 [collection-per-class, parallel (16 threads)]"
    test-framework="xUnit.net 99.99.99.0"
    run-date="2017-03-21"
    run-time="10:55:56"
    config-file="C:\Dev\xunit\xunit\test\test.xunit.assert\bin\Release\net452\test.xunit.assert.dll.config"
    total="380"
    passed="380"
    failed="0"
    skipped="0"
    time="2.077"
    errors="0">
```

As for VSTS, AFAIK they only support TRX reports, which we do not directly support ourselves (as such, I have no idea what their capabilities are).

**Comment by shaggygi** [comment]
@bradwilson thanks, this should get me started.
