### ISSUE TITLE
Unable to execute tests

### ISSUE THREAD

**Issue by sheltonc** [xunit/xunit#1178]
We've been trying to get the runner working and always end up with the same error:

When invoking as follows:

dotnet test-xunit .\TestProject.csproj

or

dotnet test-xunit .\TestProject\bin\Debug\netcoreapp1.1\TestProject.dll

we get the following error:

System.InvalidOperationException: Could not find any of the following assemblies: xunit.execution.dotnet.dll, xunit.execution.MonoAndroid.dll, xunit.execution.MonoTouch.dll, xunit.execution.iOS-Universal.dll, xunit.execution.universal.dll, xunit.execution.win8.dll, xunit.execution.wp8.dll

I've attached the sample project.
[xUnitSample.zip](https://github.com/xunit/xunit/files/863779/xUnitSample.zip)

Can you please help with this?

Thanks,

Chris

**Comment by bradwilson** [comment]
I don't know what `dotnet test-xunit` is. That's not something that we provide.

**Comment by sheltonc** [comment]
Oh, ok. I'm able to invoke the runner with that command. Everything I've read online suggests that's how it's done.

How do you suggest we invoke the runner from the command line?

We want to invoke xunit in our CI process and be able to pass in the -xml flag so we can publish results.

Cheers,

Chris

**Comment by bradwilson** [comment]
> How do you suggest we invoke the runner from the command line?

If you are using `xunit.runner.visualstudio` version 2.2.0, then you should be able to use `dotnet test`. If you're not sure how the project should be set up, either create a new xUnit.net testing project from Visual Studio 2017 (File > New > Project > Visual C# > .NET Core > xUnit Test Project), or use `dotnet new -t xunit` from the command line.

> We want to invoke xunit in our CI process and be able to pass in the -xml flag so we can publish results.

This is not currently supported. `dotnet test` is a thin wrapper around the Visual Studio test console, and the options available are only the ones offered by the Visual Studio team. That means the only output format supported today is TRX. You can use `--logger "trx;OutputFileName.xml"` command line switch with `dotnet test`. For more information on supported switches, type `dotnet test --help`.

We are working on a new runner for .NET Core that will support all the existing switches from our console runner (including `-xml`). There will be an announcement on our [xUnit.net Twitter feed](https://twitter.com/xunit) when this new runner is available.

**Comment by sheltonc** [comment]
So there's no way to access xunit on the command line under. Net core?

**Comment by bradwilson** [comment]
Only `dotnet test` today.

**Comment by bradwilson** [comment]
This is now supported by `dotnet xunit`.
