### ISSUE TITLE
dotnet test command detect the unit tests via .net CLI, however its unable to run the test cases leading in "Timeout Error".

### ISSUE THREAD

**Issue by adityaas99** [xunit/xunit#1181]
![dotnet_test_commad](https://cloud.githubusercontent.com/assets/18609230/24294476/e28c390e-1096-11e7-87fa-cf27b8aca0db.png)

**Comment by RolandPheasant** [comment]
I get the same problem when building on appveyor. However it runs perfectly on my local machine

**Comment by bradwilson** [comment]
Please re-open with a repro project.
