### ISSUE TITLE
xunit dotnet test runner locks files between discovery and execution

### ISSUE THREAD

**Issue by mgravell** [xunit/xunit#1183]
which is a problem for meta-programming code; let me explain - all of the following should be visible [at this commit of protobuf-net](https://github.com/mgravell/protobuf-net/commit/a5d15ffeb29ad970fdaa06bc8d242019c694e949)

One of the use-cases of protobuf-net is to ask it to spit out dlls, so I have tests that do exactly this. There is a restriction in `AssemblyBuilder` / `ModuleBuilder` that it will **refuse** to put dlls anywhere else (if you specify a path rather than just a filename, it shouts at you).

The first time I run my tests, all is good; the following works, for example:

    C:\code\protobuf-net\src\protobuf-net.Test>dotnet test --filter "FullyQualifiedName=FX11.FX11_Program.Execute

which after a few seconds outputs:

```
[xUnit.net 00:00:09.9192852]   Finished:    protobuf-net.Test

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
```

and all is good. However, if we re-run the test (note I've added some diagnostic code while investigating this):

`Oops, OrderSerializer.dll is locked; try looking in process explorer (sysinternals)`

Now; `OrderSerializer.dll` is one of the files that we generate during the test run *after* the line of code that is complaining. If we look in sysinternals, it is being locked by `testhost.x86.exe`.

My suspicion is that the test runner is probing all the dlls to look for tests (reasonable), and keeping them open *even if they aren't test files*. This means that we can't regenerate the file.

I'm open to advice here; if there is a magic way of excluding files from probing, then great! point me at it! I tried enabling shadow copy via the json file, but it appears to be ignored - and indeed, adding gibberish to the file suggests that it isn't looking at the json file. Alternatively, if there is a good place I can write some cleanup code at either the start or end of the test run (at a point when it won't be locked), then: great! Again, to emphasize: the MS framework implementation **will not let me** write the files to anywhere other than the active folder (although I'm not 100% whether it is the fusion probe folder vs the working path, etc).

Alternatively, the test runner could close the files if they aren't useful?

Or maybe `dotnet test` needs a nuclear "always clean the folder" option? does that exist?

Some or all of this may be going to the wrong place, so feel free to suggest better places to throw this...

**Comment by bradwilson** [comment]
Preventing file locks is why we use app domains (specifically, the shadow copy feature of app domains). App domains are not available in .NET Core, so we cannot prevent file locks.

**Comment by mgravell** [comment]
Hmmm, awkward indeed; at a pragmatic level, though, is there any way to avoid it taking them in the first place? An optional white-list / black-list on files to check? Or is that just not a thing?

**Comment by mgravell** [comment]
Or of course the other option being shadow copy; if that was working, it wouldn't matter that the transient files were locked, as they will cease to exist at the end of the test run...

**Comment by bradwilson** [comment]
Here is the core of the answer: the `xunit.runner.visualstudio` package is merely a plugin to the VSTest system, and the issues here are pretty much entirely out of our control.

> Is there any way to avoid it taking them in the first place? An optional white-list / black-list on files to check? Or is that just not a thing?

VSTest chooses what to probe, not us.

> the other option being shadow copy

Without access to app domains, this isn't really an option. And yet again, in this case in particular, it would be VSTest that would be responsible for this action.

**Comment by mgravell** [comment]
Ah, OK; sounds like I'm prodding the wrong folks, then; not a problem, cheers; by any chance do you know if there's a github project for that component?

**Comment by bradwilson** [comment]
https://github.com/microsoft/vstest

**Comment by mgravell** [comment]
thanks
