### ISSUE TITLE
How to run net452 tests when assemblies are delay signed?

### ISSUE THREAD

**Issue by rykr** [xunit/xunit#1184]
Or should I not be using delay signing?

Seems to work ok with netstandard1.6 and netcoreapp1.1   but with net452 it simply fails to discover the tests.

**Comment by bradwilson** [comment]
"Sign them, or do not. There is no try." - Yoda

**Comment by bradwilson** [comment]
Or use `sn -Vr`. https://msdn.microsoft.com/en-us/library/k5b5tt23%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396

**Comment by onovotny** [comment]
You could try disabling appdomains and shadow copying, but you'll have file locking issues if done from within VS.

**Comment by rykr** [comment]
Thanks.
