### ISSUE TITLE
License URL on NuGet.org for xunit 2.2.0 is broken

### ISSUE THREAD

**Issue by Eilon** [xunit/xunit#1186]
Go to https://www.nuget.org/packages/xunit and click on the license link; it takes you to https://raw.githubusercontent.com/xunit/xunit/master/license.txt, which doesn't exist.

Looks like maybe this commit broke it? https://github.com/xunit/xunit/commit/c3cd3f9bce49daca7636ee41f82cc07c61089e21

**Comment by bradwilson** [comment]
Thanks. I was trying to convince Github to parse my license file (which failed :-p) and this was an unintended consequence.

Fixed with 86b08ae87a77901c2e7e22abeb06d73db3e69c1b
