### ISSUE TITLE
Add extensibility hook for test class constructor argument resolution

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1190]
Spurred on by:

<img src="https://cloud.githubusercontent.com/assets/16944/24474947/2cc30936-1483-11e7-9dbc-381d96c2019d.png" width="299" />

This is a moderately frequent ask (usually under the cover of supporting DI) with a thoroughly unhappy solution: new test framework. It seems like we should be able to point to some assembly-level, class-level, etc. attribute that allowed just an override of the logic for providing constructor arguments.

**Comment by koenigst** [comment]
Suggested solution:

`public class UnitTest1 : ITestServiceProvider<ServiceProviderImpl>`

This would work analogous to fixtures but would use the `IServiceProvider` interface to resolve `ctor` arguments.

**Comment by bradwilson** [comment]
I believe this is part of the larger #1738 issue, so I'm closing this as a duplicate.
