### ISSUE TITLE
Results xml produced incorrectly when an compressed octet is present in the output.

### ISSUE THREAD

**Issue by safern** [xunit/xunit#1192]
When there is an octet present in the output the test results xml would be produced incomplete. I hit this issue while running [this tests](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs#L281-L297).

**Comment by bradwilson** [comment]
Please provide a simple repro. Thanks!

**Comment by safern** [comment]
Hi @bradwilson, so if I run the following test
```cs
[Fact]
public async Task GetAsync_DefaultAutomaticDecompression_ContentDecompressed()
        {
            using (var client = new HttpClient())
            {
                using (HttpResponseMessage response = await client.GetAsync("http://corefx-net.cloudapp.net/Deflate.ashx"))
                {
                    Assert.Equal(HttpStatusCode.OK, response.StatusCode);
                    string responseContent = await response.Content.ReadAsStringAsync();
                    _output.WriteLine(responseContent);
                    VerifyResponse(responseContent); // contains asserts that verify the response
                }
            }
        }
```

where output is `ITestOutputHelper` object initialized by xunit in the test class constructor.

The response content will have a compressed octet the test execution will print out an error saying: 
error: '', hexadecimal value 0x0B, is an invalid character.

And then the results xml file will be malformed (incomplete) like the following one:

```xml
<?xml version="1.0" encoding="utf-8"?>
<assemblies timestamp="03/31/2017 15:31:27">
<assembly>
<collection [summary of the test execution for the collection]>
<test name="System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_DefaultAutomaticDecompression_ContentDecompressed()" type="System.Net.Http.Functional.Tests.HttpClientHandlerTest" method="GetAsync_DefaultAutomaticDecompression_ContentDecompressed" time="0.0486984" result="Fail">
        <output><![CDATA[
```

So as you can see it would break when printing the output and will not close the corresponding tags so the xml would be malformed. If the test fails it wouldn't print the stack trace on the xml either.

**Comment by snerks** [comment]
Certain control characters are not allowed in XML documents. Hex `0x0B` is one of those characters.

As verification, could you try to replace `0x0B` in your `responseContent` with empty string (before the call to `_output.WriteLine`) and retry?

**Comment by bradwilson** [comment]
Please re-open w/ a simple repro if this is still an issue.
