### ISSUE TITLE
MemberData should support C# 7.0 tuples

### ISSUE THREAD

**Issue by svick** [xunit/xunit#1193]
Currently, the data provided for `MemberData` has to be a collection of `object[]`. This means the code can look like this:

```c#
public static IEnumerable<object[]> GetData()
{
    yield return new object[] { "A", 1 };
    yield return new object[] { "ABC", 3 };
}
```

It would be nice if `MemberData` also supported C# 7.0 tuples, which would make the code shorter (and also slightly more strongly typed):

```c#
public static IEnumerable<(string, int)> GetData()
{
    yield return ("A", 1);
    yield return ("ABC", 3);
}
```

This would probably require quite a lot of reflection gymnastics in the implementation, but in my opinion, it would be worth it.

**Comment by jamesqo** [comment]
@svick There was a related discussion about this here: https://github.com/xunit/xunit/issues/951. It seems like the owner doesn't want to support ValueTuple because it's not in .NET 4.5. I think reflection would allow us to get around this without taking a dependency on the type though, so that doesn't seem like it should be a barrier to this feature.

**Comment by tuespetre** [comment]
I would even be happy if MemberData would support `IEnumerable<T>` on a theory method accepting a single argument of `T`.

**Comment by bradwilson** [comment]
@tuespetre You should return `TheoryData<T>`. It implements `IEnumerable<object[]>` for you, and with the single-T version, you can send it a range of values:

```csharp
public static TheoryData<int> MyTheoryData =>
    new TheoryData<int> { 4, 8, 15, 16, 23, 42 };

[Theory]
[MemberData(nameof(MyTheoryData))]
public void MyTheory(int value) { ... }
```
```

**Comment by tuespetre** [comment]
But muh LINQ and `yield return` 🤷‍♂️

**Comment by bradwilson** [comment]
We will not be supporting this.

**Comment by dorgold** [comment]
@bradwilson can i ask why you won't support it? It makes the syntax much cleaner and add allow us to perform some build time type validations.

**Comment by bradwilson** [comment]
Because it breaks the 11+ year old contract of how data enumeration works.

**Comment by IanKemp** [comment]
So how about we instead add a new `MemberDataTupleAttribute` class?

**Comment by bradwilson** [comment]
@IanKemp This should be relatively easy to write given the extensibility model in xUnit.net.

**Comment by ogxd** [comment]
For those interested here is an example of such an implementation:
```csharp
public class MemberDataTupleAttribute : MemberDataAttributeBase
{
    public MemberDataTupleAttribute(string memberName) : base(memberName, Array.Empty<object>()) { }

    protected override object[] ConvertDataItem(MethodInfo testMethod, object item)
    {
        if (item is ITuple tuple)
        {
            object[] output = new object[tuple.Length];
            for (int i = 0; i < tuple.Length; i++)
            {
                output[i] = tuple[i];
            }

            return output;
        }

        throw new InvalidOperationException("Member data must be of type ValueTuple or Tuple");
    }
}
```

**Comment by JohnLBevan** [comment]
FYI: As of Xunit v3 the above can now be achieved OOTB; example:

```
public static IEnumerable<TheoryDataRow<string, bool>> MyProperty
{
    get
    {
        yield return ("hello", true);
        yield return ("world", false);
    }
}

[Theory]
[MemberData(nameof(MyProperty))]
public void TestHelloWorld(string word, bool expected)
{
    Assert.Equal(expected, word == "hello");
}
```

Related info: https://xunit.net/docs/getting-started/v3/whats-new#theory-data-rows-and-metadata

**Comment by bradwilson** [comment]
With modern C# you can simplify it even further:

```csharp
public static IEnumerable<TheoryDataRow<string, bool>> MyProperty =>
[
    ("hello", true),
    ("world", false),
]
```
