### ISSUE TITLE
xunit does not respect BaseIntermediateOutputPath MSBuild Property

### ISSUE THREAD

**Issue by chuckeng-isp** [xunit/xunit#1194]
It appears that the xunit targets expect the "obj" intermediate folder to be in the project folder, and not at $(BaseIntermediateOutputPath) as it should.

**Comment by bradwilson** [comment]
Aside from an unreleased project (dotnet-xunit), we have zero things that care about `obj` folders. Can you provide some more context (and perhaps a repro project)?

**Comment by chuckeng-isp** [comment]
Sure. For a build, you do not want your outputs delivered into your source tree. For .NET projects, it is this way by default for legacy reasons. The way to do this is to move the base intermediate and output paths.

When I move the path, which moves where the intermediates get built, then I get these errors:

error CS0246: The type or namespace name 'Fact' could not be found (are you missing a using directive or an assembly reference?)

I believe that the targets file is automatically importing something based on what gets placed in the "obj" folder. When I look at the output after a build, I see a .targets and .props file, in addition to the intermediate binaries and outputs.

**Comment by chuckeng-isp** [comment]
I was able to get this to work, although flaky, by putting this in the first property group of the project file:

    <BaseIntermediateOutputPath>..\..\build_output\obj\$(AssemblyName)\</BaseIntermediateOutputPath>
    <OutputPath Condition="'$(OutputPath)'=='' ">..\..\build_output\bin\</OutputPath>

So, I will call it quits...
