### ISSUE TITLE
run tests remotely

### ISSUE THREAD

**Issue by loothood** [xunit/xunit#1195]
Hi!
I need to run tests via Visual Studio remotely.
For example, I develop my tests at my computer and when I run the Test via Visual Studio, the Test must be copied to remote virtual machine and run on it.
So, How I can do this?
Does the xunit provide such functionality?
I've a lot of googleit, but I can't find information. 
If you have an a link where describe how to, I'll be very grateful!

**Comment by bradwilson** [comment]
No, xUnit.net does not offer this functionality.

**Comment by loothood** [comment]
bradwilson, thank you for your answer!
