### ISSUE TITLE
VS 2017 Test Explorer does not descover the tests

### ISSUE THREAD

**Issue by amdnaji** [xunit/xunit#1197]
Dears
As you can see from below image.I've downloaded the aspnet/Logging project for testing purposes but Test Explorer does not discover any tests. The test projects already contain `**xunit.runner.visualstudio**` 2.2.0. All tests worked find when i am using CLI. I tried also to follow the steps from your docs with no luck
https://xunit.github.io/docs/getting-started-desktop.html#run-tests-visualstudio
![capture](https://cloud.githubusercontent.com/assets/8853403/24729967/7c31b972-1a69-11e7-8932-0f5c0291e7c4.PNG)

**Comment by bradwilson** [comment]
(As an aside, you took a screenshot of the Hosting project, not the Logging project)

I looked at the Logging project and it is using netcoreapp2.0. We will not officially support that until it RTMs.

**Comment by amdnaji** [comment]
My mistake but I updated the picture :)
Thanks a lot for your comment.
