### ISSUE TITLE
Copy assemblies for dynamic loading.

### ISSUE THREAD

**Issue by hardhub** [xunit/xunit#1198]
We dynamically load some assemblies in our code.
To get success xunit test should execute code of these assembles.
Normally such assemblies are copied to output directory during build.
And all is OK but not with xUnit... 
When test is executed assembly location is something like this:
C:\Users\Administrator\AppData\Local\Temp\4c30a280-0900-4002-874b-a65591ef7c9e\4c30a280-0900-4002-874b-a65591ef7c9e\assembly\dl3\11289531\10e73523_73aed201\Some.dll

And this folder does not contain any of required assemblies (referenced to test project).

So for now we cannot use xunit test framework for our needs and have to switch to another framework.
Any chance to solve it?

**Comment by bradwilson** [comment]
This is because of shadow copying, which is used to prevent locking of DLLs.

You can [disable shadow copying with a configuration file](https://xunit.github.io/docs/configuring-with-json.html).

**Comment by hardhub** [comment]
Thanks.. It works... I will summarize:

1) Add a new JSON file to root of your test project. Name the file xunit.runner.json
2) Put into this file the following content:
```
{
   "shadowCopy": false
}
```
3) Change for this file "copy to output" option to _"Copy if newer"_.
