### ISSUE TITLE
dotnet test does not discovers tests on mac

### ISSUE THREAD

**Issue by smadala** [xunit/xunit#1199]
## Description
xUnit does not discover tests if test project depends on production project which have dependency on bunch of packages when `ulimit -n` is 256. Without any exception/error.

sample project: [MacOsNoDiscovery578.zip](https://github.com/Microsoft/vstest/files/831863/MacOsNoDiscovery578.zip)

Original issue: https://github.com/Microsoft/vstest/issues/578

## Expected behavior
Error message should display.

## Actual behavior
> No test is available in <path_to_test_source_dll>. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again

## Work around
 Increase `ulimit -n` value.  Eg: ` $ echo 'ulimit -n 4096' | sudo tee -a /etc/profile` and restart machine.

**Comment by bradwilson** [comment]
This is a limitation of OS X. What are you expecting us to do about it?

**Comment by rnowosielski** [comment]
I am not the creator but I did experience the same problem hence I can speak to what I think: Either throwing a meaningful error, when the limit is reached, or even better closing the used resources. I haven't yet had time to look through the code but my assumption is that you don't need so many of the system resources at the same time, do you?

**Comment by bradwilson** [comment]
This message:

> No test is available in /.../bin/Debug/netcoreapp1.1/SomeProject.Tests.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.

Isn't from us. It's from VSTest. This is before any of our code is running.

**Comment by smadala** [comment]
@bradwilson 
From https://github.com/Microsoft/vstest/issues/578#issuecomment-291886826.
At https://github.com/xunit/visualstudio.xunit/blob/2.2/xunit.runner.visualstudio.desktop/VsTestRunner.cs#L432.
There is exception which is not getting reported to testplatform.

**Comment by rich-ware** [comment]
I am having the same issue here. I changed the ulimit to 4096 but it did not work for me. Please advise on how I can resolve. 
![screen shot 2017-09-08 at 3 22 04 pm](https://user-images.githubusercontent.com/2387404/30229999-dcdae63a-94a9-11e7-85fd-6ea18b9acf12.png)

Thanks in advance!

**Comment by bradwilson** [comment]
External issue.

**Comment by b-zurg** [comment]
Doing the file limit change workaround broke my mac. It's really not good advice. 

To revert it I had to delete the new file created and edit out the ulimit command from `etc/profile`

Just for anyone else who broke their mac following this advice.
