### ISSUE TITLE
Question: unsupported `--no-build` option

### ISSUE THREAD

**Issue by gabrielweyer** [xunit/xunit#1201]
I'm trying to migrate to `dotnet xunit` from `dotnet test`. I'm building the assemblies first and then running the tests using the `--no-build` option.

```dos
dotnet xunit -configuration RELEASE --no-build
```

Output error:

```dos
Detecting target frameworks in <redacted>.UnitTests.csproj...
Building for framework netcoreapp1.1.1...
  <redacted> -> <redacted>\bin\RELEASE\netcoreapp1.1.1\<redacted>.dll
  <more-projects>
  <redacted>.UnitTests -> <redacted>\bin\Debug\netcoreapp1.1.1\<redacted>.UnitTests.dll
Running .NET Core tests for framework netcoreapp1.1.1...
error: unknown option: --no-build
   at Xunit.ConsoleClient.CommandLine.Parse(Predicate`1 fileExists) in C:\projects\xunit\src\xunit.console\CommandLine.cs:line 323
   at Xunit.ConsoleClient.CommandLine..ctor(IReadOnlyList`1 reporters, String[] args, Predicate`1 fileExists) in C:\projects\xunit\src\xunit.console\CommandLine.cs:line 24
   at Xunit.ConsoleClient.Program.EntryPoint(String[] args) in C:\projects\xunit\src\xunit.console\Program.cs:line 66
```

Configuration

- VS 2017 latest
- Win 10 latest 64 bit
- `xunit` `2.3.0-beta1-build3642`
- `dotnet-xunit` `2.3.0-beta1-build3642`
- `dotnet --version` `1.0.2`
- `dotnet`

```dos
Version  : 1.1.0
Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86
```

**Comment by bradwilson** [comment]
That's correct, there is no `--no-build` option. The reason is that we have to inject properties to get specific kinds of files to build, so a build is required.

**Comment by gabrielweyer** [comment]
So if I have multiple test projects leveraging `xunit` and those test projects take different options (such as different output files via `-xml`) I'll have to rebuild all the dependencies for each test project?

**Comment by bradwilson** [comment]
The `-xml` switch automatically appends the test framework ID if you are multi-targeting (f.e., if you pass `-xml foo.xml`, and you're targeting `net452` and `netcoreapp1.0`, then it will generate `foo-net452.xml` and `foo-netcoreapp1.0.xml`).

The dependencies should not need to be re-built (MSBuild does a good job of know when to build something or not). The unit test assemblies would need to be re-built, though, because of the additional properties.

**Comment by gabrielweyer** [comment]
Thanks for your answers and thanks for a great testing framework! I noticed that `dotnet xunit` is significantly faster than `dotnet test`.
