### ISSUE TITLE
Unable to discover test in Visual Studio for project built with .net 4.5

### ISSUE THREAD

**Issue by amanbha** [xunit/xunit#1202]
Repro steps:
1. Create a class library project in vS 2015 for .net 4.5.
2. Add xunit 2.2.0 nuget package and  a test case.
3. Add nuget package xunit.runner.visualstudio.
4. Open Test Explorer (go to Test > Windows > Test Explorer) and build.
5. In the output window (Ctrl-Alt-O), change the output to Test ((Shift-Alt-S)), you will see: Skipping: ClassLibrary1 (Could not find any of the following assemblies: xunit.execution.desktop.dll)

So it cannot discover tests, looked at nuget package xunit.extensibility.execution.2.2.0, it doesn't have xunit.execution.desktop.dll for net standard but has xunit.execution.dotnet.dll, it has xunit.execution.desktop.dll for 4.5.2 only. How can make it work (other than building for 4.5.2) for 4.5 as IO have requirements to build agains 4.5 only.?

**Comment by bradwilson** [comment]
2.2 requires .NET 4.5.2 at minimum. You have two choices:

* Upgrade to .NET 4.5.3 for the unit tests
* Downgrade to xunit.net 2.1

**Comment by bradwilson** [comment]
BTW, your production code can stay at 4.5.  Only the unit tests need to be updated.

**Comment by bradwilson** [comment]
This is documented in the release notes: https://xunit.github.io/release-notes/2017-02-19.html

**Comment by amanbha** [comment]
Sounds good, thanks for a quick response.
