### ISSUE TITLE
xUnit.net 2.2.0 does not honor some xunit.runner.json settings

### ISSUE THREAD

**Issue by lextm** [xunit/xunit#1203]
For a recent commit (and its following) of Obfuscar, xUnit.net test cases failed to be executed both locally and on AppVeyor,

https://github.com/lextm/obfuscar/tree/f6cf38fffb4fd6230bbbbf7601dd8ba618d19085

The failure log at AppVeyor can be found,

https://ci.appveyor.com/project/lextm/obfuscar/build/1.0.60

You can see that for the test suites, I have to disable parallel running in previous working CI rounds,

https://github.com/lextm/obfuscar/blob/f6cf38fffb4fd6230bbbbf7601dd8ba618d19085/Tests/xunit.runner.json

The failure indicates that parallel running is still chosen by the runner. Any hint on how I should get it resolved? The 2.3 prerelease bits also suffer this.

**Comment by bradwilson** [comment]
According to the logs:

> %xunit20%\xunit.console.x86 "C:\projects\obfuscar\Tests\bin\Debug\ObfuscarTests.dll" -appveyor

xunit.runner.json requires xUnit.net 2.1. You should stop using AppVeyor's built-in runner and instead download and use the current RTM (2.2) runner instead.

**Comment by lextm** [comment]
Switching to xUnit.net console runner 2.2.0 from NuGet by using a custom test script,

https://github.com/lextm/obfuscar/blob/f6afb8d94c94902c3d562909251e248b1cbfccc5/test.bat

However, the problem still remains,

https://ci.appveyor.com/project/lextm/obfuscar/build/1.0.73

I can also reproduce this locally，

1. Clone the whole repo.
2. Run pack.bat and then test.bat.

**Comment by lextm** [comment]
Just did some further investigation and found that xUnit.net console runner does disable parallelism and honor the settings. The test failure was caused by something else. So it is a false alarm and please ignore.
