### ISSUE TITLE
dotnet-xunit: support common dotnet cli parameters

### ISSUE THREAD

**Issue by natemcmaster** [xunit/xunit#1204]
Most build-in dotnet commands use these common command line args.

```
-f|--framework        Target framework
-c|--configuration    Configuration
```

This will likely lead new users to this error:
```
error: unknown option: -c
   at Xunit.ConsoleClient.CommandLine.Parse(Predicate`1 fileExists)
   at Xunit.ConsoleClient.CommandLine..ctor(IReadOnlyList`1 reporters, String[] args, Predicate`1 fileExists)
   at Xunit.ConsoleClient.Program.EntryPoint(String[] args)
```

dotnet-xunit is annoyingly different (single-dash with no short-option,  `-framework` and `-configuration`). Please consider aligning with dotnet-CLI conventions.

**Comment by bradwilson** [comment]
We prefer consistency between our runners, rather than consistency with `dotnet` (which we predate by a facade, tbh). :smile:

**Comment by bradwilson** [comment]
I'll leave this open to add undocumented support for these overly-dashed options. 😉

**Comment by natemcmaster** [comment]
Thanks @bradwilson
