### ISSUE TITLE
dotnet-xunit: fail fast when command line args are invalid

### ISSUE THREAD

**Issue by natemcmaster** [xunit/xunit#1205]
Using dotnet-xunit 2.3.0-beta1-build3642

`dotnet xunit --some-bad-arg` can take a long time to fail because the arguments aren't validated until after msbuild /t:Build completes. Also, errors are nested in lots of output, not easily visible.

Example:
![image](https://cloud.githubusercontent.com/assets/2696087/24885999/97d3745e-1e06-11e7-9da2-c3abd9b243be.png)

**Comment by bradwilson** [comment]
We are not going to fix this. It's optimizing for an exception scenario, and it would cause us to have to duplicate all command line parsing and validation.
