### ISSUE TITLE
Add Assert.Equal overload for System.ArraySegment<T>

### ISSUE THREAD

**Issue by drewnoakes** [xunit/xunit#1206]
```csharp
Assert.Equal(default(ArraySegment<byte>), default(ArraySegment<byte>));
```

This assertion fails because the resolved overload (`Equal<U>(U,U)`) treats the `ArraySegement<T>` as `IEnumerable` (which it is) however the enumerator throws for `default(ArraySegment<byte>)`.

```text
System.InvalidOperationException : The underlying array is null.
   at System.ArraySegment`1.System.Collections.IEnumerable.GetEnumerator()
```

**Comment by jamesqo** [comment]
I don't think the best solution would be to add a new overload just for `ArraySegment`. Instead, we should try to fix [this method](https://github.com/xunit/assert.xunit/blob/master/Sdk/AssertEqualityComparer.cs#L170) which is calling `GetEnumerator` and assuming it will not throw an exception.

**Comment by bradwilson** [comment]
Resolved via PR.
