### ISSUE TITLE
Cannot add dotnet-xunit to project generated with dotnet new xunit

### ISSUE THREAD

**Issue by alastairs** [xunit/xunit#1207]
## Repro
```
> dotnet --version
1.0.3
> mkdir dotnet-xunit-repro
> dotnet new xunit -o test\repro -n repro
> dotnet add test\repro\repro.csproj package dotnet-xunit
```

There are no significant differences between this project and the example one [listed in the documentation](https://xunit.github.io/docs/getting-started-dotnet-core.html) AFAICT. I'm running Windows 10 Anniversary Update. I also see the same behaviour when using the `classlib` template to `dotnet new`.

<details>
<summary>cat .\repro.csproj</summary>
&lt;Project Sdk="Microsoft.NET.Sdk"&gt;

  &lt;PropertyGroup&gt;
    &lt;TargetFramework&gt;netcoreapp1.1&lt;/TargetFramework&gt;
  &lt;/PropertyGroup&gt;

  &lt;ItemGroup&gt;
    &lt;PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" /&gt;
    &lt;PackageReference Include="xunit" Version="2.2.0" /&gt;
    &lt;PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" /&gt;
  &lt;/ItemGroup&gt;

&lt;/Project&gt;
</details>

## Expected
The package is successfully added to the project and I can use `dotnet xunit`.

## Actual
The package is not added to the package as it is considered incompatible with netcoreapp1.1:
```
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

  Writing %USERPROFILE%\AppData\Local\Temp\tmp3D87.tmp
info : Adding PackageReference for package 'dotnet-xunit' into project '.\repro.csproj'.
log  : Restoring packages for D:\test\repro\repro.csproj...
info :   CACHE https://api.nuget.org/v3-flatcontainer/dotnet-xunit/index.json
error: Unable to resolve 'dotnet-xunit' for '.NETCoreApp,Version=v1.1'.
error: Package 'dotnet-xunit' is incompatible with 'all' frameworks in project '.\repro.csproj'.
```

`dotnet xunit`, predictably, results in
```
No executable found matching command "dotnet-xunit"
```

**Comment by bradwilson** [comment]
You're missing the DotNetCliToolReference from the documentation.

**Comment by alastairs** [comment]
I added that manually and still saw the same issue. Sorry I missed that in the report.

Sent from myPhone

On 15 Apr 2017, at 18:57, Brad Wilson <notifications@github.com<mailto:notifications@github.com>> wrote:


You're missing the DotNetCliToolReference from the documentation.

**Comment by alastairs** [comment]
Ok, I think what may have happened was that I was trying to use `dotnet xunit` from outside the specific test project, or perhaps hadn't successfully `dotnet restore`d something. It's working now - sorry for the inconvenience 😄
