### ISSUE TITLE
xUnit test discovery fails in VS 2017 when System.Configuration reference is added

### ISSUE THREAD

**Issue by Hambik** [xunit/xunit#1210]
Full csproj file is here.
[UnitTest.csproj.txt](https://github.com/xunit/xunit/files/922481/UnitTest.csproj.txt)

If the following line is removed:
`<PackageReference Include="System.Configuration" Version="4.4.0-beta-24913-02" />`
the tests are getting discovered just fine.

This package is added from the following nuget repository:
`https://dotnet.myget.org/F/dotnet-core/api/v3/index.json`

Tried xunit latest (2.3... ) and stable 2.2 versions both. Also played with target frameworks and made sure The `%TEMP%\VisualStudioTestExplorerExtensions` folder is cleaned up.

**Comment by bradwilson** [comment]
I have no idea how you're getting this to build. When I attempted to run `dotnet restore`, I got the following error:

```
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Unable to resolve 'System.Configuration (>= 4.4.0-beta-24913-02)' for '.NETCoreApp,Version=v1.1'. [C:\Dev\1\1.csproj]
```

Also, looking on NuGet, the `System.Configuration` package has been unlisted: https://www.nuget.org/packages/System.Configuration

**Comment by bradwilson** [comment]
Please re-open with a repro project.
