### ISSUE TITLE
xunit runner shows test as external if debugType is 'full'

### ISSUE THREAD

**Issue by wgross** [xunit/xunit#1211]
Switching the debug type (VS2017 project properties > build > advanced) of a test project from portable to full to allow coverage analysis with open cover made all test in the project show up as 'External' in the test explorer.

I'm using:
xunit 2.2.0 + xunit.runner.visualstudio 2.2.0

**Comment by bradwilson** [comment]
This is a limitation of VSTest. When we ask it to map methods to source files, under .NET Core, it only supports portable PDBs, not full PDBs. Please open this issue with the VSTest team: https://github.com/microsoft/vstest

**Comment by bradwilson** [comment]
This looks like it might be related: https://github.com/Microsoft/vstest/issues/622

**Comment by wgross** [comment]
Thanx... I'll look at it
