### ISSUE TITLE
Proposal: Adding helper classes for ClassData

### ISSUE THREAD

**Issue by jamesqo** [xunit/xunit#1214]
## Background

Currently, there's a lot of boilerplate/cruft that you need to write when implementing a new class for `ClassData`. Here is a code snippet showing some classes of that nature I was writing recently:

```cs
    public class Int32_Data : IEnumerable<object[]>
    {
        public IEnumerator<object[]> GetEnumerator()
            => Enumerable.Range(-5, count: 11)
            .Select(i => new object[] { i })
            .GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
    }

    public class Polynomial_Data : IEnumerable<object[]>
    {
        public IEnumerator<object[]> GetEnumerator()
            => new[]
            {
                new object[] { (X() + X(-1)) * (X() + X(-1)) },
                new object[] { X(3) - 1 },
                new object[] { 4 * X(2) + 4 * X() + 1 }
            }
            .Concat(new Term_Data()
                .Select(array => new object[] { (Polynomial)(Term)array[0] }))
            .AsEnumerable().GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
    }

    public class Term_Data : IEnumerable<object[]>
    {
        public IEnumerator<object[]> GetEnumerator()
            => new[]
            {
                new object[] { X() },
                new object[] { 3 * X() },
                new object[] { 4 * X(-1) },
                new object[] { -2 * X(2) },
                new object[] { -9 * X(-2) },
                new object[] { 0 * X() } // This is equivalent to (Term)0
            }
            .Concat(new Int32_Data()
                .Select(array => new object[] { (Term)(int)array[0] }))
            .AsEnumerable().GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
    }

    public class Term_Term_Data : IEnumerable<object[]>
    {
        // Generate all possible pairs of Terms in Term_Data.
        public IEnumerator<object[]> GetEnumerator()
            => new Term_Data().SelectMany(
                array1 => new Term_Data().Select(
                    array2 => array1.Concat(array2).ToArray())).GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
    }
```

- You can see that for each one of the classes, you have to write out the explicit interface implementation for `IEnumerable.GetEnumerator()`.
- There is also a lot of noise since you have to wrap all of your parameters in `new object[] { }`.
  - This additionally makes it hard to reuse one `ClassData` in another; for example, to reuse `Int32_Data` in `Term_Data` I have to write `new Int32_Data().Select` and cast back the objects to `int`.
- Finally, since `GetEnumerator()` returns an `IEnumerator<T>` and not an `IEnumerable<T>`, you always have to add a `GetEnumerator()` at the end of the method.

## Proposal

I recently added super-simple `ClassData<T>` and `ClassData<T1, T2>` helper classes to my codebase. Here's how they look like:

```cs
    public abstract class ClassData<T> : IEnumerable<object[]>
    {
        public abstract IEnumerable<T> GetData();

        IEnumerator<object[]> IEnumerable<object[]>.GetEnumerator()
        {
            foreach (T datum in GetData())
            {
                yield return new object[] { datum };
            }
        }

        IEnumerator IEnumerable.GetEnumerator() => this.AsEnumerable().GetEnumerator();
    }

    public abstract class ClassData<T1, T2> : IEnumerable<object[]>
    {
        public abstract IEnumerable<(T1, T2)> GetData();

        IEnumerator<object[]> IEnumerable<object[]>.GetEnumerator()
        {
            foreach ((T1, T2) datum in GetData())
            {
                yield return new object[] { datum.Item1, datum.Item2 };
            }
        }

        IEnumerator IEnumerable.GetEnumerator() => this.AsEnumerable().GetEnumerator();
    }
```

Here is the new code for my ClassDatas:

```cs
    public class Int32_Data : ClassData<int>
    {
        public override IEnumerable<int> GetData() => Enumerable.Range(-5, count: 11);
    }

    public class Polynomial_Data : ClassData<Polynomial>
    {
        public override IEnumerable<Polynomial> GetData()
            => new[]
            {
                (X() + X(-1)) * (X() + X(-1)),
                X(3) - 1,
                4 * X(2) + 4 * X() + 1
            }
            .Concat(new Term_Data().GetData().Select(t => (Polynomial)t));
    }

    public class Term_Data : ClassData<Term>
    {
        public override IEnumerable<Term> GetData()
            => new[]
            {
                X(),
                3 * X(),
                4 * X(-1),
                -2 * X(2),
                -9 * X(-2),
                0 * X() // This is equivalent to (Term)0
            }
            .Concat(new Int32_Data().GetData().Select(i => (Term)i));
    }

    public class Term_Term_Data : ClassData<Term, Term>
    {
        public override IEnumerable<(Term, Term)> GetData()
            => from t1 in new Term_Data().GetData()
               from t2 in new Term_Data().GetData()
               select (t1, t2);
    }
```

- There is a lot less noise and all traces of `object[]` have disappeared from sight.
- Accessing the strongly-typed data from another data is easy, just do `GetData()`.
- It's no longer necessary to write out the explicit interface implementation for `IEnumerable.GetEnumerator()`.
- `GetData()` returns an `IEnumerable<T>` instead of an `IEnumerator<T>`, so no more suffixing everything with `GetEnumerator()`.

Do these helper classes seem like a good idea to add to xUnit?

**Comment by marcind** [comment]
Have you looked at [`TheoryData`](https://github.com/xunit/xunit/blob/master/src/xunit.core/TheoryData.cs)? There's also an example of combining sets here: https://github.com/xunit/samples.xunit/blob/master/TheoryDataExamples/MatrixTheoryData.cs. That should get you most of the way.

As for your proposal, it looks like it's using `ValueTuple`, which is not available in .Net 4.5, the lowest version that xunit supports at the moment.

**Comment by jamesqo** [comment]
@marcind The problem with `TheoryData` is it is imperative, e.g. you have to call `Add()` on everything instead of just returning an enumerable, and you can't access the strongly-typed data after you've generated it. I have found myself having to work around the latter many times, e.g. [here](https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/tests/ImmutableArrayTest.cs#L40-L42).

If the type is not available in .NET 4.5, perhaps we can add a new library dependency to xunit.core (e.g. titled xunit.core.net47) that allows xunit to take advantage of new API additions, which will only be installed if the target platform supports ValueTuple. (Alternatively, we could wait until xunit stops supporting .NET 4.5, but my feeling is that would take a while.)

**Comment by bradwilson** [comment]
I would prefer this to be done as changes to TheoryData rather than introduce a new class. Please open a new issue with suggested changes to TheoryData.
