### ISSUE TITLE
Add attribute to disable sync context for the entire assembly

### ISSUE THREAD

**Issue by davidfowl** [xunit/xunit#1215]
So I can avoid sprinkling ConfigureAwait everywhere.

**Comment by bradwilson** [comment]
We will not support this.

Why do you think you need Configures wait with xUnit.net?

**Comment by bradwilson** [comment]
Assuming this is a thread starvation issue because you're testing improperly written async code, there is a workaround: specify unlimited threads (which will not use the thread limited sync context).
