### ISSUE TITLE
dotnet xunit from a different path

### ISSUE THREAD

**Issue by ayende** [xunit/xunit#1216]
I have a few projects that are using xunit, and I followed the guidance here: http://xunit.github.io/docs/getting-started-dotnet-core

However, I can only run them using: `dotnet xunit` from the test directory itself.

With `dotnet test`, I can do:

    dotnet test -p tests/FastTests/FastTests.csproj
    dotnet test -p tests/SlowTests/SlowTests.csproj

When I try the same with `dotnet xunit`, I get:

     No executable found matching command "dotnet-xunit"

Any idea how I get this to work at the project level?

**Comment by bradwilson** [comment]
This is a limitation of the .NET CLI. Please file the issue there.

**Comment by bradwilson** [comment]
Closing as External.
