### ISSUE TITLE
[dotnet xunit] support passing parameters to MSBuild

### ISSUE THREAD

**Issue by ppekrol** [xunit/xunit#1217]
Hi,

`dotnet test` supports passing MSBuild parameters like this:
```
"C:\Program Files (x86)\dotnet\dotnet.exe" test --configuration Release /p:Platform=x86
```
but with
```
"C:\Program Files (x86)\dotnet\dotnet.exe" xunit -configuration Release /p:Platform=x86
```

I'm getting: **Unexpected parameter: /p:Platform=x86**

Can this be supported?

**Comment by bradwilson** [comment]
Unfortunately, there's no way to support this today, because the choice of bitness of the .NET Core executable is entirely dependent on whether you installed 32-bit or 64-bit dotnet.exe (and which one you choose to run).

**Comment by ppekrol** [comment]
Brad, thanks for answering.

I was referring more to the ability to pass the custom parameters to MSBuild e.g. /p:CustomParameterName=Value

Probably a Platform example was a bit unfortunate in this case.

**Comment by bradwilson** [comment]
We don't intend to offer this as a feature; instead, we will be supporting `-nobuild` in 2.3 beta 2 so that you can build everything ahead of time, and thus won't need to pass flags to influence the build results.

**Comment by ppekrol** [comment]
@bradwilson 

Works for me. Thanks!
