### ISSUE TITLE
Initialization of modules in F# is hit and miss

### ISSUE THREAD

**Issue by ronniebarker** [xunit/xunit#1221]
Because F# modules are static classes, it seems that xUnit and the way it discovers and runs tests, any intialization code in the beginning of the module before the tests is not run properly.

**Comment by bradwilson** [comment]
We make no attempt to run any module initializers; we don't know anything about them. Whoever's responsibility this is, it isn't ours.

**Comment by TheAngryByrd** [comment]
I think it's related to https://github.com/dotnet/netcorecli-fsc/issues/79

**Comment by enricosada** [comment]
is not xunit, is the f# template for xunit who is wrong (more info in dotnet/netcorecli-fsc#79 ), becuase was changed from lib to console (F# need an entry point for console app)

@bradwilson this can be closed, workaround is in the referenced issue.

Pratically is adding an empty entry point, in the last file.

```fsharp
module Program = let [<EntryPoint>] main _ = 0
```
