### ISSUE TITLE
Unable to get vstest.console.exe to control xunit runner  (parallel, noshadow, etc )

### ISSUE THREAD

**Issue by stwolfe** [xunit/xunit#1223]
I am trying to use vstest.console.exe to get code coverage of my xunit tests.   I need to turn off the shadow copy, but I can't seem to find a way to control it.

I have tried xunit.runner.json, app.config, .etc., but am unable to get vstest.console to configure the runner properly.

**Comment by stwolfe** [comment]
I can get xunit.console.exe to behave the way I like, but there isn't way to enable code coverage -- which is my ultimate goal.

**Comment by bradwilson** [comment]
You will not be able to pass any command line options, obviously, but `xunit.runner.json` should work with `vstest.console.exe`. Make sure the file is set to copy into the bin folder [as described here](https://xunit.github.io/docs/configuring-with-json.html#file) (and that you can see that the file is indeed showing up in the bin folder upon build).

**Comment by stwolfe** [comment]
Brad,  Thanks for the response.   I had read that post, and I thought I had placed the file in the right location.   But when I watch the diag logs for vstest, I see for tests started currently..... equal to the number of logical processors I have.    So I must be doing something wrong.    Is there in indication logged somewhere that the xunit.runner.json file was processed?

**Comment by bradwilson** [comment]
I'm not sure what logical processors has to do with shadow copying.

The simplest way to know the file is being processed is to enable diagnostics mode. When this mode is enabled, the output from the discovery messages will show you which options are enabled.

Diagnostics disabled:

```
  Discovering: MyProject
  Discovered:  MyProject
  Starting:    MyProject
[...]
```

Diagnostics enabled:

```
  Discovering: MyProject (app domain = on [shadow copy], method display = ClassAndMethod)
  Discovered:  MyProject (running 3 test cases)
  Starting:    MyProject (parallel test collections = on, max threads = 8)
[...]
```

**Comment by stwolfe** [comment]
Sorry there are two points...that I am trying to get covered in the xunit.runner.json.... no shadow, and no parallel.   Both seem to be on by default, and no way to have vstest.console.exe to control it.

Ok one more dumb question... how do you enable diagnostics... /diag:file is working, but the output to the console is not any different.

```
PS C:\repos\hcs\.out\bin\debug\full\test> vstest.console.exe .\UnitTests.exe /listtests /platform:x64 /InIsolation /diag:foo.txt
Microsoft (R) Test Execution Command Line Tool Version 15.0.26228.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The following Tests are available:
Information: [xUnit.net 00:00:01.2581722]   Discovering: UnitTests

    UnitTests.SampleTests.EqualityTest
```

**Comment by stwolfe** [comment]
Using xunit.console.exe IS picking up the values from xunit.runner.json, but not when invoked from vstest.console.exe

xunit.runner.json
```
PS C:\repos\hcs\.out\bin\debug\full\test> gc xunit.runner.json
{
  "shadowCopy": false
}
```
Invocation:
```
PS C:\repos\hcs\.out\bin\debug\full\test> xunit.console.exe .\UnitTests.exe -diagnostics
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
  Discovering: UnitTests (app domain = on [no shadow copy], method display = ClassAndMethod)
  Discovered:  UnitTests (running 922 test cases)
  Starting:    UnitTests (parallel test collections = on, max threads = 4)
```

**Comment by stwolfe** [comment]
If there were away to get code coverage using xunit.console.exe....I would just use it.   But I haven't figured that magic out yet, if it is possible.

**Comment by bradwilson** [comment]
Can you provide a repro project? I'm not able to duplicate the issue myself.

**Comment by stwolfe** [comment]
Brad, I will work on getting a small project to duplicate the issue.

**Comment by stwolfe** [comment]
I most have had something subtly wrong in my json, I recreated it, properties in slightly different order, and things still be working fine.   So like usual....just user trouble.

Things run faster with xunit.console.exe vs. vstest.console.exe, but at least I can get code coverage.
