### ISSUE TITLE
Cannot install xunit.extensions in .NETCoreApp 1.1

### ISSUE THREAD

**Issue by juniormayhe** [xunit/xunit#1224]
I have added xunit.extensions into my xunit NetCoreApp 1.1 test project. I did it willing to check if I can use `[PrioritizedFixture]` to order test methods execution. 

I have used Visual Studio 2017's nuget package manager to install xunit.extensions in my current test project (.NETCoreApp,Version=v1.1) and it won't work: I receive the following message:

`Package xunit.extensions 2.0.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package xunit.extensions 2.0.0 does not support any target frameworks.
One or more packages are incompatible with .
Package restore failed. Rolling back package changes for 'MyProject.XUnitTest'.`

Ref: http://www.bricelam.net/2012/04/xunitnet-extensibility.html

**Comment by bradwilson** [comment]
`xunit.extensions` was deprecated in 2.0.

Ordered test has been moved to the `TestOrderExamples` project: https://github.com/xunit/samples.xunit/tree/master/TestOrderExamples

**Comment by juniormayhe** [comment]
Thank you!
