### ISSUE TITLE
xunit only running a handful of tests on osx

### ISSUE THREAD

**Issue by rykr** [xunit/xunit#1226]
I have a library that is building against .netcoreapp1.0 on all platforms.  It has an xunit based testing library with hundreds and hundreds of tests.  These tests work fine on windows ubuntu 14 and 16 and fedora.  However on osx 10.12 it is running only 11 tests.   They all pass so it dutifully reports no errors but I have no idea why it's only running 11 tests.

Any idea what would cause this?

**Comment by bradwilson** [comment]
Sorry, I don't have a Mac. :(

**Comment by bradwilson** [comment]
I bought a Mac. 🙄 Please re-open with a repro project.
