### ISSUE TITLE
VS Test Runner is always empty but the Console runner shows errors

### ISSUE THREAD

**Issue by PureKrome** [xunit/xunit#1228]
Hi xUnit team - not sure if this is the correct place to raise this issue / request.

I've been trying to get my 4.7 Testing project to work but there's never any tests that show up in VS2017 test runner. Yay! 😢 

I've tried clearing the %temp% cache settings (ref: xunit documentation for full path) etc. Still nothing.

I then tried installing the `xunit.runner.console` and running that .. and hello! Errors are now showing!!

```
PS C:\Projects\Personal\Hornet\Hornet.Api> .\packages\xunit.runner.console.2.2.0\tools\xunit.console.exe .\tests\Hornet.
Api.Tests\bin\Debug\Hornet.Api.Tests.dll .\tests\Hornet.Api.Tests\bin\Debug\Hornet.Api.Tests.dll.config
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
PS C:\Projects\Personal\Hornet\Hornet.Api>
```

Note: my _solution_ 100% compiles btw.

hmmm... Now, regardless of what this evil error is (yes, I have binding redirects in my `app.config` file in my test project ... the fact was *There was NO error message clues in the VS2017 GUI _anywhere_* which could have helped identify the problem was my code and not a problem with test _discovery_. 

So - it would ve really nice if the test discovery or whatever the `console` test app dumps could also be dumped to some UI somewhere for the VS runner. I kept thinking that the VS runner was failing to find any tests ... as opposed to the fact that i have some messed up coding _killing_ the test discovery process.

I hope this make sense.

Dislaimer/Assumption: I've used the `console` command correctly.

/me politely cc @bradwilson

**Comment by bradwilson** [comment]
Can you provide a repro project?

**Comment by PureKrome** [comment]
:( nope. this is closed source.

**Comment by bradwilson** [comment]
I've seen something like this when trying to use the console runner to run .NET Core or netstandard tests, where the required dependencies don't end up getting properly copied into the bin folder. Unfortunately, if the dependencies aren't there, and they aren't in the GAC, there's no way for the desktop CLR runner to be able to resolve the dependencies.

**Comment by PureKrome** [comment]
Another thing I've noticed since this was first posted/opened, was that if there's some weird ..er .. runtime error, the Runner is always empty because it can't run to find the tests.

for example. I had some weird bindings added to my app.config file. they shouldn't have been there. Anyways, I installed R# because I totally exhausted my options and R# went nuts with this massive error _dilogue box_ .. which was mass-scary. BUT! it said something something something can't find dependency or whatever and when I removed them all and slowly re-added what I really knew i needed, things started to work again.

So i'm guessing this error might be more related to the crapy, sucky, VS test runner? Where, if there was some weird error going on during the "discovery" phase (i.e. exception thrown) none of this is displayed or highlighted to the enduser. While R# did highlight this.

**Comment by bradwilson** [comment]
Sounds fun. :-p

Please re-open this issue if you can figure out a repro.

**Comment by dprothero** [comment]
I have a repro: https://ci.appveyor.com/project/TwilioAPI/twilio-aspnet/build/1.0.18

**Comment by bradwilson** [comment]
@dprothero Please re-test with 2.4 beta 1.
