### ISSUE TITLE
support MemberData, using a member from external class, with arguments

### ISSUE THREAD

**Issue by kenegozi** [xunit/xunit#1236]
e.g.

    public class DataProvider {
        public static IEnumerable<object[]> Range(int start, int count) {
            return Range(start, count, 1);
        }
        public static IEnumerable<object[]> Range(int start, int count, int step) {
            return Enumerable.Range(start, count)
                .Select((_, ix) => start + ix * step)
                .Select(i => new object[] { i });
        }
    }

Cannot specify `MemberType = typeof(DataProvider)` on the attribute as it would not allow the params.

Suggested fix is to move `ConvertDataItem` implementation from `MemberDataAttribute` to `MemberDataAttributeBase`, and add `ExternalMemberDataAttribute : MemberDataAttributeBase` with the constructor:

        public ExternalMemberDataAttribute(string memberName, Type memberType, params object[] parameters)
            : base(memberName, parameters) {
            MemberType = memberType;
        }

PR will follow with testing yada yada

**Comment by bradwilson** [comment]
Please re-open with a PR.
