### ISSUE TITLE
dotnet-xunit does not support --no-build argument

### ISSUE THREAD

**Issue by alastairs** [xunit/xunit#1237]
`dotnet test` provides a `--no-build` argument, which just executes the tests, assuming the assemblies are already built. This reduces overall build run time, as builds are not even attempted for projects that are up-to-date. This would be a really useful argument for us because of the following scenario:

1. Create a .NET Core project specifying `<GeneratePackageOnBuild>True</GeneratePackageOnBuild>`, and `<VersionPrefix>1.0.0</VersionPrefix>`
2. Create .NET Core Xunit project referencing the previous project, per the Xunit docs to add dotnet-xunit.
3. Run `dotnet publish -c Release --version-suffix pre-1234 MySolution.sln`
4. A NuGet package called MyProject-1.0.0-pre-1234.nupkg is created.
5. Run `dotnet xunit -configuration Release`. A build is run, and a NuGet package called MyProject-1.0.0.nupkg is created. *Note this does not include the pre-release version suffix*

Supporting `--no-build` would mean a faster test run completion, and also result in the erroneous "final version" NuGet package being created.

**Comment by bradwilson** [comment]
Duplicate #1235
