### ISSUE TITLE
No tests discovered

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1238]
_Copied from https://github.com/Microsoft/vstest/issues/780_

## Description

I converted a project to the new .csproj format recently as a part of an effort to port to .NET Core, and after I did that and got everything building, the vstest runner stopped being able to find tests in the project. The strangest thing to me is that I can run individual tests in VS2017, but when I try to run with "Run all tests", the runner fails to find any.

The Xunit runner does work, however. When I run `dotnet xunit`, it finds all the tests and I get the expected behavior.

## Steps to reproduce

I'm not entirely sure what I did to get in this state, but the project is accessible here:
https://github.com/aggieben/dbup/tree/release/4.0.0

Access is open. Please `git clone https://github.com/aggieben/dbup; cd dbup; git checkout release/4.0.0` to get the project(s) in question.

## Expected behavior

VS2017 test runner should show discovered tests in test explorer, and when "run all tests" is selected, it should run the tests. Similarly, `dotnet test` should execute all the tests for both targets (`netcoreapp1.0` and `net46`).

As mentioned above, the Xunit runner does produce the expected results.

## Actual behavior

When running with `dotnet test`, this is the output:

```
C:\Users\ben\proj\oss\DbUp\src\dbup-tests [release/4.0.0 ≡]
λ dotnet test
Build started, please wait...
Engine\SqlScript.cs(15,33): warning CS0169: The field 'SqlScript.name' is never used [C:\Users\ben\proj\oss\DbUp\src\dbup-core\dbup-core.csproj]
Engine\SqlScript.cs(15,33): warning CS0169: The field 'SqlScript.name' is never used [C:\Users\ben\proj\oss\DbUp\src\dbup-core\dbup-core.csproj]
Helpers\NullJournalTests.cs(21,33): warning CS0618: 'SqlServerExtensions.SqlDatabase(SupportedDatabases, Func<IDbConnection>, string)' is obsolete: 'Pass connection string instead, then use .WithTransaction() and .WithTransactionPerScript() to manage connection behaviour' [C:\Users\ben\proj\oss\DbUp\src\dbup-tests\dbup-tests.csproj]
DeployChangesBuilderTests.cs(21,33): warning CS0618: 'SqlServerExtensions.SqlDatabase(SupportedDatabases, Func<IDbConnection>, string)' is obsolete: 'Pass connection string instead, then use .WithTransaction() and .WithTransactionPerScript() to manage connection behaviour' [C:\Users\ben\proj\oss\DbUp\src\dbup-tests\dbup-tests.csproj]
DeployChangesBuilderTests.cs(41,33): warning CS0618: 'SqlServerExtensions.SqlDatabase(SupportedDatabases, Func<IDbConnection>)' is obsolete: 'Pass connection string instead, then use .WithTransaction() and .WithTransactionPerScript() to manage connection behaviour' [C:\Users\ben\proj\oss\DbUp\src\dbup-tests\dbup-tests.csproj]
DeployChangesBuilderTests.cs(61,33): warning CS0618: 'SqlServerExtensions.SqlDatabase(SupportedDatabases, Func<IDbConnection>)' is obsolete: 'Pass connection string instead, then use .WithTransaction() and .WithTransactionPerScript() to manage connection behaviour' [C:\Users\ben\proj\oss\DbUp\src\dbup-tests\dbup-tests.csproj]
DeployChangesBuilderTests.cs(84,37): warning CS0618: 'SqlServerExtensions.SqlDatabase(SupportedDatabases, Func<IDbConnection>)' is obsolete: 'Pass connection string instead, then use .WithTransaction() and .WithTransactionPerScript() to manage connection behaviour' [C:\Users\ben\proj\oss\DbUp\src\dbup-tests\dbup-tests.csproj]
Build completed.

Test run for C:\Users\ben\proj\oss\DbUp\src\dbup-tests\bin\x64\Debug\netcoreapp1.0\dbup-tests.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
No test is available in C:\Users\ben\proj\oss\DbUp\src\dbup-tests\bin\x64\Debug\netcoreapp1.0\dbup-tests.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.



Test run for C:\Users\ben\proj\oss\DbUp\src\dbup-tests\bin\x64\Debug\net46\dbup-tests.dll(.NETFramework,Version=v4.6)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.9516916]   Discovering: dbup-tests
[xUnit.net 00:00:01.2040971]   Discovered:  dbup-tests
[xUnit.net 00:00:01.2348628] dbup-tests: Catastrophic failure: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo)
No test is available in C:\Users\ben\proj\oss\DbUp\src\dbup-tests\bin\x64\Debug\net46\dbup-tests.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
```

## Environment

```
C:\Users\ben\proj\oss\DbUp\src\dbup-tests [release/4.0.0 ≡]
λ dotnet --info
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3
```

Test runner-related packages from the `.csproj`:

```xml
<ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170106-08" />
    <PackageReference Include="xunit" Version="2.3.0-beta1-build3642" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-beta1-build1309" />
    <PackageReference Include="Shouldly" Version="2.8.1" />
    <PackageReference Include="TestStack.BDDfy" Version="4.3.1" />
    <!--<PackageReference Include="xunit.core" Version="2.2.0-beta2-build3300" />-->
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta1-build3642"/>
</ItemGroup>
```

**Comment by thegtakid** [comment]
I experience the same problem

**Comment by Costo** [comment]
Same here. Tests are not discovered if the project is built with x64 instead of AnyCpu

**Comment by bradwilson** [comment]
@Costo In Visual Studio, go to `Test` > `Test Settings` > `Default Processor Architecture` and set it to `x64`.

**Comment by bradwilson** [comment]
@aggieben I've figured out what the problem is: you have two identical tests (because you have [two sets of identical `InlineData` attributes](https://github.com/aggieben/DbUp/blob/8d14a7ca9b92997ca010dbddacabab1836e22f7d/src/dbup-tests/Support/SqlServer/SqlCommandSplitterTests.cs#L46-L47), which end up with identical unique IDs (clearly, the message here is not very helpful).

You can fix this by deleting one of the duplicates.

I will open a new bug to improve the duplicate detection in the Visual Studio runner.

**Comment by aggieben** [comment]
@bradwilson 
> two identical (...InlineData...) tests

Holy smokes I would never have caught that because I didn't even write those tests.  

Thanks a ton.

**Comment by AwarePL** [comment]
I have simular issue, non of above solutions helped me :/

my code:
`using System;
using RestSharp;
using Xunit;

namespace IntegrationTests
{
    public class Class1
    {
        [Fact]
        public void T()
        {
            var restClient = new RestClient("www.google.pl");
            var request = new RestRequest(Method.GET);            
        }
    }
}
`
`[13.10.2017 10:39:53 Informational] ========== Discover test finished: 0 found (0:00:00,6357275) ==========`

I run VS 15.4.0, xunit 2.3.0

Any ideas?

**Comment by bradwilson** [comment]
@AwarePL Please open a new issue with a repro project. Thanks!

**Comment by rosdi** [comment]
@AwarePL Refer to this: http://www.neekgreen.com/2017/11/20/xunit-no-test-is-available/

**Comment by 6heads** [comment]
> 
> 
> @AwarePL Refer to this: http://www.neekgreen.com/2017/11/20/xunit-no-test-is-available/

No longer available. Use archive.org: https://web.archive.org/web/20180331085013/http://www.neekgreen.com/2017/11/20/xunit-no-test-is-available/
