### ISSUE TITLE
Use collection fixture but execute tests in parallel

### ISSUE THREAD

**Issue by cwienands1** [xunit/xunit#1240]
My use case is this: For integration tests I create a database and spin up a web server. This is clearly a one-time activity, so I implemented it in a collection fixture. For simplicity let's just say that all of the test classes can principally run in parallel because they don't interfere with each other. The problem is that I need to add the same [Collection(...)] attribute to all test classes so that they can benefit from the collection fixture. As a result, all tests get executed sequentially, negating the benefit of xUnit's parallelism.

I am under the impression that the [Collection(...)] feature has a design flaw, in that it combines two completely separate aspects: One-time setup/teardown logic, and parallelism control. These two aspects often correlate but not always, as in my case. Personally, I think it would have been more consistent to be able to add the ICollectionFixture expression to the test classes directly, just like IClassFixture, instead of requiring these empty xxxCollection classes and attribute-based indirection. This way the setup aspect would have been separated from the attribute-based collection parallelism. Just my two cents.

Any idea how I can work around this limitation?

**Comment by cwienands1** [comment]
Sorry, I just read the guidelines and realized questions should be asked on Slack. I'm not able to delete this issue.

**Comment by mabead** [comment]
@cwienands1 Did you find the answer? Please document the answer here so that others can see the conclusion.

**Comment by cwienands1** [comment]
@mabead Sorry, this was so long ago, I don't recall if I ever got this working.

**Comment by reitffunk** [comment]
That is still a problem. Since a test collection is added the tests should run sequential but somehow are messing up if executed in parallel.

If one **wants** to run in parallel there is a [Stackoverflow answer](https://stackoverflow.com/a/57295764/1444145) now.
