### ISSUE TITLE
How specify target framework when run testing in vs2017?

### ISSUE THREAD

**Issue by hqywork** [xunit/xunit#1242]
I test project is multiple target:
   <TargetFrameworks>netcoreapp1.0;net451</TargetFrameworks>

In runing, only exec on netcoreapp1.0，how is run on net451?

**Comment by hqywork** [comment]
I run by vs2017 test explorer

**Comment by bradwilson** [comment]
This is an issue with VSTest, not xUnit.net. https://github.com/Microsoft/vstest/issues/624
