### ISSUE TITLE
Analyzer warning that a test method has no Assert statements

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1245]
_From @marcind on September 1, 2016 21:23_

Consider how to detect assertions that happen in helper methods (including in external libraries)

_Copied from original issue: xunit/xunit.analyzers#10_

**Comment by jamesqo** [comment]
@marcind 

> Consider how to detect assertions that happen in helper methods (including in external libraries)

This seems like a fun problem. It could probably be done with a recursive procedure. If the method belongs to an external lib, is a delegate, or can't be resolved, assume it calls `Assert` and return.

**Comment by jamesqo** [comment]
@marcind This may not be a good idea, actually. I've seen tests that don't have asserts because they're simply testing that a certain codepath doesn't throw an exception. For example: https://github.com/dotnet/corefx/blob/5c63dfd54919e080841e46bfbd793d45f47a03e9/src/System.Collections.Immutable/tests/ImmutableArrayTest.cs#L2150

**Comment by marcind** [comment]
I would argue that the provided example in corefx is an exception to the way tests are typically written. The point here was to provide a hint to the author that the test method is potentially not doing any meaningful work. Of course there are a number of problems/difficulties here, including:
1. Different assertion libraries that don't use xunit's assert
2. Different assertion libraries that do use xunit's assert but we probably wont' be able to detect unless we disassemble the binary
3. Helpers that call assert (need to calculate transitive closure of what should be considered a valid assertion method call)
4. Assert imported as source, etc.

**Comment by jamesqo** [comment]
@marcind 

> I would argue that the provided example in corefx is an exception to the way tests are typically written. The point here was to provide a hint to the author that the test method is potentially not doing any meaningful work.

How likely is it that someone would accidentally write a test method that does no meaningful work?

One more (minor) point-- this warning will always show up as a user is just creating the method and hasn't gotten a chance to type out any assertions yet, which might annoy them a little.

**Comment by bradwilson** [comment]
@jamesqo This may be beside the point, but reviewing that test, I can see it's a candidate for deadlocking because of the use of `Task.WaitAll` instead of `Task.WhenAll`.
