### ISSUE TITLE
Remove duplicate fixes in IDE

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1246]
_From @marcind on September 7, 2016 4:37_

At the moment for each rule analyzer there is one fixer class (which provides 1 or more fix options). There are a number of fixes (e.g. "Convert to Fact") that apply to multiple rule violations (e.g "Theory should have parameters" and "Theory should have Data attributes"). At the moment when two such violations occur in the same code line, the "Convert to Fact" fix is provided twice.

The 1-1 mapping of analyzer-fixer should be broken. Instead, there should be 1 fixer per fix, with each fixer handling one or more rule violations. This way multiple violations can be resolved with a single action.

_Copied from original issue: xunit/xunit.analyzers#15_

**Comment by jamesqo** [comment]
@marcind It looks like you fixed this issue?

**Comment by marcind** [comment]
I'm sure I left this open to remind me of other work I wanted to do. If only I could remember what that was.
