### ISSUE TITLE
Refactoring to fix improper usage of Assert.Throws with async code

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1248]
_From @marcind on September 11, 2016 17:39_

Instead of 

``` CSharp
Assert.Throws(() => SomethingAsync());
```

do

``` CSharp
await Assert.ThrowsAsync(() => SomethingAsync());
```
- Including the overload with `paramName` parameter
- Make test method async if it's not already
- Make sure to deal with async lambdas too

_Copied from original issue: xunit/xunit.analyzers#21_

**Comment by marcind** [comment]
Closed in https://github.com/xunit/xunit.analyzers/pull/63
