### ISSUE TITLE
Analyzer/fix for Assert.Equal/NotEqual used for collection size checks

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1252]
_From @marcind on September 12, 2016 20:28_

`Assert.Equal(0, collection.Count)` -> `Assert.Empty(collection)`
`Assert.Equal(1, collection.Count)` -> `Assert.Single(collection)`
`Assert.NotEqual(0, collection.Count)` -> `Assert.NotEmpty(collection)`

_Copied from original issue: xunit/xunit.analyzers#28_

**Comment by marcind** [comment]
Handled by https://github.com/xunit/xunit.analyzers/pull/60

**Comment by smitpatel** [comment]
What to use when asserting collection size of 2 or more?

**Comment by marcind** [comment]
Continue using `Assert.Equal`
