### ISSUE TITLE
Analyzer for Assert.Collection with no element inspectors

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1256]
_From @marcind on September 13, 2016 0:30_

`Assert.Collection(collection)` -> `Assert.Empty(collection)`

_Copied from original issue: xunit/xunit.analyzers#35_

**Comment by marcind** [comment]
Added in https://github.com/xunit/xunit.analyzers/commit/c4bcf8ea0c3038f01003433242aa6eaf737303a6
