### ISSUE TITLE
Refactoring for Assert.Throws(typeof(Ex), ...)

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1259]
_From @marcind on May 4, 2017 2:34_

Should be refactored into `Assert.Throws<Ex>(...)`

Also include `Assert.ThrowsAsync` as appropriate.

_Copied from original issue: xunit/xunit.analyzers#38_

**Comment by marcind** [comment]
Closed in https://github.com/xunit/xunit.analyzers/pull/64
