### ISSUE TITLE
Add documentation for analyzer rules

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1262]
_From @marcind on May 5, 2017 14:53_

See https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Documenting%20your%20analyzers.md

_Copied from original issue: xunit/xunit.analyzers#41_

**Comment by jamesqo** [comment]
@marcind I will take a stab at this. Just so you know, I'm basing it off the documentation for StyleCopAnalyzers here: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/tree/master/documentation

**Comment by marcind** [comment]
Before we take this any further, I'm wondering what the appropriate location to host these would be. Any thoughts @bradwilson?

A section of the analyzers' source repo (what's being WIPed in the references PR) would be easiest to work with as new analyzers are developed, but it's not the prettiest (though certainly workable for a developer audience).

We could also set up the analyzers project wiki, which might provide a slightly better experience. 

Of course there is also http://xunit.github.io/ but that might be harder to work with.

**Comment by jamesqo** [comment]
> We could also set up the analyzers project wiki, which might provide a slightly better experience.

There is no way to make "pull requests" to a GitHub wiki. You either have to restrict access to maintainers or allow everyone to edit the wiki. https://stackoverflow.com/q/10642928/4077294

**Comment by jamesqo** [comment]
@bradwilson Do you have an opinion on this?

**Comment by bradwilson** [comment]
Why not put them on our official documentation site?

https://xunit.github.io/
https://github.com/xunit/xunit.github.io/

**Comment by jamesqo** [comment]
@bradwilson That could be harder to maintain. The benefit of having them right in the repo is that you can add the doc as part of your pull request. A separate repo for the documentation means two pull requests anytime an analyzer is added or its behavior is changed.

As a secondary note, I would also find it hard to write the documentation in HTML, as I've never done web programming.

**Comment by bradwilson** [comment]
(a) Github pages also supports Markdown, which is what you'd be using for the Wiki.
(b) The Wiki sucks. If you just want some Markdown documentation files that support PRs, make a folder in the source repo (call it "docs") and just drop MD files there, one for each rule or whatever floats your boat.

**Comment by bradwilson** [comment]
Addendum to (b): It appears that's precisely what the original link suggests to do, so why was there any talk about a Wiki at all? :-p

**Comment by jamesqo** [comment]
> Addendum to (b): It appears that's precisely what the original link suggests to do, so why was there any talk about a Wiki at all? :-p

Well, that's what @marcind suggested in his comment; I totally disagreed with his opinion that the wiki might provide a "better experience", but to each his own I guess. 🤷‍♂️ 

Anyway, to confirm, you're OK with the approach taken in the PR then?

**Comment by bradwilson** [comment]
I'm fine with it, but it's @marcind's repo. I've said my preference (doc site) which nobody seems to like; in absence of the doc site, then MD files in the repo is the 2nd best option in my mind.

**Comment by jamesqo** [comment]
@marcind, have you decided between xunit.github.io and having the docs directly in the GitHub repo yet?

**Comment by marcind** [comment]
I've decided to do both. MD files checked into [/docs](https://github.com/xunit/xunit.analyzers/tree/master/docs) will be published to the project-specific section of the GitHub pages doc site, e.g. https://xunit.github.io/xunit.analyzers/xUnit1000. Just had to do some digging to figure out that this was something that github supported.

**Comment by jamesqo** [comment]
@marcind That's awesome, glad we were able to find a compromise!

Just minor nits on the UX when you go to that page: clicking on the `xunit.analyzers` link at the top and the `Help improve this page.` one at the bottom both lead to a 404.

**Comment by marcind** [comment]
I think those links are generated by the GitHub pages infrastructure, not
sure when they are broken.

**Comment by jamesqo** [comment]
@marcind That's a shame. I've never used GitHub pages so I can't look further into that apparently.

Concerning this issue, I just wanted to confirm that you're not working on more analyzer docs yourself, in addition to the 3 we already have. If you haven't already grabbed this issue, then I'll start working on finishing the rest of the docs tmrw.

**Comment by marcind** [comment]
Please hold off. I'm setting up a different structure for those docs and
want minimize the amount of merging.

**Comment by jamesqo** [comment]
@marcind Are you finished with your docs changes now? (BTW, they look pretty sweet.)

**Comment by jamesqo** [comment]
@marcind I am working on the documentation now.

**Comment by jamesqo** [comment]
@marcind I am working on the documentation now.

**Comment by marcind** [comment]
No, I'm not done yet. You're likely going to run into conflicts.

**Comment by jamesqo** [comment]
@marcind Are you still working on it?

**Comment by marcind** [comment]
It's still not complete. Just have not had much time to sit down and do it lately.

**Comment by robk410** [comment]
Just got a xunit.analyzers/rules/xUnit2007 with a 404 to the doc as to a solution. In for status updates on this.

**Comment by bradwilson** [comment]
Closing as completed.
