### ISSUE TITLE
Add tests for code fixes in analyzers

### ISSUE THREAD

**Issue by ErikSchierboom** [xunit/xunit#1264]
Currently, the analyzers only test their analysis part. The accompanying code fix(es) are not yet tested. Perhaps it would be good to also test the code fixes.

**Comment by bradwilson** [comment]
I recently added a way to easily test fixers. See this for some example usage:

https://github.com/xunit/xunit.analyzers/blob/master/test/xunit.analyzers.tests/TestClassMustBePublicFixerTests.cs

```csharp
using Microsoft.CodeAnalysis.CodeFixes;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Xunit.Analyzers
{
    public class TestClassMustBePublicFixerTests
    {
        readonly DiagnosticAnalyzer analyzer = new TestClassMustBePublic();
        readonly CodeFixProvider fixer = new TestClassMustBePublicFixer();

        [Theory]
        [InlineData("")]
        [InlineData("internal ")]
        public async void MakesClassPublic(string visibility)
        {
            var result = await CodeAnalyzerHelper.GetFixedCodeAsync(analyzer, fixer, $"{visibility}class TestClass {{ [Xunit.Fact] public void TestMethod() {{ }} }}");
            Assert.Equal("public class TestClass { [Xunit.Fact] public void TestMethod() { } }", result);
        }
    }
}
```

**Comment by marcind** [comment]
Brad has created an example, new code should have test for fixers, existing code should (at some ambiguous time in the future) have tests backfilled. No need to keep blanket issue like this open.
