### ISSUE TITLE
Analyzer to detect logging calls in tests

### ISSUE THREAD

**Issue by marcind** [xunit/xunit#1265]
Based on #745, analyzer that detects calls to `System.Console`, `System.Diagnostics.Debug`, `System.Diagnostics.Trace`, and maybe others (`System.Console.Error`?). The fix provider would suggest using `ITestOutputHelper` (as per http://xunit.github.io/docs/capturing-output.html), including injecting it into the test class via constructor.

Things to consider:
- there are lots of variants of the `Write`/`WriteLine` methods, what would be the appropriate refactoring for each?
- when injecting the output helper, consider making sure that test class hierarchies still compile

**Comment by matkoch** [comment]
@marcind I'm about to implement this. Some opinions/thoughts:
- Should all invocations (no matter if `Trace`, `Debug`, `Console`) be redirected to `ITestOutputHelper` ? I think yes.
- Fix can add a call to `ToString()` for all non-string literal types; or add additional methods on `ITestOutputHelper`. I would prefer `ToString()` calls.
- Either add additional methods for `Write`, `Write[Line]If`; or add if statements when transforming; or don't provide a fix. I would prefer to not provide a fix; conditional test code is bad.

**Comment by matkoch** [comment]
@marcind  ping 😄

**Comment by AndreyAkinshin** [comment]
@marcind ping

**Comment by SimonCropp** [comment]
@matkoch u may want to review/steal some code from here https://github.com/SimonCropp/XunitLogger

**Comment by SimonCropp** [comment]
given the plan for v3 is to add [Console / Trace / Debugger capture support ](https://github.com/xunit/xunit/issues/1730) perhaps this one should be closed?

**Comment by bradwilson** [comment]
Agreed Simon. 😄
