### ISSUE TITLE
Analyzer for Assert.True/False used for string equality checks

### ISSUE THREAD

**Issue by marcind** [xunit/xunit#1269]
`Assert.True(String.Equals("a", "a"))` -> `Assert.Equal("a", "a")`
`Assert.True(String.Equals("a", "b", StringComparison.Ordinal)` -> `Assert.Equal("a", "b")`
`Assert.True(String.Equals("a", "b", StringComparison.OrdinalIgnoreCase)` -> `Assert.Equal("a", "b", ignoreCase: true)`

Note: Other values of `StringComparison` should not be flagged since there's not appropriate `Assert.Equal` equivalent.

**Comment by ErikSchierboom** [comment]
I'm working on this analyzer. This issue's title mentions that it should work for both True/False checks. However, `Assert.NotEqual` does not have a string-specific overload, which `Assert.Equal` does. Is the title incorrect or should we still suggest using `Assert.NotEqual` but not support the `OrdinalIgnoreCase` case?

**Comment by marcind** [comment]
Well these feature bugs describe rough ideas, there's always some tweaking to be done once you start trying it out in practice.
I'm happy taking as small or large contribution as you're willing to provide, assuming it helps out the end user. I think it would be fine to only handle `Assert.False(String.Equals("a","b"))` for now.
Also note that StringComparison has a number of different values, but only Ordinal/OrdinalIgnoreCase make sense for the `Assert.True` case, other's should probably not trigger the warning at all.

**Comment by ErikSchierboom** [comment]
@marcind Okay, got it! Thanks
