### ISSUE TITLE
XunitTest target for MSBuild runner

### ISSUE THREAD

**Issue by dasMulli** [xunit/xunit#1270]
The msbuild runner should include a target that calls the xunit task, preferably with a few configuration  properties.
While it is possible to create a target in consuming projects / solutions (Directory.Build.targets), it would be a great addition to have a target that is well-known and people can learn to use with arbitrary xunit projects. This would be similar to the VSTest target.

**Comment by dasMulli** [comment]
Discussion needed:
- Name of the target (I'm for `XUnitTest`)
- Supported parameters (e.g. for xml output, shadow copying etc. I don't think there'll be need to specify individual methods as this is more for dotnet-xunit cli usage)

**Comment by bradwilson** [comment]
Method filtering is not available on the MSBuild runner anyway. :)

**Comment by bradwilson** [comment]
Everything you can pass to `<xunit>` can be set via properties:

https://github.com/xunit/xunit/blob/master/src/xunit.runner.msbuild/build/xunit.runner.msbuild.targets

I'm updated the integration project to show this in use:

https://github.com/xunit/xunit.integration/tree/master/msbuild
https://github.com/xunit/xunit.integration/commit/f3f37d997c5ea6d61d28ad2281d194861afe95b8
