### ISSUE TITLE
xUnit1013 is triggered for IAsyncLifetime implementations

### ISSUE THREAD

**Issue by nulltoken** [xunit/xunit#1271]
```
Error	xUnit1013	Public method 'InitializeAsync' on test class 'Create' should be marked as a Fact.	
Error	xUnit1013	Public method 'DisposeAsync' on test class 'Create' should be marked as a Fact.	

Public methods on a test class that return void or Task should be marked as tests or have their accessibility reduced. While test methods do not have to be public  having public non-test methods might indicate that a method was intended to be a test but the annotation was not applied.
```

switching from `public Task DisposeAsync()` to an explicit implementation `Task IAsyncLifetime.DisposeAsync()` shuts the warning off.

However, I _think_ the error message may not be that explicit. Two potential options I can think of:

 - special case these methods (and others) and not raise the warning
 - create a new analyzer that requests those interfaced based methods to always require an explicit implementation

**Comment by marcind** [comment]
Thanks for the bug report. `IDisposable.Dispose` is already special-cased so these should be special-cased as well (methods on [IAsyncLifetime](https://github.com/xunit/xunit/blob/master/src/xunit.core/IAsyncLifetime.cs))

**Comment by nulltoken** [comment]
Thanks!
