### ISSUE TITLE
After updating to NET Core 2.0 preview xunit does not allow InlineData with optional method arguments anymore 

### ISSUE THREAD

**Issue by NinoFloris** [xunit/xunit#1275]
Error returned is:

```
error xUnit1009: InlineData values must match the number of method parameters
```

For code like 

```
[InlineData("ThisThat")]
[InlineData("ThisThat", "something else")]
public void MyMethod(string thisthat, string changeIt = "the same")
```
The first attribute will trigger that exception

**Comment by marcind** [comment]
Looks like this is caused by a bug in the new xunit.analyzers.
In the meantime, you should be able to suppress the error in the following way:
```
#pragma warning disable xUnit1009
InlineData("ThisThat")]
#pragma warning restore xUnit1009
```

**Comment by NinoFloris** [comment]
Yeah or supply the optional args, but just letting you guys know

**Comment by marcind** [comment]
Yup, thanks for the report. It will get fixed.
