### ISSUE TITLE
Analyzer to detect issues with collection fixture references

### ISSUE THREAD

**Issue by marcind** [xunit/xunit#1276]
Exact rules TBD, but the general idea is that

1. If a test class expects a fixture (i.e. has a constructor parameter)
2. But there is no matching `IClassFixture<TParam>` interface on the class
3. Verify that there is a matching collection definition for the class and it has the appropriate `ICollectionFixture<TParam>` interface.

See https://xunit.github.io/docs/shared-context.html

**Comment by bradwilson** [comment]
Shipped as [xUnit1041](https://xunit.net/xunit.analyzers/rules/xUnit1041)
