### ISSUE TITLE
Add analyzer for IClassFixture usage

### ISSUE THREAD

**Issue by marcind** [xunit/xunit#1278]
Possible rules: 

- If test class has constructor parameters, suggest adding matching fixture interface/removing parameter
- If a test class has fixture interfaces but no constructor parameters, suggest adding param/removing interface

**Comment by noamyogev84** [comment]
Hi.
I'd like to tackle this one.
Any good hints/start points?

**Comment by noamyogev84** [comment]
I think there is already something like that: https://github.com/xunit/xunit.analyzers/blob/97c987a1cf35d4abbd36192321437ebd4b6aa53c/src/xunit.analyzers/TestClassShouldHaveTFixtureArgument.cs#L9

**Comment by marcind** [comment]
@noamyogev84 sorry, I'm not involved in the project at this time. Please reach out to the other maintainers.

**Comment by bradwilson** [comment]
Closing as already fixed.
