### ISSUE TITLE
Xunit2 adapter doesnt fire RecordStart and RecordEnd Synchronously

### ISSUE THREAD

**Issue by acesiddhu** [xunit/xunit#1282]
Tried searching existing issue here. Hence filling an issue

In Xunit2 adapter we see that RecordStart and RecordEnd events are not fired Synchronously. It used to work in Xunit 0.9 . Ideally the test case should not start till RecordStart call comes backs.
This is needed for data collectors (data collectors that work at test case level) to work fine. Ideally the event should be in below order (for two test cases)

Xunit Fire RecordStart for TestCase1
Process Start at Data collector level for for TestCase1
Execute test TestCase1
Xunit Fire RecordEnd for TestCase1
Process End at Data collector level for TestCase1

Xunit Fire RecordStart for TestCase2
Process Start at Data collector level for TestCase2
Execute test TestCase2
Xunit Fire RecordEnd for TestCase 2
Process End at Data collector level for TestCase2

While debugging we found out these events are not in sync with execution of test cases

**Repro Step**
[TestImpact.txt](https://github.com/xunit/xunit/files/1000881/TestImpact.txt)

1) Use attached runsetting file (you can rename it to .runsettings) in VS2017 
2) Run xunit 2 test with Xunit 2 adapter.

**Expected:**
for each test there should be a testimpact.xml generated
Actual:
No file generated.

with same setting if you run xunit 0.9 test it generates the impact file.

**Comment by bradwilson** [comment]
What version of `xunit` are you using?

What version of `xunit.runner.visualstudio` are you using?

**Comment by acesiddhu** [comment]
<packages>
  <package id="xunit" version="2.3.0-beta1-build3642" targetFramework="net452" />
  <package id="xunit.abstractions" version="2.0.1" targetFramework="net452" />
  <package id="xunit.assert" version="2.3.0-beta1-build3642" targetFramework="net452" />
  <package id="xunit.core" version="2.3.0-beta1-build3642" targetFramework="net452" />
  <package id="xunit.extensibility.core" version="2.3.0-beta1-build3642" targetFramework="net452" />
  <package id="xunit.extensibility.execution" version="2.3.0-beta1-build3642" targetFramework="net452" />
  <package id="xunit.runner.visualstudio" version="2.3.0-beta1-build1309" targetFramework="net452" developmentDependency="true" />
</packages>

**Comment by bradwilson** [comment]
As you can see [in the code](https://github.com/xunit/visualstudio.xunit/blob/75cb47f5e5da9fccff1d9da9eae5351ea1ced11c/src/xunit.runner.visualstudio/VsTestRunner.cs#L535-L539):

```csharp
if (RunSettingsHelper.DisableParallelization)
{
    executionOptions.SetSynchronousMessageReporting(true);
    executionOptions.SetDisableParallelization(true);
}
```

Synchronous message reporting is only guaranteed when parallelization has been disabled. Have you disabled parallelization? You do that by setting `DisableParallelization` in your run settings file to `true`.

**Comment by acesiddhu** [comment]
Thanks. Make sense.
