### ISSUE TITLE
Duplicate test name (overloads) within a class results in System.InvalidOperationException

### ISSUE THREAD

**Issue by ahsonkhan** [xunit/xunit#1285]
**Edit:** Duplicate of: https://github.com/xunit/xunit/issues/21 / https://github.com/xunit/xunit/issues/1133

**Questions:** 
- Any plans to support this? I observed this issue where a test class inheriting another was throwing the error shown below since it shared a method name with the class it was inheriting (different args). 
- Can we get a more explicit error message if this won't be supported?

**Steps to reproduce:**
1. Get the latest dotnet cli from https://github.com/dotnet/cli.
2. Run dotnet.exe new xunit
3. Add two tests of the same name (one as a Fact with no arguments and another as a Theory with one argument). Essentially create test method overloads.
4. Run dotnet.exe test.
5. Observe error.

**Actual Behavior:**
Build started, please wait...
Build completed.

Test run for D:\Other\trash\TestDupTests\bin\Debug\netcoreapp2.0\TestDupTests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170502-03
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.4828872]   Discovering: TestDupTests
[xUnit.net 00:00:00.5857741]   Discovered:  TestDupTests
[xUnit.net 00:00:00.6339319]   Starting:    TestDupTests
[xUnit.net 00:00:00.7978637]     TestDupTests.UnitTest1.Test1(???: True) [FAIL]
[xUnit.net 00:00:00.7991693]       System.InvalidOperationException : The test method expected 0 parameter values, but 1 parameter value was provided.
[xUnit.net 00:00:00.8035606]   Finished:    TestDupTests
Failed   TestDupTests.UnitTest1.Test1(???: True)
Error Message:
 System.InvalidOperationException : The test method expected 0 parameter values, but 1 parameter value was provided.

Total tests: 2. Passed: 1. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 1.3848 Seconds

**Expected Behavior:**
Even with method overlaods, the tests get discovered accurately, run, and pass.

**Sample test code:**
```C#
using System;
using Xunit;

namespace TestDupTests
{
    public class UnitTest1
    {
        [Fact]
        public void Test1()
        {
            Assert.True(true);
        }

        [Theory]
        [InlineData(true)]
        public void Test1(bool val)
        {
            Assert.True(val);
        }
    }
}
```

OR
```C#
        [Theory]
        [InlineData(true, true)]
        public void Test1(bool val1, bool val2)
        {
            Assert.True(val1==val2);
        }

        [Theory]
        [InlineData(true)]
        public void Test1(bool val)
        {
            Assert.True(val);
        }
```

**csproj:**
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0-preview-20170427-09" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  </ItemGroup>

</Project>
```

cc @shiftylogic, @KrzysztofCwalina

**Comment by ahsonkhan** [comment]
**Inheritence scenario:**
```C#
using System;
using Xunit;

namespace TestDupTests
{
    abstract public class UnitTest1
    {
        [Fact]
        public void Test1()
        {
            Assert.True(true);
        }
    }
    
    public class UnitTest2 : UnitTest1
    {
        [Theory]
        [InlineData(true)]
        public void Test1(bool val)
        {
            Assert.True(val);
        }
    }
}
```

This obfuscate the cause of the error even more, especially when the two classes are in separate files.

**Comment by bradwilson** [comment]
Duplicate test names are not supported. Please rename one of the tests.

**Comment by ahsonkhan** [comment]
> Duplicate test names are not supported. Please rename one of the tests.

@bradwilson, thanks for the quick response. I realize (looking at previous related issues) that it isn't supported, but I have a couple of open questions.

**Questions:** 
- Any plans to support this? I observed this issue where a test class inheriting another was throwing the error shown below since it shared a method name with the class it was inheriting (different args). This obfuscates the root cause of the error even more, especially when the two classes are in separate files and the error message is `System.InvalidOperationException : The test method expected 1 parameter value, but 0 parameter values were provided.`

- Can we get a more explicit error message if this won't be supported?

**Comment by bradwilson** [comment]
> Any plans to support this?

Unfortunately, no. It's deeply embedded into the architecture and can't be changed at this point.

> Can we get a more explicit error message if this won't be supported?

I'll see what can be done.

**Comment by bradwilson** [comment]
Going to close this, as we have an [Error-based analyzer](https://xunit.net/xunit.analyzers/rules/xUnit1024) report for this.
