### ISSUE TITLE
xunit upgrade to 2.3.0-beta2-build3683 breaks test discovery in UWP test app

### ISSUE THREAD

**Issue by thnk2wn** [xunit/xunit#1289]
After upgrading the xunit nuget package from "xunit": "2.3.0-beta1-build3642" to "xunit": "2.3.0-beta2-build3683", test discovery no longer works for me inside our UWP app. I've tried all the tricks of deleting temporary VS test cache files and restarting, double checking test settings processor architecture and so forth. I can reliably get tests discovered before the update but never after. Reverting restores discovery.

Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3

**Comment by bradwilson** [comment]
Dup #1267.
