### ISSUE TITLE
*TestCase and  messages types should be marked as serializable

### ISSUE THREAD

**Issue by safern** [xunit/xunit#1291]
In our test suite for .NET Core we currently have two custom discoverers ([ConditionalFactDiscoverer](https://github.com/dotnet/buildtools/blob/master/src/xunit.netcore.extensions/Discoverers/ConditionalFactDiscoverer.cs#L13) and [ConditionalTheoryDiscoverer](https://github.com/dotnet/buildtools/blob/master/src/xunit.netcore.extensions/Discoverers/ConditionalTheoryDiscoverer.cs#L13)) this discoverers help discover test cases with our custom [ConditionalFactAttribute](https://github.com/dotnet/buildtools/blob/master/src/xunit.netcore.extensions/Attributes/ConditionalFactAttribute.cs#L12) and [ConditionalTheoryAttribute](https://github.com/dotnet/buildtools/blob/master/src/xunit.netcore.extensions/Attributes/ConditionalTheoryAttribute.cs#L12) which main goal is to have a condition and if that condition is false it would be marked as skipped in our discoverers.

When running our tests in netcoreapp this works fine as it doesn't support `AppDomains`, the problem comes to when running the tests against .NET Framework.

Since .NET Framework supports `AppDomains` and our discoverers live in a different `AppDomain` than xunit's   main `AppDomain`, when we return the discovered or skipped test cases this will be added to a message queue that will later be Dispatched through [MessageBus.Dispatch](https://github.com/xunit/xunit/blob/master/src/xunit.execution/Sdk/MessageBus.cs#L35). Since the objects where queued on a different `AppDomain` when trying to dispatch the message and call its delegate (to do whatever action it has to do depending on the message type) the runtime will try to marshal this objects, but since they are not marked as `Serializable` we will get a `SerializationException` which xunit currently ignores and treats this test as if it was not discovered, so we get no test execution. 

Our Discoverers and Attributes are built against netstandard1.1 so we are taking a dependency on `xunit.execution.dotnet.dll` to handle this, since `SerializableAttribute` is not available until netstandard2.0 we would need to workaround this. `SerializableAttribute` is a pseudo-attribute, which means that the metadata will not be applied this attribute. Rather, there's a bit set by the C# compiler in the type definition. So the C# compiler translates `[Serializable]` into that bit which will be known to the runtime and it doesn't care which assembly defines it. So defining a `SerializableAttribute` when `targetgroup == netstandard1.1` would fix this SerializationExceptions due to Marshaling and that way people can create their custom Discoverers without running into this issues when running with AppDomains. 

cc: @bradwilson 

FYI: @danmosemsft

**Comment by bradwilson** [comment]
We don't use serialization in these cases; we use `MarshalByRefObject` instead. For example: https://github.com/xunit/xunit/blob/d9d9e25bca4a55a6dfe2026641ae227366e97e56/src/xunit.execution/Sdk/Frameworks/TestMethodTestCase.cs#L16

I honestly don't know if marking your test case objects as serializable would work. We've never tried it.

**Comment by bradwilson** [comment]
Also, if you only link against `xunit.execution.dotnet.dll`, then you will never properly work against desktop CLR projects, as they use `xunit.execution.desktop.dll`. Any extensibility library should multi-target and ship both. For example: https://github.com/AArnott/Xunit.StaFact/blob/master/src/Xunit.StaFact/Xunit.StaFact.csproj

**Comment by safern** [comment]
> We don't use serialization in these cases; we use MarshalByRefObject instead

But when running in netstandard1.1 I believe this doesn't work. I would have to try it again and see if I get an exception referencing the types that derive from `LongLivedMarshalByRefObject` but I believe I saw a lot of failures on this objects as well. 

> I honestly don't know if marking your test case objects as serializable would work. We've never tried it.

Tried it and it didn't work either as you guys use more objects than just the TestCases. For Example: `TestCaseStarting`

> Also, if you only link against xunit.execution.dotnet.dll, then you will never properly work against desktop CLR projects, as they use xunit.execution.desktop.dll. Any extensibility library should multi-target and ship both.

This is just some discoverer extensions which actually don't really execute the code itself, so it doesn't hurt our test projects.

**Comment by bradwilson** [comment]
> Tried it and it didn't work either as you guys use more objects than just the TestCases. For Example: TestCaseStarting

We use MBRO for messages, too.

This is probably the version of `LongLivedMarshalByRefObject` you'd want to use: https://github.com/xunit/xunit/blob/master/src/xunit.runner.utility/Utility/LongLivedMarshalByRefObject.cs

You'll need to copy the source into your project.

**Comment by safern** [comment]
> Also, if you only link against xunit.execution.dotnet.dll, then you will never properly work against desktop CLR projects, as they use xunit.execution.desktop.dll. Any extensibility library should multi-target and ship both.

Is there any strong reason why this assembly needs to be named different per target framework? Because if this was named the same then there is no need for us to multi-target our library as NuGet would solve the assembly resolution per framework.

**Comment by bradwilson** [comment]
> Is there any strong reason why this assembly needs to be named different per target framework?

Several, any of which breaks what you want.

1. The two libraries have a different API and different requirements. You've hit one already: when targeting desktop CLR, to support app domains, you must use MBRO on everything that crosses the app domain (like messages and test cases).

2. They will often end up in the same folder together for ludicrous reasons (read: the design of the VSTest runner which always discovers tests with the desktop CLR, whether they will be run elsewhere or not, so we need both the desktop CLR runner & execution engine to sit alongside the non-desktop CLR runners & execution engine).

3. The execution library is loaded dynamically by the runner utility library. It uses the filename of the execution library to make decisions about how to set up the execution environment (app domains being the primary example).

**Comment by safern** [comment]
Ok. So it seems like the only solution can happen in our side which is having multi-targeted library.

Thanks @bradwilson
