### ISSUE TITLE
Tests not discovered when BaseIntermediateOutputPath changed from default

### ISSUE THREAD

**Issue by mattzink** [xunit/xunit#1296]
We set custom `<OutputPath>` and `<BaseIntermediateOutputPath>` in our csproj files so that compiling does not litter up the source directory hierarchy. When we change `<BaseIntermediateOutputPath>` to anything but the default path (`obj\`), then xunit tests are no longer discovered in dotnet test or VS2017 15.3 preview.

xunit: 2.2.0 or 2.3.0-beta3-build3696 
Runtime: .NET Core 2.0 preview 1

Repro:
1. Execute `dotnet new xunit`
2. Edit csproj, adding `<BaseIntermediateOutputPath>obj2\</BaseIntermediateOutputPath>`
3. Delete existing `obj` sub-directory
4. Execute `dotnet restore`
5. Execute `dotnet test`

Expected: The included default test is executed
Actual: The following error is displayed:
```
Starting test execution, please wait...
No test is available in C:\Users\mattzink\Documents\Visual Studio 2017\Projects\core2test\source\test\bin\Debug\netcoreapp2.0\test.dll. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate and try again.
```

**Comment by onovotny** [comment]
This issue is out of our control as this is VSTest doing the discovery. Please file the issue on the GitHub.com/Microsoft/VSTest repo.

**Comment by mattzink** [comment]
Done: https://github.com/Microsoft/vstest/issues/828. Thanks

**Comment by bradwilson** [comment]
Re-open this if there are issues on our side.
