### ISSUE TITLE
Question: How a test runner can give arguments to the unit tests?

### ISSUE THREAD

**Issue by duongphuhiep** [xunit/xunit#1297]
Base on [this excellent sample](https://github.com/xunit/samples.xunit/blob/master/TestRunner/Program.cs)

I'm able to create a [custom Test Runner](https://gist.github.com/duongphuhiep/410e32a2b4710656900e88a24190b3bb) to execute any external tests dlls. Something like:

```
testReport = MyTestRunner.Run(@"External_Unit_Test.dll");
```

`MyTestRunner` wants to give some arguments / configurations to `External_Unit_Test.dll` before its run. How to achieve that?

For now `MyTestRunner` will write the arguments / configuration in a temporary file,  then `External_Unit_Test.dll` will read the configuration from it.

Is there a better way to communicate between `MyTestRunner` and `External_Unit_Test.dll`?

Thanks

**Comment by bradwilson** [comment]
There is nothing built in today (and no plans for anything). Our best suggestion here is either via a file or environment variables.
