### ISSUE TITLE
Analyzer to detect identical InlineData values on a theory

### ISSUE THREAD

**Issue by marcind** [xunit/xunit#1298]
Inspired by #1263

**Comment by wachulski** [comment]
Can I start working on it? Looks quite promising as a first step of engaging into this project.

**Comment by marcind** [comment]
Go for it. Looking forward to the contribution.

**Comment by wachulski** [comment]
All right. Started.

**Comment by wachulski** [comment]
An early draft here. https://github.com/xunit/xunit.analyzers/pull/54. Still some TODOs on the way, but you may have a sneak peak now.

**Comment by marcind** [comment]
Added in https://github.com/xunit/xunit.analyzers/commit/6fd8bed410da8dfb9252b2cd74d6348cd3325fe8
