### ISSUE TITLE
Assemblies locked between discovery and execution

### ISSUE THREAD

**Issue by EvanMachusak** [xunit/xunit#1299]
Our team is using xUnit in **Visual Studio 2017** to test some **.NET 4.5.1** assemblies.

Relevant packages snippet for the project is:
`  <package id="xunit" version="2.0.0" targetFramework="net45" /><package id="xunit.abstractions" version="2.0.0" targetFramework="net45" />
  <package id="xunit.assert" version="2.0.0" targetFramework="net45" />
  <package id="xunit.core" version="2.0.0" targetFramework="net45" />
  <package id="xunit.extensibility.core" version="2.0.0" targetFramework="net45" />
  <package id="xunit.runner.visualstudio" version="2.0.1" targetFramework="net45" />`

All other references in packages.config are for net451 (in case that is relevant).

This works fine on my machine, but my colleague is beating his head against his desk trying to get this working on his.  We are using identical codebases - we have both done cleans and gets on our environments, but he experiences one or more of these:
- During discovery, xUnit fails indicating that one of the referenced assemblies (in its bin/debug folder) is locked by another process
- When attempting to run, the test fails with a similar exception (Assembly can't be loaded because it's being used by another process).

In Windows explorer we have no trouble deleting the assemblies named by the exception messages.  I recall having similar issues with plain old MSTest projects many years ago - the test runner locking assemblies - but in that instance I was also unable to delete them either.

We've tried unchecking "Keep Test Execution Engine Running" which causes discovery to fail with a cryptic AppDomain error message.  Adding the app.config key to require AppDomains makes that problem go away and discovery works, but running the tests does not (same exception: Assembly is being used by another process).  We've manually terminated every process on his machine that we think could be even tangentially responsible for locking files and it has no effect.

He tried updating xUnit to 2.20 and was able to successfully execute a test once.  After attempting to run a test a second time, he again received the locked assembly exception and was unable to continue.

Note that these tests are not performing any specific metaprogramming - we are not using any kind of reflective assembly loading.  These are straight project references, and again, on my machine I've had no trouble working with xUnit - running tests, adding new ones, rebuilding, running again - nary a locked assembly exception.  I am able to run tests with both 2.0 and 2.2 without a problem.

At this point we're out of ideas.  Getting our PM to budget some sprint time to unit tests was a big victory for us and an inability to get every developer up and running with them will be a disaster for the future of unit testing in my group.

We've dug through the (scarce) material I can find about this issue, but to no avail.  At this juncture, we'll grasp at straws.

**Comment by bradwilson** [comment]
Please re-open with a repro project.
