### ISSUE TITLE
Question: How to use dotnet xunit command in vsts build definition?

### ISSUE THREAD

**Issue by Jajunk** [xunit/xunit#1300]
I want a step in my visual studio team services build definition to run the new dotnet xunit command after a build. I created a net core step and gave it the xunit command. unfortunately because the build agent will use dotnet.exe from the main c drive, it won't work. Any idea how to get this to work?

**Comment by onovotny** [comment]
You should be able to set the working directory to your project's directory, can you try that?

**Comment by JohnRusk** [comment]
@onovotny How do you set that?  Do you use the "dotnet build" task type? It doesn't seem to have any place to make that setting.

**Comment by Jajunk** [comment]
I tried setting the working directory using the Command Line task as suggested by @JohnRusk, but it still errored out with the message: No executable found matching command "dotnet-xunit".

I set the working directory to the folder that contains the xunit tests, using $(build.sourcesDirectory)\

no luck. Thanks though.

**Comment by axelheer** [comment]
The .NET Core build step doesn't set the current working directory, so "dotnet.exe" doesn't find the "dotnet-xunit" executable:

    [command] "C:\Program Files\dotnet\dotnet.exe" xunit D:\BuildTemp\Agent14\46\s\test\...Tests\...csproj -xml TestResults.xml

 I'm using the command line build step instead and set its working folder to "$(Build.SourcesDirectory)\test\...Tests", while setting the tool to dotnet.exe and the arguments to "xunit ...".

It's not very nice though.

Is there any way to tell the dotnet.exe to find the xunit "DotNetCliTool" even if it's not referenced within the current working directory? Or should we ask for some kind of "working folder" support, which seems to be missing in the .NET Core build step? With the current version the .NET Core build step cannot really support .NET CLI tool references...

**Comment by bradwilson** [comment]
> Is there any way to tell the dotnet.exe to find the xunit "DotNetCliTool" even if it's not referenced within the current working directory?

Unfortunately, no. This is a limitation of the .NET SDK and there's nothing that xUnit.net can do about this.
