### ISSUE TITLE
Can I run tests in sequence?

### ISSUE THREAD

**Issue by dinjonya** [xunit/xunit#1301]
I have some test and this tests muse be run in sequence. how can do it?

**Comment by pgorbas** [comment]
Me Too!  

I am having trouble getting your examples at [https://github.com/xunit/samples.xunit/tree/master/TestOrderExamples](url) to work.

When will test ordering be implemented as a core feature?

**Comment by bradwilson** [comment]
This is a sample, rather then being in the core product, because ordered tests are not appropriate for a unit testing framework; in fact, we go well out of our way to run tests in random order to prevent any order dependencies from being unintentionally introduced.

The sample is here for people who are writing something other than unit tests.

Our philosophy is that xUnit.net is a flexible & extensible testing platform which, by default, is optimized for our opinionated guidance on unit testing. It can be molded into other uses, but the core product is focused solely on unit testing.

**Comment by pgorbas** [comment]
Yeah, I can understand that.  I am actually running more of an integration test.  But I am new to testing.
I.E., I am wanting to run a series of test like this:

1. Start with dataBase table in initial state
2. Create a new element and add it to the table
3. Test that the new element is there.
4. Update the element in the table
5. Test that the updates were committed into DB
6. Delete the new element from the table
7 Test that the dataBase is back in its initial state.

As you can see, testing like this requires each step to be run in order.

**Comment by pgorbas** [comment]
Brad, Does the code to support test Ordering exists in version 2.2.0 and is it compatible with .net core 1.0+ ??

**Comment by bradwilson** [comment]
The sample should work fine on 2.2 in .NET Core.

**Comment by meehanman** [comment]
These work fine and allow ordering based on Priority or Alphabetical (https://github.com/xunit/samples.xunit/tree/master/TestOrderExamples/TestCaseOrdering)

**Comment by sandorfr** [comment]
@bradwilson that's great that the primitive TestCaseOrderer is now available in the framework. The samples seems to be working fine.

However I don't get why you are so reluctant to include them in the framework? Why have people copy pasting code for such a simple need. I understand that there are general good practice around unit test which go against test ordering, but testing is not only unit testing.

**Comment by bradwilson** [comment]
The objection is philosophical. We designed xUnit.net as a _unit testing_ tool, first and foremost. That people use it for other kinds of testing is okay, and expected (we made the extensibility points for just this reason), but it means that we are very selective about what goes into the core framework itself.

If someone wants to create NuGet packages for the more useful samples, we had an [open issue](https://github.com/xunit/xunit/issues/494) for two and a half years, and nobody seemed to want to do it. We would be happy to host them in the @xunit organization if someone actually decides to do them.

**Comment by sandorfr** [comment]
I think you are mistaken on the lack of interest for a nuget packages as there is one https://www.nuget.org/packages/XunitOrderer which unfortunately does not relies on your samples and primitives. And there a couple of (mostly out of date) blogs posts and issue here. 

Moving those samples to an official xunit.orderer package would seem reasonable to me.

**Comment by meehanman** [comment]
Although I agree with you @sandorfr a package for the additional samples should be included, but in the official NuGet package is the wrong way to go. 

XUnit should stick to the core unit-test principles, there is nothing stopping you or me to spend the time to create an additional package that extends the official package for use in UI Testing, and if kept up to date; with the support of @bradwilson to be added to the official documentation as a footnote.

**Comment by onovotny** [comment]
I already have the start of a UI Testing one...
https://github.com/xunit/uitest.xunit

Though it does need to be updated.

The issue I had was for desktop, given that WPF and WinForms do different things.

**Comment by erick-thompson** [comment]
The core problem (and is one that I'm running into) is that for integration or performance testing, there isn't anything close to xunit. Benchmark.NET is great for some use cases, but is far too complex for most integration tests (do setup, make a web call, see how long/if data shows up). The reality is that there isn't a decent solution for these types of tests, so we end up making xunit work. :)

**Comment by georgekucher** [comment]
Hi guys. Should the PriorityOrderer from Samples work for test methods from different classes, 'cause it doesn't for me.
Please help me to make it work so.
Thanks.

**Comment by bradwilson** [comment]
@georgekucher Please open a new issue with a repro.

**Comment by georgekucher** [comment]
@bradwilson no need. Solution was found.
http://www.tomdupont.net/2016/04/how-to-order-xunit-tests-and-collections.html

**Comment by meehanman** [comment]
Have you tried making your classes partial, to give them the same name and use traits to seperate out and tag tests

On 9 Aug 2018 11:48, georgekucher <notifications@github.com> wrote:

Hi guys. Should the PriorityOrderer from Samples work for test methods from different classes, 'cause it doesn't for me.
Please help me to make it work so.
Thanks.

**Comment by tomaszeman** [comment]
https://www.nuget.org/packages/Xunit.Extensions.Ordering

**Comment by danywehbe** [comment]
You can use the following attribute above the testing class:
[Collection("Serialize")]
and then each test class decorated with this attribute will run in sequence.

**Comment by upizs** [comment]
I found this one in Nuget Packages works beautifully 
https://github.com/asherber/Xunit.Priority
