### ISSUE TITLE
An Assert.Equal(float, float, int) overload should be provided.

### ISSUE THREAD

**Issue by tannergooding** [xunit/xunit#1302]
**Issue**
Currently the following two `Assert.Equal` overloads are provided:
```C#
Assert.Equal(decimal expected, decimal actual, int precision);
Assert.Equal(double expected, double actual, int precision);
```

However, there is no corresponding overload for `float`.

**Proposed Solution**
A new overload matching the following signature should be provided:
```C#
Assert.Equal(float expected, float actual, int precision);
```

**Additional Details**
I expect the reason this overload was not provided was because `System.Math` does not expose a `Math.Round(float, int)` overload.

However, on .NETCore, the `System.MathF` class exists and an appropriate overload is available so this should now be possible.

**Comment by hughbe** [comment]
+1 for consistency

**Comment by marcind** [comment]
System.MathF does not exist in .Net 4.5.2. Are you proposing that this functionality be conditional on the target runtime?

**Comment by tannergooding** [comment]
There is no reason why it could not be emulated on desktop. All float values should be directly represented as `double` values and could still undergo the appropriate rounding and comparisons.

**Comment by bradwilson** [comment]
Closing, since this doesn't seem necessary. Floats can be silently up-converted into doubles by the compiler. This works just fine:

```csharp
using System;
using Xunit;

public class UnitTest1
{
    [Fact]
    public void Test1()
    {
        float f1 = 1.01F;
        float f2 = 1.02F;

        Assert.Equal(f1, f2, 1);
    }
}
```
