### ISSUE TITLE
Analyzers for precision parameter of Assert.Equal overload for doubles and decimals

### ISSUE THREAD

**Issue by marcind** [xunit/xunit#1303]
The provided numbers get rounded with the given `precision` parameter, which is constrained to 0-15 for doubles and 0-28 for decimals (per msdn documentation for Math.Round)

**Comment by wachulski** [comment]
Can I get it assigned and start working?

**Comment by marcind** [comment]
Go for it. Looks like I can't assign you in GitHub because you are not part of the xunit org but it's your's.

**Comment by ErikSchierboom** [comment]
@wachulski Are you working on this?

**Comment by wachulski** [comment]
I started and stopped early after. @ErikSchierboom - do you want to take it over ?

**Comment by ErikSchierboom** [comment]
@wachulski It's up to you! If you don't feel like continuing, I'd be happy to take over. If you'd like to continue working on it, you're welcome of course.

**Comment by wachulski** [comment]
Ok, I'll try to get back to it in the next day or two, otherwise I'll leave it for sb else.

**Comment by wachulski** [comment]
FYI: I'm on it with ETA this week.
