### ISSUE TITLE
How to catch Table lock exception of sql from method in xunit method [ C# console Application]

### ISSUE THREAD

**Issue by yashfale** [xunit/xunit#1305]
Is there any function that allows to catch table lock sql exception in xunit method

**Comment by bradwilson** [comment]
There are two ways to catch exceptions when testing code in xUnit.net. The most common way is with `Assert.Throws`:

```csharp
var ex = Assert.Throws<SomeException>(() => myObject.MethodThatThrows(...));
```

If `SomeException` isn't thrown, then the test fails. If it is thrown, then `ex` contains the exception.

The alternative way preferred by people who like Arrange-Act-Assert style tests is `Record.Exception`:

```csharp
// Act
var ex = Record.Exception(() => myObject.MethodThatThrows(...));

// Assert
Assert.NotNull(ex);  // Make sure some exception was thrown
var someEx = Assert.IsType<SomeException>(ex);  // Make sure it's the type we expected
```

Using this method, `ex` is of type `Exception`, and it will be `null` if no exception has been thrown. You can use assertions like `NotNull` or `IsType` (as shown above) to ensure that an exception was thrown, and that it was of the expected type.

**Comment by yashfale** [comment]
Thank you @bradwilson
