### ISSUE TITLE
Alternative to xunit.runner.visualstudio? Not all Tests Discovered

### ISSUE THREAD

**Issue by thefringeninja** [xunit/xunit#1306]
After we converted our solution to use the new dotnet sdk build system, we found out that xunit stopped discovering tests all together. The solution was to add xunit.runner.visualstudio to the test project. After doing so, the resharper test runner will not discover all tests in a theory. According to https://xunit.github.io/faq/theory-data-stability-in-vs.html this is the expected behavior? I followed the advice here: https://github.com/xunit/xunit/issues/956 but in the resharper test runner, I don't see the individual tests anymore. What are my options?

**Comment by citizenmatt** [comment]
As far as I'm aware, the ReSharper runner works fine with theories from `dotnet`, just like full framework. Can you give version numbers of everything you're using, please? You also need to be on the latest ReSharper - so 2017.1

**Comment by bradwilson** [comment]
Closing as external.
