### ISSUE TITLE
Is there a way to run set custom Target Framework Moniker to Xunit runner?

### ISSUE THREAD

**Issue by safern** [xunit/xunit#1308]
In .NET Full Framework we have a lot of quirked behavior that uses the TFM of the current AppDomain when an application is started.  Since xunit.console.exe is the current AppDomain when our tests start we will get 4.5.2 as the TFM because that is what xunit targets. We have a lot of bug fixes or improvements that are enabled when TFM is at least 4.6.1 and we can't hit those cases because that behavior will never be enabled for us since the TFM will always be 4.5.2.

Is currently a way we could do that?

**Comment by bradwilson** [comment]
I'm not aware of anything you could do. Perhaps modifying the `.config` file of the console runner will give you the desired behavior.
