### ISSUE TITLE
Patterns to match test methods and classes in the test runner

### ISSUE THREAD

**Issue by hughbe** [xunit/xunit#1309]
From @danmosemsft in https://github.com/dotnet/corefx/issues/20627

> Nit: from command line, I have often wanted to pass a particular pattern to match test methods to execute. Right now I can do -method The.Full.Namespace.Class.Method but it would be so much easier to do -pattern *foo*. I used to do this on my old team with a different harness.

I'm not sure if this is `xunit.console.netcore.exe` specific though

**Comment by danmosemsft** [comment]
`-pattern *foo*`  (the asterisks above are making italics)

**Comment by bradwilson** [comment]
This tool is not part of xUnit.net.
