### ISSUE TITLE
Analyzer to detect [Theory] missing [InlineData] and [MemberData] etc.

### ISSUE THREAD

**Issue by hughbe** [xunit/xunit#1310]
Inspired by #1298.

I've lost track of the number of times I've written tests that have a [Theory] but forgotten to include the [MemberData] or [InlineData]. Instead the test just does nothing

**Comment by wachulski** [comment]
There is that diagnostic `xUnit1003` already telling *Theory methods must have test data*. Doesn't you see the test method marked red?

**Comment by hughbe** [comment]
Awesome. Thanks. I assume I hadn't set it up properly - can see it now
