### ISSUE TITLE
2.3b3 can't find ImmutableList field

### ISSUE THREAD

**Issue by rudym87** [xunit/xunit#1315]
After upgrading to 2.3 beta 3, I got a bunch of `System.MissingFieldException` because the test assembly seems not able anymore to access an `ImmutableList` declared in another referenced assembly.
Reducing its type to IEnumerable though fixes the accessibility. 

Here's some code to reproduce the problem:
In project A:
````c#
namespace A
{
    public static class C
    {
        public static readonly ImmutableList<int> ImmList = ImmutableList.Create(0, 1);
        public static readonly IEnumerable<int> ImmListAsIEnum = ImmList;

    }
}
````
In test assembly (which references project A and System.Collections.Immutable)
````c#
using A;
using Xunit;
...
        [Fact]
        public void CheckImmutableList()
        {
            Assert.NotEmpty(C.ImmList);
        }

        [Fact]
        public void CheckImmutableListAsIEnumerable()
        {
            Assert.NotEmpty(C.ImmListAsIEnum);
        }
````
The first test fails with a `System.MissingFieldException`, while the second one passes.
Downgrading to 2.3b2 makes both tests pass.
Tests also pass when moving C class in test assembly.

**Comment by bradwilson** [comment]
Please re-open with a repro project.
