### ISSUE TITLE
xUnit1004 - Test methods should not be skipped

### ISSUE THREAD

**Issue by onovotny** [xunit/xunit#1319]
What is the purpose or reasoning behind having this analyzer? I'm willing to bet that if a test is marked as skipped, there's a good reason for it. It will also show up as skipped in the runners. I don't think this should be an analyzer rule at all.

What reason is there for marking these at all, and warnings by default?

**Comment by marcind** [comment]
It's there for the people who believe tests should not be skipped, that it's an anti pattern. With this analyzer enabled, you either fix the test or delete it. Turn it up to an error or combine it with treat warnings as errors and checking skipped tests in is no longer possible.
People who like to skip tests can disable the analyzer. I opted to turn it on by default for now because with the lack of documentation nobody would discover that it exists and it would get no testing/feedback.

**Comment by marcind** [comment]
Btw, I think @bradwilson is typically one of those people, given this was originally his idea: https://github.com/xunit/xunit/issues/851#issuecomment-221040872

**Comment by onovotny** [comment]
I think it should be informational at best if it's enabled by default. Personally, I don't think it even needs to exist, but 🤷‍♂️

**Comment by marcind** [comment]
Yeah, turning it down to informational would be less intrusive for codebases with skipped tests. Let's leave this issue open for others to comment on.

**Comment by ErikSchierboom** [comment]
I sort of feel the same as @onovotny. Whenever I use Skip, it's for a good reason (mostly due to some test flakiness). I don't mind this analyzer, I actually think it's quite useful to prevent you from forgetting those skipped items. But I also do think that Informational would perhaps be better.

**Comment by jeremymeng** [comment]
We use `Skip` to disable tests that are blocked by external bugs. Any better alternatives?

**Comment by marcind** [comment]
Until I get around to changing the default severity of this rule, you can do so manually by [creating a custom ruleset](https://docs.microsoft.com/en-us/visualstudio/code-quality/creating-custom-code-analysis-rule-sets)

**Comment by ErikSchierboom** [comment]
@marcind I could give this a go next monday. The severity of this rule is to be changed to Informational, right?

**Comment by marcind** [comment]
Yes

**Comment by ErikSchierboom** [comment]
I've just submitted a [PR](https://github.com/xunit/xunit.analyzers/pull/58) to fix this.

**Comment by marcind** [comment]
Merged with https://github.com/xunit/xunit.analyzers/pull/58
