### ISSUE TITLE
Visual Studio for Mac does not detects my Tests

### ISSUE THREAD

**Issue by ChesaZ** [xunit/xunit#1321]
I have added xUnit as an extension and restarted the IDE. I have created a new xUnit Test project in my solution and wrote some code. Afterwards I went to [Run >> Run unit Tests] but this option appears to be grayed-out and I cannot click it. Does VS for Mac support yet xUnit?

**Comment by bradwilson** [comment]
This question probably belongs here: https://github.com/xunit/xamarinstudio.xunit

**Comment by ChesaZ** [comment]
@bradwilson ok, thanks for the heads up!
