### ISSUE TITLE
xUnit1013 - Public method 'Dispose' should be marked as fact for overriden Dispose()

### ISSUE THREAD

**Issue by GeorgDangl** [xunit/xunit#1323]
When I define an abstract base class that implements `IDisposable` and declares a `virtual Dispose()`, then override that method in a derived class I get the `Warning	xUnit1013	Public method 'Dispose' on test class 'DerivedIDisposable' should be marked as a Fact.` compiler warning.

![xunitdisposableerror](https://user-images.githubusercontent.com/10274404/27264416-181756c8-547e-11e7-9715-24c2df513160.PNG)

The [xunit.analyzer](https://github.com/xunit/xunit.analyzers/blob/4e4af38a4ca8391b5afa45362362fbe02e247f41/src/xunit.analyzers/PublicMethodShouldBeMarkedAsTest.cs#L38) calls `INamedTypeSymbol.AllInterfaces` (which is defined on the parent interface `ITypeSymbol`).

As per the [roslyn documentation](http://source.roslyn.io/#Microsoft.CodeAnalysis/Symbols/ITypeSymbol.cs,14726631ee5c2e02,references), the declared interfaces of base types should be present then:
```csharp
/// <summary>
/// The list of all interfaces of which this type is a declared subtype, excluding this type
/// itself. This includes all declared base interfaces, all declared base interfaces of base
/// types, and all declared base interfaces of those results (recursively). This also is the effective
/// interface set of a type parameter. Each result
/// appears exactly once in the list. This list is topologically sorted by the inheritance
/// relationship: if interface type A extends interface type B, then A precedes B in the
/// list. This is not quite the same as "all interfaces of which this type is a proper
/// subtype" because it does not take into account variance: AllInterfaces for
/// <c><![CDATA[IEnumerable<string>]]></c> will not include <c><![CDATA[IEnumerable<object>]]></c>;
/// </summary>
ImmutableArray<INamedTypeSymbol> AllInterfaces { get; }
```

I'm not sure what's happening here exactly, but it somehow doesn't recognize the overriden `Dispose()` as an implementation of an interface. This is with xUnit `2.3.0-beta4-build3710`.

**Comment by marcind** [comment]
Fix available in [v.0.5.0](https://github.com/xunit/xunit.analyzers/releases/tag/v0.5.0)

**Comment by mikesigs** [comment]
This is still an issue in v.0.8.0.
