### ISSUE TITLE
Analyzer xUnit1025 throws on test method default parameter values

### ISSUE THREAD

**Issue by wachulski** [xunit/xunit#1327]
While investigating #1324 I found a couple of faulty edge cases for xUnit1025. E.g.

```csharp
[Xunit.Theory]
[Xunit.InlineData(1, null)]
[Xunit.InlineData(1)]
public void TestMethod(int x, string y = null) { }
```
More detailed analysis: https://github.com/xunit/xunit.analyzers/pull/56

The fix should be rather straightforward: null checks should be added while examining InlineData arguments equivalence.

**Comment by marcind** [comment]
Are you working on the fix?

**Comment by wachulski** [comment]
Here you are: https://github.com/xunit/xunit.analyzers/pull/56

**Comment by marcind** [comment]
Fix available in [v.0.5.0](https://github.com/xunit/xunit.analyzers/releases/tag/v0.5.0)
