### ISSUE TITLE
AppVeyor: Test discovery OK, but runner fails

### ISSUE THREAD

**Issue by SuperJMN** [xunit/xunit#1331]
Hello!

I'm getting this in my AppVeyor build:

```
OmniXaml.Tests -> C:\projects\omnixaml\OmniXaml.Tests\bin\Debug\netcoreapp1.1\OmniXaml.Tests.dll
XamlLoadTest -> C:\projects\omnixaml\XamlLoadTest\bin\Debug\netcoreapp1.1\XamlLoadTest.dll
Discovering tests...OK
%xunit20%\xunit.console.x86 "C:\projects\omnixaml\OmniXaml.Tests\bin\Debug\netcoreapp1.1\OmniXaml.Tests.dll" -appveyor
xUnit.net Console Runner (32-bit .NET 4.0.30319.42000)
System.InvalidOperationException: Unknown test framework: could not find xunit.dll (v1) or xunit.execution.*.dll (v2) in C:\projects\omnixaml\OmniXaml.Tests\bin\Debug\netcoreapp1.1
Command exited with code 1
```

The Test Project file is here => (https://github.com/OmniGUI/OmniXAML/blob/master/OmniXaml.Tests/OmniXaml.Tests.csproj)

I don't know why.
I hope somebody knows how to fix it.

**Comment by IlyaFinkelshteyn** [comment]
Right, it is our (AppVeyor) issue. It is tracked in https://github.com/appveyor/ci/issues/1404. Sorry it takes little too long, we are putting things together and should fix it soon. For now use command line tools from article provided by Brad as `test_script`.

**Comment by bradwilson** [comment]
Closing as external.

**Comment by IlyaFinkelshteyn** [comment]
Actually now AppVeyor already discovers .NEt Core tests and runs `dotnet test` with proper options.
