### ISSUE TITLE
Modular test cases

### ISSUE THREAD

**Issue by perezLamed** [xunit/xunit#1332]
First, thanks for a great project. 

**Background:**
I have invested a lot of time to get more than 95% test coverage for my project. This has resulted in a lot of tests and test classes and I would like to manage this growing test code-base better. My project focuses on integration of different technologies into one simple interface. This design forces me to also have one big project with all test-cases for different technologies contained within it.

**The problem:**
I would like put my test cases in different projects libraries (dll's) and by some simple mechanism activate different test-cases for different projects. 

**Possible solution:**
I have found that the moment I inherit a test class from one of the library (dll) all test cases from that class become visible to the client test application. This works very well but:
.... in c# you can only inherit from one class at a time making this option only valid for 10% of cases.

**The question:**
Is it possible by some (simple) mechanism to create a test class "A" in a library (dll) that will make other test classes ("B", "C", "D") in that lib visible - that is when I run tests from class "A" it will run the test from test classes "B", "C", "D" also and when I inherit from class "A" it will also run tests from test classes"B", "C" and "D"?

If something like this is possible, please point me in the right direction?

**Comment by bradwilson** [comment]
There is no such mechanism available today, I'm afraid.

I'd have to think about how to use the extensibility points to enable this.

**Comment by perezLamed** [comment]
Thanks for the feedback. I have managed to create a workaround that seems to work very well. 

I define class "A" as a **partial** class and then classes "B", "C" and "D" becomes partial classes of "A".
Then when I run tests from class "A" the other classes also run. To add a new class to the group, I just include as a partial class. To remove a class from the group, I just remove the partial keyword and give it a unique name.

In the client test app I only inherit from class "A" and all test is discovered and run.
