### ISSUE TITLE
Static method in codebase causes xunit to 

### ISSUE THREAD

**Issue by JimBobSquarePants** [xunit/xunit#1333]
I don't know what causes this but as soon as this method is added to the codebase, dotnet.exe will get locked into a continues processing loop upon test discovery. Enabling diagnostic messaging yields no extra info.

https://github.com/JimBobSquarePants/ImageSharp/blob/ba8a5b34c8ec20043b0cb977f85f1d183158fe31/src/ImageSharp/Formats/Jpeg/Port/JpegDecoderCore.cs#L193

- xunit 2.3.0-beta2-build3683
- xunit.runner.visualstudio 2.3.0-beta2-build1317

I've tested against the most recent betas with the same issue. 

Let me know if you require any addition information.

Thanks.

**Comment by JimBobSquarePants** [comment]
It appears to be the presence of the variable name "buffer" that is causing the issue when checking the element at 0.

**Comment by bradwilson** [comment]
If this is still an issue with 2.3.1, please re-open.
