### ISSUE TITLE
Reasoning why TestMethodDisplay.NamespaceAndClassAndMethod was removed

### ISSUE THREAD

**Issue by poke** [xunit/xunit#1335]
Hey, I often have the problem that the name of the tests is not really well readable since the full qualified class name plus the test method name tends to get very long very quick, while just the method name is not specific enough to allow visual grouping.

So I was considering contributing to the project to add a `TestMethodDisplay` option to only show the class name and method name, without the full namespace.

That’s when I discovered 4a727d7b66 which removed exactly what I would wanted to propose. Unfortunately, the change does not explain why `NamespaceAndClassAndMethod` was removed in favor of just a single `ClassAndMethod` which does what the former would have done before.

Was this a fully intentional change and is a non-namespace including version not desired, or was this mostly a byproduct of the refactoring that was included in that change?

Or asked in a different way: Would work that added a `ClassAndMethodWithoutNamespace` (naming is WIP) to the enumeration be accepted?

**Comment by heaths** [comment]
I'd like to see this as well, since it would be a better work around to xUnit sending a GUID for theories to Test Explorer and our namespaces are also too long.

**Comment by bradwilson** [comment]
It was removed because of abstractions APIs don't support separating the namespace from the class name. So you can either name method name alone (`Method`), or Namespace + Class + Method (`ClassAndMethod`).

**Comment by heaths** [comment]
If you're talking about https://github.com/xunit/xunit/commit/4a727d7b6689752d514b4085f9b75882b6e1b1cf#diff-947f040e6da7bb0ae1a31254bf7ae0a3R70, could one just trim the class name from that last `.`?

**Comment by bradwilson** [comment]
Changing this enum at this point would be a breaking change for all runners, and would force a version 3.0 release. It's not gonna happen just for this.

There is a workaround: don't use namespaces for your test classes. We don't.

**Comment by heaths** [comment]
How would adding a value to the "end" of the enum break existing runners? It's never been an issue for the many public APIs I maintain. The value, it seems from the docs, is arbitrary to the xunit runner. If someone uses it, they'll need the corresponding xunit runner.

Alternatively, don't send theories with a GUID so that Test Explorer shows a tooltip with the parameters that are scrolling off the window and require constant resizing.

**Comment by bradwilson** [comment]
It's not adding a value to the end that's breaking behavior, it's changing the meaning of `ClassAndMethod` that's breaking behavior.

**Comment by poke** [comment]
@bradwilson That’s not really explaining whether a `ClassAndMethodWithoutNamespace` would be acceptable or not.

I understand that you are working differently so not using namespaces for test classes is an acceptable workaround; but it still stays a *workaround* and might not be a solution for other projects (e.g. in my case, it is not). So I personally would like to have a way to configure xunit in a way that only showed the test class and method but not the namespace, regardless of *how* that would work.

I would have a need for it, and I am willing to invest the work to get it in. But so far you haven’t answered whether *“a non-namespace including version not desired”*. If this was really intentionally removed because you don’t want it to be there, I can accept that. But if it was just removed as a byproduct of code changes and because you didn’t see an explicit need for it, then I would like to get this back in eventually.

**Comment by bradwilson** [comment]
This issue has been subsumed by #1429.
