### ISSUE TITLE
dotnet-xunit problem with SQLitePCL.raw

### ISSUE THREAD

**Issue by ericsink** [xunit/xunit#1336]
Not sure if I am doing something wrong, but I have a possible issue with dotnet-xunit.  The problem occurs with "dotnet xunit" but not with similarly-configured "dotnet test".

My conjecture is some kind of problem related to the presence of native code in the SQLitePCL.raw packages.

Repro, csproj:

    <Project Sdk="Microsoft.NET.Sdk">
      <PropertyGroup>
        <TargetFramework>netcoreapp1.1</TargetFramework>
      </PropertyGroup>
      <ItemGroup>
        <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="1.1.6" />
        <PackageReference Include="SQLitePCLraw.ugly" Version="1.1.6" />
        <PackageReference Include="xunit" Version="2.3.0-beta3-build3705" />
        <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta3-build3705" />
      </ItemGroup>
    </Project>

Repro, cs:

    using System;
    using SQLitePCL;
    using SQLitePCL.Ugly;
    using Xunit;

    namespace t2
    {
        public class Program
        {
            [Fact]
            public void t2()
            {
                SQLitePCL.Batteries_V2.Init();
                using (var db = ugly.open(":memory:"))
                {
                    db.exec("create table foo (x int);");
                }
            }
        }
    }

Error message:

    C:\Users\eric\dev\t2>dotnet xunit
    Detecting target frameworks in t2.csproj...
    Building for framework netcoreapp1.1...
      t2 -> C:\Users\eric\dev\t2\bin\Debug\netcoreapp1.1\t2.dll
    Running .NET Core tests for framework netcoreapp1.1...
    Error: assembly specified in the dependencies manifest was not found -- package: 'SQLitePCLRaw.lib.e_sqlite3.v110_xp', version: '1.1.6', path: 'runtimes/win7-x64/native/e_sqlite3.dll'

However, if I change the csproj to use "dotnet test", like this:

    <Project Sdk="Microsoft.NET.Sdk">
      <PropertyGroup>
        <TargetFramework>netcoreapp1.1</TargetFramework>
      </PropertyGroup>
      <ItemGroup>
        <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="1.1.6" />
        <PackageReference Include="SQLitePCLraw.ugly" Version="1.1.6" />
        <PackageReference Include="microsoft.net.test.sdk" Version="15.0.0" />
        <PackageReference Include="xunit" Version="2.2.0" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
      </ItemGroup>
    </Project>

Then this works:

    C:\Users\eric\dev\t2>dotnet test
    Build started, please wait...
    Build completed.

    Test run for C:\Users\eric\dev\t2\bin\Debug\netcoreapp1.1\t2.dll(.NETCoreApp,Version=v1.1)
    Microsoft (R) Test Execution Command Line Tool Version 15.3.0-dev
    Copyright (c) Microsoft Corporation.  All rights reserved.

    Starting test execution, please wait...
    [xUnit.net 00:00:00.6207155]   Discovering: t2
    [xUnit.net 00:00:00.7404275]   Discovered:  t2
    [xUnit.net 00:00:00.7966117]   Starting:    t2
    [xUnit.net 00:00:00.9394949]   Finished:    t2

    Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
    Test Run Successful.
    Test execution time: 1.6150 Seconds

**Comment by stil** [comment]
I have almost identical problem but with with NLog instead of SQLitePCL.raw, here https://github.com/NLog/NLog/issues/2187

**Comment by elovelan** [comment]
seeing similar issues.

doing a `dotnet publish` and then copying `bin/*/publish/frameworks` to just `bin/*/frameworks` "resolved" it

**Comment by bradwilson** [comment]
This appears to be the same problem as #1363, which was just fixed in `2.3.0-rc1-build3780` (available right now via [MyGet](https://myget.org/gallery/xunit)).
