### ISSUE TITLE
Reporter value 'teamcity' is invalid. There are no available reporters.

### ISSUE THREAD

**Issue by kosa-gyula-77** [xunit/xunit#1339]
Hi,

When specifying "teamcity" for the reporter, I get the following error:

_Reporter value 'teamcity' is invalid. There are no available reporters._

The issue is reproducible with the solution attached when running the following msbuild command from powershell:

_PS C:\Users\xxx\Documents\visual studio 2017\Projects\xunitreporters\xunitreporters> & 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe' .\xunitreporters.csproj /p:Configuration=Debug /t:RunXUnitTests_

The **xunit.runner.reporters.net452.dll** is present at C:\Users\xxx\Documents\visual studio 2017\Projects\xunitreporters\packages\xunit.runner.msbuild.2.3.0-beta3-build3705\build\net452

Could you please help resolving the issue?

Thanks,
Gyula

[xunitreporters.zip](https://github.com/xunit/xunit/files/1112543/xunitreporters.zip)

**Comment by kosa-gyula-77** [comment]
**xunit.runner.reporters.net452.dll** is present at C:\Users\xxx\Documents\visual studio 2017\Projects\xunitreporters\packages\xunit.runner.msbuild.2.3.0-beta3-build3705\build\net452

**Comment by bradwilson** [comment]
This has been fixed.
