### ISSUE TITLE
Visual Studio test runners do not enumerate theory correctly when member data yields non default types.

### ISSUE THREAD

**Issue by danrozenberg** [xunit/xunit#1341]
Please consider the following class:

```   csharp 
public class DataTransferObject
    {
        public string Foo { get; set; }

        public int Bar { get; set; }

        public override string ToString()
        {
            return Foo + " " + Bar.ToString();
        }
    }
```

The following test methods shows up correctly in Resharper and Test Explorer:

```  csharp 
        public static IEnumerable<object[]> GetPrimitiveArguments()
        {
            yield return new object[] { "some string", 3 };
            yield return new object[] { "another string", 6 };
        }

        [Theory, MemberData(nameof(GetPrimitiveArguments))]
        public void ParameterizedWithPrimitives(string myString, int myInt)
        {
            Assert.True(myInt >= 0);
        }
```

However, the following theory shows up as a single method. 

```  csharp 
        public static IEnumerable<object[]> GetDtoArgument()
        {
            yield return new object[] { new DataTransferObject { Foo = "some string", Bar = 3 } };
            yield return new object[] { new DataTransferObject { Foo = "another string", Bar = 6 } };
        }

        [Theory, MemberData(nameof(GetDtoArgument))]
        public void ParameterizedWithDto(DataTransferObject myDto)
        {
            Assert.True(myDto.Bar >= 0);
        }
```

If we execute the second theory, both test will run, but only one result ever shows up...if we have tests that take longer to execute, Resharper will also complain that xUnit is still running while the test has finished (in reality, the second test is still running).

However, both tests enumerate correctly in the console runner using ``dotnet-xunit``...
Am I doing something wrong, or is there an issue with how the GUI runners communicate with xUnit?

**Comment by danrozenberg** [comment]
Some screenshots...
![evidence1](https://user-images.githubusercontent.com/9957383/27755946-248c146a-5da8-11e7-927b-0f53b25603b5.JPG)

![evidence2](https://user-images.githubusercontent.com/9957383/27755947-27af4306-5da8-11e7-849b-94cc740d1522.JPG)

**Comment by bradwilson** [comment]
This is expected behavior.

The Visual Studio test runner requires that all data values implement our custom serialization system (IXunitSerializable) to get individual data rows in the UI.

**Comment by danrozenberg** [comment]
Thank you, Brad. I will look into it.

**Comment by danrozenberg** [comment]
For those stumbling into this thread, I got everything working with the help of Brad's sample code found in this other issue: https://github.com/xunit/xunit/issues/479
