### ISSUE TITLE
Executing tests with .NET 4.6.1 using a .NET Standard 2.0 library

### ISSUE THREAD

**Issue by ErikEJ** [xunit/xunit#1343]
Hi, is the following a supported scenario?

- NET 4.6.1 "classic" class library that references tests in EF Core 2.0 preview-2 (a .NET Stanadard 2.0 library) https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Relational/2.0.0-preview2-final (via https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/2.0.0-preview2-final )

- Visual Studio 2017 15.3 preview 3

- XUnit 2.2

Issues:
- No tests discovered by the VS test explorer
- TestDriven.NET does not install in preview, so I have no idea if that could work

**Comment by bradwilson** [comment]
I've never tried this combo, but I don't see any red flags.

Can you get tests to run with the console runner?

**Comment by ErikEJ** [comment]
Thnaks, Brad! Yes, I can run with Console runner - next issue:       

System.IO.FileLoadException : Could not load file or assembly 'System.ValueTuple, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
      Stack Trace:
           at Microsoft.EntityFrameworkCore.Metadata.Internal.TableMapping.GetTableMappings(IModel model)

(Not related to xUnit)
