### ISSUE TITLE
Using AssemblyRunner.WithAppDomain doesn't allow to delete the test assembly file

### ISSUE THREAD

**Issue by rudrahotta** [xunit/xunit#1347]
Hi, 
We are currently executing our xunit test using   XUnit AssemblyRunner and every things work fine.  Next we want to cleanup all the test resources once the test is completed. while doing so we are unable to delete the test assembly for which it says it is opened by the current process. 

Can someone please help us?

Our code....
```csharp
  var assembly = Assembly.LoadFrom(Path.Combine(_testAssemblyDirectory, TestRunConfiguration.TeamTestScriptProfile.AssemblyName));
            using (var runner = AssemblyRunner.WithAppDomain(assembly.Location))
            {
                LocalLog.Info("Discovering tests...");
                if (TestRunConfiguration.TestFilters != null && TestRunConfiguration.TestFilters.Length > 0)
                {
                    LocalLog.Info($"Apply test case filter: {string.Join(@"\r\n", TestRunConfiguration.TestFilters.Select(a=>a.ToString()))}.");
                    runner.TestCaseFilter = DynamicTestCaseFilter; 
                } 

                runner.OnDiscoveryComplete = OnDiscoveryComplete;
                runner.OnTestStarting = OnTestStarting; 
                runner.OnTestFailed = OnTestFailed;
                runner.OnTestSkipped = OnTestSkipped;
                runner.OnTestPassed = OnTestPassed;
                runner.OnExecutionComplete = OnExecutionComplete; 
               
                runner.Start(); 

                _finished.WaitOne();
                _finished.Dispose(); 
            } 
            return _testRunResult;

//delete the _testAssemblyDirectory
```

**Comment by bradwilson** [comment]
Do you have a configuration file (either App.config or xunit.runner.json)? If so, what are the xUnit-related settings?

**Comment by rudrahotta** [comment]
The test project. we are trying to test out with runner (above code) have few basic  tests (no customize settings for XUnit).  We are using the runner as console runner doesn't support AND operator when multiple traits are supplied.

**Comment by rudrahotta** [comment]
One more issue we noticed today, the above code throws error (not always). It happens for two run out of 12 runs.  This happen after OnExecutionComplete event as I can see the overall result.

System.InvalidOperationException: Cannot dispose the assembly runner when it's not idle
   at Xunit.Runners.AssemblyRunner.Dispose()

Let me know any more information required.

Thanks,
Rudra

**Comment by bradwilson** [comment]
Please re-open with a repro project.

**Comment by jarvisuser90** [comment]
Adding this check at the end, before returning, solved the problem for me.

```csharp
// Start testing!
assemblyRunner.Start();

// Wait for all tests to run.
Finished.WaitOne();
Finished.Dispose();
            
while (assemblyRunner.Status != AssemblyRunnerStatus.Idle)
{
    // Wait for assembly runner to finish.
    // If we try to dispose while runner is executing,
    // it will throw an error.
    Thread.Sleep(100);
}

return result;
```

**Comment by shenglol** [comment]
I came across this and the workaround above solve the issue for me as well. I wonder if this is a race condition due to the fact that [`OnExecutionComplete` is invoked before `executionCompleteEvent.Set`](https://github.com/xunit/xunit/blob/bddd53fbe6c8a88abe286719588fd99ac27e266e/src/xunit.v3.runner.utility/Runners/AssemblyRunner.cs#L372C1-L372C1). The latter is used to determine if `Status` is `Executing`. If `Finished` is set upon test completion, there is a chance that `AssemblyRunner` will be disposed before `Status` becomes `Idle`.
