### ISSUE TITLE
BeforeAfterTestAttribute to receive test instance?

### ISSUE THREAD

**Issue by sethcall** [xunit/xunit#1354]
Is there any way to get the test class instance that is being executed?  If not, could it receive it as an argument or otherwise have someway to access it?

Thanks!
Seth

**Comment by bradwilson** [comment]
There is not, purposefully. We envisioned BeforeAfter attributes to be orthogonal to the test in question. If you need access to the test class, then you should be using the test class's constructor and Dispose methods instead.
