### ISSUE TITLE
Some tests fail when "Run All" in "Test Explorer"

### ISSUE THREAD

**Issue by ircnelson** [xunit/xunit#1356]
When I use "Run All" in Test Explorer on VS2017 some tests fails, but all tests works fine when I "Run Seleceted Tests".

P.S.: This happens with parallels enable or disable.

![xunit-vs2017](https://user-images.githubusercontent.com/4714/28031029-017bee18-6574-11e7-8da6-e096283e9cb9.jpg)

**Comment by marcind** [comment]
That's unfortunate. Could you provide any more information that would help figure out what's going on?

**Comment by ircnelson** [comment]
Target framework: 
* net461 
* netcoreapp1.1

Packages: 
* Microsoft.NET.Test.Sdk (15.0.0)
* xunit (2.3.0-beta2-build3683)
* xunit.runner.visualstudio (2.3.0-beta2-build1317)

The assertions failed on tests that uses` ICollectionFixture<T>`.

P.S.: The code doesn't have any static field/property that could be shared.

I tried use xunit/xunit.runner.visualstudio 2.2.0 (stable version), but didn't works too.

When I using dotnet cli, works fine too. This problem occour only by "Run All".

**Comment by marcind** [comment]
Is there any information in the failed tests' detail views?

**Comment by ircnelson** [comment]
![xunit-vs2017 2](https://user-images.githubusercontent.com/4714/28037820-c4070ad8-658a-11e7-9049-d7ef3edb9c66.jpg)

**Comment by marcind** [comment]
Honestly it would be easiest if you could provide the source of a repro project.

**Comment by ircnelson** [comment]
[check here...](https://github.com/ircnelson/enjoy.cqrs/tree/features/projection)

branch: features/projection

**Comment by Bogatinov** [comment]
Have been using v2.2.0 for a while now. Tried today to update to v2.3.0 and the same behavior happened. Running via Traits/Projects/Classes etc works as intended. 

We have in `AssemblyInfo` the following code
```
[assembly: CollectionBehavior(MaxParallelThreads = 1, DisableTestParallelization = true)]
```

After monitoring, and still unable to find why from 1000 tests, only 16 fail, maybe some of these cause breaking change in v2.3.0

- ShimsContext 
- ThreadStatic session context from NHibernate
- One `ICollectionFixture` and one `IClassFixture` in same assembly where `IClassFixture` does not use the collection context
- Parallel tests have changed in v2.3.0 and no longer use configuration from `AssemblyInfo`

**Comment by bradwilson** [comment]
Please re-open with a repro project. (The provided repro is gone now.)

**Comment by brianperera** [comment]
Any solution for this? I'm currently facing the same issue after upgrading from .NET 1.1 to 2.2

**Comment by orihomie** [comment]
I'm facing this issue still.
