### ISSUE TITLE
No executable found matching command "dotnet-xunit" with .NET Core 2-preview2

### ISSUE THREAD

**Issue by ThmX** [xunit/xunit#1358]
Using .NET Command Line Tools (2.0.0-preview2-006497), the `dotnet xunit` command can't be launched producing this error `No executable found matching command "dotnet-xunit"`

Here's my .csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0-preview-20170517-02" />
    <PackageReference Include="xunit" Version="2.3.0-beta3-build3705" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-beta3-build3705" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta3-build3705" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyApp\MyApp.csproj" />
  </ItemGroup>
</Project>
```

I did `dotnet restore` and using `dotnet test` is working.
But the problem is that I'd like to use -xml in order to use the result on a CI Server.

Any ideas?

**Comment by bradwilson** [comment]
You **must** run the command from the folder containing your `.csproj` file.

**Comment by ThmX** [comment]
I tried in the solution and project folders, neither are working.

**Comment by ThmX** [comment]
After looking a bit inside my `.nuget` folder, I was able to launch it by directly calling the `dotnet-xunit.dll` from it:
```bash
$ cd MyApp.Tests/
$ dotnet /Users/thmx/.nuget/packages/dotnet-xunit/2.3.0-beta4-build3722/lib/netcoreapp1.0/dotnet-xunit.dll
Detecting target frameworks in MyApp.Tests.csproj...
Building for framework netcoreapp2.0...
...
```

**Comment by ThmX** [comment]
Oh my bad, I reverted yesterday and today messed up the `.csproj`.
Everything is working now.

**Comment by dasjestyr** [comment]
Sorry to resurrect but I have the same problem. If I run it from inside the project folder, I get:

> The specified SDK version [2.0.0] from global.json [/home/bamboo/source/das.core/src/global.json] not found; install specified SDK version
> Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
>   http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

And if I run it from outside the project folder:

> No executable found matching command "dotnet-xunit"

**Comment by bradwilson** [comment]
The instructions are fairly clear: you're missing the version of the SDK you requested.

Running from outside the project folder is not supported.

**Comment by agray** [comment]
I think I am getting this problem too:

    c:\Workspace\GitRepositories\DNCTest\DNC.XTest>dotnet C:\Users\xxx\.nuget\packages\dotnet-xunit\2.3.1\lib\netcoreapp2.0\dotnet-xunit.dll
    Detecting target frameworks in DNC.XTest.csproj...
    Building for framework netcoreapp2.0...
      DNC.Engine -> 
    c:\Workspace\GitRepositories\DNCTest\DNC.Engine\bin\Debug\netcoreapp2.0\DNC.Engine.dll
      DNC.XTest -> 
    c:\Workspace\GitRepositories\DNCTest\DNC.XTest\bin\Debug\netcoreapp2.0\DNC.XTest.dll
    Running .NET Core 2.0 tests for framework netcoreapp2.0...
    The specified framework version '2.0' could not be parsed
    The specified framework 'Microsoft.NETCore.App', version '2.0' was not found.
      - Check application dependencies and target a framework version installed at:
          C:\Program Files\dotnet\
      - Installing .NET Core prerequisites might help resolve this problem:
          http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
      - The .NET Core framework and SDK can be installed from:
          https://aka.ms/dotnet-download
      - The following versions are installed:
          1.0.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
          1.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
          1.1.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
          2.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
          2.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
          2.1.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

I don't understand because v2.0 is installed (see third last line of above console extract) at C:\Program Files\dotnet\shared\Microsoft.NETCore.App

Why is it no seeing it?

**Comment by bradwilson** [comment]
`dotnet xunit` is no longer supported.

**Comment by agray** [comment]
Could you please advise the supported way going forward?

**Comment by bradwilson** [comment]
For 2.x, the only supported way to run .NET Core tests is with the `xunit.runner.visualstudio` package (and either Test Explorer inside Visual Studio and/or the `dotnet test` command line).

**Comment by agray** [comment]
> I have installed dotnet-sdk-2.1.403-win-x64.

I seem to have solved the issue of basic execution by adding `<RuntimeFrameworkVersion>2.1.5</RuntimeFrameworkVersion>` to my csproj file in the `<PropertyGroup>` section.

**Comment by agray** [comment]
> > I have installed dotnet-sdk-2.1.403-win-x64.
> 
> I seem to have solved the issue of basic execution by adding `<RuntimeFrameworkVersion>2.1.5</RuntimeFrameworkVersion>` to my csproj file in the `<PropertyGroup>` section.
> 
> My remaining issue is to get `dotnet test` to emit XUnit XML to a file that the Jenkins XUnit plugin can consume.

Have solved [this](https://github.com/spekt/xunit.testlogger) with this nuget package

**Comment by RehanSaeed** [comment]
Do we need to leave `IncludeAssets` in the package reference? I'd much prefer:

```
<PackageReference Include="xunit.runner.visualstudio" PrivateAssets="All" Version="2.4.1"/>
```

Over:

```
<PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
</PackageReference>
```
