### ISSUE TITLE
libgrpc_csharp_ext.x64.dylib not found (.net core 2 preview 2)

### ISSUE THREAD

**Issue by Jonathan34** [xunit/xunit#1363]
Please read https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/1205

Everything works with these dependencies:
```
<ItemGroup>
  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0-preview-20170517-02" />
  <PackageReference Include="xunit" Version="2.2.0" />
  <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  <PackageReference Include="Grpc.Core" Version="1.4.1" />
</ItemGroup>
```

but it does not anymore when we use `<PackageReference Include="xunit" Version="2.3.0-beta*" />`

final error:
```
System.IO.FileNotFoundException : Error loading native library. Not found in any of the possible locations: /Users/jdelfour/code/UCP/UDL-API/ihs/test/IntegrationTests/bin/Debug/netcoreapp2.0/libgrpc_csharp_ext.x64.dylib,/Users/jdelfour/code/UCP/UDL-API/ihs/test/IntegrationTests/bin/Debug/netcoreapp2.0/runtimes/osx/native/libgrpc_csharp_ext.x64.dylib,/Users/jdelfour/code/UCP/UDL-API/ihs/test/IntegrationTests/bin/Debug/netcoreapp2.0/../../runtimes/osx/native/libgrpc_csharp_ext.x64.dylib
```

```
dotnet --info
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0-preview2-006497/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9
```

**Comment by jskeet** [comment]
FYI, the test project can be standalone with a very simple test:

```csharp
using Grpc.Core;
using System;
using Xunit;

namespace GrpcBug2
{
    public class UnitTest1
    {
        [Fact]
        public void Test1()
        {
            var channel = new Channel("localhost:8080", ChannelCredentials.Insecure);
        }
    }
}
```

**Comment by mamaso** [comment]
This is also an issue on windows.

**Comment by mamaso** [comment]
Looked a bit more into this:

Grpc is finding `runtimes` by looking relative to assembly location of `grpc.core.dll`.
https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/Internal/NativeExtension.cs#L106

For most projects, dependencies are not copied to output directory, so `grpc.core.dll` is found in the nuget cache location of `runtimeconfig.dev.json` `additionalProbingPaths`. Xunit test projects set `CopyNugetImplementations`, which drops all .dlls in output directory https://github.com/xunit/xunit/blob/master/src/xunit.core/build/xunit.core.props#L6

A workaround is to delete `grpc.core.dll` from the output folder prior to running tests - it will be found via `additionalProbingPaths` in a location that correctly references `runtimes`.

**Comment by jskeet** [comment]
I'll look at this again, as we're now using xunit 2.3.0-beta4 and it doesn't seem to be a problem. I wonder whether something else has changed somewhere (we're using the full release of .NET Core 2.0 SDK of course...)

**Comment by jskeet** [comment]
Ah - this only fails when targeting netcoreapp2.0 - if you target netcoreapp1.0 or net461, it's fine.

**Comment by jskeet** [comment]
I'm still not sure what the right long-term solution is though. It looks like `CopyNugetImplementations` assumes that only the managed code is required, which doesn't sound good to me.

I'm confused as to why it works under netcoreapp1.0 though, as Grpc.Core.dll is present in bin\Debug\netcoreapp1.0 as well. Looking a bit more closely, even though Grpc.Core.dll is present, the CLR is still *loading* it from the nuget package location under netcoreapp1.0, whereas with netcoreapp2.0 the CLR is loading it from the bin\Debug\netcoreapp2.0 directory.

**Comment by jskeet** [comment]
+jtattermusch for visibility

**Comment by bradwilson** [comment]
We had bugs in netcoreapp2.0 support in beta 4. See if beta 5 works better for you.

**Comment by jskeet** [comment]
I thought I'd tried that this morning, but will definitely check.

**Comment by jskeet** [comment]
Nope, same behaviour with 2.3.0-beta5-build3769.

Is the expectation that the Grpc.Core.dll assembly *should* be loaded from bin/Debug/netcoreapp2.0 or from the .nuget cache? I still don't understand why it's loaded from different places under different targets. (If it *is* meant to be loaded from bin/Debug/netcoreapp2.0, we can then try to work out whether we should expect the native code to be copied under there too, and whether there's a way of achieving that. There's not a lot of documentation on how one is expected to bundle native code in a nuget package.)

**Comment by bradwilson** [comment]
We have a hook to provide any "missing" DLL, and we look in your bin directory. It may be that .NET Core 2.0 has changed loading priority and is favoring the bin folder over the NuGet cache path, whereas it was the opposite in 1.x (this is just a wild guess based on the behavior your seeing; I'm away from a laptop for at least another week).

**Comment by Disturbing** [comment]
Just following up that beta5 still has this issue, any eta?

**Comment by jskeet** [comment]
What's unclear to me at the moment is whether this is:

- A gRPC packaging issue (could we package it differently so that the files are found?)
- A gRPC code issue (should we try to find the files in a different way?)
- A dotnet cli/build issue (should it be copying files differently?)
- An xUnit issue (should it be loading anything differently?)

I've never found good, clear guidance about how to package native binaries in the brave new .NET Core world. I've found lots of articles with "bits" of the puzzle, but no authoritative source.

**Comment by bradwilson** [comment]
No ETA yet.

**Comment by bradwilson** [comment]
> * An xUnit issue (should it be loading anything differently?)

This seems to imply it's us:

> A workaround is to delete grpc.core.dll from the output folder prior to running tests - it will be found via additionalProbingPaths in a location that correctly references runtimes.

It sounds like a solution will need to be used wherein we can turn off copying NuGet dependencies, but it will take some time to figure out what the implications of that are across all runners (VS w/ desktop, UWP, and .NET Core; devices runner w/ UWP, iOS, and Android; MSBuild w/ desktop and .NET Core, etc.).

**Comment by jskeet** [comment]
Indeed - the portability of .NET is *fantastic* in terms of what we can do, but it does make things significantly more complicating when thinking about things like this :)

Let me know if there's anything I can do to help.

**Comment by Disturbing** [comment]
Yeah it's def on xunit's end:

latest xunit beta4 and .net core 1.0 work great + grpc 1.4.1. (beta 5 does
not work).
Goal: latest xunit + .net core 2.0 + grpc 1.4.1.

FYI - This is only when I wanna start a server or channel (local server
testing) which is a gRPC recommended setup.

It's not just grpc either, I can't run any mongodb tests (where I actually
connect via a mongodb client) with a similar error.  There's something a
little off with the .netcore 2.0 environments that need to be resolved.

**Comment by bradwilson** [comment]
There was a breaking (to us) change between .NET Core SDK 1.x and 2.x wherein some conditions we were relying upon in our `.props` files weren't set yet (namely, `$(TargetFramework)`), which was causing some properties that are being correctly set in .NET Core SDK 1.x to not be set in .NET Core SDK 2.x. Moving these into the `.targets` file seems to resolve them in my local experimentation.

I believe that, also, the copying of DLLs into the `bin` folder is no longer necessary at all, and may be a hold-over from pre-`.csproj` days, when people (namely, us 😝) were using `project.json` to do multi-targeting, and dependent DLLs weren't being correctly copied for desktop CLR projects. I've removed this and I'm going to do some more experimentation to see if it's necessary to restore this behavior, and if so, make sure we do so _**only**_ for desktop CLR projects (rather than doing it in a blanket fashion as we do today).

**Comment by bradwilson** [comment]
(This is all a long way of saying that I think this will be fixed in RC1.)

**Comment by bradwilson** [comment]
So far so good with `2.3.0-rc1-build3780` (available via [MyGet](https://myget.org/gallery/xunit)); it appears to be copying locals for desktop CLR without needing any additional flags, and now I've gotten my `.runtimeconfig.json` file correctly generating on .NET Core again:

![Files and whatnot](https://user-images.githubusercontent.com/16944/30776116-a9d7daf6-a055-11e7-94e9-0da3453cb202.png)

Now to test gRPC...

**Comment by bradwilson** [comment]
Victory!

![Victory dance](https://user-images.githubusercontent.com/16944/30776177-bb4b9808-a056-11e7-9800-353069430806.png)

**Comment by mamaso** [comment]
Awesome job @bradwilson and others, thanks for getting this resolved :)

**Comment by bradwilson** [comment]
It has the additional win of not needing to copy all the dependencies any more, which people have been after me about for a while now. ;)

**Comment by Disturbing** [comment]
Yeee!
Gj

**Comment by vassilvk** [comment]
Nice! Thanks @bradwilson for fixing this!!

**Comment by Jonathan34** [comment]
Thanks to everyone for fixing this ! good job :)

**Comment by bradwilson** [comment]
I've managed to break other things with this fix, so no premature celebrating... 😒

**Comment by Disturbing** [comment]
Dev Life :)
