### ISSUE TITLE
Xunit .NET full tests not discovered

### ISSUE THREAD

**Issue by bencyoung** [xunit/xunit#1364]
I have a set of unit test project that are currently .NET Core 2. If I change it to net462 then I get errors from VS. It looks like it's trying to use the netcore runner still:

[12/07/2017 13:49:36 Error] C:\Users\Ben.Young\AppData\Local\Temp\VisualStudioTestExplorerExtensions\2.2.0/build/netcoreapp1.0/xunit.runner.visualstudio.dotnetcore.testadapter.dll
[12/07/2017 13:49:38 Error] C:\Users\Ben.Young\AppData\Local\Temp\VisualStudioTestExplorerExtensions\2.2.0/build/netcoreapp1.0/xunit.runner.visualstudio.dotnetcore.testadapter.dll

Is there anything I can do here? The project is below (it's a common props file imported by the actual test projects)

```
<Project>
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <IsPackable>false</IsPackable>
    <CodeAnalysisRuleSet>$(MSBuildThisFileDirectory)codeanalysis.ruleset</CodeAnalysisRuleSet>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0-preview-20170427-09" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.0.2" PrivateAssets="All" />
    <PackageReference Include="NETStandard.Library.NETFramework" Version="2.0.0-preview1-25305-02" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)stylecop.json" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>
</Project>
```

**Comment by bradwilson** [comment]
Are you running on a machine that has .NET 4.7 installed on it? If so, you may be hitting this bug: https://github.com/xunit/xunit/issues/1348

**Comment by bencyoung** [comment]
No, 4.6.2 unfortunately!

**Comment by bradwilson** [comment]
Does the problem persist if you shut down and restart Visual Studio? Generally speaking... it's kind of a crap shoot using their runner.

**Comment by bencyoung** [comment]
I'll give that a try. What's the recommended method then? On the commandline?

**Comment by bencyoung** [comment]
On the command line it does get picked up. So do I need to report this on a VS list somewhere?

**Comment by bradwilson** [comment]
Yes, please report this to VSTest: https://github.com/microsoft/vstest

**Comment by atjensw** [comment]
I had the same issue. Removing all files in AppData\Local\Temp\VisualStudioTestExplorerExtensions\ and restart of visual studio made it work again.

**Comment by Luis-Palacios** [comment]
@atjensw I had the same problem your solution worked like magic Thank you!
