### ISSUE TITLE
Code fix for Assert.IsType<T> has incorrectly titled menu item "Use Assert<T>.IsType"

### ISSUE THREAD

**Issue by stakx** [xunit/xunit#1366]
Note how in the below screenshot, the xUnit.net analyzer suggests changing `Assert.IsType(typeof(string), …)` to `Assert.IsType<string>(…)`, but the menu item is erroneously titled `Assert<string>.IsType`:

![xunit-analyzer-assert-istype](https://user-images.githubusercontent.com/104481/28302287-ab3eefc2-6b8c-11e7-8372-0e59ee1f7476.png)

The menu item should be titled **Use `Assert.IsType<string>`**.

This is with package `xunit` version 2.3.0-beta3-build3705.

**Comment by ErikSchierboom** [comment]
@stakx Good catch! I'll be fixing this.

**Comment by ErikSchierboom** [comment]
@stakx The [PR](https://github.com/xunit/xunit.analyzers/pull/61) has been submitted

**Comment by stakx** [comment]
Awesome, thanks for fixing this!

**Comment by ErikSchierboom** [comment]
@stakx You're welcome, although I have to admit it was also my mistake to begin with ;)

**Comment by marcind** [comment]
Fixed in xunit/xunit.analyzers#61
