### ISSUE TITLE
xunit tests not discovered in VS due to .csproj parsing 

### ISSUE THREAD

**Issue by sivakhno** [xunit/xunit#1368]
I wander if anyone has recently encountered a test discoverability problem with xunit (Test => Run All Tests) in the most recent visual studio 2017 15.2, I get:

======
No plugin found which can import settings file with extension '.csproj'. Either select a new settings file or install an extension which understands this settings file extension.
========== Discover test finished: 0 found (0:00:00.0010001) ==========

The error occurs with two configurations (VS 2017 Enterprise 15.2):

Microsoft.NET.Test.Sdk 2.3.0-beta3-build3705
xunit.runner.visualstudio 15.3.0-preview-20170628-02

Microsoft.NET.Test.Sdk 15.0.0
xunit.runner.visualstudio 2.2.0

Any suggestions will be most appreciated, I have tried a number of fixes incl. deleting TEMP at no avail.

**Comment by bradwilson** [comment]
This looks like you've told Visual Studio that your `.csproj` file is a test settings file. You should not do this. If you want a test settings file, please create a new test settings file, as described here: https://msdn.microsoft.com/en-us/library/jj635153.aspx
