### ISSUE TITLE
Directory.build.props causes error

### ISSUE THREAD

**Issue by jchannon** [xunit/xunit#1369]
When a `Directory.build.props` exists and I run `dotnet xunit` I get 

```
/Users/jonathan/Projects/vq/test/VQPortal.Tests.Integration/VQPortal.Tests.Integration.csproj : error MSB4057: The target "_Xunit_GetTargetFrameworks" does not exist in the project.
Detection failed! Please ensure you're using 'xunit.core' v2.3 beta 2 or later.
```
If I remove the `Directory.build.props` file it works fine.

This file if you don't know is like a master csproj type file where you can specify dependencies that projects in sub directories will pick up so when running dotnet restore/build the 2 files get merged.

This is seen on `2.3.0-beta3-build3705`

**Comment by bradwilson** [comment]
Please provide a repro.

**Comment by jchannon** [comment]
This was due to having xunit defined in the props file and in the csproj. It didn't like it so tip , dont mix versions.
