### ISSUE TITLE
Assert.Equal ignoreWhiteSpaceDifferences & ignoreLineEndingDifferences

### ISSUE THREAD

**Issue by philn5d** [xunit/xunit#1370]
When comparing two strings, would like to have the option to match the following:

- "foo \n bar" == "foo bar"
- "{foo:bar}" == " { foo: bar }"

I see tests which match "foo \n bar" == "foo \r bar" and "foo \t bar" == "foo bar", which are similar but not the same.

I realize that "foo bar" != "foobar" but that whitespace around certain characters is irrelevant depending on the format (e.g., xml, json). Perhaps there is another way besides changing the meaning of those parameters? An extension? Comparison rules parameter with some nice pre-build comparers for common formats?

**Comment by bradwilson** [comment]
No, we're not likely to add this. What you want is "ignoreWhiteSpace" as opposed to "ignoreWhiteSpaceDifferences", and frankly that has extremely limited value.

When evaluating strings which are structured data, is rarely a good idea for anybody other than the parser author to compare them as actual strings. You should just use a parser and compare the parsed results.

Alternatively, just copy the existing method and make a new one for your own use. https://github.com/xunit/assert.xunit/blob/ae98601b8ed4758a5c7880b087f08a8ec06e1c4c/StringAsserts.cs#L186

**Comment by philn5d** [comment]
Since I'm testing what is returned by an API call that returns JSON, I manually set up the expected value. Just to clarify completely, do you actually mean parsing or does that imply deserialization to an object?

Seems like adding any transformation could skew the results. Could you please elaborate or point to something that explains why it's rarely a good idea to compare as strings? Thanks.

**Comment by bradwilson** [comment]
If you've been given a string which contains JSON, then you should use a parser (like JSON.NET) to convert it into an object graph, and test the object graph. Comparing string against string is never the right answer: you want structural equivalence, not an exact string match.

**Comment by bradwilson** [comment]
One simple example. These two are structurally equivalent:
```json
{"a":1,"b":2}
```
```json
{
    "b" : 2 ,
    "a" : 1
}
```
No string comparison options will ever get you to a correct match.

**Comment by philn5d** [comment]
Of course, but one could remove all the padding and have a match...

But in the case where the string has extra data exposed for some erroneous reason:

{ "a":1,"b":2,"secret":"key"}

But the object Type we expected was:

{ int A, int B }

Sure it's an edge case, with dynamic it could be so - more so in a regression.

Deserialization would work and our data comparison would pass, but the actual result would be wrong.

An additional case is missing values v null but present properties - you may day they're logically equivalent, but when you say null vals won't be in the response (to keep data usage to a bare minimum)...you have to ensure the value is not present. Can't do that after deserialization.

I have two clear cases where it's better to remove the padding and compare results (much like how code compare tools don't skip semantically different but logically equivalent blocks). I can do this with some extension method or utility before validating - not as convenient but that's ok it'll give me an opportunity to put something in NuGet.

**Comment by bradwilson** [comment]
> Deserialization would work and our data comparison would pass, but the actual result would be wrong.

Only if you used a strongly typed object. If you use JSON.NET's JXxx classes, you can verify that the returned JObject only has two properties.

> An additional case is missing values v null but present properties - you may day they're logically equivalent,

Same answer.
