### ISSUE TITLE
Xamarin.Forms not supported in Visual Studio test runner

### ISSUE THREAD

**Issue by mattrichnz** [xunit/xunit#1371]
**Summary**
Visual Studio test runner previously supporting calling Xamarin.Forms.Forms.Init(e) to initialize the framework for tests which require it. With XF 2.3.4 and above, an `HRESULT E_FAIL has been returned from a call to a COM component` exception occurs when you attempt to initialize in the test runner.

**Repro Steps**
The exception is thrown if you call `Xamarin.Forms.Forms.Init(e)` in 'OnLaunched'. i.e..
```
protected override void OnLaunched(LaunchActivatedEventArgs e)
{
    Xamarin.Forms.Forms.Init(e);
    ...Initialize the test runner window etc.
}
```

**Comment by bradwilson** [comment]
Please re-open with a repro project.
