### ISSUE TITLE
Add analyzer to for Assert.True(collection.Contains("foo"))

### ISSUE THREAD

**Issue by marcind** [xunit/xunit#1374]
Something like `Assert.True(collection.Contains("foo"))` should be fixed up to `Assert.Contains("foo", collecton)`.

Same goes for `Assert.False` -> `Assert.DoesNotContain`. Also include overloads that take a custom comparer.

This should handle both `ICollection.Contains` implementations as well as `Enumerable.Contains` extensions method.

**Comment by bradwilson** [comment]
Just a reminder to be careful when offering to convert `.True` and `.False` that you do not recommend the conversion if they've provided a custom assertion message (since we regularly recommend people use True/False for this reason).

**Comment by marcind** [comment]
Closed in https://github.com/xunit/xunit.analyzers/pull/69
