### ISSUE TITLE
Could not load type 'Xunit.Sdk.LongLivedMarshalByRefObject' from assembly 'xunit.execution.desktop

### ISSUE THREAD

**Issue by osotorrio** [xunit/xunit#1375]
**Preconditions**

1. I am using Visual Studio Community 2015 Update 3.
2. NUnit 3 Test Adapter extension is installed in VS.
3. My projects, including the test project, target .net Framework 4.6.1

4. This is my packages.config file:

```xml  
  <package id="Shouldly" version="2.8.3" targetFramework="net461" />
  <package id="Xbehave" version="2.1.4" targetFramework="net461" />
  <package id="Xbehave.Core" version="2.1.4" targetFramework="net461" />
  <package id="xunit" version="2.2.0" targetFramework="net461" />
  <package id="xunit.abstractions" version="2.0.1" targetFramework="net461" />
  <package id="xunit.assert" version="2.2.0" targetFramework="net461" />
  <package id="xunit.core" version="2.2.0" targetFramework="net461" />
  <package id="xunit.extensibility.core" version="2.2.0" targetFramework="net461" />
  <package id="xunit.extensibility.execution" version="2.2.0" targetFramework="net461" />
  <package id="xunit.runner.console" version="2.2.0" targetFramework="net461" developmentDependency="true" />
  <package id="xunit.runner.visualstudio" version="2.2.0" targetFramework="net461" developmentDependency="true" />
```

**Steps**

1. First I delete the folder %Temp%/VisualStudioTestExplorerExtensions.
2. Second I open the solution in VS as administrator. 
3. I clean and rebuild the solution.
4. I open the Test Explorer window and it is empty with no tests. It seems to be "thinking" (green bar running).
5. After a few minutes, maybe 3, tests appear in Test Explorer.
6. When I run the tests, it takes again a few minutes to display an output.

Note: I have tried the same steps with the console runner with the same output. The tests also take too long to being discovered.

**This is the output:**

------ Run test started ------
[xUnit.net 00:01:10.5461519]   Starting:    ClassLibrary1
[xUnit.net 00:01:30.8716034]     ClassLibrary1.Class1.Addition [FAIL]
[xUnit.net 00:01:30.8752237]       System.TypeLoadException : Could not load type 'Xunit.Sdk.LongLivedMarshalByRefObject' from assembly 'xunit.execution.desktop, Version=2.2.0.3545, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'.
[xUnit.net 00:01:30.8783123]       Stack Trace:
[xUnit.net 00:01:30.8798234]            at Xbehave.Execution.ScenarioRunnerFactory.Create(Object[] scenarioMethodArguments)
[xUnit.net 00:01:30.8803149]         C:\projects\xbehave-net\src\Xbehave.2.Execution.desktop\ScenarioOutlineRunner.cs(81,0): at Xbehave.Execution.ScenarioOutlineRunner.<AfterTestCaseStartingAsync>d__8.MoveNext()
[xUnit.net 00:01:30.9215469]   Finished:    ClassLibrary1
========== Run test finished: 1 run (0:01:31.1344719) ==========

**Comment by bradwilson** [comment]
Since Xbehave is causing the load failure, you should probably start with them, not us.
