### ISSUE TITLE
Dispose flagged as public method needing Fact in derived type scenario

### ISSUE THREAD

**Issue by jasonmalinowski** [xunit/xunit#1379]
1. Create a new class library referencing xunit and xunit.analyzers 0.5.0.
2. Add:
```
using System;
using Xunit;

public class BaseClass : IDisposable
{
    public virtual void Dispose()
    {
    }
}

public class DerivedClass : BaseClass, IDisposable
{
    [Fact]
    public void Test()
    {
    }

    public override void Dispose()
    {
        base.Dispose();
    }
}
```
3. Compile.

*Expected:* no errors.
*Actual:* warning xUnit1013: Public method 'Dispose' on test class 'BaseClass' should be marked as a Fact.

There is a subtle behavior here: DerivedClass is also marked as implementing IDisposable. If you remove that (NB: it still does due to the base type) then it'll work fine.

**Comment by jamesqo** [comment]
@jasonmalinowski I'd like to fix this issue, but I can't repro what you have by going to .NET Core > xUnit Test Project (.NET Core), creating a project, and following the steps you've listed.

<img width="520" alt="no_errs" src="https://user-images.githubusercontent.com/9159214/28756430-1583b558-753c-11e7-8a64-7dd73e8decd4.PNG">

**Comment by jasonmalinowski** [comment]
@marcind Sorry for missing your question (it's been a long week...) Thanks for the fix!

**Comment by marcind** [comment]
@jasonmalinowski wasn't my question so no problem :)

btw, new version of the analyzers is out. I should probably start trying it out on the roslyn codebase myself, but let me know how it goes if you get a chance to upgrade.
