### ISSUE TITLE
can't create xunit project for .NET Core 2.0 Preview 2

### ISSUE THREAD

**Issue by aytacozkan** [xunit/xunit#1381]
We unable to create xunit projects targetted .NET Core 2.0 Preview 2 by using .net core cli. 

When will you release new version of xunit?

**Comment by bradwilson** [comment]
These instructions work fine with .NET Core 2.0 Preview 2:

https://xunit.github.io/docs/getting-started-dotnet-core.html

**Comment by aytacozkan** [comment]
hey Brad, thank you for your answer, I tried that blog post, and I got this error when I tried to run 'dotnet xunit'  -> 'Unsupported target framework '.NETStandard 2.0' (only .NETCoreApp 1.0+ and .NETFramework 4.5.2+ are supported),

**Comment by bradwilson** [comment]
Yes, we support `netcoreapp`, not `netstandard`. ;)

**Comment by aytacozkan** [comment]
:)) yeah..such a stupid thing that  I missed. I changed my TargetFramework to netcoreapp2.0 then it works, after creating project with "dotnet new ClassLib." I didn't take a look csproj file well.
thanks.
