### ISSUE TITLE
Add more overloads to ITestOutputHelper.

### ISSUE THREAD

**Issue by zwcloud** [xunit/xunit#1383]
I think at least it should be as powerful as `Console.Write` and `Console.WriteLine`.

	public static void Write(char[] buffer, int index, int count);
	public static void Write(char[] buffer);
	public static void Write(float value);
	public static void Write(bool value);
	public static void Write(decimal value);
	public static void Write(char value);
	public static void Write(double value);
	public static void Write(int value);
	public static void Write(long value);
	public static void Write(string value);
	public static void Write(string format, object arg0);
	public static void Write(string format, object arg0, object arg1);
	public static void Write(string format, object arg0, object arg1, object arg2);
	public static void Write(string format, params object[] arg);
	public static void Write(uint value);
	public static void Write(ulong value);
	public static void Write(object value);
	public static void WriteLine();
	public static void WriteLine(bool value);
	public static void WriteLine(char value);
	public static void WriteLine(char[] buffer);
	public static void WriteLine(ulong value);
	public static void WriteLine(double value);
	public static void WriteLine(int value);
	public static void WriteLine(long value);
	public static void WriteLine(object value);
	public static void WriteLine(float value);
	public static void WriteLine(string value);
	public static void WriteLine(string format, object arg0);
	public static void WriteLine(string format, object arg0, object arg1);
	public static void WriteLine(string format, object arg0, object arg1, object arg2);
	public static void WriteLine(string format, params object[] arg);
	public static void WriteLine(uint value);
	public static void WriteLine(decimal value);
	public static void WriteLine(char[] buffer, int index, int count);

**Comment by bradwilson** [comment]
We won't be doing any `Write` variants. The contract of ITestOutputHelper is for lines of text, not partial lines.

As for the rest, there's not much point in adding them to core. If you are bothered by their lack, add them as extension methods.
