### ISSUE TITLE
Analyzer to use Assert.Single instead of Assert.Equal(1, foo.Count/Length)

### ISSUE THREAD

**Issue by jamesqo** [xunit/xunit#1388]
The former is more readable and additionally provides a return value to tell you what the single item was.

**Comment by bradwilson** [comment]
A couple more that just occurred to me (they may or may not exist yet):

Convert Assert.Collection to Assert.Single when there is only one lambda.
Convert Assert.Collection to Assert.Empty when there are no lambda.

**Comment by jamesqo** [comment]
@bradwilson There is already an analyzer for the latter: https://github.com/xunit/xunit.analyzers/pull/55. Your first idea sounds good.

**Comment by ErikSchierboom** [comment]
@jamesqo I believe https://github.com/xunit/xunit.analyzers/pull/60 already does this. Also see the tests: https://github.com/xunit/xunit.analyzers/blob/master/test/xunit.analyzers.tests/AssertEqualShouldNotBeUsedForCollectionSizeCheckTests.cs

If it doesn't work, there is something wrong with that analyzer I think.

**Comment by jamesqo** [comment]
@ErikSchierboom I didn't see that analyzer before-- looks like this issue is mostly taken care of then. I'll keep this open for @bradwilson's idea however.

**Comment by jamesqo** [comment]
Nvm-- I opened a proper issue for @bradwilson's suggestion. #1399
