### ISSUE TITLE
Issue when running test case in .Net Core 2

### ISSUE THREAD

**Issue by d-saravanan** [xunit/xunit#1393]
Hi,
I am trying to run the test given in the aspnet/security repository with visual studio 2017 preview 3, the latest in visual studio, but the following error message is shown

[8/6/2017 11:29:46 AM Informational] ------ Load Playlist started ------
[8/6/2017 11:29:46 AM Informational] ========== Load Playlist finished (0:00:00.012) ==========
[8/6/2017 11:30:28 AM Informational] ------ Discover test started ------
[8/6/2017 11:31:30 AM Error] Testhost process exited with error: It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      \
  - Alternatively, install the framework version '2.0.0'.

Since this is from Microsoft github repository for ASP.Net Security, I have not added the same here. However, to try, please refer my repository [https://github.com/d-saravanan/Security]

**Comment by Rookian** [comment]
I have the same problem. I am using netcoreapp2.0 and use the `dotnet xunit` command.

My csproj:
```
...
  <PackageReference Include="xunit" Version="2.3.0-beta4-build3742" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-beta4-build3742" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta4-build3742" />
...
```

**Comment by bradwilson** [comment]
Please provide a repro project.

**Comment by Rookian** [comment]
It is working now with the new dotnet runtime/sdk. Imo you can close this issue.

**Comment by Saibamen** [comment]
@Rookian 
Which version works?

**Comment by bradwilson** [comment]
@Saibamen The 2.0 RTM runtime & SDK.
