### ISSUE TITLE
Tests not discovered in visual studio 15.3 preview when targeting net standard 2

### ISSUE THREAD

**Issue by clmcgrath** [xunit/xunit#1395]
When trying to run tests the test runner hangs and never starts tests 

Opening either the native test explorer and the resharper test runner explorer discover no tests 

when using the coderush explorer tests are discovered but never start when trying to run the tests 

Trying to run the tests via dotnet test throws an exception complaining that the Microsoft.Test.Sdk library needs to be installed,  tried this as well and still complains that it cannot be found

**Comment by bradwilson** [comment]
That's because the Visual Studio runner does not support `netstandard` unit test projects.

https://xunit.github.io/#runners

Please pick the target platform(s) and (multi-)target to them.

**Comment by vSzemkel** [comment]
Before upgrade my tests were discoverable and all functioning
After upgrading to VS2017.3 and migrating a project to netcore 2.0 I have permanent error:

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> JetBrains.ReSharper.UnitTestFramework.DotNetCore.Exceptions.ProcessExitedUnexpectedlyException: dotnet exited unexpectedly with the code (0)

This may well be a resharper problem..

**Comment by clmcgrath** [comment]
I am seeing the same right now after converting the target from netstandard to net47 using new project system

**Comment by clmcgrath** [comment]
See DigitalParadox.Utilities.AssemblyLoader for my setup

**Comment by bradwilson** [comment]
Resharper issues should be opened with Jetbrains. We do not write, nor support, their xUnit.net plugin.

**Comment by bradwilson** [comment]
Closed as external.
