### ISSUE TITLE
Cannot navigate to tests declared in abstract generic base class.

### ISSUE THREAD

**Issue by hubuk** [xunit/xunit#1401]
For the following tests:
```C#
public abstract class BaseUnitTests<T> {
  [Fact]
  public void Test1() { }
}
public class UnitTests : BaseUnitTests<string>{
  [Fact]
  public void Test2() { }
}
```
Test1 produces "Source: no source available" in Test Explorer.
![obraz](https://user-images.githubusercontent.com/11485931/29253328-af1291b0-8079-11e7-962f-f745a880fb7d.png)

Possible location of the problem:
https://github.com/xunit/xunit/blob/5133b76c1add95351bef471a6900de6155294370/src/xunit.runner.visualstudio/Sinks/VsDiscoverySink.cs#L87
Should be:
testClassName = xunitTestCase.TestMethod.Method.**DeclaringType**.Name;

Will try to prepare PR for this.

[NoSourceAvailable.zip](https://github.com/xunit/xunit/files/1220945/NoSourceAvailable.zip)

**Comment by onovotny** [comment]
This doesn't repro for me with the integration project:
![image](https://user-images.githubusercontent.com/1427284/29254909-19f7ab60-806a-11e7-82bc-2e2bd6e18731.png)

You can see a similar set up here:
https://github.com/xunit/xunit.integration/blob/4cbea845eea3958bf1aac5220aaf76c094e6c70f/test-explorer/v2x_net452/AbstractTestClass.cs#L6

**Comment by hubuk** [comment]
It seems that it stops working if any class in the hierarchy is generic.
```C#
using Xunit;
public abstract class Level0NonGenericTests {
    [Fact]
    public void NonGenericLevel0Test() {}
}
public abstract class Level0GenericTests<T> {
    [Fact]
    public void GenericLevel0Test() {}
}

public class Level1NonGenericTestsWitnNonGenericBase : Level0NonGenericTests {}
public class Level1GenericTestsWitnGenericBase<T> : Level0GenericTests<T> {}
public class Level1NonGenericTestsWitnGenericBase : Level0GenericTests<string> {}
public class Level1GenericTestsWitnNonGenericBase<T> : Level0NonGenericTests {}
public class Level2GenericTestsWitnNonGenericBase : Level1GenericTestsWitnNonGenericBase<string> {}
```
For the five classes above only `Level1NonGenericTestsWitnNonGenericBase` will get source available.
Reproduction repository: https://github.com/hubuk/xunit-issue-1401

**Comment by onovotny** [comment]
Just a guess here that the value being passed to `DiaSession` may not have the right escaping? Need to dig closer.

**Comment by onovotny** [comment]
Fixed in 2.3 beta 4, shipping today.

**Comment by hubuk** [comment]
@onovotny Great to hear! Thanks!

**Comment by hubuk** [comment]
@onovotny Can we reopen this issue?
It is better now, but source code for tests declared in a generic base class are not discovered in a specific scenarios:
When you modify the test cases in the [ConcreteTestClass.cs](https://github.com/xunit/xunit.integration/blob/b6c8c0a5a1167b864c5cde52fb2bddc14ae44752/test-explorer/v2x_net452_ReferencingProject/ConcreteTestClass.cs) to the code below the source code for ConcreteGenericTestClass is still not not being found.
```C#
public class ConcreteTestClass : AbstractTestClass { }
public class ConcreteOpenGenericTestClass<T> : GenericAbstractTestClass<T>{ }
public class ConcreteGenericTestClass : GenericAbstractTestClass<string> { }
```

I know that I cannot run tests for open generic types so this is not a real use case, but it shows some instability in the Test Explorer integration code. I am also getting the same problems with more complex type hierarchies without open generic test classes.

**Comment by onovotny** [comment]
The open generic shouldn't event have any tests that are discoverable in it...

For the more complex hierarchies, can you please provide an example?

**Comment by hubuk** [comment]
Strangely, after changing
`<PackageReference Include="xunit" Version="2.3.0-*" />`
to fixed version
`<PackageReference Include="xunit" Version="2.3.0-beta4-build3742" />`
things are OK.
