### ISSUE TITLE
[xunit.analyzers] Change casing for codefix titles displayed to the user

### ISSUE THREAD

**Issue by jamesqo** [xunit/xunit#1402]
I noticed that some of the codefix titles are cased a bit weirdly, e.g. [here](https://github.com/xunit/xunit.analyzers/blob/master/src/xunit.analyzers/AssertEqualLiteralValueShouldBeFirstFixer.cs#L16) or [here](https://github.com/xunit/xunit.analyzers/blob/master/src/xunit.analyzers/DataAttributeShouldBeUsedOnATheoryFixer.cs#L18). All other analyzers I've seen use regular casing for the message as if it were a sentence, so it seems a bit disconcerting to Capitalize Every Word of the message. Would it be OK to fix these messages? /cc @marcind

**Comment by marcind** [comment]
I tried to base the capitalization on existing analyzers I saw built into
VS when I first started working on this and/or what felt right to me at the
time. I'm not sure there's any official recommendation from MS about how to
format those messages. While the messages are end-user visible, I don't see
any evidence that the capitalization affects the UX and so this has a 0
priority for me right now.
