### ISSUE TITLE
Testing stops after 10 Debug.Assert()'s on Linux

### ISSUE THREAD

**Issue by LordMike** [xunit/xunit#1404]
Hello,

We have some code that I started adding unit tests for. Once I was happy, I sent it to our CI (running on Linux/Docker), which suddenly just stopped. Inspection showed that all output had halted.

Debugging the issue on Linux has lead me to the fact that `Debug.Assert()` calls on Linux through xUnit seems to stop/halt after 10 runs. I've attached a minimal sample.

On Windows 10, I can run the attached project without issues. I will as expected see 15 outputs, and an xUnit test completion banner. But on Linux, it stops after run no. 9, and just hangs. I've run the same code without xUnit, and can correctly see 15 runs of assertions (which also get logged to `stderr` for some reason, which they don't when run under xUnit).

About our code: We have a mockup of some Contract class which uses Debug.Assert() in it's failure condition. I hit this issue when I started unit testing a method that internally uses our Contracts mockup, which lead to this. In my test I'm testing a number of error conditions in a loop much like the one in the sample code.

The code:
```
using System;
using System.Diagnostics;
using Xunit;

namespace TestProject
{
    public class Tests
    {
        [Fact]
        public void B()
        {
            for (int i = 0; i < 15; i++)
            {
                Assert.ThrowsAny<Exception>(() => { Debug.Assert(false); });
                Console.WriteLine("Passed " + i);
            }
        }
    }
}
```

Output on Windows:
![image](https://user-images.githubusercontent.com/1027111/29276510-2342f094-810f-11e7-90fe-4279dcbb0ccd.png)

Output on Linux:
![image](https://user-images.githubusercontent.com/1027111/29276496-179a6e34-810f-11e7-8cd8-66556e65bb8a.png)

Attached project:
[TestProject.zip](https://github.com/xunit/xunit/files/1222510/TestProject.zip)

Verification code (to narrow it to xUnit):
```
        public static void Main()
        {
            for (int i = 0; i < 15; i++)
            {
                try
                {
                    Debug.Assert(false);
                }
                catch (Exception)
                {
                }

                Console.WriteLine();
                Console.WriteLine("Passed " + i);
            }
        }
```

**Comment by LordMike** [comment]
Bump. Is more information required?

**Comment by bradwilson** [comment]
I'm not able to repro this on Ubuntu 16.04:

![Repro](https://user-images.githubusercontent.com/16944/29627087-c0b78664-87e5-11e7-93be-80459cf2a8a4.png)

I tried on both WSL as well as an Ubuntu Server 16.04 VM.

**Comment by LordMike** [comment]
I couldn't run it in WSL as the guide I found was for .NET Core 2.0, while this project targets 1.1 (and it's late - might look at it tomorrow).

I was able to still reproduce on another Linux, this time a docker image running `microsoft/dotnet:1.1-sdk`. The behaviour was the same as I saw before: it stops at "Passed 9".

The commands run are:

    docker run -it --rm -v /root/a:/a -w /a microsoft/dotnet:1.1-sdk bash
    uname -a
    ls
    dotnet restore
    dotnet test

`/root/a` contains the test project from the original post. The docker image run had hash `sha256:232beb698194c85913ac0ecde327c41bc1158c334c2d8019e6edb24f2ebf4640`

![image](https://user-images.githubusercontent.com/1027111/29641272-1ca320e6-8863-11e7-9434-897230868cdb.png)

**Comment by bradwilson** [comment]
When I use `dotnet xunit` instead of `dotnet test`, I get a much more interesting result. First, everything runs to completion. Second, there appears to be a failure to get the stack trace from the test on the part of .NET Core when you're calling `Debug.Assert`:

```
[...]
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at System.Diagnostics.Debug.Assert(Boolean condition)
   at TestProject.Tests.<>c.<B>b__0_0() in /a/Tests.cs:line 14
   at Xunit.Assert.RecordException(Action testCode)
[...]
```

I am doubtful that this issue belongs to xUnit.net, since:

* `dotnet xunit` runs to completion
* this stack trace indicates the issue is in Debug.Assert
* everything works as expected when using the .NET Core 2.0 SDK

I believe that you should probably open this issue with the .NET Core team and see if they can track down where the problem lies, and let them determine whether this is something worth revving LTS to fix.

Good luck...

**Comment by bradwilson** [comment]
Another verification that this appears to be a bug with `Debug.Assert`: if you instead just throw an exception, everything works as expected with both `dotnet test` as well as `dotnet xunit`.

**Comment by LordMike** [comment]
We have adopted `dotnet xunit` as our test runner - I wouldn't know where to start in reporting this. If netcore20 fixes it - then that's cool :).
