### ISSUE TITLE
'dotnet test' vs. 'dotnet xunit'

### ISSUE THREAD

**Issue by bgribaudo** [xunit/xunit#1407]
Hello,

What are the pros and cons of running xUnit tests using `dotnet test` vs. using `dotnet xunit`? 

`dotnet xunit` offers more command-line options than `dotnet test`, but when those extra options aren't needed, is there a particular advantage to using one over the other or is the choice just personal preference? :-)

Thank you,
Ben

**Comment by rhyswat** [comment]
@bgribaudo a differentiator for me is that `dotnet xunit` can generate XML output for display in CI jobs.

**Comment by yangshengf** [comment]
The difference in the backend is rather large. With `dotnet xunit` it is a custom command meaning the handler gets all the commandline arguments, similar to `xunit.console.exe`. However, `dotnet test` passes through an msbuild wrapper similar to msbuild and visualstudio runner. It provides a common pattern regardless of test framework you use. Hence the extra commandline options are not available. The discussion is on dotnet/cli#3114

If you don't need the extra options it is up to you.

**Comment by stakx** [comment]
One advantage of `dotnet test` over `dotnet xunit` is that the former can be run at the solution level, and it'll run unit tests for all test projects it finds. `dotnet xunit`, it seems, only works correctly if run from inside a specific test project directory.

(Perhaps I am missing something here, and `dotnet xunit` can also run tests for several projects. If so, please correct me.)

**Comment by rhyswat** [comment]
@stakx that may be true of dotnet 2.0 and if so it’s a Good Thing.
It isn’t true of dotnet 1.1 unfortunately so you have to cd my-tests or tell it which test csproj file to use.

**Comment by stakx** [comment]
@rhyswat:

> you have to cd my-tests or tell it which test csproj file to use.

Unfortunately, this remains the same for `dotnet` 2.0.2 and xUnit 2.3.0.

**Comment by bradwilson** [comment]
> I never figured out how to specify a project file it should use, only cd works, really.

That's because what you want is not currently supported by the .NET SDK.

**Comment by vludax** [comment]
@stakx:
> One advantage of dotnet test over dotnet xunit is that the former can be run at the solution level, and it'll run unit tests for all test projects it finds.
Although when `dotnet test` is run at the solution level, it attempts to run non-test projects, and complains that they are missing `Microsoft.NET.Test.Sdk`.

**Comment by VictorioBerra** [comment]
I am currently struggling with this same thing. There are powershell/linux tricks that can automate finding projects and running tests but it is not as easy as it should be.

**Comment by FrederikNygaardSvendsen** [comment]
@vludax  @VictorioBerra I had the same problem, i solved it by executing test by running a shell file like this:

```
#!/bin/bash
ls *Tests*/*.csproj | xargs -L1 dotnet test
```

This will run the dotnet test command for all .csproj files within a folder that matches on ./*Tests*/*.csproj. So this is run from the solution folder

**Comment by VictorioBerra** [comment]
I was able to solve my issue by making sure I was specifying netcoreapp2.0 in the xunit folder
