### ISSUE TITLE
[xunit.analyzers] Add tests for code fix providers

### ISSUE THREAD

**Issue by jamesqo** [xunit/xunit#1410]
[Here](https://github.com/dotnet/roslyn-analyzers/blob/569bd373a4831d3035597197e02980b57602a7f2/src/MetaCompilation.Analyzers/UnitTests/Verifiers/CodeFixVerifier.cs#L46) is how the roslyn-analyzers repo tests their code fix providers. @marcind you said earlier you couldn't find any practical examples of how to test them, but the code there seems practical enough.

**Comment by marcind** [comment]
Duplicate of #1264
