### ISSUE TITLE
Can't run netcoreapp1.x tests when .NET Core 2 is installed

### ISSUE THREAD

**Issue by Jericho** [xunit/xunit#1412]
I recently installed Visual Studio the latest update for Visual Studio (15.3.0) and also installed dotnet core 2.0. I am now getting `Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)` when executing `dotnet xunit`.

I am not experiencing any problem when running my unit tests from Visual Studio or when running `dotnet test`. Also, I experience this problem only when my unit tests project references `netcoreapp1.0`. I see no such error if I change the `TargetFramework` to `net452`.

My unit tests `.csproj` contains:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
    <PackageReference Include="Moq" Version="4.7.99" />
    <PackageReference Include="RichardSzalay.MockHttp" Version="1.5.0" />
    <PackageReference Include="Shouldly" Version="2.8.3" />
    <PackageReference Include="xunit" Version="2.3.0-beta4-build3742" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-beta4-build3742" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta4-build3742" />
  </ItemGroup>
```
and `dotnet --info` yields the following information:
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```
Finally, here's the console output when running `dotnet xunit`:
```
Detecting target frameworks in CakeMail.RestClient.UnitTests.csproj...
Building for framework netcoreapp1.0...
C:\Program Files\dotnet\sdk\2.0.0\Microsoft.CSharp.CurrentVersion.targets(134,9): warning MSB3884: Could not find rule set file "\CakeMail.RestClient.ruleset". [E:\_build\CakeMail.RestClient\Source\CakeMail.RestClient\CakeMail.RestClient.csproj]
  CakeMail.RestClient -> E:\_build\CakeMail.RestClient\Source\CakeMail.RestClient\bin\Debug\netstandard1.3\CakeMail.RestClient.dll
  CakeMail.RestClient.UnitTests -> E:\_build\CakeMail.RestClient\Source\CakeMail.RestClient.UnitTests\bin\Debug\netcoreapp1.0\CakeMail.RestClient.UnitTests.dll
Running .NET Core tests for framework netcoreapp1.0...

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

I found [a comment](https://github.com/xunit/xunit/issues/1365#issuecomment-318518983) by @bradwilson which seems to describe the exact same error. He says the problem has been fixed in 2.3 beta 4 but, as you can see in my .csproj, I am already referencing that version.

Is there something else I need to do to resolve this problem?

**Comment by NickCraver** [comment]
I'm hitting this trying to move to beta4 as well, in Dapper `netcoreapp1.0` blows up with the same error (we multi-target tests to `net452`, `netcoreapp1.0` and `netcoreapp2.0`). Reverting to beta3 resolves the issue.

I'll try and figure out what reference path is causing this, it's not apparent to me from glancing at the tree.

**Comment by janpieterz** [comment]
Hitting it here with classic .net (462) tests that tests asp.net core on 462 and .NET Standard 1.5 libraries.

Beta3 did not solve this problem. Only thing that changed is updating Visual Studio and installing .NET Core 2.0 SDK.

**Comment by bradwilson** [comment]
I can repro this with both 1.x and 2.x installed (everything works as expected when only one is installed), because the system is choosing to use the netcoreapp2.0 runner even when the unit tests are targeting netcoreapp1.x. So netcoreapp2.0 should work.

I should have a fix for this on the CI server soon.

**Comment by bradwilson** [comment]
Fixed by https://github.com/xunit/xunit/commit/13a1eb24c05c90d6d1c1e5633627347f8de09504

Available in `2.3.0-beta5-build3745`. Verified on Windows 10 and Ubuntu 16.04.

**Comment by Jericho** [comment]
@bradwilson I updated my references to `2.3.0-beta5-build3746` and I confirm that the problem is gone. Thank you for the super fast resolution!

**Comment by chanaka1** [comment]
how can i get the 2.3.0-beta5-build3746 ?

**Comment by bradwilson** [comment]
@chanaka1 We just shipped beta 5 (build 3769) to NuGet about an hour ago.

For future reference, CI builds are available via MyGet: https://myget.org/gallery/xunit
