### ISSUE TITLE
Handle IReadOnlyCollection<T>.Count in xUnit2013

### ISSUE THREAD

**Issue by jamesqo** [xunit/xunit#1414]
Spotted this in the Roslyn unit tests: https://github.com/dotnet/roslyn/pull/21335/files#diff-ebd4143e3b5ba1ccd2e25e728d9784bcR1867. It's calling `Assert.Equal(0, list.Count)` where `list` is a `SyntaxList<TNode>`. `SyntaxList<TNode>` only implements `IReadOnlyList<TNode>`, so xUnit2013 isn't firing.

/cc @ErikSchierboom

**Comment by ErikSchierboom** [comment]
@jamesqo I can fix this next monday. Good catch!

**Comment by jamesqo** [comment]
@ErikSchierboom No worries. I'm actually working on a different issue that involves this analyzer right now (#1408), so I can fix both issues in one go.

**Comment by ErikSchierboom** [comment]
@jamesqo Okay, cool! Good luck with it :)
