### ISSUE TITLE
Issue diagnostic when test method return type is not void or Task

### ISSUE THREAD

**Issue by jamesqo** [xunit/xunit#1415]
For example, the following code should raise a diagnostic with the squiggly line under `int`:

```cs
[Fact] public int Test() { return 0; }
```

Also, in the case of `Task`, the return type must be exactly `Task` and not a derived type. This should also raise a diagnostic:

```cs
[Fact] public async Task<int> TestAsync() { return 0; }
```

@marcind Do you think this should be a warning or an error?

**Comment by marcind** [comment]
The rule I've been following is: If something is guaranteed to produce a runtime error in xUnit then it should be flagged as an error. Almost everything else so far has been a warning, although I'm beginning to reconsider this decision given the potential number of warnings you might see when adding the analyzers to a project for the first time.
