### ISSUE TITLE
Tests discovery stops after add a AspNetCore 2 project reference

### ISSUE THREAD

**Issue by wesleyteixeira** [xunit/xunit#1416]
When i add a webapi reference in a xUnit project the discovery of tests stops showing me this message:
Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

If i run the command to remove the reference the discovery of tests works again.

Steps:
- download https://github.com/wesleyteixeira/xUnitWebApiTest
- cd xUnitWebApiTest/PrimeService.Tests
- dotnet test (the discovery works ok)
- dotnet add reference ../Web/Web.csproj
- dotnet test (the discovery stops)

**Comment by bradwilson** [comment]
I'm not able to repro:

![Repro](https://user-images.githubusercontent.com/16944/29499845-9681f5fa-85ce-11e7-819a-126f7c044817.png)

**Comment by wesleyteixeira** [comment]
Seems to be something in my environment. I've removed all versions of the .net core runtime/sdk and reinstalled only version 2 but the problem continues to occur..

**Comment by merovin2** [comment]
i have the same problem. Is there any solution for it?

**Comment by merovin2** [comment]
For me, if the second project get added references "Microsoft.AspNetCore.MVC" (2.0.0), then the test project stops discovery test cases. 

if Microsoft.AspNetCore.MVC get removed, then the test project works again.

**Comment by bradwilson** [comment]
@merovin2 Please open a new issue with a repro, because I can't repro your described situation.

![image](https://user-images.githubusercontent.com/16944/31919756-6bae67c8-b819-11e7-8d3e-18dce74a6669.png)
