### ISSUE TITLE
Improved syntax for asserting collection counts

### ISSUE THREAD

**Issue by rhyswat** [xunit/xunit#1417]
`Assert.Equal(1000, myList.Count)` yields a warning.

But the solution of using `Assert.Collection(myList, /* one thousand Action objects */)` could do with some sugar, say `Assert.CollectionCount<T>(int expected, IEnumerable<T> collection)`

Happy to propose a PR if this is thought to be useful.

**Comment by bradwilson** [comment]
I don't believe this adds any particular value.
