### ISSUE TITLE
[xunit.analyzers] Codefix to use Assert.Contains/DoesNotContain is technically incorrect

### ISSUE THREAD

**Issue by jamesqo** [xunit/xunit#1418]
A [recent PR](https://github.com/xunit/xunit.analyzers/pull/69) by @ErikSchierboom offered a codefix to change

```cs
Assert.True(collection.Contains(item));
```

to

```cs
Assert.Contains(item, collection);
```

This works fine for most collection types like arrays or `List<T>`. However, for types that have a custom comparer such as `HashSet<T>` or `Dictionary<K, V>`, this could potentially be changing semantics. For example:

```cs
var set = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
{
    "FOO"
};

Assert.True(set.Contains("foo")); // passes
Assert.Contains("foo", set); // fails
```

This is because `Assert.Contains` does not bother checking for a custom ICollection impl and calling into its `Contains`: https://github.com/xunit/assert.xunit/blob/master/CollectionAsserts.cs#L98

IMO, the best fix would be to change the `Contains` impl to check for ICollections, so the codefix is always correct. Alternatively, if people are opposed to that idea for whatever reason (backwards compatibility maybe?) then we can blacklist certain types like `HashSet<T>`, `Dictionary<K, V>` and prevent the analyzer from firing on them.

/cc @bradwilson @ErikSchierboom @marcind

**Comment by bradwilson** [comment]
Please open a bug against `Assert.Contains`. Thanks!

**Comment by jamesqo** [comment]
@bradwilson Sure, I'll also open a PR right now to fix it.
