### ISSUE TITLE
Add documentation for prequisites to build the repo

### ISSUE THREAD

**Issue by jamesqo** [xunit/xunit#1421]
It would be nice if there was better documentation on how to build the repo, for example, in a `building.md` file at the root. In particular, it looks like you have to have both of the following installed or you'll get an error during `./build.ps1`:

- .NET Core 2.0 SDK
- UWP tooling

The last bullet point appears to be coming from [this dependency](https://github.com/xunit/xunit/blob/b817a2e187ec85f22ff792e438255b80cbc66784/src/xunit.runner.visualstudio/xunit.runner.visualstudio.csproj#L21), because I got this error when building xunit.runner.visualstudio:

```
C:\Users\james\.nuget\packages\msbuild.sdk.extras\1.0.6\build\netstandard1.0\MSBuildSdkExtras.Common.targets(123,5):
error : The specified language targets for uap10.0 is missing. Ensure correct tooling is installed.
Missing File: C:\Program Files\dotnet\sdk\2.0.0\\Microsoft\WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.CSharp.targets [C:\cygwin64\home\james\Code\git\xunit\src\xunit.runner.visualstudio\xunit.runner.visualstudio.csproj]
```

@onovotny, I know you maintain https://github.com/onovotny/MSBuildSdkExtras. Does the user really have to install UWP tooling if they reference your project?

**Comment by bradwilson** [comment]
This exists: https://xunit.github.io/docs/building-xunit.html

Do you think we should add a `BUILDING.md` file that just points to this URL? Is `BUILDING.md` the common practice for Github projects?

**Comment by bradwilson** [comment]
The Visual Studio runner directly references UWP, which is why it's a pre-requisite.

**Comment by jamesqo** [comment]
> Do you think we should add a BUILDING.md file that just points to this URL?

Definitely, the contents of the repo is the first place people look when they want to know how to build.

> Is BUILDING.md the common practice for Github projects?

Seems like it:

https://github.com/search?l=Markdown&q=filename%3ABUILDING.md&type=Code&utf8=%E2%9C%93

**Comment by bradwilson** [comment]
It's already done. :) Thanks!

**Comment by talweiss1982** [comment]
Would be nice to know which components are needed from each workload
