### ISSUE TITLE
Can't remove xunit.analyzer from project in VS 2017 15.3

### ISSUE THREAD

**Issue by Tornhoof** [xunit/xunit#1422]
Not sure if this is a XUnit.analyzer bug or VS bug. Please close if it's the wrong repo and I'll try my luck with VS.

Steps to reproduce:
1. Create class library project (.NET framework 4.7 in my case)
2. Add XUnit Beta 2.3.0-beta4-build3742 nuget packages
3. Go to References-Analyzers, right-click Xunit.analyzer and select Remove.

Expected result:
- Analyzer is removed
Actual result
- HRESULT E_FAIL

Screenshot:
![xunitanalyzer](https://user-images.githubusercontent.com/7989549/29554714-7b9e173e-8720-11e7-918b-1afdf55fd275.png)

Repro
[AnalyzerRemove.zip](https://github.com/xunit/xunit/files/1241219/AnalyzerRemove.zip)

Note: I tried to remove it because of  the Xunit.Analyzers.AssertCollectionContainsShouldNotUseBoolCheck exception not yet fixed on nuget.

**Comment by bradwilson** [comment]
This looks like a bug in Visual Studio.

That said, if you don't want the analyzers, then you should replace your use of the `xunit` package with the `xunit.core` and `xunit.assert` packages. The `xunit` package is just a "meta-package" that just brings in other packages:

![NuGet Gallery](https://user-images.githubusercontent.com/16944/29584223-eef8febc-8737-11e7-8fb5-43d4641bef77.png)

We have separated `xunit.core` (the package used by write unit tests), `xunit.assert` (the xUnit.net Assert class), and `xunit.analyzers` (the code analysis) precisely for this reason: most people will want them all by default, but if you don't, you can pick and choose what's right for you.

**Comment by bradwilson** [comment]
Also, if you do want the analyzers but just want that bug fixed, see if upgrading to 0.6.1 fixes your issue for you. 😃

**Comment by Tornhoof** [comment]
Thanks for the advise. I'll close this bug and refile it with Visual Studio.
