### ISSUE TITLE
Assert.Contains does not honor collection's Contains semantics

### ISSUE THREAD

**Issue by jdom** [xunit/xunit#1425]
I have a collection that implements the Contains method and does not use the default equality comparison (in my case it's a HashSet with a case insensitive comparer for strings).

If I have the following test assertions:
```
        [Fact]
        public void CantUseAssertContains()
        {
            var caseInsensitiveCollection = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            caseInsensitiveCollection.Add("one");

            Assert.True(caseInsensitiveCollection.Contains("ONE"));
            Assert.Contains("ONE", caseInsensitiveCollection);
        }
```

Notice the 2 asserts. The last assert, using `Assert.Contains` just takes an enumerable and uses the default equality comparer (I pressume), so it is failing, saying the "ONE" cannot be found.

Nevertheless, in the latest version of xUnit that comes with the analyzers, if I use the first assertion, I get a warning with a suggestion to fix it by switching to `Assert.Contains`, which is not behaviorally equivalent.

So either 1 of these 2 things is incorrect for this scenario. We could change the behavior of `Assert.Contains` so that it uses the collection's `Contains` method if it can be casted to an `ICollection`, or relax/drop the analyzer warning.

**Comment by bradwilson** [comment]
This was fixed in xunit/assert.xunit#20, and will be part of 2.3 beta 5.
