### ISSUE TITLE
Possible redondant call of VsDiscoverySink.CreateVsTestCase in VsTestRunner

### ISSUE THREAD

**Issue by vjacquet** [xunit/xunit#1428]
Aren't the 2 calls to CreateVsTestCase doing the same thing in the constructor of DiscoveredTestCase, the second call overwriting the first one result?

https://github.com/xunit/xunit/blob/850a5578c83b19451e3d53369f2c5b59086f00a4/src/xunit.runner.visualstudio/VsTestRunner.cs#L756-L762

**Comment by bradwilson** [comment]
You are correct.
