### ISSUE TITLE
Assert.{Not}Equal(..., EqualityComparer<T>.Default) => Assert.{Not}StrictEqual(...)

### ISSUE THREAD

**Issue by jamesqo** [xunit/xunit#1437]
Basically as the title says. One thing to be careful about is if the `T` inferred in the original code is different than if the comparer parameter had been omitted, e.g. `Equal("", "", EqualityComparer<object>.Default)`. I haven't thought about whether `EqualityComparer` of a base type might produce different behavior than `EqualityComparer` of the most specific type, but if that's the case then the analyzer should not fire for such scenarios.

**Comment by marcind** [comment]
Is there any behavioral difference between the two call patterns? (e.g. a more meaningful error message when a test fails). If not, I'm not sure it's worth the implementation effort.

**Comment by bradwilson** [comment]
I honestly haven't seen this come up other than this one request, so I'm closing this as "not worth the effort".
