### ISSUE TITLE
Does xUnit allow to overide parameters for particular run?

### ISSUE THREAD

**Issue by xperiandri** [xunit/xunit#1439]
Is it possible to override parameters and pass them to xUnit runner on VSTS Build like described here for MS Test?
https://blogs.msdn.microsoft.com/devops/2015/09/04/supplying-run-time-parameters-to-tests/

**Comment by onovotny** [comment]
You can do this by setting / reading environment variables, would that work for you?

**Comment by xperiandri** [comment]
@onovotny, could you show me a screenshot with build task and settings of how to do this?
All the thing I tried do not work.

**Comment by xperiandri** [comment]
In my test I do this:

Constructor
``` C#
IConfigurationRoot configuration = new ConfigurationBuilder()
    .AddUserSecrets<Startup>()
    .AddEnvironmentVariables()
    .Build();
var service = new ServiceCollection();
service.AddOptions();
service.Configure<MongoDbSettings>(configuration.GetSection("MongoDbAzure"))
```

Where 
``` C#
public class MongoDbSettings
{
    public string ConnectionString { get; set; } = "mongodb://localhost:27017";
}
```

And build variable in VSTS is set as `MongoDbAzure:ConnectionString`
But its value is not picked up.

@onovotny, @bradwilson, @davidfowl is there something wrong I do?

**Comment by xperiandri** [comment]
![image](https://user-images.githubusercontent.com/2365592/30007705-9cddc0d2-911d-11e7-8078-a17b5a0344de.png)

Not picked up

**Comment by davidfowl** [comment]
Is there a more first class way to set environment variables on VSTS?

**Comment by alexlazarciuc** [comment]
Hey guys,

I'm facing same similar issue. Basically trying to read from xunit console a param to decide on which environment to run my test. I know Nunit support that via TestContext.Parameters[paramName] - but not sure how this can be done in xUnit. Any thoughts? 

Thanks a mil.

**Comment by bradwilson** [comment]
@alexlazarciuc As mentioned above, there is no officially supported way to do this, but the convention is to use environment variables.

**Comment by xperiandri** [comment]
It is impossible on VSTS build hence forces to use alternative frameworks

**Comment by bradwilson** [comment]
We have no intention of adding this as a feature at this time.

**Comment by alexlazarciuc** [comment]
@bradwilson  - thanks for the reply! Much appreciated

**Comment by skalinets** [comment]
@davidfowl  @xperiandri  I don't think [this step](https://github.com/xunit/xunit/issues/1439#issuecomment-326840976) is needed. All build variables are available as environment variables when build runs.

**Comment by rarunkumar454** [comment]
Hi guys, I'm using xUnit Testing in my project, In that my input was diiferent from normal xUnit input. 
I want to test 
var bbCarResponse = await _bbDataService.GetMktListingAsync(request); 
this method.
Basically my inputs from a class file.
       public class Request : ServiceRequest
        {
            public string Name { get; set; }
            public string Model { get; set; }
            public string Zipcode { get; set; }
        }
So the request is "Request request".
How shall i test in xUnit please let me know.
Thanks.
