### ISSUE TITLE
mix of async Task methods and void methods in a test class not working well in server 2012 and 2016?

### ISSUE THREAD

**Issue by zijianhuang** [xunit/xunit#1444]
The test dll is built on .NET 4.6.2 and xUnit 2.2.

I had mix of async Task methods and void methods in a test class.

On Windows 10 and 7, in VS 2017 Test Explorer and xunit.console.exe, all test cases run well.

On Windows server 2012 and 2016, tests stop at the first void method which uses MyFunctionAsync.Result.

After I changed the rest methods to async Task method like 

```C#
        [Fact]
        public async Task TestCreateInvoice()
```

All test cases work fine in 2012 and 2016.

I am not sure if this is a bug of xUnit.console.exe, or there's a recommendation that all methods should be async only or void only?

**Comment by onovotny** [comment]
The issue is that `Task.Result` will deadlock and it should not be used...this is xunit finding deadlocks in your code :)

**Comment by zijianhuang** [comment]
However, such "unit finding deadlocks" happened only in server 2012 and 2016, not Windows 10 and 7. 

And in Web API controller, I have also mix of async methods and normal methods, no problem in all environments.

**Comment by bradwilson** [comment]
Please re-open with a repro project.
