### ISSUE TITLE
How to correctly setup TeamServer build to run .NET Core project with XUnit

### ISSUE THREAD

**Issue by comdiv** [xunit/xunit#1445]
I have following project
```
proj.sln
some.lib.test 
	some.lib.test.csproj
```
where 
some.lib.test.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>    
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="xunit" Version="2.3.0-beta5-build3769" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta5-build3769" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>

</Project>

```
How to setup Team Services build to get tests normally viewed?

I try to search web but don't get valid result.

**Comment by comdiv** [comment]
In logs:

c:\bin\vs\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe C:\agent\_work\1\s\iskkonekb.kuvera.model.test\bin\release\netcoreapp1.1\iskkonekb.kuvera.model.test.dll C:\agent\_work\1\s\iskkonekb.kuvera.model.test\bin\release\netcoreapp2.0\iskkonekb.kuvera.model.test.dll C:\agent\_work\1\s\iskkonekb.kuvera.model.test\result.xml\iskkonekb.kuvera.model.test.dll /EnableCodeCoverage /logger:trx "/TestAdapterPath:\"C:\agent\_work\1\s\packages\"" /InIsolation /UseVsixExtensions:true /Framework:FrameworkCore10


[xUnit.net 00:00:00.1787131] Skipping: iskkonekb.kuvera.model.test (Could not find any of the following assemblies: xunit.execution.desktop.dll)

I cannot find xunit.execution.desktop in NUgets

**Comment by bradwilson** [comment]
We do not officially support Team Services.
