### ISSUE TITLE
dotnet xunit error: "An assembly ... was not found"

### ISSUE THREAD

**Issue by bgrainger** [xunit/xunit#1451]
Adding a reference to `Dapper` to a `netcoreapp2.0` Xunit test project causes `dotnet xunit` to fail with the message `An assembly specified in the application dependencies manifest (MyFirstUnitTests.deps.json) was not found: package: 'System.Data.SqlClient', version: '4.1.0'`.

Windows 10 x64, dotnet --version 2.0.0

## Sample Project

https://github.com/bgrainger/DotnetXunitAssemblyWasNotFound

`git clone https://github.com/bgrainger/DotnetXunitAssemblyWasNotFound.git`

## Reproduction Steps

Follow the steps at https://xunit.github.io/docs/getting-started-dotnet-core to create a new project:

```
mkdir MyFirstUnitTests
cd MyFirstUnitTests
dotnet new classlib

# edit project file to change TargetFramework and add xunit references
```

Add a reference to Dapper (1.50.2):

```
dotnet add package Dapper
dotnet restore
```

Run `dotnet xunit`. It produces the following error message:

```
Detecting target frameworks in MyFirstUnitTests.csproj...                                                               
Building for framework netcoreapp2.0...                                                                                 
  MyFirstUnitTests -> F:\Code\Projects\MyFirstUnitTests\bin\Debug\netcoreapp2.0\MyFirstUnitTests.dll                    
Running .NET Core tests for framework netcoreapp2.0...                                                                  
Error:                                                                                                                  
  An assembly specified in the application dependencies manifest (MyFirstUnitTests.deps.json) was not found:            
    package: 'System.Data.SqlClient', version: '4.1.0'                                                                  
    path: 'runtimes/win/lib/netstandard1.3/System.Data.SqlClient.dll'                                                   
```

I get the same behaviour with both `2.3.0-beta4-build3742` and `2.3.0-beta5-build3769`.

Note that `<TargetFramework>net46</TargetFramework>` (or `net47`) succeeds, but `netcoreapp1.1` and `netcoreapp2.0` fail.

**Comment by bgrainger** [comment]
Possibly a duplicate of #1450.

If I `dotnet add package Microsoft.NET.Test.Sdk` as suggested in that case, then the `netcoreapp2.0` tests succeed, but `netcoreapp1.1`  fails with `Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)` and then dotnet.exe crashes (which indicates to me that this new error might be a .NET Core bug, not an Xunit problem).

**Comment by bradwilson** [comment]
This should now be fixed in RC 1.

**Comment by sergius1che** [comment]
## Hello! ##

**I have example project:**
``` xml
<PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Dapper" Version="1.50.2" />
    <PackageReference Include="xunit" Version="2.3.0-rc1-build3809" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-rc1-build3809" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-rc1-build3809" />
  </ItemGroup>
```
**And test:**

```C#
using System;
using System.Data.SqlClient;
using Xunit;
using System.Linq;
using Dapper;

[Fact]
public void Test1()
{
    string str;
    using (SqlConnection dbConnection = new SqlConnection("Data Source=localhost\\SQLSERVER;Initial Catalog=ris;User ID=sa;Password=MSSQLadmin@1;Connect Timeout=600;"))
    {
        dbConnection.Open();
        str = dbConnection.Query<string>("SELECT @@VERSION", commandTimeout: 600).Single();
    }
}
```

**When I run the test - I get an error:**
```
xunitVsDapper.Class1.Test1 [FAIL]
      System.TypeInitializationException : The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.
      ---- System.IO.FileNotFoundException : Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Не удается найти указанный файл.
```

**If I include `Dapper` at external lib, I get next exception:**
```
xunitVsDapper.Class1.Test1 [FAIL]
      System.IO.FileNotFoundException : Could not load file or assembly 'System.Data.SqlClient, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Не удается найти указанный файл.
```

How do I run tests from the console?
