### ISSUE TITLE
AppVeyorReporter - Configuration prefix / suffix for FileName

### ISSUE THREAD

**Issue by snakefoot** [xunit/xunit#1453]
I'm running the same UnitTest.dll multiple times with different configurations. AppVeyor is not picking up the test results from the different test-runs.

The problem is most likely caused by AppVeyorReporterMessageHandler. It makes a unique AppVeyor-unittest-fileName based on:

- AssemblyName
- TargetFramework

The DLL being tested is using strong-name, so renaming the DLL to match each test-configuration and adding InternalsVisibleTo to the strong-DLL is not easy.

Performing an artificial change of the TargetFramework (net452, net46, net461, net462, net47) puts a limit on how many configuration one can test.

It could nice that the AppVeyorReporterMessageHandler allowed one to add a prefix/suffix to the unittest-filename published to AppVeyor (coming from a command-line parameter, or environment variable):

`AssemblyName + TargetFramework + ConfigurationNameSuffix`

**Comment by bradwilson** [comment]
Dup of/related to #1372
