### ISSUE TITLE
"parallelizeTestCollections": false in xunit.runner.json don't work

### ISSUE THREAD

**Issue by FabioMenta** [xunit/xunit#1455]
I have this issue in a project net core 2 with this refenrence:

Microsoft.NET.Test.Sdk 15.3.0
xuni 2.3.0-beta5-build3769
dotnet-xunit 2.3.0-beta5-build3769
xunit.runner.visualstudio 2.3.0-beta5-build3769

xunit.runner.json:
{
  "parallelizeTestCollections": false
}

and code:
`    public class Class1
    {
        [Fact]
        public void Test1()
        {
            Thread.Sleep(5000);
            Assert.True(true);
        }
    }`

    
`    public class Class2
    {
        [Fact]
        public void Test2()
        {
            Thread.Sleep(5000);
            Assert.True(true);
        }
    }`

**Comment by bradwilson** [comment]
I am unable to reproduce this:

![Test results](https://user-images.githubusercontent.com/16944/30504240-6eedbeee-9a22-11e7-8cfd-b521d0fa5e37.png)

This is my .csproj file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
    <PackageReference Include="xunit" Version="2.3.0-beta5-build3769" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-beta5-build3769" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta5-build3769" />
  </ItemGroup>

  <ItemGroup>
    <None Update="xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
```

And my source file:

```csharp
using System.Threading;
using Xunit;

public class Class1
{
    [Fact] public void Test1() { Thread.Sleep(5000); Assert.True(true); }
}

public class Class2
{
    [Fact] public void Test2() { Thread.Sleep(5000); Assert.True(true); }
}
```

**Comment by FabioMenta** [comment]
I run test from visual studio (15.3.4) and not in console.
link project: [https://1drv.ms/u/s!AvanKtPyxDTjgu4-5-kmg03RYkZYyg](url)
![untitled](https://user-images.githubusercontent.com/4414875/30511430-3c42ac68-9ad9-11e7-8903-787ee86d1022.jpg)

**Comment by bradwilson** [comment]
Sorry, still no repro:

![Visual Studio](https://user-images.githubusercontent.com/16944/30513671-045b8710-9abc-11e7-999a-0e0150cf1381.png)

My suspicion is that you did not follow [these directions](https://xunit.github.io/docs/configuring-with-json.html#file):

![Directions](https://user-images.githubusercontent.com/16944/30513684-5452215c-9abc-11e7-8e7f-f1e39432c608.PNG)

**Comment by FabioMenta** [comment]
thank you for your time
