### ISSUE TITLE
Span<T> assertion failed

### ISSUE THREAD

**Issue by lextm** [xunit/xunit#1457]
Microsoft introduced `Span<T>` in `System.Memory` for .NET Core 2.0. But the simplest assertion as below,
```
var expected = new[] {(byte) 0x66};
var span = new Span<byte>(expected);
Assert.Equal(expected, span);
```
can simply lead to an exception, instead of showing the assertion fails,
```
Unhandled Exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at ConsoleApp1.Program.Main(String[] args)
```

**Comment by stephentoub** [comment]
The failure is due to boxing the span to pass it as an object to the Equal overload. Span is a byref-like type and can't be put on the heap, which boxing does. But I agree a more descriptive error would be helpful, both from the compiler and via an exception at run-time.

**Comment by onovotny** [comment]
@stephentoub 
>Span is a byref-like type and can't be put on the heap, which boxing does.

This sounds like a recipe for disaster... I understand why it cannot be boxed, but it seems like this should be a compile-time failure instead of a runtime one. Otherwise it seems like it'll leave lurking bugs.

**Comment by stephentoub** [comment]
> it seems like this should be a compile-time failure instead of a runtime one

Hence why I said "from the compiler".
cc: @VSadov

**Comment by VSadov** [comment]
New compiler will understand the limitations of Span and Span-containing types.
Newer version of Span will not be usable from old compilers.

This scenario will be a compiler error - one way or another, once all pieces are in place.

Here you are using Span with an old compiler that does not understand the safety implications. This is a point-int-time problem. Hopefully very brief.

CC: @jaredpar

**Comment by VSadov** [comment]
With the new compiler, I get 
```error CS1503: Argument 2: cannot convert from 'System.Span<byte>' to 'object'```

**Comment by mattwarren** [comment]
@stephentoub 

> But I agree a more descriptive error would be helpful, both from the compiler and **via an exception at run-time.**

Should an issue be opened on the CoreCLR repo to make this happen? There are still some scenarios where this will only get caught at run-time, i.e. using code from other C# compiler, ILASM, etc, so it would be nice to have a more descriptive error message

**Comment by karelz** [comment]
Yes, we should create tracking issue in CoreCLR/CoreFX, cc @KrzysztofCwalina @joshfree @ahsonkhan

**Comment by joshfree** [comment]
> Microsoft introduced Span<T> in System.Memory for .NET Core 2.0. 

Please note that System.Memory is a preview package.  This feature is part of the .NET Core 2.1 release wave and is still under active development along with the accompanying Roslyn compiler support.

**Comment by bradwilson** [comment]
Closing as an external issue.
