### ISSUE TITLE
Fix xunit 2.3 beta 2 release notes typo

### ISSUE THREAD

**Issue by netchkin** [xunit/xunit#1459]
The page https://xunit.github.io/releases/2.3-beta3 specifies that the command `msbuild /t:XuniTest` is available. However, the target should rather be `XunitTest`. Correcting this typo will make it less confusing.

**Comment by x2764tech** [comment]
Was this fixed? https://github.com/xunit/xunit.github.io/pull/47

**Comment by netchkin** [comment]
yes, this is fixed
