### ISSUE TITLE
Consider adding TheoryData classes with more arguments

### ISSUE THREAD

**Issue by paulomorgado** [xunit/xunit#1460]
I find `TheoryData` classes very useful for building theory data.

But, sometimes, I need more than 5 arguments.

I know I could use tuples. But, unless you're using C# 7+ (and you should :smile:), they don't help much in the way of understanding your code.

**Comment by bradwilson** [comment]
Feel free to send a PR for more parameters! :)

**Comment by paulomorgado** [comment]
PR #1470

Made from the browser.
