### ISSUE TITLE
Detect discovery vs running tests

### ISSUE THREAD

**Issue by ornatwork** [xunit/xunit#1461]
Is it possible for the code in Theory Memberdata function to detect weather xUnit is doing discovery vs running the tests ? Is there some run-time switch that one could check for.  Or perhaps one can use an attribute to run one Memberdata function for discovery and another for the actual run.

Why do I want to do this ?
Because I have a wrapper for running RSpec tests from VS and under CI builds that will bring the Rspec test results back to the environment. This way the devs can run the tests from VS instead of having to run them on the command line. To save time, I only want to shoot off RSpec once and run all test in a directory instead of once for each test. Although I don't want to run the tests during discovery, just return the test names. I have been reading through the xUnit code but I haven't been able to figure it out yet.

**Comment by bradwilson** [comment]
There is not, though if you want to prevent enumeration during discovery, you can see `DisableDiscoveryEnumeration = true` on the `[MemberData]` attribute.

**Comment by bradwilson** [comment]
> Or perhaps one can use an attribute to run one Memberdata function for discovery and another for the actual run.

This is not something we'd support, because it would open up the possibility of returning different data sets during discovery vs. execution. In general, if you're going to pre-enumerate data, it needs to be stable/repeatable; if the data cannot be guaranteed to be stable/repeatable, then discovery enumeration has to be turned off.

**Comment by ornatwork** [comment]
DisableDiscoveryEnumeration works for me, I'm closing this one out, thanks for your time.
