### ISSUE TITLE
Text comparison output difficult to read in non-fixed width font (Visual Studio 2017)

### ISSUE THREAD

**Issue by nebosite** [xunit/xunit#1463]
This assert generates output that is difficult to parse unless I paste it into a fixed-width editor:

             Assert.Equal("This is a long and interesting string", "This is a long and interesting String");

![image](https://user-images.githubusercontent.com/6156209/30752042-f9114f3a-9f6f-11e7-9442-1d953553afd6.png)

It should look like this:
![image](https://user-images.githubusercontent.com/6156209/30752120-19791dac-9f70-11e7-80c7-30352080e636.png)

**Comment by marcind** [comment]
Do you have any suggestions on what could be done about this?

**Comment by bradwilson** [comment]
We have raised this issue to the Visual Studio team in the past, as their runner is the only one (that I'm aware of) that does not use a fixed pitch font for output.

**Comment by nebosite** [comment]
I discovered that I can change the runner font this way:

Tools->Options->Environment->Fonts and Colors
Show settings for "Environment" and change the font to Consoleas or some other fixed width font.  This sort of sucks because it changes all the menu fonts and other unrelated stuff.  :(

**Comment by bradwilson** [comment]
Closing as external, as this issue is within Visual Studio, not xUnit.net itself.
