### ISSUE TITLE
XUnit Test runs are about ~5x slower than equivalent MSTest runs.

### ISSUE THREAD

**Issue by nebosite** [xunit/xunit#1465]
I have two projects of about 2000 LOC and about a dozen tests.    One project uses MSTest and the other uses XUnit. All of the tests execute individually in under 20ms, however the MSTest run completes much faster than xUnit.   The total run times are as follows:

Warm run (run all to make sure everything is in memory, then run all again)
xUnit:  ~ 7 seconds
MSTest: ~1 second

Cold run (run all, make a test code change, run all again)
xUnit: ~ 8 seconds
MSTest:  ~2 seconds

This time difference is significant and annoying enough to make me consider not using xUnit.

**Comment by nebosite** [comment]
I ran an experiment with identical projects and got a much smaller delta (1.5x) .  Closing.

**Comment by bradwilson** [comment]
This should really only be true inside of the Visual Studio runner, for architectural reasons that are too complex to go over. All our other runners tend to be extremely fast.

We have been working to reduce some of these expenses inside the VS runner, and it's the primary focus for 2.3 RTM right now.
