### ISSUE TITLE
xunit.analyzer raises false positive warnings on "public static" and "public abstract" methods

### ISSUE THREAD

**Issue by 4creators** [xunit/xunit#1466]
xUnit framework does not support neither "public static void" nor "public abstract void" as a test methods. This same is true for their async equivalents. The reasons for this design choice for "public static" are based on the use of instance constructors for test setup and IDisposable.Dispose for test tear down. While in case of abstract methods their execution is impossible since they by definition have no code to execute.

I have fixed issue already and will provide PR to xunit.analyzers repo.

**Comment by bradwilson** [comment]
> xUnit framework does not support neither "public static void" nor "public abstract void" as a test methods. 

This is half right: we absolutely do support static test methods.

**Comment by bradwilson** [comment]
Here is just one file (of many) full of counter-examples:

https://github.com/xunit/xunit/blob/b2d86d61623aba278fed1fb149b056255b87b3b6/test/test.xunit.assert/Asserts/CollectionAssertsTests.cs#L13-L53
