### ISSUE TITLE
Question: Why do some theories get expanded into individual test cases and others not?

### ISSUE THREAD

**Issue by ericwj** [xunit/xunit#1473]
I have a test class with several `[Theory, InlineData]` attributes. To me, they look quite the same in every aspect, but VS shows some of them as one test and expands others into individual tests for each `[InlineData]` attribute present.

Where does the difference come from? More importantly, how do I force the one or the other behavior? Expanding them is very useful, as it allows me to more easily see which tests fail and invoke them individually from Test Explorer in VS.

As usually, I have no clue whether this behavior comes from VS or from Xunit.

I would add some code to repro, but doing that, VS shows all tests individually always. Nevertheless, when I copy the test class to a new XUnit project, the same behavior occurs. Is there some foo in the processing of (combinations of) parameter types? If so, what is the crux?

![image](https://user-images.githubusercontent.com/9473119/31023925-af7c08be-a53d-11e7-9432-af86a3077245.png)

**Comment by ericwj** [comment]
Let me just copy the code of the test class from the screenshot into here.
```CS
using System.Collections.Generic;
using Xunit;

namespace XUnitTestProject
{
    public enum E : ushort
    {
        O, P, Q, R,
    }
    public class TestExplorerDisplayTests
    {
        public const E DefaultValue = E.R;
        public const E All = unchecked((E)(-1));
        public const E OP = E.O | E.P;
        public const E NotOP = All & ~OP;
        public const E Before = unchecked((E)(All));
        public const E After = unchecked((E)(NotOP));

        public class Params
        {
            public override string ToString() => "Hello World";
        }
        public static IEnumerable<object[]> BlaTests() {
            yield return new object[] { new Params() };
        }

        [Theory(DisplayName = nameof(Bla))]
        [MemberData(nameof(BlaTests))]
        public void Bla(Params p) { }
        [Theory(DisplayName = nameof(Other))]
        [InlineData("a", 0x0010, 0x0010, 0x0040, new byte[] { 0x01 }, new ushort[] { 0x0040 }, new ushort[0])]
        [InlineData("b", 0x0010, 0x0020, 0x0040, new byte[] { 0x01 }, new ushort[] { 0x0020, 0x0040 }, new ushort[0])]
        [InlineData("c", 0x0010, 0x0010, 0x0040, new byte[] { 0x01, 0x03, 0x00 }, new ushort[] { 0xabcd, 0xefab, 0x0040 }, new ushort[0])]
        [InlineData("d", 0x0010, 0x0020, 0x0040, new byte[] { 0x01, 0x03, 0x06 }, new ushort[] { 0xabcd, 0xefab, 0xcdef, 0x0020, 0x0040 }, new ushort[0])]
        public void Other(string expected, ushort a, ushort expectedA, ushort expectedB, byte[] array, ushort[] pre, ushort[] post) {

        }
        [Theory(DisplayName = nameof(Next))]
        [InlineData("a", 0x0010, 0x0f0e, 0x0d0c, new byte[] { 0x0f }, new ushort[0], new ushort[] { 0x0001, 0x0010, (ushort)Before })]
        [InlineData("b", 0x0010, 0x1312, 0x1110, new byte[] { 0x0f }, new ushort[0], new ushort[] { 0x0001, 0x0010, (ushort)Before })]
        [InlineData("c", 0x0010, 0x0706, 0x0504, new byte[] { 0x0f, 0x01 }, new ushort[0], new ushort[] { 0x0002, 0x0010, (ushort)Before })]
        public void Next(
            string expected, ushort a, ushort expectedA, ushort expectedB,
            byte[] bytes, ushort[] pre, ushort[] post) { }
        [Theory(DisplayName = nameof(YetAnother))]
        [InlineData("a", 0x0010, 0x0020, 0x0101, new byte[] { 0xef }, new ushort[] { (ushort)Before, 0x0020, 0x0101 }, new ushort[0])]
        public void YetAnother(
            string expected, ushort a, ushort expectedA, ushort expectedB,
            byte[] array, ushort[] pre, ushort[] post) { }
        [Theory(DisplayName = nameof(Last))]
        [InlineData("a", (sbyte)(-2), 0, E.Q, 0, 0, new byte[] { 0xfe, 0xfe }, new ushort[0])]
        [InlineData("b", (sbyte)(-1), 0, E.Q, 0, 1, new byte[] { 0xfe, 0xff }, new ushort[0])]
        [InlineData("c", (sbyte)(+0), 0, E.Q, 0, 2, new byte[] { 0xfe, 0x00 }, new ushort[0])]
        [InlineData("d", (sbyte)(+1), 0, E.Q, 0, 3, new byte[] { 0xfe, 0x01 }, new ushort[0])]
        [InlineData("e", (short)(0x1fc), 0, DefaultValue, 0, 0x1ff, new byte[] { 0xfe, 0x01 }, new ushort[] { 3 })]
        [InlineData("f", 0x001000ffu, 0, DefaultValue, 0x0010, 0x00ff, new byte[] { 0xfe, 0x00 }, new ushort[] { 0, 5 })]
        [InlineData("g", null, 4, DefaultValue, 0x0010, 0x0ff, new byte[] { 0xfe, 0x1C }, new ushort[] { 0, 6 })]
        [InlineData("h", null, 2, DefaultValue, 0, 0x1ff, new byte[] { 0xfe, 0x14 }, new ushort[] { 4 })]
        [InlineData("i", (sbyte)(-2), 0, DefaultValue, 0, 0x0000, new byte[] { 0xfe, 0xfe }, new ushort[0])]
        [InlineData("j", (short)(0x1fc), 0, DefaultValue, 0, 0x1ff, new byte[] { 0xfe, 0xfc }, new ushort[0])]
        [InlineData("k", null, 2, DefaultValue, 0, 0x1ff, new byte[] { 0xfe, 0x24 }, new ushort[0])]
        [InlineData("l", null, 4, DefaultValue, 0x0010, 0x00fe, new byte[] { 0xfe, 0x0C }, new ushort[0])]
        [InlineData("m", 0x001000ffu, 0, DefaultValue, 0x0010, 0x00ff, new byte[] { 0xfe, 0x00 }, new ushort[0])]
        public void Last(string expected, object expectedI, byte o, E e, ushort a, ushort b, byte[] array, ushort[] s) { }
    }
}
```

**Comment by bradwilson** [comment]
I think I've written this up before, so I really need to open an issue for putting this on the documentation site as a FAQ.

## The short answer

If some of your theory data can't be "serialized" by xUnit.net, then it cannot be encapsulated into the serialization of a test case which we're required to do for the Visual Studio test runner.

## The long answer

In the Visual Studio test runner, test cases are discovered in one process, and executed in another. Therefore, test cases must be able to be turned into an unqualified string representation (aka, "serialized") in order to be run. We can also serialize at the test method level, because that just involves knowing the type and method name (both strings). When you start putting data into the mix, we need to ensure we know how to serialize that data; if we can't serialize _**all**_ of the data for a theory, then we have to fall back to just a single method (which we know we can serialize).

I've used "serialize" with air quotes because while what we're doing is serialization, it isn't the serialization system built into .NET. We can't use that, because it's not available on all of our target platforms (in particular, it's not available on UWP). Therefore, we have built-in support for serializing several types (including arrays of these types):

https://github.com/xunit/xunit/blob/5c8a0181d1b84fb280c2a8d3516a6746e7505cd6/src/common/XunitSerializationInfo.cs#L326-L343

We've also added our own interface for allowing users to customize serialization (both for custom test cases, as well as custom theory data):

https://github.com/xunit/xunit/blob/9f4fe30892c3a62cc8aea23e1e7cef8dd08c0b0f/src/xunit.abstractions/Serialization/IXunitSerializable.cs#L1-L20

In the case of `Bla`, the issue is `Params`. If it were to implement serialization, you would see that you started getting individually runable test cases again.

In the case of `Last`, my guess is that you're running afoul with the `null` objects, and since the signature is `object` (which is not serializable), you're failing there. To verify, though, the easiest way would be to comment out all the InlineData, and then one at a time, restore them and rebuild, and see what Test Explorer shows (and when it stops giving you individual data items).

**Comment by ericwj** [comment]
That's a clear explanation, thanks for that!

What you don't mention, but I'm sure is true, is that enums are also somehow serializable by this means, even though that declaration you refer to makes no mention of them.

The other thing is that UWP 6.0 is soon to be available, would it be possible to make this quirk only be quirky on quirky platforms? Imho if serialization is available, including in UWP 6.0, it should be possible to use it instead of a custom fallback perhaps. I hope.

**Comment by altrive** [comment]
I've also facing this issue, and in my case that is caused by "sbyte" parameter. 

@bradwilson 
Though, "sbyte" is not contains in supportedSerializationTypes .
Is there any technical reason not to supporting "sbyte" primitive data type?

```
[Theory]
[InlineData((byte)1, (byte)2)]
[InlineData((byte)2, (byte)2)]
public void ByteParams(byte actual, byte expected)
{
    // Theory is enumerated successfully
}

[Theory]
[InlineData((sbyte)1, (sbyte)2)]
[InlineData((sbyte)2, (sbyte)2)]
public void SByteParams(sbyte actual, sbyte expected)
{
  // Theory is not enumerated!
}
```

**Comment by ericwj** [comment]
I also ran into an issue changing these `object` parameters to string and parsing them myself - easier than introducing that serialization mechanism into my code imho. The whole thing is slightly unfortunate anyway because those objects are types serializable by Xunit - I just don't know which one. (apart from sbyte indeed, please do add it)

If I change the test cases from the code I shared that have `objects` with a `string` parameter and set it to `[InlineData("null")]`, I might be able to step through or debug, but if I run those test cases from VS or the command line, I get a stack trace like this:

```
The active test run was aborted. Reason: .2.0.3545, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<RunTestMethodsAsync>d__38<System.__Canon> ByRef)
   at Xunit.Sdk.TestClassRunner`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].RunTestMethodsAsync()
   at Xunit.Sdk.TestClassRunner`1+<RunAsync>d__37[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Xunit.Sdk.TestClassRunner`1+<RunAsync>d__37[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], xunit.execution.dotnet, Version=2.2.0.3545, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<RunAsync>d__37<System.__Canon> ByRef)
   at Xunit.Sdk.TestClassRunner`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].RunAsync()
   at Xunit.Sdk.TestCollectionRunner`1+<RunTestClassesAsync>d__28[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Xunit.Sdk.TestCollectionRunner`1+<RunTestClassesAsync>d__28[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], xunit.execution.dotnet, Version=2.2.0.3545, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<RunTestClassesAsync>d__28<System.__Canon> ByRef)
   at Xunit.Sdk.TestCollectionRunner`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].RunTestClassesAsync()
   at Xunit.Sdk.TestCollectionRunner`1+<RunAsync>d__27[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Xunit.Sdk.TestCollectionRunner`1+<RunAsync>d__27[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], xunit.execution.dotnet, Version=2.2.0.3545, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<RunAsync>d__27<System.__Canon> ByRef)
   at Xunit.Sdk.TestCollectionRunner`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].RunAsync()
   at Xunit.Sdk.XunitTestAssemblyRunner+<>c__DisplayClass14_2.<RunTestCollectionsAsync>b__3()
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at System.Threading.Tasks.SynchronizationContextTaskScheduler+<>c.<.cctor>b__8_0(System.Object)
   at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(System.Threading.SendOrPostCallback, System.Object)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc()
   at Xunit.Sdk.XunitWorkerThread+<>c.<QueueUserWorkItem>b__5_0(System.Object)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
```

Doing that in a new project however, all seems to be OK.

**Comment by bradwilson** [comment]
> What you don't mention, but I'm sure is true, is that enums are also somehow serializable by this means, even though that declaration you refer to makes no mention of them.

Local enums are; GAC'd enums aren't. Too long a story to worry about for here.

https://github.com/xunit/xunit/blob/5c8a0181d1b84fb280c2a8d3516a6746e7505cd6/src/common/XunitSerializationInfo.cs#L374-L378

> The other thing is that UWP 6.0 is soon to be available, would it be possible to make this quirk only be quirky on quirky platforms?

Unfortunately, the serialization requirements have been with us since 2.0, and it would be a breaking change to now require all the extensibility points to switch from our own serialization mechanism over to something else.

> Is there any technical reason not to supporting "sbyte" primitive data type?

No reason it can't be added. It was probably overlooked because it's the only explicitly signed type.

**Comment by bradwilson** [comment]
> The active test run was aborted. Reason: .2.0.3545, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]]

This exception message looks mangled. Is this really what you saw?

**Comment by bradwilson** [comment]
Also, as an FYI, whenever you upgrade the `xunit.runner.visualstudio` package, you will need to shut down and restart Visual Studio, because it often caches the old version of the package and you can get some odd behavior as a result.

**Comment by ericwj** [comment]
Yes, I will clarify now.

**Comment by ericwj** [comment]
Mmm, I'm using `Unsafe.AsPointer<T>(ref T)` and `Unsafe.AsRef<T>(void *)` chained together. Just two tests that do that cause Xunit to either throw, or just stop without producing bright icons (failures nor successes).

I tried to reproduce but the oneliner test method just works in a new project.

I don't know where to look really - maybe it's a GC issue which requires there to be quite some time between the allocation and pinning and the subsequent use of AsPointer....no idea exactly.

**Comment by ericwj** [comment]
Ah, the assumptions...sometimes... And writing it down somehow made me rethink 

So I found it: #1482

**Comment by jherby2k** [comment]
> Unfortunately, the serialization requirements have been with us since 2.0, and it would be a breaking change to now require all the extensibility points to switch from our own serialization mechanism over to something else.

I don't understand why you couldn't just use xunit "serialization" where supported but fall back to .NET serialization (on supporting platforms). Having to implement IXunitSerializable isn't ideal - I have a type for instance that uses static methods for instantiation and a non-default constructor. It works with [Serializable] just fine because that doesn't call a constructor, but it means I can't wrap it in IXunitSerializable.

Also, having to subclass everything and implement IXunitSerializable is just kind of annoying.

**Comment by bradwilson** [comment]
I don't think we have a guarantee that `[Serializable]` is implemented identically across all platforms, which becomes important for us with TPv1 and UWP because discovery is done w/ the desktop CLR and execution is done in the device runtime. We already have to have workarounds for types which have moved from one assembly to another, because we don't have the benefit of type forwarding.

**Comment by ericwj** [comment]
It could be useful to implement basic serialization of complex objects perhaps? So public properties and fields are automatically serialized. I find what I'm doing now is declaring a class with some properties and no constructor and no logic in getters or setters, just to hold the test parameters. Implementing `IXunitSerializable` makes that code 3x longer, it is boring to write and feels unnecessary.

It would be fine for me to have to annotate it with an attribute in order to prevent using automatic serialization on types that wouldn't support it - i.e. that have no public constructor or have non-trivial logic in the getters or setters.

Combined perhaps with MemberData supporting `IEnumerable<T>` on top of `IEnumerable<object[]>` and T just a class to hold the parameters, that would quicken writing most tests that I have that had problems due to serialization. Having to new up an object[] array always felt a bit...hacky? E.g. I have tests that produce IEnumerable<T> and a generic method that wraps it in an object array, but it requires declaring another property for use in the [MemberData] every time.

**Comment by goodvinj** [comment]
This Theory is not enumerated for some reason:

`            [Theory]
            [InlineData("pub1", "pos1", "pub1", null, true)]
            [InlineData("pub1", "pos1", "pub2", null, false)]
            [InlineData("pub1", "pos1", null, null, true)]
            [InlineData("pub1", "pos1", "pub1", "pos1", true)]
            [InlineData("pub1", "pos1", "pub1", "pos2", false)]
            [InlineData("pub1", "pos1", null, "pos1", true)]
            [InlineData("pub1", "pos1", "pub2", "pos1", false)]
            public void PublisherPlacementRule(string requestPubCode, string requestPositionName,
                string rulePublisherCode, string rulePositionName, bool expectedResult)
            {
            }
`

If I restart Visual Studio R# shows it as multiple tests, but when I run them I see 1 test again.
Moreover, sometimes I can't run these tests because R# shows "Inconclusive: Test not run" message.

**Comment by goodvinj** [comment]
OK, it looks like a bug in R#, because I can run these tests from Test Explorer w/o any issues.

**Comment by reft** [comment]
Would be cool if this was fixed :) https://stackoverflow.com/questions/46749152/xunit-display-test-names-for-theory-memberdata-testcase

**Comment by bradwilson** [comment]
@reft I don't know what you mean "fixed" means in this context. This behavior is by design.

**Comment by bradwilson** [comment]
There were several issues here, some of which were fixed. If there are still outstanding things, please open new issues.

**Comment by greendimka** [comment]
Can we get an example of IXunitSerializable implementation?

**Comment by bradwilson** [comment]
There are several uses of it inside the unit tests for the serialization system: https://github.com/xunit/xunit/blob/v2/test/test.xunit.execution/Common/XunitSerializationInfoTests.cs
