### ISSUE TITLE
Platform not supported errors since update from 2.3.0-beta5 to 2.3.0-rc1

### ISSUE THREAD

**Issue by axelheer** [xunit/xunit#1478]
Since upgrading to the newest version all integration tests using sql connections fail with:

```
System.NotSupportedException : The keyword 'integrated security' is not supported on this platform.
```

Repro:

```csharp
using System;
using System.Data.SqlClient;
using Xunit;

namespace XUnitIssue
{
    public class UnitTest1
    {
        [Fact]
        public void Test1()
        {
            var connectionString = @"Data Source=(LocalDB)\MSSQLLocalDB; Initial Catalog=master; Integrated Security=true;";

            new SqlConnection(connectionString).Open();
        }
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="xunit" Version="2.3.0-rc1-build3809" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-rc1-build3809" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-rc1-build3809" />
  </ItemGroup>

</Project>
```

Notes:
* executing `dotnet test` succeeds, only `dotnet xunit` fails
* changing the version numbers back to `2.3.0-beta5-build3769` solves the problem

**Comment by bradwilson** [comment]
What target platform (OS, .NET SDK version #, etc.) are you running this on?

**Comment by axelheer** [comment]
Windows 7, .NET Core 1.1.4, .NET Core SDK 2.0.0

**Comment by bradwilson** [comment]
Found the bug... it was trying to use the `unix` version of the SqlClient assembly instead of the `win` version. Glad you caught this! Thanks!

**Comment by bradwilson** [comment]
Hmm, not quite finished yet:

`System.DllNotFoundException : Unable to load DLL 'sni.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)`

**Comment by bradwilson** [comment]
Finally got it figured out, once again due to the awesomeness of @natemcmaster. :) This will be fixed in RC 2.

**Comment by andreabalducci** [comment]
same issue updating dotnet-xunit from 2.3.0-beta1-build3642 to 2.3.1.
Platform MacOs
Dotnet 2.0.0

**2.3.0-beta1-build3642**
test ok

**2.3.1**
System.PlatformNotSupportedException : System.Data.SqlClient is not supported on this platform.

**Comment by andreabalducci** [comment]
Failing on appveyor too (with different message) https://ci.appveyor.com/project/andreabalducci/nstore/build/1.0.418

Working build (2.3.0 beta1)
https://ci.appveyor.com/project/andreabalducci/nstore/build/1.0.417

**Comment by bradwilson** [comment]
@andreabalducci Please open an new issue with a repro project.

**Comment by bradwilson** [comment]
Also, your AppVeyor error is unrelated, and is actually this non-bug: #1573

**Comment by andreabalducci** [comment]
related issue with repro prj https://github.com/xunit/xunit/issues/1585
