### ISSUE TITLE
Build 2.3.0-rc1-build3809 failing when I run from OSX Terminal

### ISSUE THREAD

**Issue by rgiampietro** [xunit/xunit#1481]
dotnet xunit
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.0.5' was not found.
  - Check application dependencies and target a framework version installed at:
      /
  - Alternatively, install the framework version '1.0.5'.

**Comment by bradwilson** [comment]
That's probably because you don't have .NET Core 1.0.5 installed. 😉 

https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.0.5-download.md

**Comment by bradwilson** [comment]
Alternatively, you could target the framework you do have installed, by using `<RuntimeFrameworkVersion>` as [documented here](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj).

**Comment by rgiampietro** [comment]
True, however I do have .net core 2.0.0. which should work, no? 

Thanks for the quick response.

Rick


Ricks-MacBook-Pro:WebIZ.Mobile.Test.CoreApp rickg$ dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by bradwilson** [comment]
Not unless your tests are compiled against `netcoreapp2.0`.

**Comment by bradwilson** [comment]
Can you provide a repro? I don't have OS X, but I can test it on Linux which should be similar enough.

**Comment by rgiampietro** [comment]
Hmm looking over the test project(s) we have 2 of them targeting 2.0.0, the third only has the target set to ‘Xamiran.iOS’. Sorry I’m new to Xamarin dev, maybe this is the issue? Other devs are not having this problem, I’ll check there setup when they’re back from their meeting. I’ll also try forcing the target framework like the example link you sent me shows.

Also, sorry I’m not sure how I’d provide a repro for this. The project is a commercial product and we’re just using the latest nuget package/compiled dlls for xunit, not sure how I’d provide a repro in this situation/on Mac/VS2017.

Rick

**Comment by rgiampietro** [comment]
For what it’s worth we already have the TargetFramework set in our proj file:


rick

**Comment by bradwilson** [comment]
`<TargetFramework>netcoreapp1.0</TargetFramework>` means "more or less, any 1.0.x framework should be fine, where adding `<RuntimeFrameworkVersion>1.0.4</RuntimeFrameworkVersion>` says "I want to run with 1.0.4".

**Comment by bradwilson** [comment]
> Other devs are not having this problem, I’ll check there setup when they’re back from their meeting.

Well, the easiest solution would be to install the .NET SDK that I linked above, and your probably should go away. My guess is that that is probably the difference between your environment and theirs.

**Comment by rgiampietro** [comment]
Oh doesn't installing 1.0.5 replace my 2.0.0 which I/we need for our main project? That's the only reason I didn't install 1.0.5. Sorry for the mixup! And thanks for the help with this.

**Comment by rgiampietro** [comment]
Installing 1.0.5 SDK Binaries fixed the issue and for anyone else wondering installing an older dotnet package left my 2.0.0 and VS2017 OSX project unaffected.

Thanks again for the help!

**Comment by bradwilson** [comment]
Yeah, it's not clear from that site, but installing SDKs adds frameworks and runtimes rather than replacing them, and in my experience (at least on Windows and Linux), installing older after newer works just fine.

Glad it's working for you now. 👍

**Comment by GeorgDangl** [comment]
Is it possible this error also triggers when The project is on a different hard disk than the dotnet install dir? dotnet is on `C:` while the project is on `D:`. The Visual Studio runner works fine, `dotnet test` also, but xUnit 2.3.0 tells me I should install netcoreapp2.0. Which is installed.

It's working when I copy the project to `C:` (Or, at least, I'm getting different errors then).

**Comment by rgiampietro** [comment]
Not in my case, I'm running on Mac. I was missing the 1.0.5 runtime which you install using the 1.0.4 package. Long/short I thought having 2.0.0 was enough, but you actually have to have 1.0.5 (runtime) installed to correct the issue. You can have both 2.0.0 and 1.0.5 installed, which wasn't clear to me.

**Comment by bradwilson** [comment]
@GeorgDangl I'm not able to repro the problem, with your source on D: and dotnet.exe on C:

![image](https://user-images.githubusercontent.com/16944/31783576-913492b0-b4b3-11e7-8edc-0c8333e4bcb4.png)

**Comment by GeorgDangl** [comment]
@bradwilson , I could narrow it down. It's a problem with the framework version `2.1.0-preview1-007102` being installed, see this console output:
![unbenannt](https://user-images.githubusercontent.com/10274404/31832760-726747cc-b5c8-11e7-8161-a1ab308b5539.PNG)

Uninstalling it and running with `2.0.2` fixed the issue for me.

**Comment by bradwilson** [comment]
That's probably because you were still targeting `netcoreapp2.0` instead of `netcoreapp2.1`, but you didn't actually have any 2.0 variant installed.

**Comment by GeorgDangl** [comment]
Yes, I was targetting `netcoreapp2.0`, but the SDK versions `2.0.0` and `2.0.2` both were installed.

**Comment by bradwilson** [comment]
SDK versions are not the same as runtime versions. What really matters is what you find in `shared` folder where `dotnet` is installed. This is what I have on Windows:

```
 PS> dir 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\'


    Directory: C:\Program Files\dotnet\shared\Microsoft.NETCore.App


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----      2017-Sep-17     11:09                1.0.4
da----      2017-Aug-15      0:26                1.0.5
d-----      2017-Sep-17     11:10                1.1.1
da----      2017-Aug-14     19:14                1.1.2
da----      2017-Aug-14     19:12                2.0.0
```

and on Linux:

```
$ ll /usr/share/dotnet/shared/Microsoft.NETCore.App/
total 0
drwxr-xr-x 0 root root 512 Aug 17 17:41 ./
drwxr-xr-x 0 root root 512 Aug 17 17:29 ../
drwxr-xr-x 0 root root 512 Aug 17 17:41 1.0.5/
drwxr-xr-x 0 root root 512 Aug 17 17:41 1.1.2/
drwxr-xr-x 0 root root 512 Aug 17 17:30 2.0.0/
```

The SDKs will let you target anything, including things that aren't locally installed, because the reference assemblies are pulled from NuGet. However, the runtime has to be installed to run it.

**Comment by GeorgDangl** [comment]
Ah, thank you very much for the clarification! I checked it, and as you said, I only had the runtime for `2.0.0` installed but none for `2.1.0`.
