### ISSUE TITLE
Problem running tests in .NET Core on RC1 w/ System.Data.SqlClient dependency

### ISSUE THREAD

**Issue by jbogard** [xunit/xunit#1484]
This commit on my project where I reverted to the beta 5 release:

https://github.com/jbogard/Respawn/commit/4e0c35b6537efeab0fc896aa283d8d34d6612a44

Fixed my build. Passing build:

https://ci.appveyor.com/project/jbogard/respawn/build/41

Failing build:

https://ci.appveyor.com/project/jbogard/respawn/build/40

🤷‍♂️

**Comment by bradwilson** [comment]
I believe this might be a different manifestation of #1478. I'm pushing an RC 2 build right now that might fix it.

**Comment by bradwilson** [comment]
I just tried RC 2 and I no longer see any assembly load failures with `netcoreapp2.0`, only inability to connect to the SQL Server, which I think is probably a good sign. :)

**Comment by jbogard** [comment]
RC2 fixed it for me. Thanks!
