### ISSUE TITLE
Skip individual test cases from MemberData

### ISSUE THREAD

**Issue by adrianiftode** [xunit/xunit#1485]
Considering the same scenario as for *InlineData* when we can skip some test cases, how can we achieve using **MemberData**?

Ie.

```
[Theory]
[MemberData(nameof(GetTestData))]
public void ShouldBehave(Product product, bool expected)
{
   ....
}

 public static IEnumerable<object[]> GetTestData()
 {
     //Case 1
      yield return new object[] {
                new Product { InStock = true },
                true
            };

   //Case 2 - skip this because we don't know yet how to handle it yet
      yield return new object[] {
                new Product { InStock = false },
                true
            };
 }
```

Possible to use a convention like?

```
      yield return new object[] {
                new Product {InStock = false},
                true,
                new Skip(reason: "skip this because we don't know yet how to handle it yet")
            };
```

**Comment by marcind** [comment]
This is not possible with xUnit at this time. You could split `GetTestData` into two "collections", one of which is skipped:

```c#
[Theory,
MemberData(nameof(GetTestData)),
MemberData(nameof(GetSkippedTestData), Skip = true)]
...
```

**Comment by adrianiftode** [comment]
Should be fine, thanks.

**Comment by shahasad** [comment]
What if I want to print individual reason for each of the skipped test cases? How to achieve that?

**Comment by markm77** [comment]
Yes would be really nice if ```MemberData``` could return a skip message (or null) to indicate whether to skip and skip reason *per input/case*. Currently my code uses ugly redirects in skip messages so the user can find the real reason a particular case is skipped:

```csharp
        [Theory]
        [MemberData(
            memberName: nameof(SkippedTestsByInputName),
            nameof(TestType),
            Skip = "Test skipped due to skip instruction in " + nameof(LookupType))]
        [MemberData(
            memberName: nameof(UnskippedTestsByInputName),
            nameof(TestType))]
```

Could this be considered @bradwilson ?

**Comment by jzabroski** [comment]
@markm77 See my xunit Assert.SkipWhen workaround here https://github.com/xunit/xunit/issues/1782#issuecomment-676589656

**Comment by markm77** [comment]
@jzabroski Thanks for this but programmatic skip like that does not allow for skipped tests to be run manually (e.g. for fixing/checking tests while out of the suite). Actually JetBrains just removed this functionality but that's another [story](https://youtrack.jetbrains.com/issue/RIDER-49097). I am trusting this functionality will be re-enabled somehow.

What we really need I believe is for MemberData to support more test case meta-data for individual tests such as skip/no-skip, skip reason and also trait etc. I have opened a new issue: https://github.com/xunit/xunit/issues/2164.

**Comment by CarlosHAraujo** [comment]
Hi!
Applying Skip to MemberData won't skip.
This:

`       [Theory]
        [MemberData(nameof(GetDealIdsFromFile), Skip = "Rodando teste simples")]
        public void ShouldGetDeal_WhenDealExists(string dealId)
        {
            Deal deal = _fixture.Scraper.SearchForDeal(dealId).Get();
            Assert.NotNull(deal);
            Assert.Equal(dealId, deal.Id);
        }`

Will not skip "GetDealIdsFromFile" and will trigger the test.
