### ISSUE TITLE
In VS running/debugging single test runs all tests in class

### ISSUE THREAD

**Issue by BrennanConroy** [xunit/xunit#1488]
We just upgraded to `xunit.runner.visualstudio/2.3.0-rc3-build3818` and now when you right click on a single test in VS to run or debug it, it will run all tests in the class instead of the individual test.

**Comment by bradwilson** [comment]
Please provide a repro project.

**Comment by BrennanConroy** [comment]
Closing and Reopening VS after xunit version got updated fixes issue.
