### ISSUE TITLE
AD0001 reported in AssertEqualShouldNotBeUsedForCollectionSizeCheck

### ISSUE THREAD

**Issue by sharwell** [xunit/xunit#1491]
This occurred while typing.

> Warning AD0001 Analyzer 'Xunit.Analyzers.AssertEqualShouldNotBeUsedForCollectionSizeCheck' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'
>
> Exception occurred with following context:
> Compilation: Tvl.Collections.Trees.Test
> SyntaxTree: J:\dev\github\sharwell\dotnet-trees\Tvl.Collections.Trees.Test\TestTreeList.cs
> SyntaxNode: Assert.Equal(0, list.FindLast(i ... [InvocationExpressionSyntax]@[25683..25727) (669,12)-(669,56)
> 
> ```
> System.NullReferenceException: Object reference not set to an instance of an object.
>   at Xunit.Analyzers.AssertEqualShouldNotBeUsedForCollectionSizeCheck.IsWellKnownSizeMethod(SymbolInfo symbolInfo)
>   at Xunit.Analyzers.AssertEqualShouldNotBeUsedForCollectionSizeCheck.Analyze(SyntaxNodeAnalysisContext context, InvocationExpressionSyntax invocation, IMethodSymbol method)
>   at Xunit.Analyzers.AssertUsageAnalyzerBase.<>c__DisplayClass5_0.<Initialize>b__1(SyntaxNodeAnalysisContext syntaxContext)
>   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__43`1.<ExecuteSyntaxNodeAction>b__43_0(ValueTuple`2 data)
>   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
> ```

**Comment by marcind** [comment]
Do you know which version of xunit.analyzers was in use?

**Comment by sharwell** [comment]
@marcind It was version 2.3.0-beta5-build3769.

**Comment by bradwilson** [comment]
That's analyzers 0.7.0.

**Comment by ChrisProlls** [comment]
Is this resolved ? Because I have the same problem ...
@sharwell @marcind @bradwilson

**Comment by bradwilson** [comment]
The analyzers were recently upgraded to support nullable reference types and import versions of their dependencies that are themselves decorated with nullable reference type information. The result was a significant update of places where null reference exceptions might've been occurring: https://github.com/xunit/xunit.analyzers/commit/c45ef67d5f2f7c4e76b3a9da65d9463d14632ede?w=1

I'm going to close this on the assumption that most of these should be caught now, and if anybody has any additional cases please open a new issue. Thanks!
