### ISSUE TITLE
Add analyzer(s) around test case serialization requirements

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1492]
Test cases in xUnit.net must do the following three things, which should be easily detectable by analysis:

- [x] Provide a public parameterless constructor.
- [x] Derive (directly or indirectly) from `LongLivedMarshalByRefObject`.

Failure to do these will cause failures in the Visual Studio test runner; as such, this should be considered an error condition.

Related: #1353

**Comment by marcind** [comment]
Obviously simple types are also serializable. Is there a list somewhere of what is and isn't serializable?

**Comment by bradwilson** [comment]
It isn't documented anywhere (it should be), but you can discern the list from the source code:

https://github.com/xunit/xunit/blob/eecf6d9269411b6ab4bbe7892b32c86ecdace69f/src/common/XunitSerializationInfo.cs#L222-L331

**Comment by bradwilson** [comment]
That said, this bug is specifically about test cases, not theory data. :)

**Comment by marcind** [comment]
I guess I've never written a custom test case.. How does one do that?

**Comment by bradwilson** [comment]
Here's an example: https://github.com/xunit/samples.xunit/tree/master/STAExamples

**Comment by bradwilson** [comment]
BTW, this sample uses `IXunitTestCase`, but the base interface to scout around for is [`ITestCase`](https://github.com/xunit/abstractions.xunit/blob/master/src/xunit.abstractions/TestCases/ITestCase.cs).

**Comment by bradwilson** [comment]
Implemented as xUnit3000 and xUnit3001 (the latter covers any class which implements `IXunitSerializable`, not just test cases).
