### ISSUE TITLE
VS Test Explorer fails for projects having 'n' as first character

### ISSUE THREAD

**Issue by axelheer** [xunit/xunit#1493]
Renaming the 'v2x_net452_DotNetSdk' project of the 'xunit.integration' repo (project path and name) to 'n2x_net452_DotNetSdk' breaks the VS Test Explorer: it's now not possible to jump from the test entry to the corresponding source code. Hence, CodeLens doesn't work any more too.

There seems to be an issue with the 'n' character:

![image](https://user-images.githubusercontent.com/3988385/31329172-1857f95e-acd9-11e7-801f-785c49e7b90e.png)

Maybe the combination "\n" translates (wrongly) to new-line somewhere?

Notes:
- Renaming the 'v2x_net452' leads to the same issue
- Switching to xunit 2.2 seems to resolve the issue

OS: Windows 7
SDK: 2.0.0

**Comment by bradwilson** [comment]
Yep, I know just where I did this. _**facepalm**_
