### ISSUE TITLE
`dotnet xunit` fails when in docker environment

### ISSUE THREAD

**Issue by chris5287** [xunit/xunit#1497]
When targeting a class library at `netstandard2.0` and then writing a test using `netcoreapp2.0`, `dotnet xunit` fails to find dll's that are references by the class library, however `dotnet test` succeeds whilst in a docker container. Running `dotnet xunit` locally on my Windows and OSX machines succeeds as well.

Docker example failure: https://hub.docker.com/r/chris5287/xunit-fails-to-run/builds/brj4kmavgsfjuvbda9akbdy/

Source code: https://github.com/chris5287/xunit-fails-to-run

Exception thrown `System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.AspNetCore.WebUtilities, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.`

**Comment by chris5287** [comment]
@bradwilson any ideas what’s causing this to fail as it’s a blocker for us atm?

**Comment by chris5287** [comment]
I can confirm that downgrading the xunit/dotnet-xunit version to beta5 works (see #1500)

> @bgrainger Note that changing the references (for xunit and dotnet-xunit) to `2.3.0-beta5-build3769` makes `dotnet xunit` succeed, but `2.3.0-rc1-build3809` fails, so it appears the problem must have been introduced between Beta 5 and RC 1.

**Comment by bradwilson** [comment]
I have verified that this is working now with `2.4.0-beta1-build3827`.

**Comment by chris5287** [comment]
I can confirm this works as well 👍 (https://hub.docker.com/r/chris5287/xunit-fails-to-run/builds/bjiqjf9sfcyer4pbtp8jecb/)

@bradwilson is there a plan for when you might do a servicing release (or at least have a version available on nuget, as I can't link to myget feeds in our projects at work)?

**Comment by bradwilson** [comment]
There were enough significant issues with `dotnet xunit` that I'm planning to release a 2.3.1 for them.

There are a few issues I'd like to get in there if I can: #1499, #1495, #1493
