### ISSUE TITLE
xunit.runner.msbuild 2.3 doesn't detect it is running in TeamCity

### ISSUE THREAD

**Issue by mjmckp** [xunit/xunit#1498]
Reproduction of error here: https://github.com/mjmckp/xunit-teamcity-repro

This contains two identical projects, the only difference between the two is the version of `xunit.runner.msbuild` (2.2, which works, and 2.3, which doesn't).  Both projects are targeting .NET framework 4.7.

The batch file which runs each program first sets the `TEAMCITY_PROJECT_NAME` env variable to simulate running under TeamCity.

- Build solution with VS2017
- Set startup project to Test-2.2 and run with F5
- Note that the output contains
```
  ##teamcity[testSuiteStarted name='Test collection for Test.Test (1)' flowId='77c25f3f56ec4765b25c133b23f091a6']
  ##teamcity[testStarted name='Test.Test.test' flowId='77c25f3f56ec4765b25c133b23f091a6']
  ##teamcity[testFinished name='Test.Test.test' duration='11' flowId='77c25f3f56ec4765b25c133b23f091a6']
  ##teamcity[testSuiteFinished name='Test collection for Test.Test (1)' flowId='77c25f3f56ec4765b25c133b23f091a6']
```

- Now set startup project to Test-2.3 and run with F5
- Note that the output is missing the lines starting with `##teamcity` as above.

**Comment by bradwilson** [comment]
That's... weird. That code did not change, unless the TeamCity reporter isn't available for some reason...

**Comment by bradwilson** [comment]
Yeah, that is exactly what's going on:

```
C:\Dev\xunit\xunit.integration\msbuild\v2x_net452\v2x_net452.csproj(56,5): error : Reporter value 'TeamCity' is invalid. There are no available reporters.
```

Doh!
