### ISSUE TITLE
`dotnet xunit` fails to load assemblies in .NET Core on Linux

### ISSUE THREAD

**Issue by bgrainger** [xunit/xunit#1500]
Follow the instructions at https://xunit.github.io/docs/getting-started-dotnet-core to create a new xUnit.net project.

Add a reference to a NuGet package; I used [MySqlConnector](https://www.nuget.org/packages/MySqlConnector) (one of my own projects): `dotnet add package MySqlConnector`

Add a test that loads that assembly:

```
[Fact]
public void Test()
{
    using (new MySqlConnection())
    {
    }
}
```

Run `dotnet xunit`; it passes on Windows.

Now run the exact same command on .NET Core 2.0 on Linux. You can do this with Docker for Windows by running:

```
docker run -it --rm -v %cd%:/code microsoft/dotnet
# in container
cd code
dotnet restore
dotnet xunit
```

It fails with the following output:

```
Detecting target frameworks in XunitLoadAssembly.csproj...
Building for framework netcoreapp2.0...
  XunitLoadAssembly -> /code/bin/Debug/netcoreapp2.0/XunitLoadAssembly.dll
Running .NET Core 2.0.0 tests for framework netcoreapp2.0...
xUnit.net Console Runner (64-bit .NET Core 4.6.00001.0)
  Discovering: XunitLoadAssembly
  Discovered:  XunitLoadAssembly
  Starting:    XunitLoadAssembly
    XunitLoadAssembly.Class1.Test [FAIL]
      System.IO.FileNotFoundException : Could not load file or assembly 'MySqlConnector, Version=0.28.2.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

      ---- System.IO.FileNotFoundException : Could not load file or assembly 'MySqlConnector, Version=0.28.2.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

      Stack Trace:

        ----- Inner Stack Trace -----
           at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
           at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, IntPtr ptrLoadContextBinder)
           at System.Reflection.Assembly.Load(AssemblyName assemblyRef, IntPtr ptrLoadContextBinder)
           at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
           at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
           at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
  Finished:    XunitLoadAssembly
=== TEST EXECUTION SUMMARY ===
   XunitLoadAssembly  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 0.163s
```

Note that changing the references (for xunit and dotnet-xunit) to `2.3.0-beta5-build3769` makes `dotnet xunit` succeed, but `2.3.0-rc1-build3809` fails, so it appears the problem must have been introduced between Beta 5 and RC 1.

Repro code here: https://github.com/bgrainger/XunitLoadAssembly

Note that to work around this issue, I had to switch from `dotnet xunit` to `dotnet test` on my Travis CI builds in this commit: https://github.com/mysql-net/MySqlConnector/commit/a4f7f6c9fa988477a868e9931f4f5b49de4af48f

This issue may be the same as #1497.

**Comment by bgrainger** [comment]
Possibly the same as #1490.

**Comment by bgrainger** [comment]
Thanks!

**Comment by bgrainger** [comment]
Tested that this is working with `2.4.0-beta1-build3832` (from MyGet).

**Comment by bgrainger** [comment]
I still get the original problem in 2.3.1-rc1-build3843.

**Comment by bradwilson** [comment]
Dumbness on my part.

I copied ResolverUtils from CoreCLR to fix the bug the first time around, and then when I imported their source wholesale, it's the one file I deleted locally, but the bug is still in their 2.0.1 tree. 😠 

This will definitely be fixed in 2.3.1 RTM. You can test it right now with 2.4.0-beta1-build3844 from the CI feed.

![It works, I swear it does](https://user-images.githubusercontent.com/16944/31809977-e0b37254-b52e-11e7-84cb-7c4aa6a3e8a4.png)

**Comment by bradwilson** [comment]
I'm pushing `2.3.1-rc2-build3844` to NuGet right now.

**Comment by chris5287** [comment]
@bradwilson I can confirm `2.3.1-rc2-build3844` works with my docker builds :smile:

**Comment by bgrainger** [comment]
`2.3.1-rc2-build3844` is working for me: https://github.com/mysql-net/MySqlConnector/pull/366

👍
