### ISSUE TITLE
Code Coverage broken for .NETCore with xunit 2.3.0

### ISSUE THREAD

**Issue by smadala** [xunit/xunit#1501]
`Analyze Code Coverage for Selected Tests` in VS 15.5.0 Preview 2.0 broken for xUnit 2.3.0.
## Steps to reproduce
Create .NETCore xUnit project with following template.
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <DebugType>Full</DebugType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.5.0-preview-20171009-10" />
    <PackageReference Include="xunit" Version="2.3.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.0" />
  </ItemGroup>

</Project>
```
## Expected result
![expected_output](https://user-images.githubusercontent.com/4337332/31483792-87f4f40a-af4b-11e7-99a3-ea10c76d638e.png)

## Actual result
![actual_output](https://user-images.githubusercontent.com/4337332/31483800-8d6083fa-af4b-11e7-9a41-86d9ec5b48ac.png)

## Root Cause
Currently code coverage need Full pdb for .NETCore, Settings portable type [here](https://github.com/xunit/xunit/blob/6ef433fe9a45469a3763efd6e8188bb627c4ef10/src/xunit.core/build/xunit.core.targets#L7) always caused the issue.

## Workaround 
Downgrade xunit version to 2.3.0-beta5-build3769. 

## Proposed fix
Set DebugType only when it is not define?
/cc: @bradwilson @onovotny

**Comment by bradwilson** [comment]
Yeah, everything in the `.targets` file should probably be conditional. This was overlooked when I moved some things from `.props` to `.targets`.

**Comment by onovotny** [comment]
I disagree with this fix. full pdb's only work for Windows. xunit needs to work cross platform. the code coverage tools must be fixed to support portable and embedded pdb's.

**Comment by smadala** [comment]
@onovotny You are right, Code coverage should work with portable PDB. Tracking here https://github.com/Microsoft/vstest/issues/800 . This is not coming in 15.5. 

But having condition helps for scenarios which depends on PDB type.

**Comment by bradwilson** [comment]
In the end, I decided to only set `DebugType` conditionally, because the other things are absolutely required (for example, binding redirects generation in desktop CLR).

**Comment by bradwilson** [comment]
Also, last time I tried, the current profiling stuff in VS2017 didn't support .NET Core. It's running unconditionally with TPv1 which doesn't support it. So unless this was fixed in 15.4, this change isn't going to make you any happier.

**Comment by smadala** [comment]
It should work with above template mentioned in `Steps to reproduce` with VS 15.3 and with this fix.

**Comment by scastaldi** [comment]
I am using .netcore 2.4 and I was able to fix the issue by adding `<DebugType>Full</DebugType>`

```
  <PropertyGroup>
    <DebugType>Full</DebugType>
  </PropertyGroup>
```
