### ISSUE TITLE
Add analyzer for use of Linq within assertions

### ISSUE THREAD

**Issue by dougbu** [xunit/xunit#1504]
Linq expressions are often an indicator the user was unfamiliar with the available assertions. They also tend to make the assertions harder to read. Suggest adding an analyzer or analyzers (and fixer(s)) to cover some of the more obvious cases. (`Assert.Collection(...)` may be one of the few assertions that begs for Linq in its (first) argument.)

A couple of examples:
``` c#
Assert.NotNull(parameterDescriptors.Where(p => p.ParameterName == "firstName").FirstOrDefault());
...
Assert.Any(parameterDescriptors.Where(p => p.ParameterName == "firstName"));
...
Assert.Any(parameterDescriptors, p => p.ParameterName == "firstName");

IEnumerable<string> extensions = ...;
Assert.True(extensions.All(ext => ext.Length == 0));
...
Assert.All(extensions, ext => Assert.True(ext.Length == 0));
...
Assert.All(extensions, ext => Assert.Empty(ext));
```

**Comment by marcind** [comment]
This is an interesting suggestion but I'd be concerned about how complicated this can get given that linq expressions can be arbitrarily complex.

**Comment by dougbu** [comment]
@marcind I agree this _could_ get complicated.

Would there be sufficient value in handling a number of well-known cases where a Linq node is front-and-center e.g. `Assert.NotNull({expression}.FirstOrDefault())` and `Assert.Single({expression1}.Where({expression2})`? Complexity within the `{expression}`s shouldn't be relevant in these cases.

**Comment by marcind** [comment]
Yeah, my general rule is that there's value in an Assert analyzer if a) it helps write terser/more expressive code which b) produces more meaningful/detailed failure messages if failures do occur.

Could you open individual issues for the specific patterns to be analyzed? I'd see each of these implemented as their own analyzer, instead of having one big AllTheLinqAnalyzer.

**Comment by dougbu** [comment]
:ok:

**Comment by dougbu** [comment]
Split into three issues covering the examples listed above.
