### ISSUE TITLE
Avoid `AssertEqualShouldNotBeUsedForBoolLiteralCheck` false positives

### ISSUE THREAD

**Issue by dougbu** [xunit/xunit#1505]
This analyzer and associated fixer apply whenever the `true` or `false` literals are the first argument in an assertion. Unfortunately, that can lead to "fixes" which cause compilation errors.

For example, starting with
``` c#
var one = new object[] { true };
Assert.Equal(true, one[0]);
```
The analyzer will warn and the fixer will suggest
``` c#
Assert.True(one[0]);
```
That's not valid c# since `one[0]` is an `object` and not a `bool`.

The user could uglify this e.g.
``` c#
Assert.True(Assert.IsType<bool>(one[0]));
```
But the better workaround is
``` c#
Assert.Equal((object)true, one[0]);
```

Fix is to check the parameter types are both `bool`.

**Comment by bradwilson** [comment]
Shouldn't you be able to see that the `Assert.Equal` that's being called is actually `Assert.Equal<bool>`? Checking parameter types seems like overkill when the type is already right there as the implicit `T`. ;)

**Comment by dougbu** [comment]
@bradwilson sure, that would be simpler 😺
