### ISSUE TITLE
Do not emit xunit1026 warning when the parameter's type is used

### ISSUE THREAD

**Issue by dougbu** [xunit/xunit#1512]
Generic test methods don't need to reference a parameter to require its type. For example,
``` c#
[Theory]
[InlineData(false)]
[InlineData(0)]
[InlineData("")]
public void TheoryMethod<T>(T value)
{
    // ...
    Assert.Equal(default(T), (T)result);
}
```

Suggest `TheoryMethodShouldUseAllParameters` should not warn about the above case.

**Comment by marcind** [comment]
Do you have a different example of where this is causing problems? The provided example could probably be achieved with `Type`s and feels like too much of an edge case.

**Comment by dougbu** [comment]
@marcind ignoring `default(T)` and `nameof(T)`, the test could call generic parsing or input formatting methods that do not have `Type`-based (non-generic) overloads. [`JToken.Value<T>(...)`](https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_Linq_JToken_Value__1.htm) might be in this bucket. (I haven't searched the Json.NET API for `Type`-based alternatives.)

That said, I could understand treating this as an edge case, requiring the user to suppress the warning.

**Comment by marcind** [comment]
Yeah, until I see a solid example, I'm not convinced this should be handled.

N.B. `nameof(T)` would print just `T` for every single case, so not even worth considering.

**Comment by jnyrup** [comment]
Would the landscape has changed since the introduction of [discards](https://docs.microsoft.com/en-us/dotnet/csharp/discards)?

Example:
```c#
[Theory]
[InlineData(1)]
void Foo<T>(T a)
{
}
```

reports:
```
IDE0060	        Remove unused parameter 'a'
xUnit1026	Theory method 'Foo' on test class 'AsyncFunctionExceptionAssertionSpecs' does not use parameter 'a'.
```

after renaming the parameter `a` to `_`

```c#
[Theory]
[InlineData(1)]
void Foo<T>(T _)
{
}
```

reports:
```
xUnit1026	Theory method 'Foo' on test class 'AsyncFunctionExceptionAssertionSpecs' does not use parameter '_'.
```
