### ISSUE TITLE
Ease creating projections of shared data sets

### ISSUE THREAD

**Issue by dougbu** [xunit/xunit#1517]
As @marcind [mentions](https://github.com/xunit/xunit/issues/1513#issuecomment-336735772) in #1513, xUnit does not make it easy to create projections of shared data sets. Suggest xUnit reduce this friction.

When a single `TheoryData<T, ...>` property is shared between multiple `[Theory]` methods, it is certainly possible to create a projection e.g.
``` c#
    public static TheoryData<int, string> FullDataSet { get { ... }}
    public static TheoryData<string> SubDataSet
    [
        get
        {
                var dataSet = new TheoryData<string>();
                foreach (var item in FullDataSet )
                {
                    dataSet.Add((string)item[1]);
                }

                return dataSet;
        }
    ]
```
However the above is cumbersome, `xunit.analyzers` doesn't contain a fixer that will create such projections, and the workaround can get overwhelming when the shared data set needs multiple projections, test methods have multiple `[MemberData]` attributes, et cetera.

Worse, a simple projection may be insufficient when the result contains duplicates i.e. the removed column contributed to row uniqueness. That'll lead at least to warnings when affected tests run.

**Comment by dougbu** [comment]
One option, also [mentioned](https://github.com/xunit/xunit/issues/1513#issue-265405244) in #1513, would be to add a new `[IgnoreDataValue(int column)]` attribute. In the above example, it could be used like
``` c#
[Theory]
[MemberData(nameof(FullDataSet))]
[IgnoreDataValue(1)]    // 0 if user should consider the value index zero-based.
public void TestMethod(string parameter)
{
    // Do stuff
}
```

Not sure if such filtering can already be hooked into the test data discovery process. If this is doable, I suspect there are better names than `IgnoreDataValueAttribute` 😃

**Comment by bradwilson** [comment]
What happens if I write this:

```csharp
[Theory]
[MemberData(nameof(DataSet1))]
[MemberData(nameof(DataSet2))]
[IgnoreDataValue(1)]
public void TestMethod(string parameter)
{
    // Do stuff
}
```

Which data set contains the value I should ignore?

**Comment by dougbu** [comment]
@bradwilson both.

Then again, could add a `ProjectWithout` property or optional `projectWithout` constructor argument to `MemberDataAttribute`. That would remove data columns from the named data set property.

Even with that addition, `[IgnoreDataValue(...)]` could be useful when dealing with custom data set attributes. But, the new attribute might be secondary.

**Comment by bradwilson** [comment]
> @bradwilson both.

Yeah, that doesn't make sense to me. How do I ignore just one item from one of the data sets?

I don't like this API, for similar reasons why we made `Skip` a property on `[Fact]` instead of its own attribute. Having two related things in separate attributes is bad usability.

**Comment by dougbu** [comment]
@bradwilson that's fine. It was an API suggestion, not the core of the issue.

What do you think of adding a `ProjectWithout` (name to be improved 😃) property or similar?

**Comment by bradwilson** [comment]
After thinking about this, I'm disinclined to use this solution. I think it's clearer in the end user code when the projection is made via a second member rather than through attributes. It also centralizes the projection so that when the original data set changes, there is a single location to change the projection (instead of all the tests that depend on the projection).
