### ISSUE TITLE
Visual Studio Test Explorer does not discover tests (with paket)

### ISSUE THREAD

**Issue by pmiossec** [xunit/xunit#1521]
After hours on this problem and tested a lot of solution, I didn't found the way to solve it :(

Long time ago, on the project https://github.com/git-tfs/git-tfs, I successfully had tests discover working (I can't remember but it should be before version 2).

Since I updated, and with all the successive version (2.0, 2.1 and now 2.3), I never was able to make it work again.

```
[18/10/2017 00:08:35 Informational] ------ Discover test started ------
[18/10/2017 00:08:35 Informational] ========== Discover test finished: 0 found (0:00:00.1138154) ==========
```

* Problem reproduced on 2 different computers.
* With VS 2015 and 2017.
* The `xunit.runner.visualstudio` (https://github.com/git-tfs/git-tfs/blob/master/src/GitTfsTest/paket.references) which is well copied in the output directory.
* No exception are thrown in the "Test" output tab
* It works in the command line with `xunit.runner.console`
* It works with the ReSharper runner
* I have cleaned the %Temp% folder many times (or other files) like some solution asked to do it without effects

Does someone have an idea to solve it or at least some trick to debug that case?

I have tried [this solution](https://blogs.msdn.microsoft.com/aseemb/2012/03/01/how-to-enable-ute-logs/) but didn't had the expected log files. If you say me that it is the way to go, I will try to spend more time on it...

Note: If you want to build the solution, unload all the `GitTfs.Vs201x` projects (that should not build because it require dependencies) and keep only `GitTfs.Vs2015` (the dependencies are retrieved through nuget packages).

Thanks a lot in advance.

**Comment by bradwilson** [comment]
Paket has historically had problems with VSTest extensions, since the way they're discovered by Visual Studio requires them to have version numbers in their paths. Please see this issue for potential fixes:

https://github.com/fsprojects/Paket/issues/516#issuecomment-124248402

**Comment by pmiossec** [comment]
Thanks, it worked!

I didn't even imagine it could be a bad behavior due to paket. They have a doc on that behavior here: 
https://fsprojects.github.io/Paket/nuget-dependencies.html#Putting-the-version-number-in-the-path

Their is surely a (good?) reason that Visual Studio need the version in the path but that seems to me like a bad design...
