### ISSUE TITLE
Running xunit.runner.console in 2.3.0 while output directed to xml, on second run results in malformed xml

### ISSUE THREAD

**Issue by bone9820** [xunit/xunit#1522]
When running the console runner and output is directed to xml, the second and subsequent runs can result in malformed xml. It appears that the output has remaining information in the buffer and is writing that out.

Console params: 
xunit.console.exe C:\jenkins\workspace\cbh-common-lib\Lib.Measurement.Test\bin\Release\Lib.Measurement.Test.dll -xml C:\jenkins\workspace\cbh-common-lib\test_results\Lib.Measurement.Test.dll.xml

Below is a very simple project that runs just fine and tests just fine in the studio but when run through the console runner and output passes it results in the following;

`<?xml version="1.0" encoding="utf-8"?>
<assemblies timestamp="10/18/2017 12:42:03">
  <assembly name="C:\jenkins\workspace\cbh-common-lib\Lib.Measurement.Test\bin\Release\Lib.Measurement.Test.DLL" environment="64-bit .NET 4.0.30319.42000 [collection-per-class, parallel (2 threads)]" test-framework="xUnit.net 2.3.0.3820" run-date="2017-10-18" run-time="12:42:01" config-file="C:\jenkins\workspace\cbh-common-lib\packages\xunit.runner.console.2.3.0\tools\net452\xunit.console.exe.Config" total="18" passed="18" failed="0" skipped="0" time="1.277" errors="0">
    <errors />
    <collection total="9" passed="9" failed="0" skipped="0" name="Test collection for Lib.Measurement.Test.CheckpointTest" time="0.094">
      <test name="Lib.Measurement.Test.CheckpointTest.GetJournalTextTest" type="Lib.Measurement.Test.CheckpointTest" method="GetJournalTextTest" time="0.0895785" result="Pass" />
      <test name="Lib.Measurement.Test.CheckpointTest.ClassNameTest" type="Lib.Measurement.Test.CheckpointTest" method="ClassNameTest" time="0.0004318" result="Pass" />
      <test name="Lib.Measurement.Test.CheckpointTest.SubeventNameTest" type="Lib.Measurement.Test.CheckpointTest" method="SubeventNameTest" time="0.0006284" result="Pass" />
      <test name="Lib.Measurement.Test.CheckpointTest.ApplicationNameTest" type="Lib.Measurement.Test.CheckpointTest" method="ApplicationNameTest" time="0.0004804" result="Pass" />
      <test name="Lib.Measurement.Test.CheckpointTest.ProjectNameTest" type="Lib.Measurement.Test.CheckpointTest" method="ProjectNameTest" time="0.00039" result="Pass" />
      <test name="Lib.Measurement.Test.CheckpointTest.OffsetTest" type="Lib.Measurement.Test.CheckpointTest" method="OffsetTest" time="0.000705" result="Pass" />
      <test name="Lib.Measurement.Test.CheckpointTest.EventNameTest" type="Lib.Measurement.Test.CheckpointTest" method="EventNameTest" time="0.0003461" result="Pass" />
      <test name="Lib.Measurement.Test.CheckpointTest.CheckpointConstructorTest" type="Lib.Measurement.Test.CheckpointTest" method="CheckpointConstructorTest" time="0.0003647" result="Pass" />
      <test name="Lib.Measurement.Test.CheckpointTest.ProcessStartTimeTest" type="Lib.Measurement.Test.CheckpointTest" method="ProcessStartTimeTest" time="0.0007421" result="Pass" />
    </collection>
    <collection total="9" passed="9" failed="0" skipped="0" name="Test collection for Lib.Measurement.Test.CodeTimerTest" time="1.137">
      <test name="Lib.Measurement.Test.CodeTimerTest.FailTimerTest" type="Lib.Measurement.Test.CodeTimerTest" method="FailTimerTest" time="0.1287063" result="Pass" />
      <test name="Lib.Measurement.Test.CodeTimerTest.StartTimerTest" type="Lib.Measurement.Test.CodeTimerTest" method="StartTimerTest" time="1.0028721" result="Pass" />
      <test name="Lib.Measurement.Test.CodeTimerTest.StopTimerTest" type="Lib.Measurement.Test.CodeTimerTest" method="StopTimerTest" time="0.0008179" result="Pass" />
      <test name="Lib.Measurement.Test.CodeTimerTest.StartedTest" type="Lib.Measurement.Test.CodeTimerTest" method="StartedTest" time="0.0008823" result="Pass" />
      <test name="Lib.Measurement.Test.CodeTimerTest.TimerDisposeTest" type="Lib.Measurement.Test.CodeTimerTest" method="TimerDisposeTest" time="0.0007236" result="Pass" />
      <test name="Lib.Measurement.Test.CodeTimerTest.TimerConstructorTest" type="Lib.Measurement.Test.CodeTimerTest" method="TimerConstructorTest" time="0.0006924" result="Pass" />
      <test name="Lib.Measurement.Test.CodeTimerTest.TimerEventTest" type="Lib.Measurement.Test.CodeTimerTest" method="TimerEventTest" time="0.0003904" result="Pass" />
      <test name="Lib.Measurement.Test.CodeTimerTest.GetJournalTextTest" type="Lib.Measurement.Test.CodeTimerTest" method="GetJournalTextTest" time="0.0010745" result="Pass" />
      <test name="Lib.Measurement.Test.CodeTimerTest.RunningTest" type="Lib.Measurement.Test.CodeTimerTest" method="RunningTest" time="0.0010809" result="Pass" />
    </collection>
  </assembly>
</assemblies>es>`

As you can see on the last line it gets an extra "es>" stuffed in there. I have also seen it where you get more of the word assemblies. The current work around is to simply delete the existing file prior to run.

https://github.com/bone9820/xunit-error

**Comment by bone9820** [comment]
@bradwilson why was this just closed?

**Comment by bradwilson** [comment]
Did you click [the link](https://github.com/xunit/xunit/commit/25678ba1b971e52e611386a9966fd99fb7efe1a2) in the closure message? 😸

**Comment by bone9820** [comment]
Stupid me, my browser didn't highlight the link where I saw it. Thanks!
