### ISSUE TITLE
Is there a API to short UT names at class level?

### ISSUE THREAD

**Issue by heku** [xunit/xunit#1523]
Hi,

I'd like there's a API like below to short the test method names at class level, not method level.
```csharp
namespace abc.def {
    [Name("short")]
    class xyz {
        [Fact]
        public void unittest () {}
    }
}
```
Then in the unit test explorer, it is displayed as `short.unittest`  rather than `abc.def.xyz.unittest`.

Any idea?

**Comment by bradwilson** [comment]
There is no such capability today.

**Comment by heku** [comment]
So do you have a plan to add this?

**Comment by bradwilson** [comment]
Dup of #1429
