### ISSUE TITLE
xunit VisualStudio runner debug failure

### ISSUE THREAD

**Issue by MOGitStuff** [xunit/xunit#1532]
I am observing failure with xUnit 2.3.0 and VisualStudio 2015 update 3.

I was able to reproduce the failure in new .NET Framework 4.7.1 project with a single Assert statement.  NuGet was used to add both xunit 2.3.0 and xunit.runner.visualstudio 2.3.0

I am running on a Windows 10 machine (Windows Version 1703, OS Build 15063.483)

From the Test Explorer window, Debug Selected Test produces a failure due missing assemblies.
  could not find dependent assembly 'Microsoft.Extensions.DependencyModel, Version=1.1.0'
  Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.1.0.0

The error content is attached:
[xUnitRunnerErrror.log](https://github.com/xunit/xunit/files/1416011/xUnitRunnerErrror.log)

The trivial project I used to illustrate this behavior is accessible at:
https://github.com/MOGitStuff/MO_xUnit

I have not observed this failure prior to recent updates.

Please advise if I am overlooking something.

**Comment by bradwilson** [comment]
This does not reproduce in VS 2017:

![VS 2017 15.4.1](https://user-images.githubusercontent.com/16944/32033234-41c31f50-b9c0-11e7-8ffa-40b3f19333e8.png)

I don't have a copy of VS 2015 handy at the moment.

Does the problem reproduce if you use an older version of .NET? It may be possible that the version of VSTest inside of VS 2015 does not support .NET 4.7.1. Those DLLs you've mentioned are not part of the desktop CLR, nor are they loadable from the GAC; in fact, I don't understand how you have references to them at all.

Out of curiosity, have you tried 2.3.1 RC 2?

**Comment by MOGitStuff** [comment]
2.3.1 RC 2 seems to bring resolution.  

Unfortunately, it is problematic to deploy anything less than a full release version in our work environment (it is a Quality process thing ...).  But knowing there is a solution in the near future is good enough for now.

Thanks for looking into this.
