### ISSUE TITLE
System.Reflection.TargetParameterCountException: Parameter count mismatch. VS2017 and XUNIT 2.3.1

### ISSUE THREAD

**Issue by sborghini** [xunit/xunit#1539]
Hello
i'm creating a VS 2017 Unit test project in order to check my .NET Framework 4.7 development.

I added XUNIT 2.3.1 to my test project and, when i'm trying to use it, i always receive the following error
System.Reflection.TargetParameterCountException: Parameter count mismatch

Here my test method declaration: 
[TestMethod]
[Theory]        
[InlineData(1)]        
public void testMethod(int value)

This error make me crazy :)
Someone can help me?

**Comment by marcind** [comment]
What is `[TestMethod]` doing there? That's not an xUnit attribute. You're likely executing the test both in xUnit and MSTest.

**Comment by sborghini** [comment]
I added XUNIT NuGet package to an MS Unit Test project because i'm working with .NET Framework 4.7 and , if i understood well, XUNIT native test project are .NET Core.

**Comment by marcind** [comment]
Xunit supports both .Net Core and .Net Framework 4.7

**Comment by bradwilson** [comment]
The compatibility grid shows what is supported: https://xunit.github.io/#runners

**Comment by bradwilson** [comment]
Please re-open with a repro project.

**Comment by nasskov** [comment]
The problem here is that method expects argument, and no arguments are provided in the attributes, therefore is this exception. 
I recommend this case to be checked and handled properly, instead of hitting reflection exception, which is quite puzzling :)
