### ISSUE TITLE
ITestOutputHelper throws exception incorrectly claiming "There is no currently active test"

### ISSUE THREAD

**Issue by iremolmezses** [xunit/xunit#1540]
When running all tests that use ITestOutputHelper together, an InvalidOperationException is thrown by xunit as shown below.

![image](https://user-images.githubusercontent.com/20420478/32235745-9997e360-be60-11e7-838f-95cd72c51595.png)

Strangely, when these tests are run separately, they are passing with expected logs.

Any idea why it’s claiming that there is no active test as call stack clearly shows it?

**Comment by bradwilson** [comment]
Please provide a repro project.

**Comment by bradwilson** [comment]
Please re-open with a repro project.

**Comment by alexsorokoletov** [comment]
I think the repro can be found here - https://github.com/tmenier/Flurl/issues/375 
Somehow async init of Flurl breaks xunit tests with the exactly same error inside.

**Comment by bradwilson** [comment]
I don't know what HttpTest is, but the error there looks suspiciously like an inappropriate use of thread local storage (which is incompatible with async/await).

**Comment by alexsorokoletov** [comment]
wow :) that was fast @bradwilson 
Maybe it is something inside HttpTest, though it also says the HttpTest is using AsyncLocal so it should be all good.

Wanted to explain my though on that but then ... anyway.

I have two collections of tests.
One does not have any class fixtures, just plain class with like 1 test.
Simple http call with Flurl.

Another one has IClassFixture with IAsyncLifetime.
In that async lifetime I do some http calls with Flurl as well.

When both collections run in parallel, I get that error that the Flurl call failed and the inner exception is actually coming from xUnit saying there is no active test. I traced the exception back to the ITestOutputHelper https://github.com/xunit/xunit/blob/master/src/xunit.execution/Sdk/Frameworks/TestOutputHelper.cs#L51

I was wondering whether I am missing something inside the IAsyncLifetime to properly initialize that before I start using it inside IAsyncLifetime (Flurl uses it to trace calls).

**Comment by zenlambda** [comment]
The following error is raised when tests are run together with ITestOutputHelper capturing Console output.

    Error Message:
    System.InvalidOperationException : There is no currently active test.

You can find a reproducer project here:

https://github.com/zenlambda-testcases/xunit-consoleout

I think it is related to the code-under-test writing multiple lines to Console.WriteLine().

**Comment by vorou** [comment]
Facing the same issue, is the repro from @zenlambda enough to re-open and investigate this?

**Comment by bradwilson** [comment]
@vorou The problem is @zenlambda's code has a fatal bug. It overrides the global `Console` output stream in the `TestBase` constructor, but it does not restore it. So as soon as something tries to write to the console after the test is done, the `Converter` class tries to intercept it and write the output into the `ITestOutputHelper`, which is no longer valid. `TestBase` needs to implement `IDisposable` and in the `Dispose` method, it needs to clean up after itself so it's no longer intercepting the global console stream.
