### ISSUE TITLE
Assert.DoesNotContain analyzer misses negated form

### ISSUE THREAD

**Issue by sharwell** [xunit/xunit#1544]
### Steps to reproduce

```
Assert.False(m_visited.Contains(template));
Assert.True(!m_visited.Contains(template));
```

### Expected results

`Assert.DoesNotContain` is suggested for both of the above forms.

### Actual results

`Assert.DoesNotContain` is only suggested for the first form.

**Comment by marcind** [comment]
My initial reaction is that it would be better if there was an analyzer that inverts `Assert.True` <-> `Assert.False` when a negation is present. It would get you to the desired result in 2 fix-ups, but the first one would be more generic and would help in other situations.

**Comment by bradwilson** [comment]
Closing this because #1435 will get you there now.
