### ISSUE TITLE
Request specialized exception filter on Assert.Throws and variants

### ISSUE THREAD

**Issue by mwpowellhtx** [xunit/xunit#1547]
Would it be difficult to provide something like this:

```C#
public static delegate bool ExceptionFilter<T>(T ex)
    where T : Exception;
```

```C#
public static T Throws<T>(Action testCode, ExceptionFilter<T> filter = null)
    where T : Exception
{
    // Default always accepts the Exception of type T when thrown.
    filter = filter ?? (x => true);
    // ...
}
```

Or perhaps even with default arguments, if .NET/C# version is not an issue.

And API permutations. Basically, where ever an exception can be thrown (or not), etc.

For now I plan on working around it via internal extension methods, but something like this would be grand!

Thank you!

**Comment by bradwilson** [comment]
I'm not clear how this is any better than just writing a second conditional assertion.

**Comment by mwpowellhtx** [comment]
Come again? I'm vaguely familiar with conditional catch statements. Is the same sort of thing possible using ``Assert.Throws``?

**Comment by bradwilson** [comment]
Let me phrase it another way: show me how you would use this requested feature.

**Comment by mwpowellhtx** [comment]
Simply this:

```C#
Assert.Throws<MyException>(() => { /* ... */ }, (MyException ex) => ex.ErrorCode == AnErrorCode);
```
I included the type in the filter lambda for illustrative purposes.

**Comment by mwpowellhtx** [comment]
Whose implementation itself would be really simple, using C# 6.0 exception filters as you said.

```C#
try
{
    action();
}
catch (T ex) when (filter(ex))
{
    // Success. Everything else is a failure.
}
```

Even if you didn't have that, it wouldn't be terrible, methinks.

And variants.

**Comment by marcind** [comment]
You can do
```c#
var ex = Assert.Throws<MyException>(() => { /* ... */ });
Assert.Equal(AnErrorCode, ex.ErrorCode)
```

**Comment by mwpowellhtx** [comment]
Actually, I cooked up a simple prototype:

```C#
public static class Exceptions
{
    public delegate bool ExceptionFilter<in T>(T ex)
        where T : Exception;

    public static void Thrown<T>(Action action, ExceptionFilter<T> filter)
        where T : Exception
    {
        try
        {
            action();
        }
        catch (T ex) when (filter(ex))
        {
            // Success. Everything else is a failure.
        }
    }
}
```

**Comment by mwpowellhtx** [comment]
Which in practice works famously well.

**Comment by bradwilson** [comment]
I'm with Marcin. I have no motivation to do this, because the two asserts are clearer.

**Comment by mwpowellhtx** [comment]
I was unaware Throws actually returns the exception. This would be a simpler approach then. What I'm really after as a one-liner, even with syntactic sugar. It's just easier to reason about.

```C#
public delegate bool ExceptionFilter<in T>(T ex)
    where T : Exception;

public static void Matching<T>(this T ex, Expression<ExceptionFilter<T>> filterExpr)
    where T : Exception
{
    var filter = filterExpr.Compile();
    Assert.True(filter(ex), $"Expected exception {typeof(T)} to be thrown but was not. Using filter: {filterExpr.Body}");
}
```

**Comment by marcind** [comment]
I'm having a hard time getting over the fact that whether (and what) exception filter is used inside the method under test is an implementation detail that shouldn't necessarily be repeated in the test code.

Note that you can write your own assertion helpers (either as an arbitrary method, or as part of the `Assert` class if you import [`xunit.assert` as source](https://www.nuget.org/packages/xunit.assert.source/)) if you want to.

**Comment by mwpowellhtx** [comment]
@marcind Really, I don't know what you're talking about. In this case, there are details about the exception that are expected under different conditions. So we want to test for those specifically. Not just that the exception was thrown.

In practice, this looks like this, a one liner, which is really what I'm after.

```C#
using static ErrorCode;
// ...
Assert.Throws<NanoException>(() => s.DoSomethingExceptional())
  .Matching(ex => ex.ErrorCode.ToErrorCode() == TimedOut);
```

Along these lines.

Notice ``Throws`` actually returns the exception. Additionally, since I can leverage ``Expression``, I can get a more meaningful error report should the condition fail for whatever reason.

Cheers.
