### ISSUE TITLE
-nunit and -html support on .NET Core 2+

### ISSUE THREAD

**Issue by mattzink** [xunit/xunit#1551]
.NET Core 2.0.0
xUnit 2.3.1

When passing `-nunit` or `-html` options to xunit.runner.console the following message is given:
```
Skipping -html because XSL-T is not supported on .NET Core
Skipping -nunit because XSL-T is not supported on .NET Core
```

XSL transforms **are** supported as of .NET Core 2.0 (see https://github.com/dotnet/corefx/issues/5593#issuecomment-287465072), so I believe this functionality could be re-enabled

**Comment by mattzink** [comment]
Just noticed that @nguerrera just submitted PR https://github.com/xunit/xunit/pull/1550 to do just this, so you can use this issue to track it or feel free to close

**Comment by bradwilson** [comment]
Merged.
