### ISSUE TITLE
`xunit` nuget package can no longer be included transitively

### ISSUE THREAD

**Issue by andycmaj** [xunit/xunit#1553]
## Symptom

```bash
$ dotnet xunit                                     
Detecting target frameworks in ImsHealth.WorkflowFramework.Tests.csproj...
/Workspace/ims/TheChunnel/test/ImsHealth.WorkflowFramework.Tests/ImsHealth.WorkflowFramework.Tests.csproj : error MSB4057: The target "_Xunit_GetTargetFrameworks" does not exist in the project.
Detection failed! Please ensure you're using 'xunit.core' v2.3 beta 2 or later.
```

## Description

I expected `xunit` package reference to work transitively. I have a `TestCommon` project that's referenced by all actual test projects, and includes all nuget test dependencies.

at `xunit` version `2.3.0-*`, this worked fine (ie I didn't need to include an `xunit` nuget package reference directly in my test projects.

after updating to `2.3.1`, i noticed this stopped working, and showed error message above about missing msbuild target.

adding the `xunit@2.3.1` package reference directly to test projects seems to work.

I'm wondering if this is related to https://github.com/xunit/xunit/issues/1369, but basically the root cause is that now, xunit core package seems to include some msbuild targets, which apparently do not work as transient package references.

## Repro

Using repo https://github.com/andycmaj/xunit-transient-reference-bug.

1. checkout https://github.com/andycmaj/xunit-transient-reference-bug/commit/87521fd63fca84bab506a3329270267f030d4410
1. run `dotnet restore` in `/testproject`
1. run `dotnet xunit` in `/testproject`

expect:
successful test run

actual:
```
/Workspace/ims/TheChunnel/test/ImsHealth.WorkflowFramework.Tests/ImsHealth.WorkflowFramework.Tests.csproj : error MSB4057: The target "_Xunit_GetTargetFrameworks" does not exist in the project.
Detection failed! Please ensure you're using 'xunit.core' v2.3 beta 2 or later.
```

to fix, follow this repro
1. checkout (or make same change as) https://github.com/andycmaj/xunit-transient-reference-bug/commit/f9a5308c1fcf3a491c1f722eec1b47e0080b6694
1. run `dotnet restore` in `/testproject`
1. run `dotnet xunit` in `/testproject`

expect:
successful test run

actual:
works as expected

**Comment by bradwilson** [comment]
> I expected xunit package reference to work transitively.

This is not a supported scenario for us. Unfortunately, there's no way for us to inject the things we need into your .csproj unless you are pulling in the package directly.

**Comment by andycmaj** [comment]
understood, and that's fine (using Directory.Build.props actually works
fine), but also calling out that this is a breaking change in a minor
version increment :shrug:

might want to think about version numbers or at least documenting...

thanks for looking.

**Comment by bradwilson** [comment]
> this is a breaking change in a minor version increment

We don't follow SemVer.

**Comment by bradwilson** [comment]
> might want to think about version numbers or at least documenting...

We'll see if it comes up. My guess is you're doing something fairly unusual.

**Comment by dtabuenc** [comment]
Trying to maintain consistent versioning across many projects by having a single meta-package such as MyCompany.Common.Testing that then brings in other dependencies transitively does not seem something that's fairly unusual.
