### ISSUE TITLE
Is it possible to get error code when using netcoreapp2.0 console runner directly?

### ISSUE THREAD

**Issue by kasper3** [xunit/xunit#1554]
I have multiple steps build configuration in CI, where one step builds projects and publish artifacts for the next one.
The next step has no access to sources but only whatever was in bin directory of project.

Step 1
```
nuget restore
msbuild /t:Build /p:stuff..

xcopy bin_dir to_artifacts # for later use
```

Now i have bit of unconventional way to run the test in CI:

Step 2 (i have no project/sources at this point, just assemblies and binaries)
```
nuget install xunit.runner.console -version 2.3.0

dotnet  xunit.runner.console.2.3.0/tools/netcoreapp2.0/xunit.console.dll  path_to_artifact_test.dll
```

It runs all the tests but even if any test fail, the exit code is always 0 and hence the CI builds are always green.

Compare this with non dotnet core runner:

```
nuget install xunit.runner.console -version 2.3.0

xunit.runner.console.2.3.0/tools/net452/xunit.console.exe path_to_artifact_test.dll
```

where we don't need `dotnet` runner. If tests fail, the process exists with non-zero error code. **this is what i want with netcoreapp2.0 variant**

Third option is perhaps using `nuget install dotnet-xunit -version 2.3.0`, which gives a bizarre error at install time:

```Package 'dotnet-xunit 2.3.0' has a package type 'DotnetCliTool' that is not supported by project```

meaning it requires project context to get installed (which i don't have in Step 2 mentioned above)

Question:
##### Is there any way to fail the process with non-zero error when using `dotnet  xunit.runner.console.2.3.0/tools/netcoreapp2.0/xunit.console.dll     myproj.dll`?

**Comment by bradwilson** [comment]
This is working as expected for me:

![image](https://user-images.githubusercontent.com/16944/32420497-07626a7c-c240-11e7-9619-b37ffee49386.png)

**Comment by kasper3** [comment]
You are right Brad, something was messed up in my ci that was causing it (script had it's own stub with exit code). Thanks for the inputs!
