### ISSUE TITLE
Resources from Resx ignore current culture when running with xUnit

### ISSUE THREAD

**Issue by GeorgDangl** [xunit/xunit#1555]
[The repro project is available here](https://github.com/GeorgDangl/xUnitCultureTests). I've noticed that due to a regression when my CI environment reported failing tests after an upgrade from `2.3.0-beta3-build3705` to `2.3.1`.

The tests work fine in the full .Net framework, only `netcoreapp` is failing.

I've defined three resource files, `Resource.resx`, `Resource.de.resx` and `Resource.fr.resx`, all contain a string `Greeting`.

Then I have these tests:

    [Fact]
    public void CheckGermanCulture()
    {
        var expected = "Guten Tag";
        var actual = GetResourceWithCulture("de");
        Assert.Equal(expected, actual);
    }

     [Fact]
    public void CheckFrenchCulture()
    {
        var expected = "Bonjour";
        var actual = GetResourceWithCulture("fr");
        Assert.Equal(expected, actual);
    }

    private string GetResourceWithCulture(string cultureName)
    {
        var culture = new CultureInfo(cultureName);
        CultureInfo.CurrentCulture = culture;
        CultureInfo.CurrentUICulture = culture;
        var resource = Resource.Greeting;
        return resource;
    }

The tests pass in `dotnet test` but fail with `dotnet xunit`. I'm currently using xUnit 2.3.1.

Here's the output:

## Output with xUnit

`dotnet xunit`

    Detecting target frameworks in xUnitCulture.csproj...
    Building for framework netcoreapp2.0...
      xUnitCulture -> C:\Users\Georg\Desktop\xUnitCulture\bin\Debug\netcoreapp2.0\xUnitCulture.dll
    Running .NET Core 2.0.0 tests for framework netcoreapp2.0...
    xUnit.net Console Runner (64-bit .NET Core 4.6.00001.0)
      Discovering: xUnitCulture
      Discovered:  xUnitCulture
      Starting:    xUnitCulture
        xUnitCulture.UnitTest1.CheckGermanCulture [FAIL]
          Assert.Equal() Failure
                    ↓ (pos 0)
          Expected: Guten Tag
          Actual:   Hello
                    ↑ (pos 0)
          Stack Trace:
            C:\Users\Georg\Desktop\xUnitCulture\UnitTest1.cs(14,0): at xUnitCulture.UnitTest1.CheckGermanCulture()
        xUnitCulture.UnitTest1.CheckFrenchCulture [FAIL]
          Assert.Equal() Failure
                    ↓ (pos 0)
          Expected: Bonjour
          Actual:   Hello
                    ↑ (pos 0)
          Stack Trace:
            C:\Users\Georg\Desktop\xUnitCulture\UnitTest1.cs(22,0): at xUnitCulture.UnitTest1.CheckFrenchCulture()
      Finished:    xUnitCulture
    === TEST EXECUTION SUMMARY ===
       xUnitCulture  Total: 2, Errors: 0, Failed: 2, Skipped: 0, Time: 0,153s

## Output with dotnet test

`dotnet test`

    Build started, please wait...
    Build completed.
    
    Test run for C:\Users\Georg\Desktop\xUnitCulture\bin\Debug\netcoreapp2.0\xUnitCulture.dll(.NETCoreApp,Version=v2.0)
    Microsoft (R) Testausführungs-Befehlszeilentool Version 15.3.0-preview-20170628-02
    Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.
    
    Die Testausführung wird gestartet, bitte warten...
    [xUnit.net 00:00:00.3232283]   Discovering: xUnitCulture
    [xUnit.net 00:00:00.3934721]   Discovered:  xUnitCulture
    [xUnit.net 00:00:00.3976951]   Starting:    xUnitCulture
    [xUnit.net 00:00:00.5044358]   Finished:    xUnitCulture
    
    Tests gesamt: 2. Bestanden: 2. Fehler: 0. Übersprungen: 0.
    Der Testlauf war erfolgreich.
    Testausführungszeit: 0,9478 Sekunden

**Comment by bradwilson** [comment]
Verified fixed with 2.4.0-beta1-build3897:

![image](https://user-images.githubusercontent.com/16944/34452235-ace6a6c8-ecef-11e7-8184-a0d34d74d024.png)

**Comment by GeorgDangl** [comment]
Can confirm it's working, I've updated [the repro project](https://github.com/GeorgDangl/xUnitCultureTests). Thanks a lot!
