### ISSUE TITLE
error CS0012: The type 'ValueType' is defined in an assembly that is not referenced.

### ISSUE THREAD

**Issue by GerjanOnline** [xunit/xunit#1560]
I'm getting the following error on my build machine (TeamCity):

```
error CS0012: The type 'ValueType' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. 
```

On my dev machine it "just works"

Unit Test project:

```
  <package id="xunit" version="2.3.1" targetFramework="net461" />
  <package id="xunit.abstractions" version="2.0.1" targetFramework="net461" />
  <package id="xunit.analyzers" version="0.7.0" targetFramework="net461" />
  <package id="xunit.assert" version="2.3.1" targetFramework="net461" />
  <package id="xunit.core" version="2.3.1" targetFramework="net461" />
  <package id="xunit.extensibility.core" version="2.3.1" targetFramework="net461" />
  <package id="xunit.extensibility.execution" version="2.3.1" targetFramework="net461" />
  <package id="xunit.runner.console" version="2.3.1" targetFramework="net461" developmentDependency="true" />
  <package id="xunit.runner.visualstudio" version="2.3.1" targetFramework="net461" developmentDependency="true" />
```

![image](https://user-images.githubusercontent.com/1153419/32490423-749c9dd2-c3b3-11e7-98a3-8e88d784b37e.png)

**Comment by bradwilson** [comment]
> On my dev machine it "just works"

We're probably not going to be able to help with this if you can't find a consistent repro. You're going to need to figure out what's different between your dev machine and the CI machine.

**Comment by marcind** [comment]
Also, there's nothing in your bug report that indicates how this is related to xUnit. More detail and information is necessary.

**Comment by bradwilson** [comment]
Please re-open with a repro project.

**Comment by quasarea** [comment]
I think it is due to xunit targeting netstandard, and us consuming it in 4.6.1

See:
* https://stackoverflow.com/questions/44652434/type-object-is-defined-in-an-assembly-that-is-not-referenced-net-standard-2-0
* https://github.com/dotnet/standard/issues/542

I managed to overcome it adding ".Net Core build tools" workload to my visual studio 2017 build tools
