### ISSUE TITLE
Autofixture's AutoDataAttribute makes xunit's analyzers unhappy

### ISSUE THREAD

**Issue by bitbonk** [xunit/xunit#1569]
[Autofixture's AutoDataAttribute](https://github.com/AutoFixture/AutoFixture/wiki/Cheat-Sheet#autodata-theories) makes xunit's analyzers complain.

The following code

```c#
[Theory, AutoData]
public void Test(int primitiveValue, string text)
{
}
```

yields the following analyzer error: [xUnit1003: Theory methods must have test data](https://xunit.github.io/xunit.analyzers/rules/xUnit1003.html) 

It should not complain because the test data is coming from the `AutoDataAttribute`.

**Comment by marcind** [comment]
Figure out why an attribute derived from DataAttribute is not satisfying the rule. Potentially add the signature of https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture.xUnit.net2/AutoDataAttribute.cs to the permit-list.

**Comment by tparikka** [comment]
I ran into a similar issue with the `AutoMoqData` attribute; is it close enough that a code sample from me would be useful or is this issue already well enough understood?

**Comment by bradwilson** [comment]
@tparikka It couldn't hurt! 😄

**Comment by tparikka** [comment]
I went looking for that project and loaded it up, and now the analyzers aren't complaining 🤷‍♀️ If I see it come up again I'll throw a gist or repo link here.

**Comment by bradwilson** [comment]
I'm unable to repro this on `1.2.0-pre.36`, so I'm assuming this has already been fixed and closing the issue. Please let me know if you can still repro on the latest prerelease build.
