### ISSUE TITLE
Consider failing tests when background threads terminate with unhandled exceptions

### ISSUE THREAD

**Issue by davidmatson** [xunit/xunit#157]
This might make a better discussion than an issue, but I'm not sure how to do that in GitHub (let me know if there's a better place to put this.)

The way xUnit.net behaves using the VS test runner combines a bit oddly with the debugger when background threads have unhandled exceptions.

For example, consider the following test:

``` c#
[Fact]
public void TestExceptionInBackgroundThread()
{
    Thread t = new Thread(() => { throw new InvalidOperationException(); });
    t.Start();
    t.Join();
}
```

This test passes. However, if the test is executed under the debugger, VS won't let the test finish because there's an unhandled exception. (It will keep highlighting the line "throw new InvalidOperationException();" no matter how many times you hit F5.)

It's weird to have a test that passes with right-click Run but hangs with right-click Debug.

Here's another test that passes. It would be nice if somehow this problem were reported when the test runner executes:

``` c#
[Fact]
public void TestHungBackgroundThread()
{
    Thread t = new Thread(() => { Thread.Sleep(Timeout.Infinite); });
    t.Start();
}
```

Is there any good option for handling either of these two tests differently?

One possible approach for the first case:
Hook AppDomain.CurrentDomain.UnhandledException and cause any currently executing test to fail if e.IsTerminating is true.

I don't currently have a suggestion for the second case.

**Comment by bradwilson** [comment]
Does not appear to be anything we can do about this.

**Comment by ashelleyPurdue** [comment]
Please reconsider marking this "won't fix".  I have a ton of tests that are incorrectly passing.

Even if you can't stop the process from crashing, *at least* don't let it be reported as a success!  I would rather my IDE crash horrifically, if it means I get informed when things go wrong.  That's the whole point of a test framework, is it not?

**Comment by bradwilson** [comment]
As previously mentioned, there's nothing that we can do about this. It's outside of our control.

**Comment by ashelleyPurdue** [comment]
Sorry, I should have been more clear(and civil).

You said there's nothing you can do to catch the exception without letting the process crash.
> On second thought, there appears to be nothing we can do to stop the runaway exception (there's no way to prevent the process from crashing)

I think you should let the process crash *anyway*, so that way you at least know something is wrong.

**Comment by bradwilson** [comment]
You're asking us not to do anything, but that's already what we're doing. We can't force the process to crash because Visual Studio is what's stopping it, not us.

**Comment by ashelleyPurdue** [comment]
Hmm, well it's not crashing when I run "dotnet test".  It just ignores the exception and lets the test pass.

**Comment by bradwilson** [comment]
I'm not sure if you think you're disagreeing with me, because you're not. The VSTest engine--which is what powers both `dotnet test` and Visual Studio's Test Explorer--is catching the unhandled exception and ignoring it. Your complaint is with them, not us.

**Comment by ashelleyPurdue** [comment]
OK, I think I understand now.  Thanks for clarifying!
