### ISSUE TITLE
Allow passing typeof(SomeType) to attributes instead of class name and assembly name.

### ISSUE THREAD

**Issue by eriksunsol** [xunit/xunit#1572]
There are a few Attributes whose constructors require the name of a type and the name of the containing assembly (e.g. `CollectionBehaviorAttribute(string factoryTypeName, string factoryAssemblyName)`, `TestCaseOrdererAttribute(string ordererTypeName, string ordererAssemblyName)`, `TestCollectionOrdererAttribute(string ordererTypeName, string ordererAssemblyName)`, `TestFrameworkAttribute(string typeName, string assemblyName)`).

Is there any reason not to add constructors to these that accept the type directly?

At least for `TestCaseOrdererAttribute` and `TestCollectionOrdererAttribute` it seems likely that whenever they are used the assembly of the type referred to is referenced by the test project anyway which means the type will be available. I'd rather have the compiler complain than scratching my head trying to figure out why my test cases run in the wrong order when there is a typo in the class name or assembly name. Better for refactoring too.

**Comment by bradwilson** [comment]
Yes, `typeof` support can be added, with the following caveat: when using `typeof` from an assembly which has been decorated with [`PlatformSpecificAssemblyAttribute`](https://github.com/xunit/xunit/blob/master/src/xunit.core/Sdk/PlatformSpecificAssemblyAttribute.cs), then the generated assembly name string must be correctly munged. For example, if the assembly in question is called `foo.bar.desktop.dll` when this discovery happens, the resulting assembly name string should be `foo.bar.{Platform}`.

**Comment by Grompot77** [comment]
I also see this as an enhancement as another constructor overload.  Just moved from MSTest to XUnit to do ordering for integration type testing and found TestCaseOrdererAttribute lacking the typeof(T) overload, and personally I hate to hardcode anything.

**Comment by bradwilson** [comment]
@Grompot77 If you look at the source, you'll notice the attributes don't actually store the constructor arguments: https://github.com/xunit/xunit/blob/cbf28f6d911747fc2bcd64b6f57663aecac91a4c/src/xunit.core/TestCaseOrdererAttribute.cs#L17

The arguments are extracted via reflection. Support for adding a `Type` constructor involves updating the reflection code to support this alternative signature: https://github.com/xunit/xunit/blob/cbf28f6d911747fc2bcd64b6f57663aecac91a4c/src/xunit.execution/Sdk/ExtensibilityPointFactory.cs#L109-L123

It's done this way to support source-based discovery. We cannot run code (or even count on the code being in a compilable state) so reflection abstractions are used instead.

**Comment by pmunin** [comment]
Who was the genius that decided to **seal** the class TestCaseOrdererAttribute, and make parameters typeName+assemblyName, without having overload of just Type, so no string constants involved?? (at the same time AttributeUsage[Inherited=true], seriously?)

I was always curious who uses `seal` except microsoft, who thinks all developers are retards shooting their own feet all over and Microsoft saves the universe by sealing the classes... What was the motive of sealing the class?

https://github.com/xunit/xunit/blob/9e853d3144e0c437b0456b8b4c8529f72510fc15/src/xunit.core/TestCaseOrdererAttribute.cs#L10

**Comment by pmunin** [comment]
Who was the super-hero that decided to **seal** the class `TestCaseOrdererAttribute` (at the same time `AttributeUsage[Inherited=true]`, seriously?), and make parameters typeName+assemblyName, without having overload for just typeof(...), so no string constants involved?? 

I was always curious who uses `seal` except microsoft, who thinks all developers are retards shooting their own feet all over and Microsoft is the only one who can save the universe... What was the motive of sealing the class?

https://github.com/xunit/xunit/blob/9e853d3144e0c437b0456b8b4c8529f72510fc15/src/xunit.core/TestCaseOrdererAttribute.cs#L10

**Comment by onovotny** [comment]
@pmunin Please refrain from using abusive language here as that's a violation of our [Code of Conduct](https://www.dotnetfoundation.org/code-of-conduct). 

We're more than happy to have a constructive discussion around issues and improving the product.

**Comment by pmunin** [comment]
sorry I didn't meant it to abusive - sarcastic maybe. But seriously can someone fix it or at least explain what's the value of locking the class?

**Comment by bradwilson** [comment]
This attribute (like many others) are locked because they are intended to be supported during source-based discovery, which means we need to be able to discern their intent without running any code (as the code may not be compiled, or even able to be successfully compiled). Allowing the user to override the attribute would force us to run code and break this model.

Instead, people who want to override this should create their own attributes and discoverers that properly participate in source-based discovery.

</answer mode="super-hero">

**Comment by dojo90** [comment]
Is there any news on this? I would like to pack the attribute class into an external library and without knowing the the strings to be passed. Is this somehow possible?

In `nunit` is an `Order Attribute` (https://github.com/nunit/docs/wiki/Order-Attribute), why hasn't this already been implemented as a default?

**Comment by bradwilson** [comment]
I've enabled `typeof()` constructors for the following attributes:

| Attribute | Commit |
| :--- | :--- |
| `CollectionBehaviorAttribute` | https://github.com/xunit/xunit/commit/5eb756cce955dff97d2943f294eb7a791e9b4c86 |
| `DataDiscovererAttribute` | https://github.com/xunit/xunit/commit/468f3590808145fe6207187b9daef91fd8d95922 |
| `TestCaseOrdererAttribute` | https://github.com/xunit/xunit/commit/b49cb40975eb9fa012051b4e5db5ee6a71e60cef |
| `TestCollectionOrdererAttribute` | https://github.com/xunit/xunit/commit/b54316e310cc107edef3874f8df1c3a67bc6563c |
| `TestFrameworkAttribute` | https://github.com/xunit/xunit/commit/fdcade4256800c027d8b4a6e41050a4d9caef728 |
| `TestFrameworkDiscovererAttribute` | https://github.com/xunit/xunit/commit/acf28bc50e6f9b206b0bf62f2c9b2b34aa296ecb |
| `TraitDiscovererAttribute` | https://github.com/xunit/xunit/commit/5a0c9d8404f92ebe2a780fe294c1a36d3b6fa0b9 |
| `XunitTestCaseDiscovererAttribute` | https://github.com/xunit/xunit/commit/bd27ce84ebbb5f5ef96148003d2eb11aabdb8b92 |

If you are aware of any other that I've missed, please open a new issue. Thanks!
