### ISSUE TITLE
xUnit3000 doesn't trigger with just xunit.abstractions reference

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1575]
If you create a project which references only `xunit.abstractions` (and neither of the extensibility libraries), then the xUnit3000 rule does not trigger at all.

**Comment by marcind** [comment]
Problem is likely here: https://github.com/xunit/xunit.analyzers/blob/master/src/xunit.analyzers/XunitDiagnosticAnalyzer.cs#L48

**Comment by bradwilson** [comment]
We could probably still enable behavior like this with a set of base classes that filter out based on abstractions vs. core vs. execution.

**Comment by marcind** [comment]
👍

**Comment by wachulski** [comment]
This seems to be pretty trivial (overriding `XunitDiagnosticAnalyzer.ShouldAnalyze` in x3000 and x3001). When it comes to:
>We could probably still enable behavior like this with a set of base classes that filter out based on abstractions vs. core vs. execution.

I'm not sure as using inheritance for some conditional feature check (ShouldAnalyze) IMO looks like abusing OO design means. It could be justified, if the distribution of specific inheritors would be even. Is it in fact? Now it seems only x3000 and x3001 are outliers as xunit.Core is required for most of anlyzers, isn't it?

**Comment by bradwilson** [comment]
Fixed in https://github.com/xunit/xunit.analyzers/commit/de864cca9048ed9b7df7f3affbf79c73b5e6d434
