### ISSUE TITLE
xUnit3001 doesn't trigger with just xunit.abstractions reference

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1576]
If you create a project which references only `xunit.abstractions` (and neither of the extensibility libraries), then the xUnit3001 rule does not trigger at all.

**Comment by marcind** [comment]
Problem is likely here: https://github.com/xunit/xunit.analyzers/blob/master/src/xunit.analyzers/XunitDiagnosticAnalyzer.cs#L48

**Comment by bradwilson** [comment]
Fixed in https://github.com/xunit/xunit.analyzers/commit/f1f80dcf73ec920881a8a35f45ead830c6705550
