### ISSUE TITLE
Improve documentation for vstest.console.exe

### ISSUE THREAD

**Issue by christopherbahr** [xunit/xunit#1581]
The documentation around setting up xUnit to work inside the Visual Studio test explorer works great! The thing I'd like to see added is a mention of how to run it using vstest.console.exe.

I was able to get it set up after some digging. The trick is that your vstest command has to have `/TestAdapterPath:path/to/testprojectoutput` in order to find the xUnit discoverer and executor.

Maybe this is obvious to people who really know their way around vstest but it took me a while to sort out. It would be great to have it spelled out in the docs.

**Comment by bradwilson** [comment]
I don't think this is an issue now.

Given a .csproj like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net6.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.6.5" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.6" />
  </ItemGroup>

</Project>
```

I'm able to run both .NET and .NET Framework tests via `vstest.console.exe` without needing to pass a path to the test adapter:

![image](https://github.com/xunit/xunit/assets/16944/4a0b262d-e1a2-4273-8b03-4daa977bfcfa)

Closing this issue for now. If this is still a problem, please open a new issue (and apologies for not getting to it sooner!).
