### ISSUE TITLE
xunit.console.exe fails with "could not load file or assembly" error on Mac

### ISSUE THREAD

**Issue by sandunweera** [xunit/xunit#1584]
Run the following command on Terminal of a Mac

mono packages/xunit.runner.console.2.3.1/tools/net452/xunit.console.exe MyTests/bin/debug/MyTests.dll -xml UnitTestsResults.xml

It fails with this error,
Could not load file or assembly 'MyTests' or one of its dependencies

But it works fine on windows

**Comment by bradwilson** [comment]
xUnit.net does not officially support Mono.

**Comment by sandunweera** [comment]
Is there any other way of running xUnit unit tests on a Mac?

**Comment by bradwilson** [comment]
On non-Windows machines, we only support .NET Core.

**Comment by sandunweera** [comment]
What I am trying to achieve is running unit tests written for a PCL, in my Xamarin project, which is built on a Mac.

Since this doesn't work with mono, I guess I don't have a workaround for the issue?

**Comment by bradwilson** [comment]
Neither .NET Core nor desktop Mono are your actual target platform, so my first recommendation would be to run them on the device instead. https://github.com/xunit/devices.xunit

If you're still intent on running them on the desktop, then use .NET Core instead of Mono.

**Comment by sandunweera** [comment]
I actually need to run these tests on my build agent (which is a Mac mini) That is why I tried to run them with mono.

Basically what I need is a command-line tool to run xunit tests on a Mac.

Would this be helpful? https://github.com/xunit/xamarinstudio.xunit

**Comment by bradwilson** [comment]
.NET Core runs on the Mac (which is why I've recommended it twice now). There are two command line runners for it: `dotnet xunit` and `dotnet test`.

These Getting Started directions show you how to use `dotnet xunit` and work on Windows, Linux, and Mac: https://xunit.github.io/docs/getting-started-dotnet-core.html
