### ISSUE TITLE
TraitAttribute changes in v2 should be documented in migration guide

### ISSUE THREAD

**Issue by MaceWindu** [xunit/xunit#159]
In xUnit v2 TraitAttribute marked as sealed.
In v1 I defined several custom attributes to mark tests like:
```
class UnitTestAttribute : TraitAttribute
{
     public UnitTestAttribute(): base("Type", "UnitTest")
     {
     }
}

class FunctionalTestAttribute : TraitAttribute
{
     public FunctionalTestAttribute(): base("Type", "Functional")
     {
     }
}
// etc
```

And used them to filter attributes for execution for different scenarios. In v2 I cannot create such attributes and need to copy-paste [Trait("blah-blah-blah", "even more blah-blah-blah")] everywhere, or define base classes per test type. From source code I see that we cannot just remove sealed from this attribute, because it loaded in very special way for some reason...

I propose at least document this in migration guide (or fix it).

**Comment by bradwilson** [comment]
Moved here: https://github.com/xunit/xunit.github.io/issues/5
