### ISSUE TITLE
Test with Trait stops test discovery when the value part is an empty string

### ISSUE THREAD

**Issue by dparvin** [xunit/xunit#1591]
When I was using older versions of xunit, I could make a test like the one listed below and I would discover them and run them.  With  xunit 2.3.1 (it also fails in 2.3.0) it will stop discovery and sit waiting for it to finish forever.  This is running in VS 2017 (15.5.2) trying to get the test listed in the Test Explorer.

```cs
[Fact]
[Trait("UnitTest", "")]
public void Test()
{
}
```

**Comment by bradwilson** [comment]
Dup #1562
