### ISSUE TITLE
Unable to build xUnit UWP Tests Project

### ISSUE THREAD

**Issue by godrose** [xunit/xunit#1592]
Environment:

Windows 10 1709 - FCU via Parallels Desktop
VS 2017 15.4.5
xUnit 2.3.1

Repro steps:
Follow the steps in tutorial https://xunit.github.io/docs/getting-started-uwp.html
Set the min and max target versions for UWP as FCU
Build the project

Expected result:
Project builds successfully

Actual result:

Project fails to build with the following error:
Could not copy the file "Y:\Workspace\logofx-project\cl-mvvm-vm-ex\src\LogoFX.Client.Mvvm.ViewModel.Extensions.Platform.UWP.Tests\obj\x86\Release\ilc\intermediate\LogoFX.Client.Mvvm.ViewModel.Extensions.Platform.UWP.Tests.ITFProxy\LogoFX.Client.Mvvm.ViewModel.Extensions.Platform.UWP.Tests.ITFProxy.g.cs" because it was not found.

**Comment by bradwilson** [comment]
Dup #1530
