### ISSUE TITLE
Exception stack trace missing from test report

### ISSUE THREAD

**Issue by D0tNet4Fun** [xunit/xunit#1599]
Steps to reproduce:

1. Create a new unit test project in Visual Studio 2017. 
Framework: .NET Core. 
Project name: `Xunit.MyProject.Tests`.
2. Edit the generated unit test and make it throw an exception.
3. Run the test using the Visual Studio test runner.

Expected result: the test fails. The test report contains the exception and its stack trace.
Actual result: the test fails. The test report mentions an exception was thrown, but there is no stack trace.

Note: I think this happens because the name of the project starts with `Xunit{dot}`. This issue does not happen for other test projects such as `XunitTestProject`.

**Comment by bradwilson** [comment]
You are correct. We filter everything out of the stack trace that comes from the namespace `Xunit`. This is working as designed. Please rename your default namespace to not start with `Xunit.`.
