### ISSUE TITLE
Missing PDBs on symbolsource.org

### ISSUE THREAD

**Issue by citizenmatt** [xunit/xunit#160]
Looks like the PDB files are missing on symbolsource.org. Trying to download the symbols for beta4-build2738, I get a 404:

http://srv.symbolsource.org/pdb/Public/xunit.runner.utility.pdb/FEE0B00874574946A310D41831E9664D1/xunit.runner.utility.pdb

and 

http://srv.symbolsource.org/pdb/MyGet/xunit.runner.utility.pdb/FEE0B00874574946A310D41831E9664D1/xunit.runner.utility.pdb

I don't know if this is a symbolsource.org bug, or something wrong with the build process. If we look at the page for the .net framework v3.5 build, the symbol type is "none", as is the documentation type:

https://www.symbolsource.org/Public/Metadata/NuGet/Project/xunit.runner.utility/2.0.0-beta4-build2738/Release/.NETFramework%2cVersion%3dv3.5?Profile=AnyCPU

But xunit.runner.utility build2650 lists the symbol type as "pdb" and documentation type as "xml":

https://www.symbolsource.org/Public/Metadata/NuGet/Project/xunit.runner.utility/2.0.0-beta-build2650/Release/.NETFramework%2cVersion%3dv3.5?Profile=AnyCPU

As does the mono touch and MonoAndroid versions of build 2738:

https://www.symbolsource.org/Public/Metadata/NuGet/Project/xunit.runner.utility/2.0.0-beta4-build2738/Release/MonoAndroid%2cVersion%3dv0.0?Profile=AnyCPU

Any ideas?

**Comment by ErikSchierboom** [comment]
@citizenmatt Did you manage to get this working? I'm also having problems getting the symbols loaded.

**Comment by citizenmatt** [comment]
No, I've mostly given up on symbolsource. Feels like it's been abandoned. I think xunit is using GitLink now, to put GitHub links into the pub files, works much more reliably.

**Comment by bradwilson** [comment]
@citizenmatt is correct, we abandoned Symbolsource because it was very unreliable.
