### ISSUE TITLE
Paths in *.runtimeconfig.dev.json aren't searched

### ISSUE THREAD

**Issue by nismolo** [xunit/xunit#1600]
We are having an issue similar to #1509. We were using version 2.3.1 and also tried by updating to 2.4.0-beta1-build3894.

X unit cannot find the dll for System.Text.Encoding.CodePages please note that mimekit is depended on 4.3.0 however for some reason an exception is thrown because version 4.0.2 is not found when running tests using xunit (dotnet xunit from CLI).

```
System.TypeInitializationException : The type initializer for 'MimeKit.ParserOptions' threw an exception.
                                                ---> System.TypeInitializationException : The type initializer for 'MimeKit.Utils.CharsetUtils' threw an exception.
                                                        ---> System.IO.FileNotFoundException : Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
                                                                ---> System.IO.FileNotFoundException : Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
                                        at MailKit.Net.Imap.ImapEngine.<ParseMessageAsync>d__190.MoveNext() in C:\Git\Third Party\MailKit\MailKit\Net\Imap\ImapEngine.cs:line 2527
                                        --- End of stack trace from previous location where exception was thrown ---
                                        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Issue Project Repo: https://github.com/nismolo/xunit-issue

**Comment by bradwilson** [comment]
This is (somewhat) related to the MVC testing bug, which is: the "root" folder of the execution is not the unit test assembly folder, but rather the folder containing `dotnet-xunit.dll`, which means the unit test assembly's `.runtimeconfig.dev.json` file isn't being read, and the probing paths do not include the locally cached assemblies in `%ProgramFiles%\dotnet\sdk\NuGetFallbackFolder`.

**Comment by bradwilson** [comment]
Verified with 2.4 beta 1 build 3896.

![image](https://user-images.githubusercontent.com/16944/34452081-5ae1fa24-ecec-11e7-8ca6-c8218e552e6c.png)
