### ISSUE TITLE
xUnit1000: Analyzer does not recognize `partial class` as public if `public` modifier is not repeated

### ISSUE THREAD

**Issue by stakx** [xunit/xunit#1602]
Given the following snippet, the xUnit analyzer will erroneously emit an error *xUnit1000: Test classes must be public*. This is obviously wrong, since the test class in question *is* public:

```csharp
public partial class Tests
{
}

partial class Tests
//            ^^^^^ Error xUnit1000: Test classes must be public
{
	[Fact]
	public void Test()
	{
	}
}
```

![xunit-analyzer-partial-class](https://user-images.githubusercontent.com/104481/34453690-a31b9520-ed5a-11e7-8809-e5d832a111e8.png)

(I would normally have the two `Tests` class declarations in separate files, but for brevity's sake I have put them together here.)

I am using packages `xunit` 2.3.1 and `xunit.analyzers` 0.7.0 (though the error appears to be present in 0.8.0, too).

**Comment by wachulski** [comment]
I can take it. @marcind can you assign me?

**Comment by marcind** [comment]
@wachulski consider yourself assigned (can't actually do it via github since you don't appear to be a contributor in this repo)
