### ISSUE TITLE
Platform not specified warning from Paket

### ISSUE THREAD

**Issue by tlycken** [xunit/xunit#1603]
When using Paket, it gives a bunch of warnings about not being able to determine platforms for some xUnit dlls. For example, [this repository](https://github.com/tlycken/AProjectHasNoName/tree/5d7756bb746fe216ad12f5d0b86358ecee01e730) yields the following output:

```
> .\.paket\paket.exe install
Paket version 5.128.1
Skipping resolver for group Main since it is already up-to-date
D:\Code\F# Foundation\AProjectHasNoName\src\paket.lock is already up-to-date
Installing into projects:
 - Creating model and downloading packages.
Could not detect any platforms from '_desktop' in 'D:\Code\F# Foundation\AProjectHasNoName\src\packages\xunit.core\build\_desktop\xunit.execution.desktop.dll', please tell the package authors
Could not detect any platforms from '_common' in 'D:\Code\F# Foundation\AProjectHasNoName\src\packages\xunit.runner.visualstudio\build\_common\xunit.abstractions.dll', please tell the package authors
 - FSharp.Project.FileOrderer/paket.references -> FSharp.Project.FileOrderer/FSharp.Project.FileOrderer.fsproj
 - FSharp.Project.FileOrderer.Runner/paket.references -> FSharp.Project.FileOrderer.Runner/FSharp.Project.FileOrderer.Runner.fsproj
 - FSharp.Project.FileOrderer.Tests/paket.references -> FSharp.Project.FileOrderer.Tests/FSharp.Project.FileOrderer.Tests.fsproj
Performance:
 - Disk IO: 63 milliseconds
 - Runtime: 5 seconds
Paket omitted 8 warnings similar to the ones above. You can see them in verbose mode.
```

A full verbose log output is available in [this gist](https://gist.github.com/tlycken/fced0778dba3a90f137deac570e8648e).

To reproduce, clone the linked repo (and checkout tlycken/AProjectHasNoName@5d7756bb746fe216ad12f5d0b86358ecee01e730), `cd src` and then `.paket/paket.exe install`. (This obviously depends on running on Windows.)

**Comment by tlycken** [comment]
Also, I'm not 100% sure this is the correct place to file the issue, but since the warning says "please tell the package authors", I figured it's as good a place as any to start.

**Comment by bradwilson** [comment]
Those folders aren't intended to be platforms: they contain DLLs which are referenced by .props or .targets files.

We have no intention to change this. The alternative would be duplicating files, causing package size to bloat as a result.

**Comment by matthid** [comment]
> they contain DLLs which are referenced by .props or .targets files.
> The alternative would be duplicating files, causing package size to bloat as a result.

People usually put those files into `/tools` or a subdirectory of `/build`. Why is that not an option?

**Comment by baronfel** [comment]
It looks like what's happening is that Paket is treating the nuget package spec for the contents of the `build` directory as exclusive, and this package isn't treating the `build` folder the same way.

Per [Nuget Docs](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#including-msbuild-props-and-targets-in-a-package) for including build props and targets:
> In some cases, you might want to add custom build targets or properties in projects that consume your package, such as running a custom tool or process during build. You do this by placing files in the form `<package_id>.targets` or `<package_id>.props` (such as `Contoso.Utility.UsefulStuff.targets`) within the `\build` folder of the project.
```
 \build
    \netstandard1.4
        \Contoso.Utility.UsefulStuff.props
        \Contoso.Utility.UsefulStuff.targets
    \net462
        \Contoso.Utility.UsefulStuff.props
        \Contoso.Utility.UsefulStuff.targets
```

Because of this, Paket looks for matching framework-specific (or framework agnostic!) resources either in the root `build` directory or in a `build\{framework}` subfolder as described above.  If these files are indeed meant to be cross-framework, then they should go into the root `build` directory, because there is no known target framework moniker `_common`.

**Comment by bradwilson** [comment]
The `/tools` folder has a different purpose in NuGet packages: those things get push onto the PATH in the NuGet command prompt.

Regardless, we never intend to issue a new version of `xunit.abstractions`, so there's no way this could ever be "fixed", even if we agreed that it was broken (which I don't).

**Comment by matthid** [comment]
> Regardless, we never intend to issue a new version of xunit.abstractions, so there's no way this could ever be "fixed", even if we agreed that it was broken (which I don't).

So we 
 - either start building up some whitelist folder names `_common`, `_desktop`, ... (ugly because every package will add their own)
 - or we ignore everything starting with `_` and hope nuget will never introduce such frameworks-ids :/
 - or we leave the warning in place

We cannot just remove the warning because it tells us when nuget introduces new framework monikers, which means our logic might not be correct anymore.

/cc @forki maybe for additional ideas

**Comment by onovotny** [comment]
I think the point here is that the only thing Paket should be looking for in `\build` are `props` and `targets` files that match the package id. It shouldn't even be considering unknown platforms or dll's there.

**Comment by matthid** [comment]
Yes we do, but technically an empty folder means don't use any props or targets files for that particular framework.

So how can we know if we have done the wrong thing by not detecting the foldername properly? This is one reason for the warning.

**Comment by onovotny** [comment]
@matthid I think the key is that the logic should only work for TFM's that you recognize. If you don't recognize the folder name, it should be ignored and removed from the evaluation criteria.

**Comment by matthid** [comment]
Then we get hard to debug errors when new tfms are introduced, that's the point

**Comment by onovotny** [comment]
What can you really do with an unknown TFM? Either Paket recognizes and supports it or it doesn't?

**Comment by matthid** [comment]
We print a warning and implement it when we see the warning ;)

**Comment by onovotny** [comment]
I'll add that TFM's are transparent to NuGet and work only with an exact match.

**Comment by matthid** [comment]
> I'll add that TFM's are transparent to NuGet and work only with an exact match.

While it doesn't change any of my arguments, just for the sake of it: I don't think that is true, see
http://nugettoolsdev.azurewebsites.net/4.0.0/parse-framework?framework=net4912# NuGet has no problem handling `net4912` and you could probably push a package right now with `net2913` and it will work just fine without it being documented nor an exact match to the documented ones (https://docs.microsoft.com/en-us/nuget/schema/target-frameworks).

TFMs are a huge mess and the warning helps :). The big irony is that we in Paket do exact matching while NuGet doesn't. This means we need to somehow "see" when an unknown TFM enters the wild (like `net2913` above).

I think we will just ignore folders starting with `_` and hope the NuGet team never decides to use TFMs starting with `_`.

**Comment by onovotny** [comment]
That's following the rules precisely. `net` is the TFM and the number is the version. The TFM has a base and a version. It doesn't need to know about every version of every TFM.

**Comment by bradwilson** [comment]
> We cannot just remove the warning because it tells us when nuget introduces new framework monikers, which means our logic might not be correct anymore.

This is fine for your internal use, but need not be exposed to the community at large. You'll find out about TFMs you don't expose either through your internal testing, or from customers saying "this new TFM isn't supported, when will it be?" without populating their builds full of warnings _**they can't do anything about**_.

**Comment by onovotny** [comment]
Point is also that NuGet doesn't need to introduce new framework monikers. They can be arbitrary and defined in the project itself. NuGet will match the TFM (text part) and version without any extra knowledge.

I.e., If my project targets `banana2.1` it'll just work if a nuget reference has a `\lib\banana1.5` and successfully reject as incompatible a `\lib\banana2.2`.
