### ISSUE TITLE
Add Assert.Equivalent

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1604]
Rather than a strict equality comparer, the equivalence comparer would be able to:

1. Use reflection against two classes (regardless of whether they match types) to see if they have the same values for their public properties and/or fields;
2. Determine if two collections contain equivalent values<br />`[1, 2]` vs. `[2, 1]`
3. Determine if two dictionaries contain equivalent values<br />`{ { "foo", "bar" }, { "baz", 42 } }` vs. `{ { "baz", 42 }, { "foo", "bar" } }`
4. Use all of these rules collaboratively during deep dives (keys and/or values which are classes use rule 1; fields and properties of classes can be collections and/or dictionaries, following rules 2 and 3)

This is a big feature. Please start some discussion here to talk about implementations and implications if you plan to tackle it. Thanks!

**Comment by GeorgDangl** [comment]
I think this is a great idea, an `Assert.Equivalent` has lots of use cases.
However, I'm not sure if xUnit should be the right place to have it. I'm very happy with [CompareNETObjects](https://github.com/GregFinzer/Compare-Net-Objects), for example when comparing roundtrips of serialized/deserialized values.
I've found that for real projects, you'll need a lot of configurability (such as decimal precision, properties to ignore, case invariance...).

**Comment by scottt732** [comment]
Re: `[1, 2]` being equivalent to `[2, 1]`.  I think it's lost in the JSON whether the original type was a Set where order isn't important & dupes might not exist or an Enumerable/array where order is captured (though only significant in some contexts) and dupes are allowed.

If I'm reviewing someone else's code & tests, I'd rather either see differently named test methods for the set-based vs. enumerables w/ordering vs. enumerables w/o concern of ordering.  Equivalent is too vague of a term to me.  Something like `Assert.False(c1.Except(c2).Any())`, `Assert.True(c1.OrderBy(x => x).SequenceEqual(c2.OrderBy(x => x))` (hopefully with some comments explaining the author's intent) would work fine.

This gets tricky when you get to (4).  If you're trying to analyze an entire object graph that will implicitly have these various equivalence tests within it, a user might need to specify at the property/nested-property level which mechanism to use.

Similarly, they might need to specify an `IComparer<>` or an `IEqualityComparer<>`.  If so, where would the property-specific details live?  In attributes with the code itself (not thrilled about adding xunit namespaces to non-test code)?  With some complex options lambdas on the test method?  Complex enough to warrant testing your tests?

**Comment by bradwilson** [comment]
> If I'm reviewing someone else's code & tests, I'd rather either see differently named test methods for the set-based vs. enumerables w/ordering vs. enumerables w/o concern of ordering.

If you're implementing a deep object comparison, how do you specify which assertions to use at which layers? For example, you're comparing equality of two objects, and they have a collection inside them. Is that collection difference expressed as equivalence or equality? This question is why I think a single Equivalent makes sense (rather than 3 or 4 of them) because it will be explicitly explained that equivalence means various things based on the object type, and its deep equivalence comparison spreads those rules into the compared values.

**Comment by bradwilson** [comment]
(clicked the wrong button)

**Comment by scottt732** [comment]
I see the point, but I think it leaves a little room for ambiguity in the one part of the codebase where I prefer not to have any.  I get that it's always safe to assume that `HashSet<int>`'s Equivalent just means `!a.Except(b).Any()`.  But what if someone could have used a `HashSet<int>` but instead used a `List<int>` with the expectation that there would never be duplicates.  I don't want that oversight concealed by virtue of the fact that it happens to be inside of an object graph as opposed to the subject of a test.  That hard-to-catch mistake coupled with the behavior I think you're proposing could allow bugs to get through.

I'd rather the person writing the tests to walk the object graph and explicitly tell me what the expectations are around their data structures.  From a code review perspective, if I saw tests trying to treat a `List` like a `HashSet`, I'd probably ask for the data structure to be changed.

**Comment by michalkowal** [comment]
@bradwilson 
I have few additional questions/examples:
1. Is `{ "Field1":1 }` equivalent to `{ "Field1":1, "Field2": 2 }` ?
2. Is `{ "Field1":1, "Field2": 2 }` equivalent to `{ "Field1":1 }` ?
3. Is `[1, 2]` equivalent to `[1, 2, 3]` ?
4. Is `[1, 2, 3]` equivalent `[1,2]` ?
5. Should there be a limit for nesting level during deep compare? I think, it should be (5 maybe 10) to prevent easly circular dependencies.


Below also my proposal about API:
```
partial class Assert
{
	/// <summary>
	/// Checks objects equivalency (default comparison)
	/// </summary>
	/// <param name="expected">expected object (equivalent)</param>
	/// <param name="actual">actual object</param>
	/// <exception cref="EquivalentException">thrown when expected is not equivalent of actual</exception>
	public static void Equivalent(object expected, object actual)
	{
		throw new EquivalentException(expected, actual);
	}

	/// <summary>
	/// Checks objects equivalency with custom comparisons
	/// </summary>
	/// <param name="expected">expected object (equivalent)</param>
	/// <param name="actual">actual object</param>
	/// <param name="comparers">custom comparers</param>
	/// <exception cref="EquivalentException">thrown when expected is not equivalent of actual</exception>
	public static void Equivalent(object expected, object actual, params IEquivalencyComparer[] comparers)
	{
		throw new EquivalentException(expected, actual);
	}

	/// <summary>
	/// Checks objects equivalency (default comparison)
	/// </summary>
	/// <param name="expected">expected object (equivalent)</param>
	/// <param name="actual">actual object</param>
	/// <exception cref="NotEquivalentException">thrown when expected is equivalent of actual</exception>
	public static void NotEquivalent(object expected, object actual)
	{
		throw new NotEquivalentException(expected, actual);
	}

	/// <summary>
	/// Checks objects equivalency with custom comparisons
	/// </summary>
	/// <param name="expected">expected object (equivalent)</param>
	/// <param name="actual">actual object</param>
	/// <param name="comparers">custom comparers</param>
	/// <exception cref="NotEquivalentException">thrown when expected is equivalent of actual</exception>
	public static void NotEquivalent(object expected, object actual, params IEquivalencyComparer[] comparers)
	{
		throw new NotEquivalentException(expected, actual);
	}
}

/// <summary>
/// Defines equivalency comparison of two types (can be equal).
/// </summary>
public interface IEquivalencyComparer
{
	/// <summary>
	/// Type of object checked as equivalent
	/// </summary>
	Type EquivalentType { get; }
	/// <summary>
	/// Type of source object
	/// </summary>
	Type SourceType { get; }

	/// <summary>
	/// Check objects equivalency
	/// </summary>
	/// <param name="equivalent">object checked as equivalent</param>
	/// <param name="source">source object</param>
	/// <returns>True when objects are equivalent</returns>
	bool Equivalent(object equivalent, object source);
}
```
`IEquivalencyComparer` will be used like `IEqualityComparer<>` in `Assert.Equals`, but here types can be different and also we can provide multiple comparers, because we can find multiple different types on different levels during deep compare.
I think we can also use `IEquivalencyComparer` internally for checking equivalency in default way (simillar to `IEqualityComparer<>` in `Assert.Equals`.

Brad, and other patricipants, what do you think?

**Comment by bradwilson** [comment]
My answer to 1-4 is no.

As for 5, circular dependencies are definitely something to be accounted for. I'd tend to prefer a reference tracker, and then an outright failure if you end up too many levels deep (I'd prefer to know that you're not comparing things because they're too deep, as opposed to silently passing); the depth should be a parameter.

**Comment by bradwilson** [comment]
Why is there an array of equivalence comparers?

**Comment by michalkowal** [comment]
Maybe example :) 
```
class Order
{
	private readonly List<ItemDto> _items = new List<ItemDto>();

	public Order(string number, CustomerDto customer)
	{
		Number = number;
		Customer = customer;
	}

	public string Number { get; }
	public IEnumerable<ItemDto> Items => _items;
	public CustomerDto Customer { get; }
}

class OrderDto
{
	public string Number { get; set; }
	public List<ItemDto> Items { get; set; }
	public CustomerDto Customer { get; set; }
}

class Customer
{
	public Customer(string name)
	{
		Name = name;
	}

	public string Name { get; }
}

class CustomerDto
{
	public string Name { get; set; }
}

class Item
{
	public Item(string code)
	{
		Code = code;
	}

	public string Code { get; }
}

class ItemDto
{
	public string Code { get; set; }
}
```

We want to compare business objects with DTOs, but for example we want to customize ONLY comparison of Item<->ItemDto and Customer<->CustomerDto but other compares are ok for us (body of Order, collections etc)
```
Assert.Equivalent(order, orderDto, new ItemEquivalencyComparer(), new OrderEquivalencyComparer);
```

Algorithm will look like (more-less):
```
get both types
get all public properties/fields
create map by names
foreach
    if types have comparer
        compare
    if types are IEnumerable (also Dictionaries)
        compare with default CollectionComparer
    if simple types (string, int etc) 
        compare by Equals
    else
        recursion
```

To avoid array of "comparers", there can be something like `EquivalencyOptions` parameter with collection of comparers. Also there can be an option about levels of deep and so on. But I haven't seen before in xunit solution, this kind of customization and it looks like incoherently.

**Comment by AdamHess** [comment]
Equal has always meant equal by reference. Why not just keep it simple and have an order invariant equal check? 

Deep equality is like deep cloning, a problem for some other library.

**Comment by IanKemp** [comment]
> Equal has always meant equal by reference. Why not just keep it simple and have an order invariant equal check?
> 
> Deep equality is like deep cloning, a problem for some other library.

I love having to install another library just because I need a single method that xunit doesn't have.

**Comment by wizofaus** [comment]
Definitely a feature that would be very helpful, but only if it told you exactly which sub-property the equivalence was failing at.
Would make sense to look at how this is done in other development environments e.g. NodeJs assert.deepEqual().

**Comment by wizofaus** [comment]
> Equal has always meant equal by reference. Why not just keep it simple and have an order invariant equal check?
> 
Surely `Assert.Equal(  )` should always attempt to compare by value, `Assert.Same(  )` is for comparing by reference.
I don't think I've ever even needed to use Assert.Same( ) but obviously there may be cases where it's important that a reference returned by a function points to the same object as some originally supplied reference (if nothing else, so that object modifications through the actual reference will update the expected object).

**Comment by bradwilson** [comment]
I've started implementing this, and I think I've reconsidered some of my previous opinions. I'm putting in a "strict" option, which will influence how I answer some of these questions. I think I would summarize it like this:

- In strict mode, the two objects must be fully equivalent (nothing missing on either side).
- In non-strict mode, the "expected" value is what needs to be present in the "actual" value, and anything extra that's in the "actual" value is ignored.

Not sure which mode should be default, but as I was coding around the API, I went with non-strict by default.

So, to re-answer now, on the assumption that left value == expected, right value == actual:

>Is { "Field1":1 } equivalent to { "Field1":1, "Field2": 2 } ?
>Is [1, 2] equivalent to [1, 2, 3] ?

Strict mode: no.
Non-strict mode: yes.

>Is { "Field1":1, "Field2": 2 } equivalent to { "Field1":1 } ?
>Is [1, 2, 3] equivalent [1,2] ?

Always no.

**Comment by wizofaus** [comment]
The relatively quick'n'dirty version I wrote a) only works on JObject/JArray, but b) does the equivalent of your "non-strict" mode - and the only reason I made that the default is that the objects I wanted to check had 100s of fields (nested at various levels), but there were really only 30 or so that I truly cared about - specifying the full expected object would make the tests quite unwieldy. But I agree a "strict mode" is important for cases where, for instance, extra fields in the "actual" object might serialize into JSON/XML/etc. that would cause issues with other clients, and probably should be the default.
But the key and vital thing I *did* add is ensuring that you can easily see what field/s don't match in the exception message - in my case by including the JSON path, but there should be a way it can be done more generically.

**Comment by bradwilson** [comment]
The currently implementation stops after the first mismatch and reports that, and it reports it with a "dotted accesor" style syntax. Here's an example using anonymous objects:

```csharp
[Fact]
public void Failure()
{
	var ex = Record.Exception(() => Assert.Equivalent(new { x = new { y = 42 } }, new { x = new { y = 2112 } }));

	Assert.IsType<EquivalentException>(ex);
	Assert.Equal(
		"Assert.Equivalent() Failure: Mismatch on member 'x.y'" + Environment.NewLine +
		"Expected: 42" + Environment.NewLine +
		"Actual:   2112",
		ex.Message
	);
}
```

**Comment by bradwilson** [comment]
>there were really only 30 or so that I truly cared about

Yeah, that's how I suspect it'll get used most: "Here's an object, probably anonymous, which describes the values I care about. Everything else is irrelevant." But I'm not 100% sure. 😂
