### ISSUE TITLE
Why the file name change with the xunit.runner.msbuild.<framework>.dll

### ISSUE THREAD

**Issue by BlackFrog1** [xunit/xunit#1606]
Why did the DLL name of the xUnit Runner for MSBuild changed in version 2.3.0 and higher?

> xunit.runner.msbuild.2.2.0: xunit.runner.msbuild.dll
> xunit.runner.msbuild.2.3.0: xunit.runner.msbuild.net452.dll

According to your documentation for [running tests in msbuild](https://xunit.github.io/docs/running-tests-in-msbuild.html), the file name is fixed.

`<UsingTask AssemblyFile="path\to\xunit.runner.msbuild.dll" TaskName="Xunit.Runner.MSBuild.xunit"/>`

Because I don't see a reason for change.  The dll is already in a folder with the name **net452**. 
![xunit msbuild file name](https://user-images.githubusercontent.com/550820/34579313-762e61fa-f156-11e7-8ea7-9fa0fb40d5eb.png)

I will have to update my build script every time the framework changes.  It would be a lot easier to search for the fixed name **xunit.runner.msbuild.dll** in the proper folder.

**Comment by bradwilson** [comment]
It was originally changed in anticipation of adding support for .NET Core (which got killed when we realized it wasn't possible).

**Comment by bradwilson** [comment]
FWIW, the new location is the correct location based on NuGet standards. The old location predated multi-platform support in NuGet.

**Comment by BlackFrog1** [comment]
The location is correct, **net452**.  I am taking about the name of the file itself.  Why add net452 to the name.  If you get to support .NET Core, should the folder reflect that instead of changing the name?

I know my example is a library, but it's the same name in each folder.
![sample](https://user-images.githubusercontent.com/550820/34580021-574d5ed2-f159-11e7-96bc-320d8277f5f5.png)

**Comment by bradwilson** [comment]
Sorry, I misunderstood your point. Not uncommon for me. :stuck_out_tongue_closed_eyes: 

I'm not sure it was a necessary change, though I wouldn't want to change it back again at this point (since it generates yet another disruption). I will update the docs.

**Comment by BlackFrog1** [comment]
Can we generate two copies of the same dll?  Old name and new name.  Minimize disruption and no document change.

**Comment by bradwilson** [comment]
The move of the path is already disruptive, and I'd rather not bloat the size of the NuGet package unnecessarily (their compression algorithm does not do data de-duplication).

**Comment by bradwilson** [comment]
Closing as this is not something we're planning to change.
