### ISSUE TITLE
Use implicit/explicit type conversions declared on theory arguments' types

### ISSUE THREAD

**Issue by ascott18** [xunit/xunit#1607]
Related to https://github.com/xunit/xunit/issues/1013 - The PR for that issue, https://github.com/xunit/xunit/pull/1020, implemented calls to user-defined conversions, but only did so for conversions that are declared on the theory's parameter type. It did not check for conversions that are defined on the actual argument's type. Since C# allows you to define a conversion operator on either the class on the left-hand side or the right-hand side, the solution in https://github.com/xunit/xunit/pull/1020 is only half complete.

The use case is essentially the same as https://github.com/xunit/xunit/issues/1013 - wanting to make the names of tests more concise and relevant to the pertinent data. However, my particular use case necessitated that my user-defined conversions be placed on the arguments supplied to my tests rather than the parameters themselves.

Pull request incoming momentarily.

**Comment by GrantErickson** [comment]
Really helpful, thanks for adding this @ascott18 and @bradwilson.
