### ISSUE TITLE
Allow custom test attributes to opt out of xunit1013

### ISSUE THREAD

**Issue by adamralph** [xunit/xunit#1611]
As [discussed](https://xunit.slack.com/archives/C034MFNED/p1515007487000117).

**Comment by zvirja** [comment]
@adamralph Could you please copy text here for people who are not registered on slack (and for better search)?

**Comment by adamralph** [comment]
@zvirja here you go:

> adamralph [19:46]
> 
> I have a problem regarding xUnit1013: Public method 'Foo' on test class 'Bar' should be marked as a Fact.
> 
> In xbehave 2.3.0 and earlier, the `Background` attribute (https://github.com/xbehave/xbehave.net/wiki/Backgrounds) inherits `Fact`. However, this is redundant, so I removed it in xbehave 2.3.1 (currently in pre-release), specifically because it causes ReSharper to show a dummy "test" in the output, which is marked as inconclusive because it never actually runs. All good so far. However, I just noticed that xunit1013 is being triggered, because xbehave background methods are public methods on test classes, and the `Background` attribute no longer inherits `Fact`. I'm not sure how to proceed... (edited)
> 
> it it wasn't for ReSharper's behaviour, I'd re-introduce `Fact` into the inheritance tree for `Background`, but I'm now stuck between the analyser and ReSharper, and I don't know how I can please both /cc @citizenmatt
> 
> Perhaps, rather than the analyser insisting on having an attribute derived from `Fact` on all public methods, there should be a way for other attributes to signal to the analyser that their presence also validates the existence of the public method. Perhaps by inheriting from a "marker" interface instead of `Fact`?
> 
> marcind [20:01]
> 
> I’m the author of the analyzers. So far the analyzers have done little to accommodate extensions on top of xUnit that break the typical mold.
> 
> adamralph [20:03]
> 
> if the analyzer were opt-in, that wouldn't be too bad
> 
> but the xunit package depends on it
> 
> marcind [20:03]
> 
> Not being familiar with xbehave, my initial reaction is that the `Background` attribute seems to replicate the functionality of test setup in the constructor in regular xUnit tests. However, looks like this feature was introduced back in 2012, so I’m guessing there’s little chance you’d remove it? :stuck_out_tongue:
> 
> adamralph [20:05]
> 
> @marcind there's one big difference: an xbehave background can itself contain many "steps", each of which produces a test result, just like an xbehave scenario
> 
> marcind [20:05]
> 
> the analyzers are included in the main `xunit` package to help adoption/awareness (this decision was based on a twitter poll Brad did a while ago). `xunit.core` can be depended on directly to exclude them altogether. individual rules can also be disabled in a project using various mechanisms.
> 
> tullo_x86 [20:05]
> 
> ^
> 
> was halfway through typing this
> 
> adamralph [20:06]
> 
> having to disable the rule explicitly isn't great, since everyone using xbehave would have to carry around that exclusion with them everywhere (assuming they are using backgrounds)
> 
> marcind [20:07]
> 
> does it make sense for xbehave to depend on `xunit` instead of `xunit.core`?
> 
> adamralph [20:07]
> 
> I did consider depending on xunit.core instead of xunit, but xbehave actually mirrors xunit in that way. There is xbehave, which depends on xunit, and xbehave.core which depends on xunit.core
> 
> that way, you install just one package, xbehave, and you get "the lot"
> 
> marcind [20:08]
> 
> the other thing you get with `xunit` is the assert library, which (based on 2 seconds reading the docs) don’t seem to be used
> 
> adamralph [20:09]
> 
> assertion is at the discretion of the user. xbehave doesn't provide anything. The user can choose to use xunit.assert (which xbehave brings in for you) or something else (in which case they'd probably choose xbehave.core)
> 
> marcind [20:10]
> 
> cool, so now that you’ve pushed back against my pushback, I do agree that users should have a good experience out of the box :slightly_smiling_face: (edited)
> 
> adamralph [20:10]
> 
> I am open to the possibility of collapsing xbehave into one package and depending on xunit.core. However, it is a shame that the analyser is tripped up by just this one thing
> 
> i.e. it would be nice to use the analyser with xbehave regardless, and not have to always explicitly switch off this rule
> 
> marcind [20:11]
> 
> I see two options: a) analyzers have special handling of particular extensions or b) analyzers expose a way for extensions to opt out of triggering particular rulels
> 
> (bonus option: c) all of the above)
> 
> I’m hesitant about a) because it means there now has to be hardcoded knowledge about various extension and their patterns (which could change down the line)
> 
> adamralph [20:12]
> 
> what about d) introduce an interface which has the meaning "if a public method has an attribute on it deriving from this, then it's OK to be a public method" and have the analyser trigger on the absence of that instead (and obviously make `Fact` derive from it too)?
> 
> marcind [20:14]
> 
> b) would put the onus on the extension author (assuming that a specific opt out trigger mechanism has been designed/implemented by the analyzers)
> 
> yeah, I see b) as being implemented via ‘duck typed’ marker interfaces
> 
> adamralph [20:14]
> 
> yeah, my suggestion d) is effectively a way to do b) (edited)
> 
> marcind [20:14]
> 
> right, we’re in violent agreement :slightly_smiling_face:
> 
> adamralph [20:15]
> 
> :slightly_smiling_face:
> 
> marcind [20:15]
> 
> so, for this particular rule, if your attribute is marked with an interface that matches a name known by the analyzer, the rule would not trigger
> 
> adamralph [20:16]
> 
> right
> 
> marcind [20:16]
> 
> there would not be a binary dependency on some sort of analyzer sdk, just reflection to see if this thing implements something named `IgnoreXunitAnalyzersRule1234` or whatever (edited)
> 
> adamralph [20:17]
> 
> yeah, I was just thinking that the interface could even be rule specific, e.g. `DoNotTrigger1013`, rather than some higher semantic meaning
> 
> and yes, it could be duck typed
> 
> marcind [20:18]
> 
> Cool
> 
> well, I’ve been known to accept PRs :stuck_out_tongue:
> 
> adamralph [20:18]
> 
> I was initially thinking that it would be defined in xunit somewhere but I guess that would come with it's own problems
> 
> marcind [20:20]
> 
> yeah, I’d rather keep things loose and avoid coordinating changes in too many packages. The goal of the analyzers is to support older versions of xunit and perform ‘feature detection’ (however that is specified)
> 
> adamralph [20:21]
> 
> yeah, I think that's the best approach
> 
> perhaps it would also be cleaner to define an attribute and mark the extension attribute with that attribute, rather than make the extension attribute inherit from an interface (edited)
> 
> marcind [20:22]
> 
> that’s also an option
> 
> I guess it does bring up the issue of inheritance and whether a child type would want to opt back in.
> 
> though probably not for this rule
> 
> adamralph [20:23]
> 
> OK, I have to run, but thanks for the discussion. I'll give it some more thought and there may be a PR incoming. I won't be releasing xbehave 2.3.1 until there's some resolution to this, so I have incentive to do something about it :slightly_smiling_face:
> 
> marcind [20:23]
> 
> the marker interface would probably be a bit easier to detect in the class hierarchy than the marker attribute
> 
> yeah, feel free to open an issue in the main `xunit` repo for tracking purposes

**Comment by adamralph** [comment]
🎉 

I assume this will be part of xunit 2.4? Will it be released in a beta/RC before RTM?

**Comment by marcind** [comment]
The change will be released in the next build of `xunit.analyzers`, which will be rolled into any upcoming prerelease builds of `xunit` itself. You could add an explicit dependency on the new build of `xunit.analyzers` or wait until it gets pulled in transitively with the next `xunit`.

**Comment by adamralph** [comment]
@marcind is this going to be released soon?

FYI The [xbehave 2.3.1 release](https://github.com/xbehave/xbehave.net/issues/416) is blocked, awaiting this.

**Comment by marcind** [comment]
I've finally gotten around to pushing this out: https://github.com/xunit/xunit.analyzers/releases/tag/v0.9.0. Core `xunit` metapackage updated to depend on 0.9.0 as well.

**Comment by marcind** [comment]
You could always add an explicit dependency to the newer xunit.analyzers
package version to force your users to upgrade, then drop it once the next
xunit release happens.

**Comment by adamralph** [comment]
🤔 that's not a bad idea...
