### ISSUE TITLE
Remove unnecessary conditional in descriptor deserialization

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1619]
This line:

https://github.com/xunit/xunit/blob/b592a1a475d1542b8e6598c6c704dd1da5fa2ffa/src/xunit.runner.visualstudio/Sinks/VsDiscoverySink.cs#L100

is unnecessary, and prevents providing valuable information when it's present.

Slack chat transcript:

-----

**Christopher Haws [12:05]** 

> Hello, I work on a custom test discoverer that discovers tests written in a DSL. A few months ago, when using the extension in Visual Studio I would receive source info in the Test Explorer so that I could double click the test to navigate to it, however this doesnt seem to be working anymore. After looking for a few hours it I am at a loss as to why this doesnt work anymore. I have a suspicion that it has to do with the new feature in VS where VS can enumerate your tests without building (When looking at `Microsoft.VisualStudio.TestWindow.Extensions.VsSourceInformationProvider` in `TestWindow.Dotnet.Core.dll` I can see that it is using the type's FQN to reflect on source info. Is the `ISourceInformation` on `ITestCase` not used anymore? (edited)

**Christopher Haws [09:43]** 

> @bradwilson I believe the issue with source info is happening here: https://github.com/xunit/xunit/blob/master/src/xunit.runner.visualstudio/Sinks/VsDiscoverySink.cs#L100

> For .NET Core test projects, VSTest is sending false for `RequireSourceInformation`. I made a simple test adapter to play around with this and no matter what I do VSTest sends false here. If I ignore the fact that it sends false and set the source info anyways, it does work properly.

**Brad Wilson [08:16]** 

> As I'm looking at that code, I'm not 100% sure why that test is there. There is no cost savings to be had, because the descriptor is a local object (not across the app domain).

**Comment by ChristopherHaws** [comment]
@bradwilson That correct, it is not C# (it is actually an extension for SpecFlow https://github.com/gasparnagy/SpecFlow.xUnitAdapter). The descriptor does have the correct info in it, it just isn't getting passed back to vstest.
