### ISSUE TITLE
Test fixture classes which are registered using `IClassFixture` should not be created asynchronously.

### ISSUE THREAD

**Issue by r-aghaei** [xunit/xunit#1621]
Test fixture classes which are registered using `IClassFixture` should not be created asynchronously.

Currently the test runner creates text fixture classes asynchronously using `CreateClassFixtureAsync` in `XunitTestClassRunner.cs`. This way, they may overwrite each other initializations.

As a simple example suppose we have two test fixture classes, which each of them performs some initializations, including writing a specific text in a specific file which is expected by test. Then if `Test1Fixture` writes `1` in `somefile.txt` and `TestFixture2` writes `2` in the same file, then always one of the test cases will fail, because the frameworks will do initialization at first, so the file content will be overwritten by test fixtures and the when executing the tests, one sets of tests will definitely fail.

Here is a simple code to reproduce the problem:
```
using System;
using Xunit;

namespace UnitTestProject1
{
    public class Test1Fixture : IDisposable
    {
        public Test1Fixture()
        {
            System.IO.File.WriteAllText("somefile.txt", "1");
        }
        public void Dispose()
        {
        }
    }
    public class Test2Fixture : IDisposable
    {
        public Test2Fixture()
        {
            System.IO.File.WriteAllText("somefile.txt", "2");
        }
        public void Dispose()
        {
        }
    }
    public class Test1 : IClassFixture<Test1Fixture>
    {
        [Fact]
        public void Fact1()
        {
            var actual = System.IO.File.ReadAllText("somefile.txt");
            Assert.Equal("1", actual);
        }
    }
    public class Test2 : IClassFixture<Test2Fixture>
    {
        [Fact]
        public void Fact2()
        {
            var actual = System.IO.File.ReadAllText("somefile.txt");
            Assert.Equal("2", actual);
        }
    }
}
```

**Comment by bradwilson** [comment]
This is by design.

Those two test classes are in separate test collections, and therefore are available for parallelization against one another. There is no guarantee which order those classes will be run, and whether or not methods in those classes will be running at the same time.

If you want those two classes to run synchronously, place them into the same test collection:

```csharp
    [Collection("Mutates somefile.txt")]
    public class Test1 : IClassFixture<Test1Fixture>
    {
        [Fact]
        public void Fact1()
        {
            var actual = System.IO.File.ReadAllText("somefile.txt");
            Assert.Equal("1", actual);
        }
    }

    [Collection("Mutates somefile.txt")]
    public class Test2 : IClassFixture<Test2Fixture>
    {
        [Fact]
        public void Fact2()
        {
            var actual = System.IO.File.ReadAllText("somefile.txt");
            Assert.Equal("2", actual);
        }
    }
```

For more information on parallelization and test collections, see [Running Tests in Parallel](https://xunit.github.io/docs/running-tests-in-parallel.html) on our [documentation site](https://xunit.github.io/).

**Comment by r-aghaei** [comment]
@bradwilson Thanks for the reply. I missed some parts of the documentations and didn't tried that.
