### ISSUE TITLE
AppVeyor reporter fails test run even if all tests pass

### ISSUE THREAD

**Issue by natemcmaster** [xunit/xunit#1628]
We're experiencing flaky test failures due to errors thrown from here: https://github.com/xunit/xunit/blob/b592a1a475d1542b8e6598c6c704dd1da5fa2ffa/src/xunit.runner.reporters/AppVeyorClient.cs#L120-L124

Example:
https://ci.appveyor.com/project/aspnetci/razor/build/1.0.3951
![image](https://user-images.githubusercontent.com/2696087/35748453-f18399b6-0802-11e8-8fb4-990b8788e4dc.png)

This happens most on projects with lots of tests, like EntityFrameworkCore (cc @smitpatel), so we've resorted to disabling auto reporters to workaround this. So, I suspect this is related to load.

**Comment by bradwilson** [comment]
I'm not sure why this is our issue rather than AppVeyor's.

**Comment by natemcmaster** [comment]
Would you accept a PR to add a retries? I was thinking a simple loop to retry at most 2 more times should help reduce the frequency of the error

**Comment by bradwilson** [comment]
It's a localhost server. What makes you believe retries would be an effective solution?

I accept that this may be an xUnit.net bug, but *not* if it's because the server on localhost is rejecting the API request. If that's the problem, it's on AppVeyor to fix it.

**Comment by natemcmaster** [comment]
As far as I can tell from the stack trace, this is caused by timing out when sending the POST. It only appears under load when thousands of tests results are produced. We could also try increasing the timeout, which is currently set to 30 seconds.

**Comment by bradwilson** [comment]
Before we up this to yet another arbitrary number, I would like confirmation from AppVeyor that (a) this is expected behavior (that a localhost API would take longer than 30 seconds), and (b) the duration they suggest is appropriate.

**Comment by natemcmaster** [comment]
@onovotny might know something (cref https://github.com/appveyor/ci/issues/997#issuecomment-243623795)

**Comment by bradwilson** [comment]
I sent an e-mail to them (and CC'd you Nate). Let's see what they say.

**Comment by FeodorFitsner** [comment]
Hi guys,

Thanks for adding us to the loop discussing this issue.

Indeed, that localhost `/api/tests/batch` call is just about pushing request details into internal queue and shouldn't timeout...in theory.

Is possible to do a simple repro with this issue? Like the same amount of test results pushing to AppVeyor API, but without a real code?

**Comment by natemcmaster** [comment]
I haven't been able to reproduce this without actual building aspnet/Razor. I'm not convinced the source of the timeout is response time on the appveyor API. I think there it may have something to do with the funky threading/async stuff going on in the aspnet/Razor tests. It may be bleeding over into how the reporter is queuing up its work to send results.

One clue: the tests that cause the appveyor reporter are often using https://github.com/aspnet/Razor/blob/dev/test/Microsoft.AspNetCore.Razor.Design.Test/IntegrationTests/MSBuildProcessManager.cs

cc @rynowak @ajaybhargavb

**Comment by rynowak** [comment]
> I think there it may have something to do with the funky threading/async stuff going on in the aspnet/Razor tests. 

We're not really doing anything novel or tricky. We have some tests that automate MSBuild by shelling out, but they just do normal stuff like `Task.Run`. We're not aborting threads or anything wacky like that. [example run](https://ci.appveyor.com/project/aspnetci/razor/build/1.0.4037)

We also have some tests that use a sync context to simulate a UI-thread, but I haven't seen this problem crop up during that test group.

**Comment by natemcmaster** [comment]
This issue seems to have gone away, and I was never able to get a consistent repro.
