### ISSUE TITLE
The execution's order of multiple InlineData attributes.

### ISSUE THREAD

**Issue by WHATSAF** [xunit/xunit#1633]
I have a test method, has two InlineData attribute. How can i know the sequence of the execution of the InlineData.
Because i need some code to run before the first InlineData executed, and don't run after the others InlineData. Should i must implement it with the external status variable?

**Comment by bradwilson** [comment]
Order is randomized.

I'm not 100% sure based on your description, but it sounds like you want a class fixture. Docs here: https://xunit.github.io/docs/shared-context.html

**Comment by WHATSAF** [comment]
@bradwilson Ok, seems like it's not the xunit's feature. I'll do it myself. Thanks.
