### ISSUE TITLE
Misspelling of Analysers as it appears in package list in Visual Studio 2017

### ISSUE THREAD

**Issue by blackram** [xunit/xunit#1634]
![image](https://user-images.githubusercontent.com/374148/35887798-5ef2cbbc-0be5-11e8-8976-4d1bd3bb12f4.png)

"Code **Analayzers** for xUnit.net" should be "Code Analyzers for xUnit.net" or my preference "Code Analysers for xUnit.net".

Go the S!

**Comment by wachulski** [comment]
@blackram Most analyzers out there are of Z flavour. And it was MS that coined the name, so I'm afraid it must remain (although I prefer British version too).

**Comment by wachulski** [comment]
@blackram Sure, the fix is on its way https://github.com/xunit/xunit.analyzers/pull/98, thx for keeping an eye on that.

**Comment by blackram** [comment]
I saw the pull request, thanks for doing it.



Sent from my Samsung Galaxy smartphone.

-------- Original message --------
