### ISSUE TITLE
Unstable result when using console runner

### ISSUE THREAD

**Issue by BobClaerhout** [xunit/xunit#1635]
From time to time, the xunit.console.x86-runner returns an empty result.
Following xml shows the result:
```xml
<?xml version="1.0" encoding="utf-8"?>
<test-results name="Test results" errors="0" inconclusive="0" ignored="0" invalid="0" not-run="0" date="2018-02-07" time="09:49:58" total="0" failures="0" skipped="0">
  <environment os-version="unknown" platform="unknown" cwd="unknown" machine-name="unknown" user="unknown" user-domain="unknown" nunit-version="xUnit.net 2.2.0.3545" clr-version="32-bit .NET 4.0.30319.42000 [collection-per-class, parallel (2 threads)]" />
  <culture-info current-culture="unknown" current-uiculture="unknown" />
  <test-suite type="Assemblies" name="xUnit.net Tests" executed="True" success="True" result="Success" time="0">
    <results>
      <test-suite type="Assembly" executed="True" name="D:\<PathToDll>\<TestingDll>.DLL" result="" success="" time="">
        <results />
      </test-suite>
    </results>
  </test-suite>
</test-results>
```
When the nunit test result is empty, the xunit output is empty as well.
Our automated build (using bamboo) fails because no test results were found. When rerunning the build (several minutes later) and if we're lucky, the test results aren't empty and we can actually view the results of the test run.

**Edit**
Additional information in the form of logging:
build	07-Feb-2018 09:32:50	xUnit.net Console Runner (32-bit Desktop .NET 4.0.30319.42000)
build	07-Feb-2018 09:32:50	  Discovering: <TestingDll> (app domain = on [shadow copy], method display = ClassAndMethod)
build	07-Feb-2018 09:32:51	  Discovered:  <TestingDll> (running 113 test cases)
build	07-Feb-2018 09:32:51	  Starting:   <TestingDll> (parallel test collections = on, max threads = 2)
.
. All tests listed
.
build	07-Feb-2018 09:32:55	 Finished:    <TestingDll>
build	07-Feb-2018 09:32:55	=== TEST EXECUTION SUMMARY ===
build	07-Feb-2018 09:32:55	   <TestingDll>  Total: 118, Errors: 0, Failed: 0, Skipped: 0, Time: 3,733s

**Comment by bradwilson** [comment]
Please re-open with a repro.

**Comment by Inzanit** [comment]
@BobClaerhout I seem to be having the same issue with Bamboo. Did you ever solve this?

**Comment by urbaniser** [comment]
Just wondered if this was still running fine for you?  We're using 2.4.1 and still experience this on random occasions.

**Comment by BobClaerhout** [comment]
I'm not longer working with the same employer since a couple of months. Before that, we didn't experience any problems with this anymore.

**Comment by kaushikveluru** [comment]
@bradwilson We are seeing the same issue too.
