### ISSUE TITLE
xUnit2002 should not be reported for unconstrained generic types

### ISSUE THREAD

**Issue by sharwell** [xunit/xunit#1637]
Version 0.8.0

```csharp
public class Class<T>
{
  public void Method(IEnumerable<T> collection)
  {
    foreach (T item in collection)
    {
      // Should not report xUnit2002, but currently does
      Assert.NotNull(item);
    }
  }
}
```

**Comment by marcind** [comment]
Wonder if a `: class` constraint on `T` makes the problem go away. Regardless though, this should be fixed as I can see cases where you would want to use this on collections of both value and reference types.

**Comment by wachulski** [comment]
On it.

**Comment by wachulski** [comment]
> Wonder if a : class constraint on T makes the problem go away.

That's true indeed. FYI
