### ISSUE TITLE
String conversion for InlineData that supports nullable types such as decimal?, TimeSpan? and DateTime?

### ISSUE THREAD

**Issue by robert-j-engdahl** [xunit/xunit#1642]
This issue is created as a follow-up on this Twitter thread:

https://twitter.com/robert_engdahl/status/963492556893016067

Basically C# doesn't fully support literal decimals.  Which makes `Theories` with nullable decimal arguments hard to test (`MemberData` and similar works).  The following does not work for any of the `InlineData`:

```
[Theory]
[InlineData(1234m)] //< not supported by C#
[InlineData(1234)] //< int cannot be converted to nullable decimal
[InlineData(1234.0)] //< double cannot be converted  to nullable decimal
[InlineData("1234")] //< string cannot be converted to nullable decimal
[InlineData("1234m")] //< string cannot be converted to nullable decimal
public TestMethod(decimal? someValue) { }
```

It would be very awesome if `[InlineData("1234m")]` worked

**Comment by marcind** [comment]
Are any of these inputs supported in a conversion to a non-nullable decimal?

**Comment by bradwilson** [comment]
The issue is that the CLR has built-in conversions from string to several intrinsics, but no built-in conversions to the nullable equivalents.

**Comment by bradwilson** [comment]
Looked into this on today's live stream, and there isn't anything simple that can be done here. We're expecting MethodInfo.Invoke to do the conversion, and there's not an easy way for us to plumb any kind of custom conversion here. I'm afraid you're going to have to rely on the .NET team to implement this conversion for you.
