### ISSUE TITLE
 How can i pass a test list for dotnet xunit ?

### ISSUE THREAD

**Issue by radhikagadde** [xunit/xunit#1645]
1. How can i pass a specific test list for dotnet xunit ?
2. How can i customize time format during  XML report generation
dotnet xunit -xml "abc"

dotnet --info output:

.NET Command Line Tools (2.0.0)

Product Information:
Version: 2.0.0
Commit SHA-1 hash: cdcd192

Runtime Environment:
OS Name: Windows
OS Version: 10.0.14393
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

Version : 2.0.0
Build : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

Thanks,
Radhika.

**Comment by bradwilson** [comment]
Neither of these things is possible today.

The closest you can get to (1) is repeated using the `-class` and/or `-method` and/or `-trait` switches.

As for (2), the formats are standardized, so they could be post-processed. But there is no custom formatting available in the XML itself.

**Comment by bradwilson** [comment]
Closed as `dotnet xunit` was deprecated.
