### ISSUE TITLE
Unexpected behavior when using long variables in Theory with integer arguments in function (and vise-versa)

### ISSUE THREAD

**Issue by StPaulis** [xunit/xunit#1647]
![image](https://user-images.githubusercontent.com/12777136/36427036-acd5cdd8-1654-11e8-9028-81094cd3d3ed.png)

When I am asking for float[] type as a parameter in my Theory instead of int[] and in the InlineData I am giving an integer value (like the example: 1919,1818... ) then the result is a very unexpected behavior.

The test won't fall or success and I will not be able to build or run my project, unless I 'll restart VS.

When I put an L after the value in the inline data (to convert integer to float). Everything works ok!

**Comment by bradwilson** [comment]
What is the error?

**Comment by StPaulis** [comment]
The error is that after you run a test with int variables as Inline data in theory
and the parameters are long, tests never run and visual studio does not let you build
or do anything with your project unless you restart VS
________________________________
Από: Brad Wilson <notifications@github.com>
Στάλθηκε: Τρίτη, 20 Φεβρουαρίου 2018 6:52 μμ
Προς: xunit/xunit
Κοιν.: Stamatis Pavlis; Author
Θέμα: Re: [xunit/xunit] Unexpected behavior when using long variables in Theory with integer arguments in function (and vise-versa) (#1647)


What is the error?

**Comment by bradwilson** [comment]
Please re-test with 2.4 beta 1.

**Comment by bradwilson** [comment]
If it's still causing the problem, please provide a repro project.

**Comment by bradwilson** [comment]
Please re-open with a repro project.
