### ISSUE TITLE
xunit Tests Deadlocked Specific to Using Azure Key Vault

### ISSUE THREAD

**Issue by adamkjonesmesh** [xunit/xunit#1648]
Hello,

#### Scenario
1. You have a .net core xunit test project.
2. You have more than three test classes.
3. Each test class implements IClassFixture.
4. The class fixture class contains code that uses key vault in the configuration builder.

#### Problem
When you go to Test Explorer in Visual Studio 2017 and select Run All on the tests, the tests will hang and never execute.  None of the tests will even begin to execute.

#### Steps taken to investigate the issue
Investigating this issue, I have found that the problem lies directly in the extension call to AddAzureKeyVault off of IConfigurationBuilder.  Please see code snippets below.  I have found that if you run between 1 and 3 classes that contain tests, they will all run successfully.  Once you add the fourth or any number above four, they will never run.  When you click Run All in the Test Explorer windows, the tests never execute.  Each class implements IClassFixture.  IClassFixture just gives each test class an instance of some base class that contains some common data for each test class.  In my case (see below) each class implements IClassFixture with a GenericClassFixture class.  The GenericClassFixture class contains the code that hydrates some environment variables and then sets up the configuration builder with a call out to key vault.  If you have four test classes or more, and you are debugging, you can break on the configurationBuilder.Build() line (see below) and you will see it get called successfully for each number of test classes you have; however, it will never proceed to the next line of code no matter how long you wait (I have waited for more than 30 minutes before and finally just manually stopped the tests).

### Repro
https://github.com/adamkjonesmesh/sandbox.git

### Expected Scenario
I would expect that the tests would run regardless of how many test classes you have that are calling key vault.

#### Sample Test Class (envision this times 4)
```    
public class TestOne : IClassFixture<GenericStartupFixture>
{
	GenericStartupFixture _fixture;

	public TestOne(GenericStartupFixture fixture)
	{
		_fixture = fixture;
	}

	[Fact]
	public void ShowValueOne()
	{
		Assert.Equal("MeshDev", _fixture.EnvironmentContext);
	}
}
```
#### GenericStartupFixture class
```
public class GenericStartupFixture
{
	public string EnvironmentContext { get; set; }
	public IConfigurationRoot Configuration { get; set; }

	public GenericStartupFixture()
	{
		LoadEnvironmentSettings();
		HydrateConfigurationSettings();
	}

	private void LoadEnvironmentSettings()
	{
		try
		{
			var launchSettingsPath = Path.Combine("Properties", "launchSettings.json");

			using (var file = File.OpenText(launchSettingsPath))
			{
				var reader = new JsonTextReader(file);
				var jObject = JObject.Load(reader);

				var variables = jObject
					.GetValue("profiles")
					.SelectMany(profiles => profiles.Children())
					.SelectMany(profile => profile.Children<JProperty>())
					.Where(prop => prop.Name == "environmentVariables")
					.SelectMany(prop => prop.Value.Children<JProperty>())
					.ToList();

				foreach (var variable in variables)
				{
					Environment.SetEnvironmentVariable(variable.Name, variable.Value.ToString());
				}

				EnvironmentContext = Environment.GetEnvironmentVariable("someenvironmentname");

			}
		}
		catch { }
	}

	private void HydrateConfigurationSettings()
	{
		var azureServiceTokenProvider = new AzureServiceTokenProvider();
		var keyVaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider.KeyVaultTokenCallback));

		var configurationBuilder = new ConfigurationBuilder()
			.AddJsonFile($"appsettings.{EnvironmentContext}.json", optional: true);
		var cfg = configurationBuilder.Build();

		configurationBuilder.AddAzureKeyVault(cfg["KeyVaultUri"], keyVaultClient, new DefaultKeyVaultSecretManager()).AddEnvironmentVariables();

		Configuration = configurationBuilder.Build();
	}
}
```

**Comment by bradwilson** [comment]
Deadlocks are usually caused by application code that is improperly coded for working with `Task` objects. Nothing is obviously wrong at the level of the code you've posted, but you'd have to look inside the implementation to see if there is any use of `.Result` or `.GetAwaiter().GetResult()` on `Task` objects that would be causing deadlocks. The most obvious place to look for these would be to see if there are both sync and async versions of methods, and see if the sync versions (that you're calling) are just delegating to the async methods and doing the inappropriate waits.

A workaround would be to use 2.4 beta 1 of xUnit.net, and seeing `maxParallelThreads` to `-1` in your [JSON config file](https://xunit.github.io/docs/configuring-with-json).

**Comment by bradwilson** [comment]
It's a good idea to move to 2.4 beta 1 anyway since you're using MVC, and we've fixed issues related to the MVC context objects not always working correctly.

**Comment by onovotny** [comment]
FYI, the Key Vault configuration builder does have a Wait() in it.

**Comment by onovotny** [comment]
https://github.com/aspnet/Configuration/blob/dev/src/Config.AzureKeyVault/AzureKeyVaultConfigurationProvider.cs#L46

**Comment by bradwilson** [comment]
And `LoadAsync` is private? Assholes.

**Comment by onovotny** [comment]
You don't get to call it anyway, Load is an override from the base.

**Comment by onovotny** [comment]
On the startup path of ASP.NET Core, they've said it's okay to use Wait(). 

So like in your Configure() method, if you need to create a Cosmos DB and do something with async before the app continues starting up, calling Wait() there is okay too.

**Comment by bradwilson** [comment]
Tweeted: https://twitter.com/xunit/status/966015728242409473

**Comment by alextolp** [comment]
@bradwilson is there a workaround for this issue in xunit 2.3.1?

**Comment by bradwilson** [comment]
@alextolp Set `maxParallelThreads` to `-1`. https://xunit.github.io/docs/configuring-with-json

**Comment by alextolp** [comment]
@bradwilson that doesn’t work in 2.3.1, correct? The fix is available in 2.4.0 beta 1, but I can’t move to that version due to the following issue: https://github.com/xunit/xunit/issues/1665

**Comment by bradwilson** [comment]
Use a build from MyGet: https://myget.org/gallery/xunit

**Comment by alextolp** [comment]
That worked, thanks a bunch!
