### ISSUE TITLE
NUnit migration path from TestFixtureSetupAttribute and TestFixtureTearDownAttribute

### ISSUE THREAD

**Issue by mwpowellhtx** [xunit/xunit#1649]
I need to gain a better understanding how xUnit treats the life cycle of a given set of *Facts*, *Theories*, etc, in the scope of a *test fixture*, so to speak. In particular, consider a migration path from NUnit ``TestFixtureSetupAttribute``/``TestFixtureTearDownAttribute``, which happen *only once* per test fixture, as compared/contrasted with ``SetupAttribute``/``TearDownAttribute``, which happen just prior to and after each ``TestAttribute`` decorated unit test.

I've read in at least one blog along the lines of which *constructor* and/or ``IDisposable`` of a test fixture parameter instance are plausible migration paths, but I would contend potentially not. That is, that the type, class, of the parameter has internal constructor and/or disposable capability.

For what it's worth, I am migrating from [``NUnit`` version 2.6.4](http://www.nuget.org/packages/NUnit/2.6.4), prior to Mr. Poole's purported philosophical changes in unit testing philosophy.

There was also some discussion around [Assembly fixture setup](111), but this is not quite that, I don't think.

Thoughts?

**Comment by mwpowellhtx** [comment]
The [documentation](http://xunit.github.io/docs/comparisons.html) mentions ``NUnit 3.x``, but fails to mention anything about ``NUnit 2.6.4``. Ostensibly we're talking about ``OneTimeSetup``/``TestFixtureSetup`` and/or ``OneTimeTearDown``/``TestFixtureTearDown``, but I could be wrong about that.

**Comment by mwpowellhtx** [comment]
The problem I am running into is this: now combine the notion of fixture/test setup/teardown timing, as relates to a test class *hierarchy* in which I override my test methods. The test fixture must be setup *once*, and the individual setup must occur prior to the *one* test method, at whatever point it is overridden.

I can emulate that only somewhat by capturing the *Fact*/*Theory* level setup in a separate, disposable context. But only somewhat. I think I may need to separate out the actual implementation from the test level lineage, but could be mistaken there.

Thoughts?

**Comment by marcind** [comment]
Have you read this piece of documentation: http://xunit.github.io/docs/shared-context?

**Comment by mwpowellhtx** [comment]
@marcind Yes, scanning through this document, I grasp these concepts, *in and of themselves*, however, I do not see any migration paths from ``SetupAttribute``/``TearDownAttribute``, being resolved just prior to and just after each invocation of *Fact* or *Theory*.

The conclusion I am drawing is that I need to rethink the organization of the test code; perhaps even refactor into a fixture of sorts.

Just didn't know if there are any other *Xunit*-based mechanisms for a migration path.

**Comment by marcind** [comment]
Not being familiar with the details of how that particular version of NUnit works, I can't provide you with a migration path.

All I can say is that in xUnit.Net, if you want to run code just before and just after each test invocation, you put that code in the constructor and `Dispose` method, respectively, of the class containing those tests. This follows standard .NET object hierarchy rules for constructors, for example, if you want to run some code before each and every test in your project, you would put that code in the constructor of a test base class and then have each of your test classes derive from it.

If the above doesn't answer your question, it would help if you asked in the form of _In xUnit, how would I accomplish X?_, rather than _I'm using feature Y of framework Z, does xUnit have the same?_

**Comment by mwpowellhtx** [comment]
I described what it does.

* ``SetupAttribute``: runs just prior to each ``TestAttribute``; in *Xunit*, that's ``FactAttribute`` or ``TheoryAttribute``.
* ``TearDown``: similarly, runs just after.

In and of themselves, the fixture approach gets you as far as emulating ``TestFixtureSetupAttribute``/``TestFixtureTearDownAttribute``, literally setting up, or constructing, the test fixture, or tearing down or disposing of the test fixture.

Like I said, unless, possibly I refactor additional bits of code into the fixtures. Possibly, just wanted to ask about any other bits I may be missing here.

**Comment by bradwilson** [comment]
@mwpowellhtx wrote:

> I do not see any migration paths from SetupAttribute/TearDownAttribute, being resolved just prior to and just after each invocation of Fact or Theory.

That's constructor and implementing `IDisposable.Dispose()` on the test class (the first style of shared context in the documentation).

**Comment by mwpowellhtx** [comment]
@bradwilson Depends on *"which"* ctor/``IDisposable`` we're talking about. I think that's the key. I think it was somewhat illustrated with the notion of *"test data"* I think it was. I modeled it as an ``IScenario``, which itself ``IDisposable``, which I pass into what amounts to simply an *Xunit adapter* of sorts at that point, with the real *"meat"* of the test handled by the scenario, but which is also instantiated in a ``using`` statement in the ``Fact``, or ``Theory``, or what have you.

I'm going to close this issue, per se, in and of itself. Perhaps the docs, however, could see some additional clarification along these lines.

**Comment by bradwilson** [comment]
`IScenario` is something of your construction, not ours. We're obviously not going to document that.

If you create objects which require disposing, then the owning object should dispose it. This is a general rule for the CLR, and has nothing to do with xUnit.net itself. So implement `IDisposable.Dispose()` as the documentation suggests, and dispose whatever objects you've created there.

Teaching people how `IDisposable` is supposed to be implemented is not the purpose of our documentation.

**Comment by mwpowellhtx** [comment]
@bradwilson My point is, not ``IScenario``, per se, but to point out that the parallels aren't quite there as they've been illustrated. Setup/tear-down immediately prior to and after each ``Fact``, ``Theory``, etc, is not the same thing as ctor/``IDisposable``. At least not without further elaboration. ``Test data`` only somewhat alludes to the issue, but not quite, IMO.

Anyway, take it or leave it, for what it's worth. The facts and the truth of the matter are what they are.

**Comment by bradwilson** [comment]
> Setup/tear-down immediately prior to and after each Fact, Theory, etc, is not the same thing as ctor/IDisposable.

It **is** the same in xUnit.net.

**Comment by mwpowellhtx** [comment]
Yes, I realize it is not precisely the same thing. There is also demarcation from the broader fixture level setup/tear-down, which happens only once per fixture. This simple **CANNOT** be the same ctor/``IDisposable``? This is the difference. I understand it's not like *"scenario"* is intercepting the ``Fact`` or ``Theory`` invocation, that sort of thing, but it is a close enough approximation for my purposes.

**Comment by bradwilson** [comment]
You should re-read the docs.

We have three levels of "fixture":

1. the test class itself (which is created & destroyed for every test)
2. a class-level fixture (which is created & destroyed for every test class)
3. a collection-level fixture (which is created & destroyed for every test fixture)

They are implemented as:

1. ctor & `Dispose` on the _test class_
2. ctor & `Dispose` on the _fixture class_, and decorated with `IClassFixture<T>`
3. ctor & `Dispose` on the _fixture class_, and decorated with `ICollectionFixture<T>`

**Comment by mwpowellhtx** [comment]
I'm starting to see it. I'm not sure what ``ICollectionFixture<T>`` is all about, or I may not have a use case for it today, but I sort of get it. Thanks.

**Comment by bradwilson** [comment]
Test collections are groups of test classes, which serves two purposes:
- They can share zero or more fixtures, as discussed here: https://xunit.github.io/docs/shared-context#collection-fixture
- Tests in the same collection will not be run in parallel against each other, as discussed here: https://xunit.github.io/docs/running-tests-in-parallel#parallelism-in-test-frameworks

By default, each test class has its own unique, implicit test collection (the default behavior can be overridden as discussed in the 2nd link).

**Comment by mwpowellhtx** [comment]
So, this appears to be [key](http://xunit.github.io/docs/shared-context): *"We already know that xUnit.net creates a new instance of the test class for every test."*. So, in effect, the *ctor*/*IDisposable* for each test class is like the *Setup*/*TearDown*, whereas, at the *"class/'fixture'"* level, that is ``IClassFixture<T>``.

So, internally, I inject an ``IScenario``, ostensibly rather ``ITestFixture`` is a better name for it, whose life cycle is the same as that of the test class itself, i.e. is initialized then disposed along with the test class.

Bingo! I think I've got it. Thanks !
