### ISSUE TITLE
ConnectionStrings not loading correctly

### ISSUE THREAD

**Issue by mwpowellhtx** [xunit/xunit#1653]
This is a strange issue. My ``System.Configuration.ConfigurationManager.ConnectionStrings`` are not loading correctly. I think they are possibly *"loading"* (so-called) from a ``machine.config`` I have someplace on the machine. How I know this is because the configuration that is there is by the key ``"LocalSqlServer"``. However, my configuration should reflect this:

```Xml
<connectionStrings>
    <add name="MasterConnectionString" connectionString="Server=localhost;Database=master;Integrated Security=true" />
</connectionStrings>
```

However, this ``name`` does not exist, returns ``null``. I've tried adding a ``<clear/>`` line, but that does not work, either.

Methinks this is possibly an ``Xunit`` runner issue not loading the assembly correctly.

Which, incidentally, this was working prior to migration to ``Xunit``, from ``NUnit``. I'm not just sure quite what the issue is.

**Comment by bradwilson** [comment]
Please provide a repro project.

**Comment by mwpowellhtx** [comment]
@bradwilson Not a repro, yet, but I do have a stack trace to begin with. I wonder if this has to do with how ``AppDomain`` is handled between ``xUnit`` and ``NHibernate``? At least one StackOverflow would seem to [indicate as much](http://stackoverflow.com/questions/48641137/filenotfoundexception-for-cefsharp-when-running-xunit-test); not concerning ``NHibernate``, per se, but along similar lines. I have followed up via NHibernate, as well as R#, channels as well, to gain further insights.

```
System.IO.FileNotFoundException was unhandled by user code
  FileName=NHibernate, Version=4.0.0.4000, Culture=neutral, PublicKeyToken=aa95f207798dfdb4
  FusionLog==== Pre-bind state information ===
LOG: DisplayName = NHibernate, Version=4.0.0.4000, Culture=neutral, PublicKeyToken=aa95f207798dfdb4
 (Fully-specified)
LOG: Appbase = file:///C:/Users/Michael/AppData/Local/JetBrains/Installations/ReSharperPlatformVs14/
LOG: Initial PrivatePath = NULL
Calling assembly : FluentNHibernate, Version=2.0.3.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\Users\Michael\AppData\Local\JetBrains\Installations\ReSharperPlatformVs14\JetBrains.ReSharper.TaskRunner.CLR45.x64.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: NHibernate, Version=4.0.0.4000, Culture=neutral, PublicKeyToken=aa95f207798dfdb4
LOG: Attempting download of new URL file:///C:/Users/Michael/AppData/Local/JetBrains/Installations/ReSharperPlatformVs14/NHibernate.DLL.
LOG: Attempting download of new URL file:///C:/Users/Michael/AppData/Local/JetBrains/Installations/ReSharperPlatformVs14/NHibernate/NHibernate.DLL.
LOG: Attempting download of new URL file:///C:/Users/Michael/AppData/Local/JetBrains/Installations/ReSharperPlatformVs14/NHibernate.EXE.
LOG: Attempting download of new URL file:///C:/Users/Michael/AppData/Local/JetBrains/Installations/ReSharperPlatformVs14/NHibernate/NHibernate.EXE.
LOG: Attempting download of new URL file:///G:/Source/Kingdom Software/Kingdom.Foundations/Prototype/src/Kingdom.Data.Repository.Hibernate.Fluent.Tests/bin/Debug/NHibernate.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Minor Version
LOG: Attempting download of new URL file:///G:/Source/Kingdom Software/Kingdom.Foundations/Prototype/src/Kingdom.Data.Repository.Hibernate.Fluent.Tests/bin/Debug/NHibernate/NHibernate.DLL.
LOG: Attempting download of new URL file:///G:/Source/Kingdom Software/Kingdom.Foundations/Prototype/src/Kingdom.Data.Repository.Hibernate.Fluent.Tests/bin/Debug/NHibernate.EXE.
LOG: Attempting download of new URL file:///G:/Source/Kingdom Software/Kingdom.Foundations/Prototype/src/Kingdom.Data.Repository.Hibernate.Fluent.Tests/bin/Debug/NHibernate/NHibernate.EXE.

  HResult=-2147024894
  Message=Could not load file or assembly 'NHibernate, Version=4.0.0.4000, Culture=neutral, PublicKeyToken=aa95f207798dfdb4' or one of its dependencies. The system cannot find the file specified.
  Source=Kingdom.Data.Repository.Hibernate.Fluent
  StackTrace:
       at Kingdom.Data.Repository.Hibernate.Fluent.FluentHibernateSessionFactoryConfigurationManager`1.CreateManagedConfiguration(TManagerConfig managerCfg)
       at Kingdom.Data.Repository.Hibernate.Fluent.FluentHibernateSessionFactoryConfigurationManager`1.CreateSessionFactory(TManagerConfig managerCfg) in G:\Source\Kingdom Software\Kingdom.Foundations\Prototype\src\Kingdom.Data.Repository.Hibernate.Fluent\Core\FluentHibernateSessionFactoryConfigurationManager.cs:line 196
       at Kingdom.Data.Repository.Hibernate.Fluent.FluentHibernateSessionFactoryConfigurationManager`1.CreateSession(String connectionString) in G:\Source\Kingdom Software\Kingdom.Foundations\Prototype\src\Kingdom.Data.Repository.Hibernate.Fluent\Core\FluentHibernateSessionFactoryConfigurationManager.cs:line 60
       at Kingdom.Data.Repository.SessionFactoryManagerBase`3.get_Item(String connectionString) in G:\Source\Kingdom Software\Kingdom.Foundations\Prototype\src\Kingdom.Data.Repository\Core\SessionFactoryManagerBase.cs:line 97
       at Kingdom.Data.Repository.Hibernate.Fluent.Modules.MigrationManagerModule.<>c__DisplayClass2_0`1.<BuildMigrationManager>b__0(PreparingEventArgs args) in G:\Source\Kingdom Software\Kingdom.Foundations\Prototype\src\Kingdom.Data.Repository.Hibernate.Fluent.Tests\Modules\MigrationManagerModule.cs:line 46
       at Autofac.Core.Registration.ComponentRegistration.RaisePreparing(IComponentContext context, IEnumerable`1& parameters)
       at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
       at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
       at Autofac.Core.Resolving.InstanceLookup.Execute()
       at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
       at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
  InnerException: 
  ```

**Comment by bradwilson** [comment]
Using configuration files definitely requires app domains to be enabled (so the only supported platform for configuration files is desktop CLR w/ app domains).

Your code may not properly support shadow copying. You could try disabling that to see if the tests starts passing.

**Comment by bradwilson** [comment]
Also, it looks like you're using the Resharper runner. We don't officially support that (JetBrains does), so please try running the tests with one of the supported runners (like our console runner).

**Comment by mwpowellhtx** [comment]
@bradwilson Thanks for the feedback. I'm looking into all these avenues. Not convinced it is Xunit, per se; probably more a combination of Fluent/NHibernate+R# migration paths.

**Comment by mwpowellhtx** [comment]
I'm not sure why *Configuration* is unsupported? I checked, R# was shadow copying, but I disabled this feature. Beyond that, I'm not sure why *Configuration* does not work on a sudden. Oddly, it does appear to find the System ``master.config``. My ``app.config`` is configured properly to land in the output folder.

It would seem that I can sort of workaround it, but assuming ``System.Configuration`` is really that antiquated, obsolete, or there is a better, more contemporary way to do things via configuration, I'm open to suggestions. The default paths to Configuration are, however, broken; it would seem that the parent host would have its own configuration, not necessarily the assembly under test.

```C#
using System.Configuration;
uisng System.Reflection;
// ...
var cfg = ConfigurationManager.OpenExeConfiguration(Assembly.GetExecutingAssembly().Location);
var x = cfg.ConnectionStrings.ConnectionStrings["MasterConnectionString"].ConnectionString;
```

I'm still not 100% sure why that's different from ``NUnit`` to ``Xunit``, however.

**Comment by bradwilson** [comment]
Configuration files are only supported on desktop CLR, because they are a feature that only applies to desktop CLR. So it's not that they're unsupported, but rather that they are only supported in a limited scenario. This actually has nothing to do with xUnit.net itself, but rather with the platform(s) you're testing on. We don't do anything to explicit enable (or disable) support for Configuration; that's the behavior of the platforms.

As for what's happening with Resharper, as I mentioned previously, we don't support Resharper (JetBrains does). So if the issue is isolated to Resharper, then you will need to go to JetBrains to get it resolved. I suggested using one of the runners that we wrote (specifically, the desktop CLR console runner) so that we can rule in or rule out issues related to Resharper.

**Comment by mwpowellhtx** [comment]
Thanks for that clarification.

I'm parsing through the dependency issue; not sure it's 100% R#, per se; possibly more of a Fluent/NHibernate (mistaken?) strong name assembly reference. Which artificially, IMO, prohibits any interim NHibernate migration paths from the POV of the Fluent stack. Assuming that's an accurate assessment of what's going on there.

If I downgrade NHibernate to 4.0.0.4000, funnily enough, half-expected, the tests run successfully, and to passing completion.

Anyhow, have followed up on those within those channels.

**Comment by bricelam** [comment]
This has *finally* been unblocked in .NET 6. I've submitted PR #2420 to enable tests to use ConfigurationManager.
