### ISSUE TITLE
Xunit silently ignores xunit.runner.json when the file contains comments

### ISSUE THREAD

**Issue by ChristopherHaws** [xunit/xunit#1654]
### Issue description
Xunit silently ignore the `xunit.runner.json` settings when the file contains commented lines.

### Steps to reproduce the issue
1.  Add an `xunit.runner.json` file to you project with the following content and `Copy to Output Directory` set to `Copy if newer`:
```json
{
	"parallelizeAssembly": true,
	"methodDisplay": "method"
}
```
2. Build your project and notice that the tests show up with just the method name
3. Modify the `xunit.runner.json` file to look like the following:
```json
{
	//"parallelizeAssembly": true,
	"methodDisplay": "method"
}
```
4. Build your project and notice that the tests show up with the class name and method name

### What's the expected result?
One of the following should happen:
- The commented line should be ignored and the settings should be read correctly
- The test run should fail with an error logged to the test output window
- The test run should continue with an error logged to the output window

### What's the actual result?
The tests run with all of the default settings and no errors or warnings are logged.

### Additional details
While it is true that comments are not formally accepted in json files, there are many parsers that support them. One simple solution could be to read the json file, strip it of any lines starting with `//` and then pass it along to the parser.

**Comment by bradwilson** [comment]
We're not planning on supporting this.

A work-around exists: just change the name of the key to something that's not valid (using your example, change `"parallelizeAssembly"` to `"_parallelizeAssembly"`).

**Comment by ChristopherHaws** [comment]
Your workaround will work for me. I still think it would be nice to have some kind of log message stating that the config file was not valid and the default values are being used. I spent almost an hour today trying to figure out why something wasn't working and it turned out to be a comment in the xunit.runner.json file. :)

**Comment by RedX2501** [comment]
@ChristopherHaws JSON generally does NOT support comments. Not only in this project you will have problems if you add comments to JSON files and expect them to work. https://www.json.org/

**Comment by ChristopherHaws** [comment]
@RedX2501 The new `System.Test.Json` package from Microsoft has support for it:

```csharp
void Main()
{
    var json = @"{
        //""parallelizeAssembly"": true,
        ""methodDisplay"": ""method""
    }";
    
    var settings = JsonSerializer.Parse<XunitRunnerSettings>(json, new JsonSerializerOptions
    {
        ReadCommentHandling = JsonCommentHandling.Skip,
        PropertyNameCaseInsensitive = true
    });
}

public class XunitRunnerSettings
{
    public Boolean ParallelizeAssembly { get; set; }
    public String MethodDisplay { get; set; }
}
```

**Comment by bradwilson** [comment]
@ChristopherHaws v3 is using `System.Text.Json`: https://github.com/xunit/xunit/blob/d53d0761f997ae132b9147c2347659029c9d0e23/src/xunit.v3.runner.common/Frameworks/_TestFrameworkOptions.cs#L25
