### ISSUE TITLE
FYI: if you use Console Runner and start to get exceptions for accessing https recently

### ISSUE THREAD

**Issue by xied75** [xunit/xunit#1659]
Dear all,

Just encountered this, I used to have some tests accessing https fine (two months ago), now it will throw:

```
---- System.Net.WebException : The request was aborted: Could not create SSL/TLS secure channel.
```
(In my case the target host is GitHub.com,
https://developer.github.com/changes/2018-02-01-weak-crypto-removal-notice/)

After some googling, I found this to be the most easy solution without touching my code:
https://stackoverflow.com/questions/44751179/tls-1-2-not-negotiated-in-net-4-7-without-explicit-servicepointmanager-security

Lots other people suggest you to modify your code to specify TLSv1.2, but I prefer the solution for running the Console Runner by adding this to the runner config file:

```
<runtime>
   <AppContextSwitchOverrides value="Switch.System.ServiceModel.DisableUsingServicePointManagerSecurityProtocols=false;Switch.System.Net.DontEnableSchUseStrongCrypto=false" /> 
</runtime>
```

p.s. Anyone can suggest how to do similar things for VS runner?

**Comment by bradwilson** [comment]
In general, I'm usually reluctant to make changes like this (which conditionally change the behavior of the runner), for two reasons: (a) the change is truly conditional, based on whether the framework understands that switch or not; and (b) changing the default behavior of the framework makes it impossible to know whether your code runs correctly against the unmodified framework.

I'd be much more likely to support the idea of just compiling the console runner against several versions of the desktop CLR, and letting people choose at test run time which one they would want.

**Comment by bradwilson** [comment]
Subsumed by #1709.

**Comment by olsh** [comment]
The TLS issue still exists when `dotnet test` command is used.
Even if I specify the target framework to net471.

**Comment by bradwilson** [comment]
Using `dotnet test` always runs the .NET 4.5.2 version of the console runner. The only available workaround today is to call `xunit.console.exe` of your preferred framework, rather than using `dotnet test`.

**Comment by thomazmoura** [comment]
> Using dotnet test always runs the .NET 4.5.2 version of the console runner. The only available workaround today is to call xunit.console.exe of your preferred framework, rather than using dotnet test.

@bradwilson  Does that mean that even today you can't actually use xunit to run integration tests that access TLS 1.2 resources when running the tests from Visual Studio and dotnet test?

I've been trying to make this work on Visual Studio for a while now, but unfortunately Visual Studio seems to always target 4.5.2 while running xunit tests. The same tests work fine if run with MS Test (switching the Fact to TestMethod and adding the TestClass annotations). I'm using the xunit.runner.visualstudio nuget package, by the way.

Is there no way to force Visual Studio to use a > 4.6 version of the runner or something like?

**Comment by bradwilson** [comment]
>@bradwilson Does that mean that even today you can't actually use xunit to run integration tests that access TLS 1.2 resources when running the tests from Visual Studio and dotnet test?

For .NET Framework tests, that's still true, yes.

This is something that should get fixed with v3 given the new design (your tests become an executable program rather than a DLL).

**Comment by ohadschn** [comment]
I'm seeing this too when using the Visual Studio test explorer
1. I reckon the VS test explorer uses the same logic `dotnet test` namely executes the .NET 4.5.2 runner?
1. How is this even issue? If I have the .NET 4.8 installed on my machine, that's an in-place replacement for .NET 4.5.2, so I would expect the `ServicePointManager` to be loaded with the .NET 4.8 defaults (which support TLS 1.2)?
