### ISSUE TITLE
Unable to share an ambient transaction (TransactionScope) between tests in a class fixture

### ISSUE THREAD

**Issue by mariusin79** [xunit/xunit#1661]
I write some bdd-style tests which means i run Given/When once for the class fixture and multiple assertions (Facts) afterwards. The shared state:

    public class Fixture : IDisposable, IScenario
    {
        public TransactionScope TransactionScope { get; set; }

        public Fixture()
        {
            TransactionScope = TransactionScopeFactory.Create();
        }

        ~Fixture()
        {
            DisposeInternal();
        }

        public virtual void Dispose()
        {
            DisposeInternal();
            GC.SuppressFinalize(this);
        }

        private void DisposeInternal()
        {
            if (TransactionScope != null)
            {
                TransactionScope.Dispose();
                TransactionScope = null;
            }
        }
    }

The problem: System.Transactions.Transaction.Current returns null in the class constructors using the shared state:

public class ClassScenario<T> : IClassFixture<T> where T : Fixture

// ctor
protected ClassScenario(T fixture)
{
    System.Transactions.Transaction.Current == null;
}
And the transactionscope is initialized with TransactionScopeAsyncFlowOption.Enabled.

**Comment by bradwilson** [comment]
Fixtures are not created on the same "async flow" as the tests (even the tests themselves don't share an async flow, much less the build-up and tear-down).

You should be able to share a `TransactionScope` instance, but it won't flow between tests (or the fixture) via `.Current`. You should make the instance of the scope available via the fixture.

**Comment by mariusin79** [comment]
I understand that, but that defeats the purpose of an ambient transaction, hence this feature request :-) This is something that has been possible to do since the days of (even) mstest.

**Comment by bradwilson** [comment]
We cannot accommodate this feature request, technically.
