### ISSUE TITLE
was there any easy way to add AutoFac and NHibernate support ?

### ISSUE THREAD

**Issue by sgf** [xunit/xunit#1666]
was there any easy way to add AutoFac and NHibernate support ?

recently i take  some time to add Autofac in Xunit.
but faild,im not know much for Xunit details.
i cant find out an easy way to add AutoFac to test my Service Code.

so,im create this issues ask for some help.

**Comment by bradwilson** [comment]
I'm sorry, I'm not familiar with either product. You might get more help asking users of those projects how they integrate with xUnit.net.

**Comment by sgf** [comment]
thank you.
