### ISSUE TITLE
Improve Display name for "params object[]" in Theory

### ISSUE THREAD

**Issue by osjimenez** [xunit/xunit#1667]
I create a very specific scenario, my code:

	public static IEnumerable<object[]> Generate()
	{
		yield return new[] { "VAL1.1", "VAL2.1", "VAL3.1", "VAL4.1", "VAL5.1", "VAL6.1" };
		yield return new[] { "VAL1.2", "VAL2.2", "VAL3.2", "VAL4.2", "VAL5.2", "VAL6.2" };
	}
	[Theory(DisplayName = "MyName")]
	[MemberData(nameof(Generate))]
	public void MyTestTheory1(params object[] _) { }
	[Theory(DisplayName = "MyName")]
	[MemberData(nameof(Generate))]
	public void MyTestTheory2(string p1, string p2, string p3, string p4, string p5, string p6) { }

This show as:

![image](https://user-images.githubusercontent.com/4103496/37395953-d89aee60-2777-11e8-812c-c45ccbbd3291.png)

I prefer "MyTestTheory1" display way, without parameters names, because the value of each parameter say me all that i need, but, the problem is than only show the five first parameters.

It's possible to show all parameters of my "params object[] _" array?

**Comment by bradwilson** [comment]
There is no way to tweak this today. It is hard coded here: https://github.com/xunit/assert.xunit/blob/6263e7b3d894ccee8c3afbd080e8f76410aa6c8f/Sdk/ArgumentFormatter.cs#L18

Ideally a generalized support for customizing display names (including method arguments) should be part of the conversation here: #1429, so closing this as a duplicate
