### ISSUE TITLE
Add assert for near identical datetimes

### ISSUE THREAD

**Issue by kbilsted** [xunit/xunit#1668]
It would be very productive to be able to compare datetimes that are almost identical. Eg. storing a date in the db and fetching it again may be subject to rounding. I've made a PR for the assert at https://github.com/xunit/assert.xunit/pull/25

**Comment by bloritsch** [comment]
Yes and please.  This is very useful in expiration tests that depend on DateTime.Now or DateTime.UtcNow.

**Comment by normanhh3** [comment]
Something like what was done here look like a good start?

https://www.automatetheplanet.com/assert-datetime-mstest-nunit/

**Comment by bradwilson** [comment]
Merged with xunit/assert.xunit#25.
