### ISSUE TITLE
Improving `Assert` API to simplify the collection asserting.

### ISSUE THREAD

**Issue by PMExtra** [xunit/xunit#1671]
Could we consider adding some APIs in `Assert` to simplify the following operations?

#### ~~Now:~~

```
Assert.True(exceptedEnumerable.SequenceEqual(actualEnumerable));
```

#### ~~Want:~~

```
Assert.SequenceEqual(exceptedEnumerable, actualEnumerable);
```

#### Now:

```
Assert.Empty(exceptedCollection.Except(actualCollection));
Assert.Empty(actualCollection.Except(exceptedCollection));
```

#### Want:

```
Assert.SetEqual(exceptedCollection, actualCollection);
```

**Comment by PMExtra** [comment]
Ok, I found the `Assert.Equal<T>(IEnumerable<T> excepted, IEnumerable<T> actual)` can replace `SequenceEqual`.
But how about the `SetEqual`? (For Set<T> or ICollection<T> that order doesn't matter)

**Comment by bradwilson** [comment]
I think I'd prefer two new Equal methods:

1. Something set-specific
2. An overload of Equal with IEnumerable to say "order is not important".

**Comment by GiancarloLelli** [comment]
Hi @bradwilson 
I would like to help out on this. Can you help me get started? :)

**Comment by sdelarosbil** [comment]
> I think I'd prefer two new Equal methods:
> 
>     1. Something set-specific
> 
>     2. An overload of Equal with IEnumerable to say "order is not important".

I would like to help with this, but I have some questions about how this would work.

Well, (1) to me seems straight forward: do what Equal did, but with ISet. The confusion comes with (2): what is the best way to indicate the order isn't important while preserving the method's name? I would think the best way to distinguish between with or without order would be the naming.

That being said, if point (1) is enough for now, I could submit a pr with just that one for now, what do you think?

**Comment by bradwilson** [comment]
Sorry, this has already been done, and needs to be closed.
