### ISSUE TITLE
xUnit3001 warning - blech

### ISSUE THREAD

**Issue by jherby2k** [xunit/xunit#1672]
I don't like this new analyzer. I thought it was a bug at first, but its apparently a feature.

"Classes that implement Xunit.Abstractions.IXunitSerializable must have a public parameterless constructor"

a) My classes do have an implicit public parameterless constructor. Why isn't that good enough?
b) https://xunit.github.io/xunit.analyzers/rules/xUnit3001 says to add an [Obsolete] attribute. I don't want to mark them as obsolete. I want to create instances of my test classes.

At least ignoring b) doesn't trigger another analyzer warning.

**Comment by bradwilson** [comment]
We should definitely be okay with no constructors (i.e., implicit ctor). This sounds like a bug.

**Comment by jherby2k** [comment]
cool! Thanks. Happens with beta1 and beta2 off myget.
