### ISSUE TITLE
Xunit.Runner.VisualStudio.VsDiscoverySink.Finish seems to hang in the latest Visual Studio 2017 versions 15.5.x to current 15.6.3

### ISSUE THREAD

**Issue by kae36** [xunit/xunit#1674]
This started showing up in Visual Studio as the testhost.x86.exe process would not exit and relinquish the hold on the .dll file.  It also shows up as test discovery never finishes.  Most of the troubleshooting is at this link on the Visual Studio developer community.
https://developercommunity.visualstudio.com/content/problem/205144/cannot-rebuild-due-to-dll-files-being-held-open-by.html

There is a simple Visual Studio test solution at https://github.com/kae36/TimeTesterSolution where the problem shows up.

The following is a comment from Sarabjot Singh [MSFT] on the Visual Studio Developer Community.

`I was able to reproduce the issue. The process seems to waiting at the below call stack.
Seems like the adapter is waiting, can you please log an issue here https://github.com/xunit/xunit

xunit.runner.visualstudio.testadapter.dll!Xunit.Runner.VisualStudio.VsDiscoverySink.Finish() Line 133

xunit.runner.visualstudio.testadapter.dll!Xunit.Runner.VisualStudio.VsTestRunner.DiscoverTestsInSource<System.__Canon>(Xunit.XunitFrontController framework, LoggerHelper logger, Xunit.Runner.VisualStudio.TestPlatformContext testPlatformContext, System.Func<string, Xunit.Abstractions.ITestFrameworkDiscoverer, Xunit.Abstractions.ITestFrameworkDiscoveryOptions, System.__Canon> visitorFactory, System.Action<string, Xunit.Abstractions.ITestFrameworkDiscoverer, Xunit.Abstractions.ITestFrameworkDiscoveryOptions, System.__Canon> visitComplete, string assemblyFileName, bool shadowCopy, Xunit.TestAssemblyConfiguration configuration) Line 272

xunit.runner.visualstudio.testadapter.dll!Xunit.Runner.VisualStudio.VsTestRunner.DiscoverTests<Xunit.Runner.VisualStudio.VsDiscoverySink>(System.Collections.Generic.IEnumerable<string> sources, LoggerHelper logger, Xunit.Runner.VisualStudio.TestPlatformContext testPlatformContext, System.Func<string, Xunit.Abstractions.ITestFrameworkDiscoverer, Xunit.Abstractions.ITestFrameworkDiscoveryOptions, Xunit.Runner.VisualStudio.VsDiscoverySink> visitorFactory, System.Action<string, Xunit.Abstractions.ITestFrameworkDiscoverer, Xunit.Abstractions.ITestFrameworkDiscoveryOptions, Xunit.Runner.VisualStudio.VsDiscoverySink> visitComplete) Line 214

xunit.runner.visualstudio.testadapter.dll!Xunit.Runner.VisualStudio.VsTestRunner.Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ITestDiscoverer.DiscoverTests(System.Collections.Generic.IEnumerable<string> sources, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IDiscoveryContext discoveryContext, Microsoft.VisualStudio.TestPlatform.ObjectModel.Logging.IMessageLogger logger, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ITestCaseDiscoverySink discoverySink) Line 103
`

**Comment by akrobet** [comment]
Having similar/the same with VS 15.7.1. XUnit tests are discovered, but when running them, the test runner just hangs.

**Comment by bradwilson** [comment]
Dup of #1644
