### ISSUE TITLE
Cannot run dotnet xunit with NetCoreApp2.1 and dotnet core 2.1 preview1 runtime

### ISSUE THREAD

**Issue by SaltyDH** [xunit/xunit#1675]
Hi,

I'm trying to use the dotnet xunit cli on a test project that has NetCoreApp deps.

Using internal diagnostics, I extracted the lines from the tmp file that's created when dotnet xunit cli discovers the Framework info:

```
TargetFrameworkIdentifier: .NETCoreApp
TargetFrameworkVersion: v2.1
RuntimeFrameworkVersion: 2.1.0-preview1-26216-03
```

An Input string format exception is thrown on the line below because the RuntimeFrameworkVersion doesn't adhere to the dotted notation that `System.Runtime's Version` is expecting.

https://github.com/xunit/xunit/blob/master/src/dotnet-xunit/Program.cs#L348

Because of the order of this line and the lines below it, I'm unable to override this behaviour using the FxVersion command line switch.

**Comment by SimplerSoftware** [comment]
I'm not positive but I believe I'm running into the same issue.  When I run my tests they all fail with different  errors trying to load assemblies.  The gist of the error messages is: "Could not load file or assembly 'Microsoft.AspNetCore.XXX Version=2.1.0.0'.  The system cannot find the file specified.

**Comment by SaltyDH** [comment]
I'm having better luck with dotnet vstest, might be worth a go depending on your needs

**Comment by SimplerSoftware** [comment]
@SaltyDH - Thanks!  That got things working for me as well.

**Comment by roji** [comment]
And same here, running on .NET Core 2.1.0-rc1, dotnet-xunit 2.4.0-beta.1.build3958.

**Comment by roji** [comment]
Great, thanks @bradwilson

**Comment by bradwilson** [comment]
Yeah, that's definitely just a work-around and not a fix, so if someone is doing a PR, it needs a real fix. :)

**Comment by stvndall** [comment]
Unfortunately, due to Microsoft ONLY putting 2.1.0-x versions onto bionic library, I am forced into this test runner that doesn't work.

**Comment by tlycken** [comment]
FWIW, adding `<RuntimeFrameworkVersion>2.1.0-rc1</RuntimeFrameworkVersion>` to the csproj file of my test project worked for me. Still not a fix, but something an xUnit user can do while waiting for the real fix.

**Comment by bradwilson** [comment]
You can test this (without your workaround) by pulling the latest build from [MyGet](https://myget.org/gallery/xunit).

**Comment by cod7alex** [comment]
With latest version from MyGet i get `The specified framework 'Microsoft.AspNetCore.All', version '2.1.0-rc1' was not found.` even though version is `2.1.0-rc1-final`.

**Comment by bradwilson** [comment]
@cod7alex Please open a new issue with a repro project. Thanks!

**Comment by moh-hassan** [comment]
JFI, dotnet xunit is removed starting from xunit 2.4 [Ref: Release Notes 2.4 ](https://xunit.github.io/releases/2.4)
>Unfortunately, this release also removes the dotnet xunit runner, as the stability of the runner was never perfect, and it suffered from many assembly-loading related issues. Users from .NET Core can continue to use VSTest (either inside Visual Studio, or via dotnet test).
