### ISSUE TITLE
Migration path for NUnit Inconclusive

### ISSUE THREAD

**Issue by mwpowellhtx** [xunit/xunit#1676]
I suppose I could throw an exception, something like that. However, I would like to capture a result that is ``"inconclusive"``. In ``NUnit`` parlance, for instance, that is something like:

```C#
Assert.Inconclusive("message format", [args...]);
```

In this instance, I do not necessarily want to throw an exception. I just want to signal that the unit test results are inconclusive.

**Comment by bradwilson** [comment]
We do not have any intention to support "inconclusive" tests. xUnit.net is designed for automated unit testing, and we believe such a state is invalid for unit tests.

**Comment by RussKie** [comment]
This is a very poor response IMO.
Users may have different requirements to dynamically ignore tests _within_ the framework of running automated tests. But the current design outright makes it impossible.

Windows Forms has tests that require STA decorations, and thus unable to use `SkippableFact` attributes. 
We also must detect whether certain Windows capabilities are installed and available, and bail out if these capabilities are not available. We can only do so at runtime.
