### ISSUE TITLE
Migration path for NUnit TestCaseSourceAttribute

### ISSUE THREAD

**Issue by mwpowellhtx** [xunit/xunit#1677]
``NUnit`` offers a way of specifying a range of theorized ``InlineDataAttribute`` entries, loosely translating to ``Xunit`` parlance, in the form of ``TestCaseSourceAttribute``. I was wondering if there is a migration path into ``Xunit`` along these lines?

Doing a bit of ecosystem reading, potentially this falls under the purview of [xunit.combinatorial](/AArnott/Xunit.Combinatorial/issues/15) for best possible results, I'm not sure.

**Comment by mwpowellhtx** [comment]
Actually, lo and behold, I ran across [this](http://andrewlock.net/creating-parameterised-tests-in-xunit-with-inlinedata-classdata-and-memberdata/) helpful article on the subject. This will work perfectly!

**Comment by mwpowellhtx** [comment]
@bradwilson Actually I do have one follow on question. It seems like the ``*Data`` decorations prefer static members to instance ones. I can work with that, provided the ``Theory`` and ``*Data`` attributes, taken together, roll up as inherited attributes. So my question is simply that: do they roll up as inherited attributes?

I ask because I have a case where I know the Theory blueprint at a base class level, but I do not know the specific test cases until the point at which the abstract base class is derived. It would be fine for me to provide the test cases statically at that level along with the corresponding ``*Data`` attribute, provided the base class ``Theory`` decoration is rolled up accordingly.

i.e.

```C#
[Theory]
public virtual void MyTheory(...)
{
}

// ...

[*Data]
public override void MyTheory(...)
{
  base.MyTheory(...);
}
```

Yes, I know there is no ``*Data``, per se; replace with, say, ``ClassData``, etc.

Does this make sense?

**Comment by bradwilson** [comment]
Honestly, I've never tried this, so I don't know what it would do. I assume if the base were in an abstract class, it wouldn't try to run it (since it's not runnable as-is), and then everything would just work, but I'm not 100% sure.
