### ISSUE TITLE
The warning description in `xUnit2013` is incorrect

### ISSUE THREAD

**Issue by westonpace** [xunit/xunit#1678]
The wording on this warning does not match what is actually being checked.  The error currently states: `Do not use Assert.Equal() to check for collection size.`  However, the warning is issued when using Assert.Equal to check if a collection is empty (in which case `Assert.Empty` is better) or to check if a collection has a single item (in which case `Assert.Single` is better).  The warning is factually incorrect because there are times when `Assert.Equal` is the correct way to check collection size (any time the size is greater than 1).  This makes it very confusing to understand.

Every few months I run into this warning and have to search the internet to figure out again what is going on.  This has caused at least one [Stackoverflow question](https://stackoverflow.com/questions/46653557/whats-the-idiomatic-way-to-verify-collection-size-in-xunit) and I suspect is a large portion of the motivation behind #1423.

Ideally it should be broken into two warnings:

 * Assert.Single should be used to test if a collection has a single element
 * Assert.Empty should be used to test if a collection is empty

Or, if it is easier to leave as one warning

 * Assert.Single and Assert.Empty should be used to test if collections contain a single element or are empty.

I'll try and submit a PR later.

**Comment by annayafi** [comment]
By the way, when you use Assert.Single(faultedTasks) where faultedTasks is a collection of Tasks where at least one is faulted, this assert crashes the whole test so you're forced to use  Assert.Equal(1, faulted.Count());

**Comment by ben-reilly** [comment]
I'd like to put my vote in for splitting the warning. It would help to address this issue, but it would have the added benefit of allowing users to decide how to handle the 0-comparison and 1-comparison separately.

I personally have cases where a collection is of size 1, but it's fairly incidental and is likely to change if the test is altered: I would prefer to use `Assert.Equal` here so that the collection size can change without having to swap between assertion syntaxes.

Conversely, it's usually intentional when a collection should be empty/non-empty, so the warning and proposed correction are helpful there.

**Comment by winiciuscota** [comment]
Maybe they should just remove the warning?

**Comment by springy76** [comment]
The description could also mention (or provide according sample code) that `Single()` is one of the rare `Assert` methods which don't "return" void. I was searching for an overload with `Action<TItem> validateItem` argument till I finally noticed that the single item is just returned.

**Comment by JesseNewman19** [comment]
This entire warning is straight up a pointless waste of effort and unnecessary clutter. The Api is not any cleaner and I seriously doubt it provides enough increased efficiency to warrant spamming my build log with warnings.

This thing needs to GO

**Comment by grokys** [comment]
What is the reason for this warning? What is likely to go wrong if I do `Assert.Equal(1, collection.Size)` instead of `Assert.Single(collection)`. The warning message/documentation doesn't give any reasoning.

**Comment by bradwilson** [comment]
As part of xunit/xunit.analyzers@39aa196f2088dd79b10a5b356b3215b5223f1ed7 this was addressed to include the fix. Example:

![image](https://user-images.githubusercontent.com/16944/133908945-1079ffde-00be-4897-ab9c-f7f37767f2e7.png)

**Comment by westonpace** [comment]
Thanks!
