### ISSUE TITLE
xunit global CLI tool

### ISSUE THREAD

**Issue by natemcmaster** [xunit/xunit#1684]
I would like to be able to install an xunit console runner globally using the `dotnet tool install -g` feature of the 2.1.300 .NET Core CLI. I know there is already the `dotnet-xunit` tool, but this requires adding a DotNetCliToolReference to all .csproj files, which I find annoying.

IMO ideal usage looks like this
```
$ dotnet tool install -g xunit-cli
$ xunit MyTests.dll
```

Some open design questions:

 - Package name? packages cannot be both a DotNetCliToolRef and a global tool, so unless you want to drop support for `dotnet xunit`, we probably need a new package. I propose making a new package called `xunit-cli` for this.
 - Syntax? `xunit <blah>`. what is `<blah>`? A .dll? A .csproj? Both? IMO, I think you could probably make `xunit MyTests.csproj` and `xunit MyTests.dll` both work, and that would be ideal.
 - .NET Framework support? The initial process launched by a global tool is typically implemented in .NET Core, but the tool could launch `xunit.console.exe` for .NET Framework support on Windows. If we support `xunit file.dll` usage, what would .NET Framework usage look like? Should we attempt to auto-detect framework by looking for config files like `runtimeconfig.json` or `.dll.config` or by reading `System.Runtime.Versioning.TargetFrameworkAttribute` from the assembly? Require a switch to choose the runtime? something else

Happy to help contribute PRs to make this happen.

**Update June 2019**: I've built a prototype and published it for use. See https://github.com/natemcmaster/xunit-cli. 
```
dotnet tool install -g xunit-cli
xunit MyTests.dll
```

cc @bradwilson @onovotny

**Comment by bradwilson** [comment]
However this feature lands, desktop CLR support is an absolute requirement.

On the one hand, I definitely don't want .csproj to be the only way to run, either (people already have `dotnet xunit` for that, and it already has a ton of limitations that I'm not anxious to repeat). On the other hand, I'm not sure how I feel about mixing DLLs and CSPROJs. I'm not sure that I agree with it being ideal, given how different they are. What about supporting .sln files? This is something that people try to do with `dotnet test` today (and run up against their limitations).

**Comment by natemcmaster** [comment]
If it were me, I wouldn't add .sln, but I think .csproj is a common-enough gesture that it's worth having. I was thinking the .dll/.csproj support might work like parameter sets in powershell cmdlets. You can either invoke xunit on .dll files, or xunit on a .csproj file, but not both in the same invocation.

```
Usage: xunit [test.dll] [test2.dll...] [test options]

Usage: xunit [project.csproj] [project options] [test options]

Project options:
  -framework name        : set the framework (default: all targeted frameworks)
  -configuration name    : set the build configuration (default: 'Debug')
  -nobuild               : do not build the test assembly before running
  -usemsbuild            : build with msbuild instead of dotnet
  -msbuildverbosity      : sets MSBuild verbosity level (default: 'minimal')

Test options:
 -parallel option       : set parallelization based on option
 -noautoreporters       : do not allow reporters to be auto-enabled by environment

...etc
```
Are there options that would only apply to running .dll's directly, and not when running through .csproj first?

**Comment by bradwilson** [comment]
Why multiple DLLs, but only a single .csproj? Was that intentional?

**Comment by bradwilson** [comment]
The single most common complaint people have with `dotnet xunit` today (and, for the most part, with `dotnet test`) is that it only works against a single project at a time.

**Comment by natemcmaster** [comment]
Not intentional. You could support multiple csproj too

**Comment by bradwilson** [comment]
I spent some time thinking about this, and discussing it with @onovotny.

- I want to remove all project file processing. Point to DLLs only.
- I want to remove .NET Core 1.x support. `net452`+ and `netcoreapp2.0`+ only.
- The assumption should be, when running .NET Core assemblies, unless otherwise requested, the latest 2.x installed framework should be used.

You can mix Desktop and Core assemblies; any multi-targeting is achieved by pointing at separate DLL files that are already built.

I believe we will be deprecating `dotnet xunit` entirely once this feature is available.

Thoughts?

**Comment by paulomorgado** [comment]
> I believe we will be deprecating `dotnet xunit` entirely once this feature is available.

How will that work then?

**Comment by bradwilson** [comment]
@paulomorgado Only the global tool will be available. The project-level tool will no longer be an option.

**Comment by natemcmaster** [comment]
> I want to remove all project file processing. 

Bummer. I get why, but seems like a missed opportunity for a clean CLI experience. I rarely run tests on command line against a .dll file directly. I almost always invoke `dotnet xunit`, and was hoping for a global CLI tool to replace this so I don't have to keep adding DotNetCliToolReference all over the place.

**Comment by bradwilson** [comment]
Invoking the DLL means knowing where the DLL will be ahead of time. This is exactly how `xunit.console.exe` works today.

**Comment by paulomorgado** [comment]
I know. Doesn't mean that I like it. And multi-targeting adds complexity.

The right way would be if dotnet/msbuild had a way to output the paths to the DLLs.

**Comment by AArnott** [comment]
> I want to remove .NET Core 1.x support. net452+ and netcoreapp2.0+ only.

Doesn't that mean libraries that support netstandard1.x will not be able to use (the latest versions of) xunit to test on .NET Core 1.x, which they claim to support?

Does cutting support for .NET Core 1.x make development of xunit easier, somehow?

**Comment by AArnott** [comment]
> net452+ and netcoreapp2.0+ only.

Wouldn't that preclude any xunit extension (e.g. xunit.skippablefact) from targeting any version of .netstandard, instead requiring them to build twice to target each of these target frameworks? Isn't that exactly what netstandard was developed to avoid?

**Comment by onovotny** [comment]
I'd prefer to see net461 as the minimum as that would allow a netstandard2 based extension.

**Comment by AArnott** [comment]
One advantage to supported net452 is that libraries that multi-target net452 and net46 can use multi-targeting in the test project (targeting each respective version) to test *both* builds of the library. If the test project must compile against net461 itself, then the test project will never pick up the net452 build of the library, so it can't be tested.

**Comment by onovotny** [comment]
I'd really like to see usage numbers of .NET again.... how many people are really *running* on .NET 4.5.2 anymore?

**Comment by bradwilson** [comment]
> Wouldn't that preclude any xunit extension (e.g. xunit.skippablefact) from targeting any version of .netstandard, instead requiring them to build twice to target each of these target frameworks? Isn't that exactly what netstandard was developed to avoid?

No, this is about supported platforms by the runner. That has nothing to do with the target frameworks of the libraries that comprise xUnit.net, which will not be changing (for xUnit.net 2.x).

**Comment by bradwilson** [comment]
> I'd prefer to see net461 as the minimum as that would allow a netstandard2 based extension.

This is on the table for xUnit.net 3.0. It would seem to make sense to shift everything up to .NET Standard 2, .NET Core 2, and .NET 4.6.1.

**Comment by bradwilson** [comment]
> Does cutting support for .NET Core 1.x make development of xunit easier, somehow?

It does. There is a decent amount of .NET Core 1.x workarounds, and usage numbers (as well as a recent poll) suggest that there are very few people running on .NET Core 1.x. They will be welcome to stay on the xUnit.net 2.x code base.

**Comment by damianh** [comment]
> This is on the table for xUnit.net 3.0. It would seem to make sense to shift everything up to .NET Standard 2, .NET Core 2, and .NET 4.6.1.

Recent guidance says that it'll need to be .NET 4.7.2 for netstandard 2 support.

**Comment by bradwilson** [comment]
@damianh This is already covered here: https://github.com/xunit/xunit/issues/1732

**Comment by tmds** [comment]
Is there some documented/recommended way of acquiring xunit.console?

I'm trying to use the DotNetCliToolReference:
```
  <ItemGroup>
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />
    <PackageReference Include="xunit" Version="2.4.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
  </ItemGroup>
```
but that fails:
```
$ dotnet xunit
Detecting target frameworks in xunit2.csproj...
Building for framework netcoreapp2.2...
  xunit2 -> /tmp/xunit2/bin/Debug/netcoreapp2.2/xunit2.dll
Running .NET Core  tests for framework netcoreapp2.2...
The specified framework version '/home/tmds/.nuget/packages/dotnet-xunit/2.3.1/tools/netcoreapp2.0/xunit.console.dll' could not be parsed
The specified framework 'Microsoft.NETCore.App', version '/home/tmds/.nuget/packages/dotnet-xunit/2.3.1/tools/netcoreapp2.0/xunit.console.dll' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/lib64/dotnet/
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.1.11 at [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
      2.2.4 at [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by tmds** [comment]
> The specified framework version '/home/tmds/.nuget/packages/dotnet-xunit/2.3.1/tools/netcoreapp2.0/xunit.console.dll' could not be parsed
The specified framework 'Microsoft.NETCore.App', version '/home/tmds/.nuget/packages/dotnet-xunit/2.3.1/tools/netcoreapp2.0/xunit.console.dll' was not found.

This looks really weird, digging a bit deeper. It seems this is being executed:
```
/usr/lib64/dotnet/dotnet exec --fx-version /home/tmds/.nuget/packages/dotnet-xunit/2.3.1/tools/netcoreapp2.0/xunit.console.dll xunit2.dll
```
while something like this would work:
```
$ /usr/lib64/dotnet/dotnet exec --fx-version 2.2.5 /home/tmds/.nuget/packages/dotnet-xunit/2.3.1/tools/netcoreapp2.0/xunit.console.dll bin/Debug/netcoreapp2.2/xunit2.dll
xUnit.net Console Runner (64-bit .NET Core 4.6.27617.05)
  Discovering: xunit2
  Discovered:  xunit2
  Starting:    xunit2
  Finished:    xunit2
=== TEST EXECUTION SUMMARY ===
   xunit2  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.140s
```

**Comment by bradwilson** [comment]
There is no global CLI tool today.

**Comment by tmds** [comment]
> There is no global CLI tool today.

Does that mean DotNetCliToolReference is still the recommended way to aquire and run xunit.console?

**Comment by natemcmaster** [comment]
I'm going to have some free time soon and might be able to help build this. Is this something you would still be interested in?

**Comment by bradwilson** [comment]
If you mean the .NET Core console runner, it is not supported at all. If you mean the .NET Framework console runner, then the older NuGet package (xunit.runner.console) is the only supported delivery mechanism.

To reiterate: there are no supported .NET CLI tools for xUnit.net today.

**Comment by tmds** [comment]
> To reiterate: there are no supported .NET CLI tools for xUnit.net today.

On github dotnet org, .NET Core development is using xunit and xunit.runner.console, that gives visibility and drives adoption.

I'm surprised this isn't supported/maintained. There is definitely a need here.

I don't think it matters much whether it is `DotNetCliToolReference` or `dotnet tool install -g`.

**Comment by onovotny** [comment]
I haven't found any significant gaps in using `dotnet test` and `dotnet vstest` today. The biggest downside is that we lose control over the output formatting and command line parameter options.

**Comment by bradwilson** [comment]
Both of those things will be returning in v3.

**Comment by tmds** [comment]
> The biggest downside is that we lose control over the output formatting and command line parameter options.

Things I miss with `dotnet test` are filtering by trait, result formats, and controlling parallel/maxthreadcounts.
Maybe some of these are possible using `dotnet test/vstest`?
Do `dotnet test/vstest` use the `xunit.runner.json` file?

> In fact, by running through dotnet test, it's now really easy to do code coverage with Coverlet. 

I didn't know, that's great!

> Both of those things will be returning in v3.

What does that mean?

**Comment by bradwilson** [comment]
>>Both of those things will be returning in v3.

>What does that mean?

In v3, the design is that unit tests are executable programs, not DLLs. If you want to run your .NET Core tests, the preferred option will be to simply `dotnet run` your test project, with command line options that are (roughly) the same as those available today when you run the stand-alone console runner (or the old `dotnet xunit` command).

**Comment by bradwilson** [comment]
>Things I miss with dotnet test are filtering by trait, result formats, and controlling parallel/maxthreadcounts.

All of these (except for result formats) are available via `xunit.runner.json`. https://xunit.net/docs/configuring-with-json

**Comment by tmds** [comment]
> In v3, the design is that unit tests are executable programs, not DLLs.

Is this for .NET Core 3.0? Or is the v3 unrelated to that (xunit v3, independent of .NET Core version)?

With the things I've learned, I seems there is no need for a global tool. Maybe this issue can be closed? @natemcmaster ok for you?

**Comment by bradwilson** [comment]
I meant v3 of xUnit net, independent of platform

**Comment by natemcmaster** [comment]
v3 plans sound cool. In the meantime, here's a prototype:https://github.com/natemcmaster/xunit-cli. Would be happy to contribute it to xunit if this looks like something you want to own. 

	dotnet tool install -g xunit-cli --add-source https://myget.org/F/natemcmaster/api/v3/index.json

![image](https://user-images.githubusercontent.com/2696087/59874797-0449eb80-9354-11e9-8b0f-fa29f3929901.png)

**Comment by bradwilson** [comment]
The decision about whether there will be meta-runners (and what form they'll take) is a decision that's still in the future. :smiley:

Any meta-runner that exists would be there solely in support of running multiple test projects (potentially across multiple platforms), so the existing code is not likely to be useful.

**Comment by natemcmaster** [comment]
So...are you saying no, yes, or maybe later? Sort of sounds like you're saying no, and if that's the case, I'm thinking of publishing a console runner global tool to nuget.org on my own. I've been using my own, private tools for over a year hoping we might make some progress on this together. But if this idea is basically dead in the water, I'm willing to publish my tools for others to use under my own nuget account.

**Comment by bradwilson** [comment]
I believe probably yes, but it's unlikely to be based on your codebase because of the changes planned for v3.

**Comment by natemcmaster** [comment]
Ok, cool. Thanks for clarifying

**Comment by bradwilson** [comment]
Reviewing this with 3+ years in the meantime, I don't think the global CLI tool is going to end up existing. A lot of the shortcomings of `dotnet test` have been resolved. As such I'm going to close this. Thanks all!
