### ISSUE TITLE
app.config settings not read in netcore xunit test project 

### ISSUE THREAD

**Issue by SamVanhoutte** [xunit/xunit#1689]
Hello all,

I have a test project created, and added the following package:

- System.Configuration.ConfigurationManager : 4.4.1
- xunit : 2.3.1
- xunit.runner : 2.3.1

Then I have added an app.config file with the following content:
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <appSettings>
    <add key="configuredSecretKeyName" value="configuredKeyName" />
  </appSettings>
</configuration>
```
But when executing the following test, it seems the app.config settings are not being read?
```
[Fact]
public void TestAppSettings()
{
    var configValue = ConfigurationManager.AppSettings["configuredSecretKeyName"];
    Assert.NotNull(configValue);
}
```
Any idea?

**Comment by bradwilson** [comment]
App.config is not supported on .NET Core (and is [officially deprecated](https://xunit.github.io/docs/configuring-with-xml)). You should [configure via JSON](https://xunit.github.io/docs/configuring-with-json), instead.

**Comment by SamVanhoutte** [comment]
Hello @bradwilson ,

I agree and understood that "the configuration of the xunit behavior" is deprecated, using the app.config.  However, the dotnetstandard library I want to test, is using System.Configuration.ConfigurationManager, against the app.config.

Is there also a statement that that is not officially supported?

**Comment by bradwilson** [comment]
App.config files have never been supported by .NET Core (this has nothing to do with xUnit.net itself).

**Comment by bricelam** [comment]
I hit this while porting the EF6 tests to .NET Core. Here's my workaround:
``` xml
<ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp3.0'">
  <None Update="App.config">
    <Link>xunit.console.dll.config</Link>
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
</ItemGroup>
```
Note, this only works because `xunit.console.dll` is the entry assembly. If you're using a different runner, you'll need to use its entry assembly instead.

**Comment by bricelam** [comment]
@bradwilson dotnet/corefx#32095 would provide an alternative to `AppDomainSetup.ConfigurationFile` on .NET Core

**Comment by bradwilson** [comment]
@bricelam It's unlikely that we would take a .NET Core 3.0 dependency any time soon.

Plus, the plan right now is to kill XML-based configuration (`app.config`) entirely (even on `net4x`) so we can standardize on just supporting JSON for xUnit.net v3.

**Comment by bricelam** [comment]
Note well, this isn't about configuring xUnit.net--it's about using ConfigurationManager in your tests including testing components that use ConfigurationManager.

I think it will become more relevant as more WPF and WinForms apps are ported to .NET Core.

But it may also become a non-issue in xUnit.net 3 if the execution model is changed from using a runner to execute your tests to just making your tests an executable.

**Comment by bricelam** [comment]
Looks like the proposal would compile just fine on .NET Standard 2.0: (Tests would just need a newer version of [System.Configuration.ConfigurationManager](https://www.nuget.org/packages/System.Configuration.ConfigurationManager) to work)
``` csharp
AppDomain.CurrentDomain.SetData("APP_CONTEXT_CONFIGURATION_FILE", configurationFile);
```
It would mirror this line on the AppDomain codepath.
https://github.com/xunit/xunit/blob/c54cc52ffb275c81afed022521870193bbca6c39/src/xunit.runner.utility/AppDomain/AppDomainManager_AppDomain.cs#L52

**Comment by bradwilson** [comment]
Of course, as you pointed out, all this code goes away in the new design. :smile:

**Comment by bricelam** [comment]
This has *finally* been unblocked in .NET 6. I've submitted PR #2420 to enable tests to use ConfigurationManager.
