### ISSUE TITLE
Unable to install Xunit.runner.visualstudio to a .NET Core Console App with version 2.3.1

### ISSUE THREAD

**Issue by alexanderkyte** [xunit/xunit#1690]
I'm seeing

``` error NU1701: Package 'xunit.runner.visualstudio 2.3.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.```

with 

```dotnetcli/dotnet --version
2.1.2
```
.

After looking elsewhere, everybody has closed bugs and said this bug was fixed in this version. That doesn't seem to be the case.

**Comment by bradwilson** [comment]
.NET Standard is not supported (with any runner).

Please change the unit tests to be `netcoreapp` rather than `netstandard`.
