### ISSUE TITLE
Analyzer xUnit1013 throws NullReferenceException

### ISSUE THREAD

**Issue by JosefPihrt** [xunit/xunit#1694]
repro:
```csharp
using Xunit;

public class C
{
    [Fact]
    public void M()
    {
    }

    public override void M2()
    {
    }
}
```

I did check the source and the problem is that `IMethodSymbol.OverriddenMethod` can return null even if `ISymbol.IsOverride` returns true.

**Comment by tiesmaster** [comment]
I'm going to take a stab at this. @marcind Let me know if you have any objections.

**Comment by marcind** [comment]
go for it

**Comment by marcind** [comment]
I prefer analyzers to stay silent if there are compilation problems with the source code. No point in lighting them up if someone is in the process of refactoring code.

**Comment by tiesmaster** [comment]
Alright, PR is ready then ;)
