### ISSUE TITLE
(IHostingEnvironment)env.WebRootPath is null while testing

### ISSUE THREAD

**Issue by markentingh** [xunit/xunit#1695]
Running the application, everything is fine, but when running an integration test using `Microsoft.AspNetCore.TestHost`, I cannot retrieve the `WebRootPath` from `IHostingEnvironment` because it returns null. Am I missing something?

**Comment by bradwilson** [comment]
Have you tried with 2.4 beta 1? There were issues with MVC + `dotnet xunit` that caused several issues which we believe is now resolved.

**Comment by bradwilson** [comment]
Please re-open with a repro written against 2.4 beta 1 or later.

**Comment by madelson** [comment]
@bradwilson I just ran into this exact issue. I'm using Microsoft.AspNetCore.Mvc.Testing 2.2... I don't even see version 2.4 on nuget.org.

I am testing with NUnit 3.
