### ISSUE TITLE
Live Testing excludes all tests

### ISSUE THREAD

**Issue by MisinformedDNA** [xunit/xunit#1696]
Over at [corefxlabs](https://github.com/dotnet/corefxlab/pull/2258#issuecomment-386739044), our solution suddenly doesn't find any tests for live testing. I can, however, run them manually. Here's my output:

> [16:15:47.876 Info] Live Unit Testing started.
> [16:15:57.965 Info] Build completed (succeeded).
> [16:15:58.655 Info] Started executing tests from D:\Repos\corefxlab.vs\corefxlab\lut\0\t\System.IO.FileSystem.Watcher.Polling.Tests\Debug\netcoreapp2.1\System.IO.FileSystem.Watcher.Polling.Tests.dll.
> [16:16:01.669 Error] [TestRunner 1] [xUnit.net 00:00:01.5380188] System.IO.FileSystem.Watcher.Polling.Tests: Exception filtering tests: No tests matched the filter because it contains one or more properties that are not valid (TestCategory). Specify filter expression containing valid properties (DisplayName, FullyQualifiedName) and try again.
> [16:16:01.779 Info] [TestRunner 1] No test is available in D:\Repos\corefxlab.vs\corefxlab\lut\0\t\System.IO.FileSystem.Watcher.Polling.Tests\Debug\netcoreapp2.1\System.IO.FileSystem.Watcher.Polling.Tests.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.

![image](https://user-images.githubusercontent.com/1784452/39655467-5ac16e86-4fbf-11e8-8b96-bd049e737d56.png)

Was there a recent release that could have caused this?

VS 2017 15.7 Preview 5
Xunit 2.2.0

**Comment by bradwilson** [comment]
Issues with Live Testing (that don't repro in other environments) should be reported to the VSTest team.

Also, you should probably try to use the latest xUnit.net before reporting an issue to them.

**Comment by MisinformedDNA** [comment]
No need to be rude. The issue is happening to two of us. For me, it was working then I updated the repo to latest and then it suddenly spotted working. My best guess was an xunit update since nothing else changed.

I don't own corefxlab, so updating to latest may not be an option unless something is wrong with the version we already have.

**Comment by bradwilson** [comment]
Closed an external.
