### ISSUE TITLE
Support ASP.NET vNext

### ISSUE THREAD

**Issue by bricelam** [xunit/xunit#170]
As @bradwilson, @davidfowl, @rynowak, @lodejard, and I discussed, there are a few things that need to happen for this to work.

1. Create compatible versions of xunit.execution and xunit.runner.utility
2. Create a compatible runner
4. Integrate with the VS "14" ASP.NET vNext projects' test runner

**Comment by bristolcityfc** [comment]
**XUnit Unable to write test case for Web Api in vNext**

Just tried this using beta7, does not appear to work.

Create a new Web Api project
![clipboard1](https://cloud.githubusercontent.com/assets/806505/9769396/fe762f12-56f7-11e5-9c9f-6582c512015c.jpg)

Add XUnit Test project (I used Side Waffle)

![clipboard2](https://cloud.githubusercontent.com/assets/806505/9769433/2c6b5596-56f8-11e5-8674-2925fbd0dfd9.jpg)

We want to run tests on WebApi project as per http://www.asp.net/web-api/overview/testing-and-debugging/unit-testing-with-aspnet-web-api   

Add Web Api core to test project

![clipboard3](https://cloud.githubusercontent.com/assets/806505/9769516/ae71db78-56f8-11e5-8946-fc4962664f45.jpg)

**Snafu # 1 Core does not support reference to WebApi Core** 

![clipboard4](https://cloud.githubusercontent.com/assets/806505/9769576/04d9280e-56f9-11e5-88eb-dac1e03c9284.jpg)

 Update project.json to remove core

```
{
  "version": "1.0.0-*",
  "description": "UnitTestProject1 test project",
  "authors": [ "87120J" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
    "Microsoft.AspNet.WebApi.Core": "5.2.3",
    "xunit": "2.1.0-beta4-build3109",
    "xunit.runner.dnx": "2.1.0-beta4-build134"
  },
  "commands": {
    "test": "xunit.runner.dnx"
  },

  "frameworks" : {
    "dnx451": { }
  }
}
```

 Add reference to WebApi project from XUnit project and create test

![clipboard5](https://cloud.githubusercontent.com/assets/806505/9769679/91fecf40-56f9-11e5-8f29-800be81d2994.jpg)

```
using System.Collections.Generic;
using Xunit;
using WebApplication4.Controllers;
namespace UnitTestProject1.Controllers
{

    public class ValuesControllerTest
    {

        [Fact]
        public void PassingTest()
        {
            ValuesController controller = new ValuesController();

            // Act
            IEnumerable<string> result = controller.Get();

            // Assert
            Assert.NotEmpty(result);
        }
    }
}
````

Test discovery does not work - no test is run

![clipboard6](https://cloud.githubusercontent.com/assets/806505/9769743/fd8d9656-56f9-11e5-9d10-f7a6c3229dd1.jpg)

If it does work and I'm just following the wrong steps could clear instructions be provided on how to achieve the equivalent of adding unit tests to Web API 2 as outlined for previous MVC version in link above.

**Comment by bradwilson** [comment]
You're using incompatible DNX and xUnit.net versions.

Please consult the table on the top of this page to figure out what combination you need/want: http://xunit.github.io/docs/getting-started-dnx.html

**Comment by bristolcityfc** [comment]
Thank you for the quick response. After updating xUnit version in project.json the test for the simple example of the ValuesController was indeed discovered and executed.
