### ISSUE TITLE
xunit lept into the .NET Core arena too quickly

### ISSUE THREAD

**Issue by mwpowellhtx** [xunit/xunit#1700]
What do I mean by that? Some of us are still supporting .NET Framework based applications, tests, etc. And in some cases, the leap to .NET Core is prohibitive and breaks the test runners. I've confirmed this in a discussion with my ReSharper team. This is particularly an issue, especially during Combinatorial usage. My suspicion is that when you provide a .NET Framework alternative in addition to the .NET Core deployment, this issue should resolve itself, yet still provide the migration path into .NET Core. I don't know how you capture this, as a NuGet dependency, etc.

**Comment by bradwilson** [comment]
I honestly don't understand what you're asking for here. Support for desktop CLR hasn't been removed.

**Comment by mwpowellhtx** [comment]
According to the report, apparently it is a difference between VS2017 Core test discovery, and VS2015 Framework non-discovery. It may be more to do with ``xunit.combinatorial``, but I'm not sure; however, the exceptions lead me to believe it is the Core-nature of ``xunit`` today that may be the root cause.

**Comment by bradwilson** [comment]
I'm closing this issue as it isn't a feature request/bug report. General discussion of xUnit.net should be done on the Slack server. Please open a new issue if there are specific technical issues you want to raise.
