### ISSUE TITLE
Proposal: Method / Class / Namespace exclusions as XUnitFilters

### ISSUE THREAD

**Issue by A-And** [xunit/xunit#1701]
<h2>Problem</h2>
Currently XUnit doesn't support a way of dynamically skipping methods, classes or namespaces. Disabling tests requires adding annotations to source code, which is often not feasible or convenient - e.g. when multiple projects need to run the same test suite. Considering that assemblies can be explicitly excluded from running, exclusion of methods seems like a fairly straightforward addition. 

<h2>Proposal</h2>
Mirror the implementation for included methods, namespaces and classes in `XunitFilters.cs` to allow for exclusions of the above. 

https://github.com/xunit/xunit/blob/6bd342df4ea50477ada6e128f366cb8756b3016d/src/xunit.runner.utility/Project/XunitFilters.cs#L35-L55

This would allow for Xunit to be run with a (for example) `-nomethod`  or `-noclass` option from the command line. 

<h2>Comments</h2>
The behavior of Included/excluded traits seems to specify that inclusion supersedes exclusion, so this will be mimicked here as well.
The only mention of this I could find was in #791 , which seems to have been closed for age. 

Has this feature been considered before? 
Seems like the implementation would be straight-forward and if the change is considered appropriate to the project, I would submit a PR with the changes.

**Comment by ViktorHofer** [comment]
@bradwilson as you marked this issue with _help wanted_ and @A-And expressed his support to submit a PR with the changes, is this ready to be implemented?

**Comment by ViktorHofer** [comment]
@A-And to remove our private console runner in dotnet/buildtools it would be great if you could implement this feature here.

**Comment by A-And** [comment]
@ViktorHofer Thanks for bump! Agreed that the feature should live here - the buildtools wrapper was a workaround so we could get the change out quickly.

**Comment by ViktorHofer** [comment]
You are welcome. This is the last item that's left for our migration, can I help you somehow with or do you just need a few more days to work on it?

**Comment by A-And** [comment]
@ViktorHofer Let's move this to e-mail.

**Comment by A-And** [comment]
@bradwilson - Is there an established way to test the xunit.console project outside of running `dotnet test`? I'd like to be able to test the changes, but the CLI's filters are limited. 
Otherwise, invoking the .dll with `dotnet.exe` doesn't discover any in the sample test project http://xunit.github.io/docs/getting-started-dotnet-core.

**Comment by bradwilson** [comment]
It is non-trivial to invoke the .NET Core version of `xunit.console.dll`. You're much better off just testing the desktop CLR version (`xunit.console.exe`).
