### ISSUE TITLE
Error (CS0234) while trying to build xUnit

### ISSUE THREAD

**Issue by pkosel** [xunit/xunit#1703]
Environment:
Windows 10 1709
VS 2017 15.71
xUnit Latest

Steps to reproduce:
Follow the steps as described here [https://xunit.github.io/docs/building-xunit.html](https://xunit.github.io/docs/building-xunit.html)
Try to build and run tests from the command

Expected result:
Solution builds successfully

Actual result:
`
Utility\DiaSessionWrapperHelper_DotNet.cs(65,53): error CS0234: The type or namespace name 'ApplicationModel' does not
exist in the namespace 'Windows' (are you missing an assembly reference?) [C:\Users\pkosel\Dev\CSharp\xunit\src\xunit.r
unner.utility\xunit.runner.utility.csproj]
Utility\DiaSession.cs(63,29): error CS0234: The type or namespace name 'ApplicationModel' does not exist in the namespa
ce 'Windows' (are you missing an assembly reference?) [C:\Users\pkosel\Dev\CSharp\xunit\src\xunit.runner.utility\xunit.
runner.utility.csproj]
`

Maybe related: [https://github.com/xunit/xunit/pull/1618#issuecomment-360558300](https://github.com/xunit/xunit/pull/1618#issuecomment-360558300)

**Comment by bradwilson** [comment]
I'm unable to repro this locally. Is this is the only message you get when building?

**Comment by Ilchert** [comment]
I have the same issue.

**Comment by pkosel** [comment]
Ok, I see.

**Comment by pkosel** [comment]
@bradwilson 
Update: After I fetched and merged the latest upstream/master I also get the following errors now while trying to run the build script.

`
Asserts\CollectionAssertsTests.cs(212,55): error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.ID
ictionary<string, int>' to 'System.Predicate<char>' [C:\Users\pkosel\Dev\CSharp\xunit\test\test.xunit.assert\test.xunit
.assert.csproj]
Asserts\CollectionAssertsTests.cs(212,17): error CS0815: Cannot assign void to an implicitly-typed variable [C:\Users\p
kosel\Dev\CSharp\xunit\test\test.xunit.assert\test.xunit.assert.csproj]
Asserts\CollectionAssertsTests.cs(423,84): error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.ID
ictionary<string, int>' to 'System.Predicate<char>' [C:\Users\pkosel\Dev\CSharp\xunit\test\test.xunit.assert\test.xunit
.assert.csproj]
Asserts\CollectionAssertsTests.cs(436,84): error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.ID
ictionary<string, int>' to 'System.Predicate<char>' [C:\Users\pkosel\Dev\CSharp\xunit\test\test.xunit.assert\test.xunit
.assert.csproj]
Asserts\CollectionAssertsTests.cs(453,84): error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.IR
eadOnlyDictionary<string, int>' to 'System.Predicate<char>' [C:\Users\pkosel\Dev\CSharp\xunit\test\test.xunit.assert\te
st.xunit.assert.csproj]
Asserts\CollectionAssertsTests.cs(466,84): error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.IR
eadOnlyDictionary<string, int>' to 'System.Predicate<char>' [C:\Users\pkosel\Dev\CSharp\xunit\test\test.xunit.assert\te
st.xunit.assert.csproj]
Asserts\CollectionAssertsTests.cs(224,78): error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.ID
ictionary<string, int>' to 'System.Predicate<char>' [C:\Users\pkosel\Dev\CSharp\xunit\test\test.xunit.assert\test.xunit
.assert.csproj]
Asserts\CollectionAssertsTests.cs(241,55): error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.IR
eadOnlyDictionary<string, int>' to 'System.Predicate<char>' [C:\Users\pkosel\Dev\CSharp\xunit\test\test.xunit.assert\te
st.xunit.assert.csproj]
Asserts\CollectionAssertsTests.cs(241,17): error CS0815: Cannot assign void to an implicitly-typed variable [C:\Users\p
kosel\Dev\CSharp\xunit\test\test.xunit.assert\test.xunit.assert.csproj]
Asserts\CollectionAssertsTests.cs(253,78): error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.IR
eadOnlyDictionary<string, int>' to 'System.Predicate<char>' [C:\Users\pkosel\Dev\CSharp\xunit\test\test.xunit.assert\te
st.xunit.assert.csproj]
Asserts\CollectionAssertsTests.cs(423,84): error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.ID
ictionary<string, int>' to 'System.Predicate<char>' [C:\Users\pkosel\Dev\CSharp\xunit\test\test.xunit.assert\test.xunit
.assert.csproj]
Asserts\CollectionAssertsTests.cs(436,84): error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.ID
ictionary<string, int>' to 'System.Predicate<char>' [C:\Users\pkosel\Dev\CSharp\xunit\test\test.xunit.assert\test.xunit
.assert.csproj]
Asserts\CollectionAssertsTests.cs(453,84): error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.IR
eadOnlyDictionary<string, int>' to 'System.Predicate<char>' [C:\Users\pkosel\Dev\CSharp\xunit\test\test.xunit.assert\te
st.xunit.assert.csproj]
Asserts\CollectionAssertsTests.cs(466,84): error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.IR
eadOnlyDictionary<string, int>' to 'System.Predicate<char>' [C:\Users\pkosel\Dev\CSharp\xunit\test\test.xunit.assert\te
st.xunit.assert.csproj]
Asserts\CollectionAssertsTests.cs(212,55): error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.ID
ictionary<string, int>' to 'System.Predicate<char>' [C:\Users\pkosel\Dev\CSharp\xunit\test\test.xunit.assert\test.xunit
.assert.csproj]
Asserts\CollectionAssertsTests.cs(212,17): error CS0815: Cannot assign void to an implicitly-typed variable [C:\Users\p
kosel\Dev\CSharp\xunit\test\test.xunit.assert\test.xunit.assert.csproj]
Asserts\CollectionAssertsTests.cs(224,78): error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.ID
ictionary<string, int>' to 'System.Predicate<char>' [C:\Users\pkosel\Dev\CSharp\xunit\test\test.xunit.assert\test.xunit
.assert.csproj]
Asserts\CollectionAssertsTests.cs(241,55): error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.IR
eadOnlyDictionary<string, int>' to 'System.Predicate<char>' [C:\Users\pkosel\Dev\CSharp\xunit\test\test.xunit.assert\te
st.xunit.assert.csproj]
Asserts\CollectionAssertsTests.cs(241,17): error CS0815: Cannot assign void to an implicitly-typed variable [C:\Users\p
kosel\Dev\CSharp\xunit\test\test.xunit.assert\test.xunit.assert.csproj]
Asserts\CollectionAssertsTests.cs(253,78): error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.IR
eadOnlyDictionary<string, int>' to 'System.Predicate<char>' [C:\Users\pkosel\Dev\CSharp\xunit\test\test.xunit.assert\te
st.xunit.assert.csproj]
`

**Comment by bradwilson** [comment]
Closing, as we were never able to reproduce the problem. 😞

**Comment by nvborisenko** [comment]
Installing `Windows 10 SDK (10.0.10240.0)` helped me.
