### ISSUE TITLE
xUnit.Analyzers cannot be loaded side-by-side resulting in errors if you switch between branches containing different versions

### ISSUE THREAD

**Issue by davkean** [xunit/xunit#1704]
xUnit.Analyzers.dll cannot be side-by-side loaded preventing Visual Studio from loading multiple of versions of them in the same AppDomain.

Switching between a branch that referenced xunit.analyzers 0.7.0.0 to a branch that references 0.8.0.0 results in the following error:

```
Warning	CS8032	An instance of analyzer Xunit.Analyzers.TestCaseMustBeLongLivedMarshalByRefObject cannot be created from C:\Users\davkean\.nuget\packages\xunit.analyzers\0.8.0\analyzers\dotnet\cs\xunit.analyzers.dll: Could not load type 'Xunit.Analyzers.TestCaseMustBeLongLivedMarshalByRefObject' from assembly 'xunit.analyzers, Version=0.7.0.0, Culture=neutral, PublicKeyToken=null'..	Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests		1	Active	System.TypeLoadException: Could not load type 'Xunit.Analyzers.TestCaseMustBeLongLivedMarshalByRefObject' from assembly 'xunit.analyzers, Version=0.7.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerFileReference.Extensions`1.GetAnalyzersForTypeNames(Assembly analyzerAssembly, IEnumerable`1 analyzerTypeNames, Boolean& reportedError)
```

I spent some time manually inspecting the analyzer code to figure out why this is occurring, and what is happening is the following:

1. Using a static metadata reader (no CLR binding policy), Analyzer driver finds all analyzers in xunit.analyzers\0.7.0\analyzers\dotnet\cs\xunit.analyzers.dll
2. Analyzer driver calls Assembly.LoadFrom("xunit.analyzers\0.7.0\analyzers\dotnet\cs\xunit.analyzers.dll")
3. On resulting assembly, Analyzer driver does Assembly.GetType with types names found in 1.

-- Branch switch while Visual Studio is open --

4. Using a static metadata reader (no CLR binding policy), Analyzer driver finds all analyzers in xunit.analyzers\0.8.0\analyzers\dotnet\cs\xunit.analyzers.dll
5. Analyzers driver calls Assembly.LoadFrom("xunit.analyzers\0.8.0\analyzers\dotnet\cs\xunit.analyzers.dll"), **_this returns xunit.analyzers\0.7.0\analyzers\dotnet\cs\xunit.analyzers.dll_**
6. On resulting assembly, does Assembly.GetType with types names found in 4, this blows up with above

The CLR binding policy of assemblies without a strong name prevents them from being side-by-side loaded. To fix this, these analyzers should be strong-named. Given these are _**not**_ for general library consumption this will not result in binding redirect hell that usually occurs when you strong name an assembly.

**Comment by sharwell** [comment]
Related to Microsoft/vs-threading#279. Analyzer assemblies need to use a versioning policy that ensures every release gets a new strong name, which generally means changing the `[AssemblyVersion]` value. This is often different from the versioning policy applied to the library the analyzers are related to, but critical for scenarios like the above to work properly.

**Comment by onovotny** [comment]
No, but we need to set that up to anyway since xUnit depends on this. If companies use NuGet publisher lock down, then xUnit will fail if analyzers aren't signed. It's easy to set you up.

**Comment by davkean** [comment]
Strong name sign=yes
Authenticode sign=orthogonal to the problem

**Comment by bradwilson** [comment]
@marcind Feel free to use our (not even remotely secret) pub/priv key for this, if you want:

https://github.com/xunit/xunit/blob/master/src/signing.snk
https://github.com/xunit/xunit/blob/6084e70f108841a13c1ecac57ddcdcf86e6fc689/src/Directory.Build.props#L4
https://github.com/xunit/xunit/blob/6084e70f108841a13c1ecac57ddcdcf86e6fc689/src/Directory.Build.props#L17

I expect either me and/or @onovotny will also, orthogonally, get the analyzers integrated into our NuGet package signing process, so you don't eventually lose your package's Sexy Blue Check Mark :tm:

**Comment by memark** [comment]
@davkean Great investigation!
