### ISSUE TITLE
Integration of XUnit and TeamCity is broken for Minimal and Quiet verbosity level

### ISSUE THREAD

**Issue by NikolayPianikov** [xunit/xunit#1706]
I've also created https://github.com/Microsoft/vstest/issues/1590

## Steps to reproduce
- Create xunit test project `dotnet new xunit`
- Set environment variable `SET TEAMCITY_PROJECT_NAME` to some value to simulate running under TeamCity, for instance: `SET TEAMCITY_PROJECT_NAME=my`
- Run tests using some verbosity level: `dotnet test --verbosity Minimal` or `dotnet test -v quiet`

## Expected behavior
You should find messages like `##teamcity[testStarted` in stdOut
for all verbosity levels

## Actual behavior
There are no any messages like `##teamcity[testStarted` in stdOut

## Environment
dotnet --version: 
2.1.200
2.1.300-rc1-008673

**Comment by bradwilson** [comment]
Unfortunately, this is working as designed (and not designed by us). The change in verbosity is hiding the messages, and we have no control over that.

To work around this, stop using minimal verbosity on TeamCity.

**Comment by jvandertil** [comment]
@zone117x Passing '--verbosity=normal' to 'dotnet test' seems to work for me.

**Comment by zone117x** [comment]
https://github.com/Microsoft/vstest/issues/1590#issuecomment-392955873

**Comment by paralaxsd** [comment]
Missing TC status messages such as `##teamcity[testStarted` still seem to be a problem under very specific circumstances:

1. `dotnet test` must be run from a non-interactive context, e.g. via the dotnet `Process` class with shell execution disabled.
2. `--no-build` must be missing from the command line in question.

Example that won't create status messages on Team City:
`"C:\Program Files\dotnet\dotnet.exe" test path\to\proj.csproj --test-adapter-path my_user_dir\.nuget\packages\teamcity.dotnet.integration\1.0.33\build\_common\vstest15 --configuration Release`

As mentioned above, currently separating build and test calls via `--no-build` helped me get my status messages back. I've had this problem for a while running tests via `Nuke` and frustratingly could not reproduce the problem when running Nuke's command line on a Terminal. It seemingly started to happen out of the blue.

**Comment by bradwilson** [comment]
What is this?

`--test-adapter-path my_user_dir\.nuget\packages\teamcity.dotnet.integration\1.0.33\build\_common\vstest15`

This implies you aren't using our test adapter, at which point...I have no idea what this third party test adapter outputs (or doesn't).

**Comment by paralaxsd** [comment]
Sorry Brad you're absolutely right. Wrong project, I'll remove my comment.
