### ISSUE TITLE
Add ability to replace default FactDiscoverer & TheoryDiscoverer

### ISSUE THREAD

**Issue by malylemire1** [xunit/xunit#1708]
Can you reopen? https://github.com/xunit/xunit/issues/573

You could check for metadata and override default discoverer

```
[MetadataType(typeof(FactAttributeMetadata))]
public partial class FactAttribute { }

[XunitTestCaseDiscoverer("MyNamespace.MyDiscoverer", "MyDiscovererAssembly")]
public partial class FactAttributeMetadata
{
}
```

**Comment by bradwilson** [comment]
This doesn't appear to solve the original problem (which is: overriding the default fact and theory discoverer). Your solution appears to require someone to change the source of xUnit.net itself.

**Comment by bradwilson** [comment]
No, your solution above is attaching an attribute to `FactAttribute`. This is a type owned by xUnit.net, not by end users.

Regardless, the proposed (and closed) solution is the correct way to do this. If someone is interested in implementing the original suggestion, then I would re-open the issue. However, I'm not interested in this metadata solution.

**Comment by malylemire1** [comment]
Ok sorry I was thinking that there was no solution for this.
Is there a way to use a custom discoverer for the fact and theory attributes?

**Comment by bradwilson** [comment]
Without using new attributes (replacing Fact with YourFact, for example), not today. That's the nature of issue #573.

For examples of writing custom facts with discoverers, see our [RetryFactExample](https://github.com/xunit/samples.xunit/tree/master/RetryFactExample).
