### ISSUE TITLE
Compile console runner against all known .NET frameworks

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1709]
Per issues related to #1659 and #1664, consider shipping several builds of the desktop CLR console runner, compiled against all known frameworks from 4.5.2 forward.

**Comment by xied75** [comment]
👍 When will this get into a release vehicle?

**Comment by bradwilson** [comment]
2.4 beta 2, shipping in the next couple days.

**Comment by ViktorHofer** [comment]
I just run into the issue trying to build xunit.console but failing because of a missing targeting pack for net472. You probably want to note that in the docs: https://xunit.github.io/docs/building-xunit.html
