### ISSUE TITLE
Overcome 'filename or extension is too long' Windows command prompt limitation

### ISSUE THREAD

**Issue by nawfalhasan** [xunit/xunit#1710]
When running xunit.console we can pass a list of classes that need to be run as command line argument. But sometimes this list can be too long which will hit the maximum number of characters Windows cmd supports. 

**Sample that creates the problem (powershell script)**

    $exp = '.\MySolution\packages\xunit.runner.console.2.0.0\tools\xunit.console.x86.exe "bin\Tests\Debug\IntegrationTests.dll" -class Namespace1.Class1 -class Namespace2.Class2
    Invoke-Expression $exp

In the above example I only pass 2 class names. In my case class names would be in thousands range. The total number of characters in arguments is ~45000.

**Error I get:**

> Program 'xunit.console.x86.exe' failed to run: The filename or extension is too longAt line:1 char:1

**Suggested fix:**

It is a known issue with within Windows command prompt as described [here](https://support.microsoft.com/en-gb/help/830473/command-prompt-cmd-exe-command-line-string-limitation). The fix the link suggests is accept list of parameters via a file. So I suggest we have add a command line argument to accept file, something like, 

    .\MySolution\packages\xunit.runner.console.2.0.0\tools\xunit.console.x86.exe "bin\Tests\Debug\IntegrationTests.dll" -file "bla.txt"

In the file I can have valid xUnit arguments, like in my case,

    -class Namespace1.Class1 -class NamespaceN.ClassN

**My environment:**

xUnit version: 2.3.1
.NET version: 4.5.2
Architecture: x86
Windows version: Windows 10, build 16299

**Sample repo:**

I am not sure how a repo should be attached here. Please let me know if it is absolutely required.

**Comment by bradwilson** [comment]
Dup of #1089.
