### ISSUE TITLE
xunit stops while running unit tests

### ISSUE THREAD

**Issue by Jalalx** [xunit/xunit#1712]
I have a problem with running all tests. `xunit.runner.visualstudio` stops in the middle of running. green progress bar stops somewhere in middle (each time running stops on a different unit test method) until I click on Cancel link in the Test Explorer window.
How can I find more info? There is nothing special in Tests output window. Is there any log file somewhere so I can show you?

I'm using Windows 10 x64 Visual Studio 2017 and xunit version 2.3.1

**Comment by bradwilson** [comment]
Enable long running test support to find the test(s) that are hung and not returning. For more information, see: https://xunit.github.io/docs/configuring-with-json

**Comment by Jalalx** [comment]
I guess it's not because of long-running test option because this problem doesn't appear on our CI server. All tests run successfully on CI server, which has lower resources than my development machine.
Also, I tried to run tests on xunit console runner but it stopped (freezing) on starting step.

Anyway, I'll try your solution and update this issue.

**Comment by bradwilson** [comment]
If you try to turn off thread limiting (`-maxthreads unlimited` on the console runner) and things start running, it likely means that deadlocks in `Task`s are to blame.

**Comment by bradwilson** [comment]
Also, combining long running test detection with `-maxthreads 1` is the best way to track them down, because a single deadlock will then stop everything, and the long-running detection should be able to identify the offender right away. You may need to repeat that process until you find and fix them all.

**Comment by Jalalx** [comment]
I just looked back to newly written tests and found the issue in my unit tests. There was a wrong way of mocking async method in one of unit tests. 
Here is a sample of wrong way of writing `async` expect:
```csharp
var expectedFooResult = new Task<FooResult>(() => FooResult.Success);
bundle.MockedFooService.Setup(x => x.CreateAsync(It.IsAny<Foo>(), It.IsAny<string>())).Returns(expectedFooResult);
```
And this is the fixed one:
```csharp
bundle.MockedFooService.Setup(x => x.CreateAsync(It.IsAny<Foo>(), It.IsAny<string>())).Returns(Task.FromResult(FooResult.Success));
```

Then I found out this unit test was not tracked by TFS so the test never been executed on CI server! I'm going to close the issue as labeled `my-fault!` 😫
