### ISSUE TITLE
when running dotnet xunit from command line gets: Could not load file or assembly 'System.Linq, Version=4.2.0.0

### ISSUE THREAD

**Issue by paylocity-sflanders** [xunit/xunit#1714]
Not sure if something is corrupted on my box since it doesn't happen on other machines but if i run any project with xunit tests from command line it blows up immediately with 

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Linq, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Program.Execute(String[] args)
   at Program.Main(String[] args)

Any ideas what this means or where to look?   It worked fine before and just stopped working recently.

-------------

C:\Code\Corp\COM\Paylocity.Apis.Communication.Recipient\UnitTests>dotnet --info
.NET Command Line Tools (2.1.200)

Product Information:
 Version:            2.1.200
 Commit SHA-1 hash:  2edba8d7f1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.200\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

------------

The app is using the 2.3.1 version of the xunit packages

**Comment by bradwilson** [comment]
Please provide a repro project. Thanks!

**Comment by paylocity-sflanders** [comment]
I can create one, but i suspect its not going to produce the same issue.   This issue just started happening on a few boxes but i have no insight into how xunit is loading that dll.   If using the normal "dotnet test" functionality it has no issues.   I guess that is what i'm looking for any info you can supply regarding how xunit is using/loading system.linq that could possibly cause this issue so we can possibly track down the  problem, otherwise the only solution i supposed is a box rebuild anytime this starts happening.

**Comment by paylocity-sflanders** [comment]
Appears to have been a corrupted nuget package that was causing the issue.   Clearing the cache resolved it.
