### ISSUE TITLE
dotnet xunit fails for integration tests on ASP.NET Core 2.1-rc1

### ISSUE THREAD

**Issue by cod7alex** [xunit/xunit#1715]
Repro:

1. Download .NET Core 2.1 RC1 SDK.
2. Create solution with two projects: `dotnet new webapi`, `dotnet new xunit`.
3. Add reference from test project to api project
4. Add simple integration test
```
            var server = new TestServer(new WebHostBuilder()
                .UseStartup<Startup>());
            var client = server.CreateClient();

            var response = await client.GetAsync("/api/values");

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
```
5. `dotnet xunit` from test project folder results in `System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.AspNetCore.Hosting, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.`
6. Apply modifications from https://stackoverflow.com/questions/50401152/integration-and-unit-tests-no-longer-work-on-asp-net-core-2-1-failing-to-find-as

Results:

`dotnet xunit` with `2.3.1` runner results in `System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Core, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.`

`dotnet xunit` with `2.4.0-beta.2.build4003` runner results in 
```It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '2.1.0-rc1' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.1.0-rc1-final at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App].
```

cc @bradwilson

**Comment by bradwilson** [comment]
2.3.1 is known to be broken.

We don't make any requests of frameworks, so I'm left wondering whether the second behavior you described is actually anything related to us or not. /cc @natemcmaster

**Comment by bradwilson** [comment]
My suspicion is that our launching of `dotnet.exe` with a specific `-fxversion` breaks the fact that .NET Core and ASP.NET Core aren't the same version.

**Comment by cod7alex** [comment]
Yes, i have just discovered that `dotnet xunit -fxversion 2.1.0-rc1-final` actually works.

**Comment by natemcmaster** [comment]
You're likely hitting https://github.com/aspnet/Home/issues/3156. Does your xunit test project have a `PackageReference` to Microsoft.AspNetCore.App?

**Comment by bradwilson** [comment]
I'm comfortable at this point saying this is both external and ephemeral.

**Comment by cod7alex** [comment]
@natemcmaster yes, it does. The thing is that `dotnet test` works for me, but `dotnet xunit` does not.

**Comment by cod7alex** [comment]
Thanks @natemcmaster ! This is definitely the cause, taking into account workaround that I shared above.

**Comment by natemcmaster** [comment]
I believe https://github.com/xunit/xunit/pull/1716 should fix this.
