### ISSUE TITLE
Create stand-alone linked-in console runner

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1717]
Create a console-based stand-alone linked in runner, such that compiling a unit test project that links this in will yield either an executable that can just run (on desktop CLR) or be run through the normal execution pipeline for the platform (for example, with `dotnet run`).

**Comment by onovotny** [comment]
It would be nice if `dotnet xunit` were updated to call out to this new thing so build scripts don't break. Can be a global tool as well (long as the name is the same, you can still call it with `dotnet foo`). This would shell out and invoke either dotnet run, or the executable output of the library, passing the args along.

**Comment by bradwilson** [comment]
Closing this, as it's an implicit part of the 3.0 re-design.
