### ISSUE TITLE
Unit-test element not found for test-case

### ISSUE THREAD

**Issue by mwpowellhtx** [xunit/xunit#1721]
The tests appear to run well enough, but I am finding that a warning is reported:

```
2018.05.31 13:58:01.593    WARN Unit-test element not found for test-case <Kingdom.Collections.DerivedEnumerationClassMustBePartialTests.Given_Source_then_Verify_Diagnostics_and_Code_Fixes> from <G:\Source\Kingdom Software\Kingdom.Collections\Migrate\src\Kingdom.Collections.Enumerations.Analyzers.Test\bin\Debug\netcoreapp2.0\Kingdom.Collections.Enumerations.Analyzers.Test.dll>
```

This is probably a ``R#`` warning, but I am trying to narrow it down.

I am generating ``Theory`` test cases via ``ClassData``.

```C#
[Theory, ClassData(typeof(TestCases))]
public void Given_Source_then_Verify_Diagnostics_and_Code_Fixes(
#pragma warning disable xUnit1026 // Theory methods should use all of their parameters
    string description,
#pragma warning restore xUnit1026 // Theory methods should use all of their parameters
    string oldSource, DiagnosticResult[] diagnosticResults, string newSource)
{
    // ...
}
```

The warning begins appearing when I include this test case:

```C#
// ...
{
    const string src = "class TestClass {}";
    yield return new GeneratorTheoryData
    {
        Description = "Non-Enumeration class",
        OldSource = src,
        NewSource = src
    };
}
// ...
```

Based on the Roslyn Analyzers and Code Fixes project(s), with a bit of Verifier refactoring, replacing Xunit for MSTest, and so on.

I know probably not enough to go on, but I wanted to get some feedback, and at least put it on the radar for the time being. I'm working at pulling my solution work space together and will have something further to report at that time.

**Comment by mwpowellhtx** [comment]
Whatever it is, it seems to be isolated in the Visual Studio Runner. Possibly a ``R#`` thing then...

**Comment by bradwilson** [comment]
Can this be reproduced outside of R#? If not, then you may want to ask them (JetBrains) for guidance, as they are responsible for their runner.
