### ISSUE TITLE
Assert.Throws methods should capture original exception as InnerException

### ISSUE THREAD

**Issue by AArnott** [xunit/xunit#1722]
I've received feedback on xunit.skippablefact that the fact should be "skipped" if `NotImplementedException` is thrown (as it does), but *even* if thrown within an `Assert.Throws` delegate. But that `Assert.Throws` wrapper rethrows a different exception and does *not* preserve the original exception as an `InnerException`. 

https://github.com/xunit/assert.xunit/blob/bbece92b18661cc18ede9d72b28648466f9a1709/Sdk/Exceptions/ThrowsException.cs#L32-L34

That leads the test method below to fail instead of be reported as skipped when `Provider.GetTreeMemberNamesAsync` throws `NotImplementedException`.

```cs
    [SkippableFact(typeof(NotImplementedException))]
    public async Task GetTreeMemberNamesAsync_IsAFile()
    {
        await Assert.ThrowsAsync<DirectoryNotFoundException>(() => this.Provider.GetTreeMemberNamesAsync("doc/index.md", "1e187c0a93afb43f08cc36517b44b653a8934b79", this.TimeoutToken));
    }
```

Is there some reason we can't preserve the original exception as an inner exception? (serialization, perhaps)? It seems that we can handle any exception type when we *don't* use `Assert.Throws`, so why should `Assert.Throws` hide the inner exception?

**Comment by AArnott** [comment]
I'm willing to submit a PR for this, but wanted to get agreement first.

**Comment by bradwilson** [comment]
Make it so.

**Comment by AArnott** [comment]
@bradwilson Ping. I've got two PRs to address this waiting for review.
