### ISSUE TITLE
Bug debugging specified class data theories

### ISSUE THREAD

**Issue by mwpowellhtx** [xunit/xunit#1723]
Instead of debugging the selected instance of ``ClassData`` generated ``Theory`` test, the Visual Studio runner is running all of the instances.

**Comment by bradwilson** [comment]
Please provide a repro.

**Comment by mwpowellhtx** [comment]
I changed the ``Theory`` parameter types and order from:

```C#
[Theory, ClassData(typeof(TestCases))]
public void Given_Source_then_Verify_Diagnostics_and_Code_Fixes(string description,
    string givenSource, DiagnosticResult[] diagnosticResults, string fixedSource)
{
    // ...
}
```

To:

```C#
[Theory, ClassData(typeof(TestCases))]
public void Given_Source_then_Verify_Diagnostics_and_Code_Fixes(string description,
    string givenSource, string fixedSource, IEnumerable<DiagnosticResult> diagnosticResults)
{
    // ...
}
```

And the issue seems to have resolved itself. I cannot say the precise root cause, outside of the apparent differences in parameter orders and/or types.

Haven't got my code in a presentable form just yet, but you may be able to reference [RecordGenerator](/amis92/RecordGenerator) tests, which [I am using](/amis92/RecordGenerator/blob/master/test/Amadevus.RecordGenerator.Analyzers.Test/RecordMustBePartialTests.cs#L14) as one of my references.

That being said, I haven't actually run his code at all outside of patterning mine after his, to a certain point.

**Comment by ilmax** [comment]
To me it happens with theory + memberdata. Debugging a failing test from vs test explorer does runs other tests before running the failing one

**Comment by bradwilson** [comment]
Please re-open with a simple repro project if it's still happening.

**Comment by mwpowellhtx** [comment]
@bradwilson No, I will not set up a "test" project for you. Yes, it is still happening AFAIK. When I select to run a specific test case, all of them are being run. Does not matter if the ``Theory`` saw ``Class``, ``Member``, etc, data. Same happens for both. i.e. the problem ain't to do with the *source* of the data, I think. Not sure if it's a VS test explorer thing, per se, to be fair; i.e. attribute the error in the right place.
