### ISSUE TITLE
Drop-in replacement for NUnit

### ISSUE THREAD

**Issue by SeanKilleen** [xunit/xunit#1724]
You said *anything*, so I'm dreaming big.

I've got a large project using NUnit. I'd really really love to move it to xUnit. How could I do that as quickly as possible across 15,000 tests?

I'm thinking something like a Roslyn analyzer that can "convert to xUnit", or a Nuget extension package that Bridges NUnit conventions so that I can add that package, remove NUnit, and have most things work. 

Tests convert to facts, cases convert to theories and inline data, setup converts to Ctor, etc.

I'm keeping this high level because I'm not honestly sure how you'd do it. But that'd be like magic.

**Comment by mgw854** [comment]
I had to replace NUnit with xUnit in a project with around a hundred tests (I say _had to_ when I really mean _wanted to_). Most of what I did was find and replace--xUnit and NUnit have APIs that are so similar for the most part, but differ by name (`AreEqual` vs `Equal`, `[Fact]` vs `[Test]`). There was very little that required thought--which would seem to me to be a perfect thing to automate.

**Comment by wachulski** [comment]
I did a project like that a while ago: https://github.com/wachulski/nunit-migrator which migrates NUnit v2 to v3. And your intuition is correct - it has that nice property of ~80% boilerplate API naming changes which Roslyn supports well. The rest 20% requires some manual ingenious work.

So, it seems the automation is worth its cost, but at the same time when it comes to NUnit -> xUnit migration I suspect a handful of smart regexes would usually do the same.

The important part that justifies the investment could be a list of cases that don't have corresponding regexes and they are used frequently in unit testing code bases. Any ideas? (I'm pretty sure [SetUp] -> ctor has its regex).

**Comment by ewgenym** [comment]
We had similar task - migrate from NUnit to xUnit and came up with following solution: https://github.com/Scalepoint/n2x
Probably you can also use it as a starting point. I'm ready to contribute more in it as well if you suggest features that you miss.

**Comment by reduckted** [comment]
@SeanKilleen You may want to check out the [XUnitConverter project](https://github.com/dotnet/codeformatter/tree/master/src/XUnitConverter) over in the [dotnet/codeformatter](https://github.com/dotnet/codeformatter) repository. It converts MSTest to xUnit, so it might give you some ideas about how to tackle this.

**Comment by waf** [comment]
I have some roslyn-based code that converts NUnit to xunit here: https://github.com/jetabroad/NUnitToXunit

It's not perfect (use source control before running it!) but it converted about 90% of ~5000 unit tests, the remaining 10% we fixed up manually.

It has some experimental support for converting asserts (e.g. NUnit's `Assert.That(11, Is.GreaterThan(10))` to something compatible with xunit's `Assert.True(11 > 10)`)

**Comment by SimonCropp** [comment]
@bradwilson this is really not worth the effort. i have move many projects from nunit to xunit. it is mostly search and replace. any tooling would not have significantly sped up the process

**Comment by SeanKilleen** [comment]
Yes -- I've come to the same conclusion.  I don't know that it's worth the investment in tooling. I think I'd be fine if this was closed.

**Comment by AraHaan** [comment]
Yep, if you want to move from any test framework to xUnit, you just might as well rewrite your tests from scratch to ensure they do the same thing anyway.

Because sometimes the converters just might get it wrong and break them anyway.

**Comment by SeanKilleen** [comment]
Since I raised this one a few years back, I've really come around to some of the other comments on this thread.

Therefore, since I'm the originator of the request, going to respectfully close this. 👍
