### ISSUE TITLE
Document the supported RunSettings for VSTest

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1726]
https://github.com/xunit/xunit/blob/master/src/xunit.runner.visualstudio/Utility/RunSettings.cs#L68-L97

Probably also worth shoring up this list by comparing to the console runner, and see which things would be worth adding for better feature parity.

**Comment by ViktorHofer** [comment]
Is it also possible to pass runsettings via the command line as described with `dotnet test --help`?

> RunSettings arguments:
  Arguments to pass runsettings configurations through commandline. Arguments may be specified as name-value pair of the form [name]=[value] after "-- ". Note the space after --.
  Use a space to separate multiple[name] =[value].
  More info on RunSettings arguments support: https://aka.ms/vstest-runsettings-arguments
  Example: dotnet test -- MSTest.DeploymentEnabled=false MSTest.MapInconclusiveToFailed=True

**Comment by bradwilson** [comment]
I was not able to make this work, but I have no idea how we could/would do anything to enable this. The runsettings values are handed to us by VSTest, so I would've expected them to fill in these values for us.

**Comment by bradwilson** [comment]
Just noticed this is a dup of #1598.
