### ISSUE TITLE
Discovery failure not logged as an error

### ISSUE THREAD

**Issue by cltshivash** [xunit/xunit#1729]
**Repro**
Execute tests from a test assembly (with a missing dependency in the test assembly location) using vstest.console.exe

**Expected**
Failure to discover tests from an assembly should be shown as an error and result in failure (if executed in a CI system)

**Actual**
The failure is logged as a warning and the build passes (with partial results). The relevant code
https://github.com/xunit/xunit/blob/5983e1d2bf6667277f28b2540aaa7beabaf108b6/src/xunit.runner.visualstudio/VsTestRunner.cs#L321

**Comment by bradwilson** [comment]
The reason this isn't an error today is that VSTest can (and does) call us for assemblies that don't contain any xUnit.net tests. It cannot be considered an error when it does so, or you'd potentially be stuck in a situation where you're erroring out 100% of the time.

**Comment by cltshivash** [comment]
@bradwilson Is it possible to identify if a assembly passed is a xunit test assembly (based on the usage of the xunit framework) and then error out if the dependencies aren't found leading to a discovery failure ?

**Comment by bradwilson** [comment]
@cltshivash In most cases we won't know about missing dependencies until they try to get used, because we aren't the code responsible for loading those dependencies. We are forced to wait until the failing dependency is discovered by the platform loader.
