### ISSUE TITLE
3.0: Build from Linux

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1733]
This is more of an aspiration than an outright goal, but it would be nice to be able to build as much of the core as possible from a Linux box w/ just .NET SDK installed.

**Comment by onovotny** [comment]
It wouldn't be complete, but we could do something like Xamarin Essentials to make this work:

https://github.com/xamarin/Essentials/blob/3042e6ea9878347a83a99c1e2d38a7352179721e/Xamarin.Essentials/Xamarin.Essentials.csproj#L5-L6

**Comment by bradwilson** [comment]
I'm not sure why the core would need anything from Xamarin (we don't today).

**Comment by onovotny** [comment]
We don't -- I was highlighting how they used `TargetFrameworks` to enable the solution to load/build on non-windows:
```xml
    <!--Work around so the conditions work below-->
    <TargetFrameworks></TargetFrameworks>
    <TargetFrameworks Condition=" '$(OS)' == 'Windows_NT' ">netstandard1.0;netstandard2.0;Xamarin.iOS10;MonoAndroid81;uap10.0.16299</TargetFrameworks>
    <TargetFrameworks Condition=" '$(OS)' != 'Windows_NT' ">netstandard1.0;netstandard2.0;Xamarin.iOS10;MonoAndroid81;</TargetFrameworks>
```

**Comment by bradwilson** [comment]
Gotcha. :smile:
