### ISSUE TITLE
Unable to run tests - The type initializer for 'Xunit.DiaSession' threw an exception

### ISSUE THREAD

**Issue by bencgreen** [xunit/xunit#1735]
I have just updated all my projects to netcoreapp2.1, and I can no longer run tests.  I believe this is related to that update, which now targets System.Reflection.TypeExtensions 4.3, as opposed to 4.1 as previously.

I have xunit.runner.visualstudio 2.3.1 - but the same thing happens with the latest preview 2.4 beta 2.

The tests are discovered, but when I try Run All, I get the following error in the Output window multiple times:

> Catastrophic failure: System.TypeInitializationException: The type initializer for 'Xunit.DiaSession' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
>    at Xunit.DiaSession..cctor()
>    --- End of inner exception stack trace ---
>    at Xunit.DiaSession..ctor(String assemblyFileName)
>    at Xunit.DiaSessionWrapper..ctor(String assemblyFilename)
>    at Xunit.XunitFrontController..ctor(AppDomainSupport appDomainSupport, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, ISourceInformationProvider sourceInformationProvider, IMessageSink diagnosticMessageSink)
>    at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo)

I've just spent an hour Googling this - I have removed the Nuget package, reinstalled it, upgraded it, downgraded it, I have ensured I have .NET Framework SDK 4.5, 4.6 and 4.7 installed on my machine - I am confident it is to do with the package targeting an old version of the TypeExtensions library.

Is there anything I can do?

**Comment by bradwilson** [comment]
I just looked at our .nuspec, and we don't have a dependency listed for that. I'll have to double check and ensure we're not missing something there.

**Comment by bencgreen** [comment]
Have you been able to reproduce it at least, so I know it's not my system that's doing something strange?

**Comment by bencgreen** [comment]
I've just been doing some more digging and I've spotted that right before any exceptions are thrown, the Output shows this:

> Could not find test executor with URI 'executor://xunit/VsTestRunner2'.  Make sure that the test executor is installed and supports .net runtime version 4.0.30319.42000.

Does that help?  After that in the output, multiple exceptions are thrown, all identical to what I posted above.

**Comment by bencgreen** [comment]
Any updates on this? I’m still not able to run my tests.

**Comment by bradwilson** [comment]
Sorry, I haven't had any time for xunit recently so no further progress had been made.

**Comment by onovotny** [comment]
Do you have a simplified project that reproduces this behavior?

**Comment by bencgreen** [comment]
Yup: 
[Tests.Simple.zip](https://github.com/xunit/xunit/files/2120209/Tests.Simple.zip)

This is the output I get when I try to run the test:

`[20/06/2018 17:24:10 Informational] ------ Run test started ------
[20/06/2018 17:24:12 Warning] Could not find test executor with URI 'executor://xunit/VsTestRunner2'.  Make sure that the test executor is installed and supports .net runtime version 4.0.30319.42000.
[20/06/2018 17:24:12 Informational] ========== Run test finished: 0 run (0:00:01.4829995) ==========`

I apologise if it's my setup, but as I said earlier my tests used to run fine.

**Comment by bencgreen** [comment]
I think I've tracked it down - in xunit.runner.utility there is a condition that specifically references System.Reflection.TypeExtensions 4.1.0, which isn't compatible with netstandard2.0.

**Comment by onovotny** [comment]
I just tried your repro with VS 2017 15.7.4 and the .NET Core 2.1.300 SDK and did not have any issues. The test explorer discovered and executed the tests without issue.

I was able to use, "Run All", "Run Test", and debug the test successfully.

Could an extension be interfering? Does it repro on a clean machine for you?

**Comment by bencgreen** [comment]
Thanks - I've finally tracked it down, the Visual Studio Test Platform extension was disabled.  As I said earlier, this is a fresh install of Windows 10 / Visual Studio 2017, and I don't remember ever enabling it  before, but enabling it makes everything work.
