### ISSUE TITLE
warning AD0001: Analyzer 'Xunit.Analyzers.AssertEqualShouldNotBeUsedForCollectionSizeCheck' threw an exception of type 'System.InvalidCastException'

### ISSUE THREAD

**Issue by calrsom** [xunit/xunit#1736]
warning AD0001: Analyzer 'Xunit.Analyzers.AssertEqualShouldNotBeUsedForCollectionSizeCheck' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'System.Byte' to type 'System.Int32'.'.

**Comment by calrsom** [comment]
VSCode indicates that `Assert.Equal<int>()` is used in the first case, and `Assert.Equal<byte>()` in the second.

**Comment by calrsom** [comment]
I'm still trying to narrow down where this is happening.

**Comment by chinnarao** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Warning	AD0001	Analyzer 'Xunit.Analyzers.PublicMethodShouldBeMarkedAsTest' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	ad.xunittest		1	Active

**Comment by bradwilson** [comment]
Please re-open this issue with a repro project.
