### ISSUE TITLE
xUnit v1 XML format documentation

### ISSUE THREAD

**Issue by nil4** [xunit/xunit#1737]
The [xUnit v2 XML format documentation](https://xunit.github.io/docs/format-xml-v2.html) links to a CodePlex page about the v1 XML format:

> *Note: The XML format changed from v1 to v2. If you are looking for documentation on the old v1 format, the [CodePlex site](http://xunit.codeplex.com/wikipage?title=XmlFormat&referringTitle=Home) still contains that documentation.*

Unfortunately that link is now invalid since CodePlex has been archived. I found the page content in the CodePlex download archive and converted it to markdown format in [this gist](https://gist.github.com/nil4/7a3cd9c23835ec6b126fe588e836a2e8).

Would you accept a PR to xunit.github.io that
- adds the `format-xml-v1.md` file under `/docs`, and
- updates the link from [format-xml-v2.html](https://github.com/xunit/xunit.github.io/blob/abf0c24acbd8028ab6ccaa6d3a6cd722e1144454/docs/format-xml-v2.html#L38) to this file instead?

**Comment by bradwilson** [comment]
Sure! Thanks!

**Comment by nil4** [comment]
@bradwilson PR xunit/xunit.github.io#54 submitted. Let me know if I should make any changes.

**Comment by bradwilson** [comment]
Merged
