### ISSUE TITLE
FileNotFoundException when run tests in VSTS 

### ISSUE THREAD

**Issue by Marusyk** [xunit/xunit#1739]
I got this error when I run test in VSTS

> System.IO.FileNotFoundException: Unable to find tests for D:\agent\_work\2\s\src\backend\Modules\FileStorage\***.FileStorage.Tests\bin\x64\Debug\netcoreapp2.1\xunit.runner.visualstudio.dotnetcore.testadapter.dll. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate. Rerun with /diag option to diagnose further.
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
>  xUnit.net VSTest Adapter v2.4.0-beta.2.build4010 (64-bit .NET Core 4.6.26406.07)

My csproj contains:
  ```
  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.7.2" />
    <PackageReference Include="xunit.core" Version="2.4.0-beta.2.build4010" />
    <PackageReference Include="xunit.assert.source" Version="2.4.0-beta.2.build4010" />
    <PackageReference Include="xunit.runner.console" Version="2.4.0-beta.2.build4010" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0-beta.2.build4010" />
```
I'm using **netcoreapp2.1** as a target framework. Some tests passed but not all. I've attached log file from VSTS. Please suggest how can I fix that.
[7_Run tests.txt](https://github.com/xunit/xunit/files/2091532/7_Run.tests.txt)

**Comment by bradwilson** [comment]
Please provide a repro project.

**Comment by Marusyk** [comment]
@bradwilson I can't mu project is not open source!

**Comment by bradwilson** [comment]
I will see if I can repro with a simple project, but I'm skeptical (since we do test this scenario already).

**Comment by bradwilson** [comment]
https://github.com/xunit/xunit.integration/tree/master/test-explorer/v2x_netcoreapp2.1

**Comment by Marusyk** [comment]
@bradwilson My test project is the same as example [here](https://xunit.github.io/docs/getting-started-dotnet-core)

**Comment by bradwilson** [comment]
Do the tests run successfully with `dotnet test`? We don't officially support VSTS, so if the issue is VSTS-specific, you'll need to ask them for assistance.

**Comment by Marusyk** [comment]
Yes, `dotnet test` returns the same. I've tried to create a new empty project and run `dotnet test` on my computer
![screenshot_1](https://user-images.githubusercontent.com/9221694/41420253-b597e684-6ffc-11e8-848d-ea4b5bf41a00.png)

**Comment by Marusyk** [comment]
Microsoft/vsts-agent#1624

**Comment by Marusyk** [comment]
Fixed 🙃. The problem was in my build configuration in this line:
` "testAssemblyVer2": "**\\*test*.dll\n!**\\obj\\**",`

where I tried to find all assemblies that contains word "test" in the name. 

There are **xunit.runner.visualstudio.dotnetcore.testadapter.dll** that, of course doesn't have any tests. So, the runner was actually right when says

>  Unable to find tests for xunit.runner.visualstudio.dotnetcore.testadapter.dll

My fault 😕. Thanks

**Comment by NeelBhatt** [comment]
So, which wildcard you selected finally?

"testAssemblyVer2": "**\\*tests*.dll\n!**\\obj\\**",

This one?

**Comment by Marusyk** [comment]
@NeelBhatt 
Yeah, I used `"testAssemblyVer2": "**\*.Tests.dll"`
