### ISSUE TITLE
xunit deadlocks on single CPU environments

### ISSUE THREAD

**Issue by marcwittke** [xunit/xunit#1747]
> cross post from https://stackoverflow.com/questions/50918647

This test:

```csharp
using System;
using System.Threading;
using System.Threading.Tasks;
using Xunit;

public class AsyncStuffTest
{
    [Fact]
    public void AsyncTest()
    {
        SomethingAsync().Wait();
    }

    private static async Task SomethingAsync()
    {
        Console.WriteLine("before async loop...");
        await Task.Factory.StartNew(() => {
                                        for (int i = 0; i < 10; i++)
                                        {
                                            Console.WriteLine("in async loop...");
                                            Thread.Sleep(500);     
                                        }
                                    });
        Console.WriteLine("after async loop...");
    }
}
```

never reaches the output `after async loop...` on a single CPU environment. Specs:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300/

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.300 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              1
On-line CPU(s) list: 0
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          15
Model:               6
Model name:          Common KVM processor
Stepping:            1
CPU MHz:             2199.998
BogoMIPS:            4399.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            4096K
L3 cache:            16384K
NUMA node0 CPU(s):   0
```

I know that `.Wait()` is considered evil, but what makes the story interesting is the fact, that a simple console application calling `SomethingAsync().Wait();` in `Main()` does not deadlock. Therefore I would consider this a bug.

Reproduced using versions:
- 2.3.1
- 2.4.0-beta.2.build4010
- 2.4.0-beta.3.build4024

**Comment by onovotny** [comment]
xUnit has its own synchronization contexts. Wait() is the problem and cannot be used here. Comparing xUnit to a console app isn't a like-for-like comparison.

**Comment by bradwilson** [comment]
> Therefore I would consider this a bug.

We do not. We consider this to be expected behavior. Turn your test `async` and use `await` instead.

**Comment by marcwittke** [comment]
> Wait() is the problem and cannot be used here

actually it can, as long as there is more than one CPU in your machine. So that's why I'm asking. But nevermind

**Comment by marcwittke** [comment]
> you can set `maxParallelThreads` to `-1`

Yes that works. Actually, `2` is enough. Isn't that at least a hint that the default should not be "the number of logical processors in your PC", but "the number of logical processors in your PC *plus one*"?

**Comment by bradwilson** [comment]
No, the hint is "stop doing things that deadlock Tasks". Seriously.

**Comment by bradwilson** [comment]
(If you had two of these tests that ran in parallel, with 2 threads, you'd still be deadlocked. No default value can protect against bad coding practices.)
