### ISSUE TITLE
Test which returns non-started Task fails to run at all

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1751]
A test which returns a Task that's not running will never successfully complete.

This test never finishes:

```csharp
[Fact]
public Task TestWithCustomTask()
{
    return new Task(() =>
    {
        Thread.Sleep(500);
        Assert.True(false);
    });
}
```

Converting it to this causes the test to run correctly:

```csharp
[Fact]
public Task TestWithCustomTask()
{
    var task = new Task(() =>
    {
        Thread.Sleep(500);
        Assert.True(false);
    });

    task.Start();
    return task;
}
```

Either the framework should reject un-started tasks, or it should start them. I'm not sure which behavior is right.

**Comment by bradwilson** [comment]
After several Twitter threads, I'm convinced that rejection is the correct behavior for any `Created`-status Task. Note that `TaskCompletionSource`, a non-executing `Task`, returns `WaitingForActivation`, not `Created`, so this does not preclude non-executing `Task`s like TCS (assuming they implement the same contract as TCS).

**Comment by onovotny** [comment]
Can this be added to the analyzers to check? Not sure how well it can capture this scenario

**Comment by bradwilson** [comment]
@onovotny It seems unlikely to be something easily detected by the analyzer, because you'd have to track down through all methods called with the task object (the .Start call doesn't necessarily have to happen in the body of the test method).
