### ISSUE TITLE
Could not find `xunit.execution.desktop.dll` in v.2.3.1 (latest stable)

### ISSUE THREAD

**Issue by mikhailnikolaev** [xunit/xunit#1754]
I have installed XUnit v.2.3.1 for Visual Studio. But get error when running tests
```Could not find/load assembly xunit.execution.desktop.dll```

Some people have already faced this problem (#1083 and #1138, for example). That was about previous versions of XUnit. So, can I fix this problem and how can I fix it?

**Comment by mikhailnikolaev** [comment]
I have solved the problem just updated .NET Framework version of the project to 4.5.2 and reinstalled the XUnit

**Comment by sarthak-k** [comment]
That is not a real solution, what if I have to reference .NET Standard 2.0 libraries? I can't go back to 4.5.2 just so xUnit can show tests across Visual Studio.

**Comment by bradwilson** [comment]
https://xunit.github.io/docs/why-no-netstandard

**Comment by AraHaan** [comment]
I seem to run up on this issue using the latest prerelease https://gist.github.com/AraHaan/694835dc089d98cd12c96a292631fb0d
