### ISSUE TITLE
Make colors and indentation easier to distinguish information

### ISSUE THREAD

**Issue by WildYorkies** [xunit/xunit#1756]
Original issue: https://github.com/fsprojects/FsUnit/issues/122

Since the output is coming from xUnit, I figured here may be more appropriate. Not 100% sure.

# Description
Users should be able to more easily see which tests failed and then see the related errors associated at a glance.

This is the red wall of text as it displays now:

![image](https://user-images.githubusercontent.com/1299322/42185085-b1576ec4-7e15-11e8-91e9-e0e43a0c59d3.png)

# Possible Fixes
Only make the first `[xUnit.net 00:00:00.6835735]` lines red. And group the relevant details immediately underneath in white text.

This way, you're not repeating which test failed twice and the eye is immediately drawn to which test failed and the user can easily ignore the details if they so wish.
```
Starting test execution, please wait...
[xUnit.net 00:00:00.6835735]     LeapTest.Year divisible by 4, not divisible by 100: leap year [FAIL]
  Error Message:
     FsUnit.Xunit+MatchException : Exception of type 'FsUnit.Xunit+MatchException' was thrown.
  Expected: Equals true
  Actual:   was False
  Stack Trace:
     at FsUnit.Xunit.Assert.That.Static[a](a actual, IMatcher`1 matcher) in X:\FsUnit\src\FsUnit.Xunit\FsUnit.fs:line 19
[xUnit.net 00:00:00.6874387]     LeapTest.Year divisible by 400: leap year [FAIL]
  Error Message:
     FsUnit.Xunit+MatchException : Exception of type 'FsUnit.Xunit+MatchException' was thrown.
  Expected: Equals true
  Actual:   was False
  Stack Trace:
     at FsUnit.Xunit.Assert.That.Static[a](a actual, IMatcher`1 matcher) in X:\FsUnit\src\FsUnit.Xunit\FsUnit.fs:line 19

Total tests: 4. Passed: 2. Failed: 2. Skipped: 0.
Test Run Failed.
```

**Comment by bradwilson** [comment]
Some of the text (not all) comes from xUnit. The rest of the text, and all the colorization, comes from VSTest.

**Comment by bradwilson** [comment]
Closing as External.
