### ISSUE TITLE
`Assert.Equal` behaviour is not propper

### ISSUE THREAD

**Issue by mikhailnikolaev** [xunit/xunit#1757]
Hello. There is written that the `Assert.Equal(double, double, int)` method compares two doubles within the given number of decimal places in `Assert.Equal` description. But this is not the truth. For example, if you compare two numbers `2.34999` and `2.35001` within one decimal place, they are equal (because these numbers in *truncated* form are `2.3` and `2.3`). But if you round them, they aren't equal (because these numbers after *rounding* in truncated form are `2.3` and `2.4`). And the second case is not a comparasion within given numbers of decimal places. However, `Assert.Equal` works in this case.

Can you please rewrite description or behaviour of this method?

**Comment by mikhailnikolaev** [comment]
Now documentation is corect, but I still think, that behaviour of the method is exectly incorrect. I suggest rewrite it.

**Comment by bradwilson** [comment]
The behavior is what we want. Truncation is almost never the right answer given that the purpose of specifying precision is to deal with the inherent inaccuracy of storing numbers.

Your sample is testing with the wrong precision, IMO.
