### ISSUE TITLE
Provide richer theory data API than IEnumerable<object?[]>

### ISSUE THREAD

**Issue by jacobengel** [xunit/xunit#1758]
I am working with data-driven tests, and have many test cases to funnel through the same test method.  I would like to be able to organize these test cases by setting traits based on the data in each test case.  E.g...

```c#
public class TestClass
{
     [Theory]
     [ClassData(typeof(TestCaseSource)]
     public void TestMethod(int id, string name, bool foo)
     {
          // blah blah test method
     }
}
```
```c#
public class TestCaseSource
{
     public IEnumerator<object[]> GetEnumerator()
     {
          var data = new object[] { 1, "Steve", false };
          data.SetTrait("Category", "Steve");
          yield return data;

          var moreData = new object[] { 2, "Steve", true };
          data.SetTrait("Category", "Steve");
          yield return moreData;

          var carlData = new object[] { 3, "Carl", false };
          data.SetTrait("Category", "Carl");
          yield return carlData;

          // blah blah more test cases with categories
     }    
}
```

[A similar issue was opened a few years ago, but didn't make it into 2.0.](https://github.com/xunit/xunit/issues/218)

This is a huge requirement for migrating my test suite to Xunit, so this is a feature I'd love to see in 3.0!

**Comment by Glen-Cocoa** [comment]
+1

**Comment by marthurIntersys** [comment]
Any update on this?

**Comment by bradwilson** [comment]
Work on 3.0 is progressing, but new features haven't started yet.

**Comment by bradwilson** [comment]
In addition to supporting traits, this richer API should also support:

- Skipping individual data rows
- Providing overrides of test case metadata like description

If there's anything else that should be on the list, please add it in a comment here! Thanks!

**Comment by bradwilson** [comment]
> Isn't this covered by `TheoryData` and `TheoryData<T>`?

Because of my comment just above yours, the answer is "no".

**Comment by weitzhandler** [comment]
Was referring to first comment, but your second one makes it all so much more exciting!
