### ISSUE TITLE
xUnit VS Runner breaks Live Unit Testing

### ISSUE THREAD

**Issue by majorimi** [xunit/xunit#1760]
I have a similar issue like https://github.com/xunit/xunit/issues/1514 which was closed. However I still can reproduce the problem. VS 2017 Live unit testing does not work.

Looking into the Output window I just got a very weird error message:

> [08:57:44.028 Info] Live Unit Testing started.
> **[08:57:45.001 Info] Build completed (failed).**

**But it is completely bogus. I can build, run, debug the project.** So there is no build error. Additional info: my project is a Visual Studio Extension. Can it be the issue?

Repo to test the issue can be found [here](https://github.com/majorimi/vs-reopen/tree/master).

**Comment by bradwilson** [comment]
FYI, I am unable to restore packages for this solution:

```
Errors in packages.config projects
    Unable to find version '15.7.104' of package 'Microsoft.VSSDK.BuildTools'.
      C:\Users\Brad\.nuget\packages\: Package 'Microsoft.VSSDK.BuildTools.15.7.104' is not found on source 'C:\Users\Brad\.nuget\packages\'.
      C:\Users\brad\.dotnet\NuGetFallbackFolder: Package 'Microsoft.VSSDK.BuildTools.15.7.104' is not found on source 'C:\Users\brad\.dotnet\NuGetFallbackFolder'.
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Microsoft.VSSDK.BuildTools.15.7.104' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
      https://api.nuget.org/v3/index.json: Package 'Microsoft.VSSDK.BuildTools.15.7.104' is not found on source 'https://api.nuget.org/v3/index.json'.
      https://mseng.pkgs.visualstudio.com/_packaging/Analytics/nuget/v3/index.json: Package 'Microsoft.VSSDK.BuildTools.15.7.104' is not found on source 'https://mseng.pkgs.visualstudio.com/_packaging/Analytics/nuget/v3/index.json'.
      https://www.myget.org/F/xunit/api/v3/index.json: Package 'Microsoft.VSSDK.BuildTools.15.7.104' is not found on source 'https://www.myget.org/F/xunit/api/v3/index.json'.
      https://msazure.pkgs.visualstudio.com/_packaging/Analytics-Backup/nuget/v3/index.json: Package 'Microsoft.VSSDK.BuildTools.15.7.104' is not found on source 'https://msazure.pkgs.visualstudio.com/_packaging/Analytics-Backup/nuget/v3/index.json'.
```

**Comment by bradwilson** [comment]
After upgrading that package to 15.7.109, I was able to successfully run your tests with our desktop CLR console runner, as well as running them with Test Explorer inside VS, so I'm closing this issue as external, and I recommend you open the bug against the Live Unit Testing feature in Visual Studio.

**Comment by majorimi** [comment]
Thanks for your feedback. I have never encountered this issue with "Microsoft.VSSDK.BuildTools" package.  I created a Visual Studio Extension project and started to work on my code. It was building every time. So it is very strange....

Yes I had no problem with running xUnit tests in VS. The issue is only Live Unit Testing. According to this documentation it should work with xUnit: https://blogs.msdn.microsoft.com/visualstudio/2017/03/09/live-unit-testing-in-visual-studio-2017-enterprise/

So before I post an issue to MS I want to make sure the problem is not in xunit.runner.visualstudio. Have you tried to turn on the Live Unit Testing? **Test -> Live Unit Testing -> Start menu.**

**PS** Updated every VS Extension package to the latest. **Live Unit Testing** still broken.

**Comment by bradwilson** [comment]
In general, Live Unit Testing with xUnit.net does work. In cases like this where it doesn't (but standard VSTest execution does), then the bug likely lies within LUT itself and that's where the investigation belongs (triply so in this case since it seems like a build-related issue and has nothing to do with us).

**Comment by majorimi** [comment]
Makes sense. I have reported this particular issue on [MS Dev Community](https://developercommunity.visualstudio.com/content/problem/295274/live-unit-testing-does-not-work-with-vs-extensibil.html).
Also reported your findings when you were unable to restore Nuget packages for VS Extensibility project. And I run into a lot of issue when updated all the Nuget packages. Basically the whole project was not running any more... Something is messed up with this project type.
