### ISSUE TITLE
Docs are horribly incomplete

### ISSUE THREAD

**Issue by jpeg729** [xunit/xunit#1762]
The Getting started pages tell me about [Fact], [Theory] and [InlineData(x)] and the parallel execution and shared context pages tell me a little more about how I should structure my tests.

On other sites I found [MemberData(..)] and [ClassData(..)]
Google also found me the page detailing the analyzers https://xunit.github.io/xunit.analyzers/rules/ but the info on that page isn't in any way attractive to someone who has just found xunit and wants to know how to use it.

A page saying that [MemberData] and [ClassData] exist with maybe a link to a blog post on them would be very useful to beginners.

**Comment by jpeg729** [comment]
Knowing whether there are alternatives to Assert.True would be useful too.

**Comment by bradwilson** [comment]
The issue as titled is not particularly actionable by the community; opening specific issues would probably make it easier for people to contribute to specific problems. We are of course happy to accept PRs for the [docs site](https://github.com/xunit/xunit.github.io/).

Thanks!

**Comment by jpeg729** [comment]
The first thing to do would be to create two pages. One that lists all the available attributes such as [MemberData(..)] and friends, and one that lists the alternatives to Assert.True.

A simple list of the possibilities without any attempt to explain them would be a great start. Once someone knows what the possibilities are, then they can start searching for explanations of them.

I notice that the source code is full of documentation comments. Why not use them to generate some documentation pages?

**Comment by bradwilson** [comment]
Please open individual issues for your suggestions. Thanks!
