### ISSUE TITLE
Cannot run tests from Visual Studio 15.7.5

### ISSUE THREAD

**Issue by Ibrahim-Islam** [xunit/xunit#1764]
![xunit](https://user-images.githubusercontent.com/6401874/42801056-5278eb44-89c8-11e8-9897-4b48b61fcc62.png)

Visual Studio Professional Version 15.7.5

```
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.7.2" />
<PackageReference Include="Moq" Version="4.9.0" />
<PackageReference Include="xunit" Version="2.3.1" />
<PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
```

As can be seen on the screenshot, tests are not discovered so cannot run or debug them from VS but if I run `dotnet test` from inside the directory then tests run fine.

**Comment by bradwilson** [comment]
Please provide a repro project (as requested by the issue template).

**Comment by Ibrahim-Islam** [comment]
@bradwilson Sorry for missing that out. Please find the repro repo here : https://github.com/Ibrahim-Islam/xunit-repro.

**Comment by OlekRia** [comment]
The same with me. Also I cannot debug tests in Visual Studio 2017. I suspect this is something happened in VS2017. But I dont absolutely know how to fix this issue.

**Comment by Ibrahim-Islam** [comment]
I am currently getting work done by using ReSharper's Unit Test tool.

**Comment by OlekRia** [comment]
In my copany JetBrains, Yandex, Rambler, and etc. well known brands are prohibited. :( I need it working just in VS 2017.

**Comment by bradwilson** [comment]
I am unable to reproduce this issue, with VS 2017 15.7.6.

![image](https://user-images.githubusercontent.com/16944/43997756-a32dd18c-9d99-11e8-91dd-9b4737dc9821.png)

**Comment by bradwilson** [comment]
I'm sorry that you're having inconsistent behavior, but that isn't necessarily the fault of xUnit.net. Why do you assume the problem is with us, rather than with Visual Studio?

**Comment by bradwilson** [comment]
Support for Visual Studio: https://visualstudio.microsoft.com/support/

**Comment by OlekRia** [comment]
"Why do you assume the problem is with us". As I wrote - NUnit and MSTEST are OK.
I re-installed VS., Now it works OK with xunit. However reinstall is painful process :(
