### ISSUE TITLE
3.0: Allow extensions to support the desktop CLR with only a netstandard assembly

### ISSUE THREAD

**Issue by adamralph** [xunit/xunit#1765]
Currently [xBehave.net](https://github.com/xbehave/xbehave.net) ships both `net452` and `netstandard1.1` execution assemblies, matching those shipped by xUnit.net. This is required to support test assemblies targeting `net452` (and later).

I would prefer to ship a single `netstandard` execution assembly, and have that used when running on the desktop CLR. This would make my build and test simpler and quicker, and it would allow me to perform a full CI build on a Linux machine.

**Comment by bradwilson** [comment]
That is definitely the current plan of record. Only the runners themselves should be platform-specific.

**Comment by bradwilson** [comment]
Gonna close this now because we have definitely landed far enough into v3 and it's clear that the core framework will be only `netstandard2.0`. Only the runner libraries include `net472` (and only then because of v1/v2 back compat).

**Comment by adamralph** [comment]
🎉 Great to hear @bradwilson
