### ISSUE TITLE
Consider fixing a first-chance FileNotFoundException in ConfigReader_Json

### ISSUE THREAD

**Issue by KirillOsenkov** [xunit/xunit#1766]
In ConfigReader_Json here:
https://github.com/xunit/xunit/blob/56e4a0b3799c8ba575bf438b0f9095b7261c34e3/src/xunit.runner.utility/Configuration/ConfigReader_Json.cs#L137-L147

if the file doesn't exist on disk, it will be probed for and the catch block will swallow the first-chance exception. This happens twice because it tries for these two file name patterns:

```csharp
return LoadFile(Path.Combine(directoryName, $"{assemblyName}.xunit.runner.json"))
                ?? LoadFile(Path.Combine(directoryName, "xunit.runner.json"));
```

When debugging unit-tests in Visual Studio with first-chance exceptions enabled this is distracting and would be nice to get rid of.

I'm guessing one would need a File.Exists abstraction unless the API exists in .NETStandard 1.1?

I'm going to try and make a PR for this, but wanted to file an issue first, just in case.

**Comment by KirillOsenkov** [comment]
1. git clone https://github.com/KirillOsenkov/XunitTest1
2. git checkout f4ca76388e06abdd1aa37d648ddb46475009b961
3. msbuild /r XunitTest1.sln
4. Run xunit.console.exe C:\XunitTest1\XunitTest1\bin\Debug\net461\XunitTest1.dll under debugger with first-chance exceptions enabled.

**Comment by KirillOsenkov** [comment]
Also reproduces if you open that solution in VS, enable first-chance exceptions and debug.

**Comment by bradwilson** [comment]
Since we're moving to 3.0, and it's not clear how much of the code will be brought over, I'm going to open a general 3.0 feature to reduce/eliminate 1st chance exceptions (rather than just highlight this one).

**Comment by KirillOsenkov** [comment]
This is now fixed in v2.
