### ISSUE TITLE
dotnet-xunit doesn't work with .NET Core SDK (+ runtime) 2.1.1

### ISSUE THREAD

**Issue by ViktorHofer** [xunit/xunit#1767]
When the .NET Core 2.1.1 SDK (+ runtime) installed but not a 2.1.0 runtime, dotnet-xunit fails to launch as it looks for a 2.1.0 and does not consider 2.1.1 as appropriate.

## Repro

Install 2.1.1 SDK and make sure that you don't have the 2.1.0 runtime installed.

```
dotnet new xunit
dotnet xunit

Detecting target frameworks in dxunit.csproj...
Building for framework netcoreapp2.1...
  dxunit -> C:\temp\dxunit\bin\Debug\netcoreapp2.1\dxunit.dll
Running .NET Core 2.1.0 tests for framework netcoreapp2.1...
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by bradwilson** [comment]
`dotnet xunit` is no longer supported. Please move to `dotnet test` for .NET Core projects.

**Comment by ViktorHofer** [comment]
Right but I was thinking of servicing the existing 2.3.1 package as it isn't usable anymore with newer runtimes.

**Comment by bradwilson** [comment]
If it were in a state where we felt it was fixable, we would've fixed it rather than abandoning it. We will not be spending any time on it, nor accepting any PRs for it, nor issuing any further releases for it.
