### ISSUE TITLE
Create Task-related analyzers

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1774]
Given how often people are tripped up with deadlocks from bad Task code, maybe we should add analyzers that could at least catch these things in the tests; in particular:

- Using `.Wait()`
- Using `.Result`
- Using `.GetAwaiter()`
- Using `Task.WaitAll()`
- Using `Task.WaitAny()`
- ...others?

**Comment by wachulski** [comment]
@bradwilson you mean for all such occurrences it would offer 1) detection with msg like "use async/await instead" 2) async/await transformation fixes?

**Comment by bradwilson** [comment]
1. Yes
2. If easy to do correctly

**Comment by wachulski** [comment]
ok, consider me on it

**Comment by wachulski** [comment]
Isn't this a duplicate for https://github.com/xunit/xunit/issues/1390 ?

**Comment by bradwilson** [comment]
Yep.
