### ISSUE TITLE
xunit.abstractions.nuspec source code is not reflecting the nuget.org version

### ISSUE THREAD

**Issue by dieterp1** [xunit/xunit#1776]
When downloading xunit 2.4 from nuget.org the package xunit.abstractions version 2.0.2 is also downloaded. The source code on github for xunit.abstractions.nuspec contains version 2.0.1 and the releases are only showing version 2.0.1.
Please update the version in xunit.abstractions.nuspec to 2.0.2 and create a release for version "2.0.2", so that the source code in github is in sync with the other xunit components and also with nuget.

**Comment by bradwilson** [comment]
The binaries have remained unchanged since 2.0, and don't at all relate to the source in Github.

Since 2.x is done now, there is no way this can be fixed.
