### ISSUE TITLE
3.0: Add Timeout to TestState status

### ISSUE THREAD

**Issue by dotMorten** [xunit/xunit#1777]
I'd like to be able to note in my report that a test timed out, as opposed to threw an error. This involves add `Timeout` to the `TestStatus` enumeration, and use this value when a test has timed out based on the TestMethod Timeout property.

**Comment by bradwilson** [comment]
Not 100% sure what `TestStatus` you mean here, @dotMorten. On the xUnit.net side, I think adding a flag to `TestFailed` to indicate that the failure was a timeout is probably the simplest change to make that wouldn't break expectations with existing test messages.
