### ISSUE TITLE
Add a Timeout Attribute class

### ISSUE THREAD

**Issue by dotMorten** [xunit/xunit#1778]
Currently setting the Timeout of a test is done with the Timeout property on the Fact Attribute.
However this complicates interoperability with other test frameworks that uses a separate attribute for timeout.  I'd suggest adding this:

```cs


    [AttributeUsageAttribute(AttributeTargets.Method, AllowMultiple = false)]
    public sealed class TimeoutAttribute : Attribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TimeoutAttribute"/> class.
        /// </summary>
        /// <param name="timeout">The time-out period of a unit test. This is measured in milliseconds.</param>
        public TimeoutAttribute(int timeout)
        {
            Timeout = timeout;
        }
        /// <summary>
        /// The time-out period for a unit test. This is measured in milliseconds.
        /// </summary>
        public int Timeout { get; }
    }
```

**Comment by bradwilson** [comment]
We made a very explicit decision **not** to do this, based on our experience with NUnit. This is why Skip and Timeout are properties rather than attributes (not to mention that it may not make sense to mix these things in with 3rd party extension).

This is working as designed.
