### ISSUE TITLE
Reduce/eliminate first chance exceptions

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#1779]
See also #1766

**Comment by slaneyrw** [comment]
I've searched for all catch { } in the solution, and came up with only the 2 below of the ones that could be avoided

xunit.v3.runner.utility
  AssemblyUtility.GetTargetFramework - File check
  DiaSessionWrapperHelper.ctor - 2 File checks
  
The code snippet from the original OP already has a file existence check

**Comment by bradwilson** [comment]
Thanks @slaneyrw.

I took a look at `AssemblyUtility.GetTargetFramework`, and the `File.Exists` check does make sense there (I even left myself a TODO note to validate that). (Fixed in c27a91f)

As for `DiaSessionWrapperHelper`'s constructor, a file existence check doesn't work there, because the loading logic can't be boiled down to a specific file check.

In both cases, though, the generic `catch` needs to stay, because the exceptions that may be thrown there are something that should be eaten and ignored (and are not solely related to files not existing on disk).

I'm going to leave this issue open, because there are more to be found here (namely, not just every empty `catch` but also every `catch (Exception)` needs to be inspected to ensure it's not unnecessary).

**Comment by bradwilson** [comment]
Testing today with v3 `0.3.0-pre.20` and a relatively empty project, I don't see any first chance exceptions that aren't expected: just the ones being thrown by failing tests (and anything related to that, like `TargetInvocationException` because we use reflection to invoke the tests).

If people find any specific first chance exceptions they believe are avoidable, please open a new issue with a repro.

Thanks!
