### ISSUE TITLE
How to use code stop run tests ?

### ISSUE THREAD

**Issue by stulzq** [xunit/xunit#1785]
I am doing some initialization of the configuration data when I perform the test. If the initialization fails, how to terminate the running test, I try to use Environment.Exit(1) to terminate, but the reason for this termination will not be terminated in the console output. . So I want to ask if xunit has such a way.

**Comment by bartelink** [comment]
The mechanisms described in [Shared Context](https://xunit.github.io/docs/shared-context.html) are the main tool xUnit provides - a failure to create such a fixture manifests as all dependent tests failing.

**Comment by bradwilson** [comment]
When in doubt, throw an exception. :)

**Comment by stulzq** [comment]
Thanks.
