### ISSUE TITLE
Duplicate entry in [Content_Types].xml/xunit.abstractions.2.0.2.nupkg causes NuGet.Server to fail

### ISSUE THREAD

**Issue by larsw** [xunit/xunit#1786]
Hi,

The [Content_Types].xml file in the root of the aforementioned NuGet package contain two entries for the ```psmdcp``` extension.
This causes NuGet.Server to puke on import with an ArgumentException (Dictionary<> item already exists).

As far as I can tell, the only package that has this double entry is .abstractions.2.0.2.nupkg.

Semantically, the Type element of the given schema used in the file allows only one entry per extension type (as far as I can tell),
so the NuGet.Server implementation (which just rely on the underlying libraries for Package handling) works as expected.

**Comment by bradwilson** [comment]
I don't think I'll be able to get a new version of this package pushed to NuGet.org, and it doesn't permit that. That would mean a full rebuild of the stack will be necessary.

**Comment by larsw** [comment]
I understand. I guess you'll fix it for the next release. At least it's now documented, and it has the following workaround:

Remove the extra entry with ```psmdcp``` -> application/octet from the file and save it back into the NuGet package before trying to digest it with NuGet.Server.

**Comment by onovotny** [comment]
@larsw That workaround will break/remove the signature on the package.

**Comment by larsw** [comment]
Ok, I guess it's possible to first verify the sig, and remove both the p7s-file and the extra element from the file then before deploying it to a private repo.

**Comment by ChristophHornung** [comment]
It seems the psmdcp entry is also responsible for breaking the Package Manager in Visual Studio 2015. 

Simply start a new project in VS2015, go to the package manager and add xunit, then switch to the "Installed" tab in the package manager.

This will display "Error occured" with an output of "An item with the same key has already been added."

Manually removing the psmdcp entry in xunit.abstractions.2.0.2.nupkg inside the packages folder will fix the problem.

**Comment by larakrefski** [comment]
@ChristophHornung I tried doing what you said but I am not able to find a psmdcp entry in xunit.abstractions.2.0.2.nupkg. I examined the file with the Nuget Package Explorer. Where should I be seeing the duplicate entries? Please explain how to do it. Here is what I see:

![image](https://user-images.githubusercontent.com/42155524/45041510-7b68fa00-b036-11e8-9b20-3c6c0654f3d1.png)

Thank you.

**Comment by bradwilson** [comment]
Closed for age (and because a 2.0.3 was shipped for this package).
