### ISSUE TITLE
Error Assert xunit

### ISSUE THREAD

**Issue by jinujoseph** [xunit/xunit#1789]
Hi! With the new version of visual studio the 15.8.0 I get errors with the extensions, sometimes the visual studio isnt't responding
the stacktrace is this
System.NullReferenceException : Object reference not set to an instance of an object.
at async Xunit.Analyzers.AssertEqualsShouldNotBeUsedFixer.RegisterCodeFixesAsync(<Unknown Parameters>)
at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)

This issue has been moved from https://developercommunity.visualstudio.com/content/problem/312034/error-assert-xunit.html
VSTS ticketId: 664705
These are the original issue comments:
(no comments)
These are the original issue solutions:
(no solutions)

**Comment by bradwilson** [comment]
Can you provide a repro project that illustrates the issue?

**Comment by bradwilson** [comment]
Please re-open with repro project
