### ISSUE TITLE
xunit 2.4.0 Core and xunit.runner.visualstudio 2.4.0 doesn't support .Net Framework 4.6.2?

### ISSUE THREAD

**Issue by raviraj1976** [xunit/xunit#1795]
Hello,

We have come across slowness and hanging unit test cases when we upgrade xunit.Core and xunit.runner.visualstudio to 2.4.0 with Net Framework 4.6.2 and Visual studio 2017.  However no issues when using xunit.Core 2.4.0 with 2.1.0 version of xunit.runner.visualstudio and Visual studio 2017. 

xunit.runner.visualstudio 2.4.0 supports .Net Framework 4.6.2 or only .Net Framework  4.5.2, .Net Core, Net Standard library with Visual studio 2017?

What are the external NuGet package dependencies for xunit.Core 2.4.0 and xunit.runner.visualstudio 2.4.0?

Appreciate your help!

**Comment by bradwilson** [comment]
For xUnit.net 2.x, we support .NET Framework 4.5.2 or later, including 4.6.2.

You can see package dependencies on the NuGet website, like this: https://www.nuget.org/packages/xunit.runner.visualstudio

![image](https://user-images.githubusercontent.com/16944/46032576-de3b3780-c0b0-11e8-9474-e326add33b14.png)

Alternatively, you can look at our .nuspec files here: https://github.com/xunit/xunit/tree/master/src
