### ISSUE TITLE
xunit.runner.visualstudio build does not copy files marked as 'CopyAllways' from dependent projects

### ISSUE THREAD

**Issue by lstrzepek** [xunit/xunit#1796]
Repro steps:
1. Create Web project P1
2. Add appsettings.json (or other file) and mark it as 'CopyAllways'
3. Create Test project P2 and refere to P1
4. Create Test which depends on appsettings.json
5. Rebuild P2 (in this step everything is ok and files are copied)
6. Run test
7. Change something in test and run it once again

Result:
appsettings.json file is not copied to P2 bin directory
Expected behavior:
appsettings.json file exists in P2 bin directory

[Repro project](https://ufile.io/1liuq)

This scenario is common to integration tests where you need to have appsettings.jon file from tested project to properly configure TestServer

**Comment by bradwilson** [comment]
I'm not sure why you think build issues are related to xUnit.net, as we don't build your project.

**Comment by lstrzepek** [comment]
when you run test xunit is building project upfront and only during this build procedure files are not copied. Rebuild in VS works fine, even running test from console works fine. 
But you are right i should directly said that this issue is related to xunit.runner.visualstudio

**Comment by bradwilson** [comment]
> when you run test xunit is building project upfront

When you run them _how_? Unless you're talking about the no-longer-supported `dotnet xunit`, then any time your project is being built, it's not being built by us. I promise you won't find any code to build your projects anywhere in `xunit.runner.visualstudio`.

**Comment by lstrzepek** [comment]
> When you run them how?
By clicking on 
![image](https://user-images.githubusercontent.com/185352/44450832-35517680-a5f2-11e8-99f7-02a6d1cdebfd.png) green mark or in Test Explorer window
So what you are saying is that this issue could be related with visual studio?

**Comment by bradwilson** [comment]
Yes, definitely.

**Comment by sphinxy** [comment]
Problem seems to be fixed, but only in VS2019
https://developercommunity.visualstudio.com/content/problem/317986/build-before-test-run-does-not-copy-files-marked-a.html

As a workaround, https://github.com/dotnet/project-system/issues/3568#issuecomment-465323579 may help, in P1 project.
