### ISSUE TITLE
F# 4.5.0.0 under VS 15.8.1 + xUnit 2.4.0

### ISSUE THREAD

**Issue by kkkmail** [xunit/xunit#1799]
I've just literally hit a brick wall trying to configure F# 4.5.0.0 under VS 15.8.1 to run xUnit 2.4.0 tests. Here is the repo with the issue: https://github.com/kkkmail/fSharp-xUnit and a zipped solution for convenience: 
[DummyApp.zip](https://github.com/xunit/xunit/files/2320875/DummyApp.zip)

When I try to run all tests, VS comes back with this message: 

_No test is available in C:\GitHub\fSharp-xUnit\DummyApp\DummyApp\bin\Debug\DummyApp.exe C:\GitHub\fSharp-xUnit\DummyApp\Tests\bin\Debug\Tests.dll C:\GitHub\fSharp-xUnit\DummyApp\DummyApp\DummyApp.fsproj C:\GitHub\fSharp-xUnit\DummyApp\Tests\Tests.fsproj. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again._

Both the "DummyApp" and tests were created from scratch using VS and I cleared all temp files and all nuget caches prior to creating the solution as advised in various places on the web.

**Comment by bradwilson** [comment]
You're missing the NuGet package reference to `xunit.runner.visualstudio`. Once I installed that, tests were correctly discovered and run.

![Visual Studio](https://user-images.githubusercontent.com/16944/44632944-6f937e80-a938-11e8-8b16-ff1b1a21fef2.png)

**Comment by CaringDev** [comment]
Suggest to close, solved. See also on [SO](https://stackoverflow.com/questions/52019103/f-xunit-what-could-possibly-go-wrong/52031075#52031075)
