### ISSUE TITLE
Warning "xUnit1026: Theory method xx on test class xx does not use parameter xx" shown wrongly

### ISSUE THREAD

**Issue by sam1018** [xunit/xunit#1802]
The below code:
```csharp
        [Theory]
        [MemberData(nameof(Data))]
        public void TestFunc(int transactionNumber, DateTime businessDate)
        {
            int shiftId = 1;
            int terminalId = 1;

            _objectFactory.MockOdspOrderOps.Setup(r => r.GetTranData(out transactionNumber, out shiftId, out terminalId, out businessDate));
        }
```

Shows warning xUnit1026 for parameters transactionNumber and businessDate wrongly. These parameters are used in MockOdspOrderOps.Setup. Here MockOdspOrderOps is a Moq.Mock class.

xUnit version: 2.4.0

**Comment by bradwilson** [comment]
Fixed in xunit/xunit.analyzers#137

**Comment by wizofaus** [comment]
I also got this for a function that refers to the parameter as part of an interpolated format string ($"{{parameter}}") - is that fixed too?
