### ISSUE TITLE
Use editbin /LARGEADDRESSAWARE in xunit.console.x86.exe

### ISSUE THREAD

**Issue by gpetrou** [xunit/xunit#1804]
Run the following dummy example with xunit.console.x86.exe:

        [Fact]
        public void LargeAddressAwareTest()
        {
            int[] largeArray = new int[500000000];
            Assert.Equal(500000000, largeArray.LongLength);
        }

There is an expected System.OutOfMemoryException.
Now use editbin xunit.console.x86.exe /LARGEADDRESSAWARE and run the same code.
The test passes.

Would it be possible to use the editbin trick in the official xunit.console.x86.exe?
If no, is there a reason not to do that?
If yes, I could add a PR for 2.4.1.
Is there a preferred way to implement this in the build?
One option would be to try using https://www.nuget.org/packages/LargeAddressAware/
Other option would be to use https://www.nuget.org/packages/vswhere/ to get the editbin path.
Any other option?

**Comment by bradwilson** [comment]
Giving it some thought, I don't believe we want to support this. If you need access to more than 2GB of RAM, then use the 64-bit console runner.
