### ISSUE TITLE
Include full value in Assert.Empty output

### ISSUE THREAD

**Issue by ashmind** [xunit/xunit#1806]
Example:
```csharp
[Fact]
public void Empty() {
    Assert.Empty(new[] { 1, 2, 3 });
}
```

produces

```
Message: Assert.Empty() Failure
```

which is not very useful.

Would be good to get something like this instead:
```
Message: Assert.Empty() Failure
Expected: <empty>
Actual:   { 1, 2, 3 }
```

**Comment by arms11** [comment]
Hi there, I have a change ready for review for this ask. I am not able to push as the change required for this is in the submodule. Since this is my first time, could you please guide me?

**Comment by arms11** [comment]
I went ahead and created a Pull request for the change in the sub-module. Here is the link for the review...
https://github.com/xunit/assert.xunit/pull/27
Please let me know if I could have done it differently as this is my first time!
Thanks!
