### ISSUE TITLE
.NET Core console output

### ISSUE THREAD

**Issue by mattfrear** [xunit/xunit#1808]
It's 2018 and .NET Core has been out for a few years. Is it possible to write output to console from tests? I have tried using `ITestOutputHelper`, and I can see test output in Visual Studio. But I don't see anything on the console using either `dotnet test` or `dotnet xunit`.

**Comment by bradwilson** [comment]
We don't control the ability to view Output with VSTest (the engine behind `dotnet test`); we report the output to them, and then it's up to them to decide what to do with it. I suspect it's probably only visible in the TRX report, although you might also be able to see it on the console by raising the verbosity level with `--verbosity`.
