### ISSUE TITLE
"Console runner return codes" was deleted from the .NET Core docs

### ISSUE THREAD

**Issue by christianspecht** [xunit/xunit#1810]
On [the "Getting started with xUnit.net (.NET Core / ASP.NET Core)" page](https://xunit.github.io/docs/getting-started-dotnet-core), there's a bunch of navigation links at the top.

The last one is [Console runner return codes](https://xunit.github.io/docs/getting-started-dotnet-core#console-return-codes), but the actual content is missing from the page. It was deleted in [this commit](https://github.com/xunit/xunit.github.io/commit/abf0c24acbd8028ab6ccaa6d3a6cd722e1144454#diff-e6981fa5e830904ae892353fb5dda37eL425) by @bradwilson.

Was the deletion by mistake or will the return codes be changed?

**Comment by bradwilson** [comment]
They were deleted, because they were only valid for `dotnet xunit`, which is no longer supported.

**Comment by bradwilson** [comment]
I've just removed the broken link.

**Comment by christianspecht** [comment]
@bradwilson: Okay, but is there any kind of replacement for the return codes?

Previously, I had a PowerShell build script which quit the whole build if at least one test failed (return code 1):

```
dotnet test "$PSScriptRoot\src\Foo.Tests\Foo.Tests.csproj" -c Release
if ($LASTEXITCODE -eq 1) {
    exit
}
```

How can I do this without the return codes?
