### ISSUE TITLE
Jenkins failes to cancel xunit.console run

### ISSUE THREAD

**Issue by Lyra2108** [xunit/xunit#1811]
This issue is similar to #1338. But that was reported to be fixed with 2.3.1 and this error occurs with 2.4.0.

When a build job is canceled, while it currently runs the test , the xunit.console runner is not terminating. This causes the next builds to fail, because the `git clean -fdx`, which we do in the beginning, is failing.

# How to reproduce

1. Have a project where the tests take longer. Our project has ~16k tests and needs ~4 min to run them all.
2. Execute them automatically on Jenkins e.g. on changes to a Github-PR or a Gerrit patchset.
3. Cancel the build manually or automatically (it is common that if you upload a new Gerrit patchset to a change and a build for the same change is running the older one is canceled, because you do not need it any longer)
4. Have a new build running in the same workspace
-> It fails to clean the workspace because of file locks. Also in the process manger of the build node you can see the process still running.

This process will keep running more or less the time it needs to finish the test run regularly. 

# Question

Is this the bug of #1338 and it got added again to 2.4.0? 
Or if everything is working as intended, would it be possible to have a flag for the console runner, which doesn't require 2 times Ctrl-C to be force canceled?

**Comment by bradwilson** [comment]
`dotnet xunit` is no longer supported.

Is your bug with `dotnet xunit` (like #1338) or is it with `xunit.console`?

**Comment by Lyra2108** [comment]
It is with the console runner. We execute on the Jenkins the following  stage:

```
stage('Run the tests') {
    steps {
        powershell 'ci/nuget.exe install xunit.runner.console -Version 2.4.0 -OutputDirectory ci'
        powershell 'ci/xunit.runner.console.2.4.0/tools/net452/xunit.console  <path to dll> -xml ./result.xml'
    }
}
```

as a workaround we kill now the process if the checkout failed:

```
stage('Git checkout') {
    steps {
        script {
            retry(3) {
                try {
                    checkout scm
                } catch (Exception e){
                    // Due to https://github.com/xunit/xunit/issues/1811 sometimes the console runner is still there this gets the process and kills it.
                    // If there are errors in this step then the previous checkout failed due to other reasons
                    powershell '''
                        $searchPath = $env:WORKSPACE -replace '\\\\','\\\\'
                        $xunit = gwmi win32_process | Where-Object { $_.Path -match $searchPath } | Where-Object { $_.Name -match 'xunit.console'}
                        Taskkill /PID $xunit.Handle /F
                    '''
                    throw e
                    }
            }
        }
    }
}
```

**Comment by bradwilson** [comment]
I believe the issue is not Jenkins related so much as it is that we allow Ctrl+C to normally let tests finish; if a test is run away and never coming back, a second Ctrl+C is required to hard terminate it.

That said, Jenkins should not rely on Ctrl+C to cancel a running application. It should simply terminate the process. I unclear what we would want to do here on our side.

**Comment by Lyra2108** [comment]
Would it be possible to have a command line parameter which kills it on the first Ctrl + C? Than we could call it with e.g. ```ci/xunit.runner.console.2.4.0/tools/net452/xunit.console  <path to dll> -xml ./result.xml --fast-exit```

**Comment by meirkr** [comment]
> `we allow Ctrl+C to normally let tests finish;

May I ask why?
The world wide convension is that ctrl c terminates a running process.
Why do we need and exceptional double srrike?

**Comment by bradwilson** [comment]
> The world wide convension is that ctrl c terminates a running process.

I disagree with this assertion, but to be clear, we do let an _**interactive user**_ use Ctrl+C to request things be completed, _**and**_ give those users an opportunity to press Ctrl+C again to indicate that they don't want to wait.

> Why do we need and exceptional double srrike?

Hard-terminating processes can leave things in bad states. One easy example comes to mind: cleaning up after yourself when tests end, like cleaning up database records or deleting temporary files.

That said, if Jenkins wants to kill a process, the only hard and fast "kill a process" that exists is actually killing the process. Pressing a keyboard shortcut and hoping that it behaves to immediately terminate a process is a bad design.

**Comment by Lyra2108** [comment]
> > The world wide convension is that ctrl c terminates a running process.
> 
> I disagree with this assertion, but to be clear, we do let an _**interactive user**_ use Ctrl+C to request things be completed, _**and**_ give those users an opportunity to press Ctrl+C again to indicate that they don't want to wait.

I think there is a difference between "wanting to wait" and "expecting a gracefull shutdown".
I would expect one Ctrl + C hit to finish the currently in progress tests and finish the tear down of those to do a graceful shutdown. I would not expect it to run also the tests which where not even started. If I remember it correctly in our case it run the entire suite for the full time. Which does not make sense for a gracefull shutdown with linear test runs. It could finish after the test would be done. Which would also work usually perfectly fine with Jenkins as it waits some time before it reuses the workspace for the next test.

**Comment by bradwilson** [comment]
>I would expect one Ctrl + C hit to finish the currently in progress tests and finish the tear down of those to do a graceful shutdown. I would not expect it to run also the tests which where not even started.

It's likely that more tests have started than you realize. If you the verbose reporter (`-verbose` with the command line runner) it should show you information lines when each test starts, in addition to reporting when tests finish.

**Comment by Lyra2108** [comment]
There where no parallel tests in that test suite. So if more then one test case would have been started, I would consider that another bug. 
I moved to an other team in the mean time and therefor do not longer have the xunit test for which I reported this accessible. Therefore it is hard for me to run the test right now.
