### ISSUE TITLE
Tests not reported in TeamCity with dotnet test

### ISSUE THREAD

**Issue by JamesFenton** [xunit/xunit#1813]
The `dotnet xunit` tool has been removed in 2.4.0, leaving us with `dotnet test` as the recommended way of running tests. 

TeamCity does not capture the test output when using `dotnet test`

To reproduce:
```
set TEAMCITY_PROJECT_NAME=foo
dotnet new xunit
dotnet test
```
No `##teamcity[...` messages are output, and TeamCity does not report the number of successful tests (it just says "Build succeeded"

Versions:
dotnet sdk 2.1.401
Microsoft.NET.Test.Sdk 15.8.0
xunit 2.4.0
xunit.runner.visualstudio 2.4.0

Related issue from last year https://github.com/xunit/xunit/issues/1162

**Comment by bradwilson** [comment]
This is not really an issue for us; this is a question about how to properly integrate VSTest (the engine behind `dotnet test`) with Team City.

**Comment by JamesFenton** [comment]
Thanks for the feedback, I found https://github.com/Microsoft/vstest/issues/1590#issuecomment-393460921 which is the same problem (with a solution). 

We run our tests from a PowerShell script that calls `dotnet test`. What is the recommended way of running Xunit tests on .Net Core? `dotnet test`?

**Comment by bradwilson** [comment]
That is the only way to run tests in .NET Core today.

**Comment by bradwilson** [comment]
Closed as "external".
