### ISSUE TITLE
Tests failing due to custom JsonConverter

### ISSUE THREAD

**Issue by felschr** [xunit/xunit#1815]
Some of my integration tests are failing with the following error:
`The active test run was aborted. Reason: Error converting value "PT36.558305S" to type 'System.TimeSpan'. Path 'TestRunCompleteArgs.ElapsedTimeInRunningTests'.`

I have a custom JsonConverter which I set as the global default in my ASP.NET Core project via:
`JsonConvert.DefaultSettings`
It seems that xunit also uses these default options internally which causes issues for me.

When debugging I could see that my custom converter's `WriteJson` method was called. But not it's `ReadJson`. So I guess for reading the value xunit is later using their own settings.

**Comment by bradwilson** [comment]
I'm not sure in what context you're talking about here, but all JSON parsing that's done internally by xUnit.net (namely, the parsing of the JSON configuration files) uses a custom parser that you cannot configure.

As for type conversions for theory data, we use the built-in type conversion system. If you register custom type converters in the standard ways, they will be used.

**Comment by tucanus** [comment]
Same for me.
It is easy to reproduce, simply create a xUnit test project, add reference to Newtonsoft and create a class for test with code below

`
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Xml;
using Xunit;

namespace TimeSpanTester.xTest
{
    public class TimeSpanNewtonsoftConverter : JsonConverter<TimeSpan>
    {

        public override TimeSpan ReadJson(JsonReader reader, Type objectType, TimeSpan existingValue, bool hasExistingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.String:
                    return XmlConvert.ToTimeSpan((string)reader.Value);
                default:
                    throw new NotImplementedException($"Cannot convert {reader.TokenType} to TimeSpan");
            }
        }

        public override void WriteJson(JsonWriter writer, TimeSpan value, JsonSerializer serializer)
        {
            writer.WriteRawValue($"\"{XmlConvert.ToString(value)}\"");

        }
    }

    public class TimeSpanTest
    {

        public TimeSpanTest()
        {
            JsonConvert.DefaultSettings = () => new JsonSerializerSettings
            {
                Converters = new List<JsonConverter>() { new TimeSpanNewtonsoftConverter() }
            };
        }
        [Fact]
        public void Test()
        {
            Assert.True(true);
        }
    }
}
`

After execution Test output window reports:
`Error converting value "PT1.0311192S" to type 'System.TimeSpan'. Path 'TestRunCompleteArgs.ElapsedTimeInRunningTests'.`

**Comment by bradwilson** [comment]
I am unable to repro with the given code:

![image](https://user-images.githubusercontent.com/16944/121787380-928b8d80-cb7a-11eb-8024-742a5f545b4e.png)

Please re-open with a full repro project. Thanks!
