### ISSUE TITLE
Error message doesn't respect -nocolor option

### ISSUE THREAD

**Issue by BruceForstall** [xunit/xunit#1816]
This error message:
```
Skipping -html because XSL-T is not supported on .NET Core 1.x
```
does not respect the `-nocolor` option. (That is, it emits color codes unconditionally, which show up as garbage in text log files.)

Looks like this code:
```
        static void Handler_XslTransform(string key, string resourceName, XElement xml, string outputFileName)
        {
#if NETCOREAPP1_0
            ConsoleHelper.SetForegroundColor(ConsoleColor.Yellow);
            Console.WriteLine($"Skipping -{key} because XSL-T is not supported on .NET Core 1.x");
            ConsoleHelper.ResetColor();
#else
```

**Comment by bradwilson** [comment]
Closing this issue, since .NET Core 1.0 will not be supported on v3 (so this error message, and its lack of respect for color issues, is now irrelevant).
