### ISSUE TITLE
Does not support .NET Framework v4.0

### ISSUE THREAD

**Issue by AraHaan** [xunit/xunit#1817]
I got a project that targets .net standard 2.0, net40, net45, net451, net452, net46, net461, net462, net47, net471, and net 472 on both the main assemblies and the unit test assembly. I was expecting that xunit would work on the net40 assembly version of my library too. However it seems that the unit test project would fail under the 4.0 target.

**Comment by onovotny** [comment]
Targeting 4.0 does not mean running on 4.0. There are no supported 4.0 runtimes in the wild. The lowest supported runtime is .NET 4.5.2, and most of them are higher.

**Comment by AraHaan** [comment]
ah, it also seems that if I compile unit tests with the latest nuget pre-build of xunit that the build will fail for ``netcoreapp2.1`` and the ``netcoreapp2.0`` targets, but I cannot possibly target ``netcoreapp1.0`` due to things like missing ``System.Environment.CurrentDirectory``.

**Comment by onovotny** [comment]
Do you have a small repro? xUnit does support `netcoreapp2.1` and `netcoreapp2.0`.

**Comment by AraHaan** [comment]
Sure, it is here: https://github.com/AraHaan/XmlAbstraction/ Maybe there is a problem somehow on my end.

**Comment by AraHaan** [comment]
@onovotny it seems that appveyor also has this issue too.

**Comment by bradwilson** [comment]
As an FYI, `netstandard` is not supported for unit test projects. https://xunit.github.io/docs/why-no-netstandard

![image](https://user-images.githubusercontent.com/16944/45771378-cb7cba80-bbf9-11e8-8bc3-9a1052dcec45.png)

**Comment by bradwilson** [comment]
So I edited the .Test.csproj file, removed the unsupported frameworks (`netstandard2.0`, `net45`, and `net451`), and everything built and ran for me. (There is one failing test which fails on all frameworks. 😝)

![image](https://user-images.githubusercontent.com/16944/45771845-0b906d00-bbfb-11e8-9c26-4c2040280c0b.png)

**Comment by AraHaan** [comment]
hmm interesting, you are using dotnet test, I am using OpenCover to generate coverage xml files to send to codecov.io. If only ``dotnet test`` could output that xml coverage data for codecov.io so I can drop the ``OpenCover`` dependency.

**Comment by bradwilson** [comment]
There's no plan to integrate code coverage into xUnit.net.

**Comment by bradwilson** [comment]
No issues running it here by hand. I'm willing to believe this is an AppVeyor issue, perhaps because the version of the console runner they're using is too out-of-date for your needs...?

![image](https://user-images.githubusercontent.com/16944/45774239-51503400-bc01-11e8-8833-0272e2cd29e8.png)

**Comment by bradwilson** [comment]
If you wanted, you could add the NuGet reference to `xunit.runner.console` to your test project, and then run it from `~\.nuget\packages` just like you to today for OpenCover.

**Comment by AraHaan** [comment]
ah ok, also that failing test was patched on master since the time you ran the original test.

**Comment by bradwilson** [comment]
Closing as "won't fix" (at least as far as the original title is concerned).
