### ISSUE TITLE
How to use the verbose logger with xunit.console?

### ISSUE THREAD

**Issue by ViktorHofer** [xunit/xunit#1818]
Maybe I'm missing something but I looked through documentation and couldn't find anything regarding how to enable the verbose logger. How do I enable it with xunit.console(.dll/.exe)? I can't find an option for it here: https://github.com/xunit/xunit/blob/master/src/xunit.console/CommandLine.cs. I know there was a -verbose switch in dotnet-xunit.

**Comment by bradwilson** [comment]
It's the same: `-verbose`.

![image](https://user-images.githubusercontent.com/16944/45909780-daf63200-bdb8-11e8-82f2-e200857ef591.png)

**Comment by bradwilson** [comment]
The reason you don't see it in CommandLine.cs is because reporters are discovered at runtime.

https://github.com/xunit/xunit/blob/1fb6b672768bed98f5e7b6656c1bbb3792ed0530/src/xunit.console/ConsoleRunner.cs#L127-L175

**Comment by ViktorHofer** [comment]
thanks!
