### ISSUE TITLE
Consider separate verbosity level for listing tests being ran

### ISSUE THREAD

**Issue by codefactorydevelopment** [xunit/xunit#1820]
If we have a test suite, it would be nice to have separate verbosity level (in `dotnet test`) that would be like `q[uiet]` but that would include list of all tests within suite/filter that was ran.

Reason is that currently, if we want to see the list of particular tests being ran, we also get a lot of other information which is completely unrelated to test results.

Would it be possible to organize verbosity a bit different?

**Comment by bradwilson** [comment]
We don't control the verbosity level of `dotnet test`. You should take this issue up with the VSTest team.

**Comment by codefactorydevelopment** [comment]
My understanding was that `dotnet test -v level` takes whatever underlying `dotnet xunit` output was. and i haven't found any verbosity level with `dotnet xunit` either that would output only tests that were ran along with overall test statistics.

Please correct me if i am wrong.

**Comment by codefactorydevelopment** [comment]
@bradwilson you're right, this is for VSTest team.

thanks for clarifying that!
