### ISSUE TITLE
TestDisplayName does not print enough digits to differentiate certain inputs

### ISSUE THREAD

**Issue by tannergooding** [xunit/xunit#1822]
**Repro Steps**
* Create a new 'xUnit Test Project (.NET Core)
  * I used the built-in template from VS 2017 15.8
* Set the contents of `UnitTest1.cs` to the following:
```csharp
using Xunit;

public class UnitTest1
{
    [Theory]
    [InlineData(1.17549421E-38f)]
    [InlineData(1.17549435E-38f)]
    public void Test1(float f)
    {

    }
}
```
* Run the tests and examine the "TestDisplayName" that is printed to the result logs

**Expected Behavior**
The inline data is printed with enough precision to differentiate the two inputs.

**Actual Behavior**
The `TestDisplayName` for both scenarios is `Test1(f: 1.175494E-38)`.

**Comment by tannergooding** [comment]
`floats` should be printed using `G9` and `doubles` should be printed as `G17` to ensure that they always contain enough digits to differentiate the values (when the number of significand digits is greater than the default of `7`/`15`).

**Comment by tannergooding** [comment]
CC. @ViktorHofer

**Comment by tannergooding** [comment]
@bradwilson, I commented on https://github.com/xunit/xunit/pull/2341#discussion_r664790090, but could you reopen?

The lengths specified aren't quite right to guarantee unique outputs for any input on `float` and are more precise than necessary for `double`.

**Comment by Xcodo** [comment]
@tannergooding Sorry, I must have got my format specifiers mixed up. I can fix it.

**Comment by Xcodo** [comment]
I don't think "R" is a good idea personally as it will give different results on dotnet core vs framework. Happy to be overuled though.

**Comment by bradwilson** [comment]
No worries, I'll fix this on today's stream. I agree, G is what we want here. Roundtripability isn't an important requirement IMO, as these are for display purposes only.
