### ISSUE TITLE
AsyncLocal<T> lost its state during multiple test runs with Theory attribute

### ISSUE THREAD

**Issue by LiangZugeng** [xunit/xunit#1826]
I have a class with a static field using AsyncLocal<T> to maintain the local state, it works OK in a single test case (using FactAttribute), however in repeated test cases using TheoryAttribute and InlineDataAttribute, AsyncLocal<T>'s state was set to null from the 2nd run of the same test case.

I created a [minimal repro code](https://github.com/LiangZugeng/xunit-issue), please take a look and advice. Thank you.

**Comment by bradwilson** [comment]
This is not supported. Two tests are not guaranteed to share the same execution context, so AsyncLocal<T> will not work.

Fixtures are the only supported mechanism for sharing data between tests. https://xunit.github.io/docs/shared-context

**Comment by bradwilson** [comment]
Closing as by-design.
