### ISSUE TITLE
No xunit2 XML formatter anymore for .NET Core

### ISSUE THREAD

**Issue by mattleibow** [xunit/xunit#1827]
I used to use the `dotnet-xunit` package, but I see it was deprecated and no longer supported. I switched to the `dotnet test`, and that is mostly fine - except for 2 things:

 - logging passing tests: #1078 (not too essential)
 - no way to use the xunit2 formatter like with the old system.

The missing formatter is a fairly big breaking change since now I need to do a fair bit of work. Either I have to get my .NET Framework tests to use the new format, or I have to update my CI to be able to handle 2 different formats, and merge the results.

I did find this guy https://github.com/spekt/xunit.testlogger and I believe it does the job. But... Why? Why drop your own format?

**Comment by bradwilson** [comment]
We didn't drop the format so much as we dropped the only runner that supported it.

This will be resolved in v3.
