### ISSUE TITLE
Test filtering expressions

### ISSUE THREAD

**Issue by mattzink** [xunit/xunit#1833]
It would be nice if xUnit supported passing a simple expression argument to the runners to filter down the set of tests to execute. Today, xUnit only supports passing `-trait`, `-notrait`, `-method`, etc arguments that have preset boolean logic applied. This means that certain test combinations are not expressible, with the only alternatives being performing multiple runs, or listing each test method individually on the command line. For those of us with very large test bases, neither alternative is very practical.

`dotnet vstest` has a similar `--TestCaseFilter` option that allows passing an expression, but that runner is missing many other nice features/perfomance of xUnit's runners, so it would be great if xUnit could be enhanced in this way.

**Comment by bradwilson** [comment]
Related: https://github.com/microsoft/testfx/blob/main/docs/mstest-runner-graphqueryfiltering/graph-query-filtering.md

**Comment by mattzink** [comment]
That related mstest filter expression is exactly what I was thinking too. I hope xunit can add such support.

**Comment by bradwilson** [comment]
I have some open questions [here](https://github.com/microsoft/testfx/discussions/3781) and I'm curious whether anybody here has any thoughts or questions on the query language that I haven't asked.

**Comment by bradwilson** [comment]
I have a draft of the documentation of the feature here. It's not linked from the homepage yet, and my implementation is still incomplete, but I thought I'd put it here if anybody had any feedback. https://xunit.net/docs/query-filter-language

**Comment by bradwilson** [comment]
To be clear, it's inspired by (but not directly an implementation of) the MSTest query syntax. In particular, I left off `**`, and added multipart logical grouping so you can mix AND and OR logical operations. I think the latter is a little complex to look at, but seemed like enough value-add to include.

**Comment by mattzink** [comment]
Wow! Thank looks great!

**Comment by bradwilson** [comment]
Available in `0.4.0-pre.16` https://xunit.net/docs/using-ci-builds
