### ISSUE TITLE
Latest version large number of member data test cases timing rest of the tests out

### ISSUE THREAD

**Issue by mwpowellhtx** [xunit/xunit#1834]
In my test suite I am rolling up a non-trivial number of test cases. I mean a seriously large number of them. This is unavoidable in order to property verify functionality. In prior versions of ``Xunit`` this would work just fine. The roll up itself would take some time, but the tests at least kept running, particularly if I was running these tests in conjunction with others in my test sessions.

However, it seems with the latest version of ``Xunit`` this is breaking down and others among my unit tests are timing out with *inconclusive".

First, is there a way to put a hold on tests until the member data test cases have rolled up?

Second, is there a timeout I can set, disable, etc?

Typically, I am approaching member data test cases something like this:

```C#
private static IEnumerable<object[]> _memberDataTestCases;

public static IEnumerable<object[]> MemberDataTestCases
{
    get
    {
        IEnumerable<object[]> GetAll()
        {
            IEnumerable<object> GetOne(...)
            {
                yield return someArgs;
            }

            yield return GetOne(...).ToArray();
        }

        return _memberDataTestCases ?? (_memberDataTestCases = GetAll().ToArray());
    }
}
```

Depending on the test case, ``GetOne(...)`` or variations thereof can be more or less complex.

In this case I've got some 15,125+ for a given test case.

Like I said, this was not a problem before the most recent ``Xunit`` release. So whatever changed between then and now has had an adverse effect on rolling up a range of tests, test cases, etc, timing out.

**Comment by bradwilson** [comment]
Unless you use the `Timeout` parameter on a Fact/Theory, we will let your tests run as long you want. In addition, we don't even have a state of "inconclusive".

My guess is whatever runner you're using is doing this you, and it has nothing to do with the core xUnit.net framework itself. What runner is it?

**Comment by mwpowellhtx** [comment]
@bradwilson I'm not doing anything timeout-wise that I am aware of. I am using the *Visual Studio* test runner.

**Comment by bradwilson** [comment]
Is this desktop CLR? If so, do you experience the same issues with the console runner?

**Comment by mwpowellhtx** [comment]
@bradwilson Actually, it is; targeting *Framework 4.6.2* at the moment. Is that a problem? There's nothing firm holding me there that I am aware of; I just needed a run-time CLR and it seemed like the best choice at the time.

I haven't tried with console runner. Typically I just run with *Visual Studio*.

**Comment by mwpowellhtx** [comment]
@bradwilson Also, just to be clear, by ["we"](/xunit/xunit/issues/1834#issuecomment-430328803), I want to be clear, the *Visual Studio* runner is now merged with the ``Xunit`` monolithic repository.

**Comment by mwpowellhtx** [comment]
So... I should be able to run against *Framework 4.7.x*? Or even ``netcore``?

**Comment by bradwilson** [comment]
You have several choices for next steps:

- Use `net472`
- Downgrade to xUnit.net `2.3.1`
- Upgrade to xUnit.net `2.4.1-pre.build.4071`

I would not suggest using .NET Core unless you're actually interested in testing on .NET Core.

**Comment by mwpowellhtx** [comment]
Thanks. So far so good targeting ``net472``. The tests seem to make steadier progress at any rate.

Still would be nice to buffer a few more of the test cases before they turn around and get evaluated in the test.

Closing for now.

**Comment by mwpowellhtx** [comment]
Well, I spoke too soon. It got to a point, then started stuttering, and finally self-aborted out. I did not abort it.

**Comment by mwpowellhtx** [comment]
Honestly, whatever the change was, or the motivation for it, I was depending on ``netstandard2.0`` bits being there; and I was targeting ``net462`` prior to this without difficulty. I hate the word "performant", because what does that really mean, but not being able to make it through the testing now on account of these changes is troubling.

**Comment by mwpowellhtx** [comment]
Still having problems even after downgrade to *2.3.1*. I did have a BSOD this morning starting up, *BAD_POOL_HEADER*. My system did "recover" to a prior system restore point, but I am suspicious that there is still something to do with that issue.

Closing this, I'm starting to think it is probably just happy coincidence I am seeing the performance that I am seeing, probably subsequent to the BSOD.

If I learn any different one way or another I'll follow up.

**Comment by mwpowellhtx** [comment]
I tried disabling parallelization, this helps a little, but not much. The VS runner gets through most of the tests, but barely 25% of the way through the big ones VS halts and I get a "restart VS" prompt.

I don't know; something definitely got hosed this morning with that BSOD.

Trying a couple of things, repairing VS; maybe clearing some of the caches involved, stuff like this.

**Comment by mwpowellhtx** [comment]
I think this is what it is/was: still in the process of repairing VS, but it's definitely churning away and repairing. Possibly my C: is teetering on the edge of needing to be replaced and/or rebuilt. Might need to look into upgrading to Win 10 x64 Pro while I'm at it.

**Comment by mwpowellhtx** [comment]
Still don't know what the issue is; repaired VS, seemingly to a "blank slate" scenario. Reinstalled R#, for instance. Still, the test cases are not fully presenting before the runner is attempting to evaluate them.

Running against ``xunit2.3.1``.

This is definitely a change in behavior and I'm not entirely certain why. Perhaps a change in the CLR?

I need a way for ``xunit``, the ``runner``, or something like that, to hold until the test cases have fully presented. It's causing issues in the test runner, and eventually VS crashes out and shows a *Restart VS* message.

Oh, and it would be nice to re-run single test cases while there, but I need to get past this queue consumption issue first.

**Comment by mwpowellhtx** [comment]
I'm looking into the [``configuration``](http://xunit.github.io/docs/configuring-with-json) for possible options. Open to any other suggestions. Honestly, not sure why I didn't see these problematic behaviors before, unless those options somehow were set/re-set in the upgrade/downgrade shuffle...

**Comment by bradwilson** [comment]
Wait, are you running the tests with VSTest or with R#?

**Comment by mwpowellhtx** [comment]
I've tried both the R# runner and the Test Explorer, including now trying to furnish my own ``xunit.runner.json``. The behavior I am running afoul of is what appears to be ``preEnumerateTheories``. The default behavior was indeed exhibited in ``2.3.1``, but has somehow now either been changed or "reverted" to ``preEnumerateTheories=false`` and will not get unstuck from that for the life of me. Additionally, I'm not positive, but I may also be running into ``appDomain`` issues as well. It seems like the upgrade to ``2.4.0`` carried with it some system wide settings and my project specific settings may be ignored somewhere in the pipeline. Can you clarify please?

**Comment by mwpowellhtx** [comment]
The metric I have at the moment is the R# runner is receiving between 4-5 test cases in the queue at a time and evaluating those. This behavior definitely changed from before where the entire set of 15,125 would roll up, then the test cases would evaluate. I'm not sure this is a difference in CLR, or the xunit JSON options or what have you.

My options are currently:

```JSON
{
  "appDomain": "required",
  "longRunningTestSeconds": 0,
  "preEnumerateTheories": true,
  "shadowCopy": true
}
```

And are furnished via the ``<AssemblyName/>.xunit.runner.json`` convention.

**Comment by mwpowellhtx** [comment]
I'm not positive whether this is connected at all, but I've got a *.tools/dotnet-xunit/2.3.1* folder in my NuGet global packages folder on my system. Scanning these files, I do not see anything that jumps out at me as specifically some sort of global xunit settings, but it's rather in depth the bits that are recorded there, so I cannot say.

**Comment by mwpowellhtx** [comment]
I'm still uncertain, trying to wrap my head around the settings pipeline. The *Test Explorer* seems to be running okay with the settings:

```JSON
{
  "appDomain": "required",
  "longRunningTestSeconds": 0,
  "preEnumerateTheories": true,
  "shadowCopy": true
}
```

Trying to wrap my head around how/where the bits are landing in the R# test runner pipeline. Possibly something to do with shadow copying?

**Comment by mwpowellhtx** [comment]
> Those are all default values. :-/

I agree; however, the exhibited behavior would lead me to believe that I've got some sort of mystery configuration artifact other than that, in particular ``preEnumerateTheories=false``.

This apparently since shuffling the upgrade to ``xunit 2.4`` and downgrade to ``xunit 2.3.1``.

I'm reaching out to the JB folks as well, but I wondered if there was anything from an xunit standpoint, some artifacts, etc, I may be missing.

**Comment by bradwilson** [comment]
Honestly, I have no idea whether they honor that file or not.

**Comment by mwpowellhtx** [comment]
That's what I'm investigating right now. At least according to their documentation they do, but in what orders, whether they are dumping some sort of "default" artifacts that are taking precendence, I don't know yet. Obviously, if I understand the configuration, *something* is overriding instead of my user furnished config.

**Comment by mwpowellhtx** [comment]
Closing for now. If something comes up will file a new issue afresh.
