### ISSUE TITLE
Need to know purpose of console runner tools targets

### ISSUE THREAD

**Issue by mwpowellhtx** [xunit/xunit#1836]
For instance, ``net452``, ``netcoreapp1.0`` and ``netcoreapp2.0`` are represented. Does this need to necessarily align with the assembly under test? That is, I am targeting ``net472`` in my case. Thanks!

**Comment by bradwilson** [comment]
In that case, you'd use the `net452`.

**Comment by mwpowellhtx** [comment]
Thanks!

**Comment by mwpowellhtx** [comment]
@bradwilson When I have unit tests targeting ``netcoreapp2.0`` for instance, I would "invoke" the *tools\netcoreapp2.0\xunit.console.dll* assembly? I may misunderstand that convention; I am trying starting with ``dotnet run`` for instance, but this do, and then specifying the output DLL, but this does not seem to be the same convention as for the executable? In other words, when *dotnet running* the ``netcoreapp2.0`` test assembly wants a *--project*, literally that's the ``.csproj``?

**Comment by bradwilson** [comment]
It's not something we support. We ship those DLLs there basically to support some teams at Microsoft who require them. It's not as simple as a `dotnet run`; you have to use `dotnet exec` with several flags, and it still has many of the same issues that we had with `dotnet xunit` which caused us to abandon that tool (it basically did automatically for you what you would need to do by hand).

The only officially supported way to run xUnit.net 2.x tests for netcoreapp is with `xunit.runner.visualstudio` and `dotnet test` and/or the Test Explorer UI inside Visual Studio.

**Comment by mwpowellhtx** [comment]
Okay, being couched in that preface, how do I facilitate that happening? What options, etc?

**Comment by bradwilson** [comment]
https://github.com/xunit/xunit/blob/c54cc52ffb275c81afed022521870193bbca6c39/src/dotnet-xunit/Program.cs#L422-L457

**Comment by mwpowellhtx** [comment]
So, assuming I've changed directory to my ``bin\Debug\netcoreapp2.0`` directory, if I provide something like this:

```
dotnet exec path\to\packages\xunit.runner.console.version\tools\netcoreapp2.0\xunit.console.dll assembly.under.test.dll xunit-options
```

**Comment by bradwilson** [comment]
No, you also need the arguments for the .deps.json and .runtimeconfig.json files (those come before the xunit.console.dll argument).

**Comment by mwpowellhtx** [comment]
I need to provide what? Artifacts from the build? i.e. there is a ``.deps.json``? Or ``.runtimeconfig.json``? I'm not as familiar with these.

**Comment by bradwilson** [comment]
Yes, you'll see them in the build folder. Here is the example for `test.xunit.assert.dll`:

![image](https://user-images.githubusercontent.com/16944/47260967-2b28e880-d47a-11e8-8eb9-3397120c62fe.png)

(You want the `.runtimeconfig.json` file; you can ignore the `.runtimeconfig.dev.json` file)

**Comment by mwpowellhtx** [comment]
In fact I see them. :+1: Thanks for clarifying that.

**Comment by mwpowellhtx** [comment]
Maybe a stupid question, but the *xUnit.net* ``deps`` and ``runtimeconfig``, correct? That would make better sense, positionally speaking, than the assembly under test, at any rate.

**Comment by bradwilson** [comment]
Nope. The ones for your test assembly.

**Comment by bradwilson** [comment]
Did you review the code link I pasted in?

**Comment by mwpowellhtx** [comment]
The parts about the ``var args`` I gather. So I actually need the ``--depsfile`` and ''--runtimeconfig`` parameters. ``--fx-version`` as well?

**Comment by bradwilson** [comment]
If you want to pick one explicitly, then you need --fx-version. If you want to let the system pick one for you, then you don't need it.

**Comment by mwpowellhtx** [comment]
I understand. What do we do for Xml logging? Or detecting "errorlevel" (or similar) results?

**Comment by bradwilson** [comment]
It has the same command line options as the desktop CLR console runner, and returns the same error codes.

**Comment by mwpowellhtx** [comment]
Fabulous! :+1: :+1: :+1: Works great, thank you!
