### ISSUE TITLE
System.InvalidOperationException: Could not find/load any of the following assemblies: xunit.execution.dotnet.dll

### ISSUE THREAD

**Issue by MarcoRossignoli** [xunit/xunit#1839]
If I create a xunit project template `dotnet new xunit` and after I want to use `xunit.runner.console` from `launchSettings.json`
```
{
  "profiles": {
    "xunittest": {
      "commandName": "Executable",
      "executablePath": "dotnet",
      "commandLineArgs": "$(XunitConsoleNetCore2AppPath) $(TargetPath) -wait"
    }
  }
}
```
Command seems ok 
`"C:\Program Files\dotnet\dotnet.exe" C:\Users\xxx\.nuget\packages\xunit.runner.console\2.4.0\build\..\tools\netcoreapp2.0\xunit.console.dll C:\Users\xxx\Downloads\xunittest\bin\Debug\netcoreapp2.1\xunittest.dll -wait`

Console output
```
xUnit.net Console Runner v2.4.0 (64-bit .NET Core 4.6.26614.01)
System.InvalidOperationException: Could not find/load any of the following assemblies: xunit.execution.dotnet.dll
```

I read this guide https://xunit.github.io/releases/2.3-rc1

Is it still supported?
Repro [xunittest.zip](https://github.com/xunit/xunit/files/2510753/xunittest.zip)

**Comment by bradwilson** [comment]
Unfortunately, no. We officially stopped supporting both `dotnet xunit` and the .NET Core console runner in 2.4. We continue to include the binary in the NuGet package for some advanced use cases that cannot be addressed in other ways, but those users are not supported.

**Comment by MarcoRossignoli** [comment]
Thank's for quick reply, maybe you can help me...I like develop/test using very fast path on VS(I don't use VS text explorer), now I developed custom console runner using some xunit binary(copied some code from xunit console runner from codebase), so I can put it on launchsettings.json and use all filter like method/class etc...I click F5 and go(very similar to xunit.console.dll)!Very fast very good.
Is there a way to have same behaviour with current version of xunit without custom code?
I prefer use a long term supported way if it exists!For now I need to add strong reference to some external ref lib to my custom runner to resolve all correctly.

**Comment by bradwilson** [comment]
There's no way to do this today.

We're making changes to the design of xUnit.net v3 that will probably be more like what you're doing today.

**Comment by MarcoRossignoli** [comment]
Understood...thank's a lot for explanation!
I close this issue.
