### ISSUE TITLE
Linux arm/arm64 intermittent failures

### ISSUE THREAD

**Issue by echesakovMSFT** [xunit/xunit#1842]
We recently switched to using **xunit.console.dll** for running tests in https://github.com/dotnet/coreclr on Linux arm and Linux arm64 and we immediately started seeing the following failures during the test runs https://github.com/dotnet/coreclr/issues/20392
```
$CORE_ROOT/corerun $CORE_ROOT/xunit.console.dll [List of test assemblies]

System.IO.FileLoadException: Could not load file or assembly 'Exceptions.Finalization.XUnitWrapper, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (Exception from HRESULT: 0x80131509 (COR_E_INVALIDOPERATION))
System.IO.FileLoadException: Could not load file or assembly 'Exceptions.ForeignThread.XUnitWrapper, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (Exception from HRESULT: 0x80131509 (COR_E_INVALIDOPERATION))
```

These are hard to reproduce on a local machine issues and sometimes it would take 20-30 runs to actually see the failure. But they are failing pretty consistently in our CI jobs.

I tried to investigate the failures to see if this is our runtime issue or an Xunit issue (you can see https://github.com/dotnet/coreclr/issues/20594 for more information). What I suspect causes this exception (System.IO.FileLoadException) is another exception (System.InvalidOperationException) thrown when multiple threads call LoadManagedDll and modify managedAssemblyCache https://github.com/xunit/xunit/blob/9d10262a3694bb099ddd783d735aba2a7aac759d/src/common/AssemblyResolution/DependencyContextAssemblyCache.cs#L156-L165

My question if this is a known issue? Would you be interested to investigate? 

I also was trying to add a simple instrumentation code to Xunit to see it this is a case. But as soon as I compile my own version of Xunit and use this to run our tests I can't reproduce the issue anymore.

I also see differences in IL code for my compiled version of xunit.console.dll (ad20ed120a3653d6af533b76cf8a04f096095349) and for a version published on NuGet (https://www.nuget.org/packages/xunit/2.4.1-pre.build.4059 ). This is an example of such code difference 
```
17753c18019
<       IL_002a:  ldstr      "File not found: {0}"
---
>       IL_002a:  ldstr      "File not found: "
17755,17756c18021,18022
<       IL_0030:  call       string [System.Runtime]System.String::Format(string,
<                                                                         object)
---
>       IL_0030:  call       string [System.Runtime]System.String::Concat(string,
>                                                                         string)
```

Can you please tell what version of Visual Studio (and Roslyn) is used during Xunit official build? I am gonna try to see if I can get this issue reproduced locally using that version of Roslyn.

**Comment by bradwilson** [comment]
Unfortunately we don't support this runner (we provide it without support), as it has many known issues. The only supported mechanism for running test on .NET Core with xUnit v2.x is `dotnet test`.

**Comment by bradwilson** [comment]
BTW the version of Visual Studio used for the builds is whatever is current on AppVeyor.

**Comment by bradwilson** [comment]
Closing, as this code no longer exists.
