### ISSUE TITLE
Invalid "xUnit1000: Test classes must be public" on partial classes

### ISSUE THREAD

**Issue by tristanlabelle** [xunit/xunit#1844]
The `Xunit.Analyzers.TestClassMustBePublic` analyzer reports an error on this:

```
public partial class Test { }
partial class Test { [Fact] public static void Foo() { } }
```

The resulting `Test` class is clearly public, but xUnit apparently only checks the visibility of the current partial declaration, resulting in an incorrect error being reported.

**Comment by voroninp** [comment]
By the way, @bradwilson , is the requirement for test classes to be public externally enforced, or is it just the design choice of xUnit authors?

**Comment by bradwilson** [comment]
We chose to only support public classes because private reflection is (at least was) extremely slow: not just mechanically slow, but also because it would dramatically increase the number of types we'd have to search.

**Comment by voroninp** [comment]
And are there any plans to use source generators which will enumerate test classes/methods at the build phase?

**Comment by bradwilson** [comment]
No current plans.

**Comment by bjornhellander** [comment]
Unable to reproduce this. Looks like a duplicate of #1602, which has already been fixed.

**Comment by bradwilson** [comment]
Agreed, this does appear to be a dup. Closing.
