### ISSUE TITLE
Feature: Runner option to treat assert failures as warnings

### ISSUE THREAD

**Issue by daveyostcom** [xunit/xunit#1845]
Sometimes when we run a test, we just want to be able to keep going after an assert failure to see what else is wrong. Perhaps we would like to get an overview of all failing asserts, so we can size the problem or look for patterns.

The runner could offer optional assert failure behaviors:
• abort
• break into the debugger
• print only

**Comment by bradwilson** [comment]
This is available in v3:

- On the console runner as [`-failWarns`](https://github.com/xunit/xunit/blob/cf9d8bb2a2dc83e8d34e7f17872d6c1b11ba9451/src/xunit.v3.runner.common/Parsers/CommandLineParserBase.cs#L55-L56)
- On the MSBuild runner as [`FailWarns="true"`](https://github.com/xunit/xunit/blob/cf9d8bb2a2dc83e8d34e7f17872d6c1b11ba9451/src/xunit.v3.runner.msbuild/xunit.cs#L62)
- Via configuration as [`failWarns`](https://xunit.net/docs/configuration-files#failWarns)

**Comment by daveyostcom** [comment]
Hurray!
