### ISSUE TITLE
xUnit API restriction

### ISSUE THREAD

**Issue by brianlagunas** [xunit/xunit#1847]
I just converted all the Prism tests from MS Test to xUnit and have run into an interesting exception when running a particular set of tests.

Message: System.IO.FileLoadException : API restriction: The assembly 'file:///C:\Users\blagunas\AppData\Local\Temp\b86e146e-0f40-4225-945a-36050bb8350b\b86e146e-0f40-4225-945a-36050bb8350b\assembly\dl3\08e39305\0031ca8f_706fd401\xunit.runner.utility.net452.dll' has already loaded from a different location. It cannot be loaded from a new location within the same appdomain.

A repro can be found on this branch:

https://github.com/PrismLibrary/Prism/tree/upgrade-tests

Open the PrismLibrary_Wpf.sln and run the tests from this branch. You will notice nearly every test in the Prism.Wpf.Tests.DirectoryModuleCatalogFixture fails with this exception.

**Comment by brianlagunas** [comment]
So it seems to work fine (tests pass) if I run the Prism.WPF.Tests group by itself. But, if I select the Run All option, the tests fail.

**Comment by bradwilson** [comment]
Is the failure limited to VSTest, or does it also fail with our command line runner (xunit.console.exe)?

**Comment by brianlagunas** [comment]
Honestly, I am not familiar with the console runner or how to use it, so I have not tested it.

**Comment by onovotny** [comment]
Is it always the same test that causes this?

**Comment by brianlagunas** [comment]
Yes, it's always the same tests.

**Comment by onovotny** [comment]
Is it possible to extract those tests into an isolated test project? Just trying to simplify things into the smallest/simplest possible repro?

**Comment by brianlagunas** [comment]
The thing is, the tests pass just fine when just a singe project is run. If all test projects are run, then it fails. So I think the context of being in multiple projects is important.

**Comment by onovotny** [comment]
Are there two test projects that trigger it? Just trying to narrow things down.

**Comment by brianlagunas** [comment]
I just commented out the failing tests for now. I am on a time crunch and will come back to this. Thanks.

**Comment by onovotny** [comment]
Okay. We can keep this open for tracking if you want. I’d love to find a minimal retro so we can at least understand what is going on.

**Comment by bradwilson** [comment]
Repro project has disappeared (sorry that we never got a fix for you ☹️), so closing.
