### ISSUE TITLE
Dispose / DisposeAsync not run when test run aborted or debugging stopped.

### ISSUE THREAD

**Issue by simonvane** [xunit/xunit#1848]
I have an IClassFixture<T> that creates a database then deletes it when the tests have run. I need to do that to avoid excessive costs in Azure.

The problem is that the Dispose or DisposeAsync code does not run if:
1. The test run is stopped before completion.
1. A test is being debugged then debugging is stopped before test completion.

I am running tests in Visual Studio 2017 (15.8.9) with xunit 2.4.1 and xunit.runner.visualstudio 2.4.1 nuget packages.

**Comment by bradwilson** [comment]
There's nothing we can do. The debugger kills the process without any possibility of running cleanup code.

**Comment by simonvane** [comment]
Thanks @bradwilson. That at least tells me I'm not doing anything wrong. I just need to find a way to handle it.

**Comment by bradwilson** [comment]
Honestly, the I'm pretty sure the only thing you're going to be able to do is to let the test run to completion rather than halting the debugger.

**Comment by simonvane** [comment]
Thank you @bradwilson.

**Comment by SimonCropp** [comment]
@bradwilson looks like this one can be closed?

**Comment by bradwilson** [comment]
Agreed.
