### ISSUE TITLE
Design of Assert.All is inconsistent, deceptive and prone to bugs

### ISSUE THREAD

**Issue by pkaminsky** [xunit/xunit#1853]
`IEnumerable`'s `.All` is a bool-returning function which takes as input a `Func<TSource, bool>` and checks the results of that against the collection until it receives at least one `false`.

`Xunit.Assert`'s `.All` takes in an `IEnumerable<T>` and an `Action<T>`. Since the action is not returning a value, what is it even doing in there? You have to go to github to find out. Turns out, nothing. If your supplied Action<T> doesn't contain an Assert statement or throw an exception, nothing is tested.

Consider this code, which compiles and passes the test because the boolean value is discarded:

>            var list = new int[] { 1, 2, 3, 4, 5 };
>            bool IsEqual(object input1, object input2) { return input1 == input2; }
>            Assert.All(list, f => IsEqual(f, 5));

Compare this to `Assert.Contains` which behaves more like the IEnumerable counterpart. This sets the false expectation that .All will also follow the pattern. This means the above example is more likely than it may seem if you are reading this comment defensively, looking at the `Action<T>` in the method signature wondering why any fool would think the return value would be acknowledged. But on the contrary, many users will simply intuitively expect the boolean return value to be _required_ since that's how All() is supposed to work.

I understand why Assert.All is the way it is--individual failures are preserved--but this feature isn't actually helpful, since all it does is save you a few keystrokes compared to just calling `Assert.True` in a `foreach` loop. Actually by my count, the way I would write it, it saves you exactly 1 keystroke. On the other hand the way it is implemented could be counterintuitive to some users compared to both Xunit's other collection methods and IEnumerable's extension methods, causing people to unwittingly write pass-through tests.

**Comment by bradwilson** [comment]
There's no reason to write Assert.All as you proposed, because using Assert.True and Linq is all you need:

```csharp
Assert.True(list.All(f => IsEqual(f, 5));
```

Assert.All is written the way it is because it offers a significantly more descriptive error message than the above code.
