### ISSUE TITLE
`dotnet test --blame` does not always find the right test to blame, TestCaseStart event missing

### ISSUE THREAD

**Issue by peterzeller** [xunit/xunit#1854]
I originally reported this at https://github.com/dotnet/cli/issues/10344 and https://github.com/Microsoft/vstest/issues/1841 but it seems to be a problem with xunit.

## Steps to reproduce

1. Write an xunit test method that produces a stackoverflow (For example as in this project: [blameprob.zip](https://github.com/dotnet/cli/files/2586390/blameprob.zip))
2. Run `dotnet test --blame`

## Expected  behavior

Actually I expected to get a stack trace as I get in other programming languages like Java or C.

But according to the documentation, I would at least expect something like:

```
The active Test Run was aborted because the host process exited unexpectedly while executing following test(s):
Tests.example B
```

## Actual behavior

Sometimes the failing test is not detected and in other cases it even blames a wrong test.

## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.500/

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.500 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Here is the analysis from @karanjitsingh at https://github.com/Microsoft/vstest/issues/1841

> @livarcocc, I debugged the issue you were getting, it seems the wrong result/no result is because of the XUnit adapter itself, the blame datacollector receives 4 events from the test adapter
> 
>     1. `TestCaseStart`
> 
>     2. `TestCaseEnd`
> 
>     3. `TestSessionStart`
> 
>     4. `TestSessionEnd`
> 
> 
> The blame detection logic works by tracing test case starts and test case ends. If vstest abruptly exists, the last test case with a `TestCaseStart` event and no `TestCaseEnd` event gets blamed for the crash.
> 
> ![image](https://user-images.githubusercontent.com/4632805/48648595-03e01f80-ea16-11e8-88b7-5c1e16377279.png)
> 
> From the debug, it seems the only `TestCaseStart` event that's received is for the `"Tests.example c"` test method. I believe you should log this issue at [xunit issues](https://github.com/xunit/xunit/issues)

**Comment by bradwilson** [comment]
`StackOverflowException` cannot be caught by user code, so there's no way we can "fix" this problem.

**Comment by peterzeller** [comment]
MsTest behaves correctly, so it can be done right.

You merely have to trigger the TestCaseStart event before running the test code, so that --blame can show the test case causing the crash.

To me this looks like a race condition in xunit.

**Comment by bradwilson** [comment]
It is a "race condition" because reporting in xUnit.net is asynchronous. If the process dies before messages are sent, then the process dies. This is done for performance reasons; turning off the asynchronous message delivery system would penalize all users for what is clearly an edge case for you.

**Comment by peterzeller** [comment]
I see. Maybe you can work with the vstest developers so that asynchronous reporting is disabled when running with the `--blame` option. 

Otherwise there is probably nothing that can be done here, so feel free to close the issue. 
If the CLR gets better error reporting (https://github.com/dotnet/coreclr/issues/20478) this won't be necessary anyways.
