### ISSUE TITLE
Set `maxThreads` via config file

### ISSUE THREAD

**Issue by RedX2501** [xunit/xunit#1856]
I have a problem similar to the one described here https://github.com/xunit/xunit/issues/864 : lots of threads, very slow throughput.

One of the fixes mentioned is to use `-maxthreads unlimited`. But according to this [comment](https://github.com/xunit/xunit/issues/1629#issuecomment-363234940) settings `maxParallelThreads` is not the same.

Is that still true for 2.x? Can I somehow set `maxthreads` from the config file? Can this value be set when using the xunit msbuild runner? It seems it only knows `MaxParallelThreads` which I assume to be the same parameter as the one in the config files.

**Comment by bradwilson** [comment]
It is the same. Specifying `"maxParallelThreads": -1` in the [config file](https://xunit.github.io/docs/configuring-with-json) is equivalent to `-maxthreads unlimited` on the command line.

The comment you linked to was pointing out the fact that a command line option overrides whatever is in the config file.
