### ISSUE TITLE
AppDomain.CurrentDomain in Xunit differs from Microsoft.VisualStudio.TestTools.UnitTesting

### ISSUE THREAD

**Issue by 1Jesper1** [xunit/xunit#1861]
When I run a test with AppDomain.CurrentDomain in XUnit, the currentDomain is the project assembly name. When I run test with AppDomain.CurrentDomain in Microsoft.VisualStudio.TestTools.UnitTesting, the CurrentDomain is "UnitTestAdapter: Running test".

Xunit runner visualstudio: Version 2.4.1
Visual Studio 2017: Version 15.9.3

**Comment by bradwilson** [comment]
...and? 😉

**Comment by bradwilson** [comment]
That has nothing to do with the difference of the way the app domains are named. This is a dup of #1852.

**Comment by 1Jesper1** [comment]
@bradwilson You are right, I will close this issue.
