### ISSUE TITLE
build.ps1 requires msbuild in environment path to build solution

### ISSUE THREAD

**Issue by nvborisenko** [xunit/xunit#1862]
It would be better to use some another approach to avoid adding `msbuild` into path env variables.

**Comment by nvborisenko** [comment]
Thanks for your tip. I am just starting to investigate this framework deeper, and I use `build.ps1` to create `nupkg` packages with specific version to further usage (testing). It's not super easy, but as is. Could you please suggest some another tip to build nuget packages with specific version? BTW the issue can be considered as closed. Thanks.

**Comment by bradwilson** [comment]
There's really no workaround today. We need access to MSBuild. I think you're probably doing the right thing to build your own custom packages. The easiest way to get MSBuild on the path is to use [the `vs2017.ps1` file](https://gist.github.com/bradwilson/0cf1818bc9dc6c203c68d44d2f96c102#file-vs2017-ps1) that I discuss in [my blog post on custom command prompts](http://bradwilson.io/blog/anatomy-of-a-prompt).
