### ISSUE TITLE
Global setup and cleanup

### ISSUE THREAD

**Issue by pawelpabich** [xunit/xunit#187]
Hi,

@bradwilson in this SO thread http://stackoverflow.com/questions/13829737/xunit-run-code-before-and-after-all-tests you mentioned that this might be supported in 2.0. Is that still a plan?

**Comment by Mpdreamz** [comment]
ICollectionFixture would be sufficient but it also forces everything in the same collection to be run sequentially (if I understand the documentation correctly).

Being able to setup and teardown a collection of tests while having the tests within a collection still running in parrallel seems impossible now.

**Comment by JaroslawWaliszko** [comment]
@Mpdreamz: it's the issue I've faced right now. Is there a way to overcome this?

**Comment by JaroslawWaliszko** [comment]
Here is the package which helps: https://github.com/kzu/xunit.assemblyfixture.

**Comment by helmerm** [comment]
any change on this one?

**Comment by bradwilson** [comment]
Still no plans for the mainline. Kzu's package does what you want.

**Comment by StrangeWill** [comment]
@bradwilson any plans on this? Kzu's package has been abandoned and there is no way to accomplish this on .NET Core.

**Comment by eltiare** [comment]
So are static constructors the only way to do this then?

**Comment by WhatFreshHellIsThis** [comment]
What is the modern guidance on this pressing issue?

**Comment by bradwilson** [comment]
@WhatFreshHellIsThis Same guidance as 2017: https://github.com/kzu/xunit.assemblyfixture

**Comment by WhatFreshHellIsThis** [comment]
@bradwilson According to what others posted here in this issue and checking it out again that is not suitable solution as it is a long abandoned project and doesn't support .net core.  Why not build this functionality in?  What am I missing here? It seems like an obvious must have, fundamental requirement for any non-trivial usage.

**Comment by eltiare** [comment]
It also seems like it would be fairly trivial to implement.
