### ISSUE TITLE
Theory type-chooser chooses wrong type in inheritence/generics combo

### ISSUE THREAD

**Issue by manofstick** [xunit/xunit#1870]
I've stripped down a real error bug to to the essentials (I believe):

    internal abstract class Low<T> : IEnumerable<T>
    {
        public abstract IEnumerator<T> GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
    }

    internal abstract class Mid<T, U> : Low<U> { }

    internal class Top<V, T> : Mid<V, T>
    {
        public override IEnumerator<T> GetEnumerator() { yield break; }
    }

    public class SomeTest
    {
        [Theory, MemberData(nameof(Data))]
        public void TestATheory<T>(IEnumerable<T> source) => Assert.True(source != null);

        public static IEnumerable<object[]> Data() => new[] { new[] { new Top<int, string>(), }};
    }

But xunit has the exception:

    System.ArgumentException : Object of type 'ClassLibrary1.Top`2[System.Int32,System.String]' cannot be converted to type 'System.Collections.Generic.IEnumerable`1[System.Int32]'.

because it has got the generic type parameters mixed up (i.e. it should be trying to convert to `IEnumerable<string>`)

**Comment by manofstick** [comment]
@bradwilson 

I had a little look around the code base (but debug info not displaying great for some reason which I don't really have time to investigate) and see that the problem is in `TypeUtility.cs`'s `ResolveGenericType`, but I don't fully grok the logic going on there.

Anyway, what I think is needed is adding somewhere along the lines something like:

        static Type ResolveGenericInterfaceArgumenetType(Type methodGenericInterfaceArgumentType, Type inputArgumentType) =>
            inputArgumentType
            .GetInterfaces()
            .FirstOrDefault(itf => itf.IsGenericType && itf.GetGenericTypeDefinition() == methodGenericInterfaceArgumentType);

        static void Main(string[] args)
        {
            var methodGenericInterfaceArgumentType = typeof(IEnumerable<>);
            var inputArgumenetType = typeof(Top<int, string>);

            var resolvedType = ResolveGenericInterfaceArgumenetType(methodGenericInterfaceArgumentType, inputArgumenetType);

            Console.WriteLine(resolvedType);
        }

But unless I spent a fair bit more time on it I don't think I can safely slot this in...

**Comment by manofstick** [comment]
This is the bug in the real world:

https://github.com/manofstick/corefx/blob/ChainLinqFence/src/System.Linq/tests/ReverseTests.cs#L52-L78

https://github.com/manofstick/corefx/blob/ChainLinqFence/src/System.Linq/src/System/Linq/ChainLinq/Chain.cs#L76

https://github.com/manofstick/corefx/blob/ChainLinqFence/src/System.Linq/src/System/Linq/ChainLinq/Consumables/Base.cs#L8

https://github.com/manofstick/corefx/blob/ChainLinqFence/src/System.Linq/src/System/Linq/ChainLinq/Consumables/Enumerable.cs#L5

**Comment by bradwilson** [comment]
Fixed in https://github.com/xunit/xunit/commit/4d1f2e5d4ac9260487d0a8f35a2d045388021b33
