### ISSUE TITLE
Runners which skip theory pre-enumeration by default should offer an override switch

### ISSUE THREAD

**Issue by ryanbrandenburg** [xunit/xunit#1871]
In AspNetCore we've created [ConditionalTheoryDiscoverer](https://github.com/aspnet/Extensions/blob/master/src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/ConditionalTheoryDiscoverer.cs) to allow us to skip specific TheoryData, and this has worked fine under vstest, but when we switched to building with xunit.console (and thus with PreEnumerateTheories=false) theory data that previously skipped no longer does.

I've created a pared down [repro project](https://github.com/ryanbrandenburg/PreenumerateXunit) to showcase this.
Repro steps:
1. Clone the above project.
1. `cd Microsoft.AspNetCore.Testing/test; dotnet restore`
1. `dotnet xunit`. See that a test which was expected to be skipped ran (and failed).
1. `dotnet test`. See that the appropriate test skipped.

We've found that this behavior can be avoided with [this workaround](https://github.com/ryanbrandenburg/PreenumerateXunit/blob/master/Microsoft.AspNetCore.Testing/src/xunit/ConditionalTheoryDiscoverer.cs#L17-L34) but it seems less than ideal to just override that setting in some scenarios.

Is our implementation of CreateTestCasesForDataRow just wrong, and if so is there an example of a successful implementation of this scenario?

**Comment by bradwilson** [comment]
That's true. The system was not designed to do this, as the level of skipping is at the Test Case level, and when theory pre-enumeration is turned off, there is a single Test Case for the theory (rather than one per data row).

Renaming this issue to reflect the actual needed feature.

**Comment by bradwilson** [comment]
I have tagged both Console and MSBuild runners, though it's likely that actual location of the behavior will change for 3.0.

**Comment by bradwilson** [comment]
In-proc console runner: 4d4964c7c0a3293d71c094763946171e8175213a
Stand-alone console runner: c98c54a984006495fefca971141ee94eef101a59
MSBuild runner: 5cf67b2989d9145154ca6f1daa625dc01a8d5915
