### ISSUE TITLE
Assert the sort order of a list

### ISSUE THREAD

**Issue by jasonycw** [xunit/xunit#1872]
https://github.com/xunit/xunit/blob/9d10262a3694bb099ddd783d735aba2a7aac759d/test/test.xunit.assert/Asserts/CollectionAssertsTests.cs#L661
https://github.com/xunit/xunit/blob/9d10262a3694bb099ddd783d735aba2a7aac759d/test/test.xunit.assert/Asserts/CollectionAssertsTests.cs#L704

From the above 2 test cases, it seems that `Assert.Equal` doesn't really care about the order of the list as long as all the items are there.

``` C#
        [Fact]
        public static void Api_Should_Return_Sorted_List()
        {
            var result = await SomeApi(sortByStartDate, Order.Desc);

            // Assert if the list is now sorted asc/desc
        }
```

Is there a way in XUnit where I can test if a list is sorted correctly?
e.g. 
``` C#
Assert.OrderAsc(listShouldBeSorted, x => x.StartDate)
Assert.OrderDesc(listShouldBeSorted, x => x.StartDate)
```

**Comment by jmoralesv** [comment]
I would like to have that kind of asserts with Xunit, as my code under testing is using Linq's OrderBy and OrderByDescending, and part of the unit test is about ensuring the order of the items in the result. I'm looking forward to seeing these in the future.

**Comment by stefannikolei** [comment]
@jmoralesv have a look at Fluent.Assertions 

there you can write it like this `object.Should().BeInAscendingOrder()`

**Comment by bradwilson** [comment]
> From the above 2 test cases, it seems that Assert.Equal doesn't really care about the order of the list as long as all the items are there.

Those tests are specifically related to `Dictionary<,>` and `HashSet<>`, which [_do not have a predictable order_](https://xunit.net/docs/hash-sets-vs-linear-containers). Your assumption that we don't care about order in general is incorrect, as illustrated here with linear containers:

![image](https://github.com/xunit/xunit/assets/16944/560c51eb-4d66-40c0-9487-2dcb5e068354)

We do not offer (and do not plan to offer) assertions that ensure items are in a specific order. You can do that today with `Assert.Equal` and compare your collection against one that's in the "correct" order as your code sees fit.
