### ISSUE TITLE
NuGet: cannot install package xunit.assert.source 2.4.1 due to incompatible references

### ISSUE THREAD

**Issue by katusk** [xunit/xunit#1875]
This is most probably a missing entry problem in the `.nuspec` file of the package: I am trying to install xunit.assert.source 2.4.1 both via the "Project > Manage NuGet Packages..." window in Visual Studio 2017 (Version 15.8.7), and via the Package Manager Console with NuGet Version: 4.9.2.5706 to no avail.

### Reproduction
In case of the latter, I get the following error, no matter what other xunit packages are already installed (I also tried installing from scratch, e.g. removing all xunit-related packages, and install the core package and then assert.source only):

```
PM> Install-Package xunit.assert.source -Version 2.4.1

Attempting to gather dependency information for package 'xunit.assert.source.2.4.1' with respect to project 'TestMyStuff', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 44.82 ms
Attempting to resolve dependencies for package 'xunit.assert.source.2.4.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'xunit.assert.source.2.4.1'
Resolved actions to install package 'xunit.assert.source.2.4.1'
Retrieving package 'xunit.assert.source 2.4.1' from 'nuget.org'.
Install failed. Rolling back...
Package 'xunit.assert.source.2.4.1' does not exist in project 'TestMyStuff'
Package 'xunit.assert.source.2.4.1' does not exist in folder 'C:\MyLittleProject\packages'
Executing nuget actions took 204.52 ms
Install-Package : Could not install package 'xunit.assert.source 2.4.1'. You are trying to install this package into a project that targets 
'.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that 
framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package xunit.assert.source -Version 2.4.1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:00.9680950
```

### Hints for fix
If you compare the `xunit.assert.2.4.1.nupkg\xunit.assert.nuspec` file with `xunit.assert.source.2.4.1.nupkg\xunit.assert.source.nuspec` you realize that latter does not have the following section:

```
    <dependencies>
      <group targetFramework=".NETFramework4.5.2" />
      <group targetFramework=".NETStandard1.1">
        <dependency id="NETStandard.Library" version="1.6.1" />
      </group>
    </dependencies>
```

This might be the source of the problem as things fail during package installation, not later e.g. during building of my project.

### Slightly related issues
These links were encountered by me whilst trying to get to the bottom of this problem, but eventually they turned out to be not that related, although somewhat similar problems in my estimation:
- GitHub Issue https://github.com/xunit/xunit/issues/1127
- GitHub Issue https://github.com/mj1856/GeoTimeZone/issues/27

### Need for xunit.assert.source
I would like to install xunit.assert.source because I want to add new custom assertions to the `Assert` class of xunit as mentioned here: https://github.com/xunit/xunit/issues/350#issuecomment-78211019 -- see:

> To support people writing better assertions, v2 includes a NuGet package that ships the assertion library in source code. The `Assert` class is a partial, so you can add whatever assertions you like to the built-in set. We've even gone so far as to publish gists with extra assertions, just to show people how it's done: https://gist.github.com/bradwilson/7797444

**Comment by katusk** [comment]
Hi @onovotny, thanks a lot! Indeed, after moving from `packages.config` to `PackageReference` xunit.assert.source got installed via the "Manage NuGet Packages..." window without any problems.

I am not sure why we are still using `packages.config` on the first place, I still need to investigate. Are you basically saying that installing via `packages.config` is not supported by the xunit.assert.source package? With the default xunit package I did not have any problems in relation with `packages.config`.

**Comment by bradwilson** [comment]
That's correct, it's not supported. The source package uses features of NuGet that are apparently not supported in packages.config. You don't see issues with the binary packages because those aren't using the same content feature.

**Comment by katusk** [comment]
OK, I think we can close this issue then. Things work fine with NuGet `PackageReference`. Thanks for the help.
