### ISSUE TITLE
How to display the output using ITestOutputHelper on VSTS?

### ISSUE THREAD

**Issue by ranouf** [xunit/xunit#1879]
Hi,

Packages used:
```
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
```

Code:
```
ITestOutputHelper output
output.WriteLine("Test");
```

On VS I am able to see the output:
![image](https://user-images.githubusercontent.com/1764519/50922657-09a42100-1419-11e9-9a0d-99733a3ca9a5.png)

Here is the build definition:
![image](https://user-images.githubusercontent.com/1764519/50923150-3f95d500-141a-11e9-9e32-1e228ec7ce36.png)

When I run the Test in VSTS, I m supposed to see the output in the attchment section, but it s empty.
![image](https://user-images.githubusercontent.com/1764519/50922853-78817a00-1419-11e9-9261-b3a77e9ee414.png)

How to configure the XUnit Project to get the output in VSTS?

Thanks

**Comment by bradwilson** [comment]
We don't officially support VSTS. This question is better directed at the VSTS team ("where does unit test output go?") since we have no control over their UI.

**Comment by ranouf** [comment]
For people interested by the answer, I created an issue here: https://developercommunity.visualstudio.com/content/problem/424353/how-to-display-the-output-using-itestoutputhelper.html
