### ISSUE TITLE
`InlineMember` data attribute for data theories.

### ISSUE THREAD

**Issue by achobanov** [xunit/xunit#1881]
I would love to have the functionality to pass in named fields in `InlineDataAttribute`.  For example my use case is feeding a test method with ~20 different `string` content examples, containing various errors. Having all these literals in `InlineData` is very unreadable, since the errors in question can be somewhat obfuscated. Instead I have created a static class with constants, containing named properties, e.g. InvalidForSpecificReason`. 

I took a look at your own implementations of inline and member attributes and created a prototype for `InlineMember`, accepting a method name and optional type parameter. I got it to work as intended, but unfortunately it's not being detected by the tests explorer. 

Can I get that to work somehow? Also, would you guys consider potential contribution about it?

**Comment by bradwilson** [comment]
How would this be different from the existing `MemberData`?

**Comment by achobanov** [comment]
From what I gather, `MemberData` expects a `IEnumerable` of `object[]`. I can technically create my named members in separate class, as I did, and expose a list of those items, but ideally I would like to remove that list entirely and simply use it as `InlineData` - put 20 attributes above my method. However having those attributes containing a named property would improve on readability. For example:
```
[InlineMemberData(nameof(InvalidClosingTag)]
```
looks better than:
```
[InlineData("[tag]content[/tag")] // note ']' missing in the closing tag
```

Similarly, several attributes are more readable, then a generic collection name:
```
[MemberData(nameof(InvalidContentCollection)]
```

The example is simple, but imagine a content string containing tag that looks like this `[tag]content[/tag]`. However the `a` could be a Bulgarian `а`, as opposed to English `a`. The test input would look valid, but would actually be invalid. A property named `InvalidWithNonEnglishSymbolInOpeningTag` would be far better.

**Comment by achobanov** [comment]
@bradwilson, never mind the issue with the test explorer. Works after successful compilation and restart of VS. I know this attribute is not a big deal, since it's closely based on your own implementation, but I'd be happy to partake - it would be a first timer :). Nice response time, though.

**Comment by bradwilson** [comment]
I'll ponder it, but fair warning that I'm leaning towards no right now (too many ways to do the same thing, and once you've paid the cost of initializing a property/method/field for data, it seems wasteful to only have it be able to return a single record).

**Comment by achobanov** [comment]
Fair enough, I didn't notice any performance impact in my own case, but I guess it could be relevant if testing with abnormal amount of inputs.

**Comment by bradwilson** [comment]
It's not about performance, it's about the amount of "ceremony" involved in declaring separate methods/properties just for a single data item.
