### ISSUE TITLE
Add support for Circle CI test format

### ISSUE THREAD

**Issue by omerlh** [xunit/xunit#1882]
Circle CI has support for parsing [test results](https://circleci.com/docs/2.0/collect-test-data/). The test result should be reported as XML in nunit format. Is this is something that xunit can support? I saw old post suggesting using `dotnet test -xml` but this is not working anymore...

**Comment by bradwilson** [comment]
Unfortunately, we do not control the output of `dotnet test`. You have to do that with a VSTest plugin. You should request this feature from the VSTest team. https://github.com/Microsoft/vstest
