### ISSUE TITLE
Case-sensitive enum parsing

### ISSUE THREAD

**Issue by matkoch** [xunit/xunit#1884]
Any reason why this should work case-sensitive?

https://github.com/xunit/xunit/blob/d321bb572abf9027e3762848068b3e9eea2458f2/src/xunit.console/CommandLine.cs#L274

**Comment by bradwilson** [comment]
The answer is that everything there right now, including switch names, is case sensitive. I'm okay with fixing this for case insensitivity, but the change should encompass switch names in addition to switch values.

**Comment by matkoch** [comment]
I didn't try it on console, but this looks like it's case-insensitive:

https://github.com/xunit/xunit/blob/d321bb572abf9027e3762848068b3e9eea2458f2/src/xunit.console/CommandLine.cs#L147

**Comment by matkoch** [comment]
Okay, seems this is done somewhere earlier...
