### ISSUE TITLE
AsyncLocal values don't flow from InitializeAsync to tests

### ISSUE THREAD

**Issue by tmenier** [xunit/xunit#1885]
Repro:

```c#
public class AsyncLocalTests : IAsyncLifetime
{
    static AsyncLocal<string> _asyncLocal1 = new AsyncLocal<string>();
    static AsyncLocal<string> _asyncLocal2 = new AsyncLocal<string>();

    public AsyncLocalTests() {
        _asyncLocal1.Value = "foo";
    }

    public async Task InitializeAsync() {
        _asyncLocal2.Value = "foo";
    }

    [Fact] // passes
    public void WorksWithSyncSetup() {
        Assert.Equal("foo", _asyncLocal1.Value);
    }

    [Fact] // fails
    public void WorksWithAsyncSetup() {
        Assert.Equal("foo", _asyncLocal2.Value);
    }

    public Task DisposeAsync() {
        return Task.CompletedTask;
    }
}
```

As noted, `WorksWithSyncSetup` passes consistently; `WorksWithAsyncSetup` fails consistently.

FWIW, this was discovered via a [bug](https://github.com/tmenier/Flurl/issues/375) reported in Flurl by someone using MSTest, and I have confirmed the same issue exists in NUnit. In all cases, the behavior appears to be specific to the _async_ setup mechanism in each library. In all cases, when used in the synchronous setup mechanism, it seems to work fine consistently, even when the test itself and the SUT that it calls into really "challenge" it with lot of async/concurrent/parallel calls. So not to pick on xUnit but I thought I'd start here since it seems to be the most popular and active of the group. :)

**Comment by trullock** [comment]
Just encountered this same bug via different means (probably the same cause)
Will post repo code shortly

**Comment by trullock** [comment]
`	public class Foo : IClassFixture<Bar>
	{
		readonly Bar bar;

		public Foo(Bar bar)
		{
			this.bar = bar;
		}

		[Fact]
		public void XUnitIsBugged()
		{
			bar.Booly.Value.Should().BeTrue();
		}
	}

	public class Bar
	{
		public AsyncLocal<bool> Booly;

		public Bar()
		{
			this.Booly = new AsyncLocal<bool>();
			this.Booly.Value = true;
		}
	}`

This test fails, becuase `Booly` is false, I'd expect this to be true?

**Comment by SimonCropp** [comment]
@tmenier u can work around this by putting your own contextual class in the asynclocal. then instead of setting a new value, read the asynclocal context, and set a property on that instance.

```
using System.Threading;
using System.Threading.Tasks;
using Xunit;

public class AsyncLocalTests : IAsyncLifetime
{
    static AsyncLocal<MyContext> _asyncLocal = new AsyncLocal<MyContext>();

    public AsyncLocalTests()
    {
        _asyncLocal.Value = new MyContext {Member1 = "foo"};
    }

    public async Task InitializeAsync()
    {
        _asyncLocal.Value.Member2 = "bar";
    }

    [Fact]
    public void WorksWithSyncSetup()
    {
        Assert.Equal("foo", _asyncLocal.Value.Member1);
    }

    [Fact]
    public void WorksWithAsyncSetup()
    {
        Assert.Equal("bar", _asyncLocal.Value.Member2);
    }

    public Task DisposeAsync()
    {
        return Task.CompletedTask;
    }
}

class MyContext
{
    public string Member1 { get; set; }
    public string Member2 { get; set; }
}
```

**Comment by SimonCropp** [comment]
@bradwilson 

> , I'm tempted to say this probably can't be fixed.

that is my understanding as well
