### ISSUE TITLE
Build error in xunit/samples.xunit / WpfTestCase

### ISSUE THREAD

**Issue by jho1965us** [xunit/xunit#1890]
Downloaded latest xunit/samples.xunit
Build from

------ Build started: Project: STAExamples, Configuration: Debug Any CPU ------
WpfTestCase.cs(18,61,18,75): error CS0535: 'WpfTestCase' does not implement interface member 'IXunitTestCase.InitializationException'
WpfTestCase.cs(18,61,18,75): error CS0535: 'WpfTestCase' does not implement interface member 'IXunitTestCase.Timeout'
Done building project "STAExamples.csproj" -- FAILED.

------ Build started: Project: PartialTrustExample, Configuration: Debug Any CPU ------
XunitExtensions\PartialTrustTestCase.cs(11,13,11,76): warning CS0618: 'XunitTestCase.XunitTestCase(IMessageSink, TestMethodDisplay, ITestMethod, object[])' is obsolete: 'Please call the constructor which takes TestMethodDisplayOptions'
XunitExtensions\PartialTrustTestCase.cs(8,18,8,38): error xUnit3001: Class PartialTrustTestCase must have a public parameterless constructor to support Xunit.Abstractions.IXunitSerializable
Done building project "PartialTrustExample.csproj" -- FAILED.

**Comment by jho1965us** [comment]
Closed by mistake

**Comment by bradwilson** [comment]
Fixed in https://github.com/xunit/samples.xunit/commit/413e29ab744a354bc26aee2b8748b16d3ef969e6
