### ISSUE TITLE
AsyncLocal lost in async call

### ISSUE THREAD

**Issue by mabead** [xunit/xunit#1891]
https://github.com/xunit/xunit/issues/1880 and https://github.com/xunit/xunit/issues/1885 both flag issues with AsyncLocal but they are not the most trivial use case. Here's a really trivial one that does not use any TestClass member variable, shared context, async initializers or any other fancy stuff.

```csharp
    public class Demo
    {
        static class Foo
        {
            public static AsyncLocal<int> Bar = new AsyncLocal<int>();
        }

        private async Task ChangeFooBarTo123Async()
        {
            await Task.Delay(1);
            Foo.Bar.Value = 123;
        }

        [Fact]
        public async Task ShowBug()
        {
            Foo.Bar.Value = 456;
            await ChangeFooBarTo123Async();
            Assert.Equal(123, Foo.Bar.Value);
        }
    }
```

This test fails with
```
Message: Assert.Equal() Failure
Expected: 123
Actual:   456
```

I am using XUnit 2.4.1.0 under netcoreapp2.1.

**Comment by bradwilson** [comment]
I converted that into a program to remove xUnit.net from the equation.

`Repro.csproj`

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>Latest</LangVersion>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

</Project>
```

`Program.cs`

```csharp
using System;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    static async Task Main(string[] args)
    {
        await new Demo().ShowBug();
    }
}

public class Demo
{
    static class Foo
    {
        public static AsyncLocal<int> Bar = new AsyncLocal<int>();
    }

    private async Task ChangeFooBarTo123Async()
    {
        await Task.Delay(1);
        Foo.Bar.Value = 123;
    }

    public async Task ShowBug()
    {
        Foo.Bar.Value = 456;
        await ChangeFooBarTo123Async();
        Console.WriteLine(Foo.Bar.Value);
    }
}
```

And it printed 456, not 123.

Therefore I don't believe that (a) this has anything to do with xUnit.net, nor (b) is this likely to actually be a bug, but rather a misunderstanding of how/when the copy-on-read semantics get applied to `AsyncLocal<T>` values.

**Comment by Mauzer93** [comment]
@bradwilson  This is indeed correct. AsyncLocal should flow to asynchronous calls, but changes made in those asynchronous calls never flow back to the caller. This is expected behavior.

**Comment by trullock** [comment]
@Mauzer93 Can you elaborate a bit more? Conscious to learn how my understanding of why i think #1885 is a bug is wrong.

What does "never flow back to the caller" mean?

That changes to AsyncLocal within an async (2nd) thread will not be reflected back in the main thread by design? Do you have a link to the spec for this?

**Comment by mabead** [comment]
Wow, I didn't know about this behavior. Thank you guys for enlightening me!

FYI: here's a [little information](https://stackoverflow.com/questions/42959056/whats-the-effect-of-asynclocalt-in-non-async-await-code/42959816#42959816) that may help.
