### ISSUE TITLE
Xunit Cannot run test for UWP

### ISSUE THREAD

**Issue by gordonsnc** [xunit/xunit#1892]
Hi,
I have Xunit installed for my UWP project, followed the Xunit instruction to create and run, I can see there are few tests in Test Explore, however, none of them can run.
the Discovery is OK for find the test, the the run said No test is available
the error message is 
 Catastrophic failure: System.TypeLoadException: Could not load type 'System.Runtime.Remoting.Channels.IChannel' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Xunit.RemotingUtility.CleanUpRegisteredChannels()
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.RunTests(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, Func`1 testCaseAccessor)
 xUnit.net VSTest Adapter v2.4.1 (64-bit Universal Windows)
 No test is available in 

My Visual Studio is 15.8.1, UWP Test project is target to 16299. 
I googled a few options like 
delete the %temp/VisualStudioTestExplorerExtensions
delete the /bin /obj
but none of them working.
has anyone have same problem and fixed?

Regards,
Gordon

**Comment by bradwilson** [comment]
Please provide a repro project. /cc @onovotny
