### ISSUE TITLE
xUnit not always catching async exception

### ISSUE THREAD

**Issue by mysteryx93** [xunit/xunit#1895]
I created a xUnit test that calls a method twice to ensure the 2nd call throws an exception saying the class instance is busy. Pretty straightforward.

    [Fact]
    public async Task RunTwice() {
        var P = Create();
        Task T1 = Task.Run(() => P.Run("test", null));
        Task T2 = Task.Run(() => P.Run("test", null));
        await Assert.ThrowsAsync<InvalidOperationException>(() => Task.WhenAll(new Task[] { T1, T2 }));
    }

Problem is, this test will randomly either succeed or fail!

The Run method starts like this

    public IProcess WorkProcess;
    private readonly object lockToken = new object();

    public virtual CompletionStatus Run(string fileName, string arguments) {
        IProcess P;
        lock (lockToken) {
            if (WorkProcess != null)
                throw new InvalidOperationException();
            P = factory.Create();
            WorkProcess = P;
        }
    ...

Is this a buy in xUnit or am I doing something wrong? I know async support was added in xUnit 1.9. I'm using v2.4.1.

When I look at debug information, when the test fails, the exception is still thrown, so this definitely looks like a bug in xUnit.

If I run this unit test alone, it generally works, but when running all tests, then it sometimes fail.

**Comment by TimCorwin** [comment]
I am seeing the exact same symptoms with a test that matches that syntax.

I've tried a few other things without effect:
- downgrading to xUnit 2.4.0 and 2.3.1
- changing the anonymous method to `( async () => await sut.method())` 
- rendering it synchronous with asyncMethod().Wait() and feeding to vanilla Assert.Throws<>()
- public async void VS public async Task on the test method

What other troubleshooting steps can I take?

**Comment by bradwilson** [comment]
I tried to simplify it to this:

```csharp
using System;
using System.Threading.Tasks;
using Xunit;

public class xunit_1895
{
    public static volatile bool initialized = false;
    private static readonly object lockToken = new object();

    [Fact]
    public async void Test1()
    {
        var t1 = Task.Run(() => Run());
        var t2 = Task.Run(() => Run());

        await Assert.ThrowsAsync<DivideByZeroException>(() => Task.WhenAll(t1, t2));
    }

    private void Run()
    {
        lock (lockToken)
        {
            if (initialized)
                throw new DivideByZeroException();

            initialized = true;
        }
    }
}
```

And I am unable to get it to ever fail. I feel like something in your repro is causing a race condition that is not obvious from the snippet you've provided. Please provide a full repro project.

**Comment by mysteryx93** [comment]
I'll note that when running this test alone, it succeeds, but it sometimes fails only when running a whole series of tests.

**Comment by mysteryx93** [comment]
Ah. After double-checking, when the test fails, the exception does NOT get thrown. When running several tests at once, the tasks queue is busy and thus the 2nd Run doesn't get called right away, and thus there is no race. When running that test alone, then there is a race. It is thus not xUnit's fault.
