### ISSUE TITLE
MemberData analyser confused by C# 8 preview non-nullable references

### ISSUE THREAD

**Issue by CornedBee** [xunit/xunit#1897]
```
        public static readonly object[][] NestedTypes =
        {
            new object[] { new Obj() },
            new object[] { new List() },
            new object[] { new DictionaryByKey() },
            new object[] { new DictionaryByValue() },
            new object[] { new Optional() },
        };
        [Theory, MemberData(nameof(NestedTypes))]
        public void CheckFixesTypePlaceholder(INestedType type)
        { /* ... */ }
```

With C# 8 nullable reference types enabled, this code produces an xUnit1019 error:

> MemberData must reference a data type assignable to 'System.Collections.Generic.IEnumerable<object[]>'. The referenced type 'object[][]' is not valid.

This may be a bug in the underlying system, but I cannot tell.

**Comment by bradwilson** [comment]
I think you'd be better off opening this bug against the C# team to see whether they think it's legit or not. We don't officially support pre-release compilers, so unless we know that this is a legitimate issue (and how to fix it), we're unlikely to look at this before C# 8 ships.

**Comment by CornedBee** [comment]
Fair enough.

**Comment by michaelvolz** [comment]
Using `Visual Studio 16.3.0. Preview 1.0` you can fix it with:
```
#nullable disable
        public static readonly object[][] NestedTypes =
        {
            new object[] { new Obj() },
            new object[] { new List() },
            new object[] { new DictionaryByKey() },
            new object[] { new DictionaryByValue() },
            new object[] { new Optional() },
        };
#nullable enable

        [Theory, MemberData(nameof(NestedTypes))]
        public void CheckFixesTypePlaceholder(INestedType type)
        { /* ... */ }
```

**Comment by SuricateCan** [comment]
I do think this is an issue for xUnit. The types are clearly the same. In my case, the types were not even nullable. However I think it is fair to wait for the full release of C# 8.0 to take any actions.

By the way, @michaelvolz suggestion did the work around for me.

Thanks.

**Comment by upsilon** [comment]
You can also fix it with `TheoryData<T>`:

```csharp
public static readonly TheoryData<INestedType> NestedTypes = new TheoryData<INestedType>
{
    { new Obj() },
    { new List() },
    { new DictionaryByKey() },
    { new DictionaryByValue() },
    { new Optional() },
};

[Theory, MemberData(nameof(NestedTypes))]
public void CheckFixesTypePlaceholder(INestedType type)
{ /* ... */ }
```

**Comment by moh-hassan** [comment]
in vs2019 Version 16.4.2, for the MemberData: 
```cs
new object[] {"abcd", typeof (float), true, null},
```
The compiler fire the warning:
>Warning	CS8625	Cannot convert null literal to non-nullable reference type.

This can be resolved using the forgiving Operator !  with null as:   
```cs   
  //  use ! with null  ===> null!
    new object[] {"abcd", typeof (float), true, null!},
```

The solution using forgiving operator is adv iced to be use by [EntityFramework  Team](https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types)
>it is possible to simply initialize the property to null with the help of the null-forgiving operator (!):

**Comment by bradwilson** [comment]
For v3, we have updated the allowed signature for data providers to be `IEnumerable<object?>`, so with v3 you could change the signature from `new object[]` to `new object?[]` and the compiler should be okay with it.

I'm going to leave this open until I can verify that the analyzers properly support nullability here.

**Comment by bradwilson** [comment]
I am unable to repro this with `xunit.analyzers` version `1.4.0` so I presume that it has been resolved by us moving to a newer version of Roslyn that fully supported nullability.

Please open a new issue with a repro project if you're still experiencing this error.
