### ISSUE TITLE
How to pass external test parameters to xUnit fixture

### ISSUE THREAD

**Issue by amigup** [xunit/xunit#1908]
I'm writing xUnit unit test cases for a dotnet core application which uses DocumentDB (CosmosDB) as storage. The unit test are written to execute against the local cosmos db emulator. On the Azure DevOps build environment, I've setup the [Azure Cosmos DB CI/CD ](https://docs.microsoft.com/en-us/azure/cosmos-db/tutorial-setup-ci-cd) task which internally creates a container to install the emulator. However, I'm not able to figure out that how the endpoint of emulator can be passed to xUnit fixture?

Is there any way through which xUnit fixture can read the .runsettings test parameters or parameters can be passed via other source?

**Comment by GeorgDangl** [comment]
You could use environment variables:

    System.Environment.GetEnvironmentVariable("AZURE_COSMOS_DB_CONNECTION_STRING")

**Comment by amigup** [comment]
@GeorgDangl  - Thanks. I did implemented it the same way but was not happy to define the connection string as a environment variable using powershell in build task and read it in through code during unit test execution. I was thinking if there could be more sophisticated way of achieving it.

Below snapshot shows how the build tasks are configured currently as workaround to achieve the desired
![image](https://user-images.githubusercontent.com/16287600/53783347-31a29300-3f37-11e9-9c40-10496025da7a.png)

And code to read the value as 
`var serviceEndpoint = Environment.GetEnvironmentVariable("CosmosDbEmulatorEndpointEnvironmentVariable");`

Since, UnitTest task provides the option to pass .runsettings/.testsettings with option to override the test run parameters so was thinking it something can be achieved using those options.

**Comment by bradwilson** [comment]
There is no support for this today. You can use external data sources (files, environment variables, etc.) but nothing is built in to do this for you.

**Comment by amigup** [comment]
Thanks @bradwilson. I've already configured the pipeline with the mentioned workaround. So closing this thread.

**Comment by ColinM9991** [comment]
I think this should be considered for implementation as using a config file or an environment variable just isn't suitable in certain scenarios.

I have often worked on teams which use NUnit & the NUnit Console Runner to create a portable smoke test suite which we can deploy alongside an application in a deployment pipeline to confirm that the application is functioning correctly, sometimes we need to pass credentials which we can't pass via config or environment variables because it would mean either having plain text credentials on the server in a file or variable - encryption means we'd have to pass an encryption key via config or variable also.

While NUnit works fine for passing in parameters, on the other hand xUnit has better support for Microsoft's `TestServer` and `WebApplicationFactory<T>` classes when implementing integration tests which keeps your tests lean & clean, but we simply can't be consistent in our test frameworks because of these limitations with the console runner.

**Comment by ShayanZafar** [comment]
I agree, it is so much more painful to upgrade from MSTest without having some support to the .runsettings extension or a viable workaround that doesn't involve an additional task in the build. please implement this.

**Comment by realbart** [comment]
This is one of the places I encountered while searching for this answer, so it's only fair I share my workaround here.

At this moment, there is no way to pass parameters to any .net test project. You could use the mstest testsettings/runsettings file, but that requires creating seperate files. In my case, I needed a servername and a password for my Selenium Coded UI tests, and I did not want to store them.

One of the recommended ways of passing parameters, is through environment variables. So in your C# xunit file, you can do something like:

    // in mytest.cs
    var user = Environment.GetEnvironmentVariable("TestUser");
    var password = Environment.GetEnvironmentVariable("TestPassword");
    var url = Environment.GetEnvironmentVariable("TestUrl");

If you do not want to definitively set your environment variables, remember you can always set them temporarily for just your session process. One way of doing this, is by creating a simple cmd file

    #launchtests.cmd
    SETLOCAL
    SET TestUser='pete001'
    SET TestPassword='secret'
    SET TestUrl='http://testserver.local/login'
    DOTNET TEST mytest.csproj

And now the fun part. You can parameterize every aspect of this. So you can change it to:

    #run wity launchtests.cmd pete001 secret 'http://testserver.local/login'
    SETLOCAL
    SET %1
    SET %2
    SET %3
    DOTNET TEST mytest.csproj

Or if you want to launch the test from an Azure DevOps (fka VSTS or TFS) pipeline, you can simply use the $(...) notation to inline variables, even if they're marked secret and/or come from Azure KeyVault.

    #In AzureDevops, variables not marked as secret are already added to the environment
    SET TestPassword=$(TestPassword)
    dotnet test $(Build.SourcesDirectory)\MyCompany.MyProduct.UITests\MyTest.csproj --configuration $(BuildConfiguration) --collect "Code Coverage" --logger trx --results-directory $(Agent.TempDirectory)

[![run Azure DevOps command task][1]][1]


  [1]: https://i.stack.imgur.com/Z63xh.png
