### ISSUE TITLE
XUnit MemberData is executed before Contructor

### ISSUE THREAD

**Issue by ad1969** [xunit/xunit#1912]
My test uses MemberData which calls a method that relies on data generated in the fixture. Unfortunately, that way I see it, when I debug a test the methods defined in the MemberData are executed first, then the constructor and then the tests, which, in my case, renders the fixture useless since I need the data it produces to populate the MemberData methods.

Is there a way to use a fixture that will generate test data in the database, return the created data and use it in the MemberData methods for the tests?

**Comment by bradwilson** [comment]
Unfortunately, no. Data collection happens long before any of your test code is executed.

**Comment by ad1969** [comment]
Thank you for confirming.
