### ISSUE TITLE
Live unit testing and skipping theory with classdata

### ISSUE THREAD

**Issue by Im5tu** [xunit/xunit#1913]
If you have a test similar to the following:

```c#
[Theory]
[ClassData(typeof(MyData))]
public void Test(Instance one, Instance two)
{
}
```

Everything works as expected. However, if you use a modified version of the attribute [shown here](https://docs.microsoft.com/en-us/visualstudio/test/live-unit-testing-faq?view=vs-2017) then all testing seems to break with the following exception message:

> Error Message:
 System.InvalidOperationException : The test method expected 2 parameter values, but 0 parameter values were provided.

Here is the modified attribute:

```c#
[ExcludeFromCodeCoverage]
public class SkipLiveTheoryAttribute : TheoryAttribute
{
    private static bool s_lutRuntimeLoaded = AppDomain.CurrentDomain.GetAssemblies().Any(a => a.GetName().Name == "Microsoft.CodeAnalysis.LiveUnitTesting.Runtime");
    public override string Skip => s_lutRuntimeLoaded ? "Test excluded from Live Unit Testing" : "";
}
```

The attribute works as expected for live unit testing, but calling `dotnet test` fails with the error message above.

XUnit Version: 2.4.1
MSFT Testing Version: 16.0.1
.Net Core Version: 2.2
Visual Studio Version: 16.0.0 Preview 4.1 SVC1

**Comment by bradwilson** [comment]
Implementing dynamic skipping is more complicated than that. Check out our sample: https://github.com/xunit/samples.xunit/tree/master/DynamicSkipExample

**Comment by bradwilson** [comment]
Also, we have new `Assert.Skip`/`Assert.SkipWhen`/`Assert.SkipUnless` that can be used to accomplish this as well.

**Comment by jzabroski** [comment]
@bradwilson That's awesome!
