### ISSUE TITLE
[Bug] Failed in Run, But Passed in Debug (No problem in MSTest or NUnit)

### ISSUE THREAD

**Issue by MrkTheCoder** [xunit/xunit#1918]
Hi
- **UnitTest Class**
My full repo: https://github.com/mrkangany/FriendStorageTests.git

```
public class FriendEditViewModelTests
{
    private const int FriendId = 5;
    private readonly FriendEditViewModel _friendEditViewModelMoq;

    public FriendEditViewModelTests()
    {
        var friendDataProviderMoq = new Mock<IFriendDataProvider>();
        friendDataProviderMoq.Setup(dp => dp.GetFriendById(FriendId))
            .Returns(new Friend { Id = FriendId, FirstName = "Thomas" });

        _friendEditViewModelMoq = new FriendEditViewModel(friendDataProviderMoq.Object);
    }

    [Fact]
    public void ShouldRaiseCanExecuteChangedWhenFriendIsChanged()
    {
        _friendEditViewModelMoq.Load(FriendId);
        var fired = false;
        _friendEditViewModelMoq.SaveCommand.CanExecuteChanged += (sender, args) => fired = true;

        _friendEditViewModelMoq.Friend.FirstName = "Changed";

        Assert.True(fired);
    }

    [Fact]
    public void ShouldRaiseCanExecuteChangedAfterFriendLoaded()
    {
        var fired = false;
        _friendEditViewModelMoq.SaveCommand.CanExecuteChanged += (sender, args) => fired = true;
        _friendEditViewModelMoq.Load(FriendId);

        Assert.True(fired);
    }
}
```

- **My Problem**
if I **Run All Tests** or **Run Selected Test** in both Resharper or MS Test Explorer, Both tests will failed. But If I **Run in Debug** mode (_no need to put any break point anywhere_) both tests will pass!

- **What I did until now**
I install NUnit + MSTest on same unit test project and put their annotations over both above methods + class, and in both **Run** or **Debug** mode, all tests passed!!!!!?

- **Software Specifications**
Windows 10 Enterprise v1607 build14393.0
VS 2017 Update 15.9.9
Resharper 2018.3.3
All packages are updated

I hope someone can tell me that is it a bug within xUnit or it is my fault!? (_while all tests passed in both NUnit and MSTest, Still I like to use xUnit_)

Thanks in advanced
MRK

**Comment by bradwilson** [comment]
Unit testing code which uses UI APIs will often fail because the test is not running on a UI thread.

Try using @AArnott's `[WpfFact]` on those tests (instead of `[Fact]`).

**Comment by AArnott** [comment]
That's available via the [Xunit.StaFact](https://www.nuget.org/packages/xunit.stafact) unit package.

You can use `[UIFact]` instead if your code needs a general concept of a UI thread but doesn't need/want to be WPF-specific.

**Comment by MrkTheCoder** [comment]
@bradwilson  & @AArnott  
Thanks for Advises & info, both of your suggestions fix the problem.
Good luck

**Comment by bradwilson** [comment]
There are limitations that come with it, which is why it isn't the default behavior.
