### ISSUE TITLE
Build from root on Mac has errors

### ISSUE THREAD

**Issue by hughbe** [xunit/xunit#1925]
```sh
git clone https://github.com/xunit/xunit
cd xunit
dotnet build
```
```
/Users/hugh/Documents/GitHub/expo-example/xunit/test/test.harness.uwp/test.harness.uwp.csproj(185,3): error MSB4019: The imported project "/usr/local/share/dotnet/sdk/2.1.200/Microsoft/WindowsXaml/v15.0/Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

Build FAILED.

/Users/hugh/Documents/GitHub/expo-example/xunit/test/test.harness.uwp/test.harness.uwp.csproj(185,3): error MSB4019: The imported project "/usr/local/share/dotnet/sdk/2.1.200/Microsoft/WindowsXaml/v15.0/Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
    0 Warning(s)
    1 Error(s)
```

**Comment by bradwilson** [comment]
This is not supported on the (current) `master` branch.

You may find the `linux` branch (which will be merged to master eventually) builds and runs on macOS, but I have not tested it. In addition to a .NET Core 2.1+ compatible SDK, you will need a version of Mono installed (and on the path) which supports .NET 4.7.2 and .NET Standard 2.0.

This is a "Build from Linux" feature (#1733) scheduled for 3.0, but it does not explicitly call out building from macOS as being a supported platform.

**Comment by bradwilson** [comment]
This is now working as expected with v3. Please re-open (or open a new issue) if you are unable to build from the `main` branch with a Mac.

**Comment by hughbe** [comment]
Hero thanks
