### ISSUE TITLE
Used to be able to setup Theory in base class

### ISSUE THREAD

**Issue by mwpowellhtx** [xunit/xunit#1927]
Hello,

I used to be able to setup ``TheoryAttribute`` in a base class, and furnish data in a derived class.

However, I seem to have encountered a hard error, ``xUnit1003`` around this very issue.

Is there a way to disable these checks at least temporarily in a given module?

Thanks!

**Comment by mwpowellhtx** [comment]
Never mind, I recalled how to do it:

```C#
#pragma warning disable xUnit1003 // Theory methods must have test data
[Theory]
public virtual void MyBaseTheory(int one, string two, bool three) { /*...*/ }
#pragma warning restore xUnit1003 // Theory methods must have test data
```

Then override in the derived class and decorate with whatever inline, member, class, etc, data.

**Comment by mwpowellhtx** [comment]
Oh, and incidentally, there is also the warning on the derived class side that can be disabled.

```C#
#pragma warning disable xUnit1008 // Test data attribute should only be used on a theory
// ...
#pragma warning restore xUnit1008 // Test data attribute should only be used on a theory
```

Although tooling support for these is inconsistent at the moment, i.e. *ReSharper*.

But, honestly, I think this is a case that *xUnit* should be supporting out of the box. Read, not something that the analyzer should be flagging, unless necessary.

**Comment by bradwilson** [comment]
I disagree. What you're doing is so unusual that there is far more benefit to the general public to help them fall into the pit of success (at your slight inconvenience).

You can also just turn those rules off entirely in your project if you never want them enforced (and then you won't need any overrides in the source). https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019

**Comment by mwpowellhtx** [comment]
I like the warnings, but if I've already met the conditions, which ever version of the method signature the attributes landed on, that should be sufficient.

**Comment by bradwilson** [comment]
From a performance standpoint, we can't support this open-ended scan of all the source that would be required to do the 1003 part of your request. Remember, this code runs while you're typing inside Visual Studio, not just as compilation time.

**Comment by mwpowellhtx** [comment]
Okay, fair enough; but really, how open ended is it to: 1) gather up the inherited attributes? and/or 2) examine the method signatures up/down the hierarchy?

**Comment by bradwilson** [comment]
The problem is there is no such thing as "down" the hierarchy without scanning every source file in every project.

**Comment by mwpowellhtx** [comment]
I see; the moment of scanning a file would be the wrong time to do that, I think. Assuming you have some visibility into a class, method, tree, etc, I should think that was the right time. Have a look at my [``MeasureIt``](/mwpowellhtx/MeasureIt/search?q=methodinfo&unscoped_q=methodinfo), I do a scan along these lines identifying attributes, etc.

**Comment by bradwilson** [comment]
Have you written a Roslyn analyzer before? The rules and the structure of the API makes slow things difficult to impossible on purpose.

**Comment by mwpowellhtx** [comment]
It's a fair point re: the API. It is rather cumbersome to deal with every nibble as a token.
