### ISSUE TITLE
ignoreWhiteSpaceDifferences should include all Unicode white space characters

### ISSUE THREAD

**Issue by christianfredh** [xunit/xunit#1931]
`Assert.Equal("This is some text", "This\xa0is\xa0some\xa0text", ignoreWhiteSpaceDifferences: true);`

The above code currently gives an assertion errors and the strings are not considered the same  when ignoring white space differences.

Maybe there is a good reason why it's not included that I don't know. But to me it seems like non-breaking space should be included when setting ignoreWhiteSpaceDifferences to true.

**Comment by bradwilson** [comment]
No good reason other than that it was overlooked at the time.

[This page](http://jkorpela.fi/chars/spaces.html) (from which I copied the below table) shows that there are several potential white space characters that we should probably support that aren't yet supported. I would be okay supporting this entire list (except for U+1680, which seems distinctly non-space-like).

Code | Name of the character | Sample | Width of the character
-- | -- | -- | --
U+0020 | SPACE | `foo bar` | Depends on font, typically 1/4 em, often adjusted
U+00A0 | NO-BREAK SPACE | `foo bar` | As a space, but often not  adjusted
U+1680 | OGHAM SPACE MARK | `foo bar` | Unspecified; usually not really a space but a dash
U+180E | MONGOLIAN VOWEL SEPARATOR | `foo᠎bar` | 0
U+2000 | EN QUAD | `foo bar` | 1 en (= 1/2 em)
U+2001 | EM QUAD | `foo bar` | 1 em (nominally, the height of the font)
U+2002 | EN SPACE (nut) | `foo bar` | 1 en (= 1/2 em)
U+2003 | EM SPACE (mutton) | `foo bar` | 1 em
U+2004 | THREE-PER-EM SPACE (thick space) | `foo bar` | 1/3 em
U+2005 | FOUR-PER-EM SPACE (mid space) | `foo bar` | 1/4 em
U+2006 | SIX-PER-EM SPACE | `foo bar` | 1/6 em
U+2007 | FIGURE SPACE | `foo bar` | “Tabular width”, the width of digits
U+2008 | PUNCTUATION SPACE | `foo bar` | The width of a period “.”
U+2009 | THIN SPACE | `foo bar` | 1/5 em (or sometimes 1/6 em)
U+200A | HAIR SPACE | `foo bar` | Narrower than THIN SPACE
U+200B | ZERO WIDTH SPACE | `foo​bar` | 0
U+202F | NARROW NO-BREAK SPACE | `foo bar` | Narrower than NO-BREAK SPACE (or SPACE), “typically the width of a thin space or a mid space”
U+205F | MEDIUM MATHEMATICAL SPACE | `foo bar` | 4/18 em
U+3000 | IDEOGRAPHIC SPACE | `foo　bar` | The width of ideographic (CJK) characters.
U+FEFF | ZERO WIDTH NO-BREAK SPACE | `foo﻿bar` | 0

**Comment by markusschaber** [comment]
Maybe we could rely on [Char.IsWhiteSpace()](https://docs.microsoft.com/de-de/dotnet/api/system.char.iswhitespace?view=netstandard-2.0) instead of maintaining our own list?

**Comment by markusschaber** [comment]
The set of characters recognized by Char.IsWhiteSpace() differs from the table above:
- The Mongolian Vovel Separator is missing
- The Zero Width Space and Zero Width No-Break Space are missing
- Line Separator (U+2028) and Paragraph Separator (U+2029) are added.
- The characters CHARACTER TABULATION (U+0009), LINE FEED (U+000A), LINE TABULATION (U+000B), FORM FEED (U+000C), CARRIAGE RETURN (U+000D), and NEXT LINE (U+0085) are added.

However, I think using `Char.IsWhiteSpace()` has two advantages:
- Lesser maintainance burden: just rely on the framework maintainers to grasp unicode
- Consistency with framework methods like `String.Trim()`

**Comment by markusschaber** [comment]
Just noticed that Char.IsWhiteSpace() also includes line breaks. Alt least one existing test case behaves differently:
`'StringAssertsTests+Equal.FailureCases(expected: "foo \nbar", actual: "FoO  \rbar", ignoreCase: True, ignoreLineEndingDifferences: False, ignoreWhiteSpaceDifferences: True, expectedIndex: 4, actualIndex: 5)'`
Which is quite expected using the sematics of `Char.IsWhiteSpace()`, but it might introduce too much incompatibility... Maybe do it in V3?

**Comment by bradwilson** [comment]
Any changes that happen will be for v3. That said, I don't want newline or carriage return to be considered whitespace, which probably means we can't use the function from `Char`.

**Comment by markusschaber** [comment]
We could still rely on the character class definitions from Unicode, or we can blacklist the linefeeds.

**Comment by bradwilson** [comment]
Merged with https://github.com/xunit/assert.xunit/commit/eeb6224b7ad1800c78f9db93d5e263b217b24549 and https://github.com/xunit/xunit/commit/63629d811a488f61a27e392284f9b6131232c657
