### ISSUE TITLE
Standardize all assert exception argument formatting

### ISSUE THREAD

**Issue by hughbe** [xunit/xunit#1932]
E.g.

```cs
Assert.Null("\0*.*\0");
```

>Error Message:
 Assert.Null() Failure
Expected: (null)
Actual:    *.*

**Comment by bradwilson** [comment]
Widening the scope of this to ensure all assertion exceptions use identical formatting rules (printing of control characters being a subset).

**Comment by Xcodo** [comment]
I'm interested in looking at this. Two questions

1. How do you want the control characters represented? Character codes? A specific unusual character?
2. Are there other known areas where the formatting differences at the moment?

**Comment by mateusz-dobrowolny** [comment]
@Xcodo I think the best way for communication is to mention @bradwilson

**Comment by bradwilson** [comment]
Thanks for resurfacing this @mateusz-dobrowolny because it's been fixed already! 😄 

![image](https://github.com/xunit/xunit/assets/16944/efe2bfbf-5cb2-450a-bcdd-6a83635a5cfa)
