### ISSUE TITLE
Incomplete documentation of V2 XML format, "output" tag is missing.

### ISSUE THREAD

**Issue by markusschaber** [xunit/xunit#1933]
In the Documentation for the [XML V2 format](https://xunit.net/docs/format-xml-v2), the "output" tag which captures the output from `ITestOutputHelper` seems missing.

It's documented in the V1 documentation, and according to the [discussion on slack](https://xunit.slack.com/archives/C034MFNED/p1556635597065600), it's also implemented in V2.

**Comment by bradwilson** [comment]
Fixed in https://github.com/xunit/xunit/commit/f61ffd5480259cabaf660c21389e854ff6bfb79b
