### ISSUE TITLE
please check your json schema file for xunit.runner.json

### ISSUE THREAD

**Issue by springy76** [xunit/xunit#1938]
If I request this url:
https://xunit.net/schema/current/xunit.runner.schema.json

The contents look good (`methodDisplayOptions` is present) **but** there is this ugly line inside
```json
"id": "http://xunit.github.io/schema/v2.3/xunit.runner.schema.json",
```

This file of course doesn't contain `methodDisplayOptions` and there is no v2.4 file either.

So VS+R# integration (via https://github.com/SchemaStore/schemastore ) always reports errors.

see also: https://github.com/SchemaStore/schemastore/issues/681

**Comment by SimonCropp** [comment]
seems https://xunit.net/schema/current/xunit.runner.schema.json has been updated

the value is now 
```
id  "https://xunit.net/schema/current/xunit.runner.schema.json"
```

so assuming we can close this?

**Comment by bradwilson** [comment]
Yep!
