### ISSUE TITLE
Running tests sequentially from a browser state - reusing same browser window/ page

### ISSUE THREAD

**Issue by apvenk** [xunit/xunit#1941]
Hi

I would like to know if i can run tests sequentially within a class file from a specific state (browser state). Or is this not supported and we always have a new instance each time?

ex:
1. Browse a portal, do some things and get to a specific page A (class setup) with a specific state S1
2. Define means to always get back to state S1 to start each test
2. Run test case 1, 2, 3, etc within the same class sequentially (using the same browser window) as all the tests are checks within the same page A or within a category.

Reason: to save time and to reuse the browser.

**Comment by bradwilson** [comment]
You always run a new instance of the test class, but you can have shared state between test methods. Please see https://xunit.net/docs/shared-context for how to achieve what you want (specifically, you're probably looking for a class fixture).
