### ISSUE TITLE
Convert to Theory does not work in Rider

### ISSUE THREAD

**Issue by andy-codurance** [xunit/xunit#1943]
Hi,

If I a add a parameter to a method decorated with the Fact attribute, Rider quick refactor popup will let me Remove Parameters or Convert to Theory. The Remove Parameters refactor works, but the Convert to Theory one does not, ie the Fact attribute is not replaced with the Theory attribute.

I first raised this with JetBrains and their response was:

> Thanks for getting back to me. I've double checked, and it seems to be a bug in xunit.analyzers. The fix operation is provided by Roslyn, not Rider, which is indicated by the lambda icon next to it. For me, the "Remove parameter" fix works both in Rider and Visual Studio, while "Convert to Theory" does nothing in both IDEs.

I'm using Rider 2019.1.1 and dotnet is setup like so:
```
➜  ~ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.106
 Commit:    aa79b139a8

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.106/

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.1.403 [/usr/local/share/dotnet/sdk]
  2.2.106 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

Cheers

**Comment by bradwilson** [comment]
Fixed in https://github.com/xunit/xunit.analyzers/commit/00de07c96963081aaaf1245952baf7909cb0cc8a
