### ISSUE TITLE
Update System.Net.Http from System.Net.Http@4.3.0 to 4.3.2 to avoid DoS, SFB, PE and Spoofing issues.

### ISSUE THREAD

**Issue by SeppPenner** [xunit/xunit#1951]
## Description
Update the `System.Net.Http` from version 4.3.0 to 4.3.2 to avoid `Security Feature Bypass`, `Denial of Service`, `Elevation of Privilege` and `Spoofing` issues introduced with the prior version. Check https://github.com/aspnet/Announcements/issues/239 and https://app.snyk.io/vuln/SNYK-DOTNET-SYSTEMNETHTTP-60045.

I recently saw this issue using the snyk application on my Github account.

Example:

![grafik](https://user-images.githubusercontent.com/9639361/58504109-34093780-818a-11e9-9e92-de6a72d7792b.png)

**Comment by bradwilson** [comment]
This will eventually get updated, but we don't consider this an urgent issue because xUnit.net is not intended for production, customer-facing use.

**Comment by jweswilson** [comment]
A related and similar issue is the dependency on .NetCoreApp 1.0 pulling in System.Net.Security-1.0.24212.01.dll which has many open high severity CVE's.  Appreciate the perspective that it doesn't wind up customer facing but it does show up on vulnerability scans and has to have documented justifications.  The Microsoft Azure build pipeline using WhiteSource Bolt is flagging solutions as insecure if they include this library.

**Comment by bradwilson** [comment]
This has been fixed for v3.

**Comment by mcallaghan-geotab** [comment]
But where is v3? https://www.nuget.org/packages/xunit#versions-body-tab
Can we get a patch release to the `2.4.X` stream?

**Comment by bradwilson** [comment]
@mcallaghan-geotab Instructions on using the v3 alpha builds: https://xunit.net/docs/v3-alpha

Right now, there are no plans for any more v2 releases.
