### ISSUE TITLE
Theory attribute picking up all implementations of an interface

### ISSUE THREAD

**Issue by apvenk** [xunit/xunit#1952]
Does xUnit have the concept of specifying as a theory all interfaces of a type T.

Example : 

```csharp
interface IPortalTestPage
    {
        string Title { get; }
    }

    class PortalTestPage1 : IPortalTestPage
    {
        public string Title => "Page 1";
    }

    class PortalTestPage2 : IPortalTestPage
    {
        public string Title => "Page 2";
    }
```

Is it possible either directly or by using attributes to get all the implementations of IPortalTestPage within a namespace/project ? Something like this for example is supported by Spring framework with annotations where it can get all instances of an interface in the Java world. I'm trying to find the equivalence here.

Expected Usage Example is something like :

```csharp
[Theory]
        [ClassData(typeof(IPortalTestPage))]
        public void PortalPage_WhenLoading_ShouldHaveCorrectTitle(IPortalTestPage page)
        {
            var result = Load(page);
            result.Title.Should().Be(page.Title);
        }
```

**Comment by bradwilson** [comment]
There is nothing built-in for this, but it wouldn't be too hard to write it yourself. The data provider attributes are designed to be extended; you would just need to scan the test assembly looking for classes which implemented the interface.

There is a theory data provider example to get you started. It shows how to read theory data from a SQL database, but the principles are the same (with a different source for your "data"): https://github.com/xunit/samples.xunit/tree/master/SqlDataExample

**Comment by bradwilson** [comment]
Closing this as Won't Fix, since there are no plans to add this directly.
