### ISSUE TITLE
Assert.NotNull with return type

### ISSUE THREAD

**Issue by springy76** [xunit/xunit#1960]
The existing `void NotNull(object @object)` method could be split into 2 generic methods:

```cs
public static T NotNull<T>(T obj) where T : class
=> obj ?? throw new NotNullException();

public static T NotNull<T>(T? value) where T : struct
=> value ?? throw new NotNullException();
```

This would allow to get a strong typed non-null result and additionally prevent unneccesary boxing against nullable types:

```cs
var notNull = Assert.NotNull(obj.Prop?.Nested?.Deeper);
Assert.WhatEver(notNull.Prop);
```

The same kind of boxing prevention would also apply to `Assert.Null()` (but without a return value of course).

Another benefit: This way the compiler already would complain when calling (Not)Null for non-nullable value types. (Yes, this will break some (bad written) existing unit tests for sure.)

**Comment by bradwilson** [comment]
This is a nice idea, but I'm reluctant to add a return type to the object-version (because it penalizes anybody who uses xUnit.net with F#, as any function which returns a value must get that value assigned into a variable). So my only amendment would be to change the first one to return void.

**Comment by springy76** [comment]
My personal interest was more in the return value thing (similar to `Assert.Single()`) than the GC optimization.

(wasn't aware about F# at all)

**Comment by bradwilson** [comment]
I feel like the way you're describing it, you're missing your "act" and your first assert together, which is not behavior that I would want to encourage personally.

Good:

```csharp
// Act
var x = PerformSomeAction();

// Assert
Assert.NotNull(x);
```

Less good:

```csharp
// Act & Assert mixed together
var x = Assert.NotNull(PerformSomeAction());
```

Am I interpreting your request correctly?

**Comment by bradwilson** [comment]
FWIW, I'm not a fan of "chaining" asserts together either:

Good:

```csharp
var x = Assert.Single(...);
Assert.NotNull();
```

Less good:

```csharp
var x = Assert.NotNull(Assert.Single(...));
```

**Comment by springy76** [comment]
I totally agree with your good/less-good samples. I gave my sample in the original post, now extended it to fit in your pattern above:

```cs
// Act
var objGraph = PerformSomeAction();

// Assert
var otherObj = Assert.NotNull(objGraph.Prop?.Nested?.Deeper);
Assert.WhatEver(notNull.Prop); // concentrate on "otherObj" without duplicating code `objGraph.Prop?.Nested?.Deeper`
```

**Comment by Porges** [comment]
This is especially needed with the new C# nullable checking. 

We have some code that does, e.g.:

```csharp
int? result = ...;

Assert.Equal(result.Value, expected);
```

with nullable checking on this is a compiler error, as Value might not be available. We can fix it by inserting a manual if (with else branch `Assert.Fail`), but it would be nicer to write:

```csharp
int? maybeResult = ...;

var result = Assert.NotNull(maybeResult);
Assert.Equal(result, expected);
```

**Comment by RikkiGibson** [comment]
@Porges I think xunit/assert.xunit#36 addresses your use case.

**Comment by bradwilson** [comment]
Now that we have nullable annotations on the assert, I think this code is probably better written as:

```csharp
var objGraph = PerformSomeAction();

// Assert
var otherObj = objGraph.Prop?.Nested?.Deeper;
Assert.NotNull(otherObj);
Assert.WhatEver(otherObj.Prop);
```

And this allows us to keep `Assert.NotNull` as non-returning, which is better for F#.

As such, I'm going to close this issue as resolved (albeit slightly differently from the original request).
