### ISSUE TITLE
Clarify DelayedMessageBus locking behavior in Samples.Xunit

### ISSUE THREAD

**Issue by jeroenheijmans** [xunit/xunit#1964]
The [`DelayedMessageBus` in the `RetryFactExample`](https://github.com/xunit/samples.xunit/blob/master/RetryFactExample/DelayedMessageBus.cs) has some unclear code around locking.

The goal of that message bus is clear (I think), as it decorates another `IMessageBus` and keeps a queue of messages until things are flushed (via a `Dispose()` call).

What is _not_ clear is why only _one_ place uses a plain old `lock` mechanism:

https://github.com/xunit/samples.xunit/blob/5334ee9cf4a81f40dcb4cafabfeb098a555efb3d/RetryFactExample/DelayedMessageBus.cs#L21-L24

```
public bool QueueMessage(IMessageSinkMessage message)
{
    lock (messages)
        messages.Add(message);

    // etc
```

To the uninitiated, it seems that either one of these options would be an improvement:

1. Adding a comment above the `lock` statement explaining _why_ it's needed there (and only there)
2. Also using a `lock` when flushing the messages in the Dispose method
3. Replacing the `List<IMessageSinkMessage>` with a `Concurrent` collection

But as it stands, the example is confusing in this regard.

**Comment by jeroenheijmans** [comment]
I've browsed through the xUnit core repository and found these implementations of `IMessageBus`:

- [`SynchronousMessageBus`](https://github.com/xunit/xunit/blob/master/src/xunit.execution/Sdk/SynchronousMessageBus.cs)
- [`DelegatingMessageBus`](https://github.com/xunit/xunit/blob/3f3f6929c301db40e9d5d8ced2bb494084f57c82/src/xunit.execution/Sdk/Messages/DelegatingMessageBus.cs)
- [`SpyMessageBus`](https://github.com/xunit/xunit/blob/9d10262a3694bb099ddd783d735aba2a7aac759d/test/test.utility/TestDoubles/SpyMessageBus.cs)

None of them do any similar locking.

On the other hand, only the `SpyMessageBus` has a similar internal collection, and it is seemingly only used in _testing_ xunit itself, so no multi-threading expected possibly?

**Comment by bradwilson** [comment]
So there are two things going on here.

First: QueueMessage. We cannot predict when the engine will send messages to us, so using a lock (or a Concurrent container) is best. That said, there's no such thing as `ConcurrentList<T>`, which is why `lock` is used against a `List<T>` instead. Order is important with these messages.

Seconds: Dispose. There is no need to lock in the Dispose method, because Dispose is not contractually required to support re-entrance (you should never Dispose this object--or any object, for that matter--from several threads at the same time).

**Comment by bradwilson** [comment]
The more I think about it, there is an argument to be made for not having a lock in `DelayedMessageBus`. Although the engine can run things in parallel, in this _particular_ case, we know this message bus is being used for a single test case, so there is no test case parallelization going on. That said, I'm concerned that removing the lock would be an optimization that might lead people astray about the _generalized_ need for locking in this scenario for a bus which delayed messages on behalf of multiple test cases. So I'm inclined to leave it, even though in this scenario it isn't technically necessary.

**Comment by jeroenheijmans** [comment]
Thanks for your response!

> in this particular case, we know this message bus is being used for a single test case

I was indeed thinking the same, and replaced the `lock` with a comment explaining the why of things.

The `Dispose` method in the `RetryFact` `DelayedMessageBus` example is confusing though in my mind, as (a) it's used without a `using` / used straight up as a normal method, and (b) if `Dispose` is somehow called multiple times it will flush messages multiple times. 

I might take a shot at proposing improvements later on in a small PR, incorporating your suggestions as well as my own thoughts, just to give us something to make it concrete.

At any rate, many thanks again for your insights.

**Comment by bradwilson** [comment]
Closing for age

**Comment by jeroenheijmans** [comment]
@bradwilson Totally understand, and apologies for never getting back to it with a PR. Thank you for being a fantastic steward of such an important piece of the .NET ecosystem! 👍🏻❤️
