### ISSUE TITLE
TraitHelper.GetTraits() gets caught in endless loop

### ISSUE THREAD

**Issue by cowtrix** [xunit/xunit#1965]
Hello all.

Quick bug discovered in xunit/xunit/blob/master/src/xunit.execution/Sdk/TraitHelper.cs

In FindDiscovererAttributeType(), we enter a do/while loop and attempt to find the DiscovererAttributeType. The intention with this loop appears to be traversing up the inheritance tree until a type is discovered that has this attribute. **However** -  this loop is incorrect, as `typeChecking` is never updated from the BaseType of the traitAttribute.

Instead of:

typeChecking = traitAttribute.BaseType.GetTypeInfo();

It should be:

typeChecking = typeChecking.BaseType.GetTypeInfo();

This issue means that custom trait providers that have more than 1 level of abstraction will  currently cause xunit to be stuck in a silent failure loop.

Thanks!

**Comment by bradwilson** [comment]
That's a good catch. That bug has been there probably far back into v1 days!

**Comment by memark** [comment]
I'm looking for a first good issue to start contributing.

There is already a PR here, is it being merged? @bradwilson

**Comment by bradwilson** [comment]
Fixed in edf17ea33c31daa77c675c22a7cdc7f5cc8d5182
