### ISSUE TITLE
Consider providing Span<T> / Memory<T> based overloads of assertion methods

### ISSUE THREAD

**Issue by Gnbrkm41** [xunit/xunit#1966]
I've just noticed that there is no overloads of `Assert.Contains` for (ReadOnly)Span / (ReadOnly)Memory while implementing auto-fix for some of the test codes in  https://github.com/dotnet/corefx. it would be a nice addition if there are span/memory based overloads for various assertion methods.

Example:
https://github.com/dotnet/corefx/blob/master/src/Common/tests/Tests/System/StringTests.cs#L1166-L1179

```cs
public static void SameSpanContains_StringComparison()
{            
    string s1 = "456";
    Assert.Contains(s1, s1);
            
    ReadOnlySpan<char> span = s1.AsSpan();
    Assert.True(span.Contains(span, StringComparison.Ordinal));

    Assert.True(span.Contains(span, StringComparison.CurrentCulture));
    Assert.True(span.Contains(span, StringComparison.CurrentCultureIgnoreCase));
    Assert.True(span.Contains(span, StringComparison.InvariantCulture));
    Assert.True(span.Contains(span, StringComparison.InvariantCultureIgnoreCase));
    Assert.True(span.Contains(span, StringComparison.OrdinalIgnoreCase));
}
```
The assertion `Assert.True(s1.Contains(s1))` can be simplified to `Assert.Contains(s1, s1)`, however because there is no span based overloads, same thing cannot be done for the rest of the test codes.

I haven't looked deeper, but I think it would be a great addition to have in general considering that Span/Memory is being used quite widely.

~~(on an unrelated note: since the test is supposed to test the Contains function, I'd need to suppress it anyway)~~

**Comment by bradwilson** [comment]
This should be all ready to go as of https://github.com/xunit/assert.xunit/commit/b4f2de311f3b050d3cce6d6024dcdccfcfa2bbf8 and 0adb05dfe7e67a589cb17ff4a511e42d04283a51.

You may notice a lot of overloads (e.g., `Memory<T>` vs `ReadOnlyMemory<T>`) that were necessitated by compiler collisions with other Assert methods.

Also, the pretty printed `string` assertion:

https://github.com/xunit/assert.xunit/blob/b4f2de311f3b050d3cce6d6024dcdccfcfa2bbf8/StringAsserts.cs#L237-L250

has been re-written to be based on `ReadOnlySpan<char>`:

https://github.com/xunit/assert.xunit/blob/b4f2de311f3b050d3cce6d6024dcdccfcfa2bbf8/SpanAsserts.cs#L617-L675

(with the exception of null-string handling, as `null` `ReadOnlySpan<char>` isn't legal, so its handling is slightly different).

**Comment by Gnbrkm41** [comment]
Thanks, @bradwilson!
