### ISSUE TITLE
== operator not being executed

### ISSUE THREAD

**Issue by bstordrup** [xunit/xunit#1967]
I have a class that implements IEquatable<T> and overrides the == operator.
I want to test the IEquatable implementation of this class, so I write a test that takes two instances and then compare them using the == operator.
To my surprise, the == operator is not called - I have modified code to verify that the == operator function is called.

When doing the same thing in LINQ, the == operator is called.

When creating code that uses the == operator of this class, the == operator is called when running the applicaiton.

**Comment by bartelink** [comment]
worth mentioning the exact signature and/or showing it as an excerpt (also are you opening the namespace?) In general, I wouldnt expect xUnit to be involved in selecting to call an `==` method; simply objecing normal IEquatable semantics

**Comment by bradwilson** [comment]
Yes, please provide a repro project.

**Comment by bstordrup** [comment]
OK. I will create a repro and share with you. Might be a bit i the future - going on vacation soon for three weeks.

**Comment by SimonCropp** [comment]
@bstordrup still an issue?

**Comment by bradwilson** [comment]
Closing for age
