### ISSUE TITLE
Analyzer xUnit1016 / xUnit1019 fired even if matching method

### ISSUE THREAD

**Issue by Clockwork-Muse** [xunit/xunit#1968]
When test data generation methods (targets of `MemberData`) are considered by analyzers, it appears to only look at the _first_ method encountered, rather than attempting to discover whether any would actually be valid.  This appears to occur even if the method is completely invalid, due to things like parameter lists.

![image](https://user-images.githubusercontent.com/5569508/59818333-53523b00-92d8-11e9-825c-c195604615b0.png)

Switching the order of the public and private method here quiets the analyzer.
Note that, prior to the analyzer being enabled, the code would successfully build and run tests.

[Attaching the sample repro](https://github.com/xunit/xunit/files/3308756/PublicMemberReturnType.zip)

**Comment by bradwilson** [comment]
Fixed by e0f38062efcced684d717ba661578f16c675913b
