### ISSUE TITLE
-notrait and -trait is completely broken with custom traits

### ISSUE THREAD

**Issue by cowtrix** [xunit/xunit#1977]
Well, would have been nice to know that custom traits are completely useless before I went and implemented them everywhere. 

Both the `-notrait` and `-trait` command for xunit console fails to recognise traits that are provided through an ITraitDiscoverer, and only works for explicit uses of the `Trait` attribute.

**Comment by bradwilson** [comment]
Can you provide the source for the trait provider which demonstrates this?

Thanks!

**Comment by cowtrix** [comment]
In my hubris and frustration, I blamed when I should have investigated. The fault was mine! Sorry about that.
