### ISSUE TITLE
Need for inner results when publishing tests

### ISSUE THREAD

**Issue by utkarshagoswami** [xunit/xunit#1987]
When publishing data driven tests using [Theory] and [InlineData()] attribute or in any other way, when xml is generated, each iteration of the test method creates a new data row with xml attribute as `<test>`. This attribute has `name` as the combination of Solution name, class name, test method name followed by value of the data in bracket. The `type` property of this xml attribute is combination of solution name and class name where as the `method` property of this attribute is the test method name.

Each iteration of a particular test method can be uniquely identified using the combination of `type` and `method` property. If instead of considering each iteration as a new data row they are clubbed under one `test` attribute, it will save space and would result in better reporting experience. Also, the user will be able to see all the test iterations corresponding to each method inside one result thus making it easier and clearer for user to understand.

**Comment by bradwilson** [comment]
This would be a significant breaking change.

**Comment by utkarshagoswami** [comment]
We are trying to identify group the results as inner results when parsing the XML formed at our end. We understand that making change in the adapter itself would be a breaking change so we can try and fix this at our end. 

Our basic requirement is to club tests pertaining to one method under one data row and have multiple child rows to it corresponding to each iteration of the test method. Can you suggest a way to uniquely identify a test rows that belong to iteration of a particular method. When we generated XML using the following tests:
![image](https://user-images.githubusercontent.com/18283946/61700835-cbd66c80-ad5a-11e9-84ef-71ebab458a22.png), 
the following XML was generated:
![image](https://user-images.githubusercontent.com/18283946/61700876-d85ac500-ad5a-11e9-8b42-0378875aacc8.png)

From this xml we understand that the combination of `type` and `method` can be used to find tests pertaining to iterations of one method. This can be one approach. Is it the right way? Can there be cases where combination of the aforementioned attributes is same for two different methods?

**Comment by bradwilson** [comment]
That is the way to do it. Those are always the CLR names so you can rely on them to be unique and usable for grouping like you need.

**Comment by puagarwa** [comment]
Thanks @bradwilson we will go ahead and add this logic in xunit xml parsing.
I have another question related to trx generation for xunit from adaptor which we create in vstest , if we want to create this hierarchy in trx while listening to adaptor , is there a similar property by which we can create hierarchy in trx, for instance in case mstest adaptor we create the hierarchy by using parent and child execution Id, do we have this or some other property by which we can create hierarchy?

**Comment by bradwilson** [comment]
We don't create TRX. That's solely the domain of VSTest.

**Comment by puagarwa** [comment]
yes, I will check the xunit adaptor outcome to see what are the property that we can use to create hierarchy.

**Comment by bradwilson** [comment]
This appears to have been resolved, so closing.
