### ISSUE TITLE
Use TypeConverter to convert type of theory arguments

### ISSUE THREAD

**Issue by navozenko** [xunit/xunit#1989]
Now xUnit supports the implicit/explicit type conversion operators on theory arguments. 
Are there any reasons why TypeConvertor is not supported for the same purpose? Adding implicit/explicit operators to a tested class class is not always a good idea, whereas TypeConverter is the standard way to convert a type in a .NET

```csharp
[TypeConverter(typeof(CustomTypeConverter))]
class Foo
{
}

[Theory]
[InlineData("abc")]
public void SomeTest(Foo foo)
{
    DoSomething();
}
```

**Comment by bradwilson** [comment]
For v2 this isn't possible because there were several target platforms that didn't have TypeConverter available. For v3, we should be able to add this.

**Comment by navozenko** [comment]
@bradwilson I'm not sure what you mean. As far as I can see from the source code, xUnit is now compiling for .NET Standard 2.0 so any target platform where xUnit tests are run now supports TypeConverter.

If you mean that the target platform of the class under test may not support TypeConverter, then I don't understand how this interferes either. If the class doesn't have the TypeConverterAttribute it can be processed by xUnit as it is now, can't it?

**Comment by bradwilson** [comment]
That's because master is v3 now.

**Comment by navozenko** [comment]
I am closing this issue as well as the associated pull-request and the another issue because the owner has not shown interest in my proposals.
