### ISSUE TITLE
MemberData returns null with expression tree

### ISSUE THREAD

**Issue by achobanov** [xunit/xunit#1991]
## Problem
I want to test query method, by providing different filters as parameters. Here is the setup I came up with:
### Provider.cs
```c#
public static class Provider
{
    public static readonly IEnumerable<object[]> Filters = new List<object[]>
    {
        new object[] { Filter },
    };

    private static readonly Expression<Func<Model, bool>> Filter  
         = x => x.Name.Contains("A");
}
```
### Tests.cs
```c#
[Theroy]
public async Task TestMethod(Expression<Func<Model, bool>> filter)
{
    // filter is null here
}
```
I have left out a single tests for clarity. I have left out `Model` definition, because it's not important.

## Work-around
It works correctly if the expression is not contained in a static property, but directly inside the `object` array, like this:
```c#
    public static readonly IEnumerable<object[]> Filters = new List<object[]>
    {
        new object[] { (Expression<Func<Model, bool>>)  x => x.Name.Contains("A") },
    };
```

It's a small inconvenience, because I don't get to name the filters, but I am really interested as to why does it behave like that.

**Comment by navozenko** [comment]
It's because you initialize the Filters property before the Filter property. At this point, the Filter property is still null. Swap the Filter and Filters properties and everything will work.

**Comment by achobanov** [comment]
🤦‍♂ Thanks @navozenko.
