### ISSUE TITLE
Tests with mocks fail in xunit.runner.console but passes locally executed from VS

### ISSUE THREAD

**Issue by GondilOndro** [xunit/xunit#1994]
Hello currently facing problem with xunit.runner.console. Test in TFS CI are failing however they are passing locally executed in VS. Firstly I thought, that problem is maybe in CI, then that it is in dotCover because on CI following command is executed (not exactly this but something like - i run this command locally with published dll and get same errors as in CI):

`.\tools\dotcover.exe cover /TargetExecutable=".\..\xunit-runner\tools\net461\xunit.console.exe"
/TargetArguments="c:\Projects\MySolution\Sources\MyTestProject\bin\Debug\MyTestProject.dll -xml c:/temp/testResultFile.xml"
/Output="c:/temp/coverageResultFile.dcvr"
/Filters='-:module=xunit.*;-:module=*UnitTests*'`

At the end I just tried to run following command locally:

`.\xunit.console c:\Projects\MySolution\Sources\MyTestProject\bin\Debug\MyTestProject.dll`
and bingo, same errors so it seems that xunit.runner.console is the cause of the problems.

Need to mention, that errors provided by xunit.runner.console often fail on NullReferenceException or on Assert where there is expected a value but it is null. Those tests are using mock as testing data and it seems that somehow these mock data are not filled properly when running tests from xunit.runner.console, but there is no issue when running them in VS.

Do you have any advice in this? Is it a problem with xunit.runner.console or in mock initialization that is not executed by runner but it is in VS?

**Comment by bradwilson** [comment]
Since we don't ship a mocking framework, I assume the issue is probably some interaction with whatever mocking framework you've chosen. Can you provide a repro project? Thanks!

**Comment by GondilOndro** [comment]
The mocks are crazy here, probably there will be problem in them. It almost looks like that there is some kind of internal Mocking FW. I was just assuming the problem because when I run xunit.runner.console, tests failed, but when run dotnet vstest they didn't but probably vstest has different execution.
Unfortunatelly I can provide a project :/ Generally I was asking if somebody haven't faced similar problem or if you xunit developers don't know something about it. But as I said, now it seems that the problem is in mocks. I have to investigate more.
Maybe you could put this "issue" to the side for this time :)

**Comment by GondilOndro** [comment]
One of my colleagues made kind of mocking FW, when he was using C# attributes for calling mocks initialization. However when tests was executed through xunit.runner.console, it didn't call the initialization. We changed the code so for each test the initialization was called at the beginning of test explicitly and now it is working.
