### ISSUE TITLE
Feature proposition - test sharding 

### ISSUE THREAD

**Issue by maxcherednik** [xunit/xunit#1996]
We have got a crazy amount of tests. While running we are going with full parallelism provided by the xUnit, it is still not enough - even on multicore machine all the cores are used at all times.

**Proposition**
1. To have a command line parameters like: maxNodeCount, currentNode
1. Based on the parameters, using the testfixturenames determine if a certain test fixture should be executed on the node `currentNode`. 
1. Run only the ones which are matching

Having this functionality it would be possible to have N build server configurations, each of which could be executed independently. Each configuration would have a running command like this: 

- runtests maxNodeCount:3, currentNode:0
- runtests maxNodeCount:3, currentNode:1
- runtests maxNodeCount:3, currentNode:2

**Comment by bradwilson** [comment]
There are third party solutions to this already today (like [NCrunch](https://www.ncrunch.net/)) that should suit this fairly niche requirement (especially given our focus on fast-running unit tests).

**Comment by maxcherednik** [comment]
I see. But if I want to implement it myself, I should probably look into this: https://github.com/xunit/abstractions.xunit/tree/master/src/xunit.abstractions/Frameworks

Right?

**Comment by bradwilson** [comment]
Yes, you could do that. It's extremely non-trivial. There are samples available, like: https://github.com/xunit/samples.xunit/tree/master/ObservationExample

**Comment by maxcherednik** [comment]
@bradwilson I managed to achieve what I wanted without fully implementing TestFramework abstractions.
My ultimate goal was to filter the test collections based on the `node id` and `node count` variables.

I have found the `ITestCollectionOrderer` abstraction. I know its purpose is for the ordering, but it seems it is working for filtering as well.

Here is my implementation:
```csharp
public class TestCollectionShardedOrderer : ITestCollectionOrderer
    {
        public IEnumerable<ITestCollection> OrderTestCollections(IEnumerable<ITestCollection> testCollections)
        {
            var all = testCollections.ToList();

            all.Sort((collection1, collection2) =>
                string.Compare(collection1.DisplayName, collection2.DisplayName, StringComparison.Ordinal));

            //Environment.GetEnvironmentVariable("NodeCount");
            
            //Environment.GetEnvironmentVariable("NodeId");

            var nodeCount = 2;

            var nodeId = 1;

            var testCollectionsPerShard = DivideRoundUp(all.Count, nodeCount);

            var startingIndex = nodeId * testCollectionsPerShard;


            if (nodeCount - 1 == nodeId && all.Count % nodeCount > 0)
            {
                return all.Skip(startingIndex);
            }

            return all.Skip(startingIndex).Take(testCollectionsPerShard);
        }

        private static int DivideRoundUp(int dividend, int divisor)
        {
            return (dividend + divisor - 1) / divisor;
        }
    }
```

Using it with the attribute like this:
```csharp
[assembly: TestCollectionOrderer("xUnit.Sharding.TestCollectionShardedOrderer", "xUnit.Sharding")]
```

**Questions:**
Is there a better abstraction for the filtering like this?
Do you see any pitfalls in the proposed solution?

**Comment by bradwilson** [comment]
It wasn't intended for filtering but it's okay to use it that way.

**Comment by maxcherednik** [comment]
@bradwilson got a q: an exception thrown in the `ITestCollectionOrderer` is not visible anywhere and the tests are still running. Is this by design?

**Comment by bradwilson** [comment]
Probably not. 😉

**Comment by maxcherednik** [comment]
@bradwilson found it. Seems like it is by design: https://github.com/xunit/xunit/blob/c7f123adfc1d6dd0912e64c40b585b5d919077ba/test/test.xunit.execution/Sdk/Frameworks/Runners/TestAssemblyRunnerTests.cs#L285

Implemented here: https://github.com/xunit/xunit/blob/3f3f6929c301db40e9d5d8ced2bb494084f57c82/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestAssemblyRunner.cs#L119

But still no diagnostic messages printed anywhere.

**Comment by bradwilson** [comment]
The test you linked clearly showed a diagnostic message is emitted. Did your enable diagnostic messages? https://xunit.net/docs/configuration-files#diagnosticMessages

**Comment by bradwilson** [comment]
Closing for age. If there are any other problems to be resolved, please open a new issue. Thanks!

**Comment by Porges** [comment]
For those it will help, a version for v3 based upon @maxcherednik's. Set the env var `TEST_SHARD` to `1/5`, `2/5`, ...

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using Xunit;
using Xunit.Sdk;
using Xunit.v3;

[assembly: TestCollectionOrderer(typeof(Tests.XUnit.TestCollectionShardedOrderer))]

namespace Tests.XUnit;

public class TestCollectionShardedOrderer : ITestCollectionOrderer {
    public IReadOnlyCollection<TTestCollection> OrderTestCollections<TTestCollection>(
        IReadOnlyCollection<TTestCollection> testCollections
        ) where TTestCollection : ITestCollection {

        // if running locally this will not be set; run them all
        if (Environment.GetEnvironmentVariable("TEST_SHARD") is not string envVar) {
            return testCollections;
        }

        var parts = envVar.Split('/', 2);
        if (parts.Length != 2) {
            throw new ArgumentException("TEST_SHARD must be in the format 'nodeId/nodeCount'");
        }

        var nodeId = int.Parse(parts[0]) - 1; // shard IDs are 1-based
        var nodeCount = int.Parse(parts[1]);

        // ensure a stable ordering:
        var all = testCollections.ToList();
        all.Sort((l, r) =>
            string.Compare(l.TestCollectionDisplayName, r.TestCollectionDisplayName, StringComparison.Ordinal));

        // divide the collections across the nodes:
        var collectionsPerShard = DivideRoundUp(all.Count, nodeCount);
        var startingIndex = nodeId * collectionsPerShard;

        return all[startingIndex..Math.Min(startingIndex + collectionsPerShard, all.Count)];
    }

    private static int DivideRoundUp(int dividend, int divisor)
        => (dividend + (divisor - 1)) / divisor;
}
```
