### ISSUE TITLE
Add Support for ExpectedResult and Description to InlineData

### ISSUE THREAD

**Issue by RehanSaeed** [xunit/xunit#2000]
NUnit lets you do this:

```
[TestCase(0.7, 2000, 5, ExpectedResult = 4, Description = "When accelerating rapidly on low RPM should reduce gear ")]
[TestCase(0.7, 2000, 1, ExpectedResult = 1, Description = "When accelerating rapidly on low RPM should not reduce gear when on first gear ")]
[TestCase(0.4, 2000, 5, ExpectedResult = 5, Description = "When accelerating NOT rapidly on low RPM should not reduce gear")]
public int CalculateAndVerifyGear(double acceleration, int currentRpm, int gear) =>
    new GearCalculator().Calculate(acceleration, currentRpm, gear);
```

I often pass in the expected result as the last argument in xUnit. It would be nice to differentiate it as NUnit have done. The description is also a cool addition.

**Comment by bradwilson** [comment]
We rejected the `ExpectedException` design of NUnit, and I do not like `ExpectedResult` either.

Being able to provide overridden descriptions is something we're planning for v3.

**Comment by RehanSaeed** [comment]
Fair enough.

**Comment by mindplay-dk** [comment]
> Being able to provide overridden descriptions is something we're planning for v3.

Is there a roadmap or any ongoing work for v3?

Any particular reason to hold on this feature for a major release? This could be added as an optional last argument to existing assertions without any breaking changes, could it not?

**Comment by janamtote** [comment]
> Being able to provide overridden descriptions is something we're planning for v3.

Anyone knows which issue tracks this? Thanks!
