### ISSUE TITLE
Bug: Capturing exceptions, doesn't work as  [Theory] and as Linux azure pipeline.

### ISSUE THREAD

**Issue by antonyoung** [xunit/xunit#2005]
**Description:**
There are two issues, that I found recently with capturing exceptions.
* [Theory] with [InlineData] doesn't execute the code that has to be tested for capturing exceptions? Actual exception is always null. As [Fact] it works fine on Windows, not sure about Linux?
* Azure DevOps pipeline with Linux build. Doesn't build because of ambiguous Exception.Record(Action), see also attachment dump.text? With .yml build on Windows we do not have this problem.

* Is this a question? Ask it on our Slack server: https://xunit.slack.com/
  Not a member? It's easy to sign up: https://xunit-slackin.herokuapp.com/
No, it's an observation.
* Is this a bug with VSTest (aka Visual Studio Test Explorer, `dotnet test`,
  `dotnet vstest`, or `vstest.console.exe`)? Open those issues here:
  https://github.com/xunit/visualstudio.xunit/issues/
Maybe, but no?
* Is this a bug related to Mono on Linux/OS X? Sorry, we don't officially support Mono (yet).
No, it's a net core on Linux / Windows issue.
* Did you search the documentation @ https://xunit.github.io/ ?
Yes I did, and did not solve the issue as bug.
* Did you search the issues list to see if someone already reported it?
Not found.
* Did you create a simple repro for the problem?
Yes I have, use https://github.com/antonyoung/postalcode project as example,

**Examples**
Throw whatever error in [PostcodeValidator.cs](https://github.com/antonyoung/postalcode/blob/master/Validators/PostcodeValidator.cs) in the last overloaded Validate function and capture this error as [Theory] in one of the test classes in [Postcode.Tests](https://github.com/antonyoung/postalcode/tree/master/Postcode.Tests) it will fail because of null exception => the code to test has never been executed.

Uncomment the tests [ExceptionTests.cs](https://github.com/antonyoung/postalcode/blob/master/Postcode.Tests/ExceptionTests.cs)
And it will never build with Azure Devops pipeline as Linux .yml because of ambiguous => Record.Exception(Action). Note: It works fine as windows build .yml.

Hope this helps, and keep up the good work xUnit Team ;-)

Attached: The failed build azure devops pipeline via linux, see also .yml file from repository. Note: Commented out the Test code to capture the exceptions, suddenly it all worked fine!
[dump.txt](https://github.com/xunit/xunit/files/3587887/dump.txt)

**Comment by bradwilson** [comment]
Closing for age, and because the enclosed links are dead now.
