### ISSUE TITLE
Add C# 8.0 Nullable Attributes to Assert methods

### ISSUE THREAD

**Issue by YairHalberstadt** [xunit/xunit#2011]
C# 8.0 introduces Nullable annotations.

Sometimes an API is too complex to be annotated and requires custom attributes.

In particular, the following methods in Xunit.Assert could benefit from attributes:

```csharp
public class Assert
{
                public static void False( [DoesNotReturnIf(true)] bool condition);

		public static void False( [DoesNotReturnIf(true)] bool condition, string? userMessage);

                public static void True( [DoesNotReturnIf(false)] bool condition);

		public static void True( [DoesNotReturnIf(false)] bool condition, string? userMessage);

                public static void NotNull( [NotNull] object? @object); // see https://github.com/dotnet/roslyn/issues/37544
}
```

This would prevent me getting warnings in the following cases:
```csharp
Assert.True(dic.TryGetValue(key, out var value));
value.DoSomething();
```

And 

```csharp
var x = GetX();
Assert.NotNull(x);
x.DoSomething();
```

**Comment by pier2013** [comment]
Regarding to

> ```cs
>                 public static void NotNull( [NotNull] object? @object); // see https://github.com/dotnet/roslyn/issues/37544
> ```

Asserting _NotNull_ on argument parameter _@object_ is not correct as it simply shifts the warning in the wrong place:

```cs
    var ctor = MethodToTest();

    Assert.NotNull(ctor);

    var data = ctor.Invoke(null); // currently the warning is here
```
With the proposed change, you end up with two warnings:

```cs
    var ctor = MethodToTest();

    Assert.NotNull(ctor); // here you have that ctor is possibly null (and of course, we are testing that)

    var data = ctor.Invoke(null); // also you get the warning here
```

Unfortunately, there is not a way to tell "does not return when null", but only "does not return when boolean is true/false" via the DoesNotReturnWhenAttribute.

**Comment by yaakov-h** [comment]
@pier2013 I'm not seeing the behaviour that you describe about shifting the warning. This compiles for me with no warnings:

```csharp
#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;

public static class C
{
    public static void Main()
    {
        var ctor = MethodToTest();
        Assert.NotNull(ctor);
        ctor.Invoke();
    }

    public static Action? MethodToTest() => null;
}

public static class Assert
{
    public static void NotNull([NotNull] object? o)
    {
        if (o is null) throw new InvalidOperationException("It was null!");
    }
}
```

**Comment by pier2013** [comment]
@yaakov-h You are right.

I have just recompiled the sample code, and that works as expected (no warning is raised). I did several sdk changes and VS updates in the meantime hence am I no longer sure to have correctly extracted the sample from my application.

**Comment by drewnoakes** [comment]
A potential fix for this issue exists in two complementary PRs:

- https://github.com/xunit/xunit/pull/2044
- https://github.com/xunit/assert.xunit/pull/36

**Comment by RehanSaeed** [comment]
Any ideas when this feature is likely to get released? Looks like v3 will take a while to get here.

**Comment by bradwilson** [comment]
If you want to pull in the (currently alpha) v3 asserts, they should work along-side the v2 core library. Add the [v3 MyGet Alpha feed to your nuget.config](https://xunit.net/docs/v3-alpha#myget-feed), and then swap out the `xunit` package for `xunit.core`, `xunit.analyzers`, and `xunit.v3.assert`. Just a warning, though, that `Assert.Skip` and friends will actually show up as failures, since that requires core changes to work.

nuget.config:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="myget-xunit" value="https://www.myget.org/F/xunit/api/v3/index.json" />
    <add key="nuget" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.7.1" />
    <PackageReference Include="xunit.analyzers" Version="0.10.0" />
    <PackageReference Include="xunit.core" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3.assert" Version="0.1.0-pre.334" />
  </ItemGroup>
</Project>
```

test:
```csharp
using Xunit;

public class UnitTest1
{
    [Fact]
    public void BadUseOfNull()
    {
        string? x = null;

        Assert.Equal("foo", x.ToString());
    }

    [Fact]
    public void GoodUseOfNullability()
    {
        string? x = null;

        Assert.NotNull(x);  // Tells the compiler that x can't be null
        Assert.Equal("foo", x.ToString());
    }

    [Fact]
    public void DynamicSkipWillFail()
    {
        Assert.Skip("This will end up as a failure");
    }
}
```

![image](https://user-images.githubusercontent.com/16944/112209904-3ea28580-8bd7-11eb-9039-5e5313421df4.png)

![image](https://user-images.githubusercontent.com/16944/112209937-4b26de00-8bd7-11eb-9410-fca3a419b811.png)

![image](https://user-images.githubusercontent.com/16944/112210180-a062ef80-8bd7-11eb-8617-61ba0424e6cb.png)
