### ISSUE TITLE
Visual Studio 2019, .NET Framework 4.5 is not working.

### ISSUE THREAD

**Issue by powerumc** [xunit/xunit#2012]
In the visual studio 2019, .NET Framework 4.5 xunit project is not working.

Test explorer screenshot.
![image](https://user-images.githubusercontent.com/1943755/65223996-3eff2380-dafd-11e9-8b07-25609e8b39f3.png)

Solution explorer screenshot.
- `xunittest` : .NET Framework 4.7.2
- `xunittest_net45` : .NET Framework 4.5

![image](https://user-images.githubusercontent.com/1943755/65224115-81286500-dafd-11e9-8f22-e17d8d6e66d4.png)

`xunit.execution.dotnet` assembly is .net standard library based in .NET Framework 4.5 project.
Is that bug?

**Comment by bradwilson** [comment]
This is not a bug. The minimum supported version of .NET Framework is 4.5.2.

**Comment by powerumc** [comment]
@bradwilson Thanks~ 😄

**Comment by HuoYingCunCunZhang** [comment]
韩国程序员，吼吼吼！Korean Programmer houhou! 查到了
