### ISSUE TITLE
Nuget package license file link does not work

### ISSUE THREAD

**Issue by vDiBo** [xunit/xunit#2022]
With change 3a40411e1fa3066f84065b35d2f7865b199666a2 (2019/09/28) the license file link in the nuget package does not work anymore.
Can be reproduced by opening https://www.nuget.org/packages/xunit/ and clicking on "License info".
This leads to a failure in any automated license check process.

**Comment by josteink** [comment]
Can reproduce. Until a new version is published, the link will remain non-functional. 

Currently the link points to master. Would it make sense in the future to link to a specific revision to avoid other errors like this?

**Comment by vDiBo** [comment]
> Can reproduce. Until a new version is published, the link will remain non-functional.
> 
> Currently the link points to master. Would it make sense in the future to link to a specific revision to avoid other errors like this?

Linking to a specific version would really help for the future.
Thanks for reintroducing license.txt

**Comment by vDiBo** [comment]
Any news on this issue?

**Comment by bradwilson** [comment]
This has been resolved.
