### ISSUE TITLE
Feature Request: Support C# 8.0 Nullable Reference Types

### ISSUE THREAD

**Issue by hannahchan** [xunit/xunit#2033]
I'm currently experimenting with C# 8.0 and Nullable Reference Types. One of the things that currently annoy me when writing unit tests with Nullable Reference Types is how the complier doesn't complain about code like this.

```
Exception exception = Record.Exception(() => SomeCode());
```

The complier doesn't complain about this because static method signature for Record.Exception() doesn't indicate that it can return a null. There may be other areas in the Xunit code base that do this as well and makes for a confusing experience when writing unit tests in C# 8.0 with Nullable Reference Types.

To be fair I can only come up with this example right now. I believe C# 8.0 and Nullable Reference Types is out of preview now.

**Comment by jherby2k** [comment]
Also, in a semi-separate issue, data driven tests fail if you try to use `object[]?` (pretty useful if you have null values for some fields):

> error xUnit1019: MemberData must reference a data type assignable to 'System.Collections.Generic.IEnumerable<object[]>'. The referenced type 'System.Collections.Generic.IEnumerable<object?[]>' is not valid.

**Comment by drewnoakes** [comment]
@jherby2k your issue is tracked in #1897.

**Comment by drewnoakes** [comment]
Another use case for annotating xunit is this code:

```c#
string? foo = CanReturnNull();

Assert.NotNull(foo);

foo.ToUpper(); // warns here that foo can be null
```

If `NotNull` was annotated, it would "teach" to analysis that the reference cannot be null after that point.

**Comment by drewnoakes** [comment]
I filed two PRs that should how this could be implemented and am happy to discuss and develop them further, assuming there's interest from the project leads on this request and the PRs' direction.

**Comment by bradwilson** [comment]
I think this may be completed now, including these two commits:

https://github.com/xunit/assert.xunit/commit/726e48276895ecba39468990809664948113d876
https://github.com/xunit/assert.xunit/commit/5f57de068917110b61b9f7cee614a5e354704271

I ended up catching a bunch more cases when I turned nullability on for the assertion library and all of the unit tests. Let me know if you think any of the annotations are incorrect now.

**Comment by drewnoakes** [comment]
I took a bit of a look through and left some comments. Lots of unrelated changes in there made the diff hard to read.

**Comment by bradwilson** [comment]
Unfortunately, a significant amount of the changes in the assertion library in particular are there in order to support people who are consuming the library via source, without support for C# 8.

**Comment by drewnoakes** [comment]
I commented about a change of behaviour with double that is worth looking at IMO.

**Comment by bradwilson** [comment]
I changed double to use Object.Equals:

https://github.com/xunit/assert.xunit/blob/3af483c3e851ef4f463a8ce8b9399b7bc8ab4dc0/EqualityAsserts.cs#L60
https://github.com/xunit/assert.xunit/blob/3af483c3e851ef4f463a8ce8b9399b7bc8ab4dc0/EqualityAsserts.cs#L163

**Comment by drewnoakes** [comment]
What was the rationale? `Object.Equals` and `operator==` have different behaviour for `System.Double`. The latter uses the IEEE definition of equality.

**Comment by bradwilson** [comment]
I was following the guidance of your comment:

![image](https://user-images.githubusercontent.com/16944/88006529-b3f60d80-cac0-11ea-8b27-678547f8961e.png)

Did I misinterpret what you said?

**Comment by drewnoakes** [comment]
Oh sorry, no I just confused myself. Yes I think this behaves as you would expect now, and preserves behaviour.
