### ISSUE TITLE
Having a "not found" issue with Xunit while using Microsoft.Data.SQLite 3 and SQLitePCLRaw 2 on net4x

### ISSUE THREAD

**Issue by Crono1981** [xunit/xunit#2037]
I'm trying to use an in-memory SQLite database for testing purposes. Therefore, following on what I've gathered here and there on the web, I created a Xunit test project that uses `Microsoft.Data.SQLite` and `SQLitePCLRaw.bundle_green` nugets.

Up to v2 of SQLite and v1.x of SQLitePCLRaw, I didn't have any issues. However, since SQLite v3 and PCL v2, I can't make anything work.

As soon as I try to create a connection instance, I get an `Exception` thrown at me with the message: "not found", with the following stack trace:

```
Stack Trace: 
    SqliteConnection.ctor(String connectionString)
    InMemory.CreateConnection() line 81
    UnitTest1.Test1() line 15
    ----- Inner Stack Trace -----
    RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
    RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
    RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    BundleInitializer.Initialize()
    SqliteConnection.cctor()
    ----- Inner Stack Trace -----
    NativeLibrary.Load(String libraryName, Assembly assy, Int32 flags)
    Batteries_V2.MakeDynamic(String name, Int32 flags)
    Batteries_V2.DoDynamic_cdecl(String name, Int32 flags)
    Batteries_V2.Init()
```

On trying to find the issue, I created dummy test projects in Xunit, nUnit and MSTest, as well as a console project. I also target both `net48` and `netcoreapp3.0` in every project.

As it turns out, the issue occurs **only when the code runs within Xunit test engine**, on .NET 4.x (works with dotnet core). In every other scenario, everything works as expected. Therefore I find it hard to think that this is a SQLite issue more than a Xunit issue.

The code can be found here:

https://github.com/RosairePion/wonderland-csharp-sqlitepclraw

Can anybody give me a clue about what's happening? Is Xunit using SQLite internally thus causing conflicts at runtime, or something like that?

Thanks.

**Comment by bradwilson** [comment]
What runner are you using to run the net48 tests?

**Comment by bradwilson** [comment]
>Is Xunit using SQLite internally

No.

**Comment by Crono1981** [comment]
> What runner are you using to run the net48 tests?

I just tried with

```
dotnet test
```

I get the same result using Visual Studio 2019 Test Explorer, although I believe it uses the same tool behind the scenes. Not sure though.

**Comment by bradwilson** [comment]
I did a few tweaks to get it to build & run on Linux, and it seems to be okay here:

![image](https://user-images.githubusercontent.com/16944/67034865-5a922580-f0cd-11e9-91d6-9e773c344070.png)

Two things I did that might help you on Windows is (a) using the latest packages, and (b) turning off app domains:

```diff
diff --git a/XUnit.Tests/XUnit.Tests.csproj b/XUnit.Tests/XUnit.Tests.csproj
index a87c6ee..272205a 100644
--- a/XUnit.Tests/XUnit.Tests.csproj
+++ b/XUnit.Tests/XUnit.Tests.csproj
@@ -9,12 +9,16 @@

   <ItemGroup>
     <PackageReference Include="FluentAssertions" Version="5.9.0" />
-    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.2.0" />
-    <PackageReference Include="xunit" Version="2.4.0" />
-    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
-    <PackageReference Include="coverlet.collector" Version="1.0.1" />
+    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.3.0" />
+    <PackageReference Include="xunit" Version="2.4.1" />
+    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1" />
+    <PackageReference Include="coverlet.collector" Version="1.1.0" />
     <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="3.0.0" />
     <PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.0.1" />
   </ItemGroup>

+  <ItemGroup>
+    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
+  </ItemGroup>
+
 </Project>
diff --git a/XUnit.Tests/xunit.runner.json b/XUnit.Tests/xunit.runner.json
new file mode 100644
index 0000000..fe9659a
--- /dev/null
+++ b/XUnit.Tests/xunit.runner.json
@@ -0,0 +1,4 @@
+{
+    "$schema": "https://xunit.net/schema/current/xunit.runner.schema.json",
+    "appDomain": "denied"
+}
```

**Comment by Crono1981** [comment]
Oh wait. Sorry, that's the same test failing but with a different message. I'll look into it and come back right at you.

**Comment by bradwilson** [comment]
What if you swap:

```
"appDomain": "denied"
```

for:

```
"shadowCopy": false
```

?

**Comment by Crono1981** [comment]
Yep, now test runs as expected using both the command line and the GUI. Updated the repo too.

Can you provide some insights on what the issue was and how `shadowCopy` solved it? That would be very much appreciated.

**Comment by bradwilson** [comment]
So, app domains (on by default for net4x code) basically isolate your test code from the runner code. One benefit that it brings is that it sets a different load _context_ for dependencies, which includes not only which is the default directory from which assemblies will be loaded, but also some configuration items that are dependent on an app domain (like binding redirects, to inform the system how to resolve incompatible verisons of assemblies).

Turning off app domains tends to be my first try when fixing strange issues. If that doesn't work (because something in the above description is required), then my next go-to is disabling shadow copying. Shadow copying is a process whereby the assemblies are being loaded/executed are actually silently copied into a separate folder and loaded from there, to prevent file locks on the original assemblies on disk. This _usually_ works fine, but it can have some oddities with unmanaged code, since the shadow copy system provided by .NET is purely for managed code.

Given that it's now working, my guess is that the SQLite assemblies include some unmanaged code that was having problems loading.

**Comment by Crono1981** [comment]
> Given that it's now working, my guess is that the SQLite assemblies include some unmanaged code that was having problems loading.

But isn't the issue with unmanaged code not loading more likely to happen when Xunit *is* using shadow copies?

> (...) but it can have some oddities with unmanaged code, since the shadow copy system provided by .NET is purely for managed code.

Sorry, I'm just trying to make sure I'm not replacing one problem with a potential new one here. :)

**Comment by Crono1981** [comment]
Turns out that the author of SQLitePCLRaw uses your exact workaround. :D

Many thanks for your amazing support, @bradwilson . It is very appreciated.

**Comment by bradwilson** [comment]
Happy you're up and running!

**Comment by AlexBeyd** [comment]
Experienced same issue just now. After opening test project file for editing, found the below group, deleted it. Then it started to work:
`  <ItemGroup>
    <None Remove="Assets\myfile.txt" />
  </ItemGroup>`
