### ISSUE TITLE
XUnit Class Fixture (IClassFixture) is being executed twice

### ISSUE THREAD

**Issue by onkarjit** [xunit/xunit#2038]
```
public class TestFixture : IDisposable
    {
        public TestFixture()
        {
            var options = new ChromeOptions();
            options.AddExcludedArgument("enable-automation");
            options.AddAdditionalCapability("useAutomationExtension", true);
            WebDriver.Init("https://localhost:44335/", Browser.Chrome, options);
            WebDriver.GetDriver.Manage().Window.Maximize();
        }

        public void Dispose()
        {
            WebDriver.Close();
        }
    }
```

```
    public abstract class Test : IClassFixture<TestFixture>
    {

    }
```

```
    public abstract class AuthTest : Test
    {
       [Fact, Priority(-1)]
        public void LoginTest()
        {
            var home = GetPage<HomePage>();
            home.LoginModal.Open();
            home.LoginModal.EnterLoginText(new Login("username", "pw"));
            home.LoginModal.Login();
            GetPage<DashboardPage>().IsAt();
        }
    }
```

```
   [TestCaseOrderer(PriorityOrderer.Name, PriorityOrderer.Assembly)]
    public sealed class HomeTest : AuthTest
    {

    }
```

```
    [TestCaseOrderer(PriorityOrderer.Name, PriorityOrderer.Assembly)]
    public sealed class ProfileTest : AuthTest
    {
        [Fact, Priority(0)]
        public void OpenProfilePageTest()
        {
            var profile = GetPage<ProfilePage>();
            profile.GoTo();
            profile.IsAt();
        }
        [Fact, Priority(1)]
        public void LogoutTest() => GetPage<DashboardPage>().Logout();
        
    }
```

A few days ago I wrote this code and it used to create 1 browser instance. I started the project today again and now suddenly the fixture gets executed twice and it opens two seperate browsers (which causes my tests to fail). I thought the `IClassFixture` was supposed to only execute once like `[OneTimeSetUp]` attribute in NUnit. Why is my fixture executing twice?

This happens when I run all tests (all tests runs`ProfileTest` and `HomeTest`). If I run for example one of the two tests individually, then just 1 browser instance opens and the test passes.

I'm using XUnit 2.4.0.

**- EDIT -**

When I use:

VS 2019 (run all tests): It opens 2 browsers at same time and fails.<br>

VS 2019 (debug all tests): It opens 2 browsers at same time and fails.<br>

Jetbrain's Rider IDE (run all tests): It opens 2 browsers at same time and fails.<br>

Jetbrain's Rider IDE (debug all tests): It opens 1 browsers till `HomeTest` finishes and then another browser for `ProfileTest` and passes.<br>

This last is how it is supposed to be and used to be when I used NUnit before.

**Comment by bradwilson** [comment]
The class fixture is always being created twice, even in your "desired" behavior (Rider debug). That's not the problem. Your issue seems to be the default parallelism that's causing two separate test classes to run tests at the same time, thus causing the two separate windows to show at the same time.

What you need to do is put all of your browser-wielding classes into a Test Collection, as documented here: https://xunit.net/docs/running-tests-in-parallel#parallelism-in-test-frameworks

**Comment by onkarjit** [comment]
@bradwilson indeed decorating the `Test` class with `[Collection("Browser Collection")]` solved the issue for me. But how does it work? Does decorating it with that attribute tell it that it should not be ran in parallel?

**Comment by bartelink** [comment]
@onkarjit Yes - see the article Brad linked to (for more examples, the ['sharing context' article to which it links might also enhance your understanding](https://xunit.net/docs/shared-context.html)

**Comment by bradwilson** [comment]
Seems resolved, so closing.
