### ISSUE TITLE
Feature Request: xunit.analyzers - Test must have at least one Assert

### ISSUE THREAD

**Issue by fmicle** [xunit/xunit#2039]
It would be nice to have a rule that requires all test methods to have Asserts.

**Comment by chrisaut** [comment]
I don't agree...sometimes I have tests that just "assert" that no exception is thrown.

These tests do not have any explicit assert statements.

**Comment by fmicle** [comment]
How do you check for exceptions? Assert.Throws<>(), similar to a regular assertion Assert.IsTrue(). The rule can simply check for "Assert." in the test method implementation and cover both cases. Junior developers at my job have written tests that do Debug.WriteLine() and don't make any assertions, and I would like to prevent that in the future.

**Comment by chrisaut** [comment]
I check for absent of exceptions. For example to check if a constructor can handle null values without throwing.

Assert.DoesNotThrow was removed from v2 (was in v1) be wise this is the idiomatic way to "assert" for absent of exceptions.

Adding a pointless Assert.True or similar is white useless IMO.

**Comment by lxconan** [comment]
I think is good to explicitly specify what do you want to verify in the test. So, the meaning of

```
var _ = new SomeType(null);
```

is quite different from

```
Assert.DoesNotThrow(() => new SomeType(null));
```

**Comment by bradwilson** [comment]
After consideration, based on reactions from the community with analyzers that do not take into account third party extensions, I don't think this is a good idea. It will anger users who use third party assertion libraries, which are the by-far most used extensions to xUnit.net.

**Comment by voronoipotato** [comment]
Is there any way to know if tests didn't assert anything?

**Comment by bradwilson** [comment]
From within an analyzer, you could inspect all the code in the test method to look for any references to `Assert`.
