### ISSUE TITLE
Cannot install xunit package in VS2013: "Child dependencies of dependency only packages cannot mix external and project packages."

### ISSUE THREAD

**Issue by fhaag** [xunit/xunit#2042]
I am trying to install the [`xunit` NuGet package](https://www.nuget.org/packages/xunit/) into a fresh .NET 4.6.1 console project.

In Visual Studio 2017, this works flawlessly.

In Visual Studio 2013, I am getting the following output (the last line indicating a failure of the operation):

```
Attempting to resolve dependency 'xunit.core (= 2.4.1)'.
Attempting to resolve dependency 'xunit.extensibility.core (= 2.4.1)'.
Attempting to resolve dependency 'xunit.abstractions (≥ 2.0.3)'.
Attempting to resolve dependency 'xunit.extensibility.execution (= 2.4.1)'.
Attempting to resolve dependency 'xunit.assert (= 2.4.1)'.
Attempting to resolve dependency 'xunit.analyzers (≥ 0.10.0)'.
Child dependencies of dependency only packages cannot mix external and project packages.
```

Our general development is done in VS2013. Is this somehow still supported, or do I have to edit our package collection project in VS2017 in order to get the xUnit package in?

(The question template asks me to provide a sample project, but in this case, the sample project would really just be empty console project as generated from the VS template.)

**Comment by bradwilson** [comment]
Sorry, 2013 is not supported any more.

That said, you might be able to get it to work by installing `xunit.core` and `xunit.assert` instead of `xunit`, which will avoid the analyzers dependency.

**Comment by SimonCropp** [comment]
@bradwilson perhaps time to close?
