### ISSUE TITLE
xUnit class constructor should get arguments passed from theory test methods

### ISSUE THREAD

**Issue by onkarjit** [xunit/xunit#2047]
```
public class ProfileTest : AuthTest
{
    [Theory, Priority(0)]
    [Roles(Role.Editor, Role.Viewer)]
    public void OpenProfilePageTest(Role role)
    {
        AuthRepository.Login(role);
        var profile = GetPage<ProfilePage>();
        profile.GoTo();
        profile.IsAt();
    }
}
```

```
public abstract class AuthTest : Test, IDisposable
{
    public void Dispose()
    {
        GetPage<DashboardPage>().Logout();
    }
}
```

Since xUnit creates a new instance of the test class for every test that is run. I would be nice if Theory tests decorated with attributes would pass their parameters as arguments to the constructor.

So in the code above, I wouldn't need to put `AuthRepository.Login(role);` in every test method that has the `[Roles(Role)]` attribute. Rather I could put it in a constructor that takes `Role` as a argument and invoke  `AuthRepository.Login(role);` from there.

**Comment by onkarjit** [comment]
@bradwilson is something like this currently possible? 

```
public class ProfilePageTest
{
    public ProfilePageTest(Role role) 
    {
        AuthRepository.Login(role)
    }

    [Theory]
    [Roles(Role.Editor, Role.Viewer)]
    public void OpenProfilePageTest(Role role)
    {
        AuthRepository.Login(role);
        var profile = GetPage<ProfilePage>();
        profile.GoTo();
        profile.IsAt();
    }
}
```

The constructor should get a parameter from the theory method, the theory method should pass that argument to the constructor.

**Comment by mthamil** [comment]
I kind of like this idea, but I think I'd rather the attributes be placed at the class level as a form of class fixture or something.

**Comment by bradwilson** [comment]
This isn't possible today, but I'm here (on live stream :-p) and this sounds like it might be similar in design to #2050. Maybe putting theory data at the class level would be combined with constructor injection support?

**Comment by onkarjit** [comment]
@bradwilson it would be great if it could be combined with the constructor injection support

**Comment by psxvoid** [comment]
For visibility adding a reference to a comment in another topic, probably related to this one as well (duplicate?): https://github.com/xunit/xunit/issues/2050#issuecomment-2385360513

**Comment by bradwilson** [comment]
Test method arguments are available in the test class constructor now, through the test context:

![image](https://github.com/user-attachments/assets/8f3716e3-4802-4e88-bdc1-caa1b969af20)

**Comment by bradwilson** [comment]
Not sure if I should mark this "fixed" or "won't fix" since it's not constructor injection. 😁

**Comment by psxvoid** [comment]
That is good enough at least for me, thanks!

> Not sure if I should mark this "fixed" or "won't fix" since it's not constructor injection. 😁

Me neither. It's probably not the cleanest way due to necessity of "wiring" and static nature, but it allows to achieve the desired results. And if it works with parallel scenarios as well, making it "clean" might be left as an improvement for the future releases. 😁

**Comment by bradwilson** [comment]
> making it "clean" might be left as an improvement for future releases.

Mixing constructor argument sources dramatically escalates the confusion and possibility for mistakes. This pretty much guarantees we will never provide anything to constructor arguments other than fixtures (and the very limited known types that we will inject, like `ITestOutputHelper`).
