### ISSUE TITLE
Assert.Equal result unclear, with string with differing trailing spaces

### ISSUE THREAD

**Issue by brewmanz** [xunit/xunit#2049]
When comparing equality between "" and " "
`Assert.Equal("", " ");`
 the result is an unclear
`Assert.Equal() Failure
          ↓ (pos 0)
Expected: 
Actual:    
          ↑ (pos 0)
`
Consider A) mentioning string lengths, B) using some fancy unicode characters for string pre-start & post-end e.g. '«' & '»'

**Comment by bradwilson** [comment]
The new assertion library in 2.5.0 (currently in prerelease) fixes this:

```
Repro2049.TestMethod [FAIL]
  Assert.Equal() Failure: Strings differ
  Expected: ""
  Actual:   " "
             ↑ (pos 0)
```

There are two improvements here:

(a) it wraps string values in quotes, so spaces don't go unnoticed
(b) overruns don't include pointers (notice no pointer for Expected)
