### ISSUE TITLE
Shared output + test output

### ISSUE THREAD

**Issue by lobster2012-user** [xunit/xunit#2053]
Hi!
There are 2 problems.
1. I start up the ``dotnet test``, I see first the general logs(from shared classfixture), and then from the test. Not sure how to see them in sequential order.

2. In VS, I would like to see general logs + logs from the test. I think that this is not possible. Would anyone else be interested in this?

**Comment by fschwiet** [comment]
2 sounds interesting to me.  I'd like to show CollectionFixture execution times, since the UI doesn't seem to show it.  Haven't found a way to log a stopwatch result from the ICollectionFixture implementation as a work-around.

**Comment by bradwilson** [comment]
I don't think this is behavior that belongs to us, but rather to the [VSTest](https://github.com/microsoft/vstest/) project.
