### ISSUE TITLE
Facts with DisplayName shown as separate child node

### ISSUE THREAD

**Issue by fhaag** [xunit/xunit#2054]
*(I hope this is the right tracker for this issue. Things are a bit confusing, with the [`resharper-xunit` project](https://github.com/xunit/resharper-xunit) being archived and thus apparently inactive, and the [`visualstudio.xunit` project](https://github.com/xunit/visualstudio.xunit) (whose assembly appears to be responsible for ReSharper detecting and running my tests on my machine) indicating that issues specific to the VS runner should be logged on the main xUnit project's issue tracker.)*

By default, the test case tree in ReSharper's "Unit Test Sessions" shows each class as a tree node, and each method annotated with a `[Fact]` attribute therein as a leaf below the class tree node. That leaf represents the test case and, while selected, the details area shows the full test output.

When I assign a human-friendly name to one of those test cases by means of the `DisplayName` attribute, I would expect that the method name in the tree is replaced with the human-friendly name. Instead, the method name node gets a new child node:

Code:

```c#
public class MyTests
{
	[Fact]
	public void UnnamedTest()
	{
	}

	[Fact(DisplayName = "It works.")]
	public void NamedTest()
	{
	}
}
```

Resulting tree:

![excerpt of Unit Test Sessions tree](https://user-images.githubusercontent.com/1283543/69335402-2de9a480-0c5d-11ea-9d28-d8f051ac64ab.png)

Especially with many test cases, this makes it rather cumbersome to use the tree, as clicking the method nodes themselves does not display the test output anymore, and the fully expanded tree looks quite cluttered.

I do not know whether there are any situations where a single test method could be represented by different display names - maybe when using several theories or so - but as long as the test case is simply given a readable `DisplayName` value on its `[Fact]` attribute and there is nothing else to multiply the test case, could this be changed so the method node itself bears the readable name?

**Comment by bradwilson** [comment]
We don't control this display. Please open an issue with the VSTest team, as they own this Test Explorer UI.
