### ISSUE TITLE
Feature Request: PlatformSpecificAttribute

### ISSUE THREAD

**Issue by am11** [xunit/xunit#2057]
.NET runtime tests are using an elegant `[PlatformSpecific]` attribute [e.g.](https://github.com/dotnet/runtime/search?q=PlatformSpecific&unscoped_q=PlatformSpecific):

```c#
[Fact]
[PlatformSpecific(TestPlatforms.Windows)]
```

Since the use-cases of this attribute are wide-spread (basically any cross platform project is a candidate), please consider providing it out of the box, either by including it in xUnit core or an extensions package. Thanks!

---
Related:

The implementation of `PlatformSpecificAttribute` resides in dotnet/arcade repo:

* [PlatformSpecificAttribute](https://github.com/dotnet/arcade/blob/b902fd6b6948e689a5128fa6d94dc7de13e6af84/src/Microsoft.DotNet.XUnitExtensions/src/Attributes/PlatformSpecificAttribute.cs)
  * uses [XunitConstants](https://github.com/dotnet/arcade/blob/b902fd6b6948e689a5128fa6d94dc7de13e6af84/src/Microsoft.DotNet.XUnitExtensions/src/XunitConstants.cs)
* [PlatformSpecificDiscoverer](https://github.com/dotnet/arcade/blob/b902fd6b6948e689a5128fa6d94dc7de13e6af84/src/Microsoft.DotNet.XUnitExtensions/src/Discoverers/PlatformSpecificDiscoverer.cs)
  * uses [TestPlatforms](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.XUnitExtensions/src/TestPlatforms.cs)

And the trait values are set via msbuild, e.g.: https://github.com/dotnet/runtime/blob/743dc49e/src/installer/test/Directory.Build.props#L15-L23.

**Comment by prezaei** [comment]
I love this idea!

**Comment by bradwilson** [comment]
In v3, we've added `Assert.Skip`, `Assert.SkipWhen` and `Assert.SkipUnless` which can also be used for this. For example:

https://github.com/xunit/xunit/blob/e3e12e8a2db8f40b26f39f0fd6c463e8b04e6057/src/xunit.v3.core.tests/Common/SerializationHelperTests.cs#L43-L51

**Comment by bradwilson** [comment]
After consideration, I think this is something that is better done with dynamic skipping. The explosion of potential vectors for skipping is effectively infinite (it's just OS in this request, but you can imagine many more). Attributes don't feel like a good way to achieve this, especially for users to depend on us to write the ones they need.

So I'm going to close this as a Won't Fix.
