### ISSUE TITLE
dotnet test failed integration test after new .net core sdk installed 

### ISSUE THREAD

**Issue by SaeidSabzalizadeh** [xunit/xunit#2066]
Here is my xunit test project:

```xml
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

 <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.1.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />
    <PackageReference Include="moq" Version="4.12.0" />
    <PackageReference Include="xunit" Version="2.4.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
  </ItemGroup>
```

All was good up until I installed .NET Core 3.1 SDK, now all my integration tests failed.
I checked in different machines as long as I have only .NET Core 2.1 every thing is good but by installing .NET Core 3.1 all integration tests failed. 

Is there any config I should add to my project?
It's not an option for me to upgrade my project or test project to 3.1.

**Comment by bradwilson** [comment]
Unfortunately we don't control what version of .NET Core is used to run your tests when you execute with `dotnet test`, as that is controlled by the VSTest engine (they implement the functionality behind `dotnet test` as well as the Visual Studio Test Explorer). As I understand it, they do attempt to use the runtime that you specify in your `<TargetFramework>` for your project, so I'm surprised that simply installing 3.1 when you're compiled against 2.1 gives this problem.

The VSTest project is here: https://github.com/microsoft/vstest/

**Comment by SimonCropp** [comment]
@SaeidSabzalizadeh can u share a repro solution? or some stack traces?

**Comment by bradwilson** [comment]
Please re-open with a repro project if this is not solved.
