### ISSUE TITLE
xUnit exceptions are not serializable.

### ISSUE THREAD

**Issue by alexander-nesterenko-kas** [xunit/xunit#2067]
`Type 'Xunit.Sdk.AssertActualExpectedException' in assembly 'xunit.assert, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' is not marked as serializable.`

**Comment by bartelink** [comment]
This is true. Can you expand as to why this is a concern? (from what I know this is no accident; it's a fundamental part of the design)

**Comment by alexander-nesterenko-kas** [comment]
I have tests for testing behaviors and several tests for testing the case by using my library from different Web Applications hosted inside one Application Pool. I have a test in "main" AppDomain that creates several "test" AppDomains and runs test cases there, and I need to rethrow exceptions from a "test" AppDomain into ''main" AppDomain.

**Comment by bartelink** [comment]
I suspected that... given AppDomains have not made it into proposals for .NET 5, I'd say supporting them in xUnit is [highly unlikely to make sense](https://gist.github.com/stuartd/a100fb315f2e5ca9ed17551d8b538a60), but I'm not the authority...

**Comment by alexander-nesterenko-kas** [comment]
I will try to push PR with the changes for fixing this issue.

**Comment by bradwilson** [comment]
@bartelink is correct: app domains are not in .NET 5, and we've removed app domain support from xUnit.net v3 as well.
