### ISSUE TITLE
Add CodeFixProvider to implement IClassFixture constructor

### ISSUE THREAD

**Issue by chinwobble** [xunit/xunit#2068]
# Summary
It would be nice if there was a code fix provider to generate the constructor and fields to access class fixture data. The documentation on IClassFixture states that 

```
To gain access to the fixture data from inside the test, a constructor argument should be added to the test class which exactly matches the TFixture.
```

```csharp
public class TestFixture
{
    public TestFixture()
    {
        // setup some test data to be made available in the test
    }
}

public class Test : IClassFixture<TestFixture>
{
    // theories and facts removed for brevity
}
```

When I add interface `IClassFixture<TestFixture>`  we could automatically transform the code like this:
```csharp
public class Test : IClassFixture<TestFixture>
{
    private readonly TestFixture _testFixture;
    public Test(TestFixture)
    {
        _testFixture = TestFixture;
    }
    // theories and facts removed for brevity
}
```
Would you accept a pull request implementing this kind of `codefixprovider`?

**Comment by bradwilson** [comment]
Sure, that would be great.

It needs to be a combination of analyzer + code fix (because the analyzer triggering is what offers the code fix). It should probably be an Info level analysis, since it's useful as a hint but it's not necessarily wrong (aka, Warning) to fail to take the ctor argument. :)

**Comment by chinwobble** [comment]
hmm how else can the `IClassFixture<TFixture>` be used?
If I add this interface why wouldn't I add the constructor? How to I get access to the `TFixture` stuff?
