### ISSUE TITLE
Need ability to skip test programmatically

### ISSUE THREAD

**Issue by RussKie** [xunit/xunit#2073]
### Proposal:

As a user I should be able to programmatically skip a test.

There are few way how it could be achieved e.g. add the following API:
```cs
Assert.Skip(string reason);
Assert.SkipIf(bool condition, string reason); // optional

// - or -
Assert.Inconclusive(string reason);
Assert.InconclusiveIf(bool condition, string reason); // optional
```
An alternative could be handle `SkipTestException` at the xUnit level, and mark the originating method as skipped.

I personally would prefer the firs approach, as it would be significantly more discoverable.

### Reason:

I am aware of `[Fact(Skip = ...)]` and [`SkippableFactAttribute`](https://github.com/xunit/samples.xunit/blob/5de2967b340877a29d64b087c37a5bbc159651a4/DynamicSkipExample/Samples.cs) however they don't work in all scenarios. I am also aware of https://github.com/xunit/xunit/issues/1676 but in my opinion  @bradwilson's reasons fall short of explaining why this feature is not appropriate.

Windows Forms team must run pretty much all tests in STA, because we test UI controls. For this reason we can't use `FactAttribute`, and use @AArnott's [Xunit.StaFact](https://github.com/AArnott/Xunit.StaFact) library which extends the xUnit. This library offers a number of different attributes, such as `StaFact`, `WinFormsFact`, `WpfTheory` etc.
@AArnott also has a library that provides the ability to skip tests at runtime - [Xunit.SkippableFact](https://github.com/AArnott/Xunit.SkippableFact). However we can't use it either for the reasons outlined above.
Whilst we can ask Andrew to add a support for skippable facts to his StaFact library, it is not a sustainable approach, there will have to be many permutations for Sta*, WinForms*, Wpf* and whatever else attributes.

We now have a [situation in WinForms repo](https://github.com/dotnet/winforms/pull/2889#issuecomment-591190601) where we must check whether a specific Windows capability is installed before we may continue with a test. We can do that check as part of running a test, and if a capability is not detected, we need to skip the test.

Right now I can see no way of achieving the desired, other than exiting the test. This way the test won't fail, but it will be marked it as "success", which it's not.

### Example:

Here's an example:

```cs
        [WinFormsFact]
        public void WebBrowser_AttachInterfaces_Invoke_Success()
        {
            object nativeActiveXObject = null;

            try
            {
                Type t = Type.GetTypeFromCLSID(new Guid("0002DF01-0000-0000-C000-000000000046"));
                nativeActiveXObject = Activator.CreateInstance(t);
            }
            catch (COMException)
            {
                Assert.Skip("Windows doesn't have IE browser capability installed");
                return;
            }

			// do actual tests with the COM object
        }
```

You can check whether IE browser is installed from an elevated prompt:
```powershell
PS> Get-WindowsCapability -online | ?{ $_.Name.StartsWith('Browser.InternetExplorer') }

Name  : Browser.InternetExplorer~~~~0.0.11.0
State : Installed

```
Add/remove:
```powershell
dism /online /Add-Capability /CapabilityName:Browser.InternetExplorer~~~~0.0.11.0
dism /online /Remove-Capability /CapabilityName:Browser.InternetExplorer~~~~0.0.11.0
```

**Comment by Soundman32** [comment]
I have a similar requirement.   When testing exceptions, some of the (standard) constructors may not be implemented, or may not be public.

```
            // Arrange
            var constructorInfo = AssumeProtectedConstructor(new Type[] { typeof(SerializationInfo), typeof(StreamingContext) });
            if (constructorInfo == null)
            {
                // this test is not required
                return;
            }

```

**Comment by bradwilson** [comment]
Fixed in:
https://github.com/xunit/assert.xunit/commit/e6a6d5d22bbc7097f8decad5b3c8cac8cf3fb386
https://github.com/xunit/xunit/commit/f197cbf0b8b4be019ee095125863195e9fe15b9c

**Comment by RussKie** [comment]
Champion! Thank you

**Comment by RussKie** [comment]
@bradwilson has this been released yet?

**Comment by bradwilson** [comment]
No, this will ship as part of v3 later this year (actual date TBD)

**Comment by jzabroski** [comment]
One feedback on this feature: The way I am compiling against v3 globally, I often want to do something like the following:

```c#
[Theory]
[InlineData(false, "input1")]
[InlineData(true, "input2")]
public async Task DoIt(bool skip, string input)
{
  // Xunit3 API
  Assert.SkipIf(skip);
  // do test with input parameter
}
```

However, I _don't know ahead of time that I want to skip such tests_.  An example of this would be a parameterized PuppeteerSharp test that is working for 99% of my InlineData values, but is failing for some random report (e.g., performance issue where the web page takes longer than 30 seconds to load, and I don't want to add a timeout parameter just for one performance issue, since it masks the real problem.  At the same time, I don't want my entire test suite to bubble up as failed on this once test when I know the root cause is performance related).

So, I would edit the InlineData to add the `bool skip` paramter.  R# in turn interprets this as the previous test no longer existed, and there is a new test, because the signature of the method changed.

I'm just mentioning this here in case anyone else has a better idea on how to improve the usability here.  To be clear, _I love this new feature so much_ but this is probably the one thing that stops it from being 💯 .

**Comment by glenn2223** [comment]
Quick question. Will this feature allow all tests to be skipped if the constructor calls any skip function?

**Comment by bradwilson** [comment]
Yes, this does work from constructors.

<img src="https://user-images.githubusercontent.com/16944/109345409-f1740380-7824-11eb-9b5b-b8f2116b5913.png" width="412" />

<img src="https://user-images.githubusercontent.com/16944/109345445-018be300-7825-11eb-81db-82fde6d38582.png" width="974" />

**Comment by AraHaan** [comment]
When can we start using this? I am using the xunit myget feeds and still do not see these members in ``Assert``.

**Comment by AArnott** [comment]
@bradwilson from your doc I see that you have ".NET Core 2.1 (or later)" listed as a requirement. Since that version is already out of LTS, maybe you can make your life a bit easier by requiring netcoreapp3.1 as a minimum for the netcore side.

**Comment by AraHaan** [comment]
Honestly I feel like they should just have it require .NET 5 as minimum when .NET 6 gets released in November.

**Comment by AArnott** [comment]
Supporting all versions under LTS will reach many more users. Sure, customers can test under a newer runtime, but if _their_ product is expected to run under netcoreapp3.1, then testing under net5.0 may not produce the same results.

**Comment by RussKie** [comment]
.NET Core 3.1 is supported until Dec 22, whilst .NET 5.0 is until May 22.
https://dotnet.microsoft.com/platform/support/policy

**Comment by goncalo-oliveira** [comment]
Any chance this gets released with v2? It would be really helpful to be able to skip tests that can't run on a particular environment and v3 seems somewhat stalled?

**Comment by AArnott** [comment]
@goncalo-oliveira Can you use the `xunit.skippablefact` package for now?

**Comment by justinmchase** [comment]
I am trying to just do `Assert.Skip(true)` and its not even compiling. I am using version `2.8.1` and that appears to be the latest version of xunit, what am I missing?

![image](https://github.com/xunit/xunit/assets/10974/31bd3700-a52b-4a38-86ee-0f676a5fdcc1)

**Comment by AArnott** [comment]
@justinmchase see https://github.com/xunit/xunit/issues/2073#issuecomment-673632823. It is only available in v3 (which... didn't ship when the author thought it would evidently).

**Comment by AraHaan** [comment]
I feel like there should be a silent fail option too where it acts like cpython'x ``xfail`` where it's basically a failure, but one that is essentially where if it passes great, but if it fails ignore the failure entirely.

**Comment by DennisDyallo** [comment]
Any updates? The case is closed but the proposed solution is not working.

**Comment by bradwilson** [comment]
> Any updates? The case is closed but the proposed solution is not working.

Are you using v3?

**Comment by MovGP0** [comment]
Skip is not the same meaning as Inconclusive:

- Skip means that the test is not executed because it does not apply (e.g. when the test is plattform-specific)
    - Test is Grey
- Inconclusive means that something went wrong with the test setup, so the test failed but does not tell you what the error is
    - Test is Yellow

**Comment by bradwilson** [comment]
> Skip is not the same meaning as Inconclusive

I'm not sure what this is in response to.

Skipped tests in xUnit.net v3 (whether skipped statically or dynamically) are reported as Skipped, not as Inconclusive.

In addition, I have no idea what colors you're describing, since you didn't say anything about the test environment you're running the tests in. If you're using Visual Studio's Test Explorer and you mean that you'd prefer for skipped tests to show up as gray rather than yellow, then that's a request for the Visual Studio team, not us.

**Comment by jzabroski** [comment]
I think he was replying to the top-level request being slightly incongruent with the GitHub Issue title. The title should say "Ability to bail on test via programmatic Skip or Inconclusive API"; @MovGP0 See also https://github.com/xunit/xunit/issues/3248 - My feature request for "Expected Fails", which is a slightly different use case.
