### ISSUE TITLE
Suggestion : Need a new overload of Assert.Equal(double,double,precision,MidpointRounding)

### ISSUE THREAD

**Issue by mrjrdg** [xunit/xunit#2074]
I have a lot of problem dealing with `Assert.Equal(double,double,precision)` when testing `double` value. For exemple i can test two differents variables of type `double` that hold the same value but when make the call to the `Assert.Equal()` method i can't get a good answer because it's life if the `Math.round()` method use differents `MidpointRounding`.

```
  Error Message:
   Assert.Equal() Failure
Expected: 205.5399239087 (rounded from 205.53992390865)
Actual:   205.5399239086 (rounded from 205.53992390865)
  Stack Trace:
```

So it would be nice to provide an implementation with the `MidpointRounding` parameter.

**Comment by bradwilson** [comment]
Fixed in a3bc2d5f0ebc641d769bb1aa29a748dac269b8f8
