### ISSUE TITLE
How to distribute a package with custom Asserts?

### ISSUE THREAD

**Issue by tom-mckinney** [xunit/xunit#2077]
My typical workflow when starting a new project is to create a *testing-base* project that references `xunit.assert.source` so that I can write some custom assertions. Typically, I reference this testing-base project alongside the `xunit` package in my unit test projects to simplify project creation as well as to enable default test runner behavior. I recently tried to publish a NuGet package that consolidates many of these methods; however, this quickly failed because the compiler now perceived the type `Assert` as existing in both my package's assembly as well as the `xunit` assembly.

I understand that partial classes cannot span multiple assemblies, so this error makes sense; however, I imagine my use-case is common. Is there a way to write custom assertions (as static methods of the `Assert` class) that can be distributed as a standalone package and be used in conjunction with `xunit`?

**Comment by bradwilson** [comment]
The `xunit` package is a "meta-package" it exists solely to provide three reference:

- `xunit.core`
- `xunit.assert`
- `xunit.analyzers`

You should replace your `xunit` package reference with `xunit.core` (and add `xunit.analyzers` if you want to continue to use the Roslyn analyzers).
