### ISSUE TITLE
Test Discovery Edge Case Regarding Base Class Tests and Namespaces

### ISSUE THREAD

**Issue by bra1nDeaD** [xunit/xunit#2079]
xUnit version: 2.4.1
Runner: ReSharper

There seems to be a situation in which some tests are not scheduled to run, when IMO they should.

To reproduce you will need two classes of which one is an abstract base class of the other:

```
namespace FirstArea
{
    public abstract class SomeTestBase
    {
        protected abstract string ExpectedValue { get; }
        protected abstract string ActualValue { get; }

        [Fact]
        public void ItAllWorksOut()
        {
            Assert.Equal(ExpectedValue, ActualValue);
        }
    }
}
```

```
namespace SecondArea
{
    public class WhenItAllHappens : SomeTestBase
    {
        protected override string ExpectedValue => "Foo";
        protected override string ActualValue => "Bar";

        [Fact]
        public void SomethingElseWorksOut()
        {
            var otherActualValue = "Foo";

            Assert.Equal(ExpectedValue, otherActualValue);
        }
    }
}
```

It's important that they live in **seperate namespaces and seperate folders**.

When you run the tests for the class "WhenItAllHappens" it all works fine (in the example one should pass and the other should fail). The problem lies in when you want to run some of the tests and you right-click the namespace in the ReSharper unit test sessions window to re-run all tests under that namespace:
![image](https://user-images.githubusercontent.com/4800302/76945264-2def6d80-68fa-11ea-885b-124c25d2285e.png)

In the image when you, for example, right click "SecondArea" and run the tests that way.

What happens is that "SomethingElseWorksOut" is run, but "ItAllWorksOut" is being skipped. I suspect that this is because it's part of a different namespace, but I think it should be run anyway as it forms part of the class that is selected to run.

The workaround I currently use is to switch the grouping in the unit test session window from "Projects and Namespaces" to "Project Structure" but it would be great if one doesn't need to do that:
![image](https://user-images.githubusercontent.com/4800302/76945898-18c70e80-68fb-11ea-8606-8305754264c7.png)

When you right-click on a directory to run the tests inside, it **does** run the tests in the base class eventhough the base class itself sits outside of the directory you selected. This behaviour should work the same with namespaces.

Keep up the great work.

**Comment by bradwilson** [comment]
Sorry for not getting back to this sooner. Resharper support is provided by the JetBrains team. If you are still having issues, please open an issue against Resharper. Thanks!
