### ISSUE TITLE
[Feature request] Change xunit configuration value via msbuild properties

### ISSUE THREAD

**Issue by iron9light** [xunit/xunit#2080]
Now we have to add an xunit.runner.json file for every test projects to control the xunit configuration values.
I wish we can control configuration values in the msbuild project file.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <XUnit_MaxParallelThreads>-1</XUnit_MaxParallelThreads>
  </PropertyGroup>
</Project>
```

**Comment by bradwilson** [comment]
This is supported for the MSBuild runner (the `xunit.runner.msbuild` NuGet package) via property imports and a new target (`XunitTest`):

https://github.com/xunit/xunit/blob/56476a9691bb061661190b183733c5d8a2c6ef4d/src/xunit.runner.msbuild/build/xunit.runner.msbuild.targets#L2-L27

**Comment by iron9light** [comment]
It seems the `xunit.runner.msbuild` can not work with dotnet core. And I doubt whether it can work with `xunit.runner.visualstudio`.

Since nearly all test projects will use msbuild, supporting configuring via msbuild property should be a feature in the xunit core as the same level as `xunit.runner.json`.

**Comment by bradwilson** [comment]
This issue is a subset of #2126
