### ISSUE TITLE
Support .NET 4.8 xunit.runner.console

### ISSUE THREAD

**Issue by djonesCenterEdge** [xunit/xunit#2083]
A [nuget](https://www.nuget.org/packages/xunit.runner.console/) package generated from this project stops support at .NET 4.7.2. I would like to submit a PR to upgrade the project to 4.8. Per the contributing guidelines, I should open this up for discussion first. 

I upgrade the project by changing the project's targets and replacing various preprocessor directives and paths.

I tested the upgrade to 4.8 by taking the generated xunit.console.exe and running tests for external test projects targeting .NET 4.8. (In addition to the unit tests in the project)

Please let me know if anymore information is needed.

**Comment by bradwilson** [comment]
We are deprecating the way this running works in v3, so this change would be unnecessary.

We don't have plans to ship any further v2 versions. Does the lack of a 4.8 runner cause an issue for you with no workaround?

**Comment by djonesCenterEdge** [comment]
We're upgrading all of our projects to target .NET 4.8 to get ready for the release of .Net 5. We only use the console runner, is there a work you can provide us?

**Comment by bradwilson** [comment]
There is a version of this coming for v3: https://github.com/xunit/xunit/blob/a3aa36920c778e471a661d2f1f2c6ad84b018d5e/src/xunit.v3.runner.console/xunit.v3.runner.console.csproj#L5
