### ISSUE TITLE
List all available traits / traits values by trait name

### ISSUE THREAD

**Issue by orihomie** [xunit/xunit#2084]
Hi, is there any option to list all available traits used in tests either just some specified trait values?

Something like
> dotnet test traits
> "Category", 
> "Level",
> ...

or 
> dotnet test trait "Category"
> "Unit"
> "Integration",
> ...

**Comment by bradwilson** [comment]
We don't control the command line of `dotnet test`.

That said, there is no mechanism in the runners who CLI we do control to do this today.

**Comment by orihomie** [comment]
That should be great to gather all traits and put them to a list where you can enable / disable some of them and then just run. Take a look at this option, please.

**Comment by bradwilson** [comment]
This is implemented a generalized `-list` option for both console runners:

![image](https://user-images.githubusercontent.com/16944/124986140-23c21880-dff0-11eb-88c0-68d862113464.png)
