### ISSUE TITLE
Assert.Equal causes FieldAccessException when comparing F# anonymous records of 8 or more fields

### ISSUE THREAD

**Issue by DalekBaldwin** [xunit/xunit#2088]
Occurs through both Visual Studio and dotnet test.

- xunit 2.4.1
- xunit.runner.console 2.4.1
- xunit.runner.visualstudio 2.4.1
- Windows 10
- tested on netcoreapp3.1 and net472 (identical results on both)
- Microsoft Visual Studio Professional 2019, Version 16.4.6

```fsharp
[<Fact>]
let ``anonymous records should be testable for equality in xunit`` () =
    let testRecord =
        {| A = 1
           B = 2
           C = 3
           D = 4
           E = 5
           F = 6
           G = 7
           H = 8 |}
    Assert.Equal (testRecord, testRecord)
```

Result:

```
  X TestProject.Tests.anonymous records should be testable for equality in xunit [1ms]
  Error Message:
   System.FieldAccessException : Attempt by method '<StartupCode$TestProject-Tests>.$AutoGeneratedProgram+clo@1-11<TA,TB,TC,TD,TE,TF,TG,TH>.Invoke(Microsoft.FSharp.Core.Unit)' to access field '<>f__AnonymousType3742177755`8<System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32>.A@' failed.
  Stack Trace:
     at <StartupCode$TestProject-Tests>.$AutoGeneratedProgram.clo@1-11.Invoke(Unit unitVar)
   at TestProject.Tests.anonymous records should be testable for equality in xunit() in C:\dev\TestProject\tests\TestProject.Tests\Tests.fs:line 178

```

**Comment by bartelink** [comment]
This is not something that can be caused by xUnit - it just finds your test and runs it.
You can confirm this by using [Unquote](https://github.com/SwensenSoftware/unquote) to do the assert - if that also fails similarly, then it should be logged in a relevant fsharp repo

**Comment by isaacabraham** [comment]
I think that this issue can be closed, it's almost certainly related to the linked issue - seems to be around equality comparisons on anoymous records that are of a certain size.

**Comment by bradwilson** [comment]
Agreed, this issue seems like it exists outside of xUnit.net.
