### ISSUE TITLE
Project Name Limitation

### ISSUE THREAD

**Issue by alansbraga** [xunit/xunit#2092]
Hi, I've created a project with a big name and the project do not run.

```powershell
md .\SieconWeb.DocumentoAnexos.Testes\ 
cd .\SieconWeb.DocumentoAnexos.Testes\
dotnet new xunit
dotnet test
```

The error is about VSTEST_CONNECTION_TIMEOUT, I won't print the entire message because my windows is in Portuguese and the message is not going to help you, but the steps are pretty simple.

I've changed the name and It worked it. 
I think it would be better if you change the message in this case, I've spent a lot of time trying to figure the real problem out, I thought it was the code inside my test.

Thank you in advance.

**Comment by alansbraga** [comment]
The problem also happens with mstest template.
I should have test it first, I'm sorry, I'm going to open the issue to microsoft people.

**Comment by bradwilson** [comment]
You might be running into `MAX_PATH` issues (if your total path length ends up longer than 260 characters).

https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation

**Comment by alansbraga** [comment]
The project name that worked was this one: "SieconWeb.Dominio.DA.Testes", so I did the following test:
I've created the project "SieconWeb.DocumentoAnexos.Testes" and try it, obviously didn't work and then I've create new projects just removing the last character until it worked. The name that worked was:
"SieconWeb.DocumentoAnex"
If you compare the name sizes, my oficial project has more characters than the test removing characters

Thank you for your reply!
