### ISSUE TITLE
Exceptions from a custom ITestCollectionOrderer swallowed

### ISSUE THREAD

**Issue by maxcherednik** [xunit/xunit#2094]
Found while doing #1996. Moved here so that not to pollute the original issue.

**Description**
An exception thrown from a custom `TestCollectionOrderer` is not visible anywhere and tests are still running.

It seems to be by design.
https://github.com/xunit/xunit/blob/c7f123adfc1d6dd0912e64c40b585b5d919077ba/test/test.xunit.execution/Sdk/Frameworks/Runners/TestAssemblyRunnerTests.cs#L285

Implemented here: https://github.com/xunit/xunit/blob/3f3f6929c301db40e9d5d8ced2bb494084f57c82/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestAssemblyRunner.cs#L119

But still no diagnostic messages printed anywhere.

What happens is the code swallows any exception and silently falls back to the default TestCollectionOrderer. Even though the issue is registered in the diagnostic messages, those messages are not printed by default. Hence, the original problem might be discovered very late.

**Options:**
1. Fail fast. Remove exception swallowing. Exception will bubble up and crush the test. It will be super obvious to the user that there is a bug in the custom orderer.
1. If for some reason current behavior needs to be preserved, the error message must be printed somehow. Not at the point when someone spots the issue and decides to turn on the diagnostic messages and then tries to find the one(which one?) among the other diagnostic messages.

Point number 2 is a bit counter intuitive. It is possible only if you know what you are looking for.

**Comment by bradwilson** [comment]
This is currently working as designed. Diagnostic messages are for debugging when extensibility isn't working, which sort of exactly describes this scenario. Understandably, there can be a lot of diagnostic messages so having them on all the time isn't useful, which is why they're off by default.

There is no other mechanism to report these other than diagnostic messages at this time.

Is your suggestion that everything should just outright fail in this scenario? Because that's really the only other option.

**Comment by maxcherednik** [comment]
>Is your suggestion that everything should just outright fail in this scenario?

I guess, as a user I would prefer this. At least it would be an expectation from a dev point of view. I am tweaking the extension points of xUnit, it is a fresh code, of course there will be bugs in there.

If I were to fix this I would probably change this here: 

https://github.com/xunit/xunit/blob/3f3f6929c301db40e9d5d8ced2bb494084f57c82/src/xunit.execution/Sdk/Frameworks/Runners/TestAssemblyRunner.cs#L158

2 options:
1. Either completely remove the generic exception handler. Less code for you to maintain, fail fast, predictable behavior in case of unknown issues. And it is clear from the stack trace what happened and where.

2. Just wrap and re-throw it something like this:

```C#
throw new InvalidOperationException("$"Unknown error in the test collection orderer '{TestCollectionOrderer.GetType().FullName}'", ex)
```
By doing so you add just a bit extra info on top of the original exception.

**Comment by maxcherednik** [comment]
Another, probably similar issue in that area is on this line:

https://github.com/xunit/xunit/blob/3f3f6929c301db40e9d5d8ced2bb494084f57c82/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestAssemblyRunner.cs#L125

I understand that this is a design decision, but I guess it is very easy to make a typo in here:

```C#
[assembly: TestCollectionOrderer("bla.bla.bla", "AsseblyName")] // missing letter
```

which will again result in a fall back to the default implementation.

Again, natural expectation is if I specify a type which does not exist, it should fail and say: `Wait, I did not find the type you were telling to load`. Full stop, no fallbacks.

**Comment by godefroi** [comment]
I ran into this today, and I would also rather the test run fail completely. The tests are ordered for a reason, and when they're run out of order, they all fail anyway, and if the whole run failed with a message about the orderer, at least I'd know why...

**Comment by aomader** [comment]
Can this eventually be revisited? We were bitten by that as well. Since this is all about tests and we want to see where something is off, I would expect that this is not silently swallowed, but thrown into my face.

**Comment by bradwilson** [comment]
Yes, I will change the behavior for the next release.

**Comment by bradwilson** [comment]
This has been implemented for both v2 and v3, but there are no testable builds right now because I'm waiting for .NET Foundation to renew our code signing certificates. Once the builds are available, it'll be in these versions (or more likely, something later):

v2 `2.8.2-pre.11`
v3 `0.1.1-pre.457`

**Comment by bradwilson** [comment]
These builds are available now on the CI package server. https://xunit.net/docs/using-ci-builds
