### ISSUE TITLE
AppDomain.Unload should time out

### ISSUE THREAD

**Issue by sharwell** [xunit/xunit#2097]
Currently, when `AppDomain.Unload` hangs it prevents test runs from completing. The call to `AppDomain.Unload` should be moved to a dedicated thread, and time out if it fails to complete in "a reasonable time". See NUnit for an example:

https://github.com/nunit/nunit-console/blob/0958996f2735c213bad7e8ed1c81e4d4ffdfec11/src/NUnitEngine/nunit.engine.core/Services/DomainManager.cs#L144-L200

**Comment by bradwilson** [comment]
AppDomains are going away in v3.

**Comment by sharwell** [comment]
We tried disabling AppDomain for the tests, but found that this configuration failed to handle assembly binding redirects configured for the test project. Is v3 going to support this in a different way?

**Comment by bradwilson** [comment]
Yes. In v3, .NET Framework test projects will become `.exe` files, so you will be able to create your own `App.config` files just like you would with any other executable.

**Comment by bradwilson** [comment]
I'm going to implement this change in `xunit.v3.runner.utility` since it'll still be useful when using a newer runner to run older (v1 and v2) tests.
