### ISSUE TITLE
WinUI 3 support

### ISSUE THREAD

**Issue by Xarlot** [xunit/xunit#2098]
As you may know, Microsoft just releases WinUI 3 Preview 1 microsoft/microsoft-ui-xaml#2472

Do you have any plans to support it? If so, letting us know timeframe will be very helpful.

**Comment by bradwilson** [comment]
What do you propose support for this would look like? Unit testing frameworks like xUnit.net are generally agnostic of the libraries that your production code uses.

**Comment by bradwilson** [comment]
Closed for age. Please open a [discussion](https://github.com/xunit/xunit/discussions) if you have a proposal. Thanks!
