### ISSUE TITLE
IAsyncLifetime.InitializeAsync running once for each test in class

### ISSUE THREAD

**Issue by damiensawyer** [xunit/xunit#2099]
Hi, 

It was my understanding that IAsyncLifetime.InitializeAsync should run only once per class. It appears to me to be running before each test. 

I expected that all of the following would pass. Only one of the three did.

Am I missing something? 

Thank you :-)

```
using System.Threading.Tasks;
using Xunit;
using static Xunit.Assert;

namespace XUnitAsyncLifetimeTests
{
    public class AsyncLifetimeTest : IAsyncLifetime
    {
        public static int Counter = 0;

        [Fact]
        public void t1()
        {
            Equal(Counter, 1);
        }

        [Fact]
        public void t2()
        {
            Equal(Counter, 1);
        }

        [Fact]
        public void t3()
        {
            Equal(Counter, 1);
        }

        public async Task InitializeAsync()
            => await Task.Run(() => Counter++);

        public Task DisposeAsync()
            => Task.CompletedTask;
    }
}
```

**Comment by bradwilson** [comment]
We create a new instance of the class for every test, which means we create and destroy the class once per test. (This is irrespective of whether you use `IAsyncLifetime`.)

If you want to do initialization and cleanup work only one time for a class, you can do that with a Class Fixture. See https://xunit.net/docs/shared-context for more information.

**Comment by damiensawyer** [comment]
Thanks for that. I didn't realise that I could use IAsyncLifetime on the class used for the fixture as well.
