### ISSUE TITLE
Consider exposing static ITestOutputHelper via AsyncLocal per test case

### ISSUE THREAD

**Issue by GeeWee** [xunit/xunit#2101]
# The Issue
(This is the same problem as #1730 , but with a potential solution attached)
The primary issue, which many people seem to have, and have varying solutions for is: *"It sure would be nice if logging statements and Console.Writeline statements were output with my tests"*

The `ITestOutputHelper` solution now works for the `Console.Writeline` part of the problem, but it comes with a few downsides - mainly that it's pretty verbose.
- You need to initialize it and have it injected into the constructor for every test class
- When subclassing base tests or anything like that, you have to pass it up to their constructor as well.

The verbosity of injecting the ITestOutputHelper would probably be solved by #1922 or #1738 - if the superclass could get it injected directly, it would be easy to use directly in test output.
However, I'm not sure the second problem is solved. The one that goes something like: "I want my log statements to be routed to the correct ITestOutputHelper".

This is trickier. As log targets/sinks are usually static configuration, and loggers might be static as well (e.g. Serilog exposes a static `Log.Information`)
It seems like the general workaround for this is to
- Generate a GUID for each test and keep it in an AsyncLocal
- Maintain a mapping of Guids <-> TestOutputHelper

This means when you log something, you can create a log target which does the mapping through the AsyncLocal to route the log message to the correct place. This seems to be the approach taken by e.g. [XUnitContext](https://github.com/SimonCropp/XunitContext), the [Serilog TestCorrelator Sink](https://github.com/MitchBodmer/serilog-sinks-testcorrelator) and proposed [here](http://dhickey.ie/2015/06/02/capturing-log-output-in-tests-with-xunit2/)

While `XUnitContext` does some really cool work in this space, it still requires us to subclass a test, and pass the `ITestOutputHelper` along to the superclass where it can be put into an AsyncLocal.

# The Proposed Solution
The solution I'm proposing is: Put the `ITestOutputHelper` into an `AsyncLocal` before every test.

This solves the problem of using an equivalent of `Console.Writeline` in my tests. You can expose a static wrapper ala `TestOutput.WriteLine`, which will route to the correct `ITestOutputHelper`

It also makes the problem of getting log statements routed to the correct ITestOutputHelper much easier.
Contributors can write a log target/sink that simply routes to `TestOutput.WriteLine`.

This proposal would mean that:
- We could easily log in tests ala Console.WriteLine
- We can easily build log targets to route logs to the correct ITestOutputHelper
- (Maybe) few changes required to core xUnit code - "all" we have to do is expose the ITestOutputHelper in an AsyncLocal
- No need for the boilerplate of getting ITestOutputHelper injected, passing it to superclasses etc.

**Comment by bradwilson** [comment]
This would be part of test context, so #621 should be a superset issue.
