### ISSUE TITLE
Randomly generated theory test cases are not run

### ISSUE THREAD

**Issue by mwpowellhtx** [xunit/xunit#2103]
Slack seems to be broken. I've already signed into another workspace. Signed out of it, tried to sign in to another workspace using my credential, and slack kicks me out for email and/or password. Positive they are correct. And the invite I get insists I create another account. I do not need to creat another account, just add the new workspace. I tried to sign in with the same credentials, and does not work, and I cannot re-sign into another workspace. So...

Question concerning the built-in VS2019 runner vis-à-vis. I've got a set of `TheoryAttribute` test cases that are randomly generated. Apparently, they get cached one way in the built-in display, and are never run. Presumably because on running they are randomly generated once again for whatever reason, so are never run again.

I'm going to try a canned set of cases, not randomly generated, from a predictable test set and see if the xunit runner picks those up any better. Truly, once the cases have been "discovered" there is no reason for the VS2019 test explorer, or the runner, to rediscover any cases, IMO. That is unless I rebuild, or there is an option to clear the cache and repopulate, etc.

**Comment by bartelink** [comment]
Best to ask this on SO - anyone that watches this repo probably watches the tags on SO too

**Comment by bradwilson** [comment]
Please see: https://xunit.net/faq/theory-data-stability-in-vs

>Best to ask this on SO - anyone that watches this repo probably watches the tags on SO too

I definitely do not watch StackOverflow.

**Comment by mwpowellhtx** [comment]
@bartelink Thanks, appreciate the feedback. I like to bring issues like this back to the source whenever possible. Will close this one, but can I leave with a suggestion to file issue with the VS team? Thanks...

**Comment by bartelink** [comment]
Sorry, I'm just a lurker trying to help (Inappropriately as it happens - thankfully Brad has more sense than to let that eat into his day!)

If you feel an issue should be logged with team X ('the VS team' in this instance), I'd suggest that you doing the legwork would be appreciated all-round; the repos and/or feedback channels are all open after all - keeping the xunit ship running is already plenty work as it is;

**Comment by mwpowellhtx** [comment]
@bartelink Appreciate the clarification.

@bradwilson I have, done the leg work, that is; and in my professional opinion the interface on that needs to be you, sir. All due respect, at least vis-à-vis the impact on xunit Theory stochastic data.

He says he's had the conversation, reference Slack, at the time of this response. For my part, I'll gladly help get the word out, up vote, weigh in, etc, but the interface must be Brad, IMO.
