### ISSUE TITLE
IXUnitSerializationInfo doesn't handle orphaned or bad Unicode surrogate pairs

### ISSUE THREAD

**Issue by mikamikem** [xunit/xunit#2107]
The implementation of XUnitSerializationInfo uses Encoding.UTF8.GetBytes() to convert the C# UTF-16 strings to Base64 (https://github.com/xunit/xunit/blob/a89b441170f0fe76e510cc2b1839a5023ded4f99/src/common/XunitSerializationInfo.cs#L116):

```
            var bytes = Encoding.UTF8.GetBytes(value);
            return Convert.ToBase64String(bytes);
```

The UTF-8 encoding process can't (or at least doesn't) map orphaned or bad surrogate pairs, so it replaces them with 0xFFFD.  I'm using xUnit to test issues around Unicode string manipulation, so I need to be able to represent the full range of UTF-16 codepoints even if (and for this sort of test especially if) the string is malformed.

The easiest way I could find to test this bug is to just copy and paste the code that gets run by XunitSerializationInfo to see what it's doing internally:

```
            // Copied from XunitSerializationInfo.cs:386-396
            static string FromBase64(string serializedValue)
            {
                var bytes = Convert.FromBase64String(serializedValue);
                return Encoding.UTF8.GetString(bytes, 0, bytes.Length);
            }

            static string ToBase64(string value)
            {
                var bytes = Encoding.UTF8.GetBytes(value);
                return Convert.ToBase64String(bytes);
            }

            [Fact]
            public static void Test()
            {
                string testBadUTF16String = "abc\ud801xyz";

                string serialized = ToBase64(testBadUTF16String);
                string deserialized = FromBase64(serialized);

                Assert.Equal(testBadUTF16String, deserialized);
            }
```

The above assert fails because the encoding and decoding process changes the orphaned surrogate \ud801 to the unknown character symbol.

I'm not sure what the best fix is for this, but if the serialized data is always generated and read on the same machine and we don't need to worry about endianness, you could always just grab the actual char array data as a byte array and use that directly to encode to and from base64 (see this SO answer: https://stackoverflow.com/a/10380166).

If the serialized data is sent to other platforms to do testing on other device types that may have different endianness, then the solution will need to care about endianness and would be a bit more complicated.

I don't know enough about UTF-8 encoding to know for sure if there's a way to map an isolated surrogate character to UTF-8, but a brief look around suggests that it depends on how Microsoft implemented UTF-8 encoding.  It's possible you could use a custom fallback strategy (https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-encoding#implementing-a-custom-fallback-strategy) on the UTF8 encoding to handle UTF-8 encoding/decoding of the isolated surrogate if their process supports it.

A slightly messier, but straightforward solution might be a big or little endian bool (or even byte) getting serialized out first for every string and if it doesn't match the platform's endianness it does a swap (something like this: https://stackoverflow.com/q/1610868) on the raw serialized char array from above.

Another possible option is to just make a custom UTF-16 encoder that always reads/writes the value in either big or little endian UTF-16 and doesn't validate it first (sadly the Unicode and BigEndianUnicode encoders validate data so they won't work either even though they write out UTF-16 bytes).  Or to possibly use a custom fallback strategy on the Unicode or BigEndianUnicode encoders to just return the appropriate endianness version of the codepoint that failed.

**Comment by bradwilson** [comment]
My recollection is that there was a similar issue, which I closed as Won't Fix (which is how I plan to close this one as well).

My reasoning there was: we use UTF-8 to ensure that serialization of strings is generally compact. We expect strings to be valid Unicode strings, even though .NET does not necessarily make that same requirement. For us to move to any other system would involve a MUCH more expensive (memory-wise) serialization for strings. Thus, we do not plan to fix this, because it makes the much more common cases perform worse.

The work-around is for you not to put illegal Unicode into strings; instead, serialize something like `byte[]` or `char[]` (which doesn't encode as UTF-8), and then you can convert that to a string inside your test method.
