### ISSUE TITLE
Convert analyzers to IOperation analysis

### ISSUE THREAD

**Issue by sharwell** [xunit/xunit#2108]
Currently the analyzers are written as `SyntaxNode` analyzers that obtain semantic information from various `SemanticModel` APIs. While this is functional, the analysis performance is much worse than the same operations performed using the newer `IOperation` APIs. For the type of operations required by xunit analyzers, the build-time cost of these analyzers would go from "significant" (25+% of the total build-time analyzer cost in dotnet/roslyn) to nearly free ("negligible").

While the conversion is generally straightforward (I already have a local branch that makes the change), it would require us to move the analyzers from Roslyn 1.x (Visual Studio 2015+) to Roslyn 2.x (Visual Studio 2017+). Before submitting the PR, I wanted to verify that this would be an acceptable change to the analyzer dependencies. Other parts of the xunit distribution, including the assertions library, extensibility library, and all execution environments, would be unaffected by this change.

**Comment by bradwilson** [comment]
I'm all for this. Min-bar of VS 2017 is reasonable. If we don't have any significant hardships about this change in the next few days, let's make it happen.

**Comment by bradwilson** [comment]
This has been merged. Thanks for the work!
