### ISSUE TITLE
Nuget licence links broken in XUnit and XUnit.Analyzers

### ISSUE THREAD

**Issue by tomek-anuszkiewicz** [xunit/xunit#2109]
XUnit 2.4.1
Nuget licence link https://raw.githubusercontent.com/xunit/xunit/master/license.txt link o 404.
XUnit.Analyzers 0.10.0
Nuget licence link https://raw.githubusercontent.com/xunit/xunit.analyzers/master/LICENSE link to 404.

Also can you use: https://docs.microsoft.com/en-us/nuget/reference/nuspec#license

**Comment by bradwilson** [comment]
Thanks, these have been resolve.
