### ISSUE TITLE
Apply TraitAttribute to whole assembly

### ISSUE THREAD

**Issue by krwq** [xunit/xunit#211]
Hello,

I'm using many .csproj files in one project and using runner to run tests on all of them as part of the build.
It would be nice if xUnit supported applying Trait attribute on whole assembly as it would be easier to run tests related to some concrete feature.

I.e:
FeatureA.Tests.dll contains few sets of tests for FeatureA
FeatureB.Tests.dll contains few tests which test FeatureB but also use FeatureA in few of them.

It would be much easier to apply trait related to FeatureA to whole assembly than spamming this trait for every single class in FeatureA tests..

**Comment by bradwilson** [comment]
Added with #711.

**Comment by krwq** [comment]
Thanks Brad! :smile:
