### ISSUE TITLE
C# 8.0 with Nullable: analyzer xUnit1013 does not warn on public Task returning method without attribute

### ISSUE THREAD

**Issue by hwanders** [xunit/xunit#2110]
If I create a new project for .NET Core 3.1 (with `dotnet new xunit`) and enable Nullable support (add `<Nullable>enable</Nullable>` to the .csproj file), the xUnit1013 analyzer does _not_ create warnings for public `Task`-returning methods without a `Fact`/`Theory` attribute.

Project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.6.1" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>

```

Test class:
```c#
using System.Threading.Tasks;
using Xunit;

namespace XUnitBugRepro
{
    public class PublicMemberTest
    {
        public Task DoesNotShowXUnit1013Warning()
        {
            return Task.CompletedTask;
        }

        public void ShowsXUnit1013Warning()
        {
        }

        [Fact]
        public void SomeTest()
        {
        }
    }
}
```

Result:
![image](https://user-images.githubusercontent.com/9137466/85288795-9c623f80-b496-11ea-99b4-fbbe79eb2d37.png)

**Comment by manvydasu** [comment]
Isn't this intended behaviour for some reason? 
I've looked in source code and found test, which verifies that functions with return type 'Task' do not show warning.
`DoesNotFindErrorForIAsyncLifetimeMethods`

**Comment by manvydasu** [comment]
I've tried adding unit test with source like
```
                     var source = 
@"public class TestClass {
	public System.Threading.Tasks.Task Method() {
		return System.Threading.Tasks.Task.CompletedTask; 
	}

    public void ShowsXUnit1013Warning()
    {
    }

    [Fact]
    public void SomeTest()
    {
    }
}";
```

And it passes - returns warnings for both methods, which do not have [Fact] attribute.

However, if testing with IDE (rider) itself it's more interesting - build warnings show only one error, but IDE highlights both of the methods and shows that they are missing [Fact] attribute. 
Any idea what could be going wrong here? I'm not very familiar with the codebase.

**Comment by hwanders** [comment]
A little addition: while there are special cases where the analyzer is expected to report _no_ warning (for methods from the interfaces `IDisposable` and xunit's `IAsyncLifetime`), my example is no such case.

Furthermore the problem only occurs when enabling the `Nullable` option. Without it being enabled, the analysis works correctly and yields a warning

**Comment by hwanders** [comment]
@manvydasu: Writing a unit test for this case is difficult with the current testing infrastructure, because the source code (written as text) is probably parsed as C# 7.3 and not C# 8.0:
* It uses `CSharpCodeFixTest` from Microsoft.CodeAnalysis.CSharp.CodeFix.Testing v1.0.1.0
* There `CreateParseOptions` uses the `DefaultLanguageVersion` static field which is defined as `Enum.TryParse("Default", out LanguageVersion version) ? version : LanguageVersion.CSharp6`
* Since `LanguageVersion` comes from Microsoft.CodeAnalysis.CSharp v2.8.0.0 which contains a `Default` value (`0`), the decision about the version is made later  - but notice that the enum's highest language version is `CSharp7_3`

**Comment by bjornhellander** [comment]
I managed to get a test case for this running after upgrading the Roslyn version in the test project. I included some 8.0 specific syntax, to make sure the first part worked. I also added `#nullable enable` in the tested code, since I couldn't find a way to set it in the tested project. Unfortunately I can't reproduce the behaviour from Visual Studio inside the unit test either.

**Comment by bradwilson** [comment]
I am unable to repro this with `1.2.0-pre.36`:

![image](https://github.com/xunit/xunit/assets/16944/234b4ffc-b034-4841-8402-df8dfe776341)

This may have already been fixed. Can you repro it with a 2.5.0 prerelease build? @hwanders @lscpike

**Comment by bjornhellander** [comment]
@bradwilson The issue was with methods returning `Task` (your methods return `void`), but I tried changing versions back and forth in another project now and it seems to have been fixed between 2.4.2-pre.27 and 2.4.2.

**Comment by bjornhellander** [comment]
@lscpike Is your problem gone as well with a newer version? If not, maybe you should create a separate issue.

**Comment by bradwilson** [comment]
Excellent! Thanks.
