### ISSUE TITLE
Out-dated Documentation

### ISSUE THREAD

**Issue by Banyc** [xunit/xunit#2114]
The doc on the website below is out-dated:

<https://xunit.github.io/docs/getting-started/netcore/cmdline>

## Expected

Using `dotnet new xunit` to create a new project for testing.

## Actual Behavior

Using `dotnet new classlib` first and add dependencies manually.

Applying this method, the unit test cases could not be debugged in vscode.

**Comment by bradwilson** [comment]
This is purposeful.

Please provide a repro project that wouldn't properly debug, as it should work.

**Comment by Banyc** [comment]
> This is purposeful.
> 
> Please provide a repro project that wouldn't properly debug, as it should work.

I followed the tutorial to create a unit test case but change the target framework to dotnet core 3.1. This might the cause for not being able to debug test cases.

Anyway, the tutorial is for dotnet core 2.x, while it might be the best practice for the users using the latest version of dotnet core to simply use `dotnet new xunit` instead.

**Comment by bradwilson** [comment]
Closing, as the docs now use `dotnet new xunit`.
