### ISSUE TITLE
Proposal: Add predicate based DoesNotContainException

### ISSUE THREAD

**Issue by mwpowellhtx** [xunit/xunit#2116]
*DoesNotContain* was my entry use case, however, may apply to similar ones...

I've got a case in my `xUnit` fluent extensions, that I am adding a `Predicate<T>` based approach deciding whether a Collection `AssertContains` or `AssertDoesNotContain`, etc.

In the interim, I don't suppose I can do something like this, i.e

```C#
new DoesNotContainException(expectedPredicate, actual);
```

**Comment by bradwilson** [comment]
What would the exception do with the predicate? We don't throw the exception until after the test has failed.

**Comment by mwpowellhtx** [comment]
Initially I thought I might need to instantiate an exception, but I was able to use my fluent delegation strategy to invoke the underlying corresponding *xUnit.net* assertion. That'll work I think, and it relies on the inner workings of *xUnit.net* to do the right thing.
