### ISSUE TITLE
Class fixtures are not isolated, leaks and causes erratic test results

### ISSUE THREAD

**Issue by andrejohansson** [xunit/xunit#2119]
I am trying to use [class fixtures](https://xunit.net/docs/shared-context) in order to separate an in memory database between test classes. But whatever I do, I cannot seem to get the db instance separated from each other when running in parallell.

Since I am not sure where the issue lies, I posted code and a more detailed description in the sqlite driver page, see:
https://github.com/dotnet/efcore/issues/21633#issuecomment-659565156

But top level description goes like this:

My understanding is this:

- I can create a db fixture
- I can create two test classes containing tests
- I can use the db fixture from the test classes
- Test methods **within the same class** should share their db instance
- Test methods **in different classes** should have separate db instances. That is, one dbfixture gets created per class
- I should be able to run the **test classes** in parallell without any intervention between the test classes since they each have their own db

But this is whats happening

- I run testclass A and testclass B sequentially -> everything works
- I run testclass A and B in parallell -> sporadic failures since db content seems to be modified/cleared when a parallell test is run **in another thread**

As far as I can understand ``SqliteConnection`` is **not** threadsafe. But I assume that since each test class gets their own db instance this should not be a problem. Is this a faulty assumption or have I hit a bug somehow?

**Comment by bradwilson** [comment]
Based on https://github.com/dotnet/efcore/issues/21633#issuecomment-660217953 I'm assuming this isn't an xUnit.net issue.

**Comment by andrejohansson** [comment]
@bradwilson, thank you for your response. I just tested the solution in the comment and it worked for me so you are right, it´s not a xunit issue!
