### ISSUE TITLE
In Xunit tests for net461, how to enable AppDomain in Windows  then  disable it in Linux when using `dotnet test`

### ISSUE THREAD

**Issue by moh-hassan** [xunit/xunit#2121]
Xunit Support Multi-targeting test with [non-Windows OSes](https://xunit.net/docs/getting-started/multi-target/non-windows), so I can build Xunit multi-target test project in Linux, 
I run the multi-target project `net461,netcoreapp3.1` on CI server in both windows and Linux.
in windows and Linux, I run the command
```
dotnet test project.dll
```
Test success on Windows, but fail for net461 on Linux (Ubuntu 20.04 ).

I know that Xunit, by default, create a new AppDomain in net4x (appdomain=required/ifAvailable) whatever is OS Windows  or Linux.
I can't use the [json configuration](https://xunit.net/docs/configuration-files) because It's shared in all environment.

I didn't find setting for Xunit in CLI `dotnet test` to disable` appDomain`  (but I  may miss something). 
I want to run these command on Linux and disable AppDomain in net461:
```
# in Linux Environment
dotnet test project.dll -f netcoreapp3.1   # ok it's fine
dotnet test project.dll   -f net461 -- setting:appdomain=denied ???   # what the exact syntax for setting
```

What is valid syntax for disabling appDomain in `dotnet test`?

Note: (Feature request): It's nice if Xunit disable AppDomain in net4x in non-windows Environment by default  at runtime whatever setting is (it's disabled by default in netcore).

**Comment by bradwilson** [comment]
Good news, bad news.

Good news: v3 no long supports app domains, so this won't be an issue with v3.

Bad news: I don't think there's anything we can do now about `dotnet test` and how it handles v2 w/ app domains, especially since we're not planning on making any more v2 releases.

**Comment by bradwilson** [comment]
I don't have a good resolution take for this, but "By Design" is close as I can get.

**Comment by moh-hassan** [comment]
Thanks @bradwilson  for suggestion.
For net461, I installed `xunit.console.exe` [v2.4.1](https://www.nuget.org/packages/xunit.runner.console/) to run the test in Linux with Mono installed (Mono version 6.8.0.105).
`xunit.console.exe` has an option `-appdomains`  with values `required/denied/ifavailable`.
The strange, Xunit test success for appdomain either denied or required, and the performance is very high ( parallel 4 threads).
the next script is working:

```sh
dotnet test -f netcoreapp3.1       # for netcore
path/to/xunit.console.exe  test.dll  -appdomains denied     # net461 working
path/to/xunit.console.exe  test.dll  -appdomains required  # net461 working
path/to/xunit.console.exe  test.dll             # net461 working with default appdomain=required
```

**Comment by bradwilson** [comment]
Seems like this has been resolved, please re-open if not.
