### ISSUE TITLE
methodDisplay:method does not work for Theory 'container'

### ISSUE THREAD

**Issue by acrov** [xunit/xunit#2122]
When using "methodDisplay": "method" in xunit.runner.json it is applied to the individual InlineData theories but not to the containing Theory itself.

For the following test
```cs
namespace xunit_runner
{
    public class UnitTest1
    {
        [Theory]
        [InlineData(1)]
        [InlineData(2)]
        public void MyTheory(int x)
        {

        }
    }
}
```
I would expect output like:
```
xunit-runner
   UnitTest1
     MyTheory
      MyTheory(x: 1)
      MyTheory(x: 2)
```
but instead I get
```
xunit-runner
   UnitTest1
     xunit-runner.UnitTest1.MyTheory
      MyTheory(x: 1)
      MyTheory(x: 2)
```

i.e. the namespace and class are still included when outputting the theory "container" item.

xunit 2.4.1
xunit.runner.visualstudio 2.4.2
windows 10 1909
visual studio community 2019 16.6.2

**Comment by bradwilson** [comment]
If you're speaking about the UI inside Visual Studio's Test Explorer window, we cannot control how they choose to display the test method name when grouping tests. This issue belongs with the VSTest team.

**Comment by bradwilson** [comment]
This is an issue with Visual Studio, so closing now.

**Comment by knumat** [comment]
This bug in Visual Studio has been carried over to the Test Explorer provided by the C# Dev Kit extension for VS Code.  I added a [comment](https://github.com/microsoft/vscode-dotnettools/issues/533#issuecomment-1758486616) linking back to this issue.
