### ISSUE TITLE
Unit Test derived Controller class using protected IMapper in base controller in asp.net core 3.1

### ISSUE THREAD

**Issue by MathavanN** [xunit/xunit#2135]
I am using xUnit to test my controllers

    public class BaseController : ControllerBase
    {
        private IMapper _mapper;
        protected IMapper Mapper => _mapper ?? (_mapper = HttpContext.RequestServices.GetService<IMapper>());
    }

    public class TestController : BaseController
    {
        private readonly IReportRepository _reportRepository;
        public TestController(IReportRepository reportRepository)
        {
            _reportRepository = reportRepository;
        }

        [HttpGet("{id}")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<IActionResult> GetDataById(string id)
        {
            var result = await _reportRepository.FindDataByIdAsync(id);

            var dataDto = Mapper.Map<GetDataDto>(result);

            return Ok(dataDto);
        }
    }
How to mock BaseController IMapper? Here is the unit test implementation. 

    public class TestControllerFixture : IDisposable
    {
        public Mock<IReportRepository> MockReportRepository { get; private set; }

        public Mock<BaseController> MockBaseController { get; private set; }

        public DataReportRequest MyDataReportRequest { get; private set; }

        public IMapper MockMapper { get; set; }

        public TestControllerFixture()
        {
            MockReportRepository = new Mock<IReportRepository>();

            //auto mapper configuration
            var configuration = new MapperConfiguration(cfg =>
            {
                cfg.AddProfile(new AutoMapping());
            });
            MockMapper = configuration.CreateMapper();

            MockBaseController = new Mock<BaseController>() { CallBase = true };

            MockBaseController.Protected().SetupGet<IMapper>("Mapper").Returns(MockMapper);

            MyDataReportRequest = new DataReportRequest
            {
                Id = "11111111-1111-1111-1111-111111111111",
                ReportName = "Test Report",
                ReportGenrationDate = DateTime.Now.AddDays(-1),
                ReportStatus = ReportStatus.Completed
            };
        }

        public void Dispose()
        {
            MockMapper = null;
            MockReportRepository = null;
        }
    }

I am getting this error. System.NotSupportedException: 'Unsupported expression: mock => mock.Mapper Non-overridable members (here: BaseController.get_Mapper) may not be used in setup / verification expressions.'

**Comment by skimmedsquare** [comment]
Apologies for the erroneous commit reference, typoed the issue number
