### ISSUE TITLE
xUnitSummary.xsl

### ISSUE THREAD

**Issue by torrentx** [xunit/xunit#214]
Might be looking in the wrong place, but this xsl needs to be updated for the 2.0 version of xUnit.  The former class, needs to be updated to collection like:
From 
xsl:if test="//assembly/class/test[@result='Fail']"
To
xsl:if test="//assembly/collection/test[@result='Fail']"

**Comment by bradwilson** [comment]
Moved here: https://github.com/xunit/xunit.github.io/issues/4
