### ISSUE TITLE
Xunit tests with complex theory data are difficult to navigate / consume in Visual Studio / ADO

### ISSUE THREAD

**Issue by cmeyertons** [xunit/xunit#2152]
When TheoryData / MemberData consists of complex types, the Xunit runner generates output in a different format than when only using primitives.

Complex types: 1 test case with N # of results attached - when many, the stack traces / error logs are more difficult to navigate

Primitives: N test cases, each with 1 result attached -- plays very nice into the expected output behavior of Xunit.

For end users, this makes it more difficult to visualize the problematic test case.

For other build systems / IDEs, this makes it more difficult to generate consistent output.  ADO seems to be having some problems with this and is not prioritizing fixing it.

https://developercommunity.visualstudio.com/content/problem/1078693/wrong-unit-test-parameter-names-in-build-results-u.html
https://developercommunity.visualstudio.com/content/problem/1037085/xunit-theory-tests-using-complex-memberdata-have-d.html

**Comment by bradwilson** [comment]
Unfortunately, there isn't much that can be done about this. We require serialization support to be able to enumerate individual test cases. Complex types can implement `IXunitSerializable` if they wish to participate in this serialization; when we discover there is non-serializable data in the data rows, then we're forced to fall back to a single test case with multiple results.

**Comment by cmeyertons** [comment]
@bradwilson thank you -- I wasn't aware of IXunitSerializable.  Did I miss that in the docs?

**Comment by bradwilson** [comment]
I don't think there's a doc for it yet.

**Comment by JDCain** [comment]
@cmeyertons I ended up making a wrapper for the theory data which allows you to assign a name to the data. You can see the info here: https://github.com/xunit/xunit/discussions/2174
