### ISSUE TITLE
xunit console fails to run tests in parallel when every test creates a new process

### ISSUE THREAD

**Issue by kartheekp-ms** [xunit/xunit#2157]
* Is this a question? `No`
* Is this a bug with VSTest (aka Visual Studio Test Explorer, `dotnet test`, `dotnet vstest`,
  or `vstest.console.exe`)? `No`
* Did you search the docs @ https://xunit.net/ ? `Yes`
* Did you search the issues list to see if someone already reported it? `Yes`
* Did you create a simple repro for the problem? `Yes`

`NuGet.Client` product has a `functional test project` where tests are executed [sequentially](https://github.com/NuGet/NuGet.Client/blob/dev/test/NuGet.Clients.Tests/NuGet.CommandLine.Test/xunit.runner.json). We would like to run these tests in parallel. This test project has around 950 tests where every test has following steps.
- Arrange 
- Act
    - Open `nuget.exe` in a separate process passing few arguments
    - `nuget.exe` executes appropriate commands and writes the log messages to the [standard output stream](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.redirectstandardoutput?view=netframework-4.8).
- Assert using output and error stream

When we try to run these tests in parallel, we have noticed that if the `number of classes in test assembly < number of cores in the machine` then tests executed successfully in `parallel`. However, when `number of classes in test assembly = number of cores in machine tests`, `xunit console runner` is waiting indefinitely.

There could be a possibility that I am missing something here, but this behavior is currently blocking us to run tests in parallel.

I created a sample solution for you to reproduce the issue we are experiencing.

[xunit-parallel.zip](https://github.com/xunit/xunit/files/5284441/xunit-parallel.zip)

- Executing tests in parallel succeeded for `xunit-project3` irrespective of no. of classes and cores in the machine. Referred [doc](https://xunit.net/docs/running-tests-in-parallel.html).

```cs
.\xunit.runner.console\2.4.1\tools\net472\xunit.console.exe "{PATH to DLL}\xunit-project3.dll" -verbose
xUnit.net Console Runner v2.4.1 (64-bit Desktop .NET 4.7.2, runtime: 4.0.30319.42000)
  Discovering: xunit-project3 (app domain = on [shadow copy], method display = ClassAndMethod, method display options = None)
  Discovered:  xunit-project3 (found 18 test cases)
  Starting:    xunit-project3 (parallel test collections = on, max threads = 8)
    xunit_project3.TestClass8.Test1 [STARTING]
    xunit_project3.TestClass3.Test2 [STARTING]
    xunit_project3.TestClass9.Test2 [STARTING]
    xunit_project3.TestClass4.Test1 [STARTING]
    xunit_project3.TestClass1.Test1 [STARTING]
    xunit_project3.TestClass2.Test2 [STARTING]
    xunit_project3.TestClass7.Test2 [STARTING]
    xunit_project3.TestClass5.Test2 [STARTING]
    xunit_project3.TestClass3.Test2 [FINISHED] Time: 10.0211819s
    xunit_project3.TestClass7.Test2 [FINISHED] Time: 10.020639s
    xunit_project3.TestClass2.Test2 [FINISHED] Time: 10.0209657s
    xunit_project3.TestClass1.Test1 [FINISHED] Time: 10.0202523s
    xunit_project3.TestClass5.Test2 [FINISHED] Time: 10.0209437s
    xunit_project3.TestClass4.Test1 [FINISHED] Time: 10.0208516s
    xunit_project3.TestClass9.Test2 [FINISHED] Time: 10.0208265s
    xunit_project3.TestClass7.Test1 [STARTING]
    xunit_project3.TestClass8.Test1 [FINISHED] Time: 10.0207918s
    xunit_project3.TestClass8.Test2 [STARTING]
    xunit_project3.TestClass9.Test1 [STARTING]
    xunit_project3.TestClass5.Test1 [STARTING]
    xunit_project3.TestClass1.Test2 [STARTING]
    xunit_project3.TestClass3.Test1 [STARTING]
    xunit_project3.TestClass2.Test1 [STARTING]
    xunit_project3.TestClass4.Test2 [STARTING]
    xunit_project3.TestClass2.Test1 [FINISHED] Time: 10.0035894s
    xunit_project3.TestClass1.Test2 [FINISHED] Time: 10.0036667s
    xunit_project3.TestClass4.Test2 [FINISHED] Time: 10.0036481s
    xunit_project3.TestClass3.Test1 [FINISHED] Time: 10.0036499s
    xunit_project3.TestClass9.Test1 [FINISHED] Time: 10.003715s
    xunit_project3.TestClass5.Test1 [FINISHED] Time: 10.0036919s
    xunit_project3.TestClass7.Test1 [FINISHED] Time: 10.0041151s
    xunit_project3.TestClass8.Test2 [FINISHED] Time: 10.006091s
    xunit_project3.TestClass6.Test2 [STARTING]
    xunit_project3.TestClass6.Test2 [FINISHED] Time: 10.0051741s
    xunit_project3.TestClass6.Test1 [STARTING]
    xunit_project3.TestClass6.Test1 [FINISHED] Time: 10.0119994s
  Finished:    xunit-project3
=== TEST EXECUTION SUMMARY ===
   xunit-project3  Total: 18, Errors: 0, Failed: 0, Skipped: 0, Time: 40.141s
```

- Executing tests in parallel for `xunit-project4` project failed and console runner is waiting indefinitely. One observation - there are 8 classes in the project and my machine has 8 cores.

```cs
.\xunit.runner.console\2.4.1\tools\net472\xunit.console.exe "{PATH to DLL}\xunit-project4.dll" -verbose
xUnit.net Console Runner v2.4.1 (64-bit Desktop .NET 4.7.2, runtime: 4.0.30319.42000)
  Discovering: xunit-project4 (app domain = on [shadow copy], method display = ClassAndMethod, method display options = None)
  Discovered:  xunit-project4 (found 16 test cases)
  Starting:    xunit-project4 (parallel test collections = on, max threads = 8)
    TestClass4.Test_2 [STARTING]
    TestClass2.Test_2 [STARTING]
    TestClass7.Test_1 [STARTING]
    TestClass3.Test_1 [STARTING]
    TestClass5.Test_1 [STARTING]
    TestClass1.Test_2 [STARTING]
    TestClass8.Test_1 [STARTING]
    TestClass6.Test_2 [STARTING]
```

- I deleted one class file from the `xunit-project4` test project. Executing tests in parallel succeeds.

```cs
.\xunit.runner.console\2.4.1\tools\net472\xunit.console.exe "{PATH to DLL}\xunit-project4.dll" -verbose
xUnit.net Console Runner v2.4.1 (64-bit Desktop .NET 4.7.2, runtime: 4.0.30319.42000)
  Discovering: xunit-project4 (app domain = on [shadow copy], method display = ClassAndMethod, method display options = None)
  Discovered:  xunit-project4 (found 14 test cases)
  Starting:    xunit-project4 (parallel test collections = on, max threads = 8)
    TestClass5.Test_1 [STARTING]
    TestClass7.Test_1 [STARTING]
    TestClass4.Test_2 [STARTING]
    TestClass2.Test_2 [STARTING]
    TestClass3.Test_1 [STARTING]
    TestClass1.Test_2 [STARTING]
    TestClass6.Test_2 [STARTING]
    TestClass3.Test_1 [FINISHED] Time: 5.1792611s
    TestClass1.Test_2 [FINISHED] Time: 5.1773855s
    TestClass7.Test_1 [FINISHED] Time: 5.1783154s
    TestClass2.Test_2 [FINISHED] Time: 5.1783335s
    TestClass7.Test_2 [STARTING]
    TestClass1.Test_1 [STARTING]
    TestClass2.Test_1 [STARTING]
    TestClass3.Test_2 [STARTING]
    TestClass4.Test_2 [FINISHED] Time: 5.2001365s
    TestClass4.Test_1 [STARTING]
    TestClass5.Test_1 [FINISHED] Time: 5.2008057s
    TestClass5.Test_2 [STARTING]
    TestClass6.Test_2 [FINISHED] Time: 5.2013812s
    TestClass6.Test_1 [STARTING]
    TestClass7.Test_2 [FINISHED] Time: 5.0822454s
    TestClass3.Test_2 [FINISHED] Time: 5.0974951s
    TestClass1.Test_1 [FINISHED] Time: 5.0979299s
    TestClass2.Test_1 [FINISHED] Time: 5.097866s
    TestClass6.Test_1 [FINISHED] Time: 5.0791454s
    TestClass5.Test_2 [FINISHED] Time: 5.0944306s
    TestClass4.Test_1 [FINISHED] Time: 5.0949469s
  Finished:    xunit-project4
=== TEST EXECUTION SUMMARY ===
   xunit-project4  Total: 14, Errors: 0, Failed: 0, Skipped: 0, Time: 10.377s
```

**Comment by bradwilson** [comment]
>When we try to run these tests in parallel, we have noticed that if the number of classes in test assembly < number of cores in the machine then tests executed successfully in parallel. However, when number of classes in test assembly = number of cores in machine tests, xunit console runner is waiting indefinitely.

This means you're deadlocked. You're probably incorrectly using async somewhere in stack by doing something like `.Result` and/or `.GetAwaiter().GetResult()` and/or one of the `Wait` family of methods. Once you've exhausted all the threads in the thread pool, then there's no way for any further async code to run.

This code here in your repro looks to be the culprit:

```csharp
        p.StartInfo = psi;
        p.Start();
        var outputTask = ConsumeStreamReaderAsync(p.StandardOutput, output);
        var errorTask = ConsumeStreamReaderAsync(p.StandardError, errors);
        p.WaitForExit();

       Task.WaitAll(outputTask, errorTask);
```

Convert RunCommand to return `Task<string>` instead of `string`, and properly use `await` with the `When` family of methods instead of the `Wait` family of methods.

Additionally, `p.WaitForExit()` is a blocking API, which is probably contributing to the problem as well. You need to find an async-compatible way to wait for the process to exit.

**Comment by kartheekp-ms** [comment]
Thank you @bradwilson. I have identified the problem in the repro and product as well and later checked your response on this issue. I agree with your comment.
