### ISSUE TITLE
Theory MemeberData support for more individual test case meta-data

### ISSUE THREAD

**Issue by markm77** [xunit/xunit#2164]
As mentioned in https://github.com/xunit/xunit/issues/1485 some of us use a workaround like below to skip individual test cases of a MemberData Theory: 

```csharp
 [Theory]
        [MemberData(
            memberName: nameof(SkippedTestsByInputName),
            nameof(TestType),
            Skip = "Test skipped due to skip instruction in " + nameof(LookupType))]
        [MemberData(
            memberName: nameof(UnskippedTestsByInputName),
            nameof(TestType))]
```

Having used this solution for a while, some limitations become evident:
* Individual test case skip reasons cannot be supplied by MemberData
* Other individual test case meta-data such as Trait etc cannot be supplied by MemberData

It would be great if MemeberData could support more test case meta-data for individual tests such as skip/no-skip, skip reason and also trait etc. This would make dynamic test generation much more powerful.

**Comment by bradwilson** [comment]
I think this will be subsumed by https://github.com/xunit/xunit/issues/1758, so closing as dup.

**Comment by markm77** [comment]
@bradwilson Sounds great this functionality will likely make v3, many thanks!
