### ISSUE TITLE
AssemblyRunner race condition - Status is not necessarily yet Idle when ExecutionComplete event is invoked

### ISSUE THREAD

**Issue by gulbanana** [xunit/xunit#2168]
There's a small issue in AssemblyRunner.cs which applies both to xUnit 2.4 and 3.0. When the ITestAssemblyFinished message is dispatched, it signals completion internally and externally like so:
```cs
	if (DispatchMessage<ITestAssemblyFinished>(message, messageTypes, assemblyFinished =>
	{
		OnExecutionComplete?.Invoke(new ExecutionCompleteInfo(assemblyFinished.TestsRun, assemblyFinished.TestsFailed, assemblyFinished.TestsSkipped, assemblyFinished.ExecutionTime));
		executionCompleteEvent.Set();
	}))
```

The problem is the order of the two lines in the lambda. First, OnExecutionComplete is invoked, notifying applications that the runner is done. However, it isn't actually done - only once executionCompleteEvent is set does it effectively change the value of the Status property. This is important because Dispose() contains the following check:
```cs
if (Status != AssemblyRunnerStatus.Idle)
	throw new InvalidOperationException("Cannot dispose the assembly runner when it's not idle");
```

In my application, I wrote code like this to use AssemblyRunner:
```cs
        using (var finished = new ManualResetEventSlim(false))
        using (var runner = AssemblyRunner.WithAppDomain(testDLL))
        {
            runner.OnExecutionComplete = info => finished.Set();
            runner.OnTestFailed = info => tests.Add(info.TestDisplayName, info.ExceptionMessage);
            runner.OnTestPassed = info => tests.Add(info.TestDisplayName, null);

            runner.Start();
            finished.Wait();
        }
```

Eventually I got unlucky, my using block terminated between the first and second lambda lines, and AssemblyRunner.Dispose() threw.

**Comment by bradwilson** [comment]
Because this runs asynchronously, you can't assume that the notification of ExecutionComplete necessarily means that the engine is idle. It will be soon, but not necessarily immediately. There are some cleanup conditions which may need to happen after this message is sent. So this is By Design.
