### ISSUE TITLE
Add async overload of Assert.Collection

### ISSUE THREAD

**Issue by fjmorel** [xunit/xunit#2172]
It may not be a good pattern, but I encountered a scenario today where the following assert would have been helpful:

```csharp
  public static Task Collection<T>(IEnumerable<T> collection, params Func<T, Task>[] elementInspectors)
```

I ended up using `.Result` inside the element inspectors, which is a bad practice. If you're ok with this being added, I can write up a PR later.

**Comment by bradwilson** [comment]
Yeah, I'm okay with this, though part of the v3 work has been to move as much to `ValueTask` rather than `Task` as possible, so when doing the PR, please use a `ValueTask`-based signature.

**Comment by fjmorel** [comment]
PRs created to add asserts and add tests.
