### ISSUE TITLE
Do we have easy way to assign xunit trait to test case InlineData

### ISSUE THREAD

**Issue by cosin2008** [xunit/xunit#2177]
Imagine that we have some test codes which are almost same, the only different is test data. But these test cases is categorized by certain test environments, DEV/CI/PROD... And while we are running tests, we want to have ways to filter by environment (using test trait filtering, for example), is that doable with less hacking in current xunit implementation? 

One naive idea is that xunit can provide inline data level trait assignment. But i do not think trait is designed to allow we use in this way. Any suggestions?

**Comment by bradwilson** [comment]
This should be covered by https://github.com/xunit/xunit/issues/1758 in v3.

**Comment by carlin-q-scott** [comment]
Is this addressed by [ITheoryDataRow](https://github.com/xunit/xunit/commit/85fc86b4e5b1f69658169b6289733f05775f4aae)? I don't see how I can use that with the InlineDataAttribute.

**Comment by bradwilson** [comment]
Good catch, this was not yet introduced onto `[InlineData]` itself, only the underlying infrastructure.

**Comment by bradwilson** [comment]
Subsumed by #2545
