### ISSUE TITLE
On Linux CI agent ~22 tests were reported as long running tests where the machine has only 2 cores.

### ISSUE THREAD

**Issue by kartheekp-ms** [xunit/xunit#2179]
* Is this a question? No, I don't think so.

* Is this a bug with VSTest (aka Visual Studio Test Explorer, `dotnet test`, `dotnet vstest`,  or `vstest.console.exe`)? Open those issues here:  May be, but not sure as of now.
  https://github.com/xunit/visualstudio.xunit/issues/

* Did you search the docs @ https://xunit.net/ ? Yes

* Did you search the issues list to see if someone already reported it? No one has reported it.

* Did you create a simple repro for the problem? This happens only on CI. **I tried to repro the issue several times on an Ubuntu VM with similar configuration but no luck.**

On CI - Ubuntu agent, we were able to rero hang frequently while running multiple test assemblies using dotnet test/vstest and xUnit. We have enabled `longRunningTestSeconds` in `xunit.runner.json` to help detect hang detection while running tests in parallel. Our CI - Ubuntu agent (18.04 LTS) has only 2 cores but when there is a hang, xUnit reports around 22 tests as long running tests. I am not sure why 22 tests were reported as long running even though the machine has only 2 cores and we expect only 2 tests to run in parallel. There could be a possibility that I am missing something here, but any additional guidance is helpful.

```log
  [xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.1 (64-bit .NET Core 4.6.28008.02)
  [xUnit.net 00:00:00.72]   Discovering: NuGet.Commands.Test (method display = ClassAndMethod, method display options = None)
  [xUnit.net 00:00:01.02]   Discovered:  NuGet.Commands.Test (found 952 test cases)
  [xUnit.net 00:00:01.03]   Starting:    NuGet.Commands.Test (parallel test collections = on, max threads = 2)

> after running few tests in parallel xunit reports 22 tests as long running.

[xUnit.net 00:02:13.08] NuGet.Commands.Test: [Long Running Test] 'NuGet.Commands.Test.DependencyTypeConstraintTests.DependencyTypeConstraint_PackagesDependOnProjectAsync', Elapsed: 00:02:11
  [Long Running Test] 'NuGet.Commands.Test.OriginalCaseGlobalPackageFolderTests.CopyPackagesToOriginalCaseAsync_WhenPackageComesFromLocalFolder_ConvertsPackagesAsync', Elapsed: 00:02:04
  [Long Running Test] 'NuGet.Commands.Test.CompatilibityCheckerTests.CompatilibityChecker_SingleFileVerifyCompatibilityAsync(file: "build/_._", expected: True)', Elapsed: 00:02:03
  [Long Running Test] 'NuGet.Commands.Test.DotnetCliToolTests.DotnetCliTool_ToolRestoreNoOpsRegardlessOfProject', Elapsed: 00:02:11
  [Long Running Test] 'NuGet.Commands.Test.RestoreSemVerTests.RestoreSemVer_RestorePackageWithMultipleReleaseLabelsAsync', Elapsed: 00:02:03
  [Long Running Test] 'NuGet.Commands.Test.RestoreResultTests.RestoreResult_WritesCommitToInformation_AssetsAndCache', Elapsed: 00:02:03
  [Long Running Test] 'NuGet.Commands.Test.RestoreRunnerTests.RestoreRunner_MultiplePackageDownloadRestoreAsync', Elapsed: 00:02:08
  [Long Running Test] 'NuGet.Commands.Test.IncludeTypeTests.IncludeType_SingleProjectEquivalentToTheDefaultAsync(projectJson: "{\n                        \"dependencies\": {\n  "...)', Elapsed: 00:02:03
  [Long Running Test] 'NuGet.Commands.Test.StandaloneProjectTests.StandaloneProject_BasicRestore', Elapsed: 00:02:08
  [Long Running Test] 'NuGet.Commands.Test.RestoreCommandTests.RestoreCommand_ObservesLowercaseFlagAsync(isLowercase: False)', Elapsed: 00:02:03
  [Long Running Test] 'NuGet.Commands.Test.NETCoreProject2ProjectTests.NETCoreProject2Project_VerifyCompileForTransitiveSettings(expected: "BDXY", ab: True, bc: False, cd: True, ax: True, xy: True, yd: True)', Elapsed: 00:02:03
  [Long Running Test] 'NuGet.Commands.Test.ContentFilesMSBuildTests.ContentFilesMSBuild_VerifyConditionForContentItemGroupWithoutCrossTargetingAsync(file: "contentFiles/fs/any/x.txt", expected: "'$(Language)' == 'F#' AND '$(ExcludeRestorePackage"...)', Elapsed: 00:02:08
  [Long Running Test] 'NuGet.Commands.Test.RestoreBuildTargetsAndPropsTests.RestoreBuildTargetsAndProps_VerifyRestoreChangeAsync', Elapsed: 00:02:08
  [Long Running Test] 'NuGet.Commands.Test.FallbackFolderRestoreTests.FallbackFolderRestore_AllPackagesFoundInFallback_NuspecModeAsync', Elapsed: 00:02:03
  [Long Running Test] 'NuGet.Commands.Test.ContentFilesTests.ContentFiles_NormalizeBuildActionNames', Elapsed: 00:02:03
  [Long Running Test] 'NuGet.Commands.Test.TrustedSignerActionsProviderTests.SyncTrustedRepositoryAsync_WithExistingRepositoryItem_UpdatesCertificatesInItemWithLatestFromRepositoryAsync', Elapsed: 00:02:03
  [Long Running Test] 'NuGet.Commands.Test.RuntimePackageTests.RuntimePackage_RejectedPackagesAreNotMerged', Elapsed: 00:02:03
  [Long Running Test] 'NuGet.Commands.Test.Project2ProjectTests.Project2ProjectInLockFile_PackageReferenceConflict', Elapsed: 00:02:03
  [Long Running Test] 'NuGet.Commands.Test.BuildAssetsUtilsTests.BuildAssetsUtils_GeneratePathProperty', Elapsed: 00:02:03
  [Long Running Test] 'NuGet.Commands.Test.RuntimeTargetsTests.RestoreTargets_RestoreWithRuntimes_ExcludeAllAsync', Elapsed: 00:02:03
  [Long Running Test] 'NuGet.Commands.Test.ProjectResolutionTests.ProjectResolution_ProjectFrameworkAssemblyReferences', Elapsed: 00:02:03

```

**Comment by bradwilson** [comment]
Do the tests ever finish? If not, it sounds like you have a deadlock (the most common cause of which is improper use of async).

If they finish, it's possible simply that they are running longer than expected because the machine in question is slower.

As for this:

>I am not sure why 22 tests were reported as long running even though the machine has only 2 cores and we expect only 2 tests to run in parallel.

While it's true that only 2 tests will actually be running simultaneously, that doesn't mean more than 2 tests have been started. Imagine this scenario

You write 3 tests which all do this:

```csharp
public class Class1
{
    [Fact]
    public async Task LongRunning1()
    {
        await Task.Delay(5000);
    }
}

public class Class2
{
    [Fact]
    public async Task LongRunning2()
    {
        await Task.Delay(5000);
    }
}

public class Class3
{
    [Fact]
    public async Task LongRunning3()
    {
        await Task.Delay(5000);
    }
}
```

What happens is we'll start two tests (at random, but let's just say it was `LongRunning1` and `LongRunning2`. As soon as we hit the `await` in one of them, it returns the thread back to the thread pool to do more work. This means it will start `LongRunning3` almost immediately as well.

All 3 will finish at roughly the same time, and the total clock time involved will only look like ~ 5 seconds, because all the actual time spent running was actually spent waiting. Our thread limitation is based on what can _run_ and not on what is _waiting_.

**Comment by zivkan** [comment]
> Our thread limitation is based on what can run and not on what is waiting.

This is very interesting, although to be honest I find it unintuitive from a user perspective. It totally makes sense from a technical perspective, knowing how async works in .NET. The "running test in parallel" docs page doesn't mention async at all on the page. I think it would be worthwhile to add. https://xunit.net/docs/running-tests-in-parallel

I understand how the behaviour you described is desirable for some scenarios. Would xunit consider adding an option to wait for async tests to complete?

I can explain scenarios if you like, but we (I work with Kartheek on the NuGet client) have some flaky tests that fail with various timeouts, and I think there's a real possibility that running so many async tests in parallel contribute. This might mean we need to do normally undesirable things like removing the `async` keyword from all tests and using `.Result` to block the thread and avoid more tests running in parallel than we expect/the machine has resources to process in parallel.

**Comment by bradwilson** [comment]
>we have some flaky tests that fail with various timeouts

We are _**very explicit**_ that our timeout feature has undefined behavior when you parallelize tests:

https://github.com/xunit/xunit/blob/a8614d34999c889e1c8014f679de95d20eae1304/src/xunit.core/FactAttribute.cs#L26-L32

Your solution today is to put your flaky tests into a parallelization-disabled test collection:

https://github.com/xunit/xunit/blob/a8614d34999c889e1c8014f679de95d20eae1304/src/xunit.core/CollectionDefinitionAttribute.cs#L20-L23

**Comment by zivkan** [comment]
Sorry, I should have been more clear. We have integration tests that launches `nuget.exe` or `dotnet.exe` as a separate process, and we do our own timeout checking. Other tests might be using `HttpClient`, and responses timeout. We're not using xunit's timeouts.

It's hard to understand why a test that is doing very little doesn't complete within 100 seconds, unless the 2 core machine is running far more than 2 tests in parallel and there's too much CPU work for it to do before these timeouts occur.

While we could create two collections and assign every test class into one of these two, it means 1. we'd need to constantly figure out the balance to ensure that one collection doesn't finish much earlier than the other, therefore losing the benefits of running tests in parallel. 2. It would also mean if our CI agents happen to get more CPUs in the future, we won't benefit from faster test execution. 3. Every time anyone adds a new test class, we have to remember that the class must be in one of the collections. Frankly, I think having a blanket ban on async tests and using `Task.Run(...).Result` is better.

**Comment by bradwilson** [comment]
> Sorry, I should have been more clear. We have integration tests that launches `nuget.exe` or `dotnet.exe` as a separate process, and we do our own timeout checking. Other tests might be using `HttpClient`, and responses timeout. We're not using xunit's timeouts.

The same reason we can't accurately measure "time consumed in the test" when things are being run in parallel, so too everything else will have the same problems.

> It's hard to understand why a test that is doing very little doesn't complete within 100 seconds, unless the 2 core machine is running far more than 2 tests in parallel and there's too much CPU work for it to do before these timeouts occur.

The way we've designed parallelism is an attempt to maximize CPU usage. When a test is in a "wait", we go look for something else to do so we can keep the CPU busy.

> Frankly, I think having a blanket ban on async tests and using `Task.Run(...).Result` is better.

That's definitely a reasonable alternative for your specific situation.

**Comment by zivkan** [comment]
So, to me it sounds like xunit does not have any options to allow me to choose my preferred async tests in parallel behaviour and my previous request to add such an option was unconvincing. That's fine, we couldn't have known without reporting our problem here. Now we know and can investigate alternatives.

I still think that this async behaviour should be documented on https://xunit.net/docs/running-tests-in-parallel. We spent time investigating this, so there's a chance that other customers will as well.

Unless @kartheekp-ms has additional questions, I think this issue can be closed.

**Comment by kartheekp-ms** [comment]
Thank you @zivkan for following up on this issue.

> I still think that this async behavior should be documented on https://xunit.net/docs/running-tests-in-parallel.

I agree.

@bradwilson Thank you for guidance on how `xUnit` runs `async` tests in parallel. I have one follow-up question before we close this issue i.e. I see that `xUnit` has an option called [`maxParallelThreads`](https://xunit.net/docs/configuration-files#maxParallelThreads) `Use a value of 0 to indicate that you would like the default behavior which is the number of logical processors in your PC; use a value of -1 to indicate that you do not wish to limit the number of threads used for parallelization. ` We are using default value now, I think using `"maxParallelThreads": -1` is not an option for us because we were able to reproduce hangs with the `default value` unless there is undocumented behavior which we should be aware of.

> Do the tests ever finish? If not, it sounds like you have a deadlock (the most common cause of which is improper use of async).

No. Usually, the test project in question completes test execution with parallelism enabled in few seconds unless there is a hang. We have CI job timeout set to 45 min which cancels running steps.

**Comment by bradwilson** [comment]
Max parallel threads of `-1` should indeed stop any deadlocks. It also will not limit the number of simultaneous running threads (it uses the built in `ThreadPool` instead).

**Comment by kartheekp-ms** [comment]
> Max parallel threads of -1 should indeed stop any deadlocks.

This comment confuses me a bit because doc says set `maxParallelThreads: -1` to use unlimited threads. There is a possibility that I could be looking at wrong place in the source code.

https://github.com/xunit/xunit/blob/6bc9543856f17cd69ec96e63307529edec2c60cd/src/xunit.v3.runner.utility/Runners/AssemblyRunner.cs#L229

**Comment by kartheekp-ms** [comment]
I am closing this issue since we are not blocked by [above](https://github.com/xunit/xunit/issues/2179#issuecomment-722569811) comment.
