### ISSUE TITLE
not able to read the Test Outcome or the Message object from the test results. 

### ISSUE THREAD

**Issue by mdaher** [xunit/xunit#2180]
I want to read the Test Outcome or the Message object from the dispose method. I tried using ITestOutputHelper but It doesn't hold any information about the test results. Please see attachment

![TestResult](https://user-images.githubusercontent.com/5772349/97698232-98ff4600-1a7e-11eb-8cd2-4a16095cfa00.JPG)

**Comment by bradwilson** [comment]
Dup of #2178
