### ISSUE TITLE
Multiple ITraitAttributes are not honored via inheritance when a child class has one attribute and base class another

### ISSUE THREAD

**Issue by safern** [xunit/xunit#2186]
If you have a test setup like this:

```cs
[Trait("category", "failing")]
public abstract class BaseClassWithFailingCategory
{
    [Fact]
    public virtual void Test1()
    {
        Assert.False(true);
    }
}

[Trait("category", "foo")]
public class DerivedClassWithFooCategory : BaseClassWithFailingCategory
{
    [Fact]
    public void Test2()
    {
        Assert.False(true);
    }
}
```

and then run these tests with `-notrait category=failing` the tests under `DerivedClassWithFooCategory` will be executed. The only way to skip them, it would be to run them with `-notrait category=foo` or by adding a duplicate `TraitAttribute` into `DerivedClassWithFooCategory` that adds the `failing` category to it's traits.

```
Discovering: MyRunner.dll (method display = ClassAndMethod, method display options = None)
Discovered:  MyRunner.dll (found 2 of 2 test cases)
Starting:    MyRunner.dll
[FAIL] ConsoleApp1.DerivedClassWithFooCategory.Test1
Assert.False() Failure
Expected: False
Actual:   True
   at ConsoleApp1.BaseClassWithFailingCategory.Test1() in C:\Users\safern\source\repos\XUnitTestProject1\ConsoleApp1\Program.cs:line 74
[FAIL] ConsoleApp1.DerivedClassWithFooCategory.Test2
Assert.False() Failure
Expected: False
Actual:   True
   at ConsoleApp1.DerivedClassWithFooCategory.Test2() in C:\Users\safern\source\repos\XUnitTestProject1\ConsoleApp1\Program.cs:line 84
Finished:    MyRunner.dll
```

It seems like the intent to support this is there: https://github.com/xunit/xunit/blob/6bc9543856f17cd69ec96e63307529edec2c60cd/src/xunit.v3.core/Sdk/Reflection/ReflectionAttributeInfo.cs#L115

And AttributeUsage data for `ITraitAttribute` allow's multiple and allows inheritance, so that condition should be true:
https://github.com/xunit/xunit/blob/6bc9543856f17cd69ec96e63307529edec2c60cd/src/xunit.v3.core/Sdk/Reflection/ReflectionAttributeInfo.cs#L16-L19

However I don't know why both traits are not added to tests under `DerivedClassWithFooCategory`

cc: @stephentoub @akoeplinger @ViktorHofer @bradwilson

**Comment by bradwilson** [comment]
I'm pretty sure this is fixed in v3. https://github.com/xunit/xunit/pull/1958

**Comment by bradwilson** [comment]
Original issue: #1397

**Comment by safern** [comment]
Thanks, @bradwilson
