### ISSUE TITLE
Missing documentation on xunit.github.io/xunit.analyzers

### ISSUE THREAD

**Issue by kevinoid** [xunit/xunit#2187]
The [xunit.analyzers README.md](https://github.com/xunit/xunit.analyzers/blob/v0.10.0/README.md) states:

> a list of supported rules is available at https://xunit.github.io/xunit.analyzers/

Unfortunately, https://xunit.github.io/xunit.analyzers/ displays "404 File not found".

This also affects the [rule `helpLink`](https://github.com/xunit/xunit.analyzers/blob/v0.10.0/src/xunit.analyzers/Descriptors.cs#L21).  For example, clicking on [xUnit2003](https://xunit.github.io/xunit.analyzers/rules/xUnit2003) in the VS Error List opens a browser for https://xunit.github.io/xunit.analyzers/rules/xUnit2003 which also displays "404 File not found".

Thanks,
Kevin

**Comment by bradwilson** [comment]
I think this is a dup of #2175 which I haven't fixed yet (because I forgot about it 😞). I'll work to fix it this weekend.

**Comment by kevinoid** [comment]
Yes indeed.  Not sure how I missed that.  Sorry for the duplicate.  Thanks for looking into it!
