### ISSUE TITLE
Analyzers don't require correct 'nullness' for MemberData and InlineData attributes for reference parameters

### ISSUE THREAD

**Issue by michsco** [xunit/xunit#2189]
The analyzers for the `InlineData` and `MemberData` attributes don't detect when a reference parameter could be null. This is especially painful when tests are being migrated to support nullable reference types.

In the following example, if nullable is enabled for this code, I'd expect the analyzer to detect that `value` should be `object?`.

```csharp
using Xunit;

namespace SomeNamespace
{
    public class SomeClass
    {
        [Theory]
        [InlineData("foo", null)]
        public void SomeMethod(string name, object value)
        {
        }
    }
}
```

I'd expect the same with the `MemberData` scenario if the return of the method is `IEnumerable<object?>` as this indicates there can be null values for some of the parameters.

```csharp
using Xunit;

namespace SomeNamespace
{
    public class SomeClass
    {
        [Theory]
        [MemberData(nameof(TestCaseScenario))]
        public void SomeMethod(string name, object value)
        {
        }

        public static IEnumerable<object?> TestCaseScenario()
        {
            // ...
        }
    }
}
```

I am not sure if this is considered a duplicate for #1897 or will be covered by #2133.

**Comment by louis-z** [comment]
I'd like to give it a shot.

**Comment by JamesTerwilliger** [comment]
@bradwilson I've created a partial fix for handling the InlineDataAttribute case: https://github.com/xunit/xunit.analyzers/pull/164

**Comment by JamesTerwilliger** [comment]
@bradwilson I've created a fix for the rest of the issue (MemberData) as well as two fixers for the analyzer warnings. May need more fixers, will think about it - one case (changing IEnumerable<object[]> to IEnumerable<object?[]>) could probably be done with a fixer.

**Comment by JamesTerwilliger** [comment]
@bradwilson Adding one more PR for TheoryData analyzers https://github.com/xunit/xunit.analyzers/pull/166

Hopefully that clears out this Jira item as much as we'd like to go

**Comment by bradwilson** [comment]
@JamesTerwilliger You're giving me PTSD with "Jira" 😂 

Thanks for all the PRs! I'm considering this done for now, and if anybody finds any other holes, they can open a new issue.
