### ISSUE TITLE
Disabling appDomain for .NET 4.8 tests changes ResourceManager behavior

### ISSUE THREAD

**Issue by Crono1981** [xunit/xunit#2195]
I have a test project that uses an `xunit.runner.json` config file which has `appDomain` property set to "denied". This is to circumvent a different issue about strongly named assemblies and code coverage.

I am testing a few extension methods I've made on top of `System.Resources.ResourceManager` type. To do so, I created a dummy resource files within the test project itself, named `DummyRes.resx`, and an additional `DummyRes.en-CA.resx` file for Canada-specific string values.

At some point in my test, a localized string will be fetched from a resource manager instance, using a `CultureInfo` object with `en-CA` as the code.

```
// NOTE: Not the actual test's code. This is just pseudo to explain the behavior.
var s = manager.GetString("MyResource", new CultureInfo("en-CA"));
```

Unfortunately, the value for `s` will be the one specified in `DummyRes.resx`, *not* the one in `DummyRes.en-CA.resx`.

On investigating the issue, I've found that if I removed the `appDomain` setting from `xunit.runner.json` file, the test behaves as expected.

So it would seem that for some reason, the test engine is not loading the satellite assemblies created in `<output directory>/en-CA` whenever application domains are not used to isolate tests.

How can I work around this while keeping the application domains feature disabled?

**Comment by bradwilson** [comment]
Yeah, there's nothing we do about this. This is behavior from .NET, not from us. Sorry. 😞

**Comment by Crono1981** [comment]
Ah, that's unfortunate. 😔

Out of curiosity, can you tell if the behavior you speak of is the same as the one causing the issue described [here](https://stackoverflow.com/questions/99642/resourcemanager-and-unit-testing)?

**Comment by bradwilson** [comment]
Not sure, but it could be. xUnit.net doesn't have anything equivalent to `DeploymentItem` in MSTest. We generally recommend people embed files as resources if they can't count on the normal build system to copy them into the right location.
