### ISSUE TITLE
Add default implementations of IAsyncLifetime

### ISSUE THREAD

**Issue by chillitom** [xunit/xunit#2198]
Would be nice to have default implementations on IAsyncLifetime, something like the following.  Then either can be implemented optionally.

```csharp
namespace Xunit
{
  /// <summary>
  /// Used to provide asynchronous lifetime functionality. Currently supported:
  /// - Test classes
  /// - Classes used in <see cref="T:Xunit.IClassFixture`1" />
  /// - Classes used in <see cref="T:Xunit.ICollectionFixture`1" />.
  /// </summary>
  public interface IAsyncLifetime
  {
    /// <summary>
    /// Called immediately after the class has been created, before it is used.
    /// </summary>
    Task InitializeAsync() => Task.CompletedTask;
    /// <summary>
    /// Called when an object is no longer needed. Called just before <see cref="M:System.IDisposable.Dispose" />
    /// if the class also implements that.
    /// </summary>
    Task DisposeAsync() => Task.CompletedTask;
  }
}
```

I wanted to submit a PR but noticed that V3 `IAsyncLifetime` now extends `IAsyncDisposable`, not sure of the consequences of this.

**Comment by bradwilson** [comment]
Unfortunately this requires target platform support and not just compiler support, and this feature isn't available in `netstandard2.0`:

![CS8701: Target runtime doesn't support default interface implementation](https://user-images.githubusercontent.com/16944/99886854-a8446000-2bf4-11eb-9f4c-940fd63d487f.png)

**Comment by chillitom** [comment]
Interesting, would it be possible to support it then with target conditional compilation? 

```csharp
public interface IAsyncLifetime : IAsyncDisposable
{
#if NETSTANDARD2_1
     ValueTask InitializeAsync() => default;
     ValueTask IAsyncDisposable.DisposeAsync() => default;
#else
     ValueTask InitializeAsync();
#endif
}
````
It seems like there are many cases where you might wish to perform some action only in initialization or cleanup  but not both.  If `#if`s are out of the question maybe we could have a pair of interfaces `IAsyncInitialize` / `IAsyncCleanup`.

**Comment by chillitom** [comment]
Went with the _DIY_ method in own project:
```csharp
    public interface IAsyncInitialise : IAsyncLifetime {
        // make the DisposeAsync method optional
        Task IAsyncLifetime.DisposeAsync() => Task.CompletedTask;
    }
```

**Comment by bradwilson** [comment]
Closing this as Won't Fix, since we don't want multiple binaries (it unnecessarily complicates the extensibility story).
