### ISSUE TITLE
Support running test assemblies under their target framework version

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#22]
Currently, the MSBuild runner always runs tests under .NET 4.0, and the VS 2012 runner always runs tests under .NET 4.5. This behavior means that some tests that pass in the MSBuild runner fail in the VS 2012 runner and vice versa.

In order to remove this discrepancy, the test executor would need to ensure the AppDomain in which the test assembly is loaded is using the matching target framework version (either using the default AppDomain for the process and routing through separate executables per target framework version or creating separate AppDomains manually within the same process).

One way to remove this discrepancy would be to use AppDomainSetup.TargetFrameworkName when creating an AppDomain; see the related discussion for a code snippet (http://xunit.codeplex.com/discussions/401293).

**Comment by MiniverCheevy** [comment]
Wouldn't it be useful to be able to run tests against multiple frameworks to ensure backwards compatibility?

**Comment by bradwilson** [comment]
I believe that, at the moment, we're unable to do anything about this, since it requires launching the tests into a separate process, which completely breaks the debugging experience.
