### ISSUE TITLE
xunit.runner.console Unhandled exception thrown if dll under test is missing

### ISSUE THREAD

**Issue by vrodaxAptos** [xunit/xunit#2208]
If you attempt to run a test on a dll and the dll is missing the console will report an unhandled exception and Windows error reporting displays a dialog box stating "xUnit.new Console Test Runner (.NET 4.6.1) has stopped working" with Debug and Close Program buttons.  This causes an automated build process to hang.  Please either handle the file not found exception or add an unhandled exception handler so that the exception can be handled and the program exit with a normal error code.

Right now I am working around the issue by testing for the existence of the file before running the command.

Repro steps:
Run the following command line:

xunit.runner.console nonExistingFile.dll -xml results.xml

where: nonExistingFile.dll is a file that does not exist.

**Comment by bradwilson** [comment]
Thanks, that's a good catch! The CommandLine.Parse call is outside of our try/catch. I couldn't reproduce the Windows popup, but that may be a difference in our environments and/or how we're invoking the executable (I'm doing it from an interactive PowerShell command line).
