### ISSUE TITLE
Docs page for netfx is out of date

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#2209]
The specific issue is that https://xunit.net/docs/getting-started/netfx/visual-studio#run-tests-visualstudio is missing instructions on adding a reference to `Microsoft.NET.Test.Sdk` which is now required rather than implied. That definitely needs to be fixed.

That said, this page is really out of date. Last time it had updated images was xUnit.net v2.2, so it could probably use an overhaul anyway with some new VS2019-style issues, and maybe even a section on support for SDK-style `.csproj` files.

**Comment by amaroniz** [comment]
It appears that the netfx documentation has already been updated to specify that `Microsoft.NET.Test.Sdk` is required.

**Comment by bradwilson** [comment]
You are correct @amaroniz!
