### ISSUE TITLE
Add configuration element to disable pre-enumeration of [Theory] data

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#221]
This would revert back to 1.x behavior of a single test case for the theory. This feature is primarily about re-enabling CodeLens in Visual Studio for those users who want that, but it can also make discovery faster by not pre-enumerating the theories (at the expense of being able to run just a single set of data).

**Comment by danrub** [comment]
please add ability to disable pre-enumeration of Theories by test basis.
maybe: [Theory(PreEnumerate=false)]

Take for an example, unit test, with data provider that provides thousands of use cases to check. the discovery process can take about one minute or more at each compilation.

in our case, we have an excel data provider with 12,000 rows, every addition or change inside unit test assembly causing a significant delay of about 2 min, before the discovery process is completed and we can run tests.

although disabling the feature at assembly level, is nice feature, and can fix our issue, we don't want to disable all pre-enumeration discovery, only for this specific unit test, which is unique within all other test cases.

**Comment by bradwilson** [comment]
We have opted, instead, to enable this at a data attribute level rather than the theory level, since the data attribute is the best position to know whether it should pre-enumerate. When the attribute can't make the decision, it can offer to expose that decision to the end user, like we did here with `MemberAttribute`:

https://github.com/xunit/xunit/blob/master/src/xunit.core/MemberDataAttribute.cs#L33-L38
https://github.com/xunit/xunit/blob/master/src/xunit.core/Sdk/MemberDataDiscoverer.cs#L11-L14

You should consider implementing this on your long-running data attributes.

**Comment by danrub** [comment]
Thanks! this is what we have been looking for :)
