### ISSUE TITLE
Building xUnit.net on Windows failed 

### ISSUE THREAD

**Issue by tonyhallett** [xunit/xunit#2216]
Forked the repo and then ran ./build restore build.

Receiving 
error CS8604: Possible null reference argument
error CS8600: Converting null literal or possible null value to non-nullable type

C:\Users\tonyh\Source\Repos\xunit\xunit\src\xunit.v3.runner.common\Sinks\DelegatingSinks\DelegatingXmlCreationSink.cs(106,38): error CS8604: Possible null reference argument for parameter 'value' in 'XAttribute.XAttribute(XName name, object value)'. [C:\Users\tonyh\Source\Repos\xunit\xunit\src\xunit.v3.runner.common\xunit.v3.runner.common.csproj]
C:\Users\tonyh\Source\Repos\xunit\xunit\src\xunit.v3.runner.common\Transforms\TransformFactory.cs(91,44): error CS8604: Possible null reference argument for parameter 'input' in 'XmlReader XmlReader.Create(Stream input)'. [C:\Users\tonyh\Source\Repos\xunit\xunit\src\xunit.v3.runner.common\xunit.v3.runner.common.csproj]
C:\Users\tonyh\Source\Repos\xunit\xunit\src\xunit.v3.runner.common\Sinks\DelegatingSinks\DelegatingXmlCreationSink.cs(274,28): error CS8604: Possible null reference argument for parameter 'value' in 'XAttribute.XAttribute(XName name, object value)'. [C:\Users\tonyh\Source\Repos\xunit\xunit\src\xunit.v3.runner.common\xunit.v3.runner.common.csproj]
C:\Users\tonyh\Source\Repos\xunit\xunit\src\xunit.v3.runner.common\Transforms\TransformFactory.cs(91,44): error CS8604: Possible null reference argument for parameter 'input' in 'XmlReader XmlReader.Create(Stream input)'. [C:\Users\tonyh\Source\Repos\xunit\xunit\src\xunit.v3.runner.common\xunit.v3.runner.common.csproj]
C:\Users\tonyh\Source\Repos\xunit\xunit\src\xunit.v3.runner.common\Sinks\DelegatingSinks\DelegatingXmlCreationSink.cs(106,38): error CS8604: Possible null reference argument for parameter 'value' in 'XAttribute.XAttribute(XName name, object value)'. [C:\Users\tonyh\Source\Repos\xunit\xunit\src\xunit.v3.runner.common\xunit.v3.runner.common.csproj]
C:\Users\tonyh\Source\Repos\xunit\xunit\src\xunit.v3.runner.common\Sinks\DelegatingSinks\DelegatingXmlCreationSink.cs(274,28): error CS8604: Possible null reference argument for parameter 'value' in 'XAttribute.XAttribute(XName name, object value)'. [C:\Users\tonyh\Source\Repos\xunit\xunit\src\xunit.v3.runner.common\xunit.v3.runner.common.csproj]
C:\Users\tonyh\Source\Repos\xunit\xunit\src\xunit.v3.core\Sdk\Frameworks\Runners\TestAssemblyRunner.cs(241,36): error CS8604: Possible null reference argument for parameter 'path' in 'void Directory.SetCurrentDirectory(string path)'. [C:\Users\tonyh\Source\Repos\xunit\xunit\src\xunit.v3.core\xunit.v3.core.csproj]
C:\Users\tonyh\Source\Repos\xunit\xunit\src\xunit.v3.core\Sdk\TraitHelper.cs(60,14): error CS8600: Converting null literal or possible null value to non-nullable type. [C:\Users\tonyh\Source\Repos\xunit\xunit\src\xunit.v3.core\xunit.v3.core.csproj]
C:\Users\tonyh\Source\Repos\xunit\xunit\src\xunit.v3.core\Sdk\Frameworks\TestFrameworkDiscoverer.cs(322,36): error CS8604: Possible null reference argument for parameter 'path' in 'void Directory.SetCurrentDirectory(string path)'. [C:\Users\tonyh\Source\Repos\xunit\xunit\src\xunit.v3.core\xunit.v3.core.csproj]
C:\Users\tonyh\Source\Repos\xunit\xunit\src\xunit.v3.core\Sdk\Reflection\ReflectionAssemblyInfo.cs(82,48): error CS8604: Possible null reference argument for parameter 'type' in 'IReflectionTypeInfo Reflector.Wrap(Type type)'. [C:\Users\tonyh\Source\Repos\xunit\xunit\src\xunit.v3.core\xunit.v3.core.csproj]
C:\Users\tonyh\Source\Repos\xunit\xunit\src\xunit.v3.core\Sdk\Reflection\ReflectionAttributeInfo.cs(62,11): error CS8600: Converting null literal or possible null value to non-nullable type. [C:\Users\tonyh\Source\Repos\xunit\xunit\src\xunit.v3.core\xunit.v3.core.csproj]

I am building as I want to debug the source as my custom FactAttribute / IXunitTestCaseDiscoverer is not behaving as anticipated.  
I need to debug the test running code - e.g https://github.com/xunit/xunit/blob/a8f55d61022f39362ff10c1f73eab0cb965c2619/src/xunit.v3.core/Sdk/Frameworks/Runners/TestRunner.cs#L237 but also from version 2.4.1.  

I checked out the V2 branch but Building.md said 

> For information on building xUnit.net, please see [our documentation page](https://xunit.github.io/docs/building-xunit.html).
but could not find anything in the repo.

Any suggestions of where I can get pdbs without building ? Visual studio decompiling did not work.  I could try DotPeek symbol server as a last resort.

**Comment by dharmaturtle** [comment]
I'm also having an issue with custom `FactAttribute`s, in particular with netcoreapp. I forked the `sample` project [here](https://github.com/dharmaturtle/samples.xunit), created a new project (`RetryFactExampleNetCore`) using the default visual studio xUnit template, and copied the files from `RetryFactExample` to it. The `RetryFactSample` test is discovered, but it isn't run:

![image](https://user-images.githubusercontent.com/1278803/102386959-68735d00-3f95-11eb-98fc-ce8481e61095.png)

It is not discovered by `dotnet test`.

![image](https://user-images.githubusercontent.com/1278803/102387497-1121bc80-3f96-11eb-9ba6-539ed265668e.png)

I've tested with `dotnet sdk 3.1.301` & `netcoreapp3.1`, and with dotnet sdk `2.2.401` & `netcoreapp2.1`.

**Comment by tonyhallett** [comment]
@dharmaturtle I am not at my computer so cannot check the args to the attribute below. Are they correct ?
XunitTestCaseDiscoverer("RetryFactExample.RetryFactDiscoverer........ 
Add a Debugger.Launch in the discoverer to check that it gets loaded

**Comment by dharmaturtle** [comment]
Yes, I believe the `XunitTestCaseDiscoverer` is correct. It's in a different assembly (`RetryFactExampleNetCore`) but retains the namespace (`RetryFactExample`). I literally just copy/pasted the (working) sample code to a new xUnit test project that targets dotnet core.

Adding `System.Diagnostics.Debugger.Launch();` to both the ctor and `Discover` method of `RetryFactDiscoverer` does _not_ cause the debugger to open:

![image](https://user-images.githubusercontent.com/1278803/102400831-0d973100-3fa8-11eb-8608-ae7474e8525d.png)

Adding it to `Test1` (the automatically added test added when creating a new xUnit test project) _does_ cause the debugger to open.

**Comment by tonyhallett** [comment]
@dharmaturtle Now that I have access to my computer I can see that this is incorrect

`[XunitTestCaseDiscoverer("RetryFactExample.RetryFactDiscoverer", "RetryFactExample")]`

The second argument is the assembly name.

The namespace may be RetryFactExample but the assembly is RetryFactExampleNetCore - and that is why the discoverer is not loaded, the debugger not attached and ultimately the test is not found.

**Comment by dharmaturtle** [comment]
@tonyhallett you're correct. This resolves my issue; thanks! It's the simplest things 🙄

---

I'm also getting the same issue when trying to build off master.

However, if I find/replace `<Nullable>enable</Nullable>` with `<Nullable>annotations</Nullable>`, `./build` works for me.

![image](https://user-images.githubusercontent.com/1278803/102407735-2efd1a80-3fb2-11eb-8657-ae6c8dc1f981.png)

**Comment by tonyhallett** [comment]
@dharmaturtle that change does allow the build to proceed.  Thanks.  

Going to keep the issue open though.

**Comment by tonyhallett** [comment]
For anyone else wanting to debug in to the source code for version 2 the following worked for me.

Download the repo 
Checkout v2 branch
Add new function breakpoint and when hit point visual studio to the local file.

Also the reason my custom discoverer was not working was due to the requirement to Serialize/Deserialize members of my custom XUnitTestCase derivation.

**Comment by bradwilson** [comment]
I believe that you caught a moment where we had some nullable things that needed to get cleaned up, which ended up getting cleaned up here: f4851cc2219e8d507a7fb18989195d5e5ab02221

Please try pulling latest from `main` and let me know if you have any more issues. Thanks!
