### ISSUE TITLE
ITestCaseOrderer is only asked to order *some* of the cases

### ISSUE THREAD

**Issue by godefroi** [xunit/xunit#2217]
ITestCaseOrderer is only asked to order *some* of the cases; I would expect that *all* of the cases that will be run are included in the call to `OrderTestCases`. The following test fails:

```cs
using System.Collections.Generic;
using System.Linq;
using Xunit;
using Xunit.Abstractions;
using Xunit.Sdk;

[assembly:TestCaseOrderer("TheOrderer", "xunit_orderer_repro")]

public class TheOrderer : ITestCaseOrderer
{
	public IEnumerable<TTestCase> OrderTestCases<TTestCase>(IEnumerable<TTestCase> testCases) where TTestCase : ITestCase
	{
		testCases = testCases.ToList();
		UnitTest1.CaseCount = testCases.Count();
		return testCases;
	}
}

public class UnitTest1
{
	public static int CaseCount { get; set; }

	[Fact]
	public void Test1()
	{
		Assert.Equal(2, CaseCount);
	}
}

public class UnitTest2
{
	[Fact]
	public void Test2()
	{
		Assert.Equal(2, UnitTest1.CaseCount);
	}
}
```

My run of these tests:
![image](https://user-images.githubusercontent.com/7189728/102396738-1aad2380-3f9a-11eb-88a0-b5ed03b8b64c.png)

Both tests were run, but the orderer was only asked to order one of them.

**Comment by bradwilson** [comment]
Actually, it was asked to order them both, but separately.

The test case orderer is called once per test collection. By default, each test class is its own test collection. So you should've seen two calls to your orderer, once with the test case from UnitTest1, and once with the test case from UnitTest2. You could update your test slightly to see this result, by changing this:

```csharp
UnitTest1.CaseCount = testCases.Count();
```

to this:

```csharp
UnitTest1.CaseCount += testCases.Count();
```

**Comment by godefroi** [comment]
Maybe you mean something other than "once per test collection"? Maybe you mean "once per test class"? I updated my repro code:

```cs
using System.Collections.Generic;
using System.Linq;
using Xunit;
using Xunit.Abstractions;
using Xunit.Sdk;

[assembly:TestCaseOrderer("TheOrderer", "xunit_orderer_repro")]

public class TheOrderer : ITestCaseOrderer
{
	public IEnumerable<TTestCase> OrderTestCases<TTestCase>(IEnumerable<TTestCase> testCases) where TTestCase : ITestCase
	{
		testCases = testCases.ToList();
		UnitTest1.CaseCount = testCases.Count();
		return testCases;
	}
}

[Collection("my_collection")]
public class UnitTest1
{
	public static int CaseCount { get; set; }

	[Fact]
	public void Test1() => Assert.Equal(2, CaseCount);
}

[Collection("my_collection")]
public class UnitTest2
{
	[Fact]
	public void Test2() => Assert.Equal(2, UnitTest1.CaseCount);
}

[CollectionDefinition("my_collection")]
public class MyCollection : ICollectionFixture<MyFixture> { }

public class MyFixture { }
```

The tests are now organized in a single collection, but the tests still fail the same way.

**Comment by bradwilson** [comment]
You are correct, I misremembered. It is once per test class, not once per test collection.

**Comment by godefroi** [comment]
I realize my case here is definitely an edge case, but I'm doing integration tests with my database, and it would definitely be useful for me to be able to both organize tests into separate classes *and* order everything at once.

**Comment by bradwilson** [comment]
There's nothing that can done about this today. We could consider changing this design for v3, after considering whether the change would break expectations of how things work today.
