### ISSUE TITLE
Update docs/capturing-output to list IClassFixture

### ISSUE THREAD

**Issue by barecode** [xunit/xunit#2218]
I stumbled on Issue #565 while looking for logging from an IClassFixture. I commented in that issue that this does work, but the documentation on https://xunit.net/docs/capturing-output does not list IClassFixture as a supported. Opening this issue to recommend updating the doc.

**Comment by bradwilson** [comment]
I assume you mean the section titled `Capturing output in extensibility classes`, right? Thanks for noticing that!

**Comment by randomnoise** [comment]
I guess one line addition would be enough, I'll give it a shot.
