### ISSUE TITLE
Parallelizing test assemblies in TeamCity may cause some tests to not be reported

### ISSUE THREAD

**Issue by alefranz** [xunit/xunit#2227]
I've been noticing for a long time that when running on Teamcity tests on a solution with many assemblies, using parallelize assemblies, sometimes a few tests are not reported (e.g. one or two every thousand)
On close inspection of the logs, I've noticed that sometimes two logs lines e.g.
```
##teamcity[testFinished ...] ##teamcity[testFinished ...]
```
and when this happens TeamCity only parse the second message, so the first test outputted is not reported.

This is really frequent when running on Linux.

**Comment by bradwilson** [comment]
I just validated in [ConsoleRunnerLogger](https://github.com/xunit/xunit/blob/v2/src/xunit.runner.utility/Utility/ConsoleRunnerLogger.cs) that all calls to `Console.WriteLine()` have locks around them, so it's not clear to me how we can end up with two messages on the same line. ☹️

**Comment by alefranz** [comment]
Hi Brad,
thanks for looking at this.
Please have a look at my proposed PR #2228 , as on linux/mac setting the color is causing a Write and I guess if the escape sequences get mixed up it could somehow be lost

**Comment by alefranz** [comment]
Raised to JetBrains on [TW-70266](https://youtrack.jetbrains.com/issue/TW-70266)

**Comment by bradwilson** [comment]
Fixed in #2228.
