### ISSUE TITLE
Assert.Contains overload for IEqualityComparer

### ISSUE THREAD

**Issue by jzabroski** [xunit/xunit#2229]
Assert.Contains supports several ways to verify a collection contains a specific object.  However, the easiest one to use (write code for) is also least useful one to debug when the assertion fails:

```c#
var comparer = new SomeEntityEqualityComparer();
Assert.Contains(savedEntities, entity => comparer.Equals(entity, expectedEntity));
```
This produces the following output on test failure:
```
Xunit.Sdk.ContainsException
Assert.Contains() Failure
Not found: (filter expression)
In value:  List<SomeEntity> [SomeEntity{ AsOfDate = 2021-01-25T21:50:22.7364789-05:00, CompositeKey1Id = "acdd310f-5f73-4b7c-b590-8f38fb2ccf68", CompositeKey2Id = "abcd310f-5f73-4b7c-b590-8f38fb2ccf67", CreatedDateTime = null, Id = 0, ... }]
   at Tests.Services.SomeEntityServiceTests.TestSaveEntitiesToDatabase() in D:\Users\John.Zabroski\Source\Services.Tests\Services\SomeEntityServiceTests.cs:line 90
```

I would rather write:
```c#
var comparer = new SomeEntityEqualityComparer();
Assert.Contains(savedEntities, expectedEntity, comparer);
```
and get a more detailed "Not found: " message than "Not found: (filter expression)".  In particular, you can imagine a special `StructuralEqualityComparer` class that lets you define properties that comprise the "Identity" of an object:

```c#
var comparer = new StructuralEqualityComparer<SomeEntity>(x => x.CompositeKey1Id, x=> x.CompositeKey2Id);
```
This would then allow an even more specific overload of Contains that could tell you the closest match.

Bonus points would support `IEquatable<T>`, `IComparable<T>`, but it's probably not needed.

**Comment by bradwilson** [comment]
The [built-in comparer](https://github.com/xunit/assert.xunit/blob/v2/Sdk/AssertEqualityComparer.cs) does already consider `IEquatable<T>` and `IComparable<T>`, as well as `IComparable`, `IStructuralEquatable`.

There is also already an override which allows you to pass a custom `IEqualityComparer<T>` without having to associate it with the type, if you can't change the type.

**Comment by jzabroski** [comment]
If you know the equality comparer uses structural equality you can pretty print a diff between expected and actual.

**Comment by bradwilson** [comment]
I don't think we're going to add specific logic trying to determine if there is a structural equality comparer in use. Instead, we are proposing a new `Assert.Equivalent` feature which differentiates itself from `Assert.Equal` in that it does very specific structural-style equivalence testing: https://github.com/xunit/xunit/issues/1604

**Comment by jzabroski** [comment]
Love that idea
