### ISSUE TITLE
Extensions instances caching does not work, when TraitHelper.GetTraits is used

### ISSUE THREAD

**Issue by estrizhok** [xunit/xunit#2232]
`Xunit.Sdk.TraitHelper.GetTraits` creates a new instance of `Xunit.Sdk.NullMessageSink`, a type that does not override Equals. That instance is later used as a part of the key for caching instance inside `Xunit.Sdk.ExtensibilityPointFactory`, resulting in caching not working for such calls at all.

**Comment by octos4murai** [comment]
Hi there! I'd like to suggest the following solution:
```
public class _NullMessageSink : _IMessageSink
{

...

  public override bool Equals(Object obj)
  {
    return obj != null &&
      this.GetType().Equals(obj.GetType());
  }

  public override int GetHashCode()
  {
    this.GetType().GetHashCode();
  }

...

}
```
Since the `_NullMessageSink` class is very minimal, I'm not sure we can do much better than using the object type itself to evaluate equality and compute a hashcode.

**Comment by octos4murai** [comment]
Checking in on my suggestion above. If it seems like a reasonable way to go, I'll submit a PR.

**Comment by randomnoise** [comment]
I think @bradwilson is missing some notifications for issues. IMHO, give it a shot with a PR 😏

**Comment by KiKoS0** [comment]
Hi everyone, I wanted to take a look at this but apparently it's not relevant because `Xunit.Sdk.ExtensibilityPointFactory` does not cache instances anymore ([commit](https://github.com/xunit/xunit/commit/b4ca6874dc499b20cc42efaa36d7b982ce74f7ff)), so I guess this issue should be closed right?

**Comment by bradwilson** [comment]
@KiKoS0 That is correct.
