### ISSUE TITLE
Sample TestRunner code out of date

### ISSUE THREAD

**Issue by KristaRutz** [xunit/xunit#2233]
Directed here from README for https://github.com/xunit/samples.xunit/blob/main/TestRunner/Program.cs

On line 30 of this file,  AssemblyRunner.WithAppDomain() method doesn't exist in v2.4.1.

**Comment by bradwilson** [comment]
I'm able to build the sample:

<img src="https://user-images.githubusercontent.com/16944/106397158-cc74a800-63c0-11eb-8bb7-c4fc894f3838.png" width="1160" />

My suspicion is that you're running in a target framework which is not .NET Framework, and therefore `.WithAppDomain` is not supported, as seen here: https://github.com/xunit/xunit/blob/v2/src/xunit.runner.utility/Runners/AssemblyRunner.cs#L266-L285

**Comment by KristaRutz** [comment]
Aha, good catch. I was running netcoreapp3.1.
