### ISSUE TITLE
Single test failed when run all tests

### ISSUE THREAD

**Issue by sonomirco** [xunit/xunit#2234]
Hi there,
I am facing the same problem I saw others got in the past.
When I run all the tests one test failed, but if it runs independently works.

I am using Theory and MemberData from another class used to collect data, named BoundingBoxCollection.
[Theory][MemberData(nameof(BoundingBoxCollection.BoundingBoxIntersectionsUnset), MemberType = typeof(BoundingBoxCollection))]

This is the name of the test.
Intersect_Returns_UnsetBBox_If_OneOfTheTwoBBoxes_IsNotInitialized_OrNotIntersection

Looks like it keeps a result from a previous test and uses it for the check into the test that failed.

Here the branch of the repo.
https://github.com/cesarecaoduro/GeometrySharp/tree/dev/mibi/nurbs-curve-length

Looking forward to hearing from you.
Best
Mirco.

**Comment by bradwilson** [comment]
Your theory data is static.

If your test manipulates the theory data, and then the theory is reused multiple times (as `BoundingBoxFrom5Points` is [here](https://github.com/cesarecaoduro/GeometrySharp/blob/048dc398c62bf2d0792440aa3e4d96ab2700ad05/GeometrySharp.Test.XUnit/Geometry/BoundingBoxCollection.cs#L66-L67)) then you end up polluting your data across tests.

I strongly recommend you stop using static data members; meaning, get rid of [these](https://github.com/cesarecaoduro/GeometrySharp/blob/048dc398c62bf2d0792440aa3e4d96ab2700ad05/GeometrySharp.Test.XUnit/Geometry/BoundingBoxCollection.cs#L9-L33) and instead new up a new instance for every data row. You can convert this static data into static data factory functions to keep the reuse, without actually having static data.

**Comment by sonomirco** [comment]
Hi @bradwilson,
Thanks for your message.

I think I am doing something wrong because I followed your advice, so I got rid of the static data members, and replace them in this way.

```
        public static Vector3[] BoundingBoxFrom5Points()
        {
            return new[]
            {
                new Vector3() {0d, 0d, 0d},
                new Vector3() {10d, 0d, 0d},
                new Vector3() {10d, 10d, 0d},
                new Vector3() {5d, 5d, 0d}
            };
        }

        public static Vector3[] NegativeBoundingBox()
        {
            return new[]
            {
                new Vector3() {-15d, -15d, 0d},
                new Vector3() {-5d, -5d, 0d}
            };
        }

        public static Vector3[] NegativeMinValuePositiveMaxValue()
        {
            return new[]
            {
                new Vector3() {-12d, -17d, 0d},
                new Vector3() {10d, 13d, 0d}
            };
        }

        public static Vector3[] BoundingBoxWithZValue()
        {
            return new[]
            {
                new Vector3() {-12d, -17d, -10d},
                new Vector3() {10d, 13d, 5d}
            };
        }
```

 but I still have the error.
 So I am probably doing something wrong.

**Comment by sonomirco** [comment]
Fixed, one of the methods was mutating the object!
Bad design as you said on twitch!!  👍 
Thanks very much!
