### ISSUE TITLE
Use `Fact(false)` to skip temporarily a test method

### ISSUE THREAD

**Issue by xp44mm** [xunit/xunit#2259]
Let's say we have a test method like this:
```F#
    [<Fact>]
    member this.``test method``() = ....
```
This method for some reason, we don't want to test it. So we're going to comment out his attribute
```F#
    // [<Fact>]
    member this.``test method``() = ....
```
Can we add a bool parameter to this attribute to indicate whether the test is temporarily skiped?

```F#
    [<Fact(false)>]
    member this.``test method``() = ....
```

Another benefit of this feature is that methods marked as `Fact(false)` are explicitly showed in the list of third-party tools.

**Comment by bartelink** [comment]
`Fact(Skip="A reason")]` already does this.

**Comment by bradwilson** [comment]
Right, I'm tempted to close this as "won't fix" since the Skip property does what you want.
