### ISSUE TITLE
Feature request: Parallel execution inside a single test class

### ISSUE THREAD

**Issue by kkeranen** [xunit/xunit#2260]
Modern architectures like functional architecture strive for methods that don't rely on class members (in case of OOP, with FP that's obvious). Therefore my C# test methods could be run parallel, but it seems it's not supported.

I have only one xUnit test class with 80 methods. The project has hundreds of other tests in other old nUnit classes. I would like to run to 80 tests in parallel because we are not going to port those old nUnit tests to xUnit. And I don't want to clutter the xUnit tests by creating artificial classes for test execution.

**Comment by bradwilson** [comment]
Feels like a dup of https://github.com/xunit/xunit/issues/1986, yes?

**Comment by kkeranen** [comment]
Yes, looks like the same issue. Closing this as duplicate.
