### ISSUE TITLE
Add flag to string assertions to disable the partial display

### ISSUE THREAD

**Issue by Youssef1313** [xunit/xunit#2274]
I'm comparing long strings in tests, the output with `Assert.Equals(s1, s2)` is shown as follows:

```
    Assert.Equal() Failure
              ↓ (pos 0)
    Expected: 
    Actual:   My actual output here is trimme...
              ↑ (pos 0)
```

Is there a good way to show the complete output?

**Comment by bradwilson** [comment]
Yes, though it's not obvious (so maybe we should add a flag).

Change `Assert.Equal(s1, s2)` to `Assert.Equal<object>(s1, s2)` so it bypasses the special handling used for strings.

**Comment by Youssef1313** [comment]
@bradwilson This probably won't allow me to use `ignoreLineEndingDifferences` and any other string-specific options.

**Comment by bradwilson** [comment]
@JamesTerwilliger Yep. Good catch.
