### ISSUE TITLE
Reflector's search for ToArray isn't specific enough

### ISSUE THREAD

**Issue by stephentoub** [xunit/xunit#2275]
https://github.com/xunit/xunit/blob/48faa2dffe24d3c2851a666789ebf73f43351431/src/xunit.v3.common/Reflection/Reflector.cs#L20

This code is searching for `Enumerable.ToArray`, but it's not specific enough in terms of visibility, arguments, etc.  If LINQ ever gets another ToArray overload (multiple have been proposed in the past), this may break (depending on the order in which reflection yields the methods).

We noticed this because we tried adding an internal overload (but different arguments and visibility), and it broke xunit.

**Comment by bradwilson** [comment]
Thanks! For safety I also changed `Cast`:

https://github.com/xunit/xunit/blob/99e012e7c29aeb07fef29d20d854928bbbf0d598/src/xunit.v3.common/Reflection/Reflector.cs#L20-L36
