### ISSUE TITLE
Analyzers should disallow Xunit attributes on local functions

### ISSUE THREAD

**Issue by RikkiGibson** [xunit/xunit#2277]
C# 9 added the ability to put attributes on local functions. It feels like it's not valid to put Xunit attributes like Fact and Theory on local functions, so perhaps the analyzers should report an error in such cases.

```cs
using Xunit;

public class C
{
    public void M()
    {
        int x = 0;
        local();

        [Fact]
        void local()
        {
            x++;
            Assert.True(false);
        }
    }
}
```

**Comment by adison88** [comment]
I'd like to pick this one up.

**Comment by douglasg14b** [comment]
Alternatively this could be a supported use case?

Is that possible?

**Comment by bradwilson** [comment]
@douglasg14b This is definitely not something we want to support.

1. Syntactically, there's no reason for us to support this. What the the value of an "embedded" test inside a random function?

2. The complication level involved in needing to identify and provide any captured values makes it a non-starter.
