### ISSUE TITLE
Tests in nested classes aren't shown by CodeLens

### ISSUE THREAD

**Issue by C-xC-c** [xunit/xunit#2278]
In the attached image, there are two tests for `Example.Foo`, but CodeLens only reports "1/1 passing". This is the case for `[Fact]` and `[Theory]`, with a fresh XUnit project, using any target framework(s).

I'm running Visual Studio Community 2019 Version 16.9.1, with the following package references:
``` xml
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.1" />
<PackageReference Include="xunit" Version="2.4.1" />
<PackageReference Include="xunit.runner.visualstudio" Version="2.4.3" />
```
![nested classes](https://user-images.githubusercontent.com/58750933/112354412-90750980-8cc4-11eb-839a-1e5edf7e1800.PNG)

**Comment by bradwilson** [comment]
We don't own CodeLens. This should be opened against Visual Studio.

**Comment by C-xC-c** [comment]
I had assumed it was an issue with xunit without looking in to it properly, but it seems to be an issue for other test frameworks also.

Sorry about this!
