### ISSUE TITLE
XUNIT throws "Aborting test run due to build errors" - yet none exist

### ISSUE THREAD

**Issue by codeputer** [xunit/xunit#2289]
I'm running a simple test with a reference to another project (console 5.0).

I'm using CSVHelper in that project (may be the issue to this problem).

Run the test, and issues this error on the status line, with this error in the Test Output
![image](https://user-images.githubusercontent.com/611541/115471939-0ef69580-a1f6-11eb-909c-c2fa8fd760d9.png)
![image](https://user-images.githubusercontent.com/611541/115471988-233a9280-a1f6-11eb-9e0f-6f2ad32e4cff.png)

I have no idea what is going on as it fails before tests are even run.

**Comment by bradwilson** [comment]
Please project a repro project. Thanks!

**Comment by bradwilson** [comment]
Please re-open with a repro.
