### ISSUE TITLE
Analyzer: Consider detecting when CollectionDefinition class is not in same assembly as test class

### ISSUE THREAD

**Issue by oising** [xunit/xunit#2311]
I lost a couple of hours on this one today -- apparently fixtures can be in a shared assembly, but the ICollectionFixture / CollectionDefinition must be in the same assembly as the test classes decorated with it, or it won't be found by DI. This elicits a confusing message:

```
Xunit.Sdk.TestClassException
The following constructor parameters did not have matching fixture data: MyFixture fixture
```

Thank you!

edit: I eventually figured it out through stackoverflow, which pointed me to a _tiny_ note at the foot of https://xunit.net/docs/shared-context: 
 
 _Important note: Fixtures can be shared across assemblies, but collection definitions must be in the same assembly as the test that uses them._

**Comment by etherfield** [comment]
I'll implement the analyzer for this.

**Comment by bradwilson** [comment]
Available in `1.7.0-pre.12`

**Comment by bradwilson** [comment]
While writing the integration tests for this, it appears that this new analyzer is being triggered even when there is no `[CollectionDefinition]`, which is a valid scenario.

I'm thinking about optimal ways to implement this, but for now I'm going to re-open the issue and mark the existing analyzer as `Hidden` so that it doesn't trigger for now.

**Comment by oising** [comment]
Appreciate the diligence, @bradwilson

**Comment by etherfield** [comment]
@bradwilson do you mean the case when the collection definition is missing, the class is marked with `Collection` attribute but the fixture is not used? Like here [PassingTests](https://github.com/xunit/xunit.analyzers/compare/main...etherfield:xunit.analyzers:2311-no-collection-definition-case) ?
If so, wouldn't it be better to require developers to create definitions if they've used the `Collection` attribute? I mean it looks like a breaking change, yea, but if the developer claims they need a collection definition and ends up not using it, it may take some time for the other developer to figure out the attribute is pointless in that part of code.

**Comment by etherfield** [comment]
@bradwilson okay. So it seems to me it would be sufficient to check if a fixture is going to be used along with the class marked with `Collection` attribute. I grasped from the code there must be a single public constructor with parameters in such case and dependency injection via property is not supported. This is what I propose.

**Comment by bradwilson** [comment]
Available in `1.7.0-pre.18`

**Comment by bradwilson** [comment]
Documentation page: https://xunit.net/xunit.analyzers/rules/xUnit1041

**Comment by vadimkhm** [comment]
Hello, I have an issue related to this, it breaks the working code.
I am also using **xunit.assemblyfixture 2.2.0** and it works as expected with **_xunit 2.6.2 all_**.

I have shared library for unit test base class, and that class receives `StartupFixture` and base class has interface `IAssemblyFixture<StartupFixture>`, and now I am getting analyzer error that I need a source, but it is defined and it is in the shared library. 

Base class definition:
```
public abstract class UnitTestBase : IDisposable, IAssemblyFixture<StartupFixture>
{
   protected UnitTestBase(ITestOutputHelper testOutputHelper, StartupFixture startupFixture)
   {
      ....
   }
}
```

Please provide some advice how to solve this, for now I will downgrade to xunit 2.6.2.
Thanks

**Comment by agross** [comment]
I also have issues with this rule since upgrading xunit.analyzers from 1.6 to 1.7. It seems as if the rule does not consider that `CollectionAttribute` is inherited.

```csharp
public class Fixture
{
}

[CollectionDefinition("test")]
public class TestCollection : ICollectionFixture<Fixture>
{
}

[Collection("test")]
public abstract class TestContext
{
  protected TestContext(HttpFixture fixture)
  {
  }
}

public class TestClass : TestContext
{
  // xUnit1041
  public TestClass(HttpFixture fixture) : base(fixture)
  {
  }

  [Fact]
  public void Foo()
  {
  }
}
```

**Comment by bradwilson** [comment]
> `IAssemblyFixture<StartupFixture>`

This is not from us, and as such is not something we consider to be a fixture source. In your case, you should disable this rule.

**Comment by bradwilson** [comment]
> It seems as if the rule does not consider that CollectionAttribute is inherited.

I'll take a look. Thanks!

**Comment by bradwilson** [comment]
@agross A fix is available in `1.8.0-pre.2`. https://xunit.net/docs/using-ci-builds

**Comment by agross** [comment]
@bradwilson Confirmed to be working. Thank you!

BTW, the changes needed to Paket to use the package where quite minimal. ;-)

```diff
diff --git a/paket.dependencies b/paket.dependencies
index bef8ac6..48dd61a 100644
--- a/paket.dependencies
+++ b/paket.dependencies
@@ -1,4 +1,5 @@
 source https://api.nuget.org/v3/index.json
+source https://f.feedz.io/xunit/xunit/nuget/index.json
 
 framework: net8.0
 storage: none
@@ -22,4 +23,4 @@ nuget Verify.Xunit
 nuget xunit ~> 2
 nuget xunit.runner.visualstudio ~> 2
 // https://github.com/xunit/xunit/issues/2311#issuecomment-1848384304
-nuget xunit.analyzers 1.6
+nuget xunit.analyzers ~> 1.8 prerelease
```

**Comment by agross** [comment]
I did just cross-check that the violating code from the docs still actually raises 1041, but it does not. I only upgraded the analyzer package. Should be enough, right?

**Comment by bradwilson** [comment]
Hmm, let me check my integration test project.

**Comment by bradwilson** [comment]
@agross I still see it being raised with `1.8.0-pre.2`:

![image](https://github.com/xunit/xunit/assets/16944/df56de24-760c-4d7e-9105-38d870d638df)

**Comment by bradwilson** [comment]
The integration test project lives here: https://github.com/xunit/xunit.integration

The Directory.Build.props lives in the root, and the tests for the analyzers lives in `$/analyzers`

**Comment by agross** [comment]
Interesting.

```diff
diff --git a/paket.dependencies b/paket.dependencies
index bef8ac6..48dd61a 100644
--- a/paket.dependencies
+++ b/paket.dependencies
@@ -1,4 +1,5 @@
 source https://api.nuget.org/v3/index.json
+source https://f.feedz.io/xunit/xunit/nuget/index.json
 
 framework: net8.0
 storage: none
@@ -22,4 +23,4 @@ nuget Verify.Xunit
 nuget xunit ~> 2
 nuget xunit.runner.visualstudio ~> 2
 // https://github.com/xunit/xunit/issues/2311#issuecomment-1848384304
-nuget xunit.analyzers 1.6
+nuget xunit.analyzers ~> 1.8 prerelease
diff --git a/paket.lock b/paket.lock
index e70cdb9..d682d41 100644
--- a/paket.lock
+++ b/paket.lock
@@ -358,7 +358,6 @@ NUGET
       xunit.assert (>= 2.6.2)
       xunit.core (2.6.2)
     xunit.abstractions (2.0.3)
-    xunit.analyzers (1.6)
     xunit.assert (2.6.3)
     xunit.core (2.6.2)
       xunit.extensibility.core (2.6.2)
@@ -370,3 +369,5 @@ NUGET
       NETStandard.Library (>= 1.6.1)
       xunit.extensibility.core (2.6.2)
     xunit.runner.visualstudio (2.5.5)
+  remote: https://f.feedz.io/xunit/xunit/nuget/index.json
+    xunit.analyzers (1.8.0-pre.2)
diff --git a/source/api/Tests/Http/HttpContext.cs b/source/api/Tests/Http/HttpContext.cs
index d7dfc7e..bb5e945 100644
--- a/source/api/Tests/Http/HttpContext.cs
+++ b/source/api/Tests/Http/HttpContext.cs
@@ -106,3 +106,13 @@ public abstract class HttpContext : IDisposable
     Daten = null;
   }
 }
+
+public class xUnit1041
+{
+  public xUnit1041(HttpFixture fixture)
+  { }
+
+  [Fact]
+  public void TestMethod()
+  { }
+}
```

```sh
$ dotnet build
MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
...

Build succeeded.

    3 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.16
```

(The 3 warnings are unrelated.)

**Comment by agross** [comment]
Your integration test project also reports the error on my machine 🤔

**Comment by agross** [comment]
I don't know why, but after cleaning the solution the 1041 now shows up where it's supposed to. Let's close this.

**Comment by bradwilson** [comment]
Yeah, Visual Studio definitely still plagued by caching problems in 2023. I don't even think about it any more: when things aren't behaving problem, I close down VS, run `git clean -xdf` on the root folder and re-open VS. 🤷🏼

**Comment by briandunnington** [comment]
> > `IAssemblyFixture<StartupFixture>`
> 
> This is not from us, and as such is not something we consider to be a fixture source. In your case, you should disable this rule.
> 
> Rules can be disabled in `.editorconfig`, in your `.csproj` file, or in the Visual Studio UI (right click on the rule and set the severity to None).
> 

This is a big bummer in what is labelled as a bug-fix point release. We also use a custom `TestFramework` and assembly fixture and now all of our test classes are broken. We could suppress the rule, but we use our test framework in tons of projects and now they all have to have this rule disabled individually instead of the test framework 'just working' like it always has. Is there a way to tell xunit "yes, i really do have a fixture source" to satisfy this analyzer (which isnt even accurate since our classes *do* all work as-is)?

<img width="744" alt="image" src="https://github.com/xunit/xunit/assets/1545776/1d770c2d-78c1-44f8-9246-5fb1b5c6eeb3">

**Comment by bradwilson** [comment]
> This is a big bummer in what is labelled as a bug-fix point release.

This is an assumption on your part that is not necessarily valid. Versioning for xUnit.net v2 does not follow SemVer, as the versioning strategy was chosen prior to SemVer existing.

We do use SemVer for v3.

> We could suppress the rule, but we use our test framework in tons of projects and now they all have to have this rule disabled individually instead of the test framework 'just working' like it always has.

A root-folder two-line .editorconfig file would disable the rule in every project.

> Is there a way to tell xunit "yes, i really do have a fixture source" to satisfy this analyzer (which isnt even accurate since our classes do all work as-is)?

Yes, you do this by suppressing the analyzer. Whether you choose to do that on a test-by-test, project-by-project, or solution-wide basis is up to you.

> i would really like to request is a way for xunit to be aware (even if it is by us telling it via some kind of attribute/etc) that we do in fact have a fixture source so that we dont have to suppress the rule but also dont get build errors.

The only thing we could do would be to reduce the severity from Error to Warning (which of course wouldn't help if you have Warnings as Errors enabled, and would pollute your compilation with warnings for every assembly-level fixture you're using). You can do this today with the .editorconfig suggested above by changing the severity to Warning.

Personally, I believe you should just disable it by setting the severity to None.

**Comment by briandunnington** [comment]
>> This is a big bummer in what is labelled as a bug-fix point release.
>
> This is an assumption on your part that is not necessarily valid. Versioning for xUnit.net v2 does not follow SemVer, as the versioning strategy was chosen prior to SemVer existing.

yes, this was an assumption on my part. we were only updating to 2.6.3 to fix the Dictionary null comparison bug from 2.6.2 and didnt expect these additional rules to be there.

> > We could suppress the rule, but we use our test framework in tons of projects and now they all have to have this rule disabled individually instead of the test framework 'just working' like it always has.
> 
> A root-folder two-line .editorconfig file would disable the rule in every project.

Unfortunately all of the projects are not in one solution - we use our custom test framework in lots of projects across dozens of solutions and repos.

> > i would really like to request is a way for xunit to be aware (even if it is by us telling it via some kind of attribute/etc) that we do in fact have a fixture source so that we dont have to suppress the rule but also dont get build errors.
> 
> The only thing we could do would be to reduce the severity from Error to Warning (which of course wouldn't help if you have Warnings as Errors enabled, and would pollute your compilation with warnings for every assembly-level fixture you're using). You can do this today with the .editorconfig suggested above by changing the severity to Warning.
> 
> Personally, I believe you should just disable it by setting the severity to None.

duly noted. it would still be nice for the analyzer to know (or be told) that we already do have our fixture sources set up properly. the point of the rule is to catch issues before runtime, and in our case, it is essentially giving a false positive. if we disable the rule, we lose any benefit from future improvements to the rule that might catch something we arent already doing.

**Comment by bradwilson** [comment]
> it would still be nice for the analyzer to know (or be told) that we already do have our fixture sources set up properly. 

Out of curiosity, how would you imagine such a system would work? We obviously cannot chase down every third party library that might provide fixture sources (much less know about any private versions that exist), so what would you suggest would be the way you would tell the analyzers how to know about your fixture data sources?
