### ISSUE TITLE
Support code coverage for static members used by MemberData attribute

### ISSUE THREAD

**Issue by ericmutta** [xunit/xunit#2320]
## The Problem

I am using Visual Studio 2019 Community v16.9.1 and have a test class similar to this:

```csharp
  public class CodeCoverageIssueTest
  {
    [Theory, MemberData(nameof(Data))]
    public void Test(int data) {
      Assert.Equal(1, data);
    }

    public static IEnumerable<object[]> Data
    {
      get {
        yield return new object[] { 1 };
      }
    }
  }
```

The problem is that when running the tests with code coverage enabled (e.g. using CodeRush in my case, though the problem applies to Visual Studio Enterprise as well), **the tools are unable to collect code coverage for the static `Data` property which generates data to feed into the `Test()` method.**

Here is the same test class but for the NUnit framework:

```csharp
  public class CodeCoverageIssueTest
  {
    [Test, TestCaseSource(nameof(Data))]
    public void Test(int data) {
      Assert.Equals(1, data);
    }

    public static IEnumerable<int> Data
    {
      get {
        return new[] { 1 };
      }
    }
  }
```

The code is pretty much identical **however you CAN collect code coverage for the static `Data` property when using NUnit**.

## The Underlying Cause

I filed a [support ticket](https://supportcenter.devexpress.com/ticket/details/t1000449/code-coverage-doesn-t-cover-static-members) with the developers of CodeRush to see why they can collect code coverage for NUnit but not for xUnit and to the best of my understanding **it's because NUnit uses a SINGLE PROCESS for both test discovery and execution, while xUnit uses SEPARATE PROCESSES, one process for test discovery and execution of the static `Data` property and another for test execution when running the `Test()` method.**

## The Proof

To prove that NUnit uses one process for both test discovery and execution while xUnit uses two distinct processes, **I modified the test code to create a file on disk with a name that indicates the process ID used in each case.**

The modified NUnit test code is this:

```csharp
  public class CodeCoverageIssueTest
  {
    private const string conDirPath = @"D:\kill\xunit_vs_nunit\";

    [Test, TestCaseSource(nameof(Data))]
    public void Test(int data) {
      DumpFile("Test");
      Assert.Equals(1, data);
    }

    public static IEnumerable<int> Data
    {
      get {
        DumpFile("Data");
        return new[] { 1 };
      }
    }

    private static void DumpFile(string ArgCaller) {
      var FileName = $"NUnit-RUN={DateTime.Now.Minute}-PID={Process.GetCurrentProcess().Id}-{ArgCaller}.txt";
      File.WriteAllText(Path.Combine(conDirPath, FileName), "Hello");
    }
  }
```

The modified xUnit code is this:

```csharp
  public class CodeCoverageIssueTest
  {
    private const string conDirPath = @"D:\kill\xunit_vs_nunit\";

    [Theory, MemberData(nameof(Data))]
    public void Test(int data) {
      DumpFile("Test");
      Assert.Equal(1, data);
    }

    public static IEnumerable<object[]> Data
    {
      get {
        DumpFile("Data");
        yield return new object[] { 1 };
      }
    }

    private static void DumpFile(string ArgCaller) {
      var FileName = $"xUnit-RUN={DateTime.Now.Minute}-PID={Process.GetCurrentProcess().Id}-{ArgCaller}.txt";
      File.WriteAllText(Path.Combine(conDirPath, FileName), "Hello");
    }
  }
```

If you paste the above code into an NUnit/xUnit test project (respectively) and run it (remember to change the `conDirPath` value to something valid on your computer) you will get files similar to this in Windows Explorer:

![image](https://user-images.githubusercontent.com/20465797/120693240-6eacb580-c4b1-11eb-8fa1-dc7cb33cc6f2.png)

Notice how NUnit used one process with PID = 10192 to run the code in the static `Data` property and in the `Test()` method. I believe it is this behaviour that allows one to collect code coverage information for the `Data` property when using NUnit. Looking at the same image you can see xUnit used two different processes (one with PID = 5548 and another with PID = 12236).

I have also noticed that NUnit seems to run the code in the static `Data` property twice (first time in a process with PID = 9504 and second time in the same process used to run the `Test()` method). Not sure why it does this but it may be an important implementation detail.

## Why Is This A Problem?

Here is the code coverage output (using CodeRush):

![image](https://user-images.githubusercontent.com/20465797/120694481-ef1fe600-c4b2-11eb-8f09-2590ef00d7dd.png)

Notice how the `Data` property getter has 100% coverage when using NUnit and 0% coverage when using xUnit even though it is actually executed fully.

**xUnit's behaviour (using two separate processes) means that static members like the `Data` property ALWAYS HAVE 0% COVERAGE which dilutes the code coverage for the ENTIRE test class they are a part of**.

You can no longer just look at the class to see if it has 100% coverage (it never will) so you have to expand the class each time and **review individual members to see which ones don't have 100% coverage**.

## The Workaround

xUnit supports the `ClassData` attribute which you can use instead of the `MemberData` attribute. So I created data classes, put them into a segregated namespace and then used `ClassData` to reference them. Using a separate namespace for these classes removes the diluting effect of 0% code coverage on the test classes that depend on their data.

## The [Suggested] Solution

Provide an option for xUnit to run its test discovery and test execution phases in a single process like NUnit does...or do something else (I am not an expert here) that would allow code coverage to be collected for static members referenced by the `MemberData` property.

## Gratitude

Thanks @bradwilson and team for such an amazing test framework! The built-in opinionated analysers are a nice touch (e.g. I learned about `Assert.Single()` when the analyser didn't like me writing `Assert.True(SomeCollection.Length == 1)` :smile:)

**Comment by bradwilson** [comment]
>xUnit uses SEPARATE PROCESSES, one process for test discovery and execution of the static Data property and another for test execution when running the Test() method.

This is only true if you're using our VSTest adapter (aka `xunit.runner.visualstudio`), and that design choice is out of our hands, unfortunately.

I don't know how to solve this problem with CodeRush, but there isn't a problem collecting code coverage with coverlet, so my guess is this is probably not something that we can or will fix. If the CodeRush people would like to reach out, please direct them to this issue.

Thanks.

**Comment by ericmutta** [comment]
Hi @bradwilson many thanks for looking into this issue and responding. I have alerted the CodeRush developers and hope they will reach out soon :+1:
