### ISSUE TITLE
Support tuples in `TheoryData`

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#2333]
For uses of `TheoryData<>` with more than one generic argument, we should support being able to pass tuples.

(In the examples below, only the two-argument version is shown, but this is applied to all the versions of `TheoryData<>` with more than one generic argument.)

In v2, the constructor signature looks like this:

```csharp
public TheoryData(IEnumerable<(T1, T2)> values)
```

For v3, we will also add a tuple-based `params` style constructor, like this:

```csharp
public TheoryData(params (T1, T2)[] values)
```

This allows the developer to use this style of initialization for `TheoryData`:

```csharp
new TheoryData<int, string>(
    (42, "Hello"),
    (2112, "World")
);
```

**Comment by siewers** [comment]
What do you think of supporting `TheoryData<T>`?
If that supported, I think it will cover both xUnit member data and combinatorial.
