### ISSUE TITLE
Add assembly-level support for BeforeAfterTestAttribute

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#2334]
`BeforeAfterTestAttribute`-derived attribute classes all the developer to run code before and after every test. In v2, this could be applied at a method (i.e., run before and after this one test) or class (i.e., run before and after every test in this class) level. In v3, we would like to allow developers to apply these attributes at the assembly level (i.e., run before and after every test in the assembly).

**Comment by goldsam** [comment]
Do you think you could backpatch this into v2? You have a great project here, but v3 seems like its been a very long time coming. This seems like something that could be added to v2 with a minor release since it doesn't seem like a backwards-breaking change.

**Comment by bradwilson** [comment]
Available in `2.6.6-pre.4` https://xunit.net/docs/using-ci-builds

**Comment by goldsam** [comment]
Utmost gratitude and respect. Thank you very much👍😀
