### ISSUE TITLE
Installation of xunit.execution into wpa81 requires manual hacks

### ISSUE THREAD

**Issue by adamralph** [xunit/xunit#234]
xunit.execution takes a dep on xunit.core, which has props/targets magic to bring xunit.execution into the bin folder.

When I install xunit.execution into a wpa81 project, the hint path points correctly to the portable-wpa81+win81 target in the xunit.execution packages folder. However, the props/targets in xunit.core mean that xunit.execution.dll is copied in from xunit.core/build/wpa81 into the output folder, which is the net45 'noserialization' version, and this overrides whatever may be found using the hint path. This results in compilation errors because that version cannot be called from a wpa81 project (no `MarshalByRefObject`).

If I manually remove all the props/targets stuff from the csproj, the correct DLL is imported and everything works OK.

IIRC I had this problem with wpa81, wp8 and Profile32 (universal).

I see three ways to proceed:

1. Leave as is. Anyone who wants to install xunit.execution.nupkg into projects targetting these platforms will just have to manually hack out the props/targets from their projects after installation. I guess this would have to be repeated on each upgrade.

1. Lift the props/targets up one level from xunit.core to xunit. This will means that only xunit.nupkg is 'special', leaving core and execution as regular packages adding lib references without any msbuild magic. This has the downside that anyone wanting to write a test lib without importing xunit.assert will no longer be able to do so, since an installation of xunit.core.nupkg only will no longer take care of the copying of the execution libs.

1. Introduce a new package sitting between the current xunit.nupkg and xunit.core.nupkg and lift the props/targets magic out of xunit.core and into this new package. xunit.nupkg can depend on this new package, and xunit.execution can bypass it and go straight to xunit.core, avoiding the props/targets.

And of course, I'm sure there's a much simpler way which I've missed :stuck_out_tongue:.

**Comment by bradwilson** [comment]
Fixed in a76be923dc3761ff6ae15445f7db358e6a2ae595

**Comment by adamralph** [comment]
:ok_hand: awesome. Wow, what a changeset!

**Comment by bradwilson** [comment]
Most of the work was done on the whiteboard. ;)

**Comment by adamralph** [comment]
Precisely where all the most important work should be done :smile:
