### ISSUE TITLE
Misleading error message when class fixture constructor throws an exception

### ISSUE THREAD

**Issue by supermihi** [xunit/xunit#2342]
When the constructor of a class fixture throws an exception, xunit outputs a messag
> The following constructor parameters did not have matching fixture data

which suggests that the fixture set-up is wrong. The actual exception is not visible at all in the output.
Minimal example:
```csharp
public class Fixture  {
  public Fixture() {
    throw new Exception("foo");
  }
}

public class Tests : IClassFixture<Fixture> {
  public Tests(Fixture _) {  }

  [Fact]
  public void Test() {  }
}
```
Output:
```
  Failed Test [1 ms]
  Error Message:
   System.AggregateException : One or more errors occurred. (foo) (The following constructor parameters did not have matching fixture data: Fixture _)
---- System.Exception : foo
---- The following constructor parameters did not have matching fixture data: Fixture _
  Stack Trace:
  
----- Inner Stack Trace #1 (System.Exception) -----
   at Fixture..ctor() in /home/xxx.cs:line 18
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----


```

**Comment by bradwilson** [comment]
Verified this is still broken in v3, so added to the roadmap.

**Comment by supermihi** [comment]
thanks

**Comment by orney21d** [comment]
Hi, is still this broken ??

**Comment by bartelink** [comment]
@orney21d AFAICT its still on [the roadmap](https://github.com/xunit/xunit/issues/2133), and this continues to be the tracking issue.

**Comment by RokasMarcinkevicius** [comment]
As this thread shows up on google, what is the best way to properly set it up?

**Comment by RichardPoes** [comment]
Using the example on the [xUnit documentation](url) it is probably because you accidentally wrote
```csharp
[CollectionDefinition("Database collection")]
public class DatabaseTestClass1
```
instead of 
```csharp
[Collection("Database collection")]
public class DatabaseTestClass1
```
At least that was what I did wrong.

**Comment by mateusz-dobrowolny** [comment]
@bradwilson After merge done on March 13, shouldn't this issue be set as "Done"?

**Comment by bradwilson** [comment]
@mateusz-dobrowolny Yes! Thank you! 😄
