### ISSUE TITLE
Improve output for Assert.Equal for collections of mis-matched sizes/underrun

### ISSUE THREAD

**Issue by Aleksbgbg** [xunit/xunit#2352]
When comparing long arrays, and in particular arrays of bytes (as may be necessary when testing binary operations, such as hashing functions, serializing, etc), xunit does not provide descriptive messages.

For example, when running this test:
```cs
Assert.Equal(new byte[] { 1, 2, 3, 4, 5, 6, 7 }, new byte[] { 1, 2, 3, 4, 5, 6, 7, 8 });
```
The output is:
```
Xunit.Sdk.EqualException
Assert.Equal() Failure
Expected: Byte[] [1, 2, 3, 4, 5, ...]
Actual:   Byte[] [1, 2, 3, 4, 5, ...]
```

and when running this test:
```cs
Assert.Equal(new byte[] { 1, 2, 3, 4, 5, 6, 7, 8 }, new byte[] { 1, 2, 3, 4, 5, 8, 7, 6 });
```
The output is the same.

These are very different failures that are being reported to the programmer as being an identical failure.

In particular, these features are missing:
1. Checking the size of the arrays
2. Reporting the position at which differences begin

An example error message that would be sufficient for each feature:
1#
```
Xunit.Sdk.EqualException
Assert.Equal() Failure
Expected: Byte[7] [1, 2, 3, 4, 5, ...]
Actual:   Byte[8] [1, 2, 3, 4, 5, ...]
```
Note the size of the arrays is reported in the array brackets - feel free to report the size in some other manner, I just thought this was fitting.

2#
```
Xunit.Sdk.EqualException
Assert.Equal() Failure at index 5
Expected: Byte[8] [..., 6, 7, 8]
Actual:   Byte[8] [..., 8, 7, 6]
```
If this index happens to be in the middle of the array, there should be ellipsis at either size of the array contents. You could show up to 5 or 10 elements to help the programmer debug the issue without having to start a debugger.

**Comment by bradwilson** [comment]
This has already been partly solved in v3:

```
Assert.Equal() Failure                                                                                                                                                                       
                             ↓ (pos 7)                                                                                                                          Expected: [..., 3, 4, 5, 6, 7]                                                                                                                                  Actual:   [..., 4, 5, 6, 7, 8]                                                                                                                                                               
                             ↑ (pos 7)
```

But there are two things that feel could be improved here:

* The length of the two collections should be printed when they differ
* The pointer for `Actual` should actually be pointing at `8`, not `]`.

So I'm going to keep this open for some additional improvements.

**Comment by bradwilson** [comment]
@mongeon I believe the assertion correctly fails; it's just about improving the output in the edge cases listed above. I don't think any of those edge cases have been fixed, but it's been a while since I opened this issue so I admit my memory is probably hazy. 😄

**Comment by bradwilson** [comment]
The overrun problem has been solved in the recent message overhaul work.

Printing collection lengths isn't a 100% safe operation, since `IEnumerable` is never required to end (and as such it's impossible to know for sure whether it would be safe to try to get the count of the collection length). So I'm going to close this for now as completed.
