### ISSUE TITLE
Add README to NuGet packages

### ISSUE THREAD

**Issue by loic-sharma** [xunit/xunit#2357]
Hello!

I am from the NuGet team at Microsoft. We recently introduced support for embedding READMEs into NuGet packages ([blog](https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/), [docs](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packagereadmefile)), and we plan to place these READMEs front and center on nuget.org. Would you be willing to accept a contribution to add embedded READMEs to your packages?

**Comment by bradwilson** [comment]
I'm fine with having READMEs in the xUnit.net packages, but the current README is crafted for people who are visiting the xunit/xunit GitHub page. We would want specific README files for each package, that are crafted to help people consume that package. So if the proposal was simply to add the existing README to all our NUSPEC files, I think I would decline that as a PR (and I'm assuming you aren't offering to write those dozen or so README files 😁). So I'll tag this and put it in my 3.0 road map.

**Comment by bradwilson** [comment]
This has been shipping since 2.5.0. Sorry for closing the issue this late.
