### ISSUE TITLE
Enable controlled randomness

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#2371]
xUnit.net has historically supported/required random test execution by default. This randomness can (purposefully) introduce interaction issues between two tests that may be uncovered simply by ordering them differently.

We should print (or somehow make available) the random seed we use for randomizing these tests, as well as enable the user to pass the random seed into subsequent runs to ensure that we get the same random order again for easier reproduction.

**Comment by bradwilson** [comment]
I'm thinking about usability, and I think one potentially good idea would be to add some stability to the randomness. Adding some stability allows someone to re-runs tests without any additional effort in the exact same order, though obviously if the user re-builds the assembly, they'll get a potential new random order. (This is where we want to be able to easily report and re-use the randomization seed.)

For stability, I was thinking about using the test assembly's ModuleVersionId as a way to feed the seed of Random() by default, so if you don't rebuild the assembly, you will get the same "random" order over and over again.

Anybody done anything like this? Any caveats? Any thoughts on the best way to convert the MVID into an int? Just use something akin to the canonical hash code implementation? (Paging @jaredpar 😄)

**Comment by jaredpar** [comment]
> For stability, I was thinking about using the test assembly's ModuleVersionId as a way to feed the seed of Random() by default, so if you don't rebuild the assembly, you will get the same "random" order over and over again.

The `ModuleVersionId` field is reproducible so even if you do rebuild it will still produce the same value. That would mean on the same machine it's stable random until you change the code in the project or one of the dependencies change. 

CI machines typically have a bit of randomization in the path the code is checked out to. This in turn will cause the `ModuleVersionId` to change. The path can be normalized via `/pathMap` but that is not the default at this time. The end result is such that two CI runs on the same code will possibly end up with different random values. 

IMHO these seem like desirable outcomes. 

> We should print (or somehow make available) the random seed we use for randomizing these tests, as well as enable the user to pass the random seed into subsequent runs to ensure that we get the same random order again for easier reproduction.

+100. 

Having this is the log + making it possible to pass this to subsequent runs would be extremely useful. Over the years randomization has found a number of bugs in our tests and product. In many cases our tracking down of the problem would've been much easier if we could go back to a passing run, re-run it under the debugger, trace the success case under the debugger, then do the same for the failure case. That capability makes it much easier to root cause the bug that randomization found.

**Comment by bradwilson** [comment]
> IMHO these seem like desirable outcomes.

Agreed, they both seem desirable.

Sounds like you think MVID is a good choice for the stability. Any thoughts on integer conversion? Is GUID's `GetHashCode` reasonable here or should I implement my own? (I know it's changed from .NET Framework to .NET Core, but I don't think that should be an issue.)

**Comment by jaredpar** [comment]
> Sounds like you think MVID is a good choice for the stability

Yes. It seems like a good choice and has a lot of the characteristics I think are desirable here. 

> Any thoughts on integer conversion? Is GUID's GetHashCode reasonable here or should I implement my own?

My instinct would be to use the `GetHashCode`

**Comment by bradwilson** [comment]
Now thinking about usability and the command line.

# Meta-runner

For the console meta-runner (`xunit.v3.runner.console.exe`), since seed values are per-assembly, my thought was to update the command line to allow appending `:seed` onto the filename.

Usage today:

```
<assemblyFile> [configFile] [assemblyFile [configFile]...] [options] [reporter] [resultFormat filename [...]]
```

Proposed usage:

```
<assemblyFile>[:seed] [configFile] [assemblyFile[:seed] [configFile]...] [options] [reporter] [resultFormat filename [...]]
```

The motivation for the syntax here is that the colon is the universal "this isn't a legal part of a filename" character across Windows, Linux, and macOS.

Thoughts on this? Alternatives?

# In-process runner

This is the usage for the in-process runner today:

```
[path/to/configFile.json] [options] [filters] [reporter] [resultFormat filename [...]]
```

Since the in-process runner doesn't require or support assembly filenames (you are directly executing the tests), I'm less sure on the usability. I have a couple possibilities I can think of:

1. Allow `:seed` as the first argument (akin to how you can pass a config file):

```
[:seed] [path/to/configFile.json] [options] [filters] [reporter] [resultFormat filename [...]]
```

2. Add a `-seed <seed>` switch (only for the in-process runner)

Option 1 feels more consistent with the console meta-runner. Option 2 feels a little cleaner and clearer.

Thoughts? Is there an option I'm missing?

**Comment by bradwilson** [comment]
The seed value needs to be passed through to the remote process for v3 runner, so tagging #2337

**Comment by bradwilson** [comment]
I landed on `<path>[:seed]` for `xunit.v3.runner.console.exe`:

```
 pwsh> ./src/xunit.v3.runner.console/bin/Debug/net472/xunit.v3.runner.console --help
xUnit.net v3 Console Runner v0.1.1-pre.106+632af90a9e [net472/AnyCPU] (64-bit .NET Framework 4.8.9075.0)
Copyright (C) .NET Foundation.

usage: xunit.v3.runner.console <assemblyFile>[:seed] [configFile] [assemblyFile[:seed] [configFile]...] [options] [reporter] [resultFormat filename [...]]
```

And just `[:seed]` for the in-process runner:

```
 pwsh> ./src/xunit.v3.assert.tests/bin/Debug/net472/xunit.v3.assert.tests.exe --help
xUnit.net v3 In-Process Runner v0.1.1-pre.106+632af90a9e (64-bit .NET Framework 4.8.9075.0)
Copyright (C) .NET Foundation.

usage: [:seed] [path/to/configFile.json] [options] [filters] [reporter] [resultFormat filename [...]]
```

Seed is also settable via configuration file: https://xunit.net/docs/configuration-files#seed
