### ISSUE TITLE
DisableParallelization does not seem to be working properly

### ISSUE THREAD

**Issue by dlemstra** [xunit/xunit#2372]
I am not sure if this is an issue with VSTest but bradwilson asked me to open the issue in this repository. I have created a project with the following three classes:

```C#
namespace XUnitBug.Tests
{
    [CollectionDefinition(nameof(RunTestsSeparately), DisableParallelization = true)]
    public class RunTestsSeparately
    {
    }
}

namespace XUnitBug.Tests
{
    public partial class AllClasses
    {
        [CollectionDefinition(nameof(RunTestsSeparately))]
        public class Class1
        {
            [Fact]
            public void Test()
            {
                var random = new Random(1234);
                for (var i = 0; i < 1_000_000; i++)
                {
                    var value = random.Next();
                    SharedClass.Value = value;

                    Assert.Equal(value, SharedClass.Value);
                }
            }
        }
    }
}

namespace XUnitBug.Tests
{
    public partial class AllClasses
    {
        [CollectionDefinition(nameof(RunTestsSeparately))]
        public class Class2
        {
            [Fact]
            public void Test()
            {
                var random = new Random(5678);
                for (var i = 0; i < 1_000_000; i++)
                {
                    var value = random.Next();
                    SharedClass.Value = value;

                    Assert.Equal(value, SharedClass.Value);
                }
            }
        }
    }
}
```

With this setup I would expect that `Class1.Test()` and `Class2.Test()` would not be running at the same time but it seems that they are. I have created a demonstration of the issue in this repository https://github.com/dlemstra/XUnitBug and also included a GitHub action that runs the tests from that project inside a container. The output of that run can be found here: https://github.com/dlemstra/XUnitBug/runs/3476327901

**Comment by bradwilson** [comment]
I notice that your tests are decorated like this:

```csharp
[CollectionDefinition(nameof(RunTestsSeparately))]
```

Was this an unintentional typo in your sample? It should be:

```csharp
[Collection(nameof(RunTestsSeparately))]
```

(There is clearly a case to be made here for a warning at runtime and/or a source analyzer about multiple uses of `[CollectionDefinition]` with the same name.)

**Comment by dlemstra** [comment]
Great find and I really should have read the documentation here better: https://xunit.net/docs/shared-context.
