### ISSUE TITLE
InlineData rejects decimal constants

### ISSUE THREAD

**Issue by oscar54321** [xunit/xunit#2388]
I have the following test theory configuration that is using InlineData attribute:

```
const decimal moneyValue = 1M;
[Theory]
[InlineData(QT.Common.Side.Buy, moneyValue)]
```

I get an highlight under moneyValue and compiler error CS0182 "an attribute argument must be a constant expression, typeof....

But moneyValue IS a constant. 

If I replace moneyValue in attribute argument with an integer (for example, 1000000), error CS0182 message goes away.

**Comment by bartelink** [comment]
See https://stackoverflow.com/a/3192891/11635 - does the tail of the message cover this sufficiently? Can you suggest a better wording that would have confused you less?

The workaround is to have a `MemberData` and have the method yield the values you're using `InlineData` for

**Comment by oscar54321** [comment]
Oh, I see, it is a CLR limitation, not xunit fault. Thanks!
