### ISSUE TITLE
AssemblyRunner and TaskCompletionSource throws Dispose exception

### ISSUE THREAD

**Issue by hudecekd** [xunit/xunit#2392]
Hello,

I am using `AssemblyRunner.WithoutAppDomain` and I have a problem. If I try to use `TaskCompletionSource` instead of `ManualResetEvent` to wait for runner to be finished it fails with exception.

```
This exception was originally thrown at this call stack:
    Xunit.Runners.AssemblyRunner.Dispose() in AssemblyRunner.cs
    ConsoleApp49.Program.ExecuteAsync(bool) in Program.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in ExceptionDispatchInfo.cs
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task) in TaskAwaiter.cs
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) in TaskAwaiter.cs
    System.Runtime.CompilerServices.TaskAwaiter.GetResult() in TaskAwaiter.cs
    ConsoleApp49.Program.Main(string[]) in Program.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in ExceptionDispatchInfo.cs
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task) in TaskAwaiter.cs
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) in TaskAwaiter.cs
    ...
    [Call Stack Truncated]

```
[ConsoleApp49.zip](https://github.com/xunit/xunit/files/7278078/ConsoleApp49.zip)

I have attached example project to reproduce the problem.

**Comment by bradwilson** [comment]
It looks like you're hitting a race condition. `OnExecutionComplete` is being called _while the engine is finishing up_, and by using a `Task` (that's potentially running on a different thread), your code to shut things down will start running before the engine is actually idle. If you want to use a `Task`, then you're still going to need to wait for the engine to actually become idle before trying to dispose the runner.

**Comment by hudecekd** [comment]
Hi @bradwilson  so it should be some race condition problem in xunit since it works with `ManualResetEvent` but does not work with tasks. I can use `ManualResetEvent` but thought that creating issue with possible problem in xunit is the best to track it and maybe someone will investigate it in the future.

**Comment by bradwilson** [comment]
The race condition was introduced by you using Tasks, which introduces parallelism (multi-threading) to the problem, combined with the fact that our reporting of `OnExecutionComplete` does _not_ mean "the engine is idle", just a notification that we've finished running the tests (but not necessarily finished cleaning up).

You must wait for idle before disposing the engine. Without you introducing parallelism, in effect the engine will be idle after the event has been reported. With the parallelism you've introduced, it's your responsibility to spin and wait for the engine to become idle. Or just use the event instead of the task and avoid needing to do that.

**Comment by hudecekd** [comment]
Hi @bradwilson  but from your example here https://github.com/xunit/samples.xunit/blob/main/TestRunner/Program.cs it seams that when `OnExecutionComplete` occurs I can assume it is possible to dispose runner. At least it is what example is doing. "waiting until OnExecutionComplete occurs and then allowing runner to be disposed".
Does it mean that example is not actually correct?

Thanks
Dusan

**Comment by bradwilson** [comment]
No, the sample uses an event (which according to your example code works fine). The issue is using a `Task`.

**Comment by hudecekd** [comment]
Hi @bradwilson  ok I think that now i understand why example works. It is actually **lucky**. If `ManualResteEvent` is used but i add some delay then runner does not "finish" fullly and same exception occurs. So I think that this example is working if there is no additional code which would slow down `OnExecutionComplete`.
Thanks for clarification.

```
runner.OnExecutionComplete = (info) =>
            {
                finished.Set();
                Thread.Sleep(1000); // now disposing fails even for event because runner will not be idle since it will be still "doing something"
            };
```
