### ISSUE TITLE
Assert.Equal(float, float, float) introduced a source breaking change

### ISSUE THREAD

**Issue by ericstj** [xunit/xunit#2393]
The addition of this API: https://github.com/xunit/assert.xunit/commit/8e86f1d10f2a38acbb9bf6fc5a4f19b583ca1939
```
public static void Equal(float expected, float actual, float tolerance)
```

Created an ambiguity for code that was calling `Assert.Equal(float, float, int)`

Here's a sample error:
```
error CS0121: The call is ambiguous between the following methods or properties: 'Assert.Equal(double, double, int)' and 'Assert.Equal(float, float, float)'
```

This could be avoided by adding an overload for `Assert.Equal(float, float, int)` that calls `Assert.Equal(double, double, int)` if this break was unintentional.

Repro project: [xunitAssert.zip](https://github.com/xunit/xunit/files/7288161/xunitAssert.zip)

**Comment by bradwilson** [comment]
No, this break was not intentional.

**Comment by bradwilson** [comment]
Fixed in xunit/assert.xunit#56 and tested in https://github.com/xunit/xunit/commit/e2250e080598c5d8f74def03ffe3fe60dc44ef63
