### ISSUE TITLE
Include flowId and parseServiceMessagesInside in testStdOut message to TeamCity

### ISSUE THREAD

**Issue by andrew-at-octopus** [xunit/xunit#2397]
When running xunit tests, we found that the output was not being grouped with the test in TeamCity, this appears to be because the testStdOut message is missing the flowId.

Also we wanted to include ##teamcity service messages in the output, and have them acted upon by teamcity for the purpose of adding test metadata such as links to external information.

We have implemented this in a fork, and shown that it does meet our integration needs with TeamCity.

**Comment by bradwilson** [comment]
Actually, not a dup, now that I look at your PR.
