### ISSUE TITLE
Parameter enumeration is continued before running test

### ISSUE THREAD

**Issue by rick-palmsens** [xunit/xunit#2403]
I am generating disposable parameters for a test, but they are disposed before the test is run. This seems to be because it first generates all parameters, and only then runs the tests. I would prefer it to enumerate the parameters properly instead of trying to store all of them in memory first. A take one -> run one approach would support disposability, and also reduced memory usage by not keeping all parameters in memory at once, which is kind of the point of IEnumerable.

Example:
```csharp
using System;
using System.Collections.Generic;
using Xunit;

namespace xUnitIteration
{
    public class Tests
    {
        public class Foo : IDisposable
        {
            public bool IsDisposed { get; private set; } = false;

            public void Dispose()
            {
                IsDisposed = true;
            }
        }

        public static IEnumerable<object[]> GenerateParameters()
        {
            for (int i = 0; i < 10; ++i)
            {
                var foo = new Foo();
                yield return new object[] { foo };
                foo.Dispose();
            }
        }


        [Theory]
        [MemberData(nameof(GenerateParameters))]
        public void IterationTest(Foo foo)
        {
            Assert.False(foo.IsDisposed);
        }
    }
}

```

**Comment by bradwilson** [comment]
You should [disable theory pre-enumeration](https://xunit.net/docs/configuration-files#preEnumerateTheories) to get the behavior you want.

Note that by disabling this, you will no longer see individual theory data rows in Test Explorer in Visual Studio, since generating that list requires pre-enumerating the theory data.
