### ISSUE TITLE
Unable to install xUnit.net package into a project targeting .NET 4.0

### ISSUE THREAD

**Issue by kkm000** [xunit/xunit#241]
Visual Studio Ultimate 2012.4 on Windows 7. Attempting to install the pre-release package produces the following error:

Attempting to resolve dependency 'xunit.core (= 2.0.0-beta5-build2785)'.
Attempting to resolve dependency 'xunit.abstractions (= 2.0.0-beta5-build2785)'.
Attempting to resolve dependency 'xunit.assert (= 2.0.0-beta5-build2785)'.
Installing 'xunit.abstractions 2.0.0-beta5-build2785'.
Successfully installed 'xunit.abstractions 2.0.0-beta5-build2785'.
Installing 'xunit.core 2.0.0-beta5-build2785'.
Successfully installed 'xunit.core 2.0.0-beta5-build2785'.
Installing 'xunit.assert 2.0.0-beta5-build2785'.
Successfully installed 'xunit.assert 2.0.0-beta5-build2785'.
Installing 'xunit 2.0.0-beta5-build2785'.
Successfully installed 'xunit 2.0.0-beta5-build2785'.
Adding 'xunit.abstractions 2.0.0-beta5-build2785' to libExperiment.Unittest.
Successfully added 'xunit.abstractions 2.0.0-beta5-build2785' to libExperiment.Unittest.
Adding 'xunit.core 2.0.0-beta5-build2785' to libExperiment.Unittest.
Uninstalling 'xunit.core 2.0.0-beta5-build2785'.
Successfully uninstalled 'xunit.core 2.0.0-beta5-build2785'.
Uninstalling 'xunit.abstractions 2.0.0-beta5-build2785'.
Successfully uninstalled 'xunit.abstractions 2.0.0-beta5-build2785'.
Install failed. Rolling back...
Could not install package 'xunit.core 2.0.0-beta5-build2785'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by AIgin** [comment]
For v2.2.0 requires .NET 4.5.2. Otherwise, you get `Could not find any of the following assemblies: xunit.execution.desktop.dll` error due to package `xunit.extensibility.execution` (#1083)
