### ISSUE TITLE
Runner utility support of test discovery in test assembly 

### ISSUE THREAD

**Issue by kareemshibli** [xunit/xunit#2412]
i have two cs projects one is test project and the other xunit runner project and iam trying to run the test dll from the first project in the second project.
now if i understand this correctly the test project is in a different app domain from xunit runner project and thus i need to load it to my runner project app domain.
after i did this and try to run test dll, xunit runner could not discover any test ? what is needed to discover tests in my test dll ?

note: there is no errors bout missing dll's from test roject
note: when i merge these two projects to one project and get single deployable unit the discovery works

thanks

environment:
.NET 5

**Comment by bradwilson** [comment]
I'm sorry, I'm going to need more information about what you're trying to do; in particular, a repro case would be useful here to help me understand what's going wrong.

**Comment by bradwilson** [comment]
Closing for age. Please open a new issue with a full repro project. Thanks!
