### ISSUE TITLE
Equivalence issue using structs containing reference types

### ISSUE THREAD

**Issue by JunkyXL86** [xunit/xunit#2431]
There is an unexpected assertion when testing for equivalence of two structs that have a field with a reference type.
I noticed that when using a Dictionary<int, #SomeReferenceType#>.

When the dictionary is checked it ends up in a simple .Equals() check on the iterated KeyValuePair, which works fine as long as TKey and TValue are 'primitives' (Guid, string, int, ...). But if you have a struct containg a field of a reference type, this reference gets compared by reference and not by equivalence anymore.
Affected part: https://github.com/xunit/assert.xunit/blob/37b46d188a5a8410cb2c15a208437b7f009a8068/Sdk/AssertHelper.cs#L118

IMO value types (except for strings, enumerables) should be treated like reference types in terms of equivalence checking as long as you have a reference type somewhere in the struct hierarchy.

Attached a super slim repro.
[ValueTypeEquivalence.zip](https://github.com/xunit/xunit/files/7633846/ValueTypeEquivalence.zip)

**Comment by bradwilson** [comment]
Have you tried using the new `Assert.Equivalent` in the 2.4.2 pre-release builds? I would be curious to know whether it covers your use cases. Here are the existing test cases for the feature, which should show some examples of usage: https://github.com/xunit/xunit/blob/v2/test/test.xunit.assert/Asserts/EquivalenceAssertsTests.cs

**Comment by bradwilson** [comment]
(sorry, deleted my previous response, as I thought this was a question about `Assert.Equal`)

**Comment by JunkyXL86** [comment]
Will there be a release soon?

**Comment by JunkyXL86** [comment]
Would you like me to create a Pull Request for this fix?

**Comment by bradwilson** [comment]
Sure!

**Comment by bradwilson** [comment]
Fixed in xunit/assert.xunit#57 and tested in https://github.com/xunit/xunit/commit/cc47692f2bae26e28ce45dc0edfb6117f12ef2bc
