### ISSUE TITLE
Review to ensure we never double enumerate

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#2439]
Some work has already happened with the v3 codebase to try to minimize or eliminate any internal usage of `IEnumerable` or `IEnumerable<T>`, instead favoring things like `IReadOnlyCollection<T>` (there is no non-generic version). This issue is a reminder to complete this work in the core [`xunit/xunit`](https://github.com/xunit/xunit) repo, and to also review and fix the [`xunit/assert.xunit`](https://github.com/xunit/assert.xunit) repo.

For the former, we are mostly comfortable breaking contracts from v2 to v3. For the latter, the repo is shared between v2 and v3, so some effort must be expended to ensure that we don't break the contracts contained therein. One possibility might include duplicating assertions which take `IEnumerable` or `IEnumerable<T>` to also include `IReadOnlyCollection<T>` versions, forwarding off to the safer versions with copies of the collections provided. We will also need to verify whether this introduces potentially compiler ambiguity situations.

**Comment by drewnoakes** [comment]
There's a new Roslyn analyzer that can help with this: https://github.com/dotnet/roslyn-analyzers/pull/5304

**Comment by bradwilson** [comment]
@drewnoakes Is this RTM'd? I don't see any analyzer issues here:

<img width="345" alt="image" src="https://user-images.githubusercontent.com/16944/167063512-1d84c8aa-330c-4140-ba80-8c1fac8f7de3.png">

<img width="896" alt="image" src="https://user-images.githubusercontent.com/16944/167063576-df7f3b5f-dc5c-4ade-9991-cc6992951246.png">

<img width="658" alt="image" src="https://user-images.githubusercontent.com/16944/167063667-f67e1716-d052-4b30-8aef-80880a2cda58.png">

**Comment by drewnoakes** [comment]
It was merged recently so might not be available yet.

**Comment by bradwilson** [comment]
> Have you set the AnalysisLevel property anywhere?

Nope, just setting it to `latest` in the .props file.

**Comment by drewnoakes** [comment]
Tagging @Cosifne for input here. Would you expect your analyser to be available in this case?

**Comment by waf** [comment]
This analyzer is available in .NET 7 now, but to get it to work I needed to explicitly enable it in my `.editorconfig`:

```ini
dotnet_diagnostic.CA1851.severity = warning
```

**Comment by bradwilson** [comment]
@waf Thanks! That's very helpful, and I've enabled it already. One instance of double-enumeration found in the custom build tool, but none in the core source itself. 😌 https://github.com/xunit/xunit/commit/e138f20c0b44909faf269af5646c5448bd4c0030

**Comment by bradwilson** [comment]
This should be resolved as of v2 `2.5.0-pre.2` and v3 `0.1.1-pre.204`.

Assertion library: https://github.com/xunit/assert.xunit/commit/f0b6639870c5e10a3ed5512457846b6f77d117d9
v2: https://github.com/xunit/xunit/commit/782190126b90f60b29b3ae2c983eee70f507c7b9
v3: https://github.com/xunit/xunit/commit/47e536c9d0cb3e3d82f707787b9cc558beb742a9
