### ISSUE TITLE
Add Assert.SequenceEqual to make it easy to prevent wrong overload resolution in Assert.Equal with collections.

### ISSUE THREAD

**Issue by Quahu** [xunit/xunit#2450]
Currently it's very easy to make the mistake of comparing two collection types that aren't stored as `IEnumerable<T>`s and have `Assert.Equal<T>(T expected, T actual)` pick it up when we'd actually want the `Assert.Equal<T>(IEnumerable<T> expected, IEnumerable<T> actual)` overload.

Example:
```cs
var array1 = new object[] { 1, 2, 3 };
var array2 = new object[] { 1, 2, 3 };
Assert.Equal(array1, array2);
```

Outputs the following in Rider:
```
Xunit.Sdk.EqualException
Assert.Equal() Failure
Expected: Object[] [1, 2, 3]
Actual:   Object[] [1, 2, 3]
```

Putting aside the somewhat confusing error, this is solvable by either casting one of the arrays or calling `AsEnumerable()`. for example:
```cs
Assert.Equal(array1, array2.AsEnumerable());
```

However I don't think this is a very good solution, it's very easy not to realize the wrong overload is getting called.
Hence I propose that the following methods should be added to the API:
```cs
public static void SequenceEqual<T>(IEnumerable<T> expected, IEnumerable<T> actual);
public static void SequenceEqual<T>(IEnumerable<T> expected, IEnumerable<T> actual, IEqualityComparer<T> comparer);
```
They can simply call the existing `Equal()` methods and exist alongside them. This lets me write the following code and rest easy knowing that I'm treating the values as collections correctly:
```cs
Assert.SequenceEqual(array1, array2);
```
It could then make sense to wrap the `EqualException` that gets thrown by the called `Assert.Equal()` in a `SequenceEqualException` with the `UserMessage` then being `"Assert.SequenceEqual() Failure"` rather than `"Assert.Equal() Failure"`. As an alternative the exception could be rethrown with the `UserMessage` property internally set to the new message.

#1671 mentions this method name, but isn't perhaps directly related.

**Comment by Quahu** [comment]
This is an error on my part, the `AssertEqualityComparer` handles `IEnumerable`s, so this issue is completely wrong. The error was due to the boxed numbers being different types, i.e:
```cs
var array1 = new object[] { 1, 2, 3 };
var array2 = new object[] { 1, 2, 3l }; // for example, the last number is a long and not an int
Assert.Equal(array1, array2);
```
Causes the above error:
```
Xunit.Sdk.EqualException
Assert.Equal() Failure
Expected: Object[] [1, 2, 3]
Actual:   Object[] [1, 2, 3]
```
I apologize for possibly causing any confusion.

**Comment by bradwilson** [comment]
I noticed this issue linked to another, and wanted to point out if someone happens across it that the new assertion library makes this failure much more obvious now:

```
   Assert.Equal() Failure: Collections differ
                 ↓ (pos 2, type System.Int32)
Expected: [1, 2, 3]
Actual:   [1, 2, 3]
                 ↑ (pos 2, type System.Int64)
```
