### ISSUE TITLE
`xUnit.Assert.Source` package results in warnings from analyzer which cannot be fixed

### ISSUE THREAD

**Issue by azygis** [xunit/xunit#2472]
We're using the `xunit.assert.source@2.4.1` package to extend `Assert` class (that way it's a bit cleaner - all the asserts are in the same place as opposed to our "CustomAssert" class or something of the sorts). This leads to two warnings generated, `xUnit2007` and `xUnit2015`.

The warnings themselves are clear, everything's good with them, but we cannot fix them ourselves. We can just add the `<NoWarn>xUnit2007,xUnit2015</NoWarn>` to the project, but that's also not desirable - misuse in our own code would not yield a warning.

I saw there's a prerelease package in NuGet, but based on [latest v2 commit](https://github.com/xunit/assert.xunit/blob/43e3e208a597bc1a4c77f2665f39f98e7401c157/ExceptionAsserts.cs) the asserts are still the same.

Are there any plans on fixing this in v2 (I understand you guys are working hard on v3), and is that resolved in v3?

**Comment by bradwilson** [comment]
Fixed in `2.5.0-pre.35`
