### ISSUE TITLE
Incorrect warning about InlineData duplicates

### ISSUE THREAD

**Issue by pekspro** [xunit/xunit#2473]
This code:

```C#
using Xunit;

namespace XuntUnitTestDuplicateWarning
{
    public class UnitTest1
    {
        [Theory]
        [InlineData(new int[] { -1 }, new int[] { 0 }, new int[] { 1, 2 })]
        [InlineData(new int[] { -1 }, new int[] { 0, 1 }, new int[] { 2 })]
        public void Test(int[] a, int[] b, int[] c)
        {
        }

        [Theory]
        [InlineData(new int[] { 0 }, new int[] { 1, 2 })]
        [InlineData(new int[] { 0, 1 }, new int[] { 2 })]
        public void Test2(int[] b, int[] c)
        {
        }
    }
}
```

Gets this warning on the first test. 

    Theory method 'Test' on test class 'UnitTest1' has InlineData duplicate(s).

Tested with latest version in Visual Studio 2022.

![image](https://user-images.githubusercontent.com/3163293/151347768-4c1a827b-7c1d-4ef6-a78a-bcceaadc9422.png)

The second test has no warning. I find that to be fascinating 😊

**Comment by bradwilson** [comment]
I'm unsure exactly _when_ this got fixed, but it's fixed in `1.2.0-pre.24`, so it'll be fixed in the final `1.2.0` release (which will be part of xUnit.net v2 `2.5.0`).
