### ISSUE TITLE
AD0001 : Analyzer 'Xunit.Analyzers.AssertEqualLiteralValueShouldBeFirst' threw an exception of type 'System.NullReferenceException'

### ISSUE THREAD

**Issue by fjmorel** [xunit/xunit#2475]
The following code in a xunit test project shows a warning when I build:
```
CSC: Warning AD0001 : Analyzer 'Xunit.Analyzers.AssertEqualLiteralValueShouldBeFirst' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
```
I don't know how to get a more detailed stack trace out of it.

```csharp
using Xunit;

public record Sample
{
    [Fact]
    public void AssertEqualAnalyzerError()
    {
        var test = "abc";
        Assert.Equal(test.GetType().Name, "string");
    }
}
```

I know this type of code is not great - it should be using IsType.

I am using the latest released version (0.10.0).

**Comment by bjornhellander** [comment]
Can reproduce this with 0.10.0 as specified, but not with 0.12.0-pre.19 or in a unit test

**Comment by bradwilson** [comment]
Agreed, cannot repro in 0.12.0-pre.24 so I'm closing this as already fixed.
