### ISSUE TITLE
Alternate test attributes

### ISSUE THREAD

**Issue by mattd73uk** [xunit/xunit#2479]
Hi,
I would like to create a PR that simply creates two new attributes:

- TestAttribute would simply inherit FactAttribute
- ParameterizedTestAttribute would simply inherit TheoryAttribute

The single reason I have encountered that developers give for not using xUnit is the unusual Fact/Theory naming convention.  This simple change would enable people to use a more conventionally named Test attribute if they wanted.
By using inheritance, the new attributes won't need any future maintenance.

Please.  It's 2022, and yet again a new project I'm working on is adopting NUnit purely because it calls tests "tests".

**Comment by mattd73uk** [comment]
"Things like these are rarely a technical problem," we are agreed, it's not technical, it's an easy to resolve issue of non-standard terminology
"the stated reason is rarely the real one." this is a quite a bold claim.  You have lots of experience with people saying this 'Fact' terminology is distracting?  What were their real reasons?

For me, I spend my days defining domains with object names that reflect business requirements.  The domain naming usefully communicates meaning, easing communication with the business.  In relation to testing I don't say to the business "We can't release because 6 facts are false", they wouldn't know what I was talking about.  I say "6 tests have failed", i.e. the terminology adopted by the other test frameworks.  I agree with those others who dislike the terminology.

It would be helpful if you could give an example of the confusion that would be caused by people being able to label a test as a Test or a Fact, according to their preference.  How would it confuse you?

**Comment by mattd73uk** [comment]
I'm just taking the criticisms of the idea as they come - it looks like we are both trying to make the other think.  For example are you saying you know what "all the people behind the 46k downloads per day" want?  Is it important to you that XUnit doesn't reach out to anyone outside that number?

**Comment by IanKemp** [comment]
If your developers reject a particular framework based solely on the "reason" that they don't like the phraseology it uses, the problem is not with the framework.

If you allow your developers to reject a particular framework based solely on the "reason" that they don't like the phraseology it uses, the problem is still not with the framework.

If you attempt to solve internal problems by making external changes, you're not solving anything.

**Comment by bradwilson** [comment]
> I have encountered that developers give for not using xUnit is the unusual Fact/Theory naming convention.

I am in agreement with others here that this is not a problem worth fixing. Any number of reasons could exist for someone to use or not use a framework; someone who refuses to learn the names of `Fact` and `Theory` is undoubtedly going to come up with additional reasons they won't use the framework (for example, we removed most of the `Is` and `Are` names from assertions, like `Assert.True` vs. `Assert.IsTrue`).
