### ISSUE TITLE
Allow multiple `CollectionAttribute` per test class

### ISSUE THREAD

**Issue by magol** [xunit/xunit#2497]
I want it to be able to have multiple `CollectionAttribute `for one test class. The test class is then created in multiple instances with different shared context and all tests and their test data is run multiple times with different context. 

In this example, I have two `CollectionAttribute` and I use `CollectionDefinitionAttribute` to tell the construction parameters that differ the instances of `DatabaseFixture`.
```C#
[Collection("Database collection_1")]
[Collection("Database collection_2")]
public class UnitTest1
{
    private readonly DatabaseFixture _fixture;

    public UnitTest1(DatabaseFixture fixture)
    {
        _fixture = fixture;
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    public void Test1(int data)
    {
    }
}

public class DatabaseFixture : IDisposable
{
    public DatabaseFixture(string connectionString, string someOtherParameter)
    {
        Db = new SqlConnection(connectionString);

        // ... initialize data in the test database ...
    }

    public void Dispose()
    {
        // ... clean up test data from the database ...
    }

    public SqlConnection Db { get; private set; }
}

// Define the collections and give the constructor parameters to construct the DatabaseFixture object
[CollectionDefinition("Database collection_1", parameters: new[] { "myConnectionString1", "Some other information")]
[CollectionDefinition("Database collection_2",                     "myConnectionString2", "Something else"        )]
public class DatabaseCollection : ICollectionFixture<DatabaseFixture>
{
    // This class has no code, and is never created. Its purpose is simply
    // to be the place to apply [CollectionDefinition] and all the
    // ICollectionFixture<> interfaces.
}
```

The result is as follow
```
UnitTest1
    UnitTest1("myConnectionString1", "Some other information")
        Test1
            Test1(0)
            Test1(1)
    UnitTest1("myConnectionString2", "Something else")
        Test1
            Test1(0)
            Test1(1)
```

Of course, this can be solved with `InlineData` or something similar, but if you have a lot of `InlineData` to each test case, these must be multiplied by all alternatives to context, and it quickly becomes unmanageable

I have a repository with the example code: https://github.com/magol/XunitCollectionTest

**Comment by ldeluigi** [comment]
Possibly related to #352, because this would represent the best alternative to parameterised fixtures

**Comment by bradwilson** [comment]
Collections are a parallelization and context-sharing boundary. They aren't meant to be used this way.

The workaround right now would be:

- Use abstract base class for fixture, derived classes for the parameters
- Use abstract base class for tests, derived classes with the fixture decoration

So, approximately:

```csharp
using Xunit;

public abstract class DatabaseTestBase
{
    private readonly DatabaseFixture _fixture;

    public DatabaseTestBase(DatabaseFixture fixture)
    {
        _fixture = fixture;
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    public void Test1(int data)
    { }
}

[Collection("Database collection_1")]
public class DatabaseTest1 : DatabaseTestBase
{
    public DatabaseTest1(DatabaseFixture1 fixture) : base(fixture)
    { }
}

[Collection("Database collection_2")]
public class DatabaseTest2 : DatabaseTestBase
{
    public DatabaseTest2(DatabaseFixture2 fixture) : base(fixture)
    { }
}

public abstract class DatabaseFixture : IDisposable
{
    public DatabaseFixture(string connectionString, string someOtherParameter)
    { }

    public void Dispose()
    { }
}

public class DatabaseFixture1 : DatabaseFixture
{
    public DatabaseFixture1() : base("myConnectionString1", "Some other information")
    { }
}

public class DatabaseFixture2 : DatabaseFixture
{
    public DatabaseFixture2() : base("myConnectionString2", "Something else")
    { }
}

[CollectionDefinition("Database collection_1")]
public class DatabaseCollection1 : ICollectionFixture<DatabaseFixture1>
{ }

[CollectionDefinition("Database collection_2")]
public class DatabaseCollection2 : ICollectionFixture<DatabaseFixture2>
{ }
```

**Comment by ldeluigi** [comment]
@bradwilson , your solution implies either duplicating the number of actual test classes or transforming every single fact test to a theory. This issue aims to avoid both these costly operations.


We understand that

> Collections are a parallelization and context-sharing boundary. They aren't meant to be used this way.

but you should consider designing this feature anyway, because it's not in contrast with the design and meaning of collections. If a collection of tests represents a boundary, consider parameterized collections as a collection of collections, meaning they are different collections, with all the effects and consequences. In your code, you are in fact creating two different collections! This feature would just be a shortcut to that, we don't want to change how collections work, just how they can be defined.

**Comment by space-alien** [comment]
Adding my vote for #2150. This level of complexity just to switch something like a connection string parameter doesn't feel right.
