### ISSUE TITLE
How can one reimplement [SkippableFact] and [SkippableTheory] in Xunit2.0?

### ISSUE THREAD

**Issue by nulltoken** [xunit/xunit#250]
Some of the LibGit2Sharp **[tests](https://github.com/libgit2/libgit2sharp/search?utf8=%E2%9C%93&q=Skippable&type=Code)** rely on `[SkippableFact]` and `[SkippableTheory]` attributes that were provided as **[examples](https://github.com/xunit/xunit/blob/v1/samples/AssertExamples/DynamicSkipExample.cs)** in v1.9.x.

However, DynamicSkipExample.cs has been dropped in commit **[2deeff5](https://github.com/xunit/xunit/commit/2deeff5cb60bdb8c12fd4f3cfaa38035cdbc7ba6#diff-1)** on the road to version 2.0.

Could you please provide us with some guidance regarding how to reimplement them in Xunit 2.0?

*Related:* https://stackoverflow.com/questions/27755539/how-to-dynamically-skip-a-test-with-xunit-2-0

**Comment by mudnug** [comment]
I've experimented with the code and made a suggestion on the stackoverflow post.

**Comment by nulltoken** [comment]
@mudnug Thanks for your answer. As explained in my comment in the SO question, I'd be very interested in a similar mechanism than the `SkipException` that allow the test to make a decision based on its context, the data its working with to eventually "decide" to be skipped.

**Comment by mudnug** [comment]
In XUnit 2 there is no context during test execution and the decision to skip the test is no longer available once the test starts. You would need to determine whether the test should be skipped based on something you can derive from the testMethod or factAttribute.

If you wanted to override this behavior, you would need to write your own runner (that could perhaps accept a SkipException during test execution and mark a test as skipped). If you do so, however, you would no longer be able to use any of the standard runners.

See the RunAsync() in
https://github.com/xunit/xunit/blob/8d4e6b68caa7c7e875ac4db72e4c87f4b12c0155/src/xunit.execution/Sdk/Frameworks/Runners/TestRunner.cs

**Comment by dahlbyk** [comment]
Could we work around the need for a `SkipException` by implementing a strategy pattern of sorts, e.g.

```csharp
[SkippableFact(typeof(RequirePrivateRepoUrl))]
public void CanDoSomethingWithPrivateRepoUrl() { ... }

class RequirePrivateRepoUrl : ISkippable
{
    public string Skip()
    {
        if (string.IsNullOrEmpty(Constants.PrivateRepoUrl))
            return "Populate Constants.PrivateRepo* to run this test";

        return null;
    }
}
```

Skippable theories dependent on `InlineData` make the API a bit trickier...maybe a bit of duck typing could work?

```csharp
[SkippableTheory(typeof(SupportsIgnoreCase), "ignorecase")]
public void CanDoSomethingWithPrivateRepoUrl(bool ignorecase) { ... }

class SupportsIgnoreCase : ISkippable  // marker interface, look for "Skip" method by convention?
{
    public string Skip(bool ignorecase)
    {
        if (ignorecase)
            return "Skipping 'ignorecase = true' test due to ignorecase issue in libgit2.";

        return null;
    }
}
```

It seems like this would be preferable to a custom runner, but I'd need to familiarize myself with XUnit internals to make it happen. At first glance the sample `SkippableTestCaseDiscoverer` code seems...complex.

**Comment by dahlbyk** [comment]
Also, out of curiosity... why this:
```csharp
[XunitTestCaseDiscoverer("TestUtility.CulturedFactAttributeDiscoverer", "test.utility")]
```
instead of this:
```csharp
[XunitTestCaseDiscoverer(typeof(TestUtility.CulturedFactAttributeDiscoverer))]
```
:question:

**Comment by bradwilson** [comment]
The reflection abstractions in xUnit.net are built without any assumption of being able to load types, as source-based runners (like Resharper and CodeRush) would like to be able to do discovery without actually having compiled (or even compilable) code.

Also, using the strings means the assemblies need not have references to one another (which would've caused circular reference problems between `xunit.core` and `xunit.execution`).

**Comment by bradwilson** [comment]
I've moved this to our samples project (ignore the incorrectly opened issue for the doc site, sorry).

Please continue any conversation/suggestions there.

https://github.com/xunit/samples/issues/8

**Comment by brazilbean** [comment]
@bradwilson  -  broken link - can you please update?

**Comment by mudnug** [comment]
Based on the headliner I'm seeing at https://github.com/xunit/samples.xunit, I believe he once again wants related issues raised here in https://github.com/xunit/xunit/issues

**Comment by bradwilson** [comment]
Yes, the sample lives here: https://github.com/xunit/samples.xunit/tree/master/DynamicSkipExample
