### ISSUE TITLE
Release notes links return a 404

### ISSUE THREAD

**Issue by rilehudd** [xunit/xunit#2512]
All the links listed here all give a 404: https://github.com/xunit/xunit/releases.

I checked several of them back in time. But the most recent is:
"Release notes are available here: http://xunit.github.io/release-notes/2015-09-27.html"

Has this method for retrieving the release notes been deprecated? Is there an alternative?

**Comment by snakefoot** [comment]
https://xunit.net/release-notes/2015-09-27.html redirects to https://xunit.net/releases/2.1

**Comment by rilehudd** [comment]
I see what you are saying, but what is in the xunit release notes doesn't point to https://xunit.net/release-notes/2015-09-27.html, it points to http://xunit.github.io/release-notes/2015-09-27.html.

**Comment by bradwilson** [comment]
Related to a different issue, I have deleted all the old releases on GitHub, which had bad links.

All release notes live here: https://xunit.net/#releases
