### ISSUE TITLE
VisualStudio warning hover over hint contains broken link

### ISSUE THREAD

**Issue by RobDBob** [xunit/xunit#2514]
Using assert on int variable generates a warning with an hyperlink pointing to https://xunit.github.io/xunit.analyzers/rules/xUnit2002

```
int a = 0

Assert.NotNull(a);
```

**Comment by mongeon** [comment]
@RobDBob Which version of xunit are you using? The link has been changed in 2020:
https://github.com/xunit/xunit.analyzers/blob/de864cca9048ed9b7df7f3affbf79c73b5e6d434/src/xunit.analyzers/Utilities/Descriptors.cs#L32

**Comment by bradwilson** [comment]
These links are definitely fixed in later builds, so closing this.
