### ISSUE TITLE
Assert.NotNull with Nullable<T>

### ISSUE THREAD

**Issue by terrajobst** [xunit/xunit#2516]
Akin to `Assert.Single()` it would be nice to have a method like this:

```C#
class Assert
{    
    public static T NotNull<T>(T? value) where T: struct;
}
```

The idea is:

If the value is `null`, it throws. If it's not `null`, it returns the underlying `T`.

Thoughts?

**Comment by JoelLoven** [comment]
Except for not returning the instance typed as ` T` `NotNull` already accepts nullable. And overload with the same name that also checks the type could be a bit confusing.
Maybe `IsInstanceOfType<T>` or similar naming would be better

**Comment by bradwilson** [comment]
This is an easy one to do, so I'll add it to 2.5.
