### ISSUE TITLE
Analyzer to suggest replacing Assert.True(false, "") with Assert.Fail for better test failure messages

### ISSUE THREAD

**Issue by drewnoakes** [xunit/xunit#2521]
I found some code like this today:

```c#
Assert.False(true, $"{definition.Type.FullName} exports a contract {exportDefinition.ContractName}, which is not applied with [ProjectSystemContract]");
```

This produces a failure saying "expected false but got true". Description of the boolean values here isn't really helpful. The message is the key information you need.

xunit has some really nice analyzers to help use the assertion library well. An analyzer that suggested replacing `Assert.False(true, ...` and `Assert.True(false, ...` could be a nice addition.

**Comment by bradwilson** [comment]
Note that the analyzer should probably only trigger when the project is using xUnit.net 2.5 or later, since that's when `Assert.Fail` was introduced.
