### ISSUE TITLE
How to build xunit.runner.visualstudio

### ISSUE THREAD

**Issue by mudnug** [xunit/xunit#253]
The version of xunit.runner.visualstudio up on nuget is from build1021 in November. We are seeing a System.Reflection.TargetParameterCountException in a particular case and wondering how we might rebuild this nuget package or the dll in order to match it up with the beta5 build2785 (to see if that fixes our issue).

**Comment by bradwilson** [comment]
The source is here: https://github.com/xunit/visualstudio.xunit

If you want the version that was release as 0.99.9, you should check out to that tag: https://github.com/xunit/visualstudio.xunit/commit/bb22b57b07883e684c2f126c57a2cfdcf999d62f
