### ISSUE TITLE
xunit.net releases not showing latest?

### ISSUE THREAD

**Issue by jscott-concord** [xunit/xunit#2533]
Looking at the top level page it shows 2.1 as the latest release from 2015. Looking at tags and what is released on NuGet it appears that should be reflecting 2.4.1

![image](https://user-images.githubusercontent.com/65616979/172208442-0ee51e40-0ce2-46b9-8b21-ea911b6b4378.png)

**Comment by bradwilson** [comment]
We don't use the release notes system on GitHub any more.

Release notes are here: https://xunit.net/#releases

**Comment by bradwilson** [comment]
I have deleted all the old releases from GitHub, just to be sure there's no future confusion.
