### ISSUE TITLE
getting an error The following constructor parameters did not have matching fixture data: PostgreSqlResource resource

### ISSUE THREAD

**Issue by pratapkumarch** [xunit/xunit#2538]
I am using xunit to do integration testing, and below is my test class.

    public class CodesAndGuidelinesTest : IClassFixture<SchemaCache>
    {
        public readonly SchemaCache schemaCache;
        public CodesAndGuidelinesTest(PostgreSqlResource resource) 
        {
            schemaCache = new SchemaCache(resource);
        }

        [Fact]
        public async Task Create_Name_Contains_Expression()
        {
            IRequestExecutor requestExecutor = await schemaCache.CodesAndGuidelinesExecutor;
            .......
        }
    }

Here is the schema cache class

    public class SchemaCache : QueryTestBase
    {
        Task<IRequestExecutor> _codesAndGuidelinesExecutor;
        public SchemaCache(PostgreSqlResource resource) : base(resource)
        {
            _codesAndGuidelinesExecutor = CreateDb(CodesAndGuidelinesMockFixture.codeStandardGuidelines);
        }

        public Task<IRequestExecutor> CodesAndGuidelinesExecutor
        {
            get { return _codesAndGuidelinesExecutor; }
        }
    }

Here `CodesAndGuidelinesMockFixture.codeStandardGuidelines` is just a mock object, and When I run the test cases, I am getting the below error. 

> Class fixture type 'API.Tests.SchemaCache` had one or more unresolved
> constructor arguments: PostgreSqlResource resource,
> CodeStandardGuideline[] codesAndGuidelines    The following
> constructor parameters did not have matching fixture data:
> PostgreSqlResource resource

I am not sure where I am doing wrong with the above code. Could anyone point me in the right direction?

Thanks!!!

QueryTestBase class 

    public class QueryTestBase
    {
        private readonly PostgreSqlResource _resource;
        public QueryTestBase(PostgreSqlResource resource)
        {
            _resource = resource;
        }

        protected async Task<Func<IResolverContext, IQueryable<T>>> BuildResolverAsync<T>(T[] arrayOfEntities) where T : class
        {
            var databaseName = Guid.NewGuid().ToString("N");
            var options = new DbContextOptionsBuilder<APIDbContext>()
                .UseNpgsql(_resource.ConnectionString)
                .Options;
            .......
			.......         
            return _ => set.AsQueryable();
        }

        protected async Task<IRequestExecutor> CreateDb<T>(T[] Entities) where T : class
        {
            Func<IResolverContext, IQueryable<T>> resolver = await BuildResolverAsync(Entities);

            return .......
        }
    }

**Comment by bradwilson** [comment]
Fixture classes are intended to be things that can be created independently. Your usage of `IClassFixture<SchemaCache>` does not match the constructor of the test class (which is currently taking `PostgreSqlResource`). That is at least part of your problem.

**Comment by bradwilson** [comment]
Closing for age. Please open a new issue with a full repro project. Thanks!
