### ISSUE TITLE
Cannot run xunit test case(source code)

### ISSUE THREAD

**Issue by sgalcheung** [xunit/xunit#2540]
When I build successful source code, everything is work well, but not found the run/debug button, right-click on the method and select run, but nothing happens.
![0b39da2307b7566a990ca71f0b290f1](https://user-images.githubusercontent.com/42566429/176588701-f6b2b737-92c0-454a-8e1d-247654786a53.png)

development environment:
windows11
Rider2021.3.3
Rider comes with MSBuild

**Comment by sgalcheung** [comment]
I use VS and found that **xunit.v3.core.tests** is not xunit test project ,Is it right?
![image](https://user-images.githubusercontent.com/42566429/177133281-37f4c062-5495-443f-a658-6ae58cde3584.png)

**Comment by bradwilson** [comment]
For now, that is correct. We do not have VSTest support for v3 right now, which means:

- no `dotnet test`
- no Visual Studio Test Explorer
- no Visual Studio Code in-editor UI

This is a temporary situation that will be fixed once we get closer to releasing v3.

**Comment by timabell** [comment]
`dotnet test` seems to work for me with the new xunit3 template, so perhaps this issue as originally described has been resolved?

That said, I can't currently make it show up in rider, but that could be just me doing something wrong.

**Comment by bradwilson** [comment]
Support for xUnit.net v3 in Rider was shipped in 2024.2. Please make sure you've upgraded.

**Comment by bradwilson** [comment]
And also going to close this, since we do support this now. 😄
