### ISSUE TITLE
Replace Task with ValueTask

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#2547]
`ValueTask` has memory and performance benefits over `Task`. v3 is the right time to ensure all public APIs and internal usage shift over to `ValueTask` as appropriate; this is especially valuable where extensibility points are designed to be "optionally async", where the non-async path will be much cheaper than `Task`.

More information: https://devblogs.microsoft.com/dotnet/understanding-the-whys-whats-and-whens-of-valuetask/

**Comment by mattzink** [comment]
FWIW, Stephan has stressed a few times in recent API design meetings that his opinion is still to default to Task, except under specific conditions (as he mentions in the linked blog post's summary). I believe he recommends using ValueTask only when 1) You believe the method will often return synchronously, 2) It will be called often enough that the small allocation avoidance is beneficial, and 3) You can live with the limitations (must be awaited immediately by caller, no WhenAny()/WhenAll(), etc).

From my team's experience, we found ValueTask to only outway its costs in tight loop IO scenarios.

**Comment by teo-tsirpanis** [comment]
Marc Gravell on the other hand has a different opinion, [recommending to _always_ use `ValueTask`](https://blog.marcgravell.com/2019/08/prefer-valuetask-to-task-always-and.html).

**Comment by bradwilson** [comment]
As mentioned above, any public API endpoints and extensibility points will be made `ValueTask`, because as Marc points out, changing that later becomes a breaking change (and v3 is the right time to do this, since it's the first version that supports `ValueTask`).

I am mostly compelled by Marc's post to just do a blanket conversion; I suspect there are very few truly private APIs in xUnit.net anyway (given its extensive extensibility support). And there should be no cases of double-awaiting anywhere inside the framework itself.

**Comment by bradwilson** [comment]
Turns out there wasn't much left to do; all the public APIs (except for `Record.ExceptionAsync`) were already updated to consume/return `ValueTask` instead of `Task`. The cleanup work involved primarily updating test helpers to use `ValueTask`: a17ec0d5d208b5b922020f2dfca507b79c6ee67c d1bb4249fd99ac6169692bac34d839649e447d68 fbf9d6c38555189e6307a168e06f0fc27f723fe3 2cee45afdc39ecce100db56c042086a4e96b345b

At the same time, I also replaced all the `async void` and `async Task` test signatures with `async ValueTask` (other than the acceptance tests specifically to validate `async void` and `async Task` functionality), which should slightly improve performance: 3b3038d6aa8d29bf85df293f0e202613ebfd55a1 0881e03f7afcdb4ef8ba41d42860441f678e7de5 20078b8db7de3486102a0e569349114fa28b621b bf88b39cdad280f4e3faa2f6c7e03fa14aa804b5

I also cleaned up the assertion tests, since they're shared with v2, which doesn't support `async ValueTask`: 1dd43ce684cc6d50bf726042173956e6bda2fa3b
