### ISSUE TITLE
ITestOutputHelper.WriteLine information is lost in VS if the test is stopped.

### ISSUE THREAD

**Issue by mrpmorris** [xunit/xunit#2552]
I have a test with a difficult to find deadlock. I've added logging via `ITestOutputHelper` to find the bug, but any content written via `ITestOutputHelper.WriteLine` is not output if you stop the test.

```c#
    public class UnitTest1
    {
        private readonly ITestOutputHelper TestOutputHelper;

        public UnitTest1(ITestOutputHelper testOutputHelper)
        {
            TestOutputHelper = testOutputHelper ?? throw new ArgumentNullException(nameof(testOutputHelper));
        }

        [Fact]
        public async Task Test1()
        {
            for (int i = 1; i <= 3; i++)
            {
                TestOutputHelper.WriteLine($"Old text {i}");
                await Task.Delay(1000);
            }
            //Console.Beep();
            //await Task.Delay(60_000);
        }
    }
```

1: Run the above test, and see the output appears in the IDE test output
2: Change "Old" to "New" in `TestOutputHelper.WriteLine`
3: Uncomment the last 2 instructions
4: Run the test and wait for the beep, so you know the content has been sent to `ITestOutputHelper.WriteLine`
5: Stop the test

Expected: New text
New text 1
New text 2
New text 3

Actual: The old output is retained, and the new output is lost
Old text 1
Old text 2
Old text 3

**Comment by bradwilson** [comment]
This behavior of retaining the old output is Visual Studio's decision, and we don't have any control over that I'm afraid. 😞

**Comment by mrpmorris** [comment]
Thank you. Checked in Rider and confirmed!

**Comment by mrpmorris** [comment]
For any other interested parties...

https://developercommunity.visualstudio.com/t/ITestOutputHelperWriteLine-information-/10103169
