### ISSUE TITLE
xUnit2005 not triggered when one parameter is null

### ISSUE THREAD

**Issue by bjornhellander** [xunit/xunit#2560]
Repro code:
```
Assert.Same(17, 18);
Assert.Same(17, null);
Assert.Same(null, 17);
```

Expected result:
xUnit2005 triggered for all asserts, since at least one of the values are of value type.

Actual result:
xUnit2005 only triggered for the first assert. (xUnit2003 is however triggered for the last one.)

xunit version: 2.4.1

**Comment by Eliminator1999** [comment]
Hi, I am a first time contributer, and would want to try and take this task, and would appreciate any help in starting

**Comment by Sevarius** [comment]
@Eliminator1999 May I ask, are you still working on this issue?

**Comment by Eliminator1999** [comment]
go ahead 👍
