### ISSUE TITLE
TryConvertType errors for InlineData of type int to nullable double - since version 2.4.2

### ISSUE THREAD

**Issue by MichaCo** [xunit/xunit#2564]
Hi,

I'm getting the following error in existing tests after upgrading to Xunit 2.4.2:

```
System.ArgumentException : Object of type 'System.Int32' cannot be converted to type 'System.Nullable`1[System.Double]'.
  Stack Trace: 
RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
MethodBase.CheckArguments(StackAllocedArguments& stackArgs, ReadOnlySpan`1 parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location ---
```

I can reproduce it in isolation with the following example:

```csharp
        [Theory]
        [InlineData("501", 234)]
        [InlineData("506", null)]
        public void TestStuff(string code, double? someNumber)
        {
            Assert.NotNull(code);
        }
```

This is working fine with version 2.4.1.

Tested in latest version of VS 2022 targeting NET6

**Comment by pvlst** [comment]
I'm experiencing the same problem, only related to `long`.

It can be avoided by adding literal suffix to the number, e.g. `1000` -> `1000L` for `long`. I guess you can change the number from `234` to `234.0` and it'll work too. But it's not very comfortable.

**Comment by MichaCo** [comment]
yep, changing the type to double via `234d` or whatever the method expects, works. 
Its not a biggy. 

Still wanted to report it as an issue ;)

**Comment by austindrenski** [comment]
My org is also seeing this after bumping to `2.4.2` this morning. Can confirm the previously reported workarounds work for us too, but as this bug breaks hundreds of tests across our org, updating each individual test, while viable, is not particularly practical.

**Comment by danports** [comment]
I'm going to guess that #2429 introduced this bug. Notably, the test suite that PR modified does not appear to cover the case of nullable numeric parameters with conversions.

**Comment by ericstj** [comment]
Looks like aspnetcore is hitting this as well.  Here's a repro of how they hit it:
```
    [Theory]
    [InlineData(0)]
    [InlineData(null)]
    public void Test1(long? aNumber)
    {
    }
```

**Comment by bradwilson** [comment]
There are currently no plans to release any more 2.x releases.

That said, this was an unintentional feature. I'm not convinced that this is something I'd want to become fixed again. .NET itself does not support this conversion; the fact that we did previously was unintentional (there were never any tests that ensured that it worked, which is how it was "broken"), so I'm not convinced at this point that I am interested in fixing this.

The "workaround" is to use the appropriate type in your inline data.

**Comment by bradwilson** [comment]
I'll leave this open for a bit for commentary, but will likely close this issue.

**Comment by MichaCo** [comment]
Hi @bradwilson 
If you decide to not fix this, that's fine. 

I was just already looking into that a bit and thought I post my findings anyways.

Regarding, ".NET itself does not support this conversion". That's not really true I think, Nullable has an implicit operator to its wrapped type, and then e.g. Int64 converts to Int32 via IConvertible, too.

This for example works and is kinda the same I guess?

```csharp
...
    SomeMethod(33);
...

    public static void SomeMethod(long? value)
    {
        if (value is null) return;

        Console.WriteLine(value);
    }

```

The "problem" in `PerformDefinedConversions` is the parameter type check which was added to find the correct implicit operator in `decimal`.

If I extend that `PerformDefinedConversions` method to 
* compare the operator method's parameter type to be the unwrapped type, it'll properly convert nullable value types (this works because the second conversation from long to int is then done by the Framework). This is a bit fishy, but I'd say better than before.
* If I also add the unwrapped type to the loop, it'll also find the correct implicit operator for `Nullable<decimal>` for example. (that didn't work even with the latest changes) 

Here is just the code. 
If you change your mind, feel free to adopt it, or let me know if you want me to send a PR for v3, if not, just /ignore ;)
(The same change works in V2, too btw)

```csharp
	static object? PerformDefinedConversions(
		object argumentValue,
		Type parameterType)
	{
		// argumentValue is known to not be null when we're called from TryConvertObject
		var argumentValueType = argumentValue.GetType();
		var unwrappedParameterType = parameterType.UnwrapNullable();
		var methodArguments = new object[] { argumentValue };

		bool isMatchingOperator(
			MethodInfo m,
			string name) =>
				m.Name.Equals(name) &&
				m.IsSpecialName &&  // Filter out non-operator methods that might bear this reserved name
				m.IsStatic &&
				!IsByRefLikeType(m.ReturnType) &&
				m.GetParameters().Length == 1 &&
				checkParamType(m.GetParameters()[0].ParameterType) &&
				parameterType.IsAssignableFrom(m.ReturnType);

		bool checkParamType(Type paramType)
		{
			return paramType == argumentValueType || paramType == unwrappedParameterType;
		}

		// Implicit & explicit conversions to/from a type can be declared on either side of the relationship.
		// We need to check both possibilities.
		foreach (var conversionDeclaringType in new[] { unwrappedParameterType, parameterType, argumentValueType })
		{
			var runtimeMethods = conversionDeclaringType.GetRuntimeMethods();

			var implicitMethod = runtimeMethods.FirstOrDefault(m => isMatchingOperator(m, "op_Implicit"));
			if (implicitMethod != null)
				return implicitMethod.Invoke(null, methodArguments);

			var explicitMethod = runtimeMethods.FirstOrDefault(m => isMatchingOperator(m, "op_Explicit"));
			if (explicitMethod != null)
				return explicitMethod.Invoke(null, methodArguments);
		}

		return null;
	}
```

and 2 new tests

```csharp
[Fact]
public async ValueTask NullableValueType()
{
	var results = await RunForResultsAsync(typeof(ClassWithNullableValueType));

	var passing = Assert.Single(results.OfType<TestPassedWithDisplayName>());
	Assert.Equal("Xunit3TheoryAcceptanceTests+TheoryTests+ClassWithNullableValueType.TestMethod(value: 5)", passing.TestDisplayName);
	var failed = Assert.Single(results.OfType<TestFailedWithDisplayName>());
	Assert.Equal("Xunit3TheoryAcceptanceTests+TheoryTests+ClassWithNullableValueType.TestMethod(value: null)", failed.TestDisplayName);
	Assert.Empty(results.OfType<TestSkippedWithDisplayName>());
}

private class ClassWithNullableValueType
{
	[Theory]
	[InlineData(5)]
	[InlineData(null!)]
	public void TestMethod(long? value)
	{
		Assert.NotNull(value);
	}
}

[Fact]
public async ValueTask NullableDecimal()
{
	var results = await RunForResultsAsync(typeof(ClassWithNullableDecimal));

	var passing = Assert.Single(results.OfType<TestPassedWithDisplayName>());
	Assert.Equal("Xunit3TheoryAcceptanceTests+TheoryTests+ClassWithNullableDecimal.TestMethod(value: 5)", passing.TestDisplayName);
	var failed = Assert.Single(results.OfType<TestFailedWithDisplayName>());
	Assert.Equal("Xunit3TheoryAcceptanceTests+TheoryTests+ClassWithNullableDecimal.TestMethod(value: null)", failed.TestDisplayName);
	Assert.Empty(results.OfType<TestSkippedWithDisplayName>());
}

private class ClassWithNullableDecimal
{
	[Theory]
	[InlineData(5)]
	[InlineData(null!)]
	public void TestMethod(decimal? value)
	{
		Assert.NotNull(value);
	}
}
```

**Comment by bradwilson** [comment]
@MichaCo I had no doubt that it could be fixed.

My point about ".NET does not support this" is via reflection. It will up-convert (for example, `Int32` to `Int64`) and it will convert to the nullable (for example, `Int32` to `Nullable<Int32>`), but it will not do both at the same time (`Int32` to `Nullable<Int64>`). So in this sense, xUnit.net now simulates the same behavior that .NET itself does.

**Comment by MichaCo** [comment]
@bradwilson yeah ok, for reflection, that's true; makes sense now. Thanks
