### ISSUE TITLE
Opting out of AsyncTestSyncContext

### ISSUE THREAD

**Issue by gdoron** [xunit/xunit#2573]
Hi All,

Everyone today's under the impression we are done with deadlocks because of SynchronizationContexts since they were removed in ASP.NET Core.
Problem is, the same code that works perfectly in development, staging and production is causing very weird problems and even deadlocks when run inside xunit tests.
This is because xunit added 2 SynchronizationContexts:

- MaxConcurrencySyncContext for limiting the number of threads
- AsyncTestSyncContext to keep track of `async void` tests

While the former can easily be opted-out, with `MaxParallelThreads=-1`, with `AsyncTestSyncContext` since it's being used very deep inside the framework in https://github.com/xunit/xunit/blob/v2/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs#L238 it seems like you simply cannot opt-out unless you override a half of the framework.

I noticed this is fixed with v3, where we only get AsyncTestSyncContext if the test method is in fact `async void`: https://github.com/xunit/xunit/blob/main/src/xunit.v3.core/Sdk/v3/Runners/TestInvoker.cs#L143

Personally, I would throw an exception for async void, aligning xunit with .NET's other test frameworks that do not support `async void` (I honestly see no advantage of having `async void`, probably a typo and can be fixed in a second or with a linter but many many disadvantages).

Can we please add a reasonable way of opting-out of `AsyncTestSyncContext` in the production V2 branch?
If investing a lot of time in it is not desirable since it's already fixed in V3, we can very easily just look at an environment variable in `TestInvoker`.

Bear in mind:
- Finding the root cause of these deadlocks is very difficult and time consuming
- ASP.NET Core integration tests framework shockingly is using sync over async in its code base, that making deadlocks super likely in big projects. See this thread: https://github.com/microsoft/vstest/issues/2080#issuecomment-1216336468
- Code under test should run and behave as much as possible as code outside the test, putting code inside a SynchronizationContext for tests, is a huge and impactful change.

Best,
Doron Grinzaig

**Comment by gdoron** [comment]
@bradwilson sorry for the rude ping.
But any chance you can review the issue?

Thanks in advance!

**Comment by bradwilson** [comment]
> and even deadlocks

You can deadlock the max concurrency context, which you already have a way to opt out of.

Looking at the code, I cannot see how you could deadlock the async void context itself, though it does delegate to the context that is wraps (so if you're using a context which could be deadlocked, like one of the STA/UI thread extensions, that's what you're deadlocking, and it has nothing to do with the async void context). If you can reliably deadlock the async void context by itself (meaning, no other contexts, including the max concurrency context), please provide a repro project.

The v3 bypass of the async void context has everything to do with performance and nothing to do with potential deadlocks.

> Personally, I would throw an exception for async void

This is not going to happen. Supporting `async void` is a pit of success feature that's been in the product for many many years. I'm not arbitrarily removing it.

> Can we please add a reasonable way of opting-out of AsyncTestSyncContext in the production V2 branch?

You can send a PR if you wish, but I have not promised there will be any more v2 releases, so you may be stuck using a MyGet-based package to get this feature for an indefinite period of time.

**Comment by bradwilson** [comment]
This will not be fixed for v2.

For v3, we only use the `AsyncTestSyncContext` when your test method is `async void`; as such, the opt-out mechanism in v3 is "don't write `async void` tests".

https://github.com/xunit/xunit/blob/e138f20c0b44909faf269af5646c5448bd4c0030/src/xunit.v3.core/Sdk/v3/Runners/TestInvoker.cs#L143-L148

As such, I consider this issue resolved.

**Comment by neuecc** [comment]
With the release of TimeProvider in .NET 8, asynchronous operations involving time can now be processed synchronously. However, the insertion of this SynchronizationContext inadvertently leads to the use of ThreadPool, making it difficult to monitor the processes. I am working on a custom implementation of Reactive Extensions, and this behavior is very inconvenient when writing tests for complex async/await code.

It's uncertain when version 3 will be released and become widespread, so I would like it to be introduced in version 2 before moving to version 3.

**Comment by bradwilson** [comment]
Available for v2 in `2.6.7-pre.11` https://xunit.net/docs/using-ci-builds

**Comment by bradwilson** [comment]
> If I got the commit right, it's not opt-out, it's opt-in, meaning you'll get the sync context if you choose to use async void.

It's really a matter of perspective, and whether you're accustomed to using `async void` with xUnit.net. Most people don't use it elsewhere except where they have to.

**Comment by mconnew** [comment]
FYI, this was a breaking change for CoreWCF as we have tests which depended on a non-null sync context to be set (we're validating whether we propagate it through to service call dispatch based on a behavior setting). Using the class name `SynchronizationContext` in the release notes item for this change would have made this easier to find when doing a contextual search to try work out what changed.

**Comment by bradwilson** [comment]
@mconnew It's unfortunate that we caused this bug, but depending on our (internal implementation detail) sync context instead of providing your own isn't really out fault.

> Using the class name SynchronizationContext in the release notes item for this change would have made this easier to find

Our release notes are pretty shallow, and we did call out the exact class in question (this is the third item in the release notes for 2.7.0):

![image](https://github.com/xunit/xunit/assets/16944/7d91f317-651d-40a1-8c22-db147fbdd2e0)

It's unfortunately impossible for me to have both anticipated that you were taking this dependency, and then how you would search to find the problem. I believe I provided as much information as most people would reasonably expect. 🤷🏼

**Comment by bradwilson** [comment]
Note that based on feedback from several users across several issues, this feature is being rolled back in 2.8.0, alongside the release of a new parallelism algorithm.

At the same time, we have removed support for `async void` tests in v3, so the sync context will be removed entirely. New analyzers in 1.13.0 will flag `async void` tests with a warning in v2 projects, and an error in v3 projects (and any attempt to run them in v3 will cause fast failures for the tests in question).

**Comment by tomaskarban** [comment]
I see the presence of `AsyncTestSyncContext` in plain synchronous tests (testing with net8.0 and xunit 2.8.0). It isn't causing me trouble, but I did not expect that.

```
[Fact]
public void Test1()
{
    Assert.NotNull(SynchronizationContext.Current);
}
```

**Comment by bradwilson** [comment]
@tomaskarban That is correct. This was the behavior prior to the attempt to only use it conditionally in 2.7.0, which was rolled back in 2.8.0 (because its absence broke tests unintentionally based on secondary behavior that the sync context did).

It's been removed entirely from v3, as `async void` is being removed from v3. Those tests which are broken by this in v3 will have to adapt. The hope is that the new conservative parallelism algorithm will allow those tests which failed in v2 2.7.x to now succeed in v3, since the Task scheduler should be much less busy.
