### ISSUE TITLE
Xamarin Studio Integration

### ISSUE THREAD

**Issue by kentcb** [xunit/xunit#258]
Sorry if this has been asked already - I couldn't find a reference.

Are there plans for "official" Xamarin Studio Integration with XUnit 2 support? I'm aware of an XUnit add-in for XS, but it does not see my tests, presumably because I'm using XUnit 2.

I am also aware of xamarin.xunit, but that needs to run on the simulator or a device. What I'm after is the ability to run my tests that are housed in a PCL in simulator/device (can do) or in XS directly (can't do). Obviously running directly in XS will save a lot of time with a TDD cycle.

**Comment by bradwilson** [comment]
We currently don't have any plans, though if some third party wanted to pick it up we could lead them in the right direction and answer any questions they might have. We'd also be happy to add the project to the family under https://github.com/xunit which includes not only first party projects, but also third party (the Xamarin runner & the Resharper runner are both owned by "not us" :grinning:).

**Comment by x2bool** [comment]
Hello, I am the author of the Xamarin Studio integration. My question is: can we host the project under http://github.com/xunit?

The thing is that after few months of trying to push my changes to the official MonoDevelop repository, I had to give up on this. I don't know why the maintainers didn't want to merge my pull request (They are either too busy or not interested anymore). I had some people emailing me about bugs, improvement requests, etc. And I couldn't do anything about bugs until the PR is merged, so I decided to close it.

I thought that this place might be the right place for the project. It would have a little more attention, and it is possible that other people will help us to improve it.

About v2 support: probably the only thing that is stopping the addin from running v2 tests is #158 . Anyway it shouldn't be too hard to make it work with v2 tests.

**Comment by bradwilson** [comment]
I'll talk to Jim about this.

Where does the project exist today?

On Wed, Feb 4, 2015 at 1:54 AM, Sergey Khabibullin <notifications@github.com

**Comment by x2bool** [comment]
https://bitbucket.org/x2bool/monodevelop-xunit

**Comment by bradwilson** [comment]
Here you go, you're all set up. https://github.com/xunit/xamarinstudio.xunit
