### ISSUE TITLE
Assert.Equal overload for DateTimeOffset that takes precision

### ISSUE THREAD

**Issue by toseni** [xunit/xunit#2588]
It was unexpected that `Assert.Equal` for `DateTime` has overload which allows to specify equality precision, but  `Assert.Equal` for `DateTimeOffset` does not. 
Since `DateTime` and `DateTimeOffset` are very similar types, they should also have same `Assert.Equal` overloads.

**Comment by 1337ninja** [comment]
Hi @bradwilson , I would like to take a stab at this

**Comment by bradwilson** [comment]
@1337ninja Go ahead! Open a PR when you're ready. You'll likely need two separate PRs: one for the code (which lives in [assert.xunit](https://github.com/xunit/assert.xunit/)) and one for the tests (which live in this project).

**Comment by 1337ninja** [comment]
Hi @bradwilson, just noticed an open PR for this https://github.com/xunit/assert.xunit/pull/52/files
Is this issue still up for grabs?  Is the PR open because it has missing tests?

**Comment by bradwilson** [comment]
@1337ninja No, the PR was still open because this is a part time project for me, so things don't necessarily get immediately merged. That said, I'm going to add the tests myself and merge the existing PR, so no need to re-implement it. :)

Thanks @toseni and @1337ninja!

**Comment by bradwilson** [comment]
Unit tests for this (+ missing tests for DateTime, + new overloads I added in https://github.com/xunit/assert.xunit/commit/acc300b953869d1e0d96e426e3a372d694065d0c) are here: https://github.com/xunit/xunit/commit/44ce9899f2b921044aca9bb0b6efd7e1c3c0d803
