### ISSUE TITLE
Folder path seems to be hard-coded

### ISSUE THREAD

**Issue by isaacabraham** [xunit/xunit#259]
I've been trying to deploy the new XUnit Nuget runner for VS, using slightly different paths than the standard OOB experience with Nuget (I use Paket).

* The ``xunit.runner.visualstudio`` package is downloaded into ``packages/xunit.runner.visualstudio`` (rather than ``xunit.runner.visualstudio.0.99.9-build1021``).
* I manually amend the .fsproj file to contain the following: -

```xml
     <Import Project="..\packages\xunit.runner.visualstudio\build\net20\xunit.runner.visualstudio.props"/>
```
* This seems to work, because the ``.testadapter.dll`` and the rest all get copied to the bin/debug folder.
* Nothing happens in the test runner - no unit tests are identified.
* HOWEVER, if I then rename the package folder to ``xunit.runner.visualstudio.0.99.9-build1021`` and restart VS, the test runner magically starts working.

**Comment by isaacabraham** [comment]
Has anyone managed to repro this - or is there anything I can do that would help in diagnosing it?

**Comment by bradwilson** [comment]
I'm having a hard time understanding how the path can be hard-coded, as it changes for every CI build we do. Also, I've found a lot of weirdness with the Visual Studio test runner that will often require you to kill all VS instances and then delete its temporary cache of test runner extensions in the `VisualStudioTestExplorerExtensions` in your `Temp` folder.

From PowerShell, type:

```
$ cd $env:temp
$ del -r -fo VisualStudioTestExplorerExtensions
```

**Comment by isaacabraham** [comment]
Re: hard-coding - I was thinking embedded within code based on version or something like that. I'll give that a go regarding the extensions and see if I can come back with something. What does XUnit do if you install one version of the top of another - does it clear the ``Temp`` folder automatically?

**Comment by bradwilson** [comment]
We don't control that temp folder (Visual Studio does), so I honestly have no idea what it's clearing algorithm is supposed to be.

**Comment by bradwilson** [comment]
Closing as apparent external problem (Visual Studio).

**Comment by isaacabraham** [comment]
Yeah - I tried again recently and couldn't repro. Sorry didn't update earlier.
