### ISSUE TITLE
Can't install xunit-2-rc1

### ISSUE THREAD

**Issue by Hinidu** [xunit/xunit#260]
NuGet provides this output:
Attempting to resolve dependency 'xunit.core (= 2.0.0-rc1-build2826)'.
'xunit.core' already has a dependency defined for 'xunit.extensibility.core'.
I'm getting the same error for updating the package in existing project and installing it in the new one.
Thanks.

**Comment by bradwilson** [comment]
Update NuGet to the latest build.

**Comment by Hinidu** [comment]
Thank you, that helped.
