### ISSUE TITLE
Suggestion: Assert Type and cast result in `out` parameter

### ISSUE THREAD

**Issue by alexandrehtrb** [xunit/xunit#2603]
Hello,

I have a suggestion of assertion method, for checking an object's type and then casting into that type.
Something like this:

```cs
public static void IsType<T>(object @object, out T castedObject)
{
    Assert.IsType<T>(@object);
    castedObject = (T) @object;
}
```

The reason is to save a line of code, of casting an object after checking its type.

**Comment by bartelink** [comment]
`Assert.IsType<T>` already returns the casted value, so you can write `var castedObject = Assert.IsType<T>(x)`

**Comment by alexandrehtrb** [comment]
Thanks!
