### ISSUE TITLE
Set NO_COLOR environment variable when user adds -nocolor command line switch

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#2605]
We already support [no-color.org](https://no-color.org/)'s recommendation for [disabling color if the user has set the `NO_COLOR` environment variable](https://github.com/xunit/xunit/blob/653218c4f84714e7031c8118d9d0bb1f5529958a/src/xunit.v3.runner.common/Frameworks/TestProjectConfiguration.cs#L75), but a comment in a [related issue](https://github.com/xunit/xunit/issues/2535#issuecomment-1287912077) suggests that we should also set the `NO_COLOR` environment variable in response to the user passing `-nocolor` to the console runner.

**Comment by eli-entelis** [comment]
is this still up for grabs? would like to try

**Comment by bradwilson** [comment]
@eli-entelis Sure, I'll assign it to you!
