### ISSUE TITLE
How to intentionally fail?

### ISSUE THREAD

**Issue by codelovercc** [xunit/xunit#2609]
> I am currently dealing with a situation in which some of our test code runs within a wrapper of a framework we are using. This framework is very nice and catches all exceptions for us, that means that my test can never fail. Since we also use a custom test wrapper between the framework and the actual application code I was hoping to bypass the nice framework with some sort of hard exception using an xUnit call.
> 
> Currently my only workaround is to call `Environment.Exit` , but that only shows the test as incomplete and won't show the developers the stack trace, which is obviously far from ideal.
> 
> So my 2 cents on this discussion would be that Assert.Fail could perhaps facilitate this special purpose.

I'd like to know how do you solve this situation? @HugoPeters1024 
Cause I am dealing with this now....

_Originally posted by @codelovercc in https://github.com/xunit/xunit/issues/2027#issuecomment-1294363305_

```C#
var subscriber = Wrapper.GetSubscriber();
var chanel = subscriber.GetChannel<TestMessage>();
var queue = subscriber.Subscribe(chanel);
queue.OnMessage(async redisMsg =>
{
    try
    {
        await Task.Run(() =>
        {
            var v = subscriber.DeserializerMessage<TestMessage>(redisMsg.Message);
            Assert.NotNull(v);
            _actualCount++;
            _testOutputHelper.WriteLine(JsonSerializer.Serialize(v));
            Assert.Contains(v!.Id, ConnectionMultiplexerWrapperTester.Messages);
            Assert.Equal(ConnectionMultiplexerWrapperTester.Messages[v.Id].Message, v.Message);
        });
    }
    catch (Exception e)
    {
        //todo make this test to fail
    }
});
```
In this code, queue.OnMessage has an Action param, any of exception throw in the Action will be discarded by the caller.that means that my test can never fail.

**Comment by trivalik** [comment]
Basically I would do it like:
```cs
var subscriber = Wrapper.GetSubscriber();
var chanel = subscriber.GetChannel<TestMessage>();
var queue = subscriber.Subscribe(chanel);

bool fail = false;
queue.OnMessage(async redisMsg =>
{
    try
    {
        await Task.Run(() =>
        {
            var v = subscriber.DeserializerMessage<TestMessage>(redisMsg.Message);
            Assert.NotNull(v);
            _actualCount++;
            _testOutputHelper.WriteLine(JsonSerializer.Serialize(v));
            Assert.Contains(v!.Id, ConnectionMultiplexerWrapperTester.Messages);
            Assert.Equal(ConnectionMultiplexerWrapperTester.Messages[v.Id].Message, v.Message);
        });
    }
    catch (Exception e)
    {
        fail = true;
    }
});
//here  some wait logic to finish the async call
Assert.False(fail);
```

If required you can also move out the Exception object.

**Comment by codelovercc** [comment]
> Basically I would do it like:
> 
> ```cs
> var subscriber = Wrapper.GetSubscriber();
> var chanel = subscriber.GetChannel<TestMessage>();
> var queue = subscriber.Subscribe(chanel);
> 
> bool fail = false;
> queue.OnMessage(async redisMsg =>
> {
>     try
>     {
>         await Task.Run(() =>
>         {
>             var v = subscriber.DeserializerMessage<TestMessage>(redisMsg.Message);
>             Assert.NotNull(v);
>             _actualCount++;
>             _testOutputHelper.WriteLine(JsonSerializer.Serialize(v));
>             Assert.Contains(v!.Id, ConnectionMultiplexerWrapperTester.Messages);
>             Assert.Equal(ConnectionMultiplexerWrapperTester.Messages[v.Id].Message, v.Message);
>         });
>     }
>     catch (Exception e)
>     {
>         fail = true;
>     }
> });
> //here  some wait logic to finish the async call
> Assert.False(fail);
> ```
> 
> If required you can also move out the Exception object.


Thank you for reply this.
This code is a test for RabbitMQ using with [https://github.com/EasyNetQ/EasyNetQ](https://github.com/EasyNetQ/EasyNetQ). The async Action will run multi times when there is more than one messages received from the RabbitMQ, that means we can't wait all of these async action, cause we don't know how many messages that we will receive.

**Comment by trivalik** [comment]
You have to define a end, else a test cannot be written. Does the messages which are received not declare when it is the end? If so a flag can be set which mark that the wait is over and will lead to the final assert.

**Comment by bradwilson** [comment]
`Assert.Fail()` is available in 2.4.2. https://github.com/xunit/assert.xunit/blob/d4e3195b3e7be0ead099819413e003c62c56eb64/FailAsserts.cs#L27-L32

**Comment by codelovercc** [comment]
@bradwilson 

```cshap
var subscriber = Wrapper.GetSubscriber();
var chanel = subscriber.GetChannel<TestMessage>();
var queue = subscriber.Subscribe(chanel);
queue.OnMessage(async redisMsg =>
{
    try
    {
        await Task.Run(() =>
        {
            var v = subscriber.DeserializerMessage<TestMessage>(redisMsg.Message);
            Assert.NotNull(v);
            _actualCount++;
            _testOutputHelper.WriteLine(JsonSerializer.Serialize(v));
            Assert.Contains(v!.Id, ConnectionMultiplexerWrapperTester.Messages);
            Assert.Equal(ConnectionMultiplexerWrapperTester.Messages[v.Id].Message, v.Message);
        });
    }
    catch (Exception e)
    {
        //make this test to fail
        Assert.Fail();
    }
});
```
`queue.OnMessage` has an Action param, any of exception throw in the Action will be discarded by the caller. Are you sure `Assert.Fail()` can work with it? `Assert.Fail()` raised another exception that will be discarded by the `queue.OnMessage`.

**Comment by bradwilson** [comment]
@codelovercc There are no assertions which accept exceptions. Any exception thrown by a test will cause it to fail, so just don't use try/catch at all and let the original exception propagate.

With this test:

```csharp
using System;
using System.Threading.Tasks;
using Xunit;

public class UnitTest
{
    [Fact]
    public async void Example()
    {
        await Task.Run(() =>
        {
            throw new DivideByZeroException();
        });
    }
}
```

Running it will fail the test:

```
UnitTest.Example [FAIL]
  System.DivideByZeroException : Attempted to divide by zero.
  Stack Trace:
    UnitTest.cs(12,0): at UnitTest.<>c.<Example>b__0_0()
       at System.Threading.Tasks.Task`1.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
    UnitTest.cs(10,0): at UnitTest.<Example>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by bradwilson** [comment]
Assertions should fail as you'd expect as well:

```csharp
using System;
using System.Threading.Tasks;
using Xunit;

public class UnitTest
{
    [Fact]
    public async void Example()
    {
        await Task.Run(() =>
        {
            Assert.True(false);
        });
    }
}
```

Results in:

```
UnitTest.Example [FAIL]
  Assert.True() Failure
  Expected: True
  Actual:   False
  Stack Trace:
    UnitTest.cs(12,0): at UnitTest.<>c.<Example>b__0_0()
       at System.Threading.Tasks.Task.Execute()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
    UnitTest.cs(10,0): at UnitTest.<Example>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by bradwilson** [comment]
> any of exception throw in the Action will be discarded by the caller

I'm not sure what this means, but if it means that it will eat any exception that you throw in the action--and there's no way to retrieve that exception somehow--then there's really nothing anybody can do about it.

If you can get access to the `Exception` object that was thrown and caught, and you'd just like to re-throw it, then you can use `ExceptionDispatchInfo` to re-throw the exception. Here's an example showing that:

```csharp
using System;
using System.Runtime.ExceptionServices;
using System.Threading.Tasks;
using Xunit;

public class UnitTest
{
    // Simulate the "run my code and return the exception"
    private async Task<Exception?> RunMyCode(Action action)
    {
        try
        {
            await Task.Run(action);
            return null;
        }
        catch (Exception ex)
        {
            return ex;
        }
    }

    [Fact]
    public async void Example()
    {
        var ex = await RunMyCode(() =>
        {
            Assert.True(false);
        });

        if (ex != null)
            ExceptionDispatchInfo.Capture(ex).Throw();
    }
}
```

And the result of running this:

```
UnitTest.Example [FAIL]
  Assert.True() Failure
  Expected: True
  Actual:   False
  Stack Trace:
    UnitTest.cs(27,0): at UnitTest.<>c.<Example>b__1_0()
       at System.Threading.Tasks.Task.Execute()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
    UnitTest.cs(13,0): at UnitTest.<RunMyCode>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    UnitTest.cs(31,0): at UnitTest.<Example>d__1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by codelovercc** [comment]
> I'm not sure what this means, but if it means that it will eat any exception that you throw in the action--and there's no way to retrieve that exception somehow

You are understand correctly.

StackExchange.Redis package.
Method:
public void OnMessage(Func<ChannelMessage,Task> handler) in class ChannelMessageQueue
Desc:
Create a message loop that processes messages sequentially. This method will eat any exception that throw in the action.
Params:
handler – The handler to execute when receiving a message.

```csharp
ChannelMessageQueue queue = subscriber.Subscribe(chanel);
queue.OnMessage(async redisMsg =>
{
    try
    {
        await Task.Run(() =>
        {
            var v = subscriber.DeserializerMessage<TestMessage>(redisMsg.Message);
            Assert.NotNull(v);
            _actualCount++;
            _testOutputHelper.WriteLine(JsonSerializer.Serialize(v));
            Assert.Contains(v!.Id, ConnectionMultiplexerWrapperTester.Messages);
            Assert.Equal(ConnectionMultiplexerWrapperTester.Messages[v.Id].Message, v.Message);
        });
    }
    catch (Exception e)
    {
        //todo make this test to fail
    }
});
```

**Comment by bradwilson** [comment]
I believe I've already answered your question. At the point you've written `//todo make this test fail`, you can throw an exception or use an assertion like `Assert.Fail`.

**Comment by trivalik** [comment]
Try this:
```
         switch (value)
         {
             case "valid":
                 break;
             default:
                 Assert.Fail($"Invalid value {value}");
                 break;
         }
```

because the compiler does a static check to know when a `break` is necessary, and does not know that `Assert.Fail` does a throw. Similar code you code also find in Microsoft repositiories.

**Comment by bradwilson** [comment]
@malaterre [`Assert.Fail` has `[DoesNotReturn]` decorated onto it](https://github.com/xunit/assert.xunit/blob/96236a4ce07679c30587c5013ef8bff2df9d63ab/FailAsserts.cs#L28), which means that the compiler should know it always throws. This feels like a potential bug/feature request in Roslyn to me.

**Comment by bradwilson** [comment]
Roslyn is at least consistent, I guess: it doesn't properly detect unreachable code with `[DoesNotReturn]`, either.

Assert version:

![image](https://github.com/xunit/xunit/assets/16944/9933755e-0b11-43a0-8669-8546c52d75ec)

Throw version:

![image](https://github.com/xunit/xunit/assets/16944/6069439d-4fc5-4705-91dd-c88c020438ae)
