### ISSUE TITLE
'xunit.core' already has a dependency defined for 'xunit.extensibility.core'.

### ISSUE THREAD

**Issue by mdsharpe** [xunit/xunit#261]
Unable to use the latest xunit v2 packages with Microsoft TFS Build 2013 Update 4, seemingly due to incompatibility with the version of nuget.exe that is bundled with Build (2.8.50126.400).

The error message is as follows:

'xunit.core' already has a dependency defined for 'xunit.extensibility.core'.

Error does not occur when restoring packages within Visual Studio.

**Comment by bradwilson** [comment]
I don't know how to update the version of NuGet that comes with TFS Build, but that's what needs to be done.

**Comment by mdsharpe** [comment]
That would solve the problem, however it is not particularly feasible for an organization running many build agents.
I was hoping it might be possible to tweak the package dependencies to avoid this problem? It is the first time I have encountered the problem, despite having installed many other packages with dependency trees.

**Comment by bradwilson** [comment]
I don't have a TFS Build server. If you can figure out what the appropriate tweaks are, we can put them into the next release. Thanks!

**Comment by giggio** [comment]
I can confirm the problem with the first RC release of xunit and TFS 2013 Update 4.

**Comment by giggio** [comment]
BTW, you can update nuget on the server by running:

````bash
"C:\Program Files\Microsoft Team Foundation Server 12.0\Tools\nuget.exe" update -self
````

**Comment by Alxandr** [comment]
@mdsharpe The problem is due to the fact that the package supports frameworks that your version of NuGet doesn't know about. It has nothing to do with deep dependency trees.

**Comment by michaelsync** [comment]
I got the same error with xunit 2.1 and TeamCity as well. NuGet.exe in TeamCity Build Agent is 2.8.50926.602. It used to work with xunit 2.0 release.

**Comment by bradwilson** [comment]
This is an external problem with NuGet. We have no control over it. My best recommendation is to use the latest build of NuGet (3.2.1).

**Comment by am11** [comment]
I was having the same issue with nuget v2.8.50926.602. This issue is fixed upstream in nuget 2.8.60717.93. To quickly obtain the fix: `path/to/my/nuget-2x/nuget.exe update -self` (thanks to @giggio for self-update tip above).

**Comment by michaelsync** [comment]
@am11 TeamCity has the build-in NuGet.exe. I don't have the permission on updating it and there are other projects running on build server and I don't want to disturb them as well. So, the workaround that I used was to enable the nuget-restore in VS (I know nuget-restore on VS is not recommended anymore ) and upload the latest version of nuget.exe to the repostiory. then I use that nuget.exe to run the "nuget install" runner .

**Comment by Alxandr** [comment]
As a general rule of thumb, always check nuget.exe into the repo **or** (as I tend to do) have a script that downloads the latest nuget.exe, instead of relying on machine-global installations. Which you choose tends to depend on whether or not you need build to work without internet or when nuget goes down etc.

**Comment by onovotny** [comment]
Basically, your build script should have something along the lines of 
https://github.com/xunit/xunit/blob/master/xunit.msbuild#L160-L194

In the URL, you can use https://dist.nuget.org/win-x86-commandline/latest/nuget.exe to always get the latest stable release.

Download NuGet from your script and use that one; it's the only way to be sure you're using a current version.

**Comment by GaTechThomas** [comment]
I had the same issue on TeamCity using nuget version 2.8.60717.93. Nuget version 3.3 seems to have done the trick.
