### ISSUE TITLE
Using Config.json with XUnit

### ISSUE THREAD

**Issue by paranoid-android** [xunit/xunit#262]
Hello,

ASP.NET vNext supports `config.json` file. This uses the `IConfiguration` interface to load configuration settings. However, it is not clear how to use settings from `config.json` in XUnit tests. For instance, if I have a `config.json` file that looks like the following:

```
{
  "emailAddress":"someone@somewhere.com"
}
```
How can these settings be loaded into a XUnit suite of tests?

**Comment by bradwilson** [comment]
xUnit.net has nothing to do with your config.json file. Whatever mechanism you would normally use to load configuration in an ASP.NET app should just work.

**Comment by paranoid-android** [comment]
ASP.NET apps have a Startup class ([example](https://github.com/aspnet/MusicStore/blob/master/src/MusicStore/Startup.cs)). What is the equivalent of a Startup class in XUnit? Or, does each file need to load the Configuration everytime?

**Comment by bradwilson** [comment]
Unit tests are intended for use in class libraries, not applications. AFAIK, there is no equivalent in class libraries to the Startup class used in Applications.

This is probably a question better posed to the ASP.NET team.

**Comment by paranoid-android** [comment]
I agree with the argument that unit tests are intended to use with class libraries. However, it is common that class libraries will connect to a database or send an email. A lot of times, those settings are stored in a configuration file. For that reason, it seems like there should be some way to globally load configuration settings for use across unit tests.

This question is specific to XUnit's ability to load config.json content.

**Comment by bradwilson** [comment]
I disagree with this assertion: "This question is specific to XUnit's ability to load config.json content."

xUnit.net is not loading your configuration. Your code has to do that. The ASP.NET team is going to need to formulate some guidance here (not the least of which because we cannot assume that you're using `config.json`, since everything is configurable).

/cc @davidfowl @damianedwards

**Comment by davidfowl** [comment]
This seems app specific. There is nothing that xunit needs to go here imo.

**Comment by xperiandri** [comment]
@bradwilson, @davidfowl, I have similar question as @paranoid-android 
https://github.com/xunit/xunit/issues/1439
I have a connection string and want to substitute it on CI build when xUnit tests are running.
How can I do that?

**Comment by bradwilson** [comment]
Use an environment variable with a default value fallback. Set the environment variable for the CI build.

**Comment by xperiandri** [comment]
@bradwilson, I have no idea if it is possible to set environment variable in VSTS hosted agent.
I tried command line task with no luck.

**Comment by xperiandri** [comment]
Even [here](https://stackoverflow.com/questions/44690138/vso-ci-aspnetcore-environment-is-set-to-production-no-matter-what-i-do) MS says that this does not work!
Really it is strange to set environment variable on a shared build agent
