### ISSUE TITLE
`Assert.Equivalent` doesn't ignore non-public properties

### ISSUE THREAD

**Issue by ExterminatorX99** [xunit/xunit#2621]
`Assert.Equivalent` docs say it only checks public instance properties, but it actually checks public and non-public, instance and static properties.

Repro
```cs
using Xunit;

namespace Test;

public static class Program
{
    public static void Main()
    {
        var a = new A(123);
        var b = new B(123);

        Assert.Equivalent(a, b);
    }
}

public class A
{
    private static int _ignoreMeStatic { get; set; }

    internal int _ignoreMeInstance { get; set; }

    public int Number { get; set; }

    public A(int number)
    {
        Number = number;
    }
}

public class B
{
    public int Number { get; set; }

    public B(int number)
    {
        Number = number;
    }
}
```

**Comment by bradwilson** [comment]
You are correct. The filter for fields is right, but the filter for properties is not:

https://github.com/xunit/assert.xunit/blob/d4e3195b3e7be0ead099819413e003c62c56eb64/Sdk/AssertHelper.cs#L32-L58

**Comment by bradwilson** [comment]
Fixed in xunit/assert.xunit#58 and tested in https://github.com/xunit/xunit/commit/f1acdedcf4db6cdec53858d876e91ae4a7241ec2
