### ISSUE TITLE
Get theory data arguments outside of the test method body

### ISSUE THREAD

**Issue by h15ter** [xunit/xunit#2623]
Hi Guys,
I'm migrating from MSTest to XUnit. The project is large and using data-driven tests. 
With MSTest, each data record was accessible via test context, so I could handle it in a single place (test initialize method) per test class. 
With XUnit 2.x I can only get the data record as an argument of the test method, which means each test needs extra code to handle the data explicitly. I find it inconvenient, I would be happy to handle it in class constructor instead, but I'm out of good ideas on how to implement that. Could you suggest me the way?
Thanks!

**Comment by bradwilson** [comment]
In v2, there is no test context, and no plans to add one.

In v3, `TestContext` gives access to the test case:

https://github.com/xunit/xunit/blob/e138f20c0b44909faf269af5646c5448bd4c0030/src/xunit.v3.core/TestContext.cs#L76-L81

And the test case gives access to the method arguments:

https://github.com/xunit/xunit/blob/e138f20c0b44909faf269af5646c5448bd4c0030/src/xunit.v3.core/Sdk/v3/TestCases/_ITestCase.cs#L32-L35
