### ISSUE TITLE
Add "don't use ConfigureAwait(false)" analyzer

### ISSUE THREAD

**Issue by Arithmomaniac** [xunit/xunit#2628]
Someone pointed out to me recently that it seems that you explicitly should **not** use `ConfigureAwait(false)` in certain places when using XUnit:

> You will, however, probably break the "maximum number of tests in flight" feature since anything which resumed on a different sync context from our "max concurrency" sync context wouldn't, by definitely, be limited.
>
> https://github.com/xunit/xunit/issues/507#issuecomment-125388959

> You should not use ConfigureAwait(false) directly in the test method.
> It's fine to use it in methods elsewhere.
> 
> https://github.com/zkSNACKs/WalletWasabi/issues/4147#issuecomment-671798346

I believe this is a pretty obscure point and would be a great candidate for an analyzer to enforce (or at least suggest). There are so many "CAF missing" analyzer out there (e.g. CA2007) that copying-and-modifying one to invert the rule seems like it shouldn't be hard.

**Comment by JazzGlobal** [comment]
Can I get this assigned to me? Thanks! 😁

**Comment by bradwilson** [comment]
Shipped in `1.3.0-pre.9`

**Comment by hugoqribeiro** [comment]
Can I still comment on this?

I understand the motivation but... this creates a problem... CA2007 doesn't distinguish xUnit test methods. :(

So you get an error if you add ConfigureAwait() or an error if you don't.

Shouldn't the analyzer recommend using ConfigureAwait(true) instead?

**Comment by bradwilson** [comment]
I would recommend just using a `.editorconfig` file in your test project(s) to disable CS2007 entirely.
