### ISSUE TITLE
Compile failure assertion

### ISSUE THREAD

**Issue by naasking** [xunit/xunit#263]
It would be nice to have some means to express that a particular expression should not compile. For instance, you can utilize the type system to ensure some object states are unrepresentable [1]. This pattern is usually called "phantom types", but it's not merely relegated to this usage.

It shouldn't be too difficult to add either, as loading and compiling source files is fairly easy with the CodeDom API. Something as simple as:

    Assert.CompileFails(expectedLineFailure, "/path/to/source.cs");

It would be nice to just specify the expression itself, ie. Assert.CompileFails("[string expression]"), but that seems to raise more difficulties, as you'll have to specify the namespaces to import and so on.

[1] https://blogs.janestreet.com/howto-static-access-control-using-phantom-types/

**Comment by bradwilson** [comment]
Thank you for the suggestion, but this feature falls outside the scope of xUnit itself.

We would recommend adding this as an extension to the xUnit `Assert` class by bringing in the assertions library using the source-based NuGet package (`xunit.assert.source`) and then adding your own partial class to add new methods to `Assert`.
