### ISSUE TITLE
samples.xunit in visaul studio 2022 is not run

### ISSUE THREAD

**Issue by bicijinlian** [xunit/xunit#2634]
示例在Visual Studio 2022中，不执行任何测试；但是在 Visual Studio 2019中是正常的。
![Snipaste_2022-12-11_16-44-56](https://user-images.githubusercontent.com/10394955/206894457-07272f64-e076-4c89-b7fd-f52d462ad908.png)

**Comment by trivalik** [comment]
Maybe because of this https://github.com/xunit/visualstudio.xunit/issues/342?

**Comment by bradwilson** [comment]
Closing as duplicate of 342.
