### ISSUE TITLE
Support an ICollectionFixture without a CollectionDefinition

### ISSUE THREAD

**Issue by MatisseHack** [xunit/xunit#2638]
I'd like to be able to add `ICollectionFixture<>` to several test classes without requiring an extra dummy class with the `CollectionDefinition` attribute and `Collection` attributes on each test class. i.e. I wish this worked:

```csharp
public class Fixture
{
    public Fixture() => Console.WriteLine("Setting up...");
}

public class Class1 : ICollectionFixture<Fixture>
{
    [Fact]
    public void Fact1() => Console.WriteLine("Fact 1");
}

public class Class2 : ICollectionFixture<Fixture>
{
    [Fact]
    public void Fact2() => Console.WriteLine("Fact 2");
}
```

This code currently produces the following error:

> A test class may not be decorated with ICollectionFixture<> (decorate the test collection class instead).

Sharing test context between tests in the same class is easy with `IClassFixture`s and I wish `ICollectionFixture`s were just as easy to use without any extra boilerplate.

It would also be cool if this support could enable shared test context without affecting parallelism. e.g. maybe adding `ICollectionFixture<>` to test classes directly could allow each test class to run in parallel while using a `CollectionDefinition` (the current method) would still serialize all the tests. However, I understand why parallelism currently isn't on by default in tests that share context so maybe there should be a separate way to enable parallelism within collections. I know some related proposals have been discussed in #1986 and #2055 already.

**Comment by bradwilson** [comment]
I'm going to close this as a sub-part of #2007 since that's already slated as part of v3. Feel free to make any additional comments regarding ease of use with fixtures on that issue.

Thanks!
