### ISSUE TITLE
xUnit Support for Playwright

### ISSUE THREAD

**Issue by hishamco** [xunit/xunit#2639]
@bradwilson I opened [this issue](https://github.com/microsoft/playwright-dotnet/issues/2244) four months, due the limitation of xUnit there's no official support from Microsoft. Then I decided to create a fork and did a community project, after the sudden I decided to contact you if it's possible to create a repository under `xUnit` account then we can start an OSS to support `xUnit` for playwright.

Please let me heard your feedback

**Comment by bartelink** [comment]
Why dnot put it on your own github? In general, the xunit org only has first part stuff, not integrations with third party things that come and go, evolving independently over time (imagine the tens to hundreds of projects that would come and go - what would be the benefit of them being under one org?).

**Comment by hishamco** [comment]
As I mentioned I can created under my account, but while it's related to `xUnit` that's why I suggested to be hosted here. If the owner(s) disagree I will make it under my own

**Comment by hishamco** [comment]
As I mentioned I can created under my account, but while it's related to `xUnit` that's why I suggested to be hosted here. If the owner(s) disagree I will make it under my own

**Comment by bradwilson** [comment]
It is our stance that the `xunit.*` packages on NuGet are only from first party libraries. There are some third party libraries that used those names before NuGet supported name reservations, and we decided not to ask them to rename them (but we are not allowing any new ones).

**Comment by hishamco** [comment]
For that I asked if the project can be hosted in xunit organization

**Comment by bartelink** [comment]
@hishamco For me, Brad can't put it more clearly - the xunit org and packages have sufficient concerns as is, hence it's recommended to host it elsewhere. I'd suggest closing this issue given you have an answer to your query.
