### ISSUE TITLE
More know types for serialization

### ISSUE THREAD

**Issue by sungam3r** [xunit/xunit#2640]
I would like to add support for `TimeSpan`, `BigInteger`, `DateOnly` and `TimeOnly` for `XunitSerializationInfo.supportedSerializationTypes`.
The latter two require additional net6 TFM. Would you like to accept PR?

**Comment by sungam3r** [comment]
I did not. Of course it requires net6 tfm in csproj.

**Comment by bradwilson** [comment]
The core packages only target `netstandard2.0` and we will not add specific target frameworks because it creates bifurcations in the support from third party extensions which invariably result in conflicting dependencies.

**Comment by sungam3r** [comment]
Ok... support for `DateOnly` and `TimeOnly` **can** be added in other way - not via explicitly declared at compile time supportedSerializationTypes.

**Comment by sungam3r** [comment]
Core code can call `GetType()` and get type name and declaring assembly. For `DateOnly` it is `System.DateOnly` and `System.Private.CoreLib`.

**Comment by sungam3r** [comment]
`TimeSpan` and `BigInteger` can be added in usual way at compile time.

**Comment by bradwilson** [comment]
Feel free to send a PR.

**Comment by sungam3r** [comment]
What target branch should I use? `origin/v2` I think.

**Comment by bradwilson** [comment]
We are currently not planning any further releases for v2 (it would require a showstopping bug at this point), so `origin/main` for v3 is the correct branch.

**Comment by sungam3r** [comment]
Ok. I don't see any releases for v3 on Nuget, even previews. I would like to use this fix ASAP. How can I get it?

**Comment by bradwilson** [comment]
CI builds are available on MyGet: https://myget.org/gallery/xunit

For v3 packages, look for names that start with `xunit.v3`.
