### ISSUE TITLE
Problem with loading AppDomiain.CurrentDomain.GetAllAsseblies() in Xunit

### ISSUE THREAD

**Issue by mehdihadeli** [xunit/xunit#2642]
Hi,
I have a simple [Api project](https://github.com/mehdihadeli/Xunit.Sample/tree/main/Api) and a separate [xunit Tests project](https://github.com/mehdihadeli/Xunit.Sample/tree/main/Tests) that has reference to this Api project. I have a [simple function](https://github.com/mehdihadeli/Xunit.Sample/blob/main/Api/ReflectionHelper.cs#L7) in my Api project that returns all AppDomain assemblies. AppDomain assemblies are lazy, and I should get just assemblies that used in my code path (here I didn't use any specific assembly in my code path), not all referenced assemblies to Api project.

Api Project:
``` csharp
public class ReflectionHelper
{
    public static IReadOnlyList<Assembly> GetAllAssemblies()
    {
        var assemblies = AppDomain.CurrentDomain.GetAssemblies();
        return assemblies.ToList().AsReadOnly();
    }
}
```
And in my test I have a unit test for testing load assemblies in AppDomain (assemblies should load lazily, not all of referenced assemblies). I test it with `xunit` and `Rider` test runner and I get correct assemblies, just used assemblies in my code path not all referenced assemblies but when I run this xunit test with `dotnet test --filter DisplayName=Tests.ReflectionHelperXunitTests.Test1` xunit load all referenced assemblies (Assemblies are not lazy now!)

``` csharp
public class ReflectionHelperXunitTests
{
    [Fact]
    public void Test1()
    {
        var assemblies = ReflectionHelper.GetAllAssemblies();
        var existsMediatRAssembly = assemblies.Any(x => x.GetName().Name.Contains("MediatR"));
        existsMediatRAssembly.Should().BeFalse(); // in rider test runner is `false` but in dotnet cmd test runner it is `true`
    }
}
```

I do this equivalent test with `MsTest` and it loads just used assemblies (lazy load assemblies) in the code path for both `Rider` and `dotnet test --filter Name=Test1` correctly

``` csharp
[TestClass]
public class MicrosoftReflectionHelperTests
{
    [TestMethod]
    public void Test1()
    {
        var assemblies = ReflectionHelper.GetAllAssemblies();
        var existsMediatRAssembly = assemblies.Any(x => x.GetName().Name.Contains("MediatR"));
        existsMediatRAssembly.Should().BeFalse(); // in rider test runner and dotnet cmd test runner is `false`
    }
}
```
I think behavior Xunit in `dotnet test` for loading assemblies is not correct, and it loads all referenced assemblies instead of used assemblies in the AppDomain.

Example code is available here: [https://github.com/mehdihadeli/Xunit.Sample](https://github.com/mehdihadeli/Xunit.Sample)

**Comment by bradwilson** [comment]
What you're doing is not retrieving the references of an assembly, but rather "whatever happens to be currently loaded". You lack determinism on two fronts: (a) some assembly you think you need hasn't been used yet, and therefore hasn't been loaded yet, and (b) the list is everything, not just strict dependencies.

You can use an API like [Cecil](https://github.com/jbevain/cecil/wiki/HOWTO) to more accurately retrieve the information you're after.

**Comment by mehdihadeli** [comment]
Thanks for your response.
I don't want to load references assemblies, this is just a sample for showing the problem. My problem is xunit loads all DLLs even though I don't use that DLL in my code path (example is AutoMapper and MediatR Dlls), this is an unpleased behavior, I think It doesn't use default loading context for app domain. Is behavior only occurs in `dotnet test`. Just run [this test](https://github.com/mehdihadeli/Xunit.Sample/blob/main/Tests/UnitTest1.cs#L13) in vscode debugger mode, and you can see It load all non-used DLLs (it is not default behavior of app domain default loading context).

**Comment by bradwilson** [comment]
Our test discovery looks in all loaded assemblies: https://github.com/xunit/xunit/blob/93616f73fc2c5a1dca11963a41d52ce9e51f1bb3/src/xunit.execution/Sdk/Frameworks/TestFrameworkDiscoverer.cs#L98

The only assembly we ask to be loaded explicitly is your test assembly. There is a lot of loading that will happen implicitly, and the fact that .NET Core chooses to load more/different things than .NET Framework really has nothing to do with us. It's all about how they choose what needs to be loaded and when.

**Comment by mehdihadeli** [comment]
Hi,
Ok thanks, I have to handle this problem manually
