### ISSUE TITLE
with latest VS2022 update to Version 17.4.4 major problem with any new project include XUnit

### ISSUE THREAD

**Issue by dlandi** [xunit/xunit#2645]
Steps to reproduce: simply create a new XUnit Project in a clean directory from the VS2022 IDE and try to compile it. You will get this error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1705	Assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel' with identity 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' uses 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	TestProject1	E:\PredictiveSafety\Research\Xunit\TestProject1\TestProject1\CSC	1	Active
```

**Comment by hrumhurum** [comment]
I can confirm that. xUnit is unusable in the latest VS 2022. Especially when the solution contains other test projects that have the following lines in the project files:

```
<ItemGroup>
  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.4.1" />
  <PackageReference Include="MSTest.TestAdapter" Version="3.0.2" />
  <PackageReference Include="MSTest.TestFramework" Version="3.0.2" />
</ItemGroup>
```

Note the fresh versions of `Microsoft.NET.Test.Sdk`, `MSTest.TestAdapter`,  `MSTest.TestFramework` packages.

Typical error messages in the Tests output window of Visual Studio:

```
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
```

After numerous errors during the test discovery, the xUnit tests are listed in the Test Explorer window but they cannot be run. The Run command is available for them. However, it leads to nothing, the tests do not run and are displayed as non-executed.

**Comment by dlandi** [comment]
Note: I rolled back to version 17.4.3 and everything works again. Perhaps someone needs to be the VS team's attention on this?

**Comment by bradwilson** [comment]
Can you provide a repro project? My simple example is not suffering any specific failures:

![image](https://user-images.githubusercontent.com/16944/213943650-82bc76d4-ccfb-4779-af2a-097b7280adda.png)

**Comment by bradwilson** [comment]
Closing for lack of repro.

**Comment by aggieben** [comment]
I'm having this problem on 17.11.5 with xunit.v3 (0.4.0-pre.20) and xunit.runner.visualstudio (3.0.0-pre.35)

**Comment by bradwilson** [comment]
@aggieben Please open a new issue with a repro project. Thanks!
