### ISSUE TITLE
Support property injection for the fixture?

### ISSUE THREAD

**Issue by voroninp** [xunit/xunit#2652]
Currently xUnit supports injection of the fixture via constructor.

It's fine, but if I want to create a base class:
```
public abstract class FooTestBase : IClassFixture<TBar>
{
    public Bar Fixture { get; }
    protected FooTestBase(Bar fixture) => Fixture = bar;
}
```
Then all descendants have to declare same constructor.
I would not call it much of a burden, but I do not think it's much of a value as well.
So, if xUnit could detect single (`public`|`private`) writable `field`|`property` of type `TFixture` and initialize it with the value of fixture, that would be nice.

**Comment by bradwilson** [comment]
I believe this is part of the larger DI issue #1738, so I'm going to close this as a duplicate. Thanks!
