### ISSUE TITLE
What happend?

### ISSUE THREAD

**Issue by carrot7291** [xunit/xunit#2666]
There are many pull requests and issues I didn't subscribe but I find them in my Email and GitHub mobile
<img width="960" alt="屏幕截图_20230206_114803" src="https://user-images.githubusercontent.com/109449995/216880069-904b666a-4cda-433e-8c3a-3d0c358ad57c.png">
<img width="960" alt="屏幕截图_20230206_115318" src="https://user-images.githubusercontent.com/109449995/216880172-4cfde408-2038-46fb-957a-a6697398bd2e.png">

**Comment by bradwilson** [comment]
This is a question for GitHub, not for us.
