### ISSUE TITLE
xUnit 1033 - In case of derived fixture type injected in constructor

### ISSUE THREAD

**Issue by manoj-choudhari-git** [xunit/xunit#2668]
Description: If fixture specified in class definition is a base type and if the type injected in the constructor is a derived type from it, then xUnit.Analyazers throw xUnit 1033.

> xUnit.Analyzers v1.1.0
> xUnit version 2.4.2

The code given below will basically show the xunit 1033.

```CSHARP
namespace DemoTestProject
{
    public class BaseClass
    {
        public int Id { get; set; }
    }

    public class Derived : BaseClass
    {
        public string? Name { get; set; }
    }

    public class UnitTest1 : IClassFixture<BaseClass>
    {
        private readonly string name = null!;
        public UnitTest1(Derived fixture)
        {
            // xUnit 1033 warning
            string name = fixture.Name!;
        }

        [Fact]
        public void Some_Test()
        {
            Assert.Equal("test", name);
        }
}
```
> xUnit1033	Test class 'DemoTestProject.UnitTest1' does not contain constructor argument of type 'DemoTestProject.BaseClass'. Add a constructor argument to consume the fixture data.	
![image](https://user-images.githubusercontent.com/46196232/217772423-981ce44f-c3a9-4ea9-9841-963899aea5b8.png)
 

I think it is because the below code which just checks for type to be exactly same as the type specified in the fixture.

```CSHARP

var hasConstructorWithTFixtureArg = classSymbol
	.Constructors
	.Any(x => x.Parameters.Length > 0 && x.Parameters.Any(p => Equals(p.Type, tFixtureDataType)));
```

**Comment by bradwilson** [comment]
What is the use case here? We see `IClassFixture<BaseClass>` and we're going to make exactly `BaseClass`. If you want `Derived`, you need to change to `IClassFixture<Derived>`.

**Comment by manoj-choudhari-git** [comment]
A library in that project had:
- a base fixture
- a IntegrationTestBaseClass which can serve as base class for all integration tests, which was using BaseFixture 
- while using IntegrationTestBaseClass as base class, we could not pass DerivedFixture as the base class was not generic.  

While I agree that we should always pass the specific type of fixture and this is very very edge case probably, but this situation made me think , if we should add this use-case as well in the xunit package - to identify even the derived type for this code analysis rule.  Thoughts ?

**Comment by bradwilson** [comment]
I'm sorry, this is not a feature we're interested in having in the core product.
