### ISSUE TITLE
Skipped tests cause build failure on build server

### ISSUE THREAD

**Issue by recumbent** [xunit/xunit#267]
When I run my build - specficially the unit tests - with V2 on our build server the fact that we have Skip tests is causing the build to fail.

It may be but I'm doing something wrong but it looks to me that this is by design (skipped tests are reported using ```Console.Error```) - if so where was this discussed as I'd like to understand the reasoning.

Obviously (given that we have skipped tests, for what I think are tolerably good reasons) I'd prefer this not to be the case but learn first, discuss second.

**Comment by bradwilson** [comment]
What build system bases failures on text being written to `Console.Error`?

**Comment by recumbent** [comment]
Your reaction strongly implies I'm doing something wrong which gives me a basis to move forward

I'm getting the error on AppVeyor, build script is Fake - and I'll chase it up there too, *but* once upon a time a skip would be yellow and now its red - and given that its being written stderr then if I'm a build script and I see errors reported then de-facto I'd expect to be unhappy?

**Comment by bradwilson** [comment]
I'm just curious. It's the first time I've heard of a build system that implies failure from stderr vs. stdout (rather than using exit codes, which is the traditional way to fail something in automated builds).

In point of fact, the only Console.Error code I could find was in the `AppVeyorLogger`, which was written by the author of AppVeyor in a pull request for us. I have no problem converting the `Console.Error` calls, but I would like to hear from @FeodorFitsner as to whether he did this purposefully.

**Comment by recumbent** [comment]
For what its worth there's Console.Error in the StandardOutputVisitor https://github.com/xunit/xunit/blame/b06daebe2437b69db20f2b1f9a6f7e50f9dd72ee/src/xunit.console/Visitors/StandardOutputVisitor.cs#L86 which is why I brought it up as an issue and wondered if it was by design.

It turns out that the cause of my issue appears to be not just one thing but several taken all together, classic unforeseen consequences - because I'm using appveyor to call powershell to call fake and because there's then stuff written to StdErr it all kind of ends badly.

It should be possible to address this in a way that *shouldn't* require any changes (I'm in conversation with @FeodorFitsner on the subject). As I said above it does work locally so its not just what but where and how (which of course is what makes it fun, but it would be nice if things "just worked" a bit more often)

**Comment by FeodorFitsner** [comment]
Regarding failure and StdErr. It's not AppVeyor, but PowerShell treats anything written into StdErr as an exception. In it's turn AppVeyor terminates build if there are exceptions in PowerShell script which is quite logical. I'm wondering what is the reason for writing something into StdErr?

**Comment by FeodorFitsner** [comment]
Well, we could easily replace `Console.Error` in AppVeyor visitor and send a pull request.
In the meantime I'll deploy patched xUnit to build workers until the next official build with this PR is coming.

Would that work?

**Comment by bradwilson** [comment]
@recumbent You're right, I missed that one. Sorry. :(

@FeodorFitsner If you did it because you were copying my code, then my apologies for dragging you into this. :)

**Comment by FeodorFitsner** [comment]
No problem! Will fix that shortly and send PR.

**Comment by FeodorFitsner** [comment]
Done: https://github.com/xunit/xunit/pull/271
