### ISSUE TITLE
Add Assert.Contains overloads for IHashSet<> and IDictionary<> with slightly different behavior to ICollection

### ISSUE THREAD

**Issue by codingdave** [xunit/xunit#2671]
Hi,

with the sample over here I can show different behavior for both xUnit.Assert.Contains and HashSet.Contains. 

This was highly unexpected for me and allowed to let bugs pass my tests. 
The analyzer warning for me suggests that xUnit.Assert.Contains is preferable and in my understanding that would mean "do the same job but better". 

https://github.com/codingdave/xunit-Hashset-Contains-Issue/tree/master

Am I missing something? Kind regards
Dave

**Comment by codingdave** [comment]
[Fact]
        public void Test1()
        {
            var persons = new HashSet<Person> { new Person("a") };
            var firstPerson = persons.First();
            Assert.NotNull(firstPerson);
            Assert.Contains(firstPerson, persons);
            Assert.True(persons.Contains(firstPerson));
            firstPerson.Name = "b";
            Assert.Contains(firstPerson, persons); <-- True
            Assert.True(persons.Contains(firstPerson)); <-- False
        }

**Comment by bradwilson** [comment]
`Assert.Contains` today uses this logic:

- If `container.Contains(item)` is `true`, then it's okay
- If `container.Contains(item)` is `false`, we resort to the provided (or our default) comparer

https://github.com/xunit/assert.xunit/blob/d4e3195b3e7be0ead099819413e003c62c56eb64/CollectionAsserts.cs#L233-L241

The reason for this is that _most_ containers don't have special comparisons, and if you provide a reference type, then the comparison would be reference vs. reference. We want an actual equality comparison to happen, not just a reference comparison, so we fall back to that.

If we were to make a change here, I think what we'd do is add explicit overloads for `IHashSet<>` and `IDictionary<>`, and then when the developer calls those without a custom comparer, we just always trust the result of `collection.Compare(item)` as we assume that there is already a custom comparer in place for hash sets and dictionaries.

**Comment by teeshajain17** [comment]
Hey, If anyone is not working on this issue, please assign this issue to me.

**Comment by codingdave** [comment]
Hi, I'm on it. However, I have trouble building. Lets see if I am successful tomorrow, otherwise I will drop my attempt.

**Comment by teeshajain17** [comment]
Sure, Please let me know.

**Comment by bradwilson** [comment]
Fixed in https://github.com/xunit/assert.xunit/commit/35047796d98e1250ef3d280c5ba6c4758c76a358, tested in https://github.com/xunit/xunit/commit/ddb0a697290e82445522322541c40dcfee4469c3

**Comment by bradwilson** [comment]
@codingdave You can get one now on MyGet:

- https://myget.org/feed/xunit/package/nuget/xunit.assert
- https://myget.org/feed/xunit/package/nuget/xunit.assert.source

There is no planned 2.x release to NuGet right now.

**Comment by bradwilson** [comment]
FYI, this is being shipped in 2.5.0.
