### ISSUE TITLE
Test description not showing in VS  test explorer 

### ISSUE THREAD

**Issue by menaheme** [xunit/xunit#2674]
Hello , im sorry if this is not relevant to xunit, 

I moved from MS Test , where the test description specified in the TestMethod attribute shows in the test explorer.

in Xunit i read the the Description attribute is the closest thing, but i dont see the description anywhere 

Please advise

**Comment by bradwilson** [comment]
Using `DisplayName`, I am not able to reproduce your issue:

Without:

![image](https://user-images.githubusercontent.com/16944/219882168-043c1fdc-3a4f-41bc-a646-68f9de8670c4.png)

With:

![image](https://user-images.githubusercontent.com/16944/219882140-a309f7b7-e301-444b-b6e9-1e79b598b9b5.png)

**Comment by menaheme** [comment]
:) 
thanks !
