### ISSUE TITLE
Theories with nullable enums don't behave well with NCrunch

### ISSUE THREAD

**Issue by bgeihsgt** [xunit/xunit#268]
If you have a theory with a nullable enum parameter, NCrunch fails running the tests.  I filed this originally with the NCrunch developer, but he mentioned it's a problem with "the way xUnit currently interprets test metadata being exposed through static analysis".  I'm not sure if that makes any sense, so I'm filing it as an issue here.  Here's a link to the forum post I filed with NCrunch:

http://forum.ncrunch.net/yaf_postsm6844_xUnit-2-0-Theory-with-nullable-enum-broken.aspx#post6844

And here's a sample test that reproduces the problem:

```
public enum Foo
        {
            First,
            Second
        }


        [Theory]
        [InlineData(null)]
        [InlineData(Foo.First)]
        [InlineData(Foo.Second)]
        public void Repro(Foo? input)
        {
            Assert.Equal(input, input);
        }
```

**Comment by bradwilson** [comment]
I'm confused by his answer, so I'll let @remcomulder suggest what needs to be fixed (or send us a PR). :grinning:

**Comment by remcomulder** [comment]
Sorry - no issue here.  It's too difficult to implement this using static analysis (cannot find a way to represent the type).  I've now switched NCrunch's default analysis method for xunit over to Dynamic Analysis, which should cleanly resolve this.
