### ISSUE TITLE
Allow test name override for InlineData tests to avoid: Incorrect format for TestCaseFilter Missing Operator '|' or '&'

### ISSUE THREAD

**Issue by istarion111** [xunit/xunit#2680]
We use xUnit on Azure Devops pipelines with VSTest / dotnet test. We have a large set of integration tests which depends on many microservices. We are working on minimizing the number of flaky tests, but for various reason we are not able to guarantee 100% availability of our testing environment and we have to deal with occasional flakiness. 

Currently Azure devops pipeline tasks are not able to rerun xunit parametrized  tests with special characters (with error **Incorrect format for TestCaseFilter Missing Operator '|' or '&'**). 
From the last interaction with support it seems that they are not fixing this bug in the near future, which makes pipelines with xunit tests unreliable.

Although I am aware this does not solve the root problem, it would help, if 

1. xUnit allowed overriding a test name (including parameters) for InlineData attributes, so that we could eliminated tests with names like ExampleTest("a") which break pipeline filters.
2. Or even better, allow a set of forbidden characters which would be replaced in test names.

**Comment by bradwilson** [comment]
Have you consulted with VSTest to see how you can provide a literal `|` or `&` in a query? I assume there is some kind of escaping mechanism available...

**Comment by bradwilson** [comment]
Closing as an external issue.
