### ISSUE TITLE
xunit.execution: TypeLoad exception when loading xunit.execution on newest aspnet vNext

### ISSUE THREAD

**Issue by Alxandr** [xunit/xunit#269]
I'm having type load exceptions when trying to reference xunit.execution on my vNext project. Spesifically:

    System.TypeLoadException: Method 'Find' in type 'Xunit.Sdk.XunitTestFrameworkDiscoverer' from assembly 'xunit.execution, Version=2.0.0.2785, Culture=neutral, PublicKeyToken=null' does not have an implementation

This happens on both `aspnet50` and `aspnetcore50`.

**Comment by Alxandr** [comment]
Some more info: This seems to steam from a incompatibility between the latest version of `xunit.execution` and `xunit.runner.utility`, or some combination of their dependencies. When I removed the dependency on `xunit.runner.utility`, the problem went away.

**Comment by bradwilson** [comment]
The dependency on `xunit.execution` should be inside your unit test project. The newest (RC1) NuGet packages correctly bring in this dependency. Previous versions of the runner had the dependency in the wrong place.

Please make sure you're using the RC1 version of both the unit test framework as well as the runner, as outlined here: http://xunit.github.io/docs/getting-started-aspnet.html

**Comment by Alxandr** [comment]
I'm not making a project I want to unit test, rater a test runner though. I started with the `aspnet.xunit` runner, and have just been exploring APIs, and using the discoverer from `xunit.runner.utility` (which causes it to load `xunit.execution`) caused this error.

**Comment by bradwilson** [comment]
Runners should only link against runner utility. They should never explicitly link against the core or execution libraries. Runners are designed to be version-independent, and that version independence comes because runner utility loads the execution library that is linked by the unit tests, rather than from the runner.

**Comment by Alxandr** [comment]
I see. However, the version-utility completely fails to locate `xunit.execution` (and as said, when I help it it crashes) on vNext...

**Comment by bradwilson** [comment]
We believe this to be functional already, so closing.
