### ISSUE TITLE
Assert.Equivalent throws System.Reflection.TargetParameterCountException when indexer used 

### ISSUE THREAD

**Issue by dzh-hs** [xunit/xunit#2698]
Assert.Equivalent() doesn't work for a instances of the same class having an indexer property. But it works OK for identical instances with indexer property.

**Is it reproducible** 
Yes
Version=2.4.2

**Path to reproduce**
1. Create a class with an indexer property
```csharp
public class IndexerClass
{
    private int _value;
    public int this[int id]
    {
        get => _value;
        set => _value = value;
    }
}
```
2. Create a test containing `Assert.Equivalent`
```csharp
[Fact]
public void Equivalent_ObjectWithIndexer_ThrowsTargetParameterCountException()
{
    var c = new IndexerClass();
    var c2 = new IndexerClass();
    Assert.Equivalent(c, c2, true);
}
```
3. Run the test

**Expected result**
Assert.Equivalent() considers objects Equivalent when all the properties are equal

**Actual result**
Throws System.Reflection.TargetParameterCountException:  Parameter count mismatch.

**Solution approach**
Skipping indexer properties is not a bad idea because indexers look more like a function with a parameter.

**Comment by bradwilson** [comment]
Already fixed. https://github.com/xunit/assert.xunit/commit/d04a4dcbb7288b4cf41e60db63a43be44f8d0cb5
