### ISSUE TITLE
IAssertionException does not honour XUNIT_VISIBILITY_INTERNAL

### ISSUE THREAD

**Issue by idg10** [xunit/xunit#2703]
Adding a reference to `xunit.assert.source` adds numerous types in source code form to your project (enabling extension scenarios not otherwise possible), and with most of these, it enables you to determine whether those types are publicly visible outside of your project with the XUNIT_VISIBILITY_INTERNAL preprocessor symbol.

But this is not the case for `IAssertionException`. I discovered this because the [Rx.NET project](https://github.com/dotnet/reactive) includes [tests to ensure that we don't accidentally change our API surface area](https://github.com/dotnet/reactive/tree/main/Rx.NET/Source/tests/Tests.System.Reactive.ApiApprovals), and I discovered to my surprise that if I upgrade the `Microsoft.Reactive.Testing` library from `xunit.assert.source` v2.4.1 to v2.4.2, our library now exports a public type named `Xunit.Sdk.IAssertionException`.

Most of xUnit's assert types carefully avoid this. For example, the `Assert` class has [this](https://github.com/xunit/assert.xunit/blob/adf018d77ea89003b0c57b9be1ba88d81ef0937e/Assert.cs#L14-L19):

```cs
#if XUNIT_VISIBILITY_INTERNAL
	internal
#else
	public
#endif
	partial class Assert
```

Non-public types such as [ArgumentFormatter](https://github.com/xunit/assert.xunit/blob/adf018d77ea89003b0c57b9be1ba88d81ef0937e/Sdk/ArgumentFormatter.cs) don't do that because they're going to be `internal` in all cases.

But [IAssertionException](https://github.com/xunit/assert.xunit/blob/adf018d77ea89003b0c57b9be1ba88d81ef0937e/Sdk/IAssertionException.cs) is declared to be unconditionally public:

```cs
	public interface IAssertionException
	{ }
```

It is possible to work around this by excluding the relevant file from compilation:

```xml
  <ItemGroup>
    <Compile Remove="$(NuGetPackageRoot)xunit.assert.source\**\contentFiles\cs\**\Asserts\Sdk\IAssertionException.cs" />
  </ItemGroup>
```

and then writing an `internal` definition of the interface to replace the removed one.

But I don't think this should be necessary. If you're using `xunit.assert.source`, I don't see why it would be necessary for components using that package to expose this as a public type as part of their own API surface area.

**Comment by bradwilson** [comment]
Thanks! This was an oversight and has been fixed. Pre-release packages will be on MyGet as soon as the CI finishes.
