### ISSUE TITLE
InlineDataMustMatchTheoryParameters does not properly handle explicit array for params array parameter

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#2711]
While working on understanding xunit/visualstudio.xunit#371, I discovered that there appears to be an edge case causing an exception.

The test looks like this:

```csharp
using Xunit;

public class UnitTest1
{
    [Theory]
    [InlineData(new int[] { })]
    public void VariableArgumentsTest(params int[] sq)
    { }
}
```

While building I get the following exception:

`CSC : warning AD0001: Analyzer 'Xunit.Analyzers.InlineDataMustMatchTheoryParameters' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Index was out of range. Must be non-negative and less than the size of the collection.`

**Comment by nih0n** [comment]
Weird, this was supposed to be fixed as #1328 says

**Comment by bradwilson** [comment]
Lemme push up a new analyzers package, this might be because I'm still using an old one.

**Comment by bradwilson** [comment]
Nope, it's definitely still happening with `1.2.0-pre.8` which is about 5 minutes old.

**Comment by bradwilson** [comment]
Looking at that issue, that seems to related to `[InlineData]` but doesn't specifically call out InlineData with an explicit array value.

**Comment by xp44mm** [comment]
@bradwilson Agree, I have tried using other methods to work around this limitation, Any combination of Theroy that uses variable parameters does not support empty arrays.

**Comment by bradwilson** [comment]
I've determined what the issue is: the analyzer does not allow you to pass an explicit array of values for a `params` array argument; it's hard-coded to assume that you will always just pass raw values. It comes down to this:

https://github.com/xunit/xunit.analyzers/blob/42de44b9f7fc5f626b4ec1b068b3baf0d3bbdfd3/src/xunit.analyzers/InlineDataMustMatchTheoryParameters.cs#L95-L99

The actual AD0001 happens when we're trying to (incorrectly) report that your data element type is wrong (because it's determined that `int[]` isn't type-compatible with `int`, because of the bad assumption described above). So that causes this code to throw:

https://github.com/xunit/xunit.analyzers/blob/42de44b9f7fc5f626b4ec1b068b3baf0d3bbdfd3/src/xunit.analyzers/InlineDataMustMatchTheoryParameters.cs#L126-L133

That's because `dataParameterExpressions` is an empty array (since our expression is an empty array), so `dataParameterExpressions[valueIdx]` throws `ArgumentOutOfRangeException`.

If you change the test slightly to this:

```csharp
using Xunit;

public class UnitTest1
{
    [Theory]
    [InlineData(new int[] { 1, 2, 3 })]
    public void VariableArgumentsTest(params int[] sq)
    { }
}
```

Now instead we get the inappropriate xUnit1010:

```
error xUnit1010: The value is not convertible to the method parameter 'sq' of type 'int'. Use a compatible data value.
```

So the bug here (incorrect handling of explicit arrays for `params`) actually manifests in two ways:

(a) we incorrectly report xUnit1010 for non-empty explicit arrays
(b) we throw an exception (causing AD0001) for empty explicit arrays
