### ISSUE TITLE
Theory support for async test running

### ISSUE THREAD

**Issue by redmondgiant** [xunit/xunit#2712]
This is about executing the TestDataRows of a [Theory] all async instead of serially, not about getting the row data async.

I have a lot of data-driven tests that logically are permutations/MatrixTheoryData sorts of scenarios. So I have a lot of permutations per [Theory]. Currently I do not see any way to let XUnit itself execute these in parallel. I would think I am not alone in needing this.

I do not want to hack/work around it in ways that report the test case results in odd or artificially bulked ways (like doing the Task.WhenAll myself in a single method, and seeing all the test results in one giant test case output).

I have seen others mention the async execution of [Theory]s in passing a few times, but I don't see an Issue open for it.

A simple repro would be to have these 8 data rows all execute simultaneously:

        [Theory]
        [InlineData(false, false, false)]
        [InlineData(false, false, true)]
        [InlineData(false, true, false)]
        [InlineData(false, true, true)]
        [InlineData(true, false, false)]
        [InlineData(true, false, true)]
        [InlineData(true, true, false)]
        [InlineData(true, true, true)]
        public async void SomeTest(bool a, bool b, bool c) { ... }

**Comment by bradwilson** [comment]
This would be covered by #2055. In essence the idea is that we would allow the user to opt into a different model of parallelism than what we have today, which would allow you to get what you want here.
