### ISSUE TITLE
NullReferenceException when test runs, unless order of test parameters is modified

### ISSUE THREAD

**Issue by lakario** [xunit/xunit#2718]
I *think* this is an XUnit issue given the stacktrace, but not completely certain.

Configuration:
- xunit 2.4.1, 2.4.2
- xunit.runner.visualstudio 2.4.5
- Moq 4.8.1
- AutoFixture 4.0.0
- AutoFixture.XUnit2 4.0.1
- AutoFixture.AutoMoq 4.0.0
- Microsoft.NET.Test.SDK 17.6.0

Scenario
- Unit test uses AutoFixture.AutoMoq (`[AutoMoqData]`) to inject various required values into a `[Theory]` test
- Depending on the order of one specific `Mock<IMyType> myTypeMock` parameter, the test logic runs to completion and the test throws a `NullReferenceException` from within XUnit
  - When the offending parameter is in ordinal position 0-7, the test **FAILS**
  - When the offending parameter is in ordinal position 8+, the test **PASSES**
  - If the offending parameter is removed entirely (it's not used), the test **PASSES**
  - Logs with `ITestOutputHelper.WriteLine` added throughout the test are all printed, regardless of the test outcome
- Running the test in Debug with xunit 2.4.1 (JetBrains Rider), the test **PASSES**
  - The same test with Debug in xunit 2.4.2 **FAILS**
- Running the test with `dotnet test`, the test **FAILS**
- Running the test with `async void` instead of `async Task`, the test **PASSES**
```
System.NullReferenceException: Object reference not set to an instance of an object.

System.NullReferenceException
Object reference not set to an instance of an object.
   at Xunit.Sdk.TestInvoker`1.GetTaskFromResult(Object obj) in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 163
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 257
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
```

![unit-tests](https://github.com/xunit/xunit/assets/120187/8a582aa0-3211-457c-80ab-2ab6660987bc)

**Comment by lakario** [comment]
I discovered today that if I change the signature of this method to `async void` the test passes with any order or parameters.

**Comment by bradwilson** [comment]
Can you provide a repro project? The screenshot is not enough to be able to reproduce the issue.

**Comment by lakario** [comment]
Hi @bradwilson given the closed source nature of this code I am unable to provide a copy here on GitHub. Is there anything else we can do to look into this? Maybe privately?

**Comment by bradwilson** [comment]
Are you able to simplify it into a repro that you can share? Or is this the only time you've seen this?

The fact that it disappears when you change to async void makes me suspect something unusual with is happening with the task...

**Comment by lakario** [comment]
First time I've ever seen anything like this after using xunit for about
ten years. This behavior is truly bizarre. I can try to isolate it into a
new project, though I'm not at all confident I'll be successful.

**Comment by bradwilson** [comment]
Closing this issue for age. Please open a new issue with a repro project if it recurs. Thanks!
