### ISSUE TITLE
Can someone document running tests with the command line test runner with nuget package?

### ISSUE THREAD

**Issue by dparvin** [xunit/xunit#272]
I ended up having to ask Microsoft how to do this: [Microsoft Forums](https://social.msdn.microsoft.com/Forums/en-US/f5d81ed3-02a2-41ae-a212-9133d4f01d1d/running-tests-where-the-test-runner-is-in-a-nuget-package-using-vstestconsoleexe?forum=vsunittest)

I got sent here: [Microsoft Blog - Aseem Bansal](http://blogs.msdn.com/b/aseemb/archive/2012/03/03/how-to-make-your-discoverer-executor-extension-visible-to-ute.aspx) and it sent me to this [Visual Studio Blog to explain more](http://blogs.msdn.com/b/visualstudioalm/archive/2013/06/11/part-3-unit-testing-with-traits-and-code-coverage-in-visual-studio-2012-using-the-tfs-build-and-the-new-nuget-adapter-approach.aspx)

It would be nice to make it so people using xunit can find this information easier.

**Comment by bradwilson** [comment]
The Getting Started documentation covers this:

http://xunit.github.io/docs/getting-started.html#add-xunit-runners-ref

**Comment by dparvin** [comment]
Ok.  I am looking into if this runner provides what I need.  I am trying to get a [code coverage report](https://reportgenerator.codeplex.com/) out of the system and with the documentation I talked about here I am able to get it.  I will let you know if I am able to get it working.
