### ISSUE TITLE
SkipReason is not deserialized for XunitSkippedDataRowTestCase

### ISSUE THREAD

**Issue by estrizhok** [xunit/xunit#2720]
Given the following test class:

```
public class UnitTest1
  {
    [Theory]
    [MemberData("SimpleData", Skip = "rgre")]
    public void TestWithSimpleData(int i)
    {
      Assert.True(i > 1);
    }

    public static IEnumerable<object[]> SimpleData()
    {
      yield return new object[] { 1 };
      yield return new object[] { 2 };
    }
  }
```

After tests are discovered, an attempt to run a particular test-case will actually run it, despite it being a XunitSkippedDataRowTestCase with a non-null SkipReason.
This happens because `ITestFrameworkExecutor.Deserialize` does not honor serialized value of the SkipReason property.
Not sure if that is intended.

**Comment by bradwilson** [comment]
In this testing, this appears to be fixed already with `xunit` 2.5.0-pre.21 and `xunit.runner.visualstudio` 2.5.0-pre.14.
