### ISSUE TITLE
Release wanted to fix vulnerabilities

### ISSUE THREAD

**Issue by azerios** [xunit/xunit#2724]
Dear,

The most recent version in pre-release available in Nuget is fixing vulnerabilities linked to NETStandard and child reference.
The last version is referencing the version 1.6.1 which reference System.Net.Http 4.3.0, but not the pre-release version.

My security team want to have every reference of my project up to date and not being as pre-release.
Without this, my project will not be validated for new releases and will not go live.

So please, share an ETA for an update and an official version of this package.

Regards

**Comment by bradwilson** [comment]
We do not take a dependency on this package. This is a transient dependency from .NET Standard. We have no intention of taking a dependency on a package that we don't use.

If you are concerned, you can work around this yourself by simply adding a reference to the latest System.Net.Http package.

In addition: xUnit.net should never be deployed into production systems. It has not been validated for such environments.
