### ISSUE TITLE
Add ability to add warning messages to tests

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#2726]
Per https://github.com/xunit/xunit/discussions/2676 this would allow warning messages to be logged, but there will not be a direct `Assert.Warn` feature in xUnit.net itself.

Adding a warning message is done via the test context:

```csharp
TestContext.Current.AddWarning("This is a warning message");
```

Warning messages are only legal during test execution (including constructor and `Dispose`/`DisposeAsync`); attempting to send a warning message in any other context will result in a diagnostic message indicating the mistake.

Unlike other extensibility points being based on "contractual exceptions", warning messages are not designed to stop test flow execution, which makes exceptions an improper way to expose this feature. Unfortunately that means any third party that wants to add an equivalent to `Assert.Warn` will need to reference `xunit.v3.core` to get access to `TestContext`. _**I am open to any suggestions about how to expose this functionality that wouldn't require a direct xUnit.net reference.**_

Passing tests with warnings will continue to be reported as a passing test. There is a [new `failWarns` configuration file setting](https://xunit.net/docs/configuration-files#failWarns) that can be used to convert "passing tests with warnings" into failed tests. The console runners will have a new `-failWarns` switch, and the MSBuild runner will have a new `FailWarns` property for this as well. Skipped tests with warnings (meaning, a test which is skipped dynamically, after logging one or more warning messages) will always be reported as skipped, regardless of the "failWarns" setting; of course, the [existing `failSkips` functionality](https://xunit.net/docs/configuration-files#failSkips) can turn any skipped test (with or without warnings) into a failed test.

The console and MSBuild runners will log warnings for all tests, even passing tests (this is identical to the existing behavior where passing tests are typically not shown unless they have output).

**Comment by amitjaura** [comment]
Can you please refer me to documentation on how can we use this?

**Comment by bradwilson** [comment]
You must be using v3 (which is currently in alpha) to use this feature.

I don't currently recommend this for most users because we're still working to enable support for `dotnet test` and Test Explorer in Visual Studio, so running tests becomes challenging for most users.
