### ISSUE TITLE
Add Assert.IsNotAssignableFrom to match reports for xUnit2018

### ISSUE THREAD

**Issue by xZise** [xunit/xunit#2727]
When using `Assert.IsNotType`/`Assert.IsType` the analyzer reports xUnit2018 to use `IsAssignableFrom`. While for the positive variant this works fine, it does not make sense for `Assert.IsNotType` (although thanks to the analyzer I noticed that this assert could never fail).

```csharp
namespace XUnitTestAnalyzer2018
{
    public class UnitTest1
    {
        [Fact]
        public void Test1()
        {
            ConcreteClass c = new();
            Assert.IsNotType<AbstractBaseClass>(c);
        }
    }

    public abstract class AbstractBaseClass { }
    public class ConcreteClass : AbstractBaseClass { }
    public class OtherClass { }
}
```

So I'd suggest to add `Assert.IsNotAssignableFrom()` and to modify the analyzer to recommend the matching assertion.

**Comment by bradwilson** [comment]
I can't come up with a case where I'd use `Assert.IsNotAssignableFrom` personally, but I also can't come up with a reason not to add it. 😂 It makes sense to exist for the purpose of symmetry.

**Comment by bradwilson** [comment]
This is shipped in `xunit.analyzers` version `1.2.0-pre.22`.
