### ISSUE TITLE
nuget package manage cannot resolve dependences for xunit using MVC5 

### ISSUE THREAD

**Issue by heathyates** [xunit/xunit#274]
I am following the directions as given here: http://xunit.github.io/docs/getting-started.html
Unfortunately, I am given the following error. 

![xuniterrormvc5](https://cloud.githubusercontent.com/assets/1896424/5932593/878746d4-a676-11e4-9abb-4a47da851bfd.PNG)

I have attempted to manually download each dependency with nuget, but xunit.core produces the same error.

**Comment by bradwilson** [comment]
Your NuGet Package Manager (inside Visual Studio) is out of date. Please update that and try again.

**Comment by heathyates** [comment]
Thanks for your reply Brad. I did see something you might be interested in though. For MVC6, instead of using >k run in the command line, it only works when you do k test. Has something changed since you wrote the directions found here: 
http://xunit.github.io/docs/getting-started-aspnet.html

You can see the issue here: 
![xuniterror](https://cloud.githubusercontent.com/assets/1896424/5940406/34b65972-a6d0-11e4-8e31-22a42d61242f.PNG)

If I'm doing something dumb again, please let me know. Thanks.

**Comment by bradwilson** [comment]
Thanks, I've fixed the documentation. :)
