### ISSUE TITLE
Add release notes link to NuGet package

### ISSUE THREAD

**Issue by bgrainger** [xunit/xunit#2742]
It actually took me a few minutes to find the (well-written and detailed) [2.5.0 release notes](https://xunit.net/releases/2.5.0): Google's top link was to an older version, and [NuGet](https://www.nuget.org/packages/xunit) has no link to them.

It would be helpful for package consumers if the xunit NuGet page promoted the release notes. 

I believe this should be possible by adding `<PackageReleaseNotes>https://xunit.net/releases/2.5.0</PackageReleaseNotes>` here: https://github.com/xunit/xunit/blob/main/src/Directory.Build.props#L48. (One downside might be having to update that URL whenever [version.json](https://github.com/xunit/xunit/blob/2.5.0/version.json) changes, although perhaps `$(BuildVersionSimple)` from Nerdback.GitVersioning could be used to keep it always up-to-date?)

I'm happy to open a PR to add this.

**Comment by bradwilson** [comment]
Agreed, this is a good idea!

**Comment by bradwilson** [comment]
FWIW, we build all our package files via .nuspec files, so putting properties into the project files will not be sufficient.

Example: https://github.com/xunit/xunit/blob/v2/src/xunit.nuspec

There, you should be able to just use `$PackageVersion$` as the substitute.
