### ISSUE TITLE
`AssertActualExpectedException` is missing in xunit.assert 2.5.0

### ISSUE THREAD

**Issue by CaptnCodr** [xunit/xunit#2744]
I updated xunit from 2.4.2 to 2.5.0 but I found out that `AssertActualExpectedException` is now missing.
Is there anything I can use now for that? This is actually a breaking change.

Thank you in advance

**Comment by bradwilson** [comment]
No, this exception has been removed from 2.5.0. The only base exception now is `XunitException` and it's expected that each assertion creates its own message wholly. This was done in the pass of improving the usefulness of messages.

Here is an example of the new pattern: https://github.com/xunit/assert.xunit/blob/c02d676a36e75da394c2f6ed9d54ffc54d3bf973/Sdk/Exceptions/NotEqualException.cs#L49-L72

**Comment by CaptnCodr** [comment]
Ok, thank you.

**Comment by abelbraaksma** [comment]
`MatchException` has gone too. Why aren't any of these mentioned in the readme or in a "upgrade to 2.5.0 guide"? A library so widely used as xUnit really ought to have massive exclamation points and warnings plus instructions on how to move to a new, largely incompatible version of the library.

I'm sure the change was warranted. However, I find it unfortunate that it wasn't communicated then, or now, and that there was no major version bump (2.4 -> 3.0) as is common when introducing (large) incompatibilities.

Another option is to keep the old exceptions/types/methods with a deprecation warning. Easy enough, and you can communicate the recommended action in the message.

But please, let us not find this out by ourselves and having to go over the commit history....

**Comment by bradwilson** [comment]
@abelbraaksma It was noted in the 2.5.0 release notes (emphasis added):

> Aside from normal quality of life improvements, the primary feature of this release is a heavily updated assertion library, which includes several new assertions, several new overloads for existing assertions, and a pass to ensure that the messages from the assertions are now more concise and consistent. We wrote up an overview of [the updates in the 2.5.0 assertion library messages](https://xunit.net/releases/v2/2.5.0-assertions). For the most part, developers should not notice much compile-time differences (aside from perhaps the occasional type ambiguity that may come from new overloads); **_there are also some breaking binary changes, most prominently with the gutting and reworking of the exception classes that are thrown by the individual assertions. Because of some of these breaking changes, we felt it was warranted to bump the version up to 2.5.0._**
