### ISSUE TITLE
TestCollectionAttribute - code and documentation disagree?

### ISSUE THREAD

**Issue by rawling** [xunit/xunit#275]
On the "Running Tests in Parallel" documentation page (http://xunit.github.io/docs/running-tests-in-parallel.html) it says you can group classes into custom test collections by decorating them with a TestCollection attribute.

However, I can't find such an attribute via Intellisense or in the source on github.

**Comment by bradwilson** [comment]
Thanks, I've updated the docs. (It should be `[Collection]`, not `[TestCollection]`.)
