### ISSUE TITLE
Assert.NotNull<T>(T?) missing non-nullable annotation

### ISSUE THREAD

**Issue by AArnott** [xunit/xunit#2750]
Updating xunit from 2.4.2 to 2.5.0 regressed nullable ref annotations. Calling `Assert.NotNull<T>(T?)` does not instruct the compiler that a successful return from that method guarantees that the argument is non-null.

It seems that for 2.4.2, my code binds against `Assert.NotNull(object?)` which _does_ have the `[NotNull]` attribute applied to the parameter.

**Comment by bradwilson** [comment]
Can you provide a repro? The override you're talking about has a "where T: struct", which means `T?` translates to `Nullable<T>`, and struct `T`s cannot be null.

**Comment by AArnott** [comment]
`T` cannot be null, but your parameter type is `T?` which *can* be null. But once it passes your method without throwing, we know that the `T?` is *not* null, and so the attribute would allow the compiler to give it that credit.

**Comment by AArnott** [comment]
Here's the sample:

```cs
public class UnitTest1
{
    [Fact]
    public void Test1()
    {
        int? s = GetSomething();
        Assert.NotNull(s);
        int s2 = s.Value;
    }

    [Fact]
    public void Test2()
    {
        int? s = GetSomething();
        AssertNotNull(s);
        int s2 = s.Value;
    }

    static int? GetSomething() => 3;

    static void AssertNotNull<T>([NotNull] T? value) where T : struct
    {
        if (value is null) throw new Exception();
    }
}
```

With xunit 2.5, Test1 has a warning about using `s.Value` but Test2 does not, because it has the attribute on the parameter.

**Comment by bradwilson** [comment]
Ah, I see. The intended usage is:

```csharp
public class UnitTest1
{
    [Fact]
    public void Test1()
    {
        int? s = GetSomething();
        int s2 = Assert.NotNull(s);
    }
}
```

I understand now that this is "old" code that's triggering, not "new" code you're writing.

**Comment by drewnoakes** [comment]
The parameter annotations help in the `Assert.Null` case too:

```
Assert.Null(o);
o.ToString(); // warns
```

---

I tried to update to 2.5.0 today and hit a bunch of warnings from this, so will hold off until the fix is available.

**Comment by bradwilson** [comment]
@drewnoakes Yep, the fix has already been committed.

**Comment by bradwilson** [comment]
I'll push out a pre-release build to NuGet soon, I need to look into a few more things before I do that.
