### ISSUE TITLE
TypeOf check in mock setup

### ISSUE THREAD

**Issue by kryptobi** [xunit/xunit#2753]
if i write a unittest with xunit and setup a mock like this:

```
_service.Setup(ms => ms.method(It.IsAny<List<string>>(), It.IsAny<CancellationToken>())).Returns(Task.FromResult(..));;
```

it will not throw an exception if the methods is implemented in this way:
```
var x  = await method(new[] myList, cancellationToken)
```

the result of the method (of the mock) will be null. 
I prefer to get an exception that the type of array is not parsable to the list.

**Comment by bradwilson** [comment]
We don't control the way your chosen mocking framework works. That's outside of our control.
