### ISSUE TITLE
2.5 Seems to have broken the way Assembly loading works

### ISSUE THREAD

**Issue by gsmeets** [xunit/xunit#2754]
I am using some type scanning to perform a few sanity checks. Up until 2.4.2 this worked fine, but since upgrading to 2.5 I suddenly two thirds of the assemblies that are retrieved via:

```AppDomain.CurrentDomain.GetAssemblies()```

I query some types via these assemblies, and insert them into my theories with a MemberData attribute.

**Comment by bradwilson** [comment]
We did not change anything about assembly loading in 2.5.

**Comment by bradwilson** [comment]
What assemblies that you're expecting are suddenly missing? Can you provide exact repro steps?

**Comment by gsmeets** [comment]
I have a bunch of assemblies with types that implement a certain interface. My tests validate that each of those types is mapped in the application. (It's more a sanity check than an actual unit test.)

It appears that the assemblies that have types are directly used in the test assembly are still loaded, but the rest isn't.

I managed to circumnavigate the issue by adding a static constructor to my helper class that generates the MemberData which scans the dll path and loads the assemblies by hand:

```
var entryAssembly = Assembly.GetEntryAssembly();
var path = Path.GetDirectoryName(entryAssembly.Location);

var assemblies = Directory.GetFiles(path, "*.Abstractions.dll")
.Select(a => Assembly.Load(Path.GetFileNameWithoutExtension(a)))
.ToList();
```

I guess this approach is better, as it doesn't rely on whatever happens to be loaded in the AppDomain at the time of setup. I'll close this issue and leave it here for future reference.

**Comment by bradwilson** [comment]
I just remembered there was a performance optimization that probably caused this.

From https://xunit.net/releases/v2/2.5.0 :

> * Fixed a performance issue with reporter discovery related to scanning every single DLL in your output folder looking for types which implement reporters. Now we only scan libraries named *reporters*.dll which may break any custom reporters you are using from first or third party assemblies without an appropriate name.
