### ISSUE TITLE
Assert.Equals doesn't use the IEqualityComparer

### ISSUE THREAD

**Issue by lucianaparaschivei** [xunit/xunit#2757]
Experienced this issue with xunit version 2.5.0. It is working as expected in version 2.4.2.

Passing a custom IEqualityComparer does not work as expected in 2.5.0. 
`Assert.Equal(expected, actual, SetEqualityComparer<int>.Default);`
When code is executed in version 2.5 the breakpoint is not hit in SetEqualityComparer and also the assert would use the default list comparer.

the object we are comparing are
public class TopologicalOrdering<T> : List<TopologicalGeneration<T>>
    where T : IEquatable<T>

public class TopologicalGeneration<T> : HashSet<T>

**Comment by bradwilson** [comment]
Dup #2743
