### ISSUE TITLE
Assert.Equivalent failed when there's a Tuple member of the same class type

### ISSUE THREAD

**Issue by vkairy** [xunit/xunit#2758]
Assert.Equivalent seems to not handle properly when using a Tuple of the same class type.
Below you can see a minimum sample reproducing the problem.

Environment:

- C# Console App
- .Net 7
- xUnit 2.5.0

```csharp
using System;
using Xunit;
					
public class Program
{
	class Person {
		public Guid Id { get; set; }
		public string Name { get; set; }
		public int Age { get; set; }
		public (Person Mother, Person Father) Parents { get; set; }
	}
	
	public static void Main() {
		Person p1 = new() {
			Id = Guid.NewGuid(),
			Name = "Person #1",
			Age = 30,
			Parents = (new() {
				Id = Guid.NewGuid(),
				Name = "Parent #1",
				Age = 60,
			}, new() {
				Id = Guid.NewGuid(),
				Name = "Parent #2",
				Age = 63,
			})
		};

		Person p2 = new() {
			Id = p1.Id,
			Name = "Person #1",
			Age = 30,
			Parents = (new() {
				Id = p1.Parents.Mother.Id,
				Name = "Parent #1",
				Age = 60,
			}, new() {
				Id = p1.Parents.Father.Id,
				Name = "Parent #2",
				Age = 63,
			})
		};

		Assert.Equivalent(new Person(), new Person()); // Assertion succeeded
		Assert.Equivalent(p1, p2);                     // Assertion failed
	}
}
```
Failure message:
 
> Unhandled exception. Xunit.Sdk.EquivalentException: Assert.Equivalent() Failure: Mismatched value on member 'Parents'
> Expected: Tuple (Person { Age = 60, Id = 8771e6b9-5235-4486-8866-d07622504464, Name = "Parent #1", Parents = Tuple (null, null) }, Person { Age = 63, Id = e597d774-01fd-42a9-8ecc-21bc489d761b, Name = "Parent #2", Parents = Tuple (null, null) })
> Actual:   Tuple (Person { Age = 60, Id = 8771e6b9-5235-4486-8866-d07622504464, Name = "Parent #1", Parents = Tuple (null, null) }, Person { Age = 63, Id = e597d774-01fd-42a9-8ecc-21bc489d761b, Name = "Parent #2", Parents = Tuple (null, null) })
>    at Xunit.Assert.Equivalent(Object expected, Object actual, Boolean strict) in /_/src/xunit.assert/Asserts/EquivalenceAsserts.cs:line 41
>    at Program.Main()
> Command terminated by signal 6

Notice: The result is the same if using `strict:true`.

**Comment by bradwilson** [comment]
In v2: `2.5.1-pre.10`
In v3: `0.1.1-pre.265`
