### ISSUE TITLE
DisableTestParallelization = true does not stop tests executing in parallel

### ISSUE THREAD

**Issue by rawling** [xunit/xunit#276]
I have a number of test classes that share a database very poorly, via a shared `IDisposable` base class; if the tests run in parallel, they fail because the shared state can't be shared.

Adding `[assembly: CollectionBehavior(CollectionBehavior.CollectionPerAssembly)]` to the assembly's AssemblyInfo makes the tests run sequentially (they're all in the same assembly) and all pass.

However, if I instead use `[assembly: CollectionBehavior(DisableTestParallelization = true)]` it does not work; the tests still run in parallel to some extent and fail.

I can replicate this with a very simple analogue. For the shared state, something along the lines of

    public class SharedState : IDisposable
    {
        private static readonly object sync = new object();
        protected static int Instances;

        public SharedState()
        {
            lock (sync)
            {
                Instances++;
                File.AppendAllLines("testlog.txt", new [] { string.Format("{0,2} {1,3} {2}", Instances, "in", this.GetType())});
            }
        }

        public void Dispose()
        {
            lock (sync)
            {
                Instances--;
                File.AppendAllLines("testlog.txt", new[] { string.Format("{0,2} {1,3} {2}", Instances, "out", this.GetType()) });
            }
        }
    }

and then for the tests, ten test classes with ten test methods each along these lines:

    public class Class1 : SharedState
    {
        [Fact]
        public void Test1()
        {
            Assert.Equal(1, Instances);
        }
        ... 9 more of these
    }

This results in many test failures, and a log file like

    1  in MyTestLibrary.Class1
    2  in MyTestLibrary.Class10
    1 out MyTestLibrary.Class10
    2  in MyTestLibrary.Class10
    1 out MyTestLibrary.Class1
    0 out MyTestLibrary.Class10

showing that the tests are executing in parallel.

If I additionally log the `ManagedThreadId` of the thread used on each test, I get two distinct thread IDs on my two-core system.

Have I misunderstood this attribute or is it not working?

**Comment by wholroyd** [comment]
This was the same issue brought up under #244 but we probably didn't explain it as well as @rawling.

I've looked at the code around where DisableTestParallelization is supposed to be honored and see how it's handled differently, but it seems there is something with the way it's done that is escaping us where parallelism remains. In my opinion the DisableTestParallelization option (as far as how people expect it to work) should have the same effect as doing MaxParallelThreads = 1.

**Comment by bradwilson** [comment]
Your problem isn't parallelization, it's that Shims is not compatible with the TPL, and xUnit.net uses the TPL extensively, even when tests aren't being run in parallel.

This is an architectural decision that is not changing. You should continue to use MaxParallelThreads=1 in your situation to ensure that the TPL tasks are pinned to a single thread (and log a bug against Shims to make them TPL-compatible).

**Comment by wholroyd** [comment]
To remove any confusion, I never repro'd with the Fakes framework, I just had a basic project using shared state on a static variable almost exactly like @rawling posted above (but without a lock) to help show it could happen without even using Fakes.

I reran the repro project I put up for #244 and it appears to work as I would expect with DisableTestParallelization set to true. I can't speak for the Fakes framework, but at least the weirdness I was seeing is gone as of this change. So it's all good now. Thanks Brad! :D
