### ISSUE TITLE
[Feature] Inline data with objects

### ISSUE THREAD

**Issue by virzak** [xunit/xunit#2760]
I have a method with a bunch of `[InlineData]` attributes. I need to pass `DateTime` object, so I must use `[ClassData]`

In my project I introduced `InlineObjectDataAttribute` and I was wondering if you'd take a PR with this class.

```cs
public class InlineObjectDataAttribute<T> : ClassDataAttribute where T : IInlineObjects
{
    public InlineObjectDataAttribute() : base(typeof(GenericTestData)) { }

    class GenericTestData : IEnumerable<object?[]>
    {
        public IEnumerator<object?[]> GetEnumerator()
        {
            foreach (var item in T.GetObjects())
            {
                yield return item;
            }
        }

        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
    }
}

public interface IInlineObjects
{
    static abstract IEnumerable<object?[]> GetObjects();
    static object?[] Line(params object?[] data) => data;
}
```

The usage would be:

```cs
using static IInlineObjects;

class MyTestClass : IInlineObjects
{
    public static IEnumerable<object?[]> GetObjects() => new object?[][]
    {
        Line(180d, new DateTime(2000, 1, 1, 6, 0, 0)),
    };
}

[Theory]
[InlineObjectData<MyTestClass>]
public void TestMethod(object o1, object o2)
```

**Comment by bartelink** [comment]
I tend to address this sort of thing with a mix of a) `MemberData` (to avoid needing a class) and b) TheoryData (to strong type things and avoid getting into directly touching `object?[]` and the like)
https://andrewlock.net/creating-parameterised-tests-in-xunit-with-inlinedata-classdata-and-memberdata/
https://andrewlock.net/creating-strongly-typed-xunit-theory-test-data-with-theorydata/#using-theorydata-with-the-classdata-attribute
Is there no way you can use TheoryData for your requirements?

**Comment by bradwilson** [comment]
I'm in agreement with @bartelink that TheoryData is your strongly typed friend. 😄

**Comment by virzak** [comment]
Thanks. I switched to https://github.com/davidwengier/Xunit.SerializedTheoryData. So far so good.
