### ISSUE TITLE
Assert.Contains() changed behavior for nested collections in 2.5.0

### ISSUE THREAD

**Issue by FlorianHockmann** [xunit/xunit#2763]
Updating to 2.5.0 lets some of our tests fail which use `Assert.Contains()` with a collection that should be found in another collection. This minimal example demonstrates what I'm talking about:

```c#
var toBeFound = new List<object> { 1 };
var collectionToCheck = new List<object> { new List<object> { 1 } };
            
Assert.Contains(toBeFound, collectionToCheck);
```

This works in 2.4.2, but fails in version 2.5.0:

```c#
Xunit.Sdk.ContainsException
Assert.Contains() Failure: Item not found in collection
Collection: [[1]]
Not found:  [1]
```

and I'm not sure if that was an intended change in that version as the only item I can find in the release notes that seems somehow related is: #2671. But that issue specifically addresses `IHashSet<>` and `IDictionary<>` so I think it should not be relevant here.

It would be good to know whether this change was intentional as we can then probably work with it by providing a custom comparer, or whether this wasn't intended and will be changed back in a future release.

**Comment by bradwilson** [comment]
Verified already fixed in 2.5.1 prerelease builds.
