### ISSUE TITLE
issue in nuget.config

### ISSUE THREAD

**Issue by CoderOnWinks** [xunit/xunit#2768]
In 2.4.1 version: nuget.config has this url "https://www.myget.org/F/b4ff5f68eccf4f6bbfed74f055f88d8f/api/v3/index.json". It simply gives error and not opens the json. Has anyone faced this issue in building xunit 2.4.1 version.

**Comment by CoderOnWinks** [comment]
I am building xunit 2.4.1 version from source code. While i do that there are some nuget errors like attached file. I see a nuget.config file in the source code folder and one of the url in that doesnt resolve. I am suscpecting due to this we are getting error as some packages are not resolved/download. 
![MicrosoftTeams-image](https://github.com/xunit/xunit/assets/24753678/c1731255-11c3-4019-bb63-d70f06848490)

**Comment by bartelink** [comment]
Ah, I've never tried to build myself
Looking at the history of https://github.com/xunit/xunit/commits/main/NuGet.Config it no longer refers to myget, so the chances are that this resource is simply defunct
Any reason you're not building latest?
Again, we're working indirectly - your objective is still not clear - http://xyproblem.info

**Comment by CoderOnWinks** [comment]
@bartelink : We are using some legacy code where xunit 2.4.1 is used. For now we cant change the version.

**Comment by bartelink** [comment]
Well, not sure anyone can help you if that's a hard constraint

But, I would venture that xunit 2.5.x
a) should compile
b) runs anything that 2.4.1 can run

**Comment by bradwilson** [comment]
The MyGet feeds which were used to build xUnit.net 2.4.1 no longer exist. If I were to need to patch 2.4.1 for some reason, I'd need to push a branch up to use the new feed(s) and package version(s) that would make it work.

**Comment by bradwilson** [comment]
I've created two new branches with updated NuGet.config files (and fixing the version of the TestDriven.Framework package, which is what was being pulled from the now-dead feed).

https://github.com/xunit/xunit/tree/v2.4.1
https://github.com/xunit/xunit/tree/v2.4.2

If you need to build 2.4.1 or 2.4.2, you should start from here instead of the tags (which will no longer build).
