### ISSUE TITLE
Resources leak

### ISSUE THREAD

**Issue by Vasil20Angelov** [xunit/xunit#2769]
Xunit and Xunit.Runner.VisualStudio v2.5.0
Visual studio v17.7.2
.NET 6

In some of my tests constructors i create an object which starts a Microsoft.Office.Interop.Excel.Application. My test classes implement IDisposable and the excel is actually closing. Looking at the task manager while debuging a test i see the following: Excel process started -> test executed -> process killed, which is as expected. The strange part begins after the whole test running process is over. Then many excel processes appear and their number is not a random number. In fact let's say i have a Test project with 3 test classes each containing 5 tests. In 2 of the test classes i start the excel process in the constructor. Whenever i run a test from this test project, in the end i will have 10 excel processes running, even if i run only a single test that does not create an excel process! Deleting a test from these that start the excel and running again 1 that does not start it will end up with 9 excel processes. Debugging these tests never actually goes to the line of code where the excel is started.

**Comment by bradwilson** [comment]
Please provide a repro project that illustrates this, as I will not be able to guess what's going on here just based on your description.

**Comment by bradwilson** [comment]
Closing due to age. Please open a new issue with a repro project if this is still occurring.
