### ISSUE TITLE
xunit.runner.utility is still referencing NetStandard.Library 1.6.0

### ISSUE THREAD

**Issue by Cosifne** [xunit/xunit#2778]
https://www.nuget.org/packages/xunit.runner.utility/2.5.1-pre.33#dependencies-body-tab

xunit.runner.utility is referencing NetStandard.Library 1.6.0, which is referencing System.Net.Http 4.1.0.
This is causing Component check failure in the Azure build pipeline, because System.Net.Http 4.1.0 has vulnerability issue.

**Comment by bartelink** [comment]
>Component check failure in the Azure build pipeline

Can said check be configured to ignore this on the basis that the dependency only signals a minimum version for System.Net.Http? (What is the checker; do they have a suggestion of a workaround or way to suppress this?)

As a workaround: Does adding an explicit reference to a newer version to the test assembly supress the error?

(Ultimately the runner is trying to take a minimal dependency / make minimal assumptions of it's environment; it doesn't actually use `System.Net.Http`)

**Comment by Cosifne** [comment]
> > Component check failure in the Azure build pipeline
> 
> Can said check be configured to ignore this on the basis that the dependency only signals a minimum version for System.Net.Http? (What is the checker; do they have a suggestion of a workaround or way to suppress this?)
> 
> As a workaround: Does adding an explicit reference to a newer version to the test assembly supress the error?
> 
> (Ultimately the runner is trying to take a minimal dependency / make minimal assumptions of it's environment; it doesn't actually use `System.Net.Http`)

Yes add that package explicitly is temp OK for us. But you can imagine we just need to add this whenever xunit is used. Is that possible to update that to .NETStandard 2.0?

**Comment by bartelink** [comment]
The primary recommendation has to be to stop scanning test assemblies - they should never touch production servers or go into installer packages. As such, the degree to which runners, test implementations, and test support libraries need to be correct from a security point of view is a different equation to how production software should be assessed (it'll also reduce scanning time)

----

> Is that possible to update that to .NETStandard 2.0?

I think there may be a little confusion here. Supporting the `netstandard 2.0` TFM is a different matter.

While it seems [that supporting `netstandard2.0` is a recommended policy](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-1-6#which-net-standard-version-to-target), my question would be whether that will silence your scanner. Can you do some more research as to whether having `xunit.runner.utility` support `netstandard2.0` is actually going to solve any problems?

OK; on to the actual question of what can be done. For some TFM variants in the package, there's a reference to `NetStandard.Library` (v `>=` 1.6.0). It does seem that updating the `NETStandard.Library` reference to [2.0.3 ](https://www.nuget.org/packages/NETStandard.Library/2.0.3) would make it pass the scan in terms of the transitive dependency of `System.Net.Http`. The concern would be, but for a package used this widely, are whether there are negative effects that make that untenable. A quick search only found me https://github.com/dotnet/sdk/issues/2261 which doesn't make any clearer for me.

It'll help the maintainers a lot if you can do some more research and report back with as much information as possible regarding the scanning process you are using, and what's going to ne necessary to placate it.

**Comment by bradwilson** [comment]
Closing as duplicate of #2724, #2294, #1951, and I'm sure others I've missed or forgotten about.

> Is that possible to update that to .NETStandard 2.0?

The changes required to make this work are **_EXTENSIVE_**. I've already done them for v3 and the work to back-port them to v2 is time I will not invest. In just one example, it would involve moving the minimum .NET Framework version to 4.7.2, because prior versions are not fully compatible with .NET Standard 2.0.

We previously tried to [add support for `netstandard2.0`](https://github.com/xunit/xunit/commit/30e98e1fa8f2ac184c8df9d1f57f791768b0014c) in 2.4.0 and we had to [roll it back almost immediately](https://github.com/xunit/xunit/commit/be452a200ea2f8fc189eded722d43bae1a37ce23) because of [user issues](https://xunit.net/releases/v2/2.4.1-pre.build.4071).
