### ISSUE TITLE
Update xUnit1030 to not flag .ConfigureAwait(true)

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#2779]
For users who have enabled [CA2007](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2007) (not recommended in xUnit.net test projects), the analyzer should not trigger if they have opted to use `.ConfigureAwait(true)`.

Workaround until this is implemented: add a `.editorconfig` file to the root folder of your test project(s) that disables CA2007. This will override any global enablement of CA2007:

```ini
[*.cs]
dotnet_diagnostic.CA2007.severity = none
```

See: https://github.com/xunit/xunit/issues/2628#issuecomment-1724283768

**Comment by JuanZamudioGBM** [comment]
Using the SDK 6.0.414 with CA2007 enable in VS 17.7.4 still throws a warning using `.ConfigureAwait(true);`

**Comment by bradwilson** [comment]
@JuanZamudioGBM Thanks for looking into that. Sounds like this is an impossible feature if so.

**Comment by bradwilson** [comment]
@JuanZamudioGBM That hasn't been my experience:

![image](https://github.com/xunit/xunit/assets/16944/e622de4c-5965-45e6-87f8-cbe5450151dc)

![image](https://github.com/xunit/xunit/assets/16944/f05ff9cd-3076-46c2-9a69-15455be6782e)

**Comment by JuanZamudioGBM** [comment]
Well, I don't know what is wrong with my setup then, it fails with 6.0.414 and 7.0.401

![image](https://github.com/xunit/xunit/assets/28072896/66ea29cd-3092-4703-b73f-540e349009b7)

**Comment by bradwilson** [comment]
@JuanZamudioGBM That's not CA2007, that's xUnit1030, and what you're seeing is the point of this bug. 😄

**Comment by JuanZamudioGBM** [comment]
lol, I misunderstood you then, I thought that with .ConfigureAwait(true); CA2007 and xUnit1030 will not trigger.

Thanks for your time

**Comment by bradwilson** [comment]
Available in `1.4.0-pre.2`.
