### ISSUE TITLE
Add overload of Assert.Equal(IEnumerable) that ignores sequence of items

### ISSUE THREAD

**Issue by feO2x** [xunit/xunit#278]
In some of my tests, I would like to check if a collection contains the correct items. I therefore create another collection but I don't know the correct order of the items when I write the test. Unfortunately the current `Assert.Equal(IEnumerable)` implementation checks the order of the items.

Thus I would like to have an overload that could look like 

```csharp
Assert.Equal(expectedCollection, actualCollection, Compare.IgnoringItemSequence);
```
where the additional parameter can be used to specifiy the compare strategy. The exception that could be thrown by this method should include the items that are in expectedCollection and not in actualCollection (and vice versa). This would really help with defect localization as one does not have to debug the test to find out which items are missing (or abundant).

I read that you have thought about this before (https://xunit.codeplex.com/workitem/9870 and probably https://github.com/xunit/xunit/issues/26) but what do you think about this? I would try to contribute this functionality to xunit.

**Comment by bradwilson** [comment]
When we discussed this, we decided that the correct behavior when you don't know the order of results is to put them into a predictable order (using LINQ's `OrderBy` method).

**Comment by feO2x** [comment]
Ok, I will add the corresponding method to my own framework and close this issue. Thank you.

**Comment by fakhrulhilal** [comment]
> 
> 
> When we discussed this, we decided that the correct behavior when you don't know the order of results is to put them into a predictable order (using LINQ's `OrderBy` method).

This is common assertion that I use. In NUnit, I can use [equivalent constraint](https://docs.nunit.org/articles/nunit/writing-tests/constraints/CollectionEquivalentConstraint.html). I expect to have that in xUnit. I can use workaround for collection of simple type (eg: string, numbers, etc) by ordering them before asserting. But not sure for complex object.

**Comment by bradwilson** [comment]
@fakhrulhilal `Assert.Equivalent` is a feature slated for v3: https://github.com/xunit/xunit/issues/1604

**Comment by fakhrulhilal** [comment]
> 
> 
> @fakhrulhilal `Assert.Equivalent` is a feature slated for v3: #1604

Glad we have plan for that, even though I have to wait for years. Appreciate for your time given to community.

**Comment by bradwilson** [comment]
The v3 assertions library is available now as a pre-release CI build on [MyGet](https://myget.org/feed/xunit/package/nuget/xunit.v3.assert), that works with the v2 framework (except for `Assert.SkipXxx`; those require v3 framework updates).
