### ISSUE TITLE
Tests results are not reported in the TeamCity

### ISSUE THREAD

**Issue by maxcherednik** [xunit/xunit#2782]
After upgrading from 2.5.0 to 2.5.1 tests are not reported any more. 

![image](https://github.com/xunit/xunit/assets/4208513/a163c163-ba5e-4b3c-9575-0a8d40ef34f6)

**Comment by bradwilson** [comment]
Duplicate of https://github.com/xunit/visualstudio.xunit/issues/384

**Comment by csMACnz** [comment]
@maxcherednik I've verified the fix for this in 2.5.2-pre.3 works, so you should be good to skip 2.5.1 and jump to 2.5.2 when it drops.
