### ISSUE TITLE
Xunit.runner.visualstudio 2.5.1 TeamCity no test result

### ISSUE THREAD

**Issue by BenBorn** [xunit/xunit#2785]
We updated our xunit version from:
- xunit 2.4.2 to 2.5.1
- xunit.runner.visualstudio 2.4.5 to 2.5.1
If we run the test under TeamCity with _dotnet test --logger:"console;verbosity=detailed"_ we get no test results
If we downgrad the xunit.runner.visualstudio to 2.5.0 we get the results in teamcity

**Comment by bradwilson** [comment]
Duplicate: https://github.com/xunit/visualstudio.xunit/issues/384
