### ISSUE TITLE
Problem with RC1

### ISSUE THREAD

**Issue by kentcb** [xunit/xunit#279]
When attempting to add xunit package within Xamarin Studio fails with:

> Adding xunit...
> Attempting to resolve dependency 'xunit.core (= 2.0.0-rc1-build2826)'.
> Downloading xunit.core 2.0.0-rc1-build2826...
> 'xunit.core' already has a dependency defined for 'xunit.extensibility.core'.

**Comment by rawling** [comment]
If Xamarin Studio uses NuGet, you need to update nuGet.

**Comment by bradwilson** [comment]
Yeah, that's what NuGet says when it doesn't understand some of the target platforms (in this case, the ASP.NET platforms). Updating NuGet will fix the issue.

**Comment by kentcb** [comment]
Thanks - I might need to raise this with Xamarin because my tooling is all up to date.

Which version of NuGet would fix this? According to Xamarin Studio, it's using V2.8.1.

**Comment by bradwilson** [comment]
It needs to be 2.8.3 or later.

http://docs.nuget.org/release-notes/nuget-2.8.3

**Comment by kentcb** [comment]
Thanks Brad. For those following in my footsteps: https://bugzilla.xamarin.com/show_bug.cgi?id=26611

**Comment by kentcb** [comment]
Note from Matt Ward on Xamarin's bugzilla:

> On xunit side it might make sense for the xunit.core NuGet package to indicate
that it only supports NuGet 2.8.3 since that would report a better error
message than the error "'xunit.core' already has a dependency defined for
'xunit.extensibility.core'.". Currently xunit.core declares it is compatible
with NuGet 2.5 or above in its .nuspec file

**Comment by bradwilson** [comment]
Yep, I've updated the NUSPEC files. Unfortunately, I didn't discover this version dependency until we'd shipped RC1. The dependency should be properly surfaced for RC2.
