### ISSUE TITLE
Vulnerable packages installed warning in 17.80 Preview 2.0 

### ISSUE THREAD

**Issue by RPossberg** [xunit/xunit#2790]
I keep getting You have 2 vulnerable package versions installed warning when trying to install or update xUnit. This happens with any version I try to use in Studio Developer 17.8 Preview 2.0, but no problem in VS Community 2022 17.7.4

**Comment by bradwilson** [comment]
What package?

(If the answer is `System.Net.Http`, or any other package that we don't explicitly reference but instead come through .NET Standard, then I will close this issue as Won't Fix, like I have a half dozen times already.)

**Comment by RPossberg** [comment]
Hi Brad,
I'm a student so have only just started with test development, but here are the package references I have installed in both versions of Studio:
  <ItemGroup>
    <PackageReference Include="coverlet.msbuild" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.7.2" />
    <PackageReference Include="coverlet.collector" Version="6.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="xunit" Version="2.5.2-pre.2" />
    <PackageReference Include="xunit.analyzers" Version="1.3.0" />
    <PackageReference Include="xunit.assert" Version="2.5.2-pre.2" />
    <PackageReference Include="xunit.core" Version="2.5.2-pre.2" />
  </ItemGroup>

I hope this helps.
Thanks

**Comment by RPossberg** [comment]
Looks like I was missing the Standard Library. Thank you.
