### ISSUE TITLE
Fact with arguments causes SerializationException during VS discovery

### ISSUE THREAD

**Issue by rawling** [xunit/xunit#280]
If I make a Fact with an argument

    [Fact]
    public void FactWithAnArgument(int argument)
    {
    }

I get the message

> Error creating Visual Studio test case for MyTestLibrary.Class1.FactWithAnArgument: System.Runtime.Serialization.SerializationException: Type 'Xunit.Sdk.LambdaTestCase' in Assembly 'xunit.execution.desktop, Version=2.0.0.2826, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' is not marked as serializable.

in the Test output pane.

It would be better if either:

- this caused a more-obvious exception ("you can't do that") to end up in the Tests output panel, or
- this produced a test that can still be discovered, serialized, run and failed

**Comment by bradwilson** [comment]
Yep, the LambdaTestCase would've given you the better error, had it been properly serializable. :-p I'll make sure this gets fixed in the next drop.
