### ISSUE TITLE
Assert.Equal for sets and a custom Func comparer throws NotImplementedException

### ISSUE THREAD

**Issue by AndriySvyryd** [xunit/xunit#2804]
```C#
[Fact]
public void Test()
{
    Assert.Equal(new HashSet<int> { 1 }, new HashSet<int> { 1 }, AreEqual);

    static bool AreEqual(int x, int y) => true;
}
```
throws
>  Message: 
    System.NotImplementedException : The method or operation is not implemented.
  Stack Trace: 
    HashSet`1.AddIfNotPresent(T value, Int32& location)
    HashSet`1.UnionWith(IEnumerable`1 other)
    HashSet`1.ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
    RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
    MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)

Surprisingly, this doesn't throw:

```C#
[Fact]
public void Test()
{
    Assert.Equal(new HashSet<int> { 1 }, new HashSet<int> { 1 }, (x, y) => true);
}
```
V2.5.3

**Comment by bradwilson** [comment]
Available in v2: `2.5.4-pre.7`
Available in v3: `0.1.1-pre.301`
