### ISSUE TITLE
CS0121 compiler error with C# 12 collection expressions for Assert.Equal(T[], T[])

### ISSUE THREAD

**Issue by martincostello** [xunit/xunit#2812]
With xunit 2.6.1 when using C# 12 collection expressions, CS0121 compiler errors occur when using code similar to the following:

```csharp
[Fact]
public static void CS0121()
{
    int[] actual = [1, 2, 3]; // Assume this value would come from the code being tested
    Assert.Equal([1, 2, 3], actual);
}
```

```text
CS0121 The call is ambiguous between the following methods or properties: 'Assert.Equal<T>(T[], T[])' and 'Assert.Equal<T>(ReadOnlySpan<T>, Span<T>)'
```

This can be worked around by using the previous syntax to create a literal array, but this generates an IDE0300 analyser suggestion in Visual Studio to change it back to a collection expression.

```csharp
[Fact]
public static void No_CS0121()
{
    int[] actual = [1, 2, 3];
    Assert.Equal(new[] { 1, 2, 3 }, actual);
}
```

```text
IDE0300	Collection initialization can be simplified
```

Otherwise, the workaround is to assign the expected value to a variable:

```csharp
[Fact]
public static void Also_No_CS0121()
{
    int[] actual = [1, 2, 3];
    int[] expected = [1, 2, 3];
    Assert.Equal(expected, actual);
}

```

This issue is similar to #2811, so this might be a duplicate of that, but I only ran into this after updating existing tests to use C# 12 and adopting collection expressions.

**Comment by bradwilson** [comment]
Unfortunately there will always be cases of compiler ambiguity given the number of overloads the `Assert.Equal` has. Removing some of those overloads is not really an option.
