### ISSUE TITLE
Using Assert.Equal to compare arrays in VB.NET fails to compile with BC30649 '' is an unsupported type

### ISSUE THREAD

**Issue by reduckted** [xunit/xunit#2813]
Using xUnit 2.6.0 or 2.6.1. Previously worked with 2.5.3.

In VB.NET, comparing two arrays using `Assert.Equal` fails to compile.

```vb
Public Class Testing

    <Fact()>
    Public Sub CompareArrays()
        Dim a() As Integer
        Dim b() As Integer

        a = {1, 2, 3}
        b = {1, 2, 3}

        Assert.Equal(a, b)
      ' ~~~~~~~~~~~~~~~~~~ BC30649	'' is an unsupported type.
    End Sub

End Class
```

**Comment by reduckted** [comment]
@bartelink I'm not sure. There might be some relation between the issues, but in #2812, the equivalent C# code to this issue works fine.

```cs
[Fact]
public static void Also_No_CS0121()
{
    int[] actual = [1, 2, 3];
    int[] expected = [1, 2, 3];
    Assert.Equal(expected, actual);
}
```

**Comment by reduckted** [comment]
It first started occurring after a6b5cc4a9c218a8f063807f233dcdaeb28572d00: `Add net6.0 binary to xunit.assert`.

**Comment by reduckted** [comment]
If I'm not mistaken, that commit enabled the `XUNIT_SPAN` constant, which resulted in this overload being available:

https://github.com/xunit/assert.xunit/blob/3bb3309722867df337161527182683b3adf32413/EqualityAsserts.cs#L34-L66

```cs
public static void Equal<T>(
#if XUNIT_NULLABLE
    [AllowNull] T[] expected,
    [AllowNull] T[] actual)
        where T : unmanaged, IEquatable<T>
```

I'm reasonably confident that it's the `unmanaged` type constraint that VB doesn't like.

There's a workaround. Force the `IEnumerable<T>` overload to be used by adding `.AsEnumerable()` to either argument:

```vb
Public Class Testing

    <Fact()>
    Public Sub CompareArrays()
        Dim a() As Integer
        Dim b() As Integer

        a = {1, 2, 3}
        b = {1, 2, 3}

        Assert.Equal(a.AsEnumerable(), b)
        ' or
        Assert.Equal(a, b.AsEnumerable())
    End Sub

End Class
```

**Comment by bradwilson** [comment]
Unfortunately compiler ambiguities are out of our control.

Further, if the issue is specific to VB and not a general ambiguity issue, it's not a language that we explicitly support (we only officially support C# and F#). It does usually work, and if workarounds can be provided by a third party PR, we will consider them, but we don't fix them ourselves.

**Comment by reduckted** [comment]
Yeah, that's fair enough. Plus, the workaround is easy to apply, so it doesn't seem worth trying to fix this.

> it's not a language that we explicitly support (we only officially support C# and F#)

Should the readme be updated then?
https://github.com/xunit/xunit/blob/b9a547c24d4b7486c55988c435234d7dda890eca/README.md?plain=1#L5

**Comment by bradwilson** [comment]
> Should the readme be updated then?

Good point! I will update it now.
