### ISSUE TITLE
[Feature request] Tests with supported platform attributes

### ISSUE THREAD

**Issue by sliekens** [xunit/xunit#2820]
Hi,

.NET 5 added a new platform compatibility analyzer, and along with it, new attributes to use in library code:

- [SupportedOSPlatformAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.versioning.supportedosplatformattribute)
- [UnsupportedOSPlatformAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.versioning.unsupportedosplatformattribute)

I'm using this for example to annotate code that only works on Windows. I have tests for this code, but right now I don't really have a good way to skip these tests when running in Linux.

![image](https://github.com/xunit/xunit/assets/1583241/8b5c15c8-a3b9-43bf-a332-53991e15e5b5)

It would be **super** cool if you could annotate a Fact with a platform compatibility attribute, such that the runner will dynamically skip it on unsupported platforms.

![image](https://github.com/xunit/xunit/assets/1583241/d0ec7630-0a91-4d8e-b7ab-0e8368a031ad)

Thanks for your consideration.

**Comment by bradwilson** [comment]
In v3, we have added `Assert.Skip` and friends, which can do this at runtime. An example from our tests:

https://github.com/xunit/xunit/blob/379140a5a89e1ede8c675e8c0ef93c83ac208dd9/src/xunit.v3.core.tests/Acceptance/DynamicAssemblyAcceptanceTests.cs#L21-L25

We do not have `Assert.Skip` in v2.

-----

We are unlikely to provide this as a standalone attribute, even in the context of v3, for the same reason that we rejected the common `[ExpectedException]` from NUnit/MSTest.

We do have an open discussion issue on whether we should add the ability to do `SkipWhen` or `SkipUnless` in the `[Fact]` attribute, which would need to point to a static field/property to get the runtime decision on skipping or not.

**Comment by bradwilson** [comment]
Skimming through the documentation for this attribute, this doesn't actually feel like a runtime request, and I don't think you need us to do anything here.

Instead, it feels to me like what you should be doing is multi-targeting your test projects with a generic TFMs (like `net5.0`) as well as any OS-specific TFMs (like `net5.0-linux`, `net5.0-windows`, etc.), and then using blocks around Windows-specific tests like `#if WINDOWS`.

I'll admit that the documentation I've found here so far is terrible when trying to determine what the actual platforms are and what pre-processor directives might exist for those platforms by default, so my suggestion here may be wrong, but I think it should set you in the right direction.

**Comment by bradwilson** [comment]
Yeah, this seemed to do be functional right now.

Project:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net6.0-windows</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.7.2" />
    <PackageReference Include="xunit" Version="2.6.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

</Project>
```

Unit test:

```csharp
using System.Runtime.Versioning;
using Xunit;

namespace Empty;

public static class MyMath
{
	[SupportedOSPlatform("windows")]
	public static int Add(int x, int y) => x + y;

	public static int Subtract(int x, int y) => x - y;
}

public class UnitTest
{
#if WINDOWS
	[Fact]
	public void TestAdd()
	{
		Assert.Equal(5, MyMath.Add(3, 2));
	}
#endif

	[Fact]
	public void TestSubtract()
	{
		Assert.Equal(1, MyMath.Subtract(3, 2));
	}
}
```

Running `dotnet test` on Windows:

```
  Determining projects to restore...
  All projects are up-to-date for restore.
  empty -> C:\Dev\repro\empty\bin\Debug\net6.0\empty.dll
  empty -> C:\Dev\repro\empty\bin\Debug\net6.0-windows\empty.dll
Test run for C:\Dev\repro\empty\bin\Debug\net6.0\empty.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.7.2 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: < 1 ms - empty.dll (net6.0)
Test run for C:\Dev\repro\empty\bin\Debug\net6.0-windows\empty.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.7.2 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     2, Skipped:     0, Total:     2, Duration: 2 ms - empty.dll (net6.0)
```

You can see we have 1 successful test from `net6.0` and 2 successful tests from `net6.0-windows`. You will have to selectively run only the TFMs that are appropriate at runtime with your build scripts, as in my experiment running `dotnet test` on Linux happily built & ran the `net6.0-windows` version (and of course it passed, because I didn't actually use any Windows-specific APIs, but I would assume it would fail in real usage).

_(When I tried to use `net6.0-linux` it complained that `linux` isn't a valid target platform identifier. I'm not sure where these lists come from at this point in time.)_

**Comment by sliekens** [comment]
RE:
> (When I tried to use `net6.0-linux` it complained that `linux` isn't a valid target platform identifier. I'm not sure where these lists come from at this point in time.)

I found this note from the TFM design

> **Why is there no TFM for Linux?**
>
> The primary reason for OS specific TFMs is to vary API surface, not for varying behavior. RIDs allow varying behavior and have support for various Linux flavors. Specifically, TFMs aren't (primarily) meant to allow calling P/Invokes under #if, most of the time that should be done by doing runtime checks or by using RIDs. The primary reason for a TFM is to exclude large amounts of managed representations for OS technologies (WinForms, WPF, Apple's NS APIs, Android etc).
>
> Also, Android, iOS, macOS, and Windows share that they offer a stable ABI so that exchanging binaries makes sense. Linux is too generic of a concept for that, it's basically just the kernel, which again boils down to the only thing you can do is calling P/Invokes.
> https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md#why-is-there-no-tfm-for-linux

With that in mind, I don't think OS specific TFMs were intended for this, because conditionally including tests falls into the _varying behavior_ bucket.

I'm still looking at what they mean by "using RIDs". The RID catalog does include linux targets.
https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.NETCore.Platforms/readme.md

**Comment by sliekens** [comment]
I hacked together a solution by pushing behavior into a custom `FactAttribute` (that always feels a bit wrong to me):

Project:

``` xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
```

The custom `FactAttribute`:

``` cs
using System.Runtime.InteropServices;

namespace OSPlatformFact;

public sealed class OSPlatformFactAttribute : FactAttribute
{
    public OSPlatformFactAttribute(string platformName)
    {
        if (!RuntimeInformation.IsOSPlatform(OSPlatform.Create(platformName)))
        {
            Skip = $"Test requires {platformName}";
        }
    }
}
```

Tests which use both the platform compatibility analyzer attributes as well as my custom Fact attribute:

``` cs
using System.Runtime.Versioning;

namespace OSPlatformFact;

public static class MyMath
{
    [SupportedOSPlatform("windows")]
    public static int Add(int x, int y) => x + y;

    [SupportedOSPlatform("linux")]
    public static int Multiply(int x, int y) => x * y;

    public static int Subtract(int x, int y) => x - y;
}


[SupportedOSPlatform("windows")]
public class WindowsMathTests
{
    [OSPlatformFact("windows")]
    public void Test_only_on_windows()
    {
        Assert.Equal(5, MyMath.Add(3, 2));
    }
}

[SupportedOSPlatform("linux")]
public class LinuxMathTests
{
    [OSPlatformFact("linux")]
    public void Test_only_on_linux()
    {
        Assert.Equal(6, MyMath.Multiply(3, 2));
    }
}

public class MathTests
{
    [Fact]
    public void Test_on_all_platforms()
    {
        Assert.Equal(1, MyMath.Subtract(3, 2));
    }
}
```

Output of `dotnet test` on Windows:

``` text
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.12]     OSPlatformFact.LinuxMathTests.Test_only_on_linux [SKIP]
  Skipped OSPlatformFact.LinuxMathTests.Test_only_on_linux [1 ms]

Passed!  - Failed:     0, Passed:     2, Skipped:     1, Total:     3, Duration: 10 ms - OSPlatformFact.dll (net8.0)
```

Output of `dotnet test` on Linux:

``` text
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.28]     OSPlatformFact.WindowsMathTests.Test_only_on_windows [SKIP]
  Skipped OSPlatformFact.WindowsMathTests.Test_only_on_windows [1 ms]

Passed!  - Failed:     0, Passed:     2, Skipped:     1, Total:     3, Duration: 33 ms - OSPlatformFact.dll (net8.0)
```

**Comment by bradwilson** [comment]
> I'm still looking for a solution where I only need to add the `SupportedOSPlatformAttribrute` like in my original post. But I don't know enough about xunit internals to extend it.

I'm not 100% sure myself what the easiest way to do this is right now. I would have to sit down and do some experiments, but surely they would be involved.

FWIW, the skipping version will be easier in v3, because you can just write this as the first line of your test:

```csharp
Assert.SkipUnless(RuntimeInformation.IsOSPlatform(OSPlatform.Windows), "Test requires Windows");
```

And we use this today to skip categories of tests which don't support Mono:

https://github.com/xunit/xunit/blob/5f336b16c23bc5eb85a82f1350b0ef89da49985e/src/xunit.v3.core.tests/Acceptance/DynamicAssemblyAcceptanceTests.cs#L23

As mentioned above, I have an open issue as to whether or not this would be something that could get integrated into the `Fact` attribute directly: https://github.com/xunit/xunit/issues/2339

**Comment by bradwilson** [comment]
While working update `[FactAttribute]` for dynamic skipping (#2339), I've been experimenting with ways to achieve this. The requested ability already exists today in v3, via `BeforeAfterTestAttribute`:

```csharp
using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using Xunit;
using Xunit.v3;

namespace Empty;

public sealed class SupportedOSPlatformAttribute(string platformName) :
	BeforeAfterTestAttribute
{
	public override ValueTask Before(MethodInfo methodUnderTest, IXunitTest test)
	{
		var platform = OSPlatform.Create(platformName.ToUpperInvariant());
		if (!RuntimeInformation.IsOSPlatform(platform))
			throw new Exception($"$XunitDynamicSkip$This test is only supported on {platformName}");

		return default;
	}
}

public class TestClass
{
	[Fact]
	[SupportedOSPlatform("Windows")]
	public void RunsOnWindows() => Assert.True(false);

	[Fact]
	[SupportedOSPlatform("Linux")]
	public void RunsOnLinux() => Assert.True(false);
}
```

```
xUnit.net v3 In-Process Runner v0.2.0-pre.41+5c13944801 (64-bit .NET 6.0.32)
  Discovering: empty (method display = ClassAndMethod, method display options = None)
  Discovered:  empty (2 test cases to be run)
  Starting:    empty (parallel test collections = on [24 threads], stop on fail = off, explicit = off, seed = 734178125)
    Empty.TestClass.RunsOnLinux [SKIP]
      This test is only supported on Linux
    Empty.TestClass.RunsOnWindows [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        UnitTest.cs(27,0): at Empty.TestClass.RunsOnWindows()
  Finished:    empty
=== TEST EXECUTION SUMMARY ===
   empty  Total: 2, Errors: 0, Failed: 1, Skipped: 1, Not Run: 0, Time: 0.079s
```

You'll notice that funny `$XunitDynamicSkip$` token at the beginning of the exception message. That tells us that this isn't a failure, but instead is a dynamic skip. We don't care about the exception type in that scenario, as the exception itself is thrown away, and the text after the token is used for the skip message.

This is documented here: https://github.com/xunit/assert.xunit/blob/main/Sdk/DynamicSkipToken.cs

And we use it here: https://github.com/xunit/assert.xunit/blob/main/Sdk/Exceptions/SkipException.cs

(This is the exception thrown by `Assert.Skip`, `Assert.SkipUnless`, and `Assert.SkipWhen`.)

Once I've finished the updated `FactAttribute`, it will also be possible to express this as replacement FactAttribute that can dynamically skip. I think from a usability standpoint most people will probably prefer this as a separate attribute, but both options will be available.

And just a reminder that all of this requires v3, and will not be supported in v2.

**Comment by bradwilson** [comment]
This works (and doesn't rely on the new SkipWhen/SkipUntil functionality), but I like it less. It's still an option, though.

```csharp
using System;
using System.Runtime.InteropServices;
using Xunit;
using Xunit.v3;

namespace Empty;

[AttributeUsage(AttributeTargets.Method)]
[XunitTestCaseDiscoverer(typeof(FactDiscoverer))]
public class OSFactAttribute : Attribute, IFactAttribute
{
	public OSFactAttribute(string platformName)
	{
		if (!RuntimeInformation.IsOSPlatform(OSPlatform.Create(platformName.ToUpperInvariant())))
			Skip = $"This test is only supported on {platformName}";
	}

	public string? DisplayName { get; set; }
	public bool Explicit { get; set; }
	public string? Skip { get; }
	Type? IFactAttribute.SkipType => null;
	string? IFactAttribute.SkipUnless => null;
	string? IFactAttribute.SkipWhen => null;
	public int Timeout { get; set; }
}

public class TestClass
{
	[OSFact("Windows")]
	public void RunsOnWindows() => Assert.True(false);

	[OSFact("Linux")]
	public void RunsOnLinux() => Assert.True(false);
}
```

```
xUnit.net v3 In-Process Runner v0.2.0-pre.50+70821585a6 (64-bit .NET 6.0.32)
  Discovering: empty (method display = ClassAndMethod, method display options = None)
  Discovered:  empty (2 test cases to be run)
  Starting:    empty (parallel test collections = on [24 threads], stop on fail = off, explicit = off, seed = 828407707)
    Empty.TestClass.RunsOnLinux [SKIP]
      This test is only supported on Linux
    Empty.TestClass.RunsOnWindows [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        UnitTest.cs(30,0): at Empty.TestClass.RunsOnWindows()
  Finished:    empty
=== TEST EXECUTION SUMMARY ===
   empty  Total: 2, Errors: 0, Failed: 1, Skipped: 1, Not Run: 0, Time: 0.083s
```

**Comment by bradwilson** [comment]
I'm going to close this now, as there are a few different ways this can be addressed in v3.
