### ISSUE TITLE
Assert.Equal fails on Dictionary comparison with nullable types

### ISSUE THREAD

**Issue by ladeak** [xunit/xunit#2824]
In xUnit (nuget package) 2.6.2 (compared to 2.6.1) `Assert.Equal` returns `false` for the following code:

```csharp
Assert.Equal(new Dictionary<string, int?> { { "two", null } }, new Dictionary<string, int?> { { "two", null } });
```
while in 2.6.1 (and I think 'ever' before) it returned `true`.

**Comment by bradwilson** [comment]
Available in v2 `2.6.3-pre.4`
Available in v3 `0.1.1-pre.327`

**Comment by ladeak** [comment]
thank you

**Comment by ladeak** [comment]
@bradwilson when can we expect a non-preview build?

**Comment by bradwilson** [comment]
@ladeak This week.
