### ISSUE TITLE
Assert.Equal fails for IEquatable<T> also implementing IEnumerable<T>

### ISSUE THREAD

**Issue by MrAntix** [xunit/xunit#2828]
I have a reproduction here

https://github.com/MrAntix/equatable-assert-fails

works on 2.4.2 fails on 2.5.0+

I think IComparable[T] needs precedence over IEnumerble 
https://github.com/xunit/assert.xunit/blob/main/Sdk/AssertEqualityComparer.cs#L137

**Comment by bradwilson** [comment]
Available in v2 `2.6.3-pre.5`
Available in v3 `0.1.1-pre.328`

**Comment by bradwilson** [comment]
Note that _only_ `IEquatable<T>` can override the collection behavior. The other interfaces are less specific (and in some cases problematic with the built-in types, like `Array`'s implementation of `IStructuralEquatable` being wrong for our needs).
