### ISSUE TITLE
Assert.NotNull does not prevent next Assert from flagging possible null

### ISSUE THREAD

**Issue by RobertBernstein** [xunit/xunit#283]
I have the following code in my test:

    // Arrange
    HomeController controller = new HomeController();

    // Act
    ViewResult result = controller.Index() as ViewResult;

    // Assert
    Assert.NotNull(result);
    Assert.Equal("Welcome", result.ViewBag.Title);

In the last line, `result` is getting flagged for a possible NullReferenceException, even though the previous line would have already asserted on null.  Am I doing something wrong or is this an actual issue?

Rob

**Comment by bradwilson** [comment]
What tool is doing the flagging?

**Comment by RobertBernstein** [comment]
It's either VS2013.4 itself or, more likely, ReSharper.  However, when I use MSTest, the Assert.IsNotNull() eliminated the flag as a possible null.

**Comment by bradwilson** [comment]
Must be Resharper. I'm not sure if there's some metadata attribute we can add that would help them, or if they've just hard-coded knowledge of MSTest into R#.

**Comment by citizenmatt** [comment]
Yep, ReSharper uses attributes to provide more context for analysis. You can mark methods as being "assertion methods" that will throw if given `null` or not-`null`, and ReSharper will use that to adjust the control flow graph and not mark that access as a possible null reference. You can add these attributes to your source by referencing the [JetBrains.Annotations](https://www.nuget.org/packages/JetBrains.Annotations/) package, or by including the source directly into your project, and applying to methods and types, etc.

By default, these are not compiled into the resulting binary, as they're marked with the `[Conditional]` attribute. If you define `JETBRAINS_ANNOTATIONS` when compiling, they are compiled in, but you have to distribute `JetBrains.Annotations.dll`, which is quite often undesirable. But if the attributes are compiled in, ReSharper can use them when someone else references your assembly.

ReSharper also supports "external annotations", which are an xml representation of applying the attributes to members in a pre-compiled assembly. ReSharper ships with a set of annotations for the entire BCL, based on automated scans looking for values that can be null or must not be null, or that will obviously throw, etc.

The ReSharper plugin ships external annotations for xunit1, but I haven't yet updated them to xunit2. See  xunit/resharper-xunit#30. I'm due a new release to support RC1, I'll see if I can get them updated to include in the next build.

Interestingly, the external annotations won't work with the `xunit.assert.source` library, as external annotations are based on assembly name. To get this to work would meaning adding the attributes to the source, and either adding a reference to the `JetBrains.Annotations` package, or add the attribute definitions to the source being distributed. As above, they wouldn't be compiled into the binary. Thoughts, @bradwilson?

**Comment by bradwilson** [comment]
I believe we are going to resolve this as an external issue, and let Resharper come up with the correct mappings. We discussed this and decided that shipping a dependency on a third party annotations library is outside the scope of what we want to do for 2.0.

**Comment by RobertBernstein** [comment]
Thanks for the discussion around this issue, guys.  I would certainly prefer to not have to include JetBrains.Annotations with my binary.  What is the likelihood of JetBrains building the correct mappings for xUnit 2.x?  And if they did, I suspect they would wait until it RTMs, no?

**Comment by citizenmatt** [comment]
The annotations will be updated in the next release of the ReSharper plugin.
