### ISSUE TITLE
Security Vulnerability: XUnit 2.6.2 has transitive references to vulnerable nuget dependencies

### ISSUE THREAD

**Issue by udlose** [xunit/xunit#2833]
v2.6.2 has transitive references to two vulnerable Nuget Packages
- System.Net.Http v4.3.0 - https://github.com/advisories/GHSA-7jgj-8wvc-jh57
- System.Text.RegularExpressions v4.3.0 - https://github.com/advisories/GHSA-cmhx-cq75-c4mj

These nugets have since been patched several years ago. Please update the dependencies.

<img width="1547" alt="image" src="https://github.com/xunit/xunit/assets/656118/abc90a85-29c3-4cc8-8159-ea1b1cc32658">

**Comment by bartelink** [comment]
https://github.com/xunit/xunit/discussions/2766

**Comment by bradwilson** [comment]
Asked and answered many times, as @bartelink links to.
