### ISSUE TITLE
Maybe support collection expression syntax for TheoryData

### ISSUE THREAD

**Issue by FreeApophis** [xunit/xunit#2836]
TheoryData is a collection type, it implements the old Pattern to initialize it (Add) so it would be convinient if it would support the C#12's[ collection expression](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/collection-expressions) syntax as well.

Currently:
```cs
    public static TheoryData<string> NumberStrings()
        => new() { string.Empty, "no number", "-12", "0"};
```

Proposed:
```cs
public static TheoryData<string> NumberStrings()
    => [string.Empty, "no number", "-12", "0"];
```

The implementation would require the implementation of a simple [Collection Builder](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/collection-expressions#collection-builder).

The other theoretical advantage to the old pattern is the support of immutable collections, but we don't have that in this case.

What do you think?

**Comment by bartelink** [comment]
note the `TheoryData<string>` bit would [actually need to be `TheoryData<string, string, string, string>`](https://stackoverflow.com/a/47835325/11635), but agreed it would be nice

**Comment by bradwilson** [comment]
@bartelink No, the TheoryData<T> (with a single T) has special compiler support. That example creates 4 rows with 1 item each, not 1 row with 4 items in it.

@FreeApophis I don't think there's anything we can do here. Either the compiler can support converting your suggested syntax into calls to `.Add` or it doesn't. We have nothing to do with how the compiler makes the `new() { string.Empty, "no number", "-12", "0" };` work (or not work).

**Comment by bartelink** [comment]
@bradwilson You are correct; I was seeing what I wanted to see

In the SO answer I linked, there's a `TheoryData` where each Data has multiple typed items. In my example, the TheoryData field needs to be initialized with `= new() { { x, y, z}, { a, b, c} }`, and I was hoping that could become `= [ { x, y, z}, { a, b, c} ]`...

But, as an aside: I just added a section to my SO answer entitled "really ugly hack", which uses a helper to initialize a TheoryData from a collection of tuples.

One could map that to an overloaded ctor on each of the `TheoryData` generic instantiations.

But whether one should, is a whole different matter...

----

    static TheoryData<T1, T2, T3, T4, T5, T6> MakeTheoryData<T1, T2, T3, T4, T5, T6>(IEnumerable<(T1, T2, T3, T4, T5, T6)> values)
    {
        var tmp = new TheoryData<T1, T2, T3, T4, T5, T6>();
        foreach(var (t1, t2, t3, t4, t5, t6) in values)
            tmp.Add(t1, t2, t3, t4, t5, t6);
        return tmp;
    }

    public static TheoryData<string, string, int, string, DateTime, DateTime> Cases = MakeTheoryData(
        [
            ( "title 1", "testing 1", 1, "Educational", new DateTime(2017, 3, 1), new DateTime(2018, 12, 31) ),
            ( "title 2", "testing 2", 2, "Self Employment", new DateTime(2017, 2, 1), new DateTime(2018, 2, 28) )
        ]);

 [Theory, MemberData(nameof(Cases))]
    public void WhenPassingCorrectData_SuccessfullyCreate(string _title,
        string _description,
        int _categoryId,
        string _category,
        DateTime _startDate,
        DateTime _endDate)
    {
        var _ = $"{_title}{_description}{_categoryId}{_category}{_startDate}{_endDate}";
        Assert.Equal(2017,_startDate.Year);
    }

**Comment by bradwilson** [comment]
@bartelink This is already natively supported in v3. Examples for 2 parameters:

https://github.com/xunit/xunit/blob/d0638f314c1fb3e5a6b85d76fc3aef78c875fdd6/src/xunit.v3.core/TheoryData.cs#L107-L112
https://github.com/xunit/xunit/blob/d0638f314c1fb3e5a6b85d76fc3aef78c875fdd6/src/xunit.v3.core/TheoryData.cs#L122-L131

**Comment by bartelink** [comment]
Ah, nice thanks for pointing that out!
(Guess who spent a few minutes just now fighting the compiler and reality assuming it should work with V2 before reading the message!)

**Comment by bradwilson** [comment]
@bartelink You could copy the v3 version of the code into your project and just use it. 😄

**Comment by bartelink** [comment]
I could, but in my context I have plenty acceptable approaches without all that code and braces, even for V2 :P

```fsharp
module Tests

open System
open Xunit

let dmy (d: int) (m: int) (y: int) = DateTime(d, m, y)

let cases = TheoryData<_, _, _, _, _, _>()
[   "title 1", "testing 1", 1, "Educational",     dmy 2017 3 1, dmy 2018 12 31
    "title 2", "testing 2", 2, "Self Employment", dmy 2017 2 1, dmy 2018 2 28
] |> List.iter cases.Add

[<Theory; MemberData(nameof cases)>]
let whenPassingCorrectData_SuccessfullyCreate(
        _title: string,
        _description: string,
        _categoryId: int,
        _category: string ,
        _startDate: DateTime ,
        _endDate: DateTime) =
    let _ = $"{_title}{_description}{_categoryId}{_category}{_startDate}{_endDate}";
    Assert.Equal(2017,_startDate.Year);
```
The ctors in V3 should collapse that to something like:
```fsharp
let cases = TheoryData [
    "title 1", "testing 1", 1, "Educational",     dmy 2017 3 1, dmy 2018 12 31
    "title 2", "testing 2", 2, "Self Employment", dmy 2017 2 1, dmy 2018 2 28
]
```

**Comment by FreeApophis** [comment]
Thanks.

**Comment by neon-sunset** [comment]
> Going to close this as external, but also point out that this should work today:
> 
> ```cs
> public static TheoryData<string> NumberStrings()
>     => new([string.Empty, "no number", "-12", "0"]);
> ```
> 
> It is a few more characters, but the best that can be done by us.

This does not seem to work. `TheoryData<T>` does not implement `AddRange(T item)` either which means that it cannot be constructed with e.g. `new TheoryData<string> { Enumerable.Range(0, 10).Select(i => $"{i}") };` either. It is unfortunate to see this issue being closed.

**Comment by bradwilson** [comment]
Oops, my example was done with v3's TheoryData, which includes an IEnumerable<T> constructor. Unfortunately v2's doesn't have that, so I'll open a new issue for that.
