### ISSUE TITLE
Assert.(Not)Equal ignores order in ordered collections that implement ISet or IDictionary 

### ISSUE THREAD

**Issue by AndriySvyryd** [xunit/xunit#2841]
```C#
[Fact]
public void Order_asserted_for_SortedSet()
    => Assert.NotEqual(
        new SortedSet<int> { 1, 2 },
        new SortedSet<int>(new ReverseComparer()) { 1, 2 });

[Fact]
public void Order_asserted_for_ImmutableSortedSet()
    => Assert.NotEqual(
        ImmutableSortedSet.CreateRange([1, 2]),
        ImmutableSortedSet.CreateRange(new ReverseComparer(), [1, 2]));

[Fact]
public void Order_asserted_for_SortedList()
    => Assert.NotEqual(
        new SortedList { { 1, "" }, { 2, "" } },
        new SortedList(new ReverseComparer()) { { 1, "" }, { 2, "" } });

[Fact]
public void Order_asserted_for_GenericSortedList()
    => Assert.NotEqual(
        new SortedList<int, string> { { 1, "" }, { 2, "" } },
        new SortedList<int, string>(new ReverseComparer()) { { 1, "" }, { 2, "" } });

[Fact]
public void Order_asserted_for_SortedDictionary()
    => Assert.NotEqual(
        new SortedDictionary<int, string> { { 1, "" }, { 2, "" } },
        new SortedDictionary<int, string>(new ReverseComparer()) { { 1, "" }, { 2, "" } });

[Fact]
public void Order_asserted_for_ImmutableSortedDictionary()
    => Assert.NotEqual(
        new Dictionary<int, string> { { 1, "" }, { 2, "" } }.ToImmutableSortedDictionary(),
        new Dictionary<int, string> { { 1, "" }, { 2, "" } }.ToImmutableSortedDictionary(new ReverseComparer()));

[Fact]
public void Order_asserted_for_OrderedDictionary()
    => Assert.NotEqual(
        new OrderedDictionary { { 1, "" }, { 2, "" } },
        new OrderedDictionary { { 2, "" }, { 1, "" } });

public class ReverseComparer : IComparer<int>, IComparer
{
    public int Compare(int x, int y) => y - x;
    public int Compare(object x, object y) => Compare((int)x, (int)y);
}
```

I expect the above tests to pass. Instead, they fail with a misleading message like:
```
Assert.NotEqual() Failure: Collections are equal
Expected: Not [[1, ], [2, ]]
Actual:       [[2, ], [1, ]]
```

Not asserting the order can hide a bug in the product while giving false confidence that the scenario has test coverage.
 
I know that as a workaround I can call `ToList` (at least on the generic types), but when the underlying collection type is unknown I'd have to call `ToList` on all collections being asserted and this becomes tedious quickly, not to mention the added perf hit.

This is a type of issue that's unlikely to be reported as lack of failure is hard to detect. The vast majority of affected users will not even know that a workaround is needed.

**Comment by bradwilson** [comment]
As previously discussed, sets != linear collections, and we have no intention of special casing this. If you want a set to be treated like a linear collection, turn it into one.

**Comment by bradwilson** [comment]
You can also use `.Select(x => x)` if you don't wish to create an intermediate container. This will make the set appear as a linear container.

**Comment by AndriySvyryd** [comment]
> You can also use .Select(x => x) if you don't wish to create an intermediate container. This will make the set appear as a linear container.

The bigger problem is that we have >120k tests that I'd need to go through. The reason I filed this is because I found a product bug by changing some of the tests to use `ToList` as a workaround for the other xunit issue.
