### ISSUE TITLE
xunit.assert 2.6.2 tag is missing

### ISSUE THREAD

**Issue by ViktorHofer** [xunit/xunit#2843]
... is that intentional? https://github.com/xunit/assert.xunit/tags

I also can't find the commit SHA on GH that's embedded into the nuspec: `f69c77d4289be26085fa8fe6cb53f5cabac4f7b4`.

Looks like this should be the HEAD Commit for the xunit.asset/2.6.2 tag: https://github.com/xunit/assert.xunit/tree/455865ac846c0812e80ffb1c4a46b9d5d35ff828

**Comment by bradwilson** [comment]
Unintentional (and fixed). Thanks!
