### ISSUE TITLE
Outdated System.Net.Http library -- multiple vulnerabilities

### ISSUE THREAD

**Issue by FaustDantes** [xunit/xunit#2848]
After integrating SNYK tool into project the latest XUNIT nuget 2.6.3 has multiple vulnerabilities. 
eg. Denial of Service (DoS), Improper Certificate Validation, Information Exposure
and also System.Text.RegularExpressions Regular Expression Denial of Service (ReDoS)

This is caused by using: 
**System.Net.Http** library  v 4.1.2.  (current one is 4.3.4 at 12th of December 2023)
 _Introduced through_ : project@* › xunit@2.6.3 › xunit.core@2.6.3 › xunit.extensibility.core@2.6.3 › NETStandard.Library@1.6.1 › System.Net.Http@4.3.0

 **System.Text.RegularExpressions** version 4.3.1. 
 _introduced through_ - project@* › xunit@2.6.3 › xunit.core@2.6.3 › xunit.extensibility.core@2.6.3 › NETStandard.Library@1.6.1 › System.Text.RegularExpressions@4.3.0

Do you have any idea when this would be resolved ? 

Thank you so much for your answers and help.

**Comment by bartelink** [comment]
Duplicate of https://github.com/xunit/xunit/issues/2833 and its predecessors
