### ISSUE TITLE
Update xUnit1030 to handle ConfigureAwaitOptions

### ISSUE THREAD

**Issue by spanglerco** [xunit/xunit#2849]
.NET 8 adds a new [`ConfigureAwait` overload](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.configureawait?view=net-8.0#system-threading-tasks-task-configureawait(system-threading-tasks-configureawaitoptions)) that takes in a new [`ConfigureAwaitOptions` flags enum](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.configureawaitoptions?view=net-8.0&devlangs=csharp&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.Threading.Tasks.ConfigureAwaitOptions)%3Bk(SolutionItemsProject)%3Bk(DevLang-csharp)%26rd%3Dtrue). `ConfigureAwaitOptions.ContinueOnCapturedContext` corresponds to `ConfigureAwait(true)`, while the other values provide new functionality.

Based on the existing `xUnit1030` flagging `ConfigureAwait(false)` but allowing `ConfigureAwait(true)`, it would be nice for it to also allow `ConfigureAwait(ConfigureAwaitOptions.ContinueOnCapturedContext)` and any combination of flags that include it.

For example, a test that waits for a task to complete regardless of whether the task faults or not:

```csharp
[Fact]
public async Task MyTest()
{
    Task task = Task.FromException(new InvalidOperationException());
    // Incorrectly flagged by xUnit1030
    await task.ConfigureAwait(ConfigureAwaitOptions.SuppressThrowing | ConfigureAwaitOptions.ContinueOnCapturedContext);
    // Correctly flagged by xUnit1030
    await task.ConfigureAwait(ConfigureAwaitOptions.SuppressThrowing);

    Assert.True(task.IsFaulted);
}
```

**Comment by bradwilson** [comment]
Available in `1.8.0-pre.11` https://xunit.net/docs/using-ci-builds

Note that, like most of our analyzers that look at arguments, we do not attempt to calculate or backtrack the values, so here we're looking for the _literal_ inclusion of `ConfigureAwaitOptions.ContinueOnCapturedContext` in the argument value.
