### ISSUE TITLE
Breaking change: Analyzer errors out on valid CollectionDefinition

### ISSUE THREAD

**Issue by sloncho** [xunit/xunit#2851]
Upgrading xunit from 2.6.2 to 2.6.3 broke our code base build. Tracked the change to the new version of xunit.analyzer. With v. 1.7.0 a new rule have been added to prevent using collection definition from another assembly: https://github.com/xunit/xunit/issues/2311

The new analyzer does not account for a code where a test class has subclasses, and the Collection attribute is applied on the base class, although the CollectionAttribute is declared with inherit=true.

As a result, this code fails to compile, even though the corresponding collection definition is (and was) in the same assembly:

``` csharp
[Collection("my collection")
public abstracts class MyClassTests
{
    protected MyClassTests(MyFixture fixture) {}
    public class MyMethod : MyClassTests
    public MyMethod(MyFixture fixture) : base(fixture)
   {
         [Fact]
        public void Should_do_something() {}
   }
}
```

If the `[Collection`] attribute is applied on the inner class, the code builds.

**Comment by bradwilson** [comment]
I believe this is a dup of #2845.
