### ISSUE TITLE
false-positive `xUnit1034` errors

### ISSUE THREAD

**Issue by viceroypenguin** [xunit/xunit#2852]
#### Code:
```cs
public class TestClass
{
  public static IEnumerable<object[]> GetSequences(IEnumerable<int> seq) =>
      [new object[] { seq }];

  [Theory]
  [MemberData(nameof(GetSequences), new int[] { 1, 2, })]
  public void Test(IEnumerable<int> seq)
  {
    Assert.NotEmpty(seq);
  }
}
```

#### Expected: 
Code will compile with no errors or warnings, as it does with xunit 2.6.1 / xunit.analyzers 1.6.0

#### Actual:
```
warning xUnit1034: Null should not be used for type parameter 'seq' of type 'System.Collections.Generic.IEnumerable<int>'. Use a non-null value, or convert the parameter to a nullable type. (https://xunit.net/xunit.analyzers/rules/xUnit1034)
```

#### Additional Notes
Sorry @JamesTerwilliger, apparently there is another bug in the analyzer for this code. I am confused by this, because it should be caught by the unit test. If I can provide any other information to help you with this, please let me know. Sorry to be a bother on this issue.

I have tested with xunit.analyzers 1.8.0.

/CC: @JamesTerwilliger

**Comment by bradwilson** [comment]
Using `semanticModel.GetConstantValue` to get the value of constants does not work for array initializers, so the code in the analyzer has incorrectly determined that the value is `null`.

Working on a fix.

**Comment by bradwilson** [comment]
Available in `1.9.0-pre.2` https://xunit.net/docs/using-ci-builds

**Comment by viceroypenguin** [comment]
Thank you!

**Comment by JamesTerwilliger** [comment]
My apologies for the oversight. :-( I'll try to tackle another issue as penance.
