### ISSUE TITLE
Get IMessageSink in the InitializeAsync method of IAsyncLifetime

### ISSUE THREAD

**Issue by michaeltg17** [xunit/xunit#2853]
I have a class called Database which has an async constructor method. I want it to take an IMessageSink parameter to write messages to output.

Before that I was using it like this:

    public class WebApplicationFactoryFixture() : WebApplicationFactory<Program>, IAsyncLifetime
    {
        public ITestOutputHelper TestOutputHelper { get; set; } = default!;

        Database Database = default!;

        public async Task InitializeAsync()
        {
            Database = await Database.Create();
        }
    }

Now to pass the new parameter I have to use GetAwaiter and I want to avoid it.

    public class WebApplicationFactoryFixture(IMessageSink messageSink) : WebApplicationFactory<Program>, IAsyncLifetime
    {
        public ITestOutputHelper TestOutputHelper { get; set; } = default!;

        Database Database = default!;

        public Task InitializeAsync()
        {
            return Task.CompletedTask;
        }

        protected override IHost CreateHost(IHostBuilder builder)
        {
            Database = Database.Create(messageSink).GetAwaiter().GetResult();

            builder.UseSerilog((context, services, configuration) =>
            {
                Program.ApplySerilogConfiguration(context, services, configuration);
                configuration.WriteTo.TestOutput(TestOutputHelper);
            });

            builder.ConfigureServices(s => s.Configure<Settings>(s =>
            {
                s.SqlServerConnectionString = Database.ConnectionString;
                s.Url = "http://localhost";
            }));

            return base.CreateHost(builder);
        }
   }

But I can't have the IMessageSink parameter before this class gets created, so this seems the only way.

Is there another way to do it?

**Comment by bradwilson** [comment]
I don't see where the `IMessageSink` comes to you in the provided sample. Is it a field from `WebApplicationFactory<Program>`?

**Comment by michaeltg17** [comment]
From the class constructor. It gets injected by xUnit as this is a fixture class (ICollectionFixture). Sorry for not giving the whole example but I can provide it if needed.

**Comment by bradwilson** [comment]
You should have access to the `IMessageSink` during `InitializeAsync` then, just store it in the constructor and use it.

**Comment by bradwilson** [comment]
```csharp
public class public class WebApplicationFactoryFixture(IMessageSink messageSink)
    : WebApplicationFactory<Program>, IAsyncLifetime
{
    private Database database;
    private readonly IMessageSink messageSink;

    public WebApplicationFactoryFixture(IMessageSink messageSink) =>
        this.messageSink = messageSink;

    public async Task InitializeAsync() =>
        database = await Database.Create(messageSink);

    // ...
}
```

**Comment by michaeltg17** [comment]
This works indeed, thanks!
