### ISSUE TITLE
xUnit1031 should not apply when syntax is part of an expression tree

### ISSUE THREAD

**Issue by bbarry** [xunit/xunit#2856]
The following test triggers xUnit1031 but no blocking call is ever made:

```csharp
[Fact]
public async Task ShouldNotTriggerXUnit1031()
{
    var mock = new Mock<AsyncTestClass>();
    mock.Setup(v => v.MethodAsync().Result).Returns(2);

    var result = await mock.Object.MethodUnderTest();

    Assert.Equal(2, result);
}

public class AsyncTestClass
{
    public virtual Task<int> MethodAsync()
    {
        return Task.FromResult(1);
    }

    public async Task<int> MethodUnderTest()
    {
        return await MethodAsync();
    }
}
```

Affects:

* xUnit 2.5.1+

A simpler test case that produces the warning:

```csharp
[Fact]
public void AlsoShouldNotTriggerXUnit1031()
{
    Expression<Func<Task<int>, int>> _ = v => v.Result;
}
```

---

I would expect this to be rather commonly triggered in any project that uses both xUnit and Moq due to the way Moq documents mocking async methods:

from: https://github.com/devlooped/moq/wiki/Quickstart#async-methods

> ### Async Methods
> 
> There are several ways to set up "async" methods (e.g. methods returning a `Task<T>` or `ValueTask<T>`):
> 
> * Starting with Moq 4.16, you can simply `mock.Setup` the returned task's `.Result` property. This works in nearly all setup and verification expressions:
> 
>    ```csharp
>    mock.Setup(foo => foo.DoSomethingAsync().Result).Returns(true);
>    ```

This seems to happen with every version of xunit >= 2.5.1 and Moq 4.16.0+

**Comment by bradwilson** [comment]
Available in `1.9.0-pre.8` https://xunit.net/docs/using-ci-builds
