### ISSUE TITLE
Support a CollectionBehaviour.CollectionPerMethod option

### ISSUE THREAD

**Issue by hach-que** [xunit/xunit#286]
We've architecture all our tests so that they're isolated at the method level (with classes just providing an additional level of context as to what a group of tests are about).

Since they're all isolated, they can all run in parallel at a method level, but there's no option to enable this level of parallel tests.

**Comment by bradwilson** [comment]
What about `IClassFixture<T>`? The design for fixtures today is shared state wherein no parallelization happens.

**Comment by hach-que** [comment]
Well we could put all of our test methods into their own classes, but it seems a bit redundant to have 1 method in each class just to enable parallel testing.  We strictly don't store any state in our test classes (no private fields or properties), so we don't need to worry about state colliding between tests as they run in parallel.

**Comment by bradwilson** [comment]
After discussion, we've decided not to do this feature.

**Comment by hach-que** [comment]
Is there a reason for not adding this feature? We design all our test methods to be completely isolated and to have no shared state so that we can maximize parallelization. Having to create one class for each method isn't ideal because we lose the ability to have related tests grouped in UIs and test reports.

**Comment by bradwilson** [comment]
It would be possible for you to add this feature yourself (it would require adapting one of the existing samples; if you want some help, I can probably send you in the right direction).

The reason we're not planning to add this to the core framework is that our design is such that where fixtures are involved, there is no parallelization. While it seems acceptable for your uses to say "I won't use fixtures", we are designing the framework for more than just your use case. :)

**Comment by rikkit** [comment]
Hi @bradwilson, could you point me in the direction of these samples? I have several tests that hit urls using [Theory] and [InlineData] and I'd like to have each of these sub-tests running in parallel.

**Comment by bradwilson** [comment]
There is no example which does exactly what you want to do (obviously), but the closest is probably the [Observation Example](https://github.com/xunit/samples.xunit/tree/master/ObservationExample) which completely redefines test discovery and the execution pipeline.

You will need to deviate from the standard behavior more significantly than it does, but this should at least get you to understand how the existing pipeline works, and where you might be able to reuse and/or replace the existing components. It will also help to look at the source of the things that are being extended, inside of xUnit.net itself.
