### ISSUE TITLE
[v2] Consider adding dependencygroups in nuspecs to avoid bringing netstandard1.x dependencies in

### ISSUE THREAD

**Issue by ViktorHofer** [xunit/xunit#2862]
Several of our .NET components reference xunit packages. I noticed that some packages still bring .NET Standard 1.x dependencies transitively into the package dependency graph. [As we want to avoid bringing .NET Standard 1.x libraries in (to simplify the dependency graph and avoid CG warnings)](https://github.com/dotnet/arcade/issues/13315), we started applying creative workarounds (hacks) such as [this](https://github.com/dotnet/arcade/blob/074491b2a86631659e28a712439befcea29041ee/src/Microsoft.DotNet.XUnitConsoleRunner/src/Microsoft.DotNet.XUnitConsoleRunner.csproj#L37-L43).

While xunit might not want to add new TFMs as part of the v2 release (note that xunit.assert did that though), I wonder if we could add a `netcoreapp2.0` / `netstandard2.0` (or any newer .NETCoreApp TFM) dependency group to the four affected packages:
- https://github.com/xunit/xunit/blob/27e91e38a3cfd7a232ba48d900fc29d4ab1121ca/src/xunit.runner.utility.nuspec#L33 -> Add `netcoreapp2.0` and `netstandard2.0` dependency groups
- https://github.com/xunit/xunit/blob/27e91e38a3cfd7a232ba48d900fc29d4ab1121ca/src/xunit.runner.reporters.nuspec#L29 -> Add `netcoreapp2.0` and `netstandard2.0` dependency groups
- https://github.com/xunit/xunit/blob/27e91e38a3cfd7a232ba48d900fc29d4ab1121ca/src/xunit.extensibility.core.nuspec#L24 -> Add `netstandard2.0` dependency group
- https://github.com/xunit/xunit/blob/27e91e38a3cfd7a232ba48d900fc29d4ab1121ca/src/xunit.extensibility.execution.nuspec#L21 -> Add `netstandard2.0` dependency group

That would remove the transitive .NET Standard 1.x dependencies from the package dependency graph when referencing these packages on "modern" runtimes that already provide that API inbox.

cc @akoeplinger @ericstj

**Comment by Zzarek** [comment]
I completely agree with this. We actually have gotten to a point where we have a standard "xunit transitive property override" block due to CVEs from those .net standard 1.x dependencies. Yours is the only package where that's true.

**Comment by bradwilson** [comment]
What do you suggest they be replaced with? According to NuGet, the [newest version of NetStandard.Library is 2.0.3](https://www.nuget.org/packages/netstandard.library#versions-body-tab), which references [System.Net.Http 4.3.2](https://www.nuget.org/packages/NETStandard.Library/2.0.3#dependencies-body-tab). Snyk says [that version has Information Disclosure vulnerabilities](https://security.snyk.io/vuln/SNYK-DOTNET-SYSTEMNETHTTP-72439) (and I assume would still be flagged by Dependabot or equivalent). This is what everybody complains about, so...?

**Comment by bradwilson** [comment]
![image](https://github.com/xunit/xunit/assets/16944/08b44f3d-ea23-4d2e-8458-a8bc97466ea3)

**Comment by bradwilson** [comment]
Looks like I can just leave the references out entirely.

Here's 2.6.5:

![image](https://github.com/xunit/xunit/assets/16944/7e05773e-2389-4c80-85b7-6f52f0a78342)

And here's 2.6.6-pre.3:

![image](https://github.com/xunit/xunit/assets/16944/db7142b9-a42a-4a56-b559-e2de17df0e74)

**Comment by ViktorHofer** [comment]
This is great 💯 Thanks for the quick fix.

**Comment by ViktorHofer** [comment]
When can we expect a new stable version with that change on nuget.org? The sooner the better 🙂
