### ISSUE TITLE
Assert Custom Event Handler

### ISSUE THREAD

**Issue by AchimStuy** [xunit/xunit#2887]
I have similar issue as described [here](https://github.com/xunit/xunit/discussions/2772#discussioncomment-7910633) or [here](https://stackoverflow.com/questions/60917970/how-to-test-in-xunit-that-event-was-raised#comment133561423_60919386), that I'd like to test `RoutedPropertyChangedEventHandler<T>`, which is currently not possible.

For such cases I added a generic handler overload to `Assert.Raises`, so user can specify his own handler method. See my commits https://github.com/AchimStuy/xunit.assert/commit/d93fb00baa593883b7c7f8177887c862dc689f74 and https://github.com/AchimStuy/xunit/commit/70819cdb376c7db61f324171f04aba760399a4a5 for details. Are you interested in that work? Should I just create PR or should I add any other overloads?

**Comment by bradwilson** [comment]
Sure!

**Comment by bradwilson** [comment]
Available in `0.1.1-pre.370` https://xunit.net/docs/using-ci-builds

**Comment by bradwilson** [comment]
I will back-port this to v2 shortly!
