### ISSUE TITLE
Compile error when referencing both xunit.core and xunit.assert.source

### ISSUE THREAD

**Issue by ap0llo** [xunit/xunit#2889]
Since xunit 2.7.0, there is a compile error if a project uses both the xunit.core and xunit.assert.source packages:

```txt
[...]\packages\xunit.assert.source\2.7.0\contentFiles\cs\netstandard1.1\Asserts\Sdk\Exceptions\CollectionException.cs(34,41): error CS0117: 'ExceptionUtility' does not contain a definition for 'TransformStackTrace' [...]
[...]\packages\xunit.assert.source\2.7.0\contentFiles\cs\netstandard1.1\Asserts\Sdk\Exceptions\CollectionException.cs(34,78): error CS0117: 'ExceptionUtility' does not contain a definition for 'FilterStackTrace' [...]
```

This is due to the fact that an "ExceptionUtility" class exists in both the xunit.assert.source (`Xunit.Internal.ExceptionUtility`) and the xunit.execution.dotnet (`Xunit.Sdk.ExceptionUtility`) packages.

You can find a repro showing this issue here: https://github.com/ap0llo/repro-xunit-2-7-compile-error/

I've prepared a fix for this here: https://github.com/xunit/assert.xunit/pull/66/files

**Comment by bradwilson** [comment]
I don't have a release planned at the moment, so I can't give you a firm date. You can either roll `xunit.assert.source` back to 2.6.6 or use a CI build in the interim: https://xunit.net/docs/using-ci-builds

**Comment by bradwilson** [comment]
@sensslen FYI, I'm shipping a release for this later today which will be versioned as `2.7.1`.
