### ISSUE TITLE
About xUnit1028 error, `Task<TResult>` should be a valid type, because it's a `Task`

### ISSUE THREAD

**Issue by codelovercc** [xunit/xunit#2895]
I've defined some interfaces for my buz classes and test classes, and it contains some methods that returns `Task<TResult>`, by now I can't mark them as a test method. `Task<TResult>` is a `Task` type, I think it should be a valid return type. We use `Task<TResult>` a lot...

**Comment by bradwilson** [comment]
Curious: Why?

Nobody is paying attention to the return value of your unit test. What do you expect us to do with the `TResult`?

**Comment by jbhelm** [comment]
In our case, we sometimes call one async test method from another and need a return value.

**Comment by bradwilson** [comment]
What you're doing is outside the norm, so disabling the rule would seem appropriate for you.

The rule is still valuable for everybody else. The most important part of xUnit1028 is ensuring that developers using xUnit.net v2 don't expect `ValueTask` to be functional here, as that frequently ends up yielding a false positive.

Disabling rules: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/suppress-warnings

**Comment by bradwilson** [comment]
Actually, I take it back. Don't disable the rule.

There is code in xUnit.net that looks for `Task` but not for `Task<T>` so returning `Task<T>` could cause issues. My suggested workaround for that you should make your shared method a private, non-test method and invoke it from test methods that return `Task`.

**Comment by manuel-esteves** [comment]
I'm also getting the xUnit1028 in the following case 

public async Task<(SomeDto A, Interface B)> DoSomething() - How should this be tackled ? 

I'm using the lated versions of xunit in .net8

Regards.

**Comment by bradwilson** [comment]
> How should this be tackled ?

Unit tests should return `Task`, not `Task<T>`. Change the signature.

If you're somehow reusing your unit test somewhere else, stop doing that. Move the common code somewhere else where you can continue to use `Task<T>`, and then have the unit test call that instead.

**Comment by bradwilson** [comment]
Note that if you're getting xUnit1028 flagging non-unit test methods, then that's a bug that should be looked into (and you'll need to provide a repro project for that scenario).

**Comment by manuel-esteves** [comment]
It's a Unit test and completely makes sense what you suggested. 

Thanks for the fast reply :)

Regards.
