### ISSUE TITLE
Where is UseCultureAttribute?

### ISSUE THREAD

**Issue by kentcb** [xunit/xunit#290]
Hi,

What's the status with `UseCultureAttribute`? I see there's a [sample implementation here](https://github.com/xunit/samples/blob/07f0d3f47acc32c1f3e131321abf14e0aaf21eb2/UseCulture/UseCultureAttribute.cs), but is it included in an XUnit 2 binary anywhere? I can't seem to find it. Am copying the source into my project for now, but would like to know whether I can remove...

Thanks

**Comment by bradwilson** [comment]
It is not our intention to include it in the core framework.

**Comment by bradwilson** [comment]
No, there's nothing at issue with the implementation. We just don't intend to ship it as part of the framework.
