### ISSUE TITLE
[Feature] add nint IntPtr derivatives among the argument formatters

### ISSUE THREAD

**Issue by mwpowellhtx** [xunit/xunit#2903]
As in the assert [`TypeMappings`](https://github.com/xunit/assert.xunit/blob/adcd7cb67aa760cba565e8acb2c9f2b49e5e3f3f/Sdk/ArgumentFormatter.cs#L79), also documented among [_Characteristics of the integral types_](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types#characteristics-of-the-integral-types), i.e.

```csharp
// List of intrinsic types => C# type names
static readonly Dictionary<TypeInfo, string> TypeMappings = new Dictionary<TypeInfo, string>
{
    //...
    { typeof(nint).GetTypeInfo(), "nint" },
    { typeof(nuint).GetTypeInfo(), "nuint" },
    // ...
};
```

I think `nint` and `nuint` are somewhat new integral types, but could not tell you exactly when they were added.

For sake of completeness.

**Comment by bradwilson** [comment]
The underlying types themselves are not new (`IntPtr` and `UIntPtr` date back to .NET Framework 1.1 in 2003), but the aliases are, and they require C# 9 (released in 2020). It's a compiler feature rather than a runtime feature since they're just type aliases.
