### ISSUE TITLE
Missing webrick gem in gh-pages Gemfile

### ISSUE THREAD

**Issue by AlanMcBee** [xunit/xunit#2907]
I'm building the gh-pages for a local dev environment. I'm using the jekyll/jekyll docker image and mounting the volume to the root on the gh-pages branch.

When I attempt to build or serve the site, I got an error:

```
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 28.385 seconds.
                    Auto-regeneration may not work on some Windows versions.
                    Please see: https://github.com/Microsoft/BashOnWindows/issues/216
                    If it does not work, please upgrade Bash on Windows or run Jekyll with --no-watch.
 Auto-regeneration: enabled for '/srv/jekyll'
/usr/gem/gems/jekyll-3.9.5/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)
        from /usr/gem/gems/jekyll-3.9.5/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
        from /usr/gem/gems/jekyll-3.9.5/lib/jekyll/commands/serve.rb:184:in `require_relative'
        from /usr/gem/gems/jekyll-3.9.5/lib/jekyll/commands/serve.rb:184:in `setup'
        from /usr/gem/gems/jekyll-3.9.5/lib/jekyll/commands/serve.rb:102:in `process'
        from /usr/gem/gems/jekyll-3.9.5/lib/jekyll/commands/serve.rb:93:in `block in start'
        from /usr/gem/gems/jekyll-3.9.5/lib/jekyll/commands/serve.rb:93:in `each'
        from /usr/gem/gems/jekyll-3.9.5/lib/jekyll/commands/serve.rb:93:in `start'
        from /usr/gem/gems/jekyll-3.9.5/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /usr/gem/gems/jekyll-3.9.5/exe/jekyll:15:in `<top (required)>'
        from /usr/local/bundle/bin/jekyll:29:in `load'
        from /usr/local/bundle/bin/jekyll:29:in `<main>'
```

It appears I can resolve this by adding the following line to `Gemfile`:
```ruby
gem 'webrick'
```

Once I add that, I'm able to browse the doc pages.

...but I want to check before I submit the PR to fix this. If this is the right fix, assign to me and I'll send a PR.

**Comment by AlanMcBee** [comment]
Doing a little more research. I did commit this to my fork, and it still generates the GitHub pages from the gh-pages without any reported errors. I think the WEBrick module is basically ignored when GH just uses it to build pages.

**Comment by bradwilson** [comment]
This is likely the source of the problem:

> ruby 3.1.1p18

GitHub Pages used Ruby 2.7.4: https://pages.github.com/versions/

The reason your branch builds fine is because the CI for GitHub Pages is using Ruby 2.7.4.

I have set the `.ruby-version` file in the project root to point to 2.7.4 as well: https://github.com/xunit/xunit/blob/gh-pages/.ruby-version

Personally I use [`rbenv`](https://github.com/rbenv/rbenv) to allow me to install individual versions of Ruby as needed rather than relying on the OSes default version. `rbenv` picks up the `.ruby-version` file to tell it what version is needed.

Here you can see my default is 3.1.1, but I have both 3.1.1 and 2.7.4 installed:

![image](https://github.com/xunit/xunit/assets/16944/f5683442-e63b-47be-8a62-9003ba4c33f8)

Using 2.7.4 should fix issues like this. There were substantial changes not only to Ruby itself between 2.x and 3.x, but also the changes that end up in gems as they add conditional support for 2.x vs. 3.x.

I use bundler to install everything, and the version that's in use is 2.1.4, so on your Ruby 2.7.4 install I would suggest running `gem install bundler --version 2.1.4` before running `bundle install` (and especially before `bundle update` if you end up needing to do that).

**Comment by AlanMcBee** [comment]
NGL I know almost nothing about the Ruby world, coming from .NET centric. I know just enough to be dangerous. Your explanation is super-helpful; I'll be learning more as I do this more.

I had wondered if the jekyll/jekyll Docker image was on par with the image used by GH in the CI pipeline for gh-pages. Clearly its not. I just checked the source at https://github.com/actions/jekyll-build-pages, and the Dockerfile does load up 2.7.4. I don't have enough confidence in my skills yet to go to town with Ruby and bundler; I'm relying mostly on the Docker images to get things right. Also, I'm avoiding installing Ruby on my machine for now.

One thing that we'll almost certainly need to do is to change the setting on this repo to process gh-pages using a workflow instead of the "build from a branch" setting:

![image](https://github.com/xunit/xunit/assets/37203424/33383be1-02c2-46af-abd5-e45ea626cb6d)

But maybe don't change it yet until I finish working out how to get the DocFX output into the form I'm looking for. I made the change on my fork and it seems neutral (https://alanmcbee.github.io/xunit/index.html) - missing some root-relative files but that's expected - but I didn't really check it out thoroughly and it might not be needed depending on how the DocFX processing stuff works out.

**Comment by bradwilson** [comment]
Oh yeah, and step 7: post to the xUnit.net Mastodon account. 😄

**Comment by AlanMcBee** [comment]
Oh, okay. Hm. So, would this be acceptable (at least for now): 

- add a DocFX step to the CI workflow that simply creates a folder with the output from DocFX
- (probably add that folder to the .gitignore)
- push/merge that output folder from main to gh-pages
- and hand-edit the index.html on the gh-pages branch to link to the top of the API pages

Something like that?

I'm considering that you probably do want additional builds for each of the tags that are listed in the Releases, but only once per tag, and that all those are aggregated so that we can do the version-selector feature.

All the aggregated pages would be kept in gh-pages branch?

**Comment by AlanMcBee** [comment]
I'm closing this because the WEbrick gem is really only needed for local dev work (as an HTTP service) and it isn't needed for the build or documentation generation.
