### ISSUE TITLE
Add wildcard support to the console runner

### ISSUE THREAD

**Issue by HellBrick** [xunit/xunit#291]
I wanted to set up a TeamCity build step that runs tests marked by a special trait from all the test assemblies in a solution and found it to be a very tricky task. The MSBuild target can process wildcards properly, but it doesn't support trait/notrait options. The console runner has the opposite problem: it respects trait/notrait options, but has no support for the wildcards.

But even the build server case aside, the wildcard support could be a very nice addition to the console runner experience. Consider scenarios like running the tests from a certain subfolder (`xunit.console ./Subsystem/**/bin/*/*.Test.dll`) or running the tests that are built with a specific build configuration (`xunit.console ./**/bin/Experimental/*.Test.dll`) or even simply running all the tests (`xunit.console **/bin/*.Test.dll`).

**Comment by meriturva** [comment]
This is really a requirement when you are on TeamCity!

**Comment by omidkrad** [comment]
Voting this up. Currently we have to create 47 build steps in TeamCity because we cannot specify `*.Test.dll` for argument for xunit.console.exe.

**Comment by sblackler** [comment]
//cc @Smudge202 @HerecyDev - Have we gotten round this internally? I cant remember...

**Comment by smudge202** [comment]
In response to @sblackler , internally we  create a build step for each project under test and don't use wildcards. It wouldn't be particularly difficult to powershell the command to run for each directory in the `.\tests\` folder but it would be convention based.

I believe @herecydev or @mattridgway have or were contemplating a meta runner which makes copy/pasting the build steps and changing them for each project pretty trivial so we have a workaround in the meantime. Perhaps one of them can comment / link the metarunner assuming it was OSS'd? Doesn't resolve the issue, but may help people in the mean time.

**Comment by ma499** [comment]
This is the xunit.net metarunner I use. https://github.com/JetBrains/meta-runner-power-pack/tree/master/xunit.net




Would be simple to extend Powershell to handle wildcards.



—

**Comment by herecydev** [comment]
The meta runner we created lives [here](https://github.com/4Com/team-city-xunit-meta-runner) but doesn't address the issue of multiple test projects (you would create a build step per test project).

AFAIK, what's being asked might not be an xunit issue. When you do a `dnx . test` the project.json in the current folder is used which invokes the runner with that current test project. So I think some sort of  restructure would need to take place to facilitate this (read: global commands?).

**Comment by smudge202** [comment]
@herecydev I understand what you're saying from DNX perspective, but this is the normal xunit repo. ;)

**Comment by herecydev** [comment]
I *think* the same rules apply. Given how busy Brad is anyway I doubt features will be making their way back into old school csproj stuff as readily as they will be for xproj. But I can't speak on behalf of him.

**Comment by bradwilson** [comment]
I am fine with adding globbing support to the console runner, though I don't want to pull in a 3rd party binary for it. It's unlikely I'll be getting to it soon, because at the moment I'm focused on the reporting plugability for runners (part of the work for #423).

**Comment by bradwilson** [comment]
Feels like maybe some code could be purloined from here: https://github.com/aspnet/FileSystem/tree/dev/src/Microsoft.Framework.FileSystemGlobbing

:smiley_cat:

**Comment by patriksvensson** [comment]
I've already implemented this already in [Cake](https://github.com/cake-build/cake) and could take a look at implementing it in xUnit as well.

**Comment by JeremyCade** [comment]
@bradwilson Do you want to assign this issue to me? 

Where do you want globing to live? e.g. `xunit.console\Utility\` ?

**Comment by bradwilson** [comment]
Will do. The `Utility` folder is a fine place.

**Comment by patriksvensson** [comment]
:+1:

**Comment by bradwilson** [comment]
Closed for age.

**Comment by antgel** [comment]
Is anyone working on this? I know it was closed, but it seems no less relevant today. We'd like to run tests from Jenkins with a simple one-liner, but we can't do `*.dll`...

**Comment by VinS101** [comment]
We would also like to run the tests using a simple wildcard instead of listing them. Any updates on this?

**Comment by kdsundhiya** [comment]
I used something like 
For /R .\\Tests\\ %%G IN (bin\\release\\*.test.dll) do packages\\xunit.runner.console.2.4.1\\tools\\net461\\xunit.console.x86.exe "%%G" -junit "%%~nG.xml"
