### ISSUE TITLE
GitHub Actions Workflow hangs with 2.7.0

### ISSUE THREAD

**Issue by andyleejordan** [xunit/xunit#2912]
The Dependabot PR https://github.com/PowerShell/PowerShellEditorServices/pull/2154 updating PowerShell Editor Services unit tests from xUnit 2.6.6 to 2.7.0 is just hanging:

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
```

until it times out (across Windows, Linux, and macOS). I tested locally and it also just hangs, so not a CI specific issue. No tests were changed, and 2.6.6 is working fine. I did see https://github.com/xunit/xunit/issues/2904 but needed to open an issue to get help in deducing what API change in 2.7.0 might be causing this for our project.

Here's my xUnit configure file: https://github.com/PowerShell/PowerShellEditorServices/blob/main/test/PowerShellEditorServices.Test/xunit.runner.json

And the .csproj file (pre-updated): https://github.com/PowerShell/PowerShellEditorServices/blob/8c61728009c946c99326148fb52215d6c6d1d3f4/test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj#L39-L44

Perhaps xunit.runner.visualstudio and Xunit.SkippableFact need updates too?

**Comment by andyleejordan** [comment]
> The only big core change that I could see was related to opting out of the AsyncTestSyncContext for async tests which return Task.

From the linked issue...I bet we also have a deadlock somewhere. _Lots_ of async code and tests.

**Comment by bradwilson** [comment]
> Perhaps xunit.runner.visualstudio and Xunit.SkippableFact need updates too?

Not sure what you mean here, but: (a) xunit.runner.visualstudio versions are independent of xunit versions, and (b) Xunit.SkippableFact is not a package we wrote or support.

**Comment by bradwilson** [comment]
Another common thread here is that you have disable test collection parallelization, which appears to be the case with the other two reports, which now means you have _no_ custom sync contexts. Whatever is causing these deadlocks to be "solved" by the presence of one of our sync contexts is really strange and unclear to me.

Have you tried identifying the hanging tests, and converting them from `async Task` to `async void`? That would ensure that the old sync context is in place.

**Comment by bradwilson** [comment]
FWIW, cloning from `main` and deleting `nuget.config`, I'm seeing a seemingly hung test in `Microsoft.PowerShell.EditorServices.Test` (`CanResolveAndLoadProfilesForHostId`) and this is on 2.6.6.

Also, I get several failing tests. Is that normal when running `dotnet test`? One example:

```
[xUnit.net 00:00:06.24]     CanHandleUndefinedPrompt [FAIL]
[xUnit.net 00:00:06.24]       Assert.Equal() Failure: Strings differ
[xUnit.net 00:00:06.24]                  ↓ (pos 0)
[xUnit.net 00:00:06.24]       Expected: "> "
[xUnit.net 00:00:06.24]       Actual:   " "
[xUnit.net 00:00:06.24]                  ↑ (pos 0)
[xUnit.net 00:00:06.24]       Stack Trace:
[xUnit.net 00:00:06.24]         C:\Dev\repro\xunit2912\test\PowerShellEditorServices.Test\Session\PsesInternalHostTests.cs(169,0): at PowerShellEditorServices.Test.Session.PsesInternalHostTests.CanHandleUndefinedPrompt()
[xUnit.net 00:00:06.24]         --- End of stack trace from previous location ---
```

**Comment by bradwilson** [comment]
I can verify that in `PowerShellEditorServices.Test`, replacing all `async Task` with `async void` on your tests with 2.7.0 causes them all to pass again without being hung, so you're definitely running up against the lack of the sync context. I'll see if I can track down where some of the deadlock(s) might be.

**Comment by bradwilson** [comment]
First one was easy: `PowerShellEditorServices.Test.Language.CompletionHandlerTests.CompletesVariableInFile` was hung. The problem is this:

```csharp
        public void Dispose()
        {
#pragma warning disable VSTHRD002
            psesHost.StopAsync().Wait();
#pragma warning restore VSTHRD002
            GC.SuppressFinalize(this);
        }
```

I searched for `VSTHRD002` and converted all `IDisposable` to `IAsyncLifetime` (converting `Dispose` to `DisposeAsync`, then either adding an "empty" `InitializeAsync` or in one case converted a constructor with problematic waits into `InitializeAsync`).

This fixed everything except for `PowerShellEditorServices.Test.Debugging.DebugServiceTests`. All the tests here are still hanging, and the tasks list while hung looks like this:

![image](https://github.com/xunit/xunit/assets/16944/027ed75d-d76f-4acc-9e17-11a67459fcdf)

With this stack trace:

![image](https://github.com/xunit/xunit/assets/16944/b9a6a469-2710-49ce-9a0b-1ff22c73318c)

I peeked in on a few things and didn't see anything obvious, though the wording in `CancellationScope.Cancel` is a little scary. 😂 

Still looking to track down what appears now to just be a single deadlock source...

**Comment by bradwilson** [comment]
I'm able to work around whatever is causing the deadlock (somewhere inside PowerShell's shutdown system) by doing this in DebugServicesTests.DisposeAsync():

```csharp
await Task.Run(psesHost.StopAsync);
```

That's effectively what the async sync context ends up doing when scheduling new work to be done and there's no underlying sync context to delegate to. That fixes up the last deadlock in `PowerShellEditorServices.Test`.

Now time to check `PowerShellEditorServices.Test.E2E`...

**Comment by bradwilson** [comment]
Didn't see anything hanging in the end to end tests.

Would you like a PR?

**Comment by bradwilson** [comment]
Here's a patch file with just the .cs and .csproj changes: 
[xunit2.7.0.patch](https://github.com/xunit/xunit/files/14913153/xunit2.7.0.patch)

**Comment by andyleejordan** [comment]
@bradwilson you are _absolutely amazing_ thank you so much! I am out presenting at a conference today, but I will pull these fixes in. Really super appreciate it!

**Comment by andyleejordan** [comment]
Again, thanks so much! Closing this as resolved. I've got a PR with all tests passing now, and so many fewer deadlocks 😁
