### ISSUE TITLE
[Feature request] Natural number sequence Theory

### ISSUE THREAD

**Issue by xp44mm** [xunit/xunit#2918]
Natural number sequence Theory is the simplest form of testing our theory with data.

Currently, I use the `InlineDataAttribute` attribute to represent array indices

```F#
type NaturalNumberSeqTest(output: ITestOutputHelper) =
    [<Theory>]
    [<InlineData(0)>]
    [<InlineData(1)>]
    [<InlineData(2)>]
    [<InlineData(3)>]
    member _.``Natural number sequence``(i:int) =
        let expect = [0;1;2;3]
        let actual = [0;1;2;3]
        Should.equal expect.[i] actual.[i]
```

Feature request: same code using `NaturalAttribute` attribute

```F#
    [<Theory>]
    [<Natural(4)>]
    member _.``Natural number sequence``(i:int) =
        let expect = [0;1;2;3]
        let actual = [0;1;2;3]
        Should.equal expect.[i] actual.[i]
```

**Comment by bartelink** [comment]
[TheoryData is a good general base for stuff like this, rather than having such specific helpers](https://github.com/xunit/xunit/issues/2836)

Something like this:

```
type NaturalNumberSeqTest(output: ITestOutputHelper) =

    let nats = TheoryData(seq { 0..4 })
    [<Theory; MemberData(nameof nats)>]
    let ``Natural number sequence``(i:int) =
        let expect = [0;1;2;3]
        let actual = [0;1;2;3]
        Should.equal expect.[i] actual.[i]
```

(The fact that the example is very artificial for me gives away the fact that this is not your true requirement, but my general contention that having lots of generation helpers like this becomes very messy remains)

**Comment by bradwilson** [comment]
@bartelink's answer is a reasonable solution here.

Additionally, for re-usability you can create your own data sources by creating an attribute that derives from `DataAttribute`. Sample (utilizing `TheoryData`) in C#:

```csharp
[AttributeUsage(
public sealed class NaturalAttribute : DataAttribute
{
	private readonly TheoryData<int> values;

	public NaturalAttribute(int count) :
		this(0, count)
	{ }

	public NaturalAttribute(int start, int count) =>
		values = new TheoryData<int>(Enumerable.Range(start, count));

	public override IEnumerable<object[]> GetData(MethodInfo testMethod) =>
		values;
}
```

**Comment by xp44mm** [comment]
Your code has been worked perfectly for me, thank you. @bradwilson
