### ISSUE TITLE
Better test spec sharing

### ISSUE THREAD

**Issue by yufeih** [xunit/xunit#292]
When using `[Theory]` with `[MemberData]`, it is sometimes desirable to apply different traits for different member data.

Take for example a simple storage system abstracted by an `IStorage` interface
```c#
public interface IStorage
{
    Task StoreAsync(string name, byte[] bytes);
}
```

Ideally we want to just write a single test spec using Theory:
```c#
public class StorageSpec
{
    [Theory, MemberData("TestDimensions")]
    public Task it_should_store_bytes(IStorage storage)
    {
        return storage.StoreAsync("name", new byte[10]);
    }
}
```

Now suppose we have 2 implementations of `IStorage`. The first one backed by a local file system that runs extremely fast and runs everytime the project is rebuilt. The other is backed by a network service that is slow and is only triggered manually. 

There doesn't seem be an obvious way to **apply different traits to each test dimensions** in xunit. nunit has a `TestCaseData` class where you can attach category data to each dimension.

Now lets push this problem further. If I want to reuse this StorageSpec as a baseline for all IStorage implementations. These implementations can resides in different projects or assemblies that the test spec is unaware of. **Theory specs cannot be extended by classes in a separate assembly.**
Consider the following project setup:

```c#
ProjectA  // contains IStorage and StorageA
   |      |
   |    ProjectATest  // contains StorageSpec
   |          |
ProjectB      |  // contains StorageB
        |     |
       ProjectBTest  // wants to test StorageB using StorageSpec in PojectATest
```
It is hard for ProjectBTest to reuse the StorageSpec defined in ProjectATest.
- MemberData in ProjectATest cannot points to somewhere in ProjectBTest.
- MemberData uses a static member to retrieve test dimensions so it is hard for classes in ProjectBTest to properly inject dimensions

So are there any ways so enabled the above 2 scenarios? Or there are already ways to do it that I just don't know :)

**Comment by Clockwork-Muse** [comment]
I, too, would find a way to apply traits to individual runs would be useful.  For instance, in corefx some long-running tests are disabled unless specifically requested.  Since the only difference between many of these tests is the input data size, creating different tests (even if only empty wrappers) isn't something I should have to do.

**Comment by bradwilson** [comment]
After discussion, we've decided not to do this feature.
