### ISSUE TITLE
update to xUnitSummary.xsl (possibly for xUnit v2?)

### ISSUE THREAD

**Issue by qujck** [xunit/xunit#294]
Hi,

not really an issue but where is the source for xUnitSummary.xsl so I can fix it?

**Line 61:**
from:
```xsl
<xsl:apply-templates select="//assembly/class"><xsl ...
```
to:
```xsl
<xsl:apply-templates select="//assembly/collection"><xsl: ...
```

**Line 92:**
from
```xsl
<xsl:template match="class">
```
to
```xsl
<xsl:template match="collection">
```

**Comment by bradwilson** [comment]
We'd left it on CodePlex in a fairly undiscoverable place. My bad. :)

It's here now: https://github.com/xunit/samples/tree/master/CruiseControl.NET
