### ISSUE TITLE
Add CTRF report format

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#2942]
Requested here: https://github.com/xunit/xunit/issues/1052#issuecomment-2144076192

CTRF documentation: https://ctrf.io/docs/intro

**Comment by bradwilson** [comment]
Available in v3 `0.1.1-pre.474` https://xunit.net/docs/using-ci-builds

**Comment by pevnyk** [comment]
Hi @bradwilson 
Sounds great with integrated support for ctrf, thanks!

I'm not sure how to use it, though.
I'd like to have my xunit produce ctrf reports for my .net project(s) and avoid generating the .trx before converting to ctrf.
Can you help me understand how to do that in a GitHub actions context? (Currently I'm building + running tests using dotnet commands.)

**Comment by bradwilson** [comment]
How you use it depends on how you run your tests.

- For native xUnit.net command line UX, you use `-ctrf <filename>`:

  ![Image](https://github.com/user-attachments/assets/47ea5e30-8cd4-4618-95ee-29900197b6a4)

  This includes invoking the test project directly (either via the `.exe` file or via `dotnet run`) as well as running with `xunit.v3.runner.console.exe`.

- For the first party MSBuild runner (`xunit.v3.runner.msbuild`), you can add a property to your MSBuild task invocation:

  `<xunit Assemblies="<assemblyFiles>" Ctrf="<filename>" />`

- For Microsoft.Testing.Platform command line UX, you use `--report-ctrf` (and optionally `--report-ctrf-filename` if you want to pick the filename):

  ![Image](https://github.com/user-attachments/assets/4e4db0b1-dc2a-4fde-b435-b507211febca)

  This includes invoking the test project directly when you've compiled with `<UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>` as well as running with `dotnet test` when you've set `<TestingPlatformDotnetTestSupport>false</TestingPlatformDotnetTestSupport>`. (It is not possible to generate our CTRF report from `dotnet test` without enabling Microsoft Testing Platform mode.)

-----

It's important to note that the first-party runners (that is, directly running your project, using `xunit.v3.runner.console`, or using `xunit.v3.runner.msbuild`) will generate a single CTRF report that encompasses results from all test assemblies. When using Microsoft.Testing.Platform, you will get a single CTRF report for each test assembly, and it will live in the `TestResults` folder by default. You can override the output directory with `--results-directory`, but if you do that you should _**not**_ use `--report-ctrf-filename` because each test assembly will overwrite the results from the previous test assembly.

**Comment by pevnyk** [comment]
Thank you very much for the docs.

Sorry, if I seem a bit dull, but I didn't manage to get it working yet.

I've not previously spent any time on MTP, but I thought I'd give it a try.
This is what I've done:
1. Upgraded my MS test project to xunit.v3
2. Added a Directory.Build.props file in he solution root folder (to enable MTP)

Contents of Directory.Build.props:
```
<Project>
  <PropertyGroup>
	  <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
	  <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>
</Project>
```
When I run this in the solution root folder:
`dotnet test --report-ctrf
`
I get this response:
```
MSBUILD : error MSB1001: Unknown switch.
    Full command line: 'C:\Program Files\dotnet\sdk\9.0.102\MSBuild.dll -maxcpucount -verbosity:m -tlp:default=auto -nologo -restore --property:VsTestUseMSBuildOutput=true -target:VSTest -nologo -ctrf -property:VSTestArtifactsProcessingMode=collect -property:VSTestSessionCorrelationId=43256_8a0dcd17-ae23-4820-8293-3a557e799b44 -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\9.0.102\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\9.0.102\dotnet.dll'
  Switches appended by response files:
Switch: -ctrf

For switch syntax, type "MSBuild -help"

```
I get the same response from `dotnet test --ctrf`
I'm not even sure if I managed to enable MTP at all ?
Can you tell me, what I should try next?

**Comment by bradwilson** [comment]
`dotnet` command lines split up command line switches between "switches for the `dotnet` executable" vs. "switches for the program you're running", separated by `--`.

Try `dotnet test -- --report-ctrf`.

**Comment by xWiiLLz** [comment]
Hey, I just tried this with the CTRF [github-reporter](https://github.com/ctrf-io/github-test-reporter) and it seems like the file that's output by this feature is an UTF8 with BOM marker, which does not work well with node parsers.

You can try this by using the ctrf node package with the following command:
`npx ctrf flaky ./your-test-results.ctrf`.

I'm using this in CI and currently need to do some postprocessing for the github reporter to work.
<details>
<summary>Current post-processing bash script</summary>

```bash
find . -type f -name "*.ctrf" -exec sed -i '1s/^\xEF\xBB\xBF//' {} +
```
</details>

**Comment by pevnyk** [comment]
> `dotnet` command lines split up command line switches between "switches for the `dotnet` executable" vs. "switches for the program you're running", separated by `--`.
> 
> Try `dotnet test -- --report-crtf`.

That works for me.

Thanks! 👍

**Comment by LockTar** [comment]
> `dotnet` command lines split up command line switches between "switches for the `dotnet` executable" vs. "switches for the program you're running", separated by `--`.
> 
> Try `dotnet test -- --report-crtf`.

Small typo here.... `ctrf` and not `crtf`.
So use `dotnet test -- --report-ctrf --report-ctrf-filename testresults.ctrf.json`.

**Comment by bradwilson** [comment]
@LockTar Oops! Of course you're right. :)
