### ISSUE TITLE
Consider async Wait in test runner

### ISSUE THREAD

**Issue by johncrim** [xunit/xunit#2955]
I've been working through some deadlocks and other contention issues that have caused flaky tests in Azure Pipelines, and I came across an issue that I think should be addressed; or if not the response could help others facing the same issue.

The Azure Pipelines VMs have 2 CPUs, so we encounter test deadlocks/contention/slowdown in builds that are not an issue on dev machines. While inspecting a dmp file, I found the following:

![image](https://github.com/xunit/xunit/assets/3312127/9e49f908-bee9-468e-bc2b-ae0e4ae89eca)

![image](https://github.com/xunit/xunit/assets/3312127/c9b6c1b1-1bed-4843-8394-f18d6cab5aae)

I've seen this in a number of test runs.

The method in question is:
```
    /// <summary>
    /// This is the default implementation of <see cref="IExecutionSink"/>, which can perform several
    /// operations (including recording XML results, detecting long running tests, and failing skipped
    /// tests). This replaces the now deprecated delegating sink classes.
    /// </summary>
    public class ExecutionSink : LongLivedMarshalByRefObject, IExecutionSink
    {

        /// <summary>
        /// Performs a Task-safe delay. Overrideable for testing purposes.
        /// </summary>
        protected virtual bool WaitForStopEvent(int millionsecondsDelay)
            => stopEvent?.WaitOne(millionsecondsDelay) ?? true;
```

What do you think about turning this (and other similar code) into an async wait?

**Comment by bradwilson** [comment]
That function is called from within a worker thread to detect long-running tests. Converting it to async would not have any impact on the `Task` thread pool.

**Comment by johncrim** [comment]
Thank you @bradwilson for the reply - I wasn't aware that tests run on a separate thread pool, but it makes sense that they do. 

My follow on question is: are there any test runner settings that limit the size of the system thread pool, or is it effectively unlimited? If it's limited (eg to a small multiple of the number of CPUs) then consuming a thread can still matter. Though probably not worth the effort since I've only ever seen a single thread blocked. I'm happy to close this if it's a non-issue.

I'm aware that ManualResetEvent/WaitHandle don't provide an async `Wait()` method, I was thinking something along the lines of using a different primitive (`TaskCompletionSource`) or that plus `RegisterWaitForSingleObject`.

**Comment by bradwilson** [comment]
> My follow on question is: are there any test runner settings that limit the size of the system thread pool, or is it effectively unlimited?

The default size of the test thread pool is `Environment.ProcessorCount`.

https://xunit.net/docs/configuration-files#maxParallelThreads

**Comment by mihnea-radulescu** [comment]
The [SemaphoreSlim](https://learn.microsoft.com/en-us/dotnet/api/system.threading.semaphoreslim?view=net-8.0) class provides a [WaitAsync()](https://learn.microsoft.com/en-us/dotnet/api/system.threading.semaphoreslim.waitasync?view=net-8.0) method with multiple overloads.

There is also the rather naive solution of wrapping a synchronous wait in an _await Task.Run(() => synchronizationPrimitive.WaitOne())_ block.

**Comment by bradwilson** [comment]
The synchronous wait is already on a background thread.

**Comment by johncrim** [comment]
> > My follow on question is: are there any test runner settings that limit the size of the system thread pool, or is it effectively unlimited?
> 
> The default size of the test thread pool is [`Environment.ProcessorCount`](https://learn.microsoft.com/en-us/dotnet/api/system.environment.processorcount).

Thanks @bradwilson - I was asking if there were any changes to the _system_ threadpool max size from default - I'm aware of the `maxParallelThreads` option, which I presume only affects the test thread pool, not the system thread pool. If it did affect the system threadpool, then setting it to 1 would cause `WaitForStopEvent()` to block, I think.

Thank you for your responses... closing the issue.

**Comment by bradwilson** [comment]
@mihnea-radulescu Unfortunately, SemaphoreSlim is not available in .NET 3.5, which is one of the target frameworks for `xunit.runner.utility`.

**Comment by bradwilson** [comment]
@johncrim We will increase the minimum thread pool size if it's not large enough, but I can add a little extra "help" to make sure the minimum is larger than 1. 😄
