### ISSUE TITLE
Public class nested inside internal class gets discovered in xunit v3

### ISSUE THREAD

**Issue by estrizhok** [xunit/xunit#2959]
Xunit v3 0.1.1-pre.485 discovers `Test.OuterClass+InnerClass.TestMethod` test case when it is given the following definition:
```
using Xunit;

namespace Test {
    internal class OuterClass {
        public class InnerClass {
          [Fact] public void TestMethod() { }
        }
    }
}
```

This behavior is different from xunit v2 and looks like an oversight.

However, I generally disagree that internal classes cannot be tests. One particular case where I find it useful is when testing components while auto-mocking their dependencies. For that purpose I usually have a base test class that looks like this:
```
public abstract class TestsFor<TSubject> {
  protected TSubject Component { get; }

  // Code to instantiate component under test while mocking its dependencies
}
```

But if the component I want to test is an internal class (assuming I add a proper [InternalsVisibleTo] pointing to the test project), the following will not compile:
```
public class InternalComponentTests : TestsFor<InternalComponent> {
  // Tests here
}
```
One has to make `InternalComponentTests` internal as well.
This is why I use NUnit myself, which does not have this constraint.

**Comment by bradwilson** [comment]
> This behavior is different from xunit v2 and looks like an oversight.

I have verified that this is no longer an issue with `0.2.0-pre.8`.

> However, I generally disagree that internal classes cannot be tests.

This decision is driven by performance requirements. Scanning all non-public types in an assembly not only means scanning a LOT more types, it also means spending a lot more time doing reflection, as the internals of reflection do not cache information about non-public types.
