### ISSUE TITLE
Source Link and Deterministic builds aren't enabled:

### ISSUE THREAD

**Issue by thomhurst** [xunit/xunit#2971]
See here: https://nuget.info/packages/xunit.abstractions/2.0.3

When building on your build agent, the `<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>` property should be set.

And to enable source link, a `Directory.Build.props` file should exist with:  
`<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />`

**Comment by bradwilson** [comment]
We don't ship new versions of that package, so this will never be fixed. Sorry.

(The good news on the source front is: it would be pointless anyways. Everything in that package is an interface with no code in it.)
