### ISSUE TITLE
xUnit's Exceptions Are Not Serializable

### ISSUE THREAD

**Issue by martincostello** [xunit/xunit#298]
I have a suite of tests currently implemented using MSTest where a number of the tests execute in a new AppDomain within the test method to provide isolation for various reasons, such as allowing a custom ```.config``` file to be used for a single specific test.

I've been investigating migrating from MSTest to xUnit.NET v2 RC1 and I've found that the exceptions used by Xunit for failed assertions are not serializable. This means that when tests fail due to failed assertions, the true reason for the test failure is hidden by an error such as the following as the exception can't be remoted across to the original AppDomain of the test method:

```
System.Runtime.Serialization.SerializationException : Type 'Xunit.Sdk.IsTypeException' in assembly 'xunit.assert, Version=2.0.0.2826, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' is not marked as serializable.
```

I took a look at the code to see if this was just an oversight and I could submit a small PR to add this, but based on the FxCop suppression messages in the source code it appears support has been intentionally omitted for whatever reason.

Is this something that could be changed to support this use case? As it stands this renders xUnit.NET unsuitable for my needs as it makes diagnosing test failures in these scenarios where I use other AppDomains more onerous to triage.

**Comment by bradwilson** [comment]
We didn't bother to mark them serializable because we knew that in our scenario they wouldn't be traversing the app domain barrier.

It would be no problem to mark them serializable. It just seemed unnecessary at the time. :)

**Comment by bradwilson** [comment]
Actually, I take it back. We can't do this.

The assertion library is a PCL which targets platforms which do not support serialization.

**Comment by AArnott** [comment]
FWIW, your assertion library could multi-target such that platforms that do support serialization can do so without breaking compatibility with the lesser platforms.

**Comment by bradwilson** [comment]
We actually offer the assertion library as source, so this isn't as straightforward as you think it should be.

Regardless, I'm not sure why people need our exceptions to be serializable. We never send actual exception objects across the app domain boundary (obviously, or they wouldn't work at all). So why do you? :)

**Comment by AArnott** [comment]
We have unit tests that create AppDomains as a way to verify that the product loads assemblies in particular ways. As such, much of the body of those tests actually run in the AppDomain themselves and may call Assert.True and other such methods. When these fail, and the exception thrown, it crosses that AppDomain boundary and the test failure regresses from a useful one to a "the exception could not be serialized" one that doesn't tell us anything beyond something broke.

**Comment by bradwilson** [comment]
I believe your use case is best suited to taking our [assertion Github project](https://github.com/xunit/assert.xunit) as a Git submodule and update it to add serialization.

**Comment by AArnott** [comment]
OK. Would you accept a PR that adds this to each of your exception types?

```csharp
#if DESKTOP || NETSTANDARD2_0
[Serializable]
#endif
```

That way, it wouldn't break anyone who's already using your git submodule, but folks who support it can just work?

**Comment by bradwilson** [comment]
Is your goal here to allow people who bring this in via source to get serialization? If so, then I don't think attempting to use those #define's would be the right answer; instead, you'd want to use something that's specific to xUnit.net (like we already do [here](https://github.com/xunit/assert.xunit/blob/da9a45a84b285ff237e131aef907c76ec0d3ff3d/Assert.cs#L10).

**Comment by AArnott** [comment]
I don't understand. Are you suggesting that we change my example to `#if XUNIT_SERIALIZABLE`? If so, the reason I picked the ones I did is that `NETSTANDARD2_0` is defined by default by netstandard2.0 targeted projects. DESKTOP isn't, but as desktop-targeted projects have so many distinct symbols (NET2_0, NET3_5, etc.) it seems asking folks to define DESKTOP in their projects to get serialization is a reasonable requirement.

**Comment by bradwilson** [comment]
The point is, there's no reason to treat `netstandard2.0` with any kind of special status. At best, you'd be updating this every time a new build of netstandard comes out (and, as mentioned before, doesn't cover any desktop CLRs, nor any versions of .NET Core). Finally, we generally do our best to discourage people from writing PCL or netstandard unit test libraries, because such a library fails to accurately declare the target platform.

**Comment by onovotny** [comment]
I agree that with @bradwilson that in this case, a feature-flag-style `XUNIT_SERIALIZABLE` is more in-line with how things have been working. It also insulates you from a specific platform version too. Once UWP supports .NET Standard 2.0, it'll also have the attribute, so there's another case where you'd need an ifdef or just use a feature-based one.

**Comment by AArnott** [comment]
Ok, good points. I'll send a PR with the proposed changes.
