### ISSUE TITLE
XunitFrontController.Create is not friendly to debuggers

### ISSUE THREAD

**Issue by estrizhok** [xunit/xunit#2987]
When implementing a custom runner/test adapter for xunit v3, there are two possible ways to go about it:

1. By using `XunitFrontController.Create`, or
2. by using `InProcessFrontController`.

The difference between the two is that the first will start a child process actually running tests, whereas the second will run them in the same process. Initially I tried going with the first option, so as to adhere with the shift towards 'test projects are applications`. However, a problem quickly surfaced that if you try to run tests under a debugger, there is no thing like "ProcessService" one could substitute to start the process that actually runs tests under a debugger.

It works for Visual Studio and xunit3 adapter, because TestPlatform extension built-in in VS does a trick for the testhost.exe process it originally starts under debug, and every child process spawned from it will also start under debug. However, this requires special support on the debugger side, and while VS debugger has it, Rider debugger at this moment unfortunately has not.

That's why I went with the option #2. And while it works, some of xunit3 own tests fails with it, because they call to `Assembly.GetEntryAssembly()`, and it returns not the assembly with tests.

Do you think it makes sense to introduce some sort of substitutable "ProcessService" to overcome this issue?

**Comment by bradwilson** [comment]
Yeah, I probably need to make the delineation clearer.

`InProcessFrontController` is what's used be `Xunit.Runner.InProc.SystemConsole` to run tests that are in the same assembly as the runner; that is, it's what provides the stand-alone executable the ability to run itself. As such, it can only run v3 tests.

`XunitFrontController` is what's used by multi-assembly runners (like `xunit.v3.runner.console` or `xunit.runner.visualstudio`) to run one or more assemblies at the same time, and supporting v1/v2/v3 test assemblies.

> However, a problem quickly surfaced that if you try to run tests under a debugger, there is no thing like "ProcessService" one could substitute to start the process that actually runs tests under a debugger.

We have an option for this now, to tell the in-process runner to wait for a debugger to attach. The flag is in `XunitProject.Configuration.WaitForDebugger`. We use this in `xunit.runner.visualstudio` to attach the debugger to the launched process when we detect we're running inside a debugger: https://github.com/xunit/visualstudio.xunit/blob/d4c272148d87c15d9f990f04058445541f152cf5/src/xunit.runner.visualstudio/VsTestRunner.cs#L603-L610

> It works for Visual Studio and xunit3 adapter, because TestPlatform extension built-in in VS does a trick for the testhost.exe process it originally starts under debug, and every child process spawned from it will also start under debug.

That's not actually how it works, at least for us. We use APIs from VSTest to attach the debugger, but it doesn't do it automatically.

> Do you think it makes sense to introduce some sort of substitutable "ProcessService" to overcome this issue?

I'm not sure if I know exactly which problem you're trying to solve at this point, so... if my answers haven't helped, maybe ask another question? 😄

**Comment by bradwilson** [comment]
This is where we wait for the debugger in ConsoleRunner: https://github.com/xunit/xunit/blob/e98cd61f9d1ed581e88797e5b42427fbeaa092c2/src/xunit.v3.runner.inproc.console/ConsoleRunner.cs#L181-L193

**Comment by bradwilson** [comment]
I assume the Resharper/Rider runner would have some similar facility to be able to attach a debugger, and you'd use it much like we do in `xunit.runner.visualstudio`.

**Comment by estrizhok** [comment]
Indeed! Thank you, guys. I missed that you manually attach to the process. Only inspected the path where you start the process. Still, why have you chosen to attach instead of starting it under debug? Is there a reason behind it? I generally think that starting under debug is better, because it eliminates to possibility that JIT optimises something useful away before the debugger is attached.

**Comment by bradwilson** [comment]
> I generally think that starting under debug is better

We are limited by the available APIs. There's no API provided by VSTest to launch with the debugger, and the variety of run environments we're in means in some cases (like in VS Code) there is no public debugger API at all. The only path into the debugger is the one provided by VSTest.

**Comment by estrizhok** [comment]
> There's no API provided by VSTest to launch with the debugger, 

What do you mean? The interface `IFrameworkHandle2` that you use to attach to the process is an extended version of an even older interface `IFrameworkHandle` that always had a method to start a process under debugger: `IFrameworkHandle.LaunchProcessWithDebuggerAttached`.

**Comment by bradwilson** [comment]
Hmm, I would need to rework the interfaces to allow the process to be launched by something else. Lemme think about that.

**Comment by bradwilson** [comment]
I have looked into this, and at the moment there is a showstopper for us: inability to redirect StdIn and StdOut (which is necessary for the way we do our communication. https://github.com/microsoft/vstest/issues/5171

**Comment by bradwilson** [comment]
I have a branch that introduces `ITestProcessLauncher`, and even though I probably won't be able to use it from `xunit.runner.visualstudio`, it may be usable for someone else who has direct access to a debugger: https://github.com/xunit/xunit/compare/main...ITestProcessLauncher

It could also in theory be used to launch the test process elsewhere (like a remote server, a Docker container, etc.), anywhere that you could effectively get a TextReader/TextWriter style stream for communication.

**Comment by bradwilson** [comment]
After discussing it with the VSTest team, there is no more for me to do here. They cannot launch in such a way that would allow StdIn/StdOut to be redirected to me. Additionally, our analysis agrees that optimization shouldn't be a problem for anybody launching a unit test project for debugging, because presumably it's a Debug build (so that it can be debugged) which has optimization turned off by default. If someone is in an odd scenario of needing to debug a unit test project that's optimized, then can simply turn off optimization before launching the debugger.

I will eventually merge the `ITestProcessLauncher` change, which would allow anybody else with their own debugger to launch via the debugger instead of being forced to launch locally and then attach the debugger later. However, `xunit.runner.visualstudio` will continue to use the standard launch + attach because that's the only option that's available to us.

**Comment by bradwilson** [comment]
The `ITestProcessLauncher` change was added here: https://github.com/xunit/xunit/commit/b7ac3c71a4ed1677c50b57e485956447e7508f94

It will be available in `0.3.0-pre.5` as soon as the build finishes. https://xunit.net/docs/using-ci-builds
