### ISSUE TITLE
Failed to update package.config when added to project from Nuget Manager

### ISSUE THREAD

**Issue by gdennie** [xunit/xunit#299]
I was able to add this package to my solution but not to my project. It was failing to update my project level packages.config. However, it worked after manually copying the specification into the project config,

  &lt;package id="xunit.runner.visualstudio" version="2.0.0-rc1-build1030" targetFramework="net451" />,

enabling Nuget package restore, and re-building the project in question.

**Comment by bradwilson** [comment]
You can't hand edit the packages.config here, because package installation makes changes to your .csproj file.
