### ISSUE TITLE
Add an analyzer which recommends nameof usage

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#2991]
Whenever we use `string` properties on attributes intended to point at a member, we should encourage the use of `nameof` rather than hard-coded strings.

This includes, at least (please look and see if there are others):

- `IFactAttribute.SkipUnless`
- `IFactAttribute.SkipWhen`
- `MemberDataAttribute` constructor

**Comment by bradwilson** [comment]
@hpatel292-seneca Sure!

**Comment by hpatel292-seneca** [comment]
Hi @bradwilson 

I wanted to confirm if I should proceed with updating the XML documentation for the `MemberDataAttribute` class to encourage the use of the `nameof` operator for the `memberName` parameter. Specifically, I would add a recommendation in the `<param>` tag, such as:

> "It is recommended to use the `nameof` operator to ensure compile-time safety, e.g., `nameof(SomeMemberName)`."

Please let me know if this approach aligns with the project's guidelines or if additional changes are needed.

**Comment by bradwilson** [comment]
@hpatel292-seneca Yep, that'd be a great addition to all the common places people should be using nameof.
