### ISSUE TITLE
Have the built-in possibility to sort tests by name in a test class

### ISSUE THREAD

**Issue by Scal-Human** [xunit/xunit#2999]
As explained in [Order by test case alphabetically](https://learn.microsoft.com/en-us/dotnet/core/testing/order-unit-tests?pivots=xunit) the first thing you have to do to sort tests is to write an orderer class. Why XUnit does not provide it ?
The second thing is to mark the tests class with a TestCaseOrdererAttribute which is not based on a type but on hardcoded strings.
As this attribute is marked as sealed, we cannot make it more friendly by using a type as parameter.
The third thing is that whenever, for instance, the ordererAssemblyName hardcoded string of the TestCaseOrdererAttribute is incorrect, XUnit silently ignores the attribute.

**Comment by bradwilson** [comment]
> Why XUnit does not provide it ?

We randomize tests because it is our opinion that writing unit tests that are order dependent is a testing smell. That's why we don't give you an easy ability to write tests this way. We gave the ability to do this via extensibility for those whose opinion differs.

**Comment by Scal-Human** [comment]
Thank you.
