### ISSUE TITLE
Range and Index should be serializable

### ISSUE THREAD

**Issue by JakeYallop** [xunit/xunit#3003]
`Range` and `Index` are inbox runtime types so cannot be customized, meaning `IXunitSerializable` cannot be added to them. Additionally, each type already overrides `ToString` to give a human readable representation of its value.

For `Range`:
```csharp
var r = (1..10).ToString(); // "1..10"
var r2 = (1..^1).ToString(); // "1..^1"
```

For `Index`:
```csharp
var i = ((Index)1).ToString(); // "1"
var i2  = (^1).ToString(); // "^1"
```

**Comment by bradwilson** [comment]
Available in v3 `0.3.0-pre.6` https://xunit.net/docs/using-ci-builds
