### ISSUE TITLE
Add test class instance to `TestContext`

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#3005]
As requested by @SimonCropp: https://hachyderm.io/@simoncropp/112945826013800654

**Comment by SimonCropp** [comment]
thanks

**Comment by bradwilson** [comment]
This adds `TestContext.TestClassInstance`. It will be `null` unless all of the following are true:

- `TestContext.PipelineStage` is `TestPipelineStage.TestExecution`
- `TestContext.TestStatus` is `TestEngineStatus.Running`
- The test class instance has been created and not yet disposed

In practice, that means the value will be available during:
- `TestRunner.PreInvoke` (where `XunitTestRunner` calls the `BeforeAfterTestAttribute.Before` methods)
- `TestRunner.InvokeTestAsync` (where `XunitTestRunner` invokes the test method via reflection)
- `TestRunner.PostInvoke` (where `XunitTestRunner` calls the `BeforeAfterTestAttribute.After` methods)

If the test method is static, there is no instance of the test class created, so the value will always be `null` for static test methods.

**Comment by bradwilson** [comment]
Available in `0.3.0-pre.10` https://xunit.net/docs/using-ci-builds
