### ISSUE TITLE
xUnit1039 fires on generic methods with generic array or enumerable argument

### ISSUE THREAD

**Issue by StefanLochauMF** [xunit/xunit#3007]
I'm getting a xUnit1039 when using `[MemberData(...)]` and a constrained generic test method with an argument type that is different from the type parameter. The warning is also on the argument, not on the attribute.

Example where the "different" type is an array:

```csharp

public class EnumExtensionsTest
{
    public enum MyEnumeration { A, B }
    
    public static TheoryData<MyEnumeration[]> MyEnumerationArrays =
        new(
            [],
            [MyEnumeration.A],
            [MyEnumeration.B],
            [MyEnumeration.A, MyEnumeration.B]);
    
    [Theory]
    [MemberData(nameof(MyEnumerationArrays))]
    public void TestEnum<T>(T[] enumerationValues)
        where T : struct, Enum
    {
        // test logic
    }
}    
```

Compiling this gives me:
`error xUnit1039: The type argument EnumExtensionsTest.MyEnumeration[] from EnumExtensionsTest.MyEnumerationArrays is not compatible with the type of the corresponding test method parameter enumerationValues. (https://xunit.net/xunit.analyzers/rules/xUnit1039)`

For arrays in particular I can get rid of the warning by using `params` on the argument, but then the test will fail with a `NotSupportedException` at runtime.

Similarly with with other generic types:
```csharp
public class EnumExtensionsTest
{
    public enum MyEnumeration { A, B }

    public record SomeGeneric<T>(T Value) where T : struct, Enum;

    public static TheoryData<SomeGeneric<MyEnumeration>> SomeGenerics =
        new(
            new SomeGeneric<MyEnumeration>(MyEnumeration.A),
            new SomeGeneric<MyEnumeration>(MyEnumeration.B));

    [Theory]
    [MemberData(nameof(SomeGenerics))]
    public static void TestEnum<T>(SomeGeneric<T> value)
        where T : struct, Enum
    {
        // test logic
    }
}
````

When ignoring the issue using `#pragma warning disable xUnit1039`, the code compiles and the tests run as expected.

**Comment by bradwilson** [comment]
I can repro this with the analyzer, but I'm not able to get the repro to trigger in a unit test, which means it's probably caused by a later version of Roslyn than we use during compilation.

This is gonna take some work to find a way to get a fixable repro.

**Comment by bradwilson** [comment]
Okay, even stranger: I can't get it repro in a unit test even with the Roslyn 4.11. 🤔

**Comment by bradwilson** [comment]
Your test passes on my machine, too, in all four combinations (.NET Framework vs. .NET, and Roslyn 3.11 vs. 4.11). I even tried Release vs. Debug. 😭

**Comment by bradwilson** [comment]
I'm gonna set up a clean Win11 VM and see if I can get it to repro there.

**Comment by bradwilson** [comment]
Doesn't repro on a clean VM, either. 😞 

![image](https://github.com/user-attachments/assets/3669a30f-6ade-4837-90bb-46444ad3dd1b)

**Comment by bradwilson** [comment]
Okay, major facepalm: I put it in the wrong X1039 test suite. 🤦🏼‍♂️ 

At least now it repros for me. 😂

**Comment by bradwilson** [comment]
So it's both `T[]` and `IEnumerable<T>` that are affected here, because our handling for type parameters did not extend to arrays and enumerable. When you use `params`, as you noted above, the problem doesn't surface because we handle `params` arrays different than non-`params` arrays (and at that point our type compatibility test would be `object` vs. `T`, which we already handled).

**Comment by bradwilson** [comment]
Available in `1.16.0-pre.29` https://xunit.net/docs/using-ci-builds

**Comment by StefanLochauMF** [comment]
Alright, that should probably cover most cases.
Ideally it would work for any generic wrapping `T`.
However, looking a bit into analyzers, I understand that implementing generic type inference is probably an enormous amount of complexity for very little gain.
Thank you, Brad.

**Comment by oliverjanik** [comment]
Hello was this released with 1.16.0 ? 

![image](https://github.com/user-attachments/assets/fd47a21e-de45-4028-9341-18d814d9994c)
![image](https://github.com/user-attachments/assets/e9ce3ae9-f6b3-4fab-a435-5d6550124d08)

Or it only applies to to first level `IEnumerable<T>` but not for e.g. `IEnumerable<IEnumerable<T>>` ?

**Comment by StefanLochauMF** [comment]
> Or it only applies to to first level `IEnumerable<T>` but not for e.g. `IEnumerable<IEnumerable<T>>` ?

The way I as issue creator read [the source](https://github.com/xunit/xunit.analyzers/blob/f3e93838e8dcc8eefb9256d2dea0b3f33f0389b9/src/xunit.analyzers/Utility/SymbolExtensions.cs#L155), it only applies to `IEnumerable<T>` or `T[]`. For all other generics (like `IEnumerable<IEnumerable<T>>` or `MyGeneric<T>`) the analyzer still fires a false positive.

At a short glance, adding support for arbitrary generics seems like a large task, basically amounting to re-implementing Roslyn's type inference.

**Comment by bradwilson** [comment]
You are correct, we generally don't try to replicate the compiler. The top level of this felt worth fixing; chasing down a potentially infinite `IEnumerable<IEnumerable<IEnumerable<IEnumerable...` does not.
