### ISSUE TITLE
Shared Context and Parallelization are two separate and district concepts...

### ISSUE THREAD

**Issue by TristenFielding** [xunit/xunit#3008]
What happened to the principle of Separation of Concern?

We use Class and Collection Fixtures to control the scope of expensive setup and cleanup. However, some of our tests that use the same Collection Fixture can't be parallelized, while others can, and tests that use a Class Fixture can run parallel. What is the harm in using a different attribute that indicates which classes can be parallelized with each other and which cannot without commingling the concept with a shared setup and cleanup?

For example, in one of our projects, we use a Collection Fixture to create and delete a shared test database, where all the tests that use this Collection Fixture also use transactions that are then rolled back at the end of each test. Thus, keep the test database "clean". Therefore, ALL the tests associated with the Collection Fiture can run in parallel. 

On the other hand, we can't use this approach due to technical issues with transactions and the code-under-test. Therefore, we are using a Class Fixture to create and delete a non-shared test database. Thus, the tests within this class cannot be run in parallel.

**Comment by bradwilson** [comment]
> What happened to the principle of Separation of Concern?

It got laid off in 2008 and couldn't find a job. 😂 

> What is the harm in using a different attribute that indicates which classes can be parallelized with each other and which cannot without commingling the concept with a shared setup and cleanup?

This issue is a encapsulated in one or both of these:

https://github.com/xunit/xunit/issues/1986
https://github.com/xunit/xunit/issues/2055
