### ISSUE TITLE
Bug in Latest NuGet Package?

### ISSUE THREAD

**Issue by dcjulian29** [xunit/xunit#302]
The latest version has broken my CI builds...
```
Executing xUnit
'xunit.runners 2.0.0-rc2-build2857' already installed.
Executing UnitTest
xUnit.net console test runner (64-bit .NET 4.0.30319.34209)
Copyright (C) 2015 Outercurve Foundation.

Discovering: UnitTests
System.MissingMethodException: Constructor on type 'Xunit.Sdk.TestFrameworkProxy' not found.
Error: 2/18/2015 12:03:49 PM:
At C:\Program Files\WindowsPowerShell\Modules\psake\psake.psm1:147 char:17 +                 throw ("Exec: " + $errorMe
ssage) +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: Exec: Error executing command  & $xunit "
$release_directory\UnitTests.dll" .
```
Hard-coding the 2.0.0-rc1-build2826 version resolves the issue...

**Comment by bradwilson** [comment]
I'm confused: are you using RC1 or RC2? You can't mix the two.

**Comment by dcjulian29** [comment]
I wasn't... but your comment made me go back and look at the "packages" folder... I do a package restore based on the packages.config file which contains the rc1 versions of: xunit, xunit.abstractions, xunit.assert, xunit.core, and xunit.extensibility.core. The build script does an "install" of the xunit.runners package to get the console version. There is no dependency listed for the NuGet package so I would expect that these other versions don't matter _**but**_ I'm thinking that the console runner is trying to use some or all of the v1 DLLs from the other packages during the build which is causing the issue. Upgrading all of the other xunit packages removed the issue. Not having the dependency on the runner package lead me to believe that the runner had everything it need to run the test...

**Comment by bradwilson** [comment]
So it sounds like you've resolved your issue, right? :)

**Comment by dcjulian29** [comment]
Yes, it did... ;)

But I wonder if the runners "depend" on the other packages, shouldn't the .nuspec files for the runners be updated to reflect that...

**Comment by bradwilson** [comment]
Runners don't depend on other packages, but during the pre-release process, we occasionally change the way things talk to each other in an incompatible way.
