### ISSUE TITLE
TestMethodArguments is empty when run on the command line

### ISSUE THREAD

**Issue by SimonCropp** [xunit/xunit#3020]
Given this test
```
public class ParametersSample
{
    [Theory]
    [InlineData(1)]
    public void Method(int arg)
    {
        var testCase = (XunitTestCase)TestContext.Current.TestCase!;
        Assert.Equal(arg, testCase.TestMethodArguments[0]);
    }
}
```

 * if i run via the rider test runner it passes
 * if i run it via `dotnet test` it fails with empty TestMethodArguments
 * if i run by executing the resulting .exe it fails with empty TestMethodArguments

**Comment by bradwilson** [comment]
Yeah, I understand why, but it's probably not obvious.

* "Run via Rider" has pre-enumerated theories on (by default).
* "Run via `dotnet test`" has pre-enumerated theories off (by default).
* "Run directly" has pre-enumerated theories off (by default).

So you're looking at the test case, not the test. When pre-enumerated theories are off, you get a _single test case per theory_, with multiple tests reporting to that one test case. When pre-enumerated theories are on (and the theory data is serializable), then you get a _single test case per data row_, with a single test reporting into each test case.

We could (but don't currently) expose the test method arguments to `IXunitTest`.

**Comment by SimonCropp** [comment]
so with "pre-enumerated theories off" how do i get the arguments?

**Comment by SimonCropp** [comment]
or does "We could (but don't currently) expose the test method arguments to IXunitTest."
mean it is not possible at the moment?

**Comment by bradwilson** [comment]
Correct, it's not possible at the moment.

Also, you're probably just experimenting right now, but I would not do `(XunitTestCase)TestContext.Current.TestCase!`. Instead, you should do `TestContext.Current.TestCase as IXunitTestCase` and check for `null`. Not every test framework is going to implement their test cases as `IXunitTestCase`, and you will have a cast failure in that case.

**Comment by SimonCropp** [comment]
is it possible to change the context to have TestMethodArguments exposed at the root for all scenarios?

so we can have TestContext.Current.Arguments

**Comment by bradwilson** [comment]
> is it possible to change the context to have TestMethodArguments exposed at the root for all scenarios?

That's not compatible with the extensibility design of the system. Even supposing that the test is based on a method is not something that's required. That's definitely the wrong layer to expose such a thing.

I'm planning to hang it off of `IXunitTest`, so your test will look like this:

```csharp
public class ParametersSample
{
    [Theory]
    [InlineData(1)]
    public void Method(int arg)
    {
        var test = TestContext.Current.Test as IXunitTest;
        Assert.NotNull(test);
        Assert.Equal(arg, test.TestMethodArguments[0]);
    }
}
```

**Comment by bradwilson** [comment]
Available in `0.3.0-pre.30` https://xunit.net/docs/using-ci-builds

**Comment by SimonCropp** [comment]
@bradwilson you are awesome

**Comment by bradwilson** [comment]
One thing I'll add: if you feel like you're in a situation trying to peek inside a concrete type to find a value that's not available via an interface or some other official source, please open an issue so I can evaluate whether what you're looking for is something that I can make more easily available, like this. 😄
