### ISSUE TITLE
Theory treats null and string.Empty inline data parameters as identical

### ISSUE THREAD

**Issue by AlexanderSher** [xunit/xunit#303]
Running this test results an error: 
> An exception occurred while invoking executor 'executor://xunit/VsTestRunner2': An item with the same key has already been added.

```
[Theory]
[InlineData(null)]
[InlineData("")]
public void Test(string input)
{
}
```

**Comment by AlexanderSher** [comment]
Looks like the issue is in `XunitSerializationInfo.Deserialize`:
```
public static object Deserialize(Type type, string serializedValue)
{
    if (serializedValue == "")
        return null;
```

For empty string, it doesn't check the type and returns null even if the type is string that should be deserialized into empty string.

**Comment by davidnmbond** [comment]
Seems that this is still broken?

**Comment by bradwilson** [comment]
Please open a new issue with a repro.
