### ISSUE TITLE
Feature Request: Add System.Guid and System.Uri as intrinsics for theory data serialization

### ISSUE THREAD

**Issue by markusschaber** [xunit/xunit#3038]
In https://github.com/xunit/xunit/discussions/2506#discussioncomment-3089302 there's a list of intrinsics defined for serialization of theory data.

As discussed in https://github.com/xunit/xunit/discussions/2506#discussioncomment-10810716, I kindly request you add `System.Guid` and `System.Uri` to the list of supported intrinsics - both are commonly used types in the framework, with a straight forward, lossless text/string representation for each of them.

**Comment by markusschaber** [comment]
For `System.Uri`, I think that `Uri.OriginalString` is the lossless variant, together with the `new Uri(string, UriKind)` constructor with `UriKind.RelativeOrAbsolute`.
For `System.Guid`, simply using `ToString()` and either `new Guid(string)` or `Guid.Parse(string)` should do the trick.

**Comment by bradwilson** [comment]
Available in v3 `0.5.0-pre.16` https://xunit.net/docs/using-ci-builds

**Comment by bradwilson** [comment]
Also, out of necessity, `Uri` is supported by `Assert.Equivalent` now 😁
