### ISSUE TITLE
"ExceptionAggregator.cs not found"

### ISSUE THREAD

**Issue by jcollum-hcg** [xunit/xunit#305]
I'm running into a strange issue trying to get a test to run. When I step into the code, once I try to step out of the ctor for my test class, I get this: 

```
ExceptionAggregator.cs not found

Locating source for 'c:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.core\Sdk\ExceptionAggregator.cs'. Checksum: MD5 {fb 54 73 ac 52 6f 84 df ee 97 6 dc 5f bb e8 ce}
The file 'c:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.core\Sdk\ExceptionAggregator.cs' does not exist.
Looking in script documents for 'c:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.core\Sdk\ExceptionAggregator.cs'...
Looking in the projects for 'c:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.core\Sdk\ExceptionAggregator.cs'.
The file was not found in a project.
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\crt\src\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\crt\src\vccorlib\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\src\mfc\'... 

```

Version is: `xunit.core 2.0.0-rc2-build2857`

The code looks like: 

```
namespace Test.Common.Data.DAL
{
	public class Test
	{
		Mock<IApplicationData> appData;
		Mock<IRemoteConfig> config;

		public Test()
		{
			this.appData = new Mock<IApplicationData>();
			this.config = new Mock<IRemoteConfig>();
		}

```

If I try to step past `this.config` I get the error.

**Comment by bradwilson** [comment]
It sounds like the debugger is trying to step into xUnit.net code and cannot find it. That's normal behavior for third party libraries.

**Comment by jcollum-hcg** [comment]
Not really, if it was trying to step into third party code it would be at least able to find the type and then say that the code is not available for that assembly: https://msdn.microsoft.com/en-us/library/3sehk0fb.aspx

**Comment by andyliau** [comment]
It's the thread issue.

When stepping through debugging, it switches to the different thread (xUnit runner).

**Comment by andyliau** [comment]
The solution is not to debug under "Release" build.

**Comment by HermanCordes** [comment]
I'm having the same issue under "Debug" build. I'm not stepping into xUnit code, but it displaying the "ExceptionAggregator.cs not found" message anyway.

I imagine @andyliau solved this issue on their solution because some property differs between Debug and Release. What property of the build configuration is causing this issue?

**Comment by weitzhandler** [comment]
Same issue here.
