### ISSUE TITLE
Array serialization broken for arrays of custom serialized types due to incorrect array type

### ISSUE THREAD

**Issue by mellis-ao** [xunit/xunit#3051]
I have been setting up the xUnit v3 preview packages on my company code base to identify any breaking changes that we can proactively fix before the official release. Unfortunately there seems to be an issue with arrays of enums causing the following error to occur during the test run:

Catastrophic failure: System.Collections.Generic.KeyNotFoundException: The given key 'IXunitSerializer' was not present in the dictionary.

Screenshot:

![image](https://github.com/user-attachments/assets/9fd92d58-a4b5-4a37-b070-2b03e544b483)

I narrowed down the issue manually by running smaller and smaller sets of tests until I ended up with a number of tests causing problems. Below is some sample code you can run to reproduce the issue:

```
public class Test
{
	public enum Numbers
	{
		One = 1,
		Two = 2,
		Three = 3,
	}

	[Theory]
	[InlineData(new Numbers[] { Numbers.One, Numbers.Two, Numbers.Three })]
	public void TestMethod(Numbers[] testEnumValues)
	{
		Assert.NotEmpty(testEnumValues);
	}
}

```
Package versions:

Runner: 3.0.0-pre.42
xunit.v3: 0.50-pre.27

![image](https://github.com/user-attachments/assets/1a6b22e7-ab26-433c-8bf3-4fbcfc624bb6)

If you need any more information, please let me know.

**Comment by bradwilson** [comment]
This is available in:

* v3 core framework `0.6.0-pre.6`
* xunit.runner.visualstudio `3.0.0-pre.49`

Please upgrade both when testing the fix. https://xunit.net/docs/using-ci-builds
