### ISSUE TITLE
`Skip` family properties cause error in custom attributes

### ISSUE THREAD

**Issue by behrouz-rad** [xunit/xunit#3071]
If you create a custom `FactAttribute` (or even a simple attribute) and apply it to a test method, using the Skip family properties results in an error in the test runner instead of displaying a warning that the test was skipped.
Using `Skip` family properties directly in test methods works as expected.

```csharp
// Attribute
[AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
public class MyAttribute : FactAttribute
{
  public MyAttribute()
  {
    Assert.SkipUnless(1==2, "My Reason");
  }
}

// Test method
[My]
public void My_Test_Method()
{
}

// Error in test runner:
Stack Trace: 
MyAttribute.ctor() line 14
CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
Attribute.GetCustomAttributes(MemberInfo element, Boolean inherit)
Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
Lazy`1.CreateValue()
```

**Comment by bradwilson** [comment]
That's not how that's intended to be used. `Assert.SkipUnless` is for use within the test, not with the attribute.

FactAttribute has a settable `SkipUnless` property that's intended to point to a static public property that will be read at the appropriate time. So what you want is this:

```csharp
public class MyAttribute : FactAttribute
{
    public MyAttribute()
    {
        Skip = "My Reason";
        SkipUnless = nameof(ShouldRun);
    }

    public static bool ShouldRun => 1 == 2;
}
```

**Comment by bradwilson** [comment]
Also, you don't need a custom attribute for this. Instead, you could just do this:

```csharp
public static bool ShouldRun => 1 == 2;

[Fact(Skip = "My Reason", SkipUnless = nameof(ShouldRun))]
public void My_Test_Method()
{
}
```

**Comment by behrouz-rad** [comment]
> That's not how that's intended to be used. `Assert.SkipUnless` is for use within the test, not with the attribute.
> 
> FactAttribute has a settable `SkipUnless` property that's intended to point to a static public property that will be read at the appropriate time. So what you want is this:
> 
> ```cs
> public class MyAttribute : FactAttribute
> {
>     public MyAttribute()
>     {
>         Skip = "My Reason";
>         SkipUnless = nameof(ShouldRun);
>     }
> 
>     public static bool ShouldRun => 1 == 2;
> }
> ```

Thanks for the answer.

Something strange happens with this code.

It seems that xUnit expects to see `ShouldRun` in the test class as well. This means I have to define `ShouldRun` twice: once in the custom attribute class and once in the test class. However, only the one in the test class will be considered!

```
Cannot find public static property 'ShouldRun' on type 'MyProject.MyTestClass' for dynamic skip on test method 'MyProject.MyTest'
```

**Comment by bradwilson** [comment]
Sorry, I forgot to mention that if you're putting it in the attribute, you need to use `SkipType` as well (set it to the attribute type).
