### ISSUE TITLE
`xunit.v3`: "Zero test run" from filtered assembly is treated as error when running with `Microsoft.TestPlatform` and `dotnet test`

### ISSUE THREAD

**Issue by julealgon** [xunit/xunit#3077]
# Description
I encountered a scenario where if an entire assembly is skipped by a test filter when running using TestPlatform and `dotnet test`, the 0-tests run on that assembly is mistakenly considered as an error.

This is causing friction in our real solution where we want to mark a couple of projects out of dozens as fully integration test assemblies and skip those during CI/CD.

# Sample repro:
- https://github.com/[julealgon/xunitv3-full-asm-ignore-issue](https://github.com/julealgon/xunitv3-full-asm-ignore-issue)

This repo contains a solution with 2 test projects, `Project1` and `Project2`, created using the default xunit v3 project templates. 

Both projects have been changed to enable the `TestingPlatformDotnetTestSupport` MSBuild flag so they can be executed using `dotnet test`.

`TraitAttribute` was added to `Project2` with a "Category=IntegrationTests" trait pair, while `Project1` was not marked.

When running `dotnet test` against this solution and filtering out "Category=IntegrationTests", we observe that the run is considered to have errors, as the following message is presented:
> Project2 test failed with 1 error(s)

However, when looking at the underlying log file, no error is present. The fact that the project ended up having zero tests in it run causes it to be reported as an error instead of a success.

# Repro steps:
- navigate to the root of the repo
- run `dotnet test -- --filter-not-trait "Category=IntegrationTest"`
- observe how `Project2`'s skip is treated as an error

```
Restore complete (0.3s)
  Project2 succeeded (0.3s) → Project2\bin\Debug\net8.0\Project2.dll
  Project1 succeeded (0.4s) → Project1\bin\Debug\net8.0\Project1.dll
  Project2 test failed with 1 error(s) (0.4s)
    C:\git\julealgon\xunitv3-full-asm-ignore-issue\Project2\bin\Debug\net8.0\Project2.dll : error run failed: Tests failed: 'C:\git\julealgon\xunitv3-full-asm-ignore-issue\Project2\bin\Debug\net8.0\TestResults\Project2_net8.0_x64.log' [net8.0|x64]
  Project1 test succeeded (0.4s)

Test summary: total: 1, failed: 0, succeeded: 1, skipped: 0, duration: 0.5s
Build failed with 1 error(s) in 1.3s
```

Contents of the linked file above, `C:\git\julealgon\xunitv3-full-asm-ignore-issue\Project2\bin\Debug\net8.0\TestResults\Project2_net8.0_x64.log`:
```
xUnit.net v3 Microsoft.Testing.Platform Runner v0.6.0-pre.7+bb04d8f4a6 (64-bit .NET 8.0.11)


Test run summary: Zero tests ran - C:\git\julealgon\xunitv3-full-asm-ignore-issue\Project2\bin\Debug\net8.0\Project2.dll (net8.0|x64)
  total: 0
  failed: 0
  succeeded: 0
  skipped: 0
  duration: 112ms

=== COMMAND LINE ===
C:\Program Files\dotnet\dotnet.exe exec C:\git\julealgon\xunitv3-full-asm-ignore-issue\Project2\bin\Debug\net8.0\Project2.dll --internal-msbuild-node testingplatform.pipe.321d13a565f84795b69edb536da2c1d6 --filter-not-trait Category=IntegrationTest 
```

# Expected Behavior

I would expect this run to succeed without any errors, since all tests that executed have passed. The fact that one of the projects had zero tests run should not be treated as an error.

**Comment by filzrev** [comment]
When running tests with `Microsoft.Testing.Platform`.
Test Runner will return an `8` exit code if no tests are found.

It need to configure to ignoring specific exit codes.
See: https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-platform-exit-codes#ignore-specific-exit-codes

In my case. I'm using the following `Directory.Build.props` configuration file.

**Directory.Build.props**
```csproj
<Project>
  <PropertyGroup>
    <TestingPlatformCommandLineArguments>$(TestingPlatformCommandLineArguments) --ignore-exit-code 8</TestingPlatformCommandLineArguments>
  </PropertyGroup>
</Project>
```

**Comment by julealgon** [comment]
> When running tests with `Microsoft.Testing.Platform`. Test Runner will return an `8` exit code if no tests are found.
> 
> It need to configure to ignoring specific exit codes. See: https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-platform-exit-codes#ignore-specific-exit-codes
> 
> In my case. I'm using the following `Directory.Build.props` configuration file.
> 
> **Directory.Build.props**
> 
> ```
> <Project>
>   <PropertyGroup>
>     <TestingPlatformCommandLineArguments>$(TestingPlatformCommandLineArguments) --ignore-exit-code 8</TestingPlatformCommandLineArguments>
>   </PropertyGroup>
> </Project>
> ```

That's interesting, thanks a lot for sharing it @filzrev! 

Adding `--ignore-exit-code 8` to the cmdline did make tests run perfectly as expected.

It does make me wonder though: why does the consumer need to customize this at all? Wouldn't it be possible for xunit v3's integration itself to automatically set this up based on its return codes?

**Comment by bradwilson** [comment]
@julealgon wrote:

> It does make me wonder though: why does the consumer need to customize this at all? Wouldn't it be possible for xunit v3's integration itself to automatically set this up based on its return codes?

We don't control those return codes. Those are generated by Microsoft Testing Platform. As the documentation says:

> Microsoft.Testing.Platform is designed to be strict by default

This was purposeful in their design: they by-default fail everything they feel should be fail-able and then count on you to opt out of the things you think shouldn't fail.
