### ISSUE TITLE
xunit v3 assemblies are not deterministic

### ISSUE THREAD

**Issue by martincostello** [xunit/xunit#3108]
I noticed that at least two of the xunit.v3 NuGet packages aren't deterministic:

- [xunit.v3.assert](https://nuget.info/packages/xunit.v3.assert/1.0.0)
- [xunit.v3.extensibility.core](https://nuget.info/packages/xunit.v3.extensibility.core/1.0.0)

![image](https://github.com/user-attachments/assets/0c206376-dad3-4a66-b2f5-b74db9809492)

Essentially the same as #2971, but I believe that the justification there doesn't apply to at least one of these two packages as the assertion package isn't just abstractions.

**Comment by bradwilson** [comment]
I have enabled deterministic builds according to these directions: https://github.com/clairernovotny/DeterministicBuilds

https://github.com/xunit/xunit/blob/9853a4b92a41b0129c30a70cd040ea5213a016c6/src/Directory.Build.targets#L81-L88

https://github.com/xunit/xunit/blob/9853a4b92a41b0129c30a70cd040ea5213a016c6/src/Directory.Build.props#L46

I have a guess as to why `xunit.v3.assert` doesn't show up as deterministic: the source is primarily from a Git submodule. I don't know what's causing the issue with `xunit.v3.extensibility.core`.

Any hints on trying to validate what's going on?

**Comment by bradwilson** [comment]
I'm going to try to "modernize" (by removing the no longer necessary steps) and see if the next CI build is any happier.

**Comment by bradwilson** [comment]
For `xunit.v3.extensibility.core`, could it be the use of T4?

https://github.com/xunit/xunit/blob/9853a4b92a41b0129c30a70cd040ea5213a016c6/src/xunit.v3.core/xunit.v3.core.csproj#L17-L24

**Comment by bradwilson** [comment]
Okay, none of our packages show as deterministic, it's not just the two you posted about, so my speculation is unnecessary.

**Comment by bradwilson** [comment]
Looks like those pre-.NET SDK 3.1 steps were the culprit.

Before:

> ![image](https://github.com/user-attachments/assets/7e7e2f01-7fc2-4a3e-90f5-6c5f88b6ff97)

After:

> ![image](https://github.com/user-attachments/assets/799696d8-15d6-4c70-b8af-734cc81ed837)
