### ISSUE TITLE
Excluding a single test/class from parallelism

### ISSUE THREAD

**Issue by stephentoub** [xunit/xunit#318]
Most of the tests in my test assembly can be run in parallel with each other... except for one: it must not be run in parallel with any other tests in the same process.  The current parallel execution knobs for xunit don't seem to make this possible.  Is there a way to do it, or if not, could such a mechanism be added?

**Comment by bradwilson** [comment]
There is no knob for this today.

We have a similar problem with the xUnit.net tests themselves in that we all the tests from 1.x, linked against 1.x, with the 2.x runners. Those tests aren't parallel friendly. We have them in a separate assembly which is run by itself, and then we parallelize everything else.

**Comment by stephentoub** [comment]
Ok.  Thanks, Brad.  Consider it a feature request for the future :smile:

**Comment by bradwilson** [comment]
Implemented.

**Comment by stephentoub** [comment]
Thanks!

**Comment by mabead** [comment]
@bradwilson You say "implemented" but I don't find anything in the documentation. Could you please provide some pointers.

**Comment by bradwilson** [comment]
Sorry, I guess the docs didn't get updated.

You can isolate a test collection from parallelism by setting a flag on the test collection attribute. From memory, it works approximately like this:

```csharp
[CollectionDefinition("NoParallelization", DisableParallelization = true)]
public class NoParallelizationCollection { }

[Collection("NoParallelization")]
public class MyTests
{
    // ...
}
```

You can add the Collection attribute to any test classes that shouldn't be parallelized, and they should all share that same single collection definition.

**Comment by jzabroski** [comment]
I found the following idiom helpful - making a single class disable parallelization, thus avoiding creating an interstitial class to mark CollectionDefinition:

```c#
using System.Threading;
using Xunit;

namespace XUnitTestProject
{
	[CollectionDefinition(nameof(UnitTest1), DisableParallelization = true)]
	[Collection(nameof(UnitTest1))]
	public class UnitTest1
	{
		[Fact]
		public void Test1()
		{
			NotThreadSafeResource.Use();
			Thread.Sleep(1000);
			NotThreadSafeResource.Release();
		}

		[Fact]
		public void Test3()
		{
			NotThreadSafeResource.Use();
			Thread.Sleep(1000);
			NotThreadSafeResource.Release();
		}
	}
}
```
