### ISSUE TITLE
Add support in runner.utility for saying "no app domains"

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#319]
With the Mono AppDomain bug garnering no comments, it's probably worth investigating a way to avoid the Mono problem entirely by just skipping AppDomains. They will have to accept the loss of functionality associated with that (no isolation, file locking on some file systems, etc.).

**Comment by adamralph** [comment]
:+1: 

(For reference, this is a workaround for https://github.com/xunit/xunit/issues/158.)

**Comment by bradwilson** [comment]
Shipping in 2.1 beta 4.

**Comment by adamralph** [comment]
For reference https://github.com/xunit/xunit/blob/cb4e9fb25015e73957a586b5e7b869b710ea70e0/src/xunit.console/Program.cs#L165
