### ISSUE TITLE
Can't generate report in nunit format when using multiple assemblies in xunit.console

### ISSUE THREAD

**Issue by batu-possible** [xunit/xunit#322]
Hi,

If I add more than one assembly to the xunit.console, the tests are executed properly, however if I would like to get the result in nunit format then I recieve an error: 

*System.InvalidOperationException: Token StartElement in state EndRootElement would result in an invalid XML document. Make sure that the ConformanceLevel setting is set to ConformanceLevel.Fragment or ConformanceLevel.Auto if you want to write an XML fragment.*

It seems that the provided NUnitXml.xslt would like to add two root (test-results) nodes, and the transformed would look something like this:

`<?xml version="1.0" encoding="UTF-8"?>
<test-results name="First.Test.dll" date="2015-02-23" time="17:12:12" total="1" failures="0" not-run="0">
  <test-suite name="First.Test.dll" success="True" time="0.290">
    <results>
      <test-suite name="xUnit.net v1 Tests for First.Test.dll" success="True" time="0.290">
        <results>
          <test-case name="First.Test.Test.TestMethod" executed="True" success="True" time="0.290"/>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>`

`<test-results name="Second.Test.dll" date="2015-02-23" time="17:12:12" total="1" failures="0" not-run="0">
  <test-suite name="Second.Test.dll" success="True" time="0.289">
    <results>
      <test-suite name="xUnit.net v1 Tests for Second.Test.dll" success="True" time="0.289">
        <results>
          <test-case name="Second.Test.dll" executed="True" success="True" time="0.289"/>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>`

Regards,
Attila

**Comment by coldacid** [comment]
@batu-possible Could I get your standard XML output? I'll try to take some time this evening to fix up the XSLT if you can attach the XML before 5pm EST.

**Comment by batu-possible** [comment]
sure, here it is: https://drive.google.com/file/d/0B_jfKAeAFyBUU0ZybjN6ZjMyQUU/view?usp=sharing

**Comment by coldacid** [comment]
Fix is in PR#324
