### ISSUE TITLE
Allow TestMessageVisitor Visits to be subscribed to.

### ISSUE THREAD

**Issue by davidgoldenberg** [xunit/xunit#323]
For example, instead of making one choose from a TeamCityVisitor, AppVeyorVisitor, or StandardOutputVisitor, visitors should have a central Observer that can be subscribed to.  That way classes that derive from the base visitor can decide what they want to do with the data, instead of relying on the Xunit team to add features.

As an example for how this can work, see https://github.com/davidgoldenberg/xunit

**Comment by bradwilson** [comment]
Related to xunit/aspnet.xunit#3

**Comment by bradwilson** [comment]
This capability shipped in 2.1 Beta 3 as the new "runner reporter" feature.
