### ISSUE TITLE
Theory with System.Windows.Forms.DialogResult parameter fails with NRE under VS runner.

### ISSUE THREAD

**Issue by AlexanderSher** [xunit/xunit#326]
> An exception occurred while invoking executor 'executor://xunit/VsTestRunner2': Object reference not set to an instance of an object.

```
	public class TestClass
	{
		[Theory]
		[InlineData(System.Windows.Forms.DialogResult.OK)]
		[InlineData(System.Windows.Forms.DialogResult.Cancel)]
		public void Test(System.Windows.Forms.DialogResult e)
		{
		}
	}
```

Bug doesn't repro with xunit.console

**Comment by bradwilson** [comment]
With what version? This should be fixed with RC3 of xUnit and the VS runner (released yesterday).

**Comment by AlexanderSher** [comment]
It is RC3 (runner build 1046).
It also doesn't repro if enum is defined in the same assembly.

Btw, how I can get the full stack trace of the error (not just the message)?

**Comment by bradwilson** [comment]
That looks like an error that's escaping our code and coming from Visual Studio. The way I usually debug things like that is to use a self-built Visual Studio binary and attach to the discovery or execution process (not trivial on either count, unfortunately).

However, given your note, that sends me in a very specific direction.

**Comment by AlexanderSher** [comment]
So if I understand it right, the problem is in the assembly deserialization - test is running in a different appdomain, and you don't have a full assembly name, so you can't load a GAC assembly.
But since you know the test assembly, you still should be able to call Assembly.ReflectionOnlyLoadFrom("PathToTestAssmbly").GetReferencedAssemblies() and then find the full name in that list.

Or there are other issues with assemblies from GAC?

**Comment by bradwilson** [comment]
Unfortunately, that's not going to help on devices where ReflectionOnlyLoadFrom is not available. :(
