### ISSUE TITLE
InlineData and Types outside of mscorlib and the currently executing assembly

### ISSUE THREAD

**Issue by ammeep** [xunit/xunit#328]
I am using RC3, and I have some tests which no longer are able to pass types as inline parameters. Specifically when the type in question lives outside the executing assembly. Null is passed instead of the type.

For example

```
public class Tests
{
     [Theory]
     [InlineData(typeof(int))]
     [InlineData(typeof(string))]
     [InlineData(typeof(MyType))]
     [InlineData(typeof(ExternalType))]
     [InlineData(typeof(GridLength))]
     [InlineData(typeof(SqlCommand))]
     public void TypeOfTests(Type type)
     {
         Assert.NotNull(type);
     }
}

public class MyType{}
```

This test will fail both for ``GridLength`` which lives in ``PresentationFramework.dll``  and ``SqlCommand`` who lives in ``System.Data.dll``

In this example ``ExternalType`` is a type which can be found in another project in this solution.

I have pushed  a small sample which shows this here https://github.com/ammeep/XunitTypeBug

Loving the work on Xunit 2.0 :sparkles:  Let me know if there is anything I can do to contribute or provide to help :smile:

**Comment by bradwilson** [comment]
Dup of #326
