### ISSUE TITLE
Xunit Didn't show in Test Explorer

### ISSUE THREAD

**Issue by XcoderTeam** [xunit/xunit#330]
I have try to install
xunit: "2.0.0-rc3-build2880"
xunit.runner.visualstudio: "2.0.0-rc3-build1046"

it didn't show in VS Test Explorer using VS CTP6

**Comment by bradwilson** [comment]
Unfortunately, there seem to be some people having problems with VS2015 CTP 5 and CTP 6. You should report these problems to the Visual Studio Connect page after verifying that VS2013 (or VS2015 Preview) is working properly for you.

https://connect.microsoft.com/VisualStudio
