### ISSUE TITLE
Invalid TestCaseOrderer not reported correctly

### ISSUE THREAD

**Issue by citizenmatt** [xunit/xunit#332]
If using a `TestCaseOrderer` attribute and the custom orderer isn't found, or throws an exception, it's not reported correctly. The console runner will sometimes throw a `NullReferenceException` if the type can't be found, but without a useful stack trace. Other times, it doesn't show anything. The Visual Studio runner just doesn't run the test, with no indication of why. Enabling diagnostic messages makes no difference.

The same happens for `TestCollectionOrderer`, except it gives a `NullReferenceException` in `OrderTestCases`.

**Comment by wholroyd** [comment]
I can reproduce the issue with the following packages on my project. I took the PriorityOrderer code from the TestCaseOrdering sample. 

    <package id="xunit" version="2.0.0-rc3-build2880" targetFramework="net45" />
    <package id="xunit.abstractions" version="2.0.0-rc3-build2880" targetFramework="net45" />
    <package id="xunit.assert" version="2.0.0-rc3-build2880" targetFramework="net45" />
    <package id="xunit.core" version="2.0.0-rc3-build2880" targetFramework="net45" />
    <package id="xunit.extensibility.core" version="2.0.0-rc3-build2880" targetFramework="net45" />
    <package id="xunit.runner.visualstudio" version="2.0.0-rc3-build1046" targetFramework="net45" />

The difference for me is that the tests are never run and remain in the "Not Run Tests" category in the Test Explorer. When I just 'Run' the tests, there is no failure reported in the Test Explorer. In a 'Debug' run of the tests, I get a NullReferenceException breakpoint in the editor stating it occurred in mscorlib.dll.

![capture2](https://cloud.githubusercontent.com/assets/147990/6510536/b7fdb3e0-c334-11e4-8daf-4e5b05ca35ec.PNG)

**Comment by wholroyd** [comment]
This is now working as expected on RC4, thanks!

One thing that did throw me for a loop on the usage of the attribute was that I needed the FullName of both the class (namespace + typename), and the FullName of the assembly whereas the sample used neither.

**Comment by bradwilson** [comment]
You shouldn't need the full name of the assembly; just the name of the DLL (minus `.dll`) should be sufficient.

**Comment by joemast** [comment]
Is this a bug that TestCaseOrderer attribute requires class name to be specified in FQDN form (with namespace)? Because only FQDN for class name worked for me (thanks to @wholroyd comment) but in your "samples" project there short form works as well

Please describe this in docs or fix a bug. Thanks for you work guys

**Comment by bradwilson** [comment]
@joemast No, it's not a bug. FQDN is definitely required. Can you point to a sample where you think a short name is sufficient?
