### ISSUE TITLE
Something wrong with the rc3 nuget package

### ISSUE THREAD

**Issue by worldspawn** [xunit/xunit#333]
Hi,

If i run the following:
`..\tools\nuget.exe install "xunit" -o ".\packages" -Version 2.0.0-rc3-build2880 -Source "https://www.nuget.org/api/v2/" -Pre`

Using nuget 2.8.50926.602

I get the output:
```
Attempting to resolve dependency 'xunit.core (= 2.0.0-rc3-build2880)'.
Unable to resolve dependency 'xunit.core (= 2.0.0-rc3-build2880)'.
```

I would expect it to work...

**Comment by worldspawn** [comment]
I had to install in the following order and it worked.

```
<package id="xunit.assert" version="2.0.0-rc3-build2880" targetFramework="net45" />
  <package id="xunit.abstractions" version="2.0.0-rc3-build2880" targetFramework="net45" />
  <package id="xunit.extensibility.core" version="2.0.0-rc3-build2880" targetFramework="net45" />
  <package id="xunit.core" version="2.0.0-rc3-build2880" targetFramework="net45" />
  <package id="xunit" version="2.0.0-rc3-build2880" targetFramework="net45" />
```

**Comment by bradwilson** [comment]
Make sure you're using NuGet 2.8.3 or later.

**Comment by worldspawn** [comment]
Hi @bradwilson, thanks for your reply. I mentioned above I am using version 2.8.50926.602 which is greater than 2.8.3.

I've had a couple of other people around the office replicate this error too. I was trying to manually restore packages for a solution by reading the packages.config and installing them 1 by 1 (because targeting a .config file does not install dependencies). Then someone pointed out to me you can do `nuget restore somethign.sln` which worked.

So this issue is not holding me up anymore but it still seems like it should work

**Comment by worldspawn** [comment]
I am an almost identical problem with RazorEngine and its dependency on Microsoft.AspNet.Razor. (https://github.com/Antaris/RazorEngine/issues/243) I think nuget is just... buggy

**Comment by bradwilson** [comment]
> I think nuget is just... buggy

Yeah. :(
