### ISSUE TITLE
MSBuild runner is looking for and failing to find xunit.dll

### ISSUE THREAD

**Issue by coldacid** [xunit/xunit#334]
The MSBuild runner is returning an error message but still running to completion since 2.0.0 RC3, stating "System.ArgumentException: Unknown test framework: Could not find xunit.dll or xunit.execution.desktop.dll." Tests are still running, but because this ends up slipping into MSBuild itself, builds are reported as failed. xunit.dll is not present alongside my test assembly, being that the test assembly works against 2.0.0, but both xunit.core.dll and xunit.execution.desktop.dll are in there.

The exception is originating from `Xunit.XunitFrontController.CreateInnerController()` but that method is fairly hairy. Combined with the fact that the doc comments for `XunitFrontController` state that it supports v1 and v2 makes me uncomfortable with just making changes to the method and PRing them, lest I break the backwards compat.

For now, I've added the ContinueOnError attribute to the `<xunit>` task tag in my project file, but it'd be better to not have such spurious messages appear to MSBuild.

**Comment by bradwilson** [comment]
`xunit.dll` is for v1, and `xunit.execution.desktop.dll` is for v2.

Do you have a repro you can post?

**Comment by coldacid** [comment]
Not one that I can post, unfortunately. I can share part of the build log though:

    	Test:
    	  xUnit.net MSBuild runner (64-bit .NET 4.0.30319.34209)
    	    Discovering: WEYES.FittingRoom.Core.Tests
    	C:\0-DATA\bamboo\xml-data\build-dir\WEYES-WEFT2DEV-JOB1\test.proj(25,5): error : System.ArgumentException: Unknown test framework: Could not find xunit.dll or xunit.execution.desktop.dll.
    	C:\0-DATA\bamboo\xml-data\build-dir\WEYES-WEFT2DEV-JOB1\test.proj(25,5): error : Parameter name: C:\0-DATA\bamboo\xml-data\build-dir\WEYES-WEFT2DEV-JOB1\WEYES.FittingRoom.Core.Tests\bin\Debug\WEYES.FittingRoom.Core.Tests.dll
    	C:\0-DATA\bamboo\xml-data\build-dir\WEYES-WEFT2DEV-JOB1\test.proj(25,5): error :    at Xunit.XunitFrontController.CreateInnerController()
    	C:\0-DATA\bamboo\xml-data\build-dir\WEYES-WEFT2DEV-JOB1\test.proj(25,5): error :    at Xunit.XunitFrontController.Find(Boolean includeSourceInformation, IMessageSink messageSink, ITestFrameworkDiscoveryOptions discoveryOptions)
    	C:\0-DATA\bamboo\xml-data\build-dir\WEYES-WEFT2DEV-JOB1\test.proj(25,5): error :    at Xunit.Runner.MSBuild.xunit.ExecuteAssembly(String assemblyFileName, String configFileName, TestAssemblyConfiguration configuration)
    	Done Building Project "C:\0-DATA\bamboo\xml-data\build-dir\WEYES-WEFT2DEV-JOB1\test.proj" (Test target(s)) -- FAILED.
    	
    	Build FAILED.

The thing is, `xunit.execution.desktop.dll` is there in `C:\0-DATA\bamboo\xml-data\build-dir\WEYES-WEFT2DEV-JOB1\WEYES.FittingRoom.Core.Tests\bin\Debug`.

**Comment by bradwilson** [comment]
This doesn't generally happen, so without some kind of repro to chase it down, it's going to be nearly impossible understand what's going on. :(

**Comment by coldacid** [comment]
It seems to be working now, fortunately. I had to RDP into the build server and wipe out the packages directory, but since then tests haven't been a problem. I'm gonna rack it up as some odd NuGet issue.

**Comment by modul8com** [comment]
I had the same errors... finally it seemed that the example MSBuild file on your website was incorrect...
The correct file should look like this:

```xml
<Project DefaultTargets="Test" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <UsingTask AssemblyFile="xunit.runner.msbuild.dll" TaskName="Xunit.Runner.MSBuild.xunit" />
  <ItemGroup>
    <TestAssemblies Include="**/bin/**/*.tests.dll" />
  </ItemGroup>
  <Target Name="Test">
    <xunit Assemblies="@(TestAssemblies)" />
  </Target>
</Project>
```

Key is this line:

 ```xml
   <TestAssemblies Include="**/bin/**/*.tests.dll" />
```

The current example tries to test the *.tests.dll file in the OBJ folder.
It took a while until I knew what happened...

**Comment by coldacid** [comment]
Ah, nice catch.

**Comment by kwesolowski** [comment]
And if Debug and Release are build before running and only one shoudl be run, even:
   <TestAssemblies Include="**/bin/Debug/*.tests.dll" />

**Comment by bradwilson** [comment]
We typically use the `$(Configuration)` property for this. If you crack open your `.csproj` file, you'll see that this is a semi-standard value which is used to determine whether you're building `Debug` or `Release`. When we write a custom MSBuild file, we use this in a few ways.

First, pick a default:

```XML
<PropertyGroup>
  <Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>
</PropertyGroup>
```

Second, pass the value into the task when building your solution:

```XML
<Task Name="Build">
  <MSBuild
    Projects="MySolution.sln"
    Targets="Build"
    Properties="Configuration=$(Configuration)"/>
</Task>
```

Third, use this value to find the tests to run:

```XML
<Target Name="Test" DependsOnTasks="Build">
  <ItemGroup>
    <TestAssemblies Include="**\bin\$(Configuration)\*.tests.dll"/>
  </ItemGroup>
  <xunit Assemblies="@(TestAssemblies)"/>
</Target>
```

**Comment by kwesolowski** [comment]
I am running build as part of CI, and as it is separate step (separate `.target` file) I don't have "$(Configuration)" available - but definitely when using as part of build this is much better.

**Comment by bradwilson** [comment]
Even if you're using a separate file, using `$(Configuration)` in this way lets you (a) choose debug vs. release from the command line; (b) lets you pass a configuration into this `.target` file from your main build where maybe you do have access to it.

**Comment by kwesolowski** [comment]
Great, thank you!:)
