### ISSUE TITLE
Visual Studio test runner fails in the presence of certain overloaded methods

### ISSUE THREAD

**Issue by sharwell** [xunit/xunit#346]
During our evaluation of xunit in DotNetAnalyzers/StyleCopAnalyzers#517, we identified a case where the Visual Studio test runner would not run test methods within certain classes. Through debugging, we narrowed this down to a failure where the `FactAttribute` was "missing" from a test on the following line:

https://github.com/xunit/xunit/blob/7b11ac459af6303882755e445776cd4b740c75d2/src/xunit.execution/Sdk/Frameworks/XunitTestCase.cs#L51

It turns out that the class where tests failed contained the following two methods:

```csharp
[Fact]
public async Task TestDestructorCorrectDocumentationGenericCustomized();

private async Task TestDestructorCorrectDocumentationCustomized(string part1, string part2, bool generic);
```

For some reason, the `Initialize` method was looking at the *second* method above, when it should have been looking at the first method. As far as I can tell, this is due to `ReflectionTypeInfo.GetMethod` not restricting the lookup to methods with the appropriate argument list. The following image shows the call stack at the time `Reflector.Wrap` was used to wrap the *wrong* method.

![image](https://cloud.githubusercontent.com/assets/1408396/6547977/882ad0e6-c5b7-11e4-9d2d-beeb9c1e77a7.png)

**Comment by bradwilson** [comment]
Dup of xunit/visualstudio.xunit#35

**Comment by sharwell** [comment]
@bradwilson The failure is caused by an incorrect serialization/deserialization of the `TestMethod` class, which is part of this repository. The Visual Studio test runner is showing incorrect behavior as a result of this, but the bug does not lie within that codebase.

Here is the serialization code I'm referring to:

https://github.com/xunit/xunit/blob/2d240f6572d812f061a0c0624dd6cc8c1149313f/src/xunit.execution/Sdk/Frameworks/TestMethod.cs#L39-L54
