### ISSUE TITLE
VS CTP 6 Warning Error

### ISSUE THREAD

**Issue by XcoderTeam** [xunit/xunit#347]
Based on this url:
http://xunit.github.io/docs/getting-started-aspnet.html

I need to add this into my project.json
"xunit": "2.0.0-rc3-*",
"xunit.runner.aspnet": "2.0.0-rc-*"

but in my solution explorer, encounter an warning icon.
http://i60.tinypic.com/2v1lmie.png

**Comment by bradwilson** [comment]
You're missing the 3 (for `rc3`) in your `xunit.runner.aspnet` declaration.

**Comment by XcoderTeam** [comment]
sorry type wrongly

here is my project json
{
	"version": "1.0.0-*",
	"dependencies": {
		"xunit": "2.0.0-rc3-*",
        "xunit.runner.aspnet": "2.0.0-rc3-*"
	},
	"commands": {
		"test": "xunit.runner.aspnet"
	},
	"frameworks": {
		"aspnet50": {
			"dependencies": {
			}
		},
		"aspnetcore50": {
			"dependencies": {
				"System.Runtime": "4.0.20-beta-22523"
			}
		}
	}
}

From the kpm restore
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='xunit.runner.aspnet'.
Error: FindPackagesById: xunit.runner.aspnet
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).

**Comment by bradwilson** [comment]
Clone our Visual Studio integration project. Does it properly do package restore for you?

https://github.com/xunit/visualstudio.xunit.integration
