### ISSUE TITLE
Test names look great in VS Test Explorer, not anywhere else

### ISSUE THREAD

**Issue by AArnott** [xunit/xunit#351]
In my custom test discovery, each test method gets executed several times and each run gets its own result displayed in the results pane. In addition, part of the setup for one of the test method invocations also gets its own test result displayed since that too tests the product and is valuable by itself. 

Here is a screenshot of how it looks, which is exactly the way I want it:
![image](https://cloud.githubusercontent.com/assets/3548/6616813/674927f0-c86f-11e4-80d7-97eed5eabaa5.png)

However: in the console runner I see output like this:

    Discovering: Microsoft.VisualStudio.Composition.Tests
    Discovered:  Microsoft.VisualStudio.Composition.Tests
    Starting:    Microsoft.VisualStudio.Composition.Tests
       V3 [SKIP]
          Test does not include V3 test.
       CompositionServiceSharedWithinRootScope [SKIP]
          Not important, and not obtainable for now.
       V3 [SKIP]
          Test does not include V3 test.

So each test result that is displayed (due to failure or skip result reported) only shows the name of the sub-test. I'd like it to show in the format "TestMethodName (sub-test)" such as "AcquireExportWithImport (V3)".

In the HTML report from the xunit2 console runner I get this which has the same problem:
![image](https://cloud.githubusercontent.com/assets/3548/6616909/637c176c-c870-11e4-8d3b-568498311c91.png)

I'm looking for a way to keep the appearance I have in Test Explorer but get a better experience in the other runners/results. It seems the only way for it to look good elsewhere is to have test discovery produce individual `IXunitTestCase` instances for each part of the test, which makes Test Explorer change its view dramatically and _doesn't even make sense in the case of the test result that is based on setup for an actual test method invocation_ since they are tightly coupled and can't be run individually.

**Comment by bradwilson** [comment]
This is a tough one.

People typically use display names for tests because they *don't* want to see the method name. I'm not sure how to make a change here that makes you happy, but doesn't also make those people unhappy.

**Comment by AArnott** [comment]
I worried about that. Might it make sense to have two display name like properties? Somehow naming them so it makes sense that one is for presentation next to the test case name, and the other for when it stands alone?

**Comment by bradwilson** [comment]
This has been resolved with configuration files.

**Comment by AArnott** [comment]
Can you elaborate on the solution please?

**Comment by bradwilson** [comment]
Configuration allows you to say you want just method names for the tests.

We are not planning on disabling display names. That historically means exactly what you don't want: "use this as the display name for this test".

**Comment by AArnott** [comment]
Hmmm... So it's been resolved as "Won't Fix" then. 
OK, I can respect that.
