### ISSUE TITLE
Add support for parametrixed test fixtures

### ISSUE THREAD

**Issue by RaYell** [xunit/xunit#352]
nUnit has a great feature that allows you to define parameters on the test fixture (class) level. One example where this feature might be useful is in integration tests that you may want to run on several browsers. You don't want to declare separate test classes for each browser, and instead you can simply add a parameter that the test class constructor will resolve and init a proper driver.

```csharp
[TestFixture("PhantomJS"]
[TestFixture("Firefox")];
public class MyTests
{
    public MyTests(string browserName)
    {
        // determine and init driver based on browserName parameter
    }

    [Test]
    public TestA()
    {
         // some test on the driver
    }
}
```

Since xunit does not have an attribute similar to `TestFixture` I couldn't find a way of achieving similar functionality with it and I'd love to see a support for similar feature in xUnit.

**Comment by bradwilson** [comment]
After discussion, we've decided not to do this feature.

**Comment by agray** [comment]
To not implementing this feature is a massive missed opportunity.  Could you provide your reasons for not wanting to implement this feature.  This would be a deal breaker for many people.

**Comment by fullcirclesolutions** [comment]
May we please open this discussion again and get this back on the to do list.?

**Comment by bradwilson** [comment]
Our reasoning is two-fold:

1. The feature is implementable via extensibility points.
2. The feature is more geared toward acceptance testing than unit testing (which is a bar that we use when deciding whether something belongs in the core framework or not).

The last 12 months have not changed our minds on this.

**Comment by fullcirclesolutions** [comment]
Hi @bradwilson It is great to hear that this feature is implementable.  Could you please advise which extensibility points would be applicable and we would be happy to implement it for our needs.

**Comment by fullcirclesolutions** [comment]
If I understand this is possible:

    internal class CollectionOfSpecifiedString : IEnumerable<MyCustomClass[]> {
        public IEnumerator<MyCustomClass[]> GetEnumerator() {
            yield return new MyCustomClass[] { ... };
        }

        IEnumerator IEnumerable.GetEnumerator() {
            return this.GetEnumerator();
        }
    }

    [Theory]
    [ClassData(typeof(MyCustomClassThatReturnsIEnumerable))]
    TheirTestMethodPollutedWithMyInternalCustomClass(MyCustomClass custom)


Is it possible to write an XUnit extension that would allow my to provide the functionality of NUnit 3's [TestFixtureSource(typeof(MyCustomClassThatReturnsIEnumerable))]?

**Comment by sbins** [comment]
I also echo the request from fullcirclesolutions.  We too are looking to switch from NUnit to XUnit to perform Selenium automated web testing and without the NUnit [TestFixture] attribute I cannot see any way of easily repeating the same tests and specifying parameters at the Class level (I can paramateris each individual test message but that will lead to massive amounts of duplication)

I've tried looking at the X-Unit online samples (specifically the RetryFactExample) which I think *may* be the extensibility point to use but can't follow the code around the RetryTestCase and DelayedMessage bus.

Any pointers or ideas would be appreciated.

**Comment by Ausm** [comment]
@sbin, @fullcirclesolutions 

What about that?
```C#
public abstract class BaseTest
{
    public BaseTest(string browserName)
    {
        // determine and init driver based on browserName parameter
    }

    [Fact]
    public virtual void TestA()
    {
        /// some test on driver
    }
}

public class FirefoxTest : BaseTest { public FirefoxTest() : base("Firefox") { } }

public class PhantomJsTest : BaseTest { public PhantomJsTest() : base("PhantomJS") { } }
```
I think that's what @bradwilson ment with "implementable via extensibility points".

**Comment by sbins** [comment]
@Ausm thanks for the suggestion.  Think I have found another way of doing this which gives me what I need.  Basically I decorate each of my test methods like this...

```
[Theory]
[MemberData("GetBrowsers")]
public void DemoTest2A(IBrowserContext browser)
{
	// this method called once for each browser which is returned from base.GetBrowsers()
}
```

and each of my test classes inherits from a common base class which includes this

```

public static IEnumerable<object[]> GetBrowsers
{
	get
	{
		yield return new object[] { new Firefox() };
		yield return new object[] { new Chrome() };
	}
}
```

Where IBrowserContext is my own construct which exposes things like the selenium browser driver.  This saves me having to subclass each test class as per your suggestion.

**Comment by agray** [comment]
@sbins But you have to add

[Theory]

[MemberData("GetBrowsers")]

to every test.

In NUnit with a testFixtureSource this not required and therefore what
we want to be able to do in XUnit.

Andrew

**Comment by sbins** [comment]
@agray Yes that is true but its a good as a workaround as I can think of at the moment.

**Comment by damianpereira86** [comment]
Someone with a better approach to solve this issue? In @sbins solution besides having to add [Theory] / 
[MemberData("GetBrowsers")] to every test, you loss the ability to use any other XxxData in your tests.
Suggestions?

**Comment by bradwilson** [comment]
@damianpereira86 Using `[MemberData]` does not mean you lose the ability to use any other data attributes. I'm not sure where you got this idea from.

**Comment by damianpereira86** [comment]
@bradwilson I tried using [MemeberData] and [InlineData] in the same [Theory]. Following the first example from @RaYell, [MemeberData] will return the browser name as a string, and the [InlineData] will provide any other desired parameter. The test works, but it seems that both Data attributes try to match with the same parameter. So you if you do this:

[Theory]
        [InlineData(3)]
        [InlineData(4)]
        [MemberData(nameof(GetBrowser))]
        public void TestBoth(int value, string browserName)
        {
            Browser = browserName;
            Assert.True(IsOdd(value));
        }

You get an error because [InlineData] values must match the number of parameters in the method.

Is there another way to implement this? Remember that the [MemberData(nameof(GetBrowser))] will decorate all the tests.

**Comment by marcind** [comment]
That's not how `InlineData` and `MemberData` work. The various `*Data` attributes are intended to provide "rows" of data for the theory. Each "row", regardless of the attribute that provided it, needs to conform to the shape specified by parameters of the theory method. E.g.

```
[Theory]
[InlineData(3, "IE")]
[InlineData(3, "Edge")]
[InlineData(4, "Edge")]
[InlineData(4, "IE")]
[MemberData(nameof(GetValuesAndBrowsers))]
public void TestBoth(int value, string browser) { ... }
```

**Comment by damianpereira86** [comment]
Thanks for the answers. I don't like the solution for this specific problem. I would prefer to set the browser in the setup of each test, instead of having to deal with it inside the test itself. But I understand that Acceptance Testing is not a priority for the framework, as @bradwilson mentioned above. Regards.

**Comment by marcind** [comment]
One potential way to organize your tests would be something like:

```csharp
public abstract class BrowserTestBase {
  protected string browser;
  protected BrowserTestBase(string browser) { this.browser = browser; }

  [Fact]
  public void A() { Assert.NotNull(this.browser); }
  [Theory]
  [InlineData(1)]
  [InlineData(2)]
  public void B(int value) { Assert.NotEqual(value, this.browser.Length); }
}

public class EdgeTests : BrowserTestBase {
  public EdgeTests(): base("Edge") {}
}

public class ChromeTests: BrowserTestBase {
  public ChromeTests(): base("Chrome") {}

  [Fact] public void ChromeSpecificTest() { Assert.True(this.browser.StartsWith("C"); }
}
```

**Comment by igalnassi** [comment]
This works if you are writing test cases only for a handful of scenarios. I have a scenario where I am testing a framework that is a full featured framework with code-generated ORM capabilities that work on multiple different database engines, caching and elastic search that work on various different service layers (WCF, WebApi, Google RPC etc).

As such, I am currently running 16 different combinations of different database layers (can be more than one) with a combination of service layers.

With the above suggestion, I will have to create 16 different Test classes. There should be a way to reuse the same class feeding in different parameters.

Without that, it will be impossible for us to migrate to Xunit, which we really would like to be able to do!

Appreciate your help or any other suggestions.

**Comment by AidanMcD** [comment]
Is there a solution to this I'm in the situation of running tests where the fixture uses different values but the same tests. Not being able to use the same tests over different data values is really inefficient.

**Comment by v-valk** [comment]
Same here, would love to just have 1 test with different setup. You can of course do the setup during the arrange phase, but you'd have to repeat the same thing for every related test when it could be done once by just passing desired values from a test class into test fixture.

**Comment by agray** [comment]
Was this feature request implemented before it was closed, or was it just ignored?

**Comment by mhmast** [comment]
This can easily be achieved via Attributes by making your ClassFixture generic like so:
`public class DemoFixture<T> : IDisposable
    {
        private readonly DemoFixtureDataAttribute _attr;

        public DemoFixture()
        {
            _attr = typeof(T).GetCustomAttribute<DemoFixtureDataAttribute>();
            if(_attr == null)
            {
                throw new ArgumentException($"{nameof(DemoFixtureDataAttribute)} not found");
            }

        }


// Use data from the attribute here

**Comment by agray** [comment]
It would be good to see a fully working example.

**Comment by ldeluigi** [comment]
Please reopen this issue

**Comment by bradwilson** [comment]
@VyacheslavPritykin We consider the built-in source introspection feature to be unsupported, because we don't control the code and it is frequently broken. If you have issues with it, please address them to the Visual Studio team.
