### ISSUE TITLE
Issue between xUnit 2, FakeItEasy and async methods

### ISSUE THREAD

**Issue by StefanBilliet** [xunit/xunit#357]
Hi

I think I'm having an issue with xUnit 2 RTM. We have a couple of tests along the lines of:

    var sut = A.Fake<IAsyncClass>();
    await sut.GetAsync(new Input{Test = "test"});
    A.CallTo(() => sut.GetAsync(A<Input>.That.Matches(_ => _.Test == "test"))).MustHaveHappened();

Basically we're trying to check if an async method is called with an object that matches certain criteria. This used to work fine in 1.9.2, but since version 2 these tests have become unpredictable.  
 If we run all of our tests, some of the tests that use "A<Input>.That.Matches" fail. If we run those tests individually, they succeed. Also, the tests which fail differ between individual runs.  

The error message we see is:   

    FakeItEasy.ExpectationException
    Assertion failed for the following call:
    ClassLibrary1.IAsyncClass.GetAsync(<NULL>)
    Expected to find it at least once but found it #0 times among the calls:
    1: ClassLibrary1.IAsyncClass.GetAsync(input: ClassLibrary1.Input)

It's almost as if there's some weird race condition going on where the "A<Input>.That.Matches" doesn't compute fast enough, leading xUnit to see it as null, if that makes any sense at all.
I've included all the code in this gist: https://gist.github.com/StefanBilliet/982ef274c4303235ecd7
It's just a few testfixtures, all with the same tests; if I run all those tests, the issue presents itself.

I'm not sure wether it's really an issue with xUnit, FakeItEasy, or a combination of both, but I hope someone can shine some light on this...
Thanks in advance.

**Comment by Samvrie** [comment]
I had the same issue with the Xunit 2.0.0-Rc3 (Didn't try the 2.0.0 RTM) and FakeItEasy.
I disable the Parallel option of xUnit.

**Comment by StefanBilliet** [comment]
Ok, I think I found something.
In our MSBuild test script if I add ParallelizeTestCollections="false", then all tests pass again. 
According to http://xunit.github.io/docs/configuration-files.html, this is a new option which defaults to true.

Thing is, we also use ReSharper to run our xUnit tests, but I can't find a way to pass that option to the ReSharper xUnit runner. I tried putting it in the app.config, but it doesn't get picked up. TestDriven.Net does pick up that setting.

So I guess I'm down to two questions:
* Is "true" a good default value for ParallelizeTestCollections?
* If so, how can I instruct the ReSharper xUnit runner to set this option to false? (Or should I ask this in the xUnit ReSharper GitHub project?)

Thanks for the help so far :-)

**Comment by bradwilson** [comment]
Yes, `true` is a good default for ParallelizeTestCollections.

Your library (FakeItEasy) is not compatible with using `Task<T>`. It very likely uses thread-local storage, which was never a safe option when using async (you just got lucky previously with v1, because it did not internally use tasks).

The same problem exists in NSubstitute, so we forked it and fixed it:

https://github.com/CenturyLinkCloud/NSubstitute/commit/f7eee68840eace09b757c500fadd47839222d22d

It has been running internally safely for several weeks now, so I guess we should approach the author(s) about whether they are interested in this fix. I presume FakeItEasy could be similarly fixed.

**Comment by Samvrie** [comment]
What Mocking framework would you recommend to you with xUnit 2.0 then?

**Comment by bradwilson** [comment]
Obviously, we use NSubstitute. :) I don't know which ones are `Task`-friendly, but we were already using NSub, which is why we patched it to fix it.

**Comment by citizenmatt** [comment]
The ReSharper runner should respect app.config, I'll check to make sure it does. Also, you can disable parallelisation using `[assembly: CollectionBehavior(DisableTestParallelisation = true)]` somewhere in your test assembly.

**Comment by PureKrome** [comment]
Ping @blairconrad and @adamralph :wave: :wave: :arrow_up:

**Comment by blairconrad** [comment]
Hi. We know that FakeItEasy is not threadsafe. You can see this in issue FakeItEasy/FakeItEasy#60 as @aarondandy referenced earlier.
Being stuck on an older .NET at work, I never `async` and `await`, and only rarely `Task` (and I don't think I've _faked_ a Task or something that returns one), so I can't say off the top of my head whether Tasks are especially bad, or if you're just seeing the regular thread-unsafety.

@bradwilson, no explicit use of thread-local storage. Quite a few statics (or at least shared instances of classes, with little to no attempts at synchronizing critical operations).

**Comment by blairconrad** [comment]
Oop. Based on @StefanBilliet's experience, I would guess that he was seeing the thread-unsafety, not a particular failing when using `Task<T>`.

**Comment by bradwilson** [comment]
Closing this, as it's not fundamentally an issue with xUnit.net.
