### ISSUE TITLE
2.0 replacement for DoesNotThrow?

### ISSUE THREAD

**Issue by niemyjski** [xunit/xunit#358]
Is there any replacement for DoesNotThrow? Or should we just remove it.

**Comment by bradwilson** [comment]
Think of it this way: every line of code you write outside of a `try` block has an invisible `Assert.DoesNotThrow` around it. :)

**Comment by niemyjski** [comment]
That's what I was thinking, it was just in 1.x so I used it :).

P.S., I upgraded and Approvals broke. I've already logged an [issue](https://github.com/approvals/ApprovalTests.Net/issues/112). But I figured I should let someone know just so they are in the loop :).

**Comment by hugonne** [comment]
How would you write a test that wants to verify that a particular method doesn't propagate the exception, but instead handles it?

**Comment by bradwilson** [comment]
```csharp
var ex = Record.Exception(() => ...code... );

Assert.Null(ex);
```

**Comment by LauraArmitage** [comment]
Sorry for commenting on an old issue but these docs need updating if the method DoesNotThrow no longer exists: https://xunit.github.io/docs/comparisons
Thanks!

**Comment by bradwilson** [comment]
@LauraArmitage  Thanks for the reminder! I've just updated the docs. :smiley: https://xunit.github.io/docs/comparisons#note5
