### ISSUE TITLE
Replacement for ClassData Attribute

### ISSUE THREAD

**Issue by toddca** [xunit/xunit#359]
Trying to upgrade a project to xUnit V2 with allot of [Theory] and [ClassData(typeof(SomeType))] however this feature has moved or been depreciated. Not really sure where the ClassDataAttribute was sourced from but I believe it was part of the extensions.

**Comment by toddca** [comment]
Found a reference to the class here https://github.com/paulecoyote/xunit/blob/master/Main/xunit.extensions/DataTheories/ClassDataAttribute.cs

integrated into my project so my issue is resolved.

**Comment by lijunle** [comment]
After read `MemberData` 's [source code](https://github.com/xunit/xunit/blob/ff6ecaaf4df79f4266e7d2ab24493e49a5133031/src/xunit.core/MemberDataAttributeBase.cs#L45), I find that `ClassData` attribute functionality has merged to `MemberData` attribute.

Do something like this:

```cs
[MemberData("{static member}", MemberType = typeof(MyClass))]
```

**Comment by bradwilson** [comment]
* `[ClassData]` in v1 was used to _**instantiate a class which was itself enumerable**_.
* `[MemberData]` can be used to pull enumerable data from a _**static member of a class**_.

They are fundamentally two different things.

**Comment by lijunle** [comment]
@bradwilson Sorry, I made a mistake.So, there is no official replacement for the v1 `ClassData` attribute?

**Comment by bradwilson** [comment]
Not at this time.

**Comment by lijunle** [comment]
What is the reason to remove it?

**Comment by bradwilson** [comment]
It was overlooked for 2.0.

**Comment by lijunle** [comment]
Will you accept such a PR?

**Comment by bradwilson** [comment]
Sure. :)
