### ISSUE TITLE
Cannot Run Tests in VS 2013 Ultimate

### ISSUE THREAD

**Issue by toddca** [xunit/xunit#360]
Tests enumerate just fine in VS and I can run them with Resharper V8.1 test runner. But when click on one test to run it the build happens, and the discovery starts again (not sure why) and the green progress bar starts scrolling and then everything just stops. 

Test output shows:
------ Discover test started ------
========== Discover test finished: 654 found (0:00:11.9238904) ==========
No tests found to run.

I have gone through everything on this page http://xunit.github.io/docs/running-tests-in-vs.html and I am totally in compliance. On V2 of everything from Nuget latest stable.

**Comment by toddca** [comment]
More info - my project is on local disk (no UNC) and I am running VS Ultimate 2013 update 4.

**Comment by bradwilson** [comment]
Is this a public project that I can test to repro with?

Also, can you please try cloning our Visual Studio Integration project at https://github.com/xunit/visualstudio.xunit.integration and see if those tests all run? (It's okay if you don't have all the supporting infrastructure like Windows Phone SDKs and emulators; I'm just looking to understand if the desktop projects are working as expected). *Note that about half the tests fail on purpose; what I'm looking for here is whether they get discovered and run.*

Thanks...

**Comment by toddca** [comment]
Brad, Using your test project I can confirm it does work. So I started looking in my project and I think I found the issue. On our core assembly which everything in the solution references we had a beforeBuild action that writes out a version into a globalAssembly.cs file that every project references. So when we would run a test it would try to determine build status, and see the core needed to be built as in the beforeBuild a new cs file would be written. This would cause discovery to kick in again and for some reason this would result in the 'no tests found to run' message. We removed that msbuild task from our core.proj and the tests run like a champ now. 

So what led me to this was that in your solution I would execute 1 test, it would run, then I would execute another test and it would run. In my environment I would execute 1 test, a build would occur, then the test would run (in xunit 1x), and then I would execute another test and a build would run and then the test would run.

**Comment by bradwilson** [comment]
Yeah, this is Visual Studio behavior that I don't really have any control over. :(

**Comment by toddca** [comment]
Thanks for your help -- so yea it appears that when VS takes a look at a project to see if it needs to be compiled it executes the preBuild event, this caused our globalAssembly.cs to get updated and hence the core.dll always needed to be compiled every time asked. Bummer.
