### ISSUE TITLE
From new project, it looks for xunit version 1.9.2.1075 for AssertManager

### ISSUE THREAD

**Issue by kousei2040** [xunit/xunit#361]
When I tried to create a new Unit test project with the latest xUnit 2.0, I was having this error when using the AssertManager

Could not load file or assembly 'xunit, Version=1.9.2.1705, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies. The system cannot find the file specified.

![image](https://cloud.githubusercontent.com/assets/7908918/6742331/dd1af5b6-cec9-11e4-8893-7aae7f8c6ee0.png)

**Comment by bradwilson** [comment]
I have no idea what "AssertManager" is.

**Comment by kousei2040** [comment]
Oops... You may close this item... I think I know now the reason...
