### ISSUE TITLE
Feature request: As a developer I want the AspNet runner to report results to AppVeyor

### ISSUE THREAD

**Issue by gingters** [xunit/xunit#369]
The console runner is capable of reporting test results to AppVeyor CI.
Sadly, aspnet 5 / vNext projects don't use the console runner, but the xunit.runner.aspnet.

If you want to build & tests these projects on AppVeyor, you don't have an easy way to see your test results. You would need to tweak the build infrastructure / KoreBuild to also generate test result xml files for each framework and test project, and manually upload them with additional scripts.

It would be great if also the aspnet runner, in addition to the console runner, would report its results to AppVeyor.

**Comment by bradwilson** [comment]
Dup of https://github.com/xunit/aspnet.xunit/issues/3 and https://github.com/xunit/aspnet.xunit/pull/4
