### ISSUE TITLE
Implement XUnit CollectionFixture in a different assembly

### ISSUE THREAD

**Issue by taherchhabra** [xunit/xunit#374]
http://stackoverflow.com/questions/28816607/implement-xunit-collectionfixture-in-a-different-assembly

**Comment by bradwilson** [comment]
This is supported:

- Assembly A: Fixture class
- Assembly B: Collection definition class, unit test class

This is not supported:

- Assembly A: Fixture class, collection definition class
- Assembly B: Unit test class

If you're doing the former, please provide a repro (because I can't repro).

If you're doing the latter, then what you're trying to do is not supported.

**Comment by taherchhabra** [comment]
I was doing the second one. was trying to reuse fixture+collection definition across projects. But now i have changed to the first option.
Thanks

**Comment by AArnott** [comment]
When doing the first option, does the fixture get created just once for all tests across assemblies that use that fixture?
For my case, it's very important that the fixture is only created once for the entire app domain and all its tests. I can fake it up by moving the fields in the fixture to a static class that the fixture just refers to, but I am wondering if that's necessary.

**Comment by bradwilson** [comment]
The answer is "no", but here is the longer answer to make sure we're on the same page.

If you use a class fixture for single class (or a collection fixture for a single collection), that fixture instance is shared among all the tests in that class/collection. If you use the same fixture for multiple classes/collections, then each class/collection gets its own unique instance of that fixture.

```csharp
public class TestClass1 : IClassFixture<MyFixture>
{
    // All tests in this class share instance #1 of MyFixture
    public TestClass1(MyFixture fixture) { ... }
}

public class TestClass2 : IClassFixture<MyFixture>
{
    // All tests in this class share instance #2 of MyFixture
    public TestClass2(MyFixture fixture) { ... }
}
```

The only way to get multiple classes to share the same fixture instance is to put them in a test collection together, and use a collection fixture.

There is no way to get multiple collections to share the same fixture instance.

**Comment by AArnott** [comment]
Hmmm.... bummer. Any possibility of supporting such a mechanism in the future?

**Comment by bradwilson** [comment]
We have no plans for assembly-level fixtures.

**Comment by AArnott** [comment]
I don't want an assembly level fixture. I want an AppDomain fixture, or AppDomain-wide collections. Before the first test in the collection starts, and after the last test ends, I need to set up and tear down (respectively) the Thread that serves as the "main thread", and other shared state. 

Short of that, I'll just have to resort to statics. And somehow I'll need to tear down the main thread before the test runner closes the AppDomain so it doesn't complain about lingering threads.

**Comment by bradwilson** [comment]
(a) not all runners use app domains, and (b) when we do, it's one test assembly per app domain. So whether you realized it or not, you were asking for assembly-level fixtures.

It is possible through extensibility to give the notion of assembly-level fixtures. The hooks are all there in the runner classes. It means defining your own "test framework", but it can be one will primarily reuses the xUnit.net extensibility classes, and therefore runs xUnit.net tests but with this added piece of functionality.

I've opened an issue for this to show how it's done. https://github.com/xunit/samples.xunit/issues/15

**Comment by bradwilson** [comment]
Also, xUnit.net does not have a concept of a "main thread". Tests are generally run on our own custom thread pool (or, occasionally as a fallback, on the system thread pool).

**Comment by AArnott** [comment]
By "main thread" I'm referring to the thread I create in the fixture that emulates the main thread in the application that normally hosts the extension that I'm testing.

**Comment by bradwilson** [comment]
After this discussion, I don't believe there is any work here for us to do.

**Comment by yngvark** [comment]
@bradwilson I believe the example https://github.com/xunit/samples.xunit/issues/15 has been moved to  https://github.com/xunit/samples.xunit/tree/master/AssemblyFixtureExample

**Comment by Wolfware2023** [comment]
I just encountered this issue too:
- I have a project with integration tests, which access the test-database. Using the CollectionFixture, we can ensure they run 1-by-1.
- I created a new project for system tests, so they also need to access the test-database. If I create a new CollectionFixture, then these tests might run simultaneously with the other tests, which might create issues in the tests.

So I guess I have to put the tests all in the same project and cant seperate the dependencies as nicely as I wanted?

**Comment by bradwilson** [comment]
This issue is significantly out of date with respect to where the project is.

In v3 pre-releases, we have support for assembly-level fixtures, as well as attaching collections by type instead of name (which allows the type to exist in another assembly).

**Comment by Wolfware2023** [comment]
> This issue is significantly out of date with respect to where the project is.
> In v3 pre-releases, we have support for assembly-level fixtures, as well as attaching collections by type instead of name (which allows the type to exist in another assembly).

Thanks for the update! Those sound like great improvements. Can't wait for an official release.

**Comment by weitzhandler** [comment]
I have an assembly which is shared between test projects, I tried to define the `AssemblyFixture` in it hoping it'll be shared between all test projects using it and it doesn't seem to work, looks like the `AssemblyFixture` must be declared in each test project separately, are there any plans to change that? Should I open a separate issue?
