### ISSUE TITLE
Discoverer not discovering tests with array parameter

### ISSUE THREAD

**Issue by herecydev** [xunit/xunit#376]
As per this [Gist](https://gist.github.com/herecydev/39a652d881353e4cb6c6) and this [twitter conversation](https://twitter.com/Smudge202/status/581081900200099840), it seems that having arrays for parameters when using a custom test discoverer is problematic.

The most concerning behavior here is that no exceptions are being thrown, no diagnostics raised and no errortestcases raised. This is dangerous as the build will pass when the tests don't get run.

**Comment by Smudge202** [comment]
If you're able to point us in the right direction @bradwilson (or anyone else) I'm happy to look into it.  But I don't admit to knowing the inner workings of xunit well enough to work this one out.

**Comment by bradwilson** [comment]
I haven't had an opportunity to dig into yet, to be honest.

**Comment by bradwilson** [comment]
Suspect this is the same problem as #384 which I just checked in a fix for.

**Comment by herecydev** [comment]
Awesome, thanks for that.
