### ISSUE TITLE
xunit1 does not always send ClassFinished messages

### ISSUE THREAD

**Issue by citizenmatt** [xunit/xunit#377]
The xunit1 code lives in a try/catch/finally block that will always call the `TestAssemblyFinished` message and will send `ErrorMessage` on exception. However, collection, class and method are not executed in try/finally blocks, so the `TestCollectionFinished` and `TestClassFinished` messages don't get sent in the case of an exception.

**Comment by bradwilson** [comment]
Do you have a repro case for when this happens?

**Comment by citizenmatt** [comment]
It's actually only the way xunit1 handles ambiguously named test methods. This'll do it:

```csharp
public class AmbiguouslyNamedTestMethods
{
    [Theory]
    [InlineData(12)]
    public void TestMethod1(int value)
    {
    }

    [Theory]
    [InlineData("foo")]
    public void TestMethod1(string value)
    {
    }
}
```

The runner starts to run the assembly, collection + class, then sees the ambiguous methods and throws and ends. It doesn't notify of class end or collection end but jumps straight to assembly finished.
