### ISSUE TITLE
Create FAQ at xunit.github.io for "How do I run test on the TFS 20?? build server"

### ISSUE THREAD

**Issue by bitbonk** [xunit/xunit#378]
Create FAQ at http://xunit.github.io for 

**How do I run test on the TFS 20?? build server?**

It is not really obvoius and seems to involve a lot of manual steps.

Is this still the way to do it? http://tech.trailmax.info/2014/01/run-xunit-in-hosted-team-foundation-service/

**Comment by bradwilson** [comment]
I have no idea. We don't officially support Team Build.

If someone wants to contribute up-to-date documentation, that would be great, but we won't be able to help.

**Comment by bradwilson** [comment]
Moved here: https://github.com/xunit/xunit.github.io/issues/19
