### ISSUE TITLE
Pass arguments to xUnit console test runner

### ISSUE THREAD

**Issue by JoaoPalinhas** [xunit/xunit#381]
Hi all,

I'd like to know if it's possible to pass arguments to xunit command line console. Since I'm using Jenkins to run my xunit tests, I need to know in my assembly file if I'm running a method or a Category (by using -trait option).

Thanks in advance,
João

**Comment by bradwilson** [comment]
I'm not sure I understand the question.

The console runner has several command line options. Just run it without any arguments (or use `-?`) to list the available command line arguments.

**Comment by bradwilson** [comment]
Environment variables are a good solution.

Also, if you're just looking to run subsets of tests, you can use `[Trait]` attributes and then use trait filtering, which is available in most of the test runners.

**Comment by malcolmarobertson** [comment]
I have a C#/Selenium/Specflow test suite which I am running using Jenkins using xunit.console.exe. I need to point these tests to different environments (Test/QA/Prod etc.) and would like to use a command line parameter.

The batch command I am calling is: "%WORKSPACE%\packages\xunit.runner.console.2.1.0\tools\xunit.console" "%WORKSPACE%[MyProject]\bin\Debug\eDC6.Test.Specs.dll" -xml test_output.xml

and would like to include an extra parameter like: "-env=PROD" to point that job to a specific environment.

I am open to better ways to do this.

**Comment by alexlazarciuc** [comment]
Hey @malcolmarobertson - did you manage to solve your issue and to read the params when running the tests from the code?

**Comment by malcolmarobertson** [comment]
Hi @alexlazarciuc yes I did, but not by using the xUnit runner. We added an Environment Parameter, which we read in before the tests run in the C# code.
e.g. 

 private TargetEnvironment getTargetEnvironment(RootObject root)
        {
            string envParam = Environment.GetEnvironmentVariable(nameof(root.[EnvironmentVar]) ?? "DEFAULT");

            if (string.IsNullOrEmpty(envParam))
                envParam = root.[EnvironmentVar];

            if (string.IsNullOrEmpty(envParam))
                envParam = "DEFAULT";

            var env = root.TargetEnvironments.FirstOrDefault(e => e.Name == envParam);

            if (env == null)
                throw new InvalidOperationException("Environment '{0}' was not defined.".FormatWith(envParam));

            return env;           
        }

**Comment by alexlazarciuc** [comment]
Hi @malcolmarobertson  - Thanks a lot for reply!

**Comment by jzabroski** [comment]
@malcolmarobertson Yes, that is possible, although it uses a global environment variable and therefore is not thread-safe if you have multiple build sessions on the same CI/CD physical instance without any hypervisor to separate them.

There are two approaches that may be cleaner:

1. Use an appSettings.json and configure your ConfigurationService to read from that file; if necessary to change configuration files, have a MSBuild target transform the settings file based on an Environment parameter
2. Use `Trait("TraitName", "TraitValue")]`, and `dotnet --filter TraitName=TraitValue` to only run specific tests
