### ISSUE TITLE
Provide test arguments to BeforeAfterTestAttribute?

### ISSUE THREAD

**Issue by axelheer** [xunit/xunit#386]
To run some general logic for theory arguments, some kind of test method interception would come in handy. Therefor I found the `BeforeAfterTestAttribute`, which unfortunately has only access to the test method's `MethodInfo`. Since these attributes are being invoked by `XunitTestInvoker`, which could provide the test method's arguments, maybe just that would make sense?

Or is there another chance to runs some code before and after any theory, which is able to access the theory data? Strictly speaking this code would be part of the test, thus "before test" / "after test" does not sound that right.

**Comment by bradwilson** [comment]
BeforeAfter attributes were designed to be completely orthogonal to any specific test; this is why they have ambient information about the test (`MethodInfo`), but no actual data (no instance of the test class, for example).

**Comment by axelheer** [comment]
Okay, I can understand that.

Is there another solution / approach? For ordinary *Facts* I use just `.ctor` / `Dispose`, but for *Theories* I'm not able to run some generic initialization / cleanup stuff without too much copy 'n paste.

It may be a bit abstract, but writing *Theories* like...

    public class SomeTests
    {
        [Theory]
        [SomeData]
        public void SomeShouldHappen(Some a, Some b, Some expected)
        {
            // f(a, b) == expected?
        }

        [Theory]
        [SomeData]
        public void SomeShouldHappenToo(Some a, Some b, Some c, Some expected)
        {
            // g(a, b, c) == expected?
        }

        [Theory]
        [SomeData]
        public void SomeShouldHappenAsWell(Some a, Some b, Some expected)
        {
            // h(a, b) == expected?
        }
    }

...and placing general setup / cleanup code like...

    public class SomeTests : IDisposable
    {
        public SomeTests(object[] args)
        {
            // a, b, maybe c, ...
        }

        public void Dispose()
        {
            // ...
        }
    }

...or...

    public class TheoryInterceptor
    {
        public void Setup(object[] args)
        {
            // a, b, maybe c, ...
        }

        public void Cleanup(object[] args)
        {
            // a, b, maybe c, ...
        }
    }

...would be great. Or am I doing it wrong?

**Comment by bradwilson** [comment]
There really is no functionality today like what you're looking for, I'm afraid. :(

**Comment by AlexanderSher** [comment]
I think you can extract a single theory into nested class and use IClassFixture<>

**Comment by axelheer** [comment]
@AlexanderSher I don't understand. Using `IClassFixture<>` means sharing some kind of context between tests, but I want to run setup / cleanup code based on theory arguments.

@bradwilson Some kind of constructor injection of theory arguments, to run some shared logic based on these arguments, would be nice. What do you think? I could try to implement that too. Any recommendations / preferences?

**Comment by axelheer** [comment]
Never mind, found another solution.

Background: to ensure immutability of some structure, I wanted to add some kind of *aspect* to every test. Alas, my original idea was to have something like an attribute.

    [Theory]
    [SomeData]
    [ShouldBeImmutable]
    public void SomeShouldHappen(Some a, Some b, Some expected)
    {
        // f(a, b) == expected?
    }

Since this seems not to be possible without some mumbo jumbo, I finally came up with a simple `IDisposeable` hack.

    [Theory]
    [SomeData]
    public void SomeShouldHappen(Some a, Some b, Some expected)
    {
        using (Immutability.Guard(a, b))
        {
            // f(a, b) == expected?
        }
    }

It's not that neat as an attribute / aspect, but it's just one line of code and works great.
