### ISSUE TITLE
Run XUnit tests in STA Apartment

### ISSUE THREAD

**Issue by radenkozec** [xunit/xunit#388]
Is there a easy way to run XUnit tests in STA thread apartment?
I have tried several ways with no success.
I am using VS 2015 
"xunit": "2.1.0.0-beta1-build2945",
"xunit.runner.aspnet": "2.1.0.0-beta1-build60",
 "xunit.runner.visualstudio": "2.1.0.0-beta1-build1051"

**Comment by radenkozec** [comment]
I have found this workaround project https://github.com/xunit/samples.xunit/tree/master/STAExamples but it would be nice have official support for this on ASP.NET 5 projects like NUnit.

**Comment by AArnott** [comment]
Also the `xunit.stafact` nuget package defines `[StaFact]` and several other attributes for use in testing UI code.
