### ISSUE TITLE
Problem with running Tests with attribute inheriting from Fact attribute

### ISSUE THREAD

**Issue by radenkozec** [xunit/xunit#391]
I have implemented project based on https://github.com/xunit/samples.xunit/tree/master/STAExamples
to run test in STAThread apartment.

When I put STAFact (which inherit from Fact) above my test method tests are discovered but not runned.
I am getting message: Source: no source available.

I am using VS 2015 
"xunit": "2.1.0.0-beta1-build2945",
"xunit.runner.aspnet": "2.1.0.0-beta1-build60",
"xunit.runner.visualstudio": "2.1.0.0-beta1-build1051"

**Comment by radenkozec** [comment]
I have managed to solve issue by creating test project on old Class library project instead of ASP.NET 5.
Than STAExample workes fine. 
Problem is probably related with reflection and getting assembly info from this type of project

**Comment by bradwilson** [comment]
My guess is that ASP.NET 5 does not support STA. Thoughts @davidfowl @damianedwards?
