### ISSUE TITLE
Failing tests in MSBuild runner

### ISSUE THREAD

**Issue by ursenzler** [xunit/xunit#392]
Maybe you can point me to some possibilities of this behaviour. I'm still trying to understand the error itself. Any input is welcome.

The reason I put the issue here is because the test suite behaves differently when run using the console runner (succeeds) or the MSBuild runner (some failing tests). Maybe you can point me to the differences between them.

I run xUnit tests that use FakeItEasy as an faking library. Some of the tests using the MustHaveHappened mechanism (check that a call onto a fake was made) fail. But only with the MSBuild runner.

**Comment by ursenzler** [comment]
it is a problem within FakeItEasy.

**Comment by bradwilson** [comment]
You can probably "fix" it by turning off all parallelization.

There are switches on the runners for this, or you can configure each individual project using `App.config` files: http://xunit.github.io/docs/configuration-files.html

**Comment by ursenzler** [comment]
I thought that parallelization causes this, too. Therefore I added

[assembly: CollectionBehavior(DisableTestParallelization = true)]

in the assembly info. Still the same behaviour: 1 out of about 3 runs, a test is failing. And it's not only in the MSBuild runner, it fails in the console runner, too.

I could narrow it down to Argument Matching in calls to fakes.
I'll open an issue at FakeItEasy.

But maybe you have an idea what could be the cause, besides parallelization? Or are the tests always run on seperate threads (just synchronized in case of no parallelization)?
The tests run without problem under xUnit 1.0.

**Comment by ursenzler** [comment]
I found the cause of the issue. it is already documented at https://github.com/FakeItEasy/FakeItEasy/issues/476
A quick hack let me run the tests successfully.

But I still wonder, why the problem persisted when turning parallelization off. Is there still running something on different threads?

**Comment by bradwilson** [comment]
I'll refer you to this previous discussion: https://github.com/xunit/xunit/issues/357

**Comment by bradwilson** [comment]
Also, since turning off parallelization didn't work, you may want to leave parallelization on but set the maximum number of threads to 1. This may actually get better behavior for this problem, because it guarantees all Task code will run on the same thread.

**Comment by ursenzler** [comment]
Many thanks.
