### ISSUE TITLE
Question: What means the "completed" output in xunit 2.0

### ISSUE THREAD

**Issue by ursenzler** [xunit/xunit#393]
When I run some unit tests, the runner writes this to the console:
```
  xUnit.net MSBuild runner (32-bit .NET 4.0.30319.34209)
    Discovering: Appccelerate.StateMachine.Facts
    Discovered:  Appccelerate.StateMachine.Facts
    Starting:    Appccelerate.StateMachine.Facts
completed A to B
completed B to C
completed C to D
completed A to B
completed B to C
completed C to D
    Finished:    Appccelerate.StateMachine.Facts
```

What do the "completed" messages mean?
And why is every message written twice?

Just wondering.

Keep up the good work!

**Comment by bradwilson** [comment]
Those messages aren't part of xUnit.net. I presume they are Console output from somewhere inside your tests.

**Comment by ursenzler** [comment]
Brad, you are really fast, and right. Probably time to stop working %-)
