### ISSUE TITLE
Add serialization support for unsigned types

### ISSUE THREAD

**Issue by MartinJohns** [xunit/xunit#397]
Hello,

I've noticed a weird behavior with Xunit (2.0.0 and 2.1.0-beta1).

The following test case produces the expected result. It is correctly identified as two test cases and is shown as such in the Visual Studio test explorer.

    [Theory]
    [InlineData(1)]
    [InlineData(2)]
    public void TestCase1(int i) {}

With the following test case this does not happen. Instead it's just shown as one single test case. But all datas a provided to the method.

    [Theory]
    [InlineData(1U)]
    [InlineData(2U)]
    public void TestCase2(UInt32 i) {}

![Test Explorer in VS2015](http://i.imgur.com/yezvV3d.png)

**Comment by bradwilson** [comment]
Any data which is not supported by the serialization system causes pre-discovery to stop for that test-case, and revert back to the 1.x behavior (single method for the theory). Note that you can still run the tests, you just can't run individual data sets (running the method always runs all data sets).

The full list is here:
https://github.com/xunit/xunit/blob/9464b84ab32959da8b5b16fa25541aa89a8dd6b6/src/common/XunitSerializationInfo.cs#L259-L289

As you can see, none of the unsigned integral types are supported in 2.0. We can add them for 2.1.

**Comment by MartinJohns** [comment]
Hey Brad. Thanks for this quick fix. But this seems like a very limiting approach. Any chance to make this extensible on our own?

**Comment by bradwilson** [comment]
For your own custom types, you can implement `IXunitSerializable`.

https://github.com/xunit/xunit/blob/master/src/abstractions/xunit.abstractions/Serialization/IXunitSerializable.cs
