### ISSUE TITLE
[Question] xunit 2.0: EnumerateTestCommands

### ISSUE THREAD

**Issue by ashmind** [xunit/xunit#399]
I'm trying xUnit 2.0 for a project that has custom attributes inherited from `FactAttribute`.
In 2.0, `FactAttribute` seems to be missing `EnumerateTestCommands`.

Is `[Theory]` + custom data attribute the recommended way forward?
Using two attributes feels too verbose in some of my scenarios.

**Comment by bradwilson** [comment]
The equivalent of `EnumerateTestCommands` is to implement a discoverer. The [RetryFactExample](https://github.com/xunit/samples.xunit/tree/d9dcdba0fe5b8513bf8d75773a12758fe5f36adf/RetryFactExample) contains a [custom `Fact` attribute with a decorator](https://github.com/xunit/samples.xunit/blob/d9dcdba0fe5b8513bf8d75773a12758fe5f36adf/RetryFactExample/RetryFactAttribute.cs#L9) and a [discoverer](https://github.com/xunit/samples.xunit/blob/d9dcdba0fe5b8513bf8d75773a12758fe5f36adf/RetryFactExample/RetryFactDiscoverer.cs). This sample uses a custom test case, too, but that part is not required. You can return instances of [`XunitTestCase`](https://github.com/xunit/xunit/blob/54d145e6413088c89714e7ed0e1f26c0335188b8/src/xunit.execution/Sdk/Frameworks/XunitTestCase.cs) if you want the built-in behavior.

**Comment by ashmind** [comment]
@bradwilson Thanks! I'll take a look.
