### ISSUE TITLE
RetryFactAttribute tests are not found by Test Runner

### ISSUE THREAD

**Issue by lcremer** [xunit/xunit#402]
I found the Retry example in the samples repo and implemented it for use in our functional UI tests.
But it seems we are out of luck as the tests are not being found by the test runner or the console runner.
I did some digging  and think it's due to how FindTestsForMethods is implemented in the XunitTestFrameworkDiscoverer class.

Is there another way that RetryFactAttribute needs to implemented or possibly a work around that I can implement to get around this issue?

**Comment by bradwilson** [comment]
Which runner is "the test runner"? There are about 8 of them. :)

**Comment by bradwilson** [comment]
Here is the sample project, running with the 2.0 console runner:

![samples running with console runner](https://cloud.githubusercontent.com/assets/16944/7308680/5c102e60-e9cb-11e4-929b-05ee1d81784c.png)

Can you reproduce this result?

**Comment by bradwilson** [comment]
Assuming you've copied the classes into your project, did you remember to update this line to correctly reference the fully qualified type name and assembly name of the discoverer?

https://github.com/xunit/samples.xunit/blob/d9dcdba0fe5b8513bf8d75773a12758fe5f36adf/RetryFactExample/RetryFactAttribute.cs#L9

**Comment by lcremer** [comment]
I was testing with the Visual studio test runner. I just double checked to make sure that I had updated the namespace. That is really the only thing I changed, I made sure that it was correctly set.

I will try and reproduce the 2.0 console runner results tonight. Thanks for taking a look!

**Comment by lcremer** [comment]
I resolved the issue. I had to create a separate project for the retry fact attribute example.
The tests wont be found otherwise.
