### ISSUE TITLE
Drop Windows 8 app support

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#406]
We are considering dropping Windows 8 app support in version 2.1. **We will continue to support Windows 8.1 and Windows 10 apps.**

The motivation behind this idea includes:

- There is a "bug"(1) in NuGet which causes Windows 8.1 test projects to incorrectly select the `win8` target framework library instead of the more appropriate `portable-win81+wpa81` library. This can become a significant issue for test runners which intend only to support universal apps, but get incorrectly linked against the non-universal `win8` library.
- We are moving to Visual Studio 2015, which is discontinuing Windows 8 app support (it will still support Windows 8.1 and Windows 10 apps). It's clear that Microsoft wants people moved to Windows 8.1 and Windows 10 applications, particularly since all Windows 8 users are eligible to a free upgrade to Windows 8.1.

This thread is here so the community can provide feedback on this plan.

_(1) = I call this a "bug" because you can make arguments on both sides of the issue (that portable libraries generally have fewer features than platform-specific ones, even if those platform-specific libraries are for older frameworks). The point is not to argue whether this decision is correct or not, but to accept the reality of NuGet's behavior today in our particular scenario._

**Comment by onovotny** [comment]
Seems like 
![The Silence](http://ichef.bbci.co.uk/images/ic/528xn/p00rwp7x.jpg)
has spoken.

Shall I submit a PR to nuke win8 from 2.x?

**Comment by bradwilson** [comment]
I'm going to throw another reminder onto Twitter. I do want to give people an honest opportunity to chime in. :)

**Comment by rskopecek** [comment]
Yes, drop Win 8.  No need to force support as it is not unreasonable for people to move from 8 to 8.1 which they should have already done.

**Comment by ceee** [comment]
No reason to keep 8.0 support. Most of devs have already moved to 8.1+ (and users too), and I am pretty sure most active 8.0 devs won't have a problem with sticking to an older version of the lib, as they still can get on nu.

**Comment by bradwilson** [comment]
It's going away this weekend. Thanks for the feedback. :)

**Comment by onovotny** [comment]
:+1: Burn it with :fire:
