### ISSUE TITLE
Collection Fixtures not working sometimes

### ISSUE THREAD

**Issue by zijianhuang** [xunit/xunit#409]
After spending a few hours and reading http://xunit.github.io/docs/shared-context.html a few times, I finally found out why.

I had this
[CollectionDefinition("IISExpress")]
public class IisCollection : ICollectionFixture<Fonlow.Testing.IisExpressFixture>
{
}

in the same assembly Fonlow.Testing.dll together with IisExpressFixture, to be reused by multiple projects of integration testing. Now I know class IisCollection has to be defined in each xUnit test project. The the scope of IisCollection is within the test assembly. 

Anyway, it will be better to mention in the documentation that the scope of the class decorated by CollectionDefinitionAttribute is within the test assembly. So programmers with good habits of developing reusable classes and components will keep this in mind.

**Comment by zijianhuang** [comment]
As Brad had suggested, "this was by design in the current version, but we are considering fixing it in a subsequent version". I don't mind copy and paste just 2 lines of codes to every test assembly that need to launch IIS Express. The whole thing still looks simple and elegant to me.

If the tear up/down operations are very expensive and slow, yes, it is desirable to have the context to be shared across multiple test assemblies.

**Comment by bradwilson** [comment]
To be clear, what I believe to be the bug is that we only search for collection definitions in the test assembly, not in all the assemblies.

This does ***not*** mean that we would support a single collection fixture instances across test assemblies. Each test assembly runes isolated in its own App Domain. You could still get a new instance of the collection fixture per App Domain.

**Comment by bradwilson** [comment]
After discussion, we've decided not to fix this issue, as it's working as we intended.
