### ISSUE TITLE
In v2: is Assert.Equals<double> meant to always fail?

### ISSUE THREAD

**Issue by TimLovellSmith** [xunit/xunit#413]
I just updated to xunit 2.0 and now I see a whole bunch of test failures like this:

Assert.Equal() Failure
Expected: 0.0166666666666667
Actual:   0.0166666666666667

Assert.Equal() Failure
Expected: 0.0833333333333333
Actual:   0.0833333333333333

What changed about the double equality test between xunit v1 and v2 that caused this - is this a bug or intentional?

**Comment by bradwilson** [comment]
Generally speaking:

- Equality for doubles ***with precision*** has not changed (see the source below)
- Equality for doubles ***without precision*** is bound to fail unpredictably, given the imprecision of floating point math.

Based on the message that you're showing here (i.e., the lack of "rounded from" in the messages), it looks like you're doing `Assert.Equal` without using precision. My recommendation is to use the precision-based comparison.

Here is the source for purposes of comparison.

[v1](https://github.com/xunit/xunit/blob/9aef27cd20ce6bb06287dc37c490f50b69bdc55d/src/xunit/Assert.cs#L212-L223
)

```csharp
public static void Equal(double expected, double actual, int precision)
{
    var expectedRounded = Math.Round(expected, precision);
    var actualRounded = Math.Round(actual, precision);

    if (!GetEqualityComparer<double>().Equals(expectedRounded, actualRounded))
        throw new EqualException(
            String.Format("{0} (rounded from {1})", expectedRounded, expected),
            String.Format("{0} (rounded from {1})", actualRounded, actual),
            skipPositionCheck: true
        );
}
```

[v2](https://github.com/xunit/xunit/blob/08455f9f761a5e10aa709970423575260f9aa858/src/xunit.assert/Asserts/EqualityAsserts.cs#L46-L56)

```csharp
public static void Equal(double expected, double actual, int precision)
{
    var expectedRounded = Math.Round(expected, precision);
    var actualRounded = Math.Round(actual, precision);

    if (!GetEqualityComparer<double>().Equals(expectedRounded, actualRounded))
        throw new EqualException(
            String.Format(CultureInfo.CurrentCulture, "{0} (rounded from {1})", expectedRounded, expected),
            String.Format(CultureInfo.CurrentCulture, "{0} (rounded from {1})", actualRounded, actual)
        );
}
```

**Comment by TimLovellSmith** [comment]
OK. Thanks for clarifying. :)
