### ISSUE TITLE
Cannot discover tests in XUnit 2 after upgrading to Visual Studio 2015 RC

### ISSUE THREAD

**Issue by radenkozec** [xunit/xunit#415]
I am having classic .NET 4.5 class library project for tests.
After I have upgraded visual studio to 2015 RC Visual Studio test runner does not discover any tests on build.

I have installed following packages:
```xml
  <package id="xunit" version="2.0.0" targetFramework="net45" userInstalled="true" />
  <package id="xunit.abstractions" version="2.0.0" targetFramework="net45" userInstalled="true" />
  <package id="xunit.assert" version="2.0.0" targetFramework="net45" userInstalled="true" />
  <package id="xunit.core" version="2.0.0" targetFramework="net45" userInstalled="true" />
  <package id="xunit.extensibility.core" version="2.0.0" targetFramework="net45" userInstalled="true" />
  <package id="xunit.extensibility.execution" version="2.0.0" targetFramework="net451" userInstalled="true" />
  <package id="xunit.runner.visualstudio" version="2.0.0" targetFramework="net45" userInstalled="true" />
```

**Comment by bradwilson** [comment]
If you clone the [Visual Studio Integration](https://github.com/xunit/visualstudio.xunit.integration) test project and build it, does Visual Studio discover any tests for you?

**Comment by radenkozec** [comment]
Hi Brad. Thanks for prompt response. 

When I restarted PC this morning I can discover tests in VS 2015 RC in both projects on build. 

I had similar problems sometimes on VS 2015 CTP 6 but when I re-opened solution I have managed to discover tests.
I am hopping that problems are solved for now on VS2015 RC.

If this occur again I will re-open issue.
Thanks

**Comment by bradwilson** [comment]
It's Windows! When in doubt, reboot. Sometimes twice. :stuck_out_tongue_winking_eye:
