### ISSUE TITLE
Is it possible to get name/context of the running test?

### ISSUE THREAD

**Issue by alfeg** [xunit/xunit#416]
We moving from nUnit to xUnit.
In nUnit we were using TestContext to get name of running test  to collect some performance stats on running tests.
Is it possible in xUnit?

**Comment by bradwilson** [comment]
Sorry, there is no equivalent to TestContext in xUnit.net.

**Comment by maxim-boligatov** [comment]
Maybe it is good time to implement it? Who is the idiot thinking that xUnit is replacement for unit testing system in VS2015?

**Comment by slawomir-brzezinski-at-interxion** [comment]
Duplicated by #416

**Comment by laurynasr** [comment]
There actually is a way for getting some of current test information, but for some reason not exposed to general public.
You need to inject an ITestOutputHelper instance to your test class, and use some reflection magic to get an ITest instance:

```csharp
public class Tests
  {
  public Tests(ITestOutputHelper output)
    {
    var type = output.GetType();
    var testMember = type.GetField("test", BindingFlags.Instance | BindingFlags.NonPublic);
    var test = (ITest)testMember.GetValue(output);
    }
<...>
  }
```

@bradwilson there already is a test context being used in xUnit, why can't it be injected just like ITestOutputHelper?

**Comment by otac0n** [comment]
@laurynasr This worked perfectly for my use case.  +1

**Comment by danrozenberg** [comment]
I wish we could do this without needing to resort to reflection (or even without requesting an ITestOutputHelper).

**Comment by SimonCropp** [comment]
i needed this for a few of my projects. so i bundled it into my xunit logging lib https://github.com/SimonCropp/XunitLogger#current-test

**Comment by ColinM9991** [comment]
There seem to be fundamental gaps in the Xunit framework, such as parameters via console not being supported, no `TestContext` equivalent.

Are these things even being considered for implementation?

**Comment by bradwilson** [comment]
#621 
#2001
