### ISSUE TITLE
Support mocking the return value when the type is Task/Task<T>

### ISSUE THREAD

**Issue by JasonMing** [xunit/xunit#421]
In xunit 2.0.0 :

When `Mock<T>.DefaultValue == DefaultValue.Empty`, the default return value of async method, which returns `Task` or `Task<T>`, will directly return null, then `await` on them will cause NullRefereceException.
In this case, the "Empty" value should be `Task.FromResult(default(T))`.

When `Mock<T>.DefaultValue == DefaultValue.Mock` the default return value of async method will change to the mocking `Task`/`Task<T>`, however, the `Task`/`Task<T>` are not able to be mocked, then the **System.ArgumentExceptionType to mock must be an interface or an abstract or non-sealed class.** will be thrown.
In this case, the "Mock" value should be `Task.FromResult(Mock.Of<T>())`.

**Comment by bradwilson** [comment]
Why is this an xUnit.net issue? It does not provide (nor prefer) any mocking support.

**Comment by JasonMing** [comment]
Oh, I'm sorry, I post to the wrong project.
