### ISSUE TITLE
Add IAsyncFixture for async startup and cleanup

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#424]
While constructor and Dispose are good general patterns, they are both very broken in the face of async code. Adding an interface would allow async fixtures and give them the equivalent of async construction and disposal.

**Comment by RichiCoder1** [comment]
:+1: Just ran into this. Async initialization and Disposal would be great.

**Comment by RichiCoder1** [comment]
Fixing in https://github.com/xunit/xunit/pull/531

**Comment by bradwilson** [comment]
Sorry, I meant to come back and add a link. Thanks!

**Comment by RichiCoder1** [comment]
No problem! Was just briefly confused :). Keep up the awesome work! Can't wait to use 2.1.

**Comment by johncrim** [comment]
Note that the #531 fix doesn't add support for async cleanup of test classes, only async cleanup of fixtures. Should this issue be re-opened, or create a new one?
