### ISSUE TITLE
Missing dnx-clr-win-x86.1.0.0-beta5-11682

### ISSUE THREAD

**Issue by krwq** [xunit/xunit#426]
When trying to open solution `xunit.vs2015.NoXamarin.sln` using VS 2015 RC I'm getting error that DNX runtime `dnx-clr-win-x86.1.0.0-beta5-11682` is missing. (fresh git clone)

I tried to install it using `dnvm install 1.0.0-beta5-11682` and `dnvm install dnx-clr-win-x86.1.0.0-beta5-11682` but I get an error that they are both missing. I went to the dnx repo and built it and it installed a version `dnx-clr-win-x86.1.0.0-beta5-11896` which seems to not fix the issue.

When I go to the folder:
`C:\Users\krwq\.dnx\runtimes`
and copy & paste the newer version of runtime and rename it to the version it looks for the solution opens without errors and builds fine.

**Comment by MichaCo** [comment]
Use `dnvm install 1.0.0-beta5-11682 -u`, otherwise dnvm will not use the dev feed.
