### ISSUE TITLE
PartialTrustFact?

### ISSUE THREAD

**Issue by shytikov** [xunit/xunit#430]
Hi,

I need to how my code will act in partial trust environment, and after some googling I discovered that `xUnit` actually allows [easy implementation](http://www.bricelam.net/2012/08/partial-trust-testing-with-xunitnet.html) of this scenario by involving `[PartialTrustFact]` attribute.

Maybe this attribute implementation should be part of the standard codebase?

**Comment by shytikov** [comment]
Ok, implementation is not easy, taking into account that API was changed completely :facepunch: 

I need to implement this by my own from scratch... Is there any documentation covering new API? Maybe some advices from experienced xUnit developers? Anyone?

And main question, is it possible at all to implement "Sanboxable" run of unit tests taking into account API changes?

Many thanks in advance for any information.

**Comment by bradwilson** [comment]
The samples project will be helpful here; in particular, I believe the `[STAFact]` example is probably closest to what you're going to need to do: https://github.com/xunit/samples.xunit/tree/master/STAExamples

**Comment by shytikov** [comment]
Thanks, it looks like it should be enough for me to complete the task!

By the way, API v.2 looks indeed much cleaner!

P.S. Can you leave this issue open for a while? Just in case of some questions will come up?

P.P.S. If

**Comment by shytikov** [comment]
Sorry, was posting from mobile and pressed something wronng.

My second post scriptum. I plan to share my code afterwards, so it could be added to samples project.

**Comment by shytikov** [comment]
So far I managed to create needed AppDomain container, pass all input parameters to the unit test execution wrapper, but I need to get `TaskCompletionSource<RunSummary>` as an answer. And here goes the trouble:

> Type 'System.Threading.Tasks.TaskCompletionSource`1' in assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' is not marked as serializable.

As far as I got, all arguments we're passing to AppDomain sandboxed methods should be either serializable or implement `MarshalByRefObject`. And both these options seems to be useless in this case.

Can you advise something? Maybe there another way to run tests except calling `RunAsync`, or maybe I should override it in some sophisticated manner? 

Thanks in advance!

**Comment by shytikov** [comment]
For me it looks like a dead-end. It couldn't be done without hacking the core, or I don't have right overview of `xunit` API.

Parameters what are passed to test case and received from it are not marked as `serializable`. This makes everything much more complicated than it should. And the asynchronous manner of running plugins are also makes things even more difficult, since result should be returned from one AppDomain to another.

It might be an option to serialize data into the memory and share it between domains manually... **BUT**! Depending on settings of AppDomain it might be forbidden to manually serialize things inside of it.

The irony is that I need this functionality to be able test serialization in partial trust sandbox environment... 

Can somebody help me elaborate how it might be possible to implement this functionality in minimal cost possible?

**Comment by shytikov** [comment]
Managed to make everything work as I wanted it to work.

However, it was done by extending `NUnit`... There I've managed to overcome this serialization issue.

I'm closing this issue, but I'm going to open new one. Since `xUnit` API is still changing, it would be nice to have ability implement restricted tests in `xUnit` as well.
