### ISSUE TITLE
AssemblyInitialize or similar

### ISSUE THREAD

**Issue by alexfoxgill** [xunit/xunit#431]
I have [this issue](http://stackoverflow.com/questions/23033505/unit-testing-with-effort-and-sql-ce-in-parallel-fails). The recommended answer is to use an assembly-wide initialization method:

```CSharp
    [AssemblyInitialize()]
    public static void AssemblyInit(TestContext context)
    {
        Effort.Provider.EffortProviderConfiguration.RegisterProvider();
    }
```

I can't find one for xUnit (1.9.2) - does such a thing exist? Might it, in the future?

**Comment by bradwilson** [comment]
Sorry, there's not.

The fixture concept (which is how you group together things that have shared state/context) can only be applied at a class and collection level. There is no assembly-level fixture.

http://xunit.github.io/docs/shared-context.html

**Comment by alexfoxgill** [comment]
That's a shame! Built-in support from xUnit would be ideal, but I have found an alternative solution to my problem and have described it [here](http://stackoverflow.com/questions/30730224/running-code-on-assembly-load-in-xunit/30730225#30730225).

On my search I did see a comment made by someone some time ago saying that this feature was planned for xUnit v2 but I guess it got dropped.

I'll close this and hope that my found solution can be of use to someone.

**Comment by rosieks** [comment]
@bradwilson Are you going to add this feature to xunit? Without that I'm forced to use some weird solutions or refactor all my tests to by fixture?

**Comment by bradwilson** [comment]
No, we're not planning to add this. You can use the extensibility model to achieve this; in fact, we have a sample that shows exactly that.

https://github.com/xunit/samples.xunit/tree/master/AssemblyFixtureExample

**Comment by girishjjain** [comment]
I tried Collection Fixtures approach and it's pretty neat, works as expected and didn't require much code either. In case anyone reaches this page then I would suggest to use approach suggested by @bradwilson using below link:
http://xunit.github.io/docs/shared-context.html

**Comment by andysmi99** [comment]
I would like to request this feature. This is much easier to implement in NUnit with the simple attribute, no need for creating Fixtures or Collection Fixtures.

**Comment by abatishchev** [comment]
Any chance to add this?

**Comment by ohadschn** [comment]
If you don't need the `TestContext`, a static constructor could do the trick.
