### ISSUE TITLE
Types received from it should be `serializable`

### ISSUE THREAD

**Issue by shytikov** [xunit/xunit#433]
I was trying to extend `xUnit 2` in the way to allow running tests in partial trust environment (#430). However I was not able to do so, since types passed to and received from test runner cannot be serialized, thus they could not be shared between AppDomains. 

I've made input parameters accessible from child AppDomain by gathering them into object derived from `MarshalByRefObject`, but my biggest issue was `TaskCompletionSource<RunSummary>` I was not able to make it cross AppDomain border no matter what I did.

Maybe it's done by-design, but this just means, that another type should be used for return value.

**Comment by bradwilson** [comment]
I was able to get a [sample working for partial trust](https://github.com/xunit/samples.xunit/tree/master/PartialTrustExample) without needing any core framework changes.

The only stumbling block I really hit was that the xUnit.net assertion exceptions aren't serializable (which gives a less than ideal message when your assertions fail). I've [logged a bug](https://github.com/xunit/xunit/issues/454) to look into whether anything can be done about this limitation for users who bring in the assertion library via source.

**Comment by shytikov** [comment]
:+1: Thanks for sample code!
