### ISSUE TITLE
Theory with multi rows of data always run in parallel?

### ISSUE THREAD

**Issue by techpro79** [xunit/xunit#438]
How do I make it run in serial?

**Comment by bradwilson** [comment]
Can you provide a repro? Using this code:

```csharp
using System;
using System.Threading;
using Xunit;

public class TestClass
{
    [Theory]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(3)]
    public void MyTheory(int unused)
    {
        Console.WriteLine("Starting {0}", unused);
        Thread.Sleep(500);
        Console.WriteLine("Finished {0}", unused);
    }
}
```

I got this output:

```
xUnit.net console test runner (64-bit .NET 4.0.30319.0)
Copyright (C) 2015 Outercurve Foundation.

Discovering: foo
Discovered:  foo
Starting:    foo
Starting 3
Finished 3
Starting 2
Finished 2
Starting 1
Finished 1
Finished:    foo

=== TEST EXECUTION SUMMARY ===
   foo  Total: 3, Errors: 0, Failed: 0, Skipped: 0, Time: 1.655s
```

You can see that each test finished before the next one started running.

**Comment by techpro79** [comment]
My code:

using Microsoft.Framework.ConfigurationModel;
using System;
using System.Collections.Generic;
using Xunit;

namespace WalkingTec.Mvvm.Core.Test
{
    public class ConfigTest
    {
        public ConfigTest()
        {
        }

        [Theory]
        [InlineData("AspNetMVVM:Common:CookiePrefix", "prefixvalue")]
        [InlineData("AspNetMVVM:Common:CookiePrefix", "xxx")]
        [InlineData("AspNetMVVM:Common:CookiePrefix", "aaa")]
        public void CookiePrefix(string k, string v)
        {
            Console.WriteLine("Starting {0}", v);
            var con = new Configuration();
            con.Add(new MemoryConfigurationSource(new List<KeyValuePair<string, string>>()
            {
                new KeyValuePair<string, string>(k,v),
            }));
            Configs.CommonConfig = con;
            if (v == null)
            {
                Assert.True(Configs.CookiePre == "");
            }
            else
            {
                Assert.True(Configs.CookiePre == v, "value is " + Configs.CookiePre);
            }
            Console.WriteLine("End {0}", v);
        }
    }

    public static class Configs
    {


        private static Configuration _commonConfig;
        public static Configuration CommonConfig
        {
            get
            {
                if (_commonConfig == null)
                {
                    _commonConfig = new Configuration();
                }
                return _commonConfig;
            }
            set
            {
                _commonConfig = value;
            }
        }

        private static string _cookiePre;

        public static string CookiePre
        {
            get
            {
                if (_cookiePre == null)
                {
                    var ls = CommonConfig.Get("AspNetMVVM:Common:CookiePrefix");
                    if (string.IsNullOrEmpty(ls))
                    {
                        _cookiePre = "";
                    }
                    else
                    {
                        _cookiePre = ls;
                    }
                }
                return _cookiePre;
            }
        }

    }
}

The output:
xUnit.net DNX test runner (64-bit DNX 4.5.1)
Copyright (C) 2015 Outercurve Foundation.

Discovering: WalkingTec.Mvvm.Core.Test
Discovered:  WalkingTec.Mvvm.Core.Test
Starting:    WalkingTec.Mvvm.Core.Test
Starting prefixvalue
End prefixvalue
Starting aaa
Starting xxx
   WalkingTec.Mvvm.Core.Test.ConfigTest.CookiePrefix(k: "AspNetMVVM:Common:Cooki
ePrefix", v: "aaa") [FAIL]
      value is prefixvalue
      Expected: True
      Actual:   False
      Stack Trace:
            在 Xunit.Assert.True(Nullable`1 condition, String userMessage) 位置
C:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.assert\Asserts\BooleanAss
erts.cs:行号 90
            在 WalkingTec.Mvvm.Core.Test.ConfigTest.CookiePrefix(String k, Strin
g v) 位置 C:\Users\Michael\Documents\Visual Studio 2015\Projects\WalkingTec.Mvvm
\WalkingTec.Mvvm.Core.Test\ConfigTest.cs:行号 33
   WalkingTec.Mvvm.Core.Test.ConfigTest.CookiePrefix(k: "AspNetMVVM:Common:Cooki
ePrefix", v: "xxx") [FAIL]
      value is prefixvalue
      Expected: True
      Actual:   False
      Stack Trace:
            在 Xunit.Assert.True(Nullable`1 condition, String userMessage) 位置
C:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.assert\Asserts\BooleanAss
erts.cs:行号 90
            在 WalkingTec.Mvvm.Core.Test.ConfigTest.CookiePrefix(String k, Strin
g v) 位置 C:\Users\Michael\Documents\Visual Studio 2015\Projects\WalkingTec.Mvvm
\WalkingTec.Mvvm.Core.Test\ConfigTest.cs:行号 33
Finished:    WalkingTec.Mvvm.Core.Test

=== TEST EXECUTION SUMMARY ===
   WalkingTec.Mvvm.Core.Test  Total: 3, Errors: 0, Failed: 2, Skipped: 0, Time:
0.117s

**Comment by techpro79** [comment]
Is it because I test against static variable?

**Comment by bradwilson** [comment]
Static variables will preserve the value across multiple test runs; they are not reset between runs. It sounds like this may be the issue you're having.

**Comment by techpro79** [comment]
But I set the static variable at the begining of the test, the problem is that the second test runs before the first finish. you can see from the result:
Starting aaa
 Starting xxx

**Comment by bradwilson** [comment]
You're right, I missed that. I'll see if I can repro it tomorrow.

**Comment by techpro79** [comment]
Sorry man , it's my fault. my static variable won't change it's value once it has one. The output error messages mislead me, it shows all assert error message after all theroy finish, so I got 

Starting aaa
Starting xxx
followed by errors

it looks like xxx start before aaa finished, but it's not. it's only because assert failed and "End aaa" message won't show

It would be nice if the error can be show like this:

Starting aaa
assert error for aaa
Starting xxx
assert error for bbb

so that idiot  like me won't get it wrong...

**Comment by bradwilson** [comment]
Ah, I see.

The reporting is done asynchronously. When the error happens, it puts a message onto a message bus to be sent to back to the user, and then the execution engine continues on its merry way. At that point it's a race to determine who would output things first.

**Comment by bradwilson** [comment]
To be clear: theories are NOT executing in parallel here. The issue is that the message system used to _**report results**_ is asynchronous.
