### ISSUE TITLE
Project based xUnit runner requires reopened solution

### ISSUE THREAD

**Issue by mwpowellhtx** [xunit/xunit#439]
It feels like about every third or fourth iteration of debugging a unit test, for whatever reason force stopping, i.e. Shift+F5, or even simply re-running a debug session, that is is necessary to close the solution, and reopen it. This seems especially the case when comparing a baseline checkout with a working branch; i.e. two IDE instances are open, running the unit tests virtually in tandem, or interleaved, comparing notes. This is cumbersome and annoying to say the least because it means breaking the train of thought and potentially losing my place over a "simple" issue.

**Comment by bradwilson** [comment]
What is the symptom that is causing you to need to reload the solution?

**Comment by mwpowellhtx** [comment]
I try to run, usually debug, but not always, unit tests, and the IDE seems to go about half way. Does appear to start, but the visual appearance of the typical Solution Explorer and other areas changes.

Likely this is due to how Visual Studio is caching its environment, I suspect. There doesn't appear to be a great separation of "multiple instances" in the cache, for itself, or for add-ins.

However, the likely scenario is multiple instances open, I was switching between a baseline and at least one working copy.

**Comment by mwpowellhtx** [comment]
I should also mention, this is running in VS2015 RC, within a NET4 targeted unit test assembly. The source is actually multi-targeted using NET framework bits: i.e. to Xamarin, Windows Phone, etc, as well as "desktop", NET4.

**Comment by bradwilson** [comment]
I admit to not understanding exactly what the problem is. Can you provide a repro?

**Comment by mwpowellhtx** [comment]
I don't know whether there's an orphaned worker thread, task, or whatever, but it's like the runner just sits there and never attaches to the debugger. Actually, perhaps that could be the issue; not attaching to the debugger. I was testing some [mods](http://github.com/AutoMapper/AutoMapper/pull/745) to AutoMapper extensively which prompted the concern. As far as repro, that's the best I can tell you. I ran a few tests, did some work, then revisited the same test(s), and would experience non-attaching test run.

**Comment by bradwilson** [comment]
Please re-open with a repro.

**Comment by mwpowellhtx** [comment]
@bradwilson It's been over two years since I last worked with this issue. Probably still exists, but that ship has since sailed, my fried.
