### ISSUE TITLE
Release new betas more frequently

### ISSUE THREAD

**Issue by MartinJohns** [xunit/xunit#442]
It would be great if new betas could be released at least a bit more frequently. The last beta is from 3th May, which is already almost two months ago.

The folks over at fscheck/FsCheck#86 (including me) are waiting for a new beta so a beta of FsCheck for xunit 2 can be released.

**Comment by bradwilson** [comment]
The current beta cycle is intended to be aligned with the DNX (ASP.NET v5) beta cycle.

https://twitter.com/xunit/status/606840251018039296
https://twitter.com/xunit/status/606841157566332929

Damian Edwards says they are aiming to ship their Beta 5 this week:

https://twitter.com/DamianEdwards/status/613147030928502784

Once they ship their Beta 5 bits, I will push rebuild and push our Beta 3 bits.

**Comment by bradwilson** [comment]
@MartinJohns FYI, Beta 3 is out now.
