### ISSUE TITLE
ITestCaseOrderer.OrderTestCases method not called when ITestOutputHelper injected

### ISSUE THREAD

**Issue by joemast** [xunit/xunit#443]
I have implementation for ITestCaseOrderer, it works fine. 

But when I add ITestOutputHelper injection like this

    class MyTestOrderer : ITestCaseOrderer
    {
        private ITestOutputHelper Output;

        public MyTestOrderer(ITestOutputHelper output)
        {
              Output = output;
        }

        public IEnumerable<TTestCase> OrderTestCases<TTestCase>(IEnumerable<TTestCase> testCases) where TTestCase : ITestCase
        {
        ............

then method OrderTestCases is not called (checked with debugger also), so no any modification for tests order was made.

Expected result
I was expected ITestOutputHelper injection has no affect to ITestCaseOrderer implementation

**Comment by joemast** [comment]
Found in version 2.1.0-beta2-build2981

**Comment by bradwilson** [comment]
You cannot inject `ITestOutputHelper` into any of the extensibility class. That's for unit tests.

If you want to write diagnostic messages, instead your constructor should take an instance of [`IMessageSink`](https://github.com/xunit/xunit/blob/b63ad8521933bbed12c28bdea1068ace443e4dcc/src/abstractions/xunit.abstractions/Messages/BaseInterfaces/IMessageSink.cs) to which you can post instances of [`DiagnosticMessage`](https://github.com/xunit/xunit/blob/b63ad8521933bbed12c28bdea1068ace443e4dcc/src/messages/DiagnosticMessage.cs).
