### ISSUE TITLE
VS 2015 Bugs - Traits and Project Grouping in Test Explorer

### ISSUE THREAD

**Issue by kspearrin** [xunit/xunit#444]
I am not sure if these are VS bugs or xunit bugs, but I figured I would post them here.

1
=====

Following the [Getting Started with dnx](http://xunit.github.io/docs/getting-started-dnx.html) tutorial in VS 2015 I have everything up and running fine, however, VS fails to group my tests by the Category trait:

    [Trait( "Category", "Blah" )]

See:  http://puu.sh/iDDy5/c7cf59544a.png

2
=====

The project grouping shows all my tests under "External" instead of my individual projects. See: http://puu.sh/iDDBL/56c90114db.png

3
=======

I have noticed that right clicking on a test or test class from inside the code editor window and clicking "Run Tests" or "Debug Tests" does not appear to properly run the tests. For example, the breakpoints will never end up getting hit and test results are not correct. I have to run the tests from the test explorer window to get them to work correctly.

**Comment by bradwilson** [comment]
Please report the issue in https://github.com/xunit/dnx.xunit, as that's the runner that's responsible for this.

**Comment by kspearrin** [comment]
I'll report it there as well, but it seems the I get the same problems when using the `"xunit.runner.aspnet": "2.0.0-aspnet-beta4"` runner as well, using a [setup similar to the ASP.NET team](https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNet.Mvc.Test/project.json).

**Comment by bradwilson** [comment]
xunit.runner.aspnet is deprecated and should not be used. xunit.runner.dnx is the only officially supported runner for DNX projects.
