### ISSUE TITLE
Nullable return value in generic interface implementation

### ISSUE THREAD

**Issue by Pondidum** [xunit/xunit#445]
I have come across an interesting problem with nullable types in interfaces while debugging tests under the resharper runner in visual studio.  #296 might be related - not really sure.

## Reproduction

This test will **fail** if:
* You *debug* in the resharper runner, set a breakpoint on `var test = store.GetLatestSequenceFor(Guid.NewGuid());`

This test will **pass** if:
* You run it in the console runner
* You run it in the resharper runner
* You *debug* it in the resharper runner, but don't set a breakpoint
* You *debug* it in the resharper runner, and step into the implementation or `GetLatestSequenceFor`
* You change the `DoTest` arguement to be `TestEventStore`, and do the fail step
* You remove the generic type parameter (change just to Guid etc.)
* Create a console application, with the same code, but the `Main` method instead of the `Fact` method

```c#
public interface IEventStore
{
	int? GetLatestSequenceFor<TKey>(TKey aggegateID);
}

public class TestEventStore : IEventStore
{
	public int? Value { get; set; }

	public int? GetLatestSequenceFor<TKey>(TKey aggegateID)
	{
		return Value;
	}
}

public class Tests
{
	[Fact]
	public void When_faking_a_value()
	{
		DoTest(new TestEventStore());
	}

	public void DoTest(IEventStore store)
	{
		var test = store.GetLatestSequenceFor(Guid.NewGuid());

		Assert.Equal(null, test);
	}
}
```

## Versions

Packages:
```xml
<package id="xunit" version="2.0.0" targetFramework="net45" />
<package id="xunit.abstractions" version="2.0.0" targetFramework="net45" />
<package id="xunit.assert" version="2.0.0" targetFramework="net45" />
<package id="xunit.core" version="2.0.0" targetFramework="net45" />
<package id="xunit.extensibility.core" version="2.0.0" targetFramework="net45" />
```

Project:
.Net Framework 4.5, Class library, AnyCpu, Debug mode.

**Comment by bradwilson** [comment]
Does this repro in any other runner than Resharper? If not, then the right place to report this bug would be https://github.com/xunit/resharper-xunit.

**Comment by Pondidum** [comment]
Apologies, I didn't realise there was another runner which supported debugging tests.

Debugging under the visualstudio runner doesn't have the problem, so will close this and re-open on the resharper repo.

Thanks
