### ISSUE TITLE
MemberData of type IXunitSerializable fails silently if it doesn't actually serialize anything

### ISSUE THREAD

**Issue by sbanni** [xunit/xunit#451]
MemberData with a type that derives from IXunitSerializable that doesn't have anything to serialize will cause the runner to fail silently with a 0 tests run.  No helpful messages that I could determine.  

```csharp
	public class Class1
	{
		[Theory]
		[MemberData("MyTestObjects")]
		public void MyTheoryTest(object myObj)
		{
		}

		public static IEnumerable<object[]> MyTestObjects
		{
			get
			{
				return new[]
				{
						new object[] { new MyTestClass() },
				};
            }
		}

		public class MyTestClass : IXunitSerializable
		{
			public void Deserialize(IXunitSerializationInfo info)
			{
			}

			public void Serialize(IXunitSerializationInfo info)
			{
			}
		}
	}
```

**Comment by bradwilson** [comment]
Which test runner? Because I was able to run this without incident with both the TestDriven.NET and the console runner.

**Comment by sbanni** [comment]
Inside visual studio.
________________________________

**Comment by bradwilson** [comment]
Thanks, I'm able to repro now. :)
