### ISSUE TITLE
Is it possible to have a test method with multiple InlineData running in parallel?

### ISSUE THREAD

**Issue by lchong0412** [xunit/xunit#452]
I would like to see if I can use xunit to provide basic load test capability, if a test method with multiple InlineData can run simultaneously. Or if it can't, is it possible to provide input data to class or collection so that we can carry out some load test with different input data running in parallel? Or even just write a custom attribute to let a test method to run in parallel in N threads.

**Comment by bradwilson** [comment]
Unfortunately, not as-is. The smallest level of parallelism that we support today is the test class.

It would be possible to support this with a custom implementation of [`ITestFramework`](https://github.com/xunit/xunit/blob/master/src/abstractions/xunit.abstractions/Frameworks/ITestFramework.cs) but this would be a significant undertaking. There is an [Observation sample](https://github.com/xunit/samples.xunit/tree/master/ObservationExample) that shows the core of what's needed to write and use a custom test framework, if you want someplace to start looking.
