### ISSUE TITLE
Add serialization support for assertion exceptions for assert-by-source

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#454]
The assertion exceptions today do not have serialization support because they reside in a PCL, which does not support serialization. That means running test code in app domains (like in the [PartialTrustExample](https://github.com/xunit/samples.xunit/tree/master/PartialTrustExample)) yields not useful messages when assertions fail.

There is an opportunity to support serialization for these exceptions if the user brings in the assertion library via source, and they are compiling on a platform that supports serialization.

**Comment by shinup** [comment]
Hi Brad any plans to address this issue?

**Comment by bradwilson** [comment]
When I looked at doing this, the issue was that there isn't a single `#define` that I can rely upon to tell the difference between when the source files are being brought into a context without serialization support, which means the only solution right now would be pre-processing the files and including duplicate copies (with and without serialization).

This is doable, but wasn't something I ended up wanting to do for 2.1. If we do this, it'll go into 2.2, but I'm not 100% sure yet that we'll get a solution that I'm happy with.

**Comment by shinup** [comment]
Thank for the quick response. We are using Mvc integration test framework in our project( http://blog.stevensanderson.com/2009/06/11/integration-testing-your-aspnet-mvc-application/) with xunit. I hope you will come with a good solution for this.

**Comment by mkaring** [comment]
@bradwilson Since you marked this issue as "Won't Fix"… is there any work-around for the issue? Any way to get the [PartialTrustExample](https://github.com/xunit/samples.xunit/tree/master/PartialTrustExample) working? I have a similar usage case where I need to pass the exceptions across different AppDomains and even different Applications. And these exceptions that can't be serialized are a real issue there.

**Comment by bradwilson** [comment]
The issue is that we can't fix this in xUnit.net itself, because the assertions are part of `xunit.assert.dll` which is compiled against `netstandard1.1` only, which does not support serialization (regardless of the target platform it's running on). Serialization isn't something you can add after the fact with reflection, either.

We could update the source files to allow someone to bring them in (via Git submodule, for example) and then enable serialization support, but I expect that's not the solution you were hoping for.

**Comment by mkaring** [comment]
Wouldn't it be a option to compile the assembly against multiple frameworks? Is there are particular reason why it is only compiled against the single version?
