### ISSUE TITLE
ObjectDisposedExceptions running msbuild from console

### ISSUE THREAD

**Issue by TimLovellSmith** [xunit/xunit#455]
This issue is with running xunit tests from msbuild. (With the XUnit nuget package ver 2.0.0)

The symptom: after running tests, Msbuild will crash with an ObjectDisposedException. The stack shown by debugger for the crashing unhandled exception is

```
>	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.ThrowAsyncIfNecessary.AnonymousMethod__1(object s)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()	Unknown
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
 	[Native to Managed Transition]	
 	mscorlib.ni.dll!00007ffd9c0b2220()	Unknown
```

That stack may be bogus. But anyway, when you break in debugger as the unhandled exception is thrown, you will see appdomain shutdown is occurring, this is the stack of another thread:

```
>	mscorlib.dll!System.AppDomain.Unload(System.AppDomain domain)	Unknown
 	xunit.runner.utility.desktop.dll!Xunit.RemoteAppDomainManager.Dispose()	Unknown
 	xunit.runner.utility.desktop.dll!Xunit.Xunit2Discoverer.Dispose()	Unknown
 	xunit.runner.utility.desktop.dll!Xunit.XunitFrontController.Dispose()	Unknown
```

I examined IL for System.Threading.Tasks.AwaitTaskContinuation.ThrowAsyncIfNecessary.AnonymousMethod__1(object s)
and I think it is actually rethrowing an earlier exception that was originally raised on another thread and rewriting the stack trace while doing so.

Possibly the original ObjectDisposedException was raised with this, different callstack:

```
 	mscorlib.dll!System.StubHelpers.StubHelpers.SafeHandleAddRef(System.Runtime.InteropServices.SafeHandle pHandle, ref bool success)	Unknown
 	mscorlib.dll!System.Threading.EventWaitHandle.Set()	Unknown
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunCallback(System.Threading.ContextCallback callback, object state, ref System.Threading.Tasks.Task currentTask)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
>	mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetResult(System.Threading.Tasks.VoidTaskResult result)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.DelayPromise.Complete()	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.TimerQueueTimer.CallCallback()	Unknown
 	mscorlib.dll!System.Threading.TimerQueueTimer.Fire()	Unknown
 	mscorlib.dll!System.Threading.TimerQueue.FireNextTimers()	Unknown
 	[Native to Managed Transition]	
 	mscorlib.ni.dll!00007ffd9c161dc5()	Unknown
```

When *that* exception was being raised, we can see in debugger the async callback portion of XUnit.Sdk.TestFramework.Dispose() is running (stack on other thread)

```
>	xunit.execution.desktop.dll!Xunit.Sdk.TestFramework.Dispose()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start<Xunit.Sdk.TestFramework.Dispose>(ref Xunit.Sdk.TestFramework.Dispose stateMachine)	Unknown
 	xunit.execution.desktop.dll!Xunit.Sdk.TestFramework.Dispose()	Unknown
 	[AppDomain (MSBuild.exe, #1) -> AppDomain (AzureProvisioningCore.tests, #3)]	
 	xunit.runner.utility.desktop.dll!Xunit.Xunit2Discoverer.Dispose()	Unknown
 	xunit.runner.utility.desktop.dll!Xunit.XunitFrontController.Dispose()	Unknown
 	xunit.runner.msbuild.dll!Xunit.Runner.MSBuild.xunit.ExecuteAssembly(string assemblyFileName, string configFileName, Xunit.TestAssemblyConfiguration configuration)	Unknown
 	xunit.runner.msbuild.dll!Xunit.Runner.MSBuild.xunit.Execute()	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()	Unknown
```

**Comment by TimLovellSmith** [comment]
I currently suspect this issue is basically caused by having an async void Dispose in TestFramework.Dispose, but this is just a theory which needs some further confirmatory details at this point.

'''
/// <inheritdoc/> 
42         public async void Dispose() 
43         { 
44             // We want to immediately return before we call DisconnectAll, since we are in the list 
45             // of things that will be disconnected. 
46             await Task.Delay(1); 
47 
 
48             ExtensibilityPointFactory.Dispose(); 
49             DisposalTracker.Dispose(); 
50 
 
51             LongLivedMarshalByRefObject.DisconnectAll(); 
52         } 
'''

**Comment by TimLovellSmith** [comment]
(Please ignore the this issue from a commit in TimLovellSmith/xunit 4 hours ago  

     Fixes xunit issue #455 (ObjectDisposedExceptions running msbuild from… …  ) notification.

I've done some testing of this, and if I comment out all the code of TestFramework.Dispose + use the latest master branch, the issue no longer reproing for me. Also if I modify the body of Dispose to:

```
        /// <inheritdoc/>
        public void Dispose()
        {
            // We want to immediately return before we call DisconnectAll, since we are in the list
            // of things that will be disconnected.

            ExtensibilityPointFactory.Dispose();
            DisposalTracker.Dispose();

            Task.Delay(1).ContinueWith(_ =>
            {
                LongLivedMarshalByRefObject.DisconnectAll();
            });
        }
```

The crash no longer repros for me in my testing so far. I'll submit a proper PR with that proposed fix.

**Comment by TimLovellSmith** [comment]
I've done some more testing of this, and I found that even though I just build master with the latest VS 2015 compiler bits that I can get, I can't repro the original issue (without any code change).

This makes me think it might be a compiler bug in the compiler that was used to build the official xunit 2.0.0 nupkg.

**Comment by TimLovellSmith** [comment]
I could not yet reproduce this with xunit.core 2.1.0-beta3-build3029 nuget package. Closing.

**Comment by bradwilson** [comment]
2.0 was build with VS 2013, and 2.1 is built with VS 2015. Sounds like you figured out the issue.
