### ISSUE TITLE
How can I get the name of the test in the test class constructor?

### ISSUE THREAD

**Issue by ansujay** [xunit/xunit#459]
Hello,

I want to know how I can get the name of the currently running test, ideally when the test object is being constructed. If that is not possible, a good enough fallback would be to get the test name before calling the test method itself (as long as I can get the test class instance). 

I have tried the following options so far:
1. The answer provided [here](http://stackoverflow.com/a/31212346/1896987) under 'Edit' (makes use of BeforeAfterTestAttribute). It works well, but I don't actually get the test class instance. 
2. The answer provided [here](http://stackoverflow.com/a/31212346/1896987) under 'Edit 2'. It works for me, except it is relying on internal detail and can break in future. 

Any help appreciated. Thanks!

**Comment by bradwilson** [comment]
We have no facility for this today.

Your hack "Edit 2" hack is the closest you're going to get for now.
