### ISSUE TITLE
"Profile Test" in Visual Studio 2013 does not work with [Theory] tests

### ISSUE THREAD

**Issue by eroller** [xunit/xunit#460]
I'm using Visual Studio 2013 Update 4 and the "Profile Test" option in Test Explorer only seems to work on [Fact] tests, not [Theory] tests. 

The [Theory] tests appear to run, but the profile results do not show up and the .vsp file is not generated in the solution's TestResults directory.

I'm using xUnit 2.0 with .Net 4.5

**Comment by bradwilson** [comment]
Try disabling theory pre-enumeration.

**Comment by eroller** [comment]
That seems to work. Thanks. 

Another interesting workaround I found is, if you add AutoFixture's [AutoData] attribute with pre-enumeration on (default) the test will still show up as a single test and the Profile Test feature will work as expected.

**Comment by bradwilson** [comment]
Pre-enumerated theory data needs to be serializable for Visual Studio to be able to make them individually runnable. We handle the built-in types, but custom types need to implement `IXunitSerializable` to support this.

I believe that in this case you're "fortunate" that at least one of the data elements being provided by `AutoFixture` isn't serializable, so we fall back to single-test-per-test method (the same behavior you get by turning off theory pre-enumeration).
