### ISSUE TITLE
When using parallelizeAssemblies, tests tend to fail with file path issues

### ISSUE THREAD

**Issue by TimLovellSmith** [xunit/xunit#463]
I believe the problem is Environment.CurrentDirectory isn't consistent versus when the tests are run without assembly parallelization. And so specifying loading a file via e.g.

```
File.ReadAllText("ServiceDefinition.csdef");
```

in project Foo.Tests

gives you error messages like fullpathto\Bar.Tests\ServiceDefintion.csdef does not exist.

**Comment by bradwilson** [comment]
There's nothing we can do about this. This is a limitation of the .NET Framework.
