### ISSUE TITLE
VS2013: Tests 'disappear' from runner/test explorer when source code is added to test project

### ISSUE THREAD

**Issue by Serenyrddraig** [xunit/xunit#469]
This is a horrible bug report (but I've spent 1/2 a day getting it to this point). I'm seeking direction on what else I can try/where to go next.

I have a VS2013 Ultimate, Update 4 Test Project with 12 successfully executing tests. xUnit 2.0 is installed from nuget (today) as is Resharper 9. If I add two *.cs files to the project from my working product code base and successfully clean/rebuild the test solution, the test explorer is suddenly completely empty. If I remove the two files from the solution, the tests reappear. 

I see nothing special about the code I'm adding. Both files are AutoMapper configuration profiles. I probably cannot send a repro due to company software distribution rules, but I could do some additional investigation.

**Comment by bradwilson** [comment]
If this is an issue with the Resharper runner, you should open it here: https://github.com/xunit/resharper-xunit

**Comment by Serenyrddraig** [comment]
I actually was using the VisualStudio runner. I disabled Resharper completely and the problem was still reproducible.

**Comment by bradwilson** [comment]
I've been unable to reproduce this issue as described. Can you provide a set of repro steps that would illustrate the problem?

**Comment by Serenyrddraig** [comment]
I’ll try to put together a repro today. If it proves to unmanageably large, I can try to debug it (perhaps with some direction). Sounds like a ‘runner’ problem to me, so I’d start there unless you have a better idea.

**Comment by Serenyrddraig** [comment]
Repro is attached. Tests will not run green without an appropriate database, but I don’t think it’s necessary.

In preparing this repro, I discovered that the problem may be/probably is associated with the “CopyLocal” (<Private/>) setting for project references.  If the CopyLocal setting is True on my dependencies, the problem does not occur. If the CopyLocal setting is FALSE, then the problem appears when I add source code.

The repro consists of a single Test project. As delivered, CopyLocal is set to false for all not .NET assemblies. A rebuild should show 12 Tests in the Test Explorer.


·         After the initial rebuild, right click the project and Add/Existing Item. In the test folder you should find two AutoMapper profiles (LineItemMapper.cs, OrderItemMapper.cs). Add both to the project and rebuild. All tests should disappear.

·         If you Exclude the new files from the project and rebuild, the Tests will reappear.

·         Re-add the existing items, the tests will disappear.

·         If you select all the non BCL references and change the CopyLocal setting to True, the tests will reappear.

The test included is a model of how we typically build tests for our product. The test includes an assembly resolver (LoadFrom context) so that we have minimal need for CopyLocal.

**Comment by bradwilson** [comment]
Please re-open with repro.

**Comment by malclear** [comment]
I had this problem when I had neglected to install the xunit.runner.visualstudio package from NuGet.
