### ISSUE TITLE
Consider allowing InlineDataAttribute to be applied to parameters

### ISSUE THREAD

**Issue by AArnott** [xunit/xunit#470]
If the `InlineDataAttribute` allowed application to parameters, then [Xunit.Combinatorial](https://github.com/AArnott/Xunit.Combinatorial)'s [CombinatorialValuesAttribute](https://github.com/AArnott/Xunit.Combinatorial/blob/master/src/Xunit.Combinatorial/CombinatorialValuesAttribute.cs) could go away in favor of reusing Xunit's own `InlineDataAttribute`.

**Comment by bradwilson** [comment]
This is a tough one.

I feel like, if we say that `[InlineData]` is allowed on parameters out of the box, it will imply that xUnit.net would do something with them, out of the box, which implies putting combinatorial support into the core framework. So it feels like an all-or-nothing kind of decision.

I'll think on it and discuss it with @jnewkirk.

**Comment by AArnott** [comment]
Yes, I understand the dilemma. And I support either way.

Are you interested in integrating my combinatorial + pairwise project into Xunit itself?

**Comment by bradwilson** [comment]
We discussed it today, and we've decided that we don't like one attribute meaning both things, so we're going to opt to leave everything as-is today.
