### ISSUE TITLE
VS2015 - Not working

### ISSUE THREAD

**Issue by Fosol** [xunit/xunit#473]
I've installed the full version of Visual Studio 2015 (it was released today).
I've created a Class Package Project.
I've downloaded the NuGet packages; xunit and xunit.runner.visualstudio.
I've add the command "test": "xunit.runner.visualstudio" to the project.json file.
The test cases do not show up in the Test Explorer.
DNX does not run and execute the tests; "Unable to load application or execute command"...

Does anyone have this working?

**Comment by bradwilson** [comment]
Please following these instructions: http://xunit.github.io/docs/getting-started-dnx.html

**Comment by Fosol** [comment]
Regrettably I've followed those instructions and simply get a similar result.

    "xunit": "2.1.0-beta3-build3029",
    "xunit.runner.dnx": "2.1.0-beta3-build99"

  "commands": {
    "test": "xunit.runner.dnx"
  }

Visual Studio doesn't show any tests in the Test Explorer.

If attempt to run in the command line "dnx . test" it throws an exception; "System.NullReferenceException".

**Comment by riegelj** [comment]
I don't have it working either; however, I can get it to run, but does not discover any tests. 

Try this and see if you can at least get it to run:

 make sure you're project.json has frameworks filled out.

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  }

**Comment by Fosol** [comment]
I was able to get a 'version' of xunit working.

Essentially it boils down to versioning hell.  You have to brew the right mix of stuff and not go outside of it.  The catch is the errors you receive don't always help (nothing new in the world).

It's all beta, so I guess we can't expect much else.

**Comment by riegelj** [comment]
Thanks. I also got it working after simplifying my project.json file.

{
  "version": "1.0.0-*",
  "description": "ClassLibrary1 Class Library",
  "authors": [ "jriegel" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
    "Microsoft.AspNet.Mvc": "6.0.0-beta6",
    "xunit": "2.1.0-beta3-*",
    "xunit.runner.dnx": "2.1.0-beta3-*"
  },
  "commands": {
    "test": "xunit.runner.dnx"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  }
}
