### ISSUE TITLE
VS2015 - Not Working

### ISSUE THREAD

**Issue by Fosol** [xunit/xunit#474]
Why would you close my last issue when your suggestion didn't resolve it?  Is anyone able to actually confirm this all works in VS2015?

"xunit": "2.1.0-beta3-build3029",
"xunit.runner.dnx": "2.1.0-beta3-build99"

"commands": {
 "test": "xunit.runner.dnx"
 }

Visual Studio doesn't show any tests in the Test Explorer.

If attempt to run in the command line "dnx . test" it throws an exception; "System.NullReferenceException".

**Comment by Fosol** [comment]
I'm not trying to be a pain, I'm actually very interested in using xunit.  I just can't get it to work at all.

I've followed the exact steps in the "getting started documentation" to no avail.
http://xunit.github.io/docs/getting-started-dnx.html

**Comment by bradwilson** [comment]
Several people are using it successfully right now. If you can provide a repro project, then it would help us determine what the issue is.

Also, don't forget that you must execute a "Build" in order for the Test Explorer to refresh the list of available tests.

**Comment by Fosol** [comment]
Brad,

Thanks for your response.  I've uploaded an example project to my GitHub.  I did it with the release version of Visual Studio 2015 and I've installed the most up-to-date NuGet packages.

Example - https://github.com/Fosol/Example.XunitTest

thanks,
Jeremy

**Comment by bradwilson** [comment]
There are two issues with your sample:

- You tried to use the target framework name `dotnet`, which is not supported in DNX Beta 5. You must explicitly pick `dnx451` and/or `dnxcore50`.
- You added `dnx.runner.visualstudio`, which is not part of the instructions

Once I resolved both issues, the tests discovered and ran correctly.

**Comment by Fosol** [comment]
Hello Brad,

Thanks for looking into this and pointing me in a direction.  Regrettably I have tried the exact same versions as the 'getting started' with no success.  I've updated the GitHub example I uploaded.

Example - https://github.com/Fosol/Example.XunitTest

Here's my config;
***
`{
  "version": "1.0.0-*",
  "description": "Example.XunitTest Class Library",
  "authors": [ "JFoster" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
    "System.Collections": "4.0.10-beta-23019",
    "System.Linq": "4.0.0-beta-23019",
    "System.Threading": "4.0.10-beta-23019",
    "System.Runtime": "4.0.10-beta-23019",
    "Microsoft.CSharp": "4.0.0-beta-23019",
    "xunit": "2.1.0-beta2-*",
    "xunit.runner.dnx": "2.1.0-beta2-*"
  },

  "commands": {
    "test": "xunit.runner.dnx"
  },

  "frameworks": {
    "dnx451": { }
  }
}`
***
I suspect it has something to do with the DNX version manager.  Here's my list (doesn't copy well).
***
Active Version     Runtime Architecture Location                       Alias
------ -------     ------- ------------ --------                       -----
  *    1.0.0-beta4 clr     x64          C:\Users\jfoster\.dnx\runtimes
       1.0.0-beta4 clr     x86          C:\Users\jfoster\.dnx\runtimes
       1.0.0-beta4 coreclr x64          C:\Users\jfoster\.dnx\runtimes
       1.0.0-beta4 coreclr x86          C:\Users\jfoster\.dnx\runtimes
       1.0.0-beta5 clr     x64          C:\Users\jfoster\.dnx\runtimes
  *    1.0.0-beta5 clr     x86          C:\Users\jfoster\.dnx\runtimes default
       1.0.0-beta5 coreclr x64          C:\Users\jfoster\.dnx\runtimes
       1.0.0-beta5 coreclr x86          C:\Users\jfoster\.dnx\runtimes
***
I am enjoying the new architecture and ideas being implemented in DNX applications, I just feel there is a huge user/developer experience issue when it comes to dealing with versioning issues.

**Comment by jderus** [comment]
Brad, I am also seeing that using the directions does not result in discovering or running tests. In Visual Studio I get "Unable to start Microsoft.Framework.TestHost" and 0 tests discovered. In posh I get "the term dnx is not a recognized command ..."

That said, in another project I have gotten xUnit to work with VS2015 RTM in the IDE, but I did not use the documented instructions. I have not yet gotten it working through command line in any project. 

Are you sure the documentation isn't missing some steps?

**Comment by Fosol** [comment]
jderus I was getting a similar error for dnx "no a recognized command".  I was able to resolve that by opening the Visual Studio Command Prompt.  Then I ran the DNVM upgrade command.  It installs the latest DNX runtime and makes it active.  It also updates the path (for that command prompt window) to include the appropriate DNX runtime.
***
>DNVM upgrade
***

**Comment by bradwilson** [comment]
The documentation states:

> Note: The examples were done with xUnit.net v2.1 Beta 2, DNX 1.0 Beta 4, ASP.NET v5 Beta 4, and Visual Studio 2015 RC. The version numbers and paths may differ for you, depending on which version you're using.

You've mixed DNX Beta *5* with xUnit.net 2.1 Beta *2*, when those versions are incompatible.

Please use either:

- DNX Beta 4 + xUnit.net 2.1 Beta 2
- DNX Beta 5 + xUnit.net 2.1 Beta 3

**Comment by Fosol** [comment]
Thanks for your response.

**Comment by renshuo123** [comment]
·11111
