### ISSUE TITLE
Xunit in visual studio 2015 depending on packages.config

### ISSUE THREAD

**Issue by Alyoshak** [xunit/xunit#477]
I am using VS2015 enterprise with xunit 2.0.0 and xunit VS runner 2.0.1 in Windows 7.

When the packages.config of the project doesn't have the xunit runner reference.
 `<package id="xunit.runner.visualstudio" version="2.0.1" targetFramework="net45" />`

Even if it still has the props references and I am sure they exist.
 `<Import Project="..\..\..\xunit.runner.visualstudio.2.0.1\build\net20\xunit.runner.visualstudio.props" Condition="Exists('..\..\..\xunit.runner.visualstudio.2.0.1\build\net20\xunit.runner.visualstudio.props')" />
  <Import Project="..\..\..\xunit.core.2.0.0\build\portable-net45+win+wpa81+wp80+monotouch+monoandroid+Xamarin.iOS\xunit.core.props" Condition="Exists('..\..\..\xunit.core.2.0.0\build\portable-net45+win+wpa81+wp80+monotouch+monoandroid+Xamarin.iOS\xunit.core.props')" />`

The project will find no tests.

Modifying  packages.config in VS2013 Premium doesn't cause the same issue.

To test you will have to restart your VS after modifying the packages.config

Thanks.

**Comment by bradwilson** [comment]
This is how Visual Studio finds test runners via NuGet. A `packages.config` reference is required. There is nothing we can do to influence this behavior. If you have issues with it, they should be reported to the Visual Studio team.

**Comment by Alyoshak** [comment]
More than anything it is unexpected since it worked in VS2013 and I had to spent some of my time to figure it out. I would think the project reference would be enough.

I submitted a ticket as you suggested
https://connect.microsoft.com/VisualStudio/feedback/details/1582285

**Comment by bradwilson** [comment]
Given the number of bugs I've seen in the VS2015 test runner, my guess is that they re-wrote large chunks of it, and this is probably one of the results.

I'm going to guess that they're going to close your issue as "we don't care", since they expect NuGet package references to be the officially supported method. But good luck. :)
