### ISSUE TITLE
Tests runner hangs after test returns

### ISSUE THREAD

**Issue by jsportaro** [xunit/xunit#480]
The following will reproduce the issue

```c#
[TestClass]
public class UnitTest1
{
    [Fact]
    [TestMethod]
    public void TestMethod1()
    {
        SpeechRecognitionEngine engine = new SpeechRecognitionEngine(new CultureInfo("en-US"));

        engine.LoadGrammar(new DictationGrammar());

        engine.Dispose();
    }
}
```
I traced through the method and it returns, but the runner never finishes.  It just looks like it's executing.

Here's the output with xunit.diagnosticMessages set to true

```
------ Discover test started ------
[xUnit.net 00:00:00.1628233] Discovering: Example (method display = ClassAndMethod)
[xUnit.net 00:00:00.2897759] Example: Discovered test case 'Example.UnitTest1.TestMethod1' (ID = '8657f8e4651bfb71819c750954ccc96590e2c7d4', VS FQN = 'Example.UnitTest1.TestMethod1')
[xUnit.net 00:00:00.2907401] Discovered: Example (1 tests)
========== Discover test finished: 2 found (0:00:00.4075092) ==========
------ Run test started ------
[xUnit.net 00:00:00.0085505] Starting: Example (parallel test collections = on, max threads = 8)
[xUnit.net 00:00:00.2471072] Example: Performing RecordStart for test case Example.UnitTest1.TestMethod1
```

I've tried this in VS 2013, VS 2015, and the console runner.  

Here's the package info

```xml
  <package id="xunit" version="2.0.0" targetFramework="net45" />
  <package id="xunit.abstractions" version="2.0.0" targetFramework="net45" />
  <package id="xunit.assert" version="2.0.0" targetFramework="net45" />
  <package id="xunit.core" version="2.0.0" targetFramework="net45" />
  <package id="xunit.extensibility.core" version="2.0.0" targetFramework="net45" />
  <package id="xunit.runner.visualstudio" version="2.0.1" targetFramework="net45" />
```

**Comment by onovotny** [comment]
It looks like you have both MSTest attributes and xunit attributes defined. What happens if you remove `[TestClass]` and `[TestMethod]`?

**Comment by jsportaro** [comment]
Even without the MSTest stuff, it still hangs.  That brings up something I forgot to include.  If I do use the MSTest stuff, the test returns without hanging.  Initially, I thought I wasn't Disposing all the things correctly.  However, after it ran fine with MSTest, I thought it might be something XUnit related.

**Comment by onovotny** [comment]
Is it just that single test with the engine that causes the hang? If you have other "simple"/"dummy" tests, do those work?

Does the SpeechRecognitionEngine have any thread affinity or any special threading?

Can you run the test with the command line xunit; does it hang there?

**Comment by jsportaro** [comment]
Anything that uses the SpeechRecognitionEngine causes the test to hang.  Meaning, if i just instantiate a SpeechRecognitionEngine, the test will not hang.  But, if I call any methods (like LoadGrammar(...)), it will hang.   Not sure about affinity or threading.  MS documentation says one of its dependent classes does use threading to do work.  But, it doesn't say anything about how or why.

Tried running the tests with the command line xunit, and it hangs there too.

**Comment by onovotny** [comment]
Do you have a simple repro for us to look at?

**Comment by onovotny** [comment]
One other thing to try - the https://github.com/xunit/samples.xunit/tree/master/STAExamples WpfFact attribute as it starts up a dispatcher

**Comment by bradwilson** [comment]
`[WpfFact]` does not seem to have any impact.

The issue appears to be with `LoadGrammar`. If that line is commented out, the test successfully ends. Unfortunately, it appears the issue is related to code that we can't look at (since `SpeechRecognitionEngine` is a wrapper around Win32 COM classes), so I don't know how much we'll be able to do here. Debugging has not really yielded much helpful information yet.

**Comment by jsportaro** [comment]
Thanks for the help.  Not sure what this thing is doing to lock up.  But, MSTest works so at least I can use that for the time being.
