### ISSUE TITLE
Test discovery throws exception: System.MissingMethodException: Constructor on type 'Xunit.Sdk.TestFrameworkProxy' not found

### ISSUE THREAD

**Issue by AArnott** [xunit/xunit#481]
This started very recently on at least one of my machines. It seems relevant to the machine more than the repo because it's started happening across several repos at roughly the same time. 
Note that despite discovery throwing the below exception, the tests are all (evidently) discovered and run successfully.

> ------ Discover test started ------
> [xUnit.net 00:00:00.1639946] Exception discovering tests from Microsoft.VisualStudio.Sdk.TestFramework.dll: System.MissingMethodException: Constructor on type 'Xunit.Sdk.TestFrameworkProxy' not found.
>    at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
>    at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
>    at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
>    at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
>    at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
>    at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
>    at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
>    at Xunit.RemoteAppDomainManager.CreateObject[TObject](String assemblyName, String typeName, Object[] args)
>    at Xunit.Xunit2Discoverer..ctor(ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, Boolean shadowCopy, String shadowCopyFolder)
>    at Xunit.XunitFrontController.CreateInnerController()
>    at Xunit.XunitFrontController.get_InnerController()
>    at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.DiscoverTests[TVisitor](IEnumerable`1 sources, IMessageLogger logger, Func`3 visitorFactory, Action`3 visitComplete, Stopwatch stopwatch)
> ========== Discover test finished: 0 found (0:00:00.4736807) ==========

Here is the relevant portion of my packages.config file:

```
<package id="xunit" version="2.0.0" targetFramework="net46" />
<package id="xunit.abstractions" version="2.0.0" targetFramework="net46" />
<package id="xunit.assert" version="2.0.0" targetFramework="net46" />
<package id="xunit.core" version="2.0.0" targetFramework="net46" />
<package id="xunit.extensibility.core" version="2.0.0" targetFramework="net46" />
<package id="xunit.runner.visualstudio" version="2.0.1" targetFramework="net46" />
```

**Comment by AArnott** [comment]
Ah, interestingly though it *does* block code coverage test runs.

**Comment by bradwilson** [comment]
Can you provide a repro project?

**Comment by AArnott** [comment]
Yes: https://github.com/aarnott/xunit481repro

**Comment by bradwilson** [comment]
I'm not able to repro your symptoms (I tried the VS runner in VS2015 Pro; I also installed the 2.0 console runner, and they both ran the project without issue). This makes it feel environmental.

Can you try to build a clean VM with VS 2015 and see if it repros in that VM?

**Comment by AArnott** [comment]
Yes. I'll try that and report back here.

**Comment by AArnott** [comment]
@bradwilson while the VM is being created, what are your theories as to what's causing this? Is there an old xunit DLL getting loaded from somewhere unexpected? I've seen several issues opened and closed with "refreshed computer fixed it" resolutions. But if it's so prevalent, I wonder how much investigation it's worth putting into finding the root cause and a possible fix that doesn't require recreating a machine.

**Comment by bradwilson** [comment]
I really don't have much of a working theory. The last time that signature changed was February 2015, and that shipped in 2.0 RC 2.

If you had an older VSIX-based test runner, you'd be seeing all kinds of unexpected behavior, and not just in this one circumstance. That's the only thing I can think of that might cause this.

**Comment by AArnott** [comment]
Hmm... well the VM is *almost* ready. But I just observed that my original machine no longer repros the problem. The only thing that changed was that I had closed all open instances of VS and restarted it. 
If it repros again, I'll attach a debugger to the discovery process and look at where each xunit module is loaded from and give you some more data.
In the interim, feel free to close if you want.

**Comment by cephius473** [comment]
Also happened to me using VS2012.
Added existing project with xunit 2.0 to a solution with projects using xunit 1.9.2.
When I tried rebuilding the solution, it triggered the error above.

Restarting the VS solved the problem and I was able to see the tests of the newly added project in Test Explorer.
