### ISSUE TITLE
Running dnx tests is a lot slower in VS than with console

### ISSUE THREAD

**Issue by ilmax** [xunit/xunit#482]
Hi, I've just updated a project to use the new dnx stuff, but running tests in VS is a lot slower than using the old csproj. Interestingly enough, running tests via `dnx . test` performs as expected. 
The slowdown is quite dramatic, since it goes from ~2.5 s when using `dnx . test` to > 1m using vs runner with run all.

if you are interested I can provide you a repro.

Best regards, Max

**Comment by bradwilson** [comment]
Our code is (literally) identical in both cases, so this is just the performance penalty you are forced by pay by using the Visual Studio runner. Sorry about that, but nothing we can do about it.

**Comment by ilmax** [comment]
Thanks for your quick response.

 might be wrong, but looks like test execution is slowing down time by time e.g. first bunch of tests run pretty quickly, but shortly after the runner start to slow down. This can be verified even with parallelization.

Is there any other place it might be worth to report such behavior?

P.S. When using VS running with csproj everything works well.

**Comment by bradwilson** [comment]
I don't know who owns the DNX => VS test adapter bridge. I think it was originally written by the ASP.NET team. Maybe @davidfowl or @damianedwards could shed some light on the best place to register performance complaints.

**Comment by DamianEdwards** [comment]
Log it at https://github.com/aspnet/Tooling
