### ISSUE TITLE
Code coverage in Visual Studio

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#483]
_From @Flavien on July 23, 2015 11:36_

Is is possible to have code coverage displayed in Visual Studio when using the Visual Studio Test Runner?

```
"dependencies": {
    "xunit": "2.1.0-*",
    "xunit.runner.dnx": "2.1.0-*"
}
```

When I run "Analyze code coverage for selected tests", I only see the 4 XUnit assemblies in the "Code Coverage Result" window.

_Copied from original issue: xunit/dnx.xunit#54_

**Comment by bradwilson** [comment]
We don't control the availability of code coverage in this scenario. The issue must be taken up with whichever team is responsible for the `project.json` support for pluggable test frameworks (might be the ASP.NET team, might be the Visual Studio team; @davidfowl or @DamianEdwards would probably know).

**Comment by bradwilson** [comment]
_From @scabana on July 27, 2015 12:57_

Tried to get this working last week as well as vstest.console.exe, seems we're out of luck at this point in time :cry:

**Comment by renevanosnabrugge** [comment]
This is solved in Visual Studio 2015.1. However when running on Windows 7 there is known bug which crashes vstest.console or hangs the unit test execution. When Running without code coverage enabled or from within Visual Studio or on another platform it works fine .

Someone from the VS product team told me so. It will probably be fixed in VS2015.2

**Comment by bruno-garcia** [comment]
@renevanosnabrugge I found no reference to Code Coverage on the Update 2 RC announcement:
https://www.visualstudio.com/en-us/news/vs2015-update2-vs.aspx

Do you have more details?

**Comment by csmith93** [comment]
@renevanosnabrugge, VS2015.3 is out now, any update on this?

**Comment by bradwilson** [comment]
We still have zero control over this. The team that owns the .NET Core support for RockSteady is going to have to deal with this issue.

**Comment by Saibamen** [comment]
Still 0%
