### ISSUE TITLE
VS 2015 Bugs - Traits and Project Grouping in Test Explorer

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#485]
_From @kspearrin on June 26, 2015 21:51_

I am not sure if these are VS bugs or xunit bugs, but I figured I would post them here.

1
=====

Following the [Getting Started with dnx](http://xunit.github.io/docs/getting-started-dnx.html) tutorial in VS 2015 I have everything up and running fine, however, VS fails to group my tests by the Category trait:

    [Trait( "Category", "Blah" )]

See:  http://puu.sh/iDDy5/c7cf59544a.png

2
=====

The project grouping shows all my tests under "External" instead of my individual projects. See: http://puu.sh/iDDBL/56c90114db.png

3
=======

I have noticed that right clicking on a test or test class from inside the code editor window and clicking "Run Tests" or "Debug Tests" does not appear to properly run the tests. For example, the breakpoints will never end up getting hit and test results are not correct. I have to run the tests from the test explorer window to get them to work correctly.

_Copied from original issue: xunit/dnx.xunit#43_

**Comment by bradwilson** [comment]
Issues 2 and 3 should be solved in 2.1 Beta 3.

Issue 1 is a dup of #37.

**Comment by bradwilson** [comment]
_From @kspearrin on July 2, 2015 20:54_

Switched to using 2.1 beta 3 (build99) and am still seeing the same problems.

**Comment by bradwilson** [comment]
Please provide a repro that shows your issues.

Also, whatever image host you're using is unreachable. Next time, please upload your images directly to GitHub.

**Comment by bradwilson** [comment]
_From @ups216 on July 7, 2015 9:26_

Hi, any progress on this? I'm having the same problem exactly like @kspearrin. Also, after upgrading to  vNext Beta 5, I got the "Object reference not set to an instance of an object" error when I try to run dnx . test in my test folder, it was working fine with Beta 4.

**Comment by bradwilson** [comment]
_From @davidfowl on July 7, 2015 9:43_

What version of the xunit runner are you using?

**Comment by bradwilson** [comment]
_From @ups216 on July 8, 2015 3:35_

@davidfowl Here is the full project.json, the runner is 2.1.0-beta3-build99

```json
{
    "version": "1.0.0-*",
    "description": "",
    "authors": [ "" ],
    "tags": [ "" ],
    "projectUrl": "",
    "licenseUrl": "",

    "dependencies": {
        "Microsoft.AspNet.Mvc": "6.0.0-beta5",
        "RestSharp": "105.1.0",
        "EIPCore.Managers": "1.0.0-*",
        "Microsoft.Framework.Configuration": "1.0.0-beta5",
        "Microsoft.Framework.Configuration.Json": "1.0.0-beta5",
        "Newtonsoft.Json": "7.0.1",
        "Microsoft.Framework.DependencyInjection": "1.0.0-beta5",
        "EntityFramework.InMemory": "7.0.0-beta5",
        "xunit": "2.1.0-beta3-build3029",
        "xunit.runner.dnx": "2.1.0-beta3-build99",
        "EIPCore.SvrSdk": "1.0.0-*",
        "Moq": "4.2.1502.911",
    },

    "commands": {
        "test": "xunit.runner.dnx"
    },

    "frameworks": {
        "dnx451": { }
    }
}
```

**Comment by mac2000** [comment]
Hi guys, we just have reproduce problem just by copying samples from [official tutorial](http://xunit.github.io/docs/getting-started-dnx.html) and adding `[Trait("Category", "Foo")]` on beta8 dnx.

**Comment by bradwilson** [comment]
This is an external issue, and should be reported at https://github.com/aspnet/testing

**Comment by imkheong** [comment]
By any chance, anyone happens to be looking into this?

The trait is still notshowing with my latest setup of Visual Studio 2015.

**Comment by bradwilson** [comment]
We are not supporting DNX, not project.json-based .NET Core. We are only supporting VS2017 (MSBuild v15) .NET Core.

If the issue is still present, please open a new bug. This one is... well worn. :-p
