### ISSUE TITLE
Add output transforms

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#486]
_From @nSwann09 on June 24, 2015 7:12_

Currently the xunit.runner.dnx only supports xUnit2 Xml output. 
For test integration into Visual Studio Online Build system, either JUnit, VSTest, Or NUnit formats are required.

Can at least one of those formats be supported?

_Copied from original issue: xunit/dnx.xunit#42_

**Comment by bradwilson** [comment]
At the moment, we're blocked from doing this by the lack of XSL-T support in DNX.

**Comment by bradwilson** [comment]
_From @eriklarko on July 14, 2015 7:38_

As a workaround we downloaded the `NUnitXml.xslt` from https://github.com/xunit/xunit/blob/master/src/xunit.console/NUnitXml.xslt and used `xsltproc` to apply the tranformation as a build step.

Example:
```
$ dnx . xunit.runner.dnx -xml xunit-test-results.xml
$ xsltproc NUnitXml.xslt xunit-test-results.xml > nunit-test-results.xml
```

**Comment by RehanSaeed** [comment]
+1

**Comment by bradwilson** [comment]
Newer issue: #1200
