### ISSUE TITLE
Running tests on multiple projects

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#488]
_From @cherrydev on April 28, 2015 23:2_

Right now, the only way that I can find to run tests on multiple projects at the same time is to make a new project that depends on all of the tests projects and then pass the names of the other projects as arguments.  Is there something that I'm missing?  If not, is this functionality that will be coming now that 'global' commands are a reality?

_Copied from original issue: xunit/dnx.xunit#25_

**Comment by bradwilson** [comment]
I don't believe there's going to be any way for us to do this, given the architecture of DNX. Maybe @davidfowl or @damianedwards can offer some thoughts.

**Comment by bradwilson** [comment]
_From @cherrydev on April 29, 2015 0:55_

DNX supports the concept of "project folders" being loaded as assemblies.  It basically uses the project.json as a surrogate.  Take a look at IMetadataProjectReference.  I wish I knew more about how the internals of it worked.

**Comment by yokomizor** [comment]
> Right now, the only way that I can find to run tests on multiple projects at the same time is to make a new project that depends on all of the tests projects and then pass the names of the other projects as arguments.

Is it documented somewhere? I am looking for some examples.
