### ISSUE TITLE
Update Comparisons page for vLatest of unit testing frameworks

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#503]
_From @bradwilson on June 30, 2015 3:26_

In particular, this is very out of date: http://xunit.github.io/docs/comparisons.html#assertions

_Copied from original issue: xunit/xunit.github.io#23_

**Comment by StewShack** [comment]
I created a pull request for the update, https://github.com/StewShack/xunit.github.io/pull/1

Please let me know if you need more information. Thank you for the great testing framework!

**Comment by bradwilson** [comment]
Closed with xunit/xunit.github.io#50
