### ISSUE TITLE
Using Assert.Throws in a .NET 4.5.1 breaks builds

### ISSUE THREAD

**Issue by behrangsa** [xunit/xunit#508]
In a .NET 4.5.1 project, if I use `Assert.Throws`, I am getting this error:

```
The type 'System.Threading.Tasks.Task' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Threading.Tasks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

I am using xUnit version `2.1.0.3029`. The xUnit.net Assertion Library version is `2.1.0-beta3-build3029`.

Are there any workarounds available for this?

**Comment by bradwilson** [comment]
The message tells you what to do, so what is your question?

**Comment by behrangsa** [comment]
Hi @bradwilson,

Looks like in .NET 4.5.1, `'System.Threading.Tasks.Task` is a part of the `mscorlib`. So it is possible using it without referencing any extra assemblies.

However the `xunit.assert` assembly is referencing it in its references:

![Xunit Assert references](http://i.imgur.com/tT8UUqb.png)

And as such it cannot be used in 4.5.1 because it shows the error I mentioned in the issue.

**Comment by bradwilson** [comment]
@behrangsa Please verify whether this is still failing with 2.1 RC 1 (shipping this weekend), as we've made a lot of changes in this area. If it's still broken, please re-open the issue.

**Comment by DaFluid** [comment]
I've tried it with the 2.1 rc1 build in Visual Studio Ultimate 2013 Update 5 and I still get the error. Best thing is, it worked before! Not sure what was changed to make this fail as we're at our deadline with the project and there have been many commits coming from various sides. Note that we're bulding with .NET version 4.5.2 .

**Comment by lrodrigueza** [comment]
I've updated to the 2.1 RC 1, and I am still getting the error. I've tried building with .NET 4.5 and 4.5.1.

**Comment by bradwilson** [comment]
@DaFluid Please provide a repro project.

**Comment by behrangsa** [comment]
Hi all,

I think I had actually made a mistake. Make sure you are using the correct .NET version, uninstall xunit, make sure it and all of its dependencies are removed from `package.config`, and reinstall xunit.

In short, make sure the `targetFramework` matches the NET version for your project:

```
<package id="..." version="..." targetFramework="net451" />
```

**Comment by DaFluid** [comment]
@bradwilson This is the best I can do with the time I have: https://github.com/DaFluid/xunit-bug-repro

**Comment by behrangsa** [comment]
@DaFluid could you please try the previous version of Xunit?

**Comment by bradwilson** [comment]
@dafluid That repro has a lot more code that I'd expect would be required to show the problem you're claiming. I did what should be the simplest repro myself with VS 2015 (this is the only version of VS I have). This is what I did:

- Create .NET 4.5.1 class library
- Add the following packages:

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="xunit" version="2.1.0-rc1-build3168" targetFramework="net451" />
  <package id="xunit.abstractions" version="2.0.0" targetFramework="net451" />
  <package id="xunit.assert" version="2.1.0-rc1-build3168" targetFramework="net451" />
  <package id="xunit.core" version="2.1.0-rc1-build3168" targetFramework="net451" />
  <package id="xunit.extensibility.core" version="2.1.0-rc1-build3168" targetFramework="net451" />
  <package id="xunit.extensibility.execution" version="2.1.0-rc1-build3168" targetFramework="net451" />
</packages>
```

- Write the following test:

```csharp
using System;
using Xunit;

namespace xunit_508
{
    public class Class1
    {
        [Fact]
        public void Repro()
        {
            Assert.Throws<DivideByZeroException>(() => ThrowingMethod());
        }

        void ThrowingMethod()
        {
            throw new DivideByZeroException();
        }
    }
}
```

This compiles and runs correctly.

If you can repro this with the exact same steps in VS 2013, then I'd suggest that either (a) your VS 2013 installation is somehow broken, or (2) VS 2013 has a bug that is causing the issue, which appears to be fixed by moving to VS 2015.

**Comment by alexdarkpool** [comment]
@behrangsa @bradwilson @DaFluid I may have a solution - I can't explain why it works but it solved this exact problem for me. Does your project have a reference to System.Runtime? If so, remove it. I noticed this because I had a different project in which Assert.Throws worked and this was the only difference in terms of references between the two projects.

**Comment by stijnherreman** [comment]
@alexdarkpool that fixes the issue for me. I've no idea why the test project has System.Runtime referenced because I'm not the original author, but it builds and runs fine without it.

**Comment by DaFluid** [comment]
@stijnherreman @alexdarkpool   not even I know how that got there. I'm assuming it was part of a nuget package that was installed and then removed (possibly installed by mistake), or just added to the test project but never used. The fix worked for me too, though, so thank you!

**Comment by benliebert** [comment]
Works for me too - cheers.  The only thing I can think I did was install JSON.Net from Nuget, perhaps it was added then.
