### ISSUE TITLE
What happend to ClassData?

### ISSUE THREAD

**Issue by vamichael** [xunit/xunit#510]
What happened to ClassData?  How could I recreate this?  Also, is there documentation and samples for all of the xunit features?  I've looked all over the place and so much stuff is deprecated it's hard to find out what is current and what is three years old.

    public class StringTests3
    {
        [Theory, ClassData(typeof(IndexOfData))]
        public void IndexOf(string input, char letter, int expected)
        {
            var actual = input.IndexOf(letter);
            Assert.Equal(expected, actual);
        }
    }
     
    public class IndexOfData : IEnumerable<object[]>
    {
        private readonly List<object[]> _data = new List<object[]>
        {
            new object[] { "hello world", 'w', 6 },
            new object[] { "goodnight moon", 'w', -1 }
        };
     
        public IEnumerator<object[]> GetEnumerator()
        { return _data.GetEnumerator(); }
     
        IEnumerator IEnumerable.GetEnumerator()
        { return GetEnumerator(); }
    }

**Comment by bradwilson** [comment]
Dup of #359 (will be shipping in 2.1 Beta 4)
