### ISSUE TITLE
Is there an xUnit for DNX beta 6?

### ISSUE THREAD

**Issue by tillig** [xunit/xunit#512]
In trying to build/test projects for the DNX beta 6 runtime, I've found that the xUnit `-beta3-*` builds seem to target DNX beta 5 and xUnit `-beta4-*` builds target DNX beta 7.

Unfortunately there were some breaking changes between DNX beta 5 and beta 6 such that I can't leave the xUnit at `-beta3-*` because it doesn't have compatible updates/dependencies and I can't upgrade to xUnit at `-beta4-*` because I'm not ready to target DNX beta 7.

Is there an xUnit (and xunit.runner.dnx package) that was built and released - even on the MyGet feed - targeting DNX beta 6?

**Comment by heathyates** [comment]
I was going to ask this myself. I could not have asked it better myself.

**Comment by bradwilson** [comment]
You can use:

```
xunit 2.1.0-beta4-build3075
xunit.runner.dnx 2.1.0-beta4-build124
```

from the CI NuGet feed (https://www.myget.org/F/xunit). We will have a final beta 4 release soon, as we're also working on UWP support (and this is a weekend thing for us).

**Comment by tillig** [comment]
No worries, Autofac is an after-hours/weekend thing for me, too. I'll give those builds a shot.

**Comment by tillig** [comment]
We have success! I found that I had to manually specify a few dependency versions to force xUnit to use the released betas (not on the aspvnext MyGet feed, but from NuGet) but it worked.

Here's the winning combo for DNX beta 6:

``` json
{
  "dependencies": {
        "Microsoft.Framework.Runtime.Abstractions": "1.0.0-beta6",
        "Microsoft.Framework.TestAdapter": "1.0.0-beta6",
        "Microsoft.Framework.TestHost": "1.0.0-beta6",
        "xunit": "2.1.0-beta4-build3075",
        "xunit.runner.dnx": "2.1.0-beta4-build124"
  }
}
```

I'm waiting on an AppVeyor build to ensure this isn't just a "works on my machine" situation. I'll post back when that's finished and, if it's successful, close the issue out.

**Comment by bradwilson** [comment]
Oops, I'll make sure I update the dependencies correctly.

**Comment by tillig** [comment]
Using the following NuGet.config:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  <packageSources>
    <add key="AspNetMaster" value="https://www.myget.org/F/aspnetmaster/api/v2" />
    <add key="xUnit.net" value="https://www.myget.org/F/xunit/api/v2/" />
    <add key="NuGet v2" value="https://www.nuget.org/api/v2" />
  </packageSources>
</configuration>
```

I can successfully build a test project with xUnit on DNX beta 6 with these dependencies:

``` json
{
    "dependencies": {
        "xunit": "2.1.0-beta4-build3075",
        "xunit.runner.dnx": "2.1.0-beta4-build125"
    }
}
```

Thanks for the help, @bradwilson!

**Comment by heathyates** [comment]
@bradwilson  @tillig Thanks a lot.
