### ISSUE TITLE
"Run all" hangs in VS2015

### ISSUE THREAD

**Issue by arthurward** [xunit/xunit#513]
When I click "Run all" in VS2015, the test explorer sits and spins the little green bar without doing anything. The output window only contains "------ Run test started ------". I can right-click on "Not Run Tests," "Run Selected Tests," and they all run with no problem. I found that if I select Test->Test Settings->Default Processor Architecture->X64 (instead of X86), the "Run All" command works.

Test discovery is working. I tried removing `%TEMP%\VisualStudioTestExplorerExtensions`, but that has no effect.

**Comment by onovotny** [comment]
This is a bug in the VS 2015 RTM Test Runner

/cc @unniravindranathan

**Comment by unniravindranathan** [comment]
Yes, we will fix this for the next update of the Win10 Tools for sure.

**Comment by DotNetSparky** [comment]
Possible workaround (I just tried it and it worked, but too soon to tell if that was a fluke or not)...

Test menu --> Test Settings --> Default Processor Architecture --> change from X86 to X64

(source:  http://stackoverflow.com/questions/30235912/visual-studio-2015-rc-test-run-hangs -- although that was about a different issue with the VS test engine, the fact that they said doing this makes it use the 'old' vstest engine  made me want to at least try it)

**Comment by arthurward** [comment]
I filed this issue with Microsoft Connect as well; I should have thought to link the two earlier. https://connect.microsoft.com/VisualStudio/feedback/details/1605406/run-all-in-test-explorer-hangs-on-x86-test-architecture

**Comment by michael-x** [comment]
Experiencing the same issue. Added a comment on Microsoft Connect.

**Comment by bradwilson** [comment]
Closing as external (and presumable already fixed).
