### ISSUE TITLE
xunit console runner test discovery fails when it can't find a constructor

### ISSUE THREAD

**Issue by AArnott** [xunit/xunit#514]
This is the exception that comes up:

$exception	{"Constructor on type 'Xunit.Sdk.TestFrameworkTypeDiscoverer' not found."}	System.MissingMethodException

>  	mscorlib.dll!System.RuntimeType.CreateInstanceImpl(System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, object[] args, System.Globalization.CultureInfo culture, object[] activationAttributes, ref System.Threading.StackCrawlMark stackMark)	Unknown
 	mscorlib.dll!System.Activator.CreateInstance(System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, object[] args, System.Globalization.CultureInfo culture, object[] activationAttributes)	Unknown
 	mscorlib.dll!System.Activator.CreateInstance(System.Type type, object[] args)	Unknown
>	xunit.execution.desktop.dll!Xunit.Sdk.ExtensibilityPointFactory.CreateInstance(Xunit.Abstractions.IMessageSink diagnosticMessageSink, System.Type type, object[] ctorArgs)	Unknown
 	xunit.execution.desktop.dll!DictionaryExtensions.GetOrAdd<System.Type, object>(System.Collections.Generic.IDictionary<System.Type, object> dictionary, System.Type key, System.Func<object> newValue)	Unknown
 	xunit.execution.desktop.dll!Xunit.Sdk.ExtensibilityPointFactory.Get<Xunit.Sdk.ITestFrameworkTypeDiscoverer>(Xunit.Abstractions.IMessageSink diagnosticMessageSink, System.Type type, object[] ctorArgs)	Unknown
 	xunit.execution.desktop.dll!Xunit.Sdk.ExtensibilityPointFactory.GetTestFrameworkTypeDiscoverer(Xunit.Abstractions.IMessageSink diagnosticMessageSink, Xunit.Abstractions.IAttributeInfo testFrameworkDiscovererAttribute)	Unknown
 	xunit.execution.desktop.dll!Xunit.Sdk.TestFrameworkProxy.GetTestFrameworkType(Xunit.Abstractions.IAssemblyInfo testAssembly, Xunit.Abstractions.IMessageSink diagnosticMessageSink)	Unknown
 	xunit.execution.desktop.dll!Xunit.Sdk.TestFrameworkProxy.TestFrameworkProxy(object testAssemblyObject, object sourceInformationProviderObject, object diagnosticMessageSinkObject)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	mscorlib.dll!System.RuntimeType.CreateInstanceImpl(System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, object[] args, System.Globalization.CultureInfo culture, object[] activationAttributes, ref System.Threading.StackCrawlMark stackMark)	Unknown
 	mscorlib.dll!System.Activator.CreateInstance(System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, object[] args, System.Globalization.CultureInfo culture, object[] activationAttributes)	Unknown
 	mscorlib.dll!System.Activator.CreateInstance(string assemblyString, string typeName, bool ignoreCase, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, object[] args, System.Globalization.CultureInfo culture, object[] activationAttributes, System.Security.Policy.Evidence securityInfo, ref System.Threading.StackCrawlMark stackMark)	Unknown
 	mscorlib.dll!System.Activator.CreateInstance(string assemblyName, string typeName, bool ignoreCase, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, object[] args, System.Globalization.CultureInfo culture, object[] activationAttributes, System.Security.Policy.Evidence securityInfo)	Unknown
 	mscorlib.dll!System.AppDomain.CreateInstance(string assemblyName, string typeName, bool ignoreCase, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, object[] args, System.Globalization.CultureInfo culture, object[] activationAttributes, System.Security.Policy.Evidence securityAttributes)	Unknown
 	mscorlib.dll!System.AppDomain.CreateInstanceAndUnwrap(string assemblyName, string typeName, bool ignoreCase, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, object[] args, System.Globalization.CultureInfo culture, object[] activationAttributes, System.Security.Policy.Evidence securityAttributes)	Unknown
 	[AppDomain (xunit.console.exe, #1) -> AppDomain (Microsoft.VisualStudio.Sdk.TestFramework.Tests, #3)]	
 	xunit.runner.utility.desktop.dll!Xunit.RemoteAppDomainManager.CreateObject<Xunit.Abstractions.ITestFramework>(string assemblyName, string typeName, object[] args)	Unknown
 	xunit.runner.utility.desktop.dll!Xunit.Xunit2Discoverer.Xunit2Discoverer(Xunit.Abstractions.ISourceInformationProvider sourceInformationProvider, Xunit.Abstractions.IAssemblyInfo assemblyInfo, string assemblyFileName, string xunitExecutionAssemblyPath, string configFileName, bool shadowCopy, string shadowCopyFolder, Xunit.Abstractions.IMessageSink diagnosticMessageSink)	Unknown
 	xunit.runner.utility.desktop.dll!Xunit.XunitFrontController.CreateInnerController()	Unknown
 	xunit.runner.utility.desktop.dll!Xunit.XunitFrontController.InnerController.get()	Unknown
 	xunit.runner.utility.desktop.dll!Xunit.XunitFrontController.Find(bool includeSourceInformation, Xunit.Abstractions.IMessageSink messageSink, Xunit.Abstractions.ITestFrameworkDiscoveryOptions discoveryOptions)	Unknown
 	xunit.console.exe!Xunit.ConsoleClient.Program.ExecuteAssembly(object consoleLock, string defaultDirectory, Xunit.XunitProjectAssembly assembly, bool quiet, bool serialize, bool needsXml, bool teamCity, bool appVeyor, bool? parallelizeTestCollections, int? maxThreadCount, Xunit.XunitFilters filters)	Unknown
 	xunit.console.exe!Xunit.ConsoleClient.Program.RunProject(string defaultDirectory, Xunit.XunitProject project, bool quiet, bool serialize, bool teamcity, bool appVeyor, bool? parallelizeAssemblies, bool? parallelizeTestCollections, int? maxThreadCount)	Unknown
 	xunit.console.exe!Xunit.ConsoleClient.Program.Main(string[] args)	Unknown

Loaded modules below. Notice that some xunit modules are loaded 2-3 times, but in different app domains (so it's probably ok).

	Microsoft.VisualStudio.Debugger.Runtime.dll	C:\WINDOWS\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll	Yes	N/A	Symbols not loaded.		23	14.00.23103.0	7/2/2015 8:44 PM	00000030A8550000-00000030A855A000	[11392] xunit.console.exe	[3] Microsoft.VisualStudio.Sdk.TestFramework.Tests	
	Microsoft.VisualStudio.Sdk.TestFramework.Tests.dll	C:\Users\andarno\AppData\Local\Temp\8f28dfbe-3008-4dd6-84e3-d1de2c269212\8f28dfbe-3008-4dd6-84e3-d1de2c269212\assembly\dl3\d10f25da\d8d497cb_3ccad001\Microsoft.VisualStudio.Sdk.TestFramework.Tests.dll	No	N/A	Symbols loaded.	C:\Users\andarno\AppData\Local\Temp\8f28dfbe-3008-4dd6-84e3-d1de2c269212\8f28dfbe-3008-4dd6-84e3-d1de2c269212\assembly\dl3\d10f25da\d8d497cb_3ccad001\Microsoft.VisualStudio.Sdk.TestFramework.Tests.pdb	18	14.00.15210.0	7/29/2015 1:26 PM	00000030A8500000-00000030A850A000	[11392] xunit.console.exe	[3] Microsoft.VisualStudio.Sdk.TestFramework.Tests	
	mscorlib.dll	C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll	Yes	N/A	Loading disabled by Include/Exclude setting.		1	4.6.79.0 built by: NETFXREL2	5/31/2015 7:38 PM	00007FFF44EA0000-00007FFF4633B000	[11392] xunit.console.exe	[1] xunit.console.exe	
	mscorlib.dll	C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll	Yes	N/A	Loading disabled by Include/Exclude setting.		11	4.6.79.0 built by: NETFXREL2	5/31/2015 7:38 PM	00007FFF44EA0000-00007FFF4633B000	[11392] xunit.console.exe	[2] xunit.runner.utility.desktop	
	mscorlib.dll	C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll	Yes	N/A	Loading disabled by Include/Exclude setting.		14	4.6.79.0 built by: NETFXREL2	5/31/2015 7:38 PM	00007FFF44EA0000-00007FFF4633B000	[11392] xunit.console.exe	[3] Microsoft.VisualStudio.Sdk.TestFramework.Tests	
	System.Configuration.dll	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll	Yes	N/A	Loading disabled by Include/Exclude setting.		8	4.6.79.0 built by: NETFXREL2	5/31/2015 7:41 PM	00007FFF51050000-00007FFF51170000	[11392] xunit.console.exe	[1] xunit.console.exe	
	System.Configuration.dll	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll	Yes	N/A	Loading disabled by Include/Exclude setting.		24	4.6.79.0 built by: NETFXREL2	5/31/2015 7:41 PM	00000030A8CC0000-00000030A8D22000	[11392] xunit.console.exe	[3] Microsoft.VisualStudio.Sdk.TestFramework.Tests	
	System.Core.dll	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll	Yes	N/A	Loading disabled by Include/Exclude setting.		5	4.6.79.0 built by: NETFXREL2	5/31/2015 7:41 PM	00007FFF438F0000-00007FFF44272000	[11392] xunit.console.exe	[1] xunit.console.exe	
	System.Core.dll	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll	Yes	N/A	Loading disabled by Include/Exclude setting.		21	4.6.79.0 built by: NETFXREL2	5/31/2015 7:41 PM	00000030A8DA0000-00000030A8EE2000	[11392] xunit.console.exe	[3] Microsoft.VisualStudio.Sdk.TestFramework.Tests	
	System.dll	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll	Yes	N/A	Loading disabled by Include/Exclude setting.		4	4.6.79.0 built by: NETFXREL2	5/31/2015 7:41 PM	00007FFF44280000-00007FFF44E94000	[11392] xunit.console.exe	[1] xunit.console.exe	
	System.dll	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll	Yes	N/A	Loading disabled by Include/Exclude setting.		17	4.6.79.0 built by: NETFXREL2	5/31/2015 7:41 PM	00000030A88F0000-00000030A8C42000	[11392] xunit.console.exe	[3] Microsoft.VisualStudio.Sdk.TestFramework.Tests	
	System.Reflection.dll	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Reflection\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Reflection.dll	Yes	N/A	Loading disabled by Include/Exclude setting.		13	4.06.79.0	5/31/2015 8:27 PM	00007FFF66AF0000-00007FFF66AF5000	[11392] xunit.console.exe	[1] xunit.console.exe	
	System.Runtime.dll	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll	Yes	N/A	Loading disabled by Include/Exclude setting.		10	4.06.79.0	5/31/2015 8:27 PM	00007FFF69940000-00007FFF69949000	[11392] xunit.console.exe	[1] xunit.console.exe	
	System.Runtime.dll	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll	Yes	N/A	Binary was not built with debug information.		22	4.06.79.0	5/31/2015 8:27 PM	00000030A8520000-00000030A852A000	[11392] xunit.console.exe	[3] Microsoft.VisualStudio.Sdk.TestFramework.Tests	
	System.Xml.dll	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll	Yes	N/A	Loading disabled by Include/Exclude setting.		7	4.6.79.0 built by: NETFXREL2	5/31/2015 7:41 PM	00007FFF41120000-00007FFF419BB000	[11392] xunit.console.exe	[1] xunit.console.exe	
	System.Xml.dll	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll	Yes	N/A	Loading disabled by Include/Exclude setting.		25	4.6.79.0 built by: NETFXREL2	5/31/2015 7:41 PM	00000030A9180000-00000030A9404000	[11392] xunit.console.exe	[3] Microsoft.VisualStudio.Sdk.TestFramework.Tests	
	System.Xml.Linq.dll	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll	Yes	N/A	Loading disabled by Include/Exclude setting.		6	4.6.79.0 built by: NETFXREL2	5/31/2015 7:42 PM	00007FFF61260000-00007FFF612D8000	[11392] xunit.console.exe	[1] xunit.console.exe	
	xunit.abstractions.dll	C:\Users\andarno\git\Microsoft.VisualStudio.Sdk.Testing\packages\xunit.runner.console.2.0.0\tools\xunit.abstractions.dll	Yes	N/A	Loading disabled by Include/Exclude setting.		9	2.00.0.0	3/15/2015 1:51 PM	000000308F430000-000000308F43A000	[11392] xunit.console.exe	[1] xunit.console.exe	
	xunit.abstractions.dll	C:\Users\andarno\AppData\Local\Temp\8f28dfbe-3008-4dd6-84e3-d1de2c269212\8f28dfbe-3008-4dd6-84e3-d1de2c269212\assembly\dl3\3219b247\90652572_71c3d001\xunit.abstractions.dll	Yes	N/A	Loading disabled by Include/Exclude setting.		16	2.00.0.0	3/15/2015 1:51 PM	00000030A8510000-00000030A851A000	[11392] xunit.console.exe	[3] Microsoft.VisualStudio.Sdk.TestFramework.Tests	
	xunit.console.exe	C:\Users\andarno\git\Microsoft.VisualStudio.Sdk.Testing\packages\xunit.runner.console.2.0.0\tools\xunit.console.exe	Yes	N/A	Loading disabled by Include/Exclude setting.		2	2.00.0.2929	3/15/2015 1:52 PM	000000308D3B0000-000000308D3C4000	[11392] xunit.console.exe	[1] xunit.console.exe	
	xunit.core.dll	C:\Users\andarno\AppData\Local\Temp\8f28dfbe-3008-4dd6-84e3-d1de2c269212\8f28dfbe-3008-4dd6-84e3-d1de2c269212\assembly\dl3\7629ea4a\90587abe_69c3d001\xunit.core.dll	Yes	N/A	Symbols loaded.	C:\Users\andarno\AppData\Local\Temp\8f28dfbe-3008-4dd6-84e3-d1de2c269212\8f28dfbe-3008-4dd6-84e3-d1de2c269212\assembly\dl3\7629ea4a\90587abe_69c3d001\xunit.core.pdb	20	2.00.0.2929	3/15/2015 1:52 PM	00000030A8530000-00000030A853E000	[11392] xunit.console.exe	[3] Microsoft.VisualStudio.Sdk.TestFramework.Tests	
	xunit.execution.desktop.dll	C:\Users\andarno\AppData\Local\Temp\8f28dfbe-3008-4dd6-84e3-d1de2c269212\8f28dfbe-3008-4dd6-84e3-d1de2c269212\assembly\dl3\9862266e\4fb517bf_69c3d001\xunit.execution.desktop.dll	Yes	N/A	Cannot find or open the PDB file.		15	2.00.0.2929	3/15/2015 1:52 PM	00000030A8560000-00000030A8590000	[11392] xunit.console.exe	[3] Microsoft.VisualStudio.Sdk.TestFramework.Tests	
	xunit.runner.utility.desktop.dll	C:\Users\andarno\git\Microsoft.VisualStudio.Sdk.Testing\packages\xunit.runner.console.2.0.0\tools\xunit.runner.utility.desktop.dll	Yes	N/A	Loading disabled by Include/Exclude setting.		3	2.00.0.2929	3/15/2015 1:51 PM	000000308F3C0000-000000308F3DE000	[11392] xunit.console.exe	[1] xunit.console.exe	
	xunit.runner.utility.desktop.dll	C:\Users\andarno\AppData\Local\Temp\c46c652b-97da-43b7-be88-8a9c487cf26d\c46c652b-97da-43b7-be88-8a9c487cf26d\assembly\dl3\2c309f21\98e64fa4_3ccad001\xunit.runner.utility.desktop.dll	Yes	N/A	Loading disabled by Include/Exclude setting.		12	2.00.0.2929	3/15/2015 1:51 PM	00000030A8130000-00000030A814E000	[11392] xunit.console.exe	[2] xunit.runner.utility.desktop	
	xunit.runner.utility.desktop.dll	C:\Users\andarno\AppData\Local\Temp\8f28dfbe-3008-4dd6-84e3-d1de2c269212\8f28dfbe-3008-4dd6-84e3-d1de2c269212\assembly\dl3\48329694\512a2a72_71c3d001\xunit.runner.utility.desktop.dll	Yes	N/A	Loading disabled by Include/Exclude setting.		19	2.00.0.2929	3/15/2015 1:51 PM	00000030A8790000-00000030A87AE000	[11392] xunit.console.exe	[3] Microsoft.VisualStudio.Sdk.TestFramework.Tests

**Comment by bradwilson** [comment]
Do you have a repro? I can believe there is a first chance exception here that is swallowed and ignored, but I don't believe that this type could never be created.

**Comment by AArnott** [comment]
I haven't seen a repro of this for a few weeks.

**Comment by bradwilson** [comment]
Please re-open if you find a repro. Thanks!

**Comment by aodennison** [comment]
I see this exception consistently, when attempting to debug into a Theory using InlineData or MemberData. 

As a first time user, I jumped to the wrong conclusion, Googling was no help as there are posts which only peripherally  related, enough to lead me away from the easy answer. I was running with VS Exception Settings (ctrl-alt e) to stop on all exceptions, and this first time-exception is correctly handled if you simply continue or restore VS Exception Settings to their defaults.

So while this is not a bug, it does not contribute to a good 1st time experience. 

A comment in the code would help, if the exception is unavoidable. With a little more reflection you may be able to avoid the exception altogether, which would have helped me.

System.MissingMethodException occurred
  HResult=-2146233069
  Message=Constructor on type 'Xunit.Sdk.InlineDataDiscoverer' not found.
  Source=mscorlib
  StackTrace:
       at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
       at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
       at System.Activator.CreateInstance(Type type, Object[] args)
       at Xunit.Sdk.ExtensibilityPointFactory.CreateInstance(IMessageSink diagnosticMessageSink, Type type, Object[] ctorArgs) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\ExtensibilityPointFactory.cs:line 25
  InnerException:

**Comment by weitzhandler** [comment]
Same here.
I constantly see this when debugging into a test.

**Comment by bradwilson** [comment]
The problem is that the level of reflection that's available in .NET Standard 1.1 does not do argument type matching, and I'm not planning to reimplement it (incorrectly, probably).
