### ISSUE TITLE
Improve error message when method value types for MemberData don't match method

### ISSUE THREAD

**Issue by mellinoe** [xunit/xunit#515]
The following works on the 2.0.0 stable version of Xunit, but does not in the latest 2.1.0-beta3. Testing this in a blank .NET 4.6 project.

````CSharp
public class TestClass
{
    public static IEnumerable<object[]> GetData(object[] data1, object[] data2)
    {
        for (int i = 0; i < data1.Length; i++)
        {
            yield return new object[] { data1[i], data2[i] };
        }
    }

    [Theory]
    [MemberData("GetData", new int[] { 4, 5, 6 }, new int[] { 8, 10, 12 })]
    public void RunTest(int data1, int data2)
    {
        Assert.Equal(data1 * 2, data2);
    }
}
````

The following error is given: 

System.ArgumentException : Could not find public static member (property, field, or method) named 'GetData' on ConsoleApplication2.TestClass

Is this still a supported use of MemberData?

**Comment by bradwilson** [comment]
It's failing because of a type mismatch (your `MemberData` attribute uses `int[]`, but your member method takes `object[]`). Everything starts working again when the types match (change either one to match the other).

**Comment by mellinoe** [comment]
Thanks Brad, that does narrow down the issue. In the 2.0 stable version, what I have posted above does work, as if the method were declared as accepting int[] parameters. I will take a look at the real tests that are exhibiting this issue and make sure it's the same (the above was just a simple example repro I threw together). Would you expect that this new behavior will be staying?

**Comment by bradwilson** [comment]
Honestly, I'm surprised it worked in 2.0, as it was unintentional behavior. Unless there's some compelling reason to fix it, I'm tempted to leave it as-is.

**Comment by mellinoe** [comment]
I don't have a strong feeling either way. I think it's reasonable to require the parameter types to match, and it shouldn't be a lot of work to make those changes to our test code. Would it be possible to improve the error message here? I probably could have caught this if it mentioned something about the parameter types. The current message implies that no member with that name exists.

**Comment by bradwilson** [comment]
Good idea. I've updated the title of this to reflect that.
