### ISSUE TITLE
cannot run tests in VS2015 RTM using xunit/xunit.runner.dnx 2.1.0-beta2 & dnx 1.0.0-beta4

### ISSUE THREAD

**Issue by jltrem** [xunit/xunit#516]
I'm using VS2015 RTM.  
global.json is:
```
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-beta4"
  }
}
```

project.json has:
```
  "dependencies": {
    "xunit": "2.1.0-beta2-*",
    "xunit.runner.dnx": "2.1.0-beta2-*"
  },

  "commands": {
    "test": "xunit.runner.dnx"
  },

  "frameworks": {
    "dnx451": { }
  }
```

Tests run fine at a PS prompt.  But in VS I get _Unable to start Microsoft.Framework.TestHost_

A simple sln that gives me the problem is at https://github.com/jltrem/xunit.dnx

I'm following http://xunit.github.io/docs/getting-started-dnx.html and https://github.com/xunit/xunit/issues/474 but cannot see where I'm going wrong.

**Comment by bradwilson** [comment]
VS 2015 RTM does not support DNX Beta 4.

**Comment by jltrem** [comment]
I've got a couple large projects using sdk version 1.0.0-beta4 working fine in VS2015 RTM.  How is it not supported?  I don't see anything at https://www.visualstudio.com/en-us/news/vs2015-vs.aspx that says this.

**Comment by bradwilson** [comment]
The interface defined to support project.json unit test in Visual Studio changed with pretty much every beta version, including beta 5.

If you want VS integration for DNX unit tests, you MUST move to beta 5 (or later).

**Comment by jltrem** [comment]
OK, I can buy that.  I'm working on moving to beta6.  I see issue https://github.com/xunit/xunit/issues/512 on using that version.  Thanks for your help, Brad.
