### ISSUE TITLE
Visual Studio 2015 RTM with AspNet 5 beta 6 not working

### ISSUE THREAD

**Issue by riegelj** [xunit/xunit#517]
I've installed the full RTM version of Visual Studio 2015.
 I've created a Class Library Project.
 I've downloaded the NuGet packages; xunit and xunit.runner.dnx.
 I've add the command "test": "xunit.runner.dnx" to the project.json file.
 The test cases do not show up in the Test Explorer.
 
dnx . test works 

Does anyone have this working?

my project.json file is

```json
{
  "version": "1.0.0-*",
  "description": "ClassLibrary1 Class Library",
  "authors": [ "jriegel" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
    "System.Collections": "4.0.10",
    "System.Linq": "4.0.0",
    "System.Threading": "4.0.10",
    "System.Runtime": "4.0.20",
    "Microsoft.CSharp": "4.0.0",
    "xunit": "2.1.0-beta3-*",
    "xunit.runner.dnx": "2.1.0-beta3-*"
  },
  "commands": {
    "test": "xunit.runner.dnx"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  }
}
```

**Comment by bradwilson** [comment]
We don't have an officially supported build that works with beta 6. It's my intention to release one this weekend, assuming I don't hit any stumbling blocks (I'm also adding support for UWP).

You're welcome to use a `2.1.0-beta4-*` CI build from our MyGet feed, which has already been built against the final release of ASP.NET 5 Beta 6: https://www.myget.org/F/xunit/

**Comment by dzolnjan** [comment]
+1

**Comment by CoreyKaylor** [comment]
Looks like the xunit.runner.dnx is missing from the private myget feed today. Not sure what happened, it was working the last few days but now I don't see the runner listed at all in that feed.

**Comment by CoreyKaylor** [comment]
Nevermind... It just started showing up again for me, strange stuff.

**Comment by bradwilson** [comment]
I've been working on getting a final build ready, and there were probably some moments of instability in those packages. These builds should be good now, though:

```
xunit 2.1.0-beta4-build3102
xunit.runner.dnx 2.1.0-beta4-build133
```

**Comment by dzolnjan** [comment]
To have test being shown (and get updated on change) in Test Explorer make sure that "test" command is added to project.json.

**Comment by riegelj** [comment]
I was able to get the xunit beta3 to work after I removed the dependencies and only added Microsoft.AspNet.MVC along with the needed xunit files.

{
    "version": "1.0.0-*",
  "dependencies": {
    "Microsoft.AspNet.Mvc": "6.0.0-beta6",
    "xunit": "2.1.0-beta3-*",
    "xunit.runner.dnx": "2.1.0-beta3-*"
  },
  "commands": {
    "test": "xunit.runner.dnx"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  }
}

**Comment by gongdo** [comment]
In my case, it works with follow configuration.
```Javascript
{
  "version": "1.0.0-*",
  "description": "WebApplication2.Tests Class Library",

  "commands": {
    "test": "xunit.runner.dnx"
  },

  "dependencies": {
    "[Your application name to test]": "",
    "Microsoft.AspNet.Mvc": "6.0.0-beta6",
    "System.Collections": "4.0.10",
    "System.Linq": "4.0.0",
    "System.Threading": "4.0.10",
    "System.Runtime": "4.0.10",
    "Microsoft.CSharp": "4.0.0",
    "xunit": "2.1.0-beta4-build3102",
    "xunit.runner.dnx": "2.1.0-beta4-build133"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  }
}
```

- Add NuGet Package Source for xunit MyGet Feed. https://www.myget.org/F/xunit/
- Add new "Class Library (Package)" project
- Replace project.json with above.

**Comment by bradwilson** [comment]
Shipped in 2.1 beta 4

**Comment by addmers** [comment]
Hi Guys,

{
  "version": "1.0.0-*",
  "description": "",
  "authors": [ "" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
    "CRMProject": "1.0.0-*",
    "xunit": "2.1.0",
    "xunit.runner.dnx": "2.1.0-beta6-build191"
  },
  "commands": {
    "test": "xunit.runner.dnx"
  },

  "frameworks" : {
    "dnx451": { },
    "dnxcore50" : {
      "dependencies": {
        "System.Collections": "4.0.11-beta-23225",
        "System.Linq": "4.0.1-beta-23225",
        "System.Threading": "4.0.11-beta-23225",
        "Microsoft.CSharp": "4.0.1-beta-23225"
      }
    }
  }
}


using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Xunit;
using CRMProject.Models;

namespace CRMProjectTest
{
    // This project can output the Class library as a NuGet Package.
    // To enable this option, right-click on the project and select the Properties menu item. In the Build tab select "Produce outputs on build".
    public class ClassTest
    {

        [Fact]
        public void PassingTest()
        {
            Assert.Equal(4, Add(2, 2));
        }

        [Fact]
        public void FailingTest()
        {
            Assert.Equal(5, Add(2, 2));
        }

        int Add(int x, int y)
        {
            return x + y;
        }
    }
}

I not getting any result in Test Explorer. Anyone have a solution for this issue.

**Comment by bradwilson** [comment]
Two comments:

1. Please don't report new/unrelated problems on existing closed issues.
2. Make sure you've STRICTLY followed the rules about matching DNX version to NuGet package versions found here: http://xunit.github.io/docs/getting-started-dnx.html
