### ISSUE TITLE
Test discovery failed n Visual Studio 2015

### ISSUE THREAD

**Issue by Kenester** [xunit/xunit#520]
Hi,

I have a solution with 4343 tests discover by Resharper. When VS2015 try to discover the tests of solution, it stopped with this message :
Operation failed. The index entry of length 902 bytes for the index 'Idx_Stale_StateValue_DisplayName' exceeds the maximum length of 900 bytes.
========== Discover test finished: 3100 found (0:01:30,4060397) ==========

And remove all test discover.

Here my package.config
  <package id="xunit" version="2.0.0" targetFramework="net45" />
  <package id="xunit.abstractions" version="2.0.0" targetFramework="net45" />
  <package id="xunit.assert" version="2.0.0" targetFramework="net45" />
  <package id="xunit.core" version="2.0.0" targetFramework="net45" />
  <package id="xunit.extensibility.core" version="2.0.0" targetFramework="net45" />
  <package id="xunit.runner.visualstudio" version="2.1.0-beta4-build1109" targetFramework="net45" />

**Comment by bradwilson** [comment]
Please update the `xunit.runner.visualstudio` version 2.0.1.

**Comment by Kenester** [comment]
With the version 2.0.1 I have the same error

**Comment by bradwilson** [comment]
Please provide a repro project. Thanks!

**Comment by bradwilson** [comment]
Re-open with a repro.
