### ISSUE TITLE
Test discovery hangs VisualStudio runner

### ISSUE THREAD

**Issue by sbanni** [xunit/xunit#521]
Using beta4, this will never finish test discovery in Visual Studio 2015 using VS runner

```csharp
        [Theory]
        [InlineData(typeof(Uri))]
        public void MyTheoryTest(Type type)
        {
        }
```

**Comment by bradwilson** [comment]
I'm not all to repro this in a .NET 4.5 class library, with `xunit 2.0.0` and `xunit.runner.visualstudio 2.0.1`. Can you provide more details?

**Comment by bradwilson** [comment]
Nevermind, I'm able to repro it with the latest beta builds.
