### ISSUE TITLE
xunit.runner.dnx not writing failed test details to console

### ISSUE THREAD

**Issue by markrendle** [xunit/xunit#525]
When I run my tests on Linux with `dnx451`, `beta6` and Mono 4.0.2 (stable), I don't get any of the failed test output that I would expect. It just shows the summary line with Tests, Failed, Errors, like this:

```
$ dnx . test
xUnit.net DNX Runner (64-bit DNX 4.5.1)
  Discovering: Platform.Test
  Discovered:  Platform.Test
  Starting:    Platform.Test
  Finished:    Platform.Test
=== TEST EXECUTION SUMMARY ===
   Platform.Test  Total: 18, Errors: 1, Failed: 1, Skipped: 0, Time: 1.772s
```

**Comment by bradwilson** [comment]
I'm not able to repro this with the tests for the DNX runner itself (I threw in a failing test):

<img width="510" alt="xunit" src="https://cloud.githubusercontent.com/assets/16944/9142578/7126aebe-3cf5-11e5-83df-d3a82c30cd42.png">

Can you provide a repro project?

**Comment by markrendle** [comment]
When I created a new "Unit test project" using `yo aspnet` and ran it with the `2.1.0-beta3` dependencies, I got output. It's when I change the dependencies to the latest `2.1.0-beta4` that I get no output. I'd switch back to beta3 but I don't think it's compatible with DNX beta6, is it?

```json
{
  "version": "1.0.0-*",
  "description": "",
  "authors": [ "" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
    "xunit": "2.1.0-beta4-build3109",
    "xunit.runner.dnx": "2.1.0-beta4-build134"
  },
  "commands": {
    "test": "xunit.runner.dnx"
  },

  "frameworks" : {
    "dnx451": { },
    "dnxcore50" : {
      "dependencies": {
        "System.Collections": "4.0.10-beta-22816",
        "System.Linq": "4.0.0-beta-22816",
        "System.Threading": "4.0.10-beta-22816",
        "Microsoft.CSharp": "4.0.0-beta-22816"
      }
    }
  }
}
```

Test class:
```csharp
public class SampleTest
{
    [Fact]
    public void TrueIsFalse()
    {
    	Assert.True(false);
    }

    [Fact]
    public void ThrowException()
    {
        string str = null;
        Console.WriteLine(str.Length);
    }
}
```

**Comment by markrendle** [comment]
My mistake, it seems that beta3 is compatible with DNX beta6, so I can use that for the time being.

**Comment by markrendle** [comment]
I'll clone this repo and see if I can repro the issue using `master`, if so I'll either fix and PR or reopen this issue.

**Comment by bradwilson** [comment]
Thanks. :)

**Comment by natemcmaster** [comment]
I'm seeing this too:

https://travis-ci.org/aspnet/Microsoft.Data.Sqlite#L1303

>  xunit 2.1.0-rc1-build3118
  xunit.abstractions 2.0.0
  xunit.assert 2.1.0-rc1-build3118
  xunit.core 2.1.0-rc1-build3118
  xunit.extensibility.core 2.1.0-rc1-build3118
  xunit.extensibility.execution 2.1.0-rc1-build3118
  xunit.runner.dnx 2.1.0-beta5-build156
  xunit.runner.reporters 2.1.0-rc1-build3115
  xunit.runner.utility 2.1.0-rc1-build3115

**Comment by bradwilson** [comment]
Are people who are seeing this all running Travis? /cc @markrendle @natemcmaster 

Are there any available repro projects?

**Comment by natemcmaster** [comment]
@bradwilson I am seeing the same behavior on Mono 4.0.x on OS X Yosemite for [aspnet/microsoft.data.sqlite](https://github.com/aspnet/microsoft.data.sqlite). Could this be a bug in DNX?

1. `dnvm upgrade -u` (I'm using dnx-mono-1.0.0-beta7-12364)
1. `git clone https://github.com/aspnet/Microsoft.Data.Sqlite.git`
2. `cd Microsoft.Data.Sqlite`
3. `./build.sh --quiet verify`
4. (Wait because dnu restore is slow)
...
![image](https://cloud.githubusercontent.com/assets/2696087/9368372/cc51e002-4677-11e5-882d-bff8b607259f.png)

**Comment by bradwilson** [comment]
What version of xUnit.net are you using? If you plan to use DNX beta 7, you need to be using a `2.1.0-beta5-*` build from our CI MyGet feed: https://www.myget.org/F/xunit/

**Comment by natemcmaster** [comment]
This project [is using the xunit CI feed](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/dev/NuGet.Config) from myget.

Here are the version in this project:
> $ dnu list
...
  xunit 2.1.0-rc1-build3118
  xunit.abstractions 2.0.0
  xunit.assert 2.1.0-rc1-build3118
  xunit.core 2.1.0-rc1-build3118
  xunit.extensibility.core 2.1.0-rc1-build3118
  xunit.extensibility.execution 2.1.0-rc1-build3118
  xunit.runner.dnx 2.1.0-beta5-build156
  xunit.runner.reporters 2.1.0-rc1-build3115
  xunit.runner.utility 2.1.0-rc1-build3115

**Comment by bradwilson** [comment]
I've been able to track down the issue, and the fix is not trivial. It was introduced in xUnit.net 2.1 beta 4.

If you can limit yourself to DNX Beta 6, then you can use the `2.1.0-beta3-*` builds of `xunit` and `xunit.runner.dnx`. Unfortunately, there is no workaround at this time that allows you to use current DNX Beta 7 builds, because the APIs used by the test runner have changed, making the older builds of xUnit.net incompatible.

**Comment by bradwilson** [comment]
Alright, I think this is fixed now. I just verified with the following:

```
Debian 8
Mono Stable 4.0.3.19/e4f44c1
DNX 1.0.0-beta7-15119
xunit 2.1.0-rc1-build3130
xunit.runner.dnx 2.1.0-beta5-build159
```

The DNX build is from https://www.myget.org/F/aspnetrelease/
The xUnit.net builds are from https://www.myget.org/F/xunit/

Let me know if things are (or aren't) working now.

**Comment by AlekseyMartynov** [comment]
@bradwilson are new builds compatible with DNX beta6? Below are my results, on Windows.
    
    xunit 2.1.0-rc1-build3131  
    xunit.runner.dnx 2.1.0-beta5-build159
    
    Microsoft .NET Development Utility CoreCLR-x64-1.0.0-beta6-12256  

    System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
       at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
       at System.Reflection.RuntimeAssembly.get_DefinedTypes()
       at Microsoft.Framework.Runtime.Common.EntryPointExecutor.TryGetEntryPoint(Assembly assembly, IServiceProvider serviceProvider, Object& instance, MethodInfo& entryPoint)
       at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
       at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
       at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
       
       
    Microsoft .NET Development Utility CLR-x86-1.0.0-beta6-12256
    
    System.NullReferenceException: Object reference not set to an instance of an object.
       at Xunit.Runner.Dnx.Program.Main(String[] args)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
       at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
       at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)    
           
Reverting to beta4 + beta4: works but don't display failures

**Comment by bradwilson** [comment]
> are new builds compatible with DNX beta6?

Unfortunately, no. There was a massive rename (and a couple API changes) in DNX Beta 7 which prevent the new builds from working with older versions of DNX.

If you're on DNX Beta 6, you should stick with the xUnit.net 2.1 beta 3 builds. They do work with DNX Beta 6.

**Comment by bradwilson** [comment]
@natemcmaster I verified that your tests run, and the failures show up appropriately.

![Failures](https://cloud.githubusercontent.com/assets/16944/9445315/60f1094c-4a40-11e5-964c-de3e9907916c.png)

**Comment by natemcmaster** [comment]
Yup, I verified this locally too. 

:closed_book:
