### ISSUE TITLE
xUnit dnx Runner Fails from Command Line

### ISSUE THREAD

**Issue by MisterJames** [xunit/xunit#526]
I am getting a null reference exception when using xUnit with a test assembly targeting dnx46, given the following dependencies in my project.json and running `dnx . test`:

    "xunit": "2.1.0-*",
    "xunit.runner.dnx": "2.1.0-*",

I also have the command registered:

    "commands": {
      "test": "xunit.runner.dnx"
    },

These are listed in the docs [here](http://xunit.github.io/docs/getting-started-dnx.html#run-tests-console).  If I also add a reference to `xunit.runner.utility` the command line invocation works as expected.

I found this line in `Program.cs` that lead me to the solution: https://github.com/xunit/dnx.xunit/blob/master/src/xunit.runner.dnx/Program.cs#L154  Not sure if it's a red herring, but adding that dependency to my project was the workaround.

Is this just an issue with the docs, or should the reference check be against the `xunit` dependency itself?

**Comment by bradwilson** [comment]
Your specifications for the packages are very loose. What package versions are you actually getting matched again?

What version of DNX are you using?

There is a strong tie between versions of xUnit.net and versions of DNX. For example, the current build of xUnit.net (2.1 beta 4) works **only** against the **released** version of DNX beta 6: nothing older or newer is expected to work (or supported).

**Comment by MisterJames** [comment]
After troubleshooting with @bradwilson I'm fairly certain that the error is due to an incompatible version of DNX getting set when PowerShell is launched. Setting the active runtime to beta 6, running `dnu restore` and then `dnx . test` seems to work without adding the reference to `utility`.

The sample docs are the ones that specify the version I'd used; perhaps an update there to recommend using a better specificity would be a good addition?
