### ISSUE TITLE
Exception in test crashes test runner (TE.ProcessHost.Managed.exe)

### ISSUE THREAD

**Issue by vegar** [xunit/xunit#527]
Visual Studio 2015
xUnit 1.9.2
xUnit.runner.visualstudio 2.0.0-rc2-build1043

I have a test that asserts on the type of an object. For some reason, the type is not what I expected, so the assert fails.

```csharp
        [Fact(DisplayName = "Returns first, and only, part from multipart content")]
        public async void ReturnsFirstAndOnlyPart()
        {
            var request = new HttpRequestMessage()
                {
                    Content = new MultipartContent
                        {
                            new StringContent("first and only"),
                        }
                };

            var part = await request.Content.AssertSinglePart();   //returns first and only part of multipart message. Throws if more than one exists
            
            part.Should().BeOfType<StringContent>();   //for some reason this fails
        }
```

The problem, though, is that that the test runner (TE.ProcessHost.Managed.exe) crashes:

> The active Test Run was aborted because the execution process exited unexpectedly. The test execution process crashed while running the tests.

From the crash dump I get the following information:

> An unhandled exception of type 'Xunit.Sdk.AssertException' occurred in mscorlib.dll
> 
> Additional information: Expected type to be System.Net.Http.StringContent, but found System.Net.Http.StreamContent.

Anyone have any idea why this takes down the testrunner?
One other thing: It sometimes run ok if I only trigger this test, but never if I trigger all tests.
And another thing: I have recreated the same test with MSTest, and there it runs fine. (it fails, but doesn't crash the runner...)

**Comment by bradwilson** [comment]
Why are you using an RC build of the Visual Studio runner? That's 6 months (and 9 builds) old.

**Comment by bradwilson** [comment]
Also, `async void` unit tests are not supported with xUnit.net 1.x. You must use `async Task`. That's the actual cause of the crash, since your code is running unobserved on a background thread, which throws an exception, which causes the crash.

**Comment by vegar** [comment]
Running a 6 months old runner should fit the 2 years old test framework, though...? ;-)
We're outdated. I know. Will fix. Pretty soon. Actually, I had a test migration earlier today, and that went pretty smooth, but I'm trying to sort out the visual studio 2013 -> 2015 issues while trying to not change too many parameters in one go...


But your `async void` -> `async Task` solution seems to work. Strange that we never got this error in Visual studio 2013? Since the test now goes red, I had to check: It's reported as green on the build server. Could it be reported as green because the exception not being detected?

Anyway: Thanks for a rapid and helpful reply!
