### ISSUE TITLE
Visual Studio 2015 RTM with beta 6 not starting/opening async tests

### ISSUE THREAD

**Issue by dzolnjan** [xunit/xunit#528]
1) Async tests fail to execute when started from context menu by right clicking on method body (right click > Run Tests). Output always show message "No tests found to run". 
* Starting async test from Test Explorer works (right click on method > Run Selected Tests).

2) Left clicking on async test in Test Explorer does not open test file, simply nothing happens. 
* Works fine with non async test.

```json
{
  "dependencies": {
    "System.Collections": "4.0.10-beta-23109",
    "System.Linq": "4.0.0-beta-23109",
    "System.Threading": "4.0.10-beta-23109",
    "System.Runtime": "4.0.10-beta-23109",
    "Microsoft.CSharp": "4.0.0-beta-23109",

    "xunit": "2.1.0-beta4-*",
    "xunit.runner.dnx": "2.1.0-beta4-*",
    "xunit.runner.visualstudio": "2.0.1",
  },

  "frameworks": {
    "dnx451": { }
  },

  "commands": {
    "test": "xunit.runner.dnx"
  }
}
```

**Comment by bradwilson** [comment]
A couple comments:

- `xunit.runner.visualstudio` is not required
- Your JSON is illegal (trailing comma on the last dependency)
- A reminder that Test Explorer will not show tests until you rebuild the project AFTER Test Explorer has first become visible.

When I fixed the first two issues (and cognizant of the third), I cannot reproduce this. Please re-open with a full repro project if this doesn't fix the issue for you.
