### ISSUE TITLE
DNX test discovery does not load metadata in VS2015 test explorer for async tests

### ISSUE THREAD

**Issue by bcrosnier** [xunit/xunit#530]
Considering the repro project at https://github.com/bcrosnier/XUnit-BugRepro1 .

On Visual Studio 2015, using `xunit.dnx.runner`, the Test Explorer identifies asynchronous Fact methods, returning either void or Tasks, but is unable to:
- Sort them by project (category) when changing the sort order (it sorts them in`External` instead)
- Link them to a source code file, accessible when double-clicking on them, or by clicking in the test's call stack in case of failure. Instead, `Source unavailable` is displayed.

Asynchronous tests can still, however, be run correctly, and seem to report a correct result.

Synchronous tests behave as expected.

Potentially linked to #485.

Versions: ([project.json](https://github.com/bcrosnier/XUnit-BugRepro1/blob/master/src/XUnitTests.Async/project.json))
```
    "xunit": "2.1.0-beta4-build3109",
    "xunit.runner.dnx": "2.1.0-beta4-build134"
```

Active runtime is CLR-x86-1.0.0-beta6-12256.
DNX SDK version is 1.0.0-beta6.

Demo screenshot:

![XUnit-BugRepro1 Test runner demo screenshot](https://raw.githubusercontent.com/bcrosnier/XUnit-BugRepro1/master/Screenshots/Scheenshot1.png)

The Tests output does not show eny error when discovering.

```
------ Discover test started ------
------ Test started: Project: XUnitTests.Async ------
Starting  Microsoft.Framework.TestHost [C:\Users\Benjamin\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta6\bin\dnx.exe --appbase "D:\Dev\Personal\XUnit-BugRepro1\src\XUnitTests.Async" Microsoft.Framework.ApplicationHost --port 40833 Microsoft.Framework.TestHost --port 40983]
Connected to Microsoft.Framework.TestHost
Discovering tests in 'D:\Dev\Personal\XUnit-BugRepro1\src\XUnitTests.Async\project.json'
========== Discover test finished: 3 found (0:00:01.1049033) ==========
```

**Comment by bradwilson** [comment]
Source information is provided externally. If this doesn't work, it's likely a bug in the DNX source information provider, not in xUnit.net. /cc @damianedwards

**Comment by DamianEdwards** [comment]
Can you log over at https://github.com/aspnet/Testing pls?

**Comment by bradwilson** [comment]
Done, thanks. :)

**Comment by rynowak** [comment]
Fixed in aspnet/Testing@19416813beebf9248ed49919660106e89284530f

This will be in the beta7 release.

**Comment by bradwilson** [comment]
Shipping in xunit.runner.dnx beta 5.

**Comment by rjpaulsen** [comment]
@bradwilson says this is fixed in beta5, but I'm on RC1 and I still have the behavior. I got here from #485 which says traits are not being displayed in the Test Explorer. I'm on VS2015 Enterprise, Update 1 with:

`  "dependencies": {
    "xunit": "2.2.0-beta1-build3239",
    "xunit.runner.dnx": "2.1.0-rc1-build204"
  },`

If I have a test like the following and run the test from the command line, (`dnx test`) I do see output referencing 'THEFACT', but no mention of "ABC" or "XYZ". 

`[Fact(DisplayName = "THEFACT")]`
`[Trait("ABC", "XYZ")]`
`public void StaticValuesABC()`
`{`
`Assert.Equal(true, false);`
`}`

**Comment by bradwilson** [comment]
If there are still issues here, then you will probably need to take this up with the ASP.NET tooling team, as we are not directly responsible for the Visual Studio integration.

**Comment by rjpaulsen** [comment]
Is it possible to get the traits to show up when running from the command line? I also don't see them there which is why I didn't think it was a VS thing..

**Comment by bradwilson** [comment]
You can use them to filter tests, or you can see them in the XML output.
