### ISSUE TITLE
Mark a InlineData as 'Skip'

### ISSUE THREAD

**Issue by twsouthwick** [xunit/xunit#532]
I know we can mark a fact as 'skip', but I can't seem to find a way to do it for theories and inline data.  I would like to be able to do this so that I don't have failures, but can still see that there are tests not working.

**Comment by bradwilson** [comment]
We do not have this capability today.

**Comment by mudnug** [comment]
Would the [SkippableTheoryAttribute sample](https://github.com/xunit/samples.xunit/tree/master/DynamicSkipExample) help you?

**Comment by cdmihai** [comment]
Any news on this? I'd find it helpful as well, since I have a theory with a bunch of InlineData out of which one fails. I want to make a github issue out of it and skip just that one.

**Comment by bradwilson** [comment]
This was shipped in 2.2 beta 1.

**Comment by michaelkargl** [comment]
The shipped fix in version 2.2 beta 1 seems to "just" fix and test skipping MemberData attributes, not InlineData. Unfortunately the issue still persists in version 2.4.0.

Reduced and simplified version of one of the tests that is failing
```csharp
[Theory]
[InlineData("{code}", Skip = "Needs clarification with customer")]
public void TestFunctionByCode_WithValidInput(string code, double expectedValue)
{
// AAA
}
```

The test is run even though it is marked with Skip.
Could it be that this is an obsolete feature?

**Comment by GeirSmestad** [comment]
In my instance, the skip-annotated tests are run even when the annotation is commented out (!). The commented-out instances are not run if I introduce a syntax error in the annotation, delete these tests from the VS test runner and clean & rebuild the project.

```
        [Theory]
	[InlineData(false, false)]
        [InlineData(true, false)]
        //[InlineData(false, true, Skip = "Do not run this test")]
        //[InlineData(true, true, Skip = "Do not run this test")]
        public void TestCreateAccount(bool parameterA, bool parameterB)
        {
	    // Test details
	}
```

Just to be explicit, this code results in four test instances being run. XUnit 2.4.1, Visual Studio 15.9.7. I have the XUnit test runner (2.4.1) installed, as well as the Microsoft.NET.Test.Sdk package (15.9.0).

**Comment by Bernoulli-IT** [comment]
It works here. The Skip reason is shown in the Test results. 
![image](https://user-images.githubusercontent.com/9802752/63594437-b8ffc380-c5b6-11e9-86dd-01cbff52cfef.png)

**Comment by clazarr** [comment]
> It works here. The Skip reason is shown in the Test results.
> ![image](https://user-images.githubusercontent.com/9802752/63594437-b8ffc380-c5b6-11e9-86dd-01cbff52cfef.png)
> Skip = "Works" 😄

Perhaps it would be useful if you show your test method with its attributes and not just the test output.

**Comment by l3oxy** [comment]
> 
> 
> It works here. The Skip reason is shown in the Test results.
> ![image](https://user-images.githubusercontent.com/9802752/63594437-b8ffc380-c5b6-11e9-86dd-01cbff52cfef.png)
> Skip = "Works" 😄

@Bernoulli-IT , how did you accomplish InlineData Skip using a stable version of XUnit?
I see that you used `Skip = "works"` , but may you show the whole 
```cs
[InlineData(...)]
```
 line of code, please?

**Comment by Bernoulli-IT** [comment]
> 
> 
> > It works here. The Skip reason is shown in the Test results.
> > ![image](https://user-images.githubusercontent.com/9802752/63594437-b8ffc380-c5b6-11e9-86dd-01cbff52cfef.png)
> > Skip = "Works" 😄
> 
> Perhaps it would be useful if you show your test method with its attributes and not just the test output.

Here is a snippet of what I used...

[Fact (Skip = "Works")]
public async void TestMethod()
{
  ...
}

**Comment by gdennie** [comment]
The inability to easily filter test queue is really a nuisance.

**Comment by vhnatyk** [comment]
still doesn't work in 2.4.1 🤦‍♂️ 
`[InlineData(false, false, Skip = "System.Text.Json v5.0 JsonConstructor")]`

**Comment by jzabroski** [comment]
Duplicate of https://github.com/xunit/xunit/issues/1782
