### ISSUE TITLE
Is there an equivalent to to NUnit's AreEquivalent?

### ISSUE THREAD

**Issue by alexbooker** [xunit/xunit#533]
From the [_NUnit documentation_](http://www.nunit.org/index.php?p=collectionAssert&r=2.6):

> `AreEquivalent` tests whether the collection contents are equal, but without regard to order

Is there an equivalent in xUnit?

Thanks!

**Comment by bradwilson** [comment]
No, there is no equivalent.

What I usually do in these scenarios where order is unpredictable (or irrelevant) is to impose any order anyway (with LINQ's `OrderBy`), and then just use `Assert.Collection` or `Assert.Equal`.

**Comment by alexbooker** [comment]
Thanks. That worked for me :smile:.
