### ISSUE TITLE
Test execution hangs when item in data row for theory contains public Task property

### ISSUE THREAD

**Issue by vlaci** [xunit/xunit#534]
After upgrading to 2.0, my test running attempts hanged.
Debugging pointed to `XunitTheoryTestCaseRunner.AfterTestCaseStartingAsync`
Here we try to generate a display name for tests:
```cs
var theoryDisplayName = TestCase.TestMethod.Method.GetDisplayNameWithArguments(DisplayName, convertedDataRow, resolvedTypes);
```
Suppose we have a theory argument holding a property (or filed) of `Task` that never finishes. That `Task` has a `Result` property that blocks on getting its value. It is a problem, because
deep down the call chain we enumerate the fields and properties of theory arguments:
```cs
var fields = type.GetRuntimeFields()
                 .Where(f => f.IsPublic && !f.IsStatic)
                 .Select(f => new { name = f.Name, value = WrapAndGetFormattedValue(() => f.GetValue(value), depth) });
var properties = type.GetRuntimeProperties()
                     .Where(p => p.GetMethod != null && p.GetMethod.IsPublic && !p.GetMethod.IsStatic)
                     .Select(p => new { name = p.Name, value = WrapAndGetFormattedValue(() => p.GetValue(value), depth) });
//                                                                                            ^ this call can block
var parameters = fields.Concat(properties)
                       .OrderBy(p => p.name)
                       .Take(MAX_OBJECT_PARAMETER_COUNT + 1)
                       .ToList();
//                      ^ Here we enumerate the properties and the blocking method is invoked

```

I don't think that it is generally a good idea to enumerate all fields and properties of theory arguments because of possible side effects of not well-behaving code. The most common example could be `Task` itself

**Comment by bradwilson** [comment]
I can put in special case logic for Task. We're not going to stop enumerating things, though.

**Comment by vlaci** [comment]
It'd be more than enough for my use case :)
