### ISSUE TITLE
SerializationException in MessageSinkWrapper

### ISSUE THREAD

**Issue by mudnug** [xunit/xunit#537]
I'm having trouble creating a solid reproducible case for this issue (it seems to be inconsistent).

We use a custom runner and a custom message sink wrapper that might influence this.

Where should we look for solving this error that shuts down our runner on ocassion?

Exception: System.Runtime.Serialization.SerializationException

Message: Type 'Xunit.Sdk.TestFrameworkProxy+MessageSinkWrapper' in Assembly 'xunit.execution.desktop, Version=2.0.0.2929, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' is not marked as serializable.

![image](https://cloud.githubusercontent.com/assets/859143/9259243/293d6c9c-41bd-11e5-8e8b-71f4787b4609.png)

**Comment by bradwilson** [comment]
Fixed 4 days ago. :) https://github.com/xunit/xunit/commit/9d22ca78d33fb375d0b9002cae76462ddbc91821

You'll have to pull an RC1 build from our [MyGet feed](https://www.myget.org/F/xunit/) in order to get a fixed version.
