### ISSUE TITLE
xunit vsix

### ISSUE THREAD

**Issue by mishfit** [xunit/xunit#544]
I'm at a company that currently uses a non-standard mechanism for getting packages which isn't compatible with the xunit visual studio runner package (adding via nuget breaks their process, but attempts to add using their process doesn't make xunit tests discoverable or runnable). How might I go about adding the xunit runner via an extension (I realize this was deprecated but the company constraints have me in a bind)?

To get the test explorer working I have to make sure not to checkin any changes related to nuget, other developers use Resharper which for me disrupts my use of VsVim and the fact that I've already learned all the shortcuts for refactoring provided with Visual Studio OOTB and don't necessarily feel the need for Resharper.

**Comment by xperiandri** [comment]
I also want to ask what was the purpose to move to NuGet instead of VSIX?
It looks like using technology in inappropriate way.

**Comment by mishfit** [comment]
Oh, I should've closed this...I learned (through various sources, none of which are official documentation) that VS2013 and up will "discover" test adapters *ONLY* through the invoking of the NuGet process...so regardless of making a VSIX it appears that VS will not "know" about the test adapters...

@bradwilson, is that accurate?

**Comment by xperiandri** [comment]
But NUnit Adapter is distributed by VSIX!

**Comment by bradwilson** [comment]
@mishfit No, that's not accurate.

The VSIX had significant downsides:

1. You can only have one version of the runner installed, and it's always used for all projects.
2. Every developer had to install the VSIX.
3. Related: you must install the VSIX on all the build machines, which may include build machines that you do not control.

We have no intention of bring the VSIX back.

**Comment by xperiandri** [comment]
1. Why will someone need different version of runner? Isn't it possible to pack different version into one VSIX?
2. Not every developer needs it. Someone uses Resharper to run unit tests, another one Code Rush, etc
3. Agree. This is the only real point.

**Comment by mishfit** [comment]
Hmmm...there are a lot of people with misconceptions about how VS test adapter discovery works then, oh well...the build machines are already taken care of where I work, we don't use NuGet (but another package manager which can't handle all types of NuGet packages)...most other people use Resharper but I can't stand it since I've already memorized the shortcuts for VS OOTB refactoring (and I use VsVim

**Comment by bradwilson** [comment]
If VSIX distribution of test runner is an absolutely requirement, NUnit remains an available option for you.
