### ISSUE TITLE
Extending TheoryAttribute and enabling Skip in debug mode breaks the functionality, InlineData stops being passed on

### ISSUE THREAD

**Issue by geoarion** [xunit/xunit#546]
Env: VS 2015 Enterprise, WinServer 2012R2, .Net 4.6 test project, XUnit 2.0

It seems that enabling skip (in debug mode) for a class extending TheoryAttribute causes xunit (or VS) to not pass on the Inline data.

Error when trying to debug the test case:
**System.InvalidOperationException: The test method expected 1 parameter value, but 0 parameter values were provided.**

New attribute is:
```c#
    public class RunnableInDebugOnlyTheoryAttribute : TheoryAttribute
    {
        public RunnableInDebugOnlyTheoryAttribute()
        {
            if (!Debugger.IsAttached)
            {
               this.Skip = "This test will only run when debugging it!";
            }
        }
    }
```

Usage:
```c#
        [RunnableInDebugOnlyTheory]
        [InlineData(3)]
        [InlineData(5)]
        [InlineData(6)]
        public void MyFirstTheory(int value)
        {
            Assert.True(true);
        }
```

Note: the same technique, for **FactAttribute** seems to work just fine.

**Comment by bradwilson** [comment]
You can't really do this with the Visual Studio runner.

The way this runner works is that it has a separated discovery and execution phase. The discovery here has determined that the test should be skipped, and does not pull the inline data. Then you try to run the test under the debugger, and it uses the discovered information, which is wrong.

Instead, you need to use something like the dynamic skip sample: https://github.com/xunit/samples.xunit/tree/master/DynamicSkipExample

**Comment by geoarion** [comment]
Thanks Brad for the explanations and the sample, that worked great!
