### ISSUE TITLE
Unable to build solution after nuget restore

### ISSUE THREAD

**Issue by ArsenShnurkov** [xunit/xunit#548]
https://gist.githubusercontent.com/ArsenShnurkov/bd7bb5b7aebe38bf9570/raw/78349b8648ff550911d90700ca7e023d9331397f/gistfile1.txt

**Comment by bradwilson** [comment]
Building xUnit.net on Mono has never been officially supported. The build.sh that's there is a convenience that may or may not work at any given time.

Right now, the source depends on features that Mono has not implemented (the `dotnet` target framework and .NET 4.6), and will not be able to compile until it catches up.

**Comment by ArsenShnurkov** [comment]
Is it possible to compile it with applying smal patch from gentoo install sctipt? (the patch will cut some minor features of xunit and provide the ability to comple hte build with sln file)

**Comment by bradwilson** [comment]
I have no idea what's needed to get it to compile, and since we don't officially support it, we're unlikely to spend any time on it ourselves.

**Comment by ArsenShnurkov** [comment]
it is possible to compile it on mono:
https://github.com/xunit/xunit/issues/607
