### ISSUE TITLE
MSBuild Runner not utilizing [Collection] Assembly attribute

### ISSUE THREAD

**Issue by dealproc** [xunit/xunit#551]
An inquiry to find out if this is an expected thing or not.

My test project(s) are both marked as `[assembly: CollectionBehavior(CollectionBehavior.CollectionPerClass, DisableTestParallelization = true)]`, but when being run via MSBuild, i had to explicitly set `DisableTestParallelization` for the MSBuild runner to respect it.

**Comment by bradwilson** [comment]
I am able to repro this with `xunit.runner.msbuild` version `2.0.0` but not with `2.1.0-beta4-build3109`, so it appears to be fixed already.
