### ISSUE TITLE
DisableTestParallelization not behaving as expected

### ISSUE THREAD

**Issue by arangas** [xunit/xunit#553]
I've been writing tests using xunit 2.1.0 beta 4. All tests use theories. They share state due to the project that is being tested, so I need to have DisableTestParallelization turned on or else they interfere with each other.

It seems that when running one test or maybe two tests at a time, there is no issue. However beyond that unpredictable behaviour occurs. Also debugging a set of tests seems to be OK, presumably because they are being run one at a time.

Is this scenario supported? Is another setting required or possibly a bug I can help investigate?

**Comment by bradwilson** [comment]
What runner? How are you disabling parallelization?

**Comment by arangas** [comment]
This is using the test runner from Visual Studio 2015. The xunit packages I have installed in the test project are:

```xml
<package id="xunit" version="2.1.0-beta4-build3109" targetFramework="net45" />
<package id="xunit.abstractions" version="2.0.0" targetFramework="net45" />
<package id="xunit.assert" version="2.1.0-beta4-build3109" targetFramework="net45" />
<package id="xunit.core" version="2.1.0-beta4-build3109" targetFramework="net45" />
<package id="xunit.extensibility.core" version="2.1.0-beta4-build3109" targetFramework="net45" />
<package id="xunit.runner.visualstudio" version="2.1.0-beta4-build1109" targetFramework="net45" />
```

I'm turning off parallelization in AssemblyInfo.cs with the line:

    [assembly: CollectionBehavior(DisableTestParallelization = true)]

**Comment by arangas** [comment]
I updated a library and despite repeated testing, I can't reproduce this issue. Not sure why that would have made any difference but I don't think there's anything to see here.

Sorry for taking your time on this issue.

**Comment by bradwilson** [comment]
Glad to know it's resolved. :)
