### ISSUE TITLE
MSBuild runner throws InvalidCastException with VS2015

### ISSUE THREAD

**Issue by James-Ko** [xunit/xunit#555]
I installed the xUnit MSBuild runner the other day and followed the documentation [here](http://xunit.github.io/docs/running-tests-in-msbuild.html), however it seems to be throwing an error when I try to run it:

    C:\Users\James\libvideo\tests\Core\Core\Core.csproj(85,5):

    error MSB4127: The "xunit" task could not be instantiated from the assembly "C:\Users\James\libvideo\tests\Core\packages\xunit.runner.msbuild.2.0.0\build\portable-net45+win+wpa81+wp80+monotouch+monoandroid+Xamarin.iOS\xunit.runner.msbuild.dll".
    Please verify the task assembly has been built using the same version of the Microsoft.Build.Framework assembly as the one installed on your computer and that your host application is not missing a binding redirect for Microsoft.Build.Framework.
    Unable to cast object of type 'Xunit.Runner.MSBuild.xunit' to type 'Microsoft.Build.Framework.ITask'.

Here is my project file:

    <?xml version="1.0" encoding="utf-8"?>
    <Project ToolsVersion="14.0" DefaultTargets="Build;Test" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
      <Import Project="..\packages\xunit.runner.msbuild.2.0.0\build\portable-net45+win+wpa81+wp80+monotouch+monoandroid+Xamarin.iOS\xunit.runner.msbuild.props"
              Condition="Exists('..\packages\xunit.runner.msbuild.2.0.0\build\portable-net45+win+wpa81+wp80+monotouch+monoandroid+Xamarin.iOS\xunit.runner.msbuild.props')" />

      

      <UsingTask AssemblyFile="xunit.runner.msbuild.dll"
                 TaskName="Xunit.Runner.MSBuild.xunit"/>
      <Target Name="Test">
        <xunit Assemblies="bin\$(Configuration)\Core.dll"/>
      </Target>
    </Project>

I've checked through it multiple times to make sure the spelling was correct and changed `Aseemblies=` to `Assembly=`, but it gives me the same results.

I looked through the source and it looks like `xunit` inherits from `Microsoft.Build.Utilities.Task`, which implements `ITask`, so I'm guessing it's an assembly mismatch of some sort.

My MSBuild version is 14.0.23107.0.

---

**Edit:** To clarify further, my version of xUnit is 2.0.0; I installed it via NuGet.

**Comment by bradwilson** [comment]
Your `UsingTask` is both incorrect (no path to the DLL) and unnecessary (because it duplicates what's in the props file):

```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <UsingTask
    AssemblyFile="$(MSBuildThisFileDirectory)xunit.runner.msbuild.dll"
    Condition="Exists('$(MSBuildThisFileDirectory)xunit.runner.msbuild.dll')"
    TaskName="Xunit.Runner.MSBuild.xunit"/>
</Project>
```

(from https://github.com/xunit/xunit/blob/2.0/src/xunit.runner.msbuild/build/xunit.runner.msbuild.props)

Remove the `UsingTask` block and it should just work.

**Comment by James-Ko** [comment]
Hm, I tried your suggestion (removing the UsingTask) and it still seems to be giving out the same error. I'll post an update after investigating this a little further.

**Comment by James-Ko** [comment]
Alright, so I just opened up ILSpy and sure enough they're using different versions of `Microsoft.Build.Framework.dll`. This is what xUnit is referencing:

    // Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Here's the results for the copy of MSBuild that's installed on my machine:

    // Microsoft.Build.Framework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

**Comment by bradwilson** [comment]
If I go to `C:\Program Files (x86)\MSBuild\14.0\bin` and open `msbuild.exe.config`, I see this binding redirect:

```xml
<dependentAssembly>
    <assemblyIdentity name="Microsoft.Build.Framework" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
    <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="14.0.0.0"/>
</dependentAssembly>
```

So it's not clear to me how you're in this situation with a default MSBuild installation. MSBuild goes to great lengths to ensure backward compatibility of the extensibility system.

Plus... we run all of our builds with MSBuild v14, and we run all of our tests with our MSBuild runner. If that was generally broken, I'd know about it. :smiley:

**Comment by James-Ko** [comment]
Oh, I see what the problem is now. I knew it was an bad idea to copy && paste MSBuild into my repo... not even sure how it worked in the first place, to be honest. Terribly sorry you had to deal with my stupidity, I'll close this right now.
