### ISSUE TITLE
generation of a cross product of multiple members for MemberData

### ISSUE THREAD

**Issue by floetscher** [xunit/xunit#557]
I'm missing functionality for generating a cross product by providing multiple members in MemberData.

For example, for the given IEnumerables...
```csharp
public static IEnumerable DataStrings
{
    get 
    { 
        yield return new object[] { "A" };
        yield return new object[] { "B" }; 
    }
}

public static IEnumerable DataIntegers
{
    get
    {
        yield return new object[] { 1 };
        yield return new object[] { 2 };
        yield return new object[] { 3 };
    }
}
```
...I'd like to write a test method with a signature like this...
```csharp
[Theory]
[MemberData("DataStrings", "DataIntegers")]
public void TestMethod(string dataString, int dataInteger)
```
...receiving "A"/1, "A"/2, "A"/3, "B"/1, "B"/2 and "B"/3 when executing the tests.

**Comment by bradwilson** [comment]
There's nothing built-in, but it's fairly trivial to do. Here's an example:

https://github.com/xunit/samples.xunit/blob/master/TheoryDataExamples/MatrixTheoryData.cs

**Comment by floetscher** [comment]
btw I found an extension to XUnit, which is doing what I wanted too: https://github.com/AArnott/Xunit.Combinatorial
