### ISSUE TITLE
Partially applied async function in F# causes xunit to hang in release mode

### ISSUE THREAD

**Issue by jamesjrg** [xunit/xunit#558]
I am using XUnit 2.0 and have tried both the Visual Studio runner and the console runner.

Compiled with .NET 4.5, F# 3.1 (F# core 4.3.1.0), Visual Studio 2013.

The following program causes the xunit runner to hang when compiled in release mode, but not in debug mode. Moving the async call inside the Fact also prevents it from freezing.

```fsharp
module xunithang

open Xunit

type MrsRecordType = {
    StringProperty : string }

let partialAsyncFunc _ () = async { return true }

let testFunc partialAsyncFunc = async {    
    return! partialAsyncFunc() }

module ``async func hangs`` =
    let parameter = {
            MrsRecordType.StringProperty = "hello"
        }

    let result =
        testFunc (partialAsyncFunc parameter)
        |> Async.RunSynchronously
    
    [<Fact>]
    let ``this is never reached`` () =

        match result with
        | true -> ()
        | _ -> failwith "fail"
```

**Comment by bradwilson** [comment]
I honestly don't know enough about F# to know what this is supposed to do.

**Comment by jamesjrg** [comment]
Is your comment a request for clarification, or just a note that you don't have time to fix edge cases in F# support?

**Comment by bradwilson** [comment]
I was pointing out that I really don't have any idea how to debug what's going on here, because I don't know what your code is supposed to do.

**Comment by jamesjrg** [comment]
Sorry, actuall, I can reproduce this without xunit at all. So not sure it is even a bug, maybe I just totally misunderstand something!

**Comment by jamesjrg** [comment]
Not an xunit issue
