### ISSUE TITLE
System.Runtime dependency in xunit.execution.DotNetCore

### ISSUE THREAD

**Issue by herecydev** [xunit/xunit#559]
The NetPlatform TFM for `xunit.execution.DotNetCore` has a dependency on `System.Runtime` (4.0.20). When I target dotnet and have xunit (beta4) as the only dependency it throws errors similar to the following:

![image](https://cloud.githubusercontent.com/assets/11328618/9517407/bbc0b052-4ca7-11e5-9be9-5255c58b537b.png)

I'm guessing that the incorrect version of `System.Runtime` is being pulled in, 4.0.0 instead of 4.0.20. Anything I'm doing wrong here?

Thanks

**Comment by onovotny** [comment]
What kind of project do you have, what are your dependencies, what is your target platform?

**Comment by herecydev** [comment]
I have an xproj targeting dotnet, with the only dependency on xunit.

**Comment by bradwilson** [comment]
- If you are using DNX beta6 or earlier: revert back to xUnit.net 2.1 beta 3.
- If you are using DNX beta7 or later: Use the latest build from our CI MyGet feed: https://www.myget.org/F/xunit/ (`xunit` will be an rc1 build, and `xunit.runner.dnx` will be a beta5 build)

**Comment by bradwilson** [comment]
Also, do not target `dotnet` with a `.xproj` today. It doesn't work the way you expect it to.

**Comment by herecydev** [comment]
Okay thanks, do you have any additional information about dotnet with xproj? Oren had some confusion to begin with, but his recent posts indicate that this should be the correct target.

**Comment by bradwilson** [comment]
For starters, `dotnet` is for class libraries only. If you're building an application, it needs to target one or more specific frameworks.

In addition, the `dotnet` target basically means "I intend to be compatible with anything which can link against System.Runtime". There is really no mechanism today to limit that to specific targets. If I were making a class library for use with ASP.NET today, it would be a two-target NuGet package which had separate binaries for `dnx451` and `dnxcore50`.

**Comment by herecydev** [comment]
Okay thanks, it is a class library I'm creating. I will hold off until more has been established. Thanks for the explanation.
