### ISSUE TITLE
Visual Studio runner should expose setting for ShadowCopy

### ISSUE THREAD

**Issue by rainersigwald** [xunit/xunit#560]
I'm working on porting MSBuild's unit tests to xunit (Microsoft/MSBuild#6), and I've run into a snag with VS integration.  Because we delay/open-source sign our assemblies, they fail to load in the test adapter, because the test adapter hardcodes `shadowCopy: true`, requiring full strong name signature checks.

Personally, I think I'd be fine with just setting shadowCopy to false in VS, period (as seems to have been done in #478), but if that's a bad idea, I'd love to see some configurability.

**Comment by bradwilson** [comment]
It cannot.

If you turn off shadow copying, the test DLLs will be locked until you shut down Visual Studio. This feature is 100% not compatible with the Visual Studio runner.

**Comment by rainersigwald** [comment]
Can you clarify what problems you expect to see?  I tried switching the hardcoded setting, and I was able to build, discover tests, run tests, rebuild, and delete the output directory in a command prompt outside of Visual Studio 2015, all with the same instance of VS open.  I also couldn't find any handles to the file open in Process Explorer.

**Comment by bradwilson** [comment]
Sorry, I was thinking about app domains. Turning that off permanently breaks builds.

Without shadow copy, you will have temporarily broken builds while tests are being discovered or executed.

**Comment by bradwilson** [comment]
This is enabled by the new Shadow Copy option in the configuration file (in commit 9b650f8).

The documentation pages will be updated before this ships in 2.1 RC 1:

http://xunit.github.io/docs/configuring-with-xml.html
http://xunit.github.io/docs/configuring-with-json.html

**Comment by mattzink** [comment]
I see that shadow copy is still hard-coded to true in another part of the VS runner:
https://github.com/xunit/visualstudio.xunit/blob/master/xunit.runner.visualstudio.testadapter/VsTestRunner.cs#L347

That expected?
