### ISSUE TITLE
Error communicating AppVeyor Build Worker API

### ISSUE THREAD

**Issue by JamesNK** [xunit/xunit#563]
I get an error when running xunit + DNX in AppVeyor: http://help.appveyor.com/discussions/problems/2882-error-communicating-appveyor-build-worker-api

> Exception: Error communicating AppVeyor Build Worker API: Could not load file or assembly 'System.Net.Requests, Version=3.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

xunit.runner.dnx.2.1.0-beta5-build159
coreclr

**Comment by bradwilson** [comment]
@JamesNK I don't know why it's not there, because it's clearly listed as a dependency of `xunit.runner.reporters`, which is a dependency of `xunit.runner.dnx`:

https://github.com/xunit/xunit/blob/4630f0df3682c374490ba27265c2267747592c89/src/xunit.runner.reporters.nuspec#L38

It might be worth enlisting some help of the DNX people to see why the dependency wouldn't be pulled in.

**Comment by JamesNK** [comment]
The build log is available in the page I linked to and System.Net.Requests is being restored.

It started breaking without any changes to the repo. The only change appears to be a new version of xunit.runner.dnx

https://ci.appveyor.com/project/JamesNewtonKing/newtonsoft-json/build/1.0.410
Installing xunit.runner.dnx.2.1.0-beta5-build156 - successful build

https://ci.appveyor.com/project/JamesNewtonKing/newtonsoft-json/build/1.0.413
Installing xunit.runner.dnx.2.1.0-beta5-build159 - failed build

**Comment by JamesNK** [comment]
I explicitly changed the xunit references to be what they were in the last successful build and that fixed it: https://ci.appveyor.com/project/JamesNewtonKing/newtonsoft-json/build/1.0.422

    "xunit": "2.1.0-rc1-build3118",
    "xunit.runner.dnx": "2.1.0-beta5-build156"

Obviously whatever has changed since then has introduced the bug.

**Comment by AlekseyMartynov** [comment]
@bradwilson 

I noticed that there are no DNX-compatible entries in System.Net.Requests 3.9.0 lib folder:

     Directory of C:\Users\am\.dnx\packages\System.Net.Requests\3.9.0\lib

    03.09.2015  00:47    <DIR>          .
    03.09.2015  00:47    <DIR>          ..
    03.09.2015  00:47    <DIR>          MonoAndroid10
    03.09.2015  00:47    <DIR>          MonoTouch10
    03.09.2015  00:47    <DIR>          net45
    03.09.2015  00:47    <DIR>          win8
    03.09.2015  00:47    <DIR>          wp80
    03.09.2015  00:47    <DIR>          wpa81
    03.09.2015  00:47    <DIR>          xamarinios10
    03.09.2015  00:47    <DIR>          xamarinmac20
    
Could this be the reason? Is it possible to use version 4.0?

**Comment by bradwilson** [comment]
Looks like I'm going to need to move to Profile111 for the reporter so that I can get access to `HttpClient`.

**Comment by bradwilson** [comment]
This appears to be fixed now in:

```
xunit 2.1.0-rc1-build3152
xunit.runner.dnx 2.1.0-beta5-build165
```

Please re-test and let me know if everything is working again for you. Sorry for the inconvenience.

**Comment by AlekseyMartynov** [comment]
#574 case works fine, both CLR and CoreCLR. Thank you.

**Comment by bradwilson** [comment]
@JamesNK Please verify (and close if solved). :)

**Comment by JamesNK** [comment]
Fixed!
