### ISSUE TITLE
Console runner hangs randomly during test discovery on Mono 4

### ISSUE THREAD

**Issue by mattzink** [xunit/xunit#564]
The console runner can hang indefinitely on the "discovering" step. In our case we have 7 test libraries, and xunit hangs randomly on a different test assembly each time, completing successfully only 10% of the time.

```
Discovering: Storage.Messaging.Test
Discovered:  Storage.Messaging.Test
Starting:    Storage.Messaging.Test
Finished:    Storage.Messaging.Test
Discovering: Storage.Utility.Test
(Hangs forever)
```

While there is a workaround to specify the -noappdomain flag, this brings along its own issues related to lack of test isolation, so it's not usable in all situations (such as tests that dynamically load assemblies)

xunit 2.1 beta 4
mono 4.2.0.179
Linux x64

**Comment by spboyer** [comment]
Having a similar issue when running the test, although it completes. it hangs upon completion.

**Comment by reppners** [comment]
Thank god I'm not the only one having this issue.



> Having a similar issue when running the test, although it completes. it hangs upon completion.

Exact same thing for me. When I locally execute the console runner it works, running the exact same script on a Jenkins CI server results in occasional freezes upon completion of one test assembly (having four test assemblies currently, sometimes it hangs after the first, sometimes after the last). Somehow it feels like the tests itself can have an influence on this behavior.


Sometimes running a single test or a subset of tests in visual studio/resharper has also the effect of the test runner not finishing even though the test code has finished.. Is there a relation between those two test runner behaviors?

**Comment by spboyer** [comment]
Solved.  There is a bug in Mono, you need to add the following to the command `-parallel none` and it will  complete.  This is not needed when running under coreclr, but not an issue if you keep it.  The complete command in the project.json file looks like this.

```
    "test": "xunit.runner.dnx -parallel none"
```

**Comment by reppners** [comment]
I should clarify that I'm running the tests on Windows 8.1 and use `-parallel none` from the start. What might be a problem though is that I am using the `xunit.console.x86.exe`-runner on a x64 system. 

Im testing multiple libraries, the majority being compiled with `Any CPU` but one with `x86`. Running the tests manually on a `x86` Windows has them running fine but on the other hand it doesn't happen always on the build server.. just too often.

**Comment by natemcmaster** [comment]
Seeing the same issue on OSX. Appears to be hung in XunitWorkerThread.

**Comment by bradwilson** [comment]
Please report Mono-specific issues to the Mono team, not us.

**Comment by natemcmaster** [comment]
@bradwilson although this might be a mono issue, could xunit workaround it?

**Comment by bradwilson** [comment]
You're welcome to investigate to see if you can find a workaround; we do not have the time.

**Comment by reppners** [comment]
So.. I'm experiencing this on Windows and our build server unit-test execution is basically unusable now. I suspect its some kind of threading issue because our unit-tests involve threads starting and stopping. We can't just stop to use threads in our unit-tests. How can we debug this?

**Comment by cottsak** [comment]
> Thank god I'm not the only one having this issue.

[I'm getting this on TeamCity](https://github.com/xunit/xunit/issues/709#issuecomment-200200591) and I've tried two different runners now:
* https://github.com/JetBrains/meta-runner-power-pack/tree/master/xUnit.net-dotCover
* https://github.com/carlpett/xUnit-TeamCity

I've also tried various versions of the console runner:
* 2.1.0
* 2.0.0
* 2.2.0-beta1

There must be some bug that's been present for some time I think.

**Comment by bradwilson** [comment]
Please re-open with a repro.
