### ISSUE TITLE
Add diagnostic message sink option for fixtures

### ISSUE THREAD

**Issue by nbarbettini** [xunit/xunit#565]
I have a test fixture that is shared via `ICollectionFixture<MyFixtureClass>`. Some of my unit tests inject `ITestOutputHelper` to output diagnostic information.

Is there any way to inject `ITestOutputHelper` into `MyFixtureClass`? I want to output log messages during construction and disposal of the fixture.

If I change the constructor:

``` chsarp
private readonly ITestOutputHelper output;

public MyFixtureClass(ITestOutputHelper output)
{
    this.output = output;
}
```

I get: 

> 'MyFixtureClass' must be a non-abstract type with a public parameterless constructor in order to use it as a parameter 'TFixture' in the generic type or method 'ICollectionFixture<TFixture>'

**Comment by bradwilson** [comment]
`ITestOutputHelper` is for tests. It's not for infrastructure or fixtures (both of which have longer lifetime than tests).

If you want output from your fixtures, and it's during a test, the test can pass its own injected `ITestOutputHelper` into the fixture. Alternatively, we could add a feature that lets you inject `IMessageSink` to send diagnostic messages to; that's available for infrastructure classes today, but not for fixtures.

**Comment by nbarbettini** [comment]
Got it, makes sense. I forgot to clarify what exactly I wanted to log; I updated my message. I specifically want to log stuff that's happening outside of the scope of a currently running test. `IMessageSink` would work perfectly if it's available for collection fixtures in some future release.

**Comment by bradwilson** [comment]
I've updated the title to reflect the feature request. :)

**Comment by nbarbettini** [comment]
Thanks @bradwilson!

**Comment by mikesigs** [comment]
+1

**Comment by salixzs** [comment]
Is there any plans for this? I was able to partially cover this by injecting ```ITestOutputHelper``` to Fixture, but it "goes away" if I want to use it in Dispose method with exception "There is no currently active test case".

**Comment by gitfool** [comment]
👍

**Comment by adamrodger** [comment]
+1

**Comment by MarcoRossignoli** [comment]
+1

**Comment by sinclairtarget** [comment]
+1!

**Comment by eriove** [comment]
I have the same need as @salixzs (i.e. getting diagnostic output in Dispose methods). Did you ever find a workaround?

**Comment by marcin-chwedczuk-cybervadis** [comment]
I am currently trying to write integration tests. One of my fixtures will be responsible for starting up a MongoDB server. I would like to output some log messages that e.g. server started and the connection string that can be used to connect to it. I need that for debug purposes. Unfortunately currently as stated above I cannot log anything from my fixture. 

One silly way that solves this problem is to store log messages inside `List<string>` and then write them to `ITestOutputHelper` at the start of every tests class (say in some `BaseIntegerationTest` class constructor), but this is clearly so ugly that I cannot even call it a workaround.

**Comment by eriove** [comment]
@marcin-chwedczuk-cybervadis while it is ugly it is still much better than nothing. Thanks!

**Comment by narendrachava** [comment]
+1

**Comment by bradwilson** [comment]
Added in #1705

**Comment by t03apt** [comment]
What is the estimate for releasing this feature?

I'd like to capture some diagnostic information in the DisposeAsync method of a Fixture. 
Is there a workaround for this?
```csharp
    public class TestCollection: IClassFixture<DbContext>
    {
        private readonly ITestOutputHelper _outputHelper;

        public TestCollection(DbContext dbContext, ITestOutputHelper outputHelper)
        {
            _outputHelper = outputHelper ?? throw new ArgumentNullException(nameof(outputHelper));
        }

        [Fact]
        public void TestSomething()
        {
            _outputHelper.WriteLine("TestSomething done.");
        }
    }

    public class DbContext : IAsyncLifetime
    {
        public Task InitializeAsync() => Task.CompletedTask;

        public Task DisposeAsync()
        {
            // How to capture logging messages from here?
            Console.WriteLine("Disposing some resources...");
            return Task.CompletedTask;
        }
    }
```
[source code](https://github.com/t03apt/xunit-logging/blob/master/Tests/TestCollection.cs)

**Comment by bradwilson** [comment]
It will be in 2.4 beta 2, which I'm hoping to release in the next few days.

**Comment by markusschaber** [comment]
IMessageSinkMessage is a rather "slim" interface - is there any documentation how to actually add data there?

**Comment by bradwilson** [comment]
It's a base type. Here are all the message interfaces: https://github.com/xunit/abstractions.xunit/tree/master/src/xunit.abstractions/Messages

**Comment by bradwilson** [comment]
Thank you for your valued feedback.

**Comment by t-l-k** [comment]
@bradwilson is this documented anywhere?

**Comment by mikerochip** [comment]
Wow, this conversation got hostile. Googling led me here. Users are experiencing pain. Pain leads to frustration. I don't think that's a good reason to get hostile or passive aggressive on either the user or maintainer side.

This still feels like an issue. It just feels weird and bad that there's no ergonomic way to see output from within a Fixture without the Test class settings its injected ITestOutputHelper on to the Fixture. I don't think injection of IMessageSink was the right solve here. The output doesn't show up in the same place as ITestOutputHelper and I think that's the desire, at least it is for me and I suspect most people that have +1 commented here were seeking this. At least in Rider, IMessageSink output doesn't show up in the output window that ITestOutputHelper uses - you have to open up the Diagnostic log to see IMessageSink output, so you have to stitch those things together yourself. On top of that, there is this issue https://github.com/xunit/xunit/pull/1705#issuecomment-610168901.

Again, the feedback here is that it feels bad to not be able to have Fixtures output to the same place as ITestOutputHelper. I'm still pretty new to xUnit so I'm not going to suggest a particular solution for fear of getting smacked down with a lack of knowledge.

**Comment by aap4ixx** [comment]
Hi. and what the result? do you have any silmple resolution on this issue?
Or any not simple example? 
Thanks.

**Comment by barecode** [comment]
While not directly documented, this does work as of 2.4.1

The capturing output page https://xunit.net/docs/capturing-output does not list IClassFixture as a supported class, but it is injected.

For example:
```
public class TestFixture: IDisposable
    {
        IMessageSink sink;

        public TestFixture(IMessageSink sink)
        {
            this.sink = sink;
            sink.OnMessage(new DiagnosticMessage("DIAG TEST CTOR"));
        }

        public void Dispose()
        {
            sink.OnMessage(new DiagnosticMessage("DIAG TEST DISPOSE"));
        }

        public void LogByTest(string expected, string actual)
        {
            sink.OnMessage(new DiagnosticMessage("DIAG TEST MSG"));
        }
    }
```
Does produce log entries (In Visual Studio 2019, its under Output -> Tests)
```
[xUnit.net 00:00:03.40] UnitTest: DIAG TEST CTOR
[xUnit.net 00:00:03.50] UnitTest: DIAG TEST MSG
[xUnit.net 00:00:03.52] UnitTest: DIAG TEST MSG
[xUnit.net 00:00:03.52] UnitTest: DIAG TEST MSG
[xUnit.net 00:00:03.53] UnitTest: DIAG TEST DISPOSE
```

**Comment by aap4ixx** [comment]
Hi " barecode".
I try implement you example to my autotest but i not understood how i can run you example.
In my test i use "[Fact]". and i not understood.
For example i have the same structure how user "t03apt" provide example.
Can you please more correct? :)

**Comment by barecode** [comment]
You need to tell xUnit what your class fixture is.
`public class TestCollection: IClassFixture<DbContext>`

**Comment by barecode** [comment]
> Hi " barecode".
> I try implement you example to my autotest but i not understood how i can run you example.
> In my test i use "[Fact]". and i not understood.
> For example i have the same structure how user "t03apt" provide example.
> Can you please more correct? :)
> 
> for example please my example:
> `public class TestCollection: IClassFixture
> {
> private readonly ITestOutputHelper _outputHelper;
> 
> ```
>     public TestCollection(DbContext dbContext, ITestOutputHelper outputHelper)
>     {
>         _outputHelper = outputHelper;
>     }
> 
>     [Fact]
>     public void TestSomething()
>     {
>         _outputHelper.WriteLine("TestSomething done.");
>     }
> }
> 
> public class DbContext: IDisposable
> {
>     IMessageSink sink;
> 
>     public DbContext(IMessageSink sink)
>     {
>         this.sink = sink;
>         sink.OnMessage(new DiagnosticMessage("DIAG TEST CTOR"));
>     }
> 
>     public void Dispose()
>     {
>         sink.OnMessage(new DiagnosticMessage("DIAG TEST DISPOSE"));
>     }
> 
>     public void LogByTest(string expected, string actual)
>     {
>         sink.OnMessage(new DiagnosticMessage("DIAG TEST MSG"));
>     }
> }`
> ```

You need to tell xUnit what your class fixture is.
`public class TestCollection: IClassFixture<DbContext>`

**Comment by aap4ixx** [comment]
Ou my mistake, sorry: I not copy all example:
It is full code and also not work :(

`    public class TestCollection: IClassFixture<DbContext>
    {
        private readonly ITestOutputHelper _outputHelper;

        public TestCollection(DbContext dbContext, ITestOutputHelper outputHelper)
        {
            _outputHelper = outputHelper;
        }

        [Fact]
        public void TestSomething()
        {
            _outputHelper.WriteLine("TestSomething done.");
        }
    }
    
    public class DbContext: IDisposable
    {
        IMessageSink sink;

        public DbContext(IMessageSink sink)
        {
            this.sink = sink;
            sink.OnMessage(new DiagnosticMessage("DIAG TEST CTOR"));
        }

        public void Dispose()
        {
            sink.OnMessage(new DiagnosticMessage("DIAG TEST DISPOSE"));
        }

        public void LogByTest(string expected, string actual)
        {
            sink.OnMessage(new DiagnosticMessage("DIAG TEST MSG"));
        }
    }`

**Comment by aap4ixx** [comment]
public class TestCollection: IClassFixture<DbContext>
    {
        private readonly ITestOutputHelper _outputHelper;

        public TestCollection(DbContext dbContext, ITestOutputHelper outputHelper)
        {
            _outputHelper = outputHelper;
        }

        [Fact]
        public void TestSomething()
        {
            _outputHelper.WriteLine("TestSomething done.");
        }
    }
    
    public class DbContext: IDisposable
    {
        IMessageSink sink;

        public DbContext(IMessageSink sink)
        {
            this.sink = sink;
            sink.OnMessage(new DiagnosticMessage("DIAG TEST CTOR"));
        }

        public void Dispose()
        {
            sink.OnMessage(new DiagnosticMessage("DIAG TEST DISPOSE"));
        }

        public void LogByTest(string expected, string actual)
        {
            sink.OnMessage(new DiagnosticMessage("DIAG TEST MSG"));
        }
    }

full code, but also not work...

**Comment by Amleto** [comment]
Also hitting the general problem of wanting output from a fixture, and also not seeing any output anywhere when using IMessageSink like aap4ix

**Comment by bradwilson** [comment]
Did you [enable diagnostic messages](https://xunit.net/docs/configuration-files#diagnosticMessages)?

**Comment by aap4ixx** [comment]
Hi, yes "diagnosticMessages": true," is enable.
But result the same...
I can't seem to get to see messages from MyFixtureClass (ICollectionFixture<MyFixtureClass>).
Or if you can provide simple example it will be perfect.

**Comment by abalaci** [comment]
@aap4ixx and @Amleto, was your configuration file enabling diagnostic messages actually being copied to the output folder? I initially thought I had a similar issue — that's how I ended up at the bottom of this thread — but then I realized my `xunit.runner.json` file wasn't being copied to the output folder during build (silly me).

Essentially, I ended up doing exactly as the docs said (https://xunit.net/docs/capturing-output#output-in-extensions and https://xunit.net/docs/configuration-files#file) and it all worked in the end.

**Comment by oising** [comment]
I have wasted hours trying to figure out how to simply inject ITestOutputHelper into my fixture class so my shared context (an Orleans Test Cluster) can log things, only to find out it's not possible (for reasons I'm not sure I understand.)

I think if people have been asking for this for 6 years, it might be time to just do it? ;)

**Comment by Simonl9l** [comment]
I'm new to xUnit, so the firehose is still bit crazy from a learning perspective.  So please excuse in advance if this is actually resoled, as I can't find anything.

It seem odd that the ability to "inject" `ITestOutputHelper` into fixtures is not available as it makes logical sense, such that it can be hooked into say Serilog via [serilog.sink.xunit](https://github.com/trbenning/serilog-sinks-xunit). It does seem the documentation was recently "[updated](https://github.com/xunit/xunit/issues/2218)" 

As @oising mentions this issue/need has been _discussed_ for 6+ years at the time.

It very unfortunate to have invested so much time in xUnit to run into this fundamental issue. Is there any kind of roadmap for xUnit - such that we'd understand if there are any plans to evolve this capability, and know that current time investment was worth it?

**Comment by abalaci** [comment]
Hi @Simonl9l -- just curious here, what's preventing you from using `IMessageSink`  in your fixtures?

**Comment by abalaci** [comment]
> Hi @Simonl9l -- just curious here, what's preventing you from using `IMessageSink` in your fixtures?

If it's just about using Serilog inside a fixture class, the XUnit sink [works with both](https://github.com/trbenning/serilog-sinks-xunit/blob/master/src/Serilog.Sinks.XUnit/XUnitLoggerConfigurationExtensions.cs) `ITestOutputHelper` and `IMessageSink` all the same. Just make sure your `xunit.runner.json` or `App.config` file is copied to the build output directory after enabling diagnostic messages -- see what I've written [above](https://github.com/xunit/xunit/issues/565#issuecomment-858792806), essentially.

**Comment by Simonl9l** [comment]
@abalaci yes it’s about using serilog in fixtures.

I’ve configured a collection fixture, but did not configure diagnostic messages…docs were not clear here…or I’m blind for looking.

thanks for followup! Will try tomorrow…

**Comment by Simonl9l** [comment]
@abalaci - so to confirm here is my `xunit.runner.json`

```json
{
  "$schema": "https://xunit.net/schema/current/xunit.runner.schema.json",
  "diagnosticMessages" : true
}
```

With switching to an IMessageSink, this now seems to work; but only get the logging output if I run `dotnet test` from a console, not in the Rider Unit Test UI. I also seem to need to have to have the `xunit.runner.visualstudio` package installed even though I'm only running form the command line or from Rider...

**Comment by RichardGaoF** [comment]
> @abalaci - so to confirm here is my `xunit.runner.json`
> 
> ```json
> {
>   "$schema": "https://xunit.net/schema/current/xunit.runner.schema.json",
>   "diagnosticMessages" : true
> }
> ```
> 
> With switching to an IMessageSink, this now seems to work; but only get the logging output if I run `dotnet test` from a console, not in the Rider Unit Test UI. I also seem to need to have to have the `xunit.runner.visualstudio` package installed even though I'm only running form the command line or from Rider...

Hi @Simonl9l  You could see the output if switch to Tests view in the Output window. 
![image](https://user-images.githubusercontent.com/25624410/135584490-3f1a3ff3-8ba7-4021-b9a0-566c2cc3ca39.png)
Not sure why it's so difficult to the xUnit team to clearly write a sample for the most frequently used IClassFixture(), instead of the ITestCaseOrderer, in their official website https://xunit.net/docs/capturing-output, while consumed each developer's much time to seek and read lots of articles from google result. I have to say it's fortunate enough to us to finally find such discussion from the articles-sea although it's so long, because I spent several days in seeking and reading various informal and incorrect articles before finding this today.   
In the page, they say "Visual Studio's output window contains a Tests tab which contains the output message...", but there is a dropdown list instead of tabs in the window at all.

**Comment by msiemens** [comment]
Regarding Rider, this seems to be missing in the IDE itself, see https://youtrack.jetbrains.com/issue/RSRP-482066/Support-IMessageSink-in-test-output. I think leaving a vote there would help increasing visibility for this issue at JetBrains
