### ISSUE TITLE
Unable to discover tests with latest xUnit beta

### ISSUE THREAD

**Issue by mellinoe** [xunit/xunit#566]
I'm in the process of updating the version of xUnit we are using in our tests in dotnet/corefx (https://github.com/dotnet/corefx), and am hitting an issue where no tests are discovered after updating to the latest beta version on NuGet (beta4-build3109). We are currently using beta3-build3029.

We are using a custom CoreCLR-based console runner, but I believe the relevant code is still identical to the version we forked in the official console runner. The runner program is located here:

https://github.com/dotnet/buildtools/blob/master/src/xunit.console.netcore/Program.cs#L287

Line 287 is basically where our discovery happens:

``` CSharp
using (var controller = new XunitFrontController(false, assembly.AssemblyFilename, assembly.ConfigFilename, assembly.ShadowCopy))
using (var discoveryVisitor = new TestDiscoveryVisitor())
{
    controller.Find(includeSourceInformation: false, messageSink: discoveryVisitor, discoveryOptions: discoveryOptions);
    discoveryVisitor.Finished.WaitOne();
...
```

_(this part is unchanged from the official console runner)_

We are running the program directly from a hosted CoreCLR instance. We aren't using dnx or anything else for these, although it should be roughly the same if you were to run the above in a DNX application. In beta3, the above code segment seemed to work correctly. Using beta4, however, no tests are discovered. Our test projects are fairly simple, just compiling against xunit.assert and xunit.core, both from the matching beta NuGet package. The only change I made was updating the references from beta3 -> beta4.

Are there any breaking changes that we need to take care of between beta3 and beta4? I see that there are a lot of changes in the source tree even since beta4 was released, especially around this area. Is it expected that another beta version may change this behavior again?

One thing that I think is relevant: in some tests that use a custom Fact-derived attribute, with its own TestDiscoverer, the runner is actually able to find those tests fine. But any tests that are only decorated with [Fact] or [Theory] are not discovered. This leads me to believe that the program is, for some reason, unable to locate the Fact/Theory discoverer classes, but is able to locate our custom discoverer. I see that the Fact attribute uses some weird syntax for labelling its discoverer, i.e.

``` CSharp
[XunitTestCaseDiscoverer("Xunit.Sdk.FactDiscoverer", "xunit.execution.{Platform}")]
```

If I had to throw a random guess out there, I'd guess that it's unable to determine which platform we are running on. I have verified that xunit.execution.DotNetCore.dll is next to our test assembly, and it does contain the FactDiscoverer, TheoryDiscoverer, etc. This part seems to be unchanged from beta3 -> beta4.

It may be that I am doing something wrong in my upgrade here. Let me know if there's anything unclear or if I have done something wrong / missed a step, or if you need more information.

**Comment by bradwilson** [comment]
The platform you're running on is dictated by the `xunit.runner.utility.*.dll` file that you're linked against (which I presume is DotNetCore).

There are some known issues with beta4 that might be hurting you. I'd try using the rc1 CI builds from https://www.myget.org/F/xunit/ and see if that makes things behave better.

**Comment by mellinoe** [comment]
We believe we narrowed down the change to this line here:

https://github.com/xunit/xunit/commit/4391bf9d18932e165a5ac824c286df7464d73430#diff-45874a413b654e20bf147b8b20cbbdf7R166

When Assembly.Load is called on xunit.execution.dotnetcore.dll, it fails because the assembly is unsigned. For our custom signed assembly, it works, and that's why our custom attributes and their discoverers are being loaded properly.

It seems that this is the root cause of it. Is this code path used in your CoreCLR DNX runner? Perhaps there is something different in how our program is hosting CoreCLR, or perhaps this path isn't exercised in the DNX runner.

**Comment by MaxWilson** [comment]
Mellinoe, thanks for that post. I'm trying to get Xunit working on a new Universal App and couldn't figure out why the Xunit directions weren't working for me. After reading your post I rolled back to beta3 and that resolved my issue. Thank you!

**Comment by mellinoe** [comment]
By the way, it may be that this code is working in DNX because they are using a custom AssemblyLoadContext, which may be intercepting the call at some point and resolving the assembly specially. I haven't dug down into the relevant code on their side, but I know they do use a custom loading context.

**Comment by bradwilson** [comment]
@mellinoe Actually, the original addition of the Version there was at the DNX team's request. Specifying a version shouldn't mandate that the assembly be signed (it doesn't on any other platform).

**Comment by mellinoe** [comment]
> Specifying a version shouldn't mandate that the assembly be signed (it doesn't on any other platform).

On CoreCLR, specifying a version actually allows you to load an UNsigned assembly (including xunit.execution.\*). Calling Assembly.Load with a null version only works for loading signed assemblies on CoreCLR, and this is the default behavior for SerializationHelper now. I suspect that the reason this works for DNX is that they use a custom AssemblyLoadContext. So loading xunit.execution.\* will always fail on CoreCLR now (minus custom load contexts) because it is unsigned, and a version is not specified.

Does that make sense? I think @MaxWilson's comment above would indicate that this is also occurring in Universal Apps, which run on CoreCLR but don't use a custom load context.

**Comment by bradwilson** [comment]
@MaxWilson's problems can't be related to specifying a Version, because we were already doing that in Beta 3. I believe his UWP problems will be solved with RC 1.

**Comment by bradwilson** [comment]
RC 1 is now out. Please re-test with the latest build.

**Comment by mellinoe** [comment]
I actually filed this bug against CoreCLR, and it has been fixed already: https://github.com/dotnet/coreclr/issues/1477. I will update and/or close this issue when we update to the latest version in our repo and verify that everything works as expected.

**Comment by bradwilson** [comment]
This is a dead runner.
