### ISSUE TITLE
Test fail on android with Assert.ThrowsAsync

### ISSUE THREAD

**Issue by krt-** [xunit/xunit#569]
I'm testing async method which throws TaskCanceledException
```
 Assert.ThrowsAsync<OperationCancelledException>(async () => await SomeAsyncMethod());
```
Everything is fine when I test on windows or windows phone. But when I run it on Xamarin Android test fails with:
```
[FAIL] ThrowsTest : Assert.Throws() Failure
Expected: typeof(System.OperationCanceledException)
Actual:   typeof(System.Threading.Tasks.TaskCanceledException): A task was canceled.
```
What am I missing? TaskCanceledException derives from OperationCanceledException

**Comment by bradwilson** [comment]
`ThrowsAsync` verifies exact exceptions. I think what you want is `ThrowsAnyAsync`.

**Comment by krt-** [comment]
Thank you
