### ISSUE TITLE
Need DNX beta 7 release

### ISSUE THREAD

**Issue by tillig** [xunit/xunit#570]
I'm having limited success with beta 7 xunit.

I've tried the current NuGet pre-releases of xunit:

- xunit 2.1.0-beta4-build3109
- xunit.runner.dnx 2.1.0-beta4-build134

Using these I get:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xunit.Runner.Dnx.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
```

No tests are executed.

I've tried a magic combination that I had working under beta 6, too:

- xunit 2.1.0-beta4-build3075
- xunit.runner.dnx 2.1.0-beta4-build125

Under beta 7 I get the same NullReferenceException.

I've tried to use one of the xunit MyGet builds that targets beta 7 and that works... until I want to try to release the latest version and allow people to be able to build the source.

The problem is that all the xunit MyGet builds need dependencies like "1.0.0-beta7-12345" (the way the ASP.NET pre-pre-releases are numbered) but the actual public NuGet pre-releases are "1.0.0-beta7",,, which comes semantically _before_ the dependencies referenced by xunit.

Which means... unless everyone is building against the pre-pre-releases, I'm stuck.

Is there a MyGet build that'll work with the released beta 7? If not, can we get one? (Or, better, a fresh beta 7 compatible push to NuGet?)

**Comment by bradwilson** [comment]
Yes, there is a MyGet build on https://www.myget.org/F/xunit/ (use a `-rc1-*` build for core xUnit.net packages, and a `-beta5-*` build for `xunit.runner.dnx`).

If all goes well, an official build will be out this weekend.

**Comment by jltrem** [comment]
Similiarly, I'm migrating from vNext beta6 to beta7.  Using the xunit.net dependencies:
```
        "xunit": "2.1.0-rc1-build3118",
        "xunit.runner.dnx": "2.1.0-beta5-build159",
```

**Comment by bradwilson** [comment]
Your version of `xunit` is out of date. It's best to use wildcards:

```
"xunit": "2.1.0-rc1-*",
"xunit.runner.dnx": "2.1.0-beta5-*"
```

If you insist on using build numbers, the latest (as of today) are `2.1.0-rc1-build3143` and `2.1.0-beta5-build159`. But please don't. :)

**Comment by tillig** [comment]
I've noticed that wildcards can sometimes get a little cranky during the move from the pre-pre-release (MyGet aspnetmaster or aspnetvnext) to pre-release (NuGet). I think once the feeds stop shifitng around it'll be more amenable to wildcards. When I get done shipping for beta 7 and start work on beta 8, for example, I'll go back to wildcards.

**Comment by tillig** [comment]
We were able to get things working using wildcards for xunit but specific versions for other dependencies.

Still might be good to get a beta 7 build out, so I'll leave the issue open at your discretion.

**Comment by bradwilson** [comment]
Planning to make it happen this weekend, so I'll close this now.
