### ISSUE TITLE
.NET Native: Theories fail to enumerate correctly

### ISSUE THREAD

**Issue by onovotny** [xunit/xunit#571]
When using xunit with .net native, I get some weird behavior. Needs investigation:

Theories don't enumerate correctly.
![2015-09-02_16-34-59](https://cloud.githubusercontent.com/assets/1427284/9648105/694bf416-51b2-11e5-9ff9-be91214085c7.png)

To repro, use the test.xunit.runner.uwp from the devices project and run in release mode. You'll see two test assemblies. In the first one there should be three theories (1, 2, 3). Works in debug, fails in release.

**Comment by bradwilson** [comment]
Closing as external.
