### ISSUE TITLE
.NET Native: Error message is wrong

### ISSUE THREAD

**Issue by onovotny** [xunit/xunit#572]
Needs investigation.

Use test.xunit.runner.uwp from the devices project. Run tests then go to the first test assembly and the first test.

In debug mode, I see this correct output:
![2015-09-02_16-36-18](https://cloud.githubusercontent.com/assets/1427284/9648131/bca62aaa-51b2-11e5-8ac9-57e6cfe05e58.png)

In release mode, I see this:
![2015-09-02_16-34-38](https://cloud.githubusercontent.com/assets/1427284/9648134/c6681968-51b2-11e5-83dc-d374644cc542.png)

For some weird reason, it's returning the results for a completely different test.

**Comment by onovotny** [comment]
The bad call stack seems related to the Optimize Code option.
See http://blogs.msdn.com/b/visualstudioalm/archive/2015/07/29/debugging-net-native-windows-universal-apps.aspx

If I create a profile/uncheck the Optimize code, then I get a better callstack:
![2015-09-03_10-33-16](https://cloud.githubusercontent.com/assets/1427284/9661111/3db02eec-5227-11e5-8c44-263943e96a5f.png)

**Comment by bradwilson** [comment]
Closing as external.
