### ISSUE TITLE
Add ability to replace default FactDiscoverer & TheoryDiscoverer

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#573]
An assembly-level override of the default FactDiscoverer will allow people to customize the behavior of [Fact] without needing their own custom attribute (just to place the discoverer on).

**Comment by bradwilson** [comment]
Closed for age.

**Comment by malylemire1** [comment]
You could check for metadata and override default discoverer 

```
[MetadataType(typeof(FactAttributeMetadata))]
public partial class FactAttribute { }

[XunitTestCaseDiscoverer("MyNamespace.MyDiscoverer", "MyDiscovererAssembly")]
public partial class FactAttributeMetadata
{
}
```
