### ISSUE TITLE
DNX: AppVeyor reporter seems broken (execution hangs after 1st test)

### ISSUE THREAD

**Issue by AlekseyMartynov** [xunit/xunit#574]
xunit.runner.dnx.2.1.0-beta5-build159
xunit.2.1.0-rc1-build3143
dnx-clr-win-x86.1.0.0-beta7

Setting `APPVEYOR_API_URL` env var to any invalid URL helps.
Cannot check CoreCLR because of #563

**Comment by AlekseyMartynov** [comment]
Sample:
https://github.com/AlekseyMartynov/xunit-574
https://ci.appveyor.com/project/AlekseyMartynov/xunit-574

**Comment by bradwilson** [comment]
Dup #563
