### ISSUE TITLE
AssemblyRunner enhancement: separate discovery and execution

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#578]
AssemblyRunner's simplified API is good for brain-dead runners, but it could be enhanced just slightly to allow separated discovery and execution, for GUI-style runners.

**Comment by onovotny** [comment]
While it's no doubt useful to have a separated discovery and execution, I might suggest that anyone wanting to implement GUI runner start with the devices project and its ViewModels as it's pretty much all done.

https://github.com/xunit/devices.xunit/tree/master/src/xunit.runner.viewmodels

Adding additional GUI "head" projects is very easy at this point.

**Comment by bradwilson** [comment]
Closed for age.
