### ISSUE TITLE
Add support for BeforeAfterTestAttributes to take fixtures in constructor args

### ISSUE THREAD

**Issue by AArnott** [xunit/xunit#581]
I have a test fixture that creates state that is shared by many tests and test classes, and must also be associated with a test collection. This shared state is _not_ immutable (and no, this can't be fixed), so it must be reset between each test.  Today, each test class has these responsibilities:
1. Apply `[MyCollection]` to the test class.
2. Implement `IClassFixture<SharedState>` and `IDisposable`
3. Define a constructor that takes `SharedState` as a parameter
4. Within the constructor, call `sharedState.Start()`
5. Within `Dispose`, call `sharedState.Stop()`

That's quite a bit of boilerplate code across every test class. And there's a high risk that some test class will leave out one of these requirements by accident, thereby leaving state corrupted for itself or other tests.

My goal is for the test class to be absolved of responsibility for all but the first requirement to apply the `[MyCollection]` attribute. With #468 I hoped that the `BeforeAfterTestAttribute` being on the `MyCollectionAttribute` class would make it possible. But the `BeforeAfterTestAttribute needs to itself be able to fulfill the rest of the above requirements on behalf of the test class. 

Of course the attribute should have a default constructor so that it can be used on the test class. My proposal is that I can add another constructor that takes a test fixture, like so:

``` csharp
[CollectionDefinition(Collection)]
[MockedVSAutoSession]
public class MockedVS : ICollectionFixture<GlobalServiceProvider>, ICollectionFixture<MefHosting>
{
    public const string Collection = "MockedVS";

    private class MockedVSAutoSessionAttribute : BeforeAfterTestAttribute, IClassFixture<GlobalServiceProvider>
    {
        private GlobalServiceProvider sp;

        public MockedVSAutoSessionAttribute() { }

        public MockedVSAutoSessionAttribute(GlobalServiceProvider sp)
        {
            this.sp = sp;
        }

        public override void Before(MethodInfo methodUnderTest)
        {
            sp.Start();
        }

        public override void After(MethodInfo methodUnderTest)
        {
            sp.Reset();
        }
    }
}
```

As [discussed on slack](https://xunit.slack.com/archives/general/p1441427348000214).

**Comment by bradwilson** [comment]
We will discuss this for 2.2, but to be clear: these cannot be constructor arguments, due to the way that .NET creates attributes.

**Comment by AArnott** [comment]
Thanks. I'm curious why they can't be constructor arguments though. I thought an attribute is just another class, if you write code to instantiate them. I know you can't *call* constructors using the `[MyAttribute(new object())]` syntax except where the arguments are instances of a very limited set of types. But as I'm proposing the attribute constructor with extra parameters be called by xunit and not used in the attribute decorator syntax I would think it would work.
That said, I don't really care so much how you manage it. I'm just curious.

**Comment by bradwilson** [comment]
Closed for age.
