### ISSUE TITLE
Add support for <AssemblyName>.xunit.runner.json

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#582]
This can be helpful when many test projects are placed into a single output folder (f.e., with the device runner).

**Comment by onovotny** [comment]
For reference, this is the device runner logic for this:
https://github.com/xunit/devices.xunit/blob/master/src/xunit.runner.viewmodels/DeviceRunner.cs#L167-L203

https://github.com/xunit/devices.xunit/blob/master/src/xunit.runner.android/PlatformHelpers.cs#L17-L27
