### ISSUE TITLE
"xunit.abstractions 2.0.0 is not compatible with DNXCore,Version=v5.0"

### ISSUE THREAD

**Issue by DixonDs** [xunit/xunit#587]
This is the error I get when I try to build some solutions from https://github.com/dotnet/corefx in Visual Studio 2015. Not sure if it is an actual issue in xUnit though, the whole DNX concept is new for me.

**Comment by bradwilson** [comment]
Unfortunately, this is a bug in the "modern PCL" tooling in Visual Studio 2015. If you uncheck the "DNX Core 5.0" target on the modern PCL properties, the compiler error will go away. It'll still target all the same libraries and run on DNX Core 5.0 without issue.

I believe they will be fixing this issue with the first service pack.

**Comment by shawnwildermuth** [comment]
I'm seeing this on new RC2 builds. I'm restoring with 'dotnet restore'. Here is my project.json if you see something magical:

```
{
  "version": "1.0.0-*",
  "description": "MetaWeblog.Tests Class Library",
  "authors": [ "shawn" ],
  "buildOptions": {
    "warningsAsErrors": true,
    "xmlDoc": false
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-*"
    },
    "xunit": "2.1.0-rc2-*",
    "dotnet-test-xunit": "1.0.0-rc2-*",
    "WilderMinds.MetaWeblog": { "target": "project" },
    "Microsoft.AspNetCore.TestHost": "1.0.0-rc2-*",
    "System.Xml.XDocument": "4.0.11-rc2-*"
  },

    "testRunner": "xunit",

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.4"
      ]
    }
  }
}
```

**Comment by onovotny** [comment]
Until xUnit's packages are updated for the `netstandard` tfm, you'll need to use an `import` statement to tell NuGet that it's compatible:
https://github.com/Humanizr/Humanizer/blob/dev/src/Humanizer.Tests.DotNet/project.json#L26-L29

**Comment by shawnwildermuth** [comment]
Ah, let me try that. But I guess I still don't understand how the import stuff works. Anyone have a writeup on it?

**Comment by onovotny** [comment]
I don't know where the docs are, it's probably somewhere, but it's just an array of TFM's that NuGet should consider compatible when looking at your dependencies. It's an "I know better than you" escape hatch.

**Comment by shawnwildermuth** [comment]
I got it working, thanks...still trying to get my head around the import stuff but at least I'm past it for now.

**Comment by bradwilson** [comment]
Although PCLs are typically technically compatible, the build system doesn't know that and must be told so. Why that logic isn't just built in is a good question. :-p
