### ISSUE TITLE
Programmatically get traits

### ISSUE THREAD

**Issue by MichaelLogutov** [xunit/xunit#588]
I need to enforce developers to decorate tests with trait "Category=IntegrationTests" if they used internal method, that performs restoring of test database. We currently using MSTests and it's quite simple to do - you get call stack of the current method, find the one that has TestMethod attribute, get all CategoryAttribute instances and check if there is one with "IntegrationTests" as a name.

In xUnit I can get TraitAttribute programmatically but I can't get actual name and value from it, because the instance of TraitAttribute does not stores parameters passed to it's constructor. Is there a way to get traits from the method programmatically?

**Comment by bradwilson** [comment]
It's even more complicated than you think, because `TraitAttribute` is not the sole source of traits; any attribute which implements ITraitAttribute can be a potential source of trait information. Getting this information requires several levels of indirection, so I'm going to make a `TraitHelper` class which can be used to get this information.

**Comment by MichaelLogutov** [comment]
That would be awesome. Thank you.

**Comment by MichaelLogutov** [comment]
Sorry to bring this up again, but I've just tried xunit version 2.1.0 with this test:

    [Fact, Trait ("Category", "Abc")]
    public void Test ()
    {
        // arrange
        var call_stack = GetCallStackMethods ();


        // act
        var xunit_categories = call_stack.SelectMany (x => TraitHelper.GetTraits ((MethodInfo) x))
                                            .Where (x => x.Key == "Category")
                                            .Select (x => x.Value);


        // assert
        Assert.Equal (xunit_categories, new[] { "Abc" });
    }


    public static IEnumerable<MethodBase> GetCallStackMethods ()
    {
        var stack_frames = new StackTrace ().GetFrames ();

        if (stack_frames != null)
            return stack_frames.Select (x => x.GetMethod ());

        return new[] { new StackFrame ().GetMethod () };
    }


And I've got this exception:

    System.TypeLoadException: Could not load type 'Xunit.Sdk.TraitHelper' from assembly 'xunit.execution.desktop, Version=99.99.99.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'.
       at Bug.Tests.<Test>b__0(MethodBase x)
       at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at Xunit.Sdk.AssertEqualityComparer`1.CheckIfEnumerablesAreEqual(T x, T y) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\Sdk\AssertEqualityComparer.cs:line 100
       at Xunit.Sdk.AssertEqualityComparer`1.Equals(T x, T y) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\Sdk\AssertEqualityComparer.cs:line 75
       at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\EqualityAsserts.cs:line 34
       at Xunit.Assert.Equal[T](IEnumerable`1 expected, IEnumerable`1 actual) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\CollectionAsserts.cs:line 194
       at Bug.Tests.Test() in C:\My\Bug (xUnit GetTraits)\Bug\Tests.cs:line 26


Am I supposed to install some package other than "xunit" ?

**Comment by MichaelLogutov** [comment]
Also, would you please change parameter to MethodBase?

**Comment by bradwilson** [comment]
> `System.TypeLoadException: Could not load type 'Xunit.Sdk.TraitHelper' from assembly 'xunit.execution.desktop, Version=99.99.99.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'`

Are you running with a local build? That version number should only be in use when locally compiled.

**Comment by MichaelLogutov** [comment]
No, I've created empty project and installed only xunit package.
