### ISSUE TITLE
How can I get TestContext for xUnit?

### ISSUE THREAD

**Issue by SetTrend** [xunit/xunit#594]
I'm trying to read and update a local test file in my tests. For this I need to copy a file from within my test project to the currently running test context's directory.

How can I get access to the current TestContext with xUnit?

**Comment by bradwilson** [comment]
There is no TestContext object in xUnit.net.

If you want the location of your test assembly, you can use [Assembly.GetExecutingAssembly().CodeBase](https://msdn.microsoft.com/en-us/library/system.reflection.assembly.codebase(v=vs.110).aspx).

**Comment by MisterSneaky** [comment]
Update: In the newer versions of xUnit, you will need Assembly.GetExecutingAssembly().Location

**Comment by bradwilson** [comment]
Also worth mentioning that we're shipping a TestContext in v3. https://github.com/xunit/xunit/blob/main/src/xunit.v3.core/TestContext.cs

**Comment by markus-codechefs** [comment]
> Also worth mentioning that we're shipping a TestContext in v3. https://github.com/xunit/xunit/blob/main/src/xunit.v3.core/TestContext.cs

But when is V3 shipping? :)
