### ISSUE TITLE
Provide a data source attribute at TestFixture Level

### ISSUE THREAD

**Issue by agray** [xunit/xunit#597]
Gallio MbUnit supports the following syntax on the TestFixture attribute:

```
[TestFixture, Factory(typeof(MyFactory), "MethodInMyFactoryThatReturnsIEnumerable")]
public class MyTestFixtureClass {
    public MyTestFixtureClass(MyFactory factory) {
        //Do stuff
    }
}
```

For every item in the IEnumerable returned by "MethodInMyFactoryThatReturnsIEnumerable" the MyTestFixtureClass constructor is called.

As far as I've been able to determine so far, while XUnit can do factories at the [Fact] level it does not support factories at the "[TestFixture]" (or XUnit equivalent) level.

If this is supported, could you please provide a C# example of how to achieve this desired behaviour in XUnit.

**Comment by agray** [comment]
@bradwilson: Could you please advise the status if this issue 

What do the labels "[a] dnx.xunit" and "[a] xunit" mean?

**Comment by bradwilson** [comment]
[a] = Affects (which project this impacts)

**Comment by agray** [comment]
Thanks Brad,  Does XUnit have a roadmap?  Could this issue be included on said roadmap?

**Comment by bradwilson** [comment]
> Does XUnit have a roadmap?

We do not.

**Comment by agray** [comment]
Thanks Brad. Could you advise how the project prioritises issues?
