### ISSUE TITLE
console slow when running -teamcity

### ISSUE THREAD

**Issue by ilivewithian** [xunit/xunit#601]
I have an assembly with about 2,500 tests, when I simply run `xunit.console.exe assembly.dll` I see a run time of about 15 seconds, when I run `xunit.console.exe myassembly.dll -teamcity` this jumps to 55 seconds. I don't see a similar performance degradation when running `-appveyor`

Why this significant discrepancy?

**Comment by ilivewithian** [comment]
> Why this significant discrepancy?

PEBKAC, that's why

**Comment by kvarv** [comment]
@ilivewithian Would you like to elaborate?

**Comment by ilivewithian** [comment]
I forget exactly what I was doing, but it was user error.
