### ISSUE TITLE
vsTestRunner 2 : File not found

### ISSUE THREAD

**Issue by ghalaax** [xunit/xunit#602]
Hi !

We are trying to use the vstest runner v2 for xunit (nuget package 2.0.1).
Our tests projects are mixed between mstests and xunit.net tests, and we give a list of assembly filenames to the vstest.console.exe.

It appears that this error is showing : 

Error: An exception occurred while invoking executor 'executor://xunit/VsTestRunner2': File not found: relative path to test assembly.dll
Parameter name: assemblyFileName

Do you have any ideas of what can cause this ?

If you need more information, feel free to ask it, I'll comunicate it as much as I can.

Cheers,

PS: thanks for your hard work on this awesome framework :)

**Comment by bradwilson** [comment]
Well, is the DLL in the location that it should be in? That error message you're getting implies that it can't find the test assembly on disk.

**Comment by ghalaax** [comment]
Hello !

Yes, the files are on the disk, the issue occurs when I give the runner relative paths to assemblies. 
Then some of the assemblies are found, and other aren't.

Note that it works with absolute paths.

Cheers,

**Comment by bradwilson** [comment]
Relative paths work with our runners (like `xunit.console.exe`), so my guess is there is something going on inside of the `vstest.console.exe` that is causing the current directory to be changed before we're given the assembly, and as such, it appears that relative paths are not supported with `vstest.console.exe`.

**Comment by bradwilson** [comment]
Please re-open with a repro.
