### ISSUE TITLE
VSTestRunner FullyQualifiedName filtering doesn't work with multiple tests of the same name

### ISSUE THREAD

**Issue by sbanni** [xunit/xunit#603]
@onovotny In VsDiscoveryVisitor.cs when creating a new test case that has multiple entries, the fully qualified name gets set to unique name like so:
```csharp
visitor.TestCases.GroupBy(tc => $"{tc.TestMethod.TestClass.Class.Name}.
{tc.TestMethod.Method.Name}").SelectMany(group => group.Select(testCase =>
 VsDiscoveryVisitor.CreateVsTestCase(source, discoverer, testCase,
     forceUniqueNames: group.Count() > 1,
                                                                                                              
var uniqueName = forceUniqueNames ? $"{fqTestMethodName} ({xunitTestCase.UniqueID})" : fqTestMethodName;
```
The problem is that there is no way to filter a specific test case off of FullyQualifiedName as it ends up being something like MyTest (0a0asd012390asda) which will get filtered out.

**Comment by bradwilson** [comment]
Unfortunately, there's not much we can do here. The unique name requirement comes from Visual Studio, and unfortunately, they didn't offer any kind of differentiate between a unique identifier vs. the named used to filter tests.

**Comment by sbanni** [comment]
Is there any reason we can't filter the list first then put the unique names on them?
