### ISSUE TITLE
build.sh is broken

### ISSUE THREAD

**Issue by ermshiperete** [xunit/xunit#607]
Trying to build by running ./build.sh on Linux results in `Directory '$HOME/Develop/xunit/xunit.xbuild.sln' not found.`

**Comment by bradwilson** [comment]
I just uploaded a fix for this.

However, `build.sh` is still not functional, because neither NuGet 3.x package restore nor C# 6 features will work on Mono right now.

**Comment by kostrse** [comment]
Faced the similar problem, thanks for information.

OS X with Mono 4.0.4:
```
~/Dev/xunit $ ./build.sh 
Restoring NuGet packages...
MSBuild auto-detection: using msbuild version '4.0' from '/Library/Frameworks/Mono.framework/Versions/4.0.4/lib/mono/4.5'.
Error parsing solution file at /Users/user1/Dev/xunit/xunit.vs2015.sln: Could not load type 'Microsoft.Build.Construction.SolutionParser'.
```

BTW, maybe switch to Paket?
It won't solve the issue with C# 6, but at least a much better (and cross-platform) package manager.

**Comment by bradwilson** [comment]
> BTW, maybe switch to Paket?

No.

**Comment by ErikSchierboom** [comment]
I had the same problem and was able to fix it by referencing Mono 3.3.0 in the `build.sh` file. Should I send a PR?

**Comment by bradwilson** [comment]
Sure. Thanks!

**Comment by akoeplinger** [comment]
@ErikSchierboom do you mean NuGet 3.3? Cause Mono 3.3 didn't have any C#6 features.

I am able to compile xunit with a recent Mono (i.e. from source) with these changes: https://github.com/akoeplinger/xunit/commit/cc0c8743d47b377fbf3d3bcb850cea8d652c037d.

**Comment by onovotny** [comment]
I wouldn't recommend mono 3.x anyway as there are major issues with deadlocks. Mono 4 does support C#6 syntax:
http://www.mono-project.com/docs/about-mono/releases/4.0.0/

**Comment by onovotny** [comment]
As far as those specific changes in https://github.com/akoeplinger/xunit/commit/cc0c8743d47b377fbf3d3bcb850cea8d652c037d, I can suggest two things.

1.  the download for nuget should be `https://dist.nuget.org/win-x86-commandline/latest/nuget.exe`. That will always get the latest version.
2.  For the reference generator targets, I'd love a PR to the targets file itself: https://github.com/onovotny/ReferenceGenerator/blob/master/src/ReferenceGenerator/NuSpec.ReferenceGenerator.targets that makes it work on mono. Probably something along the lines with an if unix, call mono blah.

**Comment by ErikSchierboom** [comment]
Doh, I meant NuGet 3.3 of course. The relevant NuGet issue can be found here: https://github.com/NuGet/Home/issues/1543. Roslyn had the [same issue](https://github.com/dotnet/roslyn/issues/7084). The [PR](https://github.com/xunit/xunit/pull/706) has been sent.

**Comment by ErikSchierboom** [comment]
@onovotny I'll try and get it running on Mono. See [this issue](https://github.com/onovotny/ReferenceGenerator/issues/16). Not even closely a Mono expert though, so don't get your hopes up too high ;)

**Comment by bradwilson** [comment]
This file is no longer part of the project.
