### ISSUE TITLE
[Question] ITestOutputHelper 

### ISSUE THREAD

**Issue by XcoderTeam** [xunit/xunit#608]
Hi,

Following the documentation on this below link.
http://xunit.github.io/docs/capturing-output.html

I'm using 

```
"xunit": "2.1.0-rc1-*",
"xunit.runner.dnx": "2.1.0-beta5-*",
"xunit.runner.visualstudio": "2.1.0-beta5-*"
```

![image](https://cloud.githubusercontent.com/assets/1622986/10123261/e9227d22-6567-11e5-9606-46505d757cc0.png)

![image](https://cloud.githubusercontent.com/assets/1622986/10123263/f5b15298-6567-11e5-8dd0-130ad6253d01.png)

I didn't see any output on VS Test Explorer.
Is there anything I miss out?

**Comment by bradwilson** [comment]
The issue here is Visual Studio, not xUnit.net. We send them the output for all tests, passing or otherwise, and they choose whether or not to show that output.

**Comment by michaelvolz** [comment]
Are there any news to this issue? I really would love to the the logging information in my asp.net 5 tests.

**Comment by bradwilson** [comment]
You should ask the ASP.NET team. They control this, not us.

**Comment by michaelvolz** [comment]
Done, thanks.
