### ISSUE TITLE
Test discovery order is meaningful when filtering tests to a specific trait with vstest.console /TestCaseFilter

### ISSUE THREAD

**Issue by htuomola** [xunit/xunit#610]
(Forked from https://github.com/xunit/xunit/issues/180#issuecomment-143749585)

Filtering by trait works fine when testing a single assembly with traits in it. However, when testing multiple assemblies in which some contain traits, the test discovery fails depending on the order of assemblies that are provided (discovered).

The error I get is: "Error: [xUnit.net 00:00:00.5282718] test.harness.notraits: Exception discovering tests: No tests matched the filter because it contains one or more properties that are not valid (TestCategory). Specify filter expression containing valid properties (DisplayName, FullyQualifiedName) and try again."

This can be reproduced by extending the current tests and adding a second test harness project which doesn't declare any traits:

``` csharp
namespace test.harness.notraits
{
    public class Class1
    {
        [Fact]
        public void ThisIsATest()
        {
            Assert.True(true);
        }
    }
}
```

```
> vstest.console.exe test.harness.notraits\bin\debug\test.harness.notraits.dll test.harness\bin\debug\test.harness.dll /testadapterpath:xunit.runner.visualstudio.testadapter /TestCaseFilter:"TestCategory!=Slow"

Information: [xUnit.net 00:00:00.2667248]   Discovering: test.harness.notraits
Error: [xUnit.net 00:00:00.5282718] test.harness.notraits: Exception discovering tests: No tests matched the filter because it contains one or more properties that are not valid (TestCategory). Specify filter expression containing valid properties (DisplayName, FullyQualifiedName) and try again.
Information: [xUnit.net 00:00:00.5310341]   Discovered:  test.harness.notraits
Information: [xUnit.net 00:00:00.7324201]   Discovering: test.harness (app domain = on [shadow copy], method display = ClassAndMethod)
Information: [xUnit.net 00:00:00.8930525]   Discovered:  test.harness (running 2 test cases)
Information: [xUnit.net 00:00:00.9660271]   Starting:    test.harness.notraits
Information: [xUnit.net 00:00:01.1437392]   Finished:    test.harness.notraits
Information: [xUnit.net 00:00:01.3423933]   Starting:    test.harness (parallel test collections = on, max threads = 4)
Information: [xUnit.net 00:00:01.5282571]   Finished:    test.harness
Passed   test.harness.Tests.ThisIsATest
Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Failed.
```

Whereas the same command with DLLs in different order works fine (and executes all expected tests):

```
>vstest.console.exe test.harness\bin\debug\test.harness.dll test.harness.notraits\bin\debug\test.harness.notraits.dll /testadapterpath:xunit.runner.visualstudio.testadapter /TestCaseFilter:"TestCategory!=Slow"
Microsoft (R) Test Execution Command Line Tool Version 14.0.23107.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
Information: [xUnit.net 00:00:00.2771416]   Discovering: test.harness (app domain = on [shadow copy], method display = ClassAndMethod)
Information: [xUnit.net 00:00:00.5611299]   Discovered:  test.harness (running 2 test cases)
Information: [xUnit.net 00:00:00.7727458]   Discovering: test.harness.notraits
Information: [xUnit.net 00:00:00.9122225]   Discovered:  test.harness.notraits
Information: [xUnit.net 00:00:01.1199381]   Starting:    test.harness (parallel test collections = on, max threads = 4)
Information: [xUnit.net 00:00:01.2835729]   Finished:    test.harness
Information: [xUnit.net 00:00:01.4708807]   Starting:    test.harness.notraits
Information: [xUnit.net 00:00:01.6211695]   Finished:    test.harness.notraits
Passed   test.harness.Tests.ThisIsATest
Passed   test.harness.notraits.Class1.ThisIsATest
Total tests: 2. Passed: 2. Failed: 0. Skipped: 0.
Test Run Successful.
```

**Comment by trbenning** [comment]
I'm having the same isssue. Our CI build is configured to test all assemblies matching **/*tests.dll, with a filter of "Category != Integration". Unless I add [Trait("Category", "SomethingElse"] to at least one test in every assembly containing our unit tests, no tests are discovered.

**Comment by bradwilson** [comment]
I wonder if the fix for #603 will also fix this...

**Comment by AlexanderSher** [comment]
I have this issue with runner 2.1.0, but I don't see it in 2.0.0

**Comment by mattbrooks2010** [comment]
Hit this issue in v2.1.0 but cannot repro in v2.0.1.

**Comment by bradwilson** [comment]
Yeah, this code changed in 2.1.0.

**Comment by jdom** [comment]
I just grabbed the latest prerelease (2.2.0-beta), and the discovery issue still occurs with it

**Comment by jcdickinson** [comment]
I'm on 2.1.0.

I assumed that the optional nature of traits would be an issue, so I used `Category!=Integration`. This is a negative condition so I assumed that it would pass for tests that have no category trait applied. No luck - it behaves in the non-deterministic fashion as above. Isn't something not equal to something by virtue of it not being there?

```
Information: [xUnit.net 00:00:02.4031385]   Discovering: SourceCode.Badger.Sync.Compute.Tests
Error: [xUnit.net 00:00:03.3246319] SourceCode.Badger.Sync.Compute.Tests: Exception discovering tests: No tests matched the filter because it contains one or more properties that are not valid (Category). Specify filter expression containing valid properties (DisplayName, FullyQualifiedName) and try again.
Information: [xUnit.net 00:00:03.3380533]   Discovered:  SourceCode.Badger.Sync.Compute.Tests
Information: [xUnit.net 00:00:05.1000409]   Discovering: SourceCode.Badger.Storage.Sql.Tests
// Contains the first instance of [Trait("Category", ...)]
Information: [xUnit.net 00:00:05.7307569]   Discovered:  SourceCode.Badger.Storage.Sql.Tests
```

Happy to PR this myself if you can point me in the right direction.

**Comment by bradwilson** [comment]
Unfortunately, this exception is generated by Visual Studio, not by us. We provide the list of traits to them, and they do the filtering; they're the ones generating this message. When you Google for the phrase ["No tests matched the filter because it contains one or more properties that are not valid"](https://www.google.com/search?q="No+tests+matched+the+filter+because+it+contains+one+or+more+properties+that+are+not+valid") you'll see hits for all testing frameworks, not just xUnit.net.

**Comment by mattbrooks2010** [comment]
This worked prior to v2.1.0 when the implementation changed in xunit. I guess what you're saying is you won't try and workaround it with the newer implementation. That's understandable — do we know of a related tracked bug or issue for `vstest.console.exe`?

**Comment by bradwilson** [comment]
This should already be fixed.

**Comment by t4rzsan** [comment]
I am still seeing this error with xunit.runner.visualstudio version 2.2.0, causing my TFS build to fail:

> No tests matched the filter because it contains one or more properties that are not valid (xxx). Specify filter expression containing valid properties (TestCategory, Priority, FullyQualifiedName, Name) and try again.
