### ISSUE TITLE
Need a better way to limit concurrency for integration tests (lock on shared resource)

### ISSUE THREAD

**Issue by MichaelLogutov** [xunit/xunit#615]
Right now the way to limit concurrency of parallel test execution base on some resource (for example - database) is to use ICollectionFixture. This solution has two major limits:
- it requires to use collection attribute making it impossible to lock on two or more resources (for example, if I need to write integration code that depends on two databases - it should never be launched in parallel with any other test depending on any of those databases)
- it does not supports locking across assembly boundaries (now I understand that it's not always possible, but when console runner launching several assemblies it sure can create some global named  Mutexes and pass their names to all assemblies)

I'm using NCrunch and there is a simple yet ellegant way to locking on shared resource - decorating a test method with [ExclusivelyUsesAttribute](https://www.ncrunch.net/documentation/reference_runtime-framework_exclusively-uses-attribute) prevents parallel execution of any tests with the same attribute and you can declare multilple ExclusivelyUses attributes on any method. I think it's a good solution to lock on some arbitratry resource with known identity (like constant name).

**Comment by bradwilson** [comment]
We are not planning on supporting this directly. This should be done through a custom test framework.

**Comment by redoz** [comment]
@bradwilson Not sure if it's considered rude bringing these things back from the grave, but I was wondering if the position on this has changed at all?

**Comment by IhnatKlimchuk** [comment]
@bradwilson I think this feature request should be reviewed again. Ability to run tests by taking into account what resources will be used can simplify xunit usage as test runner for more complex scenarios like integration tests.

**Comment by bradwilson** [comment]
No, I still don't believe this is something we want to build in, given that our target audience is unit testing (not integration/acceptance testing).

**Comment by MichaelLogutov** [comment]
We've been use xUnit for integration tests too just because there is nothing better currently.
For the OP problem - I just stick with slapping `[assembly: CollectionBehavior(CollectionBehavior.CollectionPerAssembly, DisableTestParallelization = true)]` into my tests project just because collections are very cumbersome to use.

I've said my more global thoughts about state of the framework here: https://github.com/xunit/xunit/discussions/2181
