### ISSUE TITLE
tests failing when comparing exception messages in non-EN-environments

### ISSUE THREAD

**Issue by jongleur1983** [xunit/xunit#616]
to be precise I refer to the tests testing xunit itself, not to the way xunit works.

30 of those fail for me as they assert to have the "correct" exception message.
The comparison performed here makes the assumption that any exception message is thrown in English, while in some (e.g. my) setup .NET obviously throws localized exception messages instead 

An example from test.core.test.xunit.execution.TestCollectionOrderer.TestCaseOrdererWhichThrowsLogsMessageAndDoesNotReorderTests:

```
Xunit.Sdk.StartsWithExceptionAssert.StartsWith() Failure:
Expected: Test collection orderer 'TestAssemblyRunnerTests+TestCollectionOrderer+ThrowingOrderer' threw 'System.DivideByZeroException' during ordering: Attempted to divide by zero.
Actual:   Test collection orderer 'TestAssemblyRunnerTests+TestCollectionOrderer+ThrowingOrderer' threw 'System.DivideByZeroException' during ordering: Es wurde versucht, durch 0 zu teilen.
```

**Comment by bradwilson** [comment]
Please provide an example of a test that you think should pass, but fails.

**Comment by jongleur1983** [comment]
isn't that an example already?
Failing Test: TestCaseOrdererWhichThrowsLogMessageAndDoesNotReorderTests
reason: it compares the error message of the exceptions with "StartsWithExceptionAssert.
Up to "during ordering" the message compared against is correct, but afterwards the part of the message that is generated by .NET framework is different: The test expects "Attempted to divide by zero." here, but .NET actually generates "Es wurde versucht, durch 0 zu teilen", which is the correct translation of the same message to German, which is reasoable due to my environments language.

I don't know (yet) how to export only failing tests from Resharpers Test window, but I'll try to figure that out and attach it here as well.

**Comment by bradwilson** [comment]
Ah, I understand now. You're saying that there is an issue with our own tests, not with the test framework. Got it. :)

**Comment by jongleur1983** [comment]
Hooray ;) that's what I wanted to make clear in my first sentence (but I'm not a native English speaker, so I might have been unclear nevertheless)

**Comment by bradwilson** [comment]
Do you have a list of failing tests? I don't have any non-English machines (and I only speak English, so setting one up would be a non-trivial exercise for me :-p).

**Comment by jongleur1983** [comment]
not beautiful, but it should be possible to get the failing tests from it.

    test (2 tests) 16 
      core (1 test) 16 
        test.xunit.execution (11 tests) 16 
          xUnit.net Test Class XunitTestClassElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::TestAssemblyRunnerTests+TestCollectionOrderer (1 test) 16 
            xUnit.net Test XunitTestMethodElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::TestAssemblyRunnerTests+TestCollectionOrderer.TestCaseOrdererWhichThrowsLogsMessageAndDoesNotReorderTests 16 
          xUnit.net Test Class XunitTestClassElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::TestClassRunnerTests+TestCaseOrderer (1 test) 16 
            xUnit.net Test XunitTestMethodElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::TestClassRunnerTests+TestCaseOrderer.TestCaseOrdererWhichThrowsLogsMessageAndDoesNotReorderTests 16 
          xUnit.net Test Class XunitTestClassElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::TestFrameworkProxyTests (3 tests) 16 
            xUnit.net Test XunitTestMethodElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::TestFrameworkProxyTests.Attribute_ThrowingDiscovererCtor 16 
            xUnit.net Test XunitTestMethodElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::TestFrameworkProxyTests.Attribute_ThrowingDiscovererMethod 16 
            xUnit.net Test XunitTestMethodElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::TestFrameworkProxyTests.Attribute_ThrowingTestFrameworkCtor 16 
          xUnit.net Test Class XunitTestClassElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::Xunit2AcceptanceTests+ClassFailures (1 test) 16 
            xUnit.net Test XunitTestMethodElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::Xunit2AcceptanceTests+ClassFailures.CompositeTestFailureResultsFromFailingTestsPlusThrowingDisposeInTestClass 16 
          xUnit.net Test Class XunitTestClassElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::Xunit2TheoryAcceptanceTests+CustomDataTests (1 test) 16 
            xUnit.net Test XunitTestMethodElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::Xunit2TheoryAcceptanceTests+CustomDataTests.TestDataWithInternalConstructor_ReturnsSingleFailingTheory 16 
          xUnit.net Test Class XunitTestClassElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::Xunit2TheoryAcceptanceTests+DataConversionTests (1 test) 16 
            xUnit.net Test XunitTestMethodElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::Xunit2TheoryAcceptanceTests+DataConversionTests.IncompatibleDataThrows 16 
          xUnit.net Test Class XunitTestClassElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::XunitTestAssemblyRunnerTests+TestCaseOrderer (1 test) 16 
            xUnit.net Test XunitTestMethodElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::XunitTestAssemblyRunnerTests+TestCaseOrderer.SettingTestCaseOrdererWithThrowingConstructorLogsDiagnosticMessage 16 
          xUnit.net Test Class XunitTestClassElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::XunitTestAssemblyRunnerTests+TestCollectionOrderer (1 test) 16 
            xUnit.net Test XunitTestMethodElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::XunitTestAssemblyRunnerTests+TestCollectionOrderer.SettingTestCollectionOrdererWithThrowingConstructorLogsDiagnosticMessage 16 
          xUnit.net Test Class XunitTestClassElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::XunitTestClassRunnerTests+TestCaseOrderer (1 test) 16 
            xUnit.net Test XunitTestMethodElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::XunitTestClassRunnerTests+TestCaseOrderer.SettingTestCaseOrdererWithThrowingConstructorLogsDiagnosticMessage 16 
          xUnit.net Test Class XunitTestClassElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::XunitTestCollectionRunnerTests+TestCaseOrderer (1 test) 16 
            xUnit.net Test XunitTestMethodElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::XunitTestCollectionRunnerTests+TestCaseOrderer.SettingTestCaseOrdererWithThrowingConstructorLogsDiagnosticMessage 16 
          xUnit.net Test Class XunitTestClassElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::XunitTheoryTestCaseRunnerTests (1 test) 16 
            xUnit.net Test XunitTestMethodElement - xUnit::C32639C0-50EB-49AB-9681-C3334E5DEAE7::XunitTheoryTestCaseRunnerTests.DiscovererWhichThrowsReturnsASingleFailedTest 16 
      runners (1 test) 16 
        test.xunit.runner.utility (7 tests) 16 
          xUnit.net Test Class XunitTestClassElement - xUnit::8CFA4522-D8B4-4BE9-A01A-A7F7124B5FCC::DefaultRunnerReporterMessageHandlerTests+FailureMessages (1 test) 16 
            xUnit.net Test XunitTestMethodElement - xUnit::8CFA4522-D8B4-4BE9-A01A-A7F7124B5FCC::DefaultRunnerReporterMessageHandlerTests+FailureMessages.LogsMessage (7 tests) 16 
              xUnit.net Theory XunitContrib.Runner.ReSharper.UnitTestProvider.XunitTestTheoryElement 16 
              xUnit.net Theory XunitContrib.Runner.ReSharper.UnitTestProvider.XunitTestTheoryElement 16 
              xUnit.net Theory XunitContrib.Runner.ReSharper.UnitTestProvider.XunitTestTheoryElement 16 
              xUnit.net Theory XunitContrib.Runner.ReSharper.UnitTestProvider.XunitTestTheoryElement 16 
              xUnit.net Theory XunitContrib.Runner.ReSharper.UnitTestProvider.XunitTestTheoryElement 16 
              xUnit.net Theory XunitContrib.Runner.ReSharper.UnitTestProvider.XunitTestTheoryElement 16 
              xUnit.net Theory XunitContrib.Runner.ReSharper.UnitTestProvider.XunitTestTheoryElement 16 
          xUnit.net Test Class XunitTestClassElement - xUnit::8CFA4522-D8B4-4BE9-A01A-A7F7124B5FCC::DefaultRunnerReporterMessageHandlerTests+OnMessage_ITestExecutionSummary (2 tests) 16 
            xUnit.net Test XunitTestMethodElement - xUnit::8CFA4522-D8B4-4BE9-A01A-A7F7124B5FCC::DefaultRunnerReporterMessageHandlerTests+OnMessage_ITestExecutionSummary.MultipleAssemblies 16 
            xUnit.net Test XunitTestMethodElement - xUnit::8CFA4522-D8B4-4BE9-A01A-A7F7124B5FCC::DefaultRunnerReporterMessageHandlerTests+OnMessage_ITestExecutionSummary.SingleAssembly 16 
          xUnit.net Test Class XunitTestClassElement - xUnit::8CFA4522-D8B4-4BE9-A01A-A7F7124B5FCC::DefaultRunnerReporterMessageHandlerTests+OnMessage_ITestFailed (1 test) 16 
            xUnit.net Test XunitTestMethodElement - xUnit::8CFA4522-D8B4-4BE9-A01A-A7F7124B5FCC::DefaultRunnerReporterMessageHandlerTests+OnMessage_ITestFailed.LogsTestNameWithExceptionAndStackTraceAndOutput 16 
          xUnit.net Test Class XunitTestClassElement - xUnit::8CFA4522-D8B4-4BE9-A01A-A7F7124B5FCC::ExceptionUtilityTests+CombineMessages (1 test) 16 
            xUnit.net Test XunitTestMethodElement - xUnit::8CFA4522-D8B4-4BE9-A01A-A7F7124B5FCC::ExceptionUtilityTests+CombineMessages.AggregateException 16 
          xUnit.net Test Class XunitTestClassElement - xUnit::8CFA4522-D8B4-4BE9-A01A-A7F7124B5FCC::ExceptionUtilityTests+CombineStackTraces (4 tests) 16 
            xUnit.net Test XunitTestMethodElement - xUnit::8CFA4522-D8B4-4BE9-A01A-A7F7124B5FCC::ExceptionUtilityTests+CombineStackTraces.AggregateException 16 
            xUnit.net Test XunitTestMethodElement - xUnit::8CFA4522-D8B4-4BE9-A01A-A7F7124B5FCC::ExceptionUtilityTests+CombineStackTraces.NonXunitException 16 
            xUnit.net Test XunitTestMethodElement - xUnit::8CFA4522-D8B4-4BE9-A01A-A7F7124B5FCC::ExceptionUtilityTests+CombineStackTraces.NonXunitExceptionWithInnerExceptions 16 
            xUnit.net Test XunitTestMethodElement - xUnit::8CFA4522-D8B4-4BE9-A01A-A7F7124B5FCC::ExceptionUtilityTests+CombineStackTraces.XunitException 16 
          xUnit.net Test Class XunitTestClassElement - xUnit::8CFA4522-D8B4-4BE9-A01A-A7F7124B5FCC::Xunit1ExceptionUtilityTests (1 test) 16 
            xUnit.net Test XunitTestMethodElement - xUnit::8CFA4522-D8B4-4BE9-A01A-A7F7124B5FCC::Xunit1ExceptionUtilityTests.CanParseEmbeddedExceptions 16 
          xUnit.net Test Class XunitTestClassElement - xUnit::8CFA4522-D8B4-4BE9-A01A-A7F7124B5FCC::Xunit1Tests+Run (1 test) 16 
            xUnit.net Test XunitTestMethodElement - xUnit::8CFA4522-D8B4-4BE9-A01A-A7F7124B5FCC::Xunit1Tests+Run.ExceptionThrownDuringRunTests_ResultsInErrorMessage 16

**Comment by jongleur1983** [comment]
for the remaining tests the case is slightly more complicated.
The exception message depends on the UICulture of the thread throwing it.
All tests still failing in non-en(-us?) environments throw the (expected) exceptions in some other thread than the one of the test method itself.

To fix that it would be necessary to enforce the culture in these threads as far as I know yet.

**Comment by bradwilson** [comment]
@jongleur1983 After all the merges, is there anything left to do here?

**Comment by jongleur1983** [comment]
@bradwilson I don't have any solution yet to solve the remaining tests, so I think we can close the issue for now. Nevertheless there are remaining tests failing (in Non-en-US environments of course), but as I don't have any idea how to fix that keeping how the exception messages are built in XUnit we may close this issue, yes.

To solve the remaining tests either we would have to avoid comparing exception message texts or avoid to pull in exception messages into the XUnit exceptions - or compare the exception messages with a culture-aware comparison.

**Comment by bradwilson** [comment]
Do you have a list of the tests? I'll see if I can figure them out. :)

**Comment by jongleur1983** [comment]
let's see:

Sample output of the first test (CompositeTestFailureResultsFromFailingTestsPlusThrowing...):
```Expected: ···ggregateException : One or more errors occurred.\r\n---- Assert···
    Actual:   ···ggregateException : Mindestens ein Fehler ist aufgetreten.\r\n-···
                                 ↑ (pos 28)```
The pattern is similar, although the "inner" exceptions differ, noted below.

All failing tests
- test.core.test.xunit.execution.ClassFailure.CompositeTestFailiureResultsFromFailingTestsPlusThrowingDisposeInTestClass (aggregateException contains exception message of DivideByZeroException, which is localized in .NET)
- test.core.test.xunit.execution.CustomDataTests.CustomDataWithInternalConstructor_ReturnsSingleFailingTheory (no idea about the exception type beind, "constructor on type ... not found" versus "Der Konstruktor für den Typ ... konnte nicht gefunden werden")
- test.core.test.xunit.execution.DataConversionTests.IncompatibleDataThrows ("object of type System.String cannot be converted to..." versus "Das Objekt mit dem Typ System.String kann nicht..."
- test.core.test.xunit.execution.FieldDataTests.RunsForEachDataElement: the double valu is expected to be formatted with a dot as decimal separator while in German it's printed with a comma (( 21.12 versus 21,12)

**Comment by bradwilson** [comment]
I believe these have all been addressed by now. Please re-open if there are still issues.
