### ISSUE TITLE
DataAttribute can't be implemented on dnx451

### ISSUE THREAD

**Issue by gongdo** [xunit/xunit#618]
I created a simple DataAttribute implementation in a new dnx console project like this:

``` CSharp
    public class TestDataAttribute : DataAttribute
    {
        public override IEnumerable<object[]> GetData(MethodInfo testMethod)
        {
            throw new NotImplementedException();
        }
    }
```

Complier says an error:

> Error CS0534  'TestDataAttribute' does not implement inherited abstract member 'DataAttribute.GetData(MethodInfo)'

Here's my project.json:

``` javascript
  "dependencies": {
    "xunit": "2.1.0",
    "xunit.runner.dnx": "2.1.0-beta5-build169"
  },
//... and other commands, but no more dependencies.
```

On dnxcore50 works fine, but dnx451 doesn't.
I tried to add several xunit dependencies explicitly, but it doesn't solve the problem.
Am I missing something?

**Comment by allansson** [comment]
This happens to me too. I've tried specifying different versions of xUnit for each framework. I have also tried using dnx452, but the problem still exists. Since it is a test project I think I can get away with just using dnxcore50, but it would be nice if it was working on all frameworks.

**Comment by bradwilson** [comment]
This appears to be a bug in the DNX compilation process. Please report the issue in https://github.com/aspnet/dnx

**Comment by axelheer** [comment]
Maybe my answer in #716 helps.
