### ISSUE TITLE
Invalid project grouping using vs runner with a base generic class

### ISSUE THREAD

**Issue by livioc** [xunit/xunit#619]
scenario: xunit and  xunit.runner.visualstudio 2.1.0, vs 2015 community, .net 4.6 project
when a class inherits from a generics base class the base methods are marked as External when grouping tests by project, with a not-generic base class it works.
this is the code to reproduce it:
```
    public class Class1 : BaseClass1
    {
        [Fact]
        public void Test1()  {}
    }

    public class Class2 : BaseClass2<string>
    {
        [Fact]
        public void Test2() {}
    }

    public abstract class BaseClass1
    {
        [Fact]
        public void InheritedTest1() {}
    }

    public abstract class BaseClass2<T>
    {
        [Fact]
        public void InheritedTest2() {}
    }
```
this is the test explorer behaviour when grouping by project
![testexplorer](https://cloud.githubusercontent.com/assets/6544383/10361588/628841e4-6da9-11e5-9d47-973d6ec5adf8.gif)

**Comment by bradwilson** [comment]
We don't control the grouping, nor the mapping of unit tests to source code. That is done with a component of Visual Studio called DIA. https://github.com/xunit/xunit/blob/master/src/xunit.runner.utility.desktop/Utility/DiaSession.cs

You should open this bug with the Visual Studio team.

**Comment by livioc** [comment]
thanks, but if also the nunit adapter has the some approach with dia session the DIA uses some data extracted from the specific adapter because with the same source code the nunit grouping is different (and more bugged :) ).
when i will have some time i try to investigate a bit, mean while i closed this issue becouse probably unrelated with xunit code
![nunit](https://cloud.githubusercontent.com/assets/6544383/10369557/2e37b97e-6ddb-11e5-9d49-67a72bfdf772.gif)

note:mstest has the same behaviour of xunit
