### ISSUE TITLE
Update NUnitXml.xslt to output missing required attributes for resultType element

### ISSUE THREAD

**Issue by JakobMollas** [xunit/xunit#620]
While trying to analyze NUnit-compatible xml output by XUnit via Sonars C#/NUnit parser it complains about at least one missing attribute, "errors", and I would guess it could miss more than that.
I checked the NUnit schema definition (for V2, version 2.5): 
https://github.com/nunit/nunit/wiki/XML-Formats
http://nunit.org/files/testresult_schema_25.txt

and compared to NUnitXml.xslt, located here:
https://github.com/xunit/xunit/blob/master/src/xunit.console/NUnitXml.xslt

I can see that some missing transformations for attributes, one is the "errors" attribute mentioned above.

Could you add transformations for missing attributes to the xslt file?
Some attributes do not have an exact match that I can see in XUnit xml format but some can likely be mapped anyway, for example "inconclusive" could be mapped to "skipped" or "failed".

**Comment by bradwilson** [comment]
Inconclusive is separate from failures or skips (both present in both frameworks). There is no such concept in xUnit.net.
