### ISSUE TITLE
Add test context object

### ISSUE THREAD

**Issue by takinosaji** [xunit/xunit#621]
Hello. 
I've already investigated https://github.com/xunit/xunit/issues/398 and https://github.com/xunit/xunit/issues/416
Sorry for catching up this topic again, but as for me it's very important thing. 
I have to know is my test failed or not in my Dispose method for example to make screenshot on failure or so. How can I do it without having something like ex TestContext in NUnit?

**Comment by agray** [comment]
+1, for being able to get the test name in a manner similar to NUnit.

**Comment by TakinosaJi** [comment]
For example I build my own framework based on awesome xUnit and I extremely need such a features as current test status and so on.

**Comment by anderssonjohan** [comment]
:+1: ****bump****

We use these features of Nunit when generating screenshots with Selenium WebDriver.
What we do today with Nunit that needs to be ported to xUnit:

```csharp
public static IWebDriver SaveScreenShot( this IWebDriver driver, string filename = null )
{
	var takesScreenShot = driver as ITakesScreenshot;
	if ( null == takesScreenShot ) return driver;

	var directory = TestContext.CurrentContext.WorkDirectory;
	var testName = TestContext.CurrentContext.Test.FullName;
	var name = filename ?? string.Format( CultureInfo.InvariantCulture, "Screenshot-{0}-{1:yyyyMMddHHmmss}", testName.Substring(0, testName.Length > 98 ? 98 : testName.Length), DateTime.Now );
	Screenshot sc = takesScreenShot.GetScreenshot();

	string file = Path.Combine( directory,  string.Concat( name, ".png" ) );
	Console.WriteLine( "Saving screenshot to {0}", file );
	sc.SaveAsFile( file, ImageFormat.Png );

	return driver;
}

public static IWebDriver SaveScreenShotOnTestFailure( this IWebDriver driver, string filename = null )
{
	if( TestContext.CurrentContext.Result.State == TestState.Cancelled && TestContext.CurrentContext.Result.Status == TestStatus.Failed )
		SaveScreenShot( driver, filename );
	return driver;
}
```

**Comment by bradwilson** [comment]
We have no test context in xUnit.net.

@anderssonjohan Where do you imagine this code lives in an xUnit.net test?

**Comment by anderssonjohan** [comment]
@bradwilson The method ```SaveScreenshotOnTestFailure``` is called from a NUnit ```[TearDown]``` method. I could use a ```[CallerMemberAttribute]```, but then I have to call this method from every ```[Fact]``` and not just from the tear down method (dispose) in my xUnit test. That feels quite messy.

Perhaps a solution would be to allow injection of some test run information in the constructor.
Brain dump example:

```csharp

public class MyFixture {
  public MyFixture( TestRunInfo testRunInfo ) {
    _testRunInfo = testRunInfo;
    // Outputs "Before execution of test ItsAFact"
    Console.WriteLine( $"Before execution of test {_testRunInfo.TestName}" );
  }

  [Fact]
  public void ItsAFact() {
  }

  public Dispose() {
    // Outputs "After execution of test ItsAFact"
    Console.WriteLine( $"After execution of test {_testRunInfo.TestName}" );
  }
}
```

What do you think about this?

**Comment by maxim-boligatov** [comment]
@bradwilson 

I want to get some info about current test. In MSTest I can create properties like this:
```C#
        public string Class
        {
            get { return this.TestContext.FullyQualifiedTestClassName; }
        }
        public string Method
        {
            get { return this.TestContext.TestName; }
        }
```

So at any time I can log specific info (with test class and method included) for any my purpose...
How can it be made in xUnit?

**Comment by bradwilson** [comment]
Please see my previous comment:

> We have no test context in xUnit.net.

**Comment by maxim-boligatov** [comment]
OK I see... there are no context bla-bla... I have decided finally to avoid migration from MsTest to xUnit... none of additional runners can compensate lack of testing results...

**Comment by psech** [comment]
+1 for being able to obtain test status in Dispose().  
I am using xunit for Selenium tests and I am moving to SauceLabs. With nunit it is possible to execute following code to pass test status:
```C#
[TearDown]
public void Cleanup()
{
    // Gets the status of the current test
    bool passed = TestContext.CurrentContext.Result.Status == TestStatus.Passed;
    try
    {
        // Logs the result to Sauce Labs
        ((IJavaScriptExecutor)driver).ExecuteScript("sauce:job-result=" + (passed ? "passed" : "failed"));
    }
    finally
    {
        // Terminates the remote webdriver session
        driver.Quit();
    }
            
}
```

**Comment by zsmagyar11** [comment]
+1, would really like to be able to check if the test failed in Dispose so I can capture a screenshot.

**Comment by rossmasday** [comment]
+1 for test status

**Comment by squirmy** [comment]
+1

Same scenario - wanting to take a screenshot when a test fails.

**Comment by mabreuortega** [comment]
+1 Selenium popular scenario can't be covered without this. Moving to NUnit for now.

**Comment by onovotny** [comment]
Silly question, but why can't you store the status of the test pass/fail in a member variable in the test and then check that in Dispose?

xUnit creates a new instance of the test class for each test method, so you can store state in the test class itself.

**Comment by squirmy** [comment]
@onovotny you can. It results in you having to put the logic into every test though. Which results in repeated code that bloats your tests. Since there is code needed in every test, there's no point to set something for dispose to use at a later point, you can just do the thing.

This is the kind of code you would have to put in every test. Which, is what we are doing now, but it's not ideal.

```c#
try
{
    Assert.Equal(false, true);
}
catch
{
    TakeScreenshot()
    throw;
}
```

**Comment by onovotny** [comment]
Seems like a custom `Fact` attribute could help then? They can execute code before/after a test for you.

**Comment by squirmy** [comment]
Are you sure? The `FactAttribute` attribute has very little implementation detail in it. I googled for an example, but only xunit 1.9 examples came up. Do you have an example?

The `BeforeAfterTestAttribute` seems more inline with what you said above, but again has no context of whether a test has passed or failed, and no access to the instance of the test class.

Personally, I don't think this feature is make or break, but it would be nice to have.

**Comment by mabreuortega** [comment]
That's not practical to implement for each test class

**Comment by cdibbs** [comment]
+1 My use case is a conditional integration test database drop in the Dispose method. If tests fail, I want to investigate, and so avoid dropping the test database.

@anderssonjohan's suggested solution is along the lines of what I was hoping to find.

**Comment by mikjonsson** [comment]
The workaround described in the link below solved my use case, which looks similar to the one mentioned in this thread.
[https://stackoverflow.com/questions/33320912/take-screenshot-on-test-failure-exceptions](https://stackoverflow.com/questions/33320912/take-screenshot-on-test-failure-exceptions)
Maybe this helps someone else too...?

**Comment by neurospeech** [comment]
@bradwilson , you simply don't want to provide TestContext?

I understand `async` execution does not provide correct `[ThreadStatic]` but Is this class really too difficult to implement for xunit?

```c#
public class TestContext : IDisposable
{

    public const string ContextName = "__XUNIT__TEST__CONTEXT__NAME";

    private static ConcurrentDictionary<string, TestContext> 
        Contexts = new ConcurrentDictionary<string, TestContext>();


    private string guid = Guid.NewGuid().ToString();

    internal TestContext()
    {
        CallContext.LogicalSetData(ContextName, guid);
        Contexts[guid] = this;

    }

    public void Dispose()
    {
        CallContext.FreeNamedDataSlot(ContextName);
        Contexts.TryRemove(guid, out TestContext mv);
    }

    public static TestContext Current
    {
        get
        {
            string guid = (string)CallContext.LogicalGetData(ContextName);
            if (guid == null)
                return null;
            if (Contexts.TryGetValue(guid, out TestContext val))
                return val;
            return null;
        }
    }
}

```

**Comment by bradwilson** [comment]
You can't use `[ThreadStatic]` for it, since that's not compatible with `Task<T>`. The appropriate type, `AsyncLocal<T>` is not available on either of our target platforms (.NET 4.5.2 and .NET Standard 1.1), and there is no static accessor for it.

**Comment by neurospeech** [comment]
@bradwilson I know `[ThreadStatic]` cannot be used.

I have given safe `CallContext.LogicalGetData` for .NET 4.5.2 and for .NET Core and after you can change underlying implementation with `AsyncLocal<T>`.

You mean to say there is no way you can implement `TestContext` with `AsyncLocal<T>` for .NET Core?

**Comment by bradwilson** [comment]
The execution library, where these things would exist, targets `net452` and `netstandard1.1`. It does not target `netcoreapp`; .NET Core applications rely upon `netstandard1.1`, as does UWP and Xamarin (iOS and Android).

**Comment by jakubsuchybio** [comment]
@bradwilson 
There is couple of scenarios where this feature would be really needed.
- Integration tests - When test fails I don't want to destroy DB in Dispose method, so that I can investigate it.
- UI tests - When test fails I want to make a screenshot of the desktop to have more information why the UI test failed, because stack trace won't give me info when Window is out of screen, not even started, etc...

There is a solution, but is needs to written in every test.
I know that you don't want to have some sort of static TextContext because of your stragety.

But could you elaborate on some workaround for this? Because screnarios mentioned above are really needed for Integration and UI testing.

Thanks

**Comment by jakubsuchybio** [comment]
I like the injected one best.
Exactly like ```ITestOutputHelper```, if we could have ```ITestResult``` which would have properties ```Status``` (success/fail/skipped/any other?) and maybe ```Exception``` if the test had some unhandled exception?

```
public ITestResult
{
    public TestStatus Status { get; set; }
    public Exception Exception { get; set; }
}

public enum TestStatus
{
    Success,
    Failed,
    Skipped
}
```

and then I would just inject ```ITestResult``` into constructor like ```ITestOutputHelper``` and in Dispose I could then use it to get the result of one test.

@hardhub I think you don't need ```OnStart(...)``` and ```OnEnd(...)```, because it is basically the same as Constructor/Dispose pattern for setup and teardown for each individual test. And ```OnSuccess(...)``` and ```OnFailure(...)```, it could create more complexity, because you would have more methods that do some logic before and after each test, which someone without knowledge about it would definitely miss. That is why I'd go with just properties, which I could use in ```Dispose()```

**Comment by bradwilson** [comment]
I'm adding the 3.0 label here, because I believe there is a general need for a much wider extensibility story, which should include the ability to inspect/manipulate the execution pipeline without replacing it wholesale.

I also think it's probably past time to have an available "test context".

**Comment by ArpitNagar** [comment]
@bradwilson Do you have any timelines on this?

**Comment by bradwilson** [comment]
There are no timelines for 3.0 yet.

**Comment by matsouzaleao** [comment]
+1

**Comment by SimonCropp** [comment]
ok here is my effort at solving this

https://github.com/SimonCropp/XunitLogger#test-failure

```cs
public class TestExceptionSample :
    XunitLoggingBase
{
    static TestExceptionSample()
    {
        //Called once at startup
        XunitLogging.EnableExceptionCapture();
    }

    [Fact]
    public void Usage()
    {
        //This tests will fail
        Assert.False(true);
    }

    public TestExceptionSample(ITestOutputHelper output) :
        base(output)
    {
    }

    public override void Dispose()
    {
        var theExceptionThrownByTest = Context.TestException;
        var testDisplayName = Context.Test.DisplayName;
        var testCase = Context.Test.TestCase;
        base.Dispose();
    }
}
```

**Comment by christianeisendle** [comment]
I could solve it by adding a message sink which is registered via a runner reporter.
This helped me a lot: https://stackoverflow.com/a/54973118

**Comment by GeeWee** [comment]
Just want to leave the tl;dr from issue #2101 - you can view that for more details:

 - I think it would be much preferable to expose the TestContext via an AsyncLocal rather than a dependency injection
- I think the ITestOutputHelper should be part of the TestContext, for easy access.

**Comment by DirttDiver** [comment]
Really need this functionality!

**Comment by bradwilson** [comment]
>I think it would be much preferable to expose the TestContext via an AsyncLocal rather than a dependency injection

My problem with this is that statics significantly hinder testability, and in this particular case, it means if you can end up in a place where the test context isn't available (for example, if you fired up a worker thread). You would have to understand when it is and isn't legal to call the static accessor.

A close correlation would be `HttpContext.Current` in ASP.NET, which was removed from ASP.NET Core for all the same reasons I've listed here.

**Comment by GeeWee** [comment]
While that is true if you explicitly spin up worker threads (I haven't seen many newer applications that do) - I feel like the alternative is quite a bit worse.

Currently if you e.g. want to get log output from your regular code in your tests you have to map your Serilog/NLog logging interface to `ITestOutputHelper` and then inject that into every single one of your classes you'd like to test.

Putting logging stuff in `AsyncLocal` also isn't anything wild or intense. Microsoft does it with `ILogger.BeginScope`. NLog does it with`MappedDiagnosticsLogicalContext`, and Serilog does it with `LogContext.PushProperty` (but I think this is probably an outreach of the broader discussion whether or not loggers should live in DI or exist outside of it)


I do agree that it breaks if you spin up worker threads, but I don't think that's a very common use-case. To me the "common" use-case should be the easiest one - so if you have worker threads where you need to access the thread context, you can pass it in manually - but the rest of us don't have to bother with it.

**Comment by SimonCropp** [comment]
from a consuming perspective, a static context would be ideal for me.

**Comment by geoffkizer** [comment]
> My problem with this is that statics significantly hinder testability, and in this particular case, it means if you can end up in a place where the test context isn't available (for example, if you fired up a worker thread).

How is the availability of the test context different than the availability of `Assert`?

**Comment by SimonCropp** [comment]
static or instance... why not both?

**Comment by bradwilson** [comment]
>My problem with this is that statics significantly hinder testability

You unit test your unit tests? The person for whom testability would be significantly hindered would be me, not you. 😁 

>static or instance... why not both?

Currently planning to support both, but the "instance" is just a static singleton:

https://github.com/xunit/xunit/blob/32a168c759e38d25931ee91925fa75b6900209e1/src/xunit.v3.core/ITestContextAccessor.cs#L3-L13

https://github.com/xunit/xunit/blob/32a168c759e38d25931ee91925fa75b6900209e1/src/xunit.v3.core/Sdk/v3/Runners/XunitTestClassRunner.cs#L226-L236

https://github.com/xunit/xunit/blob/32a168c759e38d25931ee91925fa75b6900209e1/src/xunit.v3.core/Sdk/Frameworks/TestContextAccessor.cs#L6-L18

**Comment by bradwilson** [comment]
Note that the reason for the accessor is that `TestContext.Current` (and therefore `ITestContextAccessor.Current`) returns an immutable object that represents the current state of the test engine. It will not change over time as the engine continues to run. So injecting the actual `TestContext` object doesn't really make sense.

**Comment by ElanHasson** [comment]
Hi @bradwilson, I can't seem to find v3 anywhere. All I can see is an alpha version from late 2021.

What is the status of 3.0?

**Comment by bartelink** [comment]
There is a roadmap in https://github.com/xunit/xunit/issues/2133
If you search around the issues, there may be a CI nuget feed, but it's definitely not released - the v3 impl is WIP on `main`

**Comment by ElanHasson** [comment]
Good call @bartelink, my bad on reviving this.

I had difficulty finding info on V3 and this was the context I was looking for.

Thank you!

**Comment by bradwilson** [comment]
Every commit to the `main` branch is pushed to the [xUnit.net MyGet Gallery](https://myget.org/gallery/xunit). The main package is here: https://myget.org/feed/xunit/package/nuget/xunit.v3

**Comment by bradwilson** [comment]
The usage instructions here are basically still applicable: https://xunit.net/docs/v3-alpha

**Comment by SimonCropp** [comment]
@bradwilson do u know if the rider test runner supports xunit 3?

**Comment by bradwilson** [comment]
@SimonCropp No 3rd party runner support yet (not even Visual Studio or VS Code). Runner Utility doesn't have v3 support yet.

**Comment by mufasalg0** [comment]
I can not add this dependency from https://myget.org/feed/xunit/package/nuget/xunit.v3# from here to .csproj,
When I add this PackageReference to project ,I am getting an error as :Unable to find package xunit.v3 with version(>=0.1.10-pre.118) error.
Is there any other way to add this?

**Comment by bradwilson** [comment]
@mufasalg0 The instructions for using the pre-release v3 version are here: https://xunit.net/docs/v3-alpha

They were written for an older release, but the steps should be the same (just use the updated version number(s)). Let me know if these don't work for you.
