### ISSUE TITLE
Premature PropertyChanged event cannot be tested against using Assert.PropertyChanged

### ISSUE THREAD

**Issue by robert-j-engdahl** [xunit/xunit#627]
The following code raises the PropertyChanged event prematurely, so that listeners will only have access to the old value. 

``` c#
public string SomeProperty
{
    get { return _someProperty; }
    set 
    {
        RaisePropertyChanged()
        _someProperty = value;
    }
}
```

In its current form `Assert.PropertyChanged` is redundant at best, because the above code needs to be tested like so:

``` c#
[Theory, AutoData]
public void SomeProperty_Is_Observable1(string expectedValue)
{
    string actualValue = null;
    _target.PropertyChanged += (s, e) =>
    {
        if (e.PropertyName == nameof(_target.SomeProperty))
        {
            actualValue = _target.SomeProperty;
        }
    };

    _target.SomeProperty = expectedValue;

    Assert.Equal(expectedValue, actualValue);
}
```

The above test will catch the bug.  Unlike the following, which will hapily pass:

``` c#
[Theory, AutoData]
public void SomeProperty_Is_Observable2(string expectedValue)
{
    Assert.PropertyChanged(_target, nameof(_target.SomeProperty), () => 
        {
            _target.SomeProperty = expectedValue;
        });
}
```

A simple solution would be to add a templated version of `Assert.PropertyChanged()`, say `Assert.PropertyChanged<T>()`, which returns the property value as it was when `PropertyChanged` was received:

``` c#
[Theory, AutoData]
public void SomeProperty_Is_Observable3(string expectedValue)
{
    var actualValue = Assert.PropertyChanged<string>(_target, nameof(_target.SomeProperty), () => 
        {
            _target.SomeProperty = expectedValue;
        });
    Assert.Equal(expectedValue, actualValue);
}
```

**Comment by bradwilson** [comment]
If the intention is that the property always sets the provided value, then why not do that for the user?

```csharp
Assert.PropertyChanged(_target, name(_target.SomeProperty), expectedValue);
// Sets the property, ensures that PropertyChanged was called, and gets the value to ensure the set value is returned
```

(I can see the value of both, just thinking that this signature would be more compact and hits the 90% case.)

**Comment by robert-j-engdahl** [comment]
That is also one awesome method signature.  It lets an observable property, which is implemented in three statements, be tested in a unit test containing just the assertion statement.

I agree that its the 90% that counts. It is perfectly acceptable that the user is required to write longer tests, if the property is supposed to be updated as a consequence of some other action.

**Comment by bradwilson** [comment]
Closed for age.
