### ISSUE TITLE
vstest: no tests discovered in UWP release mode

### ISSUE THREAD

**Issue by natemcmaster** [xunit/xunit#629]
In VS 2015 with UWP projects, the VS test runner does not discover tests when attempting to run in Release mode. This is caused by ILC (the "Compile with .NET Native tool chain" option which is enabled in Release mode).

To repro: follow exact steps from https://xunit.github.io/docs/getting-started-uwp.html. Change the project to "Release" mode and try running tests.

![image](https://cloud.githubusercontent.com/assets/2696087/10585281/4bdfde84-764b-11e5-906a-4b58f89763fc.png)

Could be related...there were several build warnings:

```
1>\UnitTestProject1\Xunit.Resources.xunit.execution.dotnet.rd.xml(5): warning : Ambiguous type name detected. There are types with name 'System.Threading.ExecutionContext' in both assembly 'System.Private.Networking' and 'System.Private.Threading'. This directive is ignored. Consider placing this directive within an Assembly scope.
1>\UnitTestProject1\Xunit.Resources.xunit.execution.dotnet.rd.xml(5): warning : Type 'System.Threading.ExecutionContext' could not be found.
1>\UnitTestProject1\Xunit.Resources.xunit.execution.dotnet.rd.xml(6): warning : Ambiguous type name detected. There are types with name 'System.Threading.ContextCallback' in both assembly 'System.Private.Networking' and 'System.Private.Threading'. This directive is ignored. Consider placing this directive within an Assembly scope.
1>\UnitTestProject1\Xunit.Resources.xunit.execution.dotnet.rd.xml(6): warning : Type 'System.Threading.ContextCallback' could not be found.
```

**Comment by bradwilson** [comment]
.NET Native (triggered by your choice to do Release instead of Debug) has issues that are unresolved:

https://github.com/xunit/xunit/issues/571
https://github.com/xunit/xunit/issues/572

There may be more. All I can say is, good luck. :disappointed:

**Comment by onovotny** [comment]
That said, we might need to further qualify the .rd.xml file from using just a type to an assembly and type.

**Comment by onovotny** [comment]
We are working with the .NET Native team on resolving the outstanding issues but are at the mercy of their release schedule on this :(

**Comment by natemcmaster** [comment]
Any update on this? Win10 updated tooling recently.

**Comment by rainman-63** [comment]
Any update on this?   VS Update 2 was just released.

**Comment by onovotny** [comment]
The latest 1.3.1 UWP tools fix the known .NET Native issues. Theories are discovered and execute correctly on the device runner (if you use xunit.runner.devices). Not sure how well, if at all any of it works with the VS Adapter.

**Comment by bradwilson** [comment]
Closing as external.
