### ISSUE TITLE
Support runsettings test adapter section for configuring test runner settings.

### ISSUE THREAD

**Issue by thebothead** [xunit/xunit#636]
MSFT's runsettings file can be used to toggle certain MSTest adapter settings, for example:
https://msdn.microsoft.com/en-us/library/jj635153.aspx

``` xml
  <!-- MSTest adapter -->
  <MSTest>
    <MapInconclusiveToFailed>True</MapInconclusiveToFailed>
    <CaptureTraceOutput>false</CaptureTraceOutput>
    <DeleteDeploymentDirectoryAfterTestRunIsComplete>False</DeleteDeploymentDirectoryAfterTestRunIsComplete>
    <DeploymentEnabled>False</DeploymentEnabled>
  </MSTest>
```

It would be good if this was supported also for some of the test runner settings shown here:
https://xunit.github.io/docs/running-tests-in-parallel.html

If this is supported please add documentation for how to use them in the runsettings file.

This seems to be supported in the xamarin test adapter for visual studio:
https://github.com/xamarin/xunit/blob/master/src/xunit.runner.visualstudio.testadapter/Settings/XunitTestRunSettings.cs

Thanks.

**Comment by bradwilson** [comment]
We do not intend to support this. We have our own configuration system, which works with all runners. Those four examples you cited have no xUnit.net equivalent (no inconclusive tests, we never capture trace output, we don't do deployments).

http://xunit.github.io/docs/configuring-with-json.html
http://xunit.github.io/docs/configuring-with-xml.html

The code you linked to is for an older runner, back when we didn't have our own configuration system.

**Comment by thebothead** [comment]
Thanks for the reply.  I am hitting an issue with the VSO build system when xunit.parallelizeTestCollections is true.  The test runner hangs infinitely.  The only way I have got around this was by setting that flag to false in each unit test project.

Can you provide some guidance, and an example would be great, on how to configure setting globally, specifically this setting is of interest, when running a build in VSO?  Setting this for each project seems like overkill, especially when I just need it set when building in VSO and not locally.

Thanks!

**Comment by bradwilson** [comment]
We don't offer a way to configure this globally with the Visual Studio runner (we have such a feature for the MSBuild runner, Console runner, and DNX runner, as they all offer support for custom execution options).

**Comment by orihomie** [comment]
@bradwilson then my question is about:
why do I need to set xunit configuration to run assemblies in parallel in local project settings (not in global solution setting)? Isn't that unobvious?

and so you force people to do that like this:
> dotnet.exe test .\Some.sln --filter "Category!=SomeCat" --configuration Release --no-build --no-restore -- xunit.parallelizeAssembly=true -- xunit.parallelizeTestCollections=true -- xunit.maxParallelThreads=-1 ...
