### ISSUE TITLE
Combining teardowns actions

### ISSUE THREAD

**Issue by DixonDs** [xunit/xunit#638]
It works well for class and collections fixtures when you can implement as many interfaces as you want thus all fixtures' `Dispose` methods will be invoked. Is there anything similar that can be used for combining teardown actions running for each test method? If you want to share single teardown action for some tests, you can define some base class, define proper `Dispose` there and then make all required test classes inherit this base class. But this approach is not going to work if you want to use multiple teardown actions in arbitrary combination. A common use case could be when you write integration tests and want to combine teardown actions cleaning data in different external systems.

**Comment by bradwilson** [comment]
There is nothing built-in, but it would be fairly trivial to write a composite fixture that was generic, and automatically created and disposed of the fixtures. Here is a two-parameter example just off the top of my head:

```csharp
public class GenericFixture<T1, T2> : IDisposable
    where T1: new()
    where T2: new()
{
    public GenericFixture()
    {
        T1 = new T1();
        T2 = new T2();
    }

    public T1 T1 { get; }
    public T2 T2 { get; }

    public void Dispose()
    {
        (T1 as IDisposable)?.Dispose();
        (T2 as IDisposable)?.Dispose();
    }
}

**Comment by DixonD-git** [comment]
@bradwilson Thank you for the example, but I'm just wondering if it makes sense to have something like that in XUnit itself so that people just reuse it instead of building helper classes over and over again. I think composing tear down actions is pretty common scenario.

**Comment by bradwilson** [comment]
We will consider it.
