### ISSUE TITLE
System.IO.Compression - Error in beta8

### ISSUE THREAD

**Issue by lazarofrancoe** [xunit/xunit#639]
Hi.
I have the following configuration on dnx beta8, according to [http://xunit.github.io/docs/getting-started-dnx.html](http://xunit.github.io/docs/getting-started-dnx.html)

    "frameworks": {
    "dnx451": { },
    "dnxcore50": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23409",
        "System.Collections": "4.0.11-beta-23409",
        "System.Linq": "4.0.1-beta-23409",
        "System.Runtime": "4.0.21-beta-23409",
        "System.Threading": "4.0.11-beta-23409"
      }
    }
    },
    "dependencies": {
    "xunit": "2.1.0",
    "xunit.runner.dnx": "2.1.0-beta6-build191"
     },
    "commands": {
    "test": "xunit.runner.dnx"
    }

It gives me the following error:

    NU1002 The dependency System.IO.Compression 4.0.0 in project Test does not support framework DNXCore,Version=v5.0. Test C:\Users<User>\Desktop\Onion\test\Test\project.json

However, by using xunit.runner.dnx 2.1.0-beta5a-build188 (which is for beta7), it compiles correctly.

**Comment by bradwilson** [comment]
NuGet disagrees: https://www.nuget.org/packages/System.IO.Compression

We have lots of projects using Beta 8 with that build of xUnit.net successfully. I believe there must be some other problem you're running into.

**Comment by lazarofrancoe** [comment]
Yes, it is weird. I cannot compile, but run "dnx test", so I continue working like this and inform you if I can resolve it.
Thanks.

**Comment by sblackler** [comment]
Just double check you have the latest tooling from here for beta 8: http://www.microsoft.com/en-us/download/details.aspx?id=49442

Also can confirm builds + runs tests succesfully.

**Comment by lazarofrancoe** [comment]
Well, I tried using the same configuration in a MVC6 default VS project, and it worked. Later, I started deleting package by package and compiling step by step, and found that if **I delete the`"Microsoft.AspNet.Authentication.Twitter": "1.0.0-beta8"` package, some references are added** inside
-DNX Core 5.0
--xunit.runner.dnx (2.1.0-beta6-build191
---xunit.runner.reportes (2.1.0)
----System.Net.Http (4.0.0)

One of that references is System.IO.Compression, which gives the error.

## With the package
![1](https://cloud.githubusercontent.com/assets/14990526/10690196/871e9054-7956-11e5-80f5-281495fe87b8.png)

## Without the package
![2](https://cloud.githubusercontent.com/assets/14990526/10690217/aa38468e-7956-11e5-8cf4-34136a50d89a.png)

I can't realize what is happening.

**Comment by bradwilson** [comment]
I don't know what to tell you, other than the fact that it works here (and for lots of people), which makes me think that perhaps your package cache is corrupted.

![image](https://cloud.githubusercontent.com/assets/16944/10697610/ab7e519a-7961-11e5-94d1-b75b046148ae.png)

**Comment by nojaf** [comment]
I had more or less the same issue.
VS was complaining about the Compression package.
I solved this by removing all the packages in the .dnx/packages folder. 
And then did a ```dnu restore``` inside my project from the console.

**Comment by lazarofrancoe** [comment]
It simply worked! I had restored the packages using dnu restore, but without cleaning the .dnx/packages folder. Now I'll clean that folder whenever have a problem with packages.
Thanks !
