### ISSUE TITLE
Override test parameters in continuous integration

### ISSUE THREAD

**Issue by rducom** [xunit/xunit#644]
Trying to run XUnit integration tests from Visual Studio Online, I cannot find a way to pass secrets stored in a vNext build definition, to my XUnit tests.

The usual way with MSFT is to put them in the global build definition variables, and let MSFT handle the parameter value override. (http://blogs.msdn.com/b/visualstudioalm/archive/2015/09/04/supplying-run-time-parameters-to-tests.aspx)

I didn't find a way to retrieve the "Override TestRun Parameters" data inside unit tests.
Since XUnit do not intend to support ".runsettings" files, what is the recommended way to store secrets (like database server/user/passwords) in VS online and retrieve them at run time ?

**Comment by onovotny** [comment]
What are you trying to do with the information in the context of a unit test? As secrets, they're intentionally not set as environment variables. The only way to get them is to pass them in as a parameter to something. You can create any script in any language, powershell, batch, etc. and pass in the secret that you need and "do stuff" with it.

I'm not sure how it fits into what you need in the context of xUnit though.

**Comment by rducom** [comment]
Hi Oren !

Here is my use case : I'm trying to continuously integrate a Github framework using Redis / SqlServer on Visual Studio Online. I know I can use Azure instances for this, but for my CI tests, it's a cost I'd like to avoid. On AppVeyor, I can directly run a localhost redis instance just by downloading it with nuget & starting it on the "install" step. On VSO, I can't (I tried multiple ways of starting it, with powershell or cmd, there's no way for the redis instance start). 
So I have created a little VM (not on Azure), and tried to pass my redis instance parameters (URL / pass) from the vNext build steps to my XUnit tests... Without success.

I can't publish my remote test server connexion infos directly on github, for security reasons. That's why AppVeyor provides usefull "secure file" or "secure string" tools, and let people start a redis instance. On VSO, in such a case, the usual way to go with MSFT it to put this kind of secured parameters on then "Override TestRun Parameters" field. With XUnit, I don't have found a way to "hack" console.runner in order to pass this informations.

As you said, I can create any script in order to pass this kind of secret and do stuff with it, but what I want is to pass theses info to the XUnit console runner in order to run the tests against a specific redis instance. I'd like to run my XUnit test the standard way on VSO, in order to take advantage of the code overage reports, and the SonarQube integration. The only way seems to directly pass theses infos as "Override TestRun Parameters", but maybe I'm missing something...

**Comment by onovotny** [comment]
I'm honestly not really sure. What I might suggest is that a script can take the secured parameter and either write data to a file in a known location or set an environment variable for you to use in your tests. You can check if you're running on VSO like this: https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/BuildServers/VsoAgent.cs#L11 and adjust where you get your connection info accordingly.

So if you're in VSO build, you look for your file/env variable, otherwise you're running locally and do whatever you need to do?

**Comment by rducom** [comment]
Thanks Oren, it's a good idea,
However, as I'm typing this, I realize there's a leak risk .... 
As I intend to integrate SonarQube analysis for PR, if someone publish a malicious PR (a script or a unit test reusing theses infos to send them elsewhere), my secrets will be leaked instantaneously.
So this issue can be closed, what I'm trying is stupid with XUnit : the only proper way to do it with VSO is to work with a paid Azure instance, as the only proper way to do it with AppVeyor is just to start a redis instance... 
Sorry for realizing this so late, and thanks for your time, now I know what to do :)
