### ISSUE TITLE
Pass custom argument in xUnit.console.exe

### ISSUE THREAD

**Issue by arpitgold** [xunit/xunit#645]
Hi team,
I have started creating my test with xUnit.
I want to pass a argument to xUnit Console runner. And want to use this argument value in test class, and derive some logic based on it.

Can you please help, how can I achieve this?

**Comment by bradwilson** [comment]
My first suggest would be to use environment variables for this purpose.

**Comment by arpitgold** [comment]
Is there any other approach ?:disappointed:

**Comment by bradwilson** [comment]
Generally speaking, if you want to pass in things from outside of your code, some environmental method is what's going to be available to you: environment variables, configuration files, etc. There is nothing special about unit testing here.

**Comment by arpitgold** [comment]
@bradwilson thanks for your input.
