### ISSUE TITLE
VS Test Runner: Error handling duplicate method names

### ISSUE THREAD

**Issue by Tornhoof** [xunit/xunit#650]
The VS Test Runner does not properly handle the case if the method name of the test is the same as some private method name. The error message is:
System.InvalidOperationException : The test method expected 1 parameter value, but 0 parameter values were provided.

Repro with Xunit and xunit.runner.visualstudio 2.1:

        private string Fails(string input)
        {
            return input;
        }
        [Fact]
        public void Fails()
        {
            var data = Fails("Hello World");
            Assert.Equal("Hello World", data);
        }

        private string WorksInternal(string input)
        {
            return input;
        }
        [Fact]
        public void Works()
        {
            var data = WorksInternal("Hello World");
            Assert.Equal("Hello World", data);
        }

The test class has an additional method Fails with string as parameter, the VS Test runner apparently tries to execute that one, atleast the exception from above points to that.

Note the Resharper Test runner works without a problem, so it appears to be a problem in the VS Test Runner

**Comment by bradwilson** [comment]
We don't plan on fixing this, because the workaround is simple: don't use duplicate method names in your test classes.

**Comment by Tornhoof** [comment]
I'm not certain if it is good practice to close the bug as won't fix, just because the workaround is simple.
The justification is kinda lacking, it's obviously a bug and has a nice and simple workaround, so assign it low priority.
Or you want the user do understand that it is actually bad practice to do duplicate method names, then you put it into some documentation and break it in the console runner (and possibly in the Resharper plugin too) as it works there. I imagine you do not really want (in a test framework runner) for the test runners to behave differently.

That said, do you accept pull requests for this?
