### ISSUE TITLE
Add Write(string message) to ITestOutputHelper

### ISSUE THREAD

**Issue by asgerhallas** [xunit/xunit#651]
We have a test setup that writes some "ascii formatted" messages to output. After updating to 2.0 we can't write without a line break, which makes those message harder to do right. Would it be possible to add a Write(string message) method to the ITestOutputHelper interface that does not append a newline to every message?

**Comment by bradwilson** [comment]
It was a conscious decision to only support WriteLine, because there is a potentially significant cost of reporting each output message across the app domain boundary. If we supported Write, then it could potentially generate lots of little objects with a very high cross-app-domain cost.

**Comment by asgerhallas** [comment]
Oh, I see. I guess I'll have to work around somehow then.

**Comment by chucklu** [comment]
Have the same problem, and find the explanation here

**Comment by markusschaber** [comment]
You could wrap your ITestOutputHelper with some helper class, internally using StringBuilder, and writing to the back storage on explicit WriteLine calls.

**Comment by markusschaber** [comment]
@asgerhallas You could wrap your ITestOutputHelper with some helper class, internally using StringBuilder, and writing to the back storage on explicit WriteLine calls.
