### ISSUE TITLE
Console runner: Add a -watch switch which automatically re-runs tests

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#658]
When this switch is used, instead of immediately running all tests, it would simply watch for changes to any of the provided assemblies, and run them when they change.

This should also allow the user to pass in paths to assemblies that don't (yet) exist, since the watch functionality should allow for assemblies to disappear and reappear in addition to just changing. In addition, it should wait until the DLLs become readable before running them, since it may detect a change before the assembly is fully written to disk.

**Comment by pvasek** [comment]
CoreyKaylor described the workaround for the similar thing here https://github.com/aspnet/dnx/issues/1795#issuecomment-100211344.

**Comment by khalidabuhakmeh** [comment]
Will it run all tests? or will there be any *"intelligence"*, which may only run the affected tests?

**Comment by bradwilson** [comment]
There's no way for it to know what has been affected (since it knows nothing about the source code, nor the build-to-build changes), so it will always run all tests.

**Comment by bradwilson** [comment]
Closed for age. (Also, unnecessary with the .NET SDK, given the availability of `dotnet watch`)
