### ISSUE TITLE
List all dependencies on the wiki or in the source so all projects can be listed

### ISSUE THREAD

**Issue by pawelpabich** [xunit/xunit#66]
Hi,

I tried to open the solution in VS 2013 and got the following message: "The project is targeting frameworks that are either not installed or are included as part of future updates to Visual Studio. See http://go.microsoft.com/fwlink/?LinkID=287985 for more information." This is not really helpful and still don't know what I'm missing on my machine. As work around I simply removed TargetProfile and ProjectTypeGuids from the project files. 

Can you list all required dependencies? 

The projects that failed to open: xunit.assert, xunit.core, xunit.abstractsion.pcl

Thanks

awel

**Comment by bradwilson** [comment]
Moved here: https://github.com/xunit/xunit.github.io/issues/6
