### ISSUE TITLE
Issues trying to run tests on dnx 1.0.0-rc1-16048

### ISSUE THREAD

**Issue by hugoarias** [xunit/xunit#661]
Hey,
I'm trying to run tests in the dnx 1.0.0-rc1-16048 version. However, I'm getting this message when I try to run 'dnx test' command with xunit 2.1.0 and xunit.runner.dnx 2.1.0-beta6-build191

System.NullReferenceException: Object reference not set to an instance of an object.
   at Xunit.Runner.Dnx.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly,
 String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b_
_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Is my dnx version supported? or Am I doing something wrong?

**Comment by bradwilson** [comment]
Short answer: no.

You're using the version that targets DNX Beta 8. We don't have an officially supported DNX RC1 build yet, but you can pull a `2.1.0-rc1-*` build from our MyGet CI feed at https://www.myget.org/F/xunit/

**Comment by hugoarias** [comment]
That worked. Thanks!
