### ISSUE TITLE
OutOfMemoryException caused by Visual Studio Test Runner

### ISSUE THREAD

**Issue by rickardgranberg** [xunit/xunit#662]
When running tests on TFS with a large set of test assemblies (~200 or more, depending on the assembly size), we get an OutOfMemoryException caused by the Visual Studio Test Runner.

I have traced the cause of the problem to be the fact that the test runner does not dispose any **XunitFrontController** instances until all tests have been executed, causing increased memory load. Just as a test, I changed the code in **VSTestRunner.RunTestsInAssembly** like so:

    using (var controller = new XunitFrontController(AppDomain, assemblyFileName: assemblyFileName, configFileName: null, shadowCopy: shadowCopy, diagnosticMessageSink: diagnosticMessageVisitor))
          {
            var xunitTestCases =
              runInfo.TestCases.Select(tc => new { vs = tc, xunit = Deserialize(logger, controller, tc) })
                .Where(tc => tc.xunit != null)
                .ToDictionary(tc => tc.xunit, tc => tc.vs);
            var executionOptions = TestFrameworkOptions.ForExecution(runInfo.Configuration);

            reporterMessageHandler.OnMessage(new TestAssemblyExecutionStarting(assembly, executionOptions));

            using (var executionVisitor = new VsExecutionVisitor(frameworkHandle, logger, xunitTestCases, executionOptions, () => cancelled))
            {
              controller.RunTests(xunitTestCases.Keys.ToList(), executionVisitor, executionOptions);
              executionVisitor.Finished.WaitOne();

              reporterMessageHandler.OnMessage(new TestAssemblyExecutionFinished(assembly, executionOptions, executionVisitor.ExecutionSummary));
            }
          }

And now the problem does not occur anymore. I suspect there's a reason why all **XunitFrontControllers** are put in a list and disposed at the end of the run, so my fix might not be the correct one. It does however pinpoint the problem.

**Comment by nesherhh** [comment]
I confirm, this fixes the bug. Console and msbuild executors also dispose the XunitFrontController.

**Comment by bradwilson** [comment]
My recollection was that we made this change to try to minimize the "accessing an unloaded app domain" problem which seems to plague the VS runner.
