### ISSUE TITLE
Get IRuntimeEnvironment inside a test dnx.runner

### ISSUE THREAD

**Issue by angelsix** [xunit/xunit#665]
I'm making some tests and they need the IRuntimeEnvironment to configure the environmental values for the test. 

I could manually create one but is there a way to get one that is filled with the correct information such as host machine (windows/linux) and RuntimeVersion?

**Comment by bradwilson** [comment]
Sorry, there is no host-specific information available inside of unit tests.

**Comment by angelsix** [comment]
Ok I'll just make a "Test Environment" runtime for inside of tests.
