### ISSUE TITLE
Cannot Install xunit Package

### ISSUE THREAD

**Issue by xepherys** [xunit/xunit#666]
I'm currently getting the following message both from the NuGet api v2 portal and from myget.org.  I've even manually installed the dependencies prior to trying to install the package again without success.

Attempting to resolve dependency 'xunit.core (= 2.1.0)'.
'xunit.core' already has a dependency defined for 'xunit.extensibility.core'.

**Comment by bradwilson** [comment]
Upgrade NuGet Package Manager inside Visual Studio to the latest version.

**Comment by xepherys** [comment]
Yeah... yikes!  Clearly not enough coffee today.  Thanks Brad.
