### ISSUE TITLE
All runner packages should set developmentDependency=true

### ISSUE THREAD

**Issue by AArnott** [xunit/xunit#667]
When installing the xunit.runner.console package to a project, the `developmentDependency=true` attribute should be set on that package in the packages.config file so that the dependency does not propagate to other projects that will interpret it as a package dependency (e.g. NuProj).

This can be fixed by setting adding this tag to the .nuspec file for the xunit.runner.console package:

```xml
<developmentDependency>true</developmentDependency>
```

**Comment by bradwilson** [comment]
Note: I made the change to the DNX runner's project.json, but it doesn't appear to actually pass that value into the NUSPEC file as-of yet. I opened a bug in DNX, but given the lateness of the development cycle, bets are off as to whether it gets fixed or not.

**Comment by AArnott** [comment]
You use DNX to build your xunit.runner.console package?
Hmmm... I'll add this to my list of reasons to continue avoiding DNX.

**Comment by bradwilson** [comment]
I don't, and I don't know why you think I do.

**Comment by AArnott** [comment]
> Note: I made the change to the DNX runner's project.json, but it doesn't appear to actually pass that value into the NUSPEC file as-of yet.

That sounds like you added the attribute to a project.json file instead of directly to your .nuspec file. The only reason I can imagine you'd do that is if you didn't have a .nuspec file, and the DNX you mentioned produced it from your project.json file. So it was a bit of deduction. 

If you're not using DNX, why would you open a bug against DNX? What does that have to do with the xunit.runner.console package?

**Comment by bradwilson** [comment]
There are four runners affected by this: Console, MSBuild, Visual Studio, and DNX. That's why there are three referenced commits.

The console runner is not built by DNX; the DNX runner is.

**Comment by AArnott** [comment]
ah, ok. that makes sense. :)
