### ISSUE TITLE
Custom Fact execution is skipped after moving discovery/testcase to portable assembly

### ISSUE THREAD

**Issue by AArnott** [xunit/xunit#669]
In [this change](https://github.com/AArnott/Xunit.SkippableFact/commit/780ef82b0144c0359919424d6e4dd60d0d08d573) I moved the discovery and test case classes from a desktop-platform assembly to the same portable assembly that defines the Fact attributes themselves. But after that change, the `[SkippableFact]` test cases are no longer executed. They are discovered, as I verified using the debugger with xunit.console.exe. But they are not executed, nor are they listed in the console output or Test Explorer in VS.

As [discussed on slack](https://xunit.slack.com/archives/general/p1447050514000032)

**Comment by bradwilson** [comment]
I've converted DynamicSkipExample in the samples project to a PCL, and I'm able to repro this issue.

**Comment by bradwilson** [comment]
Interestingly, if I run the tests with `-noappdomain` in the console runner, they discover and run correctly. My guess is that the issue is related to remoting.

**Comment by bradwilson** [comment]
Okay, I've figured out the issue.

When you import the `xunit.core` namespace, it (purposefully) causes a copy of `xunit.execution.desktop` to be emitted into the bin folder on build, in addition to the expected `xunit.execution.dotnet` (which is what PCLs use). The runners are incorrectly guessing that these tests should be run in desktop mode, and running them with app domains turned on, which causes your custom attributes not to be correctly remoted. You can't correctly remote them, since remoting doesn't exist in PCL space.

The work around is to create a configuration file, and turn off app domain support. Choose one of these two methods (they both work with PCLs):

* [Configuring xUnit.net with JSON]http://xunit.github.io/docs/configuring-with-json.html)
* [Configuring xUnit.net with XML]http://xunit.github.io/docs/configuring-with-xml.html)

**Comment by AArnott** [comment]
Thanks for the investigation, @bradwilson. The unfortunate thing in my case is I'm developing xunit.SkippableFact as a NuGet package for folks to consume. Now they have to manually create one of these files in order for the package to work. 
May I assume you're keeping this bug active to track fixin

**Comment by bradwilson** [comment]
Yes, I'm looking into a fix.

**Comment by bradwilson** [comment]
Also, if you're designing this to be used by 3rd parties, you should ship both desktop and dotnet versions.

**Comment by AArnott** [comment]
interesting idea... what would the difference be between the two, since everything I'm doing can be done in portable?

**Comment by bradwilson** [comment]
Users who write desktop unit tests will only ever link against xunit.execution.desktop, but your PCL links against xunit.execution.dotnet, so it's not usable in a desktop unit test (only in a PCL or a device unit test).

**Comment by AArnott** [comment]
I see. So my source code will be the same, but the fact that it compiles under two projects will change xunit references. I can do that.

**Comment by bradwilson** [comment]
Right. :)

**Comment by bradwilson** [comment]
You'll need to create the two assemblies with the suffixes `.desktop` and `.dotnet`, and mark the assembly with `[assembly: PlatformSpecificAssembly]` so that the xUnit.net serialization system knows how to deal with anything that might get serialized from your assembly (like the test case).

**Comment by bradwilson** [comment]
Name munging:

https://github.com/xunit/xunit/blob/e6894567a7d270e4eb34aad7ed81a8255740e464/src/common/SerializationHelper.cs#L230-L234 (serialization)
https://github.com/xunit/xunit/blob/e6894567a7d270e4eb34aad7ed81a8255740e464/src/common/SerializationHelper.cs#L155-L158 (deserialization)

You should also use the `.{Platform}` extension in your test case discovery declarations:

https://github.com/xunit/xunit/blob/e6894567a7d270e4eb34aad7ed81a8255740e464/src/xunit.core/FactAttribute.cs#L11

**Comment by bradwilson** [comment]
The obvious fix here is to say "if I see both .dotnet and .desktop assemblies here, I should treat it as though it were a .dotnet library", since the reality is that that's the primary way you get into that situation. That has implications for people who build all binaries into a single folder, but breaking those people's assumptions doesn't particularly bug me that much (since they're wrong :stuck_out_tongue:).

**Comment by AArnott** [comment]
@bradwilson I tried to follow all your steps above in Xunit.SkippableFact. But they still aren't being discovered. Could you take another peek at my updated attempt? 
https://github.com/AArnott/Xunit.SkippableFact/tree/iosSupport

**Comment by bradwilson** [comment]
You still have a dotnet-only assembly (`Xunit.SkippableFact`). You need to move all that code into the shared library, too.

**Comment by bradwilson** [comment]
Here's what I did:

- Upgrade the Visual Studio runner to 2.1 (required to run `dotnet` unit test projects)
- Move all the code out of `Xunit.SkippableFact` into the shared project
- Created a new test project (`Xunit.SkippableFact.Tests.Desktop`) which is a .NET 4.5.2 library, referencing `Xunit.SkippableFacts.Desktop`

Using the desktop unit tests, everything runs as expected with the existing 2.1 runners.

The portable unit tests still suffer from the problem that required the first for this issue, so using the console runner from the CI feed (`2.2.0-beta1-build3217`) allowed me to run the PCL unit tests correctly.

**Comment by bradwilson** [comment]
Note that the Visual Studio runner on the CI feed has not been updated yet, so it's still not capable of running these tests. Once it gets updated to use the latest xunit.runner.utility library, it too should be able to correctly discover and run those tests.

**Comment by bradwilson** [comment]
I believe that this is never going to run correctly inside of Visual Studio.

In order for these tests to run, they have to forego app domains. When you do that with the Visual Studio runner, you end up with DLLs staying locked inside the the `TE.ProcessHost.Managed.exe` process, which Visual Studio is using to do the discovery. When app domains are disable, the test assemblies are loaded directly into the app domain with the discovery process, which stays alive and therefore keeps the assemblies locked:

```
1>------ Clean started: Project: Xunit.SkippableFact.Tests.Desktop, Configuration: Debug Any CPU ------
2>------ Clean started: Project: Xunit.SkippableFact.NuGet, Configuration: Debug Any CPU ------
3>------ Clean started: Project: Xunit.SkippableFact.desktop, Configuration: Debug Any CPU ------
4>------ Clean started: Project: Xunit.SkippableFact.Tests, Configuration: Debug Any CPU ------
5>------ Clean started: Project: Xunit.SkippableFact.dotnet, Configuration: Debug Any CPU ------
5>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4603,5): warning MSB3061: Unable to delete file "D:\Dev\AArnott\Xunit.SkippableFact\src\Xunit.SkippableFact.Dotnet\bin\Debug\Xunit.SkippableFact.dotnet.dll". Access to the path 'D:\Dev\AArnott\Xunit.SkippableFact\src\Xunit.SkippableFact.Dotnet\bin\Debug\Xunit.SkippableFact.dotnet.dll' is denied.
5>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4603,5): warning MSB3061: Unable to delete file "D:\Dev\AArnott\Xunit.SkippableFact\src\Xunit.SkippableFact.Dotnet\bin\Debug\xunit.core.dll". Access to the path 'D:\Dev\AArnott\Xunit.SkippableFact\src\Xunit.SkippableFact.Dotnet\bin\Debug\xunit.core.dll' is denied.
5>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4603,5): warning MSB3061: Unable to delete file "D:\Dev\AArnott\Xunit.SkippableFact\src\Xunit.SkippableFact.Dotnet\bin\Debug\xunit.execution.dotnet.dll". Access to the path 'D:\Dev\AArnott\Xunit.SkippableFact\src\Xunit.SkippableFact.Dotnet\bin\Debug\xunit.execution.dotnet.dll' is denied.
5>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4603,5): warning MSB3061: Unable to delete file "D:\Dev\AArnott\Xunit.SkippableFact\src\Xunit.SkippableFact.Dotnet\bin\Debug\xunit.execution.dotnet.pdb". Access to the path 'D:\Dev\AArnott\Xunit.SkippableFact\src\Xunit.SkippableFact.Dotnet\bin\Debug\xunit.execution.dotnet.pdb' is denied.
========== Clean: 5 succeeded, 0 failed, 0 skipped ==========
```

There's not much that can be done here for this I'm afraid. Unit testing PCL libraries in Visual Studio has always been a bit of a sketchy situation, if the tests can't directly run inside the desktop app domain model.

**Comment by AArnott** [comment]
I can live with a more difficult test run for this project itself so long as consumers can do it easily enough.
I haven't read all your comments yet of what to try next so I'll get to that and reply more when it's done.

**Comment by bradwilson** [comment]
> I can live with a more difficult test run for this project itself so long as consumers can do it easily enough.

The Visual Studio issue affects everybody, not just you. The fact is that PCL-based unit tests just don't work as expected in Visual Studio, and never will. I'm going to drop "official" support for them, even though there's no technical way I can block them.

**Comment by AArnott** [comment]
The PCL with attributes plus the platform-specific execution library with copy hack is exactly what I was doing when you said earlier I needed to get rid of the PCL altogether. Does your most recent comment mean I don't have to do that?

**Comment by bradwilson** [comment]
Yep, I totally didn't realize that's what you were trying to do. Bad me. I think what tripped me up is that the shared library was linked against execution, which it cannot be.

**Comment by AArnott** [comment]
What do you mean the shared library can't be linked against execution? Do you mean the platform execution projects can't have references to the Shared Project? Why not? The code to execute is the same, isn't it?

**Comment by bradwilson** [comment]
Think of this the way xUnit.net itself does this.

Users link against `xunit.core.dll`, which is a pure PCL 259 and platform agnostic. The execution engine (`.desktop` vs. `.dotnet) is loaded dynamically at runtime, based on what kind of unit test project it is.

Your arrangement needs to be the same: the library that people link against needs to be a platform agnostic PCL 259 that's only linked against `xunit.core.dll`, and you bring along two platform-specific execution implementations, which are selected dynamically at runtime because the references to the discoverers use the `.{Platform}` suffix for the assembly name of the discoverer. You need to make sure that copies of those DLLs end up in the bin folder, and you will also need to follow the same logic we do (when writing a `.dotnet` unit test, make sure both the `.desktop` and `.dotnet` DLLs end up in the bin folder if you want Visual Studio test runner discovery to work correctly).

**Comment by bradwilson** [comment]
I'm going to be working on xUnit.net this weekend; I'll see if I can get this working and then push up some modifications into my fork for you to look at.

**Comment by AArnott** [comment]
thanks!

**Comment by bradwilson** [comment]
Okay, I made it work here: https://github.com/bradwilson/Xunit.SkippableFact/commit/bf472dc51cdfdefa29fff9fafcadf64780195387

The commit includes comments about the changes I made, and why.

Here you can see it working (with app domains on/off appropriately) from the console runner:

```
$ .\packages\xunit.runner.console.2.2.0-beta1-build3217\tools\xunit.console.exe .\src\Xunit.SkippableFact.Tests.Desktop\bin\Debug\Xunit.SkippableFact.Tests.desktop.dll -diagnostics
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
  Discovering: Xunit.SkippableFact.Tests.desktop (app domain = on [shadow copy], method display = Method)
  Discovered:  Xunit.SkippableFact.Tests.desktop (running 11 test cases)
  Starting:    Xunit.SkippableFact.Tests.desktop (parallel test collections = on, max threads = 8)
    SkipByOtherException [SKIP]
      The method or operation is not implemented.
    SkipTheoryMaybe(skip: True) [SKIP]
      I was told to.
    SkipMe [SKIP]
      Because it's a sample.
    SkipByOtherException_Ex2 [SKIP]
      Specified method is not supported.
    SkipTheoryMaybe_OtherExceptions(skip: True) [SKIP]
      The method or operation is not implemented.
  Finished:    Xunit.SkippableFact.Tests.desktop
=== TEST EXECUTION SUMMARY ===
   Xunit.SkippableFact.Tests.desktop  Total: 13, Errors: 0, Failed: 0, Skipped: 5, Time: 0.126s

$ .\packages\xunit.runner.console.2.2.0-beta1-build3217\tools\xunit.console.exe .\src\Xunit.SkippableFact.Tests.Dotnet\bin\Debug\Xunit.SkippableFact.Tests.dotnet.dll -diagnostics
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
  Discovering: Xunit.SkippableFact.Tests.dotnet (app domain = off, method display = Method)
  Discovered:  Xunit.SkippableFact.Tests.dotnet (running 11 test cases)
  Starting:    Xunit.SkippableFact.Tests.dotnet (parallel test collections = on, max threads = 8)
    SkipByOtherException [SKIP]
      The method or operation is not implemented.
    SkipTheoryMaybe(skip: True) [SKIP]
      I was told to.
    SkipMe [SKIP]
      Because it's a sample.
    SkipByOtherException_Ex2 [SKIP]
      Specified method is not supported.
    SkipTheoryMaybe_OtherExceptions(skip: True) [SKIP]
      The method or operation is not implemented.
  Finished:    Xunit.SkippableFact.Tests.dotnet
=== TEST EXECUTION SUMMARY ===
   Xunit.SkippableFact.Tests.dotnet  Total: 13, Errors: 0, Failed: 0, Skipped: 5, Time: 0.117s
```

And here it is in the VS runner:

![VS Runner](https://cloud.githubusercontent.com/assets/16944/11320561/7acd7786-9051-11e5-85be-794c09fd53b7.png)

**Comment by AArnott** [comment]
Thanks! I'll check it out tomorrow.

**Comment by AArnott** [comment]
I don't see any comments in the commit message or in the code changes. But it looks like the only things you changed are:

1. the version of xunit used
1. lowercased the platform name in the assemblies
1. forked the test projects to verify that the attributes work for both kinds.
1. added a manual file copy step to the test projects' builds, which I take my nuget package needs to automate for any receiving projects.

Was the assembly name change merely cosmetic or is it actually significant?

**Comment by bradwilson** [comment]
The comments are on the commit inside Github. Follow the link I provided.

Example:

![comments](https://cloud.githubusercontent.com/assets/16944/11330016/e5186800-9158-11e5-974d-0a34ee12ac4d.png)

**Comment by AArnott** [comment]
Ah, I see. thanks.

**Comment by AArnott** [comment]
@bradwilson When using `[SkippableTask]` in a UWP test project, the test fails to execute with this error. Notice how it mentions being unable to load the type from an assembly whose name *still carries the `{platform}` placeholder.

```
[xUnit.net 00:00:00.0864665] Unable to de-serialize test case CryptographicEngineTests.StreamingCipherKeyRetainsStateAcrossOperations_Encrypt: System.ArgumentException: Could not load type Xunit.Sdk.SkippableFactDiscoverer+SkippableFactTestCase, Xunit.SkippableFact.{Platform}
Parameter name: serializedValue
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue)
   at Xunit.Sdk.TestFrameworkExecutor`1.Deserialize(String value)
   at Xunit.Xunit2.Deserialize(String value)
   at Xunit.XunitFrontController.Deserialize(String value)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.Deserialize(LoggerHelper logger, ITestFrameworkExecutor executor, TestCase testCase)
[xUnit.net 00:00:00.1016315] Unable to de-serialize test case CryptographicEngineTests.StreamingCipherKeyRetainsStateAcrossOperations_Decrypt: System.ArgumentException: Could not load type Xunit.Sdk.SkippableFactDiscoverer+SkippableFactTestCase, Xunit.SkippableFact.{Platform}
Parameter name: serializedValue
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue)
   at Xunit.Sdk.TestFrameworkExecutor`1.Deserialize(String value)
   at Xunit.Xunit2.Deserialize(String value)
   at Xunit.XunitFrontController.Deserialize(String value)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.Deserialize(LoggerHelper logger, ITestFrameworkExecutor executor, TestCase testCase)
[xUnit.net 00:00:00.1177033]   Starting:    PCLCrypto.Tests.WinRT
[xUnit.net 00:00:00.1709135]   Finished:    PCLCrypto.Tests.WinRT
========== Run test finished: 0 run (0:00:07.345174) ==========
```

**Comment by AArnott** [comment]
...but it works in the SkippableFact solution itself. Odd.  I'm still investigating.

**Comment by AArnott** [comment]
...and I'm out of ideas. Both platform execution assemblies are present in the UWP project's bin directory.

**Comment by onovotny** [comment]
Just curious but does it work with the UWP device runner? Works differently than the VS Test Explorer in that it only ever uses the dotnet dll's. Discovery and Execution are all done on the same, correct, platform.

**Comment by AArnott** [comment]
How do I install the devices runner, other than installing the package? What do I replace the .xaml and code behind with?

**Comment by onovotny** [comment]
Should all be here: http://xunit.github.io/docs/getting-started-devices-uwp.html. This should get better once NuGet restores the missing content files for project.json projects.

There's also another example here:
https://github.com/Humanizr/Humanizer/tree/features/device-runner/src/Humanizer.Tests.Uwp.Runner

In that case, just look at the App.xaml.cs and app.xaml files. You don't need MainPage.xaml. I use a shared code project to pull in the tests, but they could be in a PCL too.

**Comment by bradwilson** [comment]
Could this be a case of the `.dotnet` DLL not being directly referenced anywhere, and therefore not being put into the app package?

**Comment by AArnott** [comment]
@bradwilson: interesting idea. And yes, the appxrecipe file mentions xunit.skippablefact.dll but not xunit.skippablefact.dotnet.dll. Is there already a recommended way to solve this?
(I suppose I could reference it... :smile:)

**Comment by AArnott** [comment]
Confirmed: adding a reference to the xunit.skippablefact.dotnet.dll assembly fixed the problem.
I could add a `lib\win` folder to my package so that only packaged windows projects reference the dotnet execution assembly. But it would be even more steller if no reference was required -- if I knew the magic msbuild incantation to not only copy the assembly to the bin folder but get it included in the package...

**Comment by bradwilson** [comment]
We used to use `.targets` files in 2.0 to make this happen, but we decided in 2.1 to just make it directly reference `xunit.execution.*.dll`.

Example:

https://github.com/xunit/xunit/blob/2.0/src/xunit.core.nuspec#L42-L46
https://github.com/xunit/xunit/blob/2.0/src/xunit.core/build/xunit.core.universal.targets

**Comment by bradwilson** [comment]
BTW, one of the reasons I moved towards removing .targets and .props files as much as possible was because DNX didn't support them. I have no idea how much they are supported with the new `dotnet` CLI.

**Comment by AArnott** [comment]
I believe the new NuGet v3 support for runtime dll's (as distinct from reference assemblies) probably would fix it too -- but then you give up NuGet v2 support.

**Comment by AArnott** [comment]
I'm seeing this on android and iOS as well. I haven't thoroughly investigated android yet, but when I add the reference to the dotnet execution assembly to the ios test app, the xunit.runner.devices runner still doesn't include the SkippableTheory test cases (although it does include ordinary Theory and Fact tests).
Any ideas what could be throwing iOS off?

**Comment by onovotny** [comment]
iOS is a weird beast. It proactively tries to exclude things that aren't directly referenced. Is there a public type you can do something with ... like `Debug.WriteLine(typeof(Blah).Assembly)`

**Comment by AArnott** [comment]
Thanks, @onovotny. In fact now that you mention it, I see your xunit.runner.devices AppDelegate already had a line like this, so I added this:

```csharp
this.AddExecutionAssembly(typeof(SkippableFactDiscoverer).Assembly);
```

And that fixed it! Thanks. I assume just a reference should resolve the android case then. I'll try that out.

**Comment by onovotny** [comment]
Yup, that's exactly why that was there. The `AddExecutionAssembly` does nothing but store the assm in a list. The list itself is never used.

**Comment by onovotny** [comment]
I really wish that Xamarin's AOT mechanisms supported the same `.rd.xml` files as .NET Native. BTW, that's another scenario to validate on UWP (InlineData currently won't work due to a attribute deserialization bug on .net native) but Fact's should work.

**Comment by AArnott** [comment]
Fun fun. 
And yes, the same fixes work on android tests as well. 
I think I'm ready to follow @bradwilson's lead and just put the dotnet execution assembly in the lib folder.
Then I'll just have to document that folks need to add that extra line in their device test runners in the FAQ.

**Comment by bradwilson** [comment]
This looks like everything is working now. Please re-open if not.
