### ISSUE TITLE
Commit 117d11e removes ability to specify multiple assemblies

### ISSUE THREAD

**Issue by cherrydev** [xunit/xunit#671]
In xunit/dnx.xunit@117d11e the command line parser for the DNX runner replaced the (very useful) ability to specify multiple assemblies on the command line with the ability to specify a config file.  Since only the command line parsing portion of this was removed, but not the rest of the support (for example `GetProjectFile` still takes and processes a list of multiple assemblies) this seems like an oversight, or that the code was somehow left unfinished.  In fact, the error handling implies that multiple assemblies are support: `throw new ArgumentException("must specify at least one assembly");`
Am I missing something?

**Comment by bradwilson** [comment]
You've actually never been able to specify assemblies on the command line. This runner has always only ever worked on the assembly that it's configured to run for.

**Comment by cherrydev** [comment]
Well yes, you could actually, but maybe I didn't explain myself very well.  I know that you can only be executing within the context of a single project at a time, but the command line options allowed you to list which assemblies (referenced from the current project) were used to discover the tests themselves.  Therefore you could have a single project that referenced all of your test projects and then you just list the referenced assemblies on the command line (suffixed by .dll) and it would discover the tests from all of the assemblies that you specify.  This was extremely useful because it allowed me to split my tests up into multiple projects (for each layer of my application) and then still run them together.  For users not using VS, it was also valuable for allowing you to run all of your tests inside of a single debugger session since you don't need to use a shell script to run multiple assemblies.

It appears that it would be very, very simple to re-enable that functionality by parsing the arguments since switches start with '-', the config file ends in '.json' and assemblies would end in 'dll', making them unambiguous.

Here is the relevant code from xunit/dnx.xunit@b7bbc655fe3d419ff0233e67d0b1cf83aa171dd2, before the change that added the config file:

```csharp
            var assemblies = new List<Tuple<string, string>>();

            while (arguments.Count > 0)
            {
                if (arguments.Peek().StartsWith("-"))
                    break;

                var assemblyFile = arguments.Pop();
                string configFile = null;

                assemblies.Add(Tuple.Create(assemblyFile, configFile));
            }

            if (assemblies.Count == 0)
                throw new ArgumentException("must specify at least one assembly");

            var project = GetProjectFile(assemblies);
```

Instead, now it simply pulls the first argument from the list, assumes it's the name of an assembly, makes a hard-coded single-item list and passes THAT to `GetProjectFile()`:

```csharp
            if (arguments.Count == 0)
                throw new ArgumentException("must specify at least one assembly");

            var assemblyFile = arguments.Pop();
            string configFile = null;
            if (arguments.Count > 0)
            {
                var value = arguments.Peek();
                if (!value.StartsWith("-") && value.EndsWith(".json", StringComparison.OrdinalIgnoreCase))
                {
                    configFile = arguments.Pop();
                    if (!fileExists(configFile))
                        throw new ArgumentException(string.Format("config file not found: {0}", configFile));
                }
            }

            var assemblies = new List<Tuple<string, string>> { Tuple.Create(assemblyFile, configFile) };
            var project = GetProjectFile(assemblies);
```

**Comment by bradwilson** [comment]
Given the direction they're going with RC2, this will probably never be possible for a DNX runner with their recommendations. We'll see.
