### ISSUE TITLE
Xunit tests not discoverable in Visual Studio 2015 Enterprise

### ISSUE THREAD

**Issue by ip28** [xunit/xunit#673]
Hi,
 I am facing this issue in two different machines, both running VS 2015 Enterprise (one has resharper ultimate installed in it, another doesn't).
I am trying to test a controller and the tests are not discoverable. I have tried clearing the temp files, and have restarted Visual Studio too.
It would be great if you can give a workaround or fix for this
![vs2015xunit](https://cloud.githubusercontent.com/assets/8371740/11112830/eb430c6e-890e-11e5-9f17-6fed32dc22f1.JPG)

As mentioned here - http://xunit.github.io/docs/running-tests-in-vs.html
I have installed the xunit runner nguet package for Visual Studio

![xunitrunner](https://cloud.githubusercontent.com/assets/8371740/11112837/f61a9396-890e-11e5-8653-bf83a1c46600.JPG)

**Comment by bradwilson** [comment]
Use `xunit.runner.dnx`, not `xunit.runner.visualstudio`.

**Comment by ip28** [comment]
Hi Brad,
 Thanks for your reply, I have now installed xunit.runner.dnx package, but still facing the same issue
![xunitdnxvs2015](https://cloud.githubusercontent.com/assets/8371740/11140555/aaf80298-89d3-11e5-8e72-31bad8b82294.JPG)
