### ISSUE TITLE
Xunit tests not discoverable in Visual Studio 2015 

### ISSUE THREAD

**Issue by ip28** [xunit/xunit#674]
Hi Brad,
 Even after installing xunit.runner.dnx nuget package (as mentioned by you for bug#673 - https://github.com/xunit/xunit/issues/673), Visual Studio 2015 (Enterprise edition) is not able to discover xunit tests.
Please check the attached screenshot

![xunitdnxvs2015](https://cloud.githubusercontent.com/assets/8371740/11140579/f34c0c7e-89d3-11e5-83bf-b76175845c61.JPG)

**Comment by bradwilson** [comment]
Follow these instructions exactly: http://xunit.github.io/docs/getting-started-dnx.html

Note that there is a 1:1 mapping between DNX version and the correct version of the `xunit` and `xunit.runner.dnx` package. Using another other version that the matching versions listed on that table is unsupported and will likely result in failure.

**Comment by dneimke** [comment]
@bradwilson I presume this means that there is very little chance of us getting xunit tests running inside VS if we are running off of the nightly builds?  E.g. rc2-*

**Comment by bradwilson** [comment]
Once RC1 is officially released, the CI feed will contain an RC2 build. Not before then.

**Comment by ip28** [comment]
With the above mentioned version of xunit.runner.dnx - 2.1.0-beta6-build191 , I am still not able to discover tests.
