### ISSUE TITLE
DNX Test Runner fails on DNX version 1.0.0-rc1-final coreclr on Windows

### ISSUE THREAD

**Issue by cartermp** [xunit/xunit#677]
I updated DNX to the final rc1 version `1.0.0-rc1-final` from this feed: https://www.myget.org/gallery/aspnetrc1.  I'm using this on Windows 10.

**Class under test:**

`Library.cs`
```chsarp
using System;

namespace Library
{
	public static class NewLibrary
	{
		public static string Hello => "Hello, .NET Core!";
	}
}
```

`project.json`
```javascript
{
	"frameworks": {
		"dotnet55":{
			"dependencies": {
				"System.Runtime":"4.0.0-rc1-*"
			}
		}
	}
}
```

**Test Class:**

`LibraryTest.cs`

```csharp
using Xunit;
using Library;
using System;

public class LibraryTest
{
	[Fact]
	public void HelloTest()
	{
		string expected = "Hello, .NET Core!";
		
		string actual = NewLibrary.Hello;
		
		Assert.Equal(expected, actual);
	}
}
```

`project.json`

```javascript
{
	"commands": {
		"test":"xunit.runner.dnx"
	},
	"frameworks": {
		"dnxcore50":{
			"dependencies": {
				"Library":"",
				"System.Runtime":"4.0.0-rc1-*",
				"xunit":"2.1.0-*",
				"xunit.runner.dnx": "2.1.0-*"
			}
		}
	}
}
```

Doing this (from root directory):

```
> dnu restore
> cd test/LibraryTests
> dnx test
```

Gives a NullReferenceException:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xunit.Runner.Dnx.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

The same files and commands under `1.0.0-rc1-15838` (from root directory):

```
> dnvm use 1.0.0-rc1-15838 -r coreclr
> dnu restore
> cd src/Library
> dnu build
> cd ../../test/LibraryTests
> dnx test
```

Produced the correct output:

```
xUnit.net DNX Runner (64-bit DNXCore 5.0)
  Discovering: LibraryTests
  Discovered:  LibraryTests
  Starting:    LibraryTests
  Finished:    LibraryTests
=== TEST EXECUTION SUMMARY ===
   LibraryTests  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.521s
```

Full source can be found here: https://github.com/cartermp/core-docs/tree/new-libraries/samples/core-projects/libraries/new-library

**Comment by bradwilson** [comment]
RC1 is only supported via a CI build of `xunit.runner.dnx` found here: https://www.myget.org/F/xunit/

You must use a `2.1.0-rc1-*` build.

**Comment by cartermp** [comment]
Thanks!

Not sure if this was the best way to solve it, but I was able to get it to work by changing the `xunit` dependencies in my `project.json` to `2.1.0-rc1-*` and then doing this (root directory):

```
> dnvm use 1.0.0-rc1-final -r coreclr
> dnu restore -s https://www.myget.org/F/xunit 
> cd src/Library
> dnu build
> cd ../../test/LibraryTests
> dnx test
```

Are there plans to push the rc1 packages to the www.myget.org/F/aspnetrc1/api/v2 feed?

**Comment by bradwilson** [comment]
I don't control that feed, so no.

We publicly release builds on NuGet when DNX ships. If you use CI builds of DNX, you must use our CI feed on MyGet.

Also, the `2.1.0-rc1-*` builds only apply to `xunit.runner.dnx`. You should continue to use the `2.1.0` RTM build of `xunit`.

**Comment by cartermp** [comment]
Okay.  Thanks!  

I was able to get some clarity on my side:

We're writing a manual for building cross-plat libraries with the current toolchain.  The rc1 feed on our side will be going live on NuGet on 11/18, as will our manual for creating these libraries.  Our current instructions for cross-plat testing will involve pulling from your RC1 feed for `xunit.runner.dnx` and then from NuGet for the rest of the dependencies.

Is there a timeline for when your RC build will be going live so that we can update those instructions?

**Comment by bradwilson** [comment]
Should be the same day ASP.NET ships RC1, barring any issues.

**Comment by cartermp** [comment]
Great to know.  Thanks again!
