### ISSUE TITLE
reproducible xunit.runner.dnx break

### ISSUE THREAD

**Issue by mgravell** [xunit/xunit#679]
I have a dnu beta8 test that breaks the test runner; running the test isolated in the debugger works fine - it runs to completion. But the test runner itself hates it, and exits without completing. Example output with these tests omitted:

    c:\Dev\Sigil\SigilTests.DNX>dnx test
    xUnit.net DNX Runner (32-bit DNXCore 5.0)
      Discovering: SigilTests.DNX
      Discovered:  SigilTests.DNX
      Starting:    SigilTests.DNX

      Finished:    SigilTests.DNX
    === TEST EXECUTION SUMMARY ===
       SigilTests.DNX  Total: 525, Errors: 0, Failed: 0, Skipped: 0, Time: 10.876s

Example with those tests (only) enabled:

    c:\Dev\Sigil\SigilTests.DNX>dnx test
    xUnit.net DNX Runner (32-bit DNXCore 5.0)
      Discovering: SigilTests.DNX
      Discovered:  SigilTests.DNX
      Starting:    SigilTests.DNX

(i.e. exits before running the summary, etc).

The issue can be seen at this [commit/branch/fork](https://github.com/mgravell/Sigil/commit/b3930d60a06d432917a4b68267afa0fc4a1ec51e) - to repro define the `WTFDNXTEST` symbol (see also `defineForCrazy` in `project.json`)

Am I going crazy?

Thanks in advance

Version info:

        "xunit": "2.1.0",
        "xunit.runner.dnx": "2.1.0-beta6-build191"

(because anything later has missing dependencies)

**Comment by jehof** [comment]
I have the same problem with the xunit.runner.msbuild.dll. It crashes reproducable. I have even turn on DiagnosticMessages but with no result.

    <Project DefaultTargets="Test" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<UsingTask
		AssemblyFile="xunit.runner.msbuild.dll"
		TaskName="Xunit.Runner.MSBuild.xunit"/>

	<ItemGroup>
		<TestAssemblies Include="*.Tests.dll" />
        </ItemGroup>

	<Target Name="Test">
		<xunit Assemblies="@(TestAssemblies)" nunit="nunit.xml" DiagnosticMessages="true" ContinueOnError="true"/>
	</Target>
    </Project>

**Comment by bradwilson** [comment]
The problem is your tests.

You emit code that calls `Console.SetOut`, but you didn't preserve the old output stream, and you don't restore it. The rest of the output that's being written by the DNX test runner is being captured by one of your test buffers.

**Comment by mgravell** [comment]
Fair enough; my bad :( Thanks for investigating.

On 21 November 2015 at 23:37, Brad Wilson <notifications@github.com> wrote:

> The problem is your tests.
>
> You emit code that calls Console.SetOut, but you didn't preserve the old
> output stream, and you don't restore it. The rest of the output that's
> being written by the DNX test runner is being captured by one of your test
> buffers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xunit/xunit/issues/679#issuecomment-158690829>.
>



-- 
Regards,

Marc
