### ISSUE TITLE
Xunit tests not discoverable in Visual Studio 2015 

### ISSUE THREAD

**Issue by ip28** [xunit/xunit#684]
Hi Brad,
 I am not yet able to discover tests in Visual Studio.
I have mentioned the exact build of xunit.runner.dnx as mentioned in the bug (https://github.com/xunit/xunit/issues/674) ( http://xunit.github.io/docs/getting-started-dnx.html)
Please find the screenshot attached.
![xunitdnxwithversion](https://cloud.githubusercontent.com/assets/8371740/11178038/f9e96264-8c41-11e5-8eca-ceae00a040de.JPG)

**Comment by ip28** [comment]
My project.json of test project is as below

{
  "version": "1.0.0-*",
  "description": "CalculatorApiTests Class Library",
  "authors": [ "IP" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
    "xunit": "2.1.0",
    "xunit.runner.dnx": "2.1.0-beta6-build191",
    "CalculatorApi": "1.0.0-*"
  },
  "commands": {
    "test": "xunit.runner.dnx"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }

  }
}

**Comment by bradwilson** [comment]
Assuming you're using DNX 1.0.0-beta8, I don't see anything wrong on the surface. Can you upload the repro to github and send me a link to the project?

Thanks.,..

**Comment by ip28** [comment]
Hi Brad, I have not mentioned any version of my DNX as such, I will upload my project to git today and send you the link

**Comment by ip28** [comment]
@bradwilson Hi Brad - Below is the git repo url for the project
https://github.com/ip28/MVC6CalculatorApi

**Comment by scugzbc** [comment]
Our understanding is ambiguous ,  just see the issue #692 .
There is only one truth.

**Comment by Thorium** [comment]
I had .NET Core project in my solution and it was stating a reference to `dotnet-compile-fsc": { "version": "1.0.0-preview2-*",` in project.json. For some reason this caused error that caused VS Test Explorer to stop searching tests even everything else worked ok. When I replaced the version to `"version": "1.0.0-preview2-020000"` my tests were found.
