### ISSUE TITLE
xunit 2, xunit console runner and Traces output (add AppVeyor)

### ISSUE THREAD

**Issue by pmiossec** [xunit/xunit#685]
Since I upgraded to xunit 2 (from 1.9.2), now when running the unit tests whit the runner, all the debug traces produced in the tested source code with `Trace.WriteLine("...")` are displayed in the console output and, which is more problematic for me, in the AppVeyor logs (and the page is big and not easy to read :( ).

Is there a way to disable this output? Especially in AppVeyor if you know it...
I didn't found in the documentation and in the runner parameters....

Thanks in advance.

**Comment by 304NotModified** [comment]
We (NLog) would like to know this also!

**Comment by bradwilson** [comment]
We don't capture any of these things any more.

My recommendations would vary depending on what you want done, but my first suggestion if you just want it removed is to use a logging abstraction that you could inject in your unit tests which just eats the log messages.

**Comment by bradwilson** [comment]
Closed for age.
