### ISSUE TITLE
Run Xamarin unit tests (command line) 

### ISSUE THREAD

**Issue by 304NotModified** [xunit/xunit#686]
Is it possible to run unit tests build on xamarin on the command line? If yes,  how? Because we can't get it working. 

In the ideal case we like to run and test NLog on appveyor (build is already working)

**Comment by bradwilson** [comment]
"Xamarin" is too generalized. If you mean a desktop unit test running on Mono, then yes, you can use Mono to run our console runner.

If you mean a specific device (iOS, etc.), then no, there is no way to do this today. You an use the [Devices Runner](https://github.com/xunit/devices.xunit) project to run tests interactively on a device, but there is no automated CI-style command line tools to do this today.

**Comment by onovotny** [comment]
I do need to write better/more Xamarin documentation, but there's no current way to run them from a command line. A command line would need a way to fire up the target (VM/Emulator/iOS Simulator/device), transfer/install the app package and get the results back.

While the device runners do theoretically support sending data over TCP to a listener, there's no infrastructure to do anything with that yet. I'm not aware of any command line ways to do this; if there are, I can look into how to do a similar thing.

**Comment by borrrden** [comment]
Has this changed at all since this ticket was closed?
