### ISSUE TITLE
File not found  when run the unit test runner for vs2015

### ISSUE THREAD

**Issue by scugzbc** [xunit/xunit#691]
![1](https://cloud.githubusercontent.com/assets/8499347/11329688/bebcc2b4-91da-11e5-8769-f00f19dfb59a.png)

the file path is wrong. it should be "TestWeb/Debug/dnx451/TestWeb.dll". or "TestWeb/Debug/dnxcore50/TestWeb.dll".
![2](https://cloud.githubusercontent.com/assets/8499347/11329716/282590be-91db-11e5-9b51-5687755ba78f.png)

so when i run the runner for vs,  just get the error :+1: 
![3](https://cloud.githubusercontent.com/assets/8499347/11329722/39ac0606-91db-11e5-8a59-30af953b79bd.png)

and then i change to use nunit on the dnx 4.5.1 .   but get the same error

Environmental:
vs2015  
![4](https://cloud.githubusercontent.com/assets/8499347/11329747/b70685d6-91db-11e5-9032-a0392d437651.png)

**Comment by bradwilson** [comment]
Your screenshot appears to show Resharper, which does not support DNX unit tests.

You want this issue: https://github.com/xunit/resharper-xunit/issues/58
