### ISSUE TITLE
MemberDataAttribute works counter-intuitive

### ISSUE THREAD

**Issue by jongleur1983** [xunit/xunit#695]
Today I stumbled over a case that sounded strange in the first place.

I wrote a xunit Theory that get's it's input from a PropertyData-Attribute (now replaced by MemberDataAttribute I think, but I'm pretty sure the issue stays the same as I didn't found anything about a change here).

This attribute requires the name of a property of type `IEnumerable<object[]>`, located in the test class.

So far everything sounds fine, but using an IEnumerable I assumed that any object that is enumerated by `yield` is used to call the test.
Instead, the test runner enumerates the whole property, similar to calling `ToList()` before executing the first test run.

In my case the reason to use this attribute is a quite complex data structure that serves the test input. As the objects are mutable it seemed to be easier to yield something, mutate it and yield it again with the now different state, but as the enumerable is completely enumerated before, my test in this case receives the first element not in the state I expected (that's the one when it has been yielded), but in the state it has after complete enumeration, something entirely different.

I therefore propose to do two things to clarify it:
* clearly state how it behaves in the documentation of the attribute
* change behaviour or api:
 * either, the enumerable should not be enumerated completely beforehand, or
 * the property should preferably be of type `ICollection<object[]>`instead, which may be basically the same implementation, but it's more clear that it's a list already, and all objects are inside from start on (I know that that's technically not true, but it's not that misleading).

I personally would prefer the first solution, as that would allow to mutate objects and call the same test routine in different states of the same object.

**Comment by jongleur1983** [comment]
As a workaround I used the following for now:
```C#
public static IEnumerable<object[]> WorkAroundInputSource
{
    get
    {
        var count = MutableTestInputSource.Count();
        for (int i = 0; i < count; i++)
        {
            yield return MutableTestInputSource.Skip(i).First();
        }
        yield break;
    }
}

public static IEnumerable<object[]> MutableTestInputSource 
{
    get
    {
        var result = this.GenerateFirstInput();
        yield return result;
        this.Mutate(result); // result is in a different state afterwards
        yield return result;
        // ...
    }
}

[Theory]
[PropertyData("WorkAroundInputSource")]
public void MyTest(params...) {
    // do the test
}
```

Unfortunately this iterates through the enumerable several times which may have a substantial impact on the test performance, especially for long lists and complex input data setups.

**Comment by bradwilson** [comment]
> Instead, the test runner enumerates the whole property, similar to calling ToList() before executing the first test run.

It's not similar-to, it is exactly that.

> As the objects are mutable it seemed to be easier to yield something, mutate it and yield it again with the now different state

This breaks the contract/expectations of `IEnumerable` (not just for xUnit.net). The world you live in is one where `.ToList()` exists, and is regularly used.

> the property should preferably be of type ICollection<object[]>instead

`ICollection` is dumb and broken (like a lot of .NET 2.0's first foray into collection interfaces). `IReadOnlyCollection` might be better, but this contract has been `IEnumerable` since 2007 (long before `IReadOnlyCollection` came into existence). Preserving backward compatibility was more important here than changing the contract.

**Comment by jongleur1983** [comment]
in that case it should probably clearly said in the attributes documentation. I may prepare a PR in the next days for it. thanks.

**Comment by jongleur1983** [comment]
in case someone is interested, I tried to sum the issue up slightly longer on my private blog at http://www.jugglingsource.de/blog/ienumerable-icollection-ireadonlycollection-an-api-analysis-on-net/

**Comment by bradwilson** [comment]
Documentation PR merged.
