### ISSUE TITLE
can't type the console.write()  to the "output" window

### ISSUE THREAD

**Issue by scugzbc** [xunit/xunit#696]
[Fact]
        public void Test()
        {
            Console.WriteLine("test");
        }

nothing in the "output" window.
maybe other config options  set false as default ?

**Comment by bradwilson** [comment]
From the [2.0 release notes](http://xunit.github.io/release-notes/2015-03-16.html):

>### Test Output
>
>In xUnit.net v1, we captured output written to standard output, standard error, the debug channel, and the trace channel, and we surfaced this output up to the test runners (which displayed them in a way that was appropriate to the test). In addition, the output was placed into the XML output, if you saved the result of your test runs.
>
>With xUnit.net v2, we have stopped capturing these sources. The primary reason is that these are shared resources, and it's impossible to know which of the many unit tests running in parallel might be writing to the console or the tracing system. Instead, tests can accept `ITestOutputHelper` as a constructor argument, and use that to provide output that is reported up to the runners (and placed into the XML results). It can be used from the constructor, from within the test, and from within `IDisposable.Dispose()` (if it's defined).
>
>For more information on using test output, please see the [TestOutputExample](https://github.com/xunit/samples.xunit/tree/master/TestOutputExample) sample project.

**Comment by scugzbc** [comment]
bingo, many thank you for you.
