### ISSUE TITLE
Can't get xUnit working with Universal Windows Apps (DEP3320)

### ISSUE THREAD

**Issue by 304NotModified** [xunit/xunit#698]
I followed (and double checked):
http://xunit.github.io/docs/getting-started-uwp.html

My test project build and the testcases are detected. When I try to run an unit test I see:

- The mobile emulator is starting, but nothing seems to happen
- I see in the console:

```
------ Discover test started ------
[xUnit.net 00:00:00.3930886]   Discovering: NLog.UnitTests
[xUnit.net 00:00:01.9338929]   Discovered:  NLog.UnitTests
========== Discover test finished: 424 found (0:00:02,0840014) ==========
------ Run test started ------
Error : DEP3320 : Target device's operating system version does not meet the application's minimum requirement. Minimum required operating system is Windows 10.0.

Failed to initialize client proxy: could not connect to test process .
========== Run test finished: 0 run (0:01:19,0125803) ==========

```

![image](https://cloud.githubusercontent.com/assets/5808377/11457505/3d608f54-96ab-11e5-842b-03e61506cb43.png)

Any idea what goes wrong? I'm running Windows 10 (x64, version 1511 - build 10586.14)

![image](https://cloud.githubusercontent.com/assets/5808377/11457520/760a71b2-96ab-11e5-852d-20b02b1c20b7.png)
 

Test project settings:

![image](https://cloud.githubusercontent.com/assets/5808377/11457529/95ef7ac2-96ab-11e5-9e95-60731b30cc7b.png)

With Google I can't find anything related to this error message.

**Comment by bradwilson** [comment]
I've never seen that error, either. Any ideas @onovotny?

**Comment by 304NotModified** [comment]
It has been fixed.

The first thing that there was something wrong with my testproject. Because just doing the tutorial was working.

The second strange this is that VS build was crashing in my x:\ disk (truecrypt). If I just copied the tutorial project to x:\, I got another DEP error. Maybe something with security rights, but for now it's now on my c:\ disk.

Good to feedback, I should not see the Windows mobile, but this:

![image](https://cloud.githubusercontent.com/assets/5808377/11458434/2a6b19ae-96c0-11e5-8b4b-e73e55961a4a.png)

and

![image](https://cloud.githubusercontent.com/assets/5808377/11458436/32fb1fa6-96c0-11e5-97d8-b5a5892d9fda.png)

**Comment by onovotny** [comment]
For UWP projects, I believe VS uses the "F5 dropdown" to determine what device it'll run on. A UWP project can run on either a phone emulator, real phone device, "simulator (ala win 8.1)" or local device. 

I'm guessing that the dropdown was set to start a Win 8.1 phone as the device, so it got a mismatch. You'd need to select a Win10 phone emulator, connect a win10 phone device or select local machine.

**Comment by 304NotModified** [comment]
Thanks but the dropdown was set right.

**Comment by bradwilson** [comment]
Visual Studio does not like running unit tests from what it thinks is a network drive, which could be what's causing the issue.
