### ISSUE TITLE
out of memory when running all (WPF) tests with code coverage

### ISSUE THREAD

**Issue by timvanderweijde** [xunit/xunit#702]
Hi,

I have a problem running all test with code coverage. I'm getting a "out of memory" exception.
 I can see that vstest.executionengine.exe memory usage constantly grows and finally the process crashes. 

I'm using wpffact from
https://github.com/xunit/samples.xunit/tree/master/STAExamples

I'm using xunit 2.

Is there a way to configure the memory usage e.d.?

Regards, Tim

**Comment by bradwilson** [comment]
Seems like a dup of #662.
