### ISSUE TITLE
Can not use xunit.console.exe with Windows Universal App

### ISSUE THREAD

**Issue by reinholdaudials** [xunit/xunit#704]
Hi,

my Xunit Tests in Visual Studio 2015 together with the xunit.runner.visualstudio are working fine.

But I'm not able to get it work with console runner. Basically I must use the built appx file as I have to run the tests in the app container. At least with vstest it was the way to go.

```
$ Tools/xunit/xunit.console.exe ../../Build/MyTests/MyTests_1.0.1.0_x86.appx
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
System.BadImageFormatException: Could not load file or assembly 'MyTests_1.0.1.0_x86.appx' or one of its dependencies. An attempt was made to load a program with an incorrect format.
System.BadImageFormatException: Could not load file or assembly 'MyTests_1.0.1.0_x86.appx' or one of its dependencies. An attempt was made to load a program with an incorrect format.
```

I tried some other things, but also without success. What is the correct way to run Universal Apps with xunit on command line?

Best,
Frieder

**Comment by onovotny** [comment]
The only way to do a command line test of Store/UWP/Phone apps is via the VSTest.Console runner. It can pick up/run xUnit tests the same way as the visual studio runner; you just have to pass in the path to the dll's of the xunit.runner.visualstudio.

https://msdn.microsoft.com/en-us/library/jj155796.aspx

You can specify the path to the VisualStudio test adapters with `/testadapterpath`

You can see an example in the test harness: https://github.com/xunit/visualstudio.xunit/tree/master/test.harness

**Comment by reinholdaudials** [comment]
Okay thanks.

I was hoping that the xunit runner supports code coverage which vstest.console does not.

Best,
Frieder

**Comment by reinholdaudials** [comment]
Hi again,

seems that I even have problems using vstest.console together with xunit. I'm using VS 2015 and it is not possible to install nuget packages per solution. Maybe this is related?

    $ vstest.console.exe ../../Build/MyTests/MyTests_1.0.1.0_x86_Debug.appx /testadapterpath:C:\\{WORKSPACE}\\MyTests\\bin\\x86\\Debug
    Microsoft (R) Test Execution Command Line Tool Version 14.0.23107.0
    Copyright (c) Microsoft Corporation.  All rights reserved.

    Starting test execution, please wait...
    Error: The active Test Run was aborted because the execution process exited unexpectedly. Check the execution process logs for more information. If the logs are not enabled, then enable the logs and try again.


Error: Failed to initialize client proxy: could not connect to test process .

**Comment by bradwilson** [comment]
Closed for age.
