### ISSUE TITLE
NullReferenceException when installing vsix 

### ISSUE THREAD

**Issue by DennisNerush** [xunit/xunit#707]
I'm using VS2015 and VS 2013. I tried to install the Xunit extension and received null reference while installing. The log is attached. Please help.
[VSIXInstaller_e57082cc-10df-4b72-a058-b86ad07b2764.txt](https://github.com/xunit/xunit/files/52884/VSIXInstaller_e57082cc-10df-4b72-a058-b86ad07b2764.txt)

**Comment by bradwilson** [comment]
What VSIX?

**Comment by DennisNerush** [comment]
It's visual studio extension...I downloaded it from your site.
I still can't install the xUnit runner so I don't think that the issue is
closed

**Comment by bradwilson** [comment]
We haven't supported that VSIX runner for almost a year now.

If you want to run tests in Visual Studio, the instructions are part of our "getting started" tutorial: http://xunit.github.io/docs/getting-started-desktop.html
