### ISSUE TITLE
Collection Fixture in external shared lib

### ISSUE THREAD

**Issue by SharpNoiZy** [xunit/xunit#710]
Hi,

I tried to use for multible Unit Test projects one shared library with a in memory database "Collection Fixture" but xUnit does not recordnize this Collection Fixture, but if I copy it to the unit test project itself, everything works.

Is it somehow possible to achive what I want to do?

Kind regards

**Comment by bradwilson** [comment]
We have discussed this previously (#409) and decided not to fix it, because search for collection fixtures in all assemblies could be a potentially very expensive and slow operation.
