### ISSUE TITLE
ITestOutputHelper in call context

### ISSUE THREAD

**Issue by JakeGinnivan** [xunit/xunit#713]
It would be really handy to be able to cross cut the test output helper stuff. http://dhickey.ie/2015/06/capturing-log-output-in-tests-with-xunit2

Or have some other way of getting the ITestOutputHelper inside a BeforeAfterTestAttribute.

**Comment by JakeGinnivan** [comment]
This is more of a initial discussion issue, interested to hear your thoughts

**Comment by arekbal** [comment]
I don't wanna start a sh..storm here... but when I see this:
https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/10928388-xunit-should-be-the-default-test-framework-for-vs
I feel I kind of have to.

I was one of those "let's jump on that wagon everybody gets on".
I was trying to implement xUnit version to this:
https://github.com/arekbal/GherkinSpec
All I found was roadblocks along the way. 
All assumptions I made about APIs, extensibility model, test frameworks... all mistaken in instance of xUnit.

To not list all xUnit problems here... let's solve one problem at a time:

BeforeAfterTestAttribute only gives you method runner called without any context that method was called in.
To workaround that silly flaw one would have to use static AsyncLocal just to pass around "test context" and maintain async context

**Comment by bradwilson** [comment]
> BeforeAfterTestAttribute only gives you method runner called without any context that method was called in.

That was an explicit design decision (whether you think it silly, or inconvenient).

**Comment by JakeGinnivan** [comment]
I have been thinking about this, and am interested in submitting a PR because I have written the same sort of code in about 3 projects now.

As part of running a test put a test correlationID into the logical call stack, then we introduce a static `XUnitLogger` class. If you log to that logger then it will grab the correlation id from the call context to lookup the correct ITestOutputHelper and write to that. That way I can hook whatever logging library up to the XUnitLogger at a global level and not have to worry. Otherwise there is no way for me to capture output from my application level logging.

**Comment by JakeGinnivan** [comment]
@bradwilson if the microsoft.visualstudio.threading nuget pkg was compatible with the same PCL profiles you use then we could use `AsyncLocal<T>` to allow a static logger. 

Without changing existing applications **not** to use a static logger, I need to do the `CallContext` work around in most projects I go into. Are you at all interested in looking down this road or is it always going to be an instance based logger which is injected?

**Comment by bradwilson** [comment]
Our logging story for non-tests is diagnostic messages. There are places we could make the diagnostic message sink available for this where we don't today (BeforeAfter is one example). Outside of a test, `ITestOutputHelper` does not have the correct context (a test to associate the output with).

**Comment by neurospeech** [comment]
@bradwilson I am also using `CallContext`, the only problem is every test needs an explicit constructor with `ITestOutputHelper` . Is there anyway to achieve same without using explicit constructor with `ITestOutputHelper` ?

**Comment by bradwilson** [comment]
This would be rolled into #621 if it gets implemented.

**Comment by bradwilson** [comment]
ITestOutputHelper is only valid in the context of a test.

As of 2.4 beta 2, you can instead inject `IMessageSink` and send `DiagnosticMessage`s to it. https://github.com/xunit/xunit/commit/89d11eca58bed6754304a2b3897bf2a0f6dcd838
