### ISSUE TITLE
Add generic output format for all runners.

### ISSUE THREAD

**Issue by sqeezy** [xunit/xunit#715]
I only use the console runner under windows and recently had the issue that i needed an nunit 2.x compatible output. This was only possible with modifying the nunit-xslt of the console runner. A way to feed all test runners a xslt and this gets applied would be really usefull. At least for the console runner.

**Comment by bradwilson** [comment]
The console runner already has this feature. Look at the `.config` file to the runner and you can see that you can register your own XSL-T transforms.

**Comment by sqeezy** [comment]
Thanks very much. Is this documented? I did not find it in some hours of search. Am I just blind? :)

**Comment by bradwilson** [comment]
We still have an open issue to write documentation for the console runner: https://github.com/xunit/xunit/issues/500
