### ISSUE TITLE
Can not override DataAttribute.GetData using dnx451

### ISSUE THREAD

**Issue by seesharper** [xunit/xunit#716]
I have a custom data attribute like this.

```
using System;
using System.Collections.Generic;
using System.Reflection;
using Xunit.Sdk;

public class CustomDataAttribute : DataAttribute
{
    public override IEnumerable<object[]> GetData(MethodInfo testMethod)
    {
        throw new NotImplementedException();
    }  
}
```

My project.json file 

```
{
  "version": "3.0.0.10",
  "dependencies": {
   "xunit": "2.1.0",
   "xunit.runner.dnx": "2.1.0-rc1-build204"

  },
  "frameworks": {   
    "dnx451":{      
    },

    "dnxcore50": {               
      }
    }
 }
```

This gives me the following error message for dnx451

```
error CS0115: 'TestCLass.GetData(MethodInfo)': no suitable method found to override
```

It compiles just fine if I remove the dnx451 framework in the project.json file.

```
{
  "version": "3.0.0.10",
  "dependencies": {
   "xunit": "2.1.0",
   "xunit.runner.dnx": "2.1.0-rc1-build204"

  },
  "frameworks": {       
    "dnxcore50": {               
      }
    }
 }
```

Any idea what is going on here? Looking at the actual source code for the DataAttribute class shows that there are no compiles directives that should indicate any differences between the two runtimes.
https://github.com/xunit/xunit/blob/master/src/xunit.core/Sdk/DataAttribute.cs

Could this be a local issue or is it something else that I am missing here?

**Comment by bradwilson** [comment]
I believe that this is a DNX issue, and I'm reluctant to spend any time fixing it, until `dnx` is replaced by `dotnet` (and then we can verify whether the issue still recurs).

**Comment by seesharper** [comment]
I agree.

**Comment by axelheer** [comment]
Try to add `System.Reflection` and `System.Runtime` to the `frameworkAssemblies` section as build dependencies. The compiler needs to resolve the dependencies of the xunit assemblies, which are *PCLs* and thus referencing some facades, which are generally not part of the .NET Framework and thus not known during compile time.

e.g.

    "dnx46": {
      "frameworkAssemblies": {
        "System.Reflection": {
          "type": "build",
          "version": ""
        },
        "System.Runtime": {
          "type": "build",
          "version": ""
        }
      }
    }

BTW, I [blogged about this](http://axel.heer.eu/2016/01/15/building-dnx-code-using-pcl-dependencies/) (Sorry, not English but German...).

**Comment by jonaslundgren** [comment]
Adding SystemReflection to frameworkAssemblies worked for me:

`"frameworks": {
    "dnx451": {
      "frameworkAssemblies": {
        "System.Reflection": "4.0.0.0"
      }
    }
  }`
