### ISSUE TITLE
Provide access to IRunContext inside test cases

### ISSUE THREAD

**Issue by AlexanderSher** [xunit/xunit#717]
It will be useful for tests that have to produce custom artifacts and/or use file-based input to have access to `IRunContext.SolutionDirectory` and `IRunContext.TestRunDirectory`. Currently there is a workaround based on assembly location, but it may not work on build server if binaries are deployed into folder that isn't relative to solution.

**Comment by bradwilson** [comment]
We have no concept of run context in xUnit.net. I'm not sure what you're referring to here.

**Comment by AlexanderSher** [comment]
I meant `Microsoft.VisualStudio.TestTools.Execution.IRunContext`, which is passed to `ITestExecutor.RunTests`.

**Comment by bradwilson** [comment]
Sorry, we don't add platform-specific features to xUnit.net. Any test which relied on this would be broken when run outside of Visual Studio.

**Comment by onovotny** [comment]
@AlexanderSher  You might consider using environment variables that you set from your build script that points to your solution dir. Then you can use it from within your test.

**Comment by bradwilson** [comment]
Closed for age.
