### ISSUE TITLE
ITestOutputHelper should output to screen

### ISSUE THREAD

**Issue by ghost** [xunit/xunit#720]
As mention in bug #718 it would be enormously nice if it would be possible for a test to show custom output on the console. As console/diagnostics output is now ignored and ITestOutputHelper only puts stuff in xml/reports there is no way to show anything. I would therefore help a lot if ITestOutputHelper.WriteLine would by default output to the console screen as well during execution of the tests.

**Comment by bradwilson** [comment]
Updating the reporters should generate the output for console, MSBuild, and DNX runners automatically.

**Comment by bradwilson** [comment]
Closed for age.

**Comment by justdmitry** [comment]
Wow. It seems that output IS printed in console in case of test failure (and not printed for successful tests). Cool. My previous question is unnecessary anymore.
