### ISSUE TITLE
HTML report output missing tests

### ISSUE THREAD

**Issue by ilCosmico** [xunit/xunit#721]
Hi guys,

If I run 25 tests the output shows all the test results but if I run 900 tests the output shows only few results, what am I doing wrong? Can be some bug?
I'm using Xunit 2.1.0.

![image](https://cloud.githubusercontent.com/assets/8678145/11951511/ab8ff7a6-a891-11e5-94ea-bc4451635b0a.png)

**Comment by joshuaduffy** [comment]
I've also got the same issue when running a lot of tests, I've got an error that is thrown that I can dig out and provide from the console output 

Thanks, Josh

**Comment by bradwilson** [comment]
Yeah, sounds like some kind of transformation issue. A repro or an error would be greatly helpful. :)

If you generate the XML, does that work correctly? If so, can you attach the XML which is correct, but fails to generate appropriate HTML?

**Comment by ilCosmico** [comment]
Here you are:
[XunitLogs.zip](https://github.com/xunit/xunit/files/70575/XunitLogs.zip)

**Comment by bradwilson** [comment]
@ilCosmico Sorry, just got a chance to look at this now, and it appears that the XML file is truncated. Is that also repeatable? If so, can you provide the failure information related to the test where the truncation is happening? It appears as though xUnit.net is having some issue with the stack trace on the failed test.

![truncation](https://cloud.githubusercontent.com/assets/16944/12059871/a1615c06-af18-11e5-8432-7808e577d891.png)

**Comment by ilCosmico** [comment]
@bradwilson Yes, of course

[StackTrace.txt](https://github.com/xunit/xunit/files/76992/StackTrace.txt)

**Comment by bradwilson** [comment]
Fucking obfuscators and their illegal stack traces. :angry:

**Comment by ilCosmico** [comment]
Have you enough clues for working on HTML output issue or should I provide some others stuff?

**Comment by bradwilson** [comment]
I think I have enough to work on it. Thanks. :)

**Comment by ilCosmico** [comment]
Hi @bradwilson, another little issue: sometimes, some tests result are written after the summary
![image](https://cloud.githubusercontent.com/assets/8678145/12347915/db230f4c-bb62-11e5-9f96-db5db36bf2e0.png)

Have you idea the reason why?

**Comment by bradwilson** [comment]
Hmm, never seen that before. Is it always that one test? Can you share the repro?

**Comment by ilCosmico** [comment]
Here we go: 
[TestLog.zip](https://github.com/xunit/xunit/files/92006/TestLog.zip)

**Comment by bradwilson** [comment]
Closed for age.
