### ISSUE TITLE
XUnit test detection exception in visualstudio.xunit runner

### ISSUE THREAD

**Issue by jcfarsight** [xunit/xunit#722]
Hey guys I'm having an issue with the XUnit VisualStudio runner v2.1 and above where it runs fine on my local machine but fails to detect tests on our build server (using Buildmaster).

If I downgrade to v2.0.1 of the runner the tests detect and run fine in both environments.

Here is the output snippet displaying the issue:

```
Warning: [xUnit.net 00:00:00.0186044] Exception discovering tests from MyAssemblyName: System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.IsXunitTestAssembly(String assemblyFileName)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.DiscoverTests[TVisitor](IEnumerable`1 sources, LoggerHelper logger, Func`4 visitorFactory, Action`4 visitComplete)
Warning: No test is available in MyAssemblyName.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
Information: Additionally, you can try specifying '/UseVsixExtensions' command if the test discoverer & executor is installed on the machine as vsix extensions and your installation supports vsix extensions. Example: vstest.console.exe myTests.dll /UseVsixExtensions:true
```

I pulled down the runner code (both pre and post v2.1) to put some additional logging in to try and figure out what is going wrong.

I found that this method is being passed full Directory\Filename.dll paths on my local machine but only Filename.dll on our Build server:
public void RunTests(IEnumerable<string> sources, IRunContext runContext, IFrameworkHandle frameworkHandle)

This occurs with both v2.0.1 and v2.1.0 of the runner however the old revision of the 'IsXunitTestAssembly' method appears to handle this gracefully and continue fine while the new version of the method does not.
We have VS2015, MSBuild14 and .NET 452 on both environments.

A couple of questions on this:
1) Would anyone happen to know why an ITestExecutor would not always be passed through the full file path for sources correctly?
2) Is this expected behaviour to sometimes see this and if so, should the runner handle this gracefully?

I'll be away until the 11th of January but will re-visit this issue and answer any followup questions then.

**Comment by bradwilson** [comment]
That information is passed to us by Visual Studio. We have no control over it. It should be relative to the current directory; if it's not, then we will fail.

**Comment by jcfarsight** [comment]
Alright fair enough. I'll try and investigate further why Visual Studio isn't playing nicely in our build environment then.

**Comment by bradwilson** [comment]
It's odd, to be sure. :(

**Comment by Shane88** [comment]
NUnit had this same problem with their adapter and it was fixed by adding code like the following.

    if (!Path.IsPathRooted(sourceAssembly))
    {
        sourceAssembly = Path.Combine(Environment.CurrentDirectory, sourceAssembly);
    }

See the NUnit issue here https://github.com/nunit/nunit/issues/116

**Comment by kiwidev** [comment]
Not sure if this has been chased down, but here are the details:

It appears that VsTest v14 has two modes (TAEF and non TAEF/legacy) - in portable/standalone mode it defaults to legacy, while VS installation sets a registry key to put it in TAEF mode. This affects a number of things, one of which is this value.

When in legacy mode it passes filenames as specified by the user (so you need to specify `.\UnitTests.dll` instead of `UnitTests.dll`), while in TAEF mode it fully qualifies it.

**Comment by bradwilson** [comment]
Closed for age.
