### ISSUE TITLE
Console runner does not load configuration when using config xunit.appDomain = 'denied'

### ISSUE THREAD

**Issue by TheCloudlessSky** [xunit/xunit#723]
When `xunit.appDomain` is set to `denied` in the configuration, the app's configuration is not available for use with `ConfigurationManager` when using the console runner. However, running with TestDriven.Net, it works as expected.

## Steps to reproduce

1. Create a .NET 4.5 Class Library project (I called it XunitAppDomainConfig).
2. Install xunit and the console runner:

        > install-package xunit -IncludePrerelease
        > install-package xunit.runner.console -IncludePrerelease

3. Create `SampleTests.cs`:

    ```csharp
    public class SampleTests
    {
        [Fact]
        void should_find_correct_connection_string()
        {
            var cs = ConfigurationManager.ConnectionStrings["hello_world"];
            Assert.NotNull(cs);
            Assert.Equal("Hello World", cs.ConnectionString);
        }
    }
    ````

4. Create an `App.config` with:

    ```xml
    <?xml version="1.0" encoding="utf-8" ?>
    <configuration>
      <appSettings>
        <add key="xunit.appDomain" value="denied" />
      </appSettings>
      <connectionStrings>
        <add name="hello_world" connectionString="Hello World" />
      </connectionStrings>
    </configuration>
    ```

5. Run tests with TestDriven.NET (passes):

        ------ Test started: Assembly: XunitAppDomainConfig.dll ------

        1 passed, 0 failed, 0 skipped, took 0.38 seconds (xUnit.net 2.2.0 build 3239).

6. Run tests with Console runner (fails):

        > packages\xunit.runner.console.2.2.0-beta1-build3239\tools\xunit.console.exe XunitAppDomainConfig\bin\Debug\XunitAppDomainConfig.dll -verbose -diagnostics

        xUnit.net Console Runner (64-bit .NET 4.0.30319.34209)
          Discovering: XunitAppDomainConfig (app domain = off, method display = ClassAndMethod)
          Discovered:  XunitAppDomainConfig (running 1 test case)
          Starting:    XunitAppDomainConfig (parallel test collections = on, max threads = 4)
            XunitAppDomainConfig.SampleTests.should_find_correct_connection_string
            XunitAppDomainConfig.SampleTests.should_find_correct_connection_string [FAIL]
              Assert.NotNull() Failure
              Stack Trace:
                XunitAppDomainConfig\SampleTests.cs(17,0): at XunitAppDomainConfig.SampleTests.should_find_correct_connection_string()
          Finished:    XunitAppDomainConfig
        === TEST EXECUTION SUMMARY ===
           XunitAppDomainConfig  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 0.236s

---

Even if the config is directly specified at the command line after the DLL, it still fails.

If this is expected behavior when using `appDomain=denied`, there should be a huge warning when using it. However, it feels like a bug because of the discrepancy between runners.

We are using `appDomain=denied` to significantly speed up our tests (10s of seconds) as per #353.

**Comment by bradwilson** [comment]
This is, unfortunately, working as designed.

App domains get configuration files. The app domain of the console runner has the console runner's configuration file as the one for that app domain. When xUnit.net starts new app domains, it can correctly set the configuration file for use with the tests; when you choose not to use app domains, this is one of the features you must unfortunately give up.

The alternative. rather than depending on implicit configuration file support, would be to load the configuration file explicitly. More information: http://stackoverflow.com/questions/6341906/read-custom-configuration-file-in-c-sharp-framework-4-0

**Comment by TheCloudlessSky** [comment]
That's what I expected given that using `appDomain=denied` doesn't create the new app domain. However, why does it work with the TD.NET runner and not the console runner? Does the TD.NET runner ignore the app domain setting?

It'd be nice to add some documentation around this. It's sort of weird because the configuration is *partially* loaded (to read the `xunit.appDomain` setting) but then isn't loaded and available for `ConfigurationManager` (which makes sense).

**Comment by bradwilson** [comment]
> why does it work with the TD.NET runner and not the console runner?

TestDriven.NET automatically creates separate app domains before it even invokes us.

> It'd be nice to add some documentation around this.

Yeah, I wonder if maybe we should add a page that talks about the difference between using app domains and not.

**Comment by TheCloudlessSky** [comment]
> TestDriven.NET automatically creates separate app domains before it even invokes us.

I didn't know that... it makes sense why it can work then.

:+1: For adding more docs around this. I'd be glad to contribute this.

**Comment by TheCloudlessSky** [comment]
Now that I've thought about it some more... I believe the TD.NET runner would be creating app domains *twice* (if it's created when first launched and [then when creating the Xunit2 instance](https://github.com/xunit/xunit/blob/master/src/xunit.runner.tdnet/TdNetRunnerHelper.cs#L30)). If this is the case, this would show why we're experiencing very slow loading (10s of seconds) when using TD.NET. Since TD.NET already loads the correct configuration, should the whole app domain be reloaded?

Is there a way to set `appDomain=denied` *only* when using the TD.NET runner, but use `ifAvailable` when using all other runners?

**Comment by bradwilson** [comment]
Not precisely, though you could simulate it... sort of.

TD.NET does not have any specific override functionality, so if you set your config file to be "denied", then used command line switches with the console runner (or task properties with the MSBuild runner) you could override the behavior there.

**Comment by TheCloudlessSky** [comment]
It looks as though the console runner [only supports a simple "noappdomian" switch](https://github.com/xunit/xunit/blob/master/src/xunit.console/CommandLine.cs#L149) and not the ability to override (e.g. `-appDomain=ifAvailable`). Is this correct?

**Comment by bradwilson** [comment]
Oh, hmm, that's a good point. :(

**Comment by dloukola** [comment]
So you can't use the ConfigurationManager class in xunit.net and this is considered not a bug? I'm confused. MSTest can do it.

**Comment by bradwilson** [comment]
If you can figure out the API we call to make it work, then let us know.
