### ISSUE TITLE
testextensions.xunit not properly supporting xUnit 2.1

### ISSUE THREAD

**Issue by hutterd** [xunit/xunit#725]
The "Create Unit Tests" or "Create IntelliTest" dialog does not show xUnit 2.1 (only xUnit 2.0).

To make it work for me I made the following 2 fixes:
1) IntelliTest.Xunit/XunitTestFramework_2_1.cs: change 'name: "xunit-2.0" ' to 'name: "xunit-2.1" '
2) IntelliTest.Xunit/XunitTestFrameworkPackageAttribute.cs: added line for xUnit 2.1: testFrameworkService.AddTestFramework(new XunitTestFramework_2_1(host));

**Comment by joshuaduffy** [comment]
See [#1](github.com/xunit/testextensions.xunit/pull/1)

**Comment by bradwilson** [comment]
Closed for age.

**Comment by NelsonLamprecht** [comment]
@bradwilson Assuming something similar for xunit 2.4.1? never tried intellitest before
