### ISSUE TITLE
Give BeforeAfterTestAttribute access to ITestOutputHelper

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#726]
Related; #713

**Comment by bradwilson** [comment]
Closed for age.

**Comment by ffMathy** [comment]
@bradwilson can we re-open this?

**Comment by bradwilson** [comment]
In v3, the `TestContext` gives access to send diagnostic messages from virtually anywhere in the pipeline, including from BeforeAfterTestAttributes.

https://github.com/xunit/xunit/blob/c27a91f8cbcee37cb45699a3a81287bca225e876/src/xunit.v3.core/TestContext.cs#L157-L180

**Comment by ffMathy** [comment]
Ah sorry, I missed that. Is there an ETA for v3 to release? 😅

**Comment by bradwilson** [comment]
Unfortunately no. There has been a pause recently due to personal things on my side, but I hope to pick work back up again soon.
