### ISSUE TITLE
Bug when executing test on mono that uses HttpUtlity.UrlEncode before reading a Configuration value

### ISSUE THREAD

**Issue by stefansedich** [xunit/xunit#728]
I have discovered an "interesting" bug, this only occurs when running the console runner on Mono (4.2 and 4.3 in my case), but does not occur when running the same scenario inside a console application.

If you were to use HttpUtility.UrlEncode before fetching a configuration value using ConfigurationManager.AppSettings["foo"] you will find that null is returned even though that key is defined in the configuration, which can be seen if you fetch the configuration value before the call to HttpUtility.UrlEncode.

https://github.com/stefansedich/xunit-bug-repro has a full reproduction demonstrating the exact scenario. You can just execute ./run.sh and it will fire off the console app and the test suite.

Strangely the console app runs fine and does not exhibit this behavior, I can see deep in the bowels of UrlEncode it does do some things that load from config which in turn causes configuration to be initialized but I have not dug much more at this stage.

I am still not sure if this is a Mono bug or not, but as this behavior is only displayed during execution of the test suite I came here first.

**Comment by bradwilson** [comment]
Closed for age.
