### ISSUE TITLE
in dnx.xunit - show progress

### ISSUE THREAD

**Issue by ayende** [xunit/xunit#729]
Right now, I have a test suite that can take a while (many minutes / hours in the large ones).
I'm looking at this:
![image](https://cloud.githubusercontent.com/assets/116915/12076392/ed4b53f0-b1b2-11e5-8268-0ab173590ca8.png)

And it has no input about the progress of the system.
Eventually it gives:

    === TEST EXECUTION SUMMARY ===
               Voron.Tests  Total: 317, Errors: 0, Failed: 0, Skipped: 0, Time: 494.778s

so it would be nice to have some indication, such as the number of tests that were run, the failures so far, etc.

**Comment by bradwilson** [comment]
Pass the `-verbose` switch and it will list each test to the screen as it's being started.
