### ISSUE TITLE
Is xunit loading config files for the test dlls?

### ISSUE THREAD

**Issue by victorhurdugaci** [xunit/xunit#732]
We're migrating the ASP.NET source code from dnx to dotnet and we hit an interesting issue today. In dotnet we use classic xunit console runner to run tests on desktop CLR and since there's no longer a custom assembly loader, we have to rely on binding redirects to load the correct assemblies.

Here's the issue: if you unpack the archive and run `xunit.console.exe Microsoft.AspNet.Authentication.Test.dll` you'll get

```
      System.IO.FileLoadException : Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one
of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

Now, take the binding redirects from `Microsoft.AspNet.Authentication.Test.dll.config` and move them in `xunit.console.exe.config`. Run the console runner again and tests should work now.

The question is: isn't xunit loading the config file for the test DLL? Do we have to add the binding redirects into the console runner's config file or can they be separate?

Here's the archive: [dnx451.zip](https://github.com/xunit/xunit/files/87913/dnx451.zip)

cc @pakrym @anurse

**Comment by bradwilson** [comment]
When there is no app domain, there is no way to switch the configuration file. Binding redirects is the first most obvious thing that's broken here, as you've run across. You will find others.

**Comment by anurse** [comment]
This is on desktop CLR though, does xunit not use an appdomain there? We haven't set `-noappdomain`

**Comment by bradwilson** [comment]
The question isn't the runner, it's the tests.

When you write a desktop unit test (which links against xunit.execution.desktop.dll), then we can use app domains. When you write a dotnet unit test (which links against xunit.execution.dotnet.dll), we cannot, because nothing that we would expect to be remoteable actually is (because there's no MBRO in PCL 259, which is what xunit.execution.dotnet.dll is).

**Comment by bradwilson** [comment]
FWIW, I assumed you'd end up with a new loader to deal with this problem eventually.

**Comment by anurse** [comment]
Aha, that help clarify things. Thanks!

**Comment by victorhurdugaci** [comment]
Makes sense. Thanks much!
