### ISSUE TITLE
Fail to add xunit.runner.msbuild nuget package if project.json is used

### ISSUE THREAD

**Issue by jmelosegui** [xunit/xunit#734]
Having the following project

![image](https://cloud.githubusercontent.com/assets/450246/12333093/32314824-bac0-11e5-8a15-e819bab66a2f.png)

and the following project.json configuration:

``` json
{
  "supports": { },
  "dependencies": {
    "xunit.runner.msbuild": "2.1.0"
  },
  "frameworks": {
    ".NETFramework,Version=v4.6.1": { }
  },
  "runtimes": {
    "win": { } 
  }
}
```

When restoring nuget packages I get this error:

```
xunit.runner.msbuild 2.1.0 is not compatible with .NETFramework,Version=v4.6.1.
```

As soon as I replace the `project.json` file by `packages.config` with the following configuration

``` xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="xunit.runner.msbuild" version="2.1.0" targetFramework="net461" />
</packages>
```

Restoring nuget packages runs without any problem.

I don't know if this is related with `xunit.runner.msbuild` nuget package but I can definitively add the `xunit.runner.visualstudio` nuget package to the same project using the same `project.json` file.

**Comment by jmelosegui** [comment]
CC @cbarest

**Comment by bradwilson** [comment]
Issues with project.json based package restoration should be reported to the NuGet team.

**Comment by ttrevorr** [comment]
this has been reported with the nuget team but no update as of yet.
https://github.com/NuGet/Home/issues/1936
Just here to report that I am seeing the same problem.

**Comment by jmelosegui** [comment]
@ttrevorr, seams to be a bug in `xunit.runner.msbuild` nuget package (based on [this comment](xunit.runner.msbuild nuget package), _I haven't tested it though_)

**Comment by ttrevorr** [comment]
thanks for the update... hopefully this issue can get reopened.

**Comment by bradwilson** [comment]
This week is a "pleasant bunch of undocumented bullshit from the NuGet team week" I see. :-p

**Comment by bradwilson** [comment]
Closed for age.
