### ISSUE TITLE
Assertion message formatting according to data types

### ISSUE THREAD

**Issue by zijianhuang** [xunit/xunit#735]
```
    [Fact]
    public void TestDouble()
    {
        double d = 0.3;
        double d1 = 0.1;
        double d2 = 0.2;
        Assert.Equal(d, d1+d2);
    }
```

will fail with message like:
Result Message: 
Assert.Equal() Failure
Expected: 0.3
Actual:   0.3

It will be better to show:
Result Message: 
Assert.Equal() Failure
Expected: 0.3
Actual:   0.30000000000000004

So the "ugly" nature of floating point could be revealed immediately.

**Comment by bradwilson** [comment]
Owing to the imprecision of the data types, when comparing floats or doubles, you should use the precision override of `Assert.Equal`:

https://github.com/xunit/xunit/blob/8d6d4e0d363027ed029be96567b740eaf743fa2e/src/xunit.assert/Asserts/EqualityAsserts.cs#L38-L56

**Comment by zijianhuang** [comment]
@bradwilson, 

I am well aware of such overload of Assert.Equal. And I myself basically avoid comparing floating points, but use decimal in business applications, though in scientific applications, the suggested overloading with precision is very good.

My point is that junior developers (not trained with basic computing science concepts) had often run into simple comparisons of floating points, and got puzzled by the error message while is literally confusing.

**Comment by bradwilson** [comment]
Closed for age.
