### ISSUE TITLE
The runner may have to be updated for RC2.

### ISSUE THREAD

**Issue by margagn** [xunit/xunit#737]
I upgraded my .NET version to RC2 (1.0.0-rc2-16357) and I get the following exception when trying to run my unit test. It appears to be coming from the Runner. Is this a knows issue? Is there a way to work around this?
```
PS D:\src\UnitTests> dnx test
System.TypeLoadException: Could not load type 'Microsoft.Extensions.PlatformAbstractions.IApplicationShutdown' from assembly 'Microsoft.Extensions.PlatformAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Xunit.Runner.Dnx.Program..ctor(IServiceProvider services)
```

**Comment by bradwilson** [comment]
Are you running the CI build? http://myget.org/gallery/xunit

Use `xunit 2.1.0` and `xunit.runner.dnx 2.1.0-rc2-build209`.

**Comment by margagn** [comment]
Thank you @bradwilson. It works!
