### ISSUE TITLE
Add Assert.Raises support for EventHandler and other event handler types

### ISSUE THREAD

**Issue by RehanSaeed** [xunit/xunit#740]
[This](https://github.com/xunit/xunit/pull/688#issuecomment-173935005) is very cool but this only seems to support the EventHandler<T>. What about EventHandler without the <T> or indeed events that don't use the standard EventHandler<T> handler like the PropertyChangedEventHandler?

Reactive Extensions has methods very similar to this and provides overloads for all of the above.

**Comment by bradwilson** [comment]
Closed for age.
