### ISSUE TITLE
Support net46/dnx46 TFMs for xunit.runner.dnx

### ISSUE THREAD

**Issue by davidpeden3** [xunit/xunit#742]

**Comment by NullVoxPopuli** [comment]
any updates on this?

**Comment by onovotny** [comment]
Due to how much change there is to ASP Net 5, we're not doing anything until RC2 ships. Hopefully the NuGet mess will be straightened out by then.

**Comment by NullVoxPopuli** [comment]
it looks like I got it to  work by including just 'runners'

```
    "dependencies": {
        "Microsoft.Extensions.PlatformAbstractions": "1.0.0-*",
        "System.Reflection": "4.1.0-*",
        "xunit": "2.1.0-*",
        "xunit.runners": "2.0.0",
    },
```

**Comment by NullVoxPopuli** [comment]
granted, it could still be using one of my dnx targets to run the tests :-\

**Comment by NullVoxPopuli** [comment]
see: https://github.com/NullVoxPopuli/csharp-extensions/blob/master/project.json

**Comment by bradwilson** [comment]
Closed for age.
