### ISSUE TITLE
Can't generate NUnit reports when using traits

### ISSUE THREAD

**Issue by TAGC** [xunit/xunit#744]
I have my build server configured to run a nightly SonarQube analysis of my projects, and after investigating an issue with this for one of them I noticed that a test report output had not been being generated for several commits. I managed to trace the problem back to a commit where I'd started annotating some of my XUnit tests with trait attributes ("Category=Value").

I'm using the following MSBuild task to run tests and perform code coverage analysis:

```
<Target Name="CodeCoverage" DependsOnTargets="Build">
    <MakeDir Directories="$(ReportsPath)" />
    <Exec Command="$(OpenCoverPath)\tools\OpenCover.Console.exe -register:user -target:&quot;$(XUnitConsolePath)\tools\xunit.console.exe&quot; -targetargs:&quot;@(TestAssemblies) -noshadow -nunit $(NUnitOutputFile)&quot; -filter:&quot;-[xunit*]* -[*]System.Diagnostics.Contracts.* -[$(AssemblyName)*]* +[$(MainAssemblyName)*]*&quot; -output:$(OpenCoverOutputFile)" />
    <Exec Command="$(ReportGenPath)\tools\ReportGenerator.exe &quot;$(OpenCoverOutputFile)&quot; &quot;$(ReportsPath)\HTML&quot;" />
</Target>
```

I'm able to consistently avoid this happening if I comment out the trait attributes:

``` cs
[Theory]
//[Trait("Category", "TimeSensitive")]
[InlineData(5)]
[InlineData(50)]
[InlineData(100)]
[InlineData(250)]
public async Task Multimedia_Timer_Should_Fire_Events_At_Specified_Intervals(int interval)
```

I'm able to consistently reproduce this issue by restoring the attributes:

``` cs
[Theory]
[Trait("Category", "TimeSensitive")]
[InlineData(5)]
[InlineData(50)]
[InlineData(100)]
[InlineData(250)]
public async Task Multimedia_Timer_Should_Fire_Events_At_Specified_Intervals(int interval)
```

I suppose this makes sense - NUnit doesn't have the notion of "traits". However, I would like to be able to continue using traits so that I can allow my build server to only run particular types of tests.

**Comment by bradwilson** [comment]
Closed for age.
