### ISSUE TITLE
Suggest using ITestOutputHelper when detecting output is being written to

### ISSUE THREAD

**Issue by citizenmatt** [xunit/xunit#745]
`Console.WriteLine` and friends don't capture output because of parallelisation, but `ITestOutputHelper` isn't very intuitive, and requires a search. How about the framework adding the listeners as in v1, but not capturing the output, just flagging that output was attempted, and reporting the fact to the runner (diagnostic message?). The runner could then display a hint to the user - "Output was detected, but not captured. See http://xunit.github.io/docs/capturing-output.html for more details", which would lead the user to the docs and the correct solution.

Thoughts?

**Comment by wholroyd** [comment]
Same should go for Debug.WriteLine attempts.

**Comment by bradwilson** [comment]
Closed for age.
