### ISSUE TITLE
InlineDataAttribute passing wrong double and float values to test method on OSX

### ISSUE THREAD

**Issue by sherif-elmetainy** [xunit/xunit#747]
I had tests running fine on Windows and Ubuntu while failing on OSX El Capitan version 10.11.3. I narrowed the issue down to InlineDataAttribute passing wrong value to my test method.

I created a simple reproduction of the bug. Please note that it runs fine under Windows and Ubuntu and the issue occurs when running on OSX using `DNX x64 coreclr 1.0.0-rc1-update1`.

My project.json

``` json
{
  "dependencies": {
    "xunit": "2.1.0",
    "xunit.runner.dnx": "2.1.0-rc1-build204"
  },
  "commands": {
    "test": "xunit.runner.dnx"
  },
  "frameworks": {
    "dnxcore50": {
      "dependencies": {
      }
    }
  }
}
```

Class1.cs

``` csharp
using Xunit;

public class Class1
{
    [Theory]
    [InlineData(0.5d, 0.25d)]
    public void TestValues(double a, double b)
    {
        Assert.Equal(0.5d, a);
        Assert.Equal(0.25d, b);
    }
}
```

I expect this test to pass, or if it doesn't pass, the actual value to be close to 0.25 (with double there should be no loss in the value 0.25 since it's 1/4). The actual result on MacOS is:

```
xUnit.net DNX Runner (64-bit DNXCore 5.0)
  Discovering: test
  Discovered:  test
  Starting:    test
    Class1.TestValues(a: 0.5, b: 0.25) [FAIL]
      Assert.Equal() Failure
      Expected: 0.25
      Actual:   2.40172938026497E-314
      Stack Trace:
           at Class1.TestValues(Double a, Double b)
  Finished:    test
=== TEST EXECUTION SUMMARY ===
   test  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 0.348s
```

As you can see the actual value is 2.40172938026497E-314 which is no where close to the expected value. If I am doing something wrong, I am sorry, but I had been looking at this issue for few hours. I had it in a bigger project, and I first suspected my code and spent a while debugging until I narrowed it down to this.

**Comment by bradwilson** [comment]
Closed for age.

**Comment by mysteryx93** [comment]
I get the same issue in Windows. Why is this closed with no explanation nor resolution?
