### ISSUE TITLE
Visual Studio 2015 (Update 1) cannot find my tests.

### ISSUE THREAD

**Issue by regionbbs** [xunit/xunit#748]
I use Visual Studio 2015 with Update 1 and XUnit to test my solution, I made sure my project had installed XUnit and XUnit Visual Studio Runner 2.1.

I created a Test Project, added XUnit package (and VS runner), and add some tests marked [Fact], but I can't find any test in Test Explorer. I tried to rebuild solution several times, but this issue still exists.

How can I do to resolve this issue?
Thank you.

**Comment by scripni** [comment]
Are you perhaps building x64 and have tests configured for x86? Most of my projects are explicitly configured for x64 only and I had this issue, changing VS settings to run x64 tests fixed it for me: https://msdn.microsoft.com/en-us/library/ee782531.aspx

**Comment by regionbbs** [comment]
Thank you, but I use "Any CPU" mode.
This issue can't reproduce every times, My another computer has the same environment, but it can work.

**Comment by dealproc** [comment]
Take a look at #295, as I think this may be a duplicate.  Try these instructions from @bradwilson and see if they solve your issue:

> Also, please make sure you've cleaned out Visual Studio's runner cache. If it gets corrupted, Visual Studio will permanently misbehave until it's deleted. To clear the cache, shut down all instances of Visual Studio, then delete the folder %TEMP%\VisualStudioTestExplorerExtensions (honestly, it probably wouldn't hurt to delete everything in %TEMP% that can be deleted).

**Comment by regionbbs** [comment]
Thank you, it works :+1:

**Comment by litichevskiydv** [comment]
I followed instruction http://xunit.github.io/docs/getting-started-dnx.html, but Test Explorer could not find  my tests. What can I do?
Thank you.

**Comment by realavaloro** [comment]
It didn't work for me. I've tried with
```
"xunit": "2.2.0-beta1-build3239",
 "xunit.runner.visualstudio": "2.2.0-beta1-build1144"
```
in VS2015 Update2
Test Explorer doesn't find anything, no matter whether I re-build, delete TEMP folder, restart PC, change architecture x86 or x64 in test settings, etc.

It's a dedicated project for tests targeting the framework `dnxcore50`

**Comment by bradwilson** [comment]
@realavaloro xunit.runner.visualstudio is for class library and device projects. xunit.runner.dnx is for DNX projects. Please follow the Getting Started directions: http://xunit.github.io/docs/getting-started-dnx.html

**Comment by realavaloro** [comment]
ah yes, I apologize. I misunderstood the documentation, adding the dependency `"xunit.runner.dnx": "2.1.0-rc1-build204"` and removing the unnecessary `runner.visualstudio` got it fixed. Thank you.

**Comment by adamcogx** [comment]
I'm having issues with VS 2015 Update 2, I have tried everything mentioned so far:

- Delete cache directory
- make changes to paths in Projects settings
- I am working against a class library for desktop, and have uninstalled and reinstalled VS Test Runner 2.1.0,  it goes through the discovery process but returns 0 tests.

**Comment by bradwilson** [comment]
Closed for age.
