### ISSUE TITLE
How to debug a specific set of data of a theory?

### ISSUE THREAD

**Issue by tongbong** [xunit/xunit#749]
Assuming the code below and using resharper as the test runner, resharper shows a test for each individual set of data. 

Unfortunately it is impossible to debug only one set of data, or is there a way to do it? 

```
        public static IEnumerable<object[]> Data()
        {   yield return new object[] { 0, 0 }; // set 1
            yield return new object[] { 0, 1 }  // set 2}

        [Theory]
        [MemberData("Data")]
        public void CheckStructure(int left, int right)
        {
              // Test something
        }
```

**Comment by bradwilson** [comment]
It's probably better to ask this question on https://github.com/xunit/resharper-xunit since it's a question specific to the Resharper runner.

**Comment by tongbong** [comment]
Yes you are correct, thanks for the pointer.
I close this issue.

**Comment by joehoppe** [comment]
Was this feature deprecated? Even without ReSharper, it used to work in Visual Studio 2015, but doesn't work in 2017 or 2019.

**Comment by bradwilson** [comment]
Try turning off source-based discovery, and see if the feature starts working again.

Tools > Options > Test > General > Uncheck "Discover tests in real time from source files"

If that's the problem, then it's out of our hands. We don't control the source-based discovery that's built into VS 2017+.
