### ISSUE TITLE
Dependency Type mismatch in xunit testing

### ISSUE THREAD

**Issue by regionbbs** [xunit/xunit#751]
Hi, 

I created tests for my database repository service, I use my dependency injection solution to resolve dependencies in repository service.

I have this statement:
`var strategyProvider = c.Resolve<IDbSchemaStrategyProvider>();`

When I run my test, I got InvalidCastException message, I confirmed concrete type is matched to interface type, but I found a issue:

> Concrete type's assembly is my application folder.
> Interface type's assembly is in TEMP folder.

But interface type's assembly is also placed into application folder, I confirmed it's loaded successfully in test debug.

What reason can be occur this issue? and any solution?
Thank you.

**Comment by bradwilson** [comment]
Closed for age.
