### ISSUE TITLE
xUnit.NET Web site currently 404s

### ISSUE THREAD

**Issue by SeanKilleen** [xunit/xunit#753]
Currently, the xUnit.net site is a big ol' 404: 

![image](https://cloud.githubusercontent.com/assets/2148318/12697781/8b18eca8-c759-11e5-8051-4f2461e34744.png)

However, the project does indeed have an awesome GitHub pages site: http://xunit.github.io/ 

So I'm thinking let's put those things together.

I previously posted a PR at https://github.com/xunit/xunit.github.io/pull/21 to address this, but I think since then the issue it initially referred to was closed in favor of using this repo for all issues. So I'm re-opening that issue here.

**Comment by bradwilson** [comment]
Closed for age.
