### ISSUE TITLE
xunit.abstractions not compatible with DNXCore50

### ISSUE THREAD

**Issue by scionwest** [xunit/xunit#754]
I have a dnxcore50 project that has a dependency on `xunit 2.2.0-*`. When I run `dotnet restore` using the `CLI` it fails with the following message:

```
warn : Detected package downgrade: System.Security.Cryptography.Algorithms from 4.0.0-rc3-23729 to 4.0.0-beta-23516 
Lightmap.Core.Tests (>= 1.0.0) -> xunit.runner.dnx (>= 2.1.0-rc1-build204) -> xunit.runner.reporters (>= 2.1.0) -> System.Net.Http (>= 4.0.1-rc3-23729) -> runtime.osx.10.10.System.Net.Http (>= 4.0.1-rc3-23729) -> System.Security.Cryptography.Algorithms (>= 4.0.0-rc3-23729) 
Lightmap.Core.Tests (>= 1.0.0) -> xunit.runner.dnx (>= 2.1.0-rc1-build204) -> System.Security.Cryptography.Algorithms (>= 4.0.0-beta-23516)
error: xunit.abstractions 2.0.0 is not compatible with DNXCore,Version=v5.0.
error: Some packages are not compatible with DNXCore,Version=v5.0.
error: xunit.abstractions 2.0.0 is not compatible with DNXCore,Version=v5.0 (osx.10.11-x64).
error: Some packages are not compatible with DNXCore,Version=v5.0 (osx.10.11-x64).
info : Committing restore...
info : Restore failed in 32922ms.
```

It looks like the `xunit.abstractions` is not compatible. Is that a dependency that `xunit` has, or can I include a version of `xunit` that does not take that dependency? 

This is what my `project.json` looks like:

```
{
    "version": "1.0.0-*",
    "description": "",
    "authors": [
        ""
    ],
    "tags": [
        ""
    ],
    "projectUrl": "",
    "licenseUrl": "",
    "tooling": {
        "defaultNamespace": "<%= namespace %>"
    },
    "dependencies": {
        "Lightmap.Core": "1.0.0",
        "xunit": "2.2.0-*",
        "xunit.runner.dnx": "2.1.0-rc1-build204",
        "NETStandard.Library": "1.0.0-*"
    },
    "frameworks": {
        "dnxcore50": {
            "dependencies": {}
        }
    }
}
```

**Comment by scionwest** [comment]
I tried to follow the guidance on #737 by adding the CI build packages and referencing those versions explicitly in my `project.json`. However during a restore, the server 404s.

**Comment by scionwest** [comment]
I added the `myget` feed and followed the guidance on issue #737. Both `xunit` and the `xunit.runner.dnx` will not restore from that feed, the restore error is the same as my OP.

**Comment by scionwest** [comment]
Anyone have any kind of an update on what I need to do in order to get this compiled against the CLI?

**Comment by bradwilson** [comment]
We have no intention of working on this until after RC 2 has shipped. There is too much churn to waste time on it now.

**Comment by endeffects** [comment]
same issue here, but sometimes it works with the "dotnet restore" command

**Comment by bradwilson** [comment]
Closed for age.
