### ISSUE TITLE
Huge startup time between "Discovered: <assembly>" and "Starting: <assembly>" for some assemblies on console runner 2.0.0

### ISSUE THREAD

**Issue by hach-que** [xunit/xunit#755]
We're seeing huge test runner startup times on some assemblies between the discovery of the assembly and starting the tests on the assembly.  Almost all of this time is taken up marshalling calls across proxies and performing remoting.  By huge we're talking a 5 minute wait for the tests to actually start running.

This is what I see in dotTrace when I profile until the tests start running:

![image](https://cloud.githubusercontent.com/assets/504826/12736424/5c214178-c9a4-11e5-89e9-2eda92f891ba.png)

When looking at how frequently it occurs and when, I can see it's happening multiple times inside Main before the tests start:

![image](https://cloud.githubusercontent.com/assets/504826/12736438/85d51508-c9a4-11e5-84fd-66f52147e221.png)

Unfortunately there's no further information because all of the time is allocated to the "[unknown]" block, and there's no information about what's happening inside there.

Is there any way that we can diagnose this issue further?  It is having a significant impact on running our tests.

**Comment by bradwilson** [comment]
Duplicate: https://github.com/xunit/xunit/issues/353

**Comment by bradwilson** [comment]
Closed for age.
