### ISSUE TITLE
Dnx code contracts?

### ISSUE THREAD

**Issue by dotnetshadow** [xunit/xunit#756]
How do you run tests with code contracts? CONTRACTS_FULL setting in a dnx project?

**Comment by bradwilson** [comment]
No clue. I don't know anything about code contracts.

**Comment by dotnetshadow** [comment]
I am trying to accomplish this with asp.net mvc core 1.0 or in unit tests
http://www.richard-banks.org/2009/11/unit-testing-code-contracts-with-xunit.html

**Comment by bradwilson** [comment]
Closed for age.
