### ISSUE TITLE
Assemblies are loaded differently when appdomains are turned off (xunit 2.1.0)

### ISSUE THREAD

**Issue by hach-que** [xunit/xunit#758]
With AppDomains turned on, the tests we have written pass and load assemblies as intended.  When we turn off AppDomains (to improve performance), we get exceptions relating to assembly load failures, even when the assembly exists in the same folder as the test assembly (I've removed some information from this paste):

```
C:\Code\....\Tests\.....Tests.Integration\bin\Debug>..\..\..\..\lib\packages\xunit.runner.console.2.1.0\tools\xunit.console.exe .....Tests.Integration.dll -noshadow -noappdomain
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
  Discovering: .....Tests.Integration
  Discovered:  .....Tests.Integration
  Starting:    .....Tests.Integration
    .....Tests.Integration.IocTests+........... [FAIL]
      System.Runtime.Serialization.SerializationException : Unable to find assembly 'NHibernate, Version=3.1.0.4000, Culture=neutral, PublicKeyToken=aa95f207798dfdb4'.
      Stack Trace:
           at System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly()
           at System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(BinaryAssemblyInfo assemblyInfo, String name)
           at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
           at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
           at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
           at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
           at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
        C:\Code\....\Assemblies\.....Domain\ARSupport\ActiveRecordStarterWithCaching.cs(82,0): at .....Domain.ARSupport.ActiveRecordStarterWithCaching.LoadNHibernateConfigurationFromCache(ISessionFactoryHolder holder, List`1 rootTypes)
        C:\Code\....\Assemblies\.....Domain\ARSupport\ActiveRecordStarterWithCaching.cs(58,0): at .....Domain.ARSupport.ActiveRecordStarterWithCaching.Initialize(Assembly assembly, IConfigurationSource source, List`1 rootTypes)
        C:\Code\....\Assemblies\.....Domain\ARSupport\ActiveRecordInitialiser.cs(47,0): at .....Domain.ARSupport.ActiveRecordInitialiser.Initialise(Func`1 listenersFactory, Func`1 currentUserFactory, Boolean isInWebApp)
        C:\Code\....\Tests\.....Integration.Helpers\TestUtils\StaticStateInitialiser.cs(30,0): at .....Integration.Helpers.TestUtils.StaticStateInitialiser.Initialise()
        C:\Code\....\Tests\.....Tests.Integration\Ioc\IocTests.cs(2163,0): at .....Tests.Integration.IocTests........ctor()
```

This happens even though `C:\Code\.....\Tests\......Tests.Integration\bin\Debug\NHibernate.dll` exists.  We never had this issue on 1.9.2 (which didn't use AppDomains), and we didn't have this issue on 2.0.0 (which does use AppDomains).

It should be noted that on line 27 of StaticStateInitialiser, we make an explicit reference to NHibernate as well in an attempt to fix this issue:

```
var queryClass = typeof(NHibernate.Cfg.Configuration);
```

However, that doesn't make any difference.  Given there's no AppDomain here, I don't understand how this can fail to load, because NHibernate should already be loaded into the AppDomain.

**Comment by hach-que** [comment]
After I worked around this by overloading the AssemblyResolve event in the current AppDomain, I found that Ninject was no longer able to automatically load extensions either.

**Comment by bradwilson** [comment]
There's nothing we can do about this today.

When testing with separate app domains, the app domain for the unit tests sets its base path as the path where the unit test DLL is loaded. Everything is loaded into the default (implicit) load context of that app domain.

When testing without a separate app domain, the base path is the base path of the runner executable (or whatever executable launched the testing process). DLLs are loaded explicitly into a separate load context, which does not share DLLs with the default implicit load context. Lots of things are affected here: configuration from your unit tests is not used (the configuration file of the runner is used instead); implicit loads are affected; binding redirects are affected.

This behavior is defined by the .NET Framework. We have no control over this.

**Comment by hach-que** [comment]
Is it not possible to just set the base path of the default context to the location where the unit test DLL is?  We aren't running multiple DLLs per-process.

Is there some way we can change the base path at runtime, or add the unit assembly's directory to the assembly search path?  I don't mind if we have to workaround this in our test code, but we can't really continue to use AppDomains given the huge performance hit they cause.

**Comment by bradwilson** [comment]
> Is it not possible to just set the base path of the default context to the location where the unit test DLL is? 

Nope. You can only set the base path of the app domain when it's created. Once it's created, it is what it is. You're stuck with the path where the runner lives as your base path.

> we can't really continue to use AppDomains given the huge performance hit they cause.

I am working on some performance improvements for 2.2 regarding app domains. I have some additional ideas that will probably take longer than 2.2 to implement that will yield even more performance improvements.

**Comment by bradwilson** [comment]
Closed for age.
