### ISSUE TITLE
Why can't I use params for Theory method parameters

### ISSUE THREAD

**Issue by klimcio** [xunit/xunit#763]
Hi,

I'm a new guy working with xUnit and I was wondering why can't I do something like this:

```
[Theory]
[InlineData("test", "", "thx bai")]
[InlineData("", "test", "thx bai")]
[InlineData("abc", "def", "ghi")]
[InlineData("abc", "ABC", "abc", "ABC")]
public void Testing_String_Array(params string[] strings)
{
        var commonPrefix = MyClass.DoMyChores(strings);

        commonPrefix.Should().Equals(string.Empty);
}

```
I aim at test readability. I tried to the same with MemberData, but that lead me to...

```
public static IEnumerable<object[]> ValidStrings
{
        get
        {
                return new[]
                {
                        new object[] { new string[] { "test", string.Empty, "thx bai" } },
                        new object[] { new string[] { string.Empty, "test", "thx bai" } },
                        new object[] { new string[] { "abc", "def", "ghi" } },
                        new object[] { new string[] { "abc", "ABC", "abc", "ABC" } }
                };
        }
}

```

Which works, but looks overly complicated.

Is there a chance that this will be fixed?

**Comment by bradwilson** [comment]
You can't use `params` because this is purely a compiler feature. The compiler looks at your source code and converts the individual parameters into the array for you.

xUnit.net's code doesn't run at the compiler layer. The params feature is not available to it.

You should change your code:

```csharp
[Theory]
[InlineData(new[] { "test", "", "thx bai" })]
[InlineData(new[] { "", "test", "thx bai" })]
[InlineData(new[] { "abc", "def", "ghi" })]
[InlineData(new[] { "abc", "ABC", "abc", "ABC" })]
public void Testing_String_Array(string[] strings)
{
        var commonPrefix = MyClass.DoMyChores(strings);

        commonPrefix.Should().Equals(string.Empty);
}
```

**Comment by klimcio** [comment]
Now I understand :-) Thanks, Brad, I'll go with your suggestion!

**Comment by klimcio** [comment]
Unfortunately, the compiler failed to cooperate as declaring an array in the attribute returned an exception: **An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type**.

Well, I guess I'll need to stick to the old solution.

Thanks, anyway.

**Comment by Niklas-Peter** [comment]
Why does it work in NUnit?

See http://stackoverflow.com/a/34166147/2013911

**Comment by bradwilson** [comment]
It's fixed. What's your problem?

**Comment by Niklas-Peter** [comment]
Sorry, forget it.

**Comment by sjanisz** [comment]
Xunit version 2.5.3, experiencing same issue:
Error	CS0182	An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type

code:
```
[Theory]
[InlineData(new[] { "" })]
public void TargetType(string[] x)
{
}
```

**Comment by bradwilson** [comment]
@sjanisz Yeah, it all basically comes down to the compiler not wanting to cooperate. 😂
