### ISSUE TITLE
xunit.runner.dnx: Environment variable name or value is too long.

### ISSUE THREAD

**Issue by dopic** [xunit/xunit#774]
Hi,

I'm running dnx test runner in a TFS 2015 automated build, using Power Shell. 
In my solution I have three test projects, but two of them throws a "Environment variable name or value is too long." error.

The name of the projects are:
- Promob.ManagerERP.IoC.Test
- Promob.ManagerERP.Api.Test
- Promob.Erp.AssemblyResolver.Test

The strange thing is that the error happens only in two test projects (Promob.ManagerERP.IoC.Test, Promob.ManagerERP.Api.Test), one of them runs successfuly (Promob.Erp.AssemblyResolver.Test).

Some information about the test execution:
[TFS2015-testStep-out.txt](https://github.com/xunit/xunit/files/135032/TFS2015-testStep-out.txt)

The powershell script that I'm using (It has a filter to isolate one of the problematic projects):
[ExecuteTests.txt](https://github.com/xunit/xunit/files/135038/ExecuteTests.txt)

How can I solve this?
There is any way to get more information about the error?

Thanks!

**Comment by rsbavaresco** [comment]
The same happens here but it is not runned from TFS or script file, it is from simple command line `dnx test`

project.json
```
{ 
...
"dependencies": {
    "Microsoft.Extensions.Configuration.Abstractions": "1.0.0-rc1-final",
    "Moq": "4.2.1510.2205",
    "xunit": "2.2.0-beta1-build3239",
    "xunit.runner.dnx": "2.1.0-rc1-build204"
  },
  "commands": {
    "test": "xunit.runner.dnx"
  },
  "frameworks": {
    "dnx451": { 
    }
  }
}
```

**Comment by bradwilson** [comment]
Can you reproduce this by following the [Getting Started](http://xunit.github.io/docs/getting-started-dnx.html) steps exactly?

**Comment by rsbavaresco** [comment]
It is not a problem regarding to `xunit.runner.dnx`. The same error occurs when running another commands, e.g. `dnx web`. 
It seems to be a bug or some strange validation at environment variables (maybe created by dnx at runtime) when DNX loads commands.

Fix it removing some .net dependencies, no one related to xunit.

Thanks

**Comment by bradwilson** [comment]
Closed for age.
