### ISSUE TITLE
xunit.console IRunnerReporter extensibility doesn't work when using dotnet

### ISSUE THREAD

**Issue by DavidObando** [xunit/xunit#775]
Assembly xunit.runner.utility.desktop compiles [its own copy](https://github.com/xunit/xunit/blob/master/src/xunit.runner.utility.desktop/xunit.runner.utility.desktop.csproj#L136) of [Xunit.IRunnerReporter](https://github.com/xunit/xunit/blob/master/src/xunit.runner.utility/Extensibility/IRunnerReporter.cs). The [same is done](https://github.com/xunit/xunit/blob/master/src/xunit.runner.reporters.dotnet/xunit.runner.reporters.dotnet.csproj#L47) by xunit.runner.utility.dotnet.

Project xunit.console has been [linked against xunit.runner.utility.desktop.dll](https://github.com/xunit/xunit/blob/master/src/xunit.console/xunit.console.csproj#L107). 

If one is working with the dotnet CLI code gets linked against xunit.runner.utility.dotnet.dll. When xunit.console iterates over the test assemblies looking for runner reporters it asks whether the class implements interface `IRunnerReporter` by asking `type.GetInterfaces().Any(t => t == typeof(IRunnerReporter))`. For assemblies linked against xunit.runner.utility.dotnet the expression is always false as each type comes from a different assembly, even if they represent the same thing.

I'm not sure if there are other extensibility points affected by this. I'm new to the xunit codebase.

This can be solved by not including common code in each assembly and instead have the code in a shared assembly.

**Comment by bradwilson** [comment]
FYI: We will not be looking at any "dotnet CLI"-related issues until after they have shipped RC 2.

**Comment by bradwilson** [comment]
Also, you should not be using the desktop console runner for dotnet CLI projects. They will use a new runner which has not yet been shipped.

**Comment by DavidObando** [comment]
Sounds good. Thanks!

**Comment by bradwilson** [comment]
Closed for age.
