### ISSUE TITLE
DNX runner, which framework?

### ISSUE THREAD

**Issue by 304NotModified** [xunit/xunit#776]
I read the following article: http://xunit.github.io/docs/getting-started-dnx.html

If I have the following config, as used in the example:

project.json

```
    "dependencies": {
        "xunit": "2.1.0",
        "xunit.runner.dnx": "2.1.0-rc1-build204"
    },
    "commands": {
        "test": "xunit.runner.dnx"
    },
    "frameworks": {
        "dnx451": { },
        "dnxcore50": { }
    }
```

and I run `dnx test`

Which frameworks will the test run on (dnx451,dnxcore50) ? In which order?

**Comment by bradwilson** [comment]
It runs with whatever version of DNX you have activated through DNVM.
