### ISSUE TITLE
Is SerializableType<Uri> serializable?

### ISSUE THREAD

**Issue by Ausm** [xunit/xunit#777]
Hi,

When you have a class like the following:

``` C#
class SerializableType<T> : IXunitSerializable
{
    void IXunitSerializable.Deserialize(IXunitSerializationInfo info)
    {
    }

    void IXunitSerializable.Serialize(IXunitSerializationInfo info)
    {
    }
}
```

Should `SerializableType<Uri>` be serializable?
Because `SerializationHelper.IsSerializable(typeof(SerializableType<Uri>))` returns true, but `SerializationHelper.Serialize(object value)` fails with an `ArgumentException{ Message="We cannot serialize type System.Uri because it lives in the GAC" }`

This leads to a behavior, where TheoryDiscoverer returns multiple XunitTestCase objects, because IsSerializable(dataRow) returns true, but the dnx runner fails when trying to serialize the theory data.

**Comment by bradwilson** [comment]
Do you actually have an implementation of IXunitSerializable? If so, what is it?

**Comment by Ausm** [comment]
My actual implementation is here:
[StaticTheoryData.cs](https://github.com/xunit/xunit/files/136709/StaticTheoryData.cs.txt)

It's ```StaticTheoryData<TSelf>+Item<T>```

And it should be used like this:
```C#
public class Tests
{
	[Theory, ClassData(typeof(Data))]
	public void Theory(string name, Data.Item<Expression<Func<string>>> expression)
	{
		// Test code
	}

	public class Data : StaticTheoryData<Data, string, Expression<Func<string>>>
	{
		static Data()
		{
			Add("Name1", () => "Name1");
			Add("Name2", () => "Name2");
		}
	}
}
```

That's my solution to pre-enumerate non serializable theory data, and it works well for custom types.
But if I use GAC types, TestExplorer doesn't show tests any more.
Reason is xunit.runner.dnx which throws an ArgumentException when VS tries to discover tests.

So It can be either, Data+Item<Expression<Func<string>>> is not serializable by the SerializationHelper, in this case, SerializationHelper.IsSerializable(typeof(Data+Item<Expression<Func<string>>>)) must return false, which it doesn't.
Or it is serializable. In that case SerializationHelper.Serialize(object value) must not throw the ArgumentException, which it does.

Does that make sense?
If not, then I'll make you a clean testproject and explain how to reproduce the problem.

Sorry, I hope I'm not to annoying... ;)

**Comment by bradwilson** [comment]
I'm not clear why it cares about the serializability of the Uri class, unless you are attempting to serialize it. Your class != the Uri class. That's why I wanted to know what the implementation was.

A second question: have you only tried this with DNX, or does it also fail with a straight desktop project?

I'll take a look and see if I can figure out what's going on.

**Comment by Ausm** [comment]
To reproduce it have a look at the following project (Github don't let me upload it as zip, so you need to rename it):
[TestProject.zip](https://github.com/xunit/xunit/files/137744/TestProject.zip.txt)

When I comment the Theory out, VS finds the one fact:
![capture](https://cloud.githubusercontent.com/assets/5859112/13172917/ef91b5c4-d6fa-11e5-9ea2-4d5ddd6b6742.PNG)

When I comment it in, VS finds no test any more, even not the fact which has nothing to do with the in commented theory:
![capture1](https://cloud.githubusercontent.com/assets/5859112/13173003/65e2bc32-d6fb-11e5-86a8-44ef0540a73e.PNG)

I used the "xunit.runner.dnx" to debug, but I think I had the same problem with the vsix extension, or the "xunit.runner.visualstudio".

Running the test via the dnx test command works fine, it's just the enumeration by VS that fails.

**Comment by Ausm** [comment]
Stack trace of the from xunit.runner.dnx thrown ArgumentException:
[stack.txt](https://github.com/xunit/xunit/files/138232/xunit.runner.dnx.stack.txt)

**Comment by Ausm** [comment]
@bradwilson: Did you check that. Should i make a PR?
And if yes, should i make it serializeable, or not serializable?

**Comment by bradwilson** [comment]
No, I haven't had a chance to look into it yet.

**Comment by tofutim** [comment]
I was recently trying to test some changes and ran into this odd error:

> Exception rethrown at [0]: 
>    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
>    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
>    at Xunit.Abstractions.ITestFrameworkDiscoverer.Serialize(ITestCase testCase)
>    at Xunit.Xunit2Discoverer.Serialize(ITestCase testCase)
>    at Xunit.XunitFrontController.Serialize(ITestCase testCase)
>    at Xunit.Runner.VisualStudio.TestAdapter.VsDiscoveryVisitor.CreateVsTestCase(String source, ITestFrameworkDiscoverer discoverer, ITestCase xunitTestCase, Boolean forceUniqueNames, LoggerHelper logger, HashSet`1 knownTraitNames)
> [xUnit.net 00:00:29.1996002] Microsoft.Azure.Mobile.Server.Tables.Test: Error creating Visual Studio test case for CreateContract_CallsGetContractOnDeltaTypes(input: typeof(System.Web.Http.OData.Delta<System.Uri>)): System.ArgumentException: We cannot serialize type System.Uri because it lives in the GAC
> Parameter name: type

**Comment by bradwilson** [comment]
Closed for age.
