### ISSUE TITLE
[Mono] Xunit.console sometimes throws System.TypeInitializationException

### ISSUE THREAD

**Issue by petrroll** [xunit/xunit#778]
Hi, the xunit.console.exe runner seems to throw a `System.TypeInitializationException: The type initializer for 'System.Collections.Generic.List1'` exception sometime in between all tests are finished and summary is printed out. 

It doesn't happen everytime. So far I've encountered it twice out of six builds. Once it happened when some tests failed, once when all passed so it's probably not related to tests themselves. It also seems to be Mono (4.2.2) related issue as I had no problems on Windows.

Full stack trace can be found here: [line 1204](https://travis-ci.org/petrroll/MES/builds/110122444). 
[This build](https://travis-ci.org/petrroll/MES/builds/110134723) also failed once (with the same exception) but was rerun after that which helped.

**Comment by reicheltp** [comment]
I have the same problem that sometime the test are crashing without any reason.

One of the exceptions are also: `System.TypeInitializationException: The type initializer for 'System.Collections.Generic.List1' threw an exception.`

Stack trace can be found at [line 1357](https://travis-ci.org/AntMeNet/AntMeCore/jobs/134031897)

**Comment by bradwilson** [comment]
Closed for age.
