### ISSUE TITLE
DNX runner, uses wrong framework?

### ISSUE THREAD

**Issue by 304NotModified** [xunit/xunit#779]
I have a library which supports the following frameworks:

- .NETFramework,Version=v3.5
- net451
- dotnet5.4
- Silverlight,Version=v5.0

I have a xUnit test project with has the following platforms:

- dnxcore50
- dnx451

When I run the unit tests for dnxcore50 (tested with runner and Visual Studio), I would expect the library with platform dotnet5.4 would be used. But this isn't the case. It looks more that net451 is used. 

How do I fix this?

**Comment by bradwilson** [comment]
I believe you're asking the wrong team. This is a question for the NuGet and/or DNX teams.

**Comment by peter-playtimesolutions** [comment]
I think the xunit code base needs to have the targets changed to support the new net451, etc so they are compatible with the latest aspnet core 1 code base

**Comment by bradwilson** [comment]
@peter-playtimesolutions https://twitter.com/xunit/status/702918824769662976

**Comment by 304NotModified** [comment]
The twitter is clear, but we can still dicuss things?

**Comment by bradwilson** [comment]
Of course, but we won't be taking any actions until after RC 2 ships.

**Comment by 304NotModified** [comment]
The solution is to set the correct runtime in the project settings of the unit test project (and rebuild afterwards)

![image](https://cloud.githubusercontent.com/assets/5808377/13647100/d155371a-e632-11e5-87b7-21c1fd34af01.png)
