### ISSUE TITLE
Feature Request: Running Traitnames ignoring Values

### ISSUE THREAD

**Issue by DLemberger** [xunit/xunit#781]
Hello,

right now we stand in front of the problem, that we have GUI and NON-Gui Tests marked with different Traits. Within the GUI Tests we use [Trait("GUI","")] so we have different Tests for the different Pages on our Website.

What I want to do now is configure our Jenkins to run within different Builds sometimes only, but sometimes I just want to run every single GUI Test, therefore it would be nice to have a feature to run every Test with -Trait "GUI=*" .. for example. So the console runner ignores the value of the Trait name and just runs every Test he finds with Trait name: GUI

I know there is a workaround with flagging all the Tests with 2 different Traits [Trait("XYZ","GUI")] but we actually don't want to use more flags than actually needed as it makes the Trait Overview in the Test Explorer within Visual Studio more and more unreadable.

Would really love to have this feature added in the future - hopefully soon.

Best regards,
Dominik Lemberger

**Comment by bradwilson** [comment]
Closed for age.
