### ISSUE TITLE
Question: Is there a way to get the success/failure status from a fixture?

### ISSUE THREAD

**Issue by pebezo** [xunit/xunit#784]
When working with a fixture, in the Dispose() function we can do some cleanup. However, I'd like to do the cleanup only if one or more tests have failed. Is there a way out the status of the run (failed/passed) from inside the Dispose() function? Thanks.

**Comment by bradwilson** [comment]
Nope. Sorry.

**Comment by pebezo** [comment]
OK, thanks.
