### ISSUE TITLE
Console runner: exclude tests by namespace

### ISSUE THREAD

**Issue by D0tNet4Fun** [xunit/xunit#785]
Hi,

I have a test project that is getting large and it takes several minutes to run all its unit tests. The assembly where the code under test is, contains two features F1 and F2, in different namespaces. This structure is mirrored in the test project. I was thinking to 'split' it so that I can run tests for F1 and F2 in parallel. I don't want to change the code under test or to add metadata in the test project - I would, but now is not the time. 

I can use the -namespace option to include everything that is in Project.UnitTests.F1, but then I need some other option which includes everything that is _not_ in Project.UnitTests.F1. I was thinking of -nonamespace (to be consistent with -notrait etc). Note that I can't simply use '-namespace Project.UnitTests.F2' because there are other namespaces such as Project.UnitTests.X, Project.UnitTests.Y etc.

If you think this feature is useful, I can create a PR based on https://github.com/D0tNet4Fun/xunit/commit/16f7a4982ca88e9f4bbb0962a38a81e9a2cc3976.

Thanks!

**Comment by bradwilson** [comment]
Closed for age.
