### ISSUE TITLE
Executable test assemblies to control their own execution

### ISSUE THREAD

**Issue by phliberato** [xunit/xunit#790]
In NUnit I can execute test assemblies to control their own execution using the AutoRun class.
"new NUnitLite.AutoRun().Execute(nunitArgs);"

Is there some way to do this using XUnit?

The code:
https://github.com/nunit/nunit/blob/9a6c91c97567a7602a5428a201188a59163cb014/src/NUnitFramework/nunitlite/AutoRun.cs

**Comment by bradwilson** [comment]
Closed for age.
