### ISSUE TITLE
Can I get more parallelism than a 'collection'?

### ISSUE THREAD

**Issue by cottsak** [xunit/xunit#792]
Without the aid of tools like NCrunch, I can't seem to parallelise my tests more than the [collection scope](https://xunit.github.io/docs/running-tests-in-parallel.html). Is there a way to have every single test running in parallel? I'm happy to take responsibility for isolating them. :smiley:

**Comment by bradwilson** [comment]
Sorry, the smallest level of parallelism in the system is the test collection (by default, one per test class). Overriding this behavior could be done with the extensibility points, but with significant effort (I'm not 100% sure how I'd do it until I tried to do it, to be honest).

**Comment by cottsak** [comment]
Thanks. Could you point me to the extensibility points so I can take a look at the work involved?

**Comment by bradwilson** [comment]
We really don't have any official documentation for it; what we do have is samples that use them. The most complete would be this one: https://github.com/xunit/samples.xunit/tree/master/ObservationExample

**Comment by godrose** [comment]
@bradwilson  Any development on this / quick explanation of the concept of *Observations*?

**Comment by bradwilson** [comment]
To be clear: we are not doing any work for this.

Observation is just the sample that shows using the extensibility points. It is not a solution to the specific original request.

**Comment by cottsak** [comment]
Current workarounds: 

* [NCrunch](http://www.ncrunch.net/) in VS: uses it own parallelism rules before dispatching to each runner.
* For Core, I was using `dnx watch` (now `aspnet watch`?) and my colleague @JakeGinnivan built a wrapper which enabled better test reporting on the command line (however this is entirely limited to xunit's parallelism options)
* Lastly, [tddstud10](https://github.com/parthopdas/tddstud10) might be another option. I'm not sure of the details but it's worth checking out.

**Comment by rquackenbush** [comment]
Dumb question - how do I execute the tests in the ```ObservationExample``` project?

**Comment by bradwilson** [comment]
Closed for age.
