### ISSUE TITLE
how do we read the settings from json file passed as argument in dnx test command?

### ISSUE THREAD

**Issue by gtuteja** [xunit/xunit#793]
Hello Team

I want to set some values to be read in the test based on the target environment that the tests are pointing to. dnx test command accepts configuration file in the command line. I was quite excited to see that but I don't know how do I read the values in the configuration file in the tests.

the command is 
dnx test appsettings.Development.json 

How can I read key values in appsettings.Development.json in my tests?

**Comment by bradwilson** [comment]
That configuration file is not intended for end users; it's intended for xUnit.net itself. As such, we offer no facility for reading from that file.

**Comment by gtuteja** [comment]
Thank you Brad for supersonic response. Is there any recommended practice for it? Essentially I will be running tests from Jenkins pointing to various environments and I would like to be able to ready the target urls in the test based on "something". I can't use the environment variables because the tests will run on our CI box. I thought if I could pass command line argument either with the target environment value or configuration file that I can read from then that could be resolved.

I know I can run a task as part of CI to update appsettings.json to reflect the correct url but that would be hacky...It would be nice to pass in command line argument

Any thoughts?

**Comment by bradwilson** [comment]
Why can't you use environment variables? Jenkins can absolutely set environment variables for you before running your tests.

**Comment by gtuteja** [comment]
From the same Jenkins box, I would be firing off tests against dev, qa and production environments. Are you saying before running test project set the environment variable and reset when done?

**Comment by bradwilson** [comment]
You don't run the tests on the Jenkins box? If not, then you're right, you're on your own to figure this out.

**Comment by gtuteja** [comment]
I found EnvInject plugin...I guess you were talking about that...

Thanks.

From: Preet Tuteja <gtuteja@solarcity.com<mailto:gtuteja@solarcity.com>>
Date: Monday, March 7, 2016 at 3:28 PM
To: xunit/xunit <reply@reply.github.com<mailto:reply@reply.github.com>>, xunit/xunit <xunit@noreply.github.com<mailto:xunit@noreply.github.com>>
Subject: Re: [xunit] how do we read the settings from json file passed as argument in dnx test command? (#793)

From the same Jenkins box, I would be firing off tests against dev, qa and production environments. Are you saying before running test project set the environment variable and reset when done?

**Comment by bradwilson** [comment]
Closed for age.
