### ISSUE TITLE
Adding traits to tests without a trait attribute?

### ISSUE THREAD

**Issue by stephentoub** [xunit/xunit#795]
Is there any way to have a trait discoverer that would run over all discovered tests rather than just those attributed with an attribute that directly ties back to that trait discoverer?

For example, if I wanted to do some pattern matching on tests' names and give them traits based on that without having to add an attribute to each test, is that possible?  Or if i simply wanted to assign a particular trait to every test (again without manually attributing each), is that possible?

**Comment by bradwilson** [comment]
Without using an extensibility hook, no, this is the only way to do that today.

The extensibility model allows you to completely redefine any rules you want. Everything is possible if you want to code enough classes. :) https://github.com/xunit/samples.xunit/tree/master/ObservationExample

**Comment by stephentoub** [comment]
Ok, thanks.
