### ISSUE TITLE
TaskCanceledException translated to TimeoutException during assert

### ISSUE THREAD

**Issue by tillig** [xunit/xunit#796]
This test seems to incorrectly pass:

``` csharp
[Fact]
public void ShouldFail()
{
  // Incorrectly thinks the TaskCanceledException is
  // a TimeoutException and passes.
  Assert.ThrowsAsync<TimeoutException>(() => { throw new TaskCanceledException(); });
}
```

However, if I manually try/catch and verify the exception, things work as expected.

``` csharp
[Fact]
public async void DoesFail()
{
  try
  {
    await Task.Delay(1);
    throw new TaskCanceledException();
  }
  catch(Exception ex)
  {
    // Correctly determines the type is NOT TimeoutException.
    Assert.IsType<TimeoutException>(ex);
  }
}
```

**Comment by epsitec** [comment]
This is not a bug in `xunit`. You are not using the API properly. Note that `ThrowsAsync<T>` is itself an asynchronous method. You should change your test code to:

```cs
[Fact]
public async Task ShouldFail()
{
  await Assert.ThrowsAsync<TimeoutException>(() => { throw new TaskCanceledException(); });
}
```

and you'll see that the assert will fail as you expected.

`ThrowsAsync` being async, if you do not await its result, you won't see anything happen...

**Comment by tillig** [comment]
@epsitec _Nice catch!_ I must have been blind this day. Thanks!
