### ISSUE TITLE
Be able to specify methodDisplay in xunit.console.exe

### ISSUE THREAD

**Issue by jdom** [xunit/xunit#797]
Currently I have a setup with several test assemblies, and each of them define a assemblyname.xunit.runner.json with the config properties. One of them currently must be `methodDisplay="classAndMethod"`, since otherwise the generated XML wouldn't be parseable by some CI tools (Jenkins xunit plugin for example) that assume the test display name is the full method name.

Nevertheless, this make the tests unreadable when running them from VS in the Test Explorer (they are way too long).

It would be great to be able to configure the .json with just `methodDisplay="method"` so that it works well from VS, and then have my test script that uses the console runner override that with a config switch such as `-methodDisplay classAndMethod`. This would be very similar with how one would override other config options, such as parallelization or shadow-copying.

**Comment by onovotny** [comment]
We might be able to have a VS override...like `applicationName.xunit.runner.vs.json`. I'd need to double-check the codebase, but I thought each runner is responsible for resolving the file location so it'd be possible for the VS runner to try an alternate name.

**Comment by jdom** [comment]
That would be good too. I would have assumed that adding more options to the command line would be easier, since it already has that capability for overriding some settings.
Also, it kind of make sense to define how the output is displayed (`methodDisplay`) with a command line parameter (since it's there already that we are defining to output to XML (or HTML, etc) by using the `-xml` switch).
Having said that, I think that as long there is one way to do it, it should be fine regardless of my preference, hehe.

**Comment by bradwilson** [comment]
Closed for age.
