### ISSUE TITLE
Wrong Console Runner Return Codes ( 1 <=>3)

### ISSUE THREAD

**Issue by WernerMairl** [xunit/xunit#798]
Hi

using the following spec:
http://xunit.github.io/docs/getting-started-desktop#console-return-codes

I found the following problems in Xunit.Console.exe (2.1.0)

option -nologo => console runner works like expected
option -nologgo => syntax error because "gg" => returncode 3 expected BUT returncode 1 retrieved!!

option -xml filename => console runner works like expected
option -xml <forgotten filename> => returncode 3 expected but returncode 1 retrieved

in both cases the text-based output is working/veriy helpful for that situation BUT the returncodes seem to be wrong!

regards
Werner

**Comment by bradwilson** [comment]
Sorry, I should update the documentation to indicate that this change affects version 2.2 and later. You will need to use 2.2 beta 1 to get this behavior.

**Comment by bradwilson** [comment]
Closed for age.
