### ISSUE TITLE
Discover nested classes when using -class argument

### ISSUE THREAD

**Issue by akamud** [xunit/xunit#800]
We have some tests that are divided into nested classes for better readability, like this:

``` C#
public class FooSpec
{
    public class Unauthenticated
    {
        // Lots of [Fact]s here
    }

    public class Authenticated
    {
        // Lots of [Fact]s here
    }
}
```

Passing `-class Namespace.FooSpec` to `dnx test` doesn't discover nested classes tests. I can see [this line](https://github.com/xunit/xunit/blob/fe8d78df7cfec55ddab93c29ea96b0032ca998a8/src/xunit.runner.utility/Project/XunitFilters.cs#L87) doesn't make that scenario possible, but this would be useful for us.

Are you interested in enabling this kind of scenario? I could make a PR.

**Comment by akamud** [comment]
Opinions on this?

**Comment by bradwilson** [comment]
Closed for age.
