### ISSUE TITLE
"xunit.AppDomain" set to "denied" gives a different behavior in Visual Studio vs command-line

### ISSUE THREAD

**Issue by davkean** [xunit/xunit#801]
**xUnit version**: 2.1.0

When AppDomain's are switched off, Test Explorer gives a different behavior to the command-line with regard to App.Config CLR binding settings (binding redirects, code bases, etc) and other settings.

**App.Config**

``` XML
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <appSettings>
    <add key="xunit.appDomain" value="denied" />
  </appSettings>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="1.0.0.0-1.1.37.0" newVersion="1.1.37.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Test Method**

``` C#
[Fact]
public void TestMethod()
{
    Assembly.Load("System.Collections.Immutable, Version=1.0.0.0, PublicKeyToken=b03f5f7f11d50a3a, Culture=neutral");
}
```

Alongside the test dll, place System.Collections.Immutable.dll 1.1.37.0.

If you run test in Visual Studio, the test succeeds.
If you run test via

```
> %USERPROFILE%\.nuget\packages\xunit.runner.console\2.1.0\tools\xunit.console.x86.exe" ConsoleApplication65.dll
```

You get the following:

```
xUnit.net Console Runner (32-bit .NET 4.0.30319.42000)
  Discovering: ConsoleApplication65
  Discovered:  ConsoleApplication65
  Starting:    ConsoleApplication65
    ConsoleApplication65.Test.TestMethod [FAIL]
      System.IO.FileNotFoundException : Could not load file or assembly 'System.Collections.Immutable, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
      Stack Trace:
           at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
           at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
           at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
           at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
           at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
           at System.Reflection.Assembly.Load(String assemblyString)
        c:\users\davkean\documents\visual studio 2015\Projects\ConsoleApplication65\ConsoleApplication65\Program.cs(22,0): at ConsoleApplication65.Test.TestMethod()
  Finished:    ConsoleApplication65
=== TEST EXECUTION SUMMARY ===
   ConsoleApplication65  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 0.069s
```

While I understand the reason why the binding redirect _isn't_ being respected (you're not using the test's App.config to seed the AppDomain), it would be preferable to have similar behavior between Visual Studio and command-line with this regard.

**Comment by bradwilson** [comment]
The design of Visual Studio's runner requires that we always do app domains; otherwise, the DLLs will become locked on disk by the forever-living discovery process, which would prevent building them again.

**Comment by davkean** [comment]
Could you seed that AppDomain with the command-line's App.Config and AppBase to mimic behavior?

**Comment by bradwilson** [comment]
I'm confused by what you're asking.

Binding redirects inside your App.config file only work when app domains are turned on. They do not work when app domains are turned off.

**Comment by davkean** [comment]
I understand that. I want the _same behavior_ between VS and Console. If binding redirects don't work via the console when AppDomain==denied, it shouldn't work in VS when AppDomain==denied.

Here's what breaks:

1. Sam installs JSON.NET via NuGet into a test project with AppDomain==denied. NuGet, seeing that's there's conflicting versions in the project's dependency graph, adds a binding redirect to the App.Config that maps from 2.0.0.0 -> 3.0.0.0.

2. He writes some tests, runs tests via Test Explorer, everything's green.

3. Commits and pushes these to GitHub

4. This kicks of CI build that uses the xUnit command-line tool to run tests, but fails with: `System.IO.FileNotFoundException : Could not load file or assembly 'Newtonsoft.Json, Version=2.0.0.0, Culture=neutral, PublicKeyToken=[key]' or one of its dependencies. he located assembly's manifest definition does not match the assembly reference.`

5. Sam is confused because everything was green in VS.

**Comment by bradwilson** [comment]
I think the best solution then is to disable (as in, refuse to run any tests) if a VS runner user has requested AppDomain==denied, and force them to use a runner which would obey their requirement.

**Comment by bradwilson** [comment]
Closed for age.
