### ISSUE TITLE
Pass in extra  parameters to Trait attribute that can be later used in ClassData from xunit.console

### ISSUE THREAD

**Issue by Kwirirai** [xunit/xunit#802]
Is there a way to pass extra parameters to Trait attribute that can be later used in ClassData from xunit.console.I would like to dynamically configure theory data in a ClassData before the test is run from the command line something like -trait "Auto=1,someId=123456" and get this in my  ClassData class as someId=123456 and use that in my constructor

**Comment by bradwilson** [comment]
Closed for age.
