### ISSUE TITLE
First test executed includes initialization time scewing performance metrics

### ISSUE THREAD

**Issue by heaths** [xunit/xunit#808]
We measure performance of tests from one build to the next to find significant deltas. Seemingly random tests from build to build could go from 1ms (or so, depending on test) to almost a full 1s. This is, it seems, initialization time. We have seen it with other test runners and have been able to work around it with an assembly initialization route (like `AssemblyInitializeAttribute` methods for MSTest) that does nothing but "take up the slack".

I'm not sure if there's much the test discovery / execution extensions can do about this but if there was some way to work around it. I realize you don't want to add assembly initialization, but is there anything the test runner could do instead to mimic this same behavior itself?

**Comment by bradwilson** [comment]
Closed for age.
