### ISSUE TITLE
xunit.runner.dnx: Only maximum of 100 unit tests showing 

### ISSUE THREAD

**Issue by danielcweber** [xunit/xunit#812]
I'm still investigating this, but it seems that after 100 found unit tests (in VS Test Explorer), xunit.runner.dnx stops or fails to discover further ones.

My unit tests are distributed over many test projects. Whenever I unload one of them, xunit.runner.dnx discovers new tests (that were not run previously) but the total count always adds up to 100.

From the 'dependencies' section in my project.json:
"xunit": "2.2.0-beta1-build3239",
"xunit.runner.dnx": "2.1.0-rc1-build204"

**Comment by bradwilson** [comment]
That sounds like a bug in the DNX => Visual Studio adapter, which is owned by the ASP.NET team (not me). I would report this bug in https://github.com/aspnet/testing
