### ISSUE TITLE
Determine if DataAttribute.GetData is running in the context of test discovery

### ISSUE THREAD

**Issue by seesharper** [xunit/xunit#814]
I am the author of the LightInject DI framework and there is also a extension that lets you inject services into xunit test methods. 

https://github.com/seesharper/LightInject.xUnit/blob/master/src/LightInject.xUnit2/LightInject.xUnit2.cs

The problem that I have is that it does not seem to be a way to determine if the DataAttribute.GetData method is executed in the context of test discovery or in the context of actually executing the test. 

Is it something I could use to distinguish test discovery from test execution?

**Comment by bradwilson** [comment]
Not at the moment. Marking this as a feature request.

**Comment by seesharper** [comment]
Any news on this?

**Comment by bradwilson** [comment]
Sorry, this did not make the cut for 2.2. I'll leave it open for a future release.

**Comment by bradwilson** [comment]
Closed for age.
