### ISSUE TITLE
[Question] Logging with Specflow and xUnit 2 (ITestOutputHelper)?

### ISSUE THREAD

**Issue by cobysy** [xunit/xunit#815]
Unfortunately I have a Specflow test passing locally, but it fails on the VSO Build vNext server, and I really need to see verbose information during the test run so I can figure out what is going on.
(Double posted here http://stackoverflow.com/questions/36363952/logging-with-specflow-and-xunit-2-itestoutputhelper)

But I'm struggling to try to inject ITestOutputHelper into a Specflow binding like so

`public SomeSteps(ITestOutputHelper outputHelper)`

but Specflow complains with the message

`BoDi.ObjectContainerException Interface cannot be resolved: Xunit.Abstractions.ITestOutputHelper (resolution path: ...)`

Is there some way I can new up a concrete ITestOutputHelper or is there a factory I can use to get an instance of ITestOutputHelper that I can use in my specflow tests?

**Comment by bradwilson** [comment]
The concrete type is `TestOutputHelper`, but it's not going to help you to make your own, because nobody would be listening to it. You have to use the one we provide to the test class's constructor. There is no other method today to get access to the correct instance.

**Comment by cobysy** [comment]
> You have to use the one we provide to the test class's constructor. There is no other method today to get access to the correct instance.

Well unfortunately it seems it's more a Specflow 2.0 'issue' that has it's own DI injection that "overrides" the one of xUnit. Even if I could get the injection of ITestOutputHelper through the constructor to work, it's likely I have to do it in the fixture that is auto-generated - and that would lead to a bag of other troubles.

The solution I resorted to for now is to revert back to xUnit 1.9.2 - just for my Specflow tests.
