### ISSUE TITLE
SerializationHelper Private Instead of Internal?

### ISSUE THREAD

**Issue by Jyosua** [xunit/xunit#820]
I might be mistaken about something here, so forgive me if I'm asking something that seems odd. 

Here's the context for the following question. In our project where I work, we have a custom-written xUnit test runner. As a part of this, there is an abstract class that implements ITestFrameworkExecutor called ATestFrameworkExecutor<TTestCase>. The ITestFrameworkExecutor interface has a method declaration:

`ITestCase Deserialize(string value);`

Since our test runner was written using xUnit 2.0.0 RC4, this part of the interface was implemented using the following code:

```
public virtual ITestCase Deserialize(string value)
{
    return SerializationHelper.Deserialize<ITestCase>(value);
}
```

This compiled fine in 2.0.0 RC4. I'm now trying to update our version of xUnit and make corresponding changes to the test runner, but the compiler is complaining that SerializationHelper is inaccessible due to its protection level. I checked the source history, and it appears that a [commit](https://github.com/xunit/xunit/commit/d3879d69edb203956f290e45e45603275a3c3f37) removed a bunch of internal keywords as they were "redundant". It now defaults to private, and it would seem like I can no longer easily implement this part of the ITestFrameworkExecutor interface.

My question is: **Why was this changed and is there a suitable workaround for this use case?**

**Comment by bradwilson** [comment]
You are mistaken:

> Classes and structs that are declared directly within a namespace (in other words, that are not nested within other classes or structs) can be either public or internal. Internal is the default if no access modifier is specified.

(from https://msdn.microsoft.com/en-us/library/ms173121.aspx)

This commit was the one that changed it from public to internal, because it became a class shared among several assemblies: https://github.com/xunit/xunit/commit/f41cb1fc0421a59b4bcf697effadf0afad778b09#diff-45874a413b654e20bf147b8b20cbbdf7

**Comment by Jyosua** [comment]
Ah, that makes more sense. I actually was confused why it seemed to work in the old 2.0.0 RC4 with an internal keyword, but assumed that my initial understanding of internal was wrong. I thought the date of the RC4 release was March, so I didn't look back that far for a public keyword. My bad.

That said, even with this info, I seem to still be blocked from upgrading our runner. I guess the only way to get around that is to re-implement SerializationHelper and XunitSerializationInfo?

**Comment by bradwilson** [comment]
Or bring in those two files as source.

**Comment by Jyosua** [comment]
I actually go around it by having our ATestFrameworkExecutor inherit from the TestFrameworkExecutor class now present in xUnit and removing the duplicate code. I had some trouble with disabling parallelization (our integration tests were being run in a background thread at first, since `SetValue("xunit.DisableParallelization", true)` wasn't working with ITestFrameworkOptions implementor class anymore, for some reason), but I switched to an assembly CollectionBehavior attribute and everything seems to be working now. Sorry for the bother!
