### ISSUE TITLE
Custom discoverer does not work in Visual Studio runner, but does in console runner

### ISSUE THREAD

**Issue by heaths** [xunit/xunit#821]
Using current release of packages (2.1.0), I implemented a `ConditonalFactAttribute` (intended to work similarly to the `System.ComponentModel.ConditionalAttribute` but only at test-time) with a discoverer in the same assembly, though the attribute is used in other assemblies. But in Visual Studio - even after a machine restart (thinking perhaps it was a cached TE or TM runner), my tests are not skipped as expected.

I thought maybe this was the same problem as #249 but it seems in 2.1.0 the `XunitTestCase` is now serializable (with its own `Deserialize` and `Serialize` methods) but doesn't serialize the `SkipReason`.

**Comment by heaths** [comment]
Serializing `SkipReason` myself fixed the problem.

While writing this solution for v2 (we had something similar in WiX against v1, though just by overriding `FactAttribute.EnumerateTestCommands`), documentation wasn't clear - though the samples were helpful - but found that many people are all trying to implement their own `SkippableTestCase` (or equivalent). Perhaps just adding it to xUnit if it's common enough would be helpful for many.

**Comment by bradwilson** [comment]
Closed for age.
