### ISSUE TITLE
root path incorrect when using the xunit runner with multiple assemblies.

### ISSUE THREAD

**Issue by jannickj** [xunit/xunit#822]
If i have a files structures like:

tests/A/a.dll
tests/A/a.{some resource}
tests/B/b.dll

I will get an error like:

Test X in a.dll:
cannot find file a.{some resource} in tests/B/a.{some resource}.
Which suggests to me that the root path is not being correctly set to the dll currently running.

**Comment by bradwilson** [comment]
Closed for age.
