### ISSUE TITLE
System.MissingMethodException on Mac OSX and Linux Ubuntu 14.X

### ISSUE THREAD

**Issue by joganet** [xunit/xunit#823]
On linux (Ubuntu 14) and Mac os X doesn’t work the dnx test, it crash with an error “System.MissingMethodException: Method not found: 'Microsoft.Extensions.PlatformAbstractions.ILibraryManager Microsoft.Extensions.PlatformAbstractions.PlatformServices.get_LibraryManager()'.” Is not a problem form our code, is the dnx test, idk if is a problem with the xunit runner or what.

**Comment by bradwilson** [comment]
Closed for age.
