### ISSUE TITLE
xUnit Console runner: Cannot load assembly System.Runtime in project using .NET Standard 1.5

### ISSUE THREAD

**Issue by SuperJMN** [xunit/xunit#824]
The console runner shows: Could not load file or assembly or one of its dependencies 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

The assembly containing the tests is a classic Class Library that targets .NET Framework 4.6.1 and has a reference to the assembly being tested, that is a brand new project targeting .NET Standard 1.5.

**Comment by onovotny** [comment]
It sounds like the correct System.Runtime assembly is missing from the path. You might need to use the `dotnet publish` command as `System.Runtime 4.1.0.0` is newer than what's in the desktop CLR.

**Comment by SuperJMN** [comment]
Thanks! I will try as soon as I solve some problems with my AppVeyor configuration. It seems it has problems with Nuget, too.

**Comment by brunobertechini** [comment]
I am having the same isse but could not find a solution.

NETFramework 4.7 classlibrary referencing NETStandard 1.6 project. xunit still complaining about System.Runtime - 4.1.0.0 any thoughts ?

**Comment by TheKrush** [comment]
I'm also having the same issue as @brunobertechini

**Comment by bradwilson** [comment]
@TheKrush / @brunobertechini Please open a new issue with a repro project. Thanks!

**Comment by TheKrush** [comment]
@bradwilson I updated to Xunit 2.3.1 and the issue was fixed 👍
