### ISSUE TITLE
MemberData doesn't support rectangular arrays

### ISSUE THREAD

**Issue by ayb4btu** [xunit/xunit#826]
I'm running xunit v2.2.0-beta1-build3239 (and its included packages, abstractions, assert, core, etc.) and xunit.runner.visualstudio v2.2.0-beta1-build1144. I'm also using FluentAssertions v4.3.2.

When I use `MemberData` to pass in a 1D array or a 2D jagged array it works fine, but when I try to use a 2D rectangular array (in particular a float[,]) using this code:

```
    [Theory]
    [MemberData("ArrayCheck_2D")]
    public void Array2D_SimpleAssert(float[,] someArray)
    {
        int dimensions = someArray.Rank;
        dimensions.Should().Be(2, "it is a 2D array");
    }

    public static IEnumerable<object[]> ArrayCheck_2D = new List<object[]>
    {
        new object[] {
            new float[,] { { 3.1f, 4.5f }, { 2, 4 } },
        }
    };
```

I get the following error and stack trace:

> ------ Discover test started ------
> [xUnit.net 00:00:00.7892613]   Discovering: ImageProcessing.Tests
> [xUnit.net 00:00:01.4060016] ImageProcessing.Tests: Error creating Visual Studio test case for ImageProcessing.Tests.Generic2DArrayAssertionsTests.Array2D_SimpleAssert(someArray: [3.1, 4.5, 2, 4]): System.ArgumentException: Array was not a one-dimensional array.
> 
> Server stack trace: 
>    at System.Array.GetValue(Int32 index)
>    at Xunit.Serialization.XunitSerializationInfo.ArraySerializer.Serialize(IXunitSerializationInfo info) in C:\BuildAgent\work\cb37e9acf085d108\src\common\XunitSerializationInfo.cs:line 403
>    at Xunit.Serialization.XunitSerializationInfo.Serialize(Object value) in C:\BuildAgent\work\cb37e9acf085d108\src\common\XunitSerializationInfo.cs:line 301
>    at Xunit.Serialization.XunitSerializationInfo.SerializeTriple(XunitSerializationTriple triple) in C:\BuildAgent\work\cb37e9acf085d108\src\common\XunitSerializationInfo.cs:line 73
>    at Xunit.Serialization.XunitSerializationInfo.<>c.<ToSerializedString>b__5_0(KeyValuePair`2 kvp) in C:\BuildAgent\work\cb37e9acf085d108\src\common\XunitSerializationInfo.cs:line 62
>    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
>    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
>    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
>    at Xunit.Serialization.XunitSerializationInfo.ToSerializedString() in C:\BuildAgent\work\cb37e9acf085d108\src\common\XunitSerializationInfo.cs:line 62
>    at Xunit.Serialization.XunitSerializationInfo.Serialize(Object value) in C:\BuildAgent\work\cb37e9acf085d108\src\common\XunitSerializationInfo.cs:line 301
>    at Xunit.Serialization.XunitSerializationInfo.SerializeTriple(XunitSerializationTriple triple) in C:\BuildAgent\work\cb37e9acf085d108\src\common\XunitSerializationInfo.cs:line 73
>    at Xunit.Serialization.XunitSerializationInfo.<>c.<ToSerializedString>b__5_0(KeyValuePair`2 kvp) in C:\BuildAgent\work\cb37e9acf085d108\src\common\XunitSerializationInfo.cs:line 62
>    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
>    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
>    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
>    at Xunit.Serialization.XunitSerializationInfo.ToSerializedString() in C:\BuildAgent\work\cb37e9acf085d108\src\common\XunitSerializationInfo.cs:line 62
>    at Xunit.Sdk.SerializationHelper.Serialize(Object value) in C:\BuildAgent\work\cb37e9acf085d108\src\common\SerializationHelper.cs:line 64
>    at Xunit.Sdk.TestFrameworkDiscoverer.Serialize(ITestCase testCase) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\TestFrameworkDiscoverer.cs:line 195
>    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
>    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
> 
> Exception rethrown at [0]: 
>    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
>    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
>    at Xunit.Abstractions.ITestFrameworkDiscoverer.Serialize(ITestCase testCase)
>    at Xunit.Xunit2Discoverer.Serialize(ITestCase testCase)
>    at Xunit.XunitFrontController.Serialize(ITestCase testCase)
>    at Xunit.Runner.VisualStudio.TestAdapter.VsDiscoveryVisitor.CreateVsTestCase(String source, ITestFrameworkDiscoverer discoverer, ITestCase xunitTestCase, Boolean forceUniqueNames, LoggerHelper logger, HashSet`1 knownTraitNames)
> [xUnit.net 00:00:01.4170355] ImageProcessing.Tests: Error creating Visual Studio test case for ImageProcessing.Tests.Generic2DArrayAssertionsTests.Array2D_SimpleAssert(someArray: [3.1, 4.5, 2, 4]): System.ArgumentException: Array was not a one-dimensional array.

I have only been using the latest prerelease of xunit, so I haven't tested with a stable version, so I'm not sure if this issue is version specific.

**Comment by Ausm** [comment]
Seams to be a bug in the serialization logic.
[CanSerializeObject](https://github.com/xunit/xunit/blob/1c389909bbd02cced7dd706721e81a8450a3839c/src/common/XunitSerializationInfo.cs#L336-L350) in the ```XunitSerializationInfo``` returns true, means "Can be searialized", because foreach enumerates a n-dimentional array like a 1-dimentional.
But the [ArraySerializer ](https://github.com/xunit/xunit/blob/1c389909bbd02cced7dd706721e81a8450a3839c/src/common/XunitSerializationInfo.cs#L399-L403) doesn't give the number of dimensions and their  extensions to the ```IXunitSerializationInfo```.

What I did, was to write my own theory discoverer which doesn't require to serialize the theory data, to get rid of all these serialization problems. See [here](https://github.com/Ausm/ObjectStore/blob/edfe90e9a32e4351c4bcff0238e6d985c03a5796/test/ObjectStore.Test/TheoryDiscoverer/ExtTheoryDiscoverer.cs).

**Comment by ayb4btu** [comment]
@Ausm Thanks for providing a way around the issue, though it will be good once this issue is resolved within xunit itself.
