### ISSUE TITLE
Support attribute based platform specifier for tests

### ISSUE THREAD

**Issue by tmds** [xunit/xunit#827]
The .NET core projects us the [PlatformSpecificAttribute](https://github.com/dotnet/buildtools/blob/master/src/xunit.netcore.extensions/Attributes/PlatformSpecificAttribute.cs) to include/exclude certain platforms when executing tests.

The buildtools repo which contains the Attribute has the following comment in the readme:

> Note: Please note that these tools are currently not meant for consumption outside of the .NET Core projects.

It would be nice if such an attribute was part of xunit.

**Comment by tmds** [comment]
\cc @Priya91 @mellinoe

**Comment by tmds** [comment]
*bump*
is this a good idea? is it feasible?

**Comment by bradwilson** [comment]
Closed for age.
