### ISSUE TITLE
XUnit hangs on Server 2012 with RavenDB

### ISSUE THREAD

**Issue by shederman** [xunit/xunit#830]
The attached test project hangs forever when run on Server 2012 (with CodeContracts installed). Works perfectly on Windows 10. If I remove the Fact attribute from one of the test classes it works 100%. If I move the test fact from one class to another, it works 100%.

Also reporting this to Raven DB, but not convinced it's on their side.
[XUnitRavenTest.zip](https://github.com/xunit/xunit/files/225576/XUnitRavenTest.zip)

**Comment by bradwilson** [comment]
Closed for age.
