### ISSUE TITLE
Xunit 1.9.2 adapter hangs when running a test from a dll which doesnt have any Xunit tests.

### ISSUE THREAD

**Issue by Faizan2304** [xunit/xunit#834]
The issue here is with Xunit 1.9.2. The issue occurs when we follow the below steps. 
1)  Create a dll which doesn’t have any xunit test in it. (Say its name NoXunitTest.dll)
2)  Put it in folder name “FolderTest”.
3)  Copy all (xunit.abstractions.dll, xunit.dll, xunit.runner.utility.desktop.dll, xunit.runner.visualstudio.testadapter.dll) in a new folder name  “FolderXunit”.
4)  Copy all xunit dll of “FolderXunit” into “FolderTest”.
5)  Run the following command  from Developer Command Prompt 
Vstest.console.exe (Path of “FolderTest”)\ NoXunitTest.dll  /TestAdapterPath: (path of “FolderXunit”)

On following the above steps Vstest.console.exe hangs for forever.
I debugged the code and  found following stack trace..

> > mscorlib.dll!System.Threading.WaitHandle.WaitOne(long timeout, bool exitContext) 
> > mscorlib.dll!System.Threading.WaitHandle.WaitOne(int millisecondsTimeout, bool exitContext)  
> > mscorlib.dll!System.Threading.WaitHandle.WaitOne()  
> > xunit.runner.visualstudio.testadapter.dll!Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.RunTestsInAssembly(Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IFrameworkHandle frameworkHandle, LoggerHelper logger, System.Collections.Generic.List<System.IDisposable> toDispose, Xunit.Runner.VisualStudio.AssemblyRunInfo runInfo, System.Diagnostics.Stopwatch stopwatch)
> > xunit.runner.visualstudio.testadapter.dll!Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.RunTests.AnonymousMethod__3(Xunit.Runner.VisualStudio.AssemblyRunInfo runInfo)
> > mscorlib.dll!System.Collections.Generic.List<Xunit.Runner.VisualStudio.AssemblyRunInfo>.ForEach(System.Action<Xunit.Runner.VisualStudio.AssemblyRunInfo> action)
> > xunit.runner.visualstudio.testadapter.dll!Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.RunTests(Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunContext runContext, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IFrameworkHandle frameworkHandle, LoggerHelper logger, System.Diagnostics.Stopwatch stopwatch, System.Func<System.Collections.Generic.List<Xunit.Runner.VisualStudio.AssemblyRunInfo>> testCaseAccessor)
> > xunit.runner.visualstudio.testadapter.dll!Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.RunTests(System.Collections.Generic.IEnumerable<string> sources, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunContext runContext, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IFrameworkHandle frameworkHandle)
> > Microsoft.VisualStudio.TestPlatform.Core.dll!Microsoft.VisualStudio.TestPlatform.Core.TestExecutionManager.RunTestInternalWithExecutors(System.Collections.Generic.IEnumerable<System.Uri> executorUris, bool hasTests, System.Collections.Generic.Dictionary<System.Uri, System.Collections.Generic.IEnumerable<string>> executorUriVsSourceList, System.Collections.Generic.Dictionary<System.Uri, System.Collections.Generic.List<Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase>> executorUriVsTestList, Microsoft.VisualStudio.TestPlatform.Core.RunContext runContext, long totalTests, Microsoft.VisualStudio.TestPlatform.Common.Utilities.MeasurementBlockWrapper mb) 
> > Microsoft.VisualStudio.TestPlatform.Core.dll!Microsoft.VisualStudio.TestPlatform.Core.TestExecutionManager.RunTestsInternal(System.Collections.Generic.IEnumerable<object> testOrSources, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings runSettings, Microsoft.VisualStudio.TestPlatform.Core.TestExecutionContext executionContext)  
> > Microsoft.VisualStudio.TestPlatform.Core.dll!Microsoft.VisualStudio.TestPlatform.Core.TestExecutionManager.RunTests(System.Collections.Generic.IEnumerable<object> testsOrSources, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunSettings runSettings, Microsoft.VisualStudio.TestPlatform.Core.TestExecutionContext executionContext)
> > Microsoft.VisualStudio.TestPlatform.Core.dll!Microsoft.VisualStudio.TestPlatform.Core.TestExecutionManager.RunTests(object data)

Its look like call goes to xunit adapter and never come back and we keep waiting for that in our code.

I tried to follow the same steps with latest Xunit and it didn’t repro.

**Comment by bradwilson** [comment]
Closed for age.
