### ISSUE TITLE
[fact] is not wroking in xunit - vs2012 c#

### ISSUE THREAD

**Issue by yashfale** [xunit/xunit#835]
i am trying to run test this code but here fact is not working ,(visual studio 2012,c#, xUnit)

 public class UnitTest1
    {
        [Fact]
        public void TestMethod1()
        {
            var c = new Calculater();
            var Result = c.Add(10, 10);
            Xunit.Assert.Equal(10, Result);
            
        }
    }

**Comment by yashfale** [comment]
also tried solution which is given in https://github.com/xunit/xunit/issues/295.

**Comment by bradwilson** [comment]
There's not enough information to be actionable. Please provide a repro project.

**Comment by yashfale** [comment]
thank you for quick response , unable to upload zip file here so , i sent you on your mail address :dotnetguy@gmail.com
Thanks in Advance

**Comment by yashfale** [comment]
tested it in vs2013 ,working fine , but still not working in vs2012
