### ISSUE TITLE
dotnet-test-xunit 1.0.0-rc2-build10015 has a 32 bit binary in the runtimes/net451/win7-x64 directory

### ISSUE THREAD

**Issue by pranavkm** [xunit/xunit#843]
Running corflags:
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0>corflags ".nuget\packages\dotnet-test-xunit\1.0.0-rc2-build10015\runtimes\win7-x64\lib\net451\dotnet-test-xunit.exe"
Microsoft (R) .NET Framework CorFlags Conversion Tool.  Version  4.6.1055.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Version   : v4.0.30319
CLR Header: 2.5
PE        : PE32
CorFlags  : 0x20003
ILONLY    : 1
32BITREQ  : 0
32BITPREF : 1
Signed    : 0
```

Using a 64 bit dotnet to run tests results in the following failure:
```
xUnit.net .NET CLI test runner (32-bit win81-x86)
System.DllNotFoundException: Unable to load DLL 'Microsoft.DiaSymReader.Native.x86.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

**Comment by muratg** [comment]
:eyes:

**Comment by thecodejunkie** [comment]
I just hit this as well, trying to run xunit tests (using the bits detailed at https://xunit.github.io/docs/getting-started-dotnet-core.html), targeting `net452` on a Win 10 x64 machine

> xUnit.net .NET CLI test runner (32-bit win10-x86)
> System.DllNotFoundException: Unable to load DLL 'Microsoft.DiaSymReader.Native.x86.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by pranavkm** [comment]
https://github.com/xunit/dotnet-test-xunit/pull/5 should fix this.

**Comment by bradwilson** [comment]
You can pull an RC 3 build from MyGet if this is blocking you. https://myget.org/gallery/xunit

**Comment by ItzWarty** [comment]
Hmm now getting 

```
System.DllNotFoundException: Unable to load DLL 'Microsoft.DiaSymReader.Native.amd64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

Framework: net451, dependencies: 
        "xunit": "2.2.0-beta2-build3279", 
        "dotnet-test-xunit": "1.0.0-rc3-build10019"

**Comment by Kurira** [comment]
Did any one even managed to run `dotnet test` yet?
Seems like a real blocker now, because neither `1.0.0-rc2-build10015` nor `1.0.0-rc3-build10019` works.
Is there a different way to run tests?

**Comment by thecodejunkie** [comment]
I can confirm that I have now, successfully, executed tests for both `netcoreapp1.0` and` net452` using

- dotnet-test-xunit 1.0.0-rc3-build10019
- xunit 2.1.0
- SDK 1.0.0-preview1-002702
- Dotnet CLI 1.0.0-preview1-002702

On a Windows 10 x64 machine

**Comment by pranavkm** [comment]
@ItzWarty on a net451 application you have to include `"Microsoft.NETCore.Platform": "1.0.1-24027"` as a dependency.

**Comment by thecodejunkie** [comment]
@pranavkm I think it's better to say that if you target full-framework then you need `Microsoft.NETCore.Platforms`, but when you target core you get it as a transient dependency from `Microsoft.NETCore.App`

**Comment by bragma** [comment]
@pranavkm thanks a lot your suggestion solved my problem with xunit and an asp net core project targetting net461! Where did you get that info? I'm totally confused by the new "framework" section of project.json and the new dependency requirements.

**Comment by pranavkm** [comment]
@bragma, `Microsoft.NETCore.Platforms` tells nuget \ dotnet restore how to bring in native dependencies. The package should've added this dependency so a user wouldn't have to do this.

**Comment by kcd83** [comment]
I can confirm updating to `dotnet-test-xunit` rc3 fixed this for me. I have a `dnx` project I migrated to rc2.

```
"dependencies": {
    "MyProject": "1.0.0-*",
    "Moq": "4.2.1510.2205",
    "xunit": "2.1.0",
    "dotnet-test-xunit": "1.0.0-rc3-*"
  },
  "frameworks": {
    "dnx451": {
      "imports": [
        "netcoreapp1.5"
      ]
    }
```

**Comment by macgyver76** [comment]
Is there any way to run this on `Windows 7 x64` and full .Net Framework `net461`? Or how to manage to download rc3 version of `dotnet-test-xunit`? 

Nuget (in project.json) shows me:
![image](https://cloud.githubusercontent.com/assets/9820004/15426879/a25b1d34-1e91-11e6-8805-d40c947360f9.png)

**Comment by thecodejunkie** [comment]
@macgyver76 the rc3-verison is not on NuGet, it is only published on the XUnit MyGet feed atm, so add that to your `NuGet.config` 

`https://www.myget.org/F/xunit/api/v3/index.json`

**Comment by macgyver76** [comment]
@thecodejunkie Thank you for this hint. If running by `dotnet test` it's working fine hovewer it's not possible to discover tests in VS. Here's building output:

> ------ Discover test started ------
Discovering tests in 'Path_To_Project\project.json' ["C:\Program Files\dotnet\dotnet.exe" test "Path_To_Project\project.json" --output "Path_To_Project\bin\Debug\net461\win7-x64" --port 9048 --parentProcessId 6792 --no-build]
'test-xunit' returned '1'.
========== Discover test finished: 0 found (0:00:00,9770977) ==========

**Comment by thecodejunkie** [comment]
I don't think package integrated with the VS test runner (or other runners like ReSharper och TestDriven.NET) yet. I've been using the cmd for single projects, and a small powershell script for solutions with multiple test projects

**Comment by macgyver76** [comment]
It's working when I add dependency to `net461` like:
```json
"net461": {
      "dependencies": {
        "Microsoft.NETCore.Platforms": "1.0.1-rc2-24027"
      }
    }
```

**Comment by bvanskiver** [comment]
Mine works great (with dotnet-test-xunit rc3) until I reference a class library in my solution - then `dotnet test` gives a "xUnit.net Test Runner (CoreCLR) has stopped working" error, but no additional information.

Visual Studio discovery test gives the following result:
`'test-xunit' returned '-1073741819'`

I'm using full framework net461

**Comment by thecodejunkie** [comment]
Yeah I just noticed that it works with the VS runner now

**Comment by thecodejunkie** [comment]
@bvanskiver that's an unrelated problem and should probably be raised in its own issue
