### ISSUE TITLE
Link is dead:https://xunit.github.io/docs/getting-started-dotnet-cli.html

### ISSUE THREAD

**Issue by bastienJS** [xunit/xunit#844]

**Comment by bradwilson** [comment]
Where do you see this link from?

**Comment by guylando** [comment]
The "More Information" link for a tutorial here is dead: https://github.com/dotnet/coreclr.xunit

**Comment by bastienJS** [comment]
@bradwilson sorry I lost that site :/

**Comment by bradwilson** [comment]
Closed for age.
