### ISSUE TITLE
Limit lengths of test case names

### ISSUE THREAD

**Issue by TAGC** [xunit/xunit#845]
Is there a way to reduce the size of generated test case names, for instance by making them not include the string representation of each of their parameters?

I found that all builds of a particular Bamboo plan had been failing to complete for the last week and traced it back to the fact that XUnit was generating test case names that were over 4000 characters long in some cases, which is the maximum length for test case names supported\* by Bamboo.

As a fugly workaround, I've had to wrap parameters for some of my test cases inside other objects just to override `Object.ToString()` and suppress the default string representation.

**Comment by onovotny** [comment]
Test case names are determined by the runner you're using. Which runner are you using for this?

**Comment by TAGC** [comment]
I'm using the XUnit console runner for this. Specifically, this is what gets executed:

`<Exec Command="$(OpenCoverPath)\tools\OpenCover.Console.exe -register:user -target:&quot;$(XUnitConsolePath)\tools\xunit.console.exe&quot; -targetargs:&quot;@(TestAssemblies) -noshadow -nunit $(NUnitOutputFile)&quot; -filter:&quot;-[xunit*]* -[*]System.Diagnostics.Contracts.* -[$(AssemblyName)*]* +[$(MainAssemblyName)*]*&quot; -output:$(OpenCoverOutputFile)" />`

where `NUnitOutputFile` ends up containing `<test-case name=...` attributes that are over 4000 characters long.

**Comment by kosa-gyula-77** [comment]
With the _-teamcity_ option xunit.runner.console 2.1.0 gives the following output:

`[Test collection for <namespace>.<testClass> (1)] <namespace>.<testClass>.<testMethod>`

I think that the `<namespace>.<testClass>` part is **redundant**, thus the output could be shortened by omitting one occurence of it.

I would also consider omitting `Test collection for `, but it may be required by TeamCity.

Runner used: xunit.runner.console 2.1.0

**Comment by bradwilson** [comment]
Closed for age.
