### ISSUE TITLE
unable to get passed arguments in xUnit

### ISSUE THREAD

**Issue by yashfale** [xunit/xunit#846]
i have passed arguments as shown in bellow image, and tried to get in xUnit test Method , which is not working , is it possible to get this argument ?.
1) Passed argument is:
![2](https://cloud.githubusercontent.com/assets/7036028/15354716/9153fa50-1d0c-11e6-93b9-3a66a7f6429f.png)

2)checked for passed argument:
![4](https://cloud.githubusercontent.com/assets/7036028/15354807/036a83b6-1d0d-11e6-8280-a977abb0ebff.png)

i need output as passed arguments.  i.e. - > arg1

**Comment by bradwilson** [comment]
What you're asking for is not supported. Sorry.

**Comment by yashfale** [comment]
ok. thank you.
