### ISSUE TITLE
Core RC2: dotnet-watch --command test - MissingMethodException

### ISSUE THREAD

**Issue by rdefreitas** [xunit/xunit#849]
I'm attempting to run tests in core RC2. My test project does not have an entry point (Program.cs) and runs tests properly using the command "`dotnet test`".

I'm not sure if it would be better to address this issue here or in  aspnet/dotnet-watch#100
When I try to run tests continuously, however, I see the following error:

	H:\Dev\Sample\test\Sample.Test.Unit>dotnet watch --command test
	[DotNetWatcher] info: Running dotnet with the following arguments: run -- --command test
	[DotNetWatcher] info: dotnet process id: 572048
	Project Sample (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
	Project Sample.Test.Unit (.NETCoreApp,Version=v1.0) will be compiled because inputs were modified
	Compiling Sample.Test.Unit for .NETCoreApp,Version=v1.0
	Compilation succeeded.
	0 Warning(s)
	0 Error(s)
	Time elapsed 00:00:01.7921147

	Unhandled Exception: System.MissingMethodException: Entry point not found in assembly 'Sample.Test.Unit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
	[DotNetWatcher] fail: dotnet exit code: -532462766

My project.json contains these entries:

	{
		"version": "1.0.0-*",
		"testRunner": "xunit",
		"dependencies": {
			"Sample": { "target": "project" },
			"dotnet-test-xunit": "1.0.0-rc2-*",
			"xunit": "2.1.0",
			"Microsoft.DotNet.Watcher.Tools": {
				"version": "1.0.0-preview1-final",
				"type": "build"
			}
		},
		"frameworks": {
			"netcoreapp1.0": {
				"dependencies": {
					"Microsoft.NETCore.App": {
						"type": "platform",
						"version": "1.0.0-*"
					}
				},
				"imports": [
					"dnxcore50",
					"portable-net45+win8"
				]
			}
		},
		"tools": {
			"Microsoft.DotNet.Watcher.Tools": {
				"version": "1.0.0-preview1-final",
				"imports": "portable-net451+win8"
			}
		}
	}

**Comment by victorhurdugaci** [comment]
You're hitting one of the weird cases of dotnet watch. We have a lot of processes involved in the watcher chain (dotnet -> watch -> dotnet -> command) and there's some of confusion around what argument gets passed to which process.

`dotnet watch <anything other than --help or -- >` runs`dotnet run -- <all arguments>` (yes, `dotnet run` has it's own `--` argument and we special cased it). So, `dotnet watch --command test` becomes `dotnet run -- --command test` (you can see that in the console output) which means that `--command test` is passed to the app being executed by `dotnet run`.

If you want to pass any arguments to the watcher, you have to use `--`:

- `dotnet watch --command test --` runs`dotnet test`
- `dotnet watch --command test -- -parallel none` runs`dotnet test -parallel none`

The first `--` is the separator between the watcher arguments and watched app arguments.

**Comment by rdefreitas** [comment]
replied to you there, closing this.
