### ISSUE TITLE
Add a xunit.analyzers project

### ISSUE THREAD

**Issue by aochagavia** [xunit/xunit#851]
Based on the discussion on https://github.com/dotnet/roslyn/issues/5567 I think it would be a good idea to create a xunit.analyzers project. We could begin with an analyzer that rejects async void unit test methods. Those methods are useless, as explained by @tmat in the Roslyn issue:

> The test runner can't wait for the test to finish and get exceptions from the task. So such tests are basically useless.

I would like to work on this, but don't know where to begin. I could just open the solution on Visual Studio and add a new project. However, I am not sure about how to integrate the analyzer with the rest of the framework. Any ideas on this?

cc @srivatsn

**Comment by onovotny** [comment]
This is inaccurate for xUnit. xUnit properly handles async void test methods by using a custom synchronization context.

**Comment by tmat** [comment]
@onovotny What do you mean inaccurate? From what I observed the test starts running but nothing waits for it to finish. How would the runner know the test has finished?

**Comment by bradwilson** [comment]
@tmat We use a custom synchronization context to achieve this.

https://github.com/xunit/xunit/blob/master/src/xunit.execution/Sdk/AsyncTestSyncContext.cs

**Comment by aochagavia** [comment]
Should this issue be closed then?

**Comment by bradwilson** [comment]
The idea of an analyzers project is good. It just won't include that rule. 😁

**Comment by aochagavia** [comment]
Which analyzers woud you want to have then?

**Comment by bradwilson** [comment]
For "test authors", I'll give it some thought, but the first place to focus would probably be on discoverability issues, like:

- Put a [Fact] in a non-public class
- Put a [Theory] with no data elements
- Mark all skipped tests as a warning (lets you use warnings-as-errors and prevent people from committing skipped tests to source control)
- Mark tests with no assertions with a warning (we'd probably also want some way to detect third party assertion libraries)

For "extensibility authors", I could come up with a sizeable list just by looking at all the assertions/validations that we do.

**Comment by jamesqo** [comment]
It seems like someone has already written quite a few analyzers for xUnit here: https://github.com/marcind/xunit.analyzers Apparently, however, he hasn't shared it with the world yet.

**Comment by marcind** [comment]
Sorry about that. I was working on this and then took a long vacation and hadn't gotten back into it. After chatting with Brad we've moved the project into the xunit organization and I will be publishing a `0.1.0` soon.

**Comment by marcind** [comment]
As promised, the initial version of xunit.analyzers has been published to [nuget](https://www.nuget.org/packages/xunit.analyzers). Please check it out by adding a reference to the package to your test project in either VS 2015 or 2017.

![xunit analyzer example](https://cloud.githubusercontent.com/assets/607223/25752060/fb4af444-316b-11e7-9e7c-fc69ade132fb.gif)

**Comment by jamesqo** [comment]
@marcind 

> After chatting with Brad we've moved the project into the xunit organization and I will be publishing a 0.1.0 soon.

Great to hear that! I think what you're doing is really cool so I made a post about this on Reddit: https://www.reddit.com/r/csharp/comments/69ilxx/opensource_roslyn_analyzers_for_xunit/. Hopefully some people will try out the project and leave feedback or contribute. I have some experience with Roslyn myself, so maybe I'll be able to help you out sometime :)
