### ISSUE TITLE
Customizing Time Output

### ISSUE THREAD

**Issue by Mike-EEE** [xunit/xunit#853]
Hello all.  Big fan of this project. :)  I wanted to make a suggestion for a possible feature and see how well it would be received/considered.  I did ask in the Slack channel if this existed, but it doesn't sound like it.  So I wanted to open an issue here and get some conversation around it, if possible.

Essentially, when a test runs, the output looks like such:

```
[xUnit.net 00:00:00.8281224]   Starting:    Project1
[xUnit.net 00:00:00.9764759]   Starting:    Project2
[xUnit.net 00:00:03.7691860]   Finished:    Project2
[xUnit.net 00:00:06.0205763]   Finished:    Project1
```

At first glance, Project1 looks to have taken 6.02 seconds to execute, but looking a little further you can see that this is not the case.  The actual "project execution time" (for lack of a better term ATM) is the `Finished` less the `Starting` (5.19 seconds in the example above for Project1).  When doing performance testing it would be convenient/valuable to be able to get access to the project execution time for each project that ran, preferably in a format that is easily accessible, or without having to pull out the calculator (or eyeballing it). :smile: 

Thank you for any consideration.  Please let me know if there are any questions/concerns/complaints about this idea/feature consideration.

**Comment by bradwilson** [comment]
Closed for age.
