### ISSUE TITLE
30 seconds pause between test in TFS

### ISSUE THREAD

**Issue by ChristophHornung** [xunit/xunit#855]
I am building a solution in TFS with the xUnit Test Runner, all tests are discovered and executed correctly. But between some tests there are 30 second pauses which make the whole run take a lot of time. 

That is some batch of tests are executed at the same time e.g. 9:00:54 and take only fractions of a second, but then the next batch of tests are executed exactly at 9:01:24 and also take only fractions of a second each with the next batch then being executed at 9:01:54...

The only warning I get is "Attempted to access an unloaded AppDomain. This can happen if the test(s) started a thread but did not stop it. Make sure that all the threads started by the test(s) are stopped before completion". I am not sure if that has something to do with the problem though, since as far as I can tell the tests are too simple to start any extra threads.

The problem does not exist when running the tests in Visual Studio directly.

Anyone got an idea what could be the cause of the 30 second delays? Is there a specific 30 second somewhere?

**Comment by bradwilson** [comment]
Closed for age.
