### ISSUE TITLE
Passing the ASP.NET Core Environment to the Dotnet Test Runner

### ISSUE THREAD

**Issue by RehanSaeed** [xunit/xunit#857]
It would be incredibly useful if I could do something like this:

```
dotnet test --environment 'Production'
```

Instead of having to set the `ASPNETCORE_ENVIRONMENT` environment variable before running the test and then resetting it at the end of the test. The other advantage is that you can run more than one set of tests at the same time which is important for build machines.

**Comment by Jonathan34** [comment]
wish this was implemented :)

**Comment by bradwilson** [comment]
We don't control `dotnet test`. You should open requests like that here: https://github.com/microsoft/vstest

**Comment by RehanSaeed** [comment]
Moved to https://github.com/Microsoft/vstest/issues/669.

**Comment by lechu445** [comment]
now it is possible to set env variables in dotnet test
```
dotnet test --environment 'Production'
```
is supported

see the dosc https://learn.microsoft.com/pl-pl/dotnet/core/tools/dotnet-test

it was added in 2020 https://github.com/dotnet/sdk/pull/13436
