### ISSUE TITLE
How to test with xUnit libraries that target .NET Standard 1.5?

### ISSUE THREAD

**Issue by SuperJMN** [xunit/xunit#858]
I have created a .NETCoreApp (Console) and I have been unable to add xUnit to it.

Is there any way to do test this kind of libraries with xUnit?
Thank you!

**Comment by lynxluna** [comment]
I use it to create F# projects. It works by marking them as netcoreapp1.0 with dependencies to NetStandard.Library 1.5.

You can see the example on my toy project at:

https://github.com/libil/Libil.Common

**Comment by bradwilson** [comment]
The sample from @lynxluna should help you out (I'm not an F# guy, so I don't know much about it).

Here is our official documentation on getting started with .NET Core (you can obviously replace the C#-based instructions with F# equivalents): https://xunit.github.io/docs/getting-started-dotnet-core.html

**Comment by lynxluna** [comment]
But my sample has issues when run on osx Ref: #859

**Comment by SuperJMN** [comment]
Thanks this definitely helped me! (https://xunit.github.io/docs/getting-started-dotnet-core.html)

**Comment by lorddev** [comment]
https://xunit.github.io/docs/getting-started-dotnet-core.html is blank.

**Comment by bradwilson** [comment]
.NET Standard is not .NET Core.

If you want to write tests against a .NET standard library, you can test via any of the supported platforms (desktop, .NET Core, etc.). Support for .NET Core unit tests is built into both VS 2017 and `dotnet new xunit`.

**Comment by lorddev** [comment]
@bradwilson The link was provided by you. I'm just pointing out it's broken. Thanks.

**Comment by bradwilson** [comment]
The link is not broken; it contains the content that we intend for it to contain right now.

**Comment by dennisdoomen** [comment]
Is it possible to run the XUnit console runner directly against a .NET Core class library? I'm using Cake, but when I use the ordinary (2.3 Beta 3) runner, I get:

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

**Comment by bradwilson** [comment]
No, you must use `dotnet xunit` to run the .NET Core version on the console runner. https://xunit.github.io/docs/getting-started-dotnet-core.html

**Comment by dennisdoomen** [comment]
Yeah, got that working. Trying to run tests in .NET 4.5 and .NET Core apparently requires different techniques. For future reference, check out https://github.com/fluentassertions/fluentassertions/blob/develop/build.cake#L77

**Comment by bradwilson** [comment]
We don't support 4.5 any more. Minimum is 4.5.2.

**Comment by dennisdoomen** [comment]
Sorry, that's what I meant.
