### ISSUE TITLE
dotnet-test-xunit F# gives Unknown error due to MarshalDirectiveException on OSX

### ISSUE THREAD

**Issue by lynxluna** [xunit/xunit#859]
# The Project

This is my toy app: https://github.com/libil/Libil.Common/blob/master/Libil.Common.Test/project.json

**Environment**

```
dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```
# Expected

Runs the test just like windows does. This is the result in Windows:

```
dotnet test
Project Libil.Common (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling Libil.Common for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:09.6743297
Project Libil.Common.Test (.NETCoreApp,Version=v1.0) will be compiled because dependencies changed
Compiling Libil.Common.Test for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:07.2006804


xUnit.net .NET CLI test runner (64-bit .NET Core win81-x64)
  Discovering: Libil.Common.Test
  Discovered:  Libil.Common.Test
  Starting:    Libil.Common.Test
  Finished:    Libil.Common.Test
=== TEST EXECUTION SUMMARY ===
   Libil.Common.Test  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.267s
SUMMARY: Total: 1 targets, Passed: 1, Failed: 0.
Discovering tests...OK
```
# Actual Result

It produce `System.Runtime.InteropServices.MarshalDirectiveException`

```
xUnit.net .NET CLI test runner (64-bit .NET Core osx.10.11-x64)
System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'parameter #2': Unknown error.
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.
```

**Comment by cartermp** [comment]
I ran into this as well.

**Comment by czifro** [comment]
I ran into this on an F# project. Is there a fix/workaround?

**Comment by KodrAus** [comment]
Same issue for me with an F# project.

**Comment by AnthonyLloyd** [comment]
Have same with Ubuntu on Windows:

xUnit.net .NET CLI test runner (64-bit .NET Core ubuntu.14.04-x64)
System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'parameter #2': Unknown error.
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.

**Comment by bellp** [comment]
Ditto on Mac.

**Comment by nickolasacosta** [comment]
```
.NET Command Line Tools (1.0.0-preview2-003121)                                                                                                                          
                                                                                                                                                                         
Product Information:                                                                                                                                                     
 Version:            1.0.0-preview2-003121                                                                                                                               
 Commit SHA-1 hash:  1e9d529bc5                                                                                                                                          
                                                                                                                                                                         
Runtime Environment:                                                                                                                                                     
 OS Name:     ubuntu                                                                                                                                                     
 OS Version:  16.04                                                                                                                                                      
 OS Platform: Linux                                                                                                                                                      
 RID:         ubuntu.16.04-x64   
```

Getting this on linux while playing with F# on .net core

```
Compiling test for .NETCoreApp,Version=v1.0                                                                                                                              
                                                                                                                                                                         
Compilation succeeded.                                                                                                                                                   
    0 Warning(s)                                                                                                                                                         
    0 Error(s)                                                                                                                                                           
                                                                                                                                                                         
Time elapsed 00:00:04.9164533                                                                                                                                            
                                                                                                                                                                         
                                                                                                                                                                         
xUnit.net .NET CLI test runner (64-bit .NET Core ubuntu.16.04-x64)                                                                                                       
System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'parameter #2': Unknown error.                                                                  
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1. 
```

**Comment by nickolasacosta** [comment]
Some guys in the fsharp slack discovered this workaround.  TY @enricosada and @johnberzy-bazinga.

If you used this guide:
https://docs.microsoft.com/en-us/dotnet/articles/fsharp/tutorials/getting-started/getting-started-cross-platform-tooling
Go to: "Testing the Class Library with xUnit.net"
Step 8 tells you to remove the global dependencies section.

It is wrong.

If you look at the project.json in this repo, it includes a global dependencies section.
https://github.com/johnberzy-bazinga/fsharp-dotnet-cli-samples/blob/dotnettest/examples/preview2/test-xunit/project.json

If you use a global dependencies section, dotnet test will work on mac and linux.

**Comment by cartermp** [comment]
> If you use a global dependencies section, dotnet test will work on mac and linux.

This is definitely a bug then.  There should be no difference in execution between loading a dependency which was specified in a global section or underneath the `netcoreapp` section.  I doubt that this will be fixed, though, given that `project.json` is getting retired very soon and being replaced with the cross-platform MSBuild.

I'll update the document to specify that when using xUnit, you must specify your dependnecies in the global section.

**Comment by gregkalapos** [comment]
Same for me on macOS, and unfortunately the workaround did not help either. Moved everything to the global dependencies section, then 'dotnet restore'ed it (even removed the /bin /obj folders) in the 2. try, but still have the error described above.

**Comment by bradwilson** [comment]
We are deprecating `dotnet-test-xunit` because it's based on the old `project.json`-based system. The new MSBuild-based system (which is in .NET Core SDK 1.0 Preview 3 and later) is supported by the 2.2 beta 4 build of `xunit.runner.visualstudio` (yes, even on the command line in OS X and Linux).

**Comment by enricosada** [comment]
Ad a note:

Preview3 template for f#: https://github.com/dotnet/netcorecli-fsc/blob/master/examples/preview3/xunit/xf.fsproj

Preview4 template for f#: https://github.com/enricosada/cli/blob/11b361c9b2c9a691c6bf0532053b9062af02cd97/src/dotnet/commands/dotnet-new/FSharp_Xunittest/%24projectName%24.fsproj

**Comment by enricosada** [comment]
Preview2: https://github.com/enricosada/cli/blob/a12ef54f32cb7c6a51d2384030d309cfa94ad0e5/src/dotnet/commands/dotnet-new/CSharp_xunittest/project.json.template

**Comment by bradwilson** [comment]
Oops, sorry, bad button click. :-p

**Comment by bradwilson** [comment]
FWIW, that build number of `dotnet-test-xunit` in the preview 2 template was never something produced by our team. That was produced by the Microsoft team, and we did not/do not officially support it.

**Comment by enricosada** [comment]
@bradwilson that's the default for `dotnet-new` template. Just used same version of c#. too late to change it for next preview2 drop maybe. Or not, but is really soon. Same for preview4

**Comment by bradwilson** [comment]
We are not supporting any further builds of Preview 2 (and the build # inside of Preview 4 is fine). :)

**Comment by enricosada** [comment]
@bradwilson awesome. and thanks for builtin F# `async` support!

**Comment by gregkalapos** [comment]
Thanks for the responses.

Well, I wanted to still use project.json, since it seems to be more stable for me as the alpha of the new MSBuild-based system. Plus on Windows Visual Studio still does not understand the new fsproj, so (unless I overlooked something) there is zero F# support in VS currently (neither in 2015 nor in 2017RC).

Anyway I gave it a try:
The official  .NET Core SDK 1.0 Preview 3 build (from here https://www.microsoft.com/net/download/core) did not work, I run into this bug:
https://github.com/dotnet/cli/issues/4744
(Incredible that such a fundamental functionality was broken)

As suggested in that issue I installed the latest nightly build. It works with the templates of Enrico.

So the current setup, which works for me:
-Do not use the official Preview3 build -> install nightly builds
-Use the templates from Enrico (I used the one for Priview4)
-(For F# people: I guess atm you won't have Visual Studio support... only VS Code + CommandLine)

Thanks again guys!

**Comment by czifro** [comment]
Just wanted to add that Ionide for VS Code does not fully work well with Preview 4. The static analyzer cannot resolve dependencies. So most code that refs modules or types from another lib other than what is available without any package references in the fsproj, gets underlined as not being defined. atm, VS Code is just a text editor for me when writing F#.

**Comment by gregkalapos** [comment]
@czifro Yes, same for me...

**Comment by enricosada** [comment]
@czifro @gregkalapos for vs code ref https://github.com/dotnet/netcorecli-fsc/issues/29 , atm doesnt work because cannot parse compiler arguments (so intellisense doesnt work at all), i tried to fix with  https://github.com/ionide/FsAutoComplete/pull/30 but no luck yet 😢 but is near (because preview2 works). @cloudRoutine is also working on that
If you want to help (or stay updated), feel free to ping ionide or #dotnetcore channel on fsharp.org slack from help

**Comment by enricosada** [comment]
@czifro @gregkalapos as a note, now VS Code/Ionide works now with the released preview4. 
Just redo `dotnet restore` and use new templates (check `dotnet new -l fsharp`). tested with `1.0.0-preview4-004233`. 
Be sure to do `dotnet build` **before** opening VSCode, like preview2 ( ref https://github.com/ionide/ionide-vscode-fsharp/issues/312 )
Maybe with preview4 released, and because f# features are the same of preview2, you can reevaluate the upgrade (ignoring this bug)

**Comment by markvincze** [comment]
Hey @gregkalapos,

Did you find a workaround since then?
I moved all my deps to the global `"dependencies"` section, but I still get the same error, and at this point I'd like not to move to the new preview SDK bits yet.

Thanks,
Mark

**Comment by gregkalapos** [comment]
@markvincze I moved to the MSBuild based project system... Now there is also Ionide support, so Intellisense also works... I guess project.json based tools will die sooner or later (that's just me...not an official statement!), so you have to switch to the new fsproj at some point.

**Comment by markvincze** [comment]
@gregkalapos I see, thanks for the info!  
(Yeah, I wouldn't mind switching on just my machine, but we'd also have to adjust all of our CI toolchain, and I wouldn't like to do that until it's out of preview.)

**Comment by bradwilson** [comment]
Closed for age.
