### ISSUE TITLE
Assert.IsType() throws Xunit.Sdk.IsTypeException for generic types.

### ISSUE THREAD

**Issue by bbsimonbb** [xunit/xunit#860]
When the two parts of a generic type come from different libraries, the strong names returned by typeof() and GetType() are different even when the types are the same. This causes Assert.IsType() to blow up. [See here](http://stackoverflow.com/questions/37465195/xunit-testing-web-api-2-controller-throws-xunit-sdk-istypeexception/37478239#37478239).

**Comment by bradwilson** [comment]
Closed for age.
