### ISSUE TITLE
The process cannot access the file ...\dotnet-test-xunit.exe

### ISSUE THREAD

**Issue by andreasandreou** [xunit/xunit#861]
Hi,

every time I compile my test project I get the following error:

Error       Failed to make the following project runnable: MyProject.UnitTests (.NETFramework,Version=v4.5.2) reason: The process cannot access the file 'C:\MyProject.UnitTests\bin\Debug\net452\win7-x64\dotnet-test-xunit.exe' because it is being used by another process.  

this is very frustrating cause I have to close VS, wait for file to be released, delete it, reopen VS, compile run and back from the beginning.

Please advice what I can do.

For reference here is my project.json file:

{
    "version": "0.2.0",
    "description": "MyProject.UnitTests Class Library",
    "authors": [ "MyCompany" ],

```
"testRunner": "xunit",

"dependencies": {
    "dotnet-test-xunit": "1.0.0-rc2-build10025",
    "xunit": "2.1.0"
},

"frameworks": {
    "net452": { }
},

"buildOptions": {
    "preserveCompilationContext": true,
    "copyToOutput": {
        "include": [
            "config.json"
        ]
    },
    "warningsAsErrors": true
}
```

}

**Comment by bradwilson** [comment]
Closed for age.
