### ISSUE TITLE
IAsyncLifetime fixtures are potentially initialised more than once

### ISSUE THREAD

**Issue by Sumo-MBryant** [xunit/xunit#869]
If a test class includes more than one IAsyncLifetime implementing class fixtures, all existing class fixtures will have their ```InitializeAsync()``` calls re-invoked, and on test clean-up the number of calls to ```InitializeAsync()``` won't match the number of calls to ```DisposeAsync()```.

For example, if a class includes three class fixtures ```AlphaFixture```, ```BetaFixture```, and ```GammaFixture```. ```AlphaFixture``` will be invoked 3 times, ```BetaFixture``` twice, and ```GammaFixture``` once.

Collection fixtures are also affected.

Here is a test reproducing the bug: 

```cs
using System;
using System.Threading.Tasks;
using Xunit;

namespace Xunit.AsyncFixture.Bug
{
    public class AsyncFixture<T> : IAsyncLifetime
    {
        public int TimesInitialised { get; set; } = 0;

        public Task InitializeAsync()
        {
            ++TimesInitialised;
            return Task.CompletedTask;
        }

        public Task DisposeAsync()
        {
            return Task.CompletedTask;
        }
    }

    public class Alpha { }
    public class Beta { }
    public class Gamma { }

    /// <remarks>
    /// This test asserts that each class fixture should only have its InitializeAsync() function called once.
    /// </remarks>
    public class AsyncBugTests : IClassFixture<AsyncFixture<Alpha>>, IClassFixture<AsyncFixture<Beta>>, IClassFixture<AsyncFixture<Gamma>>
    {
        public AsyncBugTests(AsyncFixture<Alpha> alpha, AsyncFixture<Beta> beta, AsyncFixture<Gamma> gamma)
        {
            Assert.Equal(1, alpha.TimesInitialised);
            Assert.Equal(1, beta.TimesInitialised);
            Assert.Equal(1, gamma.TimesInitialised);
        }

        [Fact]
        public void Test()
        {
        }
    }
}
```

A workaround for this issue is to create a composite test fixture that initialises each fixture only once. Another workaround would be to ignore repeated calls to ```InitializeAsync()``` in the fixture.

A second potential bug is that async test fixtures are initialised serially and not in parallel, reducing the benefit of supporting async fixtures.

I would expect following test to only take 2 seconds to execute but due to the combination of both bugs takes 5 seconds.

```cs
using System;
using System.Threading.Tasks;
using Xunit;

namespace Xunit.Async.TimingBug
{
    public class AsyncFixture<T> : IAsyncLifetime
    {
        public async Task InitializeAsync()
        {
            await Task.Delay(1000);
        }

        public async Task DisposeAsync()
        {
            await Task.Delay(1000);
        }
    }

    public class Alpha { }
    public class Beta { }

    public class AsyncBugTests : IClassFixture<AsyncFixture<Alpha>>, IClassFixture<AsyncFixture<Beta>>
    {
        [Fact]
        public void Test()
        {
        }
    }
}
```

**Comment by onovotny** [comment]
Looking at the code, the `IAsyncLifetime`'s are initialized serially:
https://github.com/xunit/xunit/blob/6381c93738860481af501a2372f796492b6e8d42/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestClassRunner.cs#L92

That could be made to use a `Task.WhenAll(...)` to be concurrent.
