### ISSUE TITLE
Support nested test suites when reporting to TeamCity

### ISSUE THREAD

**Issue by redoz** [xunit/xunit#87]
TeamCity supports nested test-suites, it would be nice if xunit would take advantage of that when you use a test-structure like this http://haacked.com/archive/2012/01/02/structuring-unit-tests.aspx/ to generate easier to read/navigate test reporting in TeamCity
This also applies to Theories, it would be nice if they could be grouped together.

**Comment by bradwilson** [comment]
Closed for age.
