### ISSUE TITLE
XUnit test project throwing error on build

### ISSUE THREAD

**Issue by Gillardo** [xunit/xunit#873]
I have followed the instructions on the getting started page and created a test project that uses the net46 framework.  Here is my project json
```
{
    "version": "1.0.0-*",
    "testRunner": "xunit",
    "dependencies": {
        "xunit": "2.1.0",
        "dotnet-test-xunit": "1.0.0-rc2-*"
    },
    "frameworks": {
        "net46": {
            "dependencies": {
                "Microsoft.NETCore.Platforms": "1.0.1-rc2-24027"
            },
            "frameworkAssemblies": {
                "System.Runtime": "4.0.20.0",
                "System.ComponentModel": "4.0.0.0"
            }
        }
    },
    "buildOptions": {
        "copyToOutput": {
            "include": [ "xunit.runner.json" ]
        }
    }
}
```

Now upon building my project, i get this error.  Anyone have any clues why i am getting this?  It references dnx but i thought that was all dropped for dotnet cli now?

```
> ------ Discover test started ------
> ------ Test started: Project: m2i.Unite.Data.Tests ------
> Starting  Microsoft.Dnx.TestHost ["C:\Users\Me\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-20222\bin\dnx.exe" --appbase "E:\project\tests\m2i.Unite.Data.Tests" Microsoft.Dnx.ApplicationHost --port 63010 Microsoft.Dnx.TestHost --port 63761 --parentProcessId 1920]
> 
> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.CommandLineUtils, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
> File name: 'Microsoft.Extensions.CommandLineUtils, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
>    at Microsoft.Dnx.TestHost.Program.Main(String[] args)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
>    at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()
> 
> WRN: Assembly binding logging is turned OFF.
> To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
> Note: There is some performance penalty associated with assembly bind failure logging.
> To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
> 
> Unable to start Microsoft.Dnx.TestHost
> ========== Discover test finished: 0 found (0:00:01.0529879) ==========
```

I have installed visual studio tooling preview 2 along with visual studio 2015 update 2.  
Dotnet cli is version 1.0.0-preview2-002913

**Comment by bradwilson** [comment]
There are two issues I see:

1. I see mentions of DNX. There should be no DNX used in a .NET Core application.
2. We only officially support tooling preview1, as illustrated on our [Getting Started with .NET Core](https://xunit.github.io/docs/getting-started-dotnet-core.html) documentation page. While preview2 may work as-is, we will not be able to offer any support for people on daily builds.

**Comment by Gillardo** [comment]
But why are there mentions of DNX?  I do not believe i am referencing DNX and i am using dotnet cli to run tests.  Is this because of VS2015? Does VS2015 use DNX only?

**Comment by bradwilson** [comment]
I assume you have installed the VS tooling for .NET CLI, as well as VS 2015 Update 2?

https://blogs.msdn.microsoft.com/visualstudio/2016/05/16/announcing-updated-web-development-tools-for-asp-net-core-rc2/
https://www.visualstudio.com/en-us/news/vs2015-update2-vs.aspx

**Comment by Gillardo** [comment]
Yes i have both installed

![image](https://cloud.githubusercontent.com/assets/7406381/16072856/ebfb9182-32da-11e6-96f4-800576f685db.png)

![image](https://cloud.githubusercontent.com/assets/7406381/16072889/1f71354e-32db-11e6-906f-53c0d7bc2c16.png)

**Comment by bradwilson** [comment]
**_Assuming you have not made any changes to the source you wish you keep:_**

Please shut down Visual Studio, then from your Git command line, run:

* `git reset --hard`
* `git clean -xdf`

on the root of the repository.

Then re-open the solution in Visual Studio and try building,

**Comment by Gillardo** [comment]
Tried that and upon building i get this in output

========== Load Playlist finished (0:00:00.0029841) ==========
------ Discover test started ------
------ Test started: Project: my.Project.Data.Tests ------
Starting  Microsoft.Dnx.TestHost ["C:\Users\Me\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-20222\bin\dnx.exe" --appbase "E:\Github\myProject\tests\my.Project.Data.Tests" Microsoft.Dnx.ApplicationHost --port 57878 Microsoft.Dnx.TestHost --port 58687 --parentProcessId 48156]
------ Test started: Project: my.Project.Service.Tests ------
Starting  Microsoft.Dnx.TestHost ["C:\Users\Me\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-20222\bin\dnx.exe" --appbase "E:\Github\myProject\tests\my.Project.Service.Tests" Microsoft.Dnx.ApplicationHost --port 57878 Microsoft.Dnx.TestHost --port 58688 --parentProcessId 48156]
------ Test started: Project: my.Project.Web.Tests ------
Starting  Microsoft.Dnx.TestHost ["C:\Users\Me\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-20222\bin\dnx.exe" --appbase "E:\Github\myProject\tests\my.Project.Web.Tests" Microsoft.Dnx.ApplicationHost --port 57878 Microsoft.Dnx.TestHost --port 58691 --parentProcessId 48156]

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.CommandLineUtils, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Extensions.CommandLineUtils, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.Dnx.TestHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Unable to start Microsoft.Dnx.TestHost

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.CommandLineUtils, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Extensions.CommandLineUtils, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.Dnx.TestHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Unable to start Microsoft.Dnx.TestHost

Error: Environment variable name or value is too long.
Unable to start Microsoft.Dnx.TestHost
========== Discover test finished: 0 found (0:00:04.4903359) ==========

**Comment by bradwilson** [comment]
Your Visual Studio tooling is definitely busted. Nothing I can do to help, sorry.

**Comment by Gillardo** [comment]
I will try uninstalling all references to VS and reinstall.  Hopefully this will sort it

**Comment by Gillardo** [comment]
It seems that uninstalling all vs tooling and dotnet cli installations and then reinstalling, seems to sort this out
