### ISSUE TITLE
Default traits for facts and theories that are not marked with TraitAttribute

### ISSUE THREAD

**Issue by feO2x** [xunit/xunit#875]
What's your opinion on a way to specify one or more default trait(s) for all facts and theories that are not marked with the `TraitAttribute`? This might be done as an assembly attribute specified in AssemblyInfo.cs, or via XML configuration in App.config.

Personally, I like to divide my test methods into different categories on large projects, so that I can easily distinguish and run e.g. functional, informative and performance tests. The default NoTrait category is not that user-friendly in this regard, and applying the `TraitAttribute` to every functional test class is somewhat of a nuisance and can easily be forgotten. Convention over configuration.

**Comment by bradwilson** [comment]
Assembly-level traits exist now, but they are unconditional. Otherwise, closed for age.
