### ISSUE TITLE
Can't build xunit.runner.utility.desktop.csproj with build.ps1

### ISSUE THREAD

**Issue by TimLovellSmith** [xunit/xunit#878]
C:\repo\xunit>powershell .\build.ps1
  Restoring NuGet packages...
  xunit.assert -> C:\repo\xunit\src\xunit.assert\bin\Debug\xunit.assert.dll
C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(140,5):
error : Your project is not referencing the ".NETFramework,Version=v3.5" framew
ork. Add a reference to ".NETFramework,Version=v3.5" in the "frameworks" sectio
n of your project.json, and then re-run NuGet restore. [C:\repo\xunit\src\xunit
.runner.utility.desktop\xunit.runner.utility.desktop.csproj]
  xunit.core -> C:\repo\xunit\src\xunit.core\bin\Debug\xunit.core.dll
  test.xunit1 -> C:\repo\xunit\test\test.xunit1\bin\Debug\test.xunit1.dll
  xunit.execution.desktop -> C:\repo\xunit\src\xunit.execution.desktop\bin\Debu
  g\xunit.execution.desktop.dll
  xunit.execution.dotnet -> C:\repo\xunit\src\xunit.execution.dotnet\bin\Debug\
  xunit.execution.dotnet.dll
  xunit.runner.utility.dotnet -> C:\repo\xunit\src\xunit.runner.utility.dotnet\
  bin\Debug\xunit.runner.utility.dotnet.dll
  xunit.runner.reporters.dotnet -> C:\repo\xunit\src\xunit.runner.reporters.dot
  net\bin\Debug\xunit.runner.reporters.dotnet.dll

**Comment by bradwilson** [comment]
Do you have .NET 3.5 installed on your system? That is a pre-requisite to being able to build.

**Comment by TimLovellSmith** [comment]
@bradwilson I do have .NET 3.5 installed AFAICT from Windows Add/Remove features, is there a better way to check?
![gotdotnet35](https://cloud.githubusercontent.com/assets/2711795/16054141/c0d68da0-3220-11e6-83c0-cb3959b729ff.png)

**Comment by bradwilson** [comment]
That should be all that's necessary. I've never had anybody else tell me that have compilation failures (none of us have any problems, nor does the CI machine), so I'm not really sure what's going on.

**Comment by TimLovellSmith** [comment]
Aha.. I think I found the problem. I have a project.lock.json file in that directory and deleting it may have fixed the issue!

I think that was a leftover from building xunit a long long time ago.

Closed.
