### ISSUE TITLE
Consider allowing MemberAttributeData look for members on tests' reflected type

### ISSUE THREAD

**Issue by blairconrad** [xunit/xunit#879]
I was converting a test hierarchy (see [ArgumentConstraintTestBase](https://github.com/FakeItEasy/FakeItEasy/blob/295e3dbb2f89097fcd27660299a03a46997060e4/tests/FakeItEasy.Tests/ArgumentConstraintTestBase.cs), if interested) that defines tests in the base class which operate on data generated by the subclasses. Under NUnit, the tests were decorated with `[TestCaseSource]`, similar to `[MemberData]`. The NUnit runner looks for matching test case sources starting on the class of the test that is running, but `MemberData` requires the public static source to be declared on the class that declares the tests, so there is no way (that I could fathom) to have the derived classes provide their own test data.

I'm not suggesting to have the attribute look for data on non-static methods, but would there be interest in having `MemberDataAttribute` look for data from static members declared on the reflected type of the test method, rather than the declaring type?
This could be made the default behaviour or it could be triggered by an argument to the `MemberDataAttribute` constructor.

If there's interest, I'd be happy to work on a PR.

**Comment by bradwilson** [comment]
Fixed by #967
