### ISSUE TITLE
efficiency of TestMessageVisitor in XUnit 2.1

### ISSUE THREAD

**Issue by TimLovellSmith** [xunit/xunit#880]
After picking up XUnit 2.1 and setting ("appDomain": "denied") on my test assemblies it still didn't feel fast, so I did some profiling of xunit actually running tests with CPU sampling, via msbuild, full .net framework. I notice there seems to be some inefficiency in dispatching test result messages:

_MessageBus.ReporterWorker_ accounted for 40% of CPU samples. 37.8% of these were going to _XUnit.XmlTestExecutionVisitor.OnMessage_ but that was nearly of that is the call to base, _TestMessageVisitor.OnMessage_.

_TestMessageVisitor.OnMessage_'s _DoVisit()_ (37.6%) calls seem to spend 35.1% of samples calling _JITutil_IsInstanceOfAny@8_ so it can figure out which method overloads it will actually call.

It seemed like it should be possible to rewrite this to be more efficient and only call Visit() overloads corresponding to interfaces actually implemented by the message that's being dispatched. However I ran into all sorts of problems trying to implement such a strategy due to the fact the messages are going across remoting and AreTransparentProxy...

**Comment by bradwilson** [comment]
Dup of #472.
