### ISSUE TITLE
Problems testing class that uses SynchronizationContext.Post

### ISSUE THREAD

**Issue by brianlagunas** [xunit/xunit#883]
I am having the hardest time trying to test a ICommand class the uses the SynchronizationContext.Post method.  Every test fails because the Post hasn't completed by the time the Assert is checked.  How on earth do I do this with xUnit?

Scenario; the DelegateCommand class has a static property that it uses to grab the SyncContext.

```
private static readonly SynchronizationContext _synchronizationContext = SynchronizationContext.Current;
```
Then, when ever the OnCanExecuteChnaged is called, we use the SyncContext if we are on a different thread to post the event to the UI thread.

```
        protected virtual void OnCanExecuteChanged()
        {
            if (_synchronizationContext != null)
                _synchronizationContext.Post((o) => CanExecuteChanged?.Invoke(this, EventArgs.Empty), null);
            else
                CanExecuteChanged?.Invoke(this, EventArgs.Empty);
        }
```

The issue comes when I write a simple test like this:
```
        [Fact]
        public void RaiseCanExecuteChangedRaisesCanExecuteChanged()
        {
            var handlers = new DelegateHandlers();
            var command = new DelegateCommand<object>(handlers.Execute);
            bool canExecuteChangedRaised = false;
            command.CanExecuteChanged += delegate { canExecuteChangedRaised = true; };

            // we called our OnCanExecuteChanged method
            command.RaiseCanExecuteChanged(); 

            // SyncContext.Post hasn't completed so this fails
            Assert.True(canExecuteChangedRaised);
        }
```

How on earth do I tell my xUnit test to wait until th epost has competed, or turn off the SyncContext all together per test?

**Comment by bradwilson** [comment]
You will have to remove the sync context yourself in the test.

That said: statics are an anti-pattern in unit testing. A design which relies on statics is almost always difficult (sometimes impossible) to test.

**Comment by brianlagunas** [comment]
How do you remove the SyncContext?  I could find away.  I tried 
```
        public DelegateCommandFixture()
        {
            SynchronizationContext.SetSynchronizationContext(null);
        }
```
But the DelegateCommand being called always has a SyncContext.  Ideas?

**Comment by brianlagunas** [comment]
The reason there is a static is so that we can capture the UI SyncContext.  That way if any instance of the object is created on a separate thread, we can still Post messages to the UI thread.

Is there a better way?

**Comment by onovotny** [comment]
@brianlagunas one thing to be aware of, in UWP, if you have multiple top-level windows, each has their own UI thread....so using a static would capture the wrong context potentially.

**Comment by brianlagunas** [comment]
@onovotny ohhh, didn't know that.  That right there is reason enough for me not to store the UI SyncContext off.

Is there a way to turn off the SyncContext in xUnit?

**Comment by bradwilson** [comment]
> Is there a way to turn off the SyncContext in xUnit?

No.

xUnit.net uses two synchronization contexts: one to support parallelization limitations, and one to support `async void` test methods. The former can be disabled, but the latter cannot be removed.

**Comment by brianlagunas** [comment]
Thanks for the info.
