### ISSUE TITLE
Allow xunit test runner filter tests by classname, methodname and trait.

### ISSUE THREAD

**Issue by savpek** [xunit/xunit#884]
Original XUnit runner (and probably most console test runners) supports filtering tests with way or another. 

If there is way with "dotnet test" to archieve this i cant figure it out. It is coulg be usefull for example set dotnet watch --trait "UnitTest" when writing new code to make feedback loop even faster.

**Comment by bradwilson** [comment]
Run `dotnet test -help`.

**Comment by savpek** [comment]
Ah, ok, i have only checked --help option that seems to write "dotnet-test" tool output, not underlaying xunit test runner command line help.

Passing arguments to underlying test runner seems bit messy, i first though it works like dotnet run where command line arguments to software goes after '--' (like dotnet run -- argumenthere).
