### ISSUE TITLE
xUnit.net VSIX is Deprecated page points to missing "running-tests-in-vs.html"

### ISSUE THREAD

**Issue by blairconrad** [xunit/xunit#887]
[xUnit.net VSIX is Deprecated](http://xunit.github.io/docs/vsix-deprecated.html) points to non-existent page http://xunit.github.io/docs/running-tests-in-vs.html.
This introduces confusion for the user, who is redirected to http://xunit.github.io/, and ultimately left unenlightened as to how to run tests in VS.

**Comment by blairconrad** [comment]
Perhaps pointing to https://xunit.github.io/docs/getting-started-desktop.html#run-tests-visualstudio would be preferable?

**Comment by bradwilson** [comment]
Done. Thanks!

**Comment by blairconrad** [comment]
Oh, thanks! I feel bad. I woulda submitted a PR.
