### ISSUE TITLE
XML reports are incomplete when project.json targets multiple platforms

### ISSUE THREAD

**Issue by plioi** [xunit/xunit#888]
# Sample test project's project.json

My test project's project.json targets two frameworks, and dotnet test reacts to that by running the tests twice, once for each framework.

``` javascript
{
  "testRunner": "xunit",
  "dependencies": {
    "Parsley": { "target": "project" },
    "Shouldly": "2.7.0",
    "xunit": "2.1.0",
    "dotnet-test-xunit": "1.0.0-rc2-build10025"
  },

  "frameworks": {
    "net452": {
      "dependencies": {
        "Microsoft.NETCore.Platforms": "1.0.1-rc2-24027"
      }
    },
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0-rc2-3002702"
        }
      },
      "imports": [
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  }
}
```
# Sample test will fail in one of the two runs

``` csharp
        [Fact]
        public void FailForOneTarget()
        {
#if NETCOREAPP1_0
            throw new System.Exception("Test failed in netcoreapp1.0.");
#endif
        }
```

Console output shows that my 116 tests are executed twice and that only one of them fails, as expected:

![image](https://cloud.githubusercontent.com/assets/652745/16230515/64c21a18-3787-11e6-93bc-1eb3b3afc7dc.png)
# Expected behavior

With the -xml option (near the top of the screenshot), I expect either an XML file with 116*2 test results, one of which is a failure, or possibly we have a new need to output multiple XML files, one per target.
# Actual behavior

The xml file only contains results from the regular .net framework run.  It's possible that XML was generated for both, and the second run overwrote the first.

**Comment by bradwilson** [comment]
Yeah, the problem is, we are invoked twice with two different DLLs, with the same XML filename. Our behavior has always been to overwrite the existing file. This would happen the same way if you'd done the same behavior by hand with any of our other runners.

The workaround is to invoke `dotnet test` twice, once for each framework, and pass a different XML filename for each invocation. Example:

```bash
$ dotnet test src\Parsley.tests --framework netcoreapp1.0 -xml netcoreapp.xml
$ dotnet test src\Parsley.tests --framework net452 -xml net452.xml
```

**Comment by plioi** [comment]
Thanks for the advice. That makes sense.

**Comment by Symbianx** [comment]
Are there any thoughts on this issue? 
Maybe the option to add a "?{datetime}" placeholder in the -xml parameter that would be replaced with the current date and time. An even better option would be a framework placeholder but looking at the code, i don't think that is possible.

**Comment by bradwilson** [comment]
This issue is talking about project.json, which is not officially supported (and never will be), so there is unlikely to be any kind of resolution.

**Comment by Symbianx** [comment]
Didn't realize this issue didn't apply to .csproj. Oops
