### ISSUE TITLE
Tests are grouped under the "No Traits" section in the Test Explorer even though the class has a [Trait] attribute

### ISSUE THREAD

**Issue by TheBeardedLlama** [xunit/xunit#889]
I have set up my controller tests for a .net core web api xproj.

I have a `TraitAttribute` on the class, but it's not showing up in the *Test Explorer* in VS.

My `dependencies` have `"dotnet-test-xunit": "1.0.0-*"` and `"xunit": "2.2.0-*"` and the test runner is set up as `"testRunner": "xunit"`.

Have I hit a bug or am I doing something wrong? I'm hoping I'm doing something wrong :smile:

**Comment by bradwilson** [comment]
This is a problem with the Visual Studio tooling owned by Microsoft, not with us. Their adapter does not send along any metadata like traits to the runner. This is unique to the .NET CLI tooling, as traits do work in all other scenarios.

**Comment by TheBeardedLlama** [comment]
Ah ok, apologies @bradwilson!

Should I post over there or do you know if there is a filed issue already?

**Comment by bradwilson** [comment]
I don't know if there's an issue or not.

**Comment by TheBeardedLlama** [comment]
Ok I'll have a look
