### ISSUE TITLE
Console Runner returns wrong error-code for failing tests

### ISSUE THREAD

**Issue by hkoestin** [xunit/xunit#894]
I am using version 2.1.0 of the xunit.runner.console and am getting weird results for the error-code, after unit-test execution.

It seems, that the return code is actually the number of failing tests. Could this be?

![image](https://cloud.githubusercontent.com/assets/13849875/16332496/7f6ad898-39f6-11e6-990c-7f55bd05128d.png)

However, according to the documentation, 1 should indicate failing tests:
http://xunit.github.io/docs/getting-started-desktop#console-return-codes

Is this a bug or am I using something wrong?

**Comment by bradwilson** [comment]
Those exit codes are new for version 2.2. I'll update the funds to make this clear. Thanks.

**Comment by bradwilson** [comment]
Actually, upon reviewing the text that you linked to, it already clearly states that these exit codes are for version 2.2 and later.
