### ISSUE TITLE
xunit.runner.visualstudio.testadapter.dll missing from dotnet build output

### ISSUE THREAD

**Issue by couven92** [xunit/xunit#895]
If I reference the xunit.runner.visualstudio package as a dependency in my `project.json` (example `project.json` below), the dll `xunit.runner.visualstudio.testadapter` is not included in the build output produced by `dotnet build`.

This effectively prohibits me from using the Visual Studio Test Task in automated Builds in Team Foundation Server and other tools that build upon the VsTest testing framework.

Interestingly enough, when I locate the package on disk in my Nuget packages location, the `xunit.runner.visualstudio.testadapter.dll` is included in the `build/_common` folder of the package.

Here's a sample of project.json

``` json
{
  "dependencies": {
    "MyAwesomeProject": { "target": "project" },

    "xunit": "2.2.0-*",
    "xunit.runner.visualstudio": "2.2.0-*"
  },

  "frameworks": {
    "net451": {},
    "net452": {},
    "net46": {},
    "net461": {}
  }
}
```

Not that in this case, I'm NOT trying to integrate xunit test with .NET Core (I'd use dotnet-test-xunit for that)! I am only targeting Full .NET CLRs where the test adapter is supposed to be supported!

As expected setting specific version numbers instead of `2.2.0-*` in the xunit package versions does NOT fix or change anything.

Also, specifying the runtime (as shown below) in the `project.json` does not help.

``` json
{
  "runtimes": { "win": { } }
}
```

Interestingly, if I convert the entire thing into a `.csproj` project using the traditional C# project model, and then use NuGet package restore (with the same compatible `project.json`), the CSC compiler in MSBuild will happily include the necessary dll in its build output. But having a traditional .csproj project file instead is not a feasable option as it is not possible to reference xproj (dotnet-CLI) projects from them.

**Comment by onovotny** [comment]
For xproj, I believe you have to use the CLI runner...and that does work in VS and probably team build.

However, it is possible to reference xproj from CSproj and I describe how to do it here: http://stackoverflow.com/a/37907973/738188

I do that for UWP test projects testing xproj-build assemblies.

**Comment by chrisseroka** [comment]
Hi, I faced the same problem. CLI runner does not solve the problem because there is no option to produce code coverage report. There is additional tool from Microsoft "CodeCoverage.exe" but the coverage report cannot be published to Team Foundation Server (see https://github.com/Microsoft/vsts-tasks/issues/1958)

Is there a reason why the file is not copied in case of project.json?

**Comment by couven92** [comment]
I have found a (temporary?) solution that is a little less intrusive and may serve as an alternative to what @onovotny is proposing:

This applies to Visual Studio Team Foundation Server Automated Builds:

In the root of your sources directory place a `packages.config` file with the following contents:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<packages>
  <package id="xunit" version="2.2.0-beta2-build3300" targetFramework="net46" />
  <package id="xunit.runner.visualstudio" version="2.2.0-beta2-build1149" targetFramework="net46" />
</packages>
```

In the Automated Build Definition add the `NuGet Installer` (under the `Packages` taks category) taks to the beginning of the build definition. Configure the following settings:
Path to Solution: `packages.config`
NuGet Arguments: `-PackagesDirectory packages`

This will cause NuGet to restore the xunit.runner.visualstudio package to a subfolder `packages` which basically is the 'old' traditional NuGet (not dotnet) and MSBuild compatible way of restoring packages for a solution.

The documentation for VsTest states that additional test adapters (like `xunit.runner.visualstudio.testadapter`) have to be specified via the `/TestAdapterPath` option, but it also states that NuGet restore packages are included automatically.

Thus we can now create continue the steps listed in https://xunit.github.io/docs/getting-test-results-in-vsts.html . And yes, @chrisseroka, if you tick the "Code Coverage Enabled" checkbox in the task configuration, the it even will do Code Coverage.

I came up with this solution tonight (June 28th 2016) and tested it successfully (even with Code Coverage) this morning on my On-Premise Team Foundation Server 2015.

**Comment by bradwilson** [comment]
We don't control what `dotnet build` produces, so we can't fix that.

We'll see if there's anything we can do about this, but I wouldn't hold out a lot of hope.

**Comment by couven92** [comment]
So, I should create an issue on https://github.com/dotnet/cli ?

**Comment by bradwilson** [comment]
You can try, though I suspect that they will reject it, since the current package uses `.csproj` NuGet behavior to get copies of the files rather than outright references.

**Comment by couven92** [comment]
@bradwilson, so maybe we could do something about that?

**Comment by bradwilson** [comment]
As @onovotny already pointed out, the .NET CLI runner is what should be used for all .NET CLI (aka, .xproj) projects. The fact that it is not as feature-filled as the older adapter system is something you should take up with the Visual Studio team.

**Comment by rschiefer** [comment]
@couven92 I tried your workaround for the VS Test task and my xunit tests still aren't found.  I also added a Commandline task to run dotnet test and that does run my tests.  They run locally as well via the Test Explorer.

Is this still working for you?  I would really like to get this working with test results and code coverage on the build summary page.

Also, did you open an issue on the dotnet/cli repo?  If you do, I will support it.

**Comment by couven92** [comment]
@rschiefer Contrary to the documentation that states that you do not have to specify NuGet added test adapters, I found adding the path to the packages directory IS required.
Therefore, I also added the following option for `Path to Custom Test Adapters` under `Advanced Execution Options` in the VsTest task configuration: `$(Build.SourcesDirectory)\packages`

Then everything worked like a dream :)

I have also updated my previous comment in this thread, to reflect this additional configuration.

**Comment by rschiefer** [comment]
That sounds like the solution to my problem but after implementing it, my tests are still not found via the VS Test task.  Any other ideas?

**Comment by Allann** [comment]
Not exactly the same circumstances, but I fixed a very similar problem (_after being told to convert my package.config to project.json to fix another xunit dependency issue_).

I had to do the following:

- In NuGet restore task - add **-PackagesDirectory $(Build.SourcesDirectory)\packages\** in NuGet arguments
- In VSTest task - add **$(Build.SourcesDirectory)\packages\** to Advanced Execution Options 'Path to Custom Test Adapter'.

Builds now pick up tests and correctly report results and coverage.  No need to add the package.config "hack" mentioned above.

Please note that this changes the default project.json local cache defaults and copies all packages into a packages folder.  However, I see this as a good thing because you are assured that dependencies are restored on a build further verifying the build validity.

Hope this helps someone else.

**Comment by couven92** [comment]
@Allann that's the same solution as I described! But I only put the XUnit dependency into packages.config, since I'm happy with dotnet handling its dependencies. The build command places the non-GAC dependencies into the build output folder anyway.

**Comment by bradwilson** [comment]
Closed for age.
