### ISSUE TITLE
I need to run a theory from the console for specific values

### ISSUE THREAD

**Issue by bg85** [xunit/xunit#897]
I need to be able to run a theory from the console runner but I need to specify the values it needs to run with. Is this possible ? If it is, how can I do it?

Thanks in advance,

**Comment by bradwilson** [comment]
Sorry, there is no way to do this from the command line today that is built-in.

You could create a data provider attribute (like `[InlineData]`) that read its data from a file on disk, and before running the tests, put the appropriate data into the file. That's the simplest workaround I can think of.

**Comment by bradwilson** [comment]
Closed for age.
