### ISSUE TITLE
Bug: ITestCaseOrderer receives test cases from a single class, not from a collection

### ISSUE THREAD

**Issue by johncrim** [xunit/xunit#898]
It is possible to specify the `TestCaseOrderer` for a collection, eg:

```
    /// <summary>Defines the xunit test collection.</summary>
    [CollectionDefinition(SampleTestCollection.Name)]
    [TestCaseOrderer("Base.Test.Dependency.DependencyTestOrderer", "Base.Test")]
    public class SampleTestCollection
    {
        public const string Name = "DependencySampleTests";
    }
```

This works, in that all the test classes in the collection use the specified `ITestCaseOrderer`. However, all the test cases in a multi-class collection _are not_ passed into `ITestCaseOrderer.OrderTestCases`. Instead, the set of test cases contained in each class is passed in one class at a time.

I would expect all test cases within a collection to be treated as a unit. They share fixtures, and should be orderable together.

Currently there is support for pluggable test collection ordering, and test case ordering. If test case ordering is intended to only be within a class, then we would also need support for pluggable test class ordering.

My specific use-case is that I've created a dependency test orderer, eg a test or class can specify tests that must be run before it can be run. (I'd be happy to share it or open-source it.) It's not so useful if the test case dependencies can only be used within a single test class.

**Comment by bradwilson** [comment]
Closed for age.

**Comment by aqbjteddy** [comment]
@bradwilson How did u solved this problem? We have same needs to order test cases cross classes.

**Comment by bradwilson** [comment]
This is not possible today.

**Comment by tomaszeman** [comment]
You can use this implementation that suports collection/class/case level ordering https://github.com/tomaszeman/Xunit.Extensions.Ordering
