### ISSUE TITLE
ITestCaseOrderer message sourcing is too restricted

### ISSUE THREAD

**Issue by johncrim** [xunit/xunit#902]
As recommended here: #443 - in implementations of `ITestCaseOrderer.OrderTestCases`, a `DiagnosticMessage` can be posted and can be viewed in the test output, only if the `-diagnostics` switch is active for the testrunner.

None of these message types seem to work in `ITestCaseOrderer.OrderTestCases`:
- Error message
- Warnings
- Skip test case
- Test case failure

In short, there is no capability in the test case orderer to raise errors or make any sort of loud noise. I think is is a mistake because the `ITestCaseOrderer` is a simple pluggable pattern, and it's feasible for failures to occur. (On a related note, exceptions thrown from the `OrderTestCases` method are swallowed rather silently - they're visible only if `-diagnostics` is enabled. I also think this is a problem.)

A `TestCaseOrderer` can remove test cases from the ordered result, which is great; but there should be a way to specify why the test cases were skipped or failed, instead of silently removing them.

My specific use-case is a `DependencyTestOrderer`, which allows tests to specify dependencies like:

```
[Fact]
[DependsOnTest("B")]
public void A() {}

[Fact]
[DependsOnTest("C")]
public void B() {}

[Theory]
[InlineData("c1")]
[InlineData("c2")]
[DependsOnTest("D")]
public void C(string s) {}

[Fact]
public void D() {}
```

In the case that a cycle occurs in the test dependency graph, the cycle is excluded; however I'd like to be able to make a loud noise and fail the test cases that are excluded.

**Comment by bradwilson** [comment]
Closed for age.
