### ISSUE TITLE
Strange behaviour with MaxParallelThreads

### ISSUE THREAD

**Issue by ivaylokenov** [xunit/xunit#905]
Hi, guys!

I got stuck with a strange issue using xUnit. Running parallel tests hangs on some machines with the default MaxParallelThreads value.

Unfortunately I cannot give small repro because I found it after quite a lot of written code but here are more details. I have unit tests for this project - https://github.com/ivaylokenov/MyTested.AspNetCore.Mvc. Running them locally never got me any problems, no matter if I used the console or the Visual Studio test runner. I started using a CI server and tests started hanging and not finishing for an hour (which is ridiculous) - https://ci.appveyor.com/project/ivaylokenov/mytested-aspnetcore-mvc/history

These are the only tests I run on the CI

```
dotnet test "samples/MusicStore/MusicStore.Test/project.json" --configuration Release
```

Asked the CI support and he was having the problem on his local machine too - http://help.appveyor.com/discussions/problems/4973-xunit-unit-tests-hang-randomly-in-the-ci. So out of three machines, only one is working. The CI has 2 cores, the support's machine has 4 and my own machine has 8.

At first I thought the problems may be deadlocks from my code because I have execution of tasks in a synchronous context here and there, so I tried playing around with various solutions over the Internet. No matter what I did, on my machine tests worked, on the CI they hanged. Disabling parallel tests made the CI pass, but that was not I wanted. This class is what I use to run async code:

https://github.com/ivaylokenov/MyTested.AspNetCore.Mvc/blob/development/src/MyTested.AspNetCore.Mvc.Core/Internal/AsyncHelper.cs

After trial and error I made the tests pass on the CI by setting 

```
[assembly: CollectionBehavior(MaxParallelThreads = -1)]
```

So with unlimited number of threads the tests runs fine. Any suggestions how to fix this problem? Is this xUnit problem? Possible solution?

**Comment by TimLovellSmith** [comment]
@ivaylokenov 
If you can reproduce the issue, attach a debugger to the hung process (or reproduce it by debugging), and find the call stacks for the execution threads, that should help reveal what locks/handles the deadlock is caused by and maybe pinpoint the bug.

**Comment by ivaylokenov** [comment]
@TimLovellSmith I will try, however, on my own machine everything works fine everytime. Will play around and report, if I find something useful.

**Comment by bradwilson** [comment]
Closed for age.

**Comment by bradwilson** [comment]
I can usually track down these things by setting MaxParallelThreads to 1, and then turning on long-running test detection. That'll almost always isolate it to the test that's inappropriately waiting.

**Comment by bradwilson** [comment]
In fact, our CI runs with MaxParallelThreads set to 1 always because it helps us know if we inadvertently introduced a deadlock. :)

**Comment by Fresa** [comment]
I have the exact same issue with Appveyor. Weird thing is that I have multiple similar projects in Appveyor that has no problem with parallel execution, but this one project it just hangs on Appveyor. The tests works perfectly fine in parallel with Resharper, NCrunch and Xunit.console.runner locally, so I don't believe there is anything wrong with them.

https://ci.appveyor.com/project/Fresa/test-it-while-hosting-your-web-application/build/1.0.20

As soon as I disable parallel collections, it works fine on the CI server:
https://ci.appveyor.com/project/Fresa/test-it-while-hosting-your-web-application/build/1.0.24

**Comment by bradwilson** [comment]
Yep, that's definitely a deadlock. Your local machine probably has a much larger CPU count (most developers are using at least a quad-core hyperthreaded CPU, so their default # of threads is 8).

**Comment by bradwilson** [comment]
@Fresa As expected, I see improper uses of `.Result` on Tasks. This will cause deadlocks. https://github.com/Fresa/Test.It.While.Hosting.Your.Web.Application/blob/1463031b726e09dc09494f87d5a2e3be29dec0a9/tests/Test.It.While.Hosting.Your.Web.Application.Tests/Given_a_foo_bar_application_when_getting_a_bar_from_foo.cs#L33

**Comment by Fresa** [comment]
Thanks for your feedback! 

As I know you are de facto Mr xUnit :), I'd love to get some tip on how I should use async methods in this case? I've tested to add ConfigureAwait(false), but that didn't help. Then I came across this: https://github.com/xunit/xunit/issues/864 

Does this mean that If I need to use an async method in a xUnit with parallelization, the test must have async/await "the whole way", beginning with the Fact, otherwise I might get deadlocks?

**Comment by bradwilson** [comment]
> Does this mean that If I need to use an async method in a xUnit with parallelization, the test must have async/await "the whole way", beginning with the Fact, otherwise I might get deadlocks?

Yes.

**Comment by Fresa** [comment]
Since I initialize the test specification from the constructor, async/await did not work well for me. Then I found out about IAsyncLifetime (it _really_ should be included in the documentation) and rewrote my framework and tests. Now everything works fine on Appveyor with parallel testing!

Thanks again!
