### ISSUE TITLE
Assert.Equal and multidimension arrays

### ISSUE THREAD

**Issue by artemsa** [xunit/xunit#907]
Take the following code: 
`Assert.Equal(new object[,] {{1}, {2}}, new object[,] {{1, 2}});`

Two arrays to are not equal - they have the different dimension lengths. I expected exception with "Expected is System.Object[2,1], actual is System.Object[1,2]" error message.

**Comment by jongleur1983** [comment]
To make clear: you assume that that Assertion should have failed while it did not.
I added a test for that here https://github.com/jongleur1983/xunit/commit/71ebaeddba1180ce3c65599591bc603ed43e0bbe

**Comment by jongleur1983** [comment]
The underlying problem seems to be that Arrays and Collections are compared using the default object comparer. Unfortunately Arrays seem not to be considered as IEnumerable by default in C#, thus the enumerable comparer is not used.
