### ISSUE TITLE
[VS test runner] Test runner does not report ITestSkipped.Message

### ISSUE THREAD

**Issue by ig-sinicyn** [xunit/xunit#908]
How to reproduce: 
 run `DynamicSkipExample.DynamicallySkipped()` test from XUnit.Samples repo (uses v2.2.0-beta1-build3239).

Expected result: exception message shown in VS Test Runner window

Actual behavior (skipped | failed):
![skipped_vs_failure](https://cloud.githubusercontent.com/assets/11225241/16851737/f945e49e-4a15-11e6-9191-5cf94aa1ab9a.png)

**UPD** same behavior when run from ReSharper test runner: exception message is swallowed.

**UPD2** Also, `Xunit.Sdk.TestSkipped` class should provide .ctor parameter for output. The current implementation [passes null](https://github.com/xunit/xunit/blob/6381c93738860481af501a2372f796492b6e8d42/src/messages/TestSkipped.cs#L18). 

**UPD3** And same for duration :)

**Comment by ig-sinicyn** [comment]
Emm, up?

**Comment by ig-sinicyn** [comment]
up again:(

**Comment by bradwilson** [comment]
We do not control this output. This bug belongs to the VSTest team (https://github.com/microsoft/vstest), as they control the display inside Visual Studio.

Here is our console runner output, which properly reports the messages:

![image](https://cloud.githubusercontent.com/assets/16944/24533140/7a3f15fe-157a-11e7-9ef5-2635cafbffb8.png)

**Comment by ig-sinicyn** [comment]
@bradwilson 

well, current implementation does not pass output to the vs test runner. Look at TestSkipped .ctor:
```cs
        /// <summary>
        /// Initializes a new instance of the <see cref="TestSkipped"/> class.
        /// </summary>
        public TestSkipped(ITest test, string reason)
            : base(test, 0, null)
        {
            Reason = reason;
        }
```
the TestResultMessage.Output  reason is null and therefore there's nothing to print.

**Comment by ig-sinicyn** [comment]
@bradwilson thanks! : )
