### ISSUE TITLE
xUnit 2.0 on Mono

### ISSUE THREAD

**Issue by Ravadre** [xunit/xunit#91]
I tried to run a test runner (`2.0.0-beta-build2650`) with 

```
mono xunit.console.exe Stacks.Tests.dll
```

on my OpenSuse as well as on raspberry pi (because why not) - on both machines with Mono version 3.2.8 I received an error with loading framework discoverer:

```
System.TypeLoadException: Could not load type 'Xunit.Sdk.XunitTestFrameworkDiscoverer, xunit.execution, Version=2.0.0.2616, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'.
```

Is it not supported (yet?) and I am out of luck?

**Comment by chester89** [comment]
I must be late for a party, but I've been working on build scripts for Mono - and I've made some progress. I'll try to wrap this up next week. @bradwilson let me know what you think, I guess we can set up a Travis/TeamCity builds

**Comment by bradwilson** [comment]
At the moment, the AppDomain bug mentioned in https://github.com/xunit/xunit/issues/158#issuecomment-73390966 is a show-stopper for Mono support. Given the silence on the issue, I assume it won't be fixed for our 2.0 RTM.

**Comment by chester89** [comment]
​I'm aware. I'll try to prepare everything else until then.​

2015-02-22 20:47 GMT+03:00 Brad Wilson <notifications@github.com>:

> At the moment, the AppDomain bug mentioned in #158 (comment)
> <https://github.com/xunit/xunit/issues/158#issuecomment-73390966> is a
> show-stopper for Mono support. Given the silence on the issue, I assume it
> won't be fixed for our 2.0 RTM.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xunit/xunit/issues/91#issuecomment-75447425>.
>



-- 
С уважением,
Чермённов Глеб

**Comment by et1975** [comment]
Regarding the original problem, xunit.execution.dll needs to be included with the runner - unless xunit.runner.console does some custom DLL loading .NET runtime will NOT look to load its dependencies from your build output. Manually copying it there gets the tests discovery going, but that's were it stops, at least for me.
This is a bug in packaging the runner imho.

**Comment by bradwilson** [comment]
Runners do not ship execution. Unit tests are expected to have execution with them, because the versions of execution and core must match exactly.

Runner Utility looks for an loads execution from along side the unit test DLL.

**Comment by et1975** [comment]
I guess the console runner doesn't load dependencies properly, cause monodevelop sees and runs the tests - no problem (I'm guessing via visual studio runner).

**Comment by bradwilson** [comment]
The console runner works correct. The issue is the Mono bug with AppDomains: #158

**Comment by gsscoder** [comment]
I'm experimenting the same problem.
```bash
$ mono packages/xunit.runner.console.2.0.0/tools/xunit.console.exe build/test/CommandLine.Tests.dll
xUnit.net console test runner (64-bit .NET 4.0.30319.17020)
Copyright (C) 2015 Outercurve Foundation.

Discovering: CommandLine.Tests
System.TypeLoadException: Could not load type 'Xunit.Sdk.XunitTestFrameworkDiscoverer, xunit.execution.desktop, Version=2.0.0.2929, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'.
```
