### ISSUE TITLE
dotnet-xunit: Add -class+ switch to run class + nested inner classes

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#913]
Related: jcansdale/TestDriven.Net-Issues#8

**Comment by akamud** [comment]
I think this is related to #800 too.

**Comment by bradwilson** [comment]
After thinking about this, we still need the ability to say "run just this class", so it'll probably end up being a case where we add a new switch (maybe `-class+` to say "run this class, plus any nested classes").
