### ISSUE TITLE
Latest VS2015 (Update 3) breaks tests when using 'xunit 2.1.0' and 'dotnet-test-xunit 1.0.0-rc2-build10025'

### ISSUE THREAD

**Issue by bdicioccio** [xunit/xunit#916]
After updating my VS2015 Enterprise to the latest Update 3 as of (7/19/2016) I noticed that my tests were not being recognized and I was getting an error in the Tests Output window.

Updating the dependencies in my project.json resolved the issue.

**Changing from:**

```
"dependencies": {
    "xunit": "2.1.0",
    "dotnet-test-xunit": "1.0.0-rc2-build10025"
},
```

**to**

```
"dependencies": {
    "xunit": "2.2.0-beta2-build3300",
    "dotnet-test-xunit": "2.2.0-preview2-build1029"
},
```

This fixed everything for me.

I apologize if this was noted somewhere and I missed it.

**Comment by bradwilson** [comment]
The 1st set of dependencies would be appropriate for .NET Core Tooling Preview 1; the 2nd set of dependencies would be appropriate for .NET Core Tooling Preview 2.

My guess is that, upon installing Update 3, it upgraded your projects (perhaps silently) to Preview 2 of the .NET Core Tooling, but of course it wouldn't know that you'd also need to upgrade xUnit.net.

**Comment by bradwilson** [comment]
You can tell the version of tooling that you're using by checking your `global.json` file.

**Comment by bradwilson** [comment]
Closed for age.
