### ISSUE TITLE
dotnet-test-xunit not reporting traits

### ISSUE THREAD

**Issue by citizenmatt** [xunit/xunit#917]
Traits are not reported as `Test.Properties` in the test protocol API, meaning all tests show as "Uncategorised" in the Visual Studio test runner.

See [DesignTimeTestConverter.cs](https://github.com/xunit/dotnet-test-xunit/blob/master/src/dotnet-test-xunit/DesignTime/DesignTimeTestConverter.cs#L65)

**Comment by citizenmatt** [comment]
See also #889, dotnet/core#134 and dotnet/cli#3832

**Comment by bragma** [comment]
Will this ever be solved? It is spinning around and more than a year has passed. :(

**Comment by FanMix** [comment]
It's very

**Comment by bradwilson** [comment]
This runner is no longer shipping. The issue fires not exist in the new runner.
