### ISSUE TITLE
Test Case events out of sync with visualstudio.xunit.

### ISSUE THREAD

**Issue by navingh** [xunit/xunit#918]
Getting the IFrameworkHandle callbacks out of sync when called the RunTests via visualstudio.xunit.
For example we have three tests Test1, Test2 and Test3. The series of events happening are.

Test1 Record Start.
Test1 test execution
Test 2 test execution
Test 3 test execution
Test 1 Record End
Test 2 Record Start
Test 2 Record End
Test 3 Record Start
Test 3 Record End.

Where as expected events are
Test 1 Record Start.
Test 1 Execution.
Test 1 Record End.
Test 2 Record Start.
Test 2 Execution.
Test 2 Record End.
Test 3 Record Start.
Test 3 Execution.
Test 3 Record End.

Issue is getting reproduced consistently.

**Comment by bradwilson** [comment]
Closed for age.
