### ISSUE TITLE
dotnet-test-xunit runner fails

### ISSUE THREAD

**Issue by madsj** [xunit/xunit#919]
when I run my dotnet-test-xunit runner for net461 I get the following error:

```
dotnet-test-xunit.exe GG.dll
xUnit.net .NET CLI test runner (64-bit Desktop .NET win81-x64)
System.DllNotFoundException: Unable to load DLL 'Microsoft.DiaSymReader.Native.amd64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

My setup is as follows:

```json
"dependencies": {
    "xunit": "2.2.0-beta2-build3300",
    "dotnet-test-xunit": "2.2.0-preview2-build1029"
},


"net461": {
      "dependencies": {
        "Microsoft.NETCore.Platforms": "1.0.1"
      }
    }
```
The issue relates to https://github.com/xunit/xunit/issues/843 but this error is when using .net core 1.0 final version.

I have tried to compile to x86 aswell but receives an error unable to load dll Microsoft.DiaSymReader.Native.x86.dll.

The DLL Microsoft.DiaSymReader.Native.amd64.dll and Microsoft.DiaSymReader.Native.x86.dll are located in the same directory as dotnet-test-xunit.exe.

If I use xunit.console.exe everything works fine. Hope you can help

**Comment by bradwilson** [comment]
Do you get the same error when following these directions:

http://xunit.github.io/docs/getting-started-dotnet-core.html

(There is a section at the bottom related to targeting Desktop .NET)

**Comment by madsj** [comment]
Thanks for fast reply. Yes I get the same error. 
My setup works fine on a win7-x64. I am able to open the cmd and type in

dotnet-test-xunit.exe GG.dll

but my build server which is a win81-x64 I recieve the above error when opening a CMD and typing in

dotnet-test-xunit.exe GG.dll

My setup in the project.json is as follows:

"dependencies": {
    "xunit": "2.2.0-beta2-build3300",
    "dotnet-test-xunit": "2.2.0-preview2-build1029",
    "xunit.runner.visualstudio": "2.2.0-beta2-build1149",
... 

"frameworks": {
  "net461": {
      "dependencies": {
        "Microsoft.NETCore.Platforms": "1.0.1",
 ...

And I am compiling with dotnet -version 1.0.0-preview2-003121

**Comment by bradwilson** [comment]
You should not expect to be able to run `dotnet-test-xunit.exe` directly yourself. You must run it via `dotnet test`.
