### ISSUE TITLE
V2 Setup/Teardown adapting more difficult

### ISSUE THREAD

**Issue by Tofudebeast** [xunit/xunit#92]
I'm using an adapter to run legacy tests under xunit.  These old tests run by using the RunWithAttribute and overriding FactCommand.  Override Execute, Setup/base.Execute()/Teardown was pretty simple to implement.

In the new framework deriving from XunitTestCase is more complicated.  The class isn't instantiated until RunTestWithArgumentsAsync, which pretty much leaves reimplementing the entire method as the only option.

Having BeforeAfterAttributes support getting the class instance would solve this.  (And likely open other scenarios.)

**Comment by bradwilson** [comment]
Moved here: https://github.com/xunit/xunit.github.io/issues/7

**Comment by jonorossi** [comment]
Sorry for posting on an old issue, but that link is now a 404 (looks like issues were turned off on that repo). Was any documentation written on this, I wasn't able to find any?

**Comment by bradwilson** [comment]
Sorry, I've updated the link.
