### ISSUE TITLE
Update xunit.abstractions to Dotnet Core 1.0 RTM.

### ISSUE THREAD

**Issue by jp7677** [xunit/xunit#920]
Hi there,

I'm using the following packages in my Dotnet Core 1.0 RTM  tests project 
```
"xunit": "2.2.0-beta2-build3300",
"dotnet-test-xunit": "2.2.0-preview2-build1029",
```
It works perfectly, but unfortunately nuget still pulls some rc2 packages. The reason is imho that xunit.abstraction still refers to rc2 (https://github.com/xunit/xunit/blob/master/src/abstractions/xunit.abstractions/project.json). Could you please update these to RTM packages? Would be nice to get rid of all pre-RTM stuff ;)

**Comment by bradwilson** [comment]
Change pushed here: 2671cc4

**Comment by jp7677** [comment]
Thanks a lot!
