### ISSUE TITLE
Test explorer does not discover tests in VS2015 Update 3 with vs14-kb3165756

### ISSUE THREAD

**Issue by hardhub** [xunit/xunit#922]
I am using latest available versions of xUnit but Test Explorer does not show any tests.

"testRunner": "xunit",

in dependencies:
"xunit": "2.2.0-beta2-build3300",
"xunit.runner.visualstudio": "2.2.0-beta2-build1149",

**Comment by gokussx4** [comment]
I just had the same problem and didn't think to go to the output of tests. When I went there I had an embed interop type reference setting mismatch which allowed the test project to build ok but the unit tests would not load up. 

Hope this helps.

**Comment by bradwilson** [comment]
Please follow the directions at http://xunit.github.io/docs/getting-started-dotnet-core.html

**Comment by maxim-boligatov** [comment]
I already read it many times... "dotnet test" works fine. But tests in Test Explorer are not displayed.

Can you confirm that in your case VS 20215 Update 3 (+vs14-kb3165756) shows tests for xUnit?

**Comment by bradwilson** [comment]
Yes, I've used it many times, and it does work. The fact that you're referencing `xunit.runner.visualstudio` is what suggests to me that you've not followed the directions to the letter (because nowhere in those directions does it ever suggest that you should add that package; that package is used by desktop and device projects, not .NET Core).

**Comment by maxim-boligatov** [comment]
I have found the reason. It does not work when I add custom output name for test project.
So bug is still there...

"buildOptions": {
       "outputName": "Some.My.Custom.Name"
},

**Comment by bradwilson** [comment]
Since we do not control that, it sounds like a bug with the Visual Studio tooling that supports .NET Core unit tests. You should report this bug to the Visual Studio team.

Thanks...

**Comment by maxim-boligatov** [comment]
In this case most likely it is depending on another bug reported by me: https://github.com/aspnet/Home/issues/1680

Maybe new update of VS will fix that.
Not sure that current thread should be closed or not...

**Comment by rubencc** [comment]
I have the same issue only with W8.1. I have other PC with W10 and after update with vs14-kb3165756 test explorer continue showing all solution test.

**Comment by navingh** [comment]
Is the VS installation non - ENU VS. If yes.
It's a known issue from the new update. As it's having a missing resource DLL. Please follow the steps in this below Microsoft connect link to unblock yourself.

https://connect.microsoft.com/VisualStudio/Feedback/Details/2979953

**Comment by Magnificus36** [comment]
I have installed the new version of KB3165756 my VS 2015 is now version 14.0.25425.01. But still Test Explorer does not show my xUnit tests.
Using the msbuild runner does still work.

It did work at first and if my memory is correct I already had the first/broken version of KB3165756 installed when I started using xUnit. And I have just added a new 'normal' UnitTest project to my solution and the test from that project does show up in Test Explorer.

**Comment by 22u2** [comment]
I also had to delete %TEMP%\VisualStudioTestExplorerExtensions to see the tests in Test Explorer. Does removing the file is a normal use case?

**Comment by bhider** [comment]
This may or may not be your case.

I had the same problem but in my case I had reverted to using ver 1.x.x of xUnit. While I uninstalled the v2.x.x packages  (using the Visual Studio Package manager) it did not clean up all references to it and did not remove the packages from the various folders it stores it in (within the project/solution folder hierarchy). Cleaned out all of that and ensured that only .nupkgs for the version I was using was present in the project folder hierarchy and in packages.config file(s). Had to remove rogue references from .csproj file too. In the end, got it working!

**Comment by hardhub** [comment]
xproj projects are not supported by xunit anymore: https://github.com/xunit/xunit/issues/1175

I will close this issue since it is not actual due to lack of VS2015 support (project.json).

**Comment by ashokprecise** [comment]
Hi,
I am using VisulaStudio2015 Update3 in my .netcore project i have followed all instructions that you provide [here]([http://xunit.github.io/docs/getting-started-dotnet-core.html](url)). but no luck i cant able to discovered the test result is 0. i don't know what i miss there.

**Comment by bradwilson** [comment]
VS 2015 and .NET Core is not supported. .NET Core is only supported in VS 2017.

Please see the Test Runner Compatibility table: https://xunit.github.io/#runners

<img src="https://cloud.githubusercontent.com/assets/16944/25633450/f47a9030-2f2b-11e7-8471-ddad7a1f10a8.png" width="682" />

**Comment by pgorbas** [comment]
I am having this issue as well.

BTW the article at [Please follow the directions at http://xunit.github.io/docs/getting-started-dotnet-core.html](url) is lacking.  There is no place to ask question or discussion there.  It also does not cover the common scenario of adding an xUnit test to an existing .net core project.  Just creating a class file and copying over the contents of the "Write your first tests" section does not work, as TestRunner in VS2015 does not discover the xUnit test.

**Comment by bradwilson** [comment]
.NET Core is only supported in VS2017. Please consult https://xunit.github.io/#runners
