### ISSUE TITLE
Cannot resolve dependencies (.NET Core)

### ISSUE THREAD

**Issue by Knaackee** [xunit/xunit#925]
Ive followed the simple steps from: https://xunit.github.io/docs/getting-started-dotnet-core.html.

So i have a empty .NET Core Class library with the following project.json.

```
{
    "version": "1.0.0-*",
    "testRunner": "xunit",
  "dependencies": {
    "xunit": "2.2.0-beta2-build3300",
    "dotnet-test-xunit": "2.2.0-preview2-build1029"
  },
    "frameworks": {
        "netcoreapp1.0": {
            "dependencies": {
                "Microsoft.NETCore.App": {
                    "type": "platform",
                    "version": "1.0.0"
                }
            }
        }
    }
}
```

but getting 

```

dotnet restore
log  : Restoring packages for Y:\Development\ClassLibrary1\project.json...
error: Unable to resolve 'xunit.core (= 2.2.0-beta2-build3300)' for '.NETCoreApp,Version=v1.0'.
error: Unable to resolve 'xunit.assert (= 2.2.0-beta2-build3300)' for '.NETCoreApp,Version=v1.0'.
error: Unable to resolve 'xunit.runner.reporters (>= 2.2.0-beta2-build3300)' for '.NETCoreApp,Version=v1.0'.
error: Unable to resolve 'Microsoft.DiaSymReader (>= 1.0.8)' for '.NETCoreApp,Version=v1.0'.
error: Unable to resolve 'Microsoft.DiaSymReader.Native (>= 1.4.0-rc2)' for '.NETCoreApp,Version=v1.0'.
log  : Lock file has not changed. Skipping lock file write. Path: Y:\Development\Blazingo\project.lock.json
log  : Y:\Development\ClassLibrary1\project.json
log  : Restore failed in 2056ms.

Errors in Y:\Development\ClassLibrary1\project.json
    Unable to resolve 'xunit.core (= 2.2.0-beta2-build3300)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'xunit.assert (= 2.2.0-beta2-build3300)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'xunit.runner.reporters (>= 2.2.0-beta2-build3300)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'Microsoft.DiaSymReader (>= 1.0.8)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'Microsoft.DiaSymReader.Native (>= 1.4.0-rc2)' for '.NETCoreApp,Version=v1.0'.

```

**Comment by nickfeng1982** [comment]
I had the same issue but only on the server build machine. I had a clean build in my own PC though.  I don't whether I should do sth special like manually download the xunit packpage in the server. Please advise. Here is the error message:

`Gms.Six.Database.Batch.Test\project.json (6, 51)
**The dependency dotnet-test-xunit >= 2.2.0-preview2-build1029 could not be resolved.**
Gms.Six.Database.Batch.Test\project.json (6, 51)
**The dependency Microsoft.DiaSymReader >= 1.0.8 could not be resolved.**
Gms.Six.Database.Batch.Test\project.json (6, 51)
**The dependency Microsoft.DiaSymReader.Native >= 1.4.0-rc2 could not be resolved.**
Gms.Six.Database.Batch.Test\project.json (6, 51)
**The dependency Microsoft.Extensions.Testing.Abstractions >= 1.0.0-preview2-003121 could not be resolved.**
Gms.Six.Database.Batch.Test\project.json (5, 36)
The dependency xunit >= 2.2.0-beta2-build3300 could not be resolved.
Gms.Six.Database.Batch.Test\project.json (5, 36)
The dependency xunit.abstractions >= 2.0.1-rc2 could not be resolved.
Gms.Six.Database.Batch.Test\project.json (6, 51)
The dependency xunit.abstractions >= 2.0.1-rc2 could not be resolved.
Gms.Six.Database.Batch.Test\project.json (5, 36)
The dependency xunit.assert 2.2.0-beta2-build3300 could not be resolved.
Gms.Six.Database.Batch.Test\project.json (5, 36)
The dependency xunit.core 2.2.0-beta2-build3300 could not be resolved.
Gms.Six.Database.Batch.Test\project.json (5, 36)
The dependency xunit.extensibility.core 2.2.0-beta2-build3300 could not be resolved.`

**Comment by nickfeng1982** [comment]
I had the same issue but only on the build machine. I had a clean solution build in my own PC. I don't whether I should do sth special like manually download the xunit packpage in the server. Please advise. Here is the error message:

`Gms.Six.Database.Batch.Test\project.json (6, 51)
The dependency dotnet-test-xunit >= 2.2.0-preview2-build1029 could not be resolved.
Gms.Six.Database.Batch.Test\project.json (6, 51)
The dependency Microsoft.DiaSymReader >= 1.0.8 could not be resolved.
Gms.Six.Database.Batch.Test\project.json (6, 51)
The dependency Microsoft.DiaSymReader.Native >= 1.4.0-rc2 could not be resolved.
Gms.Six.Database.Batch.Test\project.json (6, 51)
The dependency Microsoft.Extensions.Testing.Abstractions >= 1.0.0-preview2-003121 could not be resolved.
Gms.Six.Database.Batch.Test\project.json (5, 36)
The dependency xunit >= 2.2.0-beta2-build3300 could not be resolved.
Gms.Six.Database.Batch.Test\project.json (5, 36)
The dependency xunit.abstractions >= 2.0.1-rc2 could not be resolved.
Gms.Six.Database.Batch.Test\project.json (6, 51)
The dependency xunit.abstractions >= 2.0.1-rc2 could not be resolved.
Gms.Six.Database.Batch.Test\project.json (5, 36)
The dependency xunit.assert 2.2.0-beta2-build3300 could not be resolved.
Gms.Six.Database.Batch.Test\project.json (5, 36)
The dependency xunit.core 2.2.0-beta2-build3300 could not be resolved.
Gms.Six.Database.Batch.Test\project.json (5, 36)
The dependency xunit.extensibility.core 2.2.0-beta2-build3300 could not be resolved.`

**Comment by bradwilson** [comment]
Are you sure you're using the preview 2 tooling? Verify by typing `dotnet --version` from the command prompt.

**Comment by nickfeng1982** [comment]
thx for the quick reply. Here is what I got:


Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

H:\>dotnet --version
1.0.0-preview2-003121

H:\>




________________________________
发件人: Brad Wilson <notifications@github.com>
发送时间: 2016年7月30日 0:30
收件人: xunit/xunit
抄送: nick feng; Comment
主题: Re: [xunit/xunit] Cannot resolve dependencies (.NET Core) (#925)


Are you sure you're using the preview 2 tooling? Verify by typing dotnet --version from the command prompt.

―

**Comment by bradwilson** [comment]
I don't know what to suggest, then, other than networking issues, because you can clearly see all the xUnit packages listed there are on NuGet.

Example: http://www.nuget.org/packages/xunit/2.2.0-beta2-build3300

**Comment by onovotny** [comment]
you could try clearing the nuget package caches in case there's stale things. `nuget locals all clear`

**Comment by jcansdale** [comment]
> So i have a empty .NET Core Class library with the following project.json.

What happens if you change it to be a .NET Core Console Application?

**Comment by Hartdrooz** [comment]
I have the same issue, create a new dll project copy paste the example from XUnit website doesn't work.  Someone found a fix for this ?

**Comment by Hartdrooz** [comment]
I found what was the problem for this issues so I will post here maybe this can help some people.  It seems I was not using the good URL for the nuget package.  I used a VM in Azure with VS2015 Update 3 and the nuget package URL is : https://api.nuget.org/v3/index.json.  For X reason on my machine I was not targetting this but the old adress : https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/.

**Comment by naster01** [comment]
Is that closed?

**Comment by zabulus** [comment]
Fixed this by typing `dotnet restore` in working folder

**Comment by fletchsod-developer** [comment]
Thanks for the sample project.json.  That one works on my workstation.

**Comment by davidknaack** [comment]
I was experiencing this as well and found that my VS had the curated-feeds nuget url. Adding the api.nuget.org repo fixed the problem. Thanks for that!

Also, I was briefly very confused after searching for this issue, finding a match, and then noticing the name of the reporter.

**Comment by bradwilson** [comment]
Closed for age.
