### ISSUE TITLE
[VS Test Console]  It always requires absolute path of test dll.

### ISSUE THREAD

**Issue by deepanshu3131** [xunit/xunit#927]
I am using vstest.console for running xunit tests using xUnit adapter Version: 2.2.0-beta2-build3300.

When I try to run tests by giving relative path of test dll, tests are not executed. Below is the log:

Command:
C:\Users\username\Documents\Visual Studio 15\Projects\UnitTestProject2\UnitTestProject2\bin\Debug>vstest.console UnitTestProject2.dll /testadapterpath:.

Output:

Starting test execution, please wait...
Warning: [xUnit.net 00:00:00.0380136] Exception discovering tests from UnitTestProject2: System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.IsXunitTestAssembly(String assemblyFileName)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.DiscoverTests[ TVisitor\] (IEnumerable`1 sources, LoggerHelper logger, Func`4 visitorFactory, Action`4 visitComplete)

Warning: No test is available in UnitTestProject2.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.

Information: Additionally, you can try specifying '/UseVsixExtensions' command if the test discoverer & executor is installed on the machine as vsix extensions and your installation supports vsix extensions. Example: vstest.console.exe myTests.dll /UseVsixExtensions:true

If I pass absolute path of the test dll, everything work as expected.

Command:
C:\Users\username\Documents\Visual Studio 15\Projects\UnitTestProject2\UnitTestProject2\bin\Debug>vstest.console "C:\Users\username\Documents\Visual Studio 15\Projects\UnitTestProject2\UnitTestProject2\bin\Debug\UnitTestProject2.dll" /testadapterpath:.

Output:

Starting test execution, please wait...
Information: [xUnit.net 00:00:00.5512336]   Discovering: UnitTestProject2

Information: [xUnit.net 00:00:00.7513468]   Discovered:  UnitTestProject2

Information: [xUnit.net 00:00:01.2467793]   Starting:    UnitTestProject2

Information: [xUnit.net 00:00:01.5079017]   Finished:    UnitTestProject2

Passed   UnitTestProject2.UnitTest1.TestMethod12

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.7080 Seconds

Bug :
In void DiscoverTests<TVisitor>(IEnumerable<string> sources, LoggerHelper logger, Func<string, ITestFrameworkDiscoverer, ITestFrameworkDiscoveryOptions, TVisitor> visitorFactory,Action<string, ITestFrameworkDiscoverer,ITestFrameworkDiscoveryOptions, TVisitor> visitComplete = null) in  [VsTestRunner](https://github.com/xunit/visualstudio.xunit/blob/3947ccfd83f64dec6640f0f1a920e50a003bdf84/xunit.runner.visualstudio.testadapter/VsTestRunner.cs)
When we are taking AssemblyFileName from Sources then the AssemblyFileName can be relative which makes a difficulty to find the Directory Name later on.

Proposed fix: 
I can get the absolute AssemblyFileName then pass it. I am ready with the PR.

**Comment by bradwilson** [comment]
Thanks for the bug report. Yes, please send the PR. 🙂

**Comment by bradwilson** [comment]
Fixed with xunit/visualstudio.xunit#80.
