### ISSUE TITLE
New build for .NET Core 1.0 RTM support?

### ISSUE THREAD

**Issue by amattie** [xunit/xunit#931]
Now that support for .NET Core 1.0 RTM has been added in 2671cc4378301e0fa0ac51e530f19530af565016, can we get a new NuGet version?

There's something weird going on with the preview2 tooling (which still exists in preview3-003223) that appears to prevent pre-RTM dependencies in assembly A from playing nice with RTM dependencies in assembly B when referenced from project C. The errors look like this, in case you're curious:

```
Unable to satisfy conflicting requests for 'System.Reflection' 
...
... System.Reflection (>= 4.1.0-rc2-24027) (via package/xunit.abstractions 2.0.1-rc2)
... System.Reflection (>= 4.1.0) (via package/NETStandard.Library 1.6.0)
...
```

I can't figure out which ticket this belongs under in the tooling, but from the xunit side, I'd expect a build in NuGet that depends on the RTM bits to fix this.

**Comment by bradwilson** [comment]
This does not happen with the stock Preview 2 tooling (many users are using this today with success). My guess is that this is something new that's introduced with one of the pre-Preview 3 builds you are using. We do intend to fix this for our Preview 3-compatible release, but we have no plans to do any other releases in the interim.

**Comment by amattie** [comment]
I wrongly blamed this issue on xunit because it was the only outlier using the RC2 dependencies. Turns out though that the problem was related to the actual letter casing of a different package and the conflicts that would result when different casings were used across different assemblies when referencing the same package. xref NuGet/Home#2901.
