### ISSUE TITLE
Android test project fails to build due to missing res directory

### ISSUE THREAD

**Issue by sandersaares** [xunit/xunit#932]
I want to run tests in a Xamarin Android app and am following the guide at http://gregshackles.com/testing-xamarin-apps-getting-started-with-xunit/

Here is what I got so far:
1. I create a new Android Blank App project using VS 2015 Update 3 (with latest Xamarin plugin version).
2. I add the xunit package.
3. I add the xunit.runners.devices package.
4. I replace MainActivity.cs with MainActivity.cs.txt that was generated.

Expected result: test app now build fine and executes (though no tests yet created, so it cannot do much).

Actual result: `Error       resource directory 'C:\Source\xxx\Tests.Android.v2\obj\Debug\resourcecache\CA7883210B061794256419535F923160\res' does not exist Tests.Android.v2    C:\Source\xxx\Tests.Android.v2\AAPT`

Manually creating the named directory solves the issue temporarily but the directory is deleted on every clean and rebuild.

The issue only occurs after adding the xunit.runners.devices package - before that step, the project builds just fine.

**Comment by bradwilson** [comment]
Closed for age.
