### ISSUE TITLE
xunit console runner return code breaks TeamCity

### ISSUE THREAD

**Issue by StrangeWill** [xunit/xunit#933]
TeamCity reporting expects test runners to return "0" on exit as long as the test runner successfully runs, this allows TeamCity to determine if the application has passed/failed due to it's configuration of test results (taking muted tests into account), but still fail if the test runner completely bombs.

I would recommend only returning error codes for failed tests if the TeamCity integration is not running.

Maybe an optional flag instead too.

I'd be glad to make a PR on whatever you think is best.

**Comment by bradwilson** [comment]
The problem with that is most build engines (for example, MSBuild) use the exit code to indicate failure which should stop the build. Sorry, but based on common usage, TeamCity is what's broken here, not us.

**Comment by StrangeWill** [comment]
Yeah I guess you're right -- it's why a lot of test runners in TeamCity have special wrappers, so that they can toss out the positive return error codes and not trip up dotCover when dotCover thinks your test runner is crashing.

I'll ponder what can be done outside of a massive extension of the https://github.com/carlpett/xUnit-TeamCity project.
