### ISSUE TITLE
Passing null MemberData value as Generic parameter doesn't keep original type

### ISSUE THREAD

**Issue by ayb4btu** [xunit/xunit#935]
I'm not sure if this is by design or not, but when I call the following Theory test I was expecting `T` to be a `byte[]` but its type is a `System.Object`.

```C#
[Theory]
[MemberData(nameof(ParseNulledTypeScenarios))]
public void ParseGenericTypeToStringTest<T>(T value, string expected, string message)
{
	Type byteArrayType = typeof(T); // this should be a byte[] Type, but is the base object type
}

public static IEnumerable<object[]> ParseNulledTypeScenarios()
{
	byte[] nullByteArray = null;
	yield return new object[] { nullByteArray, null, "" };
}
```

If I do (essentially) the same thing with a normal method instead of passing the parameters in by a `MemberData`, I get the original type:

```C#
[Fact]
public void TypeTest()
{
	byte[] value = null;
	Type extractedType = GetType(value);

	extractedType.Should().Be(typeof(byte[]));
}

public Type GetType<T>(T value)
{
	return typeof(T);
}
```

Is it possible to get the original type (`byte[]` in this instance) of the passed in generic value using `MemberData`? Or am I stuck with the type being a `System.Object`?

**Update**
Having now read this past issue: [https://github.com/xunit/xunit/issues/296]() it looks like the null's original type is forgotten, so it is instead stored as an object type. So I guess I'll need to change the way I test variables that are of a particular type, but whose value is null.

**Comment by bradwilson** [comment]
`null` values don't have strong types associated with them _**in the CLR**_, so when it's the only expression of a generic, we are forced to fall back to `object`. Note that when the compiler has access to your source, it can make better type inferences at compile time than we can do at runtime.

**Comment by ayb4btu** [comment]
Thanks for the additional info. The code being tested ended up being modified to better handle null situations, making it sufficient to test with a `System.Object` set to null.
