### ISSUE TITLE
Failed to download 'xunit' in .NET Core App with 'dotnet run '

### ISSUE THREAD

**Issue by wddpct** [xunit/xunit#937]
Here is  the detail (Visual Studio 2015 )
log  : Retrying 'FindPackagesByIdAsync' for source 'https://myget-2e16.kxcdn.com/artifacts/xunit/nuget/v3/flatcontainer/xunit/index.json'.
log  : The HTTP request to 'GET https://myget-2e16.kxcdn.com/artifacts/xunit/nuget/v3/flatcontainer/xunit/index.json' has timed out after 100000ms.
log  : Retrying 'FindPackagesByIdAsync' for source 'https://myget-2e16.kxcdn.com/artifacts/xunit/nuget/v3/flatcontainer/system.security.cryptography.hashing.algorithms.analyzers/index.json'.
log  : The HTTP request to 'GET https://myget-2e16.kxcdn.com/artifacts/xunit/nuget/v3/flatcontainer/system.security.cryptography.hashing.algorithms.analyzers/index.json' has timed out after 100000ms.
log  : Retrying 'FindPackagesByIdAsync' for source 'https://myget-2e16.kxcdn.com/artifacts/xunit/nuget/v3/flatcontainer/dotnet-test-xunit/index.json'.
log  : The HTTP request to 'GET https://myget-2e16.kxcdn.com/artifacts/xunit/nuget/v3/flatcontainer/dotnet-test-xunit/index.json' has timed out after 100000ms.
log  : Retrying 'FindPackagesByIdAsync' for source 'https://myget-2e16.kxcdn.com/artifacts/xunit/nuget/v3/flatcontainer/desktop.analyzers/index.json'.
log  : The HTTP request to 'GET https://myget-2e16.kxcdn.com/artifacts/xunit/nuget/v3/flatcontainer/desktop.analyzers/index.json' has timed out after 100000ms.

**Comment by bradwilson** [comment]
Closed for age.
