### ISSUE TITLE
[VisualStudio.xUnit] Add support for .NET Core

### ISSUE THREAD

**Issue by harshjain2** [xunit/xunit#938]
Add support for .NET Core so that xUnit tests targeting .NET Core platform can be executed through vstest.console.

**Comment by harshjain2** [comment]
Submitted a PR for this isssue.
PR link : [https://github.com/xunit/visualstudio.xunit/pull/83](url)

**Comment by naster01** [comment]
Where is your PR?

**Comment by bradwilson** [comment]
The PR is here:
https://github.com/xunit/visualstudio.xunit/pull/83

It has been merged here, waiting for additional work to be done:
https://github.com/xunit/visualstudio.xunit/tree/dotnetcore
