### ISSUE TITLE
xunit.runner.console.2.2.0-beta2-build3300 throws error when using custom parameter

### ISSUE THREAD

**Issue by malcolmarobertson** [xunit/xunit#940]
I am using a custom parameter for my test solution but the latest version throws an error instead of ignoring the unknown paramater:

.\packages\xunit.runner.console.2.2.0-beta2-build3300\tools>xunit.console Test.Specs.dll -TargEnv TestConfig.js
on
error: unknown option: -TargEnv

**Comment by bradwilson** [comment]
We have never supported custom parameters.

**Comment by malcolmarobertson** [comment]
Would it not be simple enough without any impact to include them?

**Comment by bradwilson** [comment]
Closed for age.
