### ISSUE TITLE
[VisualStudio.xUnit] Disable appdomain creation when specified in runsettings

### ISSUE THREAD

**Issue by harshjain2** [xunit/xunit#944]
Latest RunSettings has a newly added tag "DisableAppDomain" under "RunConfiguration". VisualStudio.xUnit should honor the value of this tag and shouldn't create new app domain for discovery and execution whenever this tag's value is "true".

**Comment by harshjain2** [comment]
PR Link : https://github.com/xunit/visualstudio.xunit/pull/84

**Comment by bradwilson** [comment]
Merged with xunit/visualstudio.xunit@c507efd.
