### ISSUE TITLE
[bug] Generic nullable type inference does not work correctly

### ISSUE THREAD

**Issue by jamesqo** [xunit/xunit#946]
## Repro

```cs
public class Class1
{
    [Theory]
    [MemberData(nameof(FooData))]
    public void Foo(int? nullable)
    {
    }

    [Theory]
    [MemberData(nameof(FooData))]
    public void GenericFoo<T>(T? nullable) where T : struct
    {
        Console.WriteLine(typeof(T));
    }

    public static IEnumerable<object[]> FooData()
    {
        yield return new object[] { new int?(3) };
    }
}
```

## Expected

`System.Int32` is printed to the console.

## Actual

xUnit recognizes `T` as `System.Object`, and since it does not match the constraint of `T :  struct` an exception is thrown.

```
System.ArgumentException : GenericArguments[0], 'System.Object', on 'Void GenericFoo[T](System.Nullable`1[T])' violates the constraint of type 'T'.
 ---- System.Security.VerificationException : Method BugLib2.Class1.GenericFoo: type argument 'System.Object' violates the constraint of type parameter 'T'.
 Stack Trace:
      at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
      at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
   ----- Inner Stack Trace -----
      at System.RuntimeMethodHandle.GetStubIfNeeded(RuntimeMethodHandleInternal method, RuntimeType declaringType, RuntimeType[] methodInstantiation)
      at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
```

I believe this is due to the special way Nullable is handled when it is boxed/unboxed; when you box a `Nullable<T>` it actually becomes a boxed `T`, or null if it was null. For example:

```cs
int? nullable = 3;
object boxed = nullable;
Console.WriteLine(boxed is int); // True
object boxedNull = default(int?);
Console.WriteLine(boxedNull == null); // True
```

The changed type of the boxed item is probably causing some issues with the type inference algorithms for generic theories.

**Comment by bradwilson** [comment]
Right. `Nullable<T>` is a Heisenberg-Type when passed via `object` (it can never be discerned at runtime with reflection).

I actually blogged about this around 8 years ago: http://bradwilson.typepad.com/blog/2008/07/creating-nullab.html

Given what I learned 8 years ago, it's possible that this bug is unfixable.

**Comment by jamesqo** [comment]
@bradwilson Not necessarily. Of course I mean it would be impossible in scenarios like this:

```cs
[Theory]
[MemberData(nameof(FooData))]
public void Foo<T>(T value)
{
}

public static IEnumerable<object[]> FooData()
{
    yield return new object[] { new int?(3) };
}
```

since the boxed value would just be an `int`, and we could never infer T as a nullable. However, if the theory explicitly accepts a `Nullable<T>` then we could attempt to detect if the data being passed is nonnull and if so try to coerce it into a nullable.

An example to show that it's possible:

```cs
public static void MiniTestDriver()
{
    var parameter = FooData().First();
    if (parameter != null)
    {
        typeof(Program).GetMethod("Foo")
            .MakeGenericMethod(parameter.GetType())
            .Invoke(null, new object[] { parameter });
    }
}

public static void Foo<T>(T? nullable) where T : struct
{
    Console.WriteLine(typeof(T));
}

public static IEnumerable<object[]> FooData()
{
    yield return new object[] { new int?(3) };
}
```

Regarding your blog post: I believe you're trying to say that it's impossible to create a boxed nullable with which we can invoke `Foo` with. However, I don't think that's an issue since `MethodInfo.Invoke` will automatically do the conversion for us.

**Comment by jamesqo** [comment]
@bradwilson I just discovered that the type inference will not work if the input parameters are not all Ts:

```cs
[Theory]
[InlineData(new int[] { 1, 2, 3 })]
public void Foo<T>(T[] array)
{
}
```

results in

```
System.ArgumentException : Object of type 'System.Int32[]' cannot be converted to type 'System.Object[]'.
```

Is there a workaround for this?

**Comment by bradwilson** [comment]
I'm 99% sure that the type inference, as implemented today, only works for the parameter type being a naked `T` (not `Nullable<T>`, not `T[]`, etc.).

**Comment by jamesqo** [comment]
@bradwilson There seems to be a PR [here](https://github.com/xunit/xunit/pull/965) which achieves just this; it would be nice if you could take a look.

**Comment by hughbe** [comment]
@bradwilson indeed, I have submitted the PR James linked. Please take a look, it's quite powerful!

**Comment by hughbe** [comment]
@bradwilson this can be closed now as it's benn fixed :)

**Comment by jamesqo** [comment]
Awesome! @hughbe thanks for implementing this.
