### ISSUE TITLE
Request: Supporting ValueTuple in MemberData

### ISSUE THREAD

**Issue by jamesqo** [xunit/xunit#951]
It would be nice if [`ValueTuple`](https://github.com/dotnet/corefx/blob/master/src/System.ValueTuple/src/System/ValueTuple/ValueTuple.cs) was supported in `MemberData`, since it provides type-safety and ensures that different parameters have matching types. For example, if you attempt to write this you'll get an error:

```cs
[Theory]
[MemberData(nameof(TrueWhenXoredData))]
public void TrueWhenXored(bool left, bool right)
{
    Assert.True(left ^ right);
}

public static IEnumerable<ValueTuple<bool, bool>> TrueWhenXoredData()
{
    yield return ValueTuple.Create(true, true);
    yield return ValueTuple.Create(3, false); // error: this creates a ValueTuple<int, bool>
}
```

On the other hand, this only happens at runtime if you use `IEnumerable<object[]>`.

Another advantage of `ValueTuple` is that it's going to be [directly supported by C# 7](https://github.com/dotnet/roslyn/blob/master/docs/features/tuples.md), so later on when that's released users will simply be able to write

```cs
public static IEnumerable<(bool, bool)> TrueWhenXoredData()
{
    yield return (true, true);
    yield return (false, false);
}
```

It may also solve issues like #946 since there will no longer be any boxing of the parameters.

**Comment by bradwilson** [comment]
There are several problems with this proposal.

1. `ValueTuple` does not ship with .NET 4.5, which is our minimum supported version.
2. This contract has been fixed for several years. To change it arbitrarily would be breaking backward compatibility.
3. It's not possible to actually express the contract you want. To what would you change the signature, given that it has suddenly become arbitrary? (Related: this won't fix the boxing issue, as should be obvious when attempting to actually define the contract.)
4. We already offer a type-safe way to return data: [`TheoryData`](https://github.com/xunit/xunit/blob/master/src/xunit.core/TheoryData.cs):

```csharp
public static TheoryData<bool, bool> TrueWhenXoredData()
{
    return new TheoryData<bool, bool> {
        { true, true },
        { false, false }
    };
}
```

**Comment by jamesqo** [comment]
> We already offer a type-safe way to return data: TheoryData:

Very cool! I was not aware of that, and I suppose it makes this proposal mostly redundant (although it's necessary to repeat the type-names once). Thanks for pointing that out.

**Comment by nietras** [comment]
Just a not so others might see how this could be done. It is unfortunately a little verbose on the repetition of the value tuple definition.
```csharp
    public static TheoryData<(int[] Coins, int Amount, int ExpectedCount)> TheoryData =>
        new TheoryData<(int[] Coins, int Amount, int ExpectedCount)> {
        (new int[]{ 2 }, 1, -1),
        (new int[]{ 2 }, 2,  1),
        (new int[]{ 2 }, 3, -1),
        (new int[]{ 2 }, 4,  2),
        (new int[]{ 1, 2, 5 },   0,  0),
        (new int[]{ 1, 2, 5 },   7,  2),
        (new int[]{ 1, 2, 5 },  11,  3),
        (new int[]{ 1, 2, 5 }, 111, 23),
        (new int[]{ 1, 2, 5 }, 112, 23),
    };

    [Theory]
    [MemberData(nameof(TheoryData))]
    public void BruteForce((int[] Coins, int Amount, int ExpectedCount) t)
    {
        var actualCount = CoinChange.CountBruteForce(t.Coins, t.Amount);

        Assert.Equal(t.ExpectedCount, actualCount);
    }
```
