### ISSUE TITLE
xunit.runner.visualstudio does not launch "theory" tests

### ISSUE THREAD

**Issue by byme8** [xunit/xunit#952]
Hi, today I have installed the Visual studio '15' Preview 4 and found that runner launches only "fact" tests and ignores the "theory" tests(see screenshots below). 

![xunitfail](https://cloud.githubusercontent.com/assets/5927686/18035651/a073692e-6d0e-11e6-9d03-9478206e9a95.png)

![project](https://cloud.githubusercontent.com/assets/5927686/18035729/2da3e6d8-6d10-11e6-8c7d-b13bd06af309.png)

> Microsoft Visual Studio Enterprise 15 Preview 4
> Version 15.0.25618.0 PREVIEW
> Microsoft .NET Framework
> Version 4.6.01586
> Installed Version: Enterprise
> 
> Visual C# 15 Preview 4   00369-50000-00000-AA216
> Microsoft Visual C# 15 Preview 4
> 
> Application Insights Tools for Visual Studio Package   8.1.00712.1
> Application Insights Tools for Visual Studio
> 
> ASP.NET and Web Tools 2016   15.0.20802.0
> ASP.NET and Web Tools 2016
> 
> Common Azure Tools   1.8
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> NuGet Package Manager   3.5.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
> 
> Visual Studio Tools for Universal Windows Apps   15.0.25618.00

**Comment by bradwilson** [comment]
Is there anything in the Output window, Tests tab?

Can you also try [enabling diagnostics](http://xunit.github.io/docs/configuring-with-json.html) and re-build/re-run?

**Comment by byme8** [comment]
After enabling diagnostics output for VS '15' prints without any changes. When I do the same for older version of VS(not preview) it works as expected. Rebuild and re-launch do not help.
Output form VS '15':
>------ Run test started ------
Updating the layout...
Copying files: Total <1 mb to layout...
Checking whether required frameworks are installed...
Registering the application to run from layout...
Deployment complete (0:00:00.967). Full package name: "e1f5d00c-9de0-4267-a5e8-d8c16bcf690a_1.0.0.0_x86__qhbce5wejh4jg"
[xUnit.net 00:00:00.0933563]   Discovering: xUnitFail.Example
[xUnit.net 00:00:00.2504759]   Discovered:  xUnitFail.Example
[xUnit.net 00:00:00.2838698]   Starting:    xUnitFail.Example
[xUnit.net 00:00:00.4302429]   Finished:    xUnitFail.Example
Test adapter sent back a result for an unknown test case. Ignoring result for 'xUnitFail.Example.UnitTest.DoesNotWork(first: 2, second: 1, result: 1)'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'xUnitFail.Example.UnitTest.DoesNotWork(first: 3, second: 1, result: 2)'.
========== Run test finished: 1 run (0:00:03.975) ==========

**Comment by Vaccano** [comment]
I can confirm that this also happens in Visual Studio 2015 Update 3.

Fact tests run fine, but Theory tests are ignored.

Here is the versions I have installed:

  <package id="xunit" version="2.1.0" targetFramework="net461" />
  <package id="xunit.abstractions" version="2.0.0" targetFramework="net461" />
  <package id="xunit.assert" version="2.1.0" targetFramework="net461" />
  <package id="xunit.core" version="2.1.0" targetFramework="net461" />
  <package id="xunit.extensibility.core" version="2.1.0" targetFramework="net461" />
  <package id="xunit.extensibility.execution" version="2.1.0" targetFramework="net461" />
  <package id="xunit.runner.visualstudio" version="2.1.0" targetFramework="net461" />

**Comment by byme8** [comment]
@Vaccano, I have VS 2015 Community Update 3 and all kinds of tests work fine.

**Comment by jbayardo** [comment]
Hi. We are having similar problems and think they may be related. In our case, Theories are both displayed and run fine, the problem arises when we add our own data source (InlineDataWithRandomSeed, sets last function parameter to a "seed"). Tests that are using it (see, for example, the second one in StorageCompactionTests) are discovered by the Test Explorer, but running them from the UI does not do anything.

Aside from that, running them from console (dotnet test -method FastTests.Voron.Compaction.StorageCompactionTests.ShouldPreserveTables) does run them, and forcing them to fail does make the console call fail, but does not show in Test Explorer.

Repro can be found at:
https://github.com/jbayardo/ravendb/blob/v4.0/test/FastTests/Voron/Compaction/StorageCompactionTests.cs
https://github.com/jbayardo/ravendb/blob/v4.0/test/FastTests/Voron/FixedSize/InlineDataWithRandomSeed.cs

**Comment by bradwilson** [comment]
You're running afoul of limitations of the test runner inside Visual Studio. https://xunit.github.io/faq/theory-data-stability-in-vs.html
