### ISSUE TITLE
String resources lookup returning null

### ISSUE THREAD

**Issue by odalet** [xunit/xunit#954]
Hi all, I experience a weird behavior with xunit.net.

I have some unit tests that load a string resource from another assembly (the resources are not part of the Test assembly but of a dependant assembly):

``` C#
var expected = StringResources.Ok; // StringResources is defined in a dependant assembly
var actual = ... // some code that looks up the Ok resource
Assert.Equal(expected, actual);
```

It shouldn't matter what the current culture is as this very resource has the same value (OK) in both the default resource and the localized one (fr only for now).

These tests run perfectly well on my local machine (run either from VS or from the command line runner) but they _sometimes_ fail on our CI server (Jenkins / Win 2012 R2).

When they fail on our CI, xunit reports that the value for `expected` is `null` whereas, it should contain `"OK"`...:

```
C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\EqualityAsserts.cs(35): error : Foo.TranslationConverterTest.ConvertFound [FAIL] [E:\Jenkins\jobs\ci-develop-x64\workspace\run-xunit.proj]
        Assert.Equal() Failure
        Expected: (null)
        Actual:   Ok
        Stack Trace:
             … Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) dans C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\EqualityAsserts.cs:ligne 35
             … Foo.TranslationConverterTest.ConvertFound() dans E:\Jenkins\jobs\ci-develop-x64\...
```

As I said, even if the server locale is weird and it does not find the satelite assembly, this should never happen as the fallback culture embedded in the dependant assembly also contains 'OK'. I suppose that this `null` comes from the generated resource class failing at retrieving the string value, but how comes this kind of code fails:

``` C#
public static string Ok {
    get {
        return ResourceManager.GetString("Ok", resourceCulture);
    }
}
```

Btw, what's really weird is that the expected value is `null` but the actual value is correct; and the code that sets `actual` also uses `StringResources.ResourceManager` under the hood...

Hope someone can help!

**Comment by bradwilson** [comment]
Closed for age.
