### ISSUE TITLE
Support F# async natively

### ISSUE THREAD

**Issue by nosami** [xunit/xunit#955]
It should be possible to write the following test in F#.

```fs
[<Fact>]
let ``my async test``() =
  async {
    let! x = someAsyncCall()
    AssertOnX
  }
```

Right now, you need to do something like this, converting the F# async to a Task.

```fs
let toFact computation : Task = Async.StartAsTask computation :> _

[<Fact>]
let ``my async test``() = toFact <|  async {
    let! x = someAsyncCall()
    AssertOnX
  }
```

This works fine, but just looks a little ugly.

**Comment by bradwilson** [comment]
From the C# perspective, it looks like async methods in F# return `FSharp.AsyncTask<T>`, and static method `FSharpAsyncTask.StartAsTask` should be directly usable from within xUnit.net. (Everything is in `FSharp.Core.dll`, in the `Microsoft.FSharp.Control` namespace.)

The only question is whether taking this direct dependency means we have to ship the F# runtime, in which case we might need to do the detection dynamically via reflection.

Should be pretty straight forward.

**Comment by nosami** [comment]
There are multiple versions of FSharp.Core in the wild - It's probably best to load the version that the user is using via reflection.

**Comment by bartelink** [comment]
There's not much that's going to help, but here a [self-answered SO question by me](http://stackoverflow.com/questions/25605130/testing-f-async-workflows-with-xunit-nets-task-support) regarding this

**Comment by nosami** [comment]
Awesome, thanks!

**Comment by bartelink** [comment]
Thanks, that's fantastic. Now we need that in `Asp.Net Core` too...

**Comment by bradwilson** [comment]
I made sure the implementation would support .NET Core. :)
