### ISSUE TITLE
Test runner ignores test case with random values.

### ISSUE THREAD

**Issue by christoferpeterson** [xunit/xunit#956]
Hello,

I found using random values in test cases renders the test case undiscoverable by the test runner. Here is sample code to reproduce:

```
		[Theory(DisplayName = "Addition works")]
		[MemberData("AdditionTests", MemberType = typeof(PaginatedProviderResponseProxyModel_Tests))]
		public void Test1(int a, int b, int expected)
		{
			Assert.Equal(expected, a + b);
		}

		public static IEnumerable<object[]> AdditionTests
		{
			get
			{
				var rand = new Random();

				var a = rand.Next(1, 10);
				var b = rand.Next(1, 10);
				yield return new object[] { a, b, a + b };

				a = rand.Next(1, 10);
				b = rand.Next(1, 10);
				yield return new object[] { a, b, a + b };

				a = rand.Next(1, 10);
				b = rand.Next(1, 10);
				yield return new object[] { a, b, a + b };
			}
		}
```
Here is the error it shows: "Test adapter sent back a result for an unknown test case. Ignoring result for 'Addition works(a: 4, b: 9, expected: 13)'."

Chris

**Comment by onovotny** [comment]
Have you tried disabling preenumeration of theories? I suspect that's the issue since you're creating non-deterministic test cases: http://xunit.github.io/docs/configuring-with-json.html

**Comment by bradwilson** [comment]
Working as "designed". https://xunit.github.io/faq/theory-data-stability-in-vs.html

**Comment by christoferpeterson** [comment]
Cool, sorry I am new to xunit and wasn't aware of this feature. Adding a xunit.runner.json file and setting "preEnumerateTheories": false worked.
