### ISSUE TITLE
Tests fail randomly on Linux/Mono Stable 4.4.2.11/f72fe45

### ISSUE THREAD

**Issue by ahri** [xunit/xunit#957]
I'm running tests on both a Windows machine and a Linux box, and find that tests very often fail on the Linux box for spurious reasons:

```
System.ExecutionEngineException : Failed to create shadow copy of sibling data (CopyFile).
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x416db140 + 0x000b7> in <filename unknown>:0
```

```
System.ExecutionEngineException : Failed to create shadow copy .ini file.
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x413c6150 + 0x000b7> in <filename unknown>:0
```

Judging by the history on TeamCity I'd say they fail (on seemingly random tests - not the same one each time) more often than they pass. Of course, they pass every time on Windows (using Microsoft .NET 4.6.2), which is why I'm creating an issue.

Is there something I can do to improve the reliability of my test runs?

**Comment by SirCmpwn** [comment]
Can reproduce.

**Comment by bradwilson** [comment]
In what target environment? We only officially support Mono in the context of Xamarin; we do not officially support it for desktop or .NET CLI applications.

**Comment by SirCmpwn** [comment]
Well, that's a pretty lame policy to have. NUnit it is, I guess.

**Comment by Memorix101** [comment]
I've no issues with Mono (MonoDevelop) on Ubuntu. Every time I run it, it works :)
![ejwnykeogyaqqng7siebarg8rg9gcfi0ucbadnx07jv_-f5xfpopfrez32mb2i6rqw9qmpvui6pe9szppobkdefitnm_sumbjgrvtz_qov2e6abrgzdbhfhbegem8mq9ldz24vxd6vqfw0sdpnwrsdjn0nh1typ-fz7jki8 -ap7sfudmr4g0m46sbh5z8njbzu](https://cloud.githubusercontent.com/assets/1466920/18151760/db14a1e8-6ff1-11e6-8d8e-3cf8eb1580a0.png)

**Comment by ahri** [comment]
This is indeed on CLI, on both Debian and OSX.

**Comment by ahri** [comment]
@Memorix101 Mono seems to be working fine in all other cases - just not when executing xunit.

**Comment by bradwilson** [comment]
The .NET team does not support officially Mono with the .NET CLI, either.

**Comment by ahri** [comment]
It seems to work fine with the -noshadow param on both OSX and Debian. I've run the tests >10 times with no failures, which is good news for @SirCmpwn.

So my question to @bradwilson is: what am I missing out on by disabling shadow copies?

**Comment by bradwilson** [comment]
Shadow copying is what prevents the DLLs from being locked while the tests are running. What you'll be missing is the ability to re-build while tests are currently running.

**Comment by ahri** [comment]
Only Windows locks files, so that should be fine on POSIX.

**Comment by bradwilson** [comment]
Going to close this as a Won't Fix, with an available workaround (disable shadow copying).
