### ISSUE TITLE
Minor Diagnostic: xunit fails to execute generic test method

### ISSUE THREAD

**Issue by 0x53A** [xunit/xunit#969]
As far as I can see, this is not really a bug in xunit, but a clearer error message might help other people who stumble over this issue.

If I compile this F# test
![image](https://cloud.githubusercontent.com/assets/4236651/18435001/dc0f007c-78f0-11e6-8873-8f1ce4ca0f67.png)

and try to run it, then I get this error
![image](https://cloud.githubusercontent.com/assets/4236651/18435010/eb63d76e-78f0-11e6-90dc-dec40fed621f.png)
The error says something like 

> Late-bound operations can't be executed for fields with types or methods, for which ContainsGenericParameters was set to "true"

The real issue is that the code was compiled to this C# equivalent
![image](https://cloud.githubusercontent.com/assets/4236651/18435047/360b5abc-78f1-11e6-9213-b9ff571a4b7a.png)

The real fix is to change the F# code to this 
![image](https://cloud.githubusercontent.com/assets/4236651/18435118/93a86ee4-78f1-11e6-984f-888808eb3399.png)
so that it does not get compiled to a generic method.

In general, this issue is not restricted to F#, someone might also define a generic test method in C#, but there it would be more obvious what is wrong

Version: I have tested it with both 2.1.0 (latest stable) and 2.2.0-beta2-build1149 (latest prerelease)

**Comment by bradwilson** [comment]
Resolved by #1024
