### ISSUE TITLE
xUnit.net tests fail to run due to std::launch::async in C++ dependency

### ISSUE THREAD

**Issue by peetw** [xunit/xunit#971]
See this issue [here](http://stackoverflow.com/q/39467894/3628232)

Essentially xUnit.net seems to fail to load dependent DLLs when launching new threads in C++ via `std::async`.

**Comment by bradwilson** [comment]
What you're describing is a failure of the loader system, which xUnit.net does not control. Why do you think this is an xUnit.net issue?

Do any .NET unit test frameworks support what you're trying to do? (Meaning: is the behavior different in NUnit? MSTest?)

**Comment by peetw** [comment]
Perhaps not a xUnit.net issue exactly, but if the app runs fine normally, what does the test runner do differently that would cause issues with DLL loading?

I shall try and setup a duplicate test using NUnit to see if I can reproduce.

**Comment by bradwilson** [comment]
We don't load your C++ assemblies, so I have no idea. My first guess would be to turn off shadow copying, since I'd wager that your non-.NET assemblies are not getting correctly copied.

**Comment by peetw** [comment]
Indeed, my initial wording was pretty poor. I wasn't sure whether the test runners somehow modify the AppDomain in someway that would cause the assembly loading paths to be mixed up. Disabling shadow copying was my first thought too, but it didn't help.

Looking into it further this morning with [fuslogvw](https://msdn.microsoft.com/en-us/library/e74a18c4(v=vs.110).aspx) has revealed that when the test runner is launched, the AppBase is set to the output folder of the test project as expected. However, when a new thread is launched (from within the C++ code), the AppBase is set to the location of the test runner and thus the dependent DLLs cannot be loaded since they are not present at that location.... This occurs with both the xunit.runner.console and ReSharper test runners.

I acknowledge that this probably isn't a xUnit.net issue per se, so I'll close this issue in a couple of days if I can't find a solution.

**Comment by peetw** [comment]
It appears to be related to the problem described [here](http://stackoverflow.com/q/17993010/3628232), where the new thread is launched in the default AppDomain (i.e. that of the test runner rather than the test DLL) and therefore cannot find the dependent DLLs that it needs to load.

It seems doubtful whether the test runners can do anything to change this as it is more of a .NET issue so I'll go ahead and close the issue unless you have any suggestions?

**Comment by bradwilson** [comment]
Yep, this certainly looks like a bug in `std::async`.

**Comment by bradwilson** [comment]
You would be able to work around this by copying the runner into your output folder so that everything lives in the same folder.

**Comment by peetw** [comment]
I think it's more to do with how .NET loads mixed (managed and unmanaged code combined, e.g. C++/CLI) assemblies (see [here](http://stackoverflow.com/q/17993010/3628232)) rather than a bug in `std::async` itself.

Copying the test runner to the output folder would probably solve the issue; however, we currently run our tests in VS2013 via the ReSharper runner and I'm not sure it's possible to get ReSharper to copy the test runner executable itself prior to running the tests.

In the end, I ended up following the suggestion [here](http://stackoverflow.com/q/3167617/3628232) to detect whether the code is running under unit test and, if so, switch to `std::launch::sync` policy (i.e. no new threads). A bit hacky, but it does the job :)
