### ISSUE TITLE
dotnet-test-xunit output to nunit

### ISSUE THREAD

**Issue by brendansaunders** [xunit/xunit#977]
Can we please get an option to be able to output the test results in nunit format just like other runners with the -nunit option?

**Comment by bradwilson** [comment]
We are waiting for this to ship: https://github.com/dotnet/corefx/issues/5593

**Comment by bradwilson** [comment]
This works in 2.4 now when running on .NET Core 2.0+ (it will never be supported on .NET Core 1.x because of the lack of XSL-T).
