### ISSUE TITLE
Mono: Thread.Interrupt call inside unit test's background thread crashes XUnit runner

### ISSUE THREAD

**Issue by Aaronontheweb** [xunit/xunit#979]
We ran into a bug that occurs on Mono 4.4.2 with XUnit 2.1. The following specifications begins a background thread which will later be interrupted from a `Thread.Interrupt` call: https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Streams.Tests/Dsl/FlowSelectAsyncSpec.cs#L358

This runs just fine on Windows, but on Mono a `System.Threading.ThreadInterruptedException` is thrown insider the runner itself, which causes it to crash. 

```
[23:20:33] :             [Test collection for Akka.Streams.Tests.Dsl.FlowSelectAsyncSpec (1)] Akka.Streams.Tests.Dsl.FlowSelectAsyncSpec.A_Flow_with_SelectAsync_must_not_run_more_futures_than_configured (5s)
[23:20:33] :         [docker] System.Threading.ThreadInterruptedException: 
```

Our settings for the XUnit console runner are the same for both Windows and Mono:
- NoParallelization = true
- ForceTeamCity = true
- NoAppDomain = true

Otherwise everything else is set to its defaults.

**Comment by bradwilson** [comment]
Closed for age.
