### ISSUE TITLE
First test within Theory sets the complete indicator in VS

### ISSUE THREAD

**Issue by ornatwork** [xunit/xunit#984]
When running Theory in VS Test explorer that has multiple tests.  The first successful test will switch the Play / running icon in VS to a completed success icon before all the tests in the Theory finish.  I expect it should display the play / running icon until all the tests in the Theory have finished, see image.  

![c63ae16c-1e96-11e6-911a-3e03aaecff3a](https://cloud.githubusercontent.com/assets/94155/18723744/14a2a170-7ff7-11e6-9c85-1b8befb7087e.png)

**Comment by bradwilson** [comment]
You should report this to the Visual Studio team. This has nothing to do with us.

**Comment by ornatwork** [comment]
I was guessing it might be the xUnit runner interaction with VS.  It has nothing to do with the xUnit runner interaction with VS then ?

**Comment by ornatwork** [comment]
Solved this by making my objects serialized and run each tests individually instead in a group, thnx.
