### ISSUE TITLE
How to enable DI in xUnit v2

### ISSUE THREAD

**Issue by Rookian** [xunit/xunit#988]
Hi! I'm trying to enable DI in xUnit. I implemented two ways of achieving DI.

The first possibility is to create your own `XunitTestInvoker`and override `CreateTestClass`. I got this to work with a custom `FactAttribute`. The problem is that before the `XunitTestInvoker`is invoked there constructor arguments are already created/validated by `XunitTestClassRunner`/`TestClassRunner<TTestCase>` (`CreateTestClassConstructorArguments`). So what I did is to clear the `ExceptionAggregator`, which seems to be very hacky, but it works.

The second possibility is to create your own `XunitTestClassRunner`and override `TryGetConstructorArgument`. The problem is, that now the container is only booted once per class instead of once per method/theory data.

I have some ""working"" examples on [https://github.com/Rookian/xUnitDependencyInjection/tree/hacky-di-for-xunit](https://github.com/Rookian/xUnitDependencyInjection/tree/hacky-di-for-xunit) and [https://github.com/Rookian/xUnitDependencyInjection/tree/hacky-di-for-xunit](https://github.com/Rookian/xUnitDependencyInjection/tree/master)

Do you have any idea how I can achieve constructor injection for test classes with xUnit?

**Comment by bradwilson** [comment]
Closed for age.
