### ISSUE TITLE
Download of xunit source does not build

### ISSUE THREAD

**Issue by ayb4btu** [xunit/xunit#989]
I downloaded the xunit source by going to [https://github.com/xunit/xunit](https://github.com/xunit/xunit), clicking _**Clone or download**_ then _**Download Zip**_, but I'm unable to build the source (I'm using Visual Studio 2015 Community).

The first issue was installing the DotNetCore, which ended up being version 1.0.0-preview2-003131, so I changed global.json from 

```
{
    "projects": [ "src", "test" ],
    "sdk": {
        "version": "1.0.0-preview2-003121"
    }
}
```

to

```
{
    "projects": [ "src", "test" ],
    "sdk": {
        "version": "1.0.0-preview2-003131"
    }
}
```

which fixed the project loading. The second and current issue is that there are project.json files (such as xunit-master\src\xunit.execution\project.json) have the following references:

- "../xunit.assert/Asserts/Sdk/ArgumentFormatter.cs",
- "../xunit.assert/Asserts/Sdk/AssertEqualityComparer.cs",
- "../xunit.assert/Asserts/Sdk/AssertEqualityComparerAdapter.cs"

except these reference don't appear to exist any more (the xunit.assert project is essentially empty). I'm assuming I'm missing something simple for getting this source code to build? If necessary I can add the compilation output.

**Comment by bradwilson** [comment]
> The first issue was installing the DotNetCore, which ended up being version 1.0.0-preview2-003131

There have been two releases of the .NET CLI Preview 2 tooling: 003121 and 003131. This change should not be necessary.

> these reference don't appear to exist any more

From the home page, following the "Need some help building the source?" link will take you to https://xunit.github.io/docs/building-xunit.html which says:

> _If you have problems building the assertion library, you may have forgotten to update the submodules. From the command line, run `git submodule update --init`._

**Comment by ayb4btu** [comment]
Thanks for the info, installing and using the github app to do the clone sorted the assertion library references.

I still have to change to 003131 though (I'm assuming because I don't have 003121 installed), otherwise Visual Studio comes up with the following message box:
![image](https://cloud.githubusercontent.com/assets/14414215/19018717/19c825b8-88ca-11e6-8fae-2f06d2f64e60.png)

The only other issue was the .NET Framework 3.5 reference in xunit.runner.utility, which I think comes from not having it installed. I just removed the "net35" property from the xunit.runner.utility project.json file, ran dotnet restore and rebuilt. Now there is no warnings or errors, so I'm assuming there will be no problems with doing this, especially given that I'm not looking at the runner.utility project.
