### ISSUE TITLE
Enable xunit to skip all other tests

### ISSUE THREAD

**Issue by teyc** [xunit/xunit#990]
Call for comments.

One of the pleasant things I discovered with `Jasmine` and `Mocha` when doing TDD is the ability to ask the test runner to skip all other tests. In Jasmine, it's implemented like this:

```
// using xdescribe rather than describe causes the test runner
// to skip all other test collections, and executes only fact 1 and fact 2.
xdescribe("test collection", function() {
   it("fact1", function() { ... })
   it("fact 2", function() { ...})
})

// alternatively using xit instead of it. This executes only fact 1
describe("test collection", function() {
   xit("fact 1", function() { ... })
   it("fact 2", function() { ... } )
})
```

Combine this with a file watcher, the development cycle can be quite nice. 

I've looked over the xunit source. There are several ways we can go about implementing this.
1. Create a custom trait `XAttribute` , and in xunit console, if XAttribute is present in any test collection, then all tests in the test collection that is not marked with X is skipped. All tests in TestCaseCollection inherits the test case collection's XAttribute trait. 
2. Extend ITestCase with `bool SkipOther`. Before executing a test collection, if SkipOther is present, then apply a special set of filter.
3. Create a custom ITestFilter
4. Create a custom ITestDiscoverer

What do you think? Is this something in line with xunit's development direction?

**Comment by ligue** [comment]
I think someone looking at this framework will be very discouraged if for doing simple things such as : 

1. Order [tests](https://geeks.ms/clanderas/2016/11/16/xunit-run-your-web-api-integration-tests-in-strict-order-with-itestcaseorderer/) .
2. Skip tests if conditions are [not met](https://stackoverflow.com/questions/27755539/how-to-dynamically-skip-a-test-with-xunit-2-0).

You tend to make a lot of assumptions about how others can use xunit (even worse how others should use it).

**Comment by bradwilson** [comment]
That's true, we do make some assumptions, and we not apologetic about it. We have samples to show how to do both of those, but they're not built in because we believe that those things are philosophically opposed to unit testing. We enable you to do them, with effort, but do not wish to encourage bad behavior.

**Comment by bradwilson** [comment]
Closed for age.
