### ISSUE TITLE
Code Coverage in VSTS using Test Task

### ISSUE THREAD

**Issue by johnkattenhorn** [xunit/xunit#991]
I'm sure I've got this working before but setting up a new project today with the xunit.visualstudio.runner nuget package gives me the following error when executing the test step in VSTS when I enable Code Coverage.

`Warning: Diagnostic data adapter message: Could not find diagnostic data adapter 'Code Coverage'.  Make sure diagnostic data adapter is installed and try again.` 

It discovers and executes the tests fine.

We are using our own VSOAgent, have we missed installing something on the build machine ?

**Comment by bradwilson** [comment]
We don't do anything to specifically enable or disable support for code coverage, so it's not likely to be something with our adapter.

**Comment by cpoDesign** [comment]
I have to join to this request

my build is producing following message: 

> `Warning: Diagnostic data adapter message: Could not find diagnostic data adapter 'Code Coverage'.  Make sure diagnostic data adapter is installed and try again.`

The task definition contains  

> Code Coverage Enabled

with check box and therefore **suggest that the functionally is there**

**Comment by johnkattenhorn** [comment]
I found my solution to this problem was nothing to do with XUnit in the end. 

We were running a new build server and it was missing some components which are found in VS Enterprise
