### ISSUE TITLE
Make collection equality failures easier to spot.

### ISSUE THREAD

**Issue by Clockwork-Muse** [xunit/xunit#994]
Currently, when collections are checked for equality, it can be very difficult to determine which element is different, because of the error message.  For instance, something like this:

```
[Fact]
public static void Eq_Short()
{
    List<int> expected = Enumerable.Repeat(0, 15).ToList();
    List<int> actual = Enumerable.Repeat(0, 14).Concat(Enumerable.Repeat(1, 1)).ToList();
    Assert.Equal(expected, actual);
}
```

produces this message:

```
Result Message:
Assert.Equal() Failure
Expected: List<Int32> [0, 0, 0, 0, 0, ...]
Actual:   List<Int32> [0, 0, 0, 0, 0, ...]
```

Instead, it would be better if, when there are too many elements to display, the message looked more like this:

```
Result Message:
Assert.Equal() Failure
Expected: List<Int32> [...14 identical elements..., 0]
Actual:   List<Int32> [...14 identical elements..., 1]
```

This is already how `string` works, so makes sense to do something similar:

```
[Fact]
public static void Eq_Short()
{
    string expected = string.Join(" ", Enumerable.Repeat(0, 15));
    string actual = string.Join(" ", Enumerable.Repeat(0, 14)) + " 1";
    Assert.Equal(expected, actual);
}
```

```
Result Message:
Assert.Equal() Failure
                                 ↓ (pos 28)
Expected: ···0 0 0 0 0 0 0 0 0 0 0
Actual:   ···0 0 0 0 0 0 0 0 0 0 1
                                 ↑ (pos 28)
```

**Comment by bradwilson** [comment]
Any reason for the "14 identical elements" message rather than replicating the string-style message we have today?

**Comment by Clockwork-Muse** [comment]
No, sorry.  I just picked something temporarily (before confirming the string message).  Closer to the string message is fine.

For sets/dictionaries, would the message take the order of the "actual" collection?  Since those collections usually don't have to be in order, it would be confusing if the message printed the expected in it's order, ie:
```
 Result Message:
Assert.Equal() Failure
                                   ↓ (pos 28)
Expected: ···11 10 0 2 4 6 8 3 7 9 5
Actual:   ···9 3 11 4 5 6 8 7 2 10 1
                                   ↑ (pos 28)
```

**Comment by tmat** [comment]
FYI: http://source.roslyn.io/#Roslyn.Test.Utilities/Assert/AssertEx.cs,263df208b06030dd,references and http://source.roslyn.io/#Roslyn.Test.Utilities/Assert/AssertEx.cs,89e7dc60ad5147e8.

**Comment by bradwilson** [comment]
Fixed in https://github.com/xunit/assert.xunit/commit/bb5d19df7322627f649e55e8006157cd0af31ac6 and https://github.com/xunit/xunit/commit/f4be18e8bf926b3ec0ead036fca5df7fb2114116
