### ISSUE TITLE
Multiple frameworks doesn't work with VS test explorer

### ISSUE THREAD

**Issue by Jupakabra** [xunit/xunit#999]
I was following [Getting started with xUnit.net (.NET Core / ASP.NET Core)](https://xunit.github.io/docs/getting-started-dotnet-core.html) guide, but ran into a problem of not being able to run tests from VS test explorer then targeting `net451` and `netcoreapp1.0`.
If only one of them is targeted everything works as expected. But targeting both always results in this
```
Discovering tests in 'C:\Data\MyFirstDotNetCoreTests\project.json' ["C:\Program Files\dotnet\dotnet.exe" test "C:\Data\MyFirstDotNetCoreTests\project.json" --output "C:\Data\MyFirstDotNetCoreTests\bin\Debug\net451\win7-x64" --port 4855 --parentProcessId 10516 --no-build]
Unable to start C:\Program Files\dotnet\dotnet.exe
dotnet-test Error: 0 : [ReportingChannel]: Waiting for message failed System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.DotNet.Tools.Test.ReportingChannel.ReadMessages()
```

However, running `dotnet test` from the project folder works with both frameworks.

**Comment by bradwilson** [comment]
This is a limitation inside Visual Studio and not something we control.

**Comment by Jupakabra** [comment]
@bradwilson maybe you know where should I report to or if it's already reported to VS guys? So this issue can be closed?

**Comment by bradwilson** [comment]
I have spoken to the team in the past on this issue, and they're aware of it. They did not make any public commitments as to how or when this would be fixed, but it seems reasonable to assume that it will be fixed in VS "15" rather than back-ported into VS2015. I am personally hopeful that it will be part of the .NET CLI 1.0 RTM.

If you want to log your own issue, this is probably where I'd start: https://github.com/dotnet/cli/issues

**Comment by Jupakabra** [comment]
Ok, thanks.
